fix(tests-integration): feature account in state
starkware-libs/sequencer pull request #1061
Opened 2024-09-27 08:03 UTC by giladchase

Use `FeatureAccount` in the flow test state reader. This fixes the longstanding bug of relying on
`FeatureContract::get_instance_address`, which generates mocked addresses for accounts, rather than ones derived from deploy account txs, which is how addresses are determined in Feature Acconuts.

2024-09-27 08:09 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7mWMjR9uU08x8Xb96F:-O7mWMjS3vjscWcur1V7:bb0ir4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/tests-integration/src/state_reader.rs#L70)):*
> ```XML
>         account: contract,
>         sender_address: contract.get_instance_address(0),
>     })
> ```

Theres a missing abstraction here, since these are indeed contracts, not accounts, however later on in this code contracts and accounts are treated as the same thing sometimes, and sometimes not. 
Fix is coming up.
In this commit this just hides the address resolution by wrapping in FeatureAccount, even though some of these are actually contracts.



_Code quote:_
```XML
        FeatureContract::TestContract(CairoVersion::Cairo0),
        FeatureContract::TestContract(CairoVersion::Cairo1),
        FeatureContract::ERC20(CairoVersion::Cairo0),
    ]
    .into_iter()
    .map(|contract| FeatureAccount {
        account: contract,
        sender_address: contract.get_instance_address(0),
    })
```


<!-- Sent from Reviewable.io -->

2024-09-28 08:49 UTC, elintul requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7ro-aW6FbnindhA_HF:-O7ro-aW6FbnindhA_HG:bts1u0l) (no related file):*
The `account[s]` argument name change can be done later, if painful.

___
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 392 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7rn2yB9T-QaTKYLuxG:-O7rn2yB9T-QaTKYLuxH:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L392)):*
> ```XML
>         self.account.get_class_hash()
>     }
>     pub fn cairo_version(&self) -> CairoVersion {
> ```





_Suggestion:_
```XML
    }
    
    pub fn cairo_version(&self) -> CairoVersion {
```
___
*[`crates/tests-integration/src/state_reader.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7mWMjR9uU08x8Xb96F:-O7roLtLAq5kKhNDli5N:b-2g605s) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/tests-integration/src/state_reader.rs#L70)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Theres a missing abstraction here, since these are indeed contracts, not accounts, however later on in this code contracts and accounts are treated as the same thing sometimes, and sometimes not. 
Fix is coming up.
In this commit this just hides the address resolution by wrapping in FeatureAccount, even though some of these are actually contracts.
</blockquote></details>

How's a non-account contract is wrapped with `FeatureAccount`? Is this temporary?

Also, maybe we should rename to `AccountInstance`? "Feature" is a weird word here.
___
*[`crates/tests-integration/src/state_reader.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7rnJa54gLeAd7T_QTe:-O7rnJa54gLeAd7T_QTf:b-rpahry) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/tests-integration/src/state_reader.rs#L80)):*
> ```XML
> fn initialize_papyrus_test_state(
>     chain_info: &ChainInfo,
>     contracts: Vec<FeatureAccount>,
> ```

:grimacing: 



_Suggestion:_
```XML
accounts: &[FeatureAccount]
```
___
*[`crates/tests-integration/src/state_reader.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7rnNXECNOwa941LODJ:-O7rnNXECNOwa941LODK:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/tests-integration/src/state_reader.rs#L90)):*
> ```XML
> }
> 
> fn prepare_state_diff(chain_info: &ChainInfo, contracts: &[FeatureAccount]) -> ThinStateDiff {
> ```





_Suggestion:_
```XML
accounts: &[FeatureAccount]
```
___
*[`crates/tests-integration/src/state_reader.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7rnTScC_iMSatlD5BJ:-O7rnTScC_iMSatlD5BK:b-tky4to) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/tests-integration/src/state_reader.rs#L113)):*
> ```XML
>             }
>         }
>         deployed_contracts.insert(contract.sender_address, contract.class_hash());
> ```

Why the asymmetry? Either all getters or not (are they needed? Do they increase protection?).



_Code quote:_
```XML
contract.sender_address, contract.class_hash()
```
___
*[`crates/tests-integration/src/state_reader.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7rnvc3EQL5TEeYMmiX:-O7rnvc3EQL5TEeYMmiY:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/tests-integration/src/state_reader.rs#L126)):*
> ```XML
> }
> 
> fn prepare_compiled_contract_classes(contract_instances: &[FeatureAccount]) -> ContractClassesMap {
> ```





_Suggestion:_
```XML
accounts: &[FeatureAccount]
```
___
*[`crates/tests-integration/src/state_reader.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7rnyS3EQtfgQIjOTwm:-O7rnyS3EQtfgQIjOTwn:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/tests-integration/src/state_reader.rs#L201)):*
> ```XML
> fn fund_feature_account_contract(
>     storage_diffs: &mut IndexMap<ContractAddress, IndexMap<StorageKey, Felt>>,
>     contract: &FeatureAccount,
> ```





_Suggestion:_
```XML
account: &FeatureAccount
```


<!-- Sent from Reviewable.io -->

2024-09-29 11:43 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 392 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7rn2yB9T-QaTKYLuxG:-O7xY6faBUF-smkRlCHS:bgttmx4) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L392)):*
> ```XML
>         self.account.get_class_hash()
>     }
>     pub fn cairo_version(&self) -> CairoVersion {
> ```

:scream:  tnx
___
*[`crates/tests-integration/src/state_reader.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7mWMjR9uU08x8Xb96F:-O7w1FDy1bY6uLMO0NA-:b-ycitbu) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/tests-integration/src/state_reader.rs#L70)):*
>How's a non-account contract is wrapped with `FeatureAccount`? Is this temporary?

Discussed offline, will be fixed on top of stack
___
*[`crates/tests-integration/src/state_reader.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O7rnTScC_iMSatlD5BJ:-O7xYamACxzu_KgNL4UC:b-hp5nj1) ([raw file](https://github.com/starkware-libs/sequencer/blob/51fe2a3498e859221a12141e04c2e98d6fd24531/crates/tests-integration/src/state_reader.rs#L113)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why the asymmetry? Either all getters or not (are they needed? Do they increase protection?).
</blockquote></details>

class_hash() delegates to the inner contract, so getter.
The sender_address however, is calculated in the constructor (from the deploy account tx) and is fixed. In particular, it does not delegate, hence the assymetry.


<!-- Sent from Reviewable.io -->

2024-09-29 12:16 UTC, elintul requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-30 04:56 UTC, elintul reviewed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O80GkuQ2uKWk0-66pBd:-O80GkuQ2uKWk0-66pBe:b-rg8t2v) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa4be718319f09ad83d19fc566c04baf54ac55f2/crates/tests-integration/src/state_reader.rs#L59)):*
> ```XML
>     let block_context = BlockContext::create_for_testing();
> 
>     let accounts: Vec<FeatureAccount> = [
> ```

Why is annotation needed, given the signature of `initialize_papyrus_test_state`?



_Code quote:_
```XML
: Vec<FeatureAccount>
```


<!-- Sent from Reviewable.io -->

2024-09-30 06:49 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O80GkuQ2uKWk0-66pBd:-O80f5Zo9JLDHZVEN6TA:b-gio0ew) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa4be718319f09ad83d19fc566c04baf54ac55f2/crates/tests-integration/src/state_reader.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is annotation needed, given the signature of `initialize_papyrus_test_state`?
</blockquote></details>

Isn't needed, but i think you asked for it for readability at some point? but I might be misremembering :sweat_smile: 


<!-- Sent from Reviewable.io -->

2024-09-30 06:55 UTC, elintul requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O80GkuQ2uKWk0-66pBd:-O80hXEe5NsQ8csyXAeV:b-9sz9zl) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa4be718319f09ad83d19fc566c04baf54ac55f2/crates/tests-integration/src/state_reader.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Isn't needed, but i think you asked for it for readability at some point? but I might be misremembering :sweat_smile:
</blockquote></details>

Right, okay.
___
*[`crates/tests-integration/src/state_reader.rs` line 59 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O80hZFV9KmVJ-kupVwg:-O80hZFV9KmVJ-kupVwh:bjm51qb) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e5b752fb5c87f5a05a59514331f424f52703768/crates/tests-integration/src/state_reader.rs#L59)):*
> ```XML
>     let block_context = BlockContext::create_for_testing();
> 
>     let accounts: Vec<FeatureAccount> = [
> ```

They're not actually accounts.



_Suggestion:_
```XML
contracts
```


<!-- Sent from Reviewable.io -->

2024-09-30 06:56 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O80GkuQ2uKWk0-66pBd:-O80hd3u6WkQnX16whgb:b-wv9mzm) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa4be718319f09ad83d19fc566c04baf54ac55f2/crates/tests-integration/src/state_reader.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Right, okay.
</blockquote></details>

Are we going for the contract<>account abstraction we discussed yesterday? 


<!-- Sent from Reviewable.io -->

2024-09-30 06:56 UTC, elintul reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-30 07:25 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O80GkuQ2uKWk0-66pBd:-O80nct37alcOcqhtSPa:b-knn303) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa4be718319f09ad83d19fc566c04baf54ac55f2/crates/tests-integration/src/state_reader.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are we going for the contract<>account abstraction we discussed yesterday?
</blockquote></details>

yep, will put it up on PR once this stack gets close to merging, don't wanna get existing PRs too moldy
___
*[`crates/tests-integration/src/state_reader.rs` line 59 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-O80hZFV9KmVJ-kupVwg:-O80oB6f-9WslwPCogLW:b-l5dev0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e5b752fb5c87f5a05a59514331f424f52703768/crates/tests-integration/src/state_reader.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

They're not actually accounts.
</blockquote></details>

I made a mess :sweat:  the first three aren't accounts, but I'm chaining on top of this the users accounts, which are accounts :sweat_smile: 
ya I know...
The abstraction we discussed will fix this.  


<!-- Sent from Reviewable.io -->

2024-09-30 07:28 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1061#-:-O80pDG59jwOy6_s6KW_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-30 07:30 UTC, merged