Gilad/refactor state reader
starkware-libs/sequencer pull request #1063
Opened 2024-09-27 09:00 UTC by giladchase

2024-09-28 09:45 UTC, elintul requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1063)* status: all files reviewed, 16 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7s-1tZ1weS2ijFP111:-O7s-1tZ1weS2ijFP112:bl2hadk) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L115)):*
> ```XML
>     accounts_defined_in_the_test: &[FeatureAccount],
>     default_test_contracts: &[FeatureAccount],
>     erc20_account: &FeatureAccount,
> ```

Types are confusing. :(



_Suggestion:_
```XML
    default_test_contracts: &[FeatureAccount],
    erc20_contract: &FeatureAccount,
```
___
*[`crates/tests-integration/src/state_reader.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rzaat4yCX-RO383ob:-O7rzaat4yCX-RO383oc:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L123)):*
> ```XML
>     state_diff_builder.set_contracts(default_test_contracts).declare().deploy();
> 
>     // Declare and deploy and the erc20 contract, so that transfers from it can be made.
> ```





_Suggestion:_
```XML
ERC20
```
___
*[`crates/tests-integration/src/state_reader.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7s00O08QOnotZJ5SHI:-O7s00O08QOnotZJ5SHJ:b-tqlmlc) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L124)):*
> ```XML
> 
>     // Declare and deploy and the erc20 contract, so that transfers from it can be made.
>     state_diff_builder.set_contracts(std::slice::from_ref(erc20_account)).declare().deploy();
> ```

Consider `chain`ing to test contracts instead. :)



_Code quote:_
```XML
std::slice::from_ref(erc20_account)
```
___
*[`crates/tests-integration/src/state_reader.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rw-6aE6_mwnniJs4J:-O7rw-6aE6_mwnniJs4K:b778ea8) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L235)):*
> ```XML
> #[derive(Default)]
> struct ThinStateDiffBuilder<'a> {
>     contracts: &'a [FeatureAccount],
> ```

+ in setter name and variables.
Assuming they're all accounts. :sweat_smile: 



_Suggestion:_
```XML
accounts
```
___
*[`crates/tests-integration/src/state_reader.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rye3771PmK21OFkyU:-O7rye3771PmK21OFkyV:b-avshkf) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L236)):*
> ```XML
> struct ThinStateDiffBuilder<'a> {
>     contracts: &'a [FeatureAccount],
>     deprecated_declared_classes: Vec<ClassHash>,
> ```

Is a slice possible (and suitable) here?



_Code quote:_
```XML
Vec<ClassHash>
```
___
*[`crates/tests-integration/src/state_reader.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rx6yc4A9FA1E4Vh9Q:-O7rx6yc4A9FA1E4Vh9R:b-kije9p) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L237)):*
> ```XML
>     contracts: &'a [FeatureAccount],
>     deprecated_declared_classes: Vec<ClassHash>,
>     declared_classes: IndexMap<ClassHash, starknet_api::core::CompiledClassHash>,
> ```

Why fully-qualified?



_Code quote:_
```XML
starknet_api::core::CompiledClassHash
```
___
*[`crates/tests-integration/src/state_reader.rs` line 241 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rxAq-DxjEPcwAPIzu:-O7rxAq-DxjEPcwAPIzv:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L241)):*
> ```XML
>     storage_diffs: IndexMap<ContractAddress, IndexMap<StorageKey, Felt>>,
>     chain_info: ChainInfo,
>     initial_balances: Felt,
> ```





_Suggestion:_
```XML
initial_account_balance: Felt
```
___
*[`crates/tests-integration/src/state_reader.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rxaInCkXi8EbKg1li:-O7rxaInCkXi8EbKg1lj:b-s474dc) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L245)):*
> ```XML
> 
> impl<'a> ThinStateDiffBuilder<'a> {
>     const DEFAULT_INITIAL_BALANCE: u128 = BALANCE;
> ```

If only used inside `new`, perhaps define inside it?
Also, perhaps `[TEST_]INITIAL_ACCOUNT_BALANCE`, since "default" is usually related to a zeroed value.



_Code quote:_
```XML
const DEFAULT_INITIAL_BALANCE: u128 = BALANCE;
```
___
*[`crates/tests-integration/src/state_reader.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rxPOS0LmeZQ8KPwqb:-O7rxPOS0LmeZQ8KPwqc:be2ngrb) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L252)):*
> ```XML
> 
>         let deployed_contracts = indexmap! {
>             chain_info.fee_token_address(&FeeType::Eth) => erc20_class_hash,
> ```

Can you `map` over `FeeType` variants?



_Code quote:_
```XML
FeeType::Eth
```
___
*[`crates/tests-integration/src/state_reader.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rxgeF5tN53YYnewxB:-O7rxgeF5tN53YYnewxC:bsy8fe7) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L257)):*
> ```XML
> 
>         Self {
>             chain_info: chain_info.clone(),
> ```

Is it possible to pass by-value?



_Code quote:_
```XML
chain_info: chain_info.clone()
```
___
*[`crates/tests-integration/src/state_reader.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7s-OkH0dhv8JJ8izli:-O7s-OkH0dhv8JJ8izlj:b-a26vhe) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L285)):*
> ```XML
>     fn deploy(&mut self) -> &mut Self {
>         for contract in self.contracts {
>             self.deployed_contracts.insert(contract.sender_address, contract.class_hash());
> ```

Sanity Q: does this mean that I can invoke `get_class_hash_at(address)` on the created state reader and get the class hash inserted here?



_Code quote:_
```XML
self.deployed_contracts.insert
```
___
*[`crates/tests-integration/src/state_reader.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7ryuIIDAtX0J79phmQ:-O7ryuIIDAtX0J79phmR:blqcinr) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L297)):*
> ```XML
>                     | FeatureContract::AccountWithoutValidations(_)
>                     | FeatureContract::FaultyAccount(_),
>                 "Only Accounts can be funded"
> ```

Format actual type?



_Code quote:_
```XML
"Only Accounts can be funded"
```
___
*[`crates/tests-integration/src/state_reader.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7ryyOp05AEt2sEFll_:-O7ryyOp05AEt2sEFlla:b-996iw8) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L300)):*
> ```XML
>             );
> 
>             let fee_token_address = get_fee_token_var_address(contract.sender_address);
> ```

Getter or not? Needed or not? :grimacing: 



_Code quote:_
```XML
contract.sender [...]

2024-09-30 09:47 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1063)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7s00O08QOnotZJ5SHI:-O80tKP87xcdvGszhjaN:b-p783r4) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L124)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider `chain`ing to test contracts instead. :)
</blockquote></details>

Thought about it, but are we sure they will always be treated in the same way?
For example, do we want to support Declare txs? if so then we might want to remove/make-configurable the declare for the test contracts, (which will also force us to remove the deploy for them because deploy without declare isn't allowed, which makes me think that the deply/declare methods on the builder are coupled due to this issue but let's worry about that later :sweat_smile:).

However, the ERC20 will always be declared and deployed here, so that isn't subject to change.

Basically I'm worried that if I chain them together now ppl will be afraid to separate them later, because they'll imbue some meaning to this chain.
In other words I'm asking if its just a temporary coincidence that ERC20 and the test_contracts are getting the same treatment here (declare+deploy), if it is, then they should be kept separate for (near-)future compatibility.

 
___
*[`crates/tests-integration/src/state_reader.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rye3771PmK21OFkyU:-O80umwAAf1H3mGG4Do2:budqv3n) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L236)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is a slice possible (and suitable) here?
</blockquote></details>

Nope and nope :grimacing: 
Possible: This collection is created at the constructor of this collection, and is intended to be owned by the builder in order to accumulate changes for the diff. A ref isn't possible because the scope of the constructor dies when `new` ends.
We can create the vectors in the scope of the calling function to `new`, and pass them as &mut to `new` of the builder, but it's probably better for the builder to manage it itself.

Suitable: in general it's better for structs to own their stuff. The `contracts` field is taken by ref only to save an allocation of a Vec (FeatureAccount itself is Copy), and also because it doesn't need mutable access to this array.
___
*[`crates/tests-integration/src/state_reader.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rx6yc4A9FA1E4Vh9Q:-O80vtm80yzluhoBeW7K:bb7c8sd) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L237)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why fully-qualified?
</blockquote></details>

My mistake, fixed.
___
*[`crates/tests-integration/src/state_reader.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rxPOS0LmeZQ8KPwqb:-O80wapR0n2mit2ooGsk:bjci07x) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L252)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you `map` over `FeeType` variants?
</blockquote></details>

Good idea!
Added a (not strictly necessary) type annotation for readability though
___
*[`crates/tests-integration/src/state_reader.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rxgeF5tN53YYnewxB:-O80x7G771wkSOim8QQs:b-n464wl) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L257)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is it possible to pass by-value?
</blockquote></details>

Nope, we get a reference from BlockContext#chain_info(), which is sensible.
The clone isn't too bad here though, it's just a single short `String` for the chain name.

Anothe option is to save the ref as a field in the struct instead of the value, but that will prevent us from deriving `Default`, and will add a lifetime to the struct, which I think isn't worth it to save an alloc of a short String.
___
*[`crates/tests-integration/src/state_reader.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7s-OkH0dhv8JJ8izli:-O81JZoSEQh2PWxEHH_l:bpg9sdq) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L285)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Sanity Q: does this mean that I can invoke `get_class_hash_at(address)` on the created state reader and get the class hash inserted here?
</blockquote></details>

Yep.
Proof: papyrus state reader's [impl of this](https://github.com/starkware-libs/sequencer/blob/66aea89b8cba4ff7e34a4e8ea79a7870f25f4fab/crates/native_blockifier/src/state_readers/papyrus_state.rs#L111) uses the[ deployed_contracts table](https://github.com/starkware-libs/sequencer/blob/07e89e46deb36ead2da540fe18dccd0aeb591c99/crates/papyrus_storage/src/state/mod.rs#L252) to verify.

If this isn't there it'll fail blockifier's [in execute](https://github.com/starkware-libs/sequencer/blob/b67bf977c9c26eca60f0300cc5718c399aee74a7/crates/blockifier/src/execution/entry_point.rs#L86) with UnintializedStorageAddress
___
*[`crates/tests-integration/src/state_reader.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7ryyOp05AEt2sEFll_:-O80xnhp5Z1DBUU3tL2Y:b-odq2qo) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L300)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Getter or not? Needed or not? :grimacing:
</blockquote></details>

Discussed offline: i want to emphasize that this is different from the getter methods that delgate to inner contract.
This address is called manually in the constructor, and it's inclusion as a dedicated field is the main motivation for the struct. 
___
*[`crates/tests-integration/src/state_reader.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rzGHD9FThlxgQT-cR:-O80yA-x7txuhArp7sAs:bjh8ng0) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L314)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

MAGNIV!
Is that a usecase of returning `&mut self`?
</blockquote></details>

Yep, though in general biulder methods are consuming (it's easier on the borrow checker), and return `Self` rather than `&mut Self`, but this is typically because a builder instance isn't reused, it is instantiated then chained methods followed by an immediate `build()`.

Since we are doing this in multiple stages, using &mut will save us from having to do 
```
let thin_state_builder = thins_state_builder.set_contracts(...).declare().deploy();

let thin_state_builder = thins_state_builder.set_contracts...
`
```



<!-- Sent from Reviewable.io -->

2024-09-30 12:42 UTC, elintul requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1063)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rzaat4yCX-RO383ob:-O81RWNh8idB7pB2ucJ0:bi5xqvc) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L123)):*
> ```XML
>     state_diff_builder.set_contracts(default_test_contracts).declare().deploy();
> 
>     // Declare and deploy and the erc20 contract, so that transfers from it can be made.
> ```

Next PR? :grimacing: 
___
*[`crates/tests-integration/src/state_reader.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rxPOS0LmeZQ8KPwqb:-O81plwP21-6DbQczVkC:bgnesn0) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L252)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Good idea!
Added a (not strictly necessary) type annotation for readability though
</blockquote></details>

Where is it?
___
*[`crates/tests-integration/src/state_reader.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rzGHD9FThlxgQT-cR:-O81wG65E9aF7ERj-Y9Z:b-ucfknh) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L314)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep, though in general biulder methods are consuming (it's easier on the borrow checker), and return `Self` rather than `&mut Self`, but this is typically because a builder instance isn't reused, it is instantiated then chained methods followed by an immediate `build()`.

Since we are doing this in multiple stages, using &mut will save us from having to do 
```
let thin_state_builder = thins_state_builder.set_contracts(...).declare().deploy();

let thin_state_builder = thins_state_builder.set_contracts...
`
```

</blockquote></details>

Thanks!
___
*[`crates/tests-integration/src/state_reader.rs` line 235 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O81gYk5En94BAX7obq7:-O81gYk5En94BAX7obq8:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e55e07096c601250224c937b96cdb4afbd8f935/crates/tests-integration/src/state_reader.rs#L235)):*
> ```XML
>     storage_diffs: IndexMap<ContractAddress, IndexMap<StorageKey, Felt>>,
>     chain_info: ChainInfo,
>     initial_account_balances: Felt,
> ```





_Suggestion:_
```XML
initial_account_balance
```


<!-- Sent from Reviewable.io -->

2024-09-30 13:26 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1063)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rzaat4yCX-RO383ob:-O825V5O3O0tIOGctk5C:b-mw6hhz) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L123)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Next PR? :grimacing:
</blockquote></details>

Have other changes anyway here so added here if that's OK.
___
*[`crates/tests-integration/src/state_reader.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rxaInCkXi8EbKg1li:-O825rAY9YGE6Om7dMER:b-5e7l20) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L245)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

If only used inside `new`, perhaps define inside it?
Also, perhaps `[TEST_]INITIAL_ACCOUNT_BALANCE`, since "default" is usually related to a zeroed value.
</blockquote></details>

Totally right.
Done.
___
*[`crates/tests-integration/src/state_reader.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O7rxPOS0LmeZQ8KPwqb:-O825GVvETP0DzxTz1IG:blceh2k) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afbd7eb96ca8f01fe83edbdde4ec38a6baea8bb/crates/tests-integration/src/state_reader.rs#L252)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where is it?
</blockquote></details>

Crap missed in the rebase, tnx 4 checking.
___
*[`crates/tests-integration/src/state_reader.rs` line 235 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-O81gYk5En94BAX7obq7:-O825i4S8OZMGvEnrHOk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e55e07096c601250224c937b96cdb4afbd8f935/crates/tests-integration/src/state_reader.rs#L235)):*
> ```XML
>     storage_diffs: IndexMap<ContractAddress, IndexMap<StorageKey, Felt>>,
>     chain_info: ChainInfo,
>     initial_account_balances: Felt,
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-30 13:28 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1063#-:-O826T8_5BmAT41EDnfC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-30 13:34 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1063)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-30 13:43 UTC, merged