feat(batcher): decision reached
starkware-libs/sequencer pull request #1153
Opened 2024-10-01 16:38 UTC by yair-starkware

2024-10-07 14:12 UTC, ArniStarkware reviewed
> Reviewed 2 of 7 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @dafnamatsry and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-08 08:06 UTC, dafnamatsry requested changes
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 4 of 7 files reviewed, 9 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8eraDX70MT_meaqRxt:-O8eraDX70MT_meaqRxu:b-ksva) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/batcher.rs#L93)):*
> ```XML
> 
>     pub async fn decision_reached(&mut self, input: DecisionReachedInput) -> BatcherResult<()> {
>         self.proposal_manager.decision_reached(input.proposal_id).await.map_err(BatcherError::from)
> ```

As discussed, let's move the storage write to be here in the batcher.
___
*[`crates/batcher/src/batcher.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8eswHD0R9fNzC-VWdl:-O8eswHD0R9fNzC-VWdm:bfj9kas) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/batcher.rs#L115)):*
> ```XML
> 
> #[cfg_attr(test, automock)]
> pub trait BatcherStorageWriterTrait: Send + Sync {
> ```

Yael just added a payrus_state.rs file.
Let's put all the read/write logic there...
___
*[`crates/batcher/src/proposal_manager.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f4l8NEXWvLC4tl4Nk:-O8f4l8ODKbd2KD0WWwV:biudds3) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L246)):*
> ```XML
> 
>         let (abort_tx, abort_rx) = tokio::sync::oneshot::channel();
>         self.set_active_proposal(ActiveProposal { proposal_id, abort: abort_tx }).await?;
> ```

Can we somehow hide the channel inside `ActiveProposal`? 

Something like:
```
self.set_active_proposal(ActiveProposal::new(proposal_id)).await?; 

// in ActiveProposal:
pub fn new(id) {
    // channel creation
}

pub fn abort_listener()  -> Receiver...{
     abort_rx
}

```



_Code quote:_
```XML
        let (abort_tx, abort_rx) = tokio::sync::oneshot::channel();
        self.set_active_proposal(ActiveProposal { proposal_id, abort: abort_tx }).await?;
```
___
*[`crates/batcher/src/proposal_manager.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8ezKVJ55L9tlFUrC2g:-O8ezKVJ55L9tlFUrC2h:bb0n3hc) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L247)):*
> ```XML
>         let (abort_tx, abort_rx) = tokio::sync::oneshot::channel();
>         self.set_active_proposal(ActiveProposal { proposal_id, abort: abort_tx }).await?;
>         self.proposals
> ```

If we don't keep the streams of the proposals, might make more sense that `proposals` will only store finished proposals.
___
*[`crates/batcher/src/proposal_manager.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f-fsc3DSow83WBmfI:-O8f-fsc3DSow83WBmfJ:b-lqpnk5) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L307)):*
> ```XML
>         else {
>             return Err(DecisionReachedError::ProposalAborted { proposal_id });
>         };
> ```

I think `match` will be more readable here.



_Code quote:_
```XML
        let BlockBuilderOutput::Done { state_diff, casms } = proposal
            .block_builder_result
            .ok_or(DecisionReachedError::ProposalNotDone { proposal_id })??
        else {
            return Err(DecisionReachedError::ProposalAborted { proposal_id });
        };
```
___
*[`crates/batcher/src/proposal_manager.rs` line 345 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f10PuB5ZBce_UBDW0:-O8f10PuB5ZBce_UBDW1:b6n5cdh) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L345)):*
> ```XML
>                 new_proposal_id: proposal_id,
>             });
>         }
> ```

Would that work?



_Suggestion:_
```XML
        if let Some(current_active_proposal) = *lock {
            return Err(BuildProposalError::AlreadyGeneratingProposal {
                current_generating_proposal_id: current_active_proposal.proposal_id,
                new_proposal_id: proposal_id,
            });
        }
```
___
*[`crates/batcher/src/proposal_manager.rs` line 363 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f5h826D6TZEF13IDt:-O8f5h83CmZ4NXbp3LuB:b-bma8m7) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L363)):*
> ```XML
> 
> struct BuildProposalTask {
>     proposal_id: ProposalId,
> ```

We already have the id in `active_proposal`.



_Code quote:_
```XML
proposal_id: ProposalId,
```
___
*[`crates/batcher/src/proposal_manager.rs` line 396 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f1Q9_CSvNEiUy6ixB:-O8f1Q9_CSvNEiUy6ixC:byvw3kt) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L396)):*
> ```XML
>         let abort_listener = self.abort;
> 
>         // Keep the necessary fields before self is consumed.
> ```

Can you explain? Where is self being consumed?



_Code quote:_
```XML
// Keep the necessary fields before self is consumed.
```
___
*[`crates/batcher/src/proposal_manager.rs` line 408 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f26ll60ikf22VNZFP:-O8f26ll60ikf22VNZFQ:b94ef1f) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L408)):*
> ```XML
>                 error!("Failed to feed more mempool txs: {}.", feeding_error);
>                 // TODO: Notify the mempool about remaining txs.
>                 self.block_builder.abort_build();
> ```

Would be nice if we could use the `ActiveProposal` abort mechanism here as well. I.e. if `BuildProposalTask` will hold the active proposal, can we call it's `abort()` method here?



_Code quote:_
```XML
self.block_builder.abort_build();
```


<!-- Sent from Reviewable.io -->

2024-10-10 18:32 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 1 of 8 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8eraDX70MT_meaqRxt:-O8rOiJ5B-zFO9ef0ool:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/batcher.rs#L93)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

As discussed, let's move the storage write to be here in the batcher.
</blockquote></details>

Done.
___
*[`crates/batcher/src/batcher.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8eswHD0R9fNzC-VWdl:-O8rP3gEC8C1mRlAu551:b-kdxmfw) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/batcher.rs#L115)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Yael just added a payrus_state.rs file.
Let's put all the read/write logic there...
</blockquote></details>

In a separate PR.
___
*[`crates/batcher/src/proposal_manager.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f4l8NEXWvLC4tl4Nk:-O8rP7tD3-K0WhdPWllA:bmaar43) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L246)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can we somehow hide the channel inside `ActiveProposal`? 

Something like:
```
self.set_active_proposal(ActiveProposal::new(proposal_id)).await?; 

// in ActiveProposal:
pub fn new(id) {
    // channel creation
}

pub fn abort_listener()  -> Receiver...{
     abort_rx
}

```
</blockquote></details>

Removed abort flow
___
*[`crates/batcher/src/proposal_manager.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8ezKVJ55L9tlFUrC2g:-O8rPBmLAfpFPu4Ho8ZX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L247)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

If we don't keep the streams of the proposals, might make more sense that `proposals` will only store finished proposals.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f-fsc3DSow83WBmfI:-O8rPEtI7fOKlkDBaa1T:bmaar43) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L307)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think `match` will be more readable here.
</blockquote></details>

Removed abort flow
___
*[`crates/batcher/src/proposal_manager.rs` line 345 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f10PuB5ZBce_UBDW0:-O8rPWCv7wheIl2RZ2Yl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L345)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Would that work?
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 363 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f5h826D6TZEF13IDt:-O8rPYjT-pzXPb89ukw_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L363)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We already have the id in `active_proposal`.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 396 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f1Q9_CSvNEiUy6ixB:-O8rPkP92SG2QFb1be8e:b-x6sr35) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L396)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you explain? Where is self being consumed?
</blockquote></details>

Removed.
When there was the abort channel, the select would consume the self because it required ownership of the sender
___
*[`crates/batcher/src/proposal_manager.rs` line 408 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8f26ll60ikf22VNZFP:-O8rQbAd5dgk9y1xZIoK:b-tswgwl) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbcbe700b02eff858c90f9c3dedea1f341bdb2d1/crates/batcher/src/proposal_manager.rs#L408)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Would be nice if we could use the `ActiveProposal` abort mechanism here as well. I.e. if `BuildProposalTask` will hold the active proposal, can we call it's `abort()` method here?
</blockquote></details>

Removed abort


<!-- Sent from Reviewable.io -->

2024-10-10 20:07 UTC, dafnamatsry submitted a review, later dismissed
> Reviewed 6 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8ryCw_-AubO9sJu3J4:-O8ryCw_-AubO9sJu3J5:b54cham) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca299008a955dce05cbfd942c61f7e8596034cfd/crates/batcher/src/proposal_manager.rs#L222)):*
> ```XML
> 
>     #[instrument(skip(self), err)]
>     async fn decision_reached(
> ```

Rename to `remove_proposal`/`consume_proposal` or something similar.
There is no `decision_reached` logic here...

Or maybe even better, just `get_proposal_state_diff` without removing it from the `done_proposals` map.



_Code quote:_
```XML
async fn decision_reached(
```
___
*[`crates/batcher/src/proposal_manager.rs` line 380 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8rujt122hJYa2qCGZl:-O8rujt122hJYa2qCGZm:b-iu2zx4) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca299008a955dce05cbfd942c61f7e8596034cfd/crates/batcher/src/proposal_manager.rs#L380)):*
> ```XML
>         let proposal_id =
>             active_proposal.lock().await.take().expect("Active proposal should exist.");
>         // TODO: send ProposalCommitment in the channel.
> ```

I think we can save the commitment as part of the done proposal result, and get it only when needed in `get_proposal_content`.



_Code quote:_
```XML
// TODO: send ProposalCommitment in the channel.
```
___
*[`crates/batcher_types/src/errors.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8s0JwS7s16r-FUmsGa:-O8s0JwS7s16r-FUmsGb:bpyxhe2) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca299008a955dce05cbfd942c61f7e8596034cfd/crates/batcher_types/src/errors.rs#L23)):*
> ```XML
>          BuildProposal API."
>     )]
>     GetContentOnNonBuildProposal { proposal_id: ProposalId },
> ```

Not used I think



_Code quote:_
```XML
    #[error(
        "Can't get content for proposal with ID {proposal_id}, as it was not built by calling the \
         BuildProposal API."
    )]
    GetContentOnNonBuildProposal { proposal_id: ProposalId },
```
___
*[`crates/batcher_types/src/errors.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8s0Sxw52vQ7qqz8Ha9:-O8s0Sxw52vQ7qqz8HaA:b-7i656r) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca299008a955dce05cbfd942c61f7e8596034cfd/crates/batcher_types/src/errors.rs#L35)):*
> ```XML
>     ProposalAborted { proposal_id: ProposalId },
>     #[error("Proposal with ID {proposal_id} is still being generated.")]
>     ProposalNotDone { proposal_id: ProposalId },
> ```

used?



_Code quote:_
```XML
    #[error("Proposal with ID {proposal_id} was aborted.")]
    ProposalAborted { proposal_id: ProposalId },
    #[error("Proposal with ID {proposal_id} is still being generated.")]
    ProposalNotDone { proposal_id: ProposalId },
```


<!-- Sent from Reviewable.io -->

2024-10-13 09:40 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8ryCw_-AubO9sJu3J4:-O949B2O1vpigjwB_jp1:bval6cx) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca299008a955dce05cbfd942c61f7e8596034cfd/crates/batcher/src/proposal_manager.rs#L222)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Rename to `remove_proposal`/`consume_proposal` or something similar.
There is no `decision_reached` logic here...

Or maybe even better, just `get_proposal_state_diff` without removing it from the `done_proposals` map.
</blockquote></details>

Inserting to the storage consumes the state diff so I need to remove it from the proposals in order to avoid cloning
___
*[`crates/batcher/src/proposal_manager.rs` line 380 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8rujt122hJYa2qCGZl:-O949Pep-rkYhbToJpyf:brdihwy) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca299008a955dce05cbfd942c61f7e8596034cfd/crates/batcher/src/proposal_manager.rs#L380)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think we can save the commitment as part of the done proposal result, and get it only when needed in `get_proposal_content`.
</blockquote></details>

Removed the todo. The batcher will handle this.
___
*[`crates/batcher_types/src/errors.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8s0JwS7s16r-FUmsGa:-O94C4So1epW1pHDU5RP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca299008a955dce05cbfd942c61f7e8596034cfd/crates/batcher_types/src/errors.rs#L23)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not used I think
</blockquote></details>

Done.
___
*[`crates/batcher_types/src/errors.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O8s0Sxw52vQ7qqz8Ha9:-O94C9UB9CJHtEWV6-UD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca299008a955dce05cbfd942c61f7e8596034cfd/crates/batcher_types/src/errors.rs#L35)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

used?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-13 13:20 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 235 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O951GeP-IwF_mEjD-P5:-O951GeP-IwF_mEjD-P6:bbigj1g) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L235)):*
> ```XML
>             // TODO: Abort the block_builder.
>         }
>         self.done_proposals.lock().await.clear();
> ```

clear only proposals from the previous height, not current hight



_Code quote:_
```XML
self.done_proposals.lock().await.clear();
```


<!-- Sent from Reviewable.io -->

2024-10-13 13:57 UTC, alonh5 requested changes
> Reviewed 1 of 7 files at r1, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 6 of 8 files reviewed, 14 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 142 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O94yCyGBlp-HOgFJxVY:-O94yCyH1kzlyOzYHirS:bvdobg5) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/batcher.rs#L142)):*
> ```XML
>             .await
>             .ok_or(BatcherError::DoneProposalNotFound { proposal_id })?
>             .map_err(BatcherError::from)?;
> ```

Can `get_done_proposal` return a proposal not found error instead of an option in that case? 



_Suggestion:_
```XML
            .get_done_proposal(proposal_id)
            .await
            .map_err(BatcherError::from)?;
```
___
*[`crates/batcher/src/batcher.rs` line 144 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O950Gh-1XDtfUrp6oP0:-O950Gh-1XDtfUrp6oP1:b4azecy) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/batcher.rs#L144)):*
> ```XML
>             .map_err(BatcherError::from)?;
>         // TODO: Keep the height from start_height or get it from the input.
>         let height = self.storage_reader.height().map_err(|err| {
> ```

Can you add documentation to this trait function (that is returns the first height the is empty)?



_Code quote:_
```XML
height()
```
___
*[`crates/batcher/src/batcher.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O951t4AEJmk-08lxCgE:-O951t4AEJmk-08lxCgF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/batcher.rs#L152)):*
> ```XML
>             BatcherError::InternalError
>         })?;
>         Ok(())
> ```





_Suggestion:_
```XML
        })?
```
___
*[`crates/batcher/src/proposal_manager.rs` line 138 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O9547fS382CMzntEKFu:-O9547fS382CMzntEKFv:blf8kcf) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L138)):*
> ```XML
> 
> type ActiveTaskHandle = tokio::task::JoinHandle<()>;
> pub type DoneProposal = Result<ThinStateDiff, BuildProposalError>;
> ```

WDYT of renaming done proposal -> proposal result? I think it would have been more clear to me as a first time reader



_Code quote:_
```XML
DoneProposal
```
___
*[`crates/batcher/src/proposal_manager.rs` line 145 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O9552SQALVbHqeIbaIE:-O9552SQALVbHqeIbaIF:b-k1k6l4) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L145)):*
> ```XML
>     #[instrument(skip(self), err)]
>     async fn start_height(&mut self, height: BlockNumber) -> Result<(), StartHeightError> {
>         self.reset_height().await;
> ```

This sounds like reseting the height to zero.



_Suggestion:_
```XML
reset_active_height
```
___
*[`crates/batcher/src/proposal_manager.rs` line 276 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O956U6T6debvjhUn0ZP:-O956U6T6debvjhUn0ZQ:b-e92ja1) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L276)):*
> ```XML
>     active_proposal: Arc<Mutex<Option<ProposalId>>>,
>     deadline: tokio::time::Instant,
>     done_proposals: Arc<Mutex<HashMap<ProposalId, Result<ThinStateDiff, BuildProposalError>>>>,
> ```

Use type?



_Code quote:_
```XML
Result<ThinStateDiff, BuildProposalError>
```
___
*[`crates/batcher/src/proposal_manager.rs` line 298 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O956nfp7M1du-9_o3f2:-O956nfp7M1du-9_o3f3:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L298)):*
> ```XML
>         );
> 
>         // Wait for either the block builder to finish / the feeding of transactions to error / the
> ```





_Suggestion:_
```XML
, the feeding of transactions to error, or
```
___
*[`crates/batcher/src/proposal_manager.rs` line 313 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O959Kg_-8nxfpmRChZ5:-O959Kg_-8nxfpmRChZ6:b-tgsk0o) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L313)):*
> ```XML
>             }
>         };
>         Self::active_proposal_finished(self.active_proposal, result, self.done_proposals).await;
> ```

Why not a method like previously?



_Code quote:_
```XML
Self::active_proposal_finished(self.active_proposal, result, self.done_proposals).await;
```
___
*[`crates/batcher/src/proposal_manager.rs` line 352 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O957R8_ArFlYN1t93IR:-O957R8_ArFlYN1t93IS:b2nreh6) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L352)):*
> ```XML
>     async fn active_proposal_finished(
>         active_proposal: Arc<Mutex<Option<ProposalId>>>,
>         result: Result<ThinStateDiff, BuildProposalError>,
> ```

Same as above.



_Code quote:_
```XML
Result<ThinStateDiff, BuildProposalError>
```


<!-- Sent from Reviewable.io -->

2024-10-14 10:05 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 6 of 8 files reviewed, 13 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 142 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O94yCyGBlp-HOgFJxVY:-O99GX59DtX9_Wron8zR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/batcher.rs#L142)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can `get_done_proposal` return a proposal not found error instead of an option in that case?
</blockquote></details>

Done.
___
*[`crates/batcher/src/batcher.rs` line 144 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O950Gh-1XDtfUrp6oP0:-O99AGLy2FinUfP4AJov:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/batcher.rs#L144)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you add documentation to this trait function (that is returns the first height the is empty)?
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 138 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O9547fS382CMzntEKFu:-O99AuprCvtqbyDHKdfv:bkbnewo) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L138)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

WDYT of renaming done proposal -> proposal result? I think it would have been more clear to me as a first time reader
</blockquote></details>

Changed to `ProposalOutput` because in the following PR I change this to a struct and keep `Result<ProposalOutput>`
___
*[`crates/batcher/src/proposal_manager.rs` line 145 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O9552SQALVbHqeIbaIE:-O99BcdO-sT2u5rVEPEK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L145)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This sounds like reseting the height to zero.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 276 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O956U6T6debvjhUn0ZP:-O99BgSY-fe_4T9iTWqj:bfvnt06) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L276)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Use type?
</blockquote></details>

In the following PR
___
*[`crates/batcher/src/proposal_manager.rs` line 298 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O956nfp7M1du-9_o3f2:-O99CNT8ECRNBfzHs8gn:b499q7j) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L298)):*
> ```XML
>         );
> 
>         // Wait for either the block builder to finish / the feeding of transactions to error / the
> ```

Changed
___
*[`crates/batcher/src/proposal_manager.rs` line 313 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O959Kg_-8nxfpmRChZ5:-O99DOZa9wT9FrljQPZy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L313)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why not a method like previously?
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 352 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O957R8_ArFlYN1t93IR:-O99DU365-Jk5uriQP-f:bfvnt06) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L352)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

In the following PR


<!-- Sent from Reviewable.io -->

2024-10-14 10:52 UTC, Yael-Starkware requested changes
> Reviewed 1 of 7 files at r1, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 4 of 8 files reviewed, 20 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/batcher_test.rs` line 141 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99ZSy7AAtuVtxBzswL:-O99ZSy7AAtuVtxBzswM:b-vvnlny) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/batcher_test.rs#L141)):*
> ```XML
>         Box::new(proposal_manager),
>     );
>     batcher.decision_reached(DecisionReachedInput { proposal_id: ProposalId(0) }).await.unwrap();
> ```

add a test case for invalid proposalId
___
*[`crates/batcher/src/proposal_manager.rs` line 145 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99TwK2DU21phX8UUFx:-O99TwK2DU21phX8UUFy:badbjbx) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L145)):*
> ```XML
>     #[instrument(skip(self), err)]
>     async fn start_height(&mut self, height: BlockNumber) -> Result<(), StartHeightError> {
>         self.reset_height().await;
> ```

reset only if not already working on the input_height 



_Code quote:_
```XML
self.reset_height().await;
```
___
*[`crates/batcher/src/proposal_manager.rs` line 235 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O951GeP-IwF_mEjD-P5:-O99V3hJ6zVAg79zGajB:b9d7jfm) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L235)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

All the proposals are from the same height the whole time
</blockquote></details>

right, but they can all be from the same height, which is the current height and then you shouldn't clear them
___
*[`crates/batcher/src/proposal_manager.rs` line 313 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99XDcu6ALze1ZpZu_f:-O99XDcu6ALze1ZpZu_g:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L313)):*
> ```XML
>             }
>         };
>         Self::active_proposal_finished(self.active_proposal, result, self.done_proposals).await;
> ```





_Suggestion:_
```XML
mark_active_proposal_as_done(result)
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 228 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99_EXJ0TfAAS0YBZlY:-O99_EXJ0TfAAS0YBZlZ:b-r9d0wl) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager_test.rs#L228)):*
> ```XML
>         .expect_create_block_builder()
>         .once()
>         .returning(|_, _| simulate_build_block(None, Ok(BlockExecutionArtifacts::default())));
> ```

note that after rebase, default won't work here automatically. you'll need to use bouncer_wieghts.empty() to implement it



_Code quote:_
```XML
default
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 264 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99dQwlDKc4QkC0HUzJ:-O99dQwlDKc4QkC0HUzK:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager_test.rs#L264)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn decision_reached_no_active_proposal(
> ```





_Suggestion:_
```XML
test_get_active_proposal
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 281 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99b1n48Ba3rBtmBUFa:-O99b1n48Ba3rBtmBUFb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager_test.rs#L281)):*
> ```XML
>     });
> 
>     let expected_txs = test_txs(0..proposal_manager_config.max_txs_per_mempool_request);
> ```





_Suggestion:_
```XML
n_txs
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 310 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99djqE4LuuVxwpqCa_:-O99djqE4LuuVxwpqCaa:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager_test.rs#L310)):*
> ```XML
>     proposal_manager.await_active_proposal().await;
> 
>     proposal_manager.get_done_proposal(ProposalId(0)).await.unwrap().unwrap();
> ```





_Suggestion:_
```XML
proposal_manager.get_done_proposal(ProposalId(0)).await.unwrap().unwrap();
proposal_manager.get_done_proposal(ProposalId(1)).await.unwrap().unwrap();
```


<!-- Sent from Reviewable.io -->

2024-10-14 11:16 UTC, alonh5 reviewed
> Reviewed 2 of 7 files at r3, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 6 of 8 files reviewed, 15 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 138 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O9547fS382CMzntEKFu:-O99gBCw2K6cFGSYA5AU:bm710eq) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L138)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Changed to `ProposalOutput` because in the following PR I change this to a struct and keep `Result<ProposalOutput>`
</blockquote></details>

Right I saw, this is better. WDYT of `ProposalExecutionOutput`? A bit longer but also more definitive.
Also change function and variable names from `done_proposal`.
___
*[`crates/batcher/src/proposal_manager.rs` line 299 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99jZxx4ndENQe7y8BL:-O99jZxx4ndENQe7y8BM:bv053um) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L299)):*
> ```XML
> 
>         // Wait for either the block builder to finish / the feeding of transactions to error / the
>         // proposal to be aborted. The other tasks will be cancelled.
> ```

Did you leave this out on purpose?



_Code quote:_
```XML
proposal to be aborted.
```
___
*[`crates/batcher/src/proposal_manager.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99fQ0RApZiv5WmHImq:-O99fQ0RApZiv5WmHImr:b6vq77j) ([raw file](https://github.com/starkware-libs/sequencer/blob/754e636f5b36ed2e538ec44922db6c5ebadf1736/crates/batcher/src/proposal_manager.rs#L101)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum GetDoneProposalError {
> ```

I understand what you meant about adding a new enum. Do you think we need different enums or can we just have one `ProposalManagerError`? (not for this PR)


<!-- Sent from Reviewable.io -->

2024-10-14 13:08 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 6 of 8 files reviewed, 13 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/batcher_test.rs` line 141 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99ZSy7AAtuVtxBzswL:-O99wxIWB60TaTdP3CsK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/batcher_test.rs#L141)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

add a test case for invalid proposalId
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 138 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O9547fS382CMzntEKFu:-O9A4c4G76vM39OC7Nkk:b-ktoe9s) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L138)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Right I saw, this is better. WDYT of `ProposalExecutionOutput`? A bit longer but also more definitive.
Also change function and variable names from `done_proposal`.
</blockquote></details>

Changed the member and the function. ProposalResult that wraps ProposalOutput is good enough IMO.
___
*[`crates/batcher/src/proposal_manager.rs` line 299 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99jZxx4ndENQe7y8BL:-O99xQKW2b7PLD_OjvSC:bo639fx) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L299)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Did you leave this out on purpose?
</blockquote></details>

Yes, the abort flow is not for this milestone.
For now we let the block builder finish even if it can be stopped.
___
*[`crates/batcher/src/proposal_manager.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99fQ0RApZiv5WmHImq:-O99x-4j4ImVcAnvJbei:b-65gnmx) ([raw file](https://github.com/starkware-libs/sequencer/blob/754e636f5b36ed2e538ec44922db6c5ebadf1736/crates/batcher/src/proposal_manager.rs#L101)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I understand what you meant about adding a new enum. Do you think we need different enums or can we just have one `ProposalManagerError`? (not for this PR)
</blockquote></details>

In the beginning I did it, but it was bad.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 264 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99dQwlDKc4QkC0HUzJ:-O9A6RxP4_Kfi0jQv0FF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager_test.rs#L264)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn decision_reached_no_active_proposal(
> ```

Done.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 281 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99b1n48Ba3rBtmBUFa:-O9A6m557AkZF82q-I8H:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager_test.rs#L281)):*
> ```XML
>     });
> 
>     let expected_txs = test_txs(0..proposal_manager_config.max_txs_per_mempool_request);
> ```

Done.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 310 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99djqE4LuuVxwpqCa_:-O9A6qy3A79gM-ZbEPpB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager_test.rs#L310)):*
> ```XML
>     proposal_manager.await_active_proposal().await;
> 
>     proposal_manager.get_done_proposal(ProposalId(0)).await.unwrap().unwrap();
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-14 13:51 UTC, Yael-Starkware requested changes
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 6 of 8 files reviewed, 9 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 145 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99TwK2DU21phX8UUFx:-O9AI6z27mxFXCh3U9WK:bq72mxu) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L145)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

reset only if not already working on the input_height
</blockquote></details>

as discussed I'm retracting this


<!-- Sent from Reviewable.io -->

2024-10-14 13:52 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: 6 of 8 files reviewed, 8 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 235 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O951GeP-IwF_mEjD-P5:-O9AIDok-AooavB7b7J_:bq72mxu) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L235)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

right, but they can all be from the same height, which is the current height and then you shouldn't clear them
</blockquote></details>

as discussed I'm retracting this


<!-- Sent from Reviewable.io -->

2024-10-14 14:22 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-:-O9AOjEV9PjWb3AI1BM9:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 299 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1153#-O99jZxx4ndENQe7y8BL:-O9ALXZ_3RUGkhIbcRTz:bcr5s31) ([raw file](https://github.com/starkware-libs/sequencer/blob/7413c68a43595a803ef2e4f66181bc4e890f2ea5/crates/batcher/src/proposal_manager.rs#L299)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Yes, the abort flow is not for this milestone.
For now we let the block builder finish even if it can be stopped.
</blockquote></details>

Got it, thanks.


<!-- Sent from Reviewable.io -->

2024-10-15 07:00 UTC, yair-starkware reviewed
> Dismissed @dafnamatsry from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-10-15 07:01 UTC, yair-starkware reviewed
> Reviewed 1 of 7 files at r1, 2 of 7 files at r3, 1 of 5 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1153)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-10-15 07:02 UTC, merged