refactor(blockifier): replace Default drive of Bouncer and related st…
starkware-libs/sequencer pull request #1292
Opened 2024-10-10 09:40 UTC by ayeletstarkware

…ructs by empty func

2024-10-13 05:12 UTC, Yael-Starkware requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1292)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/batcher/src/block_builder.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93Gper00f61kFRyvRV:-O93Gper00f61kFRyvRW:b-xkq5mk) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/batcher/src/block_builder.rs#L89)):*
> ```XML
>         }
>     }
> }
> ```

please move to test_utils.rs



_Code quote:_
```XML
impl BlockExecutionArtifacts {
    pub fn empty() -> Self {
        Self {
            execution_infos: IndexMap::default(),
            commitment_state_diff: CommitmentStateDiff::default(),
            visited_segments_mapping: VisitedSegmentsMapping::default(),
            bouncer_weights: BouncerWeights::empty(),
        }
    }
}
```
___
*[`crates/blockifier/src/bouncer.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93H-bl0HiQDQBy19uK:-O93H-bl0HiQDQBy19uL:b9jmc5b) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/blockifier/src/bouncer.rs#L49)):*
> ```XML
>     pub fn empty() -> Self {
>         Self { block_max_capacity: BouncerWeights::empty() }
>     }
> ```

please move to struct_impls.rs



_Code quote:_
```XML
impl BouncerConfig {
    pub fn empty() -> Self {
        Self { block_max_capacity: BouncerWeights::empty() }
    }
```
___
*[`crates/blockifier/src/bouncer.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93H5iO3gzHhmlHWbIt:-O93H5iO3gzHhmlHWbIu:b9jmc5b) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/blockifier/src/bouncer.rs#L128)):*
> ```XML
>             n_steps: 0,
>             state_diff_size: 0,
>         }
> ```

please move to struct_impls.rs



_Code quote:_
```XML
    pub fn empty() -> Self {
        Self {
            n_events: 0,
            builtin_count: BuiltinCount::default(),
            gas: 0,
            message_segment_length: 0,
            n_steps: 0,
            state_diff_size: 0,
        }
```
___
*[`crates/blockifier/src/bouncer.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93HAP833b-0258hNyK:-O93HAP833b-0258hNyL:b-o6ymwg) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/blockifier/src/bouncer.rs#L291)):*
> ```XML
>             accumulated_weights: BouncerWeights::empty(),
>         }
>     }
> ```

please change the name of the function and move to struct_impls.rs



_Suggestion:_
```XML
    pub fn create_for_testing() -> Self {
        Bouncer {
            executed_class_hashes: HashSet::default(),
            visited_storage_entries: HashSet::default(),
            state_changes_keys: StateChangesKeys::default(),
            bouncer_config: BouncerConfig::empty(),
            accumulated_weights: BouncerWeights::empty(),
        }
    }
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93HXZWDTRrSsE8VUPi:-O93HXZWDTRrSsE8VUPj:b-7r2g0o) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/blockifier/src/test_utils/struct_impls.rs#L283)):*
> ```XML
> 
> impl BouncerWeights {
>     pub fn create_for_testing(builtin_count: BuiltinCount) -> Self {
> ```

empty



_Code quote:_
```XML
create_for_testing
```


<!-- Sent from Reviewable.io -->

2024-10-13 05:13 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1292)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93HXZWDTRrSsE8VUPi:-O93Hp-w1frz696eHyFA:b4ta5bs) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/blockifier/src/test_utils/struct_impls.rs#L283)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

empty
</blockquote></details>

retracting, this is not empty


<!-- Sent from Reviewable.io -->

2024-10-13 05:16 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1292)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/batcher/src/block_builder.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93Gper00f61kFRyvRV:-O93IJ8fAkxYOU9_bUWf:b3rjq91) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/batcher/src/block_builder.rs#L89)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

please move to test_utils.rs
</blockquote></details>

and you can keep the default trait here since it is not a part of the config

also you can use 
{
bouncer_weights: BouncerWeights::empty(),
..Default::default(),
}


<!-- Sent from Reviewable.io -->

2024-10-13 08:16 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1292)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93Gper00f61kFRyvRV:-O93txrVBRxoqpuTnV3r:bmqwbyf) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/batcher/src/block_builder.rs#L89)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

and you can keep the default trait here since it is not a part of the config

also you can use 
{
bouncer_weights: BouncerWeights::empty(),
..Default::default(),
}
</blockquote></details>

1 - renamed to default
2 - can't use `..Default::default()` here because it calls the `default` function on itself, which leads to endless looping.
3 - there's no `test_utils.rs` in batcher crate. Is there another place to move it?
___
*[`crates/blockifier/src/bouncer.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93H-bl0HiQDQBy19uK:-O93reiz0YxeW5aSXaFi:bk2chxi) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/blockifier/src/bouncer.rs#L49)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

please move to struct_impls.rs
</blockquote></details>

I relocated the empty functions for BouncerConfig and BouncerWeights from test utils, as they are now used outside of tests  (in ` Default for ExecutionConfig`, #1277).
___
*[`crates/blockifier/src/bouncer.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93H5iO3gzHhmlHWbIt:-O93wQh2C8i3-jkqTCbj:b6fjmzz) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/blockifier/src/bouncer.rs#L128)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

please move to struct_impls.rs
</blockquote></details>

same for 'BoucerWeights'
___
*[`crates/blockifier/src/bouncer.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93HAP833b-0258hNyK:-O93viIf0GLjIng6OvrX:b-bm2rnl) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/blockifier/src/bouncer.rs#L291)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

please change the name of the function and move to struct_impls.rs
</blockquote></details>

This function is being used in Bouncer's`new` function, which is being used outside of testing.


<!-- Sent from Reviewable.io -->

2024-10-13 09:30 UTC, Yael-Starkware requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1292)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/batcher/src/block_builder.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93Gper00f61kFRyvRV:-O949gxt8VHsTxr0JSES:bojx45) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/batcher/src/block_builder.rs#L89)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

1 - renamed to default
2 - can't use `..Default::default()` here because it calls the `default` function on itself, which leads to endless looping.
3 - there's no `test_utils.rs` in batcher crate. Is there another place to move it?
</blockquote></details>

Ack
3- I created the file but not pushed yet, so please create it yourself.
___
*[`crates/blockifier/src/bouncer.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93H-bl0HiQDQBy19uK:-O94CaMi4SEHo8lOsTlH:bzf0qx2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/blockifier/src/bouncer.rs#L49)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I relocated the empty functions for BouncerConfig and BouncerWeights from test utils, as they are now used outside of tests  (in ` Default for ExecutionConfig`, #1277).
</blockquote></details>

but the default for ExecutionConfig should be the real values and not  an empty config.


<!-- Sent from Reviewable.io -->

2024-10-13 10:26 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1292)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93Gper00f61kFRyvRV:-O94OlKn7My7XklI8nek:b-53idbb) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/batcher/src/block_builder.rs#L89)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Ack
3- I created the file but not pushed yet, so please create it yourself.
</blockquote></details>

Done. Renamed to `create_for_testing`. Implementing a default function in `test_utils` felt odd.
___
*[`crates/blockifier/src/bouncer.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O93H-bl0HiQDQBy19uK:-O94JLjC-EJhSUEt-DgM:b-ofzk4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a91407f370245804b5b0dc8a65db49c32c9b3/crates/blockifier/src/bouncer.rs#L49)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

but the default for ExecutionConfig should be the real values and not  an empty config.
</blockquote></details>

Discussed offline: since both `empty` and `default` are used in non-test code, their implementation will stay here.


<!-- Sent from Reviewable.io -->

2024-10-13 13:05 UTC, Yael-Starkware requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1292)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/bouncer.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O94yfBkDjgz00PuGLRc:-O94yfBkDjgz00PuGLRd:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0de31a9e5fe4d0a1e8be3b806f3d3f9d840caf70/crates/blockifier/src/bouncer.rs#L123)):*
> ```XML
>         Self {
>             n_events: 0,
>             builtin_count: BuiltinCount::default(),
> ```





_Suggestion:_
```XML
empty()
```


<!-- Sent from Reviewable.io -->

2024-10-13 13:18 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1292)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1292#-O94yfBkDjgz00PuGLRc:-O950J9sAWo90Yvm3JId:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/0de31a9e5fe4d0a1e8be3b806f3d3f9d840caf70/crates/blockifier/src/bouncer.rs#L123)):*
> ```XML
>         Self {
>             n_events: 0,
>             builtin_count: BuiltinCount::default(),
> ```

Done


<!-- Sent from Reviewable.io -->

2024-10-14 08:12 UTC, Yael-Starkware approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1292)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-10-14 08:29 UTC, merged