test(mempool): update add tx test to test two queues
starkware-libs/sequencer pull request #1295
Opened 2024-10-10 10:26 UTC by MohammadNassar1

2024-10-10 13:33 UTC, MohammadNassar1 reviewed
This PR checks that `AddTx` API updates the correct tx queue according to the `l2_gas_price_per_unit`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-:-O8qcFtm-2J8uMe7Dvwx:b-kqwbs1)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-10-10 16:13 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/test_utils.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O8rBpseAnqQsPe5lwPa:-O8rBpseAnqQsPe5lwPb:b27zqya) ([raw file](https://github.com/starkware-libs/sequencer/blob/5df4b7492f9e3b34316f874859914905ddaefa1f/crates/mempool/src/test_utils.rs#L21)):*
> ```XML
>             let resource_bounds = ValidResourceBounds::AllResources(AllResourceBounds {
>                 l2_gas: ResourceBounds {
>                     max_price_per_unit: GasPrice($max_l2_gas_price),
> ```

This is temporal till [this](https://reviewable.io/reviews/starkware-libs/sequencer/1316) PR is merged.



_Code quote:_
```XML
 max_price_per_unit: GasPrice($max_l2_gas_price),
```


<!-- Sent from Reviewable.io -->

2024-10-13 08:38 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/test_utils.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O8rBpseAnqQsPe5lwPa:-O940j7F-A1NxdX8YY3e:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/5df4b7492f9e3b34316f874859914905ddaefa1f/crates/mempool/src/test_utils.rs#L21)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This is temporal till [this](https://reviewable.io/reviews/starkware-libs/sequencer/1316) PR is merged.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-10-13 12:19 UTC, ayeletstarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-:-O94oFc80YMi7CY8rR5T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-10-13 12:27 UTC, ayeletstarkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94pm5L5pppM1bHBPR9:-O94pm5L5pppM1bHBPRA:b-6zm6nc) (no related file):*
Consider splitting into two PRs: `TransactionQueueContent` updates and the test update. 

___


<!-- Sent from Reviewable.io -->

2024-10-13 12:29 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94pm5L5pppM1bHBPR9:-O94qO0f43mUm1s6h-m6:b-eybta) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Consider splitting into two PRs: `TransactionQueueContent` updates and the test update.
</blockquote></details>

You're right, this could be split into two PRs, but I think it's small enough to keep everything in one. 
What do you think? Let's also see what others think

___


<!-- Sent from Reviewable.io -->

2024-10-13 12:31 UTC, ayeletstarkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2024-10-13 12:38 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O94s4ag5YgtjYvlJ-wV:b-deaqu9) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_multi_nonce_success() {
> ```

Should it appear in the same test?



_Code quote:_
```XML
test_add_tx_multi_nonce_success
```
___
*[`crates/mempool/src/mempool_test.rs` line 354 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94sC2_3aN5JWvfy0Pc:-O94sC2_3aN5JWvfy0Pd:brkohbx) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L354)):*
> ```XML
>     let priority_tx_input_address_0_nonce_1 =
>         add_tx_input!(tx_hash: 3, sender_address: "0x0", tx_nonce: 1, account_nonce: 0);
>     let pending_tx_input_address_1_nonce_0 = add_tx_input!(tx_hash: 2, sender_address: "0x1", tx_nonce: 0,account_nonce: 0, max_l2_gas_price: VALID_L2_GAS_MAX_PRICE_PER_UNIT - 1);
> ```

Please manually break line.



_Suggestion:_
```XML
    let pending_tx_input_address_1_nonce_0 = 
        add_tx_input!(tx_hash: 2, sender_address: "0x1", tx_nonce: 0,account_nonce: 0, 
        max_l2_gas_price: VALID_L2_GAS_MAX_PRICE_PER_UNIT - 1);
```
___
*[`crates/mempool/src/mempool_test.rs` line 354 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94sgseDzQ3uLDanvBd:-O94sgseDzQ3uLDanvBe:bnmuo0m) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L354)):*
> ```XML
>     let priority_tx_input_address_0_nonce_1 =
>         add_tx_input!(tx_hash: 3, sender_address: "0x0", tx_nonce: 1, account_nonce: 0);
>     let pending_tx_input_address_1_nonce_0 = add_tx_input!(tx_hash: 2, sender_address: "0x1", tx_nonce: 0,account_nonce: 0, max_l2_gas_price: VALID_L2_GAS_MAX_PRICE_PER_UNIT - 1);
> ```

I think a simpler number be used, say `100`. This constant is cumbersome.



_Code quote:_
```XML
VALID_L2_GAS_MAX_PRICE_PER_UNIT
```


<!-- Sent from Reviewable.io -->

2024-10-13 12:50 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O94v4Lx8r55DVoGvBeg:b-zbtbs5) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Should it appear in the same test?
</blockquote></details>

I made a small change to the test, so I thought it would be fine to incorporate it into the existing test.
wdyt?
___
*[`crates/mempool/src/mempool_test.rs` line 354 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94sgseDzQ3uLDanvBd:-O94v35q4t4KVtF56oLG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L354)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think a simpler number be used, say `100`. This constant is cumbersome.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-13 12:54 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O94w0mk3ItW5x7XZnSl:bz2wgam) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I made a small change to the test, so I thought it would be fine to incorporate it into the existing test.
wdyt?
</blockquote></details>

I guess it could qualify as the canonical `add_tx` test, but we already have one that's called `test_add_tx`.
What's the difference between them? Should we rename them?
___
*[`crates/mempool/src/mempool_test.rs` line 354 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94sC2_3aN5JWvfy0Pc:-O94wHDz0OcGJ2ygGV_S:b3o087l) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L354)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please manually break line.
</blockquote></details>

Line is still longer than `100` chars.


<!-- Sent from Reviewable.io -->

2024-10-13 13:04 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O94xnJG4wHXeJlSjOgF:b-jzhjyq) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I guess it could qualify as the canonical `add_tx` test, but we already have one that's called `test_add_tx`.
What's the difference between them? Should we rename them?
</blockquote></details>

`test_add_tx` is a basic test for adding a transaction with a single nonce per address. 

`test_add_tx_multi_nonce_success` tests adding transactions involving multiple nonces from the same address.
___
*[`crates/mempool/src/mempool_test.rs` line 354 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94sC2_3aN5JWvfy0Pc:-O94yXaB-kdbVlNfFdfn:bnr4waw) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L354)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Line is still longer than `100` chars.
</blockquote></details>

Done, now it's `94` chars.


<!-- Sent from Reviewable.io -->

2024-10-13 13:05 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O94ynI7E2NkBtOupLen:blcu366) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

`test_add_tx` is a basic test for adding a transaction with a single nonce per address. 

`test_add_tx_multi_nonce_success` tests adding transactions involving multiple nonces from the same address.
</blockquote></details>

I thinks names are good.
Maybe ``test_add_tx` can be renamed to `test_add_tx_single_nonce`.
wdyt?


<!-- Sent from Reviewable.io -->

2024-10-14 07:10 UTC, elintul requested changes
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O98r6d00RCq1RAPsrbp:bnzcjqz) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I thinks names are good.
Maybe ``test_add_tx` can be renamed to `test_add_tx_single_nonce`.
wdyt?
</blockquote></details>

Please find better more descriptive name for those two tests.


<!-- Sent from Reviewable.io -->

2024-10-14 08:32 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O992QrDCHrwjzc4JG-k:bgx17hc) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please find better more descriptive name for those two tests.
</blockquote></details>

I suggest the following names:

The first test with the single nonce:
`test_add_tx_single_nonce_sorted_by_tip`
Description:
Test focuses on adding transactions with a single nonce and ensures they are sorted by the tip in the queue.

The second test:
`test_add_tx_multi_nonce_correct_queue_by_gas_price_and_eligibility`
Description:
checks transactions with multiple nonces, ensures they are placed in the correct queue based on gas price, and only eligible transactions are prioritized.

wdyt?


<!-- Sent from Reviewable.io -->

2024-10-14 08:55 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O99E2Aw31jV9pEFPe3Q:-O99E2Aw31jV9pEFPe3R:b-tl8qfg) (no related file):*
`origin/main` is broken, which explains why the CI fails.
I will rebase once the fix is ready.

___


<!-- Sent from Reviewable.io -->

2024-10-14 10:55 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O99E2Aw31jV9pEFPe3Q:-O99eg4HBywp_fLPSPV6:bncvegj) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

`origin/main` is broken, which explains why the CI fails.
I will rebase once the fix is ready.
</blockquote></details>

Rebased.

___


<!-- Sent from Reviewable.io -->

2024-10-14 11:33 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O99kBnG2Lz90UUE_RC4:bnh1swd) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I suggest the following names:

The first test with the single nonce:
`test_add_tx_single_nonce_sorted_by_tip`
Description:
Test focuses on adding transactions with a single nonce and ensures they are sorted by the tip in the queue.

The second test:
`test_add_tx_multi_nonce_correct_queue_by_gas_price_and_eligibility`
Description:
checks transactions with multiple nonces, ensures they are placed in the correct queue based on gas price, and only eligible transactions are prioritized.

wdyt?
</blockquote></details>

Changed to new names suggested by @ayeletstarkware that are similar to the names for get_txs tests.

`test_add_tx_sorts_by_priority_order`:
This name highlights that the test ensures transactions are sorted by priority once they are added.

`test_add_tx_correctly_places_txs_in_mempool_ds`
This name emphasizes that the test ensures transactions are placed in the correct data structures (pool, priority queue, or pending queue). Multi-nonce handling is implied when transactions are added to the pools, so it doesn't need to be explicitly mentioned.


<!-- Sent from Reviewable.io -->

2024-10-14 13:00 UTC, ayeletstarkware approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2024-10-15 06:25 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O9DpPeY3EBVGDNxsxdu:bz8lcfx) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Changed to new names suggested by @ayeletstarkware that are similar to the names for get_txs tests.

`test_add_tx_sorts_by_priority_order`:
This name highlights that the test ensures transactions are sorted by priority once they are added.

`test_add_tx_correctly_places_txs_in_mempool_ds`
This name emphasizes that the test ensures transactions are placed in the correct data structures (pool, priority queue, or pending queue). Multi-nonce handling is implied when transactions are added to the pools, so it doesn't need to be explicitly mentioned.
</blockquote></details>

For the test above: still not a good name, `add_tx` doesn't sort the transactions. Also, "priority" and "order" is redundant. We should probably change the `get_txs` test name as well.
I'd like to understand this scenario: do all incoming transactions go to priority queue? Why?

Re second one: "ds" is a opaque unclear abbreviation, I'm not a fan of them (my only exception is "tx", as you know). What are those data structures for a reader? Meaning is also opaque...
I still don't understand the difference between those two tests (asked before, in my first comment). Please briefly explain the scenarios, so I won't need to read them. Does multi/single nonce also belong in this scenario? If not, maybe we should separate to another test? Can we simplify them? 
We should be careful not to overload unit tests with multiple checks (maybe that's the case, but as the one who reads the code, I'm still not convinced).

As the code writer, it is your responsibility to explain your decisions to the reviewer. 


<!-- Sent from Reviewable.io -->

2024-10-15 07:43 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O9DzubN13EFdAQ7toHC:b-sdyyd2) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

For the test above: still not a good name, `add_tx` doesn't sort the transactions. Also, "priority" and "order" is redundant. We should probably change the `get_txs` test name as well.
I'd like to understand this scenario: do all incoming transactions go to priority queue? Why?

Re second one: "ds" is a opaque unclear abbreviation, I'm not a fan of them (my only exception is "tx", as you know). What are those data structures for a reader? Meaning is also opaque...
I still don't understand the difference between those two tests (asked before, in my first comment). Please briefly explain the scenarios, so I won't need to read them. Does multi/single nonce also belong in this scenario? If not, maybe we should separate to another test? Can we simplify them? 
We should be careful not to overload unit tests with multiple checks (maybe that's the case, but as the one who reads the code, I'm still not convinced).

As the code writer, it is your responsibility to explain your decisions to the reviewer.
</blockquote></details>

Re first test:

Description of the test: 
The tests verify the `add_tx` API by sending a single transaction from each address. This ensures that all transactions are added to the queue, where they are sorted by priority (tip + hash). The test checks that the queue is correctly sorted. The test haven't changed the default gas price values, so all the transactions go to priority queue (and not to pending queue).

I agree that using both "priority" and "order" is redundant, so "order" has been removed. However, it’s important to include "sort," since the `add_tx` function adds (and sorts) transactions in a specific order. While the sorting occurs in the queue and not directly in `add_tx`, we avoid revealing implementation details in the test name.

Regarding nonces, since the transactions are sorted by priority, then all of them are eligible, and they must originate from different addresses. As a result, no need to emphasize it in the test name.

The suggested name: `test_add_tx_sorts_by_priority`



Re second test:

Description of the test: 
The test verifies that the `AddTx` API correctly places transactions in the appropriate data structures (priority\_queue, pending\_queue, or pool). It adds multiple transactions with the same nonce, which creates a scenario where some transactions are ineligible and therefore only added to the pool, not to one of the queues. The test ensures that transactions are placed in the correct structure based on their eligibility and gas price.

Suggested name:
`test_add_tx_correctly_places_txs_in_pool_or_queues`
I don’t believe it's necessary to include "multi_nonce" in the name, as the fact that not all transactions are going to the queue implies the presence of ineligible transactions, and thus multiple nonces are involved.


Re overloading a unit test:
I don’t believe the test is overloaded, as the changes I made are minimal. I didn’t add new transactions; I simply initialized the existing transactions with different gas price values. This allows me to check whether they go into the pending queue or the priority queue.

Please let me know if you have further questions about the test descriptions, and whether you liked my naming suggestions.

As for the `get_txs` tests, once we finalize the names for the `add_tx` tests, I will update the `get_txs` test names in a separate PR.


<!-- Sent from Reviewable.io -->

2024-10-15 10:21 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O9Ee9GFBDT7GnZUZUWe:b-54xe5v) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Re first test:

Description of the test: 
The tests verify the `add_tx` API by sending a single transaction from each address. This ensures that all transactions are added to the queue, where they are sorted by priority (tip + hash). The test checks that the queue is correctly sorted. The test haven't changed the default gas price values, so all the transactions go to priority queue (and not to pending queue).

I agree that using both "priority" and "order" is redundant, so "order" has been removed. However, it’s important to include "sort," since the `add_tx` function adds (and sorts) transactions in a specific order. While the sorting occurs in the queue and not directly in `add_tx`, we avoid revealing implementation details in the test name.

Regarding nonces, since the transactions are sorted by priority, then all of them are eligible, and they must originate from different addresses. As a result, no need to emphasize it in the test name.

The suggested name: `test_add_tx_sorts_by_priority`



Re second test:

Description of the test: 
The test verifies that the `AddTx` API correctly places transactions in the appropriate data structures (priority\_queue, pending\_queue, or pool). It adds multiple transactions with the same nonce, which creates a scenario where some transactions are ineligible and therefore only added to the pool, not to one of the queues. The test ensures that transactions are placed in the correct structure based on their eligibility and gas price.

Suggested name:
`test_add_tx_correctly_places_txs_in_pool_or_queues`
I don’t believe it's necessary to include "multi_nonce" in the name, as the fact that not all transactions are going to the queue implies the presence of ineligible transactions, and thus multiple nonces are involved.


Re overloading a unit test:
I don’t believe the test is overloaded, as the changes I made are minimal. I didn’t add new transactions; I simply initialized the existing transactions with different gas price values. This allows me to check whether they go into the pending queue or the priority queue.

Please let me know if you have further questions about the test descriptions, and whether you liked my naming suggestions.

As for the `get_txs` tests, once we finalize the names for the `add_tx` tests, I will update the `get_txs` test names in a separate PR.
</blockquote></details>

If you feel the above comment is too long, please skip it.
I'll try to write a succinct comment. 


<!-- Sent from Reviewable.io -->

2024-10-15 10:22 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O9Egad36ZcX8aLRVyY1:b-7w5o9i) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

If you feel the above comment is too long, please skip it.
I'll try to write a succinct comment.
</blockquote></details>

Based on our discussion, I will rename non-changed tests in another PR.


In this PR I rename only `test_add_tx_multi_nonce_success`.


<!-- Sent from Reviewable.io -->

2024-10-15 10:30 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O94s4af7sNIEJEOflTo:-O9EgjuW67H1gKJnFAuP:b3y6iqz) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d6f63187de729cfd07d48b93d4655b0c282c758/crates/mempool/src/mempool_test.rs#L348)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Based on our discussion, I will rename non-changed tests in another PR.


In this PR I rename only `test_add_tx_multi_nonce_success`.
</blockquote></details>

This test now includes non-eligible transactions and verifies that `addTx` correctly assigns transactions to the pool, priority queue, or pending queue. The only change I made was adding gas price configurations to existing transactions, which doesn’t overload the original test.

Suggested test name:
`test_add_tx_correctly_places_txs_in_pool_or_queues`

Including "multi_nonce" in the name isn’t necessary since ineligible transactions imply multiple nonces.


<!-- Sent from Reviewable.io -->

2024-10-15 13:19 UTC, ayeletstarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r10, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-:-O9FKPF34TRXzCishEml:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2024-10-15 14:56 UTC, elintul reviewed
> Reviewed 1 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-10-15 15:05 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 284 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O9Fh0_j9pShGwFKs_Ng:-O9Fh0_j9pShGwFKs_Nh:bv6sdj1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b586ce1d6c38cb1a271b2f7c5c31f0de62ad25a8/crates/mempool/src/mempool_test.rs#L284)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx(mut mempool: Mempool) {
> ```

Are you planning to rename this test (and its `get_txs` counterpart)? I think we should.
Can you shortly explained why all transactions here go to priority Q? 


<!-- Sent from Reviewable.io -->

2024-10-15 15:14 UTC, elintul reviewed
> Reviewed 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-10-15 15:15 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 315 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O9Fjmq49Gk6OLweEXke:-O9Fjmq49Gk6OLweEXkf:b-j43fug) ([raw file](https://github.com/starkware-libs/sequencer/blob/b586ce1d6c38cb1a271b2f7c5c31f0de62ad25a8/crates/mempool/src/mempool_test.rs#L315)):*
> ```XML
> fn test_add_tx_correctly_places_txs_in_pool_or_queues() {
>     // Setup.
>     let priority_tx_input_address_0_nonce_0 = add_tx_input!(tx_hash: 1, sender_address: "0x0",
> ```

Maybe we can let "input" go in this eve already long names? 


<!-- Sent from Reviewable.io -->

2024-10-15 15:16 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 284 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O9Fh0_j9pShGwFKs_Ng:-O9FjK296tNuRHHNfwtd:bu849r5) ([raw file](https://github.com/starkware-libs/sequencer/blob/b586ce1d6c38cb1a271b2f7c5c31f0de62ad25a8/crates/mempool/src/mempool_test.rs#L284)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are you planning to rename this test (and its `get_txs` counterpart)? I think we should.
Can you shortly explained why all transactions here go to priority Q?
</blockquote></details>

Yes, I'm planning; based on our discussion, I will rename non-changed tests in another PR.

In this test, the transactions come from different addresses, making all of them eligible. The test uses the default gas price configuration, so all the transactions are go to priority queue (the default settings).


<!-- Sent from Reviewable.io -->

2024-10-15 15:28 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 284 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O9Fh0_j9pShGwFKs_Ng:-O9FlKbB81IalDIBocbl:b-t5liow) ([raw file](https://github.com/starkware-libs/sequencer/blob/b586ce1d6c38cb1a271b2f7c5c31f0de62ad25a8/crates/mempool/src/mempool_test.rs#L284)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Yes, I'm planning; based on our discussion, I will rename non-changed tests in another PR.

In this test, the transactions come from different addresses, making all of them eligible. The test uses the default gas price configuration, so all the transactions are go to priority queue (the default settings).
</blockquote></details>

Okay. I think names should be somehow similar and embed the differences between them. 


<!-- Sent from Reviewable.io -->

2024-10-15 18:23 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 315 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O9GPblH34EAlF8RXGDe:-O9GPblH34EAlF8RXGDf:b-i1hvhj) ([raw file](https://github.com/starkware-libs/sequencer/blob/8473c1afd108bc4d7412c793e8144d074efcc7ef/crates/mempool/src/mempool_test.rs#L315)):*
> ```XML
> fn test_add_tx_multi_nonce_success(mut mempool: Mempool) {
>     // Setup.
>     let input_address_0_nonce_0 =
> ```

Please only keep the fields that are relevant for the test (for example, `tx_hash` isn't needed; maybe more). 
Discussed before many times, let's stop missing this issue. Please increase awareness. 


<!-- Sent from Reviewable.io -->

2024-10-15 19:33 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1295)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 313 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O9GeBWl1GWpKtiAtP35:-O9GeBWl1GWpKtiAtP36:b-xqosz0) ([raw file](https://github.com/starkware-libs/sequencer/blob/b586ce1d6c38cb1a271b2f7c5c31f0de62ad25a8/crates/mempool/src/mempool_test.rs#L313)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_correctly_places_txs_in_pool_or_queues() {
> ```

Still not sure about extending this test. 
What are the tests we have for `add_tx`? Are there other ones checking insertion to pool?
We should keep tests succinct and lean; maybe have only one to check addition to pool, and the rest be more specific about queue(s) behavior? 
Please go over `get_txs` tests, which demonstrate this beautifully (had to refactor them, so only one checks soft-deletion from pool in `get_txs).



_Code quote:_
```XML
test_add_tx_correctly_places_txs_in_pool_or_queues
```
___
*[`crates/mempool/src/mempool_test.rs` line 342 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1295#-O9GdpAPAcUynUwP5qG2:-O9GdpAPAcUynUwP5qG3:b-ih1w5a) ([raw file](https://github.com/starkware-libs/sequencer/blob/b586ce1d6c38cb1a271b2f7c5c31f0de62ad25a8/crates/mempool/src/mempool_test.rs#L342)):*
> ```XML
>         priority_tx_input_address_0_nonce_0.tx,
>         pending_tx_input_address_1_nonce_0.tx,
>         priority_tx_input_address_0_nonce_1.tx,
> ```

Confusing name, it doesn't get into priority queue.
Why include "priority/pending" in the name at all? It's clear from how you build `expected_mempool_content` later on. Keep "input" (as opposed to my comment above, would still like a status update though); remove the queue name.



_Code quote:_
```XML
priority_tx_input_address_0_nonce_1
```


<!-- Sent from Reviewable.io -->

2024-10-21 11:54 UTC, closed without merging