feat: add support for native testing
starkware-libs/sequencer pull request #1301
Opened 2024-10-10 13:18 UTC by rodrigo-pino

2024-10-13 07:22 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @rodrigo-pino)

___
*[`crates/blockifier/feature_contracts/cairo_native/test_contract.cairo` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93jcc17DxyFgLopv3i:-O93jcc17DxyFgLopv3j:by2gxy7) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/feature_contracts/cairo_native/test_contract.cairo#L35)):*
> ```Cairo
>         two_counters: starknet::storage::Map<felt252, (felt252, felt252)>,
>         ec_point: (felt252, felt252),
>     }
> ```

This contract is almost identical to the test contract of the Casm contract class. Can we add the new functions to the existing contract to avoid duplication? 


<!-- Sent from Reviewable.io -->

2024-10-13 08:37 UTC, meship-starkware reviewed
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 4 unresolved discussions (waiting on @rodrigo-pino)

___
*[`crates/blockifier/src/test_utils.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93wpyO6HNmUICVLokU:-O93wpyO6HNmUICVLokV:b-wy21ij) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/src/test_utils.rs#L63)):*
> ```XML
>     Cairo0,
>     Cairo1,
>     Native,
> ```

Why did you add Native? Isn't the Native Cairo version Cairo1? Maybe we should change the Cario1 to Casm? This is a bit confusing because this enum no longer represents the Cairo version.  I think we should create a new enum for the different compilations WDYT? 



_Code quote:_
```XML
    Cairo0,
    Cairo1,
    Native,
```
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93vqXyBh9Ga_qa5diS:-O93vqXyBh9Ga_qa5diT:b-xo4dsa) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/src/test_utils/cairo_compile.rs#L151)):*
> ```XML
>     git_tag_override: Option<String>,
>     cargo_nightly_arg: Option<String>,
> ) -> Vec<u8> {
> ```

Can you make cairo1_compile use this function to avoid this duplication  



_Code quote:_
```XML
pub fn sierra_compile(
    path: String,
    git_tag_override: Option<String>,
    cargo_nightly_arg: Option<String>,
) -> Vec<u8> {
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93yydRB2dXIAT0NRCN:-O93yydRB2dXIAT0NRCO:bu6z6nh) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L68)):*
> ```XML
>         CairoVersion::Cairo0 => CAIRO0_FEATURE_CONTRACTS_DIR,
>         CairoVersion::Cairo1 => CAIRO1_FEATURE_CONTRACTS_DIR,
>         CairoVersion::Native => NATIVE_FEATURE_CONTRACTS_DIR,
> ```

I can't entirely agree with this. Native contracts are still Cairo1 contracts. I don't see why they need a new directory. 



_Code quote:_
```XML
CairoVersion::Native => NATIVE_FEATURE_CONTRACTS_DIR,
```


<!-- Sent from Reviewable.io -->

2024-10-14 04:20 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @varex83)

___
*[`crates/blockifier/feature_contracts/cairo_native/test_contract.cairo` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93jcc17DxyFgLopv3i:-O98DI0-5OXx-m5OYVPO:b-2ioivu) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/feature_contracts/cairo_native/test_contract.cairo#L35)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This contract is almost identical to the test contract of the Casm contract class. Can we add the new functions to the existing contract to avoid duplication?
</blockquote></details>

It is meant to be the same. Duplication is not intentional but the easiest way to integrate it into your current project structure.

Not doing it like this requires some greater changes in your testing architecture that span more creates than just the blockifier. We wanted to discuss this with you in the meantime.

@varex83 could you please add a comment explaining the problem in more detail.
___
*[`crates/blockifier/src/test_utils.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93wpyO6HNmUICVLokU:-O98DvNJ597RsBlDFBqg:b70wyma) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/src/test_utils.rs#L63)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why did you add Native? Isn't the Native Cairo version Cairo1? Maybe we should change the Cario1 to Casm? This is a bit confusing because this enum no longer represents the Cairo version.  I think we should create a new enum for the different compilations WDYT?
</blockquote></details>

I personally agree. I also think it should take it's own PR because even if very simple a lot of code is going to be changed as a result which might make it deserving.
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93vqXyBh9Ga_qa5diS:-O98EIqJ0M_93YgmU478:boz6wpv) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/src/test_utils/cairo_compile.rs#L151)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Can you make cairo1_compile use this function to avoid this duplication
</blockquote></details>

Yes, @varex83 could you please address this.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93yydRB2dXIAT0NRCN:-O98EUqHDfZ7NNgO8NaE:be1c6ed) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L68)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I can't entirely agree with this. Native contracts are still Cairo1 contracts. I don't see why they need a new directory.
</blockquote></details>

I don't agree either. It's a matter of compatibility and an issue that spans other crates beyond the blockifier.

We don't want to risk fixing it the "right" way for us fearing it might be too opinionated and you guys understand your project better than us.


<!-- Sent from Reviewable.io -->

2024-10-14 10:18 UTC, varex83 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @meship-starkware, @rodrigo-pino, and @varex83)

___
*[`crates/blockifier/feature_contracts/cairo_native/test_contract.cairo` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93jcc17DxyFgLopv3i:-O99Vmj30utbSiZO9WW4:b7uc8iw) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/feature_contracts/cairo_native/test_contract.cairo#L35)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

It is meant to be the same. Duplication is not intentional but the easiest way to integrate it into your current project structure.

Not doing it like this requires some greater changes in your testing architecture that span more creates than just the blockifier. We wanted to discuss this with you in the meantime.

@varex83 could you please add a comment explaining the problem in more detail.
</blockquote></details>

I agree that duplication in projects is the number one thing to avoid. We made a PR in that way because it integrates into your codebase in the best way. So, if we put these "Native" contracts into the "cairo1" folder, we will need to generate all other artifacts for contracts not being used for native testing.  I've managed to fix it in our fork, but we still made a PR with previous changes since we weren't sure about what solution you'd prefer, please take a look into this PR, to see what I mean: https://github.com/NethermindEth/sequencer/pull/29
___
*[`crates/blockifier/src/test_utils.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93wpyO6HNmUICVLokU:-O99WtHvE6uKdwe1V6pR:b-rlsdfz) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/src/test_utils.rs#L63)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

I personally agree. I also think it should take it's own PR because even if very simple a lot of code is going to be changed as a result which might make it deserving.
</blockquote></details>

Yes, I agree with Rodrigo, these changes are better to make in the separate PR, they will be small, and easy to review, so we can refactor without any conflicts.

I propose to rename Cairo1 -> Casm and Native -> Sierra
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93vqXyBh9Ga_qa5diS:-O99X6k-BGNhtYMpEPcu:bebrt1w) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/src/test_utils/cairo_compile.rs#L151)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Yes, @varex83 could you please address this.
</blockquote></details>

Will do
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93yydRB2dXIAT0NRCN:-O99X9I_1z2ds3p-Il6G:b-bang1d) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L68)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

I don't agree either. It's a matter of compatibility and an issue that spans other crates beyond the blockifier.

We don't want to risk fixing it the "right" way for us fearing it might be too opinionated and you guys understand your project better than us.
</blockquote></details>

Answered above.


<!-- Sent from Reviewable.io -->

2024-10-14 12:41 UTC, meship-starkware reviewed
> Reviewed 4 of 7 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @varex83)

___
*[`crates/blockifier/feature_contracts/cairo_native/test_contract.cairo` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93jcc17DxyFgLopv3i:-O9A-p_n8fzHt65vGJNp:bfkcwxb) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/feature_contracts/cairo_native/test_contract.cairo#L35)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

I agree that duplication in projects is the number one thing to avoid. We made a PR in that way because it integrates into your codebase in the best way. So, if we put these "Native" contracts into the "cairo1" folder, we will need to generate all other artifacts for contracts not being used for native testing.  I've managed to fix it in our fork, but we still made a PR with previous changes since we weren't sure about what solution you'd prefer, please take a look into this PR, to see what I mean: https://github.com/NethermindEth/sequencer/pull/29
</blockquote></details>

I liked the second solution with the subdirectories @noaov1 @avi-starkware WDYT?  
___
*[`crates/blockifier/src/test_utils.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93wpyO6HNmUICVLokU:-O9A0T0SAtSkgzQJlzm1:b-8froxg) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/src/test_utils.rs#L63)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Yes, I agree with Rodrigo, these changes are better to make in the separate PR, they will be small, and easy to review, so we can refactor without any conflicts.

I propose to rename Cairo1 -> Casm and Native -> Sierra
</blockquote></details>

I agree it should be in a separate PR. 


<!-- Sent from Reviewable.io -->

2024-10-16 00:54 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @varex83)

___
*[`crates/blockifier/feature_contracts/cairo_native/test_contract.cairo` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93jcc17DxyFgLopv3i:-O9Hld6N0Vm6VyurHRWl:b-f9tcum) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/feature_contracts/cairo_native/test_contract.cairo#L35)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I liked the second solution with the subdirectories @noaov1 @avi-starkware WDYT?
</blockquote></details>

Discussed this with Noa. We agreed to allow the duplication in this instance and then change the infrastructure to a solution without it (such as individual subdirs for compilation artifacts). 

This will allow us to continue working on the issue while advancing on the Syscall PRs as well


<!-- Sent from Reviewable.io -->

2024-10-16 00:56 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @varex83)

___
*[`crates/blockifier/feature_contracts/cairo_native/test_contract.cairo` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93jcc17DxyFgLopv3i:-O9HobQ5Ax4oWsZrOTj4:b-gg1u0h) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/feature_contracts/cairo_native/test_contract.cairo#L35)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Discussed this with Noa. We agreed to allow the duplication in this instance and then change the infrastructure to a solution without it (such as individual subdirs for compilation artifacts). 

This will allow us to continue working on the issue while advancing on the Syscall PRs as well
</blockquote></details>

It was not my intention to resolve this conversation :facepalm: 


<!-- Sent from Reviewable.io -->

2024-10-21 10:41 UTC, avi-starkware requested changes
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @meship-starkware, @rodrigo-pino, and @varex83)

___
*[`.gitignore` line 42 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O9i_CMJBhcavith384l:-O9i_CMJBhcavith384m:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/486de0cba4c19296725b8d2e8fa9f8cc0a5a5d79/.gitignore#L42)):*
> ```ignore
> 
> # Generated file used for running contracts compiled with Cairo Native
> libcairo_native_runtime.so
> ```





_Suggestion:_
```ignore
libcairo_native_runtime.a
```
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 142 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O9ibcspBB4ORCTnTMsd:-O9ibcspBB4ORCTnTMse:b7difma) ([raw file](https://github.com/starkware-libs/sequencer/blob/486de0cba4c19296725b8d2e8fa9f8cc0a5a5d79/crates/blockifier/src/test_utils/cairo_compile.rs#L142)):*
> ```XML
> }
> 
> pub fn sierra_compile(
> ```

If the function is called `sierra_compile`, the variable `sierra_compile_command` seems weird. Also `starknet-compile` is the name of the binary used in this function, so it fits.



_Suggestion:_
```XML
pub fn starknet_compile(
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 293 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O9ie8AA66pozPU06iCz:-O9ie8AA66pozPU06iD-:b-bcwyth) ([raw file](https://github.com/starkware-libs/sequencer/blob/486de0cba4c19296725b8d2e8fa9f8cc0a5a5d79/crates/blockifier/src/test_utils/struct_impls.rs#L293)):*
> ```XML
> 
>         Ok(Self::new(executor, sierra_contract_class))
>     }
> ```

Why not put this method in `contract_class.rs`?
(To be consistent with `ContractClassV0` and `ContractClassV1`)



_Code quote:_
```XML
    pub fn try_from_json_string(
        raw_contract_class: &str,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        // Compile the Sierra Program to native code and loads it into the process'
        // memory space.
        fn compile_and_load(
            sierra_program: &cairo_lang_sierra::program::Program,
        ) -> Result<AotNativeExecutor, cairo_native::error::Error> {
            let native_context = cairo_native::context::NativeContext::new();
            let native_program = native_context.compile(sierra_program, false)?;
            Ok(AotNativeExecutor::from_native_module(
                native_program,
                cairo_native::OptLevel::Default,
            ))
        }

        let sierra_contract_class: cairo_lang_starknet_classes::contract_class::ContractClass =
            serde_json::from_str(raw_contract_class)?;

        let sierra_program = sierra_contract_class.extract_sierra_program()?;
        let executor = compile_and_load(&sierra_program)?;

        Ok(Self::new(executor, sierra_contract_class))
    }
```


<!-- Sent from Reviewable.io -->

2024-10-24 11:51 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @varex83)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 142 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O9ibcspBB4ORCTnTMsd:-O9yLS271bhitFVJePXU:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/486de0cba4c19296725b8d2e8fa9f8cc0a5a5d79/crates/blockifier/src/test_utils/cairo_compile.rs#L142)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

If the function is called `sierra_compile`, the variable `sierra_compile_command` seems weird. Also `starknet-compile` is the name of the binary used in this function, so it fits.
</blockquote></details>

Done
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 293 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O9ie8AA66pozPU06iCz:-O9ihIU88-KPa9wH8Igd:b-g4cg9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/486de0cba4c19296725b8d2e8fa9f8cc0a5a5d79/crates/blockifier/src/test_utils/struct_impls.rs#L293)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why not put this method in `contract_class.rs`?
(To be consistent with `ContractClassV0` and `ContractClassV1`)
</blockquote></details>

Native contracts have no JSON format like CASM or Sierra. They are instead a binary 


<!-- Sent from Reviewable.io -->

2024-10-27 22:18 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @varex83)

___
*[`.gitignore` line 42 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O9i_CMJBhcavith384l:-OAF2kqm1eClLft2axpZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/486de0cba4c19296725b8d2e8fa9f8cc0a5a5d79/.gitignore#L42)):*
> ```ignore
> 
> # Generated file used for running contracts compiled with Cairo Native
> libcairo_native_runtime.so
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-30 15:18 UTC, meship-starkware reviewed
> Reviewed 6 of 7 files at r31, 2 of 2 files at r35, 2 of 2 files at r37, 8 of 8 files at r38, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @noaov1, and @varex83)



<!-- Sent from Reviewable.io -->

2024-10-30 22:18 UTC, meship-starkware reviewed
> Reviewed 2 of 2 files at r40, 1 of 1 files at r42, 7 of 8 files at r43, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 17 of 18 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @noaov1, and @varex83)



<!-- Sent from Reviewable.io -->

2024-10-30 22:20 UTC, meship-starkware reviewed
> Reviewed 1 of 8 files at r43.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @noaov1, and @varex83)



<!-- Sent from Reviewable.io -->

2024-11-03 18:32 UTC, avi-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r45, 1 of 1 files at r47, 8 of 8 files at r48, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-:-OAnIHeGD2kw8SENNLEn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)



<!-- Sent from Reviewable.io -->

2024-11-05 08:48 UTC, meship-starkware approved these changes
> Reviewed 2 of 2 files at r45, 1 of 1 files at r47, 8 of 8 files at r48, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)



<!-- Sent from Reviewable.io -->

2024-11-05 12:58 UTC, noaov1 requested changes
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 2 unresolved discussions (waiting on @rodrigo-pino and @varex83)

___
*[`crates/blockifier/src/test_utils.rs` line 69 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OAwNwrt8cXnWc50E3Jm:-OAwNwrt8cXnWc50E3Jn:bpm6nni) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils.rs#L69)):*
> ```XML
>     #[cfg(feature = "cairo_native")]
>     Native,
> }
> ```

IIUC we only interested in a native version of the test contract. If so, you might want to consider defining an enum as [CompilerBasedVersion](https://github.com/starkware-libs/sequencer/commit/f9bf674e220d2cc0b93c1fc42b094f22feabb99b).
WDYT? I think it's cleaner.
In this case, can you avoid duplicating the test contract?



_Code quote:_
```XML
pub enum CairoVersion {
    Cairo0,
    Cairo1,
    #[cfg(feature = "cairo_native")]
    Native,
}
```


<!-- Sent from Reviewable.io -->

2024-11-06 06:49 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/test_utils.rs` line 69 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OAwNwrt8cXnWc50E3Jm:-OB-DKvFCCAoTsRnQlY3:b-41qqk8) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils.rs#L69)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Never mind. I think we may also need it for the account contract.
</blockquote></details>

There is a PR that avoids the need for duplication. See this https://github.com/starkware-libs/sequencer/pull/1455
the solution is to have a directory for the contracts and sub-directories for the compiled_contract 


<!-- Sent from Reviewable.io -->

2024-11-06 08:26 UTC, noaov1 requested changes
> Reviewed 6 of 7 files at r31, 1 of 2 files at r37, 2 of 2 files at r45, 1 of 1 files at r47, 8 of 8 files at r48.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 8 unresolved discussions (waiting on @rodrigo-pino and @varex83)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 125 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-T9RQCzzQRQaOc5Z2:-OB-T9RQCzzQRQaOc5Z3:bd8wx2q) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/cairo_compile.rs#L125)):*
> ```XML
>     if let Some(ref nightly_version) = cargo_nightly_arg {
>         base_compile_args.insert(0, format!("+nightly-{nightly_version}"));
>     }
> ```

Can be removed, no?



_Code quote:_
```XML
    // Command args common to both compilation phases.
    let mut base_compile_args = vec![
        "run".into(),
        format!("--manifest-path={}/Cargo.toml", cairo1_compiler_path.to_string_lossy()),
        "--bin".into(),
    ];
    // Add additional cargo arg if provided. Should be first arg (base command is `cargo`).
    if let Some(ref nightly_version) = cargo_nightly_arg {
        base_compile_args.insert(0, format!("+nightly-{nightly_version}"));
    }
```
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 142 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-Tj4nA03qV59njBeE:-OB-Tj4nA03qV59njBeF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/cairo_compile.rs#L142)):*
> ```XML
> }
> 
> pub fn starknet_compile(
> ```





_Suggestion:_
```XML
/// Compile cairo1 -> Sierra.
pub fn starknet_compile(
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 262 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-WEGh1NUtC_wPPyEh:-OB-WEGiDplNhzG88xrn:b-x7feki) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/struct_impls.rs#L262)):*
> ```XML
>     pub fn try_from_json_string(
>         raw_contract_class: &str,
>     ) -> Result<Self, Box<dyn std::error::Error>> {
> ```

Why do we need a result in test utils? I think that you can use `unwrap`.



_Code quote:_
```XML
) -> Result<Self, Box<dyn std::error::Error>> {
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 268 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-Ygw4CHQM4P0YhPJd:-OB-Ygw4CHQM4P0YhPJe:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/struct_impls.rs#L268)):*
> ```XML
>             sierra_program: &cairo_lang_sierra::program::Program,
>         ) -> Result<AotNativeExecutor, cairo_native::error::Error> {
>             let native_context = cairo_native::context::NativeContext::new();
> ```





_Suggestion:_
```XML
// Create a Cairo Native MLIR context. This structure handles MLIR initialization
// and compiles Sierra programs into an MLIR module.
let native_context = cairo_native::context::NativeContext::new();
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 269 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-Z7-e9Z7ZUl9obua0:-OB-Z7-f-VDm-83r3ieb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/struct_impls.rs#L269)):*
> ```XML
>         ) -> Result<AotNativeExecutor, cairo_native::error::Error> {
>             let native_context = cairo_native::context::NativeContext::new();
>             let native_program = native_context.compile(sierra_program, false)?;
> ```





_Suggestion:_
```XML
            // Compile the sierra program into a MLIR module.
            let native_program = native_context.compile(sierra_program, false)?;
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 292 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-_0IwCL3rHTxFfRm5:-OB-_0IxBRz5rT-0aNfD:brm6o9u) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/struct_impls.rs#L292)):*
> ```XML
>         Self::try_from_json_string(&raw_contract_class).unwrap()
>     }
> }
> ```

When is it used?



_Code quote:_
```XML
    pub fn from_file(contract_path: &str) -> Self {
        let raw_contract_class = get_raw_contract_class(contract_path);
        Self::try_from_json_string(&raw_contract_class).unwrap()
    }
}
```
___
*[`crates/tests-integration/Cargo.toml` line 12 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-_5hQBjFBcB_uLj-V:-OB-_5hQBjFBcB_uLj-W:bad60e9) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/tests-integration/Cargo.toml#L12)):*
> ```TOML
> 
> [features]
> cairo_native = ["blockifier/cairo_native"]
> ```

Is this necessary?



_Code quote:_
```TOML
[features]
cairo_native = ["blockifier/cairo_native"]
```


<!-- Sent from Reviewable.io -->

2024-11-06 11:13 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 12 unresolved discussions (waiting on @rodrigo-pino and @varex83)

___
*[`crates/blockifier/src/test_utils.rs` line 96 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-dVL-3RLs1_cQKvib:-OB-dVL-3RLs1_cQKvic:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils.rs#L96)):*
> ```XML
>             Self::Cairo1 => Self::Cairo0,
>             #[cfg(feature = "cairo_native")]
>             Self::Native => todo!("who should be your other?"),
> ```





_Suggestion:_
```XML
            #[cfg(feature = "cairo_native")]
            Self::Native => panic!("There is no other version for native."),
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 249 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-eTDe2K2vPR24lw8D:-OB-eTDe2K2vPR24lw8E:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/execution/stack_trace_test.rs#L249)):*
> ```XML
>         CairoVersion::Cairo1 => expected_trace_cairo1,
>         #[cfg(feature = "cairo_native")]
>         CairoVersion::Native => panic!("Cairo Native contracts are not supported"),
> ```

?



_Suggestion:_
```XML
todo!("Cairo Native is not yet supported")
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 256 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-fENw16XdZAwTrStj:-OB-fENw16XdZAwTrStk:b-6b914u) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/contracts.rs#L256)):*
> ```XML
>                 CairoVersion::Cairo1 => ERC20_CAIRO1_CONTRACT_SOURCE_PATH,
>                 #[cfg(feature = "cairo_native")]
>                 CairoVersion::Native => todo!("ERC20 cannot be tested with Native"),
> ```

Why? Do you mean currently?



_Code quote:_
```XML
                CairoVersion::Native => todo!("ERC20 cannot be tested with Native"),
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 261 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-fi189XuuMv-NLEKv:-OB-fi189XuuMv-NLEKw:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/struct_impls.rs#L261)):*
> ```XML
>     /// If control over the compilation is desired use [Self::new] instead.
>     pub fn try_from_json_string(
>         raw_contract_class: &str,
> ```





_Suggestion:_
```XML
sierra_contract_class: &str,
```


<!-- Sent from Reviewable.io -->

2024-11-07 06:12 UTC, meship-starkware reviewed
> Reviewed 2 of 2 files at r50, 1 of 8 files at r53, 3 of 9 files at r54, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 13 of 24 files reviewed, 12 unresolved discussions (waiting on @avi-starkware, @noaov1, @rodrigo-pino, and @varex83)



<!-- Sent from Reviewable.io -->

2024-11-07 11:11 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 14 of 24 files reviewed, 13 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 256 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-fENw16XdZAwTrStj:-OB5ARMT0Z-lTJcqVduB:b-tk1ibq) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/contracts.rs#L256)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why? Do you mean currently?
</blockquote></details>

ERC20 only exists in Cairo Zero
___
*[`crates/starknet_api/src/contract_class.rs` line 32 at r54](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB4Eo149mo5mH7DcNyM:-OB5B1fI7Qt29cZB9v0p:b-5wiycx) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5cc8ec820b87ed6dcb90548e2eb364178d8b35d/crates/starknet_api/src/contract_class.rs#L32)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove. 
We will get the sierra later from the DB, and not via declare transaction.
Is removing it problematic?
</blockquote></details>

Yes, it is. This was what I mentioned about being problematic. We have to put there some definition NativeContractClass, I am not sure what does that NativeContractClass should have or what is enough. I'll think on what's best to put there


<!-- Sent from Reviewable.io -->

2024-11-07 13:00 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 14 of 24 files reviewed, 13 unresolved discussions (waiting on @avi-starkware, @noaov1, @rodrigo-pino, and @varex83)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 256 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-fENw16XdZAwTrStj:-OB5grQ8EXS3cW9b3lP2:bexi6ls) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/contracts.rs#L256)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

ERC20 only exists in Cairo Zero
</blockquote></details>

There is an ERC20 contract for Cairo1 as well. https://github.com/starkware-libs/sequencer/blob/35f5081bff460a7a578a2fe941a6c0a9698c9e71/crates/blockifier/ERC20/ERC20_Cairo1/ERC20_cairo1.cairo#L16


<!-- Sent from Reviewable.io -->

2024-11-07 13:49 UTC, avi-starkware reviewed
> Reviewed 11 of 11 files at r49, 1 of 8 files at r53, 1 of 9 files at r54.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 16 of 24 files reviewed, 13 unresolved discussions (waiting on @noaov1, @rodrigo-pino, and @varex83)



<!-- Sent from Reviewable.io -->

2024-11-07 15:02 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: 16 of 24 files reviewed, 11 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93vqXyBh9Ga_qa5diS:-OB68OG0-vqMDhSVlPyY:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/2139d8800e6e8650cd949556bcd0fd4827eb300a/crates/blockifier/src/test_utils/cairo_compile.rs#L151)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 125 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-T9RQCzzQRQaOc5Z2:-OB64HsQ6a_g_j3nJUXW:bck7fi8) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/cairo_compile.rs#L125)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can be removed, no?
</blockquote></details>

For calling the `starknet-sierra-compile` we need to re build the compiler args. I don't find a simple way of removing this code duplication
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 256 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-fENw16XdZAwTrStj:-OB65cXH5JBttcnKjf7H:b-8fx2u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/contracts.rs#L256)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

There is an ERC20 contract for Cairo1 as well. https://github.com/starkware-libs/sequencer/blob/35f5081bff460a7a578a2fe941a6c0a9698c9e71/crates/blockifier/ERC20/ERC20_Cairo1/ERC20_cairo1.cairo#L16
</blockquote></details>

:+1: 
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 261 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-fi189XuuMv-NLEKv:-OB66aRe7B4MNdjqYDPe:b-896fiz) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/struct_impls.rs#L261)):*
> ```XML
>     /// If control over the compilation is desired use [Self::new] instead.
>     pub fn try_from_json_string(
>         raw_contract_class: &str,
> ```

Done,
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 262 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-WEGh1NUtC_wPPyEh:-OB664Y91FC4-cTKotUR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/struct_impls.rs#L262)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why do we need a result in test utils? I think that you can use `unwrap`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 268 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-Ygw4CHQM4P0YhPJd:-OB68MhbApCOvtuh5FuO:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/struct_impls.rs#L268)):*
> ```XML
>             sierra_program: &cairo_lang_sierra::program::Program,
>         ) -> Result<AotNativeExecutor, cairo_native::error::Error> {
>             let native_context = cairo_native::context::NativeContext::new();
> ```

Done
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 269 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-Z7-e9Z7ZUl9obua0:-OB68M1H3ozvg-FI2-Ov:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/struct_impls.rs#L269)):*
> ```XML
>         ) -> Result<AotNativeExecutor, cairo_native::error::Error> {
>             let native_context = cairo_native::context::NativeContext::new();
>             let native_program = native_context.compile(sierra_program, false)?;
> ```

Done
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 292 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-_0IwCL3rHTxFfRm5:-OB66jRq9c2R7qBa4Ur-:b-z888eh) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/test_utils/struct_impls.rs#L292)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When is it used?
</blockquote></details>

For loading feature contracts
___
*[`crates/tests-integration/Cargo.toml` line 12 at r48](https://reviewable.io/reviews/starkware-libs/sequencer/1301#-OB-_5hQBjFBcB_uLj-V:-OB66o-lDLfYQiVrW1-w:bt6ybj8) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/tests-integration/Cargo.toml#L12)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

Integration depends on the blockifier and uses definitions that also involved Native. In this specific case it is only for Cairo Version


<!-- Sent from Reviewable.io -->

2024-11-07 15:16 UTC, avi-starkware approved these changes
> Reviewed 3 of 8 files at r53, 12 of 12 files at r56, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 11 unresolved discussions (waiting on @meship-starkware, @noaov1, @rodrigo-pino, and @varex83)



<!-- Sent from Reviewable.io -->

2024-11-10 06:44 UTC, noaov1 approved these changes
> Reviewed 3 of 8 files at r53, 9 of 12 files at r56, 2 of 2 files at r57, 10 of 10 files at r58, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)



<!-- Sent from Reviewable.io -->

2024-11-10 06:46 UTC, noaov1 approved these changes
> Dismissed @varex83 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1301)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)



<!-- Sent from Reviewable.io -->

2024-11-10 06:46 UTC, merged