feat(blockifier): add read and write syscalls
starkware-libs/sequencer pull request #1305
Opened 2024-10-10 14:40 UTC by rodrigo-pino

Add the read and write syscalls to the `NativeSyscallHandler`.

Open for you to see and react. Notice that Cairo Native dependency has changed, this is because I had to update that relative paths are solved in order for it to detect the Runtime based on the `.cargo/config.toml` file. 

Looking forward to your feedback.

2024-10-13 08:57 UTC, meship-starkware reviewed
> Reviewed 3 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @rodrigo-pino)

___
*[`scripts/dependencies.sh` line 79 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O944kqa1gPOqn5Aubq4:-O944kqa1gPOqn5Aubq5:bb76mu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/scripts/dependencies.sh#L79)):*
> ```Shell
> function main() {
>     # [ "$(uname)" = "Linux" ] && install_essential_deps_linux
>     # setup_llvm_deps
> ```

Why?



_Code quote:_
```Shell
    # [ "$(uname)" = "Linux" ] && install_essential_deps_linux
    # setup_llvm_deps
```


<!-- Sent from Reviewable.io -->

2024-10-13 19:05 UTC, avi-starkware requested changes
> Reviewed 3 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @meship-starkware and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 187 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96DKxg8hujhI30bj9C:-O96DKxg8hujhI30bj9D:b8b25vt) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L187)):*
> ```XML
>         let key = StorageKey(
>             PatriciaKey::try_from(address).map_err(|e| encode_str_as_felts(&e.to_string()))?,
>         );
> ```

Why not?



_Suggestion:_
```XML
        let key = StorageKey::try_from(address).map_err(|e| encode_str_as_felts(&e.to_string()))?;
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-O96F70GASwm5B06IRKM:boa2vva) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
> ```XML
> 
>         let read_result = self.state.get_storage_at(self.contract_address, key);
>         let value = read_result.map_err(|e| encode_str_as_felts(&e.to_string()))?;
> ```

We don't do this error encoding in our current syscall handler. Are you sure we can't just use `?` here?



_Suggestion:_
```XML
        self.state.get_storage_at(self.contract_address, key)?;
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 212 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96DZuZDVYeMF51GBm-:-O96DZuZDVYeMF51GBm0:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L212)):*
> ```XML
>         let key = StorageKey(
>             PatriciaKey::try_from(address).map_err(|e| encode_str_as_felts(&e.to_string()))?,
>         );
> ```





_Suggestion:_
```XML
        let key = StorageKey::try_from(address).map_err(|e| encode_str_as_felts(&e.to_string()))?;
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 216 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96G4ry7cn-U7JSszqW:-O96G4ry7cn-U7JSszqX:b-logaup) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L216)):*
> ```XML
> 
>         let write_result = self.state.set_storage_at(self.contract_address, key, value);
>         write_result.map_err(|e| encode_str_as_felts(&e.to_string()))?;
> ```

as suggested above
can this work?



_Suggestion:_
```XML
        self.state.set_storage_at(self.contract_address, key, value)?;
```


<!-- Sent from Reviewable.io -->

2024-10-13 19:07 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 8 of 9 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @rodrigo-pino)

___
*[`Cargo.toml` line 100 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96GVP46BIWpUvbVs8C:-O96GVP46BIWpUvbVs8D:bb76mu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/Cargo.toml#L100)):*
> ```TOML
> cairo-lang-utils = "2.8.2"
> # cairo-native = "0.2.0-alpha.2"
> cairo-native = { git = "https://github.com/NethermindEth/cairo_native", branch = "rdr/resolve-runtime-library-path-2.8.2" }
> ```

Why?



_Code quote:_
```TOML
# cairo-native = "0.2.0-alpha.2"
cairo-native = { git = "https://github.com/NethermindEth/cairo_native", branch = "rdr/resolve-runtime-library-path-2.8.2" }
```
___
*[`.cargo/config.toml` line 2 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96GXaC-RKjdnW3DBn8:-O96GXaC-RKjdnW3DBn9:b2ma2dy) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/.cargo/config.toml#L2)):*
> ```TOML
> [env]
> CAIRO_NATIVE_RUNTIME_LIBRARY = "libcairo_native_runtime.a"
> ```

Please make this change in #1242



_Code quote:_
```TOML
CAIRO_NATIVE_RUNTIME_LIBRARY = "libcairo_native_runtime.a"
```


<!-- Sent from Reviewable.io -->

2024-10-14 04:42 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 2 of 9 files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`Cargo.toml` line 100 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96GVP46BIWpUvbVs8C:-O98HAcF2t85Tbu3-M6Z:b-eourtt) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/Cargo.toml#L100)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Required to correctly solve `CAIRO_NATIVE_RUNTIME_LIBRARY` otherwise we cannot use the `.cargo/config.toml` solution.
___
*[`.cargo/config.toml` line 2 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96GXaC-RKjdnW3DBn8:-O98HOg43yBbe_DW3Vgo:b-896fja) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/.cargo/config.toml#L2)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Please make this change in #1242
</blockquote></details>

Done!
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 187 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96DKxg8hujhI30bj9C:-O98J840AFwHNSGPwVmL:b-cmt4a6) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L187)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

Done! Thanks!
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-O98HuPj9vqzyuTrKXQj:bsitgge) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

We don't do this error encoding in our current syscall handler. Are you sure we can't just use `?` here?
</blockquote></details>

You return a `StateError` which Native doesn't understand.

Cairo 1 (through Native) is expecting a SyscallResult<T>, Cairo1/Sierra doesn't understand what a `StateError` is. What we do is that we propagate the error back by encoding the `StateError` message as a bunch of Felts and return control to the Contract.

Take into account that each time we are executing a contract we treat it as a black box. Each syscall is a request to the blockifier using the communication protocol established by the `StarknetSyscallHandler` trait.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 212 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96DZuZDVYeMF51GBm-:-O98JU7_AdEpUEpvy4_w:b-896fja) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L212)):*
> ```XML
>         let key = StorageKey(
>             PatriciaKey::try_from(address).map_err(|e| encode_str_as_felts(&e.to_string()))?,
>         );
> ```

Done!
___
*[`scripts/dependencies.sh` line 79 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O944kqa1gPOqn5Aubq4:-O98KMMQ6-XoByM6A01B:b-67yfl3) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/scripts/dependencies.sh#L79)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

It wasn't intentional


<!-- Sent from Reviewable.io -->

2024-10-14 06:18 UTC, meship-starkware reviewed
> Reviewed 2 of 6 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @rodrigo-pino)



<!-- Sent from Reviewable.io -->

2024-10-21 10:15 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 5 of 29 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @rodrigo-pino)

___
*[`Cargo.toml` line 100 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96GVP46BIWpUvbVs8C:-O9iZ8AZEWZ9wbRAx02Y:b-gafq83) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/Cargo.toml#L100)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Required to correctly solve `CAIRO_NATIVE_RUNTIME_LIBRARY` otherwise we cannot use the `.cargo/config.toml` solution.
</blockquote></details>

Can you please explain further?
Aren't cloning the lambdaclass repo to generate the `libcairo_native_runtime.a` in `dependencies.sh`?
Where is your fork necessary?
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-O9i5MpE9XFgTP1EjNwj:b-kj4oxx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

You return a `StateError` which Native doesn't understand.

Cairo 1 (through Native) is expecting a SyscallResult<T>, Cairo1/Sierra doesn't understand what a `StateError` is. What we do is that we propagate the error back by encoding the `StateError` message as a bunch of Felts and return control to the Contract.

Take into account that each time we are executing a contract we treat it as a black box. Each syscall is a request to the blockifier using the communication protocol established by the `StarknetSyscallHandler` trait.
</blockquote></details>

Okay I understand.

Would it be possible to add an `encode_as_felts` method to the StateError struct to avoid code duplication?
Non-blocking.
___
*[`scripts/dependencies.sh` line 74 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O9i7ig70Wfi9we3QekL:-O9i7ig70Wfi9we3QekM:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2812ca090271058de0352baedd101539f3e0e961/scripts/dependencies.sh#L74)):*
> ```Shell
>     popd || exit 1
> 
>     mv ./cairo_native/target/release/libcairo_native_runtime.a ${LIBCAIRO_NATIVE_DIR}/libcairo_native_runtime.a
> ```





_Suggestion:_
```Shell
 mv ./cairo_native/target/release/libcairo_native_runtime.a ${TARGET_LIB_DIR}/libcairo_native_runtime.a
```


<!-- Sent from Reviewable.io -->

2024-10-22 05:54 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-O9mm6TH7oIpCMi5cJnN:b1g0i8r) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Okay I understand.

Would it be possible to add an `encode_as_felts` method to the StateError struct to avoid code duplication?
Non-blocking.
</blockquote></details>

Only `SyscallError` should be returned to the native code as felts.

If we get a StateError we want to stop the execution of the Native code and return to the blockifier, is there a way to do that?


<!-- Sent from Reviewable.io -->

2024-10-22 06:57 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-O9mz5rc353DEJ3wmnkB:b-yjsxma) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Only `SyscallError` should be returned to the native code as felts.

If we get a StateError we want to stop the execution of the Native code and return to the blockifier, is there a way to do that?
</blockquote></details>

I agree. And to be more specific: only `SyscallExecutionError::SyscallError` is returned to the native code as felts and sets the failure flag. See [here](https://github.com/starkware-libs/sequencer/blob/a2ddc1a16dc0d3959cf7cf33ef07831057624f30/crates/blockifier/src/execution/syscalls/hint_processor.rs#L528) and [here](https://github.com/starkware-libs/sequencer/blob/a2ddc1a16dc0d3959cf7cf33ef07831057624f30/crates/blockifier/src/execution/syscalls/hint_processor.rs#L528).


<!-- Sent from Reviewable.io -->

2024-10-27 11:39 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-O9yP70Y23zcZtapkE8O:btahy90) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I agree. And to be more specific: only `SyscallExecutionError::SyscallError` is returned to the native code as felts and sets the failure flag. See [here](https://github.com/starkware-libs/sequencer/blob/a2ddc1a16dc0d3959cf7cf33ef07831057624f30/crates/blockifier/src/execution/syscalls/hint_processor.rs#L528) and [here](https://github.com/starkware-libs/sequencer/blob/a2ddc1a16dc0d3959cf7cf33ef07831057624f30/crates/blockifier/src/execution/syscalls/hint_processor.rs#L528).
</blockquote></details>

In my head there are two possible temporal solutions.

1. We can just panic (I prefer this one). Not ideal because we panic but good enough for the meantime?

2.  We can keep track of any error different than a SyscallError and when Native returns control the final time, do the same behavior as the blockifier. Not ideal because we don't stop execution right at the moment and we have to wait for everything  to be executed right to the very end.
___
*[`Cargo.toml` line 100 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96GVP46BIWpUvbVs8C:-O9v7qKYAKQsMOVXL0hD:b-9f987o) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/Cargo.toml#L100)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Can you please explain further?
Aren't cloning the lambdaclass repo to generate the `libcairo_native_runtime.a` in `dependencies.sh`?
Where is your fork necessary?
</blockquote></details>

So we want to define all runtime Variables in `config/cargo.toml`, MLIR variables are system fixed and because all of you are using Ubuntu we can set an absolute path.

The runtime can be anywhere since it is not installed. It has to be either compiled or download it. Project wise we always were is going to be located but the project is located at different locations depending if it is a developer, docker or a github runner. 

To do this the runtime has to have a relative path pointing somewhere inside the project. In that fork (which is not meant to be part of the final look of the PR) 


<!-- Sent from Reviewable.io -->

2024-10-28 06:16 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-OAGjodj2gkZ85ol7m1e:b1iyy1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

In my head there are two possible temporal solutions.

1. We can just panic (I prefer this one). Not ideal because we panic but good enough for the meantime?

2.  We can keep track of any error different than a SyscallError and when Native returns control the final time, do the same behavior as the blockifier. Not ideal because we don't stop execution right at the moment and we have to wait for everything  to be executed right to the very end.
</blockquote></details>

1. We should avoid panicking since there may be errors where it's preferable to fail the transaction rather than halt the entire execution. Currently, there are a few such cases (e.g., undeclared class) that we aim to convert into provable errors, though errors in a Cairo0 contract execution should still remain as they are (thanks @ilyalesokhin-starkware for pointing it out).
2. Yes, we need to assess the implications of adopting this approach (Aki mentioned a resource leak).


<!-- Sent from Reviewable.io -->

2024-10-30 21:14 UTC, meship-starkware reviewed
> Reviewed 1 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 28 of 29 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, and @rodrigo-pino)



<!-- Sent from Reviewable.io -->

2024-10-30 22:16 UTC, meship-starkware reviewed
> Reviewed 1 of 2 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, and @rodrigo-pino)



<!-- Sent from Reviewable.io -->

2024-11-01 12:22 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-OAbfA7g7vMdz1s-a5Nd:bu4aec) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

1. We should avoid panicking since there may be errors where it's preferable to fail the transaction rather than halt the entire execution. Currently, there are a few such cases (e.g., undeclared class) that we aim to convert into provable errors, though errors in a Cairo0 contract execution should still remain as they are (thanks @ilyalesokhin-starkware for pointing it out).
2. Yes, we need to assess the implications of adopting this approach (Aki mentioned a resource leak).
</blockquote></details>

What do we do in the meantime?
___
*[`scripts/dependencies.sh` line 74 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O9i7ig70Wfi9we3QekL:-OAbf4Pu04C0E1lMw7rY:btdbqyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/2812ca090271058de0352baedd101539f3e0e961/scripts/dependencies.sh#L74)):*
> ```Shell
>     popd || exit 1
> 
>     mv ./cairo_native/target/release/libcairo_native_runtime.a ${LIBCAIRO_NATIVE_DIR}/libcairo_native_runtime.a
> ```

No longer relevant


<!-- Sent from Reviewable.io -->

2024-11-05 14:14 UTC, noaov1 requested changes
> Reviewed 1 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-OAwLits7u8cgaTlJ7_5:b-kopdzm) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

What do we do in the meantime?
</blockquote></details>

We can leave it as is or use `unwrap`. 
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 195 at r20](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-OAwe_He1fq_yYqG9BKg:-OAwe_He1fq_yYqG9BKh:b-v6zah9) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d4f0d37e89afac2a2f0d23cfd0521c4eb1e4451/crates/blockifier/src/execution/native/syscall_handler.rs#L195)):*
> ```XML
>             self.context.gas_costs().storage_read_gas_cost,
>         )?;
> ```

What about address domain? See [here](https://github.com/starkware-libs/sequencer/blob/8823d312e735077259a677be3f301930a4e95e66/crates/blockifier/src/execution/syscalls/mod.rs#L575)


<!-- Sent from Reviewable.io -->

2024-11-06 13:35 UTC, noaov1 requested changes
> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-OB0cX6e1NiKFqRRoYLW:bjrbwsj) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We can leave it as is or use `unwrap`.
</blockquote></details>

Leave it as is. 
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 209 at r20](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-OB0fDUp3ALwCUPeLZ-f:-OB0fDUp3ALwCUPeLZ-g:bxibdeb) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d4f0d37e89afac2a2f0d23cfd0521c4eb1e4451/crates/blockifier/src/execution/native/syscall_handler.rs#L209)):*
> ```XML
>     fn storage_write(
>         &mut self,
>         _address_domain: u32,
> ```

Please make sure it equals 0. See [here](https://github.com/starkware-libs/sequencer/blob/8823d312e735077259a677be3f301930a4e95e66/crates/blockifier/src/execution/syscalls/mod.rs#L617).



_Code quote:_
```XML
_address_domain: u32,
```


<!-- Sent from Reviewable.io -->

2024-11-06 14:05 UTC, avi-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @meship-starkware, and @rodrigo-pino)



<!-- Sent from Reviewable.io -->

2024-11-07 06:16 UTC, meship-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @rodrigo-pino)



<!-- Sent from Reviewable.io -->

2024-11-10 10:04 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL:-OBKWir33lc_spTBy5lV:b32w1t) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a139cdfc49061b3c795caf218ffe62593dbb20f/crates/blockifier/src/execution/native/syscall_handler.rs#L190)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Leave it as is.
</blockquote></details>

Ok
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 195 at r20](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-OAwe_He1fq_yYqG9BKg:-OBKWjDOB6qmc0a7Chm-:b-jyxqk1) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ed4dcc1def8406b06dc971bfb3b2a7babc735c2/crates/blockifier/src/execution/native/syscall_handler.rs#L195)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What about address domain? See [here](https://github.com/starkware-libs/sequencer/blob/8823d312e735077259a677be3f301930a4e95e66/crates/blockifier/src/execution/syscalls/mod.rs#L575)
</blockquote></details>

Added check in read, let me know what you think
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 209 at r20](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-OB0fDUp3ALwCUPeLZ-f:-OBKWnW69krBgfSZrzQ6:bm1eoqd) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ed4dcc1def8406b06dc971bfb3b2a7babc735c2/crates/blockifier/src/execution/native/syscall_handler.rs#L209)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please make sure it equals 0. See [here](https://github.com/starkware-libs/sequencer/blob/8823d312e735077259a677be3f301930a4e95e66/crates/blockifier/src/execution/syscalls/mod.rs#L617).
</blockquote></details>

Added check in write too


<!-- Sent from Reviewable.io -->

2024-11-10 13:07 UTC, meship-starkware approved these changes
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-10 13:32 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-11-11 07:13 UTC, meship-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-11-11 09:25 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-:-OBPXhhA-5WjlhnlnWLw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-11-11 09:26 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-11-11 11:03 UTC, meship-starkware approved these changes
> Reviewed 5 of 5 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @noaov1, and @rodrigo-pino)

___
*[`-- commits` line 5 at r24](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-OBPsowp3MFFgZyZbOBo:-OBPsowp3MFFgZyZbOBp:b85tbsq):*
Can you squash these two commits into one 



_Code quote:_
```
New commits in r22 on 11/11/2024 at 00:24, probably rebased from r21:
- 2fe81ff: feat(blockifier): add read & write syscalls

New commits in r24 (same as r22) on 11/11/2024 at 12:19:
- 2fe81ff: feat(blockifier): add read & write syscalls
```


<!-- Sent from Reviewable.io -->

2024-11-11 14:24 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 30 of 31 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @meship-starkware, and @noaov1)

___
*[`-- commits` line 5 at r24](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-OBPsowp3MFFgZyZbOBo:-OBQau4l1TNj0kXXfqs0:b-h2xlte):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Can you squash these two commits into one
</blockquote></details>

It is weird, in my log I just have one commit :thinking: , not sure how to fix this.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 202 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-OBPq-p-AIRFg9OWGXMy:-OBQb-uNBkOHVy4DaaaW:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/2fe81ff1a00b4f153bd042bbc8fdf1a877aa9d53/crates/blockifier/src/execution/native/syscall_handler.rs#L202)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you add a wrapper for unprovable errors?
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 101 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-OBQaWr_23aSgqBxTRkl:-OBQaWr_23aSgqBxTRkm:b-id01w3) ([raw file](https://github.com/starkware-libs/sequencer/blob/8313167f7fc2f27cbb8134361b0490e6474283e2/crates/blockifier/src/execution/native/syscall_handler.rs#L101)):*
> ```XML
>     }
> 
>     fn handle_error(
> ```

Defined inside the impl intentionally (`self` will be used in the error handling)


<!-- Sent from Reviewable.io -->

2024-11-11 14:54 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: 30 of 31 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`-- commits` line 5 at r24](https://reviewable.io/reviews/starkware-libs/sequencer/1305#-OBPsowp3MFFgZyZbOBo:-OBQhosd0uBZOlWERFs3:bghjzy3):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

It is weird, in my log I just have one commit :thinking: , not sure how to fix this.
</blockquote></details>

Then never mind, it will be squashed when merging 


<!-- Sent from Reviewable.io -->

2024-11-11 15:18 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-11-11 15:18 UTC, meship-starkware approved these changes
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1305)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @ilyalesokhin-starkware, and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-11 15:40 UTC, merged