chore(blockifier_reexecution): full blockifier reexecution poc
starkware-libs/sequencer pull request #1346
Opened 2024-10-13 06:44 UTC by aner-starkware

2024-10-15 13:29 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1346)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9FMZ7O5MloqJxiNdXR:-O9FMZ7O5MloqJxiNdXS:biokytv) (no related file):*
very cool!

___
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9FLRrm1CzGsGIsh2tm:-O9FLRrm1CzGsGIsh2tn:b-74im7m) ([raw file](https://github.com/starkware-libs/sequencer/blob/0280c5068f80e303ef24a2f3ebbedf7cd39cd157/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L115)):*
> ```XML
> ) {
>     let ConsecutiveTestStateReaders { ref next_block_state_reader, .. } =
>         test_state_readers_last_and_current_block;
> ```

destructuring isn't really useful when you only take one field



_Suggestion:_
```XML
    let next_block_state_reader =
        &test_state_readers_last_and_current_block.next_block_state_reader;
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9FLmOo4eNj22d2Fpt_:-O9FLmOo4eNj22d2Fpta:b-1chlv8) ([raw file](https://github.com/starkware-libs/sequencer/blob/0280c5068f80e303ef24a2f3ebbedf7cd39cd157/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L118)):*
> ```XML
>     // 1. Read txs via RPC, convert to blockifier txs
>     let all_txs = next_block_state_reader.get_all_txs_in_block().unwrap();
>     let all_txs = from_api_txs_to_blockifier_txs(all_txs).unwrap();
> ```

this is the *only* usage of `get_all_txs_in_block`; and you only need the blockifier type.
please change the return type of `get_all_txs_in_block` to return blockifier txs.

Also, `from_api_txs_to_blockifier_txs` is only used here as well, so please *inline* the logic inside `get_all_txs_in_block`. 



_Suggestion:_
```XML
    let all_txs = next_block_state_reader.get_all_txs_in_block().unwrap();
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9FLaaG054IbH4deCa6:-O9FLaaG054IbH4deCa7:bidsnnm) ([raw file](https://github.com/starkware-libs/sequencer/blob/0280c5068f80e303ef24a2f3ebbedf7cd39cd157/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L130)):*
> ```XML
>         transaction_executor.finalize().expect("Couldn't finalize block");
>     // 6. Compare results of (2) (expected) and (5) (actual)
>     // TODO(Aner): replace next line with computing the value and inserting to computed state diff
> ```

end comments with punctuation



_Suggestion:_
```XML
    // 1. Read txs via RPC, convert to blockifier txs.
    let all_txs = next_block_state_reader.get_all_txs_in_block().unwrap();
    let all_txs = from_api_txs_to_blockifier_txs(all_txs).unwrap();
    // 2. Read expected statediff via RPC.
    let mut expected_state_diff = next_block_state_reader.get_state_diff().unwrap();
    // 3. Create TransactionExecutor (Read block_header via RPC).
    let mut transaction_executor =
        test_state_readers_last_and_current_block.get_transaction_executor(None).unwrap();
    // 4. Run execute_txs on txs from (1).
    transaction_executor.execute_txs(all_txs.as_slice());
    // 5. Run finalize and read statediff.
    let (actual_state_diff, _, _) =
        transaction_executor.finalize().expect("Couldn't finalize block");
    // 6. Compare results of (2) (expected) and (5) (actual).
    // TODO(Aner): replace next line with computing the value and inserting to computed state diff.
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9FMQ2A4Cvm86sAHys3:-O9FMQ2A4Cvm86sAHys4:b-d93epw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0280c5068f80e303ef24a2f3ebbedf7cd39cd157/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L130)):*
> ```XML
>         transaction_executor.finalize().expect("Couldn't finalize block");
>     // 6. Compare results of (2) (expected) and (5) (actual)
>     // TODO(Aner): replace next line with computing the value and inserting to computed state diff
> ```

"the next line" can change :)



_Suggestion:_
```XML
compute the correct block hash at storage slot 0x1 instead of removing it
```


<!-- Sent from Reviewable.io -->

2024-10-16 08:38 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1346)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9FLRrm1CzGsGIsh2tm:-O9JSxhCAi6W_E9ldUr2:b7isaf2) ([raw file](https://github.com/starkware-libs/sequencer/blob/0280c5068f80e303ef24a2f3ebbedf7cd39cd157/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L115)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

destructuring isn't really useful when you only take one field
</blockquote></details>

Done. Took a slightly different approach.
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9FLmOo4eNj22d2Fpt_:-O9JT-MT0yzQP_3TX3th:b-niwxs1) ([raw file](https://github.com/starkware-libs/sequencer/blob/0280c5068f80e303ef24a2f3ebbedf7cd39cd157/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L118)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is the *only* usage of `get_all_txs_in_block`; and you only need the blockifier type.
please change the return type of `get_all_txs_in_block` to return blockifier txs.

Also, `from_api_txs_to_blockifier_txs` is only used here as well, so please *inline* the logic inside `get_all_txs_in_block`.
</blockquote></details>

I disagree here - there are several reasons to keep it this way (debugging, further development, etc.). However, I took this suggestion for the `ConsecutiveTestStateReaders`
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9FMQ2A4Cvm86sAHys3:-O9JNoR69zGm_QaKDVrn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0280c5068f80e303ef24a2f3ebbedf7cd39cd157/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L130)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

"the next line" can change :)
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9FLaaG054IbH4deCa6:-O9JSqMo0AfLw4SraX8S:b-13hjal) ([raw file](https://github.com/starkware-libs/sequencer/blob/0280c5068f80e303ef24a2f3ebbedf7cd39cd157/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L130)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

end comments with punctuation
</blockquote></details>

Done. Removed some redundant comments (clear from code).


<!-- Sent from Reviewable.io -->

2024-10-17 10:19 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1346)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9OyZUVCnNVJ8WZKzbK:-O9OyZUVCnNVJ8WZKzbL:b-rkmry9) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac2925d567d0a0c395ce3787c0855e888f1fa804/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L109)):*
> ```XML
> }
> 
> // TODO(Aner): remove test and add as CLI test
> ```

we will run this via command, right?
also, we will need to add a node URL as input to the CLI... out of scope for this PR but please rephrase the todo



_Suggestion:_
```XML
// TODO(Aner): remove test and add as CLI command.
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 270 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9OysAnBcDJBnNp8lPr:-O9OysAnBcDJBnNp8lPs:b48sigq) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac2925d567d0a0c395ce3787c0855e888f1fa804/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L270)):*
> ```XML
>     pub fn get_state_diff(&self) -> ReexecutionResult<CommitmentStateDiff> {
>         self.next_block_state_reader.get_state_diff()
>     }
> ```

these functions are a bit ambiguous - you have two blocks in this object, right? which block txs and which state diff?
please rename



_Suggestion:_
```XML
    pub fn get_next_block_txs(&self) -> ReexecutionResult<Vec<BlockifierTransaction>> {
        from_api_txs_to_blockifier_txs(self.next_block_state_reader.get_all_txs_in_block()?)
    }

    pub fn get_next_block_state_diff(&self) -> ReexecutionResult<CommitmentStateDiff> {
        self.next_block_state_reader.get_state_diff()
    }
```


<!-- Sent from Reviewable.io -->

2024-10-27 06:52 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1346)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9OyZUVCnNVJ8WZKzbK:-OA0bsgBE8n0b8vouSH3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac2925d567d0a0c395ce3787c0855e888f1fa804/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we will run this via command, right?
also, we will need to add a node URL as input to the CLI... out of scope for this PR but please rephrase the todo
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 270 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-O9OysAnBcDJBnNp8lPr:-OA0btM2-4fuX4tgTFed:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac2925d567d0a0c395ce3787c0855e888f1fa804/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L270)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these functions are a bit ambiguous - you have two blocks in this object, right? which block txs and which state diff?
please rename
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-27 09:15 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1346)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`Cargo.lock` line 0 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-OACFOZs8aBmPKfM8lxs:-OACFOZs8aBmPKfM8lxt:bm62j9a) ([raw file](https://github.com/starkware-libs/sequencer/blob/1764896d9ce604872d055130ae2c649fd8b8c70a/Cargo.lock#L0)):*
revert changes here, you made no change to `Cargo.toml`.
Did you run `cargo update` or something?


<!-- Sent from Reviewable.io -->

2024-10-27 09:22 UTC, aner-starkware commented
*[`Cargo.lock` line  at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-OACFOZs8aBmPKfM8lxs:-OACG2nV5bYvbNFLgN-I:b-l413b0) ([raw file](https://github.com/starkware-libs/sequencer/blob/1764896d9ce604872d055130ae2c649fd8b8c70a/Cargo.lock#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

revert changes here, you made no change to `Cargo.toml`.
Did you run `cargo update` or something?
</blockquote></details>

Yes, I also ran the entire script, then `cargo clean`.


<!-- Sent from Reviewable.io -->

2024-10-27 09:24 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1346#-:-OACHWvX6LQ9I1Q7UJ3g:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2024-10-27 12:24 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1346)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2024-10-27 12:37 UTC, merged