test(mempool): two queues test get txs
starkware-libs/sequencer pull request #1351
Opened 2024-10-13 09:44 UTC by MohammadNassar1

2024-10-13 15:50 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O95ZBQ5-h3Kvwc5nV8E:-O95ZBQ68Cv8DbqrBpY5:b-j13i8l) ([raw file](https://github.com/starkware-libs/sequencer/blob/a02402ade499b30b550550955f851ce616688dac/crates/mempool/src/transaction_queue_test_utils.rs#L4)):*
> ```XML
> 
> use pretty_assertions::assert_eq;
> use starknet_api::block::GasPrice;
> ```

Please do not review this file until the previous [PR](https://reviewable.io/reviews/starkware-libs/sequencer/1295) with this implementation is merged



_Code quote:_
```XML
use starknet_api::block::GasPrice;
```


<!-- Sent from Reviewable.io -->

2024-10-13 16:21 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O95f9Wo9YR3A5lRTepf:-O95f9Wo9YR3A5lRTepg:bwhsou5) (no related file):*
This PR tests the effect of two queues. It verifies the following:
- `get_txs` does not return transactions from pending queues.
- `get_txs` rewinds nonces and places them in the correct queue.

___


<!-- Sent from Reviewable.io -->

2024-10-14 06:44 UTC, ayeletstarkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O98knm723zceSf0d1YU:-O98knm723zceSf0d1YV:b4wunp0) ([raw file](https://github.com/starkware-libs/sequencer/blob/5308539e39fe0e9bf625d5c9a7acc0e21b78ca75/crates/mempool/src/mempool_test.rs#L239)):*
> ```XML
>         &mut mempool,
>         3,
>         &[priority_tx_address_0_nonce_0, priority_tx_address_1_nonce_0],
> ```

This test previously checked that the mempool replenishes the queue in `get_txs`, but it's no longer verified.



_Code quote:_
```XML
priority_tx_address_0_nonce_0, priority_tx_address_1_nonce_0
```


<!-- Sent from Reviewable.io -->

2024-10-14 09:02 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O98knm723zceSf0d1YU:-O99Ev6s2Mzn2L3g0e22:b-jfbdm9) ([raw file](https://github.com/starkware-libs/sequencer/blob/5308539e39fe0e9bf625d5c9a7acc0e21b78ca75/crates/mempool/src/mempool_test.rs#L239)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

This test previously checked that the mempool replenishes the queue in `get_txs`, but it's no longer verified.
</blockquote></details>

Following our discussion, the test still verifies that the mempool correctly replenishes the queue. This occurs for address zero, where after receiving a transaction with nonce 0, it adds a transaction with nonce 1 to the queue. 
This behavior is validated in the assertion below:



_Code snippet:_
```XML
._with_pending_queue([TransactionReference::new(&pending_tx_address_0_nonce_1)])
```


<!-- Sent from Reviewable.io -->

2024-10-14 10:27 UTC, ayeletstarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O99YqzjAwut2d9NVNZ9:-O99YqzkDu5_p_J1vOIY:b-lkko3k) ([raw file](https://github.com/starkware-libs/sequencer/blob/5308539e39fe0e9bf625d5c9a7acc0e21b78ca75/crates/mempool/src/mempool_test.rs#L209)):*
> ```XML
> fn test_get_txs_replenishes_queue_only_between_chunks() {
>     // Setup.
>     let priority_tx_address_0_nonce_0 = tx!(tip: 20, tx_hash: 1, sender_address: "0x0", tx_nonce: 0,
> ```

I think it's not necessary for this test



_Code quote:_
```XML
tip: 20
```
___
*[`crates/mempool/src/mempool_test.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O99YyZcBYYREtzu8Fbr:-O99YyZcBYYREtzu8Fbs:b4tgfo6) ([raw file](https://github.com/starkware-libs/sequencer/blob/5308539e39fe0e9bf625d5c9a7acc0e21b78ca75/crates/mempool/src/mempool_test.rs#L213)):*
> ```XML
>     let pending_tx_address_0_nonce_1 = tx!(tip: 20, tx_hash: 2, sender_address: "0x0", tx_nonce: 1,
>         max_l2_gas_price: 99);
>     let priority_tx_address_0_nonce_2 = tx!(tip: 20, tx_hash: 3, sender_address: "0x0", tx_nonce: 2,
> ```

remove or update `get_txs` to fetch 3 transactions



_Code quote:_
```XML
let priority_tx_address_0_nonce_2
```


<!-- Sent from Reviewable.io -->

2024-10-14 11:21 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O99YqzjAwut2d9NVNZ9:-O99eVOB9qUElh1aUZ-E:bogbnlx) ([raw file](https://github.com/starkware-libs/sequencer/blob/5308539e39fe0e9bf625d5c9a7acc0e21b78ca75/crates/mempool/src/mempool_test.rs#L209)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Actually tip is necessary, as the test checks that the replenishment is done between chunks.
See the comment below:
</blockquote></details>

you're right!


<!-- Sent from Reviewable.io -->

2024-10-14 11:33 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 3 unresolved discussions

___
*[`crates/mempool/src/mempool_test.rs` line 207 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O99c0YHBq3vVLVGzY-F:-O99nE4rDuJ5FWy3xqsF:brxra74) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d98bd205bba8a70a07de81e3f16e854ad01f385/crates/mempool/src/mempool_test.rs#L207)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The new name emphasizes the following:
-   The transactions are fetched from the priority queue.
-   The replenishment happens between chunks.
</blockquote></details>

I think the original name works since it should focus on the logic, not the specific queue implementation.


<!-- Sent from Reviewable.io -->

2024-10-14 11:35 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 207 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O99c0YHBq3vVLVGzY-F:-O99nyC_2IYjfDGsEpc5:bein9bm) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d98bd205bba8a70a07de81e3f16e854ad01f385/crates/mempool/src/mempool_test.rs#L207)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think the original name works since it should focus on the logic, not the specific queue implementation.
</blockquote></details>

Sounds good, Thanks !


<!-- Sent from Reviewable.io -->

2024-10-14 14:28 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 210 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9A76Su3twS3Q5uoBEM:-O9APIopEvk-5KqwAqTS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8cfd9b1a8473494a80b60e848fcff141b9b3217e/crates/mempool/src/mempool_test.rs#L210)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think `max_l2_gas_price` should have just one value for valid and invalid cases, as multiple values imply extra meaning. The same goes for `tip` - I think it's better to have a single value for the same account.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 236 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9A8C8S5Atlkw97Rv-u:-O9APawjEVMK9RNE5HCP:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/8cfd9b1a8473494a80b60e848fcff141b9b3217e/crates/mempool/src/mempool_test.rs#L236)):*
> ```XML
>         .build_into_mempool();
> 
>     // Test and assert. Return only priority transactions.
> ```

Done
___
*[`crates/mempool/src/mempool_test.rs` line 238 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9A8S2L0zyx-VrkFc3t:-O9APv6t0WWnw6wNaGCp:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/8cfd9b1a8473494a80b60e848fcff141b9b3217e/crates/mempool/src/mempool_test.rs#L238)):*
> ```XML
>     // Test and assert. Return only priority transactions.
>     // Replenishment done in chunks: account 1 transaction is returned before the one of account 0,
>     // although its priority is higher.
> ```

Done


<!-- Sent from Reviewable.io -->

2024-10-15 10:39 UTC, ayeletstarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9EiKLR84yKaaF5JGXj:-O9EiKLR84yKaaF5JGXk:b-30p5rc) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a70eae2bf2e6bf28494b3674415e2bc17a80a4e/crates/mempool/src/mempool_test.rs#L215)):*
> ```XML
>     let pending_tx_address_0_nonce_2 = tx!(tip: 20, tx_hash: 3, sender_address: "0x0", tx_nonce: 2,
>         max_l2_gas_price: 99);
>     let priority_tx_address_0_nonce_3 = tx!(tip: 20, tx_hash: 4, sender_address: "0x0", tx_nonce: 3,
> ```

I don’t think we need to verify that we’re not popping transactions from the pending queue because `update_gas_price_threshold` tests already cover this. We just need to check replenishment in both queues, so `priority_tx_address_0_nonce_1` and `pending_tx_address_0_nonce_2` are enough.



_Code quote:_
```XML
    let pending_tx_address_0_nonce_2 = tx!(tip: 20, tx_hash: 3, sender_address: "0x0", tx_nonce: 2,
        max_l2_gas_price: 99);
    let priority_tx_address_0_nonce_3 = tx!(tip: 20, tx_hash: 4, sender_address: "0x0", tx_nonce: 3,
```
___
*[`crates/mempool/src/mempool_test.rs` line 228 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9Ehl6R0rsI1nCVWBuQ:-O9Ehl6R0rsI1nCVWBuR:bmf61qb) ([raw file](https://github.com/starkware-libs/sequencer/blob/136224af710167c3dadde7ee0ba234f63ed37750/crates/mempool/src/mempool_test.rs#L228)):*
> ```XML
> 
> #[rstest]
> fn test_get_txs_replenishes_queue_multi_account_between_chunks() {
> ```

It's out of scope, but let's discuss the difference between this test and the previous one. I'm not sure they're both needed.



_Code quote:_
```XML
test_get_txs_replenishes_queue_multi_account_between_chunks
```


<!-- Sent from Reviewable.io -->

2024-10-15 11:34 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9EiKLR84yKaaF5JGXj:-O9ErRTPCtpLjjvpRbNJ:b-lrgimn) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a70eae2bf2e6bf28494b3674415e2bc17a80a4e/crates/mempool/src/mempool_test.rs#L215)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I don’t think we need to verify that we’re not popping transactions from the pending queue because `update_gas_price_threshold` tests already cover this. We just need to check replenishment in both queues, so `priority_tx_address_0_nonce_1` and `pending_tx_address_0_nonce_2` are enough.
</blockquote></details>

The `update_gas_price_threshold` tests don’t pop transactions from the priority queue—this is the only test that does.

I added new transactions to show that `get_txs` replenishes both queues, pops from the priority queue, and ensures only a single transaction per address exists in both queues.
___
*[`crates/mempool/src/mempool_test.rs` line 228 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9Ehl6R0rsI1nCVWBuQ:-O9EvaEvAg3no_DQgryK:bfas2b1) ([raw file](https://github.com/starkware-libs/sequencer/blob/136224af710167c3dadde7ee0ba234f63ed37750/crates/mempool/src/mempool_test.rs#L228)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

It's out of scope, but let's discuss the difference between this test and the previous one. I'm not sure they're both needed.
</blockquote></details>

Good point!

The second test seems unnecessary, as the first test already covers it.

Details: 
- The first test verifies that `get_txs` replenishes nonces across chunks, and then verifies the queue update.
- The second test retrieves transactions only from the queue and checks the queue update after `get_txs`, making it redundant - as it was checked in the firsst test.

I’ll remove it in a separate PR.


<!-- Sent from Reviewable.io -->

2024-10-15 14:53 UTC, ayeletstarkware reviewed
> Reviewed 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9EiKLR84yKaaF5JGXj:-O9FcpZj1TC8AXQcwyKt:bikd20v) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a70eae2bf2e6bf28494b3674415e2bc17a80a4e/crates/mempool/src/mempool_test.rs#L215)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The `update_gas_price_threshold` tests don’t pop transactions from the priority queue—this is the only test that does.

I added new transactions to show that `get_txs` replenishes both queues, pops from the priority queue, and ensures only a single transaction per address exists in both queues.
</blockquote></details>

You're right, there was a refactor in those tests.
___
*[`crates/mempool/src/mempool_test.rs` line 228 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9Ehl6R0rsI1nCVWBuQ:-O9FdfKZAh34QSk8Et01:b-6mhyx0) ([raw file](https://github.com/starkware-libs/sequencer/blob/136224af710167c3dadde7ee0ba234f63ed37750/crates/mempool/src/mempool_test.rs#L228)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Good point!

The second test seems unnecessary, as the first test already covers it.

Details: 
- The first test verifies that `get_txs` replenishes nonces across chunks, and then verifies the queue update.
- The second test retrieves transactions only from the queue and checks the queue update after `get_txs`, making it redundant - as it was checked in the firsst test.

I’ll remove it in a separate PR.
</blockquote></details>

Great, thanks!
___
*[`crates/mempool/src/test_utils.rs` line 53 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9Feal49hH_sx9x4L6u:-O9Feal49hH_sx9x4L6v:b83ifpk) ([raw file](https://github.com/starkware-libs/sequencer/blob/96cd32488856e39a260d11ce54ea2c75ff423d1b/crates/mempool/src/test_utils.rs#L53)):*
> ```XML
>     }};
>     (tx_hash: $tx_hash:expr, sender_address: $sender_address:expr, tx_nonce: $tx_nonce:expr, max_l2_gas_price: $max_l2_gas_price:expr) => {
>         tx!(tip: 0, tx_hash: $tx_hash, sender_address: $sender_address, tx_nonce: $tx_nonce, max_l2_gas_price: $max_l2_gas_price)
> ```

Where is this used? 


<!-- Sent from Reviewable.io -->

2024-10-21 06:53 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1351)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/test_utils.rs` line 53 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1351#-O9Feal49hH_sx9x4L6u:-O9eclPo4wD08V9asyYv:bpfsu5a) ([raw file](https://github.com/starkware-libs/sequencer/blob/96cd32488856e39a260d11ce54ea2c75ff423d1b/crates/mempool/src/test_utils.rs#L53)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

In the test (`test_get_txs_replenishes_queue_only_between_chunks`) to configure gas price value.
</blockquote></details>

It's not in use anymore. Removed.


<!-- Sent from Reviewable.io -->

2024-10-28 13:21 UTC, closed without merging