feat: add broadcasting to StreamHandler
starkware-libs/sequencer pull request #1402
Opened 2024-10-14 13:41 UTC by guy-starkware

This adds the other communications direction, e.g., from the Consensus into the network.

The StreamHandler gets a receiver of receivers (well, actually it gets a tuple with stream_id and a receiver).
Each new receiver corresponds to a new stream_id (in the Consensus case it would be a new height).

Then, messages that come in the form of generic T (can be any protobuf-able message) are packaged into StreamMessage and sent out to the network.

When the Fin message comes, the receiver channel is dropped.

2024-10-30 09:35 UTC, dan-starkware requested changes
> Reviewed 4 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1402)* status: 4 of 7 files reviewed, 7 unresolved discussions (waiting on @guy-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAMHcbV2AMNiJvtuBfZ:-OAMHcbV2AMNiJvtuBf_:b91fprz) (no related file):*
Please use the type aliases in the test file.

___
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAI_-f90O7MMsEnrXp7:-OAI_-f90O7MMsEnrXp8:b-pb4q6m) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L27)):*
> ```XML
> type StreamId = u64;
> type MessageId = u64;
> ```

Please remove empty line
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAM-NKQBwETgBv9B5Qx:-OAM-NKR7B41eNK2MEdA:b-pb4q6m) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L68)):*
> ```XML
>     // This includes both the message buffer and some metadata (like the latest message_id).
>     inbound_stream_data: HashMap<StreamKey, StreamData<T>>,
> ```

Please remove empty line
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAM-DPSCYX3Xa_nzjs3:-OAM-DPSCYX3Xa_nzjs4:b-niaowi) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L73)):*
> ```XML
>     // A network sender that allows sending StreamMessages to peers.
>     outbound_sender: BroadcastTopicClient<StreamMessage<T>>,
>     // For each stream that goes out to broadcast, there is a receiver.
> ```

Try and be consistent with comments' style



_Code quote:_
```XML
// For each stream that goes out to broadcast, there is a receiver.
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 75 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAM-U4L65oiS-RoSJLH:-OAM-U4M2uWp9ouAFoaj:b-aqz08m) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L75)):*
> ```XML
>     // For each stream that goes out to broadcast, there is a receiver.
>     outbound_stream_receivers: StreamHashMap<StreamId, mpsc::Receiver<T>>,
>     outbound_stream_number: HashMap<StreamId, MessageId>,
> ```

Consider adding a comment here or removing/changing the comments on other fields.
IMO, comments should not repeat the name and type of a field, but add insights that cannot be inferred by these. 
I'll elaborate more F2F



_Code quote:_
```XML
 outbound_stream_number: HashMap<StreamId, MessageId>,
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 100 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAM18_TBu-tgnqHAuoA:-OAM18_UC7SYsy9iqBq4:bvq6kje) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L100)):*
> ```XML
> 
>     /// Listen for messages on the receiver channel, buffering them if necessary.
>     /// Guarantees that messages are sent in order.
> ```

Please fix this



_Code quote:_
```XML
    /// Listen for messages on the receiver channel, buffering them if necessary.
    /// Guarantees that messages are sent in order.
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 105 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAM0Vtr45cN9rTcfd66:-OAM0Vtr45cN9rTcfd67:beyopjq) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L105)):*
> ```XML
>             // Go over the outbound_channel_receiver to see if there is a new receiver,
>             // and go over all existing outbound_receivers to see if there are any messages to
>             // send. Finally, check if there is an input message from the network.
> ```

Consider formatting as 
```
1. Handle new outbound streams.
2. ...
3. ...
```

Or splitting to each section.

Can also refactor each section to a function with self explanatory name so the code will look like

```
loop
  select
    handle_new_outbound_streams(..)
    ...
```



_Code quote:_
```XML
            // Go over the outbound_channel_receiver to see if there is a new receiver,
            // and go over all existing outbound_receivers to see if there are any messages to
            // send. Finally, check if there is an input message from the network.
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 118 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAMEv3u2f4YNGUzE-a-:-OAMEv3v5mKkMs6MXbxj:b7pc694) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L118)):*
> ```XML
>                             self.broadcast_fin(key).await;
>                         }
>                         None => {}  // This should generally never happen
> ```

Consider Warn



_Code quote:_
```XML
 None => {}  // This should generally never happen
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 138 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAM8GNt0_udEn3bzNYz:-OAM8GNt0_udEn3bzNZ-:b-l03l75) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L138)):*
> ```XML
> 
>     // Send the message to the network.
>     async fn broadcast(&mut self, key: StreamId, message: T) {
> ```

Why not stream_id?



_Code quote:_
```XML
key
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 218 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAMGqzR7IvO76RNbVvw:-OAMGqzR7IvO76RNbVvx:b-70l1n) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L218)):*
> ```XML
>             warn!(
>                 "Received message with id that is bigger than the id of the fin message! 
>                 key: {:?}, message_id: {}, fin_message_id: {}",
> ```

Why did this change? 



_Code quote:_
```XML
                "Received message with id that is bigger than the id of the fin message!
                key: {:?}, message_id: {}, fin_message_id: {}",
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 50 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAMH3sk0uj8595UFtX0:-OAMH3sk0uj8595UFtX1:b-85bp) ([raw file](https://github.com/starkware-libs/sequencer/blob/8535ee9f2a8b34d74b9e6931b85aa7000c903a08/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L50)):*
> ```XML
>     }
> 
>     #[allow(clippy::type_complexity)]
> ```

Why did this change?



_Code quote:_
```XML
 #[allow(clippy::type_complexity)]
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 74 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAMHsGfCiCnz2xiT56H:-OAMHsGg2yX7GI-DkBRi:b7ibv0x) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L74)):*
> ```XML
>         // Note that each new channel comes in a tuple with (stream_id, receiver).
>         let (outbound_channel_sender, outbound_channel_receiver) =
>             mpsc::channel::<(u64, mpsc::Receiver<ConsensusMe [...]

2024-10-30 11:40 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1402)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAM-NKQBwETgBv9B5Qx:-OARpJ9MBPa572nTBj7a:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L68)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove empty line
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 100 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAM18_TBu-tgnqHAuoA:-OARpoIR8Z7lIv1KEdIy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L100)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please fix this
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 50 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAMH3sk0uj8595UFtX0:-OARr0GlC-pj9y4w382i:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8535ee9f2a8b34d74b9e6931b85aa7000c903a08/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L50)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why did this change?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1402#-OAMI-Nz32num0A20Sys:-OARrSTP-tVZ5SdCKN1Q:b-fw0u55) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bb0edd03bdb823eb95fc828d2b836fbeef4cc4/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L94)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Actually that is still relevant. I added some more context. 


<!-- Sent from Reviewable.io -->

2024-11-03 13:23 UTC, guy-starkware reviewed
> Reviewed 4 of 6 files at r4, 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1402)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-11-03 13:49 UTC, dan-starkware reviewed
> Reviewed 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1402)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-11-03 13:50 UTC, dan-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1402)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-11-03 13:50 UTC, dan-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1402)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-11-03 14:03 UTC, merged