chore(mempool): add logs to mempool logic
starkware-libs/sequencer pull request #1428
Opened 2024-10-15 10:30 UTC by elintul

2024-10-15 13:21 UTC, MohammadNassar1 requested changes
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FIpcK9HgMV0fA-Byp:-O9FIpcL8-KjL0gEZ9AZ:bnpsqz4) ([raw file](https://github.com/starkware-libs/sequencer/blob/6452bc57cecf84590e2199a8012a487f95e387d8/crates/mempool/src/mempool.rs#L73)):*
> ```XML
>         }
> 
>         tracing::info!(
> ```

Please import info directly.



_Code quote:_
```XML
tracing::info
```
___
*[`crates/mempool/src/mempool.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FJKvDAozzxMEx9a0M:-O9FJKvE4L0ksZMUXwqJ:bi64ka9) ([raw file](https://github.com/starkware-libs/sequencer/blob/6452bc57cecf84590e2199a8012a487f95e387d8/crates/mempool/src/mempool.rs#L92)):*
> ```XML
>     #[tracing::instrument(
>         skip(self, args),
>         fields( // Log subset of (informative) fields.
> ```

I think `tip` and `gas price` are also needed, wdyt?



_Code quote:_
```XML
// Log subset of (informative) fields.
```


<!-- Sent from Reviewable.io -->

2024-10-15 13:47 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FIpcK9HgMV0fA-Byp:-O9FOpI60kZ73iHLlJHq:b-9bfz55) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4176245137ca4c211aa406ea4549316f6dc5228/crates/mempool/src/mempool.rs#L73)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please import info directly.
</blockquote></details>

I'd rather not, it's not clear where it comes from (ours? an external crate?).
___
*[`crates/mempool/src/mempool.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FJKvDAozzxMEx9a0M:-O9FOvIG8yUE_sM6U7gI:b-4iy7su) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4176245137ca4c211aa406ea4549316f6dc5228/crates/mempool/src/mempool.rs#L92)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think `tip` and `gas price` are also needed, wdyt?
</blockquote></details>

Will add to fee esc. flow, next PR (I don't want to log this for the first transaction of this address and nonce).
I'd rather not to add a TODO, since CI is flaky.


<!-- Sent from Reviewable.io -->

2024-10-15 13:50 UTC, MohammadNassar1 requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FQ5HC0uTcdPhD-MBg:-O9FQ5HC0uTcdPhD-MBh:bki19oz) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool/src/mempool.rs#L132)):*
> ```XML
>             self.align_to_account_state(account_state);
>         }
>         tracing::info!("Aligned mempool to committed nonces.");
> ```

Is it critical information?
Can it be for debug mode?

The same goes for the below `info!`



_Code quote:_
```XML
 tracing::info!("Aligned mempool to committed nonces.");
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FQrIyCEwnn1XWqIBo:-O9FQrIz36diz1HtFKnN:bfa2g3b) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool_types/src/mempool_types.rs#L17)):*
> ```XML
> }
> 
> impl std::fmt::Display for AccountState {
> ```

please import it instead



_Code quote:_
```XML
std::fmt::Display
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRL2H3Cbgg48ddYIb:-O9FRL2H3Cbgg48ddYIc:b-g2v3hw) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool_types/src/mempool_types.rs#L17)):*
> ```XML
> }
> 
> impl std::fmt::Display for AccountState {
> ```

Can you please explain why this code is needed? and why deriving Display is not sufficient.



_Code quote:_
```XML
impl std::fmt::Display for AccountState {
```
___
*[`crates/starknet_api/src/core.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRDIF4WXHaue0Us9X:-O9FRDIF4WXHaue0Us9Y:bqo10yu) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/starknet_api/src/core.rs#L9)):*
> ```XML
> use std::sync::LazyLock;
> 
> use derive_more::Display;
> ```

Why are there two imports here?
Which one is used for the nonce?



_Code quote:_
```XML
use core::fmt::Display;
use std::fmt::Debug;
use std::sync::LazyLock;

use derive_more::Display;
```


<!-- Sent from Reviewable.io -->

2024-10-15 13:51 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRaGH7IQymduOYWza:-O9FRaGH7IQymduOYWzb:b-swn3ov) (no related file):*
General question: How do we check that the logs work as expected?

___


<!-- Sent from Reviewable.io -->

2024-10-15 14:00 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRaGH7IQymduOYWza:-O9FSxeaDVC_CZ1hgKbk:b-feaibr) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

General question: How do we check that the logs work as expected?
</blockquote></details>

I checked manually.
We don't, we trust `tracing` and our log configuration, which should be separately checked.

___
___
*[`crates/mempool/src/mempool.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FQ5HC0uTcdPhD-MBg:-O9FT4s4BOsjJ0NEEXkk:b-yglj9p) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool/src/mempool.rs#L132)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Is it critical information?
Can it be for debug mode?

The same goes for the below `info!`
</blockquote></details>

I want for this long operation to have midway logs; otherwise, debugging is hard.
___
*[`crates/mempool_types/src/mempool_types.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FQrIyCEwnn1XWqIBo:-O9FTAz8DrAEscCSDZqo:b-qaeqa4) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool_types/src/mempool_types.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

please import it instead
</blockquote></details>

I'd rather not to, same reason for `tracing` (a general answer for `std`/short named crates).
___
*[`crates/starknet_api/src/core.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRDIF4WXHaue0Us9X:-O9FTUcDApobYNrjQMMk:bz9lcul) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/starknet_api/src/core.rs#L9)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why are there two imports here?
Which one is used for the nonce?
</blockquote></details>

An excellent example why fully-qualified names should be used. The last one, first one is only a trait, as you can see from my implementation above...


<!-- Sent from Reviewable.io -->

2024-10-15 14:07 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRL2H3Cbgg48ddYIb:-O9FV0Yp4C8-HNTRHDuv:b-l1bd5) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool_types/src/mempool_types.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you please explain why this code is needed? and why deriving Display is not sufficient.
</blockquote></details>

Directly deriving isn't possible, wherever we have it it's actually `derive_more::Display`, which is only possible for newtypes (`struct A(B)`).


<!-- Sent from Reviewable.io -->

2024-10-15 14:10 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FIpcK9HgMV0fA-Byp:-O9FVJY54H_zakngU7L8:b-8meft) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool/src/mempool.rs#L73)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'd rather not, it's not clear where it comes from (ours? an external crate?).
</blockquote></details>

I'm not sure I get it. Do we have two `info`s?
___
*[`crates/mempool/src/mempool.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FQ5HC0uTcdPhD-MBg:-O9FVV758pG6IeDCS9HP:b-3dympx) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool/src/mempool.rs#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I want for this long operation to have midway logs; otherwise, debugging is hard.
</blockquote></details>

Can it be for debug mode?


<!-- Sent from Reviewable.io -->

2024-10-15 14:16 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FIpcK9HgMV0fA-Byp:-O9FWfzV-1DTBz1jAH_Y:b-gtq6gy) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool/src/mempool.rs#L73)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I'm not sure I get it. Do we have two `info`s?
</blockquote></details>

No, it's not only for disambiguation; it's also for generic names - what's "info"? Super unclear. `tracing::info` is much better.
___
*[`crates/mempool/src/mempool.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FQ5HC0uTcdPhD-MBg:-O9FWqfOBtIc0bti8YkT:b-tbvn2w) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool/src/mempool.rs#L132)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can it be for debug mode?
</blockquote></details>

Will change the level next PR, I want to keep as-is for Nadin to debug this CI.
Note the rest aren't (I'd rather us having logs when bugs happen, and not retrospectively; not always easily reproducible).


<!-- Sent from Reviewable.io -->

2024-10-15 14:16 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool_types/src/mempool_types.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRL2H3Cbgg48ddYIb:-O9FX68k8UfnSHZbWLFa:b-wy432j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool_types/src/mempool_types.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Directly deriving isn't possible, wherever we have it it's actually `derive_more::Display`, which is only possible for newtypes (`struct A(B)`).
</blockquote></details>

Thanks, and can you please explain why you had to add the trait for `Nonce` struct (below) without the implementation?


<!-- Sent from Reviewable.io -->

2024-10-15 14:18 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/starknet_api/src/core.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRDIF4WXHaue0Us9X:-O9FXXDW-ztjA0M2Aatu:b-l03uqb) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/starknet_api/src/core.rs#L9)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

An excellent example why fully-qualified names should be used. The last one, first one is only a trait, as you can see from my implementation above...
</blockquote></details>

Is it not confusing to have two imports with the same name?
(if you agree, it can be changed in a separate PR)


<!-- Sent from Reviewable.io -->

2024-10-15 14:18 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRL2H3Cbgg48ddYIb:-O9FXbZaEUiZ5ZPYqcay:bu4w14j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool_types/src/mempool_types.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Thanks, and can you please explain why you had to add the trait for `Nonce` struct (below) without the implementation?
</blockquote></details>

Again, it's not the trait; it's `derive_more::Display`.
Don't like it (it's longer compilation and linking), but that's the way it is in the rest of the file and I'd rather keep consistent.


<!-- Sent from Reviewable.io -->

2024-10-15 14:18 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/starknet_api/src/core.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRDIF4WXHaue0Us9X:-O9FXoAR-KIc6L1k6uU0:beuskmh) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/starknet_api/src/core.rs#L9)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Is it not confusing to have two imports with the same name?
(if you agree, it can be changed in a separate PR)
</blockquote></details>

Yes, but I don't want to fix in this PR.


<!-- Sent from Reviewable.io -->

2024-10-15 14:19 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9FRL2H3Cbgg48ddYIb:-O9FXueH0y31crtahIpA:b-dw3x9h) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b0916a4840caa0869d72b7c46ed1b3891682a49/crates/mempool_types/src/mempool_types.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Again, it's not the trait; it's `derive_more::Display`.
Don't like it (it's longer compilation and linking), but that's the way it is in the rest of the file and I'd rather keep consistent.
</blockquote></details>

(Did you read my answer below? Note I already answered it.)


<!-- Sent from Reviewable.io -->

2024-10-15 15:02 UTC, MohammadNassar1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)



<!-- Sent from Reviewable.io -->

2024-10-15 15:06 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-:-O9FhhcZ35dv51NL6oQZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)



<!-- Sent from Reviewable.io -->

2024-10-20 07:14 UTC, giladchase requested changes
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9cUCFc7RrJDeo7gYlg:-O9cUCFc7RrJDeo7gYlh:bttyycz) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd470d439acbbf8ea9071ba880e727bd279e2f66/crates/mempool/src/mempool.rs#L14)):*
> ```XML
>     MempoolResult,
> };
> use tracing;
> ```

Can remove, crates are always in the namespace



_Code quote:_
```XML
use tracing;
```
___
*[`crates/mempool/src/mempool.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9cYfig013yMvwCvENs:-O9cYfig013yMvwCvENt:bptthsl) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd470d439acbbf8ea9071ba880e727bd279e2f66/crates/mempool/src/mempool.rs#L97)):*
> ```XML
>             account_state = %args.account_state
>         ),
>         ret,
> ```

Just to be sure i understand, this returns `()` in case of success, that is the intended behavior? Note that this also prints the instrument fields



_Code quote:_
```XML
        ret,
```
___
*[`crates/mempool/src/mempool.rs` line 255 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9ceiK46AXNVdJOSWR_:-O9ceiK46AXNVdJOSWRa:bkpzk7h) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd470d439acbbf8ea9071ba880e727bd279e2f66/crates/mempool/src/mempool.rs#L255)):*
> ```XML
>         }
> 
>         tracing::info!("{existing_tx_ref} will be replaced by {incoming_tx_ref}.");
> ```

Do we want to instrument this function?
Without it prints look like:
```
2024-10-20T07:08:27.780747Z  INFO add_tx: TransactionReference {...} will be replaced by ...

```

And with it:
```
2024-10-20T07:08:27.780747Z  INFO add_tx::handle_fee_escalation TransactionReference {...} will be replaced by ...
```



_Code quote:_
```XML
    fn handle_fee_escalation(&mut self, incoming_tx: &Transaction) -> MempoolResult<()> {
        let incoming_tx_ref = TransactionReference::new(incoming_tx);
        let TransactionReference { address, nonce, .. } = incoming_tx_ref;
        let Some(existing_tx_ref) = self.tx_pool.get_by_address_and_nonce(address, nonce) else {
            // Replacement irrelevant: no existing transaction with the same nonce for address.
            return Ok(());
        };

        if !self.should_replace_tx(existing_tx_ref, &incoming_tx_ref) {
            tracing::info!(
                "{existing_tx_ref} was not replaced by {incoming_tx_ref} due to insufficient
                fee escalation."
            );
            // TODO(Elin): consider adding a more specific error type / message.
            return Err(MempoolError::DuplicateNonce { address, nonce });
        }

        tracing::info!("{existing_tx_ref} will be replaced by {incoming_tx_ref}.");
```


<!-- Sent from Reviewable.io -->

2024-10-20 07:24 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 317 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9cnlMkA9yRsBXu8PYz:-O9cnlMl27o3ofPSIdrs:b3mf1ul) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd470d439acbbf8ea9071ba880e727bd279e2f66/crates/mempool/src/mempool.rs#L317)):*
> ```XML
>         )
>     }
> }
> ```

Plz move to after the `impl` of the struct



_Code quote:_
```XML
impl std::fmt::Display for TransactionReference {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let TransactionReference { address, nonce, tx_hash, tip, max_l2_gas_price } = self;
        write!(
            f,
            "TransactionReference {{ address: {address}, nonce: {nonce}, tx_hash: {tx_hash},
            tip: {tip}, max_l2_gas_price: {max_l2_gas_price} }}"
        )
    }
}
```


<!-- Sent from Reviewable.io -->

2024-10-20 08:39 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9cUCFc7RrJDeo7gYlg:-O9d3hGy1BfSsyFcqTrC:brqw03y) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd470d439acbbf8ea9071ba880e727bd279e2f66/crates/mempool/src/mempool.rs#L14)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can remove, crates are always in the namespace
</blockquote></details>

Cool!!
___
*[`crates/mempool/src/mempool.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9cYfig013yMvwCvENs:-O9d2JZO15r5X_UFEbqN:bsjckvs) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd470d439acbbf8ea9071ba880e727bd279e2f66/crates/mempool/src/mempool.rs#L97)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Just to be sure i understand, this returns `()` in case of success, that is the intended behavior? Note that this also prints the instrument fields
</blockquote></details>

Removed; I'll configure the node tracing subscriber to log exit (and enter) to the span, instead.
___
*[`crates/mempool/src/mempool.rs` line 255 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9ceiK46AXNVdJOSWR_:-O9d2quM5TGxshc0qLj1:b-2fl6gd) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd470d439acbbf8ea9071ba880e727bd279e2f66/crates/mempool/src/mempool.rs#L255)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do we want to instrument this function?
Without it prints look like:
```
2024-10-20T07:08:27.780747Z  INFO add_tx: TransactionReference {...} will be replaced by ...

```

And with it:
```
2024-10-20T07:08:27.780747Z  INFO add_tx::handle_fee_escalation TransactionReference {...} will be replaced by ...
```
</blockquote></details>

Good idea, done!
(Converted all those to `debug`, so we don't spam logs.)


<!-- Sent from Reviewable.io -->

2024-10-20 08:58 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 255 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9ceiK46AXNVdJOSWR_:-O9d8XgF8BtSCkerXk5D:bwi9z7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd470d439acbbf8ea9071ba880e727bd279e2f66/crates/mempool/src/mempool.rs#L255)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Good idea, done!
(Converted all those to `debug`, so we don't spam logs.)
</blockquote></details>

Also, added `tip` and `max_l2_gas_price` logging to `add_tx` under `info`, so they always appear.


<!-- Sent from Reviewable.io -->

2024-10-20 10:26 UTC, MohammadNassar1 approved these changes
> Reviewed 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9dRvjUErWILtuT9Ozb:-O9dRvjUErWILtuT9Ozc:b4k9ufl) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdce6fd778c98d7c9861ff421e5156cae435cfdb/crates/mempool/src/mempool.rs#L124)):*
> ```XML
>     pub fn commit_block(&mut self, args: CommitBlockArgs) -> MempoolResult<()> {
>         let CommitBlockArgs { nonces, tx_hashes } = args;
>         tracing::debug!("Committing block with {} transactions to mempool.", tx_hashes.len());
> ```

Please elaborate on why this one is `debug` and not `info` level?
I see for `get_txs` and `add_tx` you've used `info`



_Code quote:_
```XML
debug!
```
___
*[`crates/mempool/src/mempool.rs` line 167 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9dRPZa9WWHrhmsxLQj:-O9dRPZbExo2Q83e1KSJ:b-hf0li8) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdce6fd778c98d7c9861ff421e5156cae435cfdb/crates/mempool/src/mempool.rs#L167)):*
> ```XML
> 
>     // TODO(Mohammad): Rename this method once consensus API is added.
>     fn _update_gas_price_threshold(&mut self, threshold: GasPrice) {
> ```

Do you need to add this API as well?



_Code quote:_
```XML
 fn _update_gas_price_threshold(
```
___
*[`crates/mempool/src/mempool.rs` line 298 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9dSFqY8pavKdi1s-Cb:-O9dSFqY8pavKdi1s-Cc:bwmj5go) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdce6fd778c98d7c9861ff421e5156cae435cfdb/crates/mempool/src/mempool.rs#L298)):*
> ```XML
> // TODO(Elin): move to a shared location with other next-gen node crates.
> fn tip(tx: &Transaction) -> Tip {
>     tx.tip().expect("Expected a valid tip value.")
> ```

I don't think the error message adds any additional information. 
You can add `unwrap` here.



_Code quote:_
```XML
"Expected a valid tip value."
```


<!-- Sent from Reviewable.io -->

2024-10-20 10:40 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9dRvjUErWILtuT9Ozb:-O9dVH7rEpwKmWoWmYsZ:b-vhae4z) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdce6fd778c98d7c9861ff421e5156cae435cfdb/crates/mempool/src/mempool.rs#L124)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please elaborate on why this one is `debug` and not `info` level?
I see for `get_txs` and `add_tx` you've used `info`
</blockquote></details>

WDYM? Default level of `instrument` spans is `info`.
`handle_fee_escalation` is an inner function, so I think it should log in `debug` level, so we don't get spammed on every `add_tx` call.
___
*[`crates/mempool/src/mempool.rs` line 167 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9dRPZa9WWHrhmsxLQj:-O9dVTS-3Guu3dGJwRnB:b-5ywjx6) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdce6fd778c98d7c9861ff421e5156cae435cfdb/crates/mempool/src/mempool.rs#L167)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do you need to add this API as well?
</blockquote></details>

Maybe later, as we integrate it to our flow.
___
*[`crates/mempool/src/mempool.rs` line 298 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9dSFqY8pavKdi1s-Cb:-O9dVgB77BKZC4F0vLeX:b-i103vl) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdce6fd778c98d7c9861ff421e5156cae435cfdb/crates/mempool/src/mempool.rs#L298)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I don't think the error message adds any additional information. 
You can add `unwrap` here.
</blockquote></details>

I'd rather production code to not use `unwrap`s.
This is temporary code anyways. What's the status of moving to a `>=V3` enum? Please answer offline.


<!-- Sent from Reviewable.io -->

2024-10-20 11:52 UTC, MohammadNassar1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9dRvjUErWILtuT9Ozb:-O9dl84N45u0Q2p17j-N:b-siyy6q) ([raw file](https://github.com/starkware-libs/sequencer/blob/753bb7024c0211c5caccf3cd44cc801f6a843810/crates/mempool/src/mempool.rs#L124)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM? Default level of `instrument` spans is `info`.
`handle_fee_escalation` is an inner function, so I think it should log in `debug` level, so we don't get spammed on every `add_tx` call.
</blockquote></details>

exactly, I see that get_txs and add_tx use info while `commit_block` uses debug. Is there a reason for that?

btw, I agree regarding `handle_fee_escalation`, but I'm asking about `commit_block`.
___
*[`crates/mempool/src/mempool.rs` line 298 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9dSFqY8pavKdi1s-Cb:-O9diWMV7NHop1QIsqtq:b-vcn5n) ([raw file](https://github.com/starkware-libs/sequencer/blob/753bb7024c0211c5caccf3cd44cc801f6a843810/crates/mempool/src/mempool.rs#L298)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'd rather production code to not use `unwrap`s.
This is temporary code anyways. What's the status of moving to a `>=V3` enum? Please answer offline.
</blockquote></details>

Answered offline


<!-- Sent from Reviewable.io -->

2024-10-20 13:34 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-O9dRvjUErWILtuT9Ozb:-O9e73xY7LCSeGAreJxi:b4vbd03) ([raw file](https://github.com/starkware-libs/sequencer/blob/753bb7024c0211c5caccf3cd44cc801f6a843810/crates/mempool/src/mempool.rs#L124)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

exactly, I see that get_txs and add_tx use info while `commit_block` uses debug. Is there a reason for that?

btw, I agree regarding `handle_fee_escalation`, but I'm asking about `commit_block`.
</blockquote></details>

Note only inside logs in commit are debug... 


<!-- Sent from Reviewable.io -->

2024-10-21 08:09 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428#-:-O9i6oPH2gCnAvkh1IdS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-10-21 14:50 UTC, MohammadNassar1 approved these changes
> Reviewed 2 of 6 files at r2, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1428)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-10-21 15:10 UTC, merged