feat(blockifier): add address and selector for intermediate cairo1 revert errors
starkware-libs/sequencer pull request #1459
Opened 2024-10-19 16:42 UTC by dorimedini-starkware

2024-10-19 16:43 UTC, lotem-starkware commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1459)
<!-- Reviewable:end -->

2024-10-19 16:43 UTC, dorimedini-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1459?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1460** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1460?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1459** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1459?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1458** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1458?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1457** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1457?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-20 06:55 UTC, Yoni-Starkware requested changes
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9ccMcTBex5ZkS3UOXN:-O9ccMcTBex5ZkS3UOXO:b9z68jn) ([raw file](https://github.com/starkware-libs/sequencer/blob/16e16d5de338f02f21e972a6aba0aff9247b6477/crates/blockifier/src/execution/stack_trace.rs#L157)):*
> ```XML
> }
> 
> pub fn extract_trailing_cairo1_revert_trace(root_callinfo: &CallInfo) -> String {
> ```

call/call_info



_Suggestion:_
```XML
(root_call: &CallInfo)
```
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9cfZITDFDLtNSaGpyP:-O9cfZITDFDLtNSaGpyQ:b-io80gf) ([raw file](https://github.com/starkware-libs/sequencer/blob/16e16d5de338f02f21e972a6aba0aff9247b6477/crates/blockifier/src/execution/stack_trace.rs#L159)):*
> ```XML
> pub fn extract_trailing_cairo1_revert_trace(root_callinfo: &CallInfo) -> String {
>     root_callinfo
>         .tail_iter()
> ```

Document why is it enough to iterate the tail



_Code quote:_
```XML
    root_callinfo
        .tail_iter()
```
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9ccT5T5tP7UoHo7dgY:-O9ccT5U1U1qLkSOH1NO:b9z68jn) ([raw file](https://github.com/starkware-libs/sequencer/blob/16e16d5de338f02f21e972a6aba0aff9247b6477/crates/blockifier/src/execution/stack_trace.rs#L160)):*
> ```XML
>     root_callinfo
>         .tail_iter()
>         .map(|callinfo| {
> ```

call/call_info



_Code quote:_
```XML
|callinfo
```
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9cg2sI2OAulg-F3bzh:-O9cg2sI2OAulg-F3bzi:b39o6mt) ([raw file](https://github.com/starkware-libs/sequencer/blob/16e16d5de338f02f21e972a6aba0aff9247b6477/crates/blockifier/src/execution/stack_trace.rs#L168)):*
> ```XML
>             )
>         })
>         .join("\n\n")
> ```

You should stop iterating when you see `call_info.failed == 0`.
Also, you should pop out `ENTRYPOINT_FAILED` in every iteration. 
If anything goes wrong (not enough ENTRYPOINT_FAILED, too much ENTRYPOINT_FAILED) 
fallback the the flat retdata string.

Please add a simple test to `extract_trailing_cairo1_revert_trace` 



_Code quote:_
```XML
        .tail_iter()
        .map(|callinfo| {
            format!(
                "Error in contract (contract address: {:#064x}, selector: {:#064x}):\n{}",
                callinfo.call.storage_address.0.key(),
                callinfo.call.entry_point_selector.0,
                format_panic_data(&callinfo.execution.retdata.0)
            )
        })
        .join("\n\n")
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9cftkn81FDU0EwsnTR:-O9cftkn81FDU0EwsnTS:b-o3afnr) ([raw file](https://github.com/starkware-libs/sequencer/blob/16e16d5de338f02f21e972a6aba0aff9247b6477/crates/blockifier/src/execution/stack_trace_test.rs#L229)):*
> ```XML
> Error in contract (contract address: {test_contract_address_2_felt:#064x}, selector: \
>          {inner_entry_point_selector_felt:#064x}):
> 0x6661696c ('fail').
> ```

I think that this is the desired output



_Suggestion:_
```XML
Error in contract (contract address: {account_address_felt:#064x}, selector: \
         {execute_selector_felt:#064x}):

Error in contract (contract address: {test_contract_address_felt:#064x}, selector: \
         {external_entry_point_selector_felt:#064x}):
         
Error in contract (contract address: {test_contract_address_2_felt:#064x}, selector: \
         {inner_entry_point_selector_felt:#064x}):
0x6661696c ('fail').
```


<!-- Sent from Reviewable.io -->

2024-10-20 08:06 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9cfZITDFDLtNSaGpyP:-O9cxetJA-X3iUsn1mw6:b31lovp) ([raw file](https://github.com/starkware-libs/sequencer/blob/c033bb89824f406436853f10deffa8bf4671f835/crates/blockifier/src/execution/stack_trace.rs#L159)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Document why is it enough to iterate the tail
</blockquote></details>

Why aren't you looking at the ret_data?


<!-- Sent from Reviewable.io -->

2024-10-20 08:11 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9cfZITDFDLtNSaGpyP:-O9cyYE1EocKW-e1oVYv:b-k6fe15) ([raw file](https://github.com/starkware-libs/sequencer/blob/c033bb89824f406436853f10deffa8bf4671f835/crates/blockifier/src/execution/stack_trace.rs#L159)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why aren't you looking at the ret_data?
</blockquote></details>

You're right, see my comment below.
I meant here - why is it enough to look at the rightmost call branch (given that the failure flag is on and the retdata is legit)


<!-- Sent from Reviewable.io -->

2024-10-20 09:23 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9cfZITDFDLtNSaGpyP:-O9ctxVL1_TJnnO73qmd:bvyb82y) ([raw file](https://github.com/starkware-libs/sequencer/blob/c033bb89824f406436853f10deffa8bf4671f835/crates/blockifier/src/execution/stack_trace.rs#L159)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You're right, see my comment below.
I meant here - why is it enough to look at the rightmost call branch (given that the failure flag is on and the retdata is legit)
</blockquote></details>

better?
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9cg2sI2OAulg-F3bzh:-O9d350CEvG_mZAd1RT3:bb20zfo) ([raw file](https://github.com/starkware-libs/sequencer/blob/c033bb89824f406436853f10deffa8bf4671f835/crates/blockifier/src/execution/stack_trace.rs#L168)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You should stop iterating when you see `call_info.failed == 0`.
Also, you should pop out `ENTRYPOINT_FAILED` in every iteration. 
If anything goes wrong (not enough ENTRYPOINT_FAILED, too much ENTRYPOINT_FAILED) 
fallback the the flat retdata string.

Please add a simple test to `extract_trailing_cairo1_revert_trace`
</blockquote></details>

Done.
Added negative tests only ([top of stack](https://reviewable.io/reviews/starkware-libs/sequencer/1469)), positive cases are covered by the other stack trace tests.
If you have a particular edge case in mind that I haven;t thought of PLMK
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9cftkn81FDU0EwsnTR:-O9dE4Bp11bv9dn_sT-H:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c033bb89824f406436853f10deffa8bf4671f835/crates/blockifier/src/execution/stack_trace_test.rs#L229)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think that this is the desired output
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-20 12:47 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9dy-izDj0U_PbrzIbh:-O9dy-izDj0U_PbrzIbi:b28sy0f) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L164)):*
> ```XML
>     // a source or error.
>     let mut error_calls: Vec<&CallInfo> = vec![];
>     for call_info in root_call.tail_iter() {
> ```

shouldn't tail_iter be in this pr?



_Code quote:_
```XML
tail_iter()
```


<!-- Sent from Reviewable.io -->

2024-10-20 12:52 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9dy6Rx0LjO5KF8mBKe:-O9dy6Ry8gCnkKGBuvVq:b-ugub00) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L169)):*
> ```XML
>         if !call_info.execution.failed {
>             break;
>         }
> ```

if you have
a -> b -> c -> d
and c fails after succesfully calling d.

what is  error_calls going to contain after the loop?



_Code quote:_
```XML
        if !call_info.execution.failed {
            break;
        }
```


<!-- Sent from Reviewable.io -->

2024-10-20 12:54 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9dzbUwC6AYut_y8okP:-O9dzbUwC6AYut_y8okQ:b-1osjr0) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L185)):*
> ```XML
>         let retdata = &error_calls[depth].execution.retdata.0;
>         let expected_retdata_len = error_calls.len() - depth;
>         if retdata.len() != expected_retdata_len || retdata[1..] != entrypoint_failed_tail[depth..]
> ```

what are you skipping here?



_Code quote:_
```XML
retdata[1..]
```


<!-- Sent from Reviewable.io -->

2024-10-20 13:11 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9dy-izDj0U_PbrzIbh:-O9e-L1KD1t6rmmdXrnu:b-kj9kgn) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L164)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

shouldn't tail_iter be in this pr?
</blockquote></details>

it is, it's in call_info.rs, above
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9dy6Rx0LjO5KF8mBKe:-O9e-R4J39SyjoS54JUv:b1spbi4) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L169)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

if you have
a -> b -> c -> d
and c fails after succesfully calling d.

what is  error_calls going to contain after the loop?
</blockquote></details>

this function will be called with c as the root_call.
c is failed, so c is added to the error_calls,
and d is not failed, so in the end error_calls is [c]
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9dzbUwC6AYut_y8okP:-O9e-aCP2TYZhsdz7KuW:b-m6m2x3) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L185)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what are you skipping here?
</blockquote></details>

the failure reason.
if `a->b->c` fails at `c` with error `x`
then
1. retdata of `c` is `[x]`
2. retdata of `b` is `[x, ENTRYPOINT_FAILED]`
3. retdata of `a` is `[x, ENTRYPOINT_FAILED, ENTRYPOINT_FAILED]`


<!-- Sent from Reviewable.io -->

2024-10-20 13:18 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/call_info.rs` line 194 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9e46GD7NM7SZ7sY31w:-O9e46GD7NM7SZ7sY31x:brygoie) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/call_info.rs#L194)):*
> ```XML
> 
> pub struct CallInfoTailIter<'a> {
>     call_infos: Vec<&'a CallInfo>,
> ```

do you need to save more than one call_info for this logic?



_Code quote:_
```XML
Vec<&'a CallInfo>,
```


<!-- Sent from Reviewable.io -->

2024-10-20 13:21 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9dy6Rx0LjO5KF8mBKe:-O9e4DdN-5iTQmFfxm2J:b8p7gqa) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L169)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function will be called with c as the root_call.
c is failed, so c is added to the error_calls,
and d is not failed, so in the end error_calls is [c]
</blockquote></details>

why is it called from c and not from a?


<!-- Sent from Reviewable.io -->

2024-10-20 13:21 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9dzbUwC6AYut_y8okP:-O9e4hL5BYRbVj4RwDdX:b-k4osml) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L185)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the failure reason.
if `a->b->c` fails at `c` with error `x`
then
1. retdata of `c` is `[x]`
2. retdata of `b` is `[x, ENTRYPOINT_FAILED]`
3. retdata of `a` is `[x, ENTRYPOINT_FAILED, ENTRYPOINT_FAILED]`
</blockquote></details>

but `x` can be more than 1 felt.


<!-- Sent from Reviewable.io -->

2024-10-20 13:21 UTC, ilyalesokhin-starkware reviewed
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-20 13:28 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9e5aLh7szTJX4QIjr7:-O9e5aLh7szTJX4QIjr8:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L171)):*
> ```XML
>         }
>         error_calls.push(call_info);
>     }
> ```





_Suggestion:_
```XML
     
    loop {
        if !call_info.execution.failed || call_info.execution.retdata.0.last() != Some(ENTRYPOINT_FAILED_ERROR) {
            break;
        }
        error_calls.push(call_info);
        if let Some(last_call) = error_calls.last.unwrap().inner_calls {
           call_info = last_call;
        } else {
           break;
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-10-20 14:38 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @ilyalesokhin-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9dy6Rx0LjO5KF8mBKe:-O9e66OHE8vOeRKGn9Xz:bj1iuxh) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L169)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it called from c and not from a?
</blockquote></details>

I'm assuming a, b are cairo0.
if the entire chain is cairo1 then the root will be `a` and error_calls will be `[a, b, c]`
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9e5aLh7szTJX4QIjr7:-O9eMHpqBHfEx5XQmqOC:bpqqfzv) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L171)):*
> ```XML
>         }
>         error_calls.push(call_info);
>     }
> ```

Done, kinda.
last call is a special case: we don't  expect to see the EF constant in the innermost retdata
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9dzbUwC6AYut_y8okP:-O9e9nKT1faedmVRunoT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/stack_trace.rs#L185)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

but `x` can be more than 1 felt.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/call_info.rs` line 194 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9e46GD7NM7SZ7sY31w:-O9e6-Mc8KTA8H-GILTE:b-o6kgiv) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ddc798fe08c383b8a533afc63de087be2731bd/crates/blockifier/src/execution/call_info.rs#L194)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you need to save more than one call_info for this logic?
</blockquote></details>

right, nope. Done.


<!-- Sent from Reviewable.io -->

2024-10-20 14:42 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 182 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9eNC-T60jI0YflBsMN:-O9eNC-T60jI0YflBsMO:b-a4jh1c) ([raw file](https://github.com/starkware-libs/sequencer/blob/969f042c5099c7b055b81ecb3ee80c228d7364a9/crates/blockifier/src/execution/stack_trace.rs#L182)):*
> ```XML
>         if let Some(ref inner_call) = next_call {
>             if inner_call.execution.failed && !last_felt_is_entrypoint_error {
>                 return fallback_value;
> ```

I think we do want to print the stack trace in this case.



_Suggestion:_
```XML
break
```


<!-- Sent from Reviewable.io -->

2024-10-20 14:46 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 6 files at r1, 2 of 3 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-20 15:02 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 182 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9eNC-T60jI0YflBsMN:-O9eRnPwDM5sbwCCSSZQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/969f042c5099c7b055b81ecb3ee80c228d7364a9/crates/blockifier/src/execution/stack_trace.rs#L182)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think we do want to print the stack trace in this case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-20 15:02 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 182 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9eNC-T60jI0YflBsMN:-O9eRpsz275DpJmQSqvm:bzbqeif) ([raw file](https://github.com/starkware-libs/sequencer/blob/969f042c5099c7b055b81ecb3ee80c228d7364a9/crates/blockifier/src/execution/stack_trace.rs#L182)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

... and [updated tests](https://reviewable.io/reviews/starkware-libs/sequencer/1469)


<!-- Sent from Reviewable.io -->

2024-10-20 18:23 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-:-O9f9tED6ROniZbB2__Q:bnfp4nl)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-10-21 05:25 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 176 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9hXCJp3iJxUfe1x_7T:-O9hXCJq0dzWWrjyS5kj:b-8hixeb) ([raw file](https://github.com/starkware-libs/sequencer/blob/68e71d9d0e713fbf2a125088a8dda9ef2bbb23c2/crates/blockifier/src/execution/stack_trace.rs#L176)):*
> ```XML
>         // Even if the next inner call is also in failed state, assume a scenario where the current
>         // call panicked after ignoring the error result of the inner call.
>         if call.execution.retdata.0.last() != Some(&entrypoint_failed_felt) {
> ```

Maybe we should do this according to the retdata of the outermost call?



_Code quote:_
```XML
if call.execution.retdata.0.last() != Some(&entrypoint_failed_felt) {
```


<!-- Sent from Reviewable.io -->

2024-10-21 09:07 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 176 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9hXCJp3iJxUfe1x_7T:-O9iIEdn02Npr-U0Yz9H:b4qo45s) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0c104ef714be92f19c76c52880c5b2fcc702211/crates/blockifier/src/execution/stack_trace.rs#L176)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe we should do this according to the retdata of the outermost call?
</blockquote></details>

Hmmm, I think it should be equivalent. Do you have a (natural) scenario where the result is different?


<!-- Sent from Reviewable.io -->

2024-10-21 11:37 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-10-22 07:41 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 202 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9n9kiT4bXk5ErzS4Kl:-O9n9kiT4bXk5ErzS4Km:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcc247390b98192cc135dddf4fb8fb9006b919d9/crates/blockifier/src/execution/stack_trace.rs#L202)):*
> ```XML
>             // Inner failure is either not unique, or does not exist (malformed retdata).
>             _ => return fallback_value,
>         };
> ```





_Suggestion:_
```XML
        let expected_inner_retdata = retdata[..retdata.len() - 1];
        let mut potential_inner_failures_iter: Vec<&CallInfo> = call
            .inner_calls
            .iter()
            .filter(|inner_call| {
                inner_call.execution.failed
                    && inner_call.execution.retdata.0 == expected_inner_retdata
            })
            .collect();
        call = potential_inner_failures_iter.next() {
            Some(unique_inner_failure) if potential_inner_failures_iter.next().is_none()  => unique_inner_failure,
            // Inner failure is either not unique, or does not exist (malformed retdata).
            _ => return fallback_value,
        };
```


<!-- Sent from Reviewable.io -->

2024-10-22 08:40 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 176 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9hXCJp3iJxUfe1x_7T:-O9nMWUgEI06jDnpQCZ0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0c104ef714be92f19c76c52880c5b2fcc702211/crates/blockifier/src/execution/stack_trace.rs#L176)):*
> ```XML
>         // Even if the next inner call is also in failed state, assume a scenario where the current
>         // call panicked after ignoring the error result of the inner call.
>         if call.execution.retdata.0.last() != Some(&entrypoint_failed_felt) {
> ```

Done.
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 202 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9n9kiT4bXk5ErzS4Kl:-O9nNcz28MAL7AJ-Y5cJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcc247390b98192cc135dddf4fb8fb9006b919d9/crates/blockifier/src/execution/stack_trace.rs#L202)):*
> ```XML
>             // Inner failure is either not unique, or does not exist (malformed retdata).
>             _ => return fallback_value,
>         };
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-22 10:21 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 166 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9njonq3gqG1rcO5HBP:-O9njonq3gqG1rcO5HBQ:bnvjcgl) ([raw file](https://github.com/starkware-libs/sequencer/blob/6494b1112e08801832e81e5e447ae0986fdf10f9/crates/blockifier/src/execution/stack_trace.rs#L166)):*
> ```XML
>     let mut error_calls: Vec<&CallInfo> = vec![];
>     let mut call = root_call;
>     let mut expected_retdata = call.execution.retdata.0.clone();
> ```

is this clone nessiary?



_Code quote:_
```XML
let mut expected_retdata = call.execution.retdata.0.clone();
```


<!-- Sent from Reviewable.io -->

2024-10-22 10:32 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 166 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9njonq3gqG1rcO5HBP:-O9nlzZq27UGvU2VdcUb:b-6sxa9i) ([raw file](https://github.com/starkware-libs/sequencer/blob/6494b1112e08801832e81e5e447ae0986fdf10f9/crates/blockifier/src/execution/stack_trace.rs#L166)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is this clone nessiary?
</blockquote></details>

I don't want to mutate the original call's retdata, I need a new copy
If I drop the `clone` won't calling `pop` mutate `call.execution.retdata`?


<!-- Sent from Reviewable.io -->

2024-10-22 11:06 UTC, ilyalesokhin-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 166 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9njonq3gqG1rcO5HBP:-O9nu-BqADX3bNjEcBWq:b-lw3o2n) ([raw file](https://github.com/starkware-libs/sequencer/blob/6494b1112e08801832e81e5e447ae0986fdf10f9/crates/blockifier/src/execution/stack_trace.rs#L166)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't want to mutate the original call's retdata, I need a new copy
If I drop the `clone` won't calling `pop` mutate `call.execution.retdata`?
</blockquote></details>

you can use last instead of pop


<!-- Sent from Reviewable.io -->

2024-10-22 11:07 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 166 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9njonq3gqG1rcO5HBP:-O9nuBro0VA2dRipmul4:b4myhnf) ([raw file](https://github.com/starkware-libs/sequencer/blob/6494b1112e08801832e81e5e447ae0986fdf10f9/crates/blockifier/src/execution/stack_trace.rs#L166)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you can use last instead of pop
</blockquote></details>

like in r6


<!-- Sent from Reviewable.io -->

2024-10-22 11:09 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 166 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9njonq3gqG1rcO5HBP:-O9nuWRm6uQmaSYvpS6Y:b5o877x) ([raw file](https://github.com/starkware-libs/sequencer/blob/6494b1112e08801832e81e5e447ae0986fdf10f9/crates/blockifier/src/execution/stack_trace.rs#L166)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

like in r6
</blockquote></details>

in r6 I had an addition expected_inner_retdata variable initialized once per iteration, with `retdata[..X].as_vec()`. Isn't this also a copy operation?
I think this way is better - I maintain the "current" expected retdata by popping once per loop, and only cloning data once before the loop starts


<!-- Sent from Reviewable.io -->

2024-10-22 11:34 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 166 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9njonq3gqG1rcO5HBP:-O9o-HmF5B4SH863q-kw:b-3rday) ([raw file](https://github.com/starkware-libs/sequencer/blob/6494b1112e08801832e81e5e447ae0986fdf10f9/crates/blockifier/src/execution/stack_trace.rs#L166)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in r6 I had an addition expected_inner_retdata variable initialized once per iteration, with `retdata[..X].as_vec()`. Isn't this also a copy operation?
I think this way is better - I maintain the "current" expected retdata by popping once per loop, and only cloning data once before the loop starts
</blockquote></details>

Yes, but the `as_vec` was unnecessary as well.

You can compare the relevant slices, there is no need to copy anything


<!-- Sent from Reviewable.io -->

2024-10-22 11:51 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 166 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9njonq3gqG1rcO5HBP:-O9o34NY0mD5DZ4RqVi0:bruwmo1) ([raw file](https://github.com/starkware-libs/sequencer/blob/6494b1112e08801832e81e5e447ae0986fdf10f9/crates/blockifier/src/execution/stack_trace.rs#L166)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Yes, but the `as_vec` was unnecessary as well.

You can compare the relevant slices, there is no need to copy anything
</blockquote></details>

ah, right
better?


<!-- Sent from Reviewable.io -->

2024-10-22 12:43 UTC, ilyalesokhin-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-:-O9oFAfADa-IpCqCSRSI:bnfp4nl)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-22 12:43 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/stack_trace.rs` line 166 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1459#-O9njonq3gqG1rcO5HBP:-O9oFBVy5bXBFsrxUUPS:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/6494b1112e08801832e81e5e447ae0986fdf10f9/crates/blockifier/src/execution/stack_trace.rs#L166)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, right
better?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2024-10-22 12:53 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1459)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-10-22 12:54 UTC, merged