feat(mempool): impl MempoolConfig
starkware-libs/sequencer pull request #1475
Opened 2024-10-20 12:21 UTC by ayeletstarkware

2024-10-20 12:21 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1475)
<!-- Reviewable:end -->

2024-10-28 10:03 UTC, MohammadNassar1 requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAHZ-LX2E7yig_ZqO7C:-OAHZ-LX2E7yig_ZqO7D:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e879b19a52b814433492194158a228916f69237/crates/mempool/src/mempool_test.rs#L9)):*
> ```XML
> use starknet_mempool_types::mempool_types::AddTransactionArgs;
> 
> use super::MempoolConfig;
> ```





_Suggestion:_
```XML
crate::mempool::MempoolConfig
```
___
*[`crates/mempool/src/mempool_test.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAHZBYQ5X0E8UZoGhMq:-OAHZBYQ5X0E8UZoGhMr:br0e8y4) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e879b19a52b814433492194158a228916f69237/crates/mempool/src/mempool_test.rs#L105)):*
> ```XML
>         self.config.fee_escalation_percentage = fee_escalation_percentage;
>         self
>     }
> ```

How to disable it?



_Code quote:_
```XML
    fn with_fee_escalation_percentage(mut self, fee_escalation_percentage: u8) -> Self {
        self.config.enable_fee_escalation = true;
        self.config.fee_escalation_percentage = fee_escalation_percentage;
        self
    }
```
___
*[`crates/mempool/src/mempool_test.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAHZdJHAMv__rq13ins:-OAHZdJHAMv__rq13int:bju27ir) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e879b19a52b814433492194158a228916f69237/crates/mempool/src/mempool_test.rs#L121)):*
> ```XML
> 
> impl Default for MempoolContentBuilder {
>     fn default() -> Self {
> ```

Why doesn't it use the `MempoolConfig` default?



_Code quote:_
```XML
fn default() -> Self
```
___
*[`crates/mempool/src/mempool_test.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAH_1Vp2v545lF0VnBv:-OAH_1Vp2v545lF0VnBw:buj9cu8) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e879b19a52b814433492194158a228916f69237/crates/mempool/src/mempool_test.rs#L121)):*
> ```XML
> 
> impl Default for MempoolContentBuilder {
>     fn default() -> Self {
> ```

Can it be implemented in the`new` funciton?



_Code quote:_
```XML
 fn default() -> Self
```


<!-- Sent from Reviewable.io -->

2024-10-28 12:51 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAHZ-LX2E7yig_ZqO7C:-OAHrH2o3LRKa4Oz5y1l:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e879b19a52b814433492194158a228916f69237/crates/mempool/src/mempool_test.rs#L9)):*
> ```XML
> use starknet_mempool_types::mempool_types::AddTransactionArgs;
> 
> use super::MempoolConfig;
> ```

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAHZBYQ5X0E8UZoGhMq:-OAHrIpf8yWkqZzIQ2a4:bzbua9w) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e879b19a52b814433492194158a228916f69237/crates/mempool/src/mempool_test.rs#L105)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

How to disable it?
</blockquote></details>

It's automatically disabled unless you call this function
___
*[`crates/mempool/src/mempool_test.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAHZdJHAMv__rq13ins:-OAHrWuUCkzDw3d-52Fb:b459e9a) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e879b19a52b814433492194158a228916f69237/crates/mempool/src/mempool_test.rs#L121)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why doesn't it use the `MempoolConfig` default?
</blockquote></details>

The default for fee escalation is set to `true` in the regular flow, but for tests, we want to isolate this functionality.
___
*[`crates/mempool/src/mempool_test.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAH_1Vp2v545lF0VnBv:-OAIAADT2-GXqyDJ6HZB:bljnj3p) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e879b19a52b814433492194158a228916f69237/crates/mempool/src/mempool_test.rs#L121)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can it be implemented in the`new` funciton?
</blockquote></details>

yep, done


<!-- Sent from Reviewable.io -->

2024-10-28 13:38 UTC, MohammadNassar1 approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAIKx5eDvinMfrgpn36:-OAIKx5eDvinMfrgpn37:b-dldy3p) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1c2f1a4f308c4b83bbeb9c8d258c21ec54edadb/crates/mempool/src/mempool_test.rs#L27)):*
> ```XML
>     tx_pool: Option<TransactionPool>,
>     tx_queue_content: Option<TransactionQueueContent>,
>     config: MempoolConfig,
> ```

Please keep the same order as in the Mempool struct.



_Suggestion:_
```XML
struct MempoolContent {
    config: MempoolConfig,
    tx_pool: Option<TransactionPool>,
    tx_queue_content: Option<TransactionQueueContent>,
```


<!-- Sent from Reviewable.io -->

2024-10-28 13:38 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-:-OAILL84DgIhtErIjObY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-10-28 15:10 UTC, MohammadNassar1 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2024-10-29 10:44 UTC, elintul requested changes
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 100 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAMrpPf59tsHJw690cT:-OAMrpPf59tsHJw690cU:b-cy0c8o) ([raw file](https://github.com/starkware-libs/sequencer/blob/803fcf1de83b620893ce21b57b5ccffac0839952/crates/mempool/src/mempool.rs#L100)):*
> ```XML
>         if self.config.enable_fee_escalation {
>             self.handle_fee_escalation(&tx)?;
>         }
> ```

Move inside.



_Code quote:_
```XML
        if self.config.enable_fee_escalation {
            self.handle_fee_escalation(&tx)?;
        }
```
___
*[`crates/mempool/src/mempool.rs` line 293 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAMrwzqEqq_MexByjSn:-OAMrwzqEqq_MexByjSo:bfo1u2t) ([raw file](https://github.com/starkware-libs/sequencer/blob/803fcf1de83b620893ce21b57b5ccffac0839952/crates/mempool/src/mempool.rs#L293)):*
> ```XML
> 
> #[derive(Debug)]
> pub struct MempoolConfig {
> ```

Please move up (before `Mempool`) next PR.



_Code quote:_
```XML
MempoolConfig
```


<!-- Sent from Reviewable.io -->

2024-10-29 11:26 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 100 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAMrpPf59tsHJw690cT:-OAN0dA19Ut6YhgpSo77:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/803fcf1de83b620893ce21b57b5ccffac0839952/crates/mempool/src/mempool.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move inside.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-29 11:39 UTC, MohammadNassar1 reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 234 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OAN3cdS11As78t6_X4U:-OAN3cdS11As78t6_X4V:b-csthdg) ([raw file](https://github.com/starkware-libs/sequencer/blob/794297fdf88830c97cd55a576ff6c9c48012dccb/crates/mempool/src/mempool.rs#L234)):*
> ```XML
>     #[tracing::instrument(level = "debug", skip(self, incoming_tx), err)]
>     fn handle_fee_escalation(&mut self, incoming_tx: &Transaction) -> MempoolResult<()> {
>         if self.config.enable_fee_escalation {
> ```

Please use early return in case of disabled fee esc.



_Code quote:_
```XML
if self.config.enable_fee_escalation {
```


<!-- Sent from Reviewable.io -->

2024-10-29 12:33 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-:-OANG7Mv-dR0OPRHDPAK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-10-29 12:34 UTC, MohammadNassar1 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-10-29 13:00 UTC, merged

2024-10-29 13:35 UTC, elintul reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/mempool/src/mempool.rs` line 36 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OANTk5pDdJP59Pspvpd:-OANTk5pDdJP59Pspvpe:b-oopv9q) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ac7280eca5c1a5afcf1c4a2119107ea599ab033/crates/mempool/src/mempool.rs#L36)):*
> ```XML
>     // The most recent account nonces received, for all account in the pool.
>     account_nonces: AccountToNonce,
>     // TODO(Elin): make configurable; should be bounded?
> ```

This shouldn't have been removed. Please add this comment to the config: `// TODO: consider adding validations; should be bounded?`. 



_Code quote:_
```XML
should be bounded?
```


<!-- Sent from Reviewable.io -->

2024-10-29 13:36 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1475)* status: all files reviewed, 2 unresolved discussions

___
*[`crates/mempool/src/mempool_test.rs` line 104 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1475#-OANU_nL1Xh3qbW5JU0S:-OANU_nL1Xh3qbW5JU0T:bsp4xea) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5f11825bbca597ee0ac939c4a79fe927dee389d/crates/mempool/src/mempool_test.rs#L104)):*
> ```XML
>     }
> 
>     fn with_fee_escalation_percentage(mut self, fee_escalation_percentage: u8) -> Self {
> ```

As discussed, this isn't very elegant and will skip validations if added in the future  
Can you find a better solution?



_Code quote:_
```XML
with_fee_escalation_percentage
```


<!-- Sent from Reviewable.io -->