refactor(mempool): remove test_add_tx_sequential_nonces redudant test
starkware-libs/sequencer pull request #1510
Opened 2024-10-21 14:29 UTC by MohammadNassar1

2024-10-21 14:29 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1510)
<!-- Reviewable:end -->

2024-10-21 14:31 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-O9jUEJVAD0LEcT8gfFl:-O9jUEJW6jqVhQ2MdlQf:bfpwj0x) (no related file):*
This test is already covered by `test_add_tx_multi_nonce_success`. Both tests verify that adding sequential nonces includes the latter transaction in the pool.

___
___
*[`crates/mempool/src/mempool_test.rs` line 325 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-O9jULAn90IaTPpXBn8C:-O9jULAn90IaTPpXBn8D:b-xjroux) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f7bcc1a7b21d8c78babf39a941470583c028108/crates/mempool/src/mempool_test.rs#L325)):*
> ```XML
>         add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 0, account_nonce: 0);
>     let input_address_0_nonce_1 =
>         add_tx_input!(tx_hash: 3, sender_address: "0x0", tx_nonce: 1, account_nonce: 0);
> ```

Already covered here.



_Code quote:_
```XML
    let input_address_0_nonce_0 =
        add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 0, account_nonce: 0);
    let input_address_0_nonce_1 =
        add_tx_input!(tx_hash: 3, sender_address: "0x0", tx_nonce: 1, account_nonce: 0);
```


<!-- Sent from Reviewable.io -->

2024-10-22 05:25 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-O9meknw2qwV8XJFv0ej:-O9meknw2qwV8XJFv0ek:bstjajy) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f7bcc1a7b21d8c78babf39a941470583c028108/crates/mempool/src/mempool_test.rs#L320)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_multi_nonce_success(mut mempool: Mempool) {
> ```

Rename this test, an option below



_Suggestion:_
```XML
test_add_tx_correctly_places_txs_in_queue_and_pool
```


<!-- Sent from Reviewable.io -->

2024-10-22 07:04 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-O9meknw2qwV8XJFv0ej:-O9n1UknCxSA6awXplSp:b-rg0gah) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f7bcc1a7b21d8c78babf39a941470583c028108/crates/mempool/src/mempool_test.rs#L320)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Rename this test, an option below
</blockquote></details>

I'll rename the tests in another PR.


<!-- Sent from Reviewable.io -->

2024-10-22 07:25 UTC, ayeletstarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-:-O9n6UQ_Df_dsmV_xhLG:bnfp4nl)* status: all files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-10-22 08:16 UTC, elintul requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-O9nHlkg4biQhcxffhkB:-O9nHlkg4biQhcxffhkC:b5qv7pp) (no related file):*
Same answer as in #1509. If you want to consolidate tests, we should make sure cases won't get deleted in the future.

___


<!-- Sent from Reviewable.io -->

2024-10-27 07:30 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-O9nHlkg4biQhcxffhkB:-OABsDTWAVitbgorEDtw:b-dbgg79) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Same answer as in #1509. If you want to consolidate tests, we should make sure cases won't get deleted in the future.
</blockquote></details>

Renamed the test so that its name now indicates it verifies insertion into either the pool or the queue, ensuring it includes transactions that go to the pool and transactions that go to the queue.

___
___
*[`crates/mempool/src/mempool_test.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-O9meknw2qwV8XJFv0ej:-OABs5BZA096gDptbc1w:b-q7a8te) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f7bcc1a7b21d8c78babf39a941470583c028108/crates/mempool/src/mempool_test.rs#L320)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I'll rename the tests in another PR.
</blockquote></details>

Renamed here, so it can answer Elin's [question](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-O9nHlkg4biQhcxffhkB).


<!-- Sent from Reviewable.io -->

2024-10-27 08:28 UTC, ayeletstarkware approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-10-28 08:27 UTC, ayeletstarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-:-OAHE608DGd_tzoiqmnd:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-10-31 10:32 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510)* status: all files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-11-03 11:59 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-:-OAltIct6Ak0KdS1ua_6:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-O9nHlkg4biQhcxffhkB:-OAlt5xZ29QhSrgsgxf6:b-7d7cg5) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Renamed the test so that its name now indicates it verifies insertion into either the pool or the queue, ensuring it includes transactions that go to the pool and transactions that go to the queue.
</blockquote></details>

Note it's not what the test you deleted declares it does.
I approve this since we do check sequential nonces practically in all tests, but this changed wasn't explained thoroughly enough to the reviewer.

___


<!-- Sent from Reviewable.io -->

2024-11-03 12:18 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1510)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1510#-O9nHlkg4biQhcxffhkB:-OAlxSqsE4sgWntNT_bh:bnwg3gq) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Note it's not what the test you deleted declares it does.
I approve this since we do check sequential nonces practically in all tests, but this changed wasn't explained thoroughly enough to the reviewer.
</blockquote></details>

Thanks.
Note that placing txs only in the pool means that we have sequential nonces.

___


<!-- Sent from Reviewable.io -->

2024-11-03 12:19 UTC, merged