refactor: move starknet logic to a different crate
starkware-libs/sequencer pull request #154
Opened 2024-07-28 12:50 UTC by AvivYossef-starkware

python side
https://github.com/starkware-industries/starkware/pull/35643

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/154)

2024-07-28 12:51 UTC, AvivYossef-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/154?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#154** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/154?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#140** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/140?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#133** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/133?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main-v0.13.2`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-31 15:23 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 55 files at r1, 21 of 22 files at r3, 9 of 10 files at r4, 2 of 4 files at r5, 19 of 19 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: all files reviewed, 14 unresolved discussions (waiting on @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38K7Zk9TLn4S9PivC5:-O38K7Zk9TLn4S9PivC6:b-evmdde) (no related file):*
rename `starknet-committer` to `starknet_committer` to be consistent with other crates in the repo

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38KCa8Ai4diuVQHHNJ:-O38KCa8Ai4diuVQHHNK:blnytdb) (no related file):*
need to add a trigger to the committer_ci.yml, to run when the contents of the new crate is changed

___
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 134 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38KTR23Ymd4KezaKK7:-O38KTR23Ymd4KezaKK8:b-p4v1en) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/types.rs#L134)):*
> ```XML
> 
>     #[allow(dead_code)]
>     pub(crate) fn from_felt_value(felt: &Felt) -> Self {
> ```

why does this need the `dead_code` mark?
if it's only used when some feature is active, you can mark the function with `#[cfg(...)]`



_Code quote:_
```XML
    #[allow(dead_code)]
    pub(crate) fn from_felt_value(felt: &Felt) -> Self {
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 58 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LIPG-Zrmdp5CSoMP:-O38LIPG-Zrmdp5CSoMQ:b-wr1fbm) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L58)):*
> ```XML
>         }
>     };
> }
> ```

this should also move to the starknet_committer crate: we don't assume all configs of users of the patricia trees, to have a `LeafModifications` and a boolean



_Code quote:_
```XML
#[macro_export]
macro_rules! generate_trie_config {
    ($struct_name:ident, $leaf_type:ty) => {
        pub struct $struct_name<'a> {
            modifications:
                &'a $crate::patricia_merkle_tree::node_data::leaf::LeafModifications<$leaf_type>,
            compare_modified_leaves: bool,
        }

        impl<'a> $struct_name<'a> {
            #[allow(dead_code)]
            pub fn new(
                modifications: &'a $crate::patricia_merkle_tree::node_data::leaf::LeafModifications<
                    $leaf_type,
                >,
                compare_modified_leaves: bool,
            ) -> Self {
                Self { modifications, compare_modified_leaves }
            }
        }

        impl OriginalSkeletonTreeConfig<$leaf_type> for $struct_name<'_> {
            fn compare_modified_leaves(&self) -> bool {
                self.compare_modified_leaves
            }

            fn compare_leaf(
                &self,
                index: &NodeIndex,
                previous_leaf: &$leaf_type,
            ) -> OriginalSkeletonTreeResult<bool> {
                let new_leaf = self
                    .modifications
                    .get(index)
                    .ok_or(OriginalSkeletonTreeError::ReadModificationsError(*index))?;
                Ok(new_leaf == previous_leaf)
            }
        }
    };
}
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 264 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LV8K60u7V_FMVr3G:-O38LV8K60u7V_FMVr3H:bq507ux) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L264)):*
> ```XML
>     }
> 
>     #[allow(dead_code)]
> ```

why is this code now dead...?



_Code quote:_
```XML
#[allow(dead_code)]
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 30 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LZizDlsOTFBeA1cA:-O38LZizDlsOTFBeA1cB:b-ss4cxr) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L30)):*
> ```XML
>     fn get_nodes_mut(&mut self) -> &mut OriginalSkeletonNodeMap;
> 
>     #[allow(dead_code)]
> ```

how is it possible to get an error here?
this is a method of a `pub trait`, shouldn't the compiler assume it could be used by external implementors?



_Code quote:_
```XML
#[allow(dead_code)]
```
___
*[`crates/starknet-committer/src/hash.rs` line 111 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LvkoDMR3fjP-zl-U:-O38LvkoDMR3fjP-zl-V:bsntp93) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/hash.rs#L111)):*
> ```XML
> 
> #[cfg(test)]
> mod test {
> ```

please open a separate module, like we had in the old crate



_Code quote:_
```XML
#[cfg(test)]
mod test {
```
___
*[`crates/starknet-committer/src/lib.rs` line 4 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38Mues5F7RmY1pkQrq:-O38Muet7vfHfVADHnRE:bd7v7df) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/lib.rs#L4)):*
> ```XML
> pub mod hash;
> pub mod starknet_forest;
> pub mod starknet_patricia_merkle_tree;
> ```

`starknet` is already in the crate name



_Suggestion:_
```XML
pub mod forest;
pub mod patricia_merkle_tree;
```
___
*[`crates/starknet-committer/src/starknet_patricia_merkle_tree.rs` line 2 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38Mz2L7TJguwD5dAUq:-O38Mz2L7TJguwD5dAUr:bd7v7df) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/starknet_patricia_merkle_tree.rs#L2)):*
> ```XML
> pub mod node;
> pub mod starknet_leaf;
> ```

`starknet` is already in the crate name



_Suggestion:_
```XML
pub mod leaf;
```
___
*[`crates/starknet-committer/src/starknet_patricia_merkle_tree/node.rs` line 0 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38NadL0hapHT_WOXg6:-O38NadL0hapHT_WOXg7:b1ruo9) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/starknet_patricia_merkle_tree/node.rs#L0)):*
why is this module called "node"?
___
*[`crates/starknet-committer/src/starknet_patricia_merkle_tree/starknet_leaf.rs` line 4 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38NTJ10YSXi8FFdguu:-O38NTJ10YSXi8FFdguv:b-k7vo2f) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/starknet_patricia_merkle_tree/starknet_leaf.rs#L4)):*
> ```XML
> pub mod leaf_serde;
> #[cfg(test)]
> pub mod leaf_serde_test;
> ```

maybe these modules should all be in the containing dir, so we don't have `starknet_leaf/leaf` etc.



_Code quote:_
```XML
pub mod leaf;
pub mod leaf_serde;
#[cfg(test)]
pub mod leaf_serde_test;
```
___
*[`crates/starknet-committer/src/starknet_patricia_merkle_tree/tree.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38NhMC0G9Gs6h_3iPc:-O38NhMC0G9Gs6h_3iPd:b-b69ee5) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/starknet_patricia_merkle_tree/tree.rs#L17)):*
> ```XML
> generate_trie_config!(OriginalSkeletonClassesTrieConfig, CompiledClassHash);
> 
> impl OriginalSkeletonTreeConfig<ContractState> for OriginalSkeletonContractsTrieConfig {
> ```

makes more sense



_Suggestion:_
```XML
generate_trie_config!(OriginalSkeletonStorageTrieConfig, StarknetStor [...]

2024-08-04 12:27 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: 0 of 67 files reviewed, 14 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38K7Zk9TLn4S9PivC5:-O3RQMjkBILCw6BvUaiU:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rename `starknet-committer` to `starknet_committer` to be consistent with other crates in the repo
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38KCa8Ai4diuVQHHNJ:-O3Rxqrz3s2iJaH0EsKY:b-hcnxkp) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

need to add a trigger to the committer_ci.yml, to run when the contents of the new crate is changed
</blockquote></details>

I think that Done now.

___
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 134 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38KTR23Ymd4KezaKK7:-O3RQZoa7z_G_F-OVxec:bcmiex0) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/types.rs#L134)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why does this need the `dead_code` mark?
if it's only used when some feature is active, you can mark the function with `#[cfg(...)]`
</blockquote></details>

It doesn't need
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 58 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LIPG-Zrmdp5CSoMP:-O3RQdnyAKTSqFNFfbUh:b-8hd1c4) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should also move to the starknet_committer crate: we don't assume all configs of users of the patricia trees, to have a `LeafModifications` and a boolean
</blockquote></details>

It is a nice utility for creating a config. We also use it for testing purposes. If I move it, I will need to create a config for testing.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 30 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LZizDlsOTFBeA1cA:-O3RSFJc-FZXXqTp_EpR:bc5dw6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L30)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how is it possible to get an error here?
this is a method of a `pub trait`, shouldn't the compiler assume it could be used by external implementors?
</blockquote></details>

You are right, I think that the problem is that the compiler yelled at me first for unused code and later to fix the visibility.
I'll check it now
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 264 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LV8K60u7V_FMVr3G:-O3RRQnR3K1cLOHWJN8Q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L264)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this code now dead...?
</blockquote></details>

Done.
___
*[`crates/starknet-committer/src/hash.rs` line 111 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LvkoDMR3fjP-zl-U:-O3RUkEI91axfM3dI8UI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/hash.rs#L111)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please open a separate module, like we had in the old crate
</blockquote></details>

Done.
___
*[`crates/starknet-committer/src/lib.rs` line 4 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38Mues5F7RmY1pkQrq:-O3RVjqn5UiaN2mA3t7l:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/lib.rs#L4)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`starknet` is already in the crate name
</blockquote></details>

Done.
___
*[`crates/starknet-committer/src/starknet_patricia_merkle_tree.rs` line 2 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38Mz2L7TJguwD5dAUq:-O3RVkLmCehakDMmQ90R:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/starknet_patricia_merkle_tree.rs#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`starknet` is already in the crate name
</blockquote></details>

Done.
___
*[`crates/starknet-committer/src/starknet_patricia_merkle_tree/types.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38M1c6-FamEwEGEyPx:-O3RvVgbAdyNvhd5AyNh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/starknet_patricia_merkle_tree/types.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

open a separate module, like in the old crate (I know this module will be tiny, but that's fine
</blockquote></details>

Done.
___
*[`crates/starknet-committer/src/starknet_forest/original_skeleton_forest.rs` line 22 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38NGjK6Txezp1iovcR:-O3RXqaG2Al8FeS5F7P1:b-hefplv) ([raw file](https://github.com/starkware-libs/sequencer/blob/de5966cfb5332259f9d750e399d044e5d469423a/crates/starknet-committer/src/starknet_forest/original_skeleton_forest.rs#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is this test now?
</blockquote></details>

Oops, I'm moving the test to starknet_forest and all the utils that this test uses to external test utils. 
___
*[`crates/starknet-committer/src/starknet_patricia_merkle_tree/node.rs` line  at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38NadL0hapHT_WOXg6:-O3Rvmif-bv9PKkb_q0d:b-j5e80u) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/starknet_patricia_merkle_tree/node.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this module called "node"?
</blockquote></details>

The code here comes from the node module in the committer crate, but I think it should be in the types module.
___
*[`crates/starknet-committer/src/starknet_patricia_merkle_tree/starknet_leaf.rs` line 4 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38NTJ10YSXi8FFdguu:-O3Rt_Mm9u0AN5jizXtZ:byxbjhs) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/starknet-committer/src/starknet_patricia_merkle_tree/starknet_leaf.rs#L4)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe these modules should all be in the containing dir, so we don't have `starknet_leaf/leaf` etc.
</blockquote></details>

What do u think of changing leaf to leaf_impl and keeping it in the leaf directory?
___
*[`crates/starknet-committer/src/starknet_patricia_merkle_tree/tree.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38NhMC0G9Gs6h_3iPc:-O3Rub1l9etzHzpBX3sw:b-896fix) ([raw f [...]

2024-08-05 08:59 UTC, dorimedini-starkware requested changes
> Reviewed 10 of 22 files at r8, 4 of 10 files at r9, 1 of 4 files at r10, 52 of 52 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 58 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LIPG-Zrmdp5CSoMP:-O3WjYNbBT3azFddbK9X:b-hzgnpg) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L58)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

It is a nice utility for creating a config. We also use it for testing purposes. If I move it, I will need to create a config for testing.
</blockquote></details>

worth it IMO.
this config concept is designed to be user-defined.
can you open a separate PR for it?
(ot can be *above* this one if it helps things along, but in that case please add a TODO here)
___
*[`crates/starknet_committer/src/patricia_merkle_tree/node.rs` line 0 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3WkdwU5Rwm4C4ALjkv:-O3WkdwU5Rwm4C4ALjkw:b-52or9y) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ed4d6779af54ee39b56379a70b473f6fe27e6ae/crates/starknet_committer/src/patricia_merkle_tree/node.rs#L0)):*
delete this function
___
*[`crates/starknet_committer/src/forest/skeleton_forest_test.rs` line 299 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3WkHbpAHEr_6T2nRq0:-O3WkHbpAHEr_6T2nRq1:b-fxzv0m) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ed4d6779af54ee39b56379a70b473f6fe27e6ae/crates/starknet_committer/src/forest/skeleton_forest_test.rs#L299)):*
> ```XML
> 
>     use super::original_skeleton_forest::OriginalSkeletonForest;
>     use crate::forest::original_skeleton_forest::ForestSortedIndices;
> ```

move to top



_Code quote:_
```XML
    use committer::storage::map_storage::MapStorage;

    use super::original_skeleton_forest::OriginalSkeletonForest;
    use crate::forest::original_skeleton_forest::ForestSortedIndices;
```


<!-- Sent from Reviewable.io -->

2024-08-05 12:05 UTC, dorimedini-starkware reviewed
> Reviewed 5 of 63 files at r12, 10 of 22 files at r13, 4 of 10 files at r14, 1 of 4 files at r15, 52 of 57 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-06 07:22 UTC, dorimedini-starkware requested changes
> Reviewed 61 of 63 files at r17, 9 of 22 files at r18, 4 of 10 files at r19, 1 of 4 files at r20, 54 of 59 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 7 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3aXz9c8XG_xKk-Yfdp:-O3aXz9c8XG_xKk-Yfdq:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1aee3b4bd8773d82cb8fc626fdc5b9095e695b/crates/committer/Cargo.toml#L7)):*
> ```TOML
> repository.workspace = true
> license-file.workspace = true
> description = "Computes hash of patricia tree."
> ```





_Suggestion:_
```TOML
description = "Library for computing and updating Patricia trees."
```
___
*[`crates/committer/src/felt.rs` line 27 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3aY9X94XRNasoJqzvQ:-O3aY9X94XRNasoJqzvR:b-i2qp2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1aee3b4bd8773d82cb8fc626fdc5b9095e695b/crates/committer/src/felt.rs#L27)):*
> ```XML
>     ($wrapper:ty) => {
>         impl $wrapper {
>             #[allow(dead_code)]
> ```

why would a `pub fn` need this annotation...?



_Code quote:_
```XML
 #[allow(dead_code)]
```


<!-- Sent from Reviewable.io -->

2024-08-07 07:40 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: 70 of 73 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 7 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3aXz9c8XG_xKk-Yfdp:-O3flSeP9NRRctZCJAcg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1aee3b4bd8773d82cb8fc626fdc5b9095e695b/crates/committer/Cargo.toml#L7)):*
> ```TOML
> repository.workspace = true
> license-file.workspace = true
> description = "Computes hash of patricia tree."
> ```

Done.
___
*[`crates/committer/src/felt.rs` line 27 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3aY9X94XRNasoJqzvQ:-O3fl_oR0ld3YqJq3CUp:bw6az22) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1aee3b4bd8773d82cb8fc626fdc5b9095e695b/crates/committer/src/felt.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why would a `pub fn` need this annotation...?
</blockquote></details>

It's not. I changed it to bre pub and forgot to remove the macro.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 58 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LIPG-Zrmdp5CSoMP:-O3YtaHfAP4-OBik3HsH:b-jb1yp3) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

worth it IMO.
this config concept is designed to be user-defined.
can you open a separate PR for it?
(ot can be *above* this one if it helps things along, but in that case please add a TODO here)
</blockquote></details>

I added TODO since it is a big PR, and it is better to merge quickly
___
*[`crates/starknet_committer/src/patricia_merkle_tree/node.rs` line  at r11](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3WkdwU5Rwm4C4ALjkv:-O3Yt3aa6XLoh87Fyyhb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ed4d6779af54ee39b56379a70b473f6fe27e6ae/crates/starknet_committer/src/patricia_merkle_tree/node.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete this function
</blockquote></details>

Done.
___
*[`crates/starknet_committer/src/forest/skeleton_forest_test.rs` line 299 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3WkHbpAHEr_6T2nRq0:-O3YtQgXE99mR6vdAt_U:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ed4d6779af54ee39b56379a70b473f6fe27e6ae/crates/starknet_committer/src/forest/skeleton_forest_test.rs#L299)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move to top
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-07 09:59 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r22, 5 of 63 files at r23, 9 of 22 files at r24, 4 of 10 files at r25, 1 of 4 files at r26, 52 of 58 files at r27, 2 of 2 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 58 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LIPG-Zrmdp5CSoMP:-O3gGk7q46aBDkkCWNZ9:ba5kh82) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L58)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I added TODO since it is a big PR, and it is better to merge quickly
</blockquote></details>

where is the todo?
___
*[`crates/starknet_committer/src/lib.rs` line 1 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3gGgX_6NrOpX7ONxS9:-O3gGgX_6NrOpX7ONxSA:b354p86) ([raw file](https://github.com/starkware-libs/sequencer/blob/7875769760a3da883ec93b063f8cd9c78f57dc4f/crates/starknet_committer/src/lib.rs#L1)):*
> ```XML
> #![allow(rustdoc::bare_urls)]
> ```

what's this?



_Code quote:_
```XML
#![allow(rustdoc::bare_urls)]
```


<!-- Sent from Reviewable.io -->

2024-08-07 11:11 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 58 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O38LIPG-Zrmdp5CSoMP:-O3gWZB71P_MEPFJ-MkA:b-jmgfpw) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f60cc8abcfa001ed8c66adb408add92b7552669/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is the todo?
</blockquote></details>

here 
https://github.com/starkware-libs/sequencer/blob/7875769760a3da883ec93b063f8cd9c78f57dc4f/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L19
___
*[`crates/starknet_committer/src/lib.rs` line 1 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3gGgX_6NrOpX7ONxS9:-O3gWaP85587SLA_cl9w:b-gb1iak) ([raw file](https://github.com/starkware-libs/sequencer/blob/7875769760a3da883ec93b063f8cd9c78f57dc4f/crates/starknet_committer/src/lib.rs#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

Its for allowing url in comments.
For example:
https://github.com/starkware-libs/sequencer/blob/7875769760a3da883ec93b063f8cd9c78f57dc4f/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L19.
Otherwise, cargo doc fails


<!-- Sent from Reviewable.io -->

2024-08-07 11:23 UTC, dorimedini-starkware reviewed
> Reviewed 17 of 63 files at r29, 9 of 22 files at r30, 4 of 10 files at r31, 1 of 4 files at r32, 53 of 58 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-07 11:28 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/starknet_committer/src/lib.rs` line 1 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/154#-O3gGgX_6NrOpX7ONxS9:-O3gZcReA3eFIVbOsJqJ:b-ss4b2o) ([raw file](https://github.com/starkware-libs/sequencer/blob/7875769760a3da883ec93b063f8cd9c78f57dc4f/crates/starknet_committer/src/lib.rs#L1)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Its for allowing url in comments.
For example:
https://github.com/starkware-libs/sequencer/blob/7875769760a3da883ec93b063f8cd9c78f57dc4f/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L19.
Otherwise, cargo doc fails
</blockquote></details>

please convert the URLs to hyperlinks and remove this attribute


<!-- Sent from Reviewable.io -->

2024-08-07 11:51 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154#-:-O3geqis0R9Yz37KENUO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-07 12:25 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-07 12:56 UTC, dorimedini-starkware approved these changes
> Reviewed 5 of 63 files at r36, 9 of 22 files at r37, 4 of 10 files at r38, 1 of 4 files at r39, 53 of 58 files at r40, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-07 14:08 UTC, dorimedini-starkware reviewed
> Reviewed 62 of 63 files at r41, 1 of 58 files at r45.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: 7 of 73 files reviewed, all discussions resolved (waiting on @amosStarkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-07 14:10 UTC, dorimedini-starkware approved these changes
> Reviewed 9 of 22 files at r42, 4 of 10 files at r43, 1 of 4 files at r44, 52 of 58 files at r45, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/154)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-07 14:31 UTC, merged