chore: clearify messages on protoc usage in papyrus_protobuf
starkware-libs/sequencer pull request #1565
Opened 2024-10-27 09:27 UTC by AlonLStarkWare

2024-10-27 09:27 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1565)
<!-- Reviewable:end -->

2024-10-27 09:27 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1565)
<!-- Reviewable:end -->

2024-10-27 10:04 UTC, ShahakShama requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1565)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_protobuf/build.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1565#-OACQdFW9Qzk6s6GSdbu:-OACQdFW9Qzk6s6GSdbv:bh52rwc) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d30aede571f7d00542b682e6c73e63dd5ddd7c0/crates/papyrus_protobuf/build.rs#L44)):*
> ```XML
>     if get_valid_preinstalled_protoc_version().is_none() {
>         println!(
>             "Protoc is not installed locally. Adding a prebuilt protoc binary via gh actions \
> ```

Please remove the word locally


<!-- Sent from Reviewable.io -->

2024-10-27 16:17 UTC, AlonLStarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1565)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/build.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1565#-OACQdFW9Qzk6s6GSdbu:-OADkz0S1bkZNCJA3P_I:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d30aede571f7d00542b682e6c73e63dd5ddd7c0/crates/papyrus_protobuf/build.rs#L44)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Please remove the word locally
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-30 07:59 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1565#-:-OARQvwV1XfOSSprZxxN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)



<!-- Sent from Reviewable.io -->

2024-10-30 09:29 UTC, merged