chore(config): add explicit usage of field separator
starkware-libs/sequencer pull request #1586
Opened 2024-10-27 21:03 UTC by Itay-Tsabary-Starkware

**Stack**:
- #1585
- #1584

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-10-27 21:03 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1586)
<!-- Reviewable:end -->

2024-10-29 13:26 UTC, lev-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1586)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_config/src/dumping.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1586#-OANRnvyAh6bj5c0PH2r:-OANRnvyAh6bj5c0PH2s:bncrg4p) ([raw file](https://github.com/starkware-libs/sequencer/blob/73efd7f498f05c5c735a7f996c974499170cf4fe/crates/papyrus_config/src/dumping.rs#L53)):*
> ```XML
>     SerializedContent,
>     SerializedParam,
>     FIELD_SEPARATOR,
> ```

If I remember correctly, the field separator in JSON names could be only '.' So, I don't see any need for this constant.


<!-- Sent from Reviewable.io -->

2024-10-29 14:40 UTC, lev-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1586#-:-OANiBCj671Q7L-6ifmq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-29 15:35 UTC, Itay-Tsabary-Starkware reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1586)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-07 08:05 UTC, closed without merging