build(blockifier_reexecution): add trait consecutive_state_readers
starkware-libs/sequencer pull request #1648
Opened 2024-10-29 12:48 UTC by aner-starkware

2024-10-29 12:48 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1648)
<!-- Reviewable:end -->

2024-10-29 15:38 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1648)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1648#-OANvGJTBo4X9zTo7cVN:-OANvGJTBo4X9zTo7cVO:b3iyvin) ([raw file](https://github.com/starkware-libs/sequencer/blob/f7f08d895a7894649050e4a702b46a8ddcbb5c36/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L243)):*
> ```XML
> 
>     fn get_next_block_state_diff(&self) -> ReexecutionResult<CommitmentStateDiff>;
> }
> ```

please doc this trait (is what I wrote correct?)



_Suggestion:_
```XML
/// Expands on the `StateReader` trait by adding more state-related queries required for reexecution.
pub trait ConsecutiveStateReaders<S: StateReader> {
    fn get_transaction_executor(
        self,
        transaction_executor_config: Option<TransactionExecutorConfig>,
    ) -> ReexecutionResult<TransactionExecutor<S>>;

    fn get_next_block_txs(&self) -> ReexecutionResult<Vec<BlockifierTransaction>>;

    fn get_next_block_state_diff(&self) -> ReexecutionResult<CommitmentStateDiff>;
}
```


<!-- Sent from Reviewable.io -->

2024-10-29 18:15 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1648)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1648#-OANvGJTBo4X9zTo7cVN:-OAOUKXW5hWioY1klaUd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f7f08d895a7894649050e4a702b46a8ddcbb5c36/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L243)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please doc this trait (is what I wrote correct?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-30 09:17 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1648#-:-OARhmD989lAWUm0upnm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2024-10-30 12:19 UTC, merged