chore(sequencer_node): drop redundant chain_id field from config
starkware-libs/sequencer pull request #1664
Opened 2024-10-29 15:06 UTC by Itay-Tsabary-Starkware

2024-10-29 15:06 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1664)
<!-- Reviewable:end -->

2024-10-30 08:22 UTC, yair-starkware approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1664)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2024-10-30 11:10 UTC, alonh5 requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1664)* status: all files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/config/node_config.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1664#-OAS5Y0FBGbIJS-odcE9:-OAS5Y0GEvyJ3yhjSWs8:bpedaxo) ([raw file](https://github.com/starkware-libs/sequencer/blob/20ae1809b6839ca36e030ce18342d5fc54281713/crates/mempool_node/src/config/node_config.rs#L57)):*
> ```XML
> pub struct SequencerNodeConfig {
>     /// The [chain id](https://docs.rs/starknet_api/latest/starknet_api/core/struct.ChainId.html) of the Starknet network.
>     #[validate(custom = "validate_ascii")]
> ```

Now that this is removed from here, is this ascii validation happening in the pointer?



_Code quote:_
```XML
#[validate(custom = "validate_ascii")]
```
___
*[`crates/tests-integration/src/integration_test_config_utils.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1664#-OAS6MKz5vgMc1vDxWVN:-OAS6MKz5vgMc1vDxWVO:b-7ewfcq) ([raw file](https://github.com/starkware-libs/sequencer/blob/277aac91c2c8707fe76062f877ba5896f1dba9d7/crates/tests-integration/src/integration_test_config_utils.rs#L66)):*
> ```XML
>             .chain_info
>             .fee_token_addresses
>             .strk_fee_token_address,
> ```

Related to this PR?



_Code quote:_
```XML
        config
            .batcher_config
            .block_builder_config
            .chain_info
            .fee_token_addresses
            .eth_fee_token_address,
        config
            .batcher_config
            .block_builder_config
            .chain_info
            .fee_token_addresses
            .strk_fee_token_address,
```
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1664#-OAS6WckAs-SwAGWdZyl:-OAS6WckAs-SwAGWdZym:b-xm1m29) ([raw file](https://github.com/starkware-libs/sequencer/blob/277aac91c2c8707fe76062f877ba5896f1dba9d7/crates/tests-integration/src/integration_test_utils.rs#L40)):*
> ```XML
> 
> // TODO(Tsabary): As the number of required parameters grow, bundle them in a struct and modify the
> // return type.
> ```

Is this todo meant to be over the `create_integration_test_config` function?



_Code quote:_
```XML
// TODO(Tsabary): As the number of required parameters grow, bundle them in a struct and modify the
// return type.
```
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1664#-OAS6DT-CO3rn-Jy5Z5R:-OAS6DT02LSow1_Ruqp7:binvy60) ([raw file](https://github.com/starkware-libs/sequencer/blob/277aac91c2c8707fe76062f877ba5896f1dba9d7/crates/tests-integration/src/integration_test_utils.rs#L76)):*
> ```XML
> }
> 
> pub async fn create_integration_test_config(
> ```

Can you share the code between the functions?


<!-- Sent from Reviewable.io -->

2024-10-30 14:14 UTC, Itay-Tsabary-Starkware commented
Closing pull request: commit has gone away

2024-10-30 14:14 UTC, closed without merging