chore(sequencer_node): add cli_args to test util + general cleanup
starkware-libs/sequencer pull request #1709
Opened 2024-10-31 07:50 UTC by Itay-Tsabary-Starkware

**Stack**:
- #1708
- #1707
- #1706
- #1701

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-10-31 07:50 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1709)
<!-- Reviewable:end -->

2024-11-03 06:14 UTC, nadin-Starkware requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1709)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/config/test_utils.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1709#-OAgjCgK1pn67MvkLvif:-OAgjCgK1pn67MvkLvig:b4atsqm) ([raw file](https://github.com/starkware-libs/sequencer/blob/e01b741cc961ce9cfe89b01b5ae27c0fbb250b3d/crates/mempool_node/src/config/test_utils.rs#L23)):*
> ```XML
>         // Verify all arguments and their values are present.
>         assert!(args.len() == Self::field_names().len() * 2, "Missing required parameters.");
>         args
> ```

Consider modifying this to iterate over the fields, or add a TODO note for future enhancement.



_Code quote:_
```XML
        let args = vec!["--chain_id".to_string(), self.chain_id.to_string()];
        // Verify all arguments and their values are present.
        assert!(args.len() == Self::field_names().len() * 2, "Missing required parameters.");
        args
```


<!-- Sent from Reviewable.io -->

2024-11-03 07:21 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1709)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/test_utils.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1709#-OAgjCgK1pn67MvkLvif:-OAktKAW7Gg_6UF8KJ_e:bsq6p3m) ([raw file](https://github.com/starkware-libs/sequencer/blob/e01b741cc961ce9cfe89b01b5ae27c0fbb250b3d/crates/mempool_node/src/config/test_utils.rs#L23)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Consider modifying this to iterate over the fields, or add a TODO note for future enhancement.
</blockquote></details>

There is a similar note in https://reviewable.io/reviews/starkware-libs/sequencer/1725, where two other fields are introduced.


<!-- Sent from Reviewable.io -->

2024-11-03 09:06 UTC, merged

2024-11-03 09:17 UTC, nadin-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1709)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->