feat: allow StreamHandler to use a generic StreamId
starkware-libs/sequencer pull request #1714
Opened 2024-10-31 11:38 UTC by guy-starkware

The stream ID is used to uniquely separate streams coming from the same peer. In the use case of consensus, this can be the `(height, round)` we are in. 

In general, the `stream_id` should be convertible into a `Vec<u8>>` and should have some other traits like `Display` and `Clone`, etc.

2024-10-31 11:38 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1714)
<!-- Reviewable:end -->

2024-12-25 09:28 UTC, guy-starkware commented
* **#1714** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1714?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1714?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-05 18:01 UTC, matan-starkware requested changes
> Reviewed 9 of 20 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1714)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @guy-starkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFraZr31pISKYfMWKZK:-OFraZr31pISKYfMWKZL:b3kre):*
?



_Code quote:_
```
- 5fb24ed: fix: update StreamHandler to use new StreamHashMap interface
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 389 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFrYijk2MO4OuiPjnqB:-OFrYijk2MO4OuiPjnqC:b-hyoy0j) ([raw file](https://github.com/starkware-libs/sequencer/blob/4633b922afbfedba2a83b3a7fe082f46aa52828d/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L389)):*
> ```XML
>     // Tries to drain as many messages as possible from the buffer (in order),
>     // DOES NOT guarantee that the buffer will be empty after calling this function.
>     // Returns true if the receiver for this stream is dropped.
> ```

Why was this removed?



_Code quote:_
```XML
    // Returns true if the receiver for this stream is dropped.
```
___
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFrbGe8D59PX4DKlmJ-:-OFrbGe8D59PX4DKlmJ0:b-5cfpft) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fb24ed3956f73a42fb99646b35f809302e9c472/crates/papyrus_protobuf/src/converters/consensus.rs#L86)):*
> ```XML
>     T: Into<Vec<u8>> + TryFrom<Vec<u8>, Error = ProtobufConversionError>,
>     StreamId: Into<Vec<u8>> + TryFrom<Vec<u8>, Error = ProtobufConversionError> + Clone,
> > TryFrom<protobuf::StreamMessage> for StreamMessage<T, StreamId>
> ```

Please switch to `where` clause everywhere that the template goes over 1 line.



_Code quote:_
```XML
impl<
    T: Into<Vec<u8>> + TryFrom<Vec<u8>, Error = ProtobufConversionError>,
    StreamId: Into<Vec<u8>> + TryFrom<Vec<u8>, Error = ProtobufConversionError> + Clone,
> TryFrom<protobuf::StreamMessage> for StreamMessage<T, StreamId>
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFrWg0P58sBTKAeF_tl:-OFrWg0P58sBTKAeF_tm:bygfv7c) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fb24ed3956f73a42fb99646b35f809302e9c472/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L45)):*
> ```XML
>         + Unpin
>         + Display
>         + Debug,
> ```

This repeats a bunch so maybe do

```
trait StraimIdTrait: ...;  // Long list

StreamId: StreamIdTrait
```

I kinda think the same thing for `T`. Maybe rename that to StreamContent



_Suggestion:_
```XML
    StreamId: Into<Vec<u8>>
        + TryFrom<Vec<u8>, Error = ProtobufConversionError>
        + Eq
        + Hash
        + Clone
        + Unpin
        + Display
        + Debug + Send,
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFr__6g5OQ8zntu11eo:-OFr__6g5OQ8zntu11ep:b6y7w1l) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fb24ed3956f73a42fb99646b35f809302e9c472/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L25)):*
> ```XML
> 
> #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
> struct TestStreamId(u64);
> ```

It feels wrong to me that we can't just use `u64` directly as a stream ID. I presume though that this would require much more complexity to support though?
1. Network deals in Vec<u8> so we need to put the converter somewhere
2. Error type would need to become generic...



_Code quote:_
```XML
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
struct TestStreamId(u64);
```
___
*[`crates/papyrus_protobuf/src/converters/test_instances.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFrc2yy1rfrV0bsMQF9:-OFrc2yy1rfrV0bsMQFA:b-6hod8q) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fb24ed3956f73a42fb99646b35f809302e9c472/crates/papyrus_protobuf/src/converters/test_instances.rs#L55)):*
> ```XML
> 
> #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
> pub struct TestStreamId(pub u64);
> ```

Can you reuse this in the consensus crate instead of redefining TestStreamId there? Maybe under feature flag "testing"



_Code quote:_
```XML
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TestStreamId(pub u64);
```


<!-- Sent from Reviewable.io -->

2025-01-06 09:11 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1714)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @matan-starkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFraZr31pISKYfMWKZK:-OFudKOPBI__i4Y2Y-bX:b-ebdyir):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

oops, that's an old commit message. I'll update it. 
___
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFrbGe8D59PX4DKlmJ-:-OFueF6kDmaPo7-PVdNw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fb24ed3956f73a42fb99646b35f809302e9c472/crates/papyrus_protobuf/src/converters/consensus.rs#L86)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Please switch to `where` clause everywhere that the template goes over 1 line.
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/test_instances.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFrc2yy1rfrV0bsMQF9:-OFueSFNA6jcq9fUr6mr:b96qbxf) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fb24ed3956f73a42fb99646b35f809302e9c472/crates/papyrus_protobuf/src/converters/test_instances.rs#L55)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can you reuse this in the consensus crate instead of redefining TestStreamId there? Maybe under feature flag "testing"
</blockquote></details>

I'm not sure what you mean? If it is only for testing then what is the "reuse" of it in another crate? You mean to be able to use it for tests in other crates? (should it be public, as well?)
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFrWg0P58sBTKAeF_tl:-OFueshf1FAyrjB3BV_T:b-nw5tz2) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fb24ed3956f73a42fb99646b35f809302e9c472/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L45)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This repeats a bunch so maybe do

```
trait StraimIdTrait: ...;  // Long list

StreamId: StreamIdTrait
```

I kinda think the same thing for `T`. Maybe rename that to StreamContent
</blockquote></details>

I didn't know we could do that! That could save me so much space in the proto crate, too... 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 389 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFrYijk2MO4OuiPjnqB:-OFuqo895sRSu2LWXjYs:b-z7gidb) ([raw file](https://github.com/starkware-libs/sequencer/blob/4633b922afbfedba2a83b3a7fe082f46aa52828d/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L389)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why was this removed?
</blockquote></details>

Good question. Returning it. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFr__6g5OQ8zntu11eo:-OFuqu_1E-73DFlT72rP:b-ns3dhd) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fb24ed3956f73a42fb99646b35f809302e9c472/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L25)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

It feels wrong to me that we can't just use `u64` directly as a stream ID. I presume though that this would require much more complexity to support though?
1. Network deals in Vec<u8> so we need to put the converter somewhere
2. Error type would need to become generic...
</blockquote></details>

a) I don't know if it is even possible to directly receive u64. I wish I had a way to do it. 
b) I think each StreamId needs to have a converter. I added a concrete type (HeightAndRound) in the protobuf crate, and along with it wrote the converters. 
c) Why does it need a generic error? Is it not good enough to use ProtobufConversionError? 


<!-- Sent from Reviewable.io -->

2025-01-08 18:21 UTC, matan-starkware requested changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1714)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFrbGe8D59PX4DKlmJ-:-OG66-67CqzP5cGpBC1a:b6ijedi) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fb24ed3956f73a42fb99646b35f809302e9c472/crates/papyrus_protobuf/src/converters/consensus.rs#L86)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you forget to upload? I don't see the where clause
___
*[`crates/papyrus_protobuf/src/converters/test_instances.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OFrc2yy1rfrV0bsMQF9:-OG66ENyAymawpbWmXp6:boa1avv) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fb24ed3956f73a42fb99646b35f809302e9c472/crates/papyrus_protobuf/src/converters/test_instances.rs#L55)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

I'm not sure what you mean? If it is only for testing then what is the "reuse" of it in another crate? You mean to be able to use it for tests in other crates? (should it be public, as well?)
</blockquote></details>

You basically redefine this in stream_handler_test
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OG67hdC5S77oQjE3Ls0:-OG67hdC5S77oQjE3Ls1:ba8brnu) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac5127385f806ecca0c7e616cf49c4412d6059b8/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L32)):*
> ```XML
> 
> /// A combination of trait bounds needed for the content of the stream.
> pub trait StreamContent:
> ```

Let's be consistent with StreamIdTrait. And then we can switch `T` below to `StreamContent`. I don't really like T with more than 1 generic arg.

(I also have a preference for all generic args eng in T, StreamContentT, StreamIdT, but I think I'm alone on that).



_Suggestion:_
```XML
pub trait StreamContentTrait:
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OG67a11AFVZPpfMXQtC:-OG67a11AFVZPpfMXQtD:bnct90e) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac5127385f806ecca0c7e616cf49c4412d6059b8/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L39)):*
> ```XML
>     StreamContent for T
> {
> }
> ```

Compiles for me without the empty impl.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OG67Ykr5mMdJxF-QgvL:-OG67Ykr5mMdJxF-QgvM:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac5127385f806ecca0c7e616cf49c4412d6059b8/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L65)):*
> ```XML
> > StreamIdTrait for StreamId
> {
> }
> ```




<!-- Sent from Reviewable.io -->

2025-01-08 18:39 UTC, matan-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1714)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OG6C_8w6gpMQd1WQLiK:-OG6C_8x7OaJpgzJwBMZ:bfko683) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac5127385f806ecca0c7e616cf49c4412d6059b8/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L39)):*
> ```XML
>     StreamContent for T
> {
> }
> ```

I find the where clause more readable any time that you cannot fit the entire thing on one line.



_Suggestion:_
```XML
impl<T> StreamContent for T where
    T: Clone + Into<Vec<u8>> + TryFrom<Vec<u8>, Error = ProtobufConversionError> + Send
{
}
```


<!-- Sent from Reviewable.io -->

2025-01-09 14:36 UTC, matan-starkware approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1714)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1714#-OG67a11AFVZPpfMXQtC:-OGAUXBW1dZCFlOO4lBm:bi6ykqp) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac5127385f806ecca0c7e616cf49c4412d6059b8/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L39)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

I run into `the trait bound `papyrus_protobuf::consensus::ProposalPart: StreamContentTrait` is not satisfied` when trying to compile without it...
</blockquote></details>

Sorry, thought I withdrew this comment.


<!-- Sent from Reviewable.io -->

2025-01-09 14:48 UTC, guy-starkware reviewed
> Reviewed 7 of 20 files at r1, 2 of 11 files at r2, 2 of 8 files at r3, 3 of 3 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1714)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2025-01-12 10:17 UTC, guy-starkware reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1714)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2025-01-12 10:24 UTC, merged