test(starknet_api): chage default resource bounds to all
starkware-libs/sequencer pull request #1769
Opened 2024-11-03 15:03 UTC by TzahiTaub

2024-11-03 15:03 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1769)
<!-- Reviewable:end -->

2024-11-05 08:34 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1769)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 1162 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1769#-OAvSOPwCmhgqZupzMDI:-OAvSOPwCmhgqZupzMDJ:bmuzl0w) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ab043cae24df2a5e2dcd78fc240aaa65fc219e/crates/starknet_api/src/transaction.rs#L1162)):*
> ```XML
> 
>     #[cfg(any(feature = "testing", test))]
>     pub fn create_for_testing() -> Self {
> ```

even if one reads the implementation it's unclear that this is what's happening...
please rename



_Suggestion:_
```XML
pub fn create_for_testing_no_fee_enforcement()
```
___
*[`crates/starknet_api/src/transaction.rs` line 1163 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1769#-OAvS6PZ1fhrdOwWy-QD:-OAvS6PZ1fhrdOwWy-QE:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ab043cae24df2a5e2dcd78fc240aaa65fc219e/crates/starknet_api/src/transaction.rs#L1163)):*
> ```XML
>     #[cfg(any(feature = "testing", test))]
>     pub fn create_for_testing() -> Self {
>         let default_l2_gas_amount = GasAmount(10000000000); // Sufficient to avoid out of gas errors.
> ```





_Suggestion:_
```XML
GasAmount(DEFAULT_L2_GAS_MAX_AMOUNT)
```


<!-- Sent from Reviewable.io -->

2024-11-05 08:52 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1769)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 1162 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1769#-OAvSOPwCmhgqZupzMDI:-OAvUWOM5H4cGJZr188d:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ab043cae24df2a5e2dcd78fc240aaa65fc219e/crates/starknet_api/src/transaction.rs#L1162)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

even if one reads the implementation it's unclear that this is what's happening...
please rename
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/transaction.rs` line 1163 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1769#-OAvS6PZ1fhrdOwWy-QD:-OAvUjX28g1q8OhHHvr1:b-qil575) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ab043cae24df2a5e2dcd78fc240aaa65fc219e/crates/starknet_api/src/transaction.rs#L1163)):*
> ```XML
>     #[cfg(any(feature = "testing", test))]
>     pub fn create_for_testing() -> Self {
>         let default_l2_gas_amount = GasAmount(10000000000); // Sufficient to avoid out of gas errors.
> ```

Do you want me to define this as a const in the top of the file? This is only for testing so I don't think we should. And if you refer to the const in the blockifier, well, it's in the blockifier, and this is starknet_api.


<!-- Sent from Reviewable.io -->

2024-11-05 12:42 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1769#-:-OAwLB_i-UO7-O4-KaKy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 1163 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1769#-OAvS6PZ1fhrdOwWy-QD:-OAwL6dTE1odK2W_-vbj:b-g2pdh) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ab043cae24df2a5e2dcd78fc240aaa65fc219e/crates/starknet_api/src/transaction.rs#L1163)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Do you want me to define this as a const in the top of the file? This is only for testing so I don't think we should. And if you refer to the const in the blockifier, well, it's in the blockifier, and this is starknet_api.
</blockquote></details>

ahhh right... nvm


<!-- Sent from Reviewable.io -->

2024-11-05 21:35 UTC, merged