feat: add contract address in range validation
starkware-libs/sequencer pull request #1790
Opened 2024-11-04 13:40 UTC by ArniStarkware

2024-11-04 13:40 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1790)
<!-- Reviewable:end -->

2024-11-04 13:41 UTC, ArniStarkware commented
* **#1790** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1790?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-04 14:14 UTC, alonh5 requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1790)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/errors.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1790#-OArQmiYARXpaLIurGAp:-OArQmiYARXpaLIurGAq:b-cy1srg) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c66c7ec4f2e99438dd196942ba7ca7bdb450487/crates/gateway/src/errors.rs#L63)):*
> ```XML
>             | StatelessTransactionValidatorError::InvalidSierraVersion(..)
>             | StatelessTransactionValidatorError::SignatureTooLong { .. }
>             | StatelessTransactionValidatorError::StarknetApiError(_)
> ```

For consistency 



_Suggestion:_
```XML
StatelessTransactionValidatorError::StarknetApiError(..)
```
___
*[`crates/starknet_api/src/core.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1790#-OArTMfBCeI2vo14FJ3R:-OArTMfBCeI2vo14FJ3S:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c66c7ec4f2e99438dd196942ba7ca7bdb450487/crates/starknet_api/src/core.rs#L113)):*
> ```XML
> impl ContractAddress {
>     /// Validates the contract address is in the valid range for external access.
>     /// The lower bound is above the special saved addresses and the upper bound is ongruent with
> ```





_Suggestion:_
```XML
congruent
```
___
*[`crates/starknet_api/src/core.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1790#-OArV6O00yDloQt2Dun-:-OArV6O00yDloQt2Dun0:b-gp813f) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c66c7ec4f2e99438dd196942ba7ca7bdb450487/crates/starknet_api/src/core.rs#L115)):*
> ```XML
>     /// The lower bound is above the special saved addresses and the upper bound is ongruent with
>     /// the storage var address upper bound.
>     pub fn strict_validate_contract_address(&self) -> Result<(), StarknetApiError> {
> ```

I like that you implemented it as a method of `ContractAddress` - in that case the name doesn't have to include `contract_address`.
Regarding the `strict`, if we end up implementing a less strict version we can rename one of them, for now let's keep it simple.



_Suggestion:_
```XML
validate
```
___
*[`crates/starknet_api/src/core.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1790#-OArVnmq-YHzcgh-ZjCa:-OArVnmq-YHzcgh-ZjCb:bzegoiw) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c66c7ec4f2e99438dd196942ba7ca7bdb450487/crates/starknet_api/src/core.rs#L118)):*
> ```XML
>         let value = self.0.0;
>         let l2_address_upper_bound = Felt::from(*L2_ADDRESS_UPPER_BOUND);
>         if (BLOCK_HASH_TABLE_ADDRESS.0.0 < value) && (value < l2_address_upper_bound) {
> ```

Tested value should come first



_Suggestion:_
```XML
value > BLOCK_HASH_TABLE_ADDRESS.0.0
```


<!-- Sent from Reviewable.io -->

2024-11-05 08:13 UTC, ArniStarkware commented
### Merge activity

* **Nov 5, 3:13 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1790).

2024-11-05 08:14 UTC, merged