test(mempool): imp test-get-txs-returns-only-priority-txs
starkware-libs/sequencer pull request #1793
Opened 2024-11-04 14:03 UTC by MohammadNassar1

2024-11-04 14:04 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1793)
<!-- Reviewable:end -->

2024-11-04 16:07 UTC, ayeletstarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OArv8rf6Zq7CVAVf3PG:-OArv8rf6Zq7CVAVf3PH:b-eyfhy6) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac531387ded2a9bc248750f427ae5e38d2d6e802/crates/mempool/src/mempool_test.rs#L227)):*
> ```XML
>     let tx_address_1 = tx!(tx_hash: 2, address: "0x1");
> 
>     let priority_queue_txs = [&tx_address_0].map(TransactionReference::new);
> ```

I think you can delete the transaction in the priority queue since we just want to ensure that `get_txs` does not return transactions from the pending queue.



_Code quote:_
```XML
 let priority_queue_txs = [&tx_address_0].map(TransactionReference::new);
```


<!-- Sent from Reviewable.io -->

2024-11-04 16:09 UTC, ayeletstarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OArv8rf6Zq7CVAVf3PG:-OArvqdXBUw0g2MzGU6c:b-74vm1e) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac531387ded2a9bc248750f427ae5e38d2d6e802/crates/mempool/src/mempool_test.rs#L227)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think you can delete the transaction in the priority queue since we just want to ensure that `get_txs` does not return transactions from the pending queue.
</blockquote></details>

you can use `tx!()` after making this change


<!-- Sent from Reviewable.io -->

2024-11-04 16:26 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OArv8rf6Zq7CVAVf3PG:-OArzxVQBeLywi3mX5mJ:b-3taaf8) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac531387ded2a9bc248750f427ae5e38d2d6e802/crates/mempool/src/mempool_test.rs#L227)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

you can use `tx!()` after making this change
</blockquote></details>

Nice, updated!


<!-- Sent from Reviewable.io -->

2024-11-05 09:52 UTC, ayeletstarkware reviewed
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 222 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAvjCEN6QN0o1dmP3n1:-OAvjCEN6QN0o1dmP3n2:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9609a07f4980cf83bc506b33ffe59e50a236db76/crates/mempool/src/mempool_test.rs#L222)):*
> ```XML
> 
> #[rstest]
> fn test_get_txs_returns_above_gas_threshold() {
> ```





_Suggestion:_
```XML
test_get_txs_does_not_return_txs_below_gas_threshold
```
___
*[`crates/mempool/src/mempool_test.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAvjKgxAdBWK0BDm6vj:-OAvjKgxAdBWK0BDm6vk:bi2mfhj) ([raw file](https://github.com/starkware-libs/sequencer/blob/9609a07f4980cf83bc506b33ffe59e50a236db76/crates/mempool/src/mempool_test.rs#L236)):*
> ```XML
>     let expected_mempool_content =
>         MempoolContentBuilder::new().with_pending_queue(pending_queue_txs).build();
>     expected_mempool_content.assert_eq(&mempool);
> ```

Why is this necessary? 



_Code quote:_
```XML
    let expected_mempool_content =
        MempoolContentBuilder::new().with_pending_queue(pending_queue_txs).build();
    expected_mempool_content.assert_eq(&mempool);
```


<!-- Sent from Reviewable.io -->

2024-11-05 11:03 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 222 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAvjCEN6QN0o1dmP3n1:-OAvyeIK1Wou6aP4R5cm:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9609a07f4980cf83bc506b33ffe59e50a236db76/crates/mempool/src/mempool_test.rs#L222)):*
> ```XML
> 
> #[rstest]
> fn test_get_txs_returns_above_gas_threshold() {
> ```

Done
___
*[`crates/mempool/src/mempool_test.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAvjKgxAdBWK0BDm6vj:-OAvynWXDPBzXSL3NL6I:b-pumnnu) ([raw file](https://github.com/starkware-libs/sequencer/blob/9609a07f4980cf83bc506b33ffe59e50a236db76/crates/mempool/src/mempool_test.rs#L236)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why is this necessary?
</blockquote></details>

Here, I want to verify that after calling `get_txs`, the transaction remains in the queue and hasn't been removed or moved to the staging area. 
Note that this is not the primary purpose of the test; the main check is to ensure that `get_txs` does not return pending transactions.


<!-- Sent from Reviewable.io -->

2024-11-05 11:36 UTC, ayeletstarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-:-OAw64Pn-3GMpTPB0-3P:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAvjKgxAdBWK0BDm6vj:-OAw5yM69MpBPIWKadVx:bwvm1sb) ([raw file](https://github.com/starkware-libs/sequencer/blob/9609a07f4980cf83bc506b33ffe59e50a236db76/crates/mempool/src/mempool_test.rs#L236)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Here, I want to verify that after calling `get_txs`, the transaction remains in the queue and hasn't been removed or moved to the staging area. 
Note that this is not the primary purpose of the test; the main check is to ensure that `get_txs` does not return pending transactions.
</blockquote></details>

yep, that's why i'm not sure it's necessary, but up to you


<!-- Sent from Reviewable.io -->

2024-11-05 11:55 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAvjKgxAdBWK0BDm6vj:-OAwAFO73otOhl7HfVpN:bf543on) ([raw file](https://github.com/starkware-libs/sequencer/blob/9609a07f4980cf83bc506b33ffe59e50a236db76/crates/mempool/src/mempool_test.rs#L236)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

yep, that's why i'm not sure it's necessary, but up to you
</blockquote></details>

I prefer to keep it, as I see a similar check in `test_get_txs_with_nonce_gap`.


<!-- Sent from Reviewable.io -->

2024-11-05 12:21 UTC, elintul requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAvjKgxAdBWK0BDm6vj:-OAwEX_L2tKQpehcbxYq:bn3fx3p) ([raw file](https://github.com/starkware-libs/sequencer/blob/9609a07f4980cf83bc506b33ffe59e50a236db76/crates/mempool/src/mempool_test.rs#L236)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I prefer to keep it, as I see a similar check in `test_get_txs_with_nonce_gap`.
</blockquote></details>

I agree with Ayelet. There's a dedicated test that checks transactions aren't deleted in `get_txs`. Note that there's no actual staging area per se, it's confusing to refer to "`get_txs` only does soft deletions" feature this way.
___
*[`crates/mempool/src/mempool_test.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAwDqW97zmpCKwkMuAO:-OAwDqW97zmpCKwkMuAP:b-o0dmpy) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b7f1c279084424793240c10fea0e921e932f414/crates/mempool/src/mempool_test.rs#L222)):*
> ```XML
> 
> #[rstest]
> fn test_get_txs_does_not_return_txs_below_gas_threshold() {
> ```

I'd rather go with your better more behavioral name, but note you're not using anything related to gas price, so it might be confusing. Best that test name and content be consistent.



_Suggestion:_
```XML
_pending_txs
```
___
*[`crates/mempool/src/mempool_test.rs` line 232 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAwE7LF4DnkgYbsPt_8:-OAwE7LGEY2oM7YQ0AkK:bsuu1il) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b7f1c279084424793240c10fea0e921e932f414/crates/mempool/src/mempool_test.rs#L232)):*
> ```XML
>         .build_into_mempool();
> 
>     // Test and assert: pending transactions are not returned.
> ```

No need, test is simple enough and you're repeating the name.



_Suggestion:_
```XML
// Test and assert.
```


<!-- Sent from Reviewable.io -->

2024-11-05 12:43 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAvjKgxAdBWK0BDm6vj:-OAwKCoW9HJxR-PvJf0Z:bl64zq1) ([raw file](https://github.com/starkware-libs/sequencer/blob/9609a07f4980cf83bc506b33ffe59e50a236db76/crates/mempool/src/mempool_test.rs#L236)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I agree with Ayelet. There's a dedicated test that checks transactions aren't deleted in `get_txs`. Note that there's no actual staging area per se, it's confusing to refer to "`get_txs` only does soft deletions" feature this way.
</blockquote></details>

Deleted, test updated.
___
*[`crates/mempool/src/mempool_test.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAwDqW97zmpCKwkMuAO:-OAwKTiZ-et0a0qkDY_k:byy5o0) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b7f1c279084424793240c10fea0e921e932f414/crates/mempool/src/mempool_test.rs#L222)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'd rather go with your better more behavioral name, but note you're not using anything related to gas price, so it might be confusing. Best that test name and content be consistent.
</blockquote></details>

Updated.

I agree that test name and content be consistent.
But, I thought pending is a design detail, and cannot be used in test name. While gas price threshold is not a design detail (we have an API that updates the threshold).
___
*[`crates/mempool/src/mempool_test.rs` line 232 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAwE7LF4DnkgYbsPt_8:-OAwJy1k-7qoeOTZ46dA:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b7f1c279084424793240c10fea0e921e932f414/crates/mempool/src/mempool_test.rs#L232)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No need, test is simple enough and you're repeating the name.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-05 12:44 UTC, ayeletstarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-:-OAwLoR91QdLb6jpSqP3:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2024-11-05 12:53 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-:-OAwNjT82gTvMCR7oLNK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1793#-OAwDqW97zmpCKwkMuAO:-OAwN_nI3wlH0eDkTOLA:b-jp5crx) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b7f1c279084424793240c10fea0e921e932f414/crates/mempool/src/mempool_test.rs#L222)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Updated.

I agree that test name and content be consistent.
But, I thought pending is a design detail, and cannot be used in test name. While gas price threshold is not a design detail (we have an API that updates the threshold).
</blockquote></details>

I agree, explained my considerations regardless.


<!-- Sent from Reviewable.io -->

2024-11-05 12:57 UTC, merged