refactor(mempool): pass sorted txs explicitly
starkware-libs/sequencer pull request #1816
Opened 2024-11-05 08:35 UTC by MohammadNassar1

2024-11-05 08:35 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1816)
<!-- Reviewable:end -->

2024-11-05 12:53 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OAwMyj04GV45eDmVFJ3:-OAwMyj04GV45eDmVFJ4:b-ttr0l4) ([raw file](https://github.com/starkware-libs/sequencer/blob/3338b433ab2f06bdb805db2e26aa8f235bf7c6ce/crates/mempool/src/mempool_test.rs#L211)):*
> ```XML
> 
>     // Check that the returned transactions are the ones with the highest priority.
>     let (expected_fetched_txs, remaining_txs) = pool_txs.split_at(fetched_txs.len());
> ```

I think using this is confusing because it’s hard to notice it’s sorted, and you’re cloning the instance to use it here. Consider creating a separate 'sorted_txs' instance instead.



_Code quote:_
```XML
pool_txs
```
___
*[`crates/mempool/src/mempool_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OAwKRVmCWNymjrnsbgr:-OAwKRVmCWNymjrnsbgs:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3338b433ab2f06bdb805db2e26aa8f235bf7c6ce/crates/mempool/src/mempool_test.rs#L216)):*
> ```XML
>     // Assert: non-returned transactions are still in the mempool.
>     let remaining_tx_references = remaining_txs.iter().map(TransactionReference::new);
>     let mempool_content =
> ```





_Suggestion:_
```XML
expected_mempool_content
```


<!-- Sent from Reviewable.io -->

2024-11-05 12:57 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OAwNwJjBXXjRIsWy0cR:-OAwNwJkDqg2XbqTyUCN:b63didx) ([raw file](https://github.com/starkware-libs/sequencer/blob/3338b433ab2f06bdb805db2e26aa8f235bf7c6ce/crates/mempool/src/mempool_test.rs#L289)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx(mut mempool: Mempool) {
> ```

I  still think this test checks an implementation detail, and we should only verify that the transactions are inserted into the mempool's structures. But if you decide to keep it, consider renaming it to this



_Suggestion:_
```XML
test_add_tx_inserts_txs_by_their_priority
```


<!-- Sent from Reviewable.io -->

2024-11-05 15:57 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OAwMyj04GV45eDmVFJ3:-OAx0f1q92LNdpvGZK7w:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3338b433ab2f06bdb805db2e26aa8f235bf7c6ce/crates/mempool/src/mempool_test.rs#L211)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think using this is confusing because it’s hard to notice it’s sorted, and you’re cloning the instance to use it here. Consider creating a separate 'sorted_txs' instance instead.
</blockquote></details>

Done
___
*[`crates/mempool/src/mempool_test.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OAwNwJjBXXjRIsWy0cR:-OAx0qTK4QYjeZ31CjlW:banao72) ([raw file](https://github.com/starkware-libs/sequencer/blob/3338b433ab2f06bdb805db2e26aa8f235bf7c6ce/crates/mempool/src/mempool_test.rs#L289)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I  still think this test checks an implementation detail, and we should only verify that the transactions are inserted into the mempool's structures. But if you decide to keep it, consider renaming it to this
</blockquote></details>

Agree, it's important to discuss whether we need to keep these tests. Let's address this in our team sync meeting. 

For now, I think we can proceed with merging this PR. 
Re test name: it has been changed in [another](https://reviewable.io/reviews/starkware-libs/sequencer/1509) PR, so we can discuss it there.


<!-- Sent from Reviewable.io -->

2024-11-07 09:30 UTC, ayeletstarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-:-OB4xXOd1jQCHIFOEur0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-11-07 13:57 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OB5uLwGE1QJZA8p6Gyk:-OB5uLwHEEHdLSjrTX0V:bpk4caa) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dccd690ea4ec27ec463aab7277cff3b7ef75c0/crates/mempool/src/mempool_test.rs#L182)):*
> ```XML
> #[case::test_get_more_than_all_eligible_txs(5)]
> #[case::test_get_less_than_all_eligible_txs(2)]
> fn test_get_txs_returns_by_priority_order(#[case] n_requested_txs: usize) {
> ```

Should the word "hash" appear in the name? It doesn't affect the test flow, only there for uniqueness. 


<!-- Sent from Reviewable.io -->

2024-11-07 14:19 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OB5uLwGE1QJZA8p6Gyk:-OB5zFMw14oYG3rc_L3x:b-o9y993) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dccd690ea4ec27ec463aab7277cff3b7ef75c0/crates/mempool/src/mempool_test.rs#L182)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Should the word "hash" appear in the name? It doesn't affect the test flow, only there for uniqueness.
</blockquote></details>

I included the hash because it's one of the elements in the priority ordering.


<!-- Sent from Reviewable.io -->

2024-11-10 06:38 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OB5uLwGE1QJZA8p6Gyk:-OBJmfOxEHdGp_Y9bBJJ:blm7fyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dccd690ea4ec27ec463aab7277cff3b7ef75c0/crates/mempool/src/mempool_test.rs#L182)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I included the hash because it's one of the elements in the priority ordering.
</blockquote></details>

Not really, it's overridden by the tip. I reckon hash is irrelevant for priority and only used for uniqueness here, so might by confusing to the reader.


<!-- Sent from Reviewable.io -->

2024-11-10 10:47 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OB5uLwGE1QJZA8p6Gyk:-OBKfm5P4oodvdmRQV5n:b-jrujs0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dccd690ea4ec27ec463aab7277cff3b7ef75c0/crates/mempool/src/mempool_test.rs#L182)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not really, it's overridden by the tip. I reckon hash is irrelevant for priority and only used for uniqueness here, so might by confusing to the reader.
</blockquote></details>

Sounds good to me.
Updated.


<!-- Sent from Reviewable.io -->

2024-11-10 12:00 UTC, ayeletstarkware approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-11-14 07:44 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OB5uLwGE1QJZA8p6Gyk:-OBdcDSRAa83svrnIOoK:b-lvowdd) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dccd690ea4ec27ec463aab7277cff3b7ef75c0/crates/mempool/src/mempool_test.rs#L182)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Sounds good to me.
Updated.
</blockquote></details>

Please fix in other test as well, no difference between them (in both, `tip`s are different).


<!-- Sent from Reviewable.io -->

2024-11-14 07:44 UTC, elintul reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-11-14 08:39 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-OB5uLwGE1QJZA8p6Gyk:-OBdolBYCBFn6J_GKxdW:b4jn8kp) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dccd690ea4ec27ec463aab7277cff3b7ef75c0/crates/mempool/src/mempool_test.rs#L182)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please fix in other test as well, no difference between them (in both, `tip`s are different).
</blockquote></details>

Sorry, updated now.


<!-- Sent from Reviewable.io -->

2024-11-14 09:28 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1816#-:-OBe-36S-1-80g9y36__:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-11-14 09:42 UTC, merged