chore(network): add workspace lints to network
starkware-libs/sequencer pull request #1823
Opened 2024-11-05 11:09 UTC by giladchase

Lior banned `as` repo-wide, unless absolutely necessary.

Nearly all as uses can be replaced with [Try]From which doesn't have implicit coercions like as (we encountered several bugs due to these coercions).

Motivation: we are standardizing lints across the repo and CI, instead of each crate having separate sets of lints.

Note: i left the `as f64` since `gauge!` expects f64, even though the metrics themselves are integers. This is probably fixable by using `counter!` instead of `gauge!`, but i haven't found anyone who knows how to test these metrics so i'm leaving it for now.
I left them at the statement level intentionaly, instead of the module level, so that it won't be forgotten.

2024-11-05 11:09 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1823)
<!-- Reviewable:end -->

2024-11-05 13:46 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1823)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1823#-OAwZjp_-4fq-VGDcCmZ:-OAwZjp_-4fq-VGDcCm_:b-1i7kq0) ([raw file](https://github.com/starkware-libs/sequencer/blob/92e7432fe9c1c4c7c116706ce40bab824c71398d/crates/papyrus_network/src/discovery/discovery_test.rs#L34)):*
> ```XML
> 
> const TIMEOUT: Duration = Duration::from_secs(1);
> const BOOTSTRAP_DIAL_SLEEP_MILLIS: u64 = 1000; // 1 second
> ```

to minimize changes, will this method work?



_Suggestion:_
```XML
const BOOTSTRAP_DIAL_SLEEP_MILLIS: u64 = 1000; // 1 second
static BOOTSTRAP_DIAL_SLEEP: LazyLock<Duration> = ...from millis
```


<!-- Sent from Reviewable.io -->

2024-11-05 14:06 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1823)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1823#-OAwZjp_-4fq-VGDcCmZ:-OAwd3GN61KaECZj-CUB:bvhq3oc) ([raw file](https://github.com/starkware-libs/sequencer/blob/92e7432fe9c1c4c7c116706ce40bab824c71398d/crates/papyrus_network/src/discovery/discovery_test.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

to minimize changes, will this method work?
</blockquote></details>

Good idea!
Made it a const cause`from_millies` is a const method.


<!-- Sent from Reviewable.io -->

2024-11-05 14:49 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1823)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1823#-OAwnOCW21U_mXuolAUv:-OAwnOCW21U_mXuolAUw:b-q4wq7g) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba1ac5cf6ac8f8049a793fd35bfe8121d23f4533/crates/papyrus_network/src/discovery/discovery_test.rs#L120)):*
> ```XML
> 
>     let event =
>         check_event_happens_after_given_duration(&mut behaviour, BOOTSTRAP_DIAL_SLEEP).await;
> ```

why was this deleted?



_Code quote:_
```XML
&mut behaviour,
```


<!-- Sent from Reviewable.io -->

2024-11-05 17:07 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1823)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1823#-OAwnOCW21U_mXuolAUv:-OAxHwEf8Or2GyGA8IR1:b-et7fye) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba1ac5cf6ac8f8049a793fd35bfe8121d23f4533/crates/papyrus_network/src/discovery/discovery_test.rs#L120)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was this deleted?
</blockquote></details>

Cause i'm an idiot :grimacing: 
Fixed


<!-- Sent from Reviewable.io -->

2024-11-06 08:53 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1823#-:-OB-fPN01Un02g0X-V5J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-11-07 08:02 UTC, merged