chore(blockifier): remove redundant blockifier transactions and related fns
starkware-libs/sequencer pull request #1831
Opened 2024-11-05 12:23 UTC by avivg-starkware

…ed fns

2024-11-05 12:35 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/execution/contract_class.rs` line 525 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OAwIJxH-4wW2kCjxs1C:-OAwIJxH-4wW2kCjxs1D:be43vc) ([raw file](https://github.com/starkware-libs/sequencer/blob/375ae34fc5ba823b1c35602d77549c7f02a1b704/crates/blockifier/src/execution/contract_class.rs#L525)):*
> ```XML
> 
> #[derive(Clone, Debug)]
> // TODO(Ayelet,10/02/2024): Change to bytes.
> ```

Copied this line to starknet_api::contract_class::ClassInfo (below)


<!-- Sent from Reviewable.io -->

2024-11-05 16:01 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OAx2nRZ7PFlq0e10RpG:-OAx2nRZ7PFlq0e10RpH:b-xy0zga) ([raw file](https://github.com/starkware-libs/sequencer/blob/07c91a3cf57cc8fcc8007434a627d4c167cbabb1/crates/blockifier/src/execution/contract_class.rs#L47)):*
> ```XML
> pub mod test;
> 
> pub type ContractClassResult<T> = Result<T, ContractClassError>;
> ```

Delete this, and delete `ContractClassError`.



_Code quote:_
```XML
pub type ContractClassResult<T> = Result<T, ContractClassError>;
```


<!-- Sent from Reviewable.io -->

2024-11-05 16:29 UTC, ArniStarkware reviewed
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OAx8eTDAiOHPv9Vqa8w:-OAx8eTDAiOHPv9Vqa8x:bit6zer) ([raw file](https://github.com/starkware-libs/sequencer/blob/968baff5480323ee0edb8dcd195d15b536e2e577/crates/blockifier/src/transaction/transactions.rs#L163)):*
> ```XML
>         let declare_version = declare_tx.version();
>         // Verify contract class version.
>         // TODO(Noa): Avoid the unnecessary conversion.
> ```

Was the corresponding todo created somewhere else during these PRs?
If so - address it.



_Code quote:_
```XML
// TODO(Noa): Avoid the unnecessary conversion.
```


<!-- Sent from Reviewable.io -->

2024-11-07 06:54 UTC, meship-starkware reviewed
> Reviewed 1 of 5 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-07 13:07 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 2 of 20 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @avivg-starkware, and @noaov1)

___
*[`-- commits` line 5 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OB5jASoDQl8Dd_fMVyF):*
Please rebase 



_Code quote:_
```
New commits in r5 on 07/11/2024 at 13:56:
- 5171ef8: refactor(blockifier): account_tx from enum to struct w api::executable_tx

New commits in r6 on 07/11/2024 at 13:56, probably rebased from r4:
- 9e44710: revert(blockifier): remove redundant blockifier transactions and related fns
```


<!-- Sent from Reviewable.io -->

2024-11-07 13:38 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 2 of 20 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`-- commits` line 5 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OB5jASoDQl8Dd_fMVyF):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OAx8eTDAiOHPv9Vqa8w:-OB5nE5W24saW-8WY5JT:b4ui3vj) ([raw file](https://github.com/starkware-libs/sequencer/blob/968baff5480323ee0edb8dcd195d15b536e2e577/crates/blockifier/src/transaction/transactions.rs#L163)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Was the corresponding todo created somewhere else during these PRs?
If so - address it.
</blockquote></details>

It was not
 @noaov1 - making sure I'm getting this right, this was only relevant for the blockifier's DeclareTransaction, and for addressing the gap between the contract_class types? 

perhaps you want it copied in the 2nd code snipped attached? 



_Code snippet (i):_
```XML
impl DeclareTransaction {
    fn create(
        declare_tx: starknet_api::transaction::DeclareTransaction,
        tx_hash: TransactionHash,
        class_info: ClassInfo,
        only_query: bool,
    ) -> TransactionExecutionResult<Self> {
        let declare_version = declare_tx.version();
        // Verify contract class version.
        // TODO(Noa): Avoid the unnecessary conversion.
        if !is_cairo1(&class_info.contract_class().try_into()?) {
            if declare_version > TransactionVersion::ONE {
                Err(TransactionExecutionError::ContractClassVersionMismatch {
                    declare_version,
                    cairo_version: 0,
                })?
            }
            ...
```



_Code snippet (ii):_
```XML
impl ValidatableTransaction for AccountTransaction {
    fn validate_tx(
        ...
        // Validate return data.
        ##### HERE ? ####
        let contract_class = state.get_compiled_contract_class(class_hash)?;
        if is_cairo1(&contract_class) {
            ...
        Ok(Some(validate_call_info))
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OAx2nRZ7PFlq0e10RpG:-OB5q7Yp1ECrYcfnaNZ0:bplbqua) ([raw file](https://github.com/starkware-libs/sequencer/blob/07c91a3cf57cc8fcc8007434a627d4c167cbabb1/crates/blockifier/src/execution/contract_class.rs#L47)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Delete this, and delete `ContractClassError`.
</blockquote></details>

Deleted in #1858 


<!-- Sent from Reviewable.io -->

2024-11-07 14:05 UTC, meship-starkware reviewed
> Reviewed 1 of 2 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-10 09:32 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OAx8eTDAiOHPv9Vqa8w:-OB6hXkG-7Z498_gwPKv:b-h1ca9h) ([raw file](https://github.com/starkware-libs/sequencer/blob/968baff5480323ee0edb8dcd195d15b536e2e577/crates/blockifier/src/transaction/transactions.rs#L163)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

It was not
 @noaov1 - making sure I'm getting this right, this was only relevant for the blockifier's DeclareTransaction, and for addressing the gap between the contract_class types? 

perhaps you want it copied in the 2nd code snipped attached?
</blockquote></details>

Ok - the answer is that this validation was not addressed in the appropriate location.
The correct location to address this issue is in:
`starknet_api::executable_transaction::DeclareTransaction`, on the `create` class method, [here](https://github.com/starkware-libs/sequencer/blob/71daa83c0a113864a3027269e68749e4782476e0/crates/starknet_api/src/executable_transaction.rs#L212).

Please address it in this PR. Please make it a simple check.

ClassInfo -> ContractClass has two versions: 0/1.
Tx version has four versions: 0, 1, 2, 3

Tx version 0, 1 <-> Class version 0
Tx version 2, 3 <-> Class version 1


<!-- Sent from Reviewable.io -->

2024-11-10 09:34 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OAx8eTDAiOHPv9Vqa8w:-OBKPw7zBpMj_0jndbvm:b4sz5kz) ([raw file](https://github.com/starkware-libs/sequencer/blob/968baff5480323ee0edb8dcd195d15b536e2e577/crates/blockifier/src/transaction/transactions.rs#L163)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Ok - the answer is that this validation was not addressed in the appropriate location.
The correct location to address this issue is in:
`starknet_api::executable_transaction::DeclareTransaction`, on the `create` class method, [here](https://github.com/starkware-libs/sequencer/blob/71daa83c0a113864a3027269e68749e4782476e0/crates/starknet_api/src/executable_transaction.rs#L212).

Please address it in this PR. Please make it a simple check.

ClassInfo -> ContractClass has two versions: 0/1.
Tx version has four versions: 0, 1, 2, 3

Tx version 0, 1 <-> Class version 0
Tx version 2, 3 <-> Class version 1
</blockquote></details>

Move this validation into a method - `validate_class_version_matches_tx_version`. Call it during the constructor. This modularity will allow us to skip this validation if we do not care.


<!-- Sent from Reviewable.io -->

2024-11-10 10:20 UTC, ArniStarkware reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-11 14:49 UTC, avivg-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1831?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1831** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1831?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1688** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1688?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1858** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1858?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1702** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1702?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @avivg-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-11 14:58 UTC, meship-starkware reviewed
> Reviewed 18 of 20 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-11 18:49 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 15 of 23 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OAx8eTDAiOHPv9Vqa8w:-OBRHgw-D4YfHMgpG8Cj:b-3hshrk) ([raw file](https://github.com/starkware-libs/sequencer/blob/968baff5480323ee0edb8dcd195d15b536e2e577/crates/blockifier/src/transaction/transactions.rs#L163)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Move this validation into a method - `validate_class_version_matches_tx_version`. Call it during the constructor. This modularity will allow us to skip this validation if we do not care.
</blockquote></details>

please see  the 2 versions I created- r9 and r10. which do you prefer?  ( i though r10 might be more correct in terms of being passing responsibility for the involved structs). 
if r9 - should i move the func someplace else? 
___
*[`crates/starknet_api/src/contract_class.rs` line 51 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBRXauED10E-rCYB7q3:-OBRXauED10E-rCYB7q4:b-dk06hf) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0dfd2f056f10af67e6d5cda43ca1a6e6b3d14a7/crates/starknet_api/src/contract_class.rs#L51)):*
> ```XML
>                 class.validate_class_version_matches_tx_version(declare_version)?;
>             }
>             // TODO(AvivG): Add validation for V1 when 'impl CasmContractClass' is available.
> ```

I saw "impl  CasmContractClass" doesn't exist yet. I'm assuming it is in the making? wasn't sure if better to create it or leave it as is for now.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 213 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBRI3aY7Z8RVFfBe0Ln:-OBRI3aY7Z8RVFfBe0Lo:byasxc8) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L213)):*
> ```XML
> }
> 
> fn validate_class_version_matches_tx_version(
> ```

was not sure about where best to place this as it does not use 'self'


<!-- Sent from Reviewable.io -->

2024-11-12 10:29 UTC, ArniStarkware requested changes
> Reviewed 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 16 of 23 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OAx8eTDAiOHPv9Vqa8w:-OBQMdXC9PNbmSTW7x0Q:buqiw3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/968baff5480323ee0edb8dcd195d15b536e2e577/crates/blockifier/src/transaction/transactions.rs#L163)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

please see  the 2 versions I created- r9 and r10. which do you prefer?  ( i though r10 might be more correct in terms of being passing responsibility for the involved structs). 
if r9 - should i move the func someplace else?
</blockquote></details>

R9 is closer to what I had in mind. 
___
*[`crates/starknet_api/src/contract_class.rs` line 51 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBRXauED10E-rCYB7q3:-OBUsdj69wPElkCQYxtB:b-p4on1y) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ee9f060f83354d73c573ab3dcd070417954049a/crates/starknet_api/src/contract_class.rs#L51)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

I saw "impl  CasmContractClass" doesn't exist yet. I'm assuming it is in the making? wasn't sure if better to create it or leave it as is for now.
</blockquote></details>

This discussion is only theoretical - as this code is irrelevant.
You can add `impl` blocks as you see fit. 
It did not exist as there was no need.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 213 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBRI3aY7Z8RVFfBe0Ln:-OBUsuoaC1HT8DKEQ91i:b-jquz6s) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L213)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

was not sure about where best to place this as it does not use 'self'
</blockquote></details>

This is good. Please document. (Use Grammarly or ChatGPT)

```
/// Declare transactions of version 0 and 1 are used to declare Cairo 0 contracts. Declare transactions of versions 2 and 3 are used to declare Cairo 1 contracts.
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 189 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBUtNXrAGopPiF5-3PV:-OBUtNXrAGopPiF5-3PW:b-8cf4aw) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L189)):*
> ```XML
>         let tx_hash = declare_tx.calculate_transaction_hash(chain_id, &declare_tx.version())?;
>         Ok(Self { tx: declare_tx, tx_hash, class_info })
>     }
> ```

Add a new line before the return statement. 



_Suggestion:_
```XML
    pub fn create(
        declare_tx: crate::transaction::DeclareTransaction,
        class_info: ClassInfo,
        chain_id: &ChainId,
    ) -> Result<Self, StarknetApiError> {
        let class = class_info.contract_class.clone();
        validate_class_version_matches_tx_version(declare_tx.version(), class)?;
        let tx_hash = declare_tx.calculate_transaction_hash(chain_id, &declare_tx.version())?;
        
        Ok(Self { tx: declare_tx, tx_hash, class_info })
    }
```


<!-- Sent from Reviewable.io -->

2024-11-12 10:30 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 16 of 23 files reviewed, 2 unresolved discussions (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 216 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBUv9tU7BhdGeRg7E62:-OBUv9tU7BhdGeRg7E63:btsfou3) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L216)):*
> ```XML
>     declare_version: TransactionVersion,
>     class: ContractClass,
> ) -> Result<(), StarknetApiError> {
> ```

No need to clone the `ContractClass`.



_Suggestion:_
```XML
fn validate_class_version_matches_tx_version(
    declare_version: TransactionVersion,
    class: &ContractClass,
) -> Result<(), StarknetApiError> {
```


<!-- Sent from Reviewable.io -->

2024-11-12 10:31 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 16 of 23 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 186 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBUvHGW9rHjdNXL4bTO:-OBUvHGW9rHjdNXL4bTP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L186)):*
> ```XML
>     ) -> Result<Self, StarknetApiError> {
>         let class = class_info.contract_class.clone();
>         validate_class_version_matches_tx_version(declare_tx.version(), class)?;
> ```





_Suggestion:_
```XML
        validate_class_version_matches_tx_version(declare_tx.version(), &class_info.contract_class)?;
```


<!-- Sent from Reviewable.io -->

2024-11-12 10:41 UTC, meship-starkware reviewed
> Reviewed 3 of 6 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 21 of 23 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-12 10:43 UTC, meship-starkware reviewed
> Reviewed 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-12 12:45 UTC, avivg-starkware commented
*[`crates/starknet_api/src/executable_transaction.rs` line 213 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBRI3aY7Z8RVFfBe0Ln:-OBVOIGYBktBR3KKTIrL:b-ke8agd) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L213)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is good. Please document. (Use Grammarly or ChatGPT)

```
/// Declare transactions of version 0 and 1 are used to declare Cairo 0 contracts. Declare transactions of versions 2 and 3 are used to declare Cairo 1 contracts.
```
</blockquote></details>

Do you mean that I'll use GPT on this comment? or for me to know for the next time? 


<!-- Sent from Reviewable.io -->

2024-11-12 13:09 UTC, meship-starkware approved these changes
> Reviewed 26 of 26 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-12 13:22 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 5 of 29 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OAx8eTDAiOHPv9Vqa8w:-OBVNkFs00zm6M4tgLDu:bwvyox4) ([raw file](https://github.com/starkware-libs/sequencer/blob/968baff5480323ee0edb8dcd195d15b536e2e577/crates/blockifier/src/transaction/transactions.rs#L163)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

R9 is closer to what I had in mind.
</blockquote></details>

Reverted
___
*[`crates/starknet_api/src/executable_transaction.rs` line 189 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBUtNXrAGopPiF5-3PV:-OBVOGrrERrmg36V4nMN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L189)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add a new line before the return statement.
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 216 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBUv9tU7BhdGeRg7E62:-OBVPK80DtXKEEDE_GGo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L216)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

No need to clone the `ContractClass`.
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/contract_class.rs` line 51 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBRXauED10E-rCYB7q3:-OBVNnHg2yVFV1lTsQ60:b-ucfknh) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ee9f060f83354d73c573ab3dcd070417954049a/crates/starknet_api/src/contract_class.rs#L51)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This discussion is only theoretical - as this code is irrelevant.
You can add `impl` blocks as you see fit. 
It did not exist as there was no need.
</blockquote></details>

Thanks!
___
*[`crates/starknet_api/src/executable_transaction.rs` line 186 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBUvHGW9rHjdNXL4bTO:-OBVODlm39VUTnh1QAEV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L186)):*
> ```XML
>     ) -> Result<Self, StarknetApiError> {
>         let class = class_info.contract_class.clone();
>         validate_class_version_matches_tx_version(declare_tx.version(), class)?;
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-12 14:25 UTC, ArniStarkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 5 of 29 files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 213 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBRI3aY7Z8RVFfBe0Ln:-OBVkk8220piCBzv7061:bb6td7q) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L213)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Do you mean that I'll use GPT on this comment? or for me to know for the next time?
</blockquote></details>

Both


<!-- Sent from Reviewable.io -->

2024-11-12 14:28 UTC, ArniStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 6 files at r9, 1 of 24 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-:-OBVli5T6jBraT2krFL3:bnfp4nl)* status: 7 of 29 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 245 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBVl5Go7mQh-DYk6qlX:-OBVl5Go7mQh-DYk6qlY:b-5mi7m2) ([raw file](https://github.com/starkware-libs/sequencer/blob/849e2b803e0e9e0cb1c5cea51ef1d2ea94346163/crates/starknet_api/src/executable_transaction.rs#L245)):*
> ```XML
>     Ok(())
> }
> #[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
> ```

Add line.



_Suggestion:_
```XML
    }
    Ok(())
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
```


<!-- Sent from Reviewable.io -->

2024-11-12 15:00 UTC, ArniStarkware reviewed
> Reviewed 1 of 26 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 7 of 29 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-12 16:59 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 6 of 29 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 213 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBRI3aY7Z8RVFfBe0Ln:-OBWCkb45gj6Z9QR48X5:b-q5t7ns) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e5a845c4f0784d3d96e320c729163ec847a8f8/crates/starknet_api/src/executable_transaction.rs#L213)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Both
</blockquote></details>

Hope now it's good, if not I'll change in a small PR 


<!-- Sent from Reviewable.io -->

2024-11-12 17:01 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 6 of 29 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 245 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBVl5Go7mQh-DYk6qlX:-OBWJUNK1iAqyqMIIlyB:bvtpruv) ([raw file](https://github.com/starkware-libs/sequencer/blob/849e2b803e0e9e0cb1c5cea51ef1d2ea94346163/crates/starknet_api/src/executable_transaction.rs#L245)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add line.
</blockquote></details>

Thankyou!


<!-- Sent from Reviewable.io -->

2024-11-12 19:02 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 6 of 29 files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 245 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBVl5Go7mQh-DYk6qlX:-OBWk0op3icRs0gRQC6Z:b-x6wdem) ([raw file](https://github.com/starkware-libs/sequencer/blob/849e2b803e0e9e0cb1c5cea51ef1d2ea94346163/crates/starknet_api/src/executable_transaction.rs#L245)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Thankyou!
</blockquote></details>

also after the block of the function `validate_class_version_matches_tx_version` and before the `derive`s of ` DeployAccountTransaction`


<!-- Sent from Reviewable.io -->

2024-11-12 19:05 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 6 of 29 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware, @meship-starkware, and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-13 07:35 UTC, meship-starkware approved these changes
> Reviewed 23 of 24 files at r12, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-13 08:05 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 245 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBVl5Go7mQh-DYk6qlX:-OBZYWQA1174I1PZyXFQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/849e2b803e0e9e0cb1c5cea51ef1d2ea94346163/crates/starknet_api/src/executable_transaction.rs#L245)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

also after the block of the function `validate_class_version_matches_tx_version` and before the `derive`s of ` DeployAccountTransaction`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-13 08:21 UTC, meship-starkware approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-13 08:37 UTC, ArniStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-:-OBZevLVAYdySYinMFl9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-13 10:12 UTC, Yoni-Starkware requested changes
> Reviewed 3 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 216 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBZzz1H9Pk6fFblGowO:-OBZzz1H9Pk6fFblGowP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/825bcf3e0b893e01fcefaaf1a225f11ac8735a7a/crates/starknet_api/src/executable_transaction.rs#L216)):*
> ```XML
> 
> /// Validates that the Declare transaction version is compatible with the Cairo contract version.
> /// Versions 0 and 1 declare Cairo 0 contracts, while versions 2 and 3 declare Cairo 1 contracts.
> ```





_Suggestion:_
```XML
/// Versions 0 and 1 declare Cairo 0 contracts, while versions >= 2 declare Cairo 1 contracts.
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 217 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBZzoDT5o4A3ITSd682:-OBZzoDT5o4A3ITSd683:bo4q0ew) ([raw file](https://github.com/starkware-libs/sequencer/blob/825bcf3e0b893e01fcefaaf1a225f11ac8735a7a/crates/starknet_api/src/executable_transaction.rs#L217)):*
> ```XML
> /// Validates that the Declare transaction version is compatible with the Cairo contract version.
> /// Versions 0 and 1 declare Cairo 0 contracts, while versions 2 and 3 declare Cairo 1 contracts.
> fn validate_class_version_matches_tx_version(
> ```

For the next time: this refactor deserves a separate PR.



_Code quote:_
```XML
fn validate_class_version_matches_tx_version(
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 234 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OB_-Gps8-vTW1kALmEz:-OB_-Gpt8XM6IWSd9vL6:b-dvc73d) ([raw file](https://github.com/starkware-libs/sequencer/blob/825bcf3e0b893e01fcefaaf1a225f11ac8735a7a/crates/starknet_api/src/executable_transaction.rs#L234)):*
> ```XML
>         ContractClass::V1(_) => {
>             if !(declare_version == TransactionVersion::TWO
>                 || declare_version == TransactionVersion::THREE)
> ```

Why not `<`, `>=`?
Future versions are also going to hold Cairo1 contracts.



_Code quote:_
```XML
            if !(declare_version == TransactionVersion::ZERO
                || (declare_version == TransactionVersion::ONE))
            {
                Err(StarknetApiError::ContractClassVersionMismatch {
                    declare_version,
                    cairo_version: 0,
                })?
            }
        }
        ContractClass::V1(_) => {
            if !(declare_version == TransactionVersion::TWO
                || declare_version == TransactionVersion::THREE)
```


<!-- Sent from Reviewable.io -->

2024-11-13 11:07 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: all files reviewed, 4 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 10 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OB_C0K76bPEd-1NeLfb:-OB_C0K76bPEd-1NeLfc:b-dx0yyv) ([raw file](https://github.com/starkware-libs/sequencer/blob/825bcf3e0b893e01fcefaaf1a225f11ac8735a7a/crates/blockifier/src/transaction/transactions.rs#L10)):*
> ```XML
>     DeployAccountTransaction as ExecutableDeployAccountTx,
>     InvokeTransaction as ExecutableInvokeTx,
>     L1HandlerTransaction,
> ```

No need for these nicknames anymore, right?



_Code quote:_
```XML
use starknet_api::executable_transaction::{
    DeclareTransaction as ExecutableDeclareTx,
    DeployAccountTransaction as ExecutableDeployAccountTx,
    InvokeTransaction as ExecutableInvokeTx,
    L1HandlerTransaction,
```


<!-- Sent from Reviewable.io -->

2024-11-13 12:24 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: 28 of 29 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 10 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OB_C0K76bPEd-1NeLfb:-OB_GlVf5e1K0OhJp2Ae:b6nszib) ([raw file](https://github.com/starkware-libs/sequencer/blob/825bcf3e0b893e01fcefaaf1a225f11ac8735a7a/crates/blockifier/src/transaction/transactions.rs#L10)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No need for these nicknames anymore, right?
</blockquote></details>

Yes indeed
___
*[`crates/starknet_api/src/executable_transaction.rs` line 217 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBZzoDT5o4A3ITSd682:-OB_GE-P4Gjadxm7kL_9:br07cxn) ([raw file](https://github.com/starkware-libs/sequencer/blob/825bcf3e0b893e01fcefaaf1a225f11ac8735a7a/crates/starknet_api/src/executable_transaction.rs#L217)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

For the next time: this refactor deserves a separate PR.
</blockquote></details>

yes will do
___
*[`crates/starknet_api/src/executable_transaction.rs` line 234 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OB_-Gps8-vTW1kALmEz:-OB_MtaJ4Nr66MuzjWlV:bmcw6y7) ([raw file](https://github.com/starkware-libs/sequencer/blob/825bcf3e0b893e01fcefaaf1a225f11ac8735a7a/crates/starknet_api/src/executable_transaction.rs#L234)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not `<`, `>=`?
Future versions are also going to hold Cairo1 contracts.
</blockquote></details>

How about now? 
___
*[`crates/starknet_api/src/executable_transaction.rs` line 223 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OB_OlEtBkp2kK10ROxe:-OB_Rpsd68ABBx9gsCys:b-s43aso) ([raw file](https://github.com/starkware-libs/sequencer/blob/9680503104a7db09770a1aeafff5eb484ddd09ba/crates/starknet_api/src/executable_transaction.rs#L223)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is more explicit.
</blockquote></details>

Sorry, I had to change, there was a problem with this implementation -
'expected_cairo_version' was incorrect in terms of the implementation of 'ContractClassVersionMismatch'.

how is it now? 

(in more details-
ContractClassVersionMismatch expects to receive the Cairo version compatible w 'declare_version', in the case here, I passed on the cairo_version that is the input of the func (the 'wrong' cairo_version).
___
*[`crates/starknet_api/src/executable_transaction.rs` line 216 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OBZzz1H9Pk6fFblGowO:-OB_GBjL-F4k-Nam-Vbu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/825bcf3e0b893e01fcefaaf1a225f11ac8735a7a/crates/starknet_api/src/executable_transaction.rs#L216)):*
> ```XML
> 
> /// Validates that the Declare transaction version is compatible with the Cairo contract version.
> /// Versions 0 and 1 declare Cairo 0 contracts, while versions 2 and 3 declare Cairo 1 contracts.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-13 12:46 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1831)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 223 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1831#-OB_OlEtBkp2kK10ROxe:-OB_Yb4z2OoLL9aq0Zxk:b4x3y5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/9680503104a7db09770a1aeafff5eb484ddd09ba/crates/starknet_api/src/executable_transaction.rs#L223)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Sorry, I had to change, there was a problem with this implementation -
'expected_cairo_version' was incorrect in terms of the implementation of 'ContractClassVersionMismatch'.

how is it now? 

(in more details-
ContractClassVersionMismatch expects to receive the Cairo version compatible w 'declare_version', in the case here, I passed on the cairo_version that is the input of the func (the 'wrong' cairo_version).
</blockquote></details>

The new version is better. Nice.


<!-- Sent from Reviewable.io -->

2024-11-13 13:06 UTC, merged