refactor(starknet_api): remove invoke_tx_args constructor macro
starkware-libs/sequencer pull request #1833
Opened 2024-11-05 12:45 UTC by noam-starkware

The `invoke_tx_args!` macro is a constructor for the `InvokeTxArgs` struct. It calls the default constructor on its input fields and uses default values for all other fields.
It was originally written in such a way that when `resource_bounds` are not supplied they are derived from `max_fee` (see [here](https://reviewable.io/reviews/starkware-libs/blockifier/953)).
Since then the macro was modified and in its current state its only benefit is allowing one to omit the `..Default::default()` for all fields not supplied in instantiation.
No other structs apart from `[Invoke/Declare/DeployAccount]TxArgs` use this form of macro instantiation. As no added benefit exists, we suggest removing these macros.

2024-11-05 12:45 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1833)
<!-- Reviewable:end -->

2024-11-05 13:28 UTC, ayeletstarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833#-:-OAwVruj68fXG0hDX7w-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)



<!-- Sent from Reviewable.io -->

2024-11-05 13:46 UTC, ArniStarkware requested changes
I disagree with the premise of this PR.
> Since then the macro was modified and in its current state its only benefit is allowing one to omit the `..Default::default()` for all fields not supplied in instantiation.

I think this is a significant benefit - it removes boilerplate code. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833#-:-OAwZDL92iVEH3Ddt4DY:blqgak8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)



<!-- Sent from Reviewable.io -->

2024-11-05 13:49 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1833#-OAw_TG07UH7NahOj032:-OAw_TG07UH7NahOj033:bftefu0) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a17edc2f30769e705144f2b74533723ffdc7f75/crates/blockifier/src/transaction/account_transactions_test.rs#L117)):*
> ```XML
>         nonce: nonce_manager.next(account_address),
>         ..Default::default()
>     };
> ```

These line breaks are improved compared to the use of the macro.



_Code quote:_
```XML
    let tx_args = InvokeTxArgs {
        sender_address: account_address,
        calldata: create_calldata(test_contract_address, "test_circuit", &[]),
        nonce: nonce_manager.next(account_address),
        ..Default::default()
    };
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1833#-OAw_Mt_AFZf2SRF7TvR:-OAw_Mta2pWwjqJ7V_sk:b-qh011a) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a17edc2f30769e705144f2b74533723ffdc7f75/crates/blockifier/src/transaction/account_transactions_test.rs#L121)):*
> ```XML
>         state,
>         &block_context,
>         InvokeTxArgs { resource_bounds: default_all_resource_bounds, ..tx_args },
> ```

This change should stay - if you revert this PR.



_Code quote:_
```XML
InvokeTxArgs { resource_bounds: default_all_resource_bounds, ..tx_args },
```


<!-- Sent from Reviewable.io -->

2024-11-07 09:46 UTC, ArniStarkware approved these changes
I concur, <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833#-:-OB5-xvzBlFwm_EzNqZP:bcn3huu)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)



<!-- Sent from Reviewable.io -->

2024-11-07 09:53 UTC, ArniStarkware approved these changes
> Reviewed 11 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)



<!-- Sent from Reviewable.io -->

2024-11-07 09:54 UTC, ArniStarkware approved these changes
> Reviewed 6 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)



<!-- Sent from Reviewable.io -->

2024-11-07 14:25 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833#-:-OB6042587HRduTnLgBL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-11-10 10:18 UTC, ArniStarkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-11-19 13:07 UTC, ArniStarkware approved these changes
> Reviewed 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-11-19 14:02 UTC, ayeletstarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833#-:-OC3ikwvBw73z_JWUDuP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)



<!-- Sent from Reviewable.io -->

2024-11-19 14:30 UTC, ArniStarkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)



<!-- Sent from Reviewable.io -->

2025-01-25 08:04 UTC, closed without merging