chore: add lints to papyrus_storage
starkware-libs/sequencer pull request #1846
Opened 2024-11-05 18:02 UTC by giladchase

Lior banned `as` repo-wide, unless absolutely necessary.

Notable changes, the rest is either `From` or usize->u64 casts:
1. storage_benchmark: all usages are usize, not u128, so switching.
2. db_stats: to usages needed `as f64` so added exception, last usage used f64 pow, no need to pass through i32.
3. serializers: multi-type use macro, added exception.
4. utils.rs: metrics need as f64.

2024-11-05 18:02 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1846)
<!-- Reviewable:end -->

2024-11-06 09:08 UTC, dorimedini-starkware requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1846)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase and @yair-starkware)

___
*[`crates/papyrus_storage/src/utils.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-gmkU3TjGiHnrpO5K:-OB-gmkU3TjGiHnrpO5L:bjn8gf) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/utils.rs#L104)):*
> ```XML
>     absolute_counter!("storage_last_transaction_index", info.last_txnid() as u64);
>     Ok(())
> }
> ```

+ please take the bottom 64 bits of the two `usize`s you convert to u64;
`f64` is the only `as` conversion actually needed, right?



_Suggestion:_
```XML
pub fn update_storage_metrics(reader: &StorageReader) -> StorageResult<()> {
    debug!("updating storage metrics");
    #[allow(clippy::as_conversions)]
    gauge!("storage_free_pages_number", reader.db_reader.get_free_pages()? as f64);
    let info = reader.db_reader.get_db_info()?;
    absolute_counter!("storage_last_page_number", info.last_pgno() as u64);
    absolute_counter!("storage_last_transaction_index", info.last_txnid() as u64);
    Ok(())
}
```
___
*[`crates/papyrus_storage/src/utils_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-hGP24nnVjDVXBOKm:-OB-hGP24nnVjDVXBOKn:b9m92i7) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/utils_test.rs#L30)):*
> ```XML
>     let ((reader, mut writer), _temp_dir) = get_test_storage();
>     for i in 0..5 {
>         let i_felt = Felt::from(u128::try_from(i).expect("usize should fit in u128"));
> ```

doesn't this work?



_Suggestion:_
```XML
    for i in 0_u64..5 {
        let i_felt = Felt::from(i);
```
___
*[`crates/papyrus_storage/src/utils_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-hR9P39HCnwHXNMe7:-OB-hR9P39HCnwHXNMe8:b9m92i7) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/utils_test.rs#L49)):*
> ```XML
>             replaced_classes: indexmap!(),
>         });
>         let block_number = BlockNumber(u64::try_from(i).expect("usize should fit in u64"));
> ```

doesn't this work?



_Suggestion:_
```XML
    for i in 0_u64..5 {
        let i_felt = Felt::from(i);
        declared_classes.push((
            ClassHash(i_felt),
            ContractClass {
                sierra_program: vec![i_felt, i_felt],
                entry_points_by_type: HashMap::new(),
                abi: "".to_string(),
            },
        ));
        state_diffs.push(ThinStateDiff {
            deployed_contracts: indexmap!(),
            storage_diffs: indexmap!(),
            declared_classes: indexmap!(
                declared_classes[i].0 => compiled_class_hash
            ),
            deprecated_declared_classes: vec![],
            nonces: indexmap!(),
            replaced_classes: indexmap!(),
        });
        let block_number = BlockNumber(i);
```
___
*[`crates/papyrus_storage/src/bin/storage_benchmark.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-heNI9X83JElxxwWD:-OB-heNI9X83JElxxwWE:bb263po) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/bin/storage_benchmark.rs#L159)):*
> ```XML
>     unit: String,
>     value: u128,
> }
> ```

@yair-starkware is this ok?



_Code quote:_
```XML
struct Entry {
    name: String,
    unit: String,
    value: u128,
}
```
___
*[`crates/papyrus_storage/src/mmap_file/mmap_file_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-i4wL6al9AQMbVtEx:-OB-i4wM1fXnCPEfc24X:bofec9l) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/mmap_file/mmap_file_test.rs#L0)):*
1. I think usize->u64 makes more sense than u64->usize
2. there are converter functions in the blockifier (`u64_from_usize` and `usize_from_u64`) which perform the explicit conversion; can you use them?

... non-blocking anyway, this is a test file
___
*[`crates/papyrus_storage/src/mmap_file/mod.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-iQcg0246Uf3q_GzJ:-OB-iQcg0246Uf3q_GzK:bf3ugs4) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/mmap_file/mod.rs#L153)):*
> ```XML
>         self.flush();
>         let new_size = self.size + self.config.growth_step;
>         let new_size_u64 = u64::try_from(new_size).expect("usize should fit in u64");
> ```

please use blockifier's `u64_from_usize`, so it will be easy to search for all problematic conversions in the future



_Code quote:_
```XML
u64::try_from(new_size).expect("usize should fit in u64");
```
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 596 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-iaJuEQtpXB1zUAGa:-OB-iaJuEQtpXB1zUAGb:bihun3b) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/serialization/serializers.rs#L596)):*
> ```XML
>         impl StorageSerde for $name {
>             fn serialize_into(&self, res: &mut impl std::io::Write) -> Result<(), StorageSerdeError> {
>                 #[allow(clippy::as_conversions)]
> ```

this is a bummer... @yair-starkware any ideas?



_Code quote:_
```XML
#[allow(clippy::as_conversions)]
```
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 768 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-imXjAMgRnEWu4cIY:-OB-imXjAMgRnEWu4cIZ:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/serialization/serializers.rs#L768)):*
> ```XML
> impl StorageSerde for usize {
>     fn serialize_into(&self, res: &mut impl std::io::Write) -> Result<(), StorageSerdeError> {
>         (u64::try_from(*self).expect("usize should fit in u64")).serialize_into(res)
> ```

see above



_Suggestion:_
```XML
u64_from_usize(*self))
```


<!-- Sent from Reviewable.io -->

2024-11-07 08:35 UTC, yair-starkware commented
*[`crates/papyrus_storage/src/bin/storage_benchmark.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-heNI9X83JElxxwWD:-OB4ktVv2HVdI3qlUIKO:b-1f6ut1) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/bin/storage_benchmark.rs#L159)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@yair-starkware is this ok?
</blockquote></details>

@DvirYo-starkware 


<!-- Sent from Reviewable.io -->

2024-11-07 09:23 UTC, dorimedini-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1846)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @DvirYo-starkware, @giladchase, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB4vufm43vrCMo2idmO:-OB4vufnEddyhPrYD71O:b-hm0lm2) (no related file):*
rebase?

___


<!-- Sent from Reviewable.io -->

2024-11-07 13:24 UTC, dorimedini-starkware reviewed
> Reviewed 9 of 9 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1846)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @giladchase)



<!-- Sent from Reviewable.io -->

2024-11-07 13:32 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1846)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/bin/storage_benchmark.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-heNI9X83JElxxwWD:-OB5oYhnBQV1f5w0j3pG:b-meq1vd) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/bin/storage_benchmark.rs#L159)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

@DvirYo-starkware
</blockquote></details>

@yair-starkware  Dvir's OOO until Sunday, OK if i revert this part and just add casts into u128? That way we can be sure it behaves the same 


<!-- Sent from Reviewable.io -->

2024-11-07 14:02 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1846)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/bin/storage_benchmark.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-heNI9X83JElxxwWD:-OB5v0E55FBsj8k_3Zdm:b3z5hjm) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/bin/storage_benchmark.rs#L159)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

@yair-starkware  Dvir's OOO until Sunday, OK if i revert this part and just add casts into u128? That way we can be sure it behaves the same
</blockquote></details>

NVM, we'll Dvir either way.

Currently the code is doing `<u128_type> as usize`, which (in practice) **truncates** the value if it is larger than u64::MAX.

Therefore I can't replace this `as usize` with `tryFrom + unwrap` because maybe Dvir was counting on this truncation behavior, either on purpose or not, and I don't want to introduce a panic.


<!-- Sent from Reviewable.io -->

2024-11-10 09:37 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1846)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/bin/storage_benchmark.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1846#-OB-heNI9X83JElxxwWD:-OBKQnzP7c-AY-yMuh2y:bh2spkf) ([raw file](https://github.com/starkware-libs/sequencer/blob/61307b8975b65525520fb7c02c888702119aab1e/crates/papyrus_storage/src/bin/storage_benchmark.rs#L159)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

NVM, we'll Dvir either way.

Currently the code is doing `<u128_type> as usize`, which (in practice) **truncates** the value if it is larger than u64::MAX.

Therefore I can't replace this `as usize` with `tryFrom + unwrap` because maybe Dvir was counting on this truncation behavior, either on purpose or not, and I don't want to introduce a panic.
</blockquote></details>

Spoke with Dvir offline, he said the proposed switch is fine (changing from `usize` to `u128`)


<!-- Sent from Reviewable.io -->

2024-11-10 09:56 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1846)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2024-11-10 10:34 UTC, merged