chore: add lints to rpc
starkware-libs/sequencer pull request #1852
Opened 2024-11-05 18:50 UTC by giladchase

Lior banned `as` repo-wide, unless absolutely necessary.

Nearly all as uses can be replaced with [Try]From which doesn't have implicit coercions like as (we encountered several bugs due to these coercions).

Motivation: we are standardizing lints across the repo and CI, instead of each crate having separate sets of lints.

2024-11-05 18:50 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1852)
<!-- Reviewable:end -->

2024-11-06 09:38 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1852)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @giladchase)

___
*[`crates/papyrus_rpc/src/v0_8/transaction.rs` line 1240 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1852#-OB-pSbb21U7357oqFHV:-OB-pSbb21U7357oqFHW:b-yceb20) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c4ff87ff56d3fa60160a6fda472d33bc71ceab/crates/papyrus_rpc/src/v0_8/transaction.rs#L1240)):*
> ```XML
>     let selector = Token::Bytes(entry_point_selector.0.to_bytes_be().to_vec());
>     let payload_length_as_felt =
>         Felt::from(u64::try_from(payload.len()).expect("usize should fit in usize"));
> ```

or reword the `expect` (usize should fit in u64)



_Suggestion:_
```XML
u64_from_usize(payload.len())
```


<!-- Sent from Reviewable.io -->

2024-11-07 09:00 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1852)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @dorimedini-starkware)

___
*[`crates/papyrus_rpc/src/v0_8/transaction.rs` line 1240 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1852#-OB-pSbb21U7357oqFHV:-OB4ptAU2_uol6y0grgK:bmb1z2z) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c4ff87ff56d3fa60160a6fda472d33bc71ceab/crates/papyrus_rpc/src/v0_8/transaction.rs#L1240)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

or reword the `expect` (usize should fit in u64)
</blockquote></details>

Whoops thanks.
Reworded the `expect`, would have loved to use the util but this hits a different issue:

a) this util is from the blockifier, which isn't a dependency here (and adding it just for that is unreasonable)
b) we can extract it from the blockifier (it isn't blockifier-specific), but we don't have a natural place to put this util ATM. There were talks about `utils` crate but nothing settled yet (I personally don't like a global `utils` crate, it's too loosely goosey and gets messy.
Maybe we can have a `stdx` crate (std extensions), which will have things that _could_ have been part of the std. rust-analyzer have this. Anyway, out of scope here probably. 


<!-- Sent from Reviewable.io -->

2024-11-07 09:19 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1852#-:-OB4uz6c3tasQazaIbI7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2024-11-08 10:52 UTC, merged