chore: SN API add lints
starkware-libs/sequencer pull request #1853
Opened 2024-11-05 19:06 UTC by giladchase

Lior banned `as` repo-wide, unless absolutely necessary.

Nearly all as uses can be replaced with [Try]From which doesn't have implicit coercions like as (we encountered several bugs due to these coercions).

Motivation: we are standardizing lints across the repo and CI, instead of each crate having separate sets of lints.

2024-11-05 19:07 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1853)
<!-- Reviewable:end -->

2024-11-06 09:39 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1853)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1853#-OB-pnVL5TzmbTXUGgJq:-OB-pnVL5TzmbTXUGgJr:b-f1opix) (no related file):*
why are there changes to papyrus rpc here?

___


<!-- Sent from Reviewable.io -->

2024-11-07 09:01 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1853)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1853#-OB-pnVL5TzmbTXUGgJq:-OB4pMZH-S_Py1ekhyuh:b-r69nea) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why are there changes to papyrus rpc here?
</blockquote></details>

Needed rebase, Done.

___


<!-- Sent from Reviewable.io -->

2024-11-07 09:19 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1853#-:-OB4v4Mv8SkP81BwqmFi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-07 14:53 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-07 18:01 UTC, dorimedini-starkware approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-08 10:54 UTC, merged