chore(monitoring): split to test utils
starkware-libs/sequencer pull request #1861
Opened 2024-11-06 18:00 UTC by Itay-Tsabary-Starkware

2024-11-06 18:00 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1861)
<!-- Reviewable:end -->

2024-11-10 09:30 UTC, nadin-Starkware requested changes
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1861)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/monitoring_endpoint/Cargo.toml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1861#-OBKPCP9EsRrRlINbUJC:-OBKPCP9EsRrRlINbUJD:bb7r2f0) ([raw file](https://github.com/starkware-libs/sequencer/blob/36ee09c0a501e1f05f0735b653a2e01a109ee1c2/crates/monitoring_endpoint/Cargo.toml#L25)):*
> ```TOML
> starknet_sequencer_infra.workspace = true
> tokio = { workspace = true, optional = true }
> tower = { workspace = true, optional = true, features = ["util"] }
> ```

why?



_Code quote:_
```TOML
[features]
testing = ["http-body", "tokio", "tower"]

[lints]
workspace = true

[dependencies]
axum.workspace = true
http-body = { workspace = true, optional = true }
hyper = { workspace = true, features = ["full"] }
papyrus_config.workspace = true
serde.workspace = true
starknet_sequencer_infra.workspace = true
tokio = { workspace = true, optional = true }
tower = { workspace = true, optional = true, features = ["util"] }
```
___
*[`crates/monitoring_endpoint/Cargo.toml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1861#-OBKO5eA7XE7qi0LM7c8:-OBKO5eBErgVpQ_KkDRI:b-l6mwxj) ([raw file](https://github.com/starkware-libs/sequencer/blob/36ee09c0a501e1f05f0735b653a2e01a109ee1c2/crates/monitoring_endpoint/Cargo.toml#L28)):*
> ```TOML
> tracing.workspace = true
> validator.workspace = true
> ```

remove


<!-- Sent from Reviewable.io -->

2024-11-10 11:04 UTC, nadin-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1861#-:-OBKjhlz3vD3I9qRcCjH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-11-10 11:06 UTC, Itay-Tsabary-Starkware commented
✓ Commit merged in pull request [#1864](https://github.com/starkware-libs/sequencer/pull/1864)

2024-11-10 11:06 UTC, closed without merging