chore(monitoring): add 'is_alive' client
starkware-libs/sequencer pull request #1862
Opened 2024-11-06 18:00 UTC by Itay-Tsabary-Starkware

**Stack**:
- #1862 ⬅
- #1861
- #1860

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-11-06 18:00 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1862)
<!-- Reviewable:end -->

2024-11-10 09:23 UTC, nadin-Starkware requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1862)* status: all files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/monitoring_endpoint/src/test_utils.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1862#-OBKMI-ZAR0pmmnxscp5:-OBKMI-ZAR0pmmnxscp6:b-oiz4um) ([raw file](https://github.com/starkware-libs/sequencer/blob/e82700efb2f32c26a9132763672d5a05f5b3e615/crates/monitoring_endpoint/src/test_utils.rs#L21)):*
> ```XML
> impl IsAliveClient {
>     pub fn new(socket: SocketAddr) -> Self {
>         let client = hyper::Client::new();
> ```

Please add it to the imports and use Client::new



_Code quote:_
```XML
 hyper::Client
```
___
*[`crates/monitoring_endpoint/src/test_utils.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1862#-OBKMf9W93xscHngbaoT:-OBKMf9W93xscHngbaoU:b1pkyvq) ([raw file](https://github.com/starkware-libs/sequencer/blob/e82700efb2f32c26a9132763672d5a05f5b3e615/crates/monitoring_endpoint/src/test_utils.rs#L30)):*
> ```XML
> 
>         self.client
>             .request(build_request(&self.socket.ip(), self.socket.port(), "alive"))
> ```

Use the const



_Code quote:_
```XML
"alive"
```
___
*[`crates/monitoring_endpoint/src/test_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1862#-OBKNXlODT1xnx4qHcIM:-OBKNXlODT1xnx4qHcIN:bb73xfv) ([raw file](https://github.com/starkware-libs/sequencer/blob/e82700efb2f32c26a9132763672d5a05f5b3e615/crates/monitoring_endpoint/src/test_utils.rs#L40)):*
> ```XML
>         while !(self.query_alive().await) {
>             info!("Waiting for node to be alive: {}.", counter);
>             tokio::time::sleep(Duration::from_secs(1)).await;
> ```

Same



_Code quote:_
```XML
tokio::time::sleep
```


<!-- Sent from Reviewable.io -->

2024-11-10 11:05 UTC, nadin-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1862#-:-OBKk53B2L4GP86UcRjM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-11-10 11:06 UTC, Itay-Tsabary-Starkware commented
✓ Commit merged in pull request [#1864](https://github.com/starkware-libs/sequencer/pull/1864)

2024-11-10 11:06 UTC, closed without merging