chore(ci): remove clippy.sh
starkware-libs/sequencer pull request #1917
Opened 2024-11-10 13:57 UTC by giladchase

- Only one source of truth for lints, main Cargo.toml, making clippy.sh unnecessary.
- Warnings no longer denied, only in the CI. To preserve existing behaviors users can add `-Dwarnings` to local RUSTFLAGS.

We still need to enforce in workspace tests that all crates inherit workspace lints.

2024-11-10 13:58 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1917)
<!-- Reviewable:end -->

2024-11-10 14:22 UTC, giladchase reviewed
See [this](https://reviewable.io/reviews/starkware-libs/sequencer/1918#-) example PR that rejects a commit that violated `nonstandard-style`, which is now just a warning locally, but generates an error in the CI.

Note: `unused-imports`, the main suspect, is already warning by default.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917#-:-OBLR2Ou0YWN8Gh-3weO:b-wg754e)* status: 0 of 3 files reviewed, all discussions resolved

___
*[`scripts/run_tests.py` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1917#-OBLRQIA86L-RUblAeSv:-OBLRQIA86L-RUblAeSw:b8ro2dj) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3383aefa7dfc5a57904c45afafaf1a28835bfc1/scripts/run_tests.py#L49)):*
> ```Python
>             # Don't remove, or warnings will merge.
>             # TODO: add this to package args instead of here, it is a rustc flag, not a clippy flag.
>             clippy_args += ["--", "-Dwarnings"]
> ```

This is suboptimal, would have preferred to add this to `package_args` but that one's already used for options, whereas `-Dwarnings` as shown below is an operand.

Technically this implies adding a package_operands array but I didn't want to overengineer this task unprompted.



_Code quote:_
```Python
            # TODO: add this to package args instead of here, it is a rustc flag, not a clippy flag.
            clippy_args += ["--", "-Dwarnings"]
```


<!-- Sent from Reviewable.io -->

2024-11-12 11:34 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`Cargo.toml` line 259 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1917#-OBUiI6Q5VxI5uftuS8w:-OBV8PfV4ziopM8Sl_yq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3383aefa7dfc5a57904c45afafaf1a28835bfc1/Cargo.toml#L259)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add instruction (here is a good place?)
</blockquote></details>

Done.
___
*[`scripts/run_tests.py` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1917#-OBLRQIA86L-RUblAeSv:-OBV5_Xx71zokkF3O-pD:b-uknr03) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3383aefa7dfc5a57904c45afafaf1a28835bfc1/scripts/run_tests.py#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you explain? (maybe offline)
</blockquote></details>

Fixed, a bit repetitive, can it be better?


<!-- Sent from Reviewable.io -->

2024-11-12 11:35 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-11-12 11:35 UTC, giladchase commented on scripts/run_tests.py
> +        operands = ["--", "-Dwarning"]  # "--" must be the first element.
:+1: 
<!-- Reviewable comment -OBV8wVQ4Crep-jZM0tQ:b-8fx2u7 -->
<!-- Sent from Reviewable.io -->

2024-11-12 11:35 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-11-12 11:35 UTC, giladchase commented on scripts/run_tests.py
> +        operands = ["--", "-Dwarning"]  # "--" must be the first element.
WOW!
<!-- Reviewable comment -OBV8ztaCiWJQunSplJS:bb763gn -->
<!-- Sent from Reviewable.io -->

2024-11-12 11:37 UTC, giladchase reviewed
> Dismissed @graphite-app[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-11-12 12:06 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`scripts/run_tests.py` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1917#-OBLRQIA86L-RUblAeSv:-OBV9x-j3pfv4XDaM11U:bx08kbx) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3383aefa7dfc5a57904c45afafaf1a28835bfc1/scripts/run_tests.py#L49)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Fixed, a bit repetitive, can it be better?
</blockquote></details>

make the if-else set the base command, then add the operand args outside the if-else blocks?


<!-- Sent from Reviewable.io -->

2024-11-12 12:06 UTC, dorimedini-starkware commented on scripts/run_tests.py
> +        operands = ["--", "-Dwarning"]  # "--" must be the first element.
lolllllllll SCIENCE
<!-- Reviewable comment -OBV9mFC9Kp3p0W38o1s:b5a5tu0 -->
<!-- Sent from Reviewable.io -->

2024-11-12 12:37 UTC, giladchase reviewed
> Dismissed @graphite-app[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`scripts/run_tests.py` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1917#-OBLRQIA86L-RUblAeSv:-OBVMIiTATxDAFTvnBDp:b-ogtn6d) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3383aefa7dfc5a57904c45afafaf1a28835bfc1/scripts/run_tests.py#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

make the if-else set the base command, then add the operand args outside the if-else blocks?
</blockquote></details>

Not sure that would work, inner branches might want to add args/operands, and you have to add them args first, operands later...
Maybe I misunderstand what you mean, can you give a rough psuedo? 


<!-- Sent from Reviewable.io -->

2024-11-12 12:37 UTC, giladchase commented on scripts/run_tests.py
> +        operands = ["--", "-Dwarning"]  # "--" must be the first element.
jjjj
<!-- Reviewable comment -OBVLeaWAkQb5uwultca:bb7isqt -->
<!-- Sent from Reviewable.io -->

2024-11-12 12:37 UTC, giladchase commented on scripts/run_tests.py
> +            return ["scripts/rust_fmt.sh"] + fmt_args
Done.
<!-- Reviewable comment -OBVM6htEfDMF8Djj2ZA:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-11-12 12:48 UTC, giladchase commented
It's messier than i thought, even though it's a rustc flag, rustfmt and doc don't respect it.
Trying a different tactic.

2024-11-12 12:49 UTC, giladchase commented
reopening

2024-11-12 12:57 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1917#-OBVRdin8QbT9hQx23Lz:-OBVRdin8QbT9hQx23M-:b-s4do2j) (no related file):*
Q: what about other CI workflows?
example: blockifier_ci builds the blockifier with the `native` feature; do we need to inject this `-D` everywhere?
___
*[`.github/workflows/main.yml` line 21 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1917#-OBVRUwd4nEtXoX4Tp8H:-OBVRUwe-EjPXonn1rYc:bh2414j) ([raw file](https://github.com/starkware-libs/sequencer/blob/dfc9bca0aa53d50ee7bcd86387f2b7f6545fe55d/.github/workflows/main.yml#L21)):*
> ```YAML
> env:
>   CI: 1
>   RUSTFLAGS: "-D warnings"
> ```

oooh... much better



_Code quote:_
```YAML
RUSTFLAGS: "-D warnings"
```


<!-- Sent from Reviewable.io -->

2024-11-12 13:35 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @graphite-app[bot])

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1917#-OBVRdin8QbT9hQx23Lz:-OBVZrFz4sTLsgQpUQsf:b-izp705) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Q: what about other CI workflows?
example: blockifier_ci builds the blockifier with the `native` feature; do we need to inject this `-D` everywhere?
</blockquote></details>

Don't need really, it's just easier and less error-prone to have this in place rather than in multiple places.
It is unlikely to cause anyone any issues, I saw other popular crates using this pattern in ci.yml.
Moved it closer to callsites.
___
*[`scripts/run_tests.py` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1917#-OBLRQIA86L-RUblAeSv:-OBVS66GDPdW68wR3K8e:bvitohl) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3383aefa7dfc5a57904c45afafaf1a28835bfc1/scripts/run_tests.py#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok now that review-bot made the RUSTFMT case a special case, my way no longer works anyway :P
</blockquote></details>

Ya rustfmt/doc can't handle this operand, which is weird cause they can handle it through RUSTFLAGS alright :shrug: 


<!-- Sent from Reviewable.io -->

2024-11-12 13:35 UTC, giladchase commented on Cargo.toml
> +# - In the terminal: add to .bashrc `export RUSTFLAGS="$RUSTFLAGS -Dwarnings"
SCIENCE!
<!-- Reviewable comment -OBVSG0w5G2TND8U_IcM:b-wyil5q -->
<!-- Sent from Reviewable.io -->

2024-11-12 14:09 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: all files reviewed, 1 unresolved discussion (waiting on @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-11-13 06:32 UTC, giladchase reviewed
> Dismissed @graphite-app[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-11-13 06:34 UTC, giladchase reviewed
> Reviewed 1 of 4 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1917)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-11-13 06:36 UTC, merged