test: add p2p class sync happy flow test
starkware-libs/sequencer pull request #1942
Opened 2024-11-11 12:52 UTC by noamsp-starkware

2024-11-11 12:53 UTC, noamsp-starkware commented
* **#1943** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1943?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1942** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1942?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noamsp-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-13 07:34 UTC, ShahakShama requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942)* status: all files reviewed, 5 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZOQyR2_ZAxYyqzGvv:-OBZOQyR2_ZAxYyqzGvw:bpkaw9y) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_protobuf/src/converters/class.rs#L285)):*
> ```XML
>         });
> 
>         // This length check and default option is needed for ContractClass test instances that
> ```

For next time: IMO this can be a separate preliminary PR
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZQgkM8IO_4l5a8xNP:-OBZQgkM8IO_4l5a8xNQ:b6y4gkf) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_p2p_sync/src/client/class_test.rs#L39)):*
> ```XML
>     // Asserting the constants so the test can assume there will be 2 state diff queries for a
>     // single header query and the second will be smaller than the first.
>     const_assert!(STATE_DIFF_QUERY_LENGTH < HEADER_QUERY_LENGTH);
> ```

Since we're not testing state diffs, we don't need this assertion
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZQg-S3F0Z3-i3lI8B:-OBZQg-S3F0Z3-i3lI8C:b5raetp) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_p2p_sync/src/client/class_test.rs#L53)):*
> ```XML
>     } = setup();
> 
>     let block_hashes_and_signatures =
> ```

Please extract all common code between this test and the state diff test
You can use this opportunity to also remove code duplication between state diff test and 
Suggestion for the function:
```
pub fn run_state_diff_sync(
    header_state_diff_lengths: Vec<usize>,
    state_diff_chunks: Vec<usize>
) -> GenericReceiver<ClassTestPayload> {
    ...
}
```

___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZOqqp0qGqKtVeabKv:-OBZOqqp0qGqKtVeabKw:bg5ub65) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_p2p_sync/src/client/class_test.rs#L192)):*
> ```XML
> }
> 
> fn create_random_state_diff_chunk(rng: &mut ChaCha8Rng) -> StateDiffChunk {
> ```

Unite these two functions into `create_random_state_diff_chunk_with_class`. This way, you'll get rid of the unreachable section
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZP76D5SKvM8N3F4a-:-OBZP76D5SKvM8N3F4a0:b-mu9a4w) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_p2p_sync/src/client/class_test.rs#L194)):*
> ```XML
> fn create_random_state_diff_chunk(rng: &mut ChaCha8Rng) -> StateDiffChunk {
>     let class_hash = ClassHash(rng.next_u64().into());
>     if rng.next_u32() % 2 == 0 {
> ```

use rng.gen_bool() instead (from the Rng trait)


<!-- Sent from Reviewable.io -->

2024-11-14 10:06 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942)* status: all files reviewed, 5 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZQg-S3F0Z3-i3lI8B:-OBe7hFO0GEcmJmQ523m:bera0ie) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_p2p_sync/src/client/class_test.rs#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Please extract all common code between this test and the state diff test
You can use this opportunity to also remove code duplication between state diff test and 
Suggestion for the function:
```
pub fn run_state_diff_sync(
    header_state_diff_lengths: Vec<usize>,
    state_diff_chunks: Vec<usize>
) -> GenericReceiver<ClassTestPayload> {
    ...
}
```

</blockquote></details>

*between state diff positive flow test and negative flow test


<!-- Sent from Reviewable.io -->

2024-11-18 15:10 UTC, noamsp-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZQgkM8IO_4l5a8xNP:-OBzoasu4BGQM0Fj2m0_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_p2p_sync/src/client/class_test.rs#L39)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Since we're not testing state diffs, we don't need this assertion
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZQg-S3F0Z3-i3lI8B:-OBzocI9BzxwhQJqNsWy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_p2p_sync/src/client/class_test.rs#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

*between state diff positive flow test and negative flow test
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZOqqp0qGqKtVeabKv:-OBzocyUAQOf8txvfokq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_p2p_sync/src/client/class_test.rs#L192)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Unite these two functions into `create_random_state_diff_chunk_with_class`. This way, you'll get rid of the unreachable section
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZP76D5SKvM8N3F4a-:-OBzodZPE-94xUk8trFs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_p2p_sync/src/client/class_test.rs#L194)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use rng.gen_bool() instead (from the Rng trait)
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OBZOQyR2_ZAxYyqzGvv:-OBzoeUF9KFMwK18mQfp:b-v0tof7) ([raw file](https://github.com/starkware-libs/sequencer/blob/82219ff1c5c426fce0372155e00cbfe6b59c6dfd/crates/papyrus_protobuf/src/converters/class.rs#L285)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

For next time: IMO this can be a separate preliminary PR
</blockquote></details>

I agree. will do next time.


<!-- Sent from Reviewable.io -->

2024-11-20 06:27 UTC, ShahakShama requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942)* status: 3 of 5 files reviewed, 20 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7E_HR-kj0Uh1v-1k6:-OC7E_HR-kj0Uh1v-1k7:b-v9a6yl) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L76)):*
> ```XML
> 
>     // Create a future that will receive queries, send responses and validate the results.
>     let parse_queries_future = async move {
> ```

Rename it to test_future
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7Efo7D7fuVbG2uKIK:-OC7Efo7D7fuVbG2uKIL:b-6l2eyb) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L84)):*
> ```XML
> 
>         tokio::join! {
>             run_state_diff_sync_custom(
> ```

Put it inside the select in the end of the test (have 3 futures in that select)
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 290 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7CnhUAutHt8BTVYnH:-OC7CnhUAutHt8BTVYnI:b-66mbvi) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L290)):*
> ```XML
> async fn validate_state_diff_fails(
>     header_state_diff_lengths: Vec<usize>,
>     state_diffs: Vec<Option<StateDiffChunk>>,
> ```

Keep the name state_diff_chunks
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC77CuA9O7mtAvWboDh:-OC77CuA9O7mtAvWboDi:bgikyac) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L338)):*
> ```XML
> }
> 
> async fn run_state_diff_sync_custom(
> ```

add doc
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7CMIb9HCRbUgjiiLI:-OC7CMIb9HCRbUgjiiLJ:bk38jb) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L338)):*
> ```XML
> }
> 
> async fn run_state_diff_sync_custom(
> ```

change the word custom to through_channel
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 342 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC77Eom0c9FLaMGEUlH:-OC77Eom0c9FLaMGEUlI:b-8fy4g6) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L342)):*
> ```XML
>     mock_state_diff_response_manager: &mut GenericReceiver<StateDiffTestPayload>,
>     header_state_diff_lengths: Vec<usize>,
>     state_diff_chunk_receiver: &mut mpsc::Receiver<Option<StateDiffChunk>>,
> ```

You can import mpsc::Receiver directly and remove the mpsc:: part. If you saw other cases in the code that reference Receiver with mpsc:: it's because there's also a different type or Receiver in the same file.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 343 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7DEV54qMfJsmLTnpE:-OC7DEV662Fu1N41VDlI:bae84gv) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L343)):*
> ```XML
>     header_state_diff_lengths: Vec<usize>,
>     state_diff_chunk_receiver: &mut mpsc::Receiver<Option<StateDiffChunk>>,
> ) -> Option<StateDiffTestPayload> {
> ```

Remove the return value and instead have a bool argument called should_assert_reported
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 344 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC77XF82oxAwx5sbuLj:-OC77XF82oxAwx5sbuLk:b2qw4ha) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L344)):*
> ```XML
>     state_diff_chunk_receiver: &mut mpsc::Receiver<Option<StateDiffChunk>>,
> ) -> Option<StateDiffTestPayload> {
>     let n_headers = header_state_diff_lengths.len();
> ```

n_headers -> num_headers
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 350 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC77idk-cRWRkL7Smr0:-OC77idk-cRWRkL7Smr1:b-i6zzwo) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L350)):*
> ```XML
>     let mut mock_header_responses_manager = mock_header_response_manager.next().await.unwrap();
> 
>     // Send headers for entire query.
> ```

Either document as assumption that the query length is >= num_headers, assert that, or perform queries in a loop until the sum of query sizes reaches num_headers

I think I prefer the latter. It can also be quite easy if you keep the current loop structure and add a condition that if
`i == sum_query_sizes` then you receive a new query and reset the mock_header_responses_manager
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 354 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC78FKk5_O2LL4LyUce:-OC78FKk5_O2LL4LyUcf:b-urlo1a) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L354)):*
> ```XML
>         block_hashes_and_signatures.iter().zip(header_state_diff_lengths.iter()).enumerate()
>     {
>         // Send responses
> ```

Send header responses
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 402 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC79RdW86l5KR4SXoLQ:-OC79RdX0PiF6EeBqFk0:b-ww3h14) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L402)):*
> ```XML
>                 step: 1,
>             })),
>             "If the limit of the query is too low, try to increase \
> ```

Remove the sleep and instead wait until header marker reaches where it should reach as we discussed be-al pe. You can do this in a separate PR (I think you should) and add a TODO instead
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 407 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7A2B67WCSZdiOQGSv:-OC7A2B67WCSZdiOQGSw:b-brszgr) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L407)):*
> ```XML
> 
>         let mut current_state_diff_length = 0;
>         let destination_state_diff_length = (start_block_number..start_block_number + limit)
> ```

Try instead `header_state_diff_lengths[start_block_number..start_block_number + limit].sum()` or if that doesn't work maybe `header_state_diff_lengths[start_block_number..start_block_number + limit].iter().sum()`
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 426 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7BoZ43DHasHwmbutu:-OC7BoZ43DHasHwmbutv:ba7uxce) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L426)):*
> ```XML
>             }
> 
>             // return if sent an empty/none state diff chunk
> ```

Why do you return here and not continue sending for the next query?
___
*[`crates/pa [...]

2024-11-21 13:23 UTC, noamsp-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942)* status: 2 of 5 files reviewed, 18 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7E_HR-kj0Uh1v-1k6:-OC8nkDGCfvABaJy8w85:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L76)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename it to test_future
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7Efo7D7fuVbG2uKIK:-OCDq4M2241bDxVcFytu:boc9kdn) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L84)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Put it inside the select in the end of the test (have 3 futures in that select)
</blockquote></details>

spoken offline, decided to keep join but move it into the select since we want to verify that both functions terminate successfully.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 290 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7CnhUAutHt8BTVYnH:-OC8nuQS6HdnjTr8vsQX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L290)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Keep the name state_diff_chunks
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7CMIb9HCRbUgjiiLI:-OC8o4ZZ9mfhL2rF7Iqd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L338)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

change the word custom to through_channel
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC77CuA9O7mtAvWboDh:-OCCw9hNCX-4IN-zNHs4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L338)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

add doc
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 342 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC77Eom0c9FLaMGEUlH:-OC8pc4I1f4piY54AL9K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L342)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can import mpsc::Receiver directly and remove the mpsc:: part. If you saw other cases in the code that reference Receiver with mpsc:: it's because there's also a different type or Receiver in the same file.
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 343 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7DEV54qMfJsmLTnpE:-OCCwT9O3x57WSI9TqXm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L343)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove the return value and instead have a bool argument called should_assert_reported
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 344 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC77XF82oxAwx5sbuLj:-OCCwXF42w5LWy8ezWMY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L344)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

n_headers -> num_headers
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 350 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC77idk-cRWRkL7Smr0:-OCD2fR04NC8cd5JIcr_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L350)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Either document as assumption that the query length is >= num_headers, assert that, or perform queries in a loop until the sum of query sizes reaches num_headers

I think I prefer the latter. It can also be quite easy if you keep the current loop structure and add a condition that if
`i == sum_query_sizes` then you receive a new query and reset the mock_header_responses_manager
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 354 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC78FKk5_O2LL4LyUce:-OC8pp0MBrzpmhrXaQA0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L354)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Send header responses
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 407 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7A2B67WCSZdiOQGSv:-OCD51Ym-utTspxQ4tUg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L407)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try instead `header_state_diff_lengths[start_block_number..start_block_number + limit].sum()` or if that doesn't work maybe `header_state_diff_lengths[start_block_number..start_block_number + limit].iter().sum()`
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 426 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7BoZ43DHasHwmbutu:-OCDcR2y6znSVNBLXX5o:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L426)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you return here and not continue sending for the next query?
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 431 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7BttE2MrMieTPY4EF:-OCDcRTo3HSxZXVGi_oU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L431)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you return here and not send more state diffs
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 436 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OC7C5qk9dxagUHAYYG1:-OCDa-JbEZVCB3wWcNZG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed8ccf786433d3bf59f2591f8c2a1fa10bc16b/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L436)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blo [...]

2024-11-21 14:52 UTC, ShahakShama requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942)* status: all files reviewed, 9 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCE4QH8-nuGj0kEVl58:-OCE4QH8-nuGj0kEVl59:b-cgd7vx) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/class_test.rs#L50)):*
> ```XML
> 
>     let mut rng = get_rng();
>     let (class_state_diffs, api_contract_classes): (Vec<_>, Vec<_>) = (0..HEADER_QUERY_LENGTH)
> ```

add TODO to add multiple state diffs per header
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCECFv9ECyCyLMos2sR:-OCECFv9ECyCyLMos2sS:b-9mbcw7) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/class_test.rs#L104)):*
> ```XML
>                 let block_number = BlockNumber(block_number);
> 
>                 // Check that before we've sent all parts the state diff wasn't written yet
> ```

update comment to fit into class test
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 123 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCECSGV70uZ5zvKqtYX:-OCECSGWCAzcMLG7Iy1r:b4b69o9) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/class_test.rs#L123)):*
> ```XML
> 
>                 let txn = storage_reader.begin_ro_txn().unwrap();
>                 let expected_class = match api_contract_class {
> ```

rename api_contract_class to expected_class and rename expected_class to actual_class
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 149 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCEBGzn6vzgYSVh8J5Z:-OCEBGzn6vzgYSVh8J5_:bj9odsp) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/class_test.rs#L149)):*
> ```XML
> }
> 
> trait GetClassHash {
> ```

Why do you declare this as a trait? you can simply write `impl StateDiffChunk {...`
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 353 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCE-s-bCmEBTThEh6vZ:-OCE-MitEvKQYah3f6TR:b-b98bna) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L353)):*
> ```XML
> 
>     // split the headers into queries of size HEADER_QUERY_LENGTH and send headers for each query
>     for header_querie in block_hashes_and_signatures
> ```

header_querie -> headers_for_current_query
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 354 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCE0YpODdoIGxFU5UyA:-OCE0YpP8xLVZ0Ze4jBR:bxvwm9i) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L354)):*
> ```XML
>     // split the headers into queries of size HEADER_QUERY_LENGTH and send headers for each query
>     for header_querie in block_hashes_and_signatures
>         .iter()
> ```

use into_iter and it will save you all the reference mess
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 360 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCE00Wx6WiliQSJxQOW:-OCE00Wx6WiliQSJxQOX:b8htlx4) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L360)):*
> ```XML
>         .chunks(HEADER_QUERY_LENGTH.try_into().unwrap())
>     {
>         let mut mock_header_responses_manager = mock_header_response_manager.next().await.unwrap();
> ```

Until we improve the naming here (it's a task that I plan for Alon to do), please add a comment that you're receiving the next query from sync


<!-- Sent from Reviewable.io -->

2024-11-25 15:01 UTC, noamsp-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942)* status: all files reviewed, 8 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCE4QH8-nuGj0kEVl58:-OCYhmuI86eC222CdnYk:b2nhb2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/class_test.rs#L50)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

add TODO to add multiple state diffs per header
</blockquote></details>

Ack
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCECFv9ECyCyLMos2sR:-OCYhlgq-uuyRBbQ3hlE:b2nhb2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/class_test.rs#L104)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

update comment to fit into class test
</blockquote></details>

Ack
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 123 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCECSGV70uZ5zvKqtYX:-OCYhogIAsjKdIToeMUp:b2nhb2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/class_test.rs#L123)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename api_contract_class to expected_class and rename expected_class to actual_class
</blockquote></details>

Ack
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 149 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCEBGzn6vzgYSVh8J5Z:-OCYgShLA5NV0zzCdy5P:b-7xbtpo) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/class_test.rs#L149)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you declare this as a trait? you can simply write `impl StateDiffChunk {...`
</blockquote></details>

I wanted this function only locally for this test. I can't do it as you suggested in this file since StateDiffChunk is not defined here. We can use this function by either using it how I wrote it or defining it at StateDiffChunk's impl at papyrus_protobuf/src/sync.rs.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 353 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCE-s-bCmEBTThEh6vZ:-OCYiVgG5ozchogbUQPG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L353)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

header_querie -> headers_for_current_query
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 354 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCE0YpODdoIGxFU5UyA:-OCYnRs8CZPU-7zwYH6N:b-p6v3n) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L354)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use into_iter and it will save you all the reference mess
</blockquote></details>

The reference mess occurs because I'm using chunk() splitting. into_iter will only help the header_state_diff_lengths vector, which I need to use later in the test, so I'll need to clone it before using into_iter on it. I think keeping it as before is simpler and more cost-effective. What do you think?
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 360 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCE00Wx6WiliQSJxQOW:-OCYor8d0KC9bZqK-oYN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L360)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Until we improve the naming here (it's a task that I plan for Alon to do), please add a comment that you're receiving the next query from sync
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-26 08:54 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942)* status: all files reviewed, 7 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 149 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCEBGzn6vzgYSVh8J5Z:-OCbemVnCgsc3N-xSjqN:bi26gkx) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/class_test.rs#L149)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

I wanted this function only locally for this test. I can't do it as you suggested in this file since StateDiffChunk is not defined here. We can use this function by either using it how I wrote it or defining it at StateDiffChunk's impl at papyrus_protobuf/src/sync.rs.
</blockquote></details>

Very well. Write down a comment saying that (that you define a new trait here in order to just add a method to GetClassHash because it comes from another crate)
___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 354 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCE0YpODdoIGxFU5UyA:-OCbf4iTAPvBzU1PNr7I:b-761qkp) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L354)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

The reference mess occurs because I'm using chunk() splitting. into_iter will only help the header_state_diff_lengths vector, which I need to use later in the test, so I'll need to clone it before using into_iter on it. I think keeping it as before is simpler and more cost-effective. What do you think?
</blockquote></details>

cost is not a concern here. The main concern is readability.
How about .cloned() at the end?


<!-- Sent from Reviewable.io -->

2024-11-26 11:13 UTC, noamsp-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942)* status: all files reviewed, 7 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/state_diff_test.rs` line 354 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-OCE0YpODdoIGxFU5UyA:-OCc9l5U0vxpOGebbf1w:b-7scgqr) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea85b7251df03a41989f2b4b8303bc78b467cb03/crates/papyrus_p2p_sync/src/client/state_diff_test.rs#L354)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

Cloned() doesn't work easily because it requires type annotations. This workaround reduces all reference levels.
</blockquote></details>

If the map(Vec::from) at the end looks weird to you, I can just remove the ref level like this:

for **&**(i, ((block\_hash, block\_signature), header\_state\_diff\_length)) in

headers\_for\_current\_query


<!-- Sent from Reviewable.io -->

2024-11-27 07:42 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-:-OCgZ_x_E6-vffSSpN6c:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)



<!-- Sent from Reviewable.io -->

2024-11-27 12:02 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1942#-:-OChVBo766Dnd_5LV0Wo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)



<!-- Sent from Reviewable.io -->

2024-11-27 12:55 UTC, merged