test: add p2p class sync fail cases tests
starkware-libs/sequencer pull request #1943
Opened 2024-11-11 12:52 UTC by noamsp-starkware

2024-11-11 12:52 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1943)
<!-- Reviewable:end -->

2024-11-11 12:53 UTC, noamsp-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1943?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1943** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1943?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1942** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1942?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noamsp-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-12-01 08:06 UTC, ShahakShama requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1943)* status: all files reviewed, 6 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OCn3yMP1X_x9bmLb1uG:-OCn3yMP1X_x9bmLb1uH:bg1ro95) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L199)):*
> ```XML
>         vec![2],
>         vec![
>             Some(StateDiffChunk::DeclaredClass(DeclaredClass::default())),
> ```

These two will have the same hash and should also result in a conflict error. Please change one of them to a non default value
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OCn4JlrC-BQ9tOy3OrL:-OCn4JlrC-BQ9tOy3OrM:b-k05u76) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L218)):*
> ```XML
> // was returned from parse_data_for_block. We currently dont have a way to check this.
> #[tokio::test]
> async fn class_not_in_state_diff() {
> ```

The class_hash and class_hash_in_state_diff in the test are the same. The name of this test should be "class_is_cairo0_and_cairo1_in_state_diff" or something like that. Plus, add a new test that does what the name of this test suggests
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OD0BZhL3nuHoHsI4m5V:-OD0BZhL3nuHoHsI4m5W:b-gpu458) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L239)):*
> ```XML
>         vec![2],
>         vec![
>             Some(StateDiffChunk::DeclaredClass(DeclaredClass::default())),
> ```

This is an invalid state diff (see comment above). Change it to contain different hashes
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OD0Ed6BEPidNn9dZJVr:-OD0Ed6BEPidNn9dZJVs:bcud2wg) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L239)):*
> ```XML
>         vec![2],
>         vec![
>             Some(StateDiffChunk::DeclaredClass(DeclaredClass::default())),
> ```

This test contains two errors (conflicting hashes and missing hashes).
I think what we can do is change it to have 3 hashes in the state diff and 2 classes sent, then we can test that it fails and doesn't wait for the 3rd class to be sent


<!-- Sent from Reviewable.io -->

2025-01-12 12:23 UTC, noamsp-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1943)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OCn3yMP1X_x9bmLb1uG:-OGPLVuV6PwmUzNksFCy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L199)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

These two will have the same hash and should also result in a conflict error. Please change one of them to a non default value
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OCn4JlrC-BQ9tOy3OrL:-OGPLV6UDy9QdKy99EMF:b-sn3i14) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L218)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The class_hash and class_hash_in_state_diff in the test are the same. The name of this test should be "class_is_cairo0_and_cairo1_in_state_diff" or something like that. Plus, add a new test that does what the name of this test suggests
</blockquote></details>

IMO the test name suits the current implementation since we assume the deprecated and non deprecated table don't have an overlapping (this is checked at state_diff). I think its better to generalize this test to more randomized version, either provided class_hash is of same type but different hash, or different type and then obviously the class is not in the state diff.
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OD0BZhL3nuHoHsI4m5V:-OGPMTSd3cchsThNbGTC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L239)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is an invalid state diff (see comment above). Change it to contain different hashes
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OD0Ed6BEPidNn9dZJVr:-OGPNJvYD9Qzt7uME3FE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L239)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This test contains two errors (conflicting hashes and missing hashes).
I think what we can do is change it to have 3 hashes in the state diff and 2 classes sent, then we can test that it fails and doesn't wait for the 3rd class to be sent
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 316 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OCn991Q-L6s_2W7ENbL:-OGPNLm0-mewYydNaiLM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L316)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

i recommend having a timeout clause to make sure this test ends
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-12 14:35 UTC, ShahakShama requested changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1943)* status: all files reviewed, 7 unresolved discussions (waiting on @eitanm-starkware and @noamsp-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OCn4JlrC-BQ9tOy3OrL:-OGPuaCZACTqocIWcMPW:b-bqvzna) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L218)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

IMO the test name suits the current implementation since we assume the deprecated and non deprecated table don't have an overlapping (this is checked at state_diff). I think its better to generalize this test to more randomized version, either provided class_hash is of same type but different hash, or different type and then obviously the class is not in the state diff.
</blockquote></details>

Why not create two separate tests instead of generalizing?
Anyway, I think the case where the class is not in state diff is much more interesting so I'd rather we test only that case if you don't want to do two tests
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OD0Ed6BEPidNn9dZJVr:-OGPvRg9-TLbZAU7vvLY:b-30isv) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L239)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Write this discussion as a comment. Say that the state diff contains 3 classes to check that we return the error once we encounter duplicate class and not wait for the third class
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 255 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OGPw0MC4Z3jexSygtO6:-OGPw0MD5ZaCj7YB2R8y:bpy97ij) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a27ce97b0024bc9007f5c3d5c258b1ce5eead51/crates/papyrus_p2p_sync/src/client/class_test.rs#L255)):*
> ```XML
>     let mut rng = get_rng();
> 
>     let mut actions = vec![
> ```

Add TODO to remove code dup with state diff test
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 294 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OGPw77G2NCOdCkiY7sx:-OGPw77G2NCOdCkiY7sy:b-odljvd) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a27ce97b0024bc9007f5c3d5c258b1ce5eead51/crates/papyrus_p2p_sync/src/client/class_test.rs#L294)):*
> ```XML
>     }
> 
>     actions.push(Action::ValidateReportSent(DataType::Class));
> ```

Add a comment saying that we validate the report is sent before we send fin


<!-- Sent from Reviewable.io -->

2025-01-12 14:47 UTC, noamsp-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1943)* status: all files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OCn4JlrC-BQ9tOy3OrL:-OGPypDkEU8iQgMwiN0l:b19lok7) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L218)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not create two separate tests instead of generalizing?
Anyway, I think the case where the class is not in state diff is much more interesting so I'd rather we test only that case if you don't want to do two tests
</blockquote></details>

Spoken offline, keeping as is.
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OD0Ed6BEPidNn9dZJVr:-OGPyR_ACg3w4jhvLdf_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9439cf303615857eeec55cbe7fe98eb14a7631a2/crates/papyrus_p2p_sync/src/client/class_test.rs#L239)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Write this discussion as a comment. Say that the state diff contains 3 classes to check that we return the error once we encounter duplicate class and not wait for the third class
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/class_test.rs` line 255 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-OGPw0MC4Z3jexSygtO6:-OGPy_fx0ArDAkGtnQS7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a27ce97b0024bc9007f5c3d5c258b1ce5eead51/crates/papyrus_p2p_sync/src/client/class_test.rs#L255)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to remove code dup with state diff test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-12 14:48 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-:-OGPzFaO5PNjXi4mmfpa:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware and @noamsp-starkware)



<!-- Sent from Reviewable.io -->

2025-01-12 14:49 UTC, eitanm-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1943#-:-OGPzTzn-xSzxzwCNoyR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)



<!-- Sent from Reviewable.io -->

2025-01-12 15:33 UTC, merged