chore(blockifier_reexecution): add parallel offline reexecution
starkware-libs/sequencer pull request #1981
Opened 2024-11-12 11:45 UTC by aner-starkware

2024-11-12 11:45 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1981)
<!-- Reviewable:end -->

2024-11-13 13:27 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1981)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1981#-OBVGPSo7KV9txMVXCgA:-OBVuxBE6s2fMzctvdTY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d438297e0637939a6072ece4f7b3e2994ff1a101/crates/blockifier_reexecution/src/main.rs#L92)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shouldn't the type be `Option<Vec<u64>>`?
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1981#-OBVGeSt5lXBO-Y8osYF:-OB_f6lM3uYUhGIW8RLm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d438297e0637939a6072ece4f7b3e2994ff1a101/crates/blockifier_reexecution/src/main.rs#L168)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a comment like this over every `spawn_blocking` line
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1981#-OBVH7S52uPxVALzFbFS:-OB_f5J09OT51hFh0V8x:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d438297e0637939a6072ece4f7b3e2994ff1a101/crates/blockifier_reexecution/src/main.rs#L197)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

change above to `Option` and then you can do this
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1981#-OBVHX3wCBh86G7IvXZx:-OB_fAiGEWeROV71StuH:b3a43bj) ([raw file](https://github.com/starkware-libs/sequencer/blob/d438297e0637939a6072ece4f7b3e2994ff1a101/crates/blockifier_reexecution/src/main.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

non-blocking
</blockquote></details>

I think it's a bit strange to spawn inside a mapping, I prefer it to be clearer when new threads are spawned.


<!-- Sent from Reviewable.io -->

2024-11-13 14:24 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1981)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1981#-OB_u9qsAWrTTLAGy6OO:-OB_u9qsAWrTTLAGy6OP:b-cr4hqw) ([raw file](https://github.com/starkware-libs/sequencer/blob/15e7ba321a511eb1f371f69af1a0326f120cd37a/crates/blockifier_reexecution/src/main.rs#L204)):*
> ```XML
>             let block_numbers = block_numbers
>                 .map(|block_numbers| block_numbers.into_iter().map(BlockNumber).collect())
>                 .unwrap_or(get_block_numbers_for_reexecution());
> ```

duplicated logic - please put in a function and use twice



_Suggestion:_
```XML
            let block_numbers = parse_block_numbers_arg(block_numbers);
```


<!-- Sent from Reviewable.io -->

2024-11-18 10:03 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1981#-:-OByicrq39MWrJ-lESCq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2024-11-18 10:26 UTC, merged