chore(network): stress test utils
starkware-libs/sequencer pull request #1995
Opened 2024-11-12 15:00 UTC by eitanm-starkware

2024-11-12 15:00 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1995)
<!-- Reviewable:end -->

2024-11-13 11:19 UTC, eitanm-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1995)* status: all files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1995#-OBZD0Y42rdO1-LrjeAz:-OB_Ee7KDST8VASmiQrt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca218367856f035b731cbb435f60460f9361e4ab/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L33)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract to a constant, and calculate it by using https://doc.rust-lang.org/std/mem/fn.size_of.html and addition
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/network_stress_test/utils.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1995#-OBZDcOc1JTF8zRQinc_:-OBZZkOyC15fyBGcLR5O:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca218367856f035b731cbb435f60460f9361e4ab/crates/papyrus_network/src/bin/network_stress_test/utils.rs#L19)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to num_messages
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/network_stress_test/utils.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1995#-OBZEDVmA3YfL_zpIyRk:-OBZatg44rKhZoXU9t7_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca218367856f035b731cbb435f60460f9361e4ab/crates/papyrus_network/src/bin/network_stress_test/utils.rs#L86)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This function both converts to u64 and serializes. IMO it shouldn't do both. If you disagree at least rename it to reflect that it does both
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/network_stress_test/utils.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1995#-OBZE4BeDe5yFt7KaTgn:-OBZaT3W-HhIDlR02AjH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca218367856f035b731cbb435f60460f9361e4ab/crates/papyrus_network/src/bin/network_stress_test/utils.rs#L93)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not `duration_since_epoch.as_millis()
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-13 12:23 UTC, ShahakShama requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1995)* status: all files reviewed, 3 unresolved discussions (waiting on @eitanm-starkware and @graphite-app[bot])

___
*[`crates/papyrus_network/src/bin/network_stress_test/utils.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1995#-OBZEDVmA3YfL_zpIyRk:-OB_TNs2DLw_i9uSjHJG:bxegryg) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca218367856f035b731cbb435f60460f9361e4ab/crates/papyrus_network/src/bin/network_stress_test/utils.rs#L86)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is not done
___
*[`crates/papyrus_network/src/bin/network_stress_test/utils.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1995#-OBZE4BeDe5yFt7KaTgn:-OB_TQc1DMN5Xlq3odMo:bxegryg) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca218367856f035b731cbb435f60460f9361e4ab/crates/papyrus_network/src/bin/network_stress_test/utils.rs#L93)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is not done


<!-- Sent from Reviewable.io -->

2024-11-13 12:23 UTC, ShahakShama commented on crates/papyrus_network/src/bin/network_stress_test/converters.rs
> +pub const METADATA_SIZE: usize = size_of::<SystemTime>() + size_of::<u32>();
:+1: 
<!-- Reviewable comment -OB_TCC0ELhrx5eGIerk:b-8fx2u7 -->
<!-- Sent from Reviewable.io -->

2024-11-13 13:16 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1995#-:-OB_ehfAC2WrSBrc_Obx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-11-13 13:16 UTC, ShahakShama commented on crates/papyrus_network/src/bin/network_stress_test/utils.rs
> +        duration_since_epoch.as_millis() + u128::from(duration_since_epoch.subsec_millis());
:+1:
<!-- Reviewable comment -OB_eQK4EQ29q-0zGhta:bb6mt9b -->
<!-- Sent from Reviewable.io -->

2024-11-13 13:17 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1995#-:-OB_f13F76lzw80vd_Eb:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-12-22 08:04 UTC, closed without merging