feat(mempool): impl calculate-gas-price according to EIP 1559
starkware-libs/sequencer pull request #203
Opened 2024-07-30 11:33 UTC by MohammadNassar1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/203)

2024-07-30 12:24 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O32a-Db47oaoeeWS0ti:-O32a-Dc-d5TZLjygQiD:bm7dz55) (no related file):*
This PR implements the calculation of gap price according to EIP 1559.
High level explanation of EIP 1559:
https://eips.ethereum.org/EIPS/eip-1559

___


<!-- Sent from Reviewable.io -->

2024-08-05 13:05 UTC, giladchase requested changes
Can you plz describe a flow that will use this function?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203#-:-O3XPn_f2WvmgAFLNAZm:bw12hu1)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3Xd2lIAvzo0dowmB6x:-O3Xd2lJ82hB8gVQfwQh:b33dtk2) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L32)):*
> ```XML
>     ///
>     /// # Parameters
>     /// - `current_price`: The base fee of the current block.
> ```

Question: is this really the current price? isn't it the previous base price, whereas the current price is the result of this block? Maybe it's not clear to me exactly when this should be called...



_Code quote:_
```XML
    /// - `current_price`: The base fee of the current block.
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XP2dK3BjE6zRFeCI4:-O3XP2dK3BjE6zRFeCI5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L38)):*
> ```XML
>     /// # Returns
>     /// The price for the next block.
>     pub fn calculate_gas_price(
> ```





_Suggestion:_
```XML
    pub fn calculate_estimated_gas_price(
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XPHQZEJGcow0ekEtN:-O3XPHQZEJGcow0ekEtO:b-irdvpl) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L38)):*
> ```XML
>     /// # Returns
>     /// The price for the next block.
>     pub fn calculate_gas_price(
> ```

Make into a free function, this doesn't use `BlockInfo`.
Keeping this as a free function inside a `block` makes sense.
___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XVI_l88e-0hc6tN4K:-O3XVI_l88e-0hc6tN4L:b-cs3q8) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
> ```XML
>         current_gas_target: u64,
>     ) -> u64 {
>         const BASE_FEE_MAX_CHANGE_DENOMINATOR: u64 = 2;
> ```

add docstring to explain this, perhaps describe it as a "sensitivity parameter" and mention that it limits the max _rate_ of change between consecutive blocks. 
Also why are we using 2 and not 8 like the eip? is that a requirement?



_Code quote:_
```XML
       const BASE_FEE_MAX_CHANGE_DENOMINATOR: u64 = 2;
```


<!-- Sent from Reviewable.io -->

2024-08-06 10:05 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3Xd2lIAvzo0dowmB6x:-O3b4MUZ0Kn177w5kMoF:bk1ojo5) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Question: is this really the current price? isn't it the previous base price, whereas the current price is the result of this block? Maybe it's not clear to me exactly when this should be called...
</blockquote></details>

Let's go with no prefix for input, and "next" for the output.
___
*[`crates/blockifier/src/blockifier/block.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XP2dK3BjE6zRFeCI4:-O3b4SjuDVauJEy5xcDA:b-8ssy2k) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L38)):*
> ```XML
>     /// # Returns
>     /// The price for the next block.
>     pub fn calculate_gas_price(
> ```

Maybe `calculate_next_base_gas_price`?
___
*[`crates/blockifier/src/blockifier/block.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XPHQZEJGcow0ekEtN:-O3b5U9o38zgNTGN97ob:b-5wlu0u) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L38)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Make into a free function, this doesn't use `BlockInfo`.
Keeping this as a free function inside a `block` makes sense.
</blockquote></details>

I'm actually not sure this is the right location, it's related to `BlockContext` creation. Also, it might be an independent logic that might be invoked from code that isn't related to execuion.
___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XSq-d9DADMWmJ6Q5B:-O3XSq-e9hAxmf_5HCr9:bqoopl2) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
> ```XML
>         current_gas_target: u64,
>     ) -> u64 {
>         const BASE_FEE_MAX_CHANGE_DENOMINATOR: u64 = 2;
> ```

Should this number be configurable?



_Code quote:_
```XML
const BASE_FEE_MAX_CHANGE_DENOMINATOR: u64 = 2;
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3b4d2c5bjmc6r2W5YA:-O3b4d2c5bjmc6r2W5YB:bvjvmql) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L44)):*
> ```XML
>     ) -> u64 {
>         const BASE_FEE_MAX_CHANGE_DENOMINATOR: u64 = 2;
> ```

Are we okay with this integer division?


<!-- Sent from Reviewable.io -->

2024-08-06 10:29 UTC, elintul submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3b4d2c5bjmc6r2W5YA:-O3bE7NVDHIC1M0Q8IM1:b-2n53p3) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L44)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are we okay with this integer division?
</blockquote></details>

Maybe we should work with floats and only round in the end? 
___
*[`crates/blockifier/src/blockifier/block.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3bDqXV-C4H2ZLf0s13:-O3bDqXWDrxWHzQTCxID:bvx59l6) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L54)):*
> ```XML
>         } else {
>             current_price - price_change
>         }
> ```

WDYT about calculating the adjustment factor, and returning `base_price * adjustment_factor`?


<!-- Sent from Reviewable.io -->

2024-08-06 10:29 UTC, elintul reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-08-13 08:56 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3Xd2lIAvzo0dowmB6x:-O49tSv1-rMNqioYWfmw:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's go with no prefix for input, and "next" for the output.
</blockquote></details>

Done
___
*[`crates/blockifier/src/blockifier/block.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XP2dK3BjE6zRFeCI4:-O49r1PWEMBt5jWhsfxG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe `calculate_next_base_gas_price`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XVI_l88e-0hc6tN4K:-O49sPOj5Y1yJpSZol_5:b-z85neo) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

add docstring to explain this, perhaps describe it as a "sensitivity parameter" and mention that it limits the max _rate_ of change between consecutive blocks. 
Also why are we using 2 and not 8 like the eip? is that a requirement?
</blockquote></details>

Product should provide the required value, added a todo.
___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XSq-d9DADMWmJ6Q5B:-O49sWfg1Yk9dCKV0plP:b-7hbprb) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Should this number be configurable?
</blockquote></details>

wdym?
___
*[`crates/blockifier/src/blockifier/block.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3b4d2c5bjmc6r2W5YA:-O49sYD14mtzmGiz-Jdg:b-w0zu70) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L44)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe we should work with floats and only round in the end?
</blockquote></details>

It appears that we do not. Added a docstring, which explains why.


<!-- Sent from Reviewable.io -->

2024-08-13 09:00 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XPHQZEJGcow0ekEtN:-O49x2ft9Niq46PRq03w:bj1wso9) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm actually not sure this is the right location, it's related to `BlockContext` creation. Also, it might be an independent logic that might be invoked from code that isn't related to execuion.
</blockquote></details>

"As I understand, this should ideally be part of the consensus unit, which we currently do not have. Therefore, I've added it to the blockifier. I believe that `BlockInfo` is an appropriate place for this, as it contains relevant information about the block. wdyt?
___
*[`crates/blockifier/src/blockifier/block.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3bDqXV-C4H2ZLf0s13:-O49xZnr24Hgu78MWxZu:b158yo1) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L54)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT about calculating the adjustment factor, and returning `base_price * adjustment_factor`?
</blockquote></details>

In any case, we still need to retrieve the old price. 
Where is the suggested returned value used? I believe it's only utilized after updating to the next price


<!-- Sent from Reviewable.io -->

2024-08-13 09:04 UTC, MohammadNassar1 reviewed
Sure.
As part of block creation, the blockifier calculates the gas used. To manage network congestion, the gas price is adjusted based on the current congestion level. 
At the end of the block creation round, the consensus unit (or possibly the blockifier) needs to calculate the gas price for the next block using this function. This updated gas price is then sent to other components, such as other blockifiers, mempools, gateways, etc.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203#-:-O49y07GEirn4Z3ztsj1:b-c4q3j0)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-08-14 06:22 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XVI_l88e-0hc6tN4K:-O4EQEmI5cjXVltEQt5M:bzhvt4h) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Product should provide the required value, added a todo.
</blockquote></details>

I think we can check with product on this value now instead of using a TODO. Should be a quick question
___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XSq-d9DADMWmJ6Q5B:-O4EWhYc30GBmpnyct-9:b6x7lus) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

wdym?
</blockquote></details>

Through a config, rather than as a const, i'm leaning towards const but perhaps we should ask product to be sure.
___
*[`crates/blockifier/src/blockifier/block.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O4EXv3g2wbjBKT8xwUR:-O4EXv3g2wbjBKT8xwUS:b-osc72e) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ceab14170053a5d857f21c80f398087c888b54b/crates/blockifier/src/blockifier/block.rs#L55)):*
> ```XML
>         // Calculate the gas change as u128 to handle potential overflow during multiplication.
>         let gas = price_u128.checked_mul(gas_delta_u128).unwrap();
>         let price_change_u128 = gas / gas_target_u128 / BASE_FEE_MAX_CHANGE_DENOMINATOR;
> ```

Add something to ward off anyone from switching the order of operations, specifically that div must happen after mul and why



_Code quote:_
```XML
        // Calculate the gas change as u128 to handle potential overflow during multiplication.
        let gas = price_u128.checked_mul(gas_delta_u128).unwrap();
        let price_change_u128 = gas / gas_target_u128 / BASE_FEE_MAX_CHANGE_DENOMINATOR;
```


<!-- Sent from Reviewable.io -->

2024-08-15 09:07 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XVI_l88e-0hc6tN4K:-O4KHEgiEh8LdL2-o_iW:b-u299xq) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think we can check with product on this value now instead of using a TODO. Should be a quick question
</blockquote></details>

Asked them in a #mempool-dev channel.
___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XSq-d9DADMWmJ6Q5B:-O4KHYeCDdQTJ5sr9xGh:b-8shg0d) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Through a config, rather than as a const, i'm leaning towards const but perhaps we should ask product to be sure.
</blockquote></details>

asked produce


<!-- Sent from Reviewable.io -->

2024-08-18 07:39 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @giladchase)



<!-- Sent from Reviewable.io -->

2024-08-19 05:46 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XSq-d9DADMWmJ6Q5B:-O4d9yk5BwVisKi3VCk9:b-pdavaq) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

asked produce
</blockquote></details>

Any updates?


<!-- Sent from Reviewable.io -->

2024-08-19 07:45 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XVI_l88e-0hc6tN4K:-O4da3FT5zvR1XKWchGZ:b-pdavaq) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Asked them in a #mempool-dev channel.
</blockquote></details>

Any updates?


<!-- Sent from Reviewable.io -->

2024-08-19 14:39 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XSq-d9DADMWmJ6Q5B:-O4f3yzB09H3BbRyfXV9:b-bajka) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Any updates?
</blockquote></details>

not yet
___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XVI_l88e-0hc6tN4K:-O4f4-7P3X86IY918JE5:b-bajka) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Any updates?
</blockquote></details>

not yet
___
*[`crates/blockifier/src/blockifier/block.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O4EXv3g2wbjBKT8xwUR:-O4f3xia2ZL3QqKqU1IW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ceab14170053a5d857f21c80f398087c888b54b/crates/blockifier/src/blockifier/block.rs#L55)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add something to ward off anyone from switching the order of operations, specifically that div must happen after mul and why
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-21 07:25 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XVI_l88e-0hc6tN4K:-O4nmu2N-0wHRQhRf79c:bdxgxr5) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L43)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

not yet
</blockquote></details>

In favor of resolving, if prod don't know yet then we can keep it at a TODO level.

Only thing is, why did you pick 2 as the default rather than 8, as is in ethereum?
___
*[`crates/blockifier/src/blockifier/block.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O4EXv3g2wbjBKT8xwUR:-O4nnClH3azwEYki5Il1:b-q1ewmz) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ceab14170053a5d857f21c80f398087c888b54b/crates/blockifier/src/blockifier/block.rs#L55)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where? :sweat_smile: 

i meant something like:

```rust
let scaled_gas_price = price_u128.checked_mul(gas_delta_u128).unwrap();
// Calculate the price change, maintaining precision by dividing after multiplication.
// This avoids significant precision loss that would occur if dividing before multiplication.
let price_change_u128 = scaled_gas_price / gas_target_u128 / BASE_FEE_MAX_CHANGE_DENOMINATOR;
```


<!-- Sent from Reviewable.io -->

2024-08-21 11:07 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-08-22 15:04 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O4uZw5x8yZKP14n2yGX:-O4uZw5x8yZKP14n2yGY:b-alsiri) (no related file):*
Once you approve this PR, I'll move the method to the fee_market.rs file under the more batch crate.

___
___
*[`crates/blockifier/src/blockifier/block.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O4EXv3g2wbjBKT8xwUR:-O4uaV4J31PGYDNXSEzc:b-j9l4re) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ceab14170053a5d857f21c80f398087c888b54b/crates/blockifier/src/blockifier/block.rs#L55)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

where? :sweat_smile: 

i meant something like:

```rust
let scaled_gas_price = price_u128.checked_mul(gas_delta_u128).unwrap();
// Calculate the price change, maintaining precision by dividing after multiplication.
// This avoids significant precision loss that would occur if dividing before multiplication.
let price_change_u128 = scaled_gas_price / gas_target_u128 / BASE_FEE_MAX_CHANGE_DENOMINATOR;
```
</blockquote></details>

Ooh, I thought you were referring to adding to the docstring.
Do you think I should also include it in the docstring?


<!-- Sent from Reviewable.io -->

2024-08-25 08:49 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O4EXv3g2wbjBKT8xwUR:-O57fn0w4TptxRbgA1JX:b9ro1ee) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ceab14170053a5d857f21c80f398087c888b54b/crates/blockifier/src/blockifier/block.rs#L55)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Ooh, I thought you were referring to adding to the docstring.
Do you think I should also include it in the docstring?
</blockquote></details>

Nope, code comment suffices i think 


<!-- Sent from Reviewable.io -->

2024-08-25 13:47 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O4EXv3g2wbjBKT8xwUR:-O58mN1EAAh6kiLxuQv7:b-bw8e14) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ceab14170053a5d857f21c80f398087c888b54b/crates/blockifier/src/blockifier/block.rs#L55)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Nope, code comment suffices i think
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2024-08-26 07:47 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 46 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5CdtGK7hES31RHrNTu:-O5CdtGK7hES31RHrNTv:b-gwsma7) ([raw file](https://github.com/starkware-libs/sequencer/blob/5801f5c583bef3c73d1a50c45ff615c2f896abc8/crates/blockifier/src/blockifier/block.rs#L46)):*
> ```XML
>         // We use unsigned integers (u64 and u128) to avoid overflow issues, as the input values are
>         // naturally unsigned and i256 is unstable in Rust. This approach allows safe handling of
>         // all inputs using u128 for intermediate calculations.
> ```

This explains why cannot use signed numbers.



_Code quote:_
```XML
        // We use unsigned integers (u64 and u128) to avoid overflow issues, as the input values are
        // naturally unsigned and i256 is unstable in Rust. This approach allows safe handling of
        // all inputs using u128 for intermediate calculations.
```


<!-- Sent from Reviewable.io -->

2024-08-27 11:05 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 50 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5IV87UAJa4nT8JoPuR:-O5IV87UAJa4nT8JoPuS:b-muzpam) ([raw file](https://github.com/starkware-libs/sequencer/blob/d55c752fc930b819dc969f6cad6e546036df6363/crates/blockifier/src/blockifier/block.rs#L50)):*
> ```XML
>         // The difference between gas_used and gas_target is always u64.
>         let gas_delta = gas_used.abs_diff(gas_target);
>         // Convert to u128 to prevent overflow and because u64 * u64 results in u128.
> ```

a product of two u64 fits inside a u128.



_Code quote:_
```XML
u64 * u64 results in u128.
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5IVH_xC2RM8Z3RN-IB:-O5IVH_xC2RM8Z3RN-IC:b-rskhl1) ([raw file](https://github.com/starkware-libs/sequencer/blob/d55c752fc930b819dc969f6cad6e546036df6363/crates/blockifier/src/blockifier/block.rs#L58)):*
> ```XML
>         let gas_delta_cost =
>             price_u128.checked_mul(gas_delta_u128).expect("Both variables originate from u64");
>         // Calculate the price change, maintaining precision by dividing after multiplication.
> ```

scaling up the result.



_Code quote:_
```XML
multiplication.
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5IVMA0C7UYak223uxu:-O5IVMA0C7UYak223uxv:b-4o05d2) ([raw file](https://github.com/starkware-libs/sequencer/blob/d55c752fc930b819dc969f6cad6e546036df6363/crates/blockifier/src/blockifier/block.rs#L60)):*
> ```XML
>         // Calculate the price change, maintaining precision by dividing after multiplication.
>         // This avoids significant precision loss that would occur if dividing before
>         // multiplication.
> ```

As per our meeting, this relying on certain bounds on our variables, which need to be documented somehow, without these bounds this statement doesn't hold water on its own.

Please think about where we can document these bounds (so we can reference them here), consult with Elin as needed.



_Code quote:_
```XML
        // This avoids significant precision loss that would occur if dividing before
        // multiplication.
```


<!-- Sent from Reviewable.io -->

2024-08-28 14:06 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 50 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5IV87UAJa4nT8JoPuR:-O5OCOnP3OeDsp_zbfGi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d55c752fc930b819dc969f6cad6e546036df6363/crates/blockifier/src/blockifier/block.rs#L50)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

a product of two u64 fits inside a u128.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5IVH_xC2RM8Z3RN-IB:-O5OCX9z0KTqQ5I35tIt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d55c752fc930b819dc969f6cad6e546036df6363/crates/blockifier/src/blockifier/block.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

scaling up the result.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5IVMA0C7UYak223uxu:-O5OIhfn0qOjWvuL2TtM:b-jjfbm7) ([raw file](https://github.com/starkware-libs/sequencer/blob/d55c752fc930b819dc969f6cad6e546036df6363/crates/blockifier/src/blockifier/block.rs#L60)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

As per our meeting, this relying on certain bounds on our variables, which need to be documented somehow, without these bounds this statement doesn't hold water on its own.

Please think about where we can document these bounds (so we can reference them here), consult with Elin as needed.
</blockquote></details>

Added as a comment after the division.
Let me know what do you think about it.


<!-- Sent from Reviewable.io -->

2024-08-28 14:10 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5OIv1zDyrf-52Y6Mnb:-O5OIv1zDyrf-52Y6Mnc:b-nqkhdy) (no related file):*
Question: Noam suggests returning the maximum between the calculation result and a minimum gas price value. Should this be integrated into the function's calculation?

___


<!-- Sent from Reviewable.io -->

2024-08-28 14:36 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5OIv1zDyrf-52Y6Mnb:-O5OPdWh34fYfbaDbfx0:bb77ufg) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Question: Noam suggests returning the maximum between the calculation result and a minimum gas price value. Should this be integrated into the function's calculation?
</blockquote></details>

Yes.

___
___
*[`crates/blockifier/src/blockifier/block.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XPHQZEJGcow0ekEtN:-O5OPGyi6C-lXVQ8YYAV:b-oaiqpe) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L38)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

"As I understand, this should ideally be part of the consensus unit, which we currently do not have. Therefore, I've added it to the blockifier. I believe that `BlockInfo` is an appropriate place for this, as it contains relevant information about the block. wdyt?
</blockquote></details>

Move to `blockifier/fee/fee_market.rs` towards merging this.


<!-- Sent from Reviewable.io -->

2024-08-29 03:56 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5IVMA0C7UYak223uxu:-O5RG2zPANylBJ0EPNbx:buqtpac) ([raw file](https://github.com/starkware-libs/sequencer/blob/d55c752fc930b819dc969f6cad6e546036df6363/crates/blockifier/src/blockifier/block.rs#L60)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Added as a comment after the division.
Let me know what do you think about it.
</blockquote></details>

I remember Noam bringing up specific bounds on these variables, have you spoken with Elin about these bounds and discussed how to incorporate them into the project?

The comment is OK, but it can go stale, especially if the gas_target isn't defined here, but only given as an arg (if the gas_target changes at someplace else, no one will know that this comment got stale).

So I'd like to know what the plan for these consts is before we add the comment, so I'll be able to know how reasonable it is to put it here.


<!-- Sent from Reviewable.io -->

2024-08-29 07:25 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O3XPHQZEJGcow0ekEtN:-O5Rlgdm99TJSuSwiqsf:b13ex4y) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3d087d698ab7bea51b8b2865a5f6faaa9dcb615/crates/blockifier/src/blockifier/block.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move to `blockifier/fee/fee_market.rs` towards merging this.
</blockquote></details>

Once you approve it, I'll move to `batcher/fee/fee_market.rs`.


<!-- Sent from Reviewable.io -->

2024-08-29 08:03 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5OIv1zDyrf-52Y6Mnb:-O5S8o1C5SQqASrdDLU5:bb6un1j) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2024-08-29 14:56 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5IVMA0C7UYak223uxu:-O5Tb0Z42MoZx2tg7O5m:b-g0stnh) ([raw file](https://github.com/starkware-libs/sequencer/blob/d55c752fc930b819dc969f6cad6e546036df6363/crates/blockifier/src/blockifier/block.rs#L60)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I remember Noam bringing up specific bounds on these variables, have you spoken with Elin about these bounds and discussed how to incorporate them into the project?

The comment is OK, but it can go stale, especially if the gas_target isn't defined here, but only given as an arg (if the gas_target changes at someplace else, no one will know that this comment got stale).

So I'd like to know what the plan for these consts is before we add the comment, so I'll be able to know how reasonable it is to put it here.
</blockquote></details>

I added an assert for a specific target value and another assert for the minimum gas price.

Since these values are bounded, the division will be safe. With the target fixed, the delta is bounded by `max_block_size / 2`, ensuring that the division remains within safe limits. Therefore, converting back to `u64` will also be safe.


<!-- Sent from Reviewable.io -->

2024-08-29 14:56 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5IVMA0C7UYak223uxu:-O5Tcq2d8nT7MJd5BjOc:b-4eufud) ([raw file](https://github.com/starkware-libs/sequencer/blob/d55c752fc930b819dc969f6cad6e546036df6363/crates/blockifier/src/blockifier/block.rs#L60)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I added an assert for a specific target value and another assert for the minimum gas price.

Since these values are bounded, the division will be safe. With the target fixed, the delta is bounded by `max_block_size / 2`, ensuring that the division remains within safe limits. Therefore, converting back to `u64` will also be safe.
</blockquote></details>

safe = valid


<!-- Sent from Reviewable.io -->

2024-09-01 07:30 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 48 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5gTndR5y-YUKOoCUSf:-O5gTndSErH558IKx8O5:b3hpd6t) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd71fc818d3d4a8038f3fb867c332a0dd96a85b4/crates/blockifier/src/blockifier/block.rs#L48)):*
> ```XML
>     pub fn calculate_next_base_gas_price(price: u64, gas_used: u64, gas_target: u64) -> u64 {
>         assert_eq!(gas_target, MAX_BLOCK_SIZE / 2, "Gas target must be half MAX_BLOCK_SIZE");
>         assert!(price >= MIN_GAS_PRICE, "Gas price should be greater than the MIN_GAS_PRICE");
> ```

I mentioned this before, assert messages should _document assumptions/invariants_.
In other words, never translate readable code into words, readable code is better than words.

Both of these bounds had a _reason_ why there chosen, so here is the spot to (succinctly) explain why they were chosen.



_Code quote:_
```XML
        assert_eq!(gas_target, MAX_BLOCK_SIZE / 2, "Gas target must be half MAX_BLOCK_SIZE");
        assert!(price >= MIN_GAS_PRICE, "Gas price should be greater than the MIN_GAS_PRICE");
```


<!-- Sent from Reviewable.io -->

2024-09-01 08:57 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 48 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5gTndR5y-YUKOoCUSf:-O5gmavl83xUjFkulmrM:b-dl7897) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd71fc818d3d4a8038f3fb867c332a0dd96a85b4/crates/blockifier/src/blockifier/block.rs#L48)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I mentioned this before, assert messages should _document assumptions/invariants_.
In other words, never translate readable code into words, readable code is better than words.

Both of these bounds had a _reason_ why there chosen, so here is the spot to (succinctly) explain why they were chosen.
</blockquote></details>

I added a comment above it, and tried to add a succinct assertion message.
Let me know what do you think now.


<!-- Sent from Reviewable.io -->

2024-09-01 09:09 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5glqLY30L5ry9YvNU_:-O5glqLY30L5ry9YvNUa:bti4mv7) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd71fc818d3d4a8038f3fb867c332a0dd96a85b4/crates/blockifier/src/blockifier/block.rs#L24)):*
> ```XML
> // between consecutive blocks.
> const GAS_PRICE_MAX_CHANGE_DENOMINATOR: u128 = 48;
> const MIN_GAS_PRICE: u64 = 100000; // In fri.
> ```

Why is there a minimum gas price?


<!-- Sent from Reviewable.io -->

2024-09-01 10:37 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5glqLY30L5ry9YvNU_:-O5h8q8NDUOfIDBkzHgT:bwzgn85) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd71fc818d3d4a8038f3fb867c332a0dd96a85b4/crates/blockifier/src/blockifier/block.rs#L24)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why is there a minimum gas price?
</blockquote></details>

We want to avoid too low gas prices; it's not profitable.


<!-- Sent from Reviewable.io -->

2024-09-01 11:06 UTC, ayeletstarkware approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2024-09-02 14:15 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/blockifier/block.rs` line 57 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5n4XWx3HB6VVKhM-dV:-O5n4XWx3HB6VVKhM-dW:buirgot) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b80fbbb011d1201796bd9b2974a12383d2908ef/crates/blockifier/src/blockifier/block.rs#L57)):*
> ```XML
>         // To prevent precision loss during multiplication and division, we set a minimum gas price.
>         // Additionally, a minimum gas price is established to prevent prolonged periods before the
>         // price reaches a higher value.
> ```

This was added after Gilad's input in today's meeting.
@giladchase, Could you please confirm if this aligns with what you intended?



_Code quote:_
```XML
        // Additionally, a minimum gas price is established to prevent prolonged periods before the
        // price reaches a higher value.
```


<!-- Sent from Reviewable.io -->

2024-09-03 05:14 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203#-:-O5qIeE9Dj1STmndrwUY:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)



<!-- Sent from Reviewable.io -->

2024-09-03 07:15 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O4uZw5x8yZKP14n2yGX:-O5qjD_i4NsF6IL_SVOg:bb6un1j) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Once you approve this PR, I'll move the method to the fee_market.rs file under the more batch crate.
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2024-09-03 11:47 UTC, elintul reviewed
> Reviewed 2 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/batcher/src/fee_market.rs` line 44 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5rNYLY8iWPO0Gyu2b5:-O5rNYLY8iWPO0Gyu2b6:btrcc7p) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bab5d4691fcca427609db3f105bfb84365dd922/crates/batcher/src/fee_market.rs#L44)):*
> ```XML
>     let price_u128 = u128::from(price);
>     let gas_delta_u128 = u128::from(gas_delta);
>     let gas_target_u128 = u128::from(gas_target);
> ```

Can we use `map`? Can we shadow the previous variables?



_Code quote:_
```XML
    let price_u128 = u128::from(price);
    let gas_delta_u128 = u128::from(gas_delta);
    let gas_target_u128 = u128::from(gas_target);
```


<!-- Sent from Reviewable.io -->

2024-09-08 07:23 UTC, giladchase approved these changes
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/batcher/src/fee_market.rs` line 44 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/203#-O5rNYLY8iWPO0Gyu2b5:-O6FUi4x56Sw_zJlVwq2:bb15hvr) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bab5d4691fcca427609db3f105bfb84365dd922/crates/batcher/src/fee_market.rs#L44)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I don't think `map` is appropriate to use here.

Regarding shadowing the previous parameters: It can be applied to some, such as `gas_delta` and `price_change`. 
However, it should not be used for `price` and `gas_target` since their original `u64` values are needed later in the code.

Do you want me to shadow some of the variables?
</blockquote></details>

For comparison: 
```rust
    let [price_u128, gas_delta_u128, gas_target_u128] =
        [price, gas_delta, gas_target].map(u128::from);
```
I don't feel strongly in either direction on this one


<!-- Sent from Reviewable.io -->

2024-09-08 07:35 UTC, MohammadNassar1 reviewed
> Dismissed @elintul from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/203)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-09-08 07:35 UTC, merged