refactor(consensus): minor refactor of the manager
starkware-libs/sequencer pull request #208
Opened 2024-07-30 13:57 UTC by matan-starkware

1. Separate fn for handling cached messages per height
2. Return errors instead of panic when receiving messages

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/208)

2024-07-30 13:57 UTC, matan-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/208?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#208** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/208?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#200** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/200?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/112?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#166** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/166?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-31 11:02 UTC, asmaastarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/208#-:-O37SEenCFNmWlOLbdxf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-08-04 06:07 UTC, ShahakShama requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/208)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3Qy77U1b1YtJ5KrFrw:-O3Qy77V1zGylqTbxibh:b-26qpka) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/manager.rs#L81)):*
> ```XML
> 
>             // TODO(matan): We need to figure out an actual cacheing strategy under 2 constraints:
>             // 1. Malicious - must be capped so a malicious peer can't DoS us.
> ```

DoS -> DDoS
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3QzKBy0tpFE35CcUIc:-O3QzKBy0tpFE35CcUId:b-7pso23) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/manager.rs#L115)):*
> ```XML
>     fn get_current_height_messages(&mut self, height: BlockNumber) -> Vec<ConsensusMessage> {
>         let mut current_height_messages = Vec::new();
>         for msg in std::mem::take(&mut self.cached_messages) {
> ```

Try to remove just the problematic messages, instead of recreating the entire vector.
Plus, consider using a different data structure (maybe HashSet, or HashMap between height and a vector of ConsensusMessages and then finding all of them is much easier)
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3Qytyi65iUNX-fwbmp:-O3Qytyi65iUNX-fwbmq:b-y87018) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/manager.rs#L117)):*
> ```XML
>         for msg in std::mem::take(&mut self.cached_messages) {
>             match height.0.cmp(&msg.height()) {
>                 std::cmp::Ordering::Less => self.cached_messages.push(msg),
> ```

IDK why, but logically it makes more sense to put msg.height() in the left of the comparison. I guess it's because it changs this arm into Greater, which means you're saying "This message is higher than the current height", which makes more sense since the current height is constant during this entire function and what's changing is msg
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3QzqsHC6yCH0pF29WS:-O3QzqsI7KfjWXzuNJHb:bhuy2qp) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/types.rs#L167)):*
> ```XML
>     Canceled(#[from] oneshot::Canceled),
>     #[error(transparent)]
>     ProtobufConversionError(#[from] ProtobufConversionError),
> ```

This should be handled by reporting the relevant peer and then continuing on (maybe voting nil on the proposal if the sending peer is the proposer). For now put a TODO to handle this error internally


<!-- Sent from Reviewable.io -->

2024-08-04 08:35 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/208)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3Qy77U1b1YtJ5KrFrw:-O3RUkY69u5oST6i-d9b:b15t72h) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/manager.rs#L81)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

DoS -> DDoS
</blockquote></details>

Why? A single malicious node could potentially send me so many messages that I OOM. There is no need for this to be a distributed attack.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3QzKBy0tpFE35CcUIc:-O3RVrCM9IZvCtVNBEuf:b-vkibki) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/manager.rs#L115)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try to remove just the problematic messages, instead of recreating the entire vector.
Plus, consider using a different data structure (maybe HashSet, or HashMap between height and a vector of ConsensusMessages and then finding all of them is much easier)
</blockquote></details>

I intentionally went for a simple solution here (with Dan't support). I am not trying to optimize this since we know that this is not the final solution. This is just a solution for the sake of our early simulations. I'd rather just wait till we implement the real solution which is still under debate.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3Qytyi65iUNX-fwbmp:-O3RWJzl3fT4COm6SOB3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/manager.rs#L117)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IDK why, but logically it makes more sense to put msg.height() in the left of the comparison. I guess it's because it changs this arm into Greater, which means you're saying "This message is higher than the current height", which makes more sense since the current height is constant during this entire function and what's changing is msg
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3QzqsHC6yCH0pF29WS:-O3RWXwe4NyorvXc4jtt:b-34usew) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/types.rs#L167)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should be handled by reporting the relevant peer and then continuing on (maybe voting nil on the proposal if the sending peer is the proposer). For now put a TODO to handle this error internally
</blockquote></details>

Reviewable isn't highlighting, but I presume you are talking about `InvalidProposal`? If so you are basically describing the current milestone that Asmaa just wrote (code is already under review with me). I'll just leave this alone then, ok?


<!-- Sent from Reviewable.io -->

2024-08-04 09:59 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/208#-:-O3Rp9fKCfMSAbJTG7D-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3QzKBy0tpFE35CcUIc:-O3RofxDDCP-SIwz6Z3P:bjetreb) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/manager.rs#L115)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I intentionally went for a simple solution here (with Dan't support). I am not trying to optimize this since we know that this is not the final solution. This is just a solution for the sake of our early simulations. I'd rather just wait till we implement the real solution which is still under debate.
</blockquote></details>

But my suggestion is as simple as your suggestion.
Unblocking for now, but I think it's worth doing this change or at least putting a TODO
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3QzqsHC6yCH0pF29WS:-O3RotZO2-arllgyffie:b-pagjuc) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/types.rs#L167)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Reviewable isn't highlighting, but I presume you are talking about `InvalidProposal`? If so you are basically describing the current milestone that Asmaa just wrote (code is already under review with me). I'll just leave this alone then, ok?
</blockquote></details>

No, I'm talking about ProtobufConversionError, but I guess the same applies for InvalidProposal
You can leave this alone if you want


<!-- Sent from Reviewable.io -->

2024-08-04 11:23 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/208)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3QzKBy0tpFE35CcUIc:-O3S45Na88cpNbp-ToWZ:b-il7mkv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/manager.rs#L115)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

But my suggestion is as simple as your suggestion.
Unblocking for now, but I think it's worth doing this change or at least putting a TODO
</blockquote></details>

Took your map suggestion
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3QzqsHC6yCH0pF29WS:-O3S4Cm-39x9J_JcLzNi:b8tokyv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b58b015211449fa5a7a4134205abf7a66fa1ecaf/crates/sequencing/papyrus_consensus/src/types.rs#L167)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No, I'm talking about ProtobufConversionError, but I guess the same applies for InvalidProposal
You can leave this alone if you want
</blockquote></details>

I can't do anything with a protobuf conversion error (besides ReportSender to network). IDK if this is a proposal or a prevote, idk what height this is for, idk who sent it. Consensus proper must ignore.

I'll update the manager though to use report sender and add a TODO since at some point we will want the SHC to also start reporting errors.


<!-- Sent from Reviewable.io -->

2024-08-05 10:30 UTC, asmaastarkware reviewed
> Reviewed 1 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/208)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 82 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3X4Mub9Ki__kCUdO4R:-O3X4Mub9Ki__kCUdO4S:bsuutbj) ([raw file](https://github.com/starkware-libs/sequencer/blob/5736f9224463e54263ba02d78860d1f5de15025f/crates/sequencing/papyrus_consensus/src/manager.rs#L82)):*
> ```XML
>                     self.cached_messages
>                         .entry(message.height())
>                         .or_insert(Vec::new())
> ```

.or_default()



_Code quote:_
```XML
.or_insert(Vec::new())
```


<!-- Sent from Reviewable.io -->

2024-08-05 10:47 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/208)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 82 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/208#-O3X4Mub9Ki__kCUdO4R:-O3X8j9ZAV7YJK3N_Bf6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5736f9224463e54263ba02d78860d1f5de15025f/crates/sequencing/papyrus_consensus/src/manager.rs#L82)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

.or_default()
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-05 10:52 UTC, asmaastarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/208#-:-O3X9v1XDqNHu58gbixz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-08-05 11:55 UTC, matan-starkware commented
### Merge activity

* **Aug 5, 7:55 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/208).

2024-08-05 11:55 UTC, merged