test(mempool_p2p): test gateway client error on adding tx from p2p
starkware-libs/sequencer pull request #2138
Opened 2024-11-18 12:35 UTC by AlonLStarkWare

- test(mempool_p2p): change p2p runner test to use automock for gateway client
- test(mempool_p2p): test gateway client error on adding tx from p2p

2024-11-18 12:52 UTC, ShahakShama approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2138)* status: all files reviewed, 16 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzIJquEjywXPHeeGAk:-OBzIJquEjywXPHeeGAl:b3hn216) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f273dc018260bca8ecbb2c95065cb854dab3b35/crates/starknet_mempool_p2p/src/runner/test.rs#L81)):*
> ```XML
>         mock_register_broadcast_topic().expect("Failed to create mock network");
>     let BroadcastTopicChannels { broadcasted_messages_receiver, broadcast_topic_client } =
>         subscriber_channels; // used to created our node's p2p runner below, which will listen for incoming txs over broadcasted_messages_receiver.
> ```

Same as before, try to reduce the amount of comments
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzI5HV-MLw-huG_iNk:-OBzI5HV-MLw-huG_iNl:br80i1k) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f273dc018260bca8ecbb2c95065cb854dab3b35/crates/starknet_mempool_p2p/src/runner/test.rs#L92)):*
> ```XML
> 
>     // send an empty message on this channel to indicate that the tx reached the gateway client.
>     let (add_tx_indicator_sender, add_tx_indicator_receiver) = futures::channel::oneshot::channel();
> ```

You don't need this. You can wait for the peer report instead
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzJm5F-qqLyEyxBq7m:-OBzJm5F-qqLyEyxBq7n:b-vgsdub) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f273dc018260bca8ecbb2c95065cb854dab3b35/crates/starknet_mempool_p2p/src/runner/test.rs#L124)):*
> ```XML
>     // if the runner fails, there was a network issue => panic.
>     // if the runner returns successfully, we panic because the runner should never terminate.
>     res = tokio::time::timeout(Duration::from_secs(5), mempool_p2p_runner.start()) => {res.expect("Test timed out").expect("Runner failed - network stopped unexpectedly"); panic!("Runner terminated")},
> ```

Same as before. newlines and MempoolP2pRunner
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzJxeuDkS9tDx5HtGs:-OBzJxeuDkS9tDx5HtGt:b-fwcidu) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f273dc018260bca8ecbb2c95065cb854dab3b35/crates/starknet_mempool_p2p/src/runner/test.rs#L130)):*
> ```XML
>     res.unwrap();
>     // After gateway client fails to add the tx, the p2p runner should have reported the peer.
>     let peer_reported = mock_reported_messages_receiver.next().await.expect("Failed to receive message");
> ```

As I said before, put this future in the select arm instead
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzK1ha0Uzx53bC6xbe:-OBzK1ha0Uzx53bC6xbf:bi2e0yg) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f273dc018260bca8ecbb2c95065cb854dab3b35/crates/starknet_mempool_p2p/src/runner/test.rs#L130)):*
> ```XML
>     res.unwrap();
>     // After gateway client fails to add the tx, the p2p runner should have reported the peer.
>     let peer_reported = mock_reported_messages_receiver.next().await.expect("Failed to receive message");
> ```

Failed to receive report
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzK4vN5T40QaZpbL6d:-OBzK4vN5T40QaZpbL6e:b2782ar) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f273dc018260bca8ecbb2c95065cb854dab3b35/crates/starknet_mempool_p2p/src/runner/test.rs#L131)):*
> ```XML
>     // After gateway client fails to add the tx, the p2p runner should have reported the peer.
>     let peer_reported = mock_reported_messages_receiver.next().await.expect("Failed to receive message");
>     assert_eq!(peer_reported, message_metadata.originator_id.private_get_peer_id())
> ```

add a TODO to add this functionality to network manager test utils
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHUzcD-c_dXOMs9Mv:-OBzHUzcD-c_dXOMs9Mw:b-shqrov) ([raw file](https://github.com/starkware-libs/sequencer/blob/6513b85a69c245a40ffa0433bb19ed303925c077/crates/starknet_mempool_p2p/src/runner/test.rs#L29)):*
> ```XML
>         mock_register_broadcast_topic().expect("Failed to create mock network");
>     let BroadcastTopicChannels { broadcasted_messages_receiver, broadcast_topic_client } =
>         subscriber_channels; // used to created our node's p2p runner below, which will listen for incoming txs over broadcasted_messages_receiver.
> ```

This comment seems unnecessary
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHYUD2CgMl5f65SSz:-OBzHYUE3zPHUvNhWe7O:b-shqrov) ([raw file](https://github.com/starkware-libs/sequencer/blob/6513b85a69c245a40ffa0433bb19ed303925c077/crates/starknet_mempool_p2p/src/runner/test.rs#L33)):*
> ```XML
>         broadcasted_messages_sender: mut mock_broadcasted_messages_sender,
>         ..
>     } = mock_network; // other node sending tx to our p2p runner
> ```

This comment seems unnecessary
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzH_yQ76C3FK8egf6R:-OBzH_yQ76C3FK8egf6S:bqs3eyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/6513b85a69c245a40ffa0433bb19ed303925c077/crates/starknet_mempool_p2p/src/runner/test.rs#L38)):*
> ```XML
>     let placeholder_network_manager = NetworkManager::new(NetworkConfig::default(), None);
> 
>     // send an empty message on this channel to indicate that the tx reached the gateway client.
> ```

This comment is incorrect. Change it to "Creating channels for sending ..."
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzIi-G5IOjcFjpFJGc:-OBzIi-G5IOjcFjpFJGd:b-gm1cnb) ([raw file](https://github.com/starkware-libs/sequencer/blob/6513b85a69c245a40ffa0433bb19ed303925c077/crates/starknet_mempool_p2p/src/runner/test.rs#L42)):*
> ```XML
> 
>     let mut mock_gateway_client = MockGatewayClient::new();
>     mock_gateway_client.expect_add_tx().return_once(move |_| {
> ```

You should assert that the transaction you've received is the one you've gotten from p2p. You can use automock's with function for that: https://docs.rs/mockall/latest/mockall/index.html#getting-started
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHfm1CQx-FRRjq2xl:-OBzHfm1CQx-FRRjq2xm:b-shqrov) ([raw file](https://github.com/starkware-libs/sequencer/blob/6513b85a69c245a40ffa0433bb19ed303925c077/crates/starknet_mempool_p2p/src/runner/test.rs#L48)):*
> ```XML
>     let mut mempool_p2p_runner = MempoolP2pRunner::new(
>         Some(placeholder_network_manager),
>         broadcasted_messages_receiver, // listen to incoming tx
> ```

This comment seems unnecessary
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHgKF3lKd9bC0jWWm:-OBzHgKF3lKd9bC0jWWn:b-shqrov) ([raw file](https://github.com/starkware-libs/sequencer/blob/6513b85a69c245a40ffa0433bb19ed303925c077/crates/starknet_mempool_p2p/src/runner/test.rs#L49)):*
> ```XML
>         Some(placeholder_network_manager),
>         broadcasted_messages_receiver, // listen to incoming tx
>         broadcast_topic_client,        // broadcast tx or report peer
> ```

This comment seems  [...]

2024-12-16 13:10 UTC, AlonLStarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2138)* status: 0 of 3 files reviewed, 16 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHUzcD-c_dXOMs9Mv:-OCDLAq9B6kVacau5P_Q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/276cdc87e9dcdae14db8914d1de63202702ddac2/crates/starknet_mempool_p2p/src/runner/test.rs#L29)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This comment seems unnecessary
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHYUD2CgMl5f65SSz:-OCDLAdk66TOzACtIPh6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/276cdc87e9dcdae14db8914d1de63202702ddac2/crates/starknet_mempool_p2p/src/runner/test.rs#L33)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This comment seems unnecessary
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzH_yQ76C3FK8egf6R:-OCD7nPW709bbZUJLuP9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/276cdc87e9dcdae14db8914d1de63202702ddac2/crates/starknet_mempool_p2p/src/runner/test.rs#L38)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This comment is incorrect. Change it to "Creating channels for sending ..."
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzIi-G5IOjcFjpFJGc:-OCD9psl6CXNiUCvGuU8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/276cdc87e9dcdae14db8914d1de63202702ddac2/crates/starknet_mempool_p2p/src/runner/test.rs#L42)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should assert that the transaction you've received is the one you've gotten from p2p. You can use automock's with function for that: https://docs.rs/mockall/latest/mockall/index.html#getting-started
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHfm1CQx-FRRjq2xl:-OCDLNES5FBXLHTc-Z3n:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/276cdc87e9dcdae14db8914d1de63202702ddac2/crates/starknet_mempool_p2p/src/runner/test.rs#L48)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This comment seems unnecessary
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHgKF3lKd9bC0jWWm:-OCDLNS97d85Bs86PAFH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/276cdc87e9dcdae14db8914d1de63202702ddac2/crates/starknet_mempool_p2p/src/runner/test.rs#L49)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This comment seems unnecessary
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHh4BBJxE5s-1aBly:-OCDM41lEl9j9FMNdlbv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/276cdc87e9dcdae14db8914d1de63202702ddac2/crates/starknet_mempool_p2p/src/runner/test.rs#L64)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This comment seems unnecessary. You have the expect for that
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHkmu8sbygds3oa72:-OCD9y-Y-EImMTKVL77i:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/276cdc87e9dcdae14db8914d1de63202702ddac2/crates/starknet_mempool_p2p/src/runner/test.rs#L67)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Runner -> MempoolP2pRunner
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHoNvBWZV0R4TF3z-:-OCDADo51t3TBD_ttXvY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/276cdc87e9dcdae14db8914d1de63202702ddac2/crates/starknet_mempool_p2p/src/runner/test.rs#L67)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

add newlines after the { and after each ;
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzHw2V4MTLXlAPKqVo:-OCDA4lv0pLFWs6JCk_f:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/276cdc87e9dcdae14db8914d1de63202702ddac2/crates/starknet_mempool_p2p/src/runner/test.rs#L68)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

... and the test succeeded
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzIJquEjywXPHeeGAk:-OCDMJqX4K_D8ym42xqG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b525c2d69269f09db21bfaa5d24c957f89729958/crates/starknet_mempool_p2p/src/runner/test.rs#L81)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as before, try to reduce the amount of comments
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzI5HV-MLw-huG_iNk:-OCDMOAM-POIgGBSBGyo:b40fzdc) ([raw file](https://github.com/starkware-libs/sequencer/blob/b525c2d69269f09db21bfaa5d24c957f89729958/crates/starknet_mempool_p2p/src/runner/test.rs#L92)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You don't need this. You can wait for the peer report instead
</blockquote></details>

Wouldn't we want to know if the gateway received the transaction if it wasn't reported? I think this helps narrow down the potential error.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzJm5F-qqLyEyxBq7m:-OCDAQI-82koMS4EIE9A:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b525c2d69269f09db21bfaa5d24c957f89729958/crates/starknet_mempool_p2p/src/runner/test.rs#L124)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as before. newlines and MempoolP2pRunner
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzJxeuDkS9tDx5HtGs:-OCDKHL-90IYRBLW9HJY:b-swxehu) ([raw file](https://github.com/starkware-libs/sequencer/blob/b525c2d69269f09db21bfaa5d24c957f89729958/crates/starknet_mempool_p2p/src/runner/test.rs#L130)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

As I said before, put this future in the select arm instead
</blockquote></details>

This future can only be resolved after the transaction is received by the gateway, so it should be in this arm, IMO.
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzK1ha0Uzx53bC6xbe:-OCDGY1p6DV_lzNif1xm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b525c2d69269f09db21bfaa5d24c957f89729958/crates/starknet_mempool_p2p/src/runner/test.rs#L130)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Failed to receive report
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/t [...]

2024-12-19 08:17 UTC, ShahakShama approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2138)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OBzI5HV-MLw-huG_iNk:-OESzTShDDtxM2-Yofz8:b32wtd) ([raw file](https://github.com/starkware-libs/sequencer/blob/b525c2d69269f09db21bfaa5d24c957f89729958/crates/starknet_mempool_p2p/src/runner/test.rs#L92)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Wouldn't we want to know if the gateway received the transaction if it wasn't reported? I think this helps narrow down the potential error.
</blockquote></details>

ok
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 142 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-OESz1ym384ZnAwBs8KT:-OESz1ym384ZnAwBs8KU:b-uxjrp8) ([raw file](https://github.com/starkware-libs/sequencer/blob/366fb7088cffea6cb2fbf8bf1b45ac9d3d9df5c7/crates/starknet_mempool_p2p/src/runner/test.rs#L142)):*
> ```XML
>             // After gateway client fails to add the tx, the p2p runner should have reported the peer.
>             let peer_reported = mock_reported_messages_receiver.next().await.expect("Failed to receive report");
>             // TODO: add this functionalionality to network manager test utils
> ```

spell error in functionalionality


<!-- Sent from Reviewable.io -->

2024-12-25 07:42 UTC, ShahakShama reviewed
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2138)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-12-25 07:42 UTC, ShahakShama commented on crates/starknet_mempool_p2p/src/runner/test.rs
> +// The p2p runner receives a tx from network, and the gateway decalines it, triggering report_peer.
:+1: 
<!-- Reviewable comment -OEwkhWQ9EtwaSpaQLs0:b-8fx2u7 -->
<!-- Sent from Reviewable.io -->

2024-12-25 07:42 UTC, ShahakShama approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2138)* status: all files reviewed, 1 unresolved discussion (waiting on @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-12-25 07:42 UTC, ShahakShama approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2138)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)



<!-- Sent from Reviewable.io -->

2024-12-25 07:42 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2138)* status: all files reviewed, 1 unresolved discussion (waiting on @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-12-26 12:41 UTC, AlonLStarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2138)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-12-26 12:41 UTC, AlonLStarkWare commented on crates/starknet_mempool_p2p/src/runner/test.rs
> +// The p2p runner receives a tx from network, and the gateway decalines it, triggering report_peer.
Done.
<!-- Reviewable comment -OF1z-fB1THc1C8xAJ_Z:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-12-30 14:25 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2138#-:-OFMxFSM6h1TjuJPGyQ4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)



<!-- Sent from Reviewable.io -->

2024-12-31 11:37 UTC, AlonLStarkWare reviewed
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2138)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)



<!-- Sent from Reviewable.io -->

2025-01-05 11:07 UTC, merged