feat(blockifier): update gas and vm resources computations
starkware-libs/sequencer pull request #2153
Opened 2024-11-18 18:23 UTC by TzahiTaub

2024-11-18 18:24 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2153)
<!-- Reviewable:end -->

2024-11-18 18:24 UTC, TzahiTaub commented
* **#2153** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2153?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2153?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-19 10:21 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 10 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 0 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2v3vxAQgscIdnExJX:-OC2v3vxAQgscIdnExJY:b-qo0tvs) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L0)):*
these changes lgtm but can you add a reviewer from noa's team?
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 517 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2tb_T12qQaC9NOnkP:-OC2tb_U3CguCu3_9Vex:b-ou36c8) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_test.rs#L517)):*
> ```XML
> #[test]
> fn test_old_cairo1_entry_point_segment_arena() {
>     let test_contract = FeatureContract::CairoStepsTestContract;
> ```

no segment arena in cairo-native?



_Code quote:_
```XML
fn test_old_cairo1_entry_point_segment_arena() {
    let test_contract = FeatureContract::CairoStepsTestContract;
```
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2sv0b9F7MAuBKY4mZ:-OC2sv0b9F7MAuBKY4m_:b7nmfi3) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_execution_test.rs#L107)):*
> ```XML
>     let chain_info = &ChainInfo::create_for_testing();
>     let contracts = CompilerBasedVersion::iter().map(|version| (version.get_test_contract(), 1u16));
>     let mut state = test_state(chain_info, BALANCE, &contracts.collect::<Vec<_>>());
> ```

I think this is better - `contracts` shouldn't be an iterator of tuples, + I don't think the `collect` should need a type hint, `test_state` argument type should be hint enough.
non-blocking



_Suggestion:_
```XML
    let contracts = CompilerBasedVersion::iter().map(|version| version.get_test_contract());
    let mut state = test_state(chain_info, BALANCE, &contracts.map(|contract| (contract, 1)).collect());
```
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2tEo1DXq7QBmhgBr4:-OC2tEo1DXq7QBmhgBr5:b-hfem92) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_execution_test.rs#L112)):*
> ```XML
>         CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1),
>         CompilerBasedVersion::random_version_for_vm(),
>         CompilerBasedVersion::random_version_for_vm(),
> ```

there are 4=O(1) combinations possible here; please explicitly parametrize instead of making a random test



_Code quote:_
```XML
        CompilerBasedVersion::random_version_for_vm(),
        CompilerBasedVersion::random_version_for_vm(),
```
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2tPKE4Xnqnqkld4AQ:-OC2tPKE4Xnqnqkld4AR:bnq634q) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_execution_test.rs#L116)):*
> ```XML
> 
>     let first_calldata = build_recurse_calldata(&call_versions);
>     let second_calldata = build_recurse_calldata(&[CompilerBasedVersion::random_version_for_vm()]);
> ```

8 cases is still O(1) :)



_Code quote:_
```XML
ompilerBasedVersion::random_version_for_vm()
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2tpBXCD1WFgHgmvEC:-OC2tpBXCD1WFgHgmvED:bstw7w8) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/transaction/account_transactions_test.rs#L183)):*
> ```XML
>             24
>         );
>     }
> ```

what about the other case? can you verify it?



_Suggestion:_
```XML
    match tx_execution_info.validate_call_info.unwrap().tracked_resource {
        TrackedResource::CairoSteps => assert_eq!(
            tx_execution_info.receipt.resources.computation.vm_resources.builtin_instance_counter
                [&BuiltinName::range_check96],
            24
        ),
        TrackedResource::SierraGas => ???
    }
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 884 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2uAeT3ExRuYDjlttb:-OC2uAeT3ExRuYDjlttc:bc6h8lk) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/transaction/account_transactions_test.rs#L884)):*
> ```XML
>     if result.validate_call_info.unwrap().tracked_resource == TrackedResource::SierraGas {
>         return;
>     }
> ```

blocking until a PR is open that does this TODO (otherwise we are losing test coverage here)



_Code quote:_
```XML
    // TODO(Tzahi): adjust the steps in the test to gas for the SierraGas run (after a validate
    // run gas limit is introduced to the code).
    if result.validate_call_info.unwrap().tracked_resource == TrackedResource::SierraGas {
        return;
    }
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 444 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2ri576ddlhZGrnyli:-OC2ri576ddlhZGrnylj:b-9lhp6w) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_execution.rs#L444)):*
> ```XML
>     let full_call_resources = &*syscall_handler.resources - &previous_resources;
>     let charged_resources = ChargedResources {
>         vm_resources: full_call_resources.filter_unused_builtins(),
> ```

if TrackedResource is SierraGas, why do you add these VM resources in the charged resources?
if the `if` above is skipped, will `full_call_resources` be empty?
if so, I prefer a `to_vm_resources_for_fee` function with a similar API to `to_gas_for_fee`, so it's clearer.
if not, what VM resources are you counting from this call?



_Code quote:_
```XML
vm_resources: full_call_resources.filter_unused_builtins(),
```
___
*[`crates/blockifier/src/test_utils.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2qsQ7Cslwgrv5pCxt:-OC2qsQ7Cslwgrv5pCxu:b-bu6iba) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/test_utils.rs#L138)):*
> ```XML
>         ];
>         VERSIONS.iter()
>     }
> ```

this is not forward-compatible, the `FeatureContracts` enum uses `EnumIter` for this.
PTAL [here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/src/test_utils/contracts.rs#L411-L423)



_Code quote:_
```XML
    /// Returns an iterator over all of the enum variants.
    pub fn iter() -> Iter<'static, Self> {
        static VERSIONS: [CompilerBasedVersion; 3] = [
            CompilerBasedVersion::CairoVersion(CairoVersion::Cairo0),
            CompilerBasedVersion::OldCairo1,
            CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1),
        ];
        VERSIONS.iter()
    }
```
___
*[`crates/blockifier/src/test_utils.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2rLTV6qWZhoJxirno:-OC2rLTW6nrSbjbE3zQ-:bvz1kid) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/test_utils.rs#L142)):*
> ```XML
>     /// Return a uniform random choice of Cairo0 versi [...]

2024-11-19 16:45 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 11 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC4J06r55iG_0tMGgvX:-OC4J06r55iG_0tMGgvY:bainnx4) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_execution.rs#L371)):*
> ```XML
> 
> /// Calculates the total gas for fee in the current call + subtree.
> fn to_gas_for_fee(
> ```

You should share this code with native


<!-- Sent from Reviewable.io -->

2024-11-19 17:07 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 444 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2ri576ddlhZGrnyli:-OC4Nvwv5i0pzoXje74K:b4dq7rn) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_execution.rs#L444)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if TrackedResource is SierraGas, why do you add these VM resources in the charged resources?
if the `if` above is skipped, will `full_call_resources` be empty?
if so, I prefer a `to_vm_resources_for_fee` function with a similar API to `to_gas_for_fee`, so it's clearer.
if not, what VM resources are you counting from this call?
</blockquote></details>

Your children can be cairoSteps


<!-- Sent from Reviewable.io -->

2024-11-21 13:01 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line  at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2v3vxAQgscIdnExJX:-OCDh_bz0b-wN4-1yCtb:bvhnnaz) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these changes lgtm but can you add a reviewer from noa's team?
</blockquote></details>

The VM resources for native are irrelevant, and I think we can drop them for the VM as well since we can derive the gas cost from the VM resources. 


<!-- Sent from Reviewable.io -->

2024-11-21 13:51 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 10 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 176 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCDzLTXBwY_FVVf2RRT:-OCDzLTXBwY_FVVf2RRU:bxdggcp) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L176)):*
> ```XML
>     };
> 
>     let storage_entry_point_gas = GasAmount(if_native(&test_contract)(26990, 16990));
> ```

@Yoni-Starkware is this gas difference related to the 10k bug you talked about?
+ same Q for the below `if_native` usage, but the other one does not have a 10k diff...



_Code quote:_
```XML
if_native(&test_contract)(26990, 16990)
```


<!-- Sent from Reviewable.io -->

2024-11-21 14:01 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: 1 of 9 files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware, @ilyalesokhin-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2qsQ7Cslwgrv5pCxt:-OC5ouCl08UNuvH-uy5z:b-i5fqjr) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/test_utils.rs#L138)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is not forward-compatible, the `FeatureContracts` enum uses `EnumIter` for this.
PTAL [here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/src/test_utils/contracts.rs#L411-L423)
</blockquote></details>

Copying that seems like an overkill for something that simple that is not expected to change. How about a count assert (I remind you this is a test_util)? If we'll add more variants it will fail, and if we'll make a static variant into a dynamic we'll have to change this code in any case.
___
*[`crates/blockifier/src/test_utils.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2rLTV6qWZhoJxirno:-OC5rjrXApk6urEq-CIv:btodypz) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/test_utils.rs#L142)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please inject the random object. I think papyrus / committer crates have examples of random tests
</blockquote></details>

Removed as I don't need anymore
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC4J06r55iG_0tMGgvX:-OC64cQuDpFgAve0Bd08:b-1grz2p) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_execution.rs#L371)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You should share this code with native
</blockquote></details>

Done. Had to change this function due to your change as well.
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2sv0b9F7MAuBKY4mZ:-OCDb2l7-Nf626INDLJp:bmzyqj0) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_execution_test.rs#L107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think this is better - `contracts` shouldn't be an iterator of tuples, + I don't think the `collect` should need a type hint, `test_state` argument type should be hint enough.
non-blocking
</blockquote></details>

Still needs the vec hint.
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2tEo1DXq7QBmhgBr4:-OCDb8SQ75kHmYBYTYOL:bs7wumx) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_execution_test.rs#L112)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there are 4=O(1) combinations possible here; please explicitly parametrize instead of making a random test
</blockquote></details>

Done. 
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2tPKE4Xnqnqkld4AQ:-OCDb8wg0uS3cYWg87l8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_execution_test.rs#L116)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

8 cases is still O(1) :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 517 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2tb_T12qQaC9NOnkP:-OCDbmYK2uCZ4_zyx3Bv:bm1kqtj) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/entry_point_test.rs#L517)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no segment arena in cairo-native?
</blockquote></details>

I don't know, but I changed the test not because of the builtin existence but because of the vm_resources verification in the end that is now 0. Don't know exactly what we want to test here, but for native it should be somehow counted in gas.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2tpBXCD1WFgHgmvEC:-OCDeqNY9GYT2b096XfT:b-s5dzi6) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/transaction/account_transactions_test.rs#L183)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about the other case? can you verify it?
</blockquote></details>

@ilyalesokhin-starkware said no, just that the run was successful.
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCE0aAc7YCtcsiE4nzB:-OCE0aAc7YCtcsiE4nzC:bjjuawa) ([raw file](https://github.com/starkware-libs/sequencer/blob/50a48fff525adddd55b7e7edbf0a2d42238aa1be/crates/blockifier/src/execution/entry_point_execution_test.rs#L119)):*
> ```XML
>         CompilerBasedVersion::OldCairo1
>     )]
>     second_branch_contract_version: CompilerBasedVersion,
> ```

Didn't find a way to make this `value` macro work dynamically



_Code quote:_
```XML
    #[values(
        CompilerBasedVersion::CairoVersion(CairoVersion::Cairo0),
        CompilerBasedVersion::OldCairo1
    )]
    third_contract_version: CompilerBasedVersion,
    #[values(
        CompilerBasedVersion::CairoVersion(CairoVersion::Cairo0),
        CompilerBasedVersion::OldCairo1
    )]
    fourth_contract_version: CompilerBasedVersion,
    #[values(
        CompilerBasedVersion::CairoVersion(CairoVersion::Cairo0),
        CompilerBasedVersion::OldCairo1
    )]
    second_branch_contract_version: CompilerBasedVersion,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 255 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2vK6x9yE7VUNgWaeu:-OCDf797DgHcMfKfNz_J:b32vhw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/transaction/transactions_test.rs#L255)):*
> ```XML
>             charged_resources = ChargedResources::from_execution_resources(resources);
>         }
>     };
> ```

:)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 546 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2vcfs8L2FXCou6sw5:-OCDfcRc1KT72Xniage6:bmdkc6d) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/transaction/transactions_test.rs#L546)):*
> ```XML
>                 expected_inner_call_charged_resources.vm_resources.clone()
>         }
>     }
> ```

:) :) 


<!-- Sent from Reviewable.io -->

2024-11-21 14:10 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: 1 of 9 files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware, @ilyalesokhin-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 176 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCDzLTXBwY_FVVf2RRT:-OCE1onR3Qwxi0iqzgm9:b-v1t8ca) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L176)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware is this gas difference related to the 10k bug you talked about?
+ same Q for the below `if_native` usage, but the other one does not have a 10k diff...
</blockquote></details>

It seems the changes disappeared after a rebase.


<!-- Sent from Reviewable.io -->

2024-11-21 14:51 UTC, dorimedini-starkware requested changes
> Reviewed 7 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 4 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 364 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCEBhVf9tWQPKVlcC1k:-OCEBhVf9tWQPKVlcC1l:b-hcazhn) ([raw file](https://github.com/starkware-libs/sequencer/blob/50a48fff525adddd55b7e7edbf0a2d42238aa1be/crates/blockifier/src/execution/entry_point_execution.rs#L364)):*
> ```XML
> 
> /// Calculates the gas for fee in the current call.
> pub fn to_gas_for_fee(
> ```

can this be a method of `CallInfo`?
all three parameters here seem to be part of this type



_Code quote:_
```XML
to_gas_for_fee(
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 379 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCE9kyT2G55-HMWhtg6:-OCE9kyT2G55-HMWhtg7:bswkjqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/50a48fff525adddd55b7e7edbf0a2d42238aa1be/crates/blockifier/src/execution/entry_point_execution.rs#L379)):*
> ```XML
>         TrackedResource::CairoSteps => 0,
>         TrackedResource::SierraGas => gas_consumed
>             .checked_sub(inner_calls.iter().map(|call| call.execution.gas_consumed).sum::<u64>())
> ```

ok, as I understand it, this function now does the following:
1. If the tracked resource is CairoSteps, returns 0
2. Otherwise: returns the gas consumed in this specific call, without the subtree

right?
so, this means that this value will not be the `gas_consumed` of the call, it will be the `gas_for_fee_charge` field?

please rewrite the documentation then... very confusing



_Suggestion:_
```XML
    // The Sierra gas consumed in this specific call is `gas_consumed`
    // (= total gas of self + subtree), minus the sum of all inner calls Sierra gas consumed.
    // To compute the total Sierra gas to charge (of self, WITHOUT the subtree), if the tracked resource is
    // Sierra gas, we subtract the subtrees consumed gas from the total.
    // If the tracked resource is Cairo steps, this specific call incurs no Sierra gas cost for fee.
    GasAmount(match tracked_resource {
        TrackedResource::CairoSteps => 0,
        TrackedResource::SierraGas => gas_consumed
            .checked_sub(inner_calls.iter().map(|call| call.execution.gas_consumed).sum::<u64>())
```


<!-- Sent from Reviewable.io -->

2024-11-24 13:06 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 364 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCEBhVf9tWQPKVlcC1k:-OCT8K2wA_91dO3DNCxK:b-41qrpr) ([raw file](https://github.com/starkware-libs/sequencer/blob/50a48fff525adddd55b7e7edbf0a2d42238aa1be/crates/blockifier/src/execution/entry_point_execution.rs#L364)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can this be a method of `CallInfo`?
all three parameters here seem to be part of this type
</blockquote></details>

CallInfo needs the gas_for_fee in its initialization. We can make a create function for CallInfo to have this calculation inside - do you prefer that?
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 379 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCE9kyT2G55-HMWhtg6:-OCT9hsE5-ohvOJBef01:b-c8b291) ([raw file](https://github.com/starkware-libs/sequencer/blob/50a48fff525adddd55b7e7edbf0a2d42238aa1be/crates/blockifier/src/execution/entry_point_execution.rs#L379)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, as I understand it, this function now does the following:
1. If the tracked resource is CairoSteps, returns 0
2. Otherwise: returns the gas consumed in this specific call, without the subtree

right?
so, this means that this value will not be the `gas_consumed` of the call, it will be the `gas_for_fee_charge` field?

please rewrite the documentation then... very confusing
</blockquote></details>

This was more relevant in the old computations. After the change Yoni made, I think the current function is pretty self-explanatory. Changed the name to match the vm_resource var where this function is called.


<!-- Sent from Reviewable.io -->

2024-11-24 13:21 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 364 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCEBhVf9tWQPKVlcC1k:-OCTK-rzDoXQ9EOz2C42:bj50m0d) ([raw file](https://github.com/starkware-libs/sequencer/blob/50a48fff525adddd55b7e7edbf0a2d42238aa1be/crates/blockifier/src/execution/entry_point_execution.rs#L364)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

CallInfo needs the gas_for_fee in its initialization. We can make a create function for CallInfo to have this calculation inside - do you prefer that?
</blockquote></details>

yes but in a separate PR... not need to continue refactoring this one.


<!-- Sent from Reviewable.io -->

2024-11-24 16:15 UTC, Yoni-Starkware submitted a review, later dismissed
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCTx9Xb41sOPc8BTgVs:-OCTx9Xb41sOPc8BTgVt:b2nhexc) ([raw file](https://github.com/starkware-libs/sequencer/blob/a47b6d2b5922c1428b551f4c9ce38b655b88e107/crates/blockifier/src/execution/native/entry_point_execution.rs#L90)):*
> ```XML
>     let charged_resources_without_inner_calls = ChargedResources {
>         vm_resources: ExecutionResources::default(),
>         gas_for_fee: to_gas_for_fee(
> ```

Fix



_Code quote:_
```XML
 to_gas_for_fee
```


<!-- Sent from Reviewable.io -->

2024-11-24 16:17 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 172 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCTxO-VBx2lhxAfdR62:-OCTxO-VBx2lhxAfdR63:bvk9itm) ([raw file](https://github.com/starkware-libs/sequencer/blob/2844be96648c3dd7e31769dd7494a0c9b1e09932/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L172)):*
> ```XML
>             builtin_instance_counter: HashMap::from([(BuiltinName::range_check, 7)]),
>         };
>     }
> ```

Cool, no VM resources for VM with new Cairo 1



_Code quote:_
```XML
    if cairo_version == CairoVersion::Cairo1 {
        first_storage_entry_point_resources.vm_resources = ExecutionResources {
            n_steps: 244,
            n_memory_holes: 0,
            builtin_instance_counter: HashMap::from([(BuiltinName::range_check, 7)]),
        };
    }
```


<!-- Sent from Reviewable.io -->

2024-12-15 14:13 UTC, TzahiTaub commented
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OCTx9Xb41sOPc8BTgVs:-OCUw_OoEsn5wL-89su5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a47b6d2b5922c1428b551f4c9ce38b655b88e107/crates/blockifier/src/execution/native/entry_point_execution.rs#L90)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Fix
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-15 15:30 UTC, dorimedini-starkware reviewed
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-15 15:48 UTC, dorimedini-starkware reviewed
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-16 12:03 UTC, TzahiTaub reviewed
> Dismissed @Yoni-Starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: 8 of 15 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 884 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OC2uAeT3ExRuYDjlttb:-OEEL7AMAYBLwSe34rid:b3kqsf6) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ac452cc1504e7d2f50610fe6214281844bb9dfe/crates/blockifier/src/transaction/account_transactions_test.rs#L884)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

blocking until a PR is open that does this TODO (otherwise we are losing test coverage here)
</blockquote></details>

The `execute_max_sierra_gas` (and validate) is not used ATM in the code, so I'm keeping the todo and working on it. Please unblock so I won't get another huge rebase :)


<!-- Sent from Reviewable.io -->

2024-12-16 13:32 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-:-OEEeoLVExWEk-Sm9H0M:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-16 15:41 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 556 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OEF73lPECv0akbDjUZZ:-OEF73lPECv0akbDjUZ_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcded19f920e46d11b8379b9311af56f4aaa71d2/crates/blockifier/src/transaction/transactions_test.rs#L556)):*
> ```XML
>     let expected_execute_call = CallEntryPoint {
>         entry_point_selector: selector_from_name(constants::EXECUTE_ENTRY_POINT_NAME),
>         initial_gas: if account_cairo_version == CairoVersion::Cairo0 {
> ```





_Suggestion:_
```XML
match
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 591 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OEF7JgY2cPCN3gnGJL_:-OEF7JgZD-HVYRAsls4f:b-y343dz) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcded19f920e46d11b8379b9311af56f4aaa71d2/crates/blockifier/src/transaction/transactions_test.rs#L591)):*
> ```XML
>         caller_address: sender_address,
>         call_type: CallType::Call,
>         initial_gas: versioned_constants.inifite_gas_for_vm_mode(),
> ```

oops
is this a typo here? or in the function name?



_Code quote:_
```XML
inifite
```


<!-- Sent from Reviewable.io -->

2024-12-16 15:42 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-16 15:45 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 591 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OEF7JgY2cPCN3gnGJL_:-OEF8B78CN_BTAVRhHOy:bk7zov3) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcded19f920e46d11b8379b9311af56f4aaa71d2/crates/blockifier/src/transaction/transactions_test.rs#L591)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

oops
is this a typo here? or in the function name?
</blockquote></details>

The function name, already told @aner-starkware  about it.


<!-- Sent from Reviewable.io -->

2024-12-16 15:49 UTC, TzahiTaub commented
*[`crates/blockifier/src/transaction/transactions_test.rs` line 591 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2153#-OEF7JgY2cPCN3gnGJL_:-OEF9KcP1CbLIYndeVTF:b-gt28ey) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcded19f920e46d11b8379b9311af56f4aaa71d2/crates/blockifier/src/transaction/transactions_test.rs#L591)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

The function name, already told @aner-starkware  about it.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/sequencer/2704#-


<!-- Sent from Reviewable.io -->

2024-12-16 15:50 UTC, TzahiTaub reviewed
> Reviewed 3 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2153)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-12-16 16:02 UTC, merged