chore: fix remote server creation macro
starkware-libs/sequencer pull request #2179
Opened 2024-11-19 12:37 UTC by nadin-Starkware

commit-id:fc4f30ad

2024-11-19 12:37 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2179)
<!-- Reviewable:end -->

2024-11-19 14:49 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2179)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2179#-OC3t34a2MJAQK2YFMoj:-OC3tU6t7OiviYRO0JXn:b3grhmm) ([raw file](https://github.com/starkware-libs/sequencer/blob/4286cd67da045f6926233a3af6bf0bc181e87904/crates/starknet_sequencer_node/src/servers.rs#L99)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

"Local client required to support inbound remote connections."
</blockquote></details>

"Local client should be set for inbound remote connections."


<!-- Sent from Reviewable.io -->

2024-11-19 14:50 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2179#-:-OC3tkUa24n65-AYLtlQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)



<!-- Sent from Reviewable.io -->

2024-11-20 11:26 UTC, nadin-Starkware reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2179)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)



<!-- Sent from Reviewable.io -->

2024-11-20 11:26 UTC, merged