feat: add TransactionHash to TransactionBatch
starkware-libs/sequencer pull request #2183
Opened 2024-11-19 15:04 UTC by guy-starkware

This is a temporary hack (as is evident from the many TODO items), that allows passing in the ProposalPart, specifically in the TransactionBatch, not only a vector of Transactions but also a vector of TransactionHashes. 

This is useful as it lets us convert a regular transaction into an ExecutableTransaction. 

In the future, we will either make the hash part of the transaction we broadcast (whatever we end up naming it) or we will have a tool that calculates this hash at the same time that we also do other calculation needed for executable transactions (e.g., compiling code).

2024-11-19 15:04 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2183)
<!-- Reviewable:end -->

2024-11-25 13:25 UTC, dan-starkware commented
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2183#-OCYUmSKEuVvMEQ4iSjV:-OCYUmSL-KiWXZGflH-F:bp8xs8k) ([raw file](https://github.com/starkware-libs/sequencer/blob/d47e4f3497db16702d8a2b7a68d5b626253fe24d/crates/papyrus_protobuf/src/converters/consensus.rs#L244)):*
> ```XML
>     fn from(value: TransactionBatch) -> Self {
>         let transactions = value.transactions.into_iter().map(Into::into).collect();
>         protobuf::TransactionBatch { transactions, tx_hashes: Vec::new() }
> ```

This seems wrong.
Is there a corresponding test?



_Code quote:_
```XML
tx_hashes: Vec::new()
```


<!-- Sent from Reviewable.io -->

2024-11-25 18:27 UTC, matan-starkware requested changes
> Reviewed 2 of 2 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2183)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @guy-starkware)

___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2183#-OCS43KR3ZEaiBavuvzZ:-OCZX02aCtt4ue0ZvYmJ:bntvl6t) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9688c3bb77751ca55e7c6d5fb5e9ae730b6b31e/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L59)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

It may be easy to do, but we've decided (with Dan) to go one with this way and fix it later.
</blockquote></details>

I had understood the decision to be "if it's hard to calculate tx hash for invoke" we'll do it this way. This seems trivially simple if we just set some constant ChainId?

https://github.com/starkware-libs/sequencer/blob/004cacf2fc7b139a9e9508918b0c51c5623c260a/crates/starknet_api/src/transaction.rs#L95

Then later in another PR we can make this configurable. This seems much easier than what is being done here and is also what we want to do going forward.
___
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 243 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2183#-OCZWem49wplxUQuVoJm:-OCZWem5-9vVURxy91OP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/004cacf2fc7b139a9e9508918b0c51c5623c260a/crates/papyrus_protobuf/src/converters/consensus.rs#L243)):*
> ```XML
>             .map(Felt::try_from)
>             .collect::<Result<Vec<Felt>, ProtobufConversionError>>()?;
>         let tx_hashes = tx_hashes.into_iter().map(TransactionHash).collect();
> ```





_Suggestion:_
```XML
        let tx_hashes = value
            .tx_hashes
            .into_iter()
            .map(|x| Felt::try_from(x).map(TransactionHash))
            .collect::<Result<_, Self::Error>>()?;
```


<!-- Sent from Reviewable.io -->

2024-11-26 08:46 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2183)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 243 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2183#-OCZWem49wplxUQuVoJm:-OCbdU9qEQ7CS-SXzJHU:b-jh8fu9) ([raw file](https://github.com/starkware-libs/sequencer/blob/004cacf2fc7b139a9e9508918b0c51c5623c260a/crates/papyrus_protobuf/src/converters/consensus.rs#L243)):*
> ```XML
>             .map(Felt::try_from)
>             .collect::<Result<Vec<Felt>, ProtobufConversionError>>()?;
>         let tx_hashes = tx_hashes.into_iter().map(TransactionHash).collect();
> ```

Thanks! I was wondering how to do that in one assignment. 


<!-- Sent from Reviewable.io -->

2024-11-26 08:48 UTC, matan-starkware approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2183)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2024-11-26 09:18 UTC, merged