feat(cairo_native): add batcher compiler struct
starkware-libs/sequencer pull request #2187
Opened 2024-11-19 15:40 UTC by avi-starkware

2024-11-19 15:40 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2187)
<!-- Reviewable:end -->

2024-11-20 06:56 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/batcher_compiler.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OC7LJWE5E3fdBK-IZ4I:-OC7LJWE5E3fdBK-IZ4J:bvetbcf) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f6aaea198d6a66749c2914fa95cb5d754928be0/crates/blockifier/src/execution/native/batcher_compiler.rs#L15)):*
> ```XML
> 
> struct BatcherCompiler {
>     contract_cache_manager: GlobalContractCacheManager,
> ```

Move this file some place else, since non-native code is going to use it.
Maybe under state dir.



_Suggestion:_
```XML
struct ContractClassManager {
    contract_cache_manager: ContractClassCaches,
```


<!-- Sent from Reviewable.io -->

2024-11-20 07:03 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/batcher_compiler.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OC7NQ-nEZxmOJH-hNwh:-OC7NQ-nEZxmOJH-hNwi:bb6u032) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f6aaea198d6a66749c2914fa95cb5d754928be0/crates/blockifier/src/execution/native/batcher_compiler.rs#L29)):*
> ```XML
>     }
>     pub fn run(&self) {
>         for (class_hash, sierra_contract_class) in self.compilation_request_receiver.iter() {
> ```

Cool



_Code quote:_
```XML
for (class_hash, sierra_contract_class) in self.compilation_request_receiver.iter() {
```


<!-- Sent from Reviewable.io -->

2024-11-20 07:11 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/batcher_compiler.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OC7PBBM0WL8fIl0m6fV:-OC7PBBM0WL8fIl0m6fW:b-kef0ly) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f6aaea198d6a66749c2914fa95cb5d754928be0/crates/blockifier/src/execution/native/batcher_compiler.rs#L44)):*
> ```XML
>                 }
>                 Err(err) => {
>                     eprintln!("Error compiling contract class: {}", err);
> ```

Why not log::error? what's the diff?



_Code quote:_
```XML
eprintln!(
```


<!-- Sent from Reviewable.io -->

2024-11-20 07:44 UTC, meship-starkware reviewed
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-21 17:01 UTC, avi-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/batcher_compiler.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OC7LJWE5E3fdBK-IZ4I:-OCDrUG_Bvf92Sxh_CGI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f6aaea198d6a66749c2914fa95cb5d754928be0/crates/blockifier/src/execution/native/batcher_compiler.rs#L15)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Move this file some place else, since non-native code is going to use it.
Maybe under state dir.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/native/batcher_compiler.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OC7NBmS6ll9_MuJhKeu:-OCDt7Nd42xY6rzEBU8u:bw4jmr7) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f6aaea198d6a66749c2914fa95cb5d754928be0/crates/blockifier/src/execution/native/batcher_compiler.rs#L42)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Whay did we say about the sierra cache? we don't need to update it here?
</blockquote></details>

It will be updated by the thread that sent the request for compilation.
___
*[`crates/blockifier/src/execution/native/batcher_compiler.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OC7PBBM0WL8fIl0m6fV:-OCDv8gW9HIk8XjyrCB7:bnv90gt) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f6aaea198d6a66749c2914fa95cb5d754928be0/crates/blockifier/src/execution/native/batcher_compiler.rs#L44)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not log::error? what's the diff?
</blockquote></details>

`error!` worked with a logger that can be configured with templates and be consistent with other modules using the same logger. `eprintln!` just prints the string as is to `stdout`. No logger, no configuration.

We should probably use `error!` here.
___
*[`crates/blockifier/src/execution/native/batcher_compiler.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OC7MsW07HFp_m6tHOi2:-OCDrPMV3r8Q_jxuUrec:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f6aaea198d6a66749c2914fa95cb5d754928be0/crates/blockifier/src/execution/native/batcher_compiler.rs#L31)):*
> ```XML
>         for (class_hash, sierra_contract_class) in self.compilation_request_receiver.iter() {
>             if self.contract_cache_manager.get_native_contract_executor(&class_hash).is_some() {
>                 // Skip the compilation if the contract class is already compiled to native.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-24 06:15 UTC, Yoni-Starkware requested changes
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/batcher_compiler.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OC7LJWE5E3fdBK-IZ4I:-OCRnpnS2QM8oAHbVwka:b-4t7cqk) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f6aaea198d6a66749c2914fa95cb5d754928be0/crates/blockifier/src/execution/native/batcher_compiler.rs#L15)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still under native. How are you going to integrate it to our executor?
___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRnRLB-FBd_kjF5MiQ:-OCRnRLC3sLt1hRakWxp:ba8359x) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L3)):*
> ```XML
> use std::sync::Arc;
> 
> use crossbeam_channel::{Receiver, Sender, TrySendError};
> ```

Why not something from the std? What's the pros/cons?


<!-- Sent from Reviewable.io -->

2024-11-24 06:17 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCRoMZG7zWYuSwrhrfG:bc37gov) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
> ```XML
>     }
> 
>     pub fn handle_compilation_requests_loop(&self) {
> ```

Better to have this private


<!-- Sent from Reviewable.io -->

2024-11-24 06:20 UTC, Yoni-Starkware requested changes
Please add a test. Can be in a separate PR

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-:-OCRp2v94Lcg7cCDYm8z:bbmoajj)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoy-U8XeakDe8FO0m:-OCRoy-U8XeakDe8FO0n:b-k8kivq) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L16)):*
> ```XML
> type CompilationRequest = (ClassHash, Arc<SierraContractClass>, ContractClassV1);
> 
> struct ContractClassManager {
> ```

Document the struct.


<!-- Sent from Reviewable.io -->

2024-11-26 08:55 UTC, avi-starkware commented
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCbe3CH2vA-yP5kytlw:b-l9do4v) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Better to have this private
</blockquote></details>

How do you want to call this function if it's private?
My understanding is that the PyBlockExecutor is going to create the ContractClassManager under `Arc` when it starts running and then give a clone of the `Arc` to the compilation thread and to each newly created `PapyrusReader`. The compilation thread just runs `handle_compilation_requests_loop`, and the `PapyrusReader` uses the caches and sends compilation requests.

If this function is private, the compilation thread cannot run it. To deny access to this function from the `PapyrusReader` we can create two structs: one containing the sender, the other containing the receiver (both containing the caches). Will that be better?


<!-- Sent from Reviewable.io -->

2024-11-26 09:02 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCbgvng9pm2GyrKyl2Z:bscdnkz) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

How do you want to call this function if it's private?
My understanding is that the PyBlockExecutor is going to create the ContractClassManager under `Arc` when it starts running and then give a clone of the `Arc` to the compilation thread and to each newly created `PapyrusReader`. The compilation thread just runs `handle_compilation_requests_loop`, and the `PapyrusReader` uses the caches and sends compilation requests.

If this function is private, the compilation thread cannot run it. To deny access to this function from the `PapyrusReader` we can create two structs: one containing the sender, the other containing the receiver (both containing the caches). Will that be better?
</blockquote></details>

In the `new` constructor. Put it inside the struct, why not?


<!-- Sent from Reviewable.io -->

2024-11-26 10:33 UTC, avi-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRnRLB-FBd_kjF5MiQ:-OCby0thECnEMlUf24Xh:b-ggzaly) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L3)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not something from the std? What's the pros/cons?
</blockquote></details>

Crossbeam offers better performance and more features. The channel is not expected to be a performance overhead and all the features of `channel` we currently use are included in both, so we're probably better off using `std::sync::mpsc`.
___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCc-0E-3GQFVyxawe6l:b-lbut5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

In the `new` constructor. Put it inside the struct, why not?
</blockquote></details>

What do you mean?


<!-- Sent from Reviewable.io -->

2024-11-26 12:01 UTC, Yoni-Starkware requested changes
> Reviewed 3 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCcLBWLCYDJlVeL7E06:bs3rbg4) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

Run the thread inside `pub fn new(`, and let the struct hold it. Why not?


<!-- Sent from Reviewable.io -->

2024-11-26 12:21 UTC, avi-starkware commented
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCcPfBdBNnXhxsQ5UYJ:b-ct0t0a) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Run the thread inside `pub fn new(`, and let the struct hold it. Why not?
</blockquote></details>

Sounds good. I'll try that.


<!-- Sent from Reviewable.io -->

2024-11-26 12:44 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCcUgqk1ilNHy9rDrLB:-OCcUgqk1ilNHy9rDrLC:bv4ejzd) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1994155b7b731f47ce10c1741f33b16b3853044/crates/blockifier/src/state/contract_class_manager.rs#L69)):*
> ```XML
> 
>     /// Tries to send a compilation request to the manager. Does not block the sender thread. If
>     /// the channel is full, returns an error.
> ```

This might be problematic (fail a specific tx)
what is the limit of the channel? 



_Code quote:_
```XML
the channel is full, returns an error.
```


<!-- Sent from Reviewable.io -->

2024-11-26 12:55 UTC, avi-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCcVoD2-aBTtxG65-8T:bks7v8z) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Sounds good. I'll try that.
</blockquote></details>

The receiver can't be part of the struct. It can only be held by one thread, so rust doesn't let me clone the arc of the struct if the struct contains the receiver.
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCcUgqk1ilNHy9rDrLB:-OCcWc7y4c90mYmPiyf0:b1nkqk8) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1994155b7b731f47ce10c1741f33b16b3853044/crates/blockifier/src/state/contract_class_manager.rs#L69)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This might be problematic (fail a specific tx)
what is the limit of the channel?
</blockquote></details>

This is what we agreed upon in the design. The size of the compilation queue is bounded to limit its memory usage. When the queue is full, no new compilation requests can be made, so it returns an error.

Do we want to make it unbounded?


<!-- Sent from Reviewable.io -->

2024-11-26 13:14 UTC, avi-starkware commented
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCcaPnn5f9Brs0Sh6uV:bdml3nh) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

The receiver can't be part of the struct. It can only be held by one thread, so rust doesn't let me clone the arc of the struct if the struct contains the receiver.
</blockquote></details>

I think this is nicer now.
To create the manager all you need is the caches struct. The compiler and channel can be created inside the method that generates the struct and starts the compilation thread.


<!-- Sent from Reviewable.io -->

2024-11-26 15:20 UTC, Yoni-Starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCd2THwE2f521xLE2i5:bf0r24f) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think this is nicer now.
To create the manager all you need is the caches struct. The compiler and channel can be created inside the method that generates the struct and starts the compilation thread.
</blockquote></details>

Don't you need to store the thread somewhere? what happens when `new` is over?
Doesn't it drop the thread?

Please add a super short test to make sure this is working
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCcUgqk1ilNHy9rDrLB:-OCd24gC6pQkhmrk4XrS:b-hqxbdu) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1994155b7b731f47ce10c1741f33b16b3853044/crates/blockifier/src/state/contract_class_manager.rs#L69)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This is what we agreed upon in the design. The size of the compilation queue is bounded to limit its memory usage. When the queue is full, no new compilation requests can be made, so it returns an error.

Do we want to make it unbounded?
</blockquote></details>

I don't want it to stop the batcher. In case the queue is full, let's not propagate this error. Maybe add a log
This size should be part of the config (add a TODO)


<!-- Sent from Reviewable.io -->

2024-11-26 16:05 UTC, avi-starkware commented
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCdBgWv2RW6C878zUoc:b8087l2) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Don't you need to store the thread somewhere? what happens when `new` is over?
Doesn't it drop the thread?

Please add a super short test to make sure this is working
</blockquote></details>

We can store the `JoinHandle` returned from `thread::spawn`, but all it does is allow us to wait for the thread to terminate, and this thread is an infinite loop.

In rust, a spawned thread stays alive as long as the main thread is alive and it did not terminate by itself.

I tried a simple example spawning a thread from inside a function and it stayed alive until it finished even after the function terminated.


<!-- Sent from Reviewable.io -->

2024-11-26 16:20 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCdFnEaC_TQaCcIL8Xi:b-2zuj4n) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

We can store the `JoinHandle` returned from `thread::spawn`, but all it does is allow us to wait for the thread to terminate, and this thread is an infinite loop.

In rust, a spawned thread stays alive as long as the main thread is alive and it did not terminate by itself.

I tried a simple example spawning a thread from inside a function and it stayed alive until it finished even after the function terminated.
</blockquote></details>

That's risky (leaks). I think we should wait for the thread to terminate once this struct is dropped.
The `drop` should inject some termination signal to the channel, and wait until the thread is terminated.


<!-- Sent from Reviewable.io -->

2024-11-26 16:23 UTC, avi-starkware commented
*[`crates/blockifier/src/state/contract_class_manager.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCcUgqk1ilNHy9rDrLB:-OCdDMyi4TWB5Bw1fFaI:bgy3550) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1994155b7b731f47ce10c1741f33b16b3853044/crates/blockifier/src/state/contract_class_manager.rs#L69)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I don't want it to stop the batcher. In case the queue is full, let's not propagate this error. Maybe add a log
This size should be part of the config (add a TODO)
</blockquote></details>

Done.

Added TODO where the channel is created.


<!-- Sent from Reviewable.io -->

2024-11-26 16:57 UTC, avi-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCdOlDU3XpS_-InUvdW:b-sjfesb) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

That's risky (leaks). I think we should wait for the thread to terminate once this struct is dropped.
The `drop` should inject some termination signal to the channel, and wait until the thread is terminated.
</blockquote></details>

Done.
Added an AtomicBool to signal the termination of the thread.


<!-- Sent from Reviewable.io -->

2024-11-27 06:39 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 6 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OCgL0Og9rUSfnp7yPbL:b-hqzn3z) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.
Added an AtomicBool to signal the termination of the thread.
</blockquote></details>

Not good enough. If the channel is empty, it will never reach to your check.
Please impl the `drop` as well


<!-- Sent from Reviewable.io -->

2024-11-27 06:41 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCcUgqk1ilNHy9rDrLB:-OCgLGeO8L-eUGE6Wya_:b-6e3fkm) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1994155b7b731f47ce10c1741f33b16b3853044/crates/blockifier/src/state/contract_class_manager.rs#L69)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.

Added TODO where the channel is created.
</blockquote></details>

Also, add a TODO to check for duplicated requests before filling the queue.
If native compile time can be 10 secs, we might blast this channel with the same request over and over again


<!-- Sent from Reviewable.io -->

2024-11-27 12:36 UTC, avi-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OChbXbk0Kl-A3YVXtgx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not good enough. If the channel is empty, it will never reach to your check.
Please impl the `drop` as well
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCcUgqk1ilNHy9rDrLB:-OChbsG20xrXb6nNcb_r:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1994155b7b731f47ce10c1741f33b16b3853044/crates/blockifier/src/state/contract_class_manager.rs#L69)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Also, add a TODO to check for duplicated requests before filling the queue.
If native compile time can be 10 secs, we might blast this channel with the same request over and over again
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-28 07:10 UTC, meship-starkware approved these changes
> Reviewed 6 of 7 files at r2, 4 of 6 files at r3, 1 of 2 files at r4, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/global_cache.rs` line 55 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCla27ACmwJ02hMQzJV:-OCla27ACmwJ02hMQzJW:byo887b) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec98965e5bc11c38afe469b1cdc317fa312d19df/crates/blockifier/src/state/global_cache.rs#L55)):*
> ```XML
> 
> #[cfg(feature = "cairo_native")]
> pub struct ContractClassCaches {
> ```

Should it be changed to Compiled class as well? If so, I'll just put it here to see if it changed after a rebase. 



_Code quote:_
```XML
pub struct ContractClassCaches 
```
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 213 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OClZVoF2Ll_diuSjhVs:-OClZVoF2Ll_diuSjhVt:b-9witzw) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec98965e5bc11c38afe469b1cdc317fa312d19df/crates/blockifier/src/state/contract_class_manager.rs#L213)):*
> ```XML
>     fn drop(&mut self) {
>         self.stop();
>         let join_handle = self.join_handle.lock().unwrap().take().expect(
> ```

Why is it ok to unwrap here? I understand only one thread should access this handle, so there should be no problem, but I am not sure that is enough. Consider implementing a self.lock_join_handle() that will expect with an error message and use it here.    



_Code quote:_
```XML
let join_handle = self.join_handle.lock().unwrap().take().expect(
```


<!-- Sent from Reviewable.io -->

2024-11-28 07:24 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 118 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCldfwoDcykpKjOb19J:-OCle0Fz2Wh6o6PB571G:b3p2uf7) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec98965e5bc11c38afe469b1cdc317fa312d19df/crates/blockifier/src/state/contract_class_manager.rs#L118)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Hey, why not use the blocking `send`? it's perfect for us
</blockquote></details>

Oh, it might block the main thread


<!-- Sent from Reviewable.io -->

2024-11-28 08:10 UTC, avi-starkware commented
*[`crates/blockifier/src/state/global_cache.rs` line 55 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCla27ACmwJ02hMQzJV:-OCloVLJ1lzfitW7TVPK:b-lsqo6u) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec98965e5bc11c38afe469b1cdc317fa312d19df/crates/blockifier/src/state/global_cache.rs#L55)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Should it be changed to Compiled class as well? If so, I'll just put it here to see if it changed after a rebase.
</blockquote></details>

Done.
Let me know what you think


<!-- Sent from Reviewable.io -->

2024-11-28 08:10 UTC, avi-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 66 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OClcAyCC6qb_T47W9-i:-OClgs2t35zIQuNqAoMA:b-954r8n) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec98965e5bc11c38afe469b1cdc317fa312d19df/crates/blockifier/src/state/contract_class_manager.rs#L66)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

SierraToCasm ???
Add a TODO to fix this, and to pass compilation config through the manager config
</blockquote></details>


Right now all this config holds is the `max_bytecode` limit argument sent to the cairo lang compiler.
I will add the config in the PR that adds the resource limits to the compilation process.
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 91 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OClcW1R8zujEE_NZOGm:-OClgk1D77VTlSSzbDvW:b-wgmuq7) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec98965e5bc11c38afe469b1cdc317fa312d19df/crates/blockifier/src/state/contract_class_manager.rs#L91)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

If I don't drop it, it doesn't let me return the `contract_class_manager` at the end, because the mutex guard borrows the join_handle field. Here's the error I get from clippy:
```
   cannot move out of `contract_class_manager` because it is borrowed
```
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 213 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OClZVoF2Ll_diuSjhVs:-OClfuMW4GeOkeFAiL_o:bl7r3gp) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec98965e5bc11c38afe469b1cdc317fa312d19df/crates/blockifier/src/state/contract_class_manager.rs#L213)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why is it ok to unwrap here? I understand only one thread should access this handle, so there should be no problem, but I am not sure that is enough. Consider implementing a self.lock_join_handle() that will expect with an error message and use it here.
</blockquote></details>

Done.

I don't think this needs another function. It doesn't save much and it forces the message to be the same in both places the mutex is taken.


<!-- Sent from Reviewable.io -->

2024-11-28 09:00 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-:-OCm--73BrfUXdzYb846:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-28 09:05 UTC, avi-starkware commented
*[`crates/blockifier/src/execution/native/contract_class_manager.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCRoMZG7zWYuSwrhrfF:-OClwfxD5u6OOtCaI1cu:beuk5g3) ([raw file](https://github.com/starkware-libs/sequencer/blob/518ba9c3c493c18c80e041f33ab4dac51cbfd71f/crates/blockifier/src/execution/native/contract_class_manager.rs#L33)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The termination mechanism and drop might not be strictly necessary, because when the `Sender` end is dropped the channel closes (unless there are additional clones of the Sender...). When the channel closes, `receiver.iter()` ends without error.

See [here](https://github.com/rust-lang/rust/blob/f005c7437def424a1c43cbc380352a58d8ac920b/library/std/src/sync/mpmc/mod.rs#L624). When a sender is dropped  the function `disconnect_senders` is called, which calls `disconnect_receivers` if there are 0 senders.

So perhaps we can assume dropping the contract class manager automatically stops the thread since it drops the sender and therefore the receiver. WDYT?


<!-- Sent from Reviewable.io -->

2024-11-28 12:59 UTC, Yoni-Starkware reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r15, 1 of 2 files at r16, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-:-OCmqgFy2BTGSpg2TYQA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/state/global_cache.rs` line 56 at r20](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCmq3R80_q0ATrCjLUn:-OCmq3R9-ucXVD2r1X6H:be34vh0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3f7ad1ecca3d806c300832dd1659855c5ddbc34d/crates/blockifier/src/state/global_cache.rs#L56)):*
> ```XML
> #[cfg(feature = "cairo_native")]
> pub struct ContractCaches {
>     pub casm_cache: GlobalContractCache<RunnableCompiledClass>,
> ```

For now, be consistent with native's type here



_Suggestion:_
```XML
CompiledClassV1
```


<!-- Sent from Reviewable.io -->

2024-11-28 13:01 UTC, avi-starkware commented
*[`crates/blockifier/src/state/global_cache.rs` line 56 at r20](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCmq3R80_q0ATrCjLUn:-OCmqyjt3YFw386TqDaW:bw1pq2a) ([raw file](https://github.com/starkware-libs/sequencer/blob/3f7ad1ecca3d806c300832dd1659855c5ddbc34d/crates/blockifier/src/state/global_cache.rs#L56)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

For now, be consistent with native's type here
</blockquote></details>

But where will we cache Cairo 0 contracts? Do you want to add another global cache for that?


<!-- Sent from Reviewable.io -->

2024-11-28 13:06 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/state/global_cache.rs` line 56 at r20](https://reviewable.io/reviews/starkware-libs/sequencer/2187#-OCmq3R80_q0ATrCjLUn:-OCms57HB4oYv4D4gHaO:b-gxdpzf) ([raw file](https://github.com/starkware-libs/sequencer/blob/3f7ad1ecca3d806c300832dd1659855c5ddbc34d/crates/blockifier/src/state/global_cache.rs#L56)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

But where will we cache Cairo 0 contracts? Do you want to add another global cache for that?
</blockquote></details>

Hmmm you are right. I think it's a good idea to separate the caches - but in a separate PR.
Resolved


<!-- Sent from Reviewable.io -->

2024-11-28 13:09 UTC, avi-starkware reviewed
> Reviewed 1 of 2 files at r4, 1 of 3 files at r15, 1 of 2 files at r16, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2187)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-11-28 13:09 UTC, merged