chore(infra): move trigget to rebuild into install command
starkware-libs/sequencer pull request #2196
Opened 2024-11-20 14:45 UTC by ArniStarkware

2024-11-20 14:45 UTC, ArniStarkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2196?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2196** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2196?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2196?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2185** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2185?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-20 14:45 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2196)
<!-- Reviewable:end -->

2024-11-20 15:22 UTC, avi-starkware requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2196)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Itay-Tsabary-Starkware)

___
*[`Cargo.lock` line 1503 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2196#-OC99ak8BvqrrsToFBpn:-OC99ak8BvqrrsToFBpo:b70nbvq) ([raw file](https://github.com/starkware-libs/sequencer/blob/e29d72b80047be3d54ac9ca3c4ff0b25161e9b30/Cargo.lock#L1503)):*
> ```TOML
>  "itertools 0.12.1",
>  "keccak",
>  "lazy_static",
> ```

Where did this change come from?



_Code quote:_
```TOML
 "lazy_static",
```


<!-- Sent from Reviewable.io -->

2024-11-21 06:22 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2196)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @Itay-Tsabary-Starkware)

___
*[`Cargo.lock` line 1503 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2196#-OC99ak8BvqrrsToFBpn:-OCCNKzq6jzd2buwV6M8:biwubg4) ([raw file](https://github.com/starkware-libs/sequencer/blob/e29d72b80047be3d54ac9ca3c4ff0b25161e9b30/Cargo.lock#L1503)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Where did this change come from?
</blockquote></details>

According to Reviewable and GitHub, this is no longer part of the PR. It was probably solved during the restack.


<!-- Sent from Reviewable.io -->

2024-11-21 09:19 UTC, merged