chore(batcher): use thin block info to create block info
starkware-libs/sequencer pull request #2238
Opened 2024-11-24 07:54 UTC by ArniStarkware

2024-11-24 07:54 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2238)
<!-- Reviewable:end -->

2024-11-24 07:54 UTC, ArniStarkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2238?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2238** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2238?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2238?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2237** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2237?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2231** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2231?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2230** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2230?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-24 08:24 UTC, yair-starkware requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @dafnamatsry)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSEZAIBtkzNEzyGgW1:-OCSEZAIBtkzNEzyGgW2:b-pso4r5) (no related file):*
Do gas prices and kzg determined at each proposal, or are they determined at the beginning of each height?
If per height, we can move them to the start height input
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSGKXMBiLjyHBWkNK5:-OCSGKXMBiLjyHBWkNK6:bb73xfv) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/proposal_manager_test.rs#L37)):*
> ```XML
> 
> static BLOCK_INFO_AT_INITIAL_HEIGHT: LazyLock<BlockInfo> =
>     LazyLock::new(|| BlockInfo { block_number: INITIAL_HEIGHT, ..Default::default() });
> ```

Same



_Code quote:_
```XML
static BLOCK_INFO_AT_INITIAL_HEIGHT: LazyLock<BlockInfo> =
    LazyLock::new(|| BlockInfo { block_number: INITIAL_HEIGHT, ..Default::default() });
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSFTG275QIu4_oLNmJ:-OCSFTG275QIu4_oLNmK:bothx1l) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/batcher_test.rs#L60)):*
> ```XML
> 
> static BLOCK_INFO_AT_INITIAL_HEIGHT: LazyLock<BlockInfo> =
>     LazyLock::new(|| BlockInfo { block_number: INITIAL_HEIGHT, ..Default::default() });
> ```

Consider using dummy values so you won't need the lazy lock.
You're supposed to remove the default anyway, right?



_Code quote:_
```XML
static BLOCK_INFO_AT_INITIAL_HEIGHT: LazyLock<BlockInfo> =
    LazyLock::new(|| BlockInfo { block_number: INITIAL_HEIGHT, ..Default::default() });
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 431 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSEELv9le3gV7Ab93p:-OCSEELv9le3gV7Ab93q:b-ffpnq) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/batcher.rs#L431)):*
> ```XML
> }
> 
> // TODO: Move to a common place.
> ```

to `starknet_batcher_types`



_Code quote:_
```XML
common place
```
___
*[`crates/starknet_batcher/src/block_builder.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSG6aO--m1mxj5ypZi:-OCSG6aP5AkC5sqJeQ_h:btvmfns) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/block_builder.rs#L316)):*
> ```XML
>             },
>             // TODO: Override the use_kzg_da flag.
>             use_kzg_da: self.block_builder_config.use_kzg_da,
> ```

Why don't you take these from the `next_block_info`?



_Code quote:_
```XML
            gas_prices: {
                let tmp_val = NonzeroGasPrice::MIN;
                GasPrices::new(tmp_val, tmp_val, tmp_val, tmp_val, tmp_val, tmp_val)
            },
            // TODO: Override the use_kzg_da flag.
            use_kzg_da: self.block_builder_config.use_kzg_da,
```


<!-- Sent from Reviewable.io -->

2024-11-24 14:54 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSEZAIBtkzNEzyGgW1:-OCTTadc5TK_FoE_RSLX:b-n9jecx) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Do gas prices and kzg determined at each proposal, or are they determined at the beginning of each height?
If per height, we can move them to the start height input
</blockquote></details>

IIUC, gas prices are determined at each proposal.
___
*[`crates/starknet_batcher/src/batcher.rs` line 431 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSEELv9le3gV7Ab93p:-OCTTjXi4hEWum0BVlDu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/batcher.rs#L431)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

to `starknet_batcher_types`
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSFTG275QIu4_oLNmJ:-OCTVP_U0A74SM_Po5lU:b-uxkkls) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/batcher_test.rs#L60)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider using dummy values so you won't need the lazy lock.
You're supposed to remove the default anyway, right?
</blockquote></details>

Initializing static ContractAddress is difficult, so I do not see how we can lose the lazy lock (other than using a function and computing the value for each test).

Now, we are using `create_for_testing()` so that we will not use default when it is not needed.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSG6aO--m1mxj5ypZi:-OCTTvQ7567XKqQQemAy:b-2eaw8p) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/block_builder.rs#L316)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why don't you take these from the `next_block_info`?
</blockquote></details>

The value of `next_block_info` originally comes from: `ProposeBlockInput`, which still needs to be filled. Once it is filled, the values should be propagated here.
https://reviewable.io/reviews/starkware-libs/sequencer/2237#-OCTUZwq3yG6618ECY0s

I can see why it is confusing - and maybe some other approach should be taken. 
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSGKXMBiLjyHBWkNK5:-OCTVH_UEnfqIHCtzSQZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/proposal_manager_test.rs#L37)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-26 09:25 UTC, yair-starkware submitted a review, later dismissed
> Reviewed 7 of 8 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSFTG275QIu4_oLNmJ:-OCbkjuBB9obcnXa5uh7:b-mmo7b1) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/batcher_test.rs#L60)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Initializing static ContractAddress is difficult, so I do not see how we can lose the lazy lock (other than using a function and computing the value for each test).

Now, we are using `create_for_testing()` so that we will not use default when it is not needed.
</blockquote></details>

Found an example:
```
pub const BLOCK_HASH_TABLE_ADDRESS: ContractAddress = ContractAddress(PatriciaKey(StarkHash::ONE));
```
___
*[`crates/starknet_batcher/src/block_builder.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSG6aO--m1mxj5ypZi:-OCbli7w-YfnD0zDNhOf:bz7l85p) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/block_builder.rs#L316)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The value of `next_block_info` originally comes from: `ProposeBlockInput`, which still needs to be filled. Once it is filled, the values should be propagated here.
https://reviewable.io/reviews/starkware-libs/sequencer/2237#-OCTUZwq3yG6618ECY0s

I can see why it is confusing - and maybe some other approach should be taken.
</blockquote></details>

Why don't you fill the tmp vals in the preliminary PR and then use them here?
___
*[`crates/starknet_batcher/src/batcher.rs` line 428 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCbkD0N7v8pp8TmPGjr:-OCbkD0N7v8pp8TmPGjs:b5fesc0) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/batcher.rs#L428)):*
> ```XML
> /// 2. `next_block_number` matches the current `height`.
> ///
> /// Returns an error if either condition is violated.
> ```

IMO this doc is unnecessary



_Code quote:_
```XML
/// Validates block input by ensuring:
/// 1. `retrospective_block_hash` is provided for blocks beyond the
///    [`STORED_BLOCK_HASH_BUFFER`](constants::STORED_BLOCK_HASH_BUFFER).
/// 2. `next_block_number` matches the current `height`.
///
/// Returns an error if either condition is violated.
```


<!-- Sent from Reviewable.io -->

2024-11-26 09:42 UTC, yair-starkware commented
*[`crates/starknet_batcher/src/batcher.rs` line 428 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCbkD0N7v8pp8TmPGjr:-OCbqQKP9ECwEvoOZgSe:b71qeie) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/batcher.rs#L428)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I like it here. Each function called `validate_object` is, by nature, very confusing. I want to see what we are validating as clearly as possible.
</blockquote></details>

A better way is to create 2 internal functions with clear naming and just calling them


<!-- Sent from Reviewable.io -->

2024-11-26 12:55 UTC, alonh5 requested changes
> Reviewed 7 of 8 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 428 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCbkD0N7v8pp8TmPGjr:-OCcXZHv7yTePz7Tv5Po:b-8fx2u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/batcher.rs#L428)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

A better way is to create 2 internal functions with clear naming and just calling them
</blockquote></details>

:+1: 
___
*[`crates/starknet_batcher/src/block_builder.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSG6aO--m1mxj5ypZi:-OCcUvC0-1zLp-lFokgg:bhjcvvg) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/block_builder.rs#L316)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why don't you fill the tmp vals in the preliminary PR and then use them here?
</blockquote></details>

You can pass these same default values in the input from the consensus and move the TODO over there (in this PR).
___
*[`crates/starknet_batcher/src/block_builder.rs` line 221 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcUCOmDEUZB0nvxxsB:-OCcUCOmDEUZB0nvxxsC:b9ocgj3) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/block_builder.rs#L221)):*
> ```XML
> 
> pub struct BlockMetadata {
>     pub next_block_info: BlockInfo,
> ```

Can we add the retrospective block hash to the block info and get rid of this struct?
___
*[`crates/starknet_batcher/src/block_builder.rs` line 310 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcUiI8Do-cTRobwHeR:-OCcUiI8Do-cTRobwHeS:b-7u6h8f) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/block_builder.rs#L310)):*
> ```XML
>         let next_block_info = BlockInfo {
>             block_number: block_metadata.next_block_info.block_number,
>             // TODO: Use block_metadata.next_block_info.block_timestamp once it is initialized.
> ```

All these can be one TODO at the top.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcDyhoAxlkSeKfeOvx:-OCcDyhoAxlkSeKfeOvy:b-wo1g59) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L119)):*
> ```XML
>             }),
>             // TODO: Fill block info.
>             next_block_info: BlockInfo { block_number: proposal_init.height, ..Default::default() },
> ```

This is part of the propose block input, everything here refers to the block that is about to be built. (Remove everywhere)



_Suggestion:_
```XML
block_info
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 59 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcTnUG3QeYktEY1WJM:-OCcTnUG3QeYktEY1WJN:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/batcher_test.rs#L59)):*
> ```XML
> const PROPOSAL_ID: ProposalId = ProposalId(0);
> 
> static BLOCK_INFO_AT_INITIAL_HEIGHT: LazyLock<BlockInfo> =
> ```





_Suggestion:_
```XML
INITIAL_BLOCK_INFO
```


<!-- Sent from Reviewable.io -->

2024-11-26 12:57 UTC, alonh5 reviewed
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-11-26 13:48 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 3 of 10 files reviewed, 4 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcDyhoAxlkSeKfeOvx:-OCccJP86fNvkPBFhWNO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L119)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is part of the propose block input, everything here refers to the block that is about to be built. (Remove everywhere)
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 428 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCbkD0N7v8pp8TmPGjr:-OCbxPuy26LojaKa5bZN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/batcher.rs#L428)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

A better way is to create 2 internal functions with clear naming and just calling them
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 221 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcUCOmDEUZB0nvxxsB:-OCc_GFV83eS-BFgVG1z:b-hz3hh) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/block_builder.rs#L221)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can we add the retrospective block hash to the block info and get rid of this struct?
</blockquote></details>

Out of scope for this PR.
Morally, the struct `BlockInfo` is an input to the Cario OS program. 
___
*[`crates/starknet_batcher/src/block_builder.rs` line 310 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcUiI8Do-cTRobwHeR:-OCcczlx5wo1IAaxyhUK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/block_builder.rs#L310)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

All these can be one TODO at the top.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 59 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcTnUG3QeYktEY1WJM:-OCccxp7CVL92qQUvBzi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/batcher_test.rs#L59)):*
> ```XML
> const PROPOSAL_ID: ProposalId = ProposalId(0);
> 
> static BLOCK_INFO_AT_INITIAL_HEIGHT: LazyLock<BlockInfo> =
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-27 07:38 UTC, yair-starkware reviewed
> Reviewed 3 of 7 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-11-27 11:07 UTC, alonh5 reviewed
> Reviewed 3 of 7 files at r6, 1 of 2 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 221 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcUCOmDEUZB0nvxxsB:-OChGERhBNjVkARzHOo6:bf3dizb) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/block_builder.rs#L221)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Out of scope for this PR.
Morally, the struct `BlockInfo` is an input to the Cario OS program.
</blockquote></details>

If it's not trivial then you're right it shouldn't be in this PR. But in general, do you think it would be possible? Where is the retrospective block hash received now in the OS?
___
*[`crates/starknet_batcher/src/batcher.rs` line 423 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OChEGLM4jA7uuRCfecA:-OChEGLM4jA7uuRCfecB:b3kmvpd) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0bb379c250dbfbf4d4087d8f7d6dc38ff9f18c7/crates/starknet_batcher/src/batcher.rs#L423)):*
> ```XML
> }
> 
> fn verify_block_input(
> ```

Looks good :)
___
*[`crates/starknet_batcher/src/batcher.rs` line 430 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OChEBJsBmXPv2lXo0MW:-OChEBJsBmXPv2lXo0MX:b-h1654o) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0bb379c250dbfbf4d4087d8f7d6dc38ff9f18c7/crates/starknet_batcher/src/batcher.rs#L430)):*
> ```XML
>     verify_non_empty_retrospective_block_hash(height, retrospective_block_hash)?;
>     verify_block_number(height, block_number)?;
> ```

Remove the blank line.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 56 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OChIFJgCihVi3yQYLTk:-OChIFJgCihVi3yQYLTl:bi5bi0c) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0bb379c250dbfbf4d4087d8f7d6dc38ff9f18c7/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L56)):*
> ```XML
> use tracing::{debug, debug_span, error, info, trace, warn, Instrument};
> 
> const TEMPORARY_GAS_PRICES: GasPrices = GasPrices {
> ```

Add TODO to remove?


<!-- Sent from Reviewable.io -->

2024-11-28 10:01 UTC, yair-starkware reviewed
> Reviewed 1 of 7 files at r6, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @dafnamatsry)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSG6aO--m1mxj5ypZi:-OCmCor6BFEgggITZh62:bvm7z8d) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/block_builder.rs#L316)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can pass these same default values in the input from the consensus and move the TODO over there (in this PR).
</blockquote></details>

Resolved
___
*[`crates/starknet_batcher/src/block_builder.rs` line 308 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCmCZ0iBMja7RAKm1qL:-OCmCZ0iBMja7RAKm1qM:b3b1xvz) ([raw file](https://github.com/starkware-libs/sequencer/blob/cefe8d0642b35f01189f1952cbf0c8d7f3426862/crates/starknet_batcher/src/block_builder.rs#L308)):*
> ```XML
>         let height = block_metadata.block_info.block_number;
>         let block_builder_config = self.block_builder_config.clone();
>         // TODO: Remove the overrides of the block info once once they are initialized.
> ```

There is already a TODO there right?
I think you can remove this TODO



_Code quote:_
```XML
// TODO: Remove the overrides of the block info once once they are initialized.
```


<!-- Sent from Reviewable.io -->

2024-11-28 12:56 UTC, ArniStarkware commented
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 56 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OChIFJgCihVi3yQYLTk:-OCmq5BM4QpFDWN4_2A8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0bb379c250dbfbf4d4087d8f7d6dc38ff9f18c7/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L56)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add TODO to remove?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-28 15:43 UTC, yair-starkware reviewed
> Reviewed 6 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-12-01 10:36 UTC, alonh5 requested changes
> Reviewed 1 of 7 files at r6, 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 59 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OD0lzUh1TMlYlvEpESA:-OD0lzUh1TMlYlvEpESB:bn1nqsp) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0aff4de015982ad5f79fa099de1d194cf6db792/crates/starknet_batcher/src/batcher_test.rs#L59)):*
> ```XML
> const PROPOSAL_ID: ProposalId = ProposalId(0);
> 
> static INITIAL_BLOCK_INFO: LazyLock<BlockInfo> =
> ```

Is it important to do this lazy in tests? Why not just create a function for it, it's simpler and you won't have to clone everywhere.


<!-- Sent from Reviewable.io -->

2024-12-01 13:12 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 430 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OChEBJsBmXPv2lXo0MW:-OCmpjO56qZm5YObyKIt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0bb379c250dbfbf4d4087d8f7d6dc38ff9f18c7/crates/starknet_batcher/src/batcher.rs#L430)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Remove the blank line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-02 07:57 UTC, yair-starkware reviewed
> Reviewed 2 of 7 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-12-02 15:55 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 5 of 11 files reviewed, 2 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSFTG275QIu4_oLNmJ:-OD6x73082bDPzB4EDJJ:b77pcxm) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/batcher_test.rs#L60)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Found an example:
```
pub const BLOCK_HASH_TABLE_ADDRESS: ContractAddress = ContractAddress(PatriciaKey(StarkHash::ONE));
```
</blockquote></details>

On a different PR, I am working on making the `create_for_testing` a `pub const fn`.
The two issues we will need to solve are to create a constant contract address and constant gas prices.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 59 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OD0lzUh1TMlYlvEpESA:-OD6x1dzEhYLl6E_6c-t:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0aff4de015982ad5f79fa099de1d194cf6db792/crates/starknet_batcher/src/batcher_test.rs#L59)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is it important to do this lazy in tests? Why not just create a function for it, it's simpler and you won't have to clone everywhere.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCSG6aO--m1mxj5ypZi:-OCmpzaDBtonUYUHbIUy:b-66zuqa) ([raw file](https://github.com/starkware-libs/sequencer/blob/228b1251f26923d484d84e707a403efd629b7e4f/crates/starknet_batcher/src/block_builder.rs#L316)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Resolved
</blockquote></details>

Resolved in the next PR: #2409.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 308 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCmCZ0iBMja7RAKm1qL:-OD6yGw8AcP8IA9c3bX3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdac31636a4c14bf1778f823eef062788cc1b5c0/crates/starknet_batcher/src/block_builder.rs#L308)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

There is already a TODO there right?
I think you can remove this TODO
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-03 11:55 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 221 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcUCOmDEUZB0nvxxsB:-ODBL6Lv4i9EFBQg99I3:b-ag9uo8) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/block_builder.rs#L221)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

If it's not trivial then you're right it shouldn't be in this PR. But in general, do you think it would be possible? Where is the retrospective block hash received now in the OS?
</blockquote></details>

TL;DR: I do not think it is correct to move `retrospective block hash` into `BlockInfo`.

The term `retrospective block hash` appears only in the context of the batcher.
The point where they diverge is here: https://github.com/starkware-libs/sequencer/blob/111c6fd7ea6895f6322c15865a6f7fafaf29781e/crates/blockifier/src/blockifier/transaction_executor.rs#L60-L74

The retrospective block hash is used in this code to pre-process the storage.
The block info is hidden inside the block context - and is later sent to the OS.


<!-- Sent from Reviewable.io -->

2024-12-03 12:00 UTC, yair-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-12-03 15:08 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 5 of 11 files reviewed, 3 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 316 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-ODC2dNK3zahmRKhwkor:-ODC2dNK3zahmRKhwkos:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/50bb19bc7b8b2336743eb18d82e11390284b7625/crates/starknet_batcher/src/block_builder.rs#L316)):*
> ```XML
>             sequencer_address: block_builder_config.sequencer_address,
>             ..block_metadata.block_info
>         };
> ```





_Suggestion:_
```XML
        let mut block_info = block_metadata.block_info;
        // TODO(Arni): Remove this override, and the corresponding config.
        block_info.sequencer_address = block_builder_config.sequencer_address;
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 169 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-ODC27flBzxCT2mgdMAs:-ODC27fmAdNt_IfPfUR_:bwnspo9) ([raw file](https://github.com/starkware-libs/sequencer/blob/50bb19bc7b8b2336743eb18d82e11390284b7625/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L169)):*
> ```XML
>             }),
>             // TODO(Dan, Matan): Fill block info. Override the sequencer address in the block info
>             // in the BlockBuilderFactory.
> ```

Revert. X2.



_Suggestion:_
```XML
            // TODO(Dan, Matan): Fill block info.
```


<!-- Sent from Reviewable.io -->

2024-12-03 16:07 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 169 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-ODC27flBzxCT2mgdMAs:-ODCFyy90n44lMTG77Hn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/50bb19bc7b8b2336743eb18d82e11390284b7625/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L169)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Revert. X2.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 316 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-ODC2dNK3zahmRKhwkor:-ODCGMBZ7iIPTvFviuly:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/50bb19bc7b8b2336743eb18d82e11390284b7625/crates/starknet_batcher/src/block_builder.rs#L316)):*
> ```XML
>             sequencer_address: block_builder_config.sequencer_address,
>             ..block_metadata.block_info
>         };
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-04 08:38 UTC, yair-starkware reviewed
> Reviewed 1 of 7 files at r11, 2 of 4 files at r13, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-12-04 14:45 UTC, ArniStarkware commented
*[`crates/starknet_batcher/src/block_builder.rs` line 221 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2238#-OCcUCOmDEUZB0nvxxsB:-ODH7XVfAqQPQqJ2Wk6c:b-cwfbkt) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c52c40ccc1e8fecf07e2d4d529712001714628d/crates/starknet_batcher/src/block_builder.rs#L221)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Okay, I didn't fully understand, but it's not important for now. I'll add a task to Monday to reconsider it
</blockquote></details>

I think it should not even be on Monday.


<!-- Sent from Reviewable.io -->

2024-12-04 15:19 UTC, alonh5 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2238)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-12-05 09:36 UTC, ArniStarkware commented
### Merge activity

* **Dec 5, 4:36 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2238).

2024-12-05 09:36 UTC, merged