refactor(starknet_api): use tx_hash constructor macro
starkware-libs/sequencer pull request #2287
Opened 2024-11-26 12:56 UTC by noam-starkware

Move `tx_hash!` macro constructor to `core.rs` in SN API and use macro throughout codebase.

2024-11-26 12:56 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2287)
<!-- Reviewable:end -->

2024-11-28 10:34 UTC, MohammadNassar1 requested changes
> Reviewed 18 of 19 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2287)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noam-starkware)

___
*[`crates/starknet_api/src/transaction.rs` line 782 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2287#-OCmJjU70g6k1T52GPrr:-OCmJjU854qtnF_abHRQ:b-t31tw4) ([raw file](https://github.com/starkware-libs/sequencer/blob/74ed2677014b64cc8bc6a9bf6095396688b67025/crates/starknet_api/src/transaction.rs#L782)):*
> ```XML
>         $crate::transaction::TransactionHash($crate::hash::StarkHash::from($tx_hash))
>     };
> }
> ```

Please move it to below the struct implementations.



_Code quote:_
```XML
/// A utility macro to create a [`TransactionHash`] from an unsigned integer representation.
#[cfg(any(feature = "testing", test))]
#[macro_export]
macro_rules! tx_hash {
    ($tx_hash:expr) => {
        $crate::transaction::TransactionHash($crate::hash::StarkHash::from($tx_hash))
    };
}
```


<!-- Sent from Reviewable.io -->

2024-11-28 12:30 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2287#-:-OCmk9RN1e2Q3uwFdAvu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-11-28 13:10 UTC, noam-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2287)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2287#-OCmseQG-Mm7TAq6S99Z:-OCmseQG-Mm7TAq6S99_:brpwgic) (no related file):*
To be consistent with similar cases (e.g., `ContractAddress`), the macro was placed near the definition of the `TransactionHash` struct.
___
*[`crates/starknet_api/src/transaction.rs` line 782 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2287#-OCmJjU70g6k1T52GPrr:-OCmOz-x-v7Mi4QODsTl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74ed2677014b64cc8bc6a9bf6095396688b67025/crates/starknet_api/src/transaction.rs#L782)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please move it to below the struct implementations.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-28 13:28 UTC, merged