test(starknet_mempool): tx added to mempool are forwarded to propagator client
starkware-libs/sequencer pull request #2288
Opened 2024-11-26 13:35 UTC by AlonLStarkWare

2024-11-26 13:35 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2288)
<!-- Reviewable:end -->

2024-11-27 08:21 UTC, ShahakShama requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2288)* status: all files reviewed, 6 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/starknet_mempool_p2p_types/src/communication.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCghKtx4wO2F3jqWRBO:-OCghKtx4wO2F3jqWRBP:bl4gkwi) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool_p2p_types/src/communication.rs#L23)):*
> ```XML
> use crate::mempool_p2p_types::MempoolP2pPropagatorResult;
> 
> #[automock]
> ```

Activate this only in feature testing and cfg test
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 708 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCggKYw0dgCb2CC8UHa:-OCggKYw0dgCb2CC8UHb:b-95wv8w) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool/src/mempool_test.rs#L708)):*
> ```XML
> async fn test_new_tx_sent_to_p2p(mempool: Mempool) {
>     // add_tx_input! creates an Invoke Transaction
>     let tx_1_args = add_tx_input!(tx_hash: 1, address: "0x0", tx_nonce: 2, account_nonce: 2);
> ```

rename to tx_args
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCggSyy4ygpu_k0T1Kt:-OCggSyy4ygpu_k0T1Ku:b3sg0wl) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool/src/mempool_test.rs#L709)):*
> ```XML
>     // add_tx_input! creates an Invoke Transaction
>     let tx_1_args = add_tx_input!(tx_hash: 1, address: "0x0", tx_nonce: 2, account_nonce: 2);
>     let new_tx_args =
> ```

rename to propagator_args
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 711 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCgguJc9YnNa8G_daHT:-OCgguJc9YnNa8G_daHU:bxfcau) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool/src/mempool_test.rs#L711)):*
> ```XML
>     let new_tx_args =
>         AddTransactionArgsWrapper { args: tx_1_args.clone(), p2p_message_metadata: None };
>     let new_rpc_tx = match tx_1_args.tx {
> ```

rename to rpc_tx
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 711 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCggxs-3xBDgk14tTAk:-OCggxs-3xBDgk14tTAl:b6nbg02) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool/src/mempool_test.rs#L711)):*
> ```XML
>     let new_tx_args =
>         AddTransactionArgsWrapper { args: tx_1_args.clone(), p2p_message_metadata: None };
>     let new_rpc_tx = match tx_1_args.tx {
> ```

add TODO to use regular conversion once we have a compiler component
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 741 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCghAZoDjMJGohYmU91:-OCghAZoDjMJGohYmU92:b3sg0wl) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool/src/mempool_test.rs#L741)):*
> ```XML
> async fn test_propagated_tx_sent_to_p2p(mempool: Mempool) {
>     // add_tx_input! creates an Invoke Transaction
>     let tx_2_args = add_tx_input!(tx_hash: 2, address: "0x0", tx_nonce: 3, account_nonce: 2);
> ```

rename to propagator_args


<!-- Sent from Reviewable.io -->

2024-12-02 14:52 UTC, AlonLStarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2288)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 708 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCggKYw0dgCb2CC8UHa:-OCn7itdC4hiN2nNrpGP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool/src/mempool_test.rs#L708)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to tx_args
</blockquote></details>

Done.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCggSyy4ygpu_k0T1Kt:-OCn7j7nA6SZrAKLi6xF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool/src/mempool_test.rs#L709)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to propagator_args
</blockquote></details>

Done.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 711 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCgguJc9YnNa8G_daHT:-OCn7iPO3G7Nu5PLlOwB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool/src/mempool_test.rs#L711)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to rpc_tx
</blockquote></details>

Done.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 711 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCggxs-3xBDgk14tTAk:-OCn7jgF3yHlUffLXMfR:b-z71z67) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool/src/mempool_test.rs#L711)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

add TODO to use regular conversion once we have a compiler component
</blockquote></details>

Done
But what does a compiler component have to do with this conversion?
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 741 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCghAZoDjMJGohYmU91:-OCn87ZjBPJQJp4103mH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool/src/mempool_test.rs#L741)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to propagator_args
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p_types/src/communication.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-OCghKtx4wO2F3jqWRBO:-OD6L-W_6QaWdsPNO0J-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38730f63ae7daf270599fb65d44611f36daae084/crates/starknet_mempool_p2p_types/src/communication.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Activate this only in feature testing and cfg test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-05 09:31 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2288#-:-ODL9FVk5MGq_k8RHUW5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)



<!-- Sent from Reviewable.io -->

2024-12-05 09:40 UTC, merged