Revert "chore(ci): increase max length of commit message from 50 to 7…
starkware-libs/sequencer pull request #2290
Opened 2024-11-26 14:47 UTC by giladchase

…2 inclusive"

This reverts commit e00252156bbe4e4d718eec3b46e677fee789ac6a.

2024-11-26 14:48 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2290)
<!-- Reviewable:end -->

2024-11-27 08:52 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2290#-:-OCgoexK4dSuK783A1QC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-12-01 08:50 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2290)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2290#-OD0PPDYBXFgPsUE89VH:-OD0PPDZ5hpVDIuQg5-t:b-hn0o2w) (no related file):*
covered by [this](https://reviewable.io/reviews/starkware-libs/sequencer/2315) iiuc


<!-- Sent from Reviewable.io -->

2024-12-01 09:07 UTC, giladchase reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2290)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-12-01 10:21 UTC, closed without merging