feat(consensus): validate streamed proposals
starkware-libs/sequencer pull request #2305
Opened 2024-11-27 12:03 UTC by guy-starkware

This PR adds the ability of the Consensus/Context to accept streamed proposals and validate them.

2024-11-27 12:03 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2305)
<!-- Reviewable:end -->

2024-12-01 10:41 UTC, matan-starkware requested changes
> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2305)* status: 11 of 19 files reviewed, 17 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 237 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0nlW02NTjiDiw8mi2:-OD0nlW02NTjiDiw8mi3:b-ptjvj) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L237)):*
> ```XML
>     // Receive a valid proposal.
>     let (mut content_sender, content_receiver) = mpsc::channel(CHANNEL_SIZE);
>     let txs = vec![generate_invoke_tx(Felt::TWO)]
> ```

Just change the return type of this



_Code quote:_
```XML
generate_invoke_tx
```
___
*[`crates/sequencing/papyrus_consensus/src/test_utils.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0jVDr8mHsz15_qtWh:-OD0jVDr8mHsz15_qtWi:b-elkdf0) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus/src/test_utils.rs#L33)):*
> ```XML
>     fn try_from(part: MockProposalPart) -> Result<Self, Self::Error> {
>         Ok(ProposalInit {
>             height: BlockNumber(part.0 as u64),
> ```

Or redefine the type as u8



_Suggestion:_
```XML
            height: BlockNumber(part.0)
```
___
*[`crates/sequencing/papyrus_consensus/src/test_utils.rs` line 129 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0jhk93NRvIoqUGAB-:-OD0jhk93NRvIoqUGAB0:bqpig57) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus/src/test_utils.rs#L129)):*
> ```XML
> pub fn proposal_fin(block_felt: Felt) -> ProposalFin {
>     ProposalFin { proposal_content_id: BlockHash(block_felt) }
> }
> ```

Not enough boilerplate saved to be worth it.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0iE0a5Uwg43kiEvf2:-OD0iE0a5Uwg43kiEvf3:b-a7rf5v) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L73)):*
> ```XML
>     content_sender.send(MockProposalPart(1)).await.unwrap();
>     // let (fin_sender, fin_receiver) = oneshot::channel();
>     // fin_sender.send(BLOCK.id).unwrap();
> ```

should this be uncommented?



_Code quote:_
```XML
    // let (fin_sender, fin_receiver) = oneshot::channel();
    // fin_sender.send(BLOCK.id).unwrap();
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0iGJBBJZ-S2dlxib9:-OD0iGJBBJZ-S2dlxibA:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L79)):*
> ```XML
>         PROPOSAL_INIT.clone(),
>         content_receiver, /* Note: we are only sending the fin, there's no actual content.
>                            * mpsc::channel(1).1, // content - ignored by SHC. */
> ```





_Suggestion:_
```XML
        content_receiver
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 190 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0klu43Qq91yOof6rH:-OD0klu43Qq91yOof6rI:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L190)):*
> ```XML
>                             panic!("Did not receive a Fin message");
>                         }
>                     }
> ```





_Suggestion:_
```XML
                    match content.next().await {
                        Some(ProposalPart::Transactions(batch)) => {
                            for tx in batch.transactions {
                                content_transactions.push(tx);
                            }
                        }
                        Some(ProposalPart::Fin(fin)) => {
                            break fin.proposal_content_id;
                        }
                        msg @ _ => panic!("unexpected message: {msg:?}"),
                    }
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 194 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0lPh4E7SCbdgoMaOJ:-OD0lPh4E7SCbdgoMaOK:bvlgmu2) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L194)):*
> ```XML
> 
>                 // Check each transaction matches the transactions in the storage.
>                 for tx in transactions.iter().rev() {
> ```

Why reverse?



_Code quote:_
```XML
                for tx in transactions.iter().rev() {
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 201 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0lE1e2jdoyJa_9dWs:-OD0lE1e2jdoyJa_9dWt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L201)):*
> ```XML
>                         panic!("Transactions are not equal. In storage: {tx:?}, : {received_tx:?}");
>                     }
>                 }
> ```





_Suggestion:_
```XML
                for tx in transactions.iter().rev() {
                    let received_tx = content_transactions
                        .pop()
                        .expect("Received less transactions than expected");
                    if tx != &received_tx {
                        panic!("Transactions are not equal. In storage: {tx:?}, : {received_tx:?}");
                    }
                }
                assert!(
                    content_transactions.is_empty(),
                    "Received more transactions than expected"
                );
```
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0exAt03XZyjSbAj9t:-OD0exAt03XZyjSbAj9u:b-aqniq6) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus/src/manager_test.rs#L106)):*
> ```XML
>     proposal_receiver_sender.send(proposal_receiver).await.unwrap();
>     proposal_sender.send(ProposalPart::Init(proposal_init(1, 0, *PROPOSER_ID))).await.unwrap();
>     proposal_sender.send(ProposalPart::Fin(proposal_fin(Felt::ONE))).await.unwrap();
> ```

Can we move this implementation to when we actually support this? This test is ignored so this is useless here



_Code quote:_
```XML
    let (mut proposal_sender, proposal_receiver) = mpsc::channel(CHANNEL_SIZE);
    proposal_receiver_sender.send(proposal_receiver).await.unwrap();
    proposal_sender.send(ProposalPart::Init(proposal_init(2, 0, *PROPOSER_ID))).await.unwrap();
    proposal_sender.send(ProposalPart::Fin(proposal_fin(Felt::TWO))).await.unwrap();
    send(&mut sender, prevote(Some(Felt::TWO), 2, 0, *PROPOSER_ID)).await;
    send(&mut sender, precommit(Some(Felt::TWO), 2, 0, *PROPOSER_ID)).await;

    let (mut proposal_sender, proposal_receiver) = mpsc::channel(CHANNEL_SIZE);
    proposal_receiver_sender.send(proposal_receiver).await.unwrap();
    proposal_sender.send(ProposalPart::Init(proposal_init(1, 0, *PROPOSER_ID))).await.unwrap();
    proposal_sender.send(ProposalPart::Fin(proposal_fin(Felt::ONE))).await.unwrap();
```
___ [...]

2024-12-02 16:43 UTC, matan-starkware requested changes
> Reviewed 4 of 19 files at r8, 3 of 15 files at r9, 3 of 12 files at r10, 12 of 12 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2305)* status: 7 of 19 files reviewed, 15 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0cpD52y1vuISmretr:-OD6x6JV0LfceThatQHg:b-32ch1d) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus/src/manager.rs#L147)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Do you want me to do anything in this PR? maybe update the TODO item?
</blockquote></details>

Sure add a TODO to have a timeout and panic if not since that means streaming isn't working properly.

Can you just confirm for me that Streaming only sends this receiver once it has the first message in the stream, not just any message in the stream (out of order)?
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 34 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD72r2w7FUAV1bo7mWY:-OD72r2w7FUAV1bo7mWZ:b-3ooypo) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L34)):*
> ```XML
>     static ref VALIDATE_PROPOSAL_EVENT: ShcEvent = ShcEvent::ValidateProposal(
>         StateMachineEvent::Proposal(Some(BLOCK.id), PROPOSAL_INIT.round, PROPOSAL_INIT.valid_round,),
>         Some(ProposalFin { proposal_content_id: BLOCK.id }),
> ```

can you define PROPOSAL_FIN in the statics section? (use Here and below)



_Code quote:_
```XML
ProposalFin { proposal_content_id: BLOCK.id })
```
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 94 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD6xRfl3dzvVGhpffVs:-OD6xRfl3dzvVGhpffVt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c5bcd2a76493557d9592c9e15f59493caee530ea/crates/sequencing/papyrus_consensus/src/manager_test.rs#L94)):*
> ```XML
> }
> 
> async fn proposal_send(
> ```





_Suggestion:_
```XML
async fn send_proposal(
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 307 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD7CE1l0L8hDkcJK5nU:-OD7CE1l0L8hDkcJK5nV:bcpl9jb) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L307)):*
> ```XML
>         mock_register_broadcast_topic().expect("Failed to create mock network");
>     let BroadcastTopicChannels { broadcasted_messages_receiver: _, broadcast_topic_client } =
>         subscriber_channels;
> ```

Unused now I think. Remove here and throughout the file.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 337 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD7E8ac5hfU-cu8EShB:-OD7E8ad0EGCMnHuFUZI:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L337)):*
> ```XML
>         context.validate_proposal(BlockNumber(0), 0, TIMEOUT, content_receiver).await;
>     content_sender.close_channel();
>     assert!(fin_receiver_past_round.await.is_err());
> ```





_Suggestion:_
```XML
    // Proposal parts sent in the proposals.
    let prop_part_txs = ProposalPart::Transactions(TransactionBatch {
        transactions: TX_BATCH.clone().into_iter().map(Transaction::from).collect(),
        tx_hashes: vec![TX_BATCH[0].tx_hash()],
    });
    let prop_part_fin = ProposalPart::Fin(ProposalFin {
        proposal_content_id: BlockHash(STATE_DIFF_COMMITMENT.0.0),
    });

    // The proposal from the past round is ignored.
    let (mut content_sender, content_receiver) = mpsc::channel(CHANNEL_SIZE);
    content_sender.send(prop_part_txs.clone()).await.unwrap();
    let fin_receiver_past_round =
        context.validate_proposal(BlockNumber(0), 0, TIMEOUT, content_receiver).await;
    // Not fin sent and the channel remains open.
    assert!(fin_receiver_past_round.await.is_err());
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 354 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD7EChY7vhA6y0jHzfR:-OD7EChY7vhA6y0jHzfS:b1uhb71) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L354)):*
> ```XML
>         context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver).await;
>     content_sender.close_channel();
>     assert_eq!(fin_receiver_curr_round.await.unwrap().0.0, STATE_DIFF_COMMITMENT.0.0);
> ```

The need for the fin was caught by the `loop break` change I suggest above.



_Suggestion:_
```XML
    // The proposal from the current round should be validated.
    let (mut content_sender, content_receiver) = mpsc::channel(CHANNEL_SIZE);
    content_sender.send(prop_part_txs.clone()).await.unwrap();
    content_sender.send(prop_part_fin.clone()).await.unwrap();
    let fin_receiver_curr_round =
        context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver).await;
    assert_eq!(fin_receiver_curr_round.await.unwrap().0.0, STATE_DIFF_COMMITMENT.0.0);
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 371 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD7ELMyB1PuIrZfKD7x:-OD7ELMyB1PuIrZfKD7y:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L371)):*
> ```XML
>         context.validate_proposal(BlockNumber(0), 2, TIMEOUT, content_receiver).await;
>     content_sender.close_channel();
>     assert!(fin_receiver_future_round.now_or_never().is_none());
> ```





_Suggestion:_
```XML
    // The proposal from the future round should not be processed.
    let (mut content_sender, content_receiver) = mpsc::channel(CHANNEL_SIZE);
    content_sender.send(prop_part_txs).await.unwrap();
    content_sender.send(prop_part_fin).await.unwrap();
    let fin_receiver_future_round =
        context.validate_proposal(BlockNumber(0), 2, TIMEOUT, content_receiver).await;
    content_sender.close_channel();
    // Even with sending fin and closing the channel.
    assert!(fin_receiver_future_round.now_or_never().is_none());
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 454 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD7F8oz7Ssg_MkJue8w:-OD7F8oz7Ssg_MkJue8x:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L454)):*
> ```XML
>     content_sender_1.close_channel();
>     // Move the context to the next round.
>     context.set_height_and_round(BlockNumber(0), 1).await;
> ```





_Suggestion:_
```XML
    let (mut content_sender_1, content_receiver) = mpsc::channel(CHANNEL_SIZE);
    content_sender_1
        .send(ProposalPart::Transactions(TransactionBatch {
            transactions: TX_BATCH.clone().into_iter().map(Transaction::from).collect(),
            tx_hashes: vec![TX_BATCH[0].tx_hash()],
        }))
        .await
        .unwrap();
    content_sender_1
        .send(ProposalPart::Fin(ProposalFin {
            proposal_content_id: BlockHash(STATE_D [...]

2024-12-02 22:10 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2305)* status: 7 of 19 files reviewed, 15 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0cpD52y1vuISmretr:-OD7xLjm1Lbf2RmayNV-:b-qltnsf) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus/src/manager.rs#L147)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Sure add a TODO to have a timeout and panic if not since that means streaming isn't working properly.

Can you just confirm for me that Streaming only sends this receiver once it has the first message in the stream, not just any message in the stream (out of order)?
</blockquote></details>

Added a TODO. 

It must be a message with id=0, but it isn't enforced by StreamHandler that it must be an Init (the content is not exposed to StreamHandler). 
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 34 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD72r2w7FUAV1bo7mWY:-OD8Gjfh7ZH-1-0IY28d:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L34)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

can you define PROPOSAL_FIN in the statics section? (use Here and below)
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 198 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD73IGp-QK6WGw9e-PX:-OD8GomI912IMMK-uU6k:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L198)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 242 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD74MyKEx-ukC81EWbB:-OD8H83b4PY6LyW9FXZI:bt8hi8s) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L242)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Now that we have streaming I think I'd like to remove the ProposalInit and ProposalFin definitions in the consensus crate and use the one in the proto crate. Can you help me remember this?
</blockquote></details>

I'm not sure what you mean. As far as I know, there is only the protobuf crate definitions. Maybe I need to look more... 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 75 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD74lUkCLb5RgZvXFCa:-OD8HH2YABbc9N-mtJ5r:b99tsh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L75)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why not remove this?
</blockquote></details>

The plan is to remove the old plumbing in another PR (same way as I added the plumbing with nothing attached). 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 517 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD774zDB12x-3BZcSEw:-OD8HVzf6zOlb0BcIXiv:bcl4z81) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L517)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I realized we actually want to use a loop to enforce we are returning. With the while loop we were silently continuing if the receiver simply finished in the middle. Now we exit early.
</blockquote></details>

Yeah, I was getting bad vibes from this loop, but wasn't sure what the expected behavior should be. 
Let's try it this way. 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 549 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD78-z3EjxpMOxbBNbb:-OD8JFO40zPrCSremZ6G:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L549)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I initially planned to do this in consensus, but may be better here since we are adding this to our state.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 307 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD7CE1l0L8hDkcJK5nU:-OD8JUE2AlElxcInXb7R:baruuw2) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L307)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Unused now I think. Remove here and throughout the file.
</blockquote></details>

I think this will have to go on another PR when I take out these channels. 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 354 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD7EChY7vhA6y0jHzfR:-OD8Kl0t3Lx9sysSyJYB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L354)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

The need for the fin was caught by the `loop break` change I suggest above.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 534 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD77j2B94U0f8GHfJ43:-OD8J7K8BbQhTiBH4R2_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L534)):*
> ```XML
>             warn!("Proposal was invalid: {:?}", proposal_id);
>             return;
>         }
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 94 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD6xRfl3dzvVGhpffVs:-OD7xjdA7neXvTx2ebgg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c5bcd2a76493557d9592c9e15f59493caee530ea/crates/sequencing/papyrus_consensus/src/manager_test.rs#L94)):*
> ```XML
> }
> 
> async fn proposal_send(
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 207 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD73RBe6NTj_bnhKdH1:-OD8Gsbb8aB84eyhiCPZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L207)):*
> ```XML
>                             break fin.proposal_content_id;
>                         }
>                         mxs @ _ => panic!("Unexpected message: {mxs:?}"),
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/ [...]

2024-12-03 08:06 UTC, matan-starkware requested changes
> Reviewed 12 of 12 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2305)* status: all files reviewed, 7 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD0cpD52y1vuISmretr:-ODAUoGn0SrgavOb0WM1:bhprgdp) ([raw file](https://github.com/starkware-libs/sequencer/blob/f515d0cd314c4d72dd1d74cbc3d25306cfea1618/crates/sequencing/papyrus_consensus/src/manager.rs#L147)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Added a TODO. 

It must be a message with id=0, but it isn't enforced by StreamHandler that it must be an Init (the content is not exposed to StreamHandler).
</blockquote></details>

Great, that's my understanding.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 34 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD72r2w7FUAV1bo7mWY:-ODAVTtE571Fpf56Rl0j:b-s5okn1) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L34)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you remove the derive?
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 242 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD74MyKEx-ukC81EWbB:-ODAVekY3Jj6G7YegC0C:b33lt7k) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L242)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

I'm not sure what you mean. As far as I know, there is only the protobuf crate definitions. Maybe I need to look more...
</blockquote></details>

I think you are correct and I misread my screen
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 534 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD77j2B94U0f8GHfJ43:-ODAWXWt1WsTUBrThNNv:b-8byt1d) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L534)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Good realization we don't need the name binding `@`
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 269 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-ODAYZI44gT-Hvrm9aYd:-ODAYZI56zLxjwcCqB9y:b-hqk6hk) ([raw file](https://github.com/starkware-libs/sequencer/blob/568a63bcc8a2e36a5a4fff127ac2c2c99c366308/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L269)):*
> ```XML
>         proposal_content_id: BlockHash(STATE_DIFF_COMMITMENT.0.0),
>     });
>     content_sender.send(prop_part).await.unwrap();
> ```

Inline, since only used once



_Code quote:_
```XML
    let prop_part = ProposalPart::Fin(ProposalFin {
        proposal_content_id: BlockHash(STATE_DIFF_COMMITMENT.0.0),
    });
    content_sender.send(prop_part).await.unwrap();
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 363 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-ODAYRmLA62pf64TyVX5:-ODAYRmLA62pf64TyVX6:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/568a63bcc8a2e36a5a4fff127ac2c2c99c366308/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L363)):*
> ```XML
>         context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver).await;
> 
>     assert_eq!(fin_receiver_curr_round.await.unwrap().0.0, STATE_DIFF_COMMITMENT.0.0);
> ```





_Suggestion:_
```XML
    let fin_receiver_curr_round =
        context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver).await;
    assert_eq!(fin_receiver_curr_round.await.unwrap().0.0, STATE_DIFF_COMMITMENT.0.0);
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 480 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-ODAVt9e92lTHg0wGu1Z:-ODAVt9e92lTHg0wGu1_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/568a63bcc8a2e36a5a4fff127ac2c2c99c366308/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L480)):*
> ```XML
>         let Some(prop_part) = content_receiver.next().await else {
>             warn!("Failed to receive proposal content: {proposal_id:?}");
>             return;
> ```





_Suggestion:_
```XML
            // TODO(Asmaa): Tell the batcher to abort.
            warn!("Failed to receive proposal content: {proposal_id:?}");
            return;
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 146 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-ODAUdedAvzkieFpY9KG:-ODAUdedAvzkieFpY9KH:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/568a63bcc8a2e36a5a4fff127ac2c2c99c366308/crates/sequencing/papyrus_consensus/src/manager.rs#L146)):*
> ```XML
>                     // Get the first message to verify the init was sent.
>                     // TODO(guyn): add a timeout and panic if nothing comes from StreamHandler
>                     // (if it isn't sending things, that means something is wrong).
> ```





_Suggestion:_
```XML
                    // TODO(guyn): add a timeout and panic, since StreamHandler should only send once
                    // the first message (message_id=0) has arrived.
```


<!-- Sent from Reviewable.io -->

2024-12-03 08:16 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2305)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 34 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD72r2w7FUAV1bo7mWY:-ODAZmeE3PppE00ePODZ:bxyleru) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L34)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can you remove the derive?
</blockquote></details>

Yes, it seems like I can. Weird, it didn't compile without it earlier... 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 534 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-OD77j2B94U0f8GHfJ43:-ODAZFYB9XWspoNWMokh:bi6uzll) ([raw file](https://github.com/starkware-libs/sequencer/blob/61f236ffa24fc35788dfc15e880f66589546968f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L534)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Good realization we don't need the name binding `@`
</blockquote></details>

That's code style CI that caught it :)
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 363 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2305#-ODAYRmLA62pf64TyVX5:-ODAZX5tDdskml14Ksui:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/568a63bcc8a2e36a5a4fff127ac2c2c99c366308/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L363)):*
> ```XML
>         context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver).await;
> 
>     assert_eq!(fin_receiver_curr_round.await.unwrap().0.0, STATE_DIFF_COMMITMENT.0.0);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-03 09:28 UTC, matan-starkware reviewed
> Reviewed 12 of 12 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2305)* status: all files reviewed, 2 unresolved discussions (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2024-12-03 09:29 UTC, matan-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2305)* status: all files reviewed, 2 unresolved discussions (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2024-12-03 09:32 UTC, merged