feat(starknet_api): add sierra version to class info
starkware-libs/sequencer pull request #2313
Opened 2024-11-27 15:31 UTC by AvivYossef-starkware

2024-11-27 15:31 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2313)
<!-- Reviewable:end -->

2024-11-27 15:31 UTC, AvivYossef-starkware commented
* **#2313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2313?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2313?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-28 09:23 UTC, Yoni-Starkware reviewed
@AvivYossef-starkware note that you need to change python's declare tx as well

> Reviewed 4 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-:-OCm4ER90vQbY0bFMAHt:b-e9ti3c)* status: 3 of 13 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-11-28 09:35 UTC, dorimedini-starkware requested changes
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 15 unresolved discussions (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm6sBWBwiQ0mirKTrB:-OCm6sBWBwiQ0mirKTrC:b276fh0) (no related file):*
1. please add reviewers from relevant teams (papyrus + gateway)
2. please open py side PR to check for breaking changes
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 353 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm3Nv2EfT3EI_9UAVt:-OCm3Nv2EfT3EI_9UAVu:balivmi) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/blockifier/src/transaction/test_utils.rs#L353)):*
> ```XML
>     let (sierra_program_length, sierra_version) = match contract_class {
>         ContractClass::V0(_) => (0, SierraVersion::zero()),
>         ContractClass::V1(_) => (100, SierraVersion::new(2, 8, 4)),
> ```

move these magic numbers to the struct impl.
that way we can later make it smarter (by checking the latest available compiler version)



_Suggestion:_
```XML
SierraVersion::latest()
```
___
*[`crates/papyrus_rpc/src/v0_8/api/mod.rs` line 471 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4TEa6N7a6EOvbl4O:-OCm4TEa6N7a6EOvbl4P:b-mnlw6u) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_rpc/src/v0_8/api/mod.rs#L471)):*
> ```XML
>             internal_server_error(format!("Missing deprecated class definition of {class_hash}."))
>         })
>         .and_then(|contract_class| {
> ```

what's this? why not `map`?



_Code quote:_
```XML
and_then
```
___
*[`crates/papyrus_rpc/src/v0_8/api/mod.rs` line 475 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4_cm2mgYw0-azHJU:-OCm4_cm2mgYw0-azHJV:bczxjbk) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_rpc/src/v0_8/api/mod.rs#L475)):*
> ```XML
>             let abi_len = contract_class.abi.len();
>             let sierra_program =
>                 (&contract_class.sierra_program).try_into().map_err(internal_server_error)?;
> ```

use `extract_from_program` explicitly



_Code quote:_
```XML
(&contract_class.sierra_program).try_into()
```
___
*[`crates/starknet_api/src/contract_class.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4geSCQVsn0Y8l6H8:-OCm4geSCQVsn0Y8l6H9:b-piqn4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_api/src/contract_class.rs#L67)):*
> ```XML
> impl Default for SierraVersion {
>     fn default() -> Self {
>         Self::new(1, 0, 0)
> ```

no, use `latest()`



_Code quote:_
```XML
Self::new(1, 0, 0)
```
___
*[`crates/starknet_api/src/contract_class.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4nPgAp4xbuZJ6x52:-OCm4nPgAp4xbuZJ6x53:b-lrvooy) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_api/src/contract_class.rs#L82)):*
> ```XML
> }
> 
> impl TryFrom<&Vec<Felt>> for SierraVersion {
> ```

`From` and `TryFrom` consume the input by convension; implement an `extract_from_program` method instead



_Code quote:_
```XML
impl TryFrom<&Vec<Felt>> for SierraVersion {
```
___
*[`crates/starknet_api/src/contract_class.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm51454-ciyQOdBAXX:-OCm51454-ciyQOdBAXY:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_api/src/contract_class.rs#L94)):*
> ```XML
> 
>         // Closure to map a Felt error to a StarknetApiError.
>         let map_felt_to_api_error = |(felt, index): (Felt, usize)| {
> ```





_Suggestion:_
```XML
|felt: Felt, index: usize| {
```
___
*[`crates/starknet_api/src/contract_class.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm5LJp3u33hoM-PdRW:-OCm5LJp3u33hoM-PdRX:byyamvx) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_api/src/contract_class.rs#L109)):*
> ```XML
>             sierra_program[1].try_into().map_err(map_felt_to_api_error((sierra_program[1], 1)))?;
>         let patch =
>             sierra_program[2].try_into().map_err(map_felt_to_api_error((sierra_program[2], 2)))?;
> ```

does this work? (non-blocking)
if it does, please delete map_felt_to_api_error and just inline the logic



_Suggestion:_
```XML
        let (major, minor, patch): [u64; 3] = [0, 1, 2]
            .iter()
            .map(|i| {
                sierra_program[i].try_into().map_err(map_felt_to_api_error((sierra_program[0], 0)))
            })
            .collect::<Result<_, _>>()
```
___
*[`crates/papyrus_execution/src/lib.rs` line 827 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm49K50F1lZK6RHCdI:-OCm49K50F1lZK6RHCdJ:b-krsqec) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_execution/src/lib.rs#L827)):*
> ```XML
>                 DEPRECATED_CONTRACT_SIERRA_SIZE,
>                 abi_length,
>                 SierraVersion::zero(),
> ```

same Q



_Code quote:_
```XML
SierraVersion::zero(),
```
___
*[`crates/papyrus_execution/src/lib.rs` line 854 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4CDC0w1Gz544EOcE:-OCm4CDC0w1Gz544EOcF:b-krsqec) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_execution/src/lib.rs#L854)):*
> ```XML
>                 DEPRECATED_CONTRACT_SIERRA_SIZE,
>                 abi_length,
>                 SierraVersion::zero(),
> ```

same Q



_Code quote:_
```XML
SierraVersion::zero(),
```
___
*[`crates/starknet_gateway/src/compilation.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm6nFh1hpNUdozXGrP:-OCm6nFh1hpNUdozXGrQ:b-vy6js8) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_gateway/src/compilation.rs#L45)):*
> ```XML
> 
>         let sierra_version: SierraVersion = (&rpc_contract_class.sierra_program)
>             .try_into()
> ```

use explicit conversion, see above



_Code quote:_
```XML
.try_into()
```
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm3aAw449nKXTk0lan:-OCm3aAw449nKXTk0lao:b46gkhd) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L30)):*
> ```XML
>                     sierra.sierra_program[2].try_into().unwrap(),
>                 );
>                 let sierra_version: SierraVersion = SierraVersion::new(major, minor, path);
> ```

move this logic to the struct impl



_Suggestion:_
```XML
                let sierra_version = SierraVersion::extract_from_program(sierra.sierra_program);
```
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm3raU8CYkOqrOoEx6:-OCm3raU8CYkOqrOoEx7:bx9qxh7) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L41)):*
> ```XML
>             StarknetContractClass::Legacy(legacy) => {
>                 let abi_length =
>                     legacy.abi.clone().expect("legendary contract should have abi").len();
> ```

lolololol



_Code quote:_
```XML
lege [...]

2024-11-28 14:02 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: 6 of 14 files reviewed, 15 unresolved discussions (waiting on @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 353 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm3Nv2EfT3EI_9UAVt:-OCmgJ_R2JDSWUQa22mc:b-edmhh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/blockifier/src/transaction/test_utils.rs#L353)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move these magic numbers to the struct impl.
that way we can later make it smarter (by checking the latest available compiler version)
</blockquote></details>

How should I maintain this function?
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm3aAw449nKXTk0lan:-OCmrBpqExC-tr6iRwrB:b-h3p1ba) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L30)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move this logic to the struct impl
</blockquote></details>

Done, see below about the function name
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm3raU8CYkOqrOoEx6:-OCmrLYw51gSLnFdErDN:b32vhw) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

lolololol
</blockquote></details>

:)
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm3w88DmRs9SzEVBUv:-OCmrStO9O_dfmphweXM:bb7s9zy) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Legacy contract is cairo0?
</blockquote></details>

yes 
___
*[`crates/papyrus_execution/src/lib.rs` line 827 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm49K50F1lZK6RHCdI:-OCmrz4IEFpAYnRPj7v3:bb77uf2) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_execution/src/lib.rs#L827)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same Q
</blockquote></details>

Yes 
___
*[`crates/papyrus_execution/src/lib.rs` line 854 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4CDC0w1Gz544EOcE:-OCms01zEg6GJiHbq2-F:bu85qab) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_execution/src/lib.rs#L854)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same Q
</blockquote></details>

Yes
V0 , V1 its cairo 0 
___
*[`crates/papyrus_execution/src/test_utils.rs` line 316 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4Hg41u4C1Ino-53-:-OCmsS705_JggRlu8Fxg:b-84a2if) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_execution/src/test_utils.rs#L316)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what is the default?
I think it should be equal to `latest()` (see above)
</blockquote></details>

Done ( but see above )
___
*[`crates/papyrus_rpc/src/v0_8/api/mod.rs` line 471 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4TEa6N7a6EOvbl4O:-OCmuEy32vFxGNou8o_S:b-bepcul) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_rpc/src/v0_8/api/mod.rs#L471)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this? why not `map`?
</blockquote></details>

It's similar to map, but If you use `map` instead, the `try_into` call would result in a type mismatch because `map` does not expect the closure to return a `Result.` 
___
*[`crates/papyrus_rpc/src/v0_8/api/mod.rs` line 475 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4_cm2mgYw0-azHJU:-OCmv52k8qLno1wyYNJV:b-jg41c7) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_rpc/src/v0_8/api/mod.rs#L475)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `extract_from_program` explicitly
</blockquote></details>

Why?
Would it be clearer if we used try from and specified the type?
___
*[`crates/starknet_api/src/contract_class.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4geSCQVsn0Y8l6H8:-OCmvYmt1iFRzVNHKP9K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_api/src/contract_class.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, use `latest()`
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/contract_class.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4nPgAp4xbuZJ6x52:-OCmvsiGBtSTMMu4yj4i:bkt7kgf) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_api/src/contract_class.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`From` and `TryFrom` consume the input by convension; implement an `extract_from_program` method instead
</blockquote></details>

but I implemented it as a reference, so it does not consume the actual input. Just clone the first three fields.
___
*[`crates/starknet_api/src/contract_class.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm5LJp3u33hoM-PdRW:-OCn185_6d81hdoUVOQA:b-zcvx68) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_api/src/contract_class.rs#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work? (non-blocking)
if it does, please delete map_felt_to_api_error and just inline the logic
</blockquote></details>

refactored fit to something rustier 
___
*[`crates/starknet_gateway/src/compilation.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm6nFh1hpNUdozXGrP:-OCn444f7xFGRh1zmQkW:bbw4h1x) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_gateway/src/compilation.rs#L45)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use explicit conversion, see above
</blockquote></details>

see above 
___
*[`crates/starknet_api/src/contract_class.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm51454-ciyQOdBAXX:-OCn0iFE924rUe-2FEC4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_api/src/contract_class.rs#L94)):*
> ```XML
> 
>         // Closure to map a Felt error to a StarknetApiError.
>         let map_felt_to_api_error = |(felt, index): (Felt, usize)| {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-28 14:07 UTC, dorimedini-starkware requested changes
> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 6 unresolved discussions (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 353 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm3Nv2EfT3EI_9UAVt:-OCn4sVOAmI3wqBHOKEm:b-spsd4i) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/blockifier/src/transaction/test_utils.rs#L353)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

How should I maintain this function?
</blockquote></details>

we need to discuss it, but it's out of scope ATM.
We can use existing infrastructure to read the current version of the compiler crates in the root cargo.toml, in write a test that `latest()` returns this version.
___
*[`crates/papyrus_rpc/src/v0_8/api/mod.rs` line 475 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4_cm2mgYw0-azHJU:-OCn4PWX7ppdmbqdP9nD:bc3ha5y) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_rpc/src/v0_8/api/mod.rs#L475)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Why?
Would it be clearer if we used try from and specified the type?
</blockquote></details>

no, try_from is usually consuming. you are not converting (consuming), you are computing a value from another value
___
*[`crates/starknet_api/src/contract_class.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4nPgAp4xbuZJ6x52:-OCn4Z035CKe-gckqewn:b-sg4ah6) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_api/src/contract_class.rs#L82)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

but I implemented it as a reference, so it does not consume the actual input. Just clone the first three fields.
</blockquote></details>

yes it compiles it's just not convension. from/into are conversions (consuming), not computations
___
*[`crates/starknet_gateway/src/compilation.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm6nFh1hpNUdozXGrP:-OCn4p0Y9n6qpvejW5ab:b-jel8rq) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_gateway/src/compilation.rs#L45)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

still relevant
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCn44UmEivVYTxkXMTg:-OCn44UmEivVYTxkXMTh:b-v8c7f1) ([raw file](https://github.com/starkware-libs/sequencer/blob/afdb57cb63079d4589c1599b9df8e04596ffb090/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L26)):*
> ```XML
>                 let sierra_length = sierra.sierra_program.len();
> 
>                 let sierra_version = SierraVersion::try_from(&sierra.sierra_program)?;
> ```

try_from is consuming by convension, iiuc.
don't implement TryFrom, implement an explicit method (discussed more in below comments)



_Code quote:_
```XML
SierraVersion::try_from(&sierra.sierra_program)?
```
___
*[`crates/starknet_api/src/contract_class.rs` line 90 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCn5FVL7ZTQQQkKOmBh:-OCn5FVL7ZTQQQkKOmBi:btyeg8f) ([raw file](https://github.com/starkware-libs/sequencer/blob/4057743fcfc6c14469becef0f350a6b4cbb7977f/crates/starknet_api/src/contract_class.rs#L90)):*
> ```XML
> /// The first 3 felts are the major, minor and patch version.
> /// The rest of the felts are ignored.
> /// Generic since there are multiple types of felts.
> ```

what?? we should only have a single felt type in the repo
what breaks if you only accept the starknet_types_core felt?



_Code quote:_
```XML
Generic since there are multiple types of felts.
```


<!-- Sent from Reviewable.io -->

2024-11-28 17:34 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: 6 of 14 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 353 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm3Nv2EfT3EI_9UAVt:-OCnh5bc6lz-KaQjrO0G:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/blockifier/src/transaction/test_utils.rs#L353)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we need to discuss it, but it's out of scope ATM.
We can use existing infrastructure to read the current version of the compiler crates in the root cargo.toml, in write a test that `latest()` returns this version.
</blockquote></details>

Done
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCn44UmEivVYTxkXMTg:-OCnh4X648OdzEoNMzSA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/afdb57cb63079d4589c1599b9df8e04596ffb090/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L26)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

try_from is consuming by convension, iiuc.
don't implement TryFrom, implement an explicit method (discussed more in below comments)
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_8/api/mod.rs` line 475 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4_cm2mgYw0-azHJU:-OCnh-clB_0oyv_1BjVP:b-w0yspw) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/papyrus_rpc/src/v0_8/api/mod.rs#L475)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, try_from is usually consuming. you are not converting (consuming), you are computing a value from another value
</blockquote></details>

got it 
___
*[`crates/starknet_api/src/contract_class.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm4nPgAp4xbuZJ6x52:-OCnlNX98c94TQ4Xw69L:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_api/src/contract_class.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes it compiles it's just not convension. from/into are conversions (consuming), not computations
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/contract_class.rs` line 90 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCn5FVL7ZTQQQkKOmBh:-OCnh7om-GwMDoE_nyEd:b8g7n8p) ([raw file](https://github.com/starkware-libs/sequencer/blob/4057743fcfc6c14469becef0f350a6b4cbb7977f/crates/starknet_api/src/contract_class.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what?? we should only have a single felt type in the repo
what breaks if you only accept the starknet_types_core felt?
</blockquote></details>

It's not from our repository. In the re-execution, we use a different crate to compile the Sierra. That crate has a different type of felt.
https://github.com/starkware-libs/sequencer/blob/4057743fcfc6c14469becef0f350a6b4cbb7977f/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L22
___
*[`crates/starknet_gateway/src/compilation.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OCm6nFh1hpNUdozXGrP:-OCnnN_H-QH1mQVtH2Nt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4836cf1a9145e9c9217721359dd35e079c0ac921/crates/starknet_gateway/src/compilation.rs#L45)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

still relevant
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-01 08:35 UTC, dorimedini-starkware requested changes
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @AvivYossef-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/starknet_api/src/contract_class.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD0LAkX3LImXo0reiGz:-OD0LAkX3LImXo0reiH-:b-k6jro1) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb77d077e4fd2e593d0722278e5e10f38597dadc/crates/starknet_api/src/contract_class.rs#L65)):*
> ```XML
> 
>     // TODO(Aviv): Replace hardcoded version with logic to fetch the latest version from the actual
>     // source.
> ```

I think it's ok to hard-code this
just need to write a test that the value is consistent with the toml
please rephrase the TODO



_Code quote:_
```XML
    // TODO(Aviv): Replace hardcoded version with logic to fetch the latest version from the actual
    // source.
```


<!-- Sent from Reviewable.io -->

2024-12-01 11:29 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/starknet_api/src/contract_class.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD0LAkX3LImXo0reiGz:-OD0yrayBKnTBunqtYsm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb77d077e4fd2e593d0722278e5e10f38597dadc/crates/starknet_api/src/contract_class.rs#L65)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it's ok to hard-code this
just need to write a test that the value is consistent with the toml
please rephrase the TODO
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-01 12:32 UTC, alonh5 requested changes
> Reviewed 3 of 13 files at r1, 2 of 8 files at r3, 5 of 8 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/starknet_gateway/src/compilation.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1C4JT4LpmXiKFbVLZ:-OD1C4JU1h1K4eBrgUQC:bnqir3m) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e8942cfdbbebb4b76498ad60b3ad1bb1762306a/crates/starknet_gateway/src/compilation.rs#L46)):*
> ```XML
>         let sierra_version =
>             SierraVersion::extract_from_program(&rpc_contract_class.sierra_program)
>                 .map_err(|_| GatewaySpecError::UnsupportedContractClassVersion)?;
> ```

Can you also create a new error for this in the gateway?


<!-- Sent from Reviewable.io -->

2024-12-01 14:20 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @DvirYo-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-01 14:47 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: 12 of 15 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/starknet_gateway/src/compilation.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1C4JT4LpmXiKFbVLZ:-OD1EhxiC-i1kE8BKcoJ:bb74ce2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e8942cfdbbebb4b76498ad60b3ad1bb1762306a/crates/starknet_gateway/src/compilation.rs#L46)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you also create a new error for this in the gateway?
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2024-12-02 08:06 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/starknet_gateway_types/src/errors.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1xhkF-OeFeWwg9dhs:-OD5OIIy1tNp2uXZH-b1:b7xr1sf) ([raw file](https://github.com/starkware-libs/sequencer/blob/25aefc4c272d39690cab05b1676fc8d1efcf965f/crates/starknet_gateway_types/src/errors.rs#L44)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why "unexpected error"?
do we want to add an error type to the spec? @alonh5
</blockquote></details>

According to the documentation above, it appears that the error should conform to the StarkNet RPC error format, and I couldn't find anything more suitable.


<!-- Sent from Reviewable.io -->

2024-12-02 10:58 UTC, alonh5 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/starknet_gateway/src/compilation.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1C4JT4LpmXiKFbVLZ:-OD6-H3r9-4c5KseCtOW:b9cghw4) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e8942cfdbbebb4b76498ad60b3ad1bb1762306a/crates/starknet_gateway/src/compilation.rs#L46)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Sure
</blockquote></details>

I see this is happening after the compilation. Is it possible that this will fail if the compilation succeeds? Isn't the sierra version used in compilation?
If it isn't possible then you can return an unexpected error, but if it is possible then we should add a new error to the spec and here (I talked to Ariel about it)
___
*[`crates/starknet_gateway_types/src/errors.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1xhkF-OeFeWwg9dhs:-OD6-Etx0gDqUmy39Po9:b-otilcs) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743d0fbe50005ddca51acd8ce8d109e2851f594/crates/starknet_gateway_types/src/errors.rs#L44)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

According to the documentation above, it appears that the error should conform to the StarkNet RPC error format, and I couldn't find anything more suitable.
</blockquote></details>

See comment above.


<!-- Sent from Reviewable.io -->

2024-12-03 08:23 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @AvivYossef-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/starknet_gateway_types/src/errors.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1xhkF-OeFeWwg9dhs:-ODAbQvo3C7DcfUSYzl8:b53maok) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743d0fbe50005ddca51acd8ce8d109e2851f594/crates/starknet_gateway_types/src/errors.rs#L44)):*
comment above says

> Can you also create a new error for this in the gateway?

does this mean adding a new error in the spec? or a new variant to the GatewaySpecError enum?


<!-- Sent from Reviewable.io -->

2024-12-03 08:53 UTC, alonh5 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/starknet_gateway/src/compilation.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1C4JT4LpmXiKFbVLZ:-ODAi7ZU1qmsKXxBhRc9:b-40bad5) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e8942cfdbbebb4b76498ad60b3ad1bb1762306a/crates/starknet_gateway/src/compilation.rs#L46)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

The Sierra version refers to the first three felts in the Sierra program. It may fail (from the Rust compiler's perspective) when attempting to cast the felt into a u64. However, as long as we maintain the convention that the first three positions in the program indicate the version, it should never fail.
</blockquote></details>

What I'm asking is whether it's possible to pass compilation and then fail the Sierra version extraction.
___
*[`crates/starknet_gateway_types/src/errors.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1xhkF-OeFeWwg9dhs:-ODAi-ADEJdwKlOvfwpk:bf2ggdr) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743d0fbe50005ddca51acd8ce8d109e2851f594/crates/starknet_gateway_types/src/errors.rs#L44)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

comment above says

> Can you also create a new error for this in the gateway?

does this mean adding a new error in the spec? or a new variant to the GatewaySpecError enum?
</blockquote></details>

I meant my reply to that comment. I moved the discussion there.


<!-- Sent from Reviewable.io -->

2024-12-03 09:50 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/starknet_gateway/src/compilation.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1C4JT4LpmXiKFbVLZ:-ODAvIUW83aVwP2kG9t4:bwev9iu) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e8942cfdbbebb4b76498ad60b3ad1bb1762306a/crates/starknet_gateway/src/compilation.rs#L46)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What I'm asking is whether it's possible to pass compilation and then fail the Sierra version extraction.
</blockquote></details>

No, unless there is a bug in the compiler.


<!-- Sent from Reviewable.io -->

2024-12-03 09:52 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/starknet_gateway/src/compilation.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1C4JT4LpmXiKFbVLZ:-ODAvaAY3OormqVT9LeJ:boi6gqp) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e8942cfdbbebb4b76498ad60b3ad1bb1762306a/crates/starknet_gateway/src/compilation.rs#L46)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

No, unless there is a bug in the compiler.
</blockquote></details>

Or, the compiler will stop using the first three places of the sierra program to encode the sierra version  


<!-- Sent from Reviewable.io -->

2024-12-03 10:43 UTC, DvirYo-starkware reviewed
> Reviewed 1 of 8 files at r3, 1 of 8 files at r5, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/papyrus_execution/src/lib.rs` line 838 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-ODB36Xo2HgxgoOIRHle:-ODB36Xo2HgxgoOIRHlf:b-4p4boc) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b48bff462917ad6c7c027fd72a946f0820e2a63/crates/papyrus_execution/src/lib.rs#L838)):*
> ```XML
>                 DEPRECATED_CONTRACT_SIERRA_SIZE,
>                 abi_length,
>                 SierraVersion::zero(),
> ```

Not the main thing I review here, but consider using constants instead of functions.
`SierraVersion::ZERO` (I prefer `SierraVersion::DEPRECATED_CLASS_VERSION`)
We do the same for felts (see `Felt::ZERO`)
If you decide to keep the function, you can make it constant
___
*[`crates/papyrus_execution/src/test_utils.rs` line 316 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-ODB3z677aapyvJPHN6l:-ODB3z677aapyvJPHN6m:bjxpmup) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b48bff462917ad6c7c027fd72a946f0820e2a63/crates/papyrus_execution/src/test_utils.rs#L316)):*
> ```XML
>             0,
>             false,
>             SierraVersion::latest(),
> ```

Again consider `SierraVersion::LATEST`
___
*[`crates/papyrus_rpc/src/v0_8/api/mod.rs` line 471 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-ODB5m-M-41RToMBO1cr:-ODB5m-M-41RToMBO1cs:b9eyuj3) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b48bff462917ad6c7c027fd72a946f0820e2a63/crates/papyrus_rpc/src/v0_8/api/mod.rs#L471)):*
> ```XML
>             internal_server_error(format!("Missing deprecated class definition of {class_hash}."))
>         })
>         .and_then(|contract_class| {
> ```

Consider creating the final result outside of the `and_than`


<!-- Sent from Reviewable.io -->

2024-12-03 11:10 UTC, alonh5 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[`crates/starknet_gateway/src/compilation.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1C4JT4LpmXiKFbVLZ:-ODBCOJ_4EYT_-DnJ0yn:biijy08) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e8942cfdbbebb4b76498ad60b3ad1bb1762306a/crates/starknet_gateway/src/compilation.rs#L46)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Or, the compiler will stop using the first three places of the sierra program to encode the sierra version
</blockquote></details>

In that case, you can just return the existing unexpected error, and you can remove this new variant.


<!-- Sent from Reviewable.io -->

2024-12-03 13:28 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/starknet_gateway/src/compilation.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-OD1C4JT4LpmXiKFbVLZ:-ODBdsJYAjrlyKr1nF3Z:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e8942cfdbbebb4b76498ad60b3ad1bb1762306a/crates/starknet_gateway/src/compilation.rs#L46)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In that case, you can just return the existing unexpected error, and you can remove this new variant.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-03 13:32 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @AvivYossef-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-04 08:48 UTC, Yoni-Starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-04 09:28 UTC, alonh5 reviewed
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-04 09:28 UTC, alonh5 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-04 09:32 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2313#-:-ODG-lo69Mmm96bi62TN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-04 09:32 UTC, merged