chore(ci): update commitlint
starkware-libs/sequencer pull request #2315
Opened 2024-11-27 18:02 UTC by Itay-Tsabary-Starkware

2024-11-27 18:02 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2315)
<!-- Reviewable:end -->

2024-11-28 15:23 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2315)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`commitlint.config.js` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2315#-OCnMUj_74JZ2tPXN5ib:-OCnMUj_74JZ2tPXN5ic:brpmnqs) ([raw file](https://github.com/starkware-libs/sequencer/blob/8edd6d76af36f68328d4c5f841e97dcf28c7624f/commitlint.config.js#L46)):*
> ```JavaScript
>             'mempool_p2p',
>             'mempool_p2p_types',
>             'mempool_test_utils',
> ```

where did this go?



_Code quote:_
```JavaScript
'mempool_test_utils',
```


<!-- Sent from Reviewable.io -->

2024-11-28 17:52 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2315)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`commitlint.config.js` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2315#-OCnMUj_74JZ2tPXN5ib:-OCntlCvBqyrsd1SWyLD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8edd6d76af36f68328d4c5f841e97dcf28c7624f/commitlint.config.js#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where did this go?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-01 08:03 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2315#-:-OD0Ecnz08_Z1QbqmuVO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-01 11:10 UTC, merged