chore(infra): add run_until utility fn
starkware-libs/sequencer pull request #2329
Opened 2024-11-28 10:40 UTC by Itay-Tsabary-Starkware

**Stack**:
- #2329 ⬅
- #2328
- #2322

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-11-28 10:40 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2329)
<!-- Reviewable:end -->

2024-12-02 14:07 UTC, lev-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2329)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/infra_utils/src/run_until.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2329#-OD6gK_wCJf398WTV8oL:-OD6gK_wCJf398WTV8oM:bfhdxai) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3b9c092a5b6091dcb10bc286c68febdcc6b0d39/crates/infra_utils/src/run_until.rs#L59)):*
> ```XML
> 
>     if let Some(config) = &logger {
>         let failure_message = format!("Condition not met after {} attempts.", max_attempts);
> ```

Condition not met after the maximum number of {} attempts.



_Code quote:_
```XML
Condition not met after {} attempts.
```


<!-- Sent from Reviewable.io -->

2024-12-03 09:12 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2329)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/infra_utils/src/run_until.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2329#-OD6gK_wCJf398WTV8oL:-ODAmm7b-2MpiVI6Uct8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3b9c092a5b6091dcb10bc286c68febdcc6b0d39/crates/infra_utils/src/run_until.rs#L59)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Condition not met after the maximum number of {} attempts.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-03 11:19 UTC, Itay-Tsabary-Starkware commented
✓ Commit merged in pull request [#2424](https://github.com/starkware-libs/sequencer/pull/2424)

2024-12-03 11:19 UTC, closed without merging