chore(blockifier): add global max_sierra_gas to versioned constants
starkware-libs/sequencer pull request #2330
Opened 2024-11-28 11:10 UTC by aner-starkware

2024-11-28 11:10 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2330)
<!-- Reviewable:end -->

2024-11-28 13:39 UTC, aner-starkware reviewed
Python side: https://reviewable.io/reviews/starkware-industries/starkware/36341

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2330#-:-OCmzpz-3ys2GEMflveq:butu7pg)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-12-01 08:11 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 8 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2330)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2330#-OD0GEsj8M_H6ogLXGo2:-OD0GEsj8M_H6ogLXGo3:b-t0f4bz) ([raw file](https://github.com/starkware-libs/sequencer/blob/d33ffaca148a2789bb4888183a71a372e64316ac/crates/blockifier/src/versioned_constants.rs#L184)):*
> ```XML
>     pub max_recursion_depth: usize,
>     pub validate_max_n_steps: u32,
>     pub validate_max_sierra_gas: u64,
> ```

can you deserialize / serialize directly to GasAmount?



_Suggestion:_
```XML
    pub execute_max_sierra_gas: GasAmount,
    pub deprecated_l2_resource_gas_costs: ArchivalDataGasCosts,
    pub archival_data_gas_costs: ArchivalDataGasCosts,
    pub max_recursion_depth: usize,
    pub validate_max_n_steps: u32,
    pub validate_max_sierra_gas: GasAmount,
```


<!-- Sent from Reviewable.io -->

2024-12-01 14:05 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2330#-:-OD1XfZM8rsuA2sCaWVV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-03 07:21 UTC, merged