test(blockifier): parametrize feature contracts and tests by runnable type
starkware-libs/sequencer pull request #2344
Opened 2024-11-28 13:35 UTC by dorimedini-starkware

2024-11-28 13:36 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2344)
<!-- Reviewable:end -->

2024-11-28 13:36 UTC, dorimedini-starkware commented
* **#2344** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2344?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2344?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-28 15:08 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2344)* status: 0 of 45 files reviewed, all discussions resolved

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-OCnHmAkDVcwZc_pVs8M:-OCnHmAlEEyTzcL69ZWj:b-p9br7o) (no related file):*
This PR will not get in until native compiled contracts exist in our test framework (and even then may indicate more required work).

What was done here:
1. Created a RunnableContractVersion enum for the FeatureContracts variants.
2. Stopped using CairoVersion for FeatureContracts variants (and removed native variant [in the next PR](https://reviewable.io/reviews/starkware-libs/sequencer/2352))
3. Updated test utils that construct feature contracts to accept the new enum instead of CairoVersion
4. Updated *and parametrized* tests (or marked with TODOs to parametrize).
5. Note that parametrization creates a lot of boilerplate, e.g:
```
#[rstest]
fn test(#[values(Cairo0, Cairo1)] cairo_version)
```
now becomes
```
#[rstest]
#[case(Cairo0)]
#[case(Cairo1Casm)]
#[cfg_attr(feature = "cairo_native", case(Cairo1Native))]
fn test(#[case] cairo_version, #[case] some_bool)
```


<!-- Sent from Reviewable.io -->

2024-12-01 13:25 UTC, meship-starkware requested changes
> Reviewed 9 of 44 files at r1, 35 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2344)* status: 44 of 45 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-OD0bhWo-0MMQMAWzgUh:-OD0bhWo-0MMQMAWzgUi:baysc1v) ([raw file](https://github.com/starkware-libs/sequencer/blob/34d67ed3a765a95b78bac58e6fc2dab8295bc76f/crates/blockifier/src/test_utils/transfers_generator.rs#L12)):*
> ```XML
> use starknet_types_core::felt::Felt;
> 
> use super::contracts::RunnableContractVersion;
> ```

Please Avoid using super



_Code quote:_
```XML
use super::contracts::RunnableContractVersion;
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 535 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-OD1LwR88wlFiN1nkZ3I:-OD1LwR95fNFDCCv1g2e:b-51yot9) ([raw file](https://github.com/starkware-libs/sequencer/blob/34d67ed3a765a95b78bac58e6fc2dab8295bc76f/crates/blockifier/src/concurrency/worker_logic_test.rs#L535)):*
> ```XML
> #[cfg_attr(
>     feature = "cairo_native",
>     case::declare_cairo1(RunnableContractVersion::Cairo1Casm, TransactionVersion::THREE)
> ```

Shouldn't it be native?



_Code quote:_
```XML
case::declare_cairo1(RunnableContractVersion::Cairo1Casm
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-OD1Ma0JCWLc8lPe6wS5:-OD1Ma0JCWLc8lPe6wS6:b-opzaik) ([raw file](https://github.com/starkware-libs/sequencer/blob/34d67ed3a765a95b78bac58e6fc2dab8295bc76f/crates/blockifier/src/execution/stack_trace_test.rs#L289)):*
> ```XML
>     "fail",
>     "0x6661696c ('fail')", (0_u16, 0_u16))
> )]
> ```

Note to self: see if it makes the NM stack_trace test PR irrelevant. 



_Code quote:_
```XML
    "invoke_call_chain",
    "0x4469766973696f6e2062792030 ('Division by 0')", (0_u16, 0_u16))
)]
#[cfg_attr(feature = "cairo_native", case(
    RunnableContractVersion::Cairo1Native,
    "fail",
    "0x6661696c ('fail')", (0_u16, 0_u16))
)]
```


<!-- Sent from Reviewable.io -->

2024-12-01 14:27 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2344)* status: 44 of 45 files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 535 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-OD1LwR88wlFiN1nkZ3I:-OD1bJZS7UqArBhPgvwb:bzbadxz) ([raw file](https://github.com/starkware-libs/sequencer/blob/34d67ed3a765a95b78bac58e6fc2dab8295bc76f/crates/blockifier/src/concurrency/worker_logic_test.rs#L535)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Shouldn't it be native?
</blockquote></details>

whoops! done, thanks
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-OD0bhWo-0MMQMAWzgUh:-OD1b57I1nCPbTIplUv0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/34d67ed3a765a95b78bac58e6fc2dab8295bc76f/crates/blockifier/src/test_utils/transfers_generator.rs#L12)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please Avoid using super
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-02 15:53 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2344)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-OD1Ma0JCWLc8lPe6wS5:-OD73l9hE1ykL6Hm3aGT:b38pzvd) ([raw file](https://github.com/starkware-libs/sequencer/blob/34d67ed3a765a95b78bac58e6fc2dab8295bc76f/crates/blockifier/src/execution/stack_trace_test.rs#L289)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Note to self: see if it makes the NM stack_trace test PR irrelevant.
</blockquote></details>

The answer is no, but there will be merge conflicts. 
https://reviewable.io/reviews/starkware-libs/sequencer/2164#-


<!-- Sent from Reviewable.io -->

2024-12-03 12:11 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2344)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-ODASAyf0YP4B6QT1cTt:-ODASAygC6fGA326bmbP:b-tdi2xf) ([raw file](https://github.com/starkware-libs/sequencer/blob/29115d19e9e778380f287cea0f40f813d1ac70e0/crates/blockifier/src/test_utils/contracts.rs#L104)):*
> ```XML
>         Self::Cairo0
>     }
> }
> ```

Why is the default cairo0? I Would have chosen Cairo1Casm as the default. 



_Code quote:_
```XML
impl Default for RunnableContractVersion {
    fn default() -> Self {
        Self::Cairo0
    }
}
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-ODAT5vC2XR4QpNe45xG:-ODAT5vC2XR4QpNe45xH:b-6zpud8) ([raw file](https://github.com/starkware-libs/sequencer/blob/29115d19e9e778380f287cea0f40f813d1ac70e0/crates/blockifier/src/test_utils/contracts.rs#L118)):*
> ```XML
>             panic!("Transaction version {:?} is not supported.", tx_version)
>         }
>     }
> ```

Will this support Native as well? If so, would we choose according to the Sierra version (after AvivY will add the Sierra to the declared TX)? 



_Code quote:_
```XML
    pub fn from_declare_tx_version(tx_version: TransactionVersion) -> Self {
        if tx_version == TransactionVersion::ZERO || tx_version == TransactionVersion::ONE {
            Self::Cairo0
        } else if tx_version == TransactionVersion::TWO || tx_version == TransactionVersion::THREE {
            Self::Cairo1Casm
        } else {
            panic!("Transaction version {:?} is not supported.", tx_version)
        }
    }
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-ODATZ7o4pekyRuyjvQG:-ODATZ7o4pekyRuyjvQH:b-wqs8o9) ([raw file](https://github.com/starkware-libs/sequencer/blob/29115d19e9e778380f287cea0f40f813d1ac70e0/crates/blockifier/src/test_utils/contracts.rs#L127)):*
> ```XML
>             RunnableContractVersion::Cairo1Casm => Self::Cairo1,
>             #[cfg(feature = "cairo_native")]
>             RunnableContractVersion::Cairo1Native => Self::Native,
> ```

The intention is for Cairo1Native to also return to Cairo1, right? Do you wait until we can remove the cairo_native folder to do so?



_Code quote:_
```XML
            RunnableContractVersion::Cairo0 => Self::Cairo0,
            RunnableContractVersion::Cairo1Casm => Self::Cairo1,
            #[cfg(feature = "cairo_native")]
            RunnableContractVersion::Cairo1Native => Self::Native,
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 475 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-ODBQMYr-6LeK2taDv72:-ODBQMYr-6LeK2taDv73:b-p203cz) ([raw file](https://github.com/starkware-libs/sequencer/blob/29115d19e9e778380f287cea0f40f813d1ac70e0/crates/blockifier/src/test_utils/contracts.rs#L475)):*
> ```XML
>                     RunnableContractVersion::Cairo0,
>                     "Default version in iteration must be Cairo0 for this logic to be correct."
>                 );
> ```

Why? Because we only handle the cairo1 cases? Can't it be casm, and we will change the handling of casm to cairo0?



_Code quote:_
```XML
                assert_eq!(
                    contract.runnable_contract_version(),
                    RunnableContractVersion::Cairo0,
                    "Default version in iteration must be Cairo0 for this logic to be correct."
                );
```


<!-- Sent from Reviewable.io -->

2024-12-03 13:02 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2344)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-ODASAyf0YP4B6QT1cTt:-ODBaCR-Az3oXAaSLNPF:b-hcxfzz) ([raw file](https://github.com/starkware-libs/sequencer/blob/29115d19e9e778380f287cea0f40f813d1ac70e0/crates/blockifier/src/test_utils/contracts.rs#L104)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why is the default cairo0? I Would have chosen Cairo1Casm as the default.
</blockquote></details>

because the default CairoVersion is Cairo0, I am being consistent
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-ODAT5vC2XR4QpNe45xG:-ODBaNPt1kEYqKdVuF2O:bgys08a) ([raw file](https://github.com/starkware-libs/sequencer/blob/29115d19e9e778380f287cea0f40f813d1ac70e0/crates/blockifier/src/test_utils/contracts.rs#L118)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Will this support Native as well? If so, would we choose according to the Sierra version (after AvivY will add the Sierra to the declared TX)?
</blockquote></details>

I am assuming the difference between casm and native is irrelevant for declares... a declare declares sierra anyway
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-ODATZ7o4pekyRuyjvQG:-ODBTNJp0IYAQz9_TpQw:bvoh6tf) ([raw file](https://github.com/starkware-libs/sequencer/blob/29115d19e9e778380f287cea0f40f813d1ac70e0/crates/blockifier/src/test_utils/contracts.rs#L127)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

The intention is for Cairo1Native to also return to Cairo1, right? Do you wait until we can remove the cairo_native folder to do so?
</blockquote></details>

yes, done [here](https://reviewable.io/reviews/starkware-libs/sequencer/2352) (next PR)
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 475 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2344#-ODBQMYr-6LeK2taDv72:-ODBTV-w322kaq3owPCx:buhs9wb) ([raw file](https://github.com/starkware-libs/sequencer/blob/29115d19e9e778380f287cea0f40f813d1ac70e0/crates/blockifier/src/test_utils/contracts.rs#L475)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why? Because we only handle the cairo1 cases? Can't it be casm, and we will change the handling of casm to cairo0?
</blockquote></details>

the logic of the `has_all_runnable_versions` case is: add cairo1 and native instances.
if the original instance is not cairo0, this logic is incorrect.
want me to explicitly add the three contract versions here? that sounds better even, I can use EnumIter on RunnableContractVersion and I won't need the `#[cfg]` here at all...
done


<!-- Sent from Reviewable.io -->

2025-01-08 10:51 UTC, closed without merging