chore(infra_utils): extending gen_field_names_fn macro to create cli …
starkware-libs/sequencer pull request #2360
Opened 2024-11-28 16:30 UTC by lev-starkware

…arguments

commit-id:56295ae8

2024-11-28 16:30 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2360)
<!-- Reviewable:end -->

2024-12-01 14:49 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2360)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/papyrus_proc_macros/src/lib.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2360#-OD1eqJxES1hS9CvLgHG:-OD1eqJxES1hS9CvLgHH:b-aode13) ([raw file](https://github.com/starkware-libs/sequencer/blob/09813b8fc0ff885d8b37ec0a9e9806c500b60f09/crates/papyrus_proc_macros/src/lib.rs#L261)):*
> ```XML
> /// the struct field element names.
> /// This macro also generates a `pub fn cli_args() -> Vec<String>`, a method that returns a vector
> /// of command arguments.
> ```

Please change to `a method that returns a vector of the struct fields as command line arguments.`



_Code quote:_
```XML
/// This macro also generates a `pub fn cli_args() -> Vec<String>`, a method that returns a vector
/// of command arguments.
```
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2360#-OD1fOat8XHIi3z2BUR2:-OD1fOat8XHIi3z2BUR3:b-66x5uf) ([raw file](https://github.com/starkware-libs/sequencer/blob/09813b8fc0ff885d8b37ec0a9e9806c500b60f09/crates/papyrus_proc_macros/src/lib.rs#L295)):*
> ```XML
>             .collect::<Vec<_>>()
>     } else {
>         panic!("#[gen_field_names_fn] can only be used on structs");
> ```

Please rename the macro in the comment



_Code quote:_
```XML
panic!("#[gen_field_names_fn] can only be used on structs");
```
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2360#-OD1fZwWBUw9UrLCNi8L:-OD1fZwWBUw9UrLCNi8M:b-tx0ov8) ([raw file](https://github.com/starkware-libs/sequencer/blob/09813b8fc0ff885d8b37ec0a9e9806c500b60f09/crates/papyrus_proc_macros/src/lib.rs#L302)):*
> ```XML
>     } else {
>         panic!("#[gen_cli_args_fn] can only be used on structs");
>     };
> ```

Seems like there is a duplication with the generation of `field_names`.
Could we do something like


```
    let field_idents = if let syn::Data::Struct(data) = &input.data {
        data.fields.iter().filter_map(|field| field.ident.as_ref()).collect::<Vec<_>>()
    } else {
        panic!("#[gen_field_names_and_cli_args_fn] can only be used on structs");
    };
    let field_names = field_idents.iter().map(|ident| ident.to_string()).collect::<Vec<_>>()`

```
?



_Code quote:_
```XML
    let field_idents = if let syn::Data::Struct(data) = &input.data {
        data.fields.iter().filter_map(|field| field.ident.as_ref()).collect::<Vec<_>>()
    } else {
        panic!("#[gen_cli_args_fn] can only be used on structs");
    };
```
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 325 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2360#-OD1gPWW7s2wSAw-fVCm:-OD1gPWW7s2wSAw-fVCn:b-pbpffa) ([raw file](https://github.com/starkware-libs/sequencer/blob/09813b8fc0ff885d8b37ec0a9e9806c500b60f09/crates/papyrus_proc_macros/src/lib.rs#L325)):*
> ```XML
>                     args.len() == Self::field_names().len() * 2,
>                     "Required parameter cli generation failure."
>                 );
> ```

Do you think this is necessary? In the original context it was to verify that adding an arg to the struct will fail this function unless also added explcitly to it.



_Code quote:_
```XML
                // Verify all arguments and their values are present.
                assert!(
                    args.len() == Self::field_names().len() * 2,
                    "Required parameter cli generation failure."
                );
```


<!-- Sent from Reviewable.io -->

2024-12-01 15:53 UTC, lev-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2360)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_proc_macros/src/lib.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2360#-OD1eqJxES1hS9CvLgHG:-OD1oRPl7QHQWzivzwQ7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/09813b8fc0ff885d8b37ec0a9e9806c500b60f09/crates/papyrus_proc_macros/src/lib.rs#L261)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to `a method that returns a vector of the struct fields as command line arguments.`
</blockquote></details>

Done.
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2360#-OD1fOat8XHIi3z2BUR2:-OD1opkH4HUr1y7jEIpr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/09813b8fc0ff885d8b37ec0a9e9806c500b60f09/crates/papyrus_proc_macros/src/lib.rs#L295)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please rename the macro in the comment
</blockquote></details>

Done.
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2360#-OD1fZwWBUw9UrLCNi8L:-OD1ryNG1olQ_DoBDrgI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/09813b8fc0ff885d8b37ec0a9e9806c500b60f09/crates/papyrus_proc_macros/src/lib.rs#L302)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Seems like there is a duplication with the generation of `field_names`.
Could we do something like


```
    let field_idents = if let syn::Data::Struct(data) = &input.data {
        data.fields.iter().filter_map(|field| field.ident.as_ref()).collect::<Vec<_>>()
    } else {
        panic!("#[gen_field_names_and_cli_args_fn] can only be used on structs");
    };
    let field_names = field_idents.iter().map(|ident| ident.to_string()).collect::<Vec<_>>()`

```
?
</blockquote></details>

Done.
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 325 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2360#-OD1gPWW7s2wSAw-fVCm:-OD1pPZ5BP3VqCwSmv__:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/09813b8fc0ff885d8b37ec0a9e9806c500b60f09/crates/papyrus_proc_macros/src/lib.rs#L325)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Do you think this is necessary? In the original context it was to verify that adding an arg to the struct will fail this function unless also added explcitly to it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-02 10:10 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2360#-:-OD5qKA71fhSkARTiEkO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)



<!-- Sent from Reviewable.io -->

2024-12-02 15:36 UTC, merged