chore(blockifier): save sierra to Feature contracts
starkware-libs/sequencer pull request #2370
Opened 2024-12-01 11:01 UTC by meship-starkware

2024-12-01 11:01 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2370)
<!-- Reviewable:end -->

2024-12-01 11:02 UTC, meship-starkware reviewed
> Reviewed 7 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-01 11:24 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD0t-8439b22qPJ0ml3:-OD0t-85D6O-RRd9EF_K:b-4xfeay) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba61e1e3a5e19d5f0dc20b6d32a6903404e6e400/crates/blockifier/src/test_utils/cairo_compile.rs#L128)):*
> ```XML
>     if fix {
>         fs::write(&file_path, &sierra_output).unwrap();
>     }
> ```

I am unsure if entering the fix inside and writing the files here is the best solution. The other solution I could think of is to return the Sierra data and write it in the test logic. Still, we have to write Sierra first to a temp file and then to the directory, and we'll also have to do something ugly with the return type since Cairo 0 does not return two data. 



_Code quote:_
```XML
    if fix {
        fs::write(&file_path, &sierra_output).unwrap();
    }
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD0tjsd3qGv31A8Q0nn:-OD0tjsd3qGv31A8Q0no:b-2p6hga) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba61e1e3a5e19d5f0dc20b6d32a6903404e6e400/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L127)):*
> ```XML
> 
>         let file_name = path.file_stem().unwrap().to_string_lossy();
>         let mut existing_sierra_path = "".to_string();
> ```

I don't like the empty string for cairo0 contracts. Should it be None, or should I get the Sierra from a different function? 



_Code quote:_
```XML
 let mut existing_sierra_path = "".to_string();
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD0sj__3l-L_uxUMhV_:-OD0sj__3l-L_uxUMhVa:bqop8dx) ([raw file](https://github.com/starkware-libs/sequencer/blob/06c9560dec091f8cd29220da10223a96708d57e2/crates/blockifier/src/execution/native/syscall_handler.rs#L35)):*
> ```XML
> use crate::execution::syscalls::hint_processor::{
>     SyscallExecutionError,
>     INVALID_INPUT_LENGTH_ERROR,
> ```

Style change for unusable import: I can do it in a separate PR if it would be better. 



_Code quote:_
```XML
   INVALID_INPUT_LENGTH_ERROR,
```


<!-- Sent from Reviewable.io -->

2024-12-01 14:31 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD0t-8439b22qPJ0ml3:-OD1c8S40f9hA5_Ed_Cz:b-ap8o03) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba61e1e3a5e19d5f0dc20b6d32a6903404e6e400/crates/blockifier/src/test_utils/cairo_compile.rs#L128)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am unsure if entering the fix inside and writing the files here is the best solution. The other solution I could think of is to return the Sierra data and write it in the test logic. Still, we have to write Sierra first to a temp file and then to the directory, and we'll also have to do something ugly with the return type since Cairo 0 does not return two data.
</blockquote></details>

I think it would be better not to have a `fix` in this context - just in-memory data creation, input-output.
as for return type, how about
```
pub enum CompilationArtifacts {
    Cairo0 { casm: Vec<u8> },
    Cairo1 { casm: Vec<u8>, sierra: Vec<u8> },
}
```
?


<!-- Sent from Reviewable.io -->

2024-12-01 14:40 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: all files reviewed, 9 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD0tjsd3qGv31A8Q0nn:-OD1e-RY0s7S0nbsi_BK:b6y8vrb) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba61e1e3a5e19d5f0dc20b6d32a6903404e6e400/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L127)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I don't like the empty string for cairo0 contracts. Should it be None, or should I get the Sierra from a different function?
</blockquote></details>

see above: you should define a `FeatureContractMetadata` type and return it here.
this type can be an enum (cairo0 or cairo1 variants) with different data
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1dZ3uEF14sRxi4wxM:-OD1dZ3uEF14sRxi4wxN:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L73)):*
> ```XML
>     let existing_compiled_path = contract.get_compiled_path();
> 
>     if fix {
> ```

see above



_Suggestion:_
```XML
    let expected_compiled_output = contract.compile();
    let existing_compiled_path = contract.get_compiled_path();

    if fix {
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1deMiD-jfm628_RFH:-OD1deMiD-jfm628_RFI:bt70y6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L90)):*
> ```XML
> /// Verifies that the feature contracts directory contains the expected contents, and returns a list
> /// of pairs (source_path, base_filename, compiled_path) for each contract.
> fn verify_and_get_files(cairo_version: CairoVersion) -> Vec<(String, String, String, String)> {
> ```

I think it's time you create a FeatureContractMetadata struct for these strings.
if you think it's out of scope, update the docstring (document the fourth return value)



_Code quote:_
```XML
/// of pairs (source_path, base_filename, compiled_path) for each contract.
fn verify_and_get_files(cairo_version: CairoVersion) -> Vec<(String, String, String, String)> {
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1eJ-q3xgY7cCzx4Yw:-OD1eJ-q3xgY7cCzx4Yx:bjpz5vc) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L164)):*
> ```XML
> 
>     let mut sierra_paths_from_enum: Vec<String> = FeatureContract::all_feature_contracts()
>         .filter(|contract| contract.cairo_version() == CairoVersion::Cairo1)
> ```

currently, cairo version also contains a Native variant (when compiled with the feature) - 
this is more robust.
or, you could `match` the cairo version explicitly here, and the compiler will catch you :)



_Suggestion:_
```XML
contract.cairo_version() != CairoVersion::Cairo0
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 294 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1dSpV4V8rZBk87Mnl:-OD1dSpV4V8rZBk87Mnm:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/src/test_utils/contracts.rs#L294)):*
> ```XML
> 
>     pub fn get_sierra_path(&self) -> String {
>         format!("feature_contracts/cairo1/sierra/{}.sierra.json", self.get_non_erc20_base_name())
> ```





_Suggestion:_
```XML
"{CAIRO1_FEATURE_CONTRACTS_DIR}/{SIERRA_CONTRACTS_SUBDIR}/{}.sierra.json"
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 295 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1cyoVAOBNi7AABDSh:-OD1cyoVAOBNi7AABDSi:b-q2oh2y) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/src/test_utils/contracts.rs#L295)):*
> ```XML
>     pub fn get_sierra_path(&self) -> String {
>         format!("feature_contracts/cairo1/sierra/{}.sierra.json", self.get_non_erc20_base_name())
>     }
> ```

add an assert that this is not a cairo0 contract, and not the ERC20 contract, with informative messages on failure



_Code quote:_
```XML
    pub fn get_sierra_path(&self) -> String {
        format!("feature_contracts/cairo1/sierra/{}.sierra.json", self.get_non_erc20_base_name())
    }
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 330 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1d9EzCxP2uRpC9zA8:-OD1d9EzCxP2uRpC9zA9:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/src/test_utils/contracts.rs#L330)):*
> ```XML
>     /// Compiles the feature contract and returns the compiled contract as a byte vector.
>     /// Panics if the contract is ERC20, as ERC20 contract recompilation is not supported.
>     pub fn compile(&self, fix: bool) -> Vec<u8> {
> ```

see above



_Suggestion:_
```XML
pub fn compile(&self) -> CompilationArtifacts
```


<!-- Sent from Reviewable.io -->

2024-12-01 14:41 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: all files reviewed, 8 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD0sj__3l-L_uxUMhV_:-OD1ehuX1-C1Z0zXWMSx:bb7k0qh) ([raw file](https://github.com/starkware-libs/sequencer/blob/06c9560dec091f8cd29220da10223a96708d57e2/crates/blockifier/src/execution/native/syscall_handler.rs#L35)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Style change for unusable import: I can do it in a separate PR if it would be better.
</blockquote></details>

lgtm


<!-- Sent from Reviewable.io -->

2024-12-02 14:50 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: 7 of 11 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD0t-8439b22qPJ0ml3:-OD526jUD1rRF-6n5jN-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba61e1e3a5e19d5f0dc20b6d32a6903404e6e400/crates/blockifier/src/test_utils/cairo_compile.rs#L128)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it would be better not to have a `fix` in this context - just in-memory data creation, input-output.
as for return type, how about
```
pub enum CompilationArtifacts {
    Cairo0 { casm: Vec<u8> },
    Cairo1 { casm: Vec<u8>, sierra: Vec<u8> },
}
```
?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 295 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1cyoVAOBNi7AABDSh:-OD6qLU70uAp_GkHUD00:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/src/test_utils/contracts.rs#L295)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add an assert that this is not a cairo0 contract, and not the ERC20 contract, with informative messages on failure
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 330 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1d9EzCxP2uRpC9zA8:-OD6qMbeC0SbRBKwjq3o:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/src/test_utils/contracts.rs#L330)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD0tjsd3qGv31A8Q0nn:-OD6qQzT-0BrAu8uRgqx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba61e1e3a5e19d5f0dc20b6d32a6903404e6e400/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above: you should define a `FeatureContractMetadata` type and return it here.
this type can be an enum (cairo0 or cairo1 variants) with different data
</blockquote></details>

Done.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1dZ3uEF14sRxi4wxM:-OD6qOj8BqtIFWuTCICy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L73)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1deMiD-jfm628_RFH:-OD6qPceBO6AOrmTtmD3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it's time you create a FeatureContractMetadata struct for these strings.
if you think it's out of scope, update the docstring (document the fourth return value)
</blockquote></details>

Done.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1eJ-q3xgY7cCzx4Yw:-OD6qTbg1dVpkxRp2OVK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L164)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

currently, cairo version also contains a Native variant (when compiled with the feature) - 
this is more robust.
or, you could `match` the cairo version explicitly here, and the compiler will catch you :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 294 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-OD1dSpV4V8rZBk87Mnl:-OD6qJ23ETvT4n-qexjT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a09a0264da06cb2c420ec259e152da043fe6d6/crates/blockifier/src/test_utils/contracts.rs#L294)):*
> ```XML
> 
>     pub fn get_sierra_path(&self) -> String {
>         format!("feature_contracts/cairo1/sierra/{}.sierra.json", self.get_non_erc20_base_name())
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-03 11:38 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: all files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODB7sJJBOXlFVYXIDAQ:-ODB7sJJBOXlFVYXIDAR:b-mfre1z) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/src/test_utils/cairo_compile.rs#L68)):*
> ```XML
> 
> impl CompilationArtifacts {
>     pub fn get_compiled_output(&self) -> Vec<u8> {
> ```

can you rename? I would expect the Cairo1 compiled output to include both casm and sierra



_Code quote:_
```XML
get_compiled_output
```
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODB7zC26AXNhZ9Cmz23:-ODB7zC26AXNhZ9Cmz24:b-j59ig3) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/src/test_utils/cairo_compile.rs#L71)):*
> ```XML
>         match self {
>             CompilationArtifacts::Cairo0 { casm } => casm.clone(),
>             CompilationArtifacts::Cairo1 { casm, .. } => casm.clone(),
> ```

combine arms



_Suggestion:_
```XML
            CompilationArtifacts::Cairo0 { casm } | CompilationArtifacts::Cairo1 { casm, .. } => casm.clone(),
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBA--B9jmkuTDUHFyO:-ODBA--B9jmkuTDUHFyP:b5v9em3) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L28)):*
> ```XML
>     Cairo1(InnerFeatureContractMetadata),
>     #[cfg(feature = "cairo_native")]
>     Native(InnerFeatureContractMetadata),
> ```

for metadata, why do you need to tell the difference between cairo1 and native?
can you delete the native variant?



_Code quote:_
```XML
    Cairo1(InnerFeatureContractMetadata),
    #[cfg(feature = "cairo_native")]
    Native(InnerFeatureContractMetadata),
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODB8mWz7oM3F10rgXZQ:-ODB8mWz7oM3F10rgXZR:b-bv6duk) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L55)):*
> ```XML
>     pub compiled_path: String,
> }
> pub struct InnerFeatureContractMetadata {
> ```

newlines



_Suggestion:_
```XML
}

pub struct DeprecatedFeatureContractMetadata {
    pub source_path: String,
    pub base_filename: String,
    pub compiled_path: String,
}

pub struct InnerFeatureContractMetadata {
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODB8qtYCYY7jdX2JCxm:-ODB8qtYCYY7jdX2JCxn:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L55)):*
> ```XML
>     pub compiled_path: String,
> }
> pub struct InnerFeatureContractMetadata {
> ```





_Suggestion:_
```XML
pub struct Cairo0FeatureContractMetadata {
    pub source_path: String,
    pub base_filename: String,
    pub compiled_path: String,
}
pub struct Cairo1FeatureContractMetadata {
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 125 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODB9AJj2Gd9iyWHU7KI:-ODB9AJj2Gd9iyWHU7KJ:b-18z5rp) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L125)):*
> ```XML
>                 fs::write(contract.get_sierra_path(), &sierra).unwrap();
>             }
>         }
> ```

1. I would put all writing logic in the `match`, and delete the `get_compiled_output` getter
2. why not fix the sierra contracts in native mode?



_Suggestion:_
```XML
    let existing_compiled_path = contract.get_compiled_path();

    if fix {
        match expected_compiled_raw_output {
            CompilationArtifacts::Cairo0 { casm } => {
                fs::write(&existing_compiled_path, &casm).unwrap();
            }
            #[cfg(feature = "cairo_native")]
            CompilationArtifacts::Cairo1Native { sierra } => {
                fs::write(contract.get_sierra_path(), &sierra).unwrap();
            }
            CompilationArtifacts::Cairo1 { sierra, casm } => {
                fs::write(&existing_compiled_path, &casm).unwrap();
                fs::write(contract.get_sierra_path(), &sierra).unwrap();
            }
        }
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 266 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBIvMM16Kufo85_KOR:-ODBIvMNALTnKULFq8IN:b-dih0ae) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L266)):*
> ```XML
>             sierra_paths_from_enum.sort();
>             sierra_paths_on_filesystem.sort();
>             assert_eq!(sierra_paths_from_enum, sierra_paths_on_filesystem);
> ```

duplicated... can you extract this into a function / lambda function?



_Code quote:_
```XML
        #[cfg(feature = "cairo_native")]
        CairoVersion::Native => {
            let mut sierra_paths_on_filesystem: Vec<String>;
            (compiled_paths_on_filesystem, sierra_paths_on_filesystem) =
                verify_and_get_files(cairo_version)
                    .into_iter()
                    .map(|metadata| {
                        (metadata.compiled_path().to_string(), metadata.sierra_path().to_string())
                    })
                    .collect();
            let mut sierra_paths_from_enum: Vec<String> = FeatureContract::all_feature_contracts()
                .filter(|contract| contract.cairo_version() == cairo_version)
                .map(|contract| contract.get_sierra_path())
                .collect();
            sierra_paths_from_enum.sort();
            sierra_paths_on_filesystem.sort();
            assert_eq!(sierra_paths_from_enum, sierra_paths_on_filesystem);
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 298 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODB8Y9c8TI0-uAScByu:-ODB8Y9c8TI0-uAScByv:b85l5nm) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/src/test_utils/contracts.rs#L298)):*
> ```XML
>     pub fn get_sierra_path(&self) -> String {
>         assert_ne!(self.cairo_version(), CairoVersion::Cairo0);
>         debug_assert_ne!(self, &Self::ERC20(CairoVersion::Cairo1));
> ```

why is this assert with `debug_`?



_Code quote:_
```XML
debug_assert_ne!
```


<!-- Sent from Reviewable.io -->

2024-12-03 13:54 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: all files reviewed, 10 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 266 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBIvMM16Kufo85_KOR:-ODBnA0qBOeF0jwvk_U-:b23zsxz) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L266)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I can, but it might become unnecessary when we remove the feature flag.  Do you want me to add a TODO to remove it once we remove the feature flag?
</blockquote></details>

yes please :)
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBmLpZ4wHte_khIZZ_:-ODBmLpZ4wHte_khIZZa:b-j59ig3) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L33)):*
> ```XML
>         match self {
>             FeatureContractMetadata::Cairo0(data) => data.compiled_path.clone(),
>             FeatureContractMetadata::Cairo1(data) => data.compiled_path.clone(),
> ```

combine arms



_Suggestion:_
```XML
            FeatureContractMetadata::Cairo0(data) | FeatureContractMetadata::Cairo1(data) => data.compiled_path.clone(),
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 123 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBmeBd4tnj4DlNK1Bb:-ODBmeBd4tnj4DlNK1Bc:b-rtagwg) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L123)):*
> ```XML
>     // Compare output of cairo-file on file with existing compiled file.
>     let expected_compiled_raw_output = contract.compile();
>     // let expected_compiled_output = expected_compiled_raw_output.get_compiled_output();
> ```

delete



_Code quote:_
```XML
// let expected_compiled_output = expected_compiled_raw_output.get_compiled_output();
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 129 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBmb_r432h037D3hZq:-ODBmb_r432h037D3hZr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L129)):*
> ```XML
>     if fix {
>         match expected_compiled_raw_output {
>             CompilationArtifacts::Cairo0 { ref casm, .. } => {
> ```





_Suggestion:_
```XML
CompilationArtifacts::Cairo0 { ref casm } =>
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBmnEsAm8hQTc1xdr6:-ODBmnEsAm8hQTc1xdr7:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L147)):*
> ```XML
>         .unwrap_or_else(|_| panic!("Cannot read {existing_compiled_path}."));
>     match expected_compiled_raw_output {
>         CompilationArtifacts::Cairo0 { casm, .. } => {
> ```





_Suggestion:_
```XML
{ casm }
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 183 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBmvVV1Ik6O72ra7ZN:-ODBmvVV1Ik6O72ra7ZO:b4cwskq) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L183)):*
> ```XML
>             );
>         }
>     }
> ```

can you move all this logic (this `match`) into the compare_compilation_data function?
this function should inspect the type of compilation done and compare the correct things



_Code quote:_
```XML
    match expected_compiled_raw_output {
        CompilationArtifacts::Cairo0 { casm, .. } => {
            compare_compilation_data(
                casm,
                existing_compiled_contents,
                existing_compiled_path,
                contract.get_source_path(),
            );
        }
        CompilationArtifacts::Cairo1 { casm, sierra } => {
            compare_compilation_data(
                casm,
                existing_compiled_contents,
                existing_compiled_path,
                contract.get_source_path(),
            );

            let sierra_compiled_path = contract.get_sierra_path();
            let existing_sierra_contents = fs::read_to_string(&sierra_compiled_path)
                .unwrap_or_else(|_| panic!("Cannot read {sierra_compiled_path}."));
            compare_compilation_data(
                sierra,
                existing_sierra_contents,
                sierra_compiled_path,
                contract.get_source_path(),
            );
        }
        // TODO (Meshi 01/01/2025) Remove this once native folder is deleted.
        #[cfg(feature = "cairo_native")]
        CompilationArtifacts::Cairo1Native { sierra, .. } => {
            compare_compilation_data(
                sierra,
                existing_compiled_contents,
                existing_compiled_path,
                contract.get_source_path(),
            );
        }
    }
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 263 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBnDaa0k2Wm9hRUHs9:-ODBnDaa0k2Wm9hRUHsA:b-iuepwu) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L263)):*
> ```XML
> }
> 
> fn verify_feature_contracts_cairo1_logic(cairo_version: CairoVersion) -> Vec<String> {
> ```

why do you return something here?



_Code quote:_
```XML
 -> Vec<String>
```


<!-- Sent from Reviewable.io -->

2024-12-03 14:01 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: 10 of 11 files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODB7sJJBOXlFVYXIDAQ:-ODBopAb2sSxcZkiiLRM:b-9wesje) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/src/test_utils/cairo_compile.rs#L68)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you rename? I would expect the Cairo1 compiled output to include both casm and sierra
</blockquote></details>

Removed the impl. 
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODB7zC26AXNhZ9Cmz23:-ODBornt-BoVyR5gs6Fg:b-9wesje) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/src/test_utils/cairo_compile.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

combine arms
</blockquote></details>

Removed the impl. 


<!-- Sent from Reviewable.io -->

2024-12-03 14:08 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: all files reviewed, 8 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-03 14:55 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 266 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBIvMM16Kufo85_KOR:-ODBvs_w6oCkm7_MxYdH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de51d1929a174796796469bec49be2388c1dbb1/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L266)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes please :)
</blockquote></details>

Done.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBmLpZ4wHte_khIZZ_:-ODBporyCGsKCUJxecJp:b-2usljw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L33)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

combine arms
</blockquote></details>

I get a mismatched type error on the data inside. 
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 123 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBmeBd4tnj4DlNK1Bb:-ODBqKcJ62AdcZ5HMwJM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L123)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 183 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBmvVV1Ik6O72ra7ZN:-ODBuXl38E9lTTcmKOb6:b-nnhemi) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L183)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you move all this logic (this `match`) into the compare_compilation_data function?
this function should inspect the type of compilation done and compare the correct things
</blockquote></details>

I don't think I understand your vision. I used the compare compilation data to avoid writing the panic message constantly. 
As long as the message is the same for all contracts, I still see value in the small function. I have no problem moving the match to a different function, but I don't think that was your intention. 
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 263 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBnDaa0k2Wm9hRUHs9:-ODBp90bD7ByPeeIN1f4:b-ltmgx1) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L263)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you return something here?
</blockquote></details>

So I won't have to write the comparison between the compiled files twice of the compiled file twice.  I you think it will be more readable I will just separate the Cairo 0 and native + Cairo one cases completely 
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 129 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBmb_r432h037D3hZq:-ODBqKVWCdump50qID0A:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L129)):*
> ```XML
>     if fix {
>         match expected_compiled_raw_output {
>             CompilationArtifacts::Cairo0 { ref casm, .. } => {
> ```

Done.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-ODBmnEsAm8hQTc1xdr6:-ODBqLBg2ONIkyGFmKK5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cd2266e6cdd9774331f61cd003809919d41faf3/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L147)):*
> ```XML
>         .unwrap_or_else(|_| panic!("Cannot read {existing_compiled_path}."));
>     match expected_compiled_raw_output {
>         CompilationArtifacts::Cairo0 { casm, .. } => {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-04 10:26 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-04 13:21 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 11 files at r1, 1 of 4 files at r3, 1 of 1 files at r6, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370#-:-ODGpJ0FD_exRA2KTrx0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-12-04 13:24 UTC, dorimedini-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2370)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-12-04 13:24 UTC, merged