WIP
starkware-libs/sequencer pull request #2397
Opened 2024-12-02 11:53 UTC by aner-starkware

2024-12-02 11:53 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2397)
<!-- Reviewable:end -->

2024-12-05 09:27 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 4 files at r3, 4 of 4 files at r4, 1 of 3 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 19 unresolved discussions (waiting on @aner-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL7gxm26YZxulleQKZ:-ODL7gxn1Y5M-VdhpwrR:b-agdv5c) (no related file):*
please add some unit tests, where you parametrize
1. for different tx types
2. for different resource bounds
3. for different account / deployed contract cairo versions

and make sure the initial gas is as expected:
1. if user bound is huge, both entry points should be the max allowed for the execution mode (validate/execute). note that `__execute__` can be run in validate execution mode (in deploy account txs)
2. if user bound is over the first entry point max but not over the second, first entry point should have the max initial gas and second should not
3. if user bound is below both entry point maxes, neither entry point should have max bounds
___
*[`crates/blockifier/src/context.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHQlt1D0i5ueY97KeW:-ODHQlt1D0i5ueY97KeX:be3sqr8) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/context.rs#L69)):*
> ```XML
> 
> impl GasCounter {
>     pub(crate) fn new(initial_gas: u64) -> Self {
> ```

for all new types/functions - be strict with the type you use.
we want to eventually migrate all representations of an amount of gas to GasAmount



_Suggestion:_
```XML
initial_gas: GasAmount
```
___
*[`crates/blockifier/src/context.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHSL5R-cmG7mW-7MXK:-ODHSL5R-cmG7mW-7MXL:b-xi6dol) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/context.rs#L73)):*
> ```XML
>     }
> 
>     pub(crate) fn spend(&mut self, amount: GasAmount) {
> ```

is this used anywhere other than in subtract_used_gas?
if not, please inline the logic and remove this function



_Code quote:_
```XML
 pub(crate) fn spend
```
___
*[`crates/blockifier/src/context.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHQy0d1vmS5r9xAmR4:-ODHQy0d1vmS5r9xAmR5:b-na9b10) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/context.rs#L79)):*
> ```XML
>             .checked_sub(amount)
>             .expect("Overuse of gas; should have been caught earlier");
>     }
> ```

consider forcing the caller to decide whether or not to panic; non-blocking



_Suggestion:_
```XML
    pub(crate) fn spend(&mut self, amount: GasAmount) -> Result<()> {
        self.spent_gas = self.spent_gas.checked_add(amount).expect("Gas overflow");
        self.remaining_gas = self
            .remaining_gas
            .checked_sub(amount)?;
    }
```
___
*[`crates/blockifier/src/context.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHRK5s5JrdL9sBeGUj:-ODHRK5s5JrdL9sBeGUk:b-bjkyon) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/context.rs#L81)):*
> ```XML
>     }
> 
>     pub(crate) fn cap_usage(&self, amount: GasAmount) -> u64 {
> ```

1. docstring (unclear to me what exactly this does, just from the function name)
2. use stricter type



_Suggestion:_
```XML
pub(crate) fn cap_usage(&self, amount: GasAmount) -> GasAmount {
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1700 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL8DY55RywhbzZ6iFd:-ODL8DY55RywhbzZ6iFe:b-f8lnyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8e25e395ad1b632dce9ff36399c8d755116d57c/crates/blockifier/src/transaction/account_transactions_test.rs#L1700)):*
> ```XML
>         .min(
>             block_context.versioned_constants.default_initial_gas_amount()
>                 - GasAmount(validate_gas_consumed),
> ```

this should depend on the user bound, not the default initial gas.



_Suggestion:_
```XML
            user_gas_bound
                - GasAmount(validate_gas_consumed),
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 262 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHRbWP26urjFq29eGc:-ODHRbWP26urjFq29eGd:bku7s19) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/versioned_constants.rs#L262)):*
> ```XML
>     pub fn max_execution_sierra_gas(&self) -> GasAmount {
>         self.execute_max_sierra_gas
>     }
> ```

are these getters necessary? aren't the fields public?



_Code quote:_
```XML
    /// Returns the maximum gas amount for validation.
    pub fn max_validation_sierra_gas(&self) -> GasAmount {
        self.validate_max_sierra_gas
    }

    /// Returns the maximum gas amount for execute.
    pub fn max_execution_sierra_gas(&self) -> GasAmount {
        self.execute_max_sierra_gas
    }
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 243 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL4ryB5_3Qk7e723Jf:-ODL4ryB5_3Qk7e723Jg:bs8wkpg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8e25e395ad1b632dce9ff36399c8d755116d57c/crates/blockifier/src/transaction/transactions_test.rs#L243)):*
> ```XML
>             TrackedResource::CairoSteps => {
>                 default_initial_gas_amount().min(VERSIONED_CONSTANTS.max_validation_sierra_gas()).0
>             }
> ```

not sure there should be a difference between cairo0 initial gas and cairo1-step-mode initial gas; discussing offline



_Code quote:_
```XML
        CairoVersion::Cairo0 => default_initial_gas_cost(),
        CairoVersion::Cairo1 => match tracked_resource {
            TrackedResource::CairoSteps => {
                default_initial_gas_amount().min(VERSIONED_CONSTANTS.max_validation_sierra_gas()).0
            }
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 529 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL55QP-vwPCEnqJ55S:-ODL55QP-vwPCEnqJ55T:b-gstrrg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8e25e395ad1b632dce9ff36399c8d755116d57c/crates/blockifier/src/transaction/transactions_test.rs#L529)):*
> ```XML
>     if account_cairo_version == CairoVersion::Cairo0 {
>         expected_arguments.inner_call_initial_gas = VERSIONED_CONSTANTS.default_initial_gas_cost();
>     }
> ```

how is this working?
currently, inner calls of cairo0 (step-mode -> step-mode) should have `default_initial_gas - gas_consumed`, why do inner calls also have the default initial gas?
maybe because, if the account version is cairo0, then `tracked_resource` is steps, so you enter the `if` below and subtract the execute gas consumed; please combine the two `if`s for clarity (put this `if` inside the below `if`)



_Code quote:_
```XML
    if account_cairo_version == CairoVersion::Cairo0 {
        expected_arguments.inner_call_initial_gas = VERSIONED_CONSTANTS.default_initial_gas_cost();
    }
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 536 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL5OJz-VrSM07Pybdl:-ODL5OK-55meQU8zaTe3:b-rtagwg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8e25e395ad1b632dce9ff36399c8d755116d57c/crates/blockifier/src/transaction/transactions_test.rs#L536)):*
> ```XML
>         } else {
>             expected_initial_execution_gas
>         }, // expected_validated_call.initial_gas - expected_arguments.validate_gas_consumed,
> ```

delete



_Code quote:_
```XML
// expected_validated_call.initial_gas - expected_arguments.validate_gas_consumed,
```
___
*[`crates/blockifier/src/transaction/transa [...]

2024-12-05 09:47 UTC, aner-starkware commented
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1813 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL6v5aAz9oZQo9DziJ:-ODLCUXuANTUnA2VOO_U:bgrm175) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8e25e395ad1b632dce9ff36399c8d755116d57c/crates/blockifier/src/transaction/transactions_test.rs#L1813)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is wrong, I think: in DEPLOY_ACCOUNT txs, the execute entry point is run in VALIDATE mode (i.e. initial gas should be capped by validate limit).
</blockquote></details>

Let's talk offline about this point - I think it contradicts what you previously said.


<!-- Sent from Reviewable.io -->

2024-12-05 12:42 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: 1 of 9 files reviewed, 19 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/context.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHQlt1D0i5ueY97KeW:-ODLn5iiC_ng3CnfKqxm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/context.rs#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

for all new types/functions - be strict with the type you use.
we want to eventually migrate all representations of an amount of gas to GasAmount
</blockquote></details>

Done.
___
*[`crates/blockifier/src/context.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHSL5R-cmG7mW-7MXK:-ODLn7g8AR3CGn5qC_bT:b-py6htg) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/context.rs#L73)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this used anywhere other than in subtract_used_gas?
if not, please inline the logic and remove this function
</blockquote></details>

I removed the `pub(crate)` - I disagree here; it's better to separate this logic.
___
*[`crates/blockifier/src/context.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHQy0d1vmS5r9xAmR4:-ODLnOqE2IimC00S9-MF:bawoqzw) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/context.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider forcing the caller to decide whether or not to panic; non-blocking
</blockquote></details>

There's an issue here—IIUC, we should never `panic!`, so panicking makes sense IMO.
___
*[`crates/blockifier/src/context.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHRK5s5JrdL9sBeGUj:-ODLneVT6kB77eTsjYOh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/context.rs#L81)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. docstring (unclear to me what exactly this does, just from the function name)
2. use stricter type
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 371 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHRxVX3765cyZH90TW:-ODLpA_s8NBle77lRKDn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/transaction/account_transaction.rs#L371)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 511 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHS9623OrN4ZeTIgdv:-ODLpt-Y2kNWa0vwhYbM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/transaction/account_transaction.rs#L511)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above (does `map` work?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-05 12:51 UTC, dorimedini-starkware reviewed
> Reviewed 7 of 8 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 15 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 360 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODLrUhg0qzlxmcaBM2B:-ODLrUhg0qzlxmcaBM2C:b-7s4s8d) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab670f8216f08bc1e3bb9fa6327f1d57252b03fa/crates/blockifier/src/transaction/account_transaction.rs#L360)):*
> ```XML
>             Ok(self
>                 .validate_tx(state, tx_context, remaining_validation_gas, limit_steps_by_resources)?
>                 .inspect(|call_info| {
> ```

cool!



_Code quote:_
```XML
inspect(
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 498 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODLrgjV7HhESRUWsaz4:-ODLrgjW8UUMotwnBNjz:b-fmza9b) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab670f8216f08bc1e3bb9fa6327f1d57252b03fa/crates/blockifier/src/transaction/account_transaction.rs#L498)):*
> ```XML
>                 .block_context
>                 .versioned_constants
>                 .sierra_gas_limit(&context.execution_mode),
> ```

can you add a `global_sierra_gas_limit` method on `EntryPointExecutionContext`? that way you won't need to write `context` twice (non-blocking)



_Suggestion:_
```XML
            context.global_sierra_gas_limit(),
```


<!-- Sent from Reviewable.io -->

2024-12-05 13:09 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 14 unresolved discussions (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-12-05 14:27 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: 8 of 10 files reviewed, 14 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1700 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL8DY55RywhbzZ6iFd:-ODMBCyZ9TEVPnSYAm-G:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8e25e395ad1b632dce9ff36399c8d755116d57c/crates/blockifier/src/transaction/account_transactions_test.rs#L1700)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should depend on the user bound, not the default initial gas.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 191 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHNqwY0uQ0a1HfjMC3:-ODMCwp_5kw0peDPaZrs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/transaction/transactions_test.rs#L191)):*
> ```XML
>         ValidResourceBounds::AllResources(bounds) => Some(bounds.l2_gas.max_amount),
>     }
> }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-05 14:37 UTC, aner-starkware commented
*[`crates/blockifier/src/transaction/transactions_test.rs` line 167 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHNXhMEmCmTwDvIQ6y:-ODMFNKv-tEmTocZODfh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/transaction/transactions_test.rs#L167)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this fixture should depend on the VC ==> depend on the block context.
I see other tests here use the static VC but if you have access to a block context object, you should use it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-05 14:48 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: 8 of 10 files reviewed, 14 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 504 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHNKssCtwehgXkR1dO:-ODMH9fFDxvM7terUFsp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/transaction/transactions_test.rs#L504)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use the versioned constants from the block context
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 511 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHNSJj0xmis6loEJ2X:-ODMHAC51J1qaU8UH2Kl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/transaction/transactions_test.rs#L511)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use the versioned constants from the block context
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 528 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODHOB8IB_sKNCPgdw0D:-ODMHAxK3P-YCUYuhUgp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d7addc7e198c2955214e222817f94d7f630d035/crates/blockifier/src/transaction/transactions_test.rs#L528)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use the versioned constants from the block context
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 536 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL5OJz-VrSM07Pybdl:-ODMHcxa6O0Xy7GFGTjo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8e25e395ad1b632dce9ff36399c8d755116d57c/crates/blockifier/src/transaction/transactions_test.rs#L536)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 547 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL5x11AOw8nutszP7P:-ODMHdFHEqxGNKD8JoTX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8e25e395ad1b632dce9ff36399c8d755116d57c/crates/blockifier/src/transaction/transactions_test.rs#L547)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete dead code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-05 15:03 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 2 files at r12, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 7 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 529 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL55QP-vwPCEnqJ55S:-ODMKlWqAZyFMoRdVDF1:bqz19zt) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8e25e395ad1b632dce9ff36399c8d755116d57c/crates/blockifier/src/transaction/transactions_test.rs#L529)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how is this working?
currently, inner calls of cairo0 (step-mode -> step-mode) should have `default_initial_gas - gas_consumed`, why do inner calls also have the default initial gas?
maybe because, if the account version is cairo0, then `tracked_resource` is steps, so you enter the `if` below and subtract the execute gas consumed; please combine the two `if`s for clarity (put this `if` inside the below `if`)
</blockquote></details>

nevermind... inner calls should have default_initial_gas without the consumed subtracted
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 560 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODL6GgRCMIbQIQWjmRb:-ODMKwiC3HWNXA6Vtode:b-srzn50) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8e25e395ad1b632dce9ff36399c8d755116d57c/crates/blockifier/src/transaction/transactions_test.rs#L560)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

similar to the Q above: why would the inner call not have some gas deducted? if the parent call is step mode, the inner call initial gas currently subtracts something (unless someone already changed this...?)
</blockquote></details>

nevermind, same as above
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1701 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMJ48C5nDwsZqw9okg:-ODMJ48C5nDwsZqw9okh:bay3pv4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4035eced2862d44d20bd4bef618d9b4c967525c/crates/blockifier/src/transaction/account_transactions_test.rs#L1701)):*
> ```XML
>         .min(user_gas_bound - GasAmount(validate_gas_consumed))
>         .0
>         + 1;
> ```

you mean: the test checks curr_initial_gas < prev?
can it work with the +1 inside the `min`?
otherwise we end up with an initial gas value that can't actually exist in this case (max execution gas + 1), right?



_Suggestion:_
```XML
    // minus the gas consumed by validate. Need to add 1 as the check is strictly less than.
    let mut prev_initial_gas = block_context
        .versioned_constants
        .max_execution_sierra_gas()
        .min(user_gas_bound - GasAmount(validate_gas_consumed) + GasAmount(1))
        .0;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 179 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMJenc0_ibAy0Lp0v1:-ODMJenc0_ibAy0Lp0v2:b-hmeuuv) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4035eced2862d44d20bd4bef618d9b4c967525c/crates/blockifier/src/transaction/transactions_test.rs#L179)):*
> ```XML
>         None => VERSIONED_CONSTANTS.default_initial_gas_amount(),
>     }
> }
> ```

for consistency in `expected_validate_call_info` (see below)



_Suggestion:_
```XML
fn default_initial_gas_amount(versioned_constants: Option<&VersionedConstants>) -> GasAmount {
    match versioned_constants {
        Some(versioned_constants) => versioned_constants.default_initial_gas_amount(),
        None => VERSIONED_CONSTANTS.default_initial_gas_amount(),
    }
}
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 247 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMK1SECxmABeTGZdFL:-ODMK1SECxmABeTGZdFM:bdkvtg0) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd614eb5450ddab82a98603f472ace990da9f9ad/crates/blockifier/src/transaction/transactions_test.rs#L247)):*
> ```XML
>         CairoVersion::Cairo1 => match tracked_resource {
>             TrackedResource::CairoSteps => {
>                 default_initial_gas_amount(None).min(VERSIONED_CONSTANTS.validate_max_sierra_gas).0
> ```

see above + this value depends on the currently used VC - the VC isn't injected to this function but be consistent?



_Suggestion:_
```XML
default_initial_gas_amount(VERSIONED_CONSTANTS).min(VERSIONED_CONSTANTS.validate_max_sierra_gas).0
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 247 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMKGccBp_aBwXXK7YL:-ODMKGccBp_aBwXXK7YM:b-in0b84) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd614eb5450ddab82a98603f472ace990da9f9ad/crates/blockifier/src/transaction/transactions_test.rs#L247)):*
> ```XML
>         CairoVersion::Cairo1 => match tracked_resource {
>             TrackedResource::CairoSteps => {
>                 default_initial_gas_amount(None).min(VERSIONED_CONSTANTS.validate_max_sierra_gas).0
> ```

if this is a cairo1 contract but it is a "cairo-steps" tracked contract - the initial gas should be V+E, why is the `min` here?



_Code quote:_
```XML
        CairoVersion::Cairo1 => match tracked_resource {
            TrackedResource::CairoSteps => {
                default_initial_gas_amount(None).min(VERSIONED_CONSTANTS.validate_max_sierra_gas).0
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 252 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMKR8J---h1wXaH3jZ:-ODMKR8J---h1wXaH3j_:b2rpthi) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd614eb5450ddab82a98603f472ace990da9f9ad/crates/blockifier/src/transaction/transactions_test.rs#L252)):*
> ```XML
>                 user_initial_gas
>                     .unwrap_or(default_initial_gas_amount(None))
>                     .min(VERSIONED_CONSTANTS.validate_max_sierra_gas)
> ```

ditto (see above)



_Suggestion:_
```XML
                    .unwrap_or(default_initial_gas_amount(VERSIONED_CONSTANTS))
                    .min(VERSIONED_CONSTANTS.validate_max_sierra_gas)
```


<!-- Sent from Reviewable.io -->

2024-12-05 15:40 UTC, aner-starkware commented
*[`crates/blockifier/src/transaction/transactions_test.rs` line 247 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMK1SECxmABeTGZdFL:-ODMTWSA-hpzjI6LlOEy:b-8wxnm7) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd614eb5450ddab82a98603f472ace990da9f9ad/crates/blockifier/src/transaction/transactions_test.rs#L247)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above + this value depends on the currently used VC - the VC isn't injected to this function but be consistent?
</blockquote></details>

What's above? It's the `block_context` that's injected - if there's no `block_context`, we take the default `VERSIONED_CONSTANTS`


<!-- Sent from Reviewable.io -->

2024-12-05 15:44 UTC, aner-starkware commented
*[`crates/blockifier/src/transaction/transactions_test.rs` line 247 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMK1SECxmABeTGZdFL:-ODMTqm7458R-9nGR9jy:b-ae7ey6) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd614eb5450ddab82a98603f472ace990da9f9ad/crates/blockifier/src/transaction/transactions_test.rs#L247)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

What's above? It's the `block_context` that's injected - if there's no `block_context`, we take the default `VERSIONED_CONSTANTS`
</blockquote></details>

Injecting the VC makes no sense, it would be better to then just delete this function and write out everything; I did rename the function to make it clearer though.


<!-- Sent from Reviewable.io -->

2024-12-05 15:46 UTC, aner-starkware commented
*[`crates/blockifier/src/transaction/transactions_test.rs` line 252 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMKR8J---h1wXaH3jZ:-ODMUw_e9qxeTFFImh1W:b6r0a5f) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd614eb5450ddab82a98603f472ace990da9f9ad/crates/blockifier/src/transaction/transactions_test.rs#L252)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto (see above)
</blockquote></details>

Renamed; should I delete this function altogether? 


<!-- Sent from Reviewable.io -->

2024-12-05 15:50 UTC, aner-starkware commented
*[`crates/blockifier/src/transaction/transactions_test.rs` line 179 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMJenc0_ibAy0Lp0v1:-ODMVhjg6jqqA7GmSRRS:bdttks9) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4035eced2862d44d20bd4bef618d9b4c967525c/crates/blockifier/src/transaction/transactions_test.rs#L179)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

for consistency in `expected_validate_call_info` (see below)
</blockquote></details>

This makes no sense to me. I think we should either keep the function as is or just write everything out inline.


<!-- Sent from Reviewable.io -->

2024-12-05 15:51 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-12-08 08:36 UTC, dorimedini-starkware reviewed
> Reviewed 9 of 9 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-12-08 08:43 UTC, aner-starkware commented
*[`crates/blockifier/src/transaction/transactions_test.rs` line 247 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMKGccBp_aBwXXK7YL:-OD_Qfwr65RA43JvNdgD:b3nyuta) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd614eb5450ddab82a98603f472ace990da9f9ad/crates/blockifier/src/transaction/transactions_test.rs#L247)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if this is a cairo1 contract but it is a "cairo-steps" tracked contract - the initial gas should be V+E, why is the `min` here?
</blockquote></details>

Done.  However, apparently, this isn't checked anywhere.


<!-- Sent from Reviewable.io -->

2024-12-08 08:58 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 247 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODMKGccBp_aBwXXK7YL:-OD_UEq877F3UtAN2vZN:b-3mho9e) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd614eb5450ddab82a98603f472ace990da9f9ad/crates/blockifier/src/transaction/transactions_test.rs#L247)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.  However, apparently, this isn't checked anywhere.
</blockquote></details>

Yes, please cover this case in your unit tests


<!-- Sent from Reviewable.io -->

2024-12-08 16:02 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 252 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODb-Fn5-P-NBfzFnQON:-ODb-Fn5-P-NBfzFnQOO:b-czi5x0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0c7871c9b349511289e90e03d2c62da4fb2f61c/crates/blockifier/src/versioned_constants.rs#L252)):*
> ```XML
> 
>     /// Default initial gas amount when L2 gas is not provided.
>     pub fn default_initial_gas_amount(&self) -> u64 {
> ```

Hmmm, how about making this a function of the resource bounds?
I don't want to get confused with the other default



_Code quote:_
```XML
pub fn default_initial_gas_amount(&self) -> u64 {
```


<!-- Sent from Reviewable.io -->

2024-12-08 16:47 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 252 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODb-Fn5-P-NBfzFnQON:-ODb9g890_1feWEWv2BR:bk54bwr) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0c7871c9b349511289e90e03d2c62da4fb2f61c/crates/blockifier/src/versioned_constants.rs#L252)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Hmmm, how about making this a function of the resource bounds?
I don't want to get confused with the other default
</blockquote></details>

WDYM?
this function is a function of the versioned constants, resource bounds (a) are irrelevant and (b) don't have access to VC


<!-- Sent from Reviewable.io -->

2024-12-08 17:29 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 252 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODb-Fn5-P-NBfzFnQON:-ODbIRtU1lpphyfc76ro:bvap8l6) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0c7871c9b349511289e90e03d2c62da4fb2f61c/crates/blockifier/src/versioned_constants.rs#L252)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM?
this function is a function of the versioned constants, resource bounds (a) are irrelevant and (b) don't have access to VC
</blockquote></details>

They are relevant. The suggestion is only for readability. E.g.,
```rust
fn get_initial_sierra_gas(self, vc){
    match &self {
        ValidResourceBounds::L1Gas(_) => vs.validate_gas() + vs.execute_gas(),
        ValidResourceBounds::AllResources(l2_gas, ...) => l2_gas
    }
}
```

Alternatively, you can rename `default_initial_gas_amount` to something more specific. 


<!-- Sent from Reviewable.io -->

2024-12-08 17:31 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 252 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODb-Fn5-P-NBfzFnQON:-ODbJjZp9L_I6zg6jGdI:b8no1nh) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0c7871c9b349511289e90e03d2c62da4fb2f61c/crates/blockifier/src/versioned_constants.rs#L252)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

They are relevant. The suggestion is only for readability. E.g.,
```rust
fn get_initial_sierra_gas(self, vc){
    match &self {
        ValidResourceBounds::L1Gas(_) => vs.validate_gas() + vs.execute_gas(),
        ValidResourceBounds::AllResources(l2_gas, ...) => l2_gas
    }
}
```

Alternatively, you can rename `default_initial_gas_amount` to something more specific.
</blockquote></details>

Or make it a function of the tx context


<!-- Sent from Reviewable.io -->

2024-12-09 14:46 UTC, aner-starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 252 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODb-Fn5-P-NBfzFnQON:-ODfsFX9BioEtUoiMZN3:b-frprk1) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0c7871c9b349511289e90e03d2c62da4fb2f61c/crates/blockifier/src/versioned_constants.rs#L252)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Or make it a function of the tx context
</blockquote></details>

There's already the function `initial_sierra_gas` in the tx context; maybe that is what you're referring to?


<!-- Sent from Reviewable.io -->

2024-12-09 16:49 UTC, aner-starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 252 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODb-Fn5-P-NBfzFnQON:-ODgIe2-3UGoS7Ph5LAA:bw2rmf5) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0c7871c9b349511289e90e03d2c62da4fb2f61c/crates/blockifier/src/versioned_constants.rs#L252)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe rename to `initial_gas_without_user_l2_bound` or something
</blockquote></details>

Which one? The `initial_sierra_gas` deals with both cases. This function is indeed for the case with no user `l2_bound`, but I actually think the other way around - the function `default_initial_gas_cost` should probably be renamed to `inifite_gas_for_vm_mode` or something.


<!-- Sent from Reviewable.io -->

2024-12-09 16:59 UTC, Yoni-Starkware submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 252 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODb-Fn5-P-NBfzFnQON:-ODgM3ua0iZbhvAcZo0H:b-8jomaj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0c7871c9b349511289e90e03d2c62da4fb2f61c/crates/blockifier/src/versioned_constants.rs#L252)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Which one? The `initial_sierra_gas` deals with both cases. This function is indeed for the case with no user `l2_bound`, but I actually think the other way around - the function `default_initial_gas_cost` should probably be renamed to `inifite_gas_for_vm_mode` or something.
</blockquote></details>

Either way is fine by me :)


<!-- Sent from Reviewable.io -->

2024-12-10 14:25 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 14:32 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 10 files at r22, 9 of 9 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 14:41 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 15:07 UTC, aner-starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 252 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/2397#-ODb-Fn5-P-NBfzFnQON:-ODl66V6EQc2vinaHFcf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0c7871c9b349511289e90e03d2c62da4fb2f61c/crates/blockifier/src/versioned_constants.rs#L252)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Either way is fine by me :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-15 08:30 UTC, dorimedini-starkware approved these changes
> Reviewed 12 of 12 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-16 13:03 UTC, aner-starkware reviewed
> Dismissed @Yoni-Starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2397)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-12-16 13:04 UTC, merged