feat(papyrus_storage): get versioned casm
starkware-libs/sequencer pull request #2420
Opened 2024-12-03 09:43 UTC by AvivYossef-starkware

2024-12-03 09:43 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2420)
<!-- Reviewable:end -->

2024-12-03 09:43 UTC, AvivYossef-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2420** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2313?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#2383](https://github.com/starkware-libs/sequencer/pull/2383) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2383?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-03 10:18 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODB-Oeo53NRjDj7flC0:-ODB-Oeo53NRjDj7flC1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8f3cb53a02675eb8271c41a83d7bdc013d679bd/crates/papyrus_storage/src/compiled_class.rs#L66)):*
> ```XML
>     /// Returns the Cairo assembly of a class given its Sierra class hash.
>     fn get_casm(&self, class_hash: &ClassHash) -> StorageResult<Option<CasmContractClass>>;
>     /// Returns the Cairo assembly of a class and his sierra version given its Sierra class hash.
> ```





_Suggestion:_
```XML
its
```
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODB-f6kDZ6V8s_bv3ts:-ODB-f6kDZ6V8s_bv3tt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8f3cb53a02675eb8271c41a83d7bdc013d679bd/crates/papyrus_storage/src/compiled_class.rs#L101)):*
> ```XML
>             }
>         }
>         Ok(None)
> ```





_Suggestion:_
```XML
        match (self.get_casm(class_hash)?, self.get_class(class_hash)?) {
            (Some(casm), Some(sierra)) => {
                let sierra_version = SierraVersion::extract_from_program(&sierra.sierra_program)?;
                Ok(Some((casm, sierra_version)))
            }
            (_, _) => Ok(None)
        }
```
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODB-xZMBmkZjf4cZ3iK:-ODB-xZMBmkZjf4cZ3iL:b-f54cfr) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8f3cb53a02675eb8271c41a83d7bdc013d679bd/crates/papyrus_storage/src/compiled_class.rs#L101)):*
> ```XML
>             }
>         }
>         Ok(None)
> ```

@AvivYossef-starkware  will this function be called in the blockifier for every entry point in a running tx?
if so, @Yoni-Starkware is this an ok performance hit?



_Code quote:_
```XML
    fn get_versioned_casm(&self, class_hash: &ClassHash) -> StorageResult<Option<VersionedCasm>> {
        // TODO(Aviv): Consider adding a dedicated table to store Sierra versions for better
        // organization and performance.
        if let Some(casm) = self.get_casm(class_hash)? {
            if let Some(sierra) = self.get_class(class_hash)? {
                let sierra_version = SierraVersion::extract_from_program(&sierra.sierra_program)?;
                return Ok(Some((casm, sierra_version)));
            }
        }
        Ok(None)
```
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 756 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODB0Wo04J726mR94uvw:-ODB0Wo04J726mR94uvx:b32zu4z) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8f3cb53a02675eb8271c41a83d7bdc013d679bd/crates/papyrus_storage/src/serialization/serializers.rs#L756)):*
> ```XML
>         serde_json::from_value(serde_json::Value::deserialize_from(bytes)?).ok()
>     }
> }
> ```

1. this is not a primitive type, why is it in the primitive types section?
2. why not use `auto_storage_serde!`?



_Code quote:_
```XML
impl StorageSerde for SierraVersion {
    fn serialize_into(&self, res: &mut impl std::io::Write) -> Result<(), StorageSerdeError> {
        serde_json::to_value(self)?.serialize_into(res)
    }

    fn deserialize_from(bytes: &mut impl std::io::Read) -> Option<Self> {
        serde_json::from_value(serde_json::Value::deserialize_from(bytes)?).ok()
    }
}
```


<!-- Sent from Reviewable.io -->

2024-12-03 10:57 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODB-xZMBmkZjf4cZ3iK:-ODB4nmvE7qfwlDjbDy5:b-1x59q) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8f3cb53a02675eb8271c41a83d7bdc013d679bd/crates/papyrus_storage/src/compiled_class.rs#L101)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@AvivYossef-starkware  will this function be called in the blockifier for every entry point in a running tx?
if so, @Yoni-Starkware is this an ok performance hit?
</blockquote></details>

No, it called only after Chache miss,
[This struct](https://github.com/starkware-libs/sequencer/blob/ef9e2af7ad9c50eca091e296e2c9416272cf3025/crates/papyrus_state_reader/src/papyrus_state.rs#L25) has a cache of 
`RunnableCompiledClass` and I'll add it also the `SierraVersion`
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 756 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODB0Wo04J726mR94uvw:-ODB5-8SDSlc3iA6Cuqb:b-lwxqbk) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8f3cb53a02675eb8271c41a83d7bdc013d679bd/crates/papyrus_storage/src/serialization/serializers.rs#L756)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. this is not a primitive type, why is it in the primitive types section?
2. why not use `auto_storage_serde!`?
</blockquote></details>

For using `auto_storage_serde!` I should copy the struct definition. 
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODB-Oeo53NRjDj7flC0:-ODB8IL82fiIjmuqOfKt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8f3cb53a02675eb8271c41a83d7bdc013d679bd/crates/papyrus_storage/src/compiled_class.rs#L66)):*
> ```XML
>     /// Returns the Cairo assembly of a class given its Sierra class hash.
>     fn get_casm(&self, class_hash: &ClassHash) -> StorageResult<Option<CasmContractClass>>;
>     /// Returns the Cairo assembly of a class and his sierra version given its Sierra class hash.
> ```

Done.
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODB-f6kDZ6V8s_bv3ts:-ODB8EDx9iiGZ8Rk6Z5W:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8f3cb53a02675eb8271c41a83d7bdc013d679bd/crates/papyrus_storage/src/compiled_class.rs#L101)):*
> ```XML
>             }
>         }
>         Ok(None)
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-03 11:38 UTC, Yoni-Starkware requested changes
You need to support `get_sierra`

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-:-ODBJ7IY2WJZOr-1BibT:bfyi2s7)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-03 11:41 UTC, Yoni-Starkware reviewed
@avi-starkware FYI

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-:-ODBJme50E4_BoZiqQNV:bahc314)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-03 15:37 UTC, Yoni-Starkware requested changes
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/papyrus_storage/src/compiled_class.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODC9K2J4YpxG0XZRWiP:-ODC9K2J4YpxG0XZRWiQ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/865d1dc15d36ca702ade2e71e87d103b89ebefb1/crates/papyrus_storage/src/compiled_class.rs#L66)):*
> ```XML
>     /// Returns the Cairo assembly of a class given its Sierra class hash.
>     fn get_casm(&self, class_hash: &ClassHash) -> StorageResult<Option<CasmContractClass>>;
>     /// Returns the Cairo assembly of a class and its sierra contract class given its Sierra class hash.
> ```





_Suggestion:_
```XML
d its Sierra con
```


<!-- Sent from Reviewable.io -->

2024-12-04 08:16 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODFipPA9YOAJQDxJqc_:-ODFipPA9YOAJQDxJqca:b31zws7) ([raw file](https://github.com/starkware-libs/sequencer/blob/2fdc7e4ee944ce3a27bdcd489594d4d10cd32650/crates/blockifier/src/execution/contract_class.rs#L71)):*
> ```XML
> }
> 
> pub type VersionedRunnableCompiledClass = (RunnableCompiledClass, SierraVersion);
> ```

the get_compiled_class_inner return value uses a dummy value for the sierra version in the cairo0 case; why not make this type an enum? so you won't need the dummy value?



_Suggestion:_
```XML
pub enum VersionedRunnableCompiledClass {
    Cairo0(RunnableCompiledClass),
    Cairo1((RunnableCompiledClass, SierraVersion)),
}
```


<!-- Sent from Reviewable.io -->

2024-12-04 09:56 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODFipPA9YOAJQDxJqc_:-ODFnf0F48PwfZZt56TG:bb70w76) ([raw file](https://github.com/starkware-libs/sequencer/blob/6475cf150fe8f6ac452ab5aa38788af81879e2d9/crates/blockifier/src/execution/contract_class.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the get_compiled_class_inner return value uses a dummy value for the sierra version in the cairo0 case; why not make this type an enum? so you won't need the dummy value?
</blockquote></details>

Nice
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 756 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODB0Wo04J726mR94uvw:-ODBuLLwDs2HXV3jydfI:b-yxytvc) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8f3cb53a02675eb8271c41a83d7bdc013d679bd/crates/papyrus_storage/src/serialization/serializers.rs#L756)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is the standard practice in this module iiuc
</blockquote></details>

We don't need it 
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODC9K2J4YpxG0XZRWiP:-ODFy2gNBkDUAcQMUpnG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/865d1dc15d36ca702ade2e71e87d103b89ebefb1/crates/papyrus_storage/src/compiled_class.rs#L66)):*
> ```XML
>     /// Returns the Cairo assembly of a class given its Sierra class hash.
>     fn get_casm(&self, class_hash: &ClassHash) -> StorageResult<Option<CasmContractClass>>;
>     /// Returns the Cairo assembly of a class and its sierra contract class given its Sierra class hash.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-04 10:24 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODGBSA-732H8WnzhKOX:-ODGBSA-732H8WnzhKOY:bnhcbfn) ([raw file](https://github.com/starkware-libs/sequencer/blob/865d1dc15d36ca702ade2e71e87d103b89ebefb1/crates/papyrus_state_reader/src/papyrus_state.rs#L87)):*
> ```XML
>             Some(starknet_api_contract_class) => Ok((
>                 CompiledClassV0::try_from(starknet_api_contract_class)?.into(),
>                 SierraVersion::zero(),
> ```

is the `zero` "version" still needed somewhere?



_Code quote:_
```XML
SierraVersion::zero()
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODGB1oC1e8YOkiVq7kR:-ODGB1oC1e8YOkiVq7kS:b-6pncnn) ([raw file](https://github.com/starkware-libs/sequencer/blob/18aa37e696b092ce4e9953b8359a423dcc0fa5df/crates/blockifier/src/execution/contract_class.rs#L85)):*
> ```XML
>                 runnable_compiled_class
>             }
>             VersionedRunnableCompiledClass::Cairo1((runnable_compiled_class, __)) => {
> ```

single underscore



_Suggestion:_
```XML
(runnable_compiled_class, _)
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODGAq5p6lmGawG7KBcD:-ODGAq5p6lmGawG7KBcE:b7tyje6) ([raw file](https://github.com/starkware-libs/sequencer/blob/18aa37e696b092ce4e9953b8359a423dcc0fa5df/crates/blockifier/src/execution/contract_class.rs#L88)):*
> ```XML
>                 runnable_compiled_class
>             }
>         }
> ```

does this work?



_Suggestion:_
```XML
        match versioned_runnable_compiled_class {
            VersionedRunnableCompiledClass::Cairo0(runnable_compiled_class)
            | VersionedRunnableCompiledClass::Cairo1((runnable_compiled_class, _)) => {
                runnable_compiled_class
            }
        }
```


<!-- Sent from Reviewable.io -->

2024-12-05 10:10 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODGB1oC1e8YOkiVq7kR:-ODGEtX-DynHnoJxyR7k:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/18aa37e696b092ce4e9953b8359a423dcc0fa5df/crates/blockifier/src/execution/contract_class.rs#L85)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

single underscore
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODGAq5p6lmGawG7KBcD:-ODGErVm9n9aNjkVBZ3w:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/18aa37e696b092ce4e9953b8359a423dcc0fa5df/crates/blockifier/src/execution/contract_class.rs#L88)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work?
</blockquote></details>

Yes
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODGBSA-732H8WnzhKOX:-ODGEIMC2lUG7PRKFgXX:b9rtam7) ([raw file](https://github.com/starkware-libs/sequencer/blob/865d1dc15d36ca702ade2e71e87d103b89ebefb1/crates/papyrus_state_reader/src/papyrus_state.rs#L87)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is the `zero` "version" still needed somewhere?
</blockquote></details>

Yes, it's now part of the class info, and we use it to represent the Sierra version of deprecated declare tx. 


<!-- Sent from Reviewable.io -->

2024-12-05 10:27 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-:-ODLM43w2hwZtXFX1169:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-05 11:41 UTC, DvirYo-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class.rs` line 66 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODL_F6zEqVS_vRRsgMy:-ODL_F6zEqVS_vRRsgMz:bdrgy67) ([raw file](https://github.com/starkware-libs/sequencer/blob/572f15e67be1da5856691c57fbdafdec1b4c7591/crates/papyrus_storage/src/compiled_class.rs#L66)):*
> ```XML
>     /// Returns the Cairo assembly of a class given its Sierra class hash.
>     fn get_casm(&self, class_hash: &ClassHash) -> StorageResult<Option<CasmContractClass>>;
>     /// Returns the Cairo assembly of a class and its Sierra contract class given its Sierra class
> ```

This function does not add functionality or make things more efficient. You can add an external utility that reads Sierra, then reads Casm and returns them both.
But, if, for some reason, it makes your life easier, it is fine for me.
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 95 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODLbslnEDyKcxzJZCk0:-ODLbslnEDyKcxzJZCk1:bwrosmp) ([raw file](https://github.com/starkware-libs/sequencer/blob/572f15e67be1da5856691c57fbdafdec1b4c7591/crates/papyrus_storage/src/compiled_class.rs#L95)):*
> ```XML
>         casm_location.map(|location| self.file_handlers.get_casm_unchecked(location)).transpose()
>     }
> ```

Test this function
___
*[`crates/papyrus_storage/src/lib.rs` line 592 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODLb5Ai3m9qtSqVuoyg:-ODLb5Ai3m9qtSqVuoyh:bxw9lhi) ([raw file](https://github.com/starkware-libs/sequencer/blob/572f15e67be1da5856691c57fbdafdec1b4c7591/crates/papyrus_storage/src/lib.rs#L592)):*
> ```XML
>     StorageVersionInconsistency(#[from] StorageVersionError),
>     #[error("The table {table_name} is unused under the {storage_scope:?} storage scope.")]
>     ScopeError { table_name: String, storage_scope: StorageScope },
> ```

What is the reason for the new error variant?


<!-- Sent from Reviewable.io -->

2024-12-05 12:11 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class.rs` line 95 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODLbslnEDyKcxzJZCk0:-ODLhAL38q64KcgpjqSn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/572f15e67be1da5856691c57fbdafdec1b4c7591/crates/papyrus_storage/src/compiled_class.rs#L95)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Test this function
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/lib.rs` line 592 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODLb5Ai3m9qtSqVuoyg:-ODLhinz6-f2NblTEp4r:b36tfqo) ([raw file](https://github.com/starkware-libs/sequencer/blob/572f15e67be1da5856691c57fbdafdec1b4c7591/crates/papyrus_storage/src/lib.rs#L592)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

What is the reason for the new error variant?
</blockquote></details>

Thanks, we don't need it :)


<!-- Sent from Reviewable.io -->

2024-12-05 12:46 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/class_test.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODLqsTa0coHlK4kpPWa:-ODLqsTb-NOaQJ-geGEp:b7yvg6j) ([raw file](https://github.com/starkware-libs/sequencer/blob/241fc85553fe1fc4d01e451c536ee5866456080f/crates/papyrus_storage/src/class_test.rs#L17)):*
> ```XML
> 
> #[test]
> pub fn append_classes_writes_correct_data() {
> ```

why do you need `pub`  in a test...?



_Code quote:_
```XML
pub
```


<!-- Sent from Reviewable.io -->

2024-12-05 12:58 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/class_test.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODLqsTa0coHlK4kpPWa:-ODLtGmO9nl-VpNH510d:b2ni9hp) ([raw file](https://github.com/starkware-libs/sequencer/blob/241fc85553fe1fc4d01e451c536ee5866456080f/crates/papyrus_storage/src/class_test.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need `pub`  in a test...?
</blockquote></details>

ops


<!-- Sent from Reviewable.io -->

2024-12-05 13:08 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-05 14:05 UTC, DvirYo-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 33 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODM7rP322IFnVJgmMEe:-ODM7rP322IFnVJgmMEf:b-7o49r2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bf986955e952d0a8277670c9f10ab099cd6c5ef/crates/papyrus_storage/src/compiled_class_test.rs#L33)):*
> ```XML
> }
> 
> #[test]
> ```

Test also the case when you return `None`
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 36 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODM7V4G0FXJojlKIU3A:-ODM7V4G0FXJojlKIU3B:b-6tsnln) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bf986955e952d0a8277670c9f10ab099cd6c5ef/crates/papyrus_storage/src/compiled_class_test.rs#L36)):*
> ```XML
> fn test_casm_and_sierra() {
>     let test_class_hash = ClassHash::default();
>     let casm_json = read_json_file("compiled_class.json");
> ```

Use `get_test_instance` instead of reading from a file.


<!-- Sent from Reviewable.io -->

2024-12-05 14:05 UTC, DvirYo-starkware reviewed
> Reviewed 1 of 3 files at r5, 1 of 3 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-05 14:47 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-08 09:19 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 33 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODM7rP322IFnVJgmMEe:-OD_TXO30be-6Yu2zDfO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bf986955e952d0a8277670c9f10ab099cd6c5ef/crates/papyrus_storage/src/compiled_class_test.rs#L33)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Test also the case when you return `None`
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 36 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODM7V4G0FXJojlKIU3A:-OD_TXvVAsHooS8tM-JS:b-iktnrk) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bf986955e952d0a8277670c9f10ab099cd6c5ef/crates/papyrus_storage/src/compiled_class_test.rs#L36)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Use `get_test_instance` instead of reading from a file.
</blockquote></details>

Done for CASM. w`get_test_instance`` has not been implemented for Sierra.


<!-- Sent from Reviewable.io -->

2024-12-08 12:37 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 4 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 6 unresolved discussions (waiting on @AvivYossef-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 88 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODaGP5x2AmZB1LSIcNf:-ODaGP5y-KyYhQqK4DZJ:b-2ef4h7) ([raw file](https://github.com/starkware-libs/sequencer/blob/ade6fb9acdbfcd619ab9d07955b446faf9756343/crates/papyrus_storage/src/compiled_class_test.rs#L88)):*
> ```XML
>     match expected_error {
>         Some(expected_message) => {
>             dbg!(&result);
> ```

necessary?



_Code quote:_
```XML
dbg!(&result);
```
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 90 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODaGTRY1QeIf4We0tm2:-ODaGTRY1QeIf4We0tm3:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ade6fb9acdbfcd619ab9d07955b446faf9756343/crates/papyrus_storage/src/compiled_class_test.rs#L90)):*
> ```XML
>             dbg!(&result);
>             // If Sierra XOR CASM exists
>             assert!(matches!(
> ```





_Suggestion:_
```XML
assert_matches!
```


<!-- Sent from Reviewable.io -->

2024-12-08 13:52 UTC, DvirYo-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 9 unresolved discussions (waiting on @AvivYossef-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 48 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODaXBka9tkj7xv2iAjj:-ODaXBka9tkj7xv2iAjk:b8hfxp5) ([raw file](https://github.com/starkware-libs/sequencer/blob/ade6fb9acdbfcd619ab9d07955b446faf9756343/crates/papyrus_storage/src/compiled_class_test.rs#L48)):*
> ```XML
> ) {
>     // Initialize the RNG with a seed
>     let mut rng = ChaCha8Rng::seed_from_u64(0);
> ```

do like
`LocationInFile::get\_test\_instance(&mut get\_rng());`
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 58 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODaWfcA6fjlq3dbZnTs:-ODaWfcA6fjlq3dbZnTt:b-pwsjcz) ([raw file](https://github.com/starkware-libs/sequencer/blob/ade6fb9acdbfcd619ab9d07955b446faf9756343/crates/papyrus_storage/src/compiled_class_test.rs#L58)):*
> ```XML
>     let expected_casm = CasmContractClass::get_test_instance(&mut rng);
>     let sierra_json = read_json_file("class.json");
>     let expected_sierra: SierraContractClass = serde_json::from_value(sierra_json).unwrap();
> ```

Use `get_test_instance` also for Sierra. The fact that it is an invalid object doesn't matter here. If you have a very strong opinion use the Default
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 99 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODaXgU_AyD9ClGSZ0k5:-ODaXgU_AyD9ClGSZ0k6:b-fiu07y) ([raw file](https://github.com/starkware-libs/sequencer/blob/ade6fb9acdbfcd619ab9d07955b446faf9756343/crates/papyrus_storage/src/compiled_class_test.rs#L99)):*
> ```XML
>             let (casm, sierra) = result.unwrap().unwrap();
>             assert_eq!(casm, expected_casm);
>             let sierra_json = read_json_file("class.json");
> ```

why read here again?


<!-- Sent from Reviewable.io -->

2024-12-09 11:18 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 6 of 11 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 48 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODaXBka9tkj7xv2iAjj:-ODeIguu3Qz4H5HRK25b:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ade6fb9acdbfcd619ab9d07955b446faf9756343/crates/papyrus_storage/src/compiled_class_test.rs#L48)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

do like
`LocationInFile::get\_test\_instance(&mut get\_rng());`
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 58 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODaWfcA6fjlq3dbZnTs:-ODeDwEY04fJY_-VOIbH:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/ade6fb9acdbfcd619ab9d07955b446faf9756343/crates/papyrus_storage/src/compiled_class_test.rs#L58)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Use `get_test_instance` also for Sierra. The fact that it is an invalid object doesn't matter here. If you have a very strong opinion use the Default
</blockquote></details>

Done
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 88 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODaGP5x2AmZB1LSIcNf:-ODeTeN7AjktVRm42qtm:b32w12) ([raw file](https://github.com/starkware-libs/sequencer/blob/ade6fb9acdbfcd619ab9d07955b446faf9756343/crates/papyrus_storage/src/compiled_class_test.rs#L88)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

necessary?
</blockquote></details>

No
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 99 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODaXgU_AyD9ClGSZ0k5:-ODeIknGCZyynkmNDzyC:b-hfpv0l) ([raw file](https://github.com/starkware-libs/sequencer/blob/ade6fb9acdbfcd619ab9d07955b446faf9756343/crates/papyrus_storage/src/compiled_class_test.rs#L99)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

why read here again?
</blockquote></details>

removed
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 90 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODaGTRY1QeIf4We0tm2:-ODeTfH-4e6hB7sLTpty:ba3dfob) ([raw file](https://github.com/starkware-libs/sequencer/blob/ade6fb9acdbfcd619ab9d07955b446faf9756343/crates/papyrus_storage/src/compiled_class_test.rs#L90)):*
> ```XML
>             dbg!(&result);
>             // If Sierra XOR CASM exists
>             assert!(matches!(
> ```

Removed


<!-- Sent from Reviewable.io -->

2024-12-09 12:36 UTC, dorimedini-starkware approved these changes
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 8 unresolved discussions (waiting on @AvivYossef-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 40 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODfPPzMCjLAYIU-Qzw4:-ODfPPzMCjLAYIU-Qzw5:bcssfhr) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/papyrus_storage/src/compiled_class_test.rs#L40)):*
> ```XML
> #[case::only_sierra_exists(false, true)]
> #[case::neither_exists(false, false)]
> fn test_casm_and_sierra(#[case] has_casm: bool, #[case] has_sierra: bool) {
> ```

now you can use cartesian testing :)
non-blocking



_Suggestion:_
```XML
fn test_casm_and_sierra(#[values(true, false)] has_casm: bool, #[values(true, false)] has_sierra: bool) {
```
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 103 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODfPGb6EKyjlhDyzNWJ:-ODfPGb76FDWKPdU0t9v:baf6zlm) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/papyrus_storage/src/compiled_class.rs#L103)):*
> ```XML
>         let casm = self.get_casm(class_hash)?;
>         let sierra = self.get_class(class_hash)?;
>         Ok((casm, sierra))
> ```

non-blocking



_Suggestion:_
```XML
        Ok((self.get_casm(class_hash)?, self.get_class(class_hash)?))
```


<!-- Sent from Reviewable.io -->

2024-12-10 07:06 UTC, Yoni-Starkware requested changes
Must have a Py side here, the get_sierra_and_casm should break python.

> Reviewed 1 of 1 files at r9, 1 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-:-ODjNy3T-bppdbPv-cct:b-84l25y)* status: all files reviewed, 11 unresolved discussions (waiting on @AvivYossef-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/papyrus_storage/src/compiled_class.rs` line 69 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODjNkb-DiGRlHOYfAPa:-ODjNkb-DiGRlHOYfAPb:bg5whac) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/papyrus_storage/src/compiled_class.rs#L69)):*
> ```XML
>     /// If both exist, returns `(Some(casm), Some(sierra))`. If neither, returns `(None, None)`.
>     /// If only one exists, returns `(Some, None)` or `(None, Some)`.
>     fn get_casm_and_sierra(
> ```

Should we use your util inside this func and let it return 
`Option<(CasmContractClass, SierraContractClass)>`
?



_Code quote:_
```XML
    /// Returns the CASM and Sierra contract classes for the given hash.
    /// If both exist, returns `(Some(casm), Some(sierra))`. If neither, returns `(None, None)`.
    /// If only one exists, returns `(Some, None)` or `(None, Some)`.
    fn get_casm_and_sierra(
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 62 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODjLsB70LFEGuGAkUfN:-ODjLsB70LFEGuGAkUfO:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/papyrus_state_reader/src/papyrus_state.rs#L62)):*
> ```XML
> 
>         if class_is_declared {
>             let (option_casm_compiled_class, option_sierra) = self
> ```





_Suggestion:_
```XML
let (option_casm, op
```
___
*[`crates/blockifier/src/state/errors.rs` line 39 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODjMEDG9mAVBB_zplpL:-ODjMEDG9mAVBB_zplpM:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/blockifier/src/state/errors.rs#L39)):*
> ```XML
> /// Converts CASM and Sierra options into a Result, raising a `CasmAndSierraMismatch` error
> /// when there is an inconsistency.
> pub fn validate_casm_and_sierra(
> ```





_Suggestion:_
```XML
/// Ensures that the CASM and Sierra classes are coupled - Meaning that they both exist or are missing. 
/// Returns a `CasmAndSierraMismatch` error when there is an inconsistency in their existence.
pub fn couple_casm_and_sierra(
```
___
*[`crates/blockifier/src/state/errors.rs` line 42 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODjLuDS9TQmntULx4J8:-ODjLuDS9TQmntULx4J9:b-qjyp2u) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/blockifier/src/state/errors.rs#L42)):*
> ```XML
>     class_hash: ClassHash,
>     casm_opt: Option<CasmContractClass>,
>     sierra_opt: Option<SierraContractClass>,
> ```

Be consistent



_Suggestion:_
```XML
    option_casm: Option<CasmContractClass>,
    option_sierra: Option<SierraContractClass>,
```


<!-- Sent from Reviewable.io -->

2024-12-10 07:37 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 5 of 11 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class.rs` line 69 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODjNkb-DiGRlHOYfAPa:-ODjPpuKCBY-msgHQxdl:b-nj8497) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/papyrus_storage/src/compiled_class.rs#L69)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Should we use your util inside this func and let it return 
`Option<(CasmContractClass, SierraContractClass)>`
?
</blockquote></details>

This function is defined in Papyrus Storage and returns a `StorageResult`. 

@DvirYo-starkware mentioned that if either Sierra or Casm exists independently, it should not be considered a storage error since the storage allows them to be saved independently. Therefore, I use this utility in functions that return a `StateResult`.
___
*[`crates/blockifier/src/state/errors.rs` line 39 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODjMEDG9mAVBB_zplpL:-ODjTMRJ-C8XTotnYqaY:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/blockifier/src/state/errors.rs#L39)):*
> ```XML
> /// Converts CASM and Sierra options into a Result, raising a `CasmAndSierraMismatch` error
> /// when there is an inconsistency.
> pub fn validate_casm_and_sierra(
> ```

Done
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 62 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODjLsB70LFEGuGAkUfN:-ODjTGi_2LL8QA5a_e4P:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/papyrus_state_reader/src/papyrus_state.rs#L62)):*
> ```XML
> 
>         if class_is_declared {
>             let (option_casm_compiled_class, option_sierra) = self
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-10 08:15 UTC, dorimedini-starkware approved these changes
> Reviewed 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 9 unresolved discussions (waiting on @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 08:20 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 9 unresolved discussions (waiting on @AvivYossef-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/state/errors.rs` line 39 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODjMEDG9mAVBB_zplpL:-ODjdxe94lC9YtO8FBGi:b-4fmxk9) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/blockifier/src/state/errors.rs#L39)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

Rename the func name as well


<!-- Sent from Reviewable.io -->

2024-12-10 08:29 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/errors.rs` line 39 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODjMEDG9mAVBB_zplpL:-ODjfxps4MXLsruEXSap:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7763b88d222bd7955cae596708b1fe83262253ec/crates/blockifier/src/state/errors.rs#L39)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Rename the func name as well
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-10 08:38 UTC, dorimedini-starkware approved these changes
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 7 unresolved discussions (waiting on @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 08:57 UTC, AvivYossef-starkware reviewed
[python](https://github.com/starkware-industries/starkware/pull/36424)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-:-ODjmNzs3wg58oG_TFGL:b-hg6f3c)* status: all files reviewed, 7 unresolved discussions (waiting on @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 09:36 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 7 unresolved discussions (waiting on @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 10:34 UTC, DvirYo-starkware requested changes
> Reviewed 1 of 6 files at r14, 1 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 46 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODk6rHf38DojaOqvjK7:-ODk6rHf38DojaOqvjK8:b-f4eq4a) ([raw file](https://github.com/starkware-libs/sequencer/blob/447a92dfeb5b7eefabf8037ce22d6c0ad5c1c3cb/crates/papyrus_storage/src/compiled_class_test.rs#L46)):*
> ```XML
>     let ((reader, mut writer), _temp_dir) = get_test_storage();
>     let expected_casm = CasmContractClass::get_test_instance(&mut rng);
>     let expected_sierra = <SierraContractClass as GetTestInstance>::get_test_instance(&mut rng);
> ```

Why do you need the `<SierraContractClass as GetTestInstance>`? I think doing the same as in the CASM case will be enough
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 65 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODk5SrUAZRqFmt2G0MF:-ODk5SrUAZRqFmt2G0MG:b8ztxoh) ([raw file](https://github.com/starkware-libs/sequencer/blob/447a92dfeb5b7eefabf8037ce22d6c0ad5c1c3cb/crates/papyrus_storage/src/compiled_class.rs#L65)):*
> ```XML
> pub trait CasmStorageReader {
>     /// Returns the Cairo assembly of a class given its Sierra class hash.
>     fn get_casm(&self, class_hash: &ClassHash) -> StorageResult<Option<CasmContractClass>>;
> ```

Add  a new line here
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 67 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODk5fP1-rIWTKX9vZz5:-ODk5fP1-rIWTKX9vZz6:b-pbsl82) ([raw file](https://github.com/starkware-libs/sequencer/blob/447a92dfeb5b7eefabf8037ce22d6c0ad5c1c3cb/crates/papyrus_storage/src/compiled_class.rs#L67)):*
> ```XML
>     fn get_casm(&self, class_hash: &ClassHash) -> StorageResult<Option<CasmContractClass>>;
>     /// Returns the CASM and Sierra contract classes for the given hash.
>     /// If both exist, returns `(Some(casm), Some(sierra))`. If neither, returns `(None, None)`.
> ```

Consider each `if` in a new line
___
*[`crates/papyrus_storage/src/compiled_class.rs` line 97 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODk5zT85gQJYQ9PJSfQ:-ODk5zT85gQJYQ9PJSfR:b-46ilb2) ([raw file](https://github.com/starkware-libs/sequencer/blob/447a92dfeb5b7eefabf8037ce22d6c0ad5c1c3cb/crates/papyrus_storage/src/compiled_class.rs#L97)):*
> ```XML
>     }
> 
>     fn get_casm_and_sierra(
> ```

Just to make it clear, the call
`reader.get_casm_and_sierra(class_hash)?`
is totally equivalent to
`(reader.get_casm(class_hash)?, reader.get_sierra(class_hash)?)`

If I understand it correctly, I don't see any reason for this function. @Yoni-Starkware, if you approve, I'm fine with adding this.


<!-- Sent from Reviewable.io -->

2024-12-10 10:58 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/compiled_class.rs` line 97 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODk5zT85gQJYQ9PJSfQ:-ODkBlpM7QtRQYwX-LCH:bd6wmgl) ([raw file](https://github.com/starkware-libs/sequencer/blob/447a92dfeb5b7eefabf8037ce22d6c0ad5c1c3cb/crates/papyrus_storage/src/compiled_class.rs#L97)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Just to make it clear, the call
`reader.get_casm_and_sierra(class_hash)?`
is totally equivalent to
`(reader.get_casm(class_hash)?, reader.get_sierra(class_hash)?)`

If I understand it correctly, I don't see any reason for this function. @Yoni-Starkware, if you approve, I'm fine with adding this.
</blockquote></details>

Yes, its the same. 
___
*[`crates/papyrus_storage/src/compiled_class_test.rs` line 46 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2420#-ODk6rHf38DojaOqvjK7:-ODkAx3h3tw6vWgP2R3M:bkzkcpx) ([raw file](https://github.com/starkware-libs/sequencer/blob/447a92dfeb5b7eefabf8037ce22d6c0ad5c1c3cb/crates/papyrus_storage/src/compiled_class_test.rs#L46)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why do you need the `<SierraContractClass as GetTestInstance>`? I think doing the same as in the CASM case will be enough
</blockquote></details>

The compiler is uncertain whether to use the function defined in `GetTestInstance` or another option. Therefore, I needed to add it.


<!-- Sent from Reviewable.io -->

2024-12-10 11:00 UTC, Yoni-Starkware approved these changes
> Reviewed 1 of 6 files at r14, 2 of 3 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-10 11:12 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: all files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-12-10 12:52 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-15 08:18 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-15 15:25 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2420)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-15 19:02 UTC, merged

2024-12-15 19:02 UTC, AvivYossef-starkware commented
### Merge activity

* **Dec 15, 2:02 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420).