chore(starknet_batcher): remove sequncer address from block builder config
starkware-libs/sequencer pull request #2425
Opened 2024-12-03 10:59 UTC by ArniStarkware

2024-12-03 10:59 UTC, ArniStarkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2425?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2425** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2425?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2425?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2409** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2409?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2238** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2238?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 2 other dependent PRs ([#2267](https://github.com/starkware-libs/sequencer/pull/2267) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2267?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>, [#2302](https://github.com/starkware-libs/sequencer/pull/2302) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2302?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#2346** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2346?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#2408](https://github.com/starkware-libs/sequencer/pull/2408) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2408?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#2345** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2345?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2341** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2341?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2342** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2342?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-03 10:59 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2425)
<!-- Reviewable:end -->

2024-12-05 13:56 UTC, alonh5 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2425)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2425#-ODM5o2h3bXrMglBOH3b:-ODM5o2h3bXrMglBOH3c:b-plczi6) ([raw file](https://github.com/starkware-libs/sequencer/blob/12e31a82c54458a250a0f9b0ff5f04646567f7b0/crates/sequencing/papyrus_consensus/src/config.rs#L93)):*
> ```XML
>         };
>         Self {
>             validator_id: ValidatorId::from(1991_u128),
> ```

This PR is where I meant you should change it. Rebase the stack and you'll see the conflicts



_Suggestion:_
```XML
100_u32
```


<!-- Sent from Reviewable.io -->

2024-12-05 14:53 UTC, ArniStarkware commented
This PR is no longer relevant. It was covered by it's downstack.

2024-12-05 14:53 UTC, closed without merging