fix(sequencing): remove old proposal pipes
starkware-libs/sequencer pull request #2452
Opened 2024-12-04 13:22 UTC by guy-starkware

This cleans up some of the leftover code from before we added streamed proposals. 
In this specific PR I remove the channels that used to pass the proposals into context.

2024-12-04 13:22 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2452)
<!-- Reviewable:end -->

2024-12-05 08:32 UTC, matan-starkware requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2452)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2452#-ODKwdQs-42fOPjQDc_w:-ODKwdQs-42fOPjQDc_x:b-nbkfl6) ([raw file](https://github.com/starkware-libs/sequencer/blob/ff611e60f1a77d429e501ced198acc3cccb824f9/crates/starknet_integration_tests/src/utils.rs#L81)):*
> ```XML
>             papyrus_network::gossipsub_impl::Topic::new(
>                 // TODO(guyn): return this to NETWORK_TOPIC once we have integrated streaming.
>                 starknet_consensus_manager::consensus_manager::NETWORK_TOPIC2,
> ```

Can you delete this consts now?



_Code quote:_
```XML
               starknet_consensus_manager::consensus_manager::NETWORK_TOPIC2,
```


<!-- Sent from Reviewable.io -->

2024-12-05 09:25 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2452)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2452#-ODKwdQs-42fOPjQDc_w:-ODL7tab1w5NGMi6YErK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ff611e60f1a77d429e501ced198acc3cccb824f9/crates/starknet_integration_tests/src/utils.rs#L81)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can you delete this consts now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-05 13:35 UTC, matan-starkware approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2452)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2024-12-05 13:35 UTC, merged