chore(sequencing): replace BTreeMap with HashMap in StreamHandler
starkware-libs/sequencer pull request #2517
Opened 2024-12-08 09:56 UTC by guy-starkware

2024-12-08 09:56 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2517)
<!-- Reviewable:end -->

2024-12-08 09:57 UTC, guy-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2517?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2517?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2517?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2512** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2512?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2510** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2510?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-09 14:20 UTC, asmaastarkware requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2517)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2517#-ODflYEoAo8zshTyNxiH:-ODflYEoAo8zshTyNxiI:bufzvtk) ([raw file](https://github.com/starkware-libs/sequencer/blob/31afe42eeb3f622ab8ff9ad817eb5ce3507d3794/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L38)):*
> ```XML
> 
>     // Check if two vectors are the same, regardless of ordering
>     fn do_vecs_match_unordered<T: PartialEq>(a: &[T], b: &[T]) -> bool
> ```

it also ignores duplicates, is this what u want?


<!-- Sent from Reviewable.io -->

2024-12-10 07:41 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2517)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2517#-ODflYEoAo8zshTyNxiH:-ODjVnhVDjqrQ-405wBr:b-gaccsa) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea76fac6ea5b8fe9d7ff9b14eb64983805a4846b/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L38)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

it also ignores duplicates, is this what u want?
</blockquote></details>

You are right. This probably doesn't matter in these test cases, but I will use a different comparison (I'm just going to order the vectors before checking the values. 


<!-- Sent from Reviewable.io -->

2024-12-10 09:08 UTC, asmaastarkware requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2517)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2517#-ODjniXJ5GAdFluYimGn:-ODjniXJ5GAdFluYimGo:b-deygae) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9b269bd4b9045e065cc3d80c3d01cbf5fca2782/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L47)):*
> ```XML
>         b.sort();
>         let matching = a.iter().zip(b.iter()).filter(|&(a, b)| a == b).count();
>         matching == a.len() && matching == b.len()
> ```

Check lengths first to avoid unnecessary sorting



_Suggestion:_
```XML
        if a.len() != b.len() {
            return false;
        }
        let mut a = a.clone();
        a.sort();
        let mut b = b.clone();
        b.sort();
        a == b
```


<!-- Sent from Reviewable.io -->

2024-12-10 09:51 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2517)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2517#-ODjniXJ5GAdFluYimGn:-ODjyY3z6dTslYE9QYO7:b2xmpkr) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9b269bd4b9045e065cc3d80c3d01cbf5fca2782/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L47)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Check lengths first to avoid unnecessary sorting
</blockquote></details>

For some reason I didn't know that `a==b` works. I think we can get rid of the length check altogether. As this is a test (on few elements) I don't see a reason to optimize it by checking lengths at all... 

Thanks! 


<!-- Sent from Reviewable.io -->

2024-12-10 10:03 UTC, asmaastarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2517#-:-ODk0cNf2Qlx7wpdnEDo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 13:33 UTC, matan-starkware approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2517)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 14:07 UTC, guy-starkware commented
### Merge activity

* **Dec 10, 9:07 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2517).

2024-12-10 16:58 UTC, merged