chore(sequencing): remove ConsensusMessage from simulation network
starkware-libs/sequencer pull request #2528
Opened 2024-12-08 13:54 UTC by guy-starkware

2024-12-08 13:54 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2528)
<!-- Reviewable:end -->

2024-12-22 11:49 UTC, asmaastarkware requested changes
1. we are creating a `NetworkReceiver` in `run_consensus`. I noticed you were considering changing what’s passed to new in the next PR #2533  . from my perspective, please ensure they are merged together.. @matan-starkware WDYT
2. currently, msg is just a Vote. Consider using vote instead of msg, add a TODO to address this in a separate PR.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2528#-:-OEi96FR2gx0Rcj96d-q:b-7pb7mp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-12-22 15:46 UTC, asmaastarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2528#-:-OEj1zbq373FHrqpjVY6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-12-23 10:17 UTC, matan-starkware requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2528)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2528#-OEn0LodEJVSZfIFu6O2:-OEn0LodEJVSZfIFu6O3:bihup1i) ([raw file](https://github.com/starkware-libs/sequencer/blob/28f0abb11cf27c9ce682f623657ce1b51be9fb5f/crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs#L82)):*
> ```XML
> }
> 
> fn create_vote_message(height: u64) -> Vote {
> ```

remove fn , just inline this



_Code quote:_
```XML
fn create_vote_message(height: u64) -> Vote {
```


<!-- Sent from Reviewable.io -->

2024-12-23 11:10 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2528)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2528#-OEn0LodEJVSZfIFu6O2:-OEnCYP8CB7IjAGDGh00:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/28f0abb11cf27c9ce682f623657ce1b51be9fb5f/crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs#L82)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

remove fn , just inline this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-24 08:13 UTC, matan-starkware approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2528)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2528#-OEriW3G3P-fQS5yr6UZ:-OEriW3H92HnddjJ5KaJ:b-yte7jx) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd88fe3aa5f2ff310223c7b5dbc9c4be7f284c28/crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs#L34)):*
> ```XML
> 
>     for height in 0..1000 {
>         let msg = papyrus_protobuf::consensus::Vote {
> ```

and below



_Suggestion:_
```XML
Vote
```


<!-- Sent from Reviewable.io -->

2024-12-24 08:20 UTC, guy-starkware reviewed
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2528)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2024-12-24 21:57 UTC, merged