chore(blockifier): add field sierra_gas to BouncerWeights
starkware-libs/sequencer pull request #2530
Opened 2024-12-08 14:43 UTC by avivg-starkware

2024-12-08 14:43 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2530)
<!-- Reviewable:end -->

2024-12-08 14:43 UTC, avivg-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2530?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2530** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2530?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2530?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2527** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2527?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-08 16:10 UTC, Yoni-Starkware reviewed
This PR should not be rebased on top of the L1 gas; they are independent.

> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-:-ODb0Z674i7x2qHvr718:b-wu2k3f)* status: 1 of 7 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-09 09:59 UTC, avivg-starkware reviewed
Moved. Thankyou.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-:-ODer-eVCeOLzyxFCkGG:bxvszq1)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-09 16:47 UTC, Yoni-Starkware requested changes
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2530)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-ODgJOCIC-dzU0yG-2vz:-ODgJOCIC-dzU0yG-2w-:b-v8iuic) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d89d6359502c0ce406c392e66f694d35ee801a6/crates/blockifier/src/bouncer_test.rs#L90)):*
> ```XML
>         n_events: 5,
>         state_diff_size: 5,
>         sierra_gas: GasAmount(5), // TODO(AvivG): replace w desired val.
> ```

It's just a test so it's okay
x2



_Suggestion:_
```XML
sierra_gas: GasAmount(5),
```
___
*[`crates/blockifier/src/bouncer.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-ODgJ0u22IAjQ_T4T0ZA:-ODgJ0u22IAjQ_T4T0ZB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d89d6359502c0ce406c392e66f694d35ee801a6/crates/blockifier/src/bouncer.rs#L155)):*
> ```XML
>             state_diff_size: 4000,
>             builtin_count: BuiltinCount::default(),
>             sierra_gas: GasAmount(1000000), // TODO(AvivG): replace w desired val.
> ```





_Suggestion:_
```XML
sierra_gas: GasAmount(250000000), 
```


<!-- Sent from Reviewable.io -->

2024-12-09 16:48 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2530)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-ODgJOCIC-dzU0yG-2vz:-ODgJWC6AK184eM5agfV:b-4rwr4a) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d89d6359502c0ce406c392e66f694d35ee801a6/crates/blockifier/src/bouncer_test.rs#L90)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It's just a test so it's okay
x2
</blockquote></details>

All over this file


<!-- Sent from Reviewable.io -->

2024-12-10 10:41 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2530)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-ODgJOCIC-dzU0yG-2vz:-ODjpned7UjeKnin9b4k:br4ncq7) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d89d6359502c0ce406c392e66f694d35ee801a6/crates/blockifier/src/bouncer_test.rs#L90)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

All over this file
</blockquote></details>

should the sierra_gas val match the l1_gas? (as currently)
___
*[`crates/native_blockifier/src/py_objects.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-ODgK0Gn7LkSb-d4uXgQ:-ODk5ADMBrwJsI28Z9KF:bqmjwcl) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d89d6359502c0ce406c392e66f694d35ee801a6/crates/native_blockifier/src/py_objects.rs#L130)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add a message
</blockquote></details>

Added 
___
*[`crates/blockifier/src/bouncer.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-ODgJ0u22IAjQ_T4T0ZA:-ODjpiH15VZ9LRX6ajes:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d89d6359502c0ce406c392e66f694d35ee801a6/crates/blockifier/src/bouncer.rs#L155)):*
> ```XML
>             state_diff_size: 4000,
>             builtin_count: BuiltinCount::default(),
>             sierra_gas: GasAmount(1000000), // TODO(AvivG): replace w desired val.
> ```

Done.
___
*[`deployments/sequencer/references/sequencer-node/ConfigMap.sequencer-node-config.k8s.yaml` line 7 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-ODk66ux0WfOfGGGgDup:-ODk66ux0WfOfGGGgDuq:b-1f72hb) ([raw file](https://github.com/starkware-libs/sequencer/blob/75385cc6479d0019ff5fcd35e361cd0f49c9d91b/deployments/sequencer/references/sequencer-node/ConfigMap.sequencer-node-config.k8s.yaml#L7)):*
> ```YAML
>   namespace: test
> data:
>   config: "{\"batcher_config.block_builder_config.bouncer_config.block_max_capacity.builtin_count.add_mod\": {\"description\": \"Max number of add mod builtin usage in a block.\", \"privacy\": \"Public\", \"value\": 156250}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.builtin_count.bitwise\": {\"description\": \"Max number of bitwise builtin usage in a block.\", \"privacy\": \"Public\", \"value\": 39062}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.builtin_count.ec_op\": {\"description\": \"Max number of EC operation builtin usage in a block.\", \"privacy\": \"Public\", \"value\": 2441}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.builtin_count.ecdsa\": {\"description\": \"Max number of ECDSA builtin usage in a block.\", \"privacy\": \"Public\", \"value\": 1220}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.builtin_count.keccak\": {\"description\": \"Max number of keccak builtin usage in a block.\", \"privacy\": \"Public\", \"value\": 1220}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.builtin_count.mul_mod\": {\"description\": \"Max number of mul mod builtin usage in a block.\", \"privacy\": \"Public\", \"value\": 156250}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.builtin_count.pedersen\": {\"description\": \"Max number of pedersen builtin usage in a block.\", \"privacy\": \"Public\", \"value\": 78125}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.builtin_count.poseidon\": {\"description\": \"Max number of poseidon builtin usage in a block.\", \"privacy\": \"Public\", \"value\": 78125}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.builtin_count.range_check\": {\"description\": \"Max number of range check builtin usage in a block.\", \"privacy\": \"Public\", \"value\": 156250}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.builtin_count.range_check96\": {\"description\": \"Max number of range check 96 builtin usage in a block.\", \"privacy\": \"Public\", \"value\": 156250}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.l1_gas\": {\"description\": \"An upper bound on the total gas used in a block.\", \"privacy\": \"Public\", \"value\": 2500000}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.message_segment_length\": {\"description\": \"An upper bound on the message segment length in a block.\", \"privacy\": \"Public\", \"value\": 3700}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.n_events\": {\"description\": \"An upper bound on the total number of events generated in a block.\", \"privacy\": \"Public\", \"value\": 5000}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.n_steps\": {\"description\": \"An upper bound on the total number of steps in a block.\", \"privacy\": \"Public\", \"value\": 2500000}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.state_diff_size\": {\"description\": \"An upper bound on the total state diff size in a block.\", \"privacy\": \"Public\", \"value\": 4000}, \"batcher_config.block_builder_config.bouncer_config.block_max_capacity.sierra_gas\": {\"description\": \"An upper bound on the total sierra_gas used in a block.\", \"privacy\": \"Public\", \"value\": 1000000}, \"batcher_config.block_builder_config.chain_info.chain_id\": {\"description\": \"The chain ID of the StarkNet chain.\", \"pointer_target\": \"chain_id\", \"privacy\": \"Public\"}, \"batcher_config.block_builder_config.chain_info.fee_token_addresses.eth_fee_token_address\": {\"description\": \"Address of the ETH fee token.\", \"pointer_target\": \"eth_fee_token_address\", \"privacy\": \"Public\"}, \"batcher_config.block_builder_config.chain_info.fee_token_addresses.strk_fee_token_address\": {\"description\": \"Address of the STRK fee token.\", \"pointer_target\": \"strk_fee_token_address\", \"privacy\": \"Public\"}, \"batcher_config.block_builder_config.execute_config.concurrency_config.chunk_size\": {\"description\": \"The size of the transaction chunk executed in parallel.\", \"privacy\": \"Public\", \"value\": 0}, \"batcher_config.block_builder_config.execute_config.concurrency_config.enabled\": {\"description\": \"Enables concurrency of transaction execution.\", \"privacy\": \"Public\", \"value\": false}, \"batcher_config.block_builder_config.execute_config.concurrency_config.n_workers\": {\"description\": \"Number of parallel transaction execution workers.\", \"privacy\": \"Public\", \"value\": 0}, \"batcher_config.block_builder_config.sequencer_address\": {\"description\": \"The address of the sequencer.\", \"pointer_target\": \"sequencer_address\", \"privacy\": \"Public\"}, \"batcher_config.block_builder_config.tx_chunk_size\": {\"description\": \"The size of the transaction chunk.\", \"privacy\": \"Public\", \"value\": 100}, \"batcher_config.block_builder_config.use_kzg_da\": {\"description\": \"Indicates whether the kzg mechanism is used for data availability.\", \"privacy\": \"Public\", \"value\": true}, \"batcher_config.block_builder_config.versioned_constants_overrides.invoke_tx_max_n_steps\": {\"description\": \"Maximum number of steps the invoke function is allowed to run.\", \"pointer_target\": \"versioned_constants_overrides.invoke_tx_max_n_steps\", \"privacy\": \"Public\"}, \"batcher_config.block_builder_config.versioned_constants_overrides.max_recursion_depth\": {\"description\": \"Maximum recursion depth for nested calls during blockifier validation.\", \"pointer_target\": \"versioned_constants_overrides.max_recursion_depth\", \"privacy\": \"Public\"}, \"batcher_config.block_builder_config.versioned_constants_overrides.validate_max_n_steps\": {\"description\": \"Maximum number of steps the validatio [...]

2024-12-10 11:13 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 7 files at r1, 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-:-ODkGXKv4keYjDU3J-ej:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/bouncer_test.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-ODgJOCIC-dzU0yG-2vz:-ODkGL1g6iCt7BrktMKG:b2dpmet) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d89d6359502c0ce406c392e66f694d35ee801a6/crates/blockifier/src/bouncer_test.rs#L90)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

should the sierra_gas val match the l1_gas? (as currently)
</blockquote></details>

Yeah it's okay


<!-- Sent from Reviewable.io -->

2024-12-10 13:09 UTC, avivg-starkware reviewed
> Reviewed 1 of 7 files at r1, 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2530)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-12-10 13:09 UTC, merged

2024-12-10 14:36 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2530)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/starknet_api/src/execution_resources.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2530#-ODkznKK42RaH9puGCFc:-ODkznKK42RaH9puGCFd:b-m85rzw) ([raw file](https://github.com/starkware-libs/sequencer/blob/70af3ef25a54dd5b16feb70a724661236a3463c9/crates/starknet_api/src/execution_resources.rs#L15)):*
> ```XML
>     derive_more::Sub,
>     derive_more::Add,
>     derive_more::AddAssign,
> ```

@avivg-starkware @Yoni-Starkware these derives are not in business logic on purpose.
we can use `+` and `-` in tests but we should explicitly saturate or check in all business logic.



_Code quote:_
```XML
    derive_more::Sub,
    derive_more::Add,
    derive_more::AddAssign,
```


<!-- Sent from Reviewable.io -->