fix(blockifier): fix test_write_at_validate_and_execute (#2529)
starkware-libs/sequencer pull request #2534
Opened 2024-12-08 16:02 UTC by yoavGrs

fix(blockifier): fix test_write_at_validate_and_execute (#2529)

feat(blockifier): aliases updater struct

2024-12-08 16:02 UTC, yoavGrs commented
* **#2535** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2534** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2534?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2534?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-09 07:17 UTC, nimrod-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODeFYf21cI-oAx1WXoh:-ODeFYf21cI-oAx1WXoi:bhyd72h) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a4d28d55c2d297002f20a2c2f14fa18da157021/crates/blockifier/src/state/stateful_compression.rs#L15)):*
> ```XML
> 
> type Alias = Felt;
> type AliasKey = StorageKey;
> ```

I think it's more suitable because `ContractAddress` & `StorageKey` wrap `PatriciaKey`.



_Suggestion:_
```XML
type AliasKey = PatriciaKey;
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODeBWVg38mbsJ0fJ6ki:-ODeBWVg38mbsJ0fJ6kj:bz2efdv) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a4d28d55c2d297002f20a2c2f14fa18da157021/crates/blockifier/src/state/stateful_compression.rs#L30)):*
> ```XML
> pub fn get_alias_counter_storage_key() -> StorageKey {
>     StorageKey::from(ALIAS_COUNTER_STORAGE_KEY)
> }
> ```

More readable, IMO, and doesn't need to recompute every time `get_alias_contract_address` & `get_alias_counter_storage_key` are called.



_Suggestion:_
```XML
// The address of the alias contract.
const ALIAS_CONTRACT_ADDRESS: ContractAddress = ContractAddress::from(2);
// The storage key of the alias counter in the alias contract.
const ALIAS_COUNTER_STORAGE_KEY: StorageKey = StorageKey::from(0);
// The minimal value for a key to be allocated an alias. Smaller keys are serialized as is (their
// alias is identical to the key).
const MIN_VALUE_FOR_ALIAS_ALLOC: Felt = Felt::from_hex_unchecked("0x80");
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODeCKFh8pUbpI9KQoAh:-ODeCKFh8pUbpI9KQoAi:b-2mbkbf) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a4d28d55c2d297002f20a2c2f14fa18da157021/crates/blockifier/src/state/stateful_compression.rs#L36)):*
> ```XML
>     state: &'a mut CachedState<S>,
>     next_free_alias: Alias,
>     was_updated: bool,
> ```

I don't think you need this field. IIUC, you use it when you need to decide if the counter should be updated or not.
I suggest always setting the counter. You can use the `Drop` trait by doing something like:
```

impl Drop for AliasUpdater {
    fn drop(&mut self) {
        self.state.set_storage_at(ALIAS_CONTRACT_ADDRESS, ALIAS_COUNTER_STORAGE_KEY, self.next_free_alias);
    }
}
```



_Code quote:_
```XML
was_updated: bool,
```


<!-- Sent from Reviewable.io -->

2024-12-10 09:21 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODeFYf21cI-oAx1WXoh:-ODjVp4I5xks70P5xc9F:b-azdu3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a4d28d55c2d297002f20a2c2f14fa18da157021/crates/blockifier/src/state/stateful_compression.rs#L15)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I think it's more suitable because `ContractAddress` & `StorageKey` wrap `PatriciaKey`.
</blockquote></details>

On the other hand, this type is a storage key in the aliases contract.
Look at the calls to `get_storage_at` and `set_storage_at`.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODeBWVg38mbsJ0fJ6ki:-ODjSNiw2IdVI2wEQaor:bv9rzoq) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a4d28d55c2d297002f20a2c2f14fa18da157021/crates/blockifier/src/state/stateful_compression.rs#L30)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

More readable, IMO, and doesn't need to recompute every time `get_alias_contract_address` & `get_alias_counter_storage_key` are called.
</blockquote></details>

I can't use `from` in a `const` context.
Maybe @dorimedini-starkware  will have a more elegant solution than mine.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODeCKFh8pUbpI9KQoAh:-ODjWrSF18cNXpvYmplc:buqwckc) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a4d28d55c2d297002f20a2c2f14fa18da157021/crates/blockifier/src/state/stateful_compression.rs#L36)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I don't think you need this field. IIUC, you use it when you need to decide if the counter should be updated or not.
I suggest always setting the counter. You can use the `Drop` trait by doing something like:
```

impl Drop for AliasUpdater {
    fn drop(&mut self) {
        self.state.set_storage_at(ALIAS_CONTRACT_ADDRESS, ALIAS_COUNTER_STORAGE_KEY, self.next_free_alias);
    }
}
```
</blockquote></details>

Removed.
Note that for the first block we will write the counter to the storage, even if it doesn't contain aliases.


<!-- Sent from Reviewable.io -->

2024-12-10 09:40 UTC, nimrod-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODeBWVg38mbsJ0fJ6ki:-ODjw1LQCpRlW5F3wxEa:b-h4hyzz) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a4d28d55c2d297002f20a2c2f14fa18da157021/crates/blockifier/src/state/stateful_compression.rs#L30)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I can't use `from` in a `const` context.
Maybe @dorimedini-starkware  will have a more elegant solution than mine.
</blockquote></details>

How does this work?..
`const MIN_VALUE_FOR_ALIAS_ALLOC: Felt = Felt::from_hex_unchecked("0x80")`
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODeCKFh8pUbpI9KQoAh:-ODjtvkA5Nv2Xvk_2JQn:b-gm4xpy) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a4d28d55c2d297002f20a2c2f14fa18da157021/crates/blockifier/src/state/stateful_compression.rs#L36)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Removed.
Note that for the first block we will write the counter to the storage, even if it doesn't contain aliases.
</blockquote></details>

That's ok; in the OS it's also the case


<!-- Sent from Reviewable.io -->

2024-12-10 10:12 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: all files reviewed, 8 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODeBWVg38mbsJ0fJ6ki:-ODk-3en1I8KRHmPzmXU:b-hp0nsd) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a4d28d55c2d297002f20a2c2f14fa18da157021/crates/blockifier/src/state/stateful_compression.rs#L30)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

How does this work?..
`const MIN_VALUE_FOR_ALIAS_ALLOC: Felt = Felt::from_hex_unchecked("0x80")`
</blockquote></details>

you should be able to make the first two const as well, e.g.
```
impl PatriciaKey {
    const fn new(v: Felt) -> Self { Self(v) }
}

const x: StorageKey = StorageKey(PatriciaKey::new(Felt::ZERO))
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODjzLWsCNNe6ZLrwjMy:-ODjzLWsCNNe6ZLrwjMz:b-btu2he) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression.rs#L10)):*
> ```XML
> #[cfg(test)]
> #[path = "stateful_compression_test.rs"]
> pub mod stateful_compression_test;
> ```

do you need the `#[path]` if the module name is identical to the file name?



_Code quote:_
```XML
#[path = "stateful_compression_test.rs"]
pub mod stateful_compression_test;
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODjzWZT-Q544rcqZ_si:-ODjzWZT-Q544rcqZ_sj:b-mm89eo) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression.rs#L18)):*
> ```XML
> const ALIAS_CONTRACT_ADDRESS: u8 = 2;
> // The storage key of the alias counter in the alias contract.
> const ALIAS_COUNTER_STORAGE_KEY: u8 = 0;
> ```

can you make these typed? maybe you can add const definitions in the types themselves



_Suggestion:_
```XML
const ALIAS_CONTRACT_ADDRESS: ContractAddress = ContractAddress(2);
// The storage key of the alias counter in the alias contract.
const ALIAS_COUNTER_STORAGE_KEY: StorageKey = StorageKey(0);
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODjzqqQEQbiCr98yjbi:-ODjzqqREd4mNrVjCa_W:bt2kjb4) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression.rs#L21)):*
> ```XML
> // The minimal value for a key to be allocated an alias. Smaller keys are serialized as is (their
> // alias is identical to the key).
> const MIN_VALUE_FOR_ALIAS_ALLOC: Felt = Felt::from_hex_unchecked("0x80");
> ```

we need to verify consistency with python-side constants.
please expose these constants with `pyfunction`s in the native blockifier, and open a py side PR to test that these values are identical to there python counterparts



_Code quote:_
```XML
// The address of the alias contract.
const ALIAS_CONTRACT_ADDRESS: u8 = 2;
// The storage key of the alias counter in the alias contract.
const ALIAS_COUNTER_STORAGE_KEY: u8 = 0;
// The minimal value for a key to be allocated an alias. Smaller keys are serialized as is (their
// alias is identical to the key).
const MIN_VALUE_FOR_ALIAS_ALLOC: Felt = Felt::from_hex_unchecked("0x80");
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODk0I3TBFwDkdrnpwhj:-ODk0I3TBFwDkdrnpwhk:b-xa5ae4) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression.rs#L32)):*
> ```XML
> /// Updates the alias contract with the new keys.
> struct AliasUpdater<'a, S: StateReader> {
>     state: &'a mut CachedState<S>,
> ```

why operate directly on the state?
I would prefer starting a transactional state, and then you can have a `fn finalize_and_commit`



_Code quote:_
```XML
state: &'a mut CachedState<S>,
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODk0Zc4CYO37YCbT8wi:-ODk0Zc4CYO37YCbT8wj:b-a6zbzz) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression.rs#L55)):*
> ```XML
>         if alias_key.0 >= PatriciaKey::try_from(MIN_VALUE_FOR_ALIAS_ALLOC)?
>             && self.state.get_storage_at(get_alias_contract_address(), *alias_key)? == Felt::ZERO
>         {
> ```

non-blocking, but seems nicer



_Suggestion:_
```XML
    fn in_aliasing_range(alias_key: &AliasKey) -> bool {
        alias_key.0 >= MIN_VALUE_FOR_ALIAS_ALLOC
    }
    
    fn get_alias(&mut self, alias_key: &AliasKey) -> StateResult<Felt> {
        self.state.get_storage_at(get_alias_contract_address(), *alias_key)
    }
    
    /// Inserts the alias key to the updates if it's not already aliased.
    fn set_alias(&mut self, alias_key: &AliasKey) -> StateResult<()> {
        if Self::in_aliasing_range(alias_key) && self.get_alias(alias_key)? == Felt::ZERO {
```
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODk1U9c9TN8vYceYqPS:-ODk1U9c9TN8vYceYqPT:bt1a6ov) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression_test.rs#L18)):*
> ```XML
> 
> fn insert_to_alias_contract(
>     storage: &mut HashMap<(ContractAddress, StorageKey), Felt>,
> ```

how about using an existing type?



_Suggestion:_
```XML
storage: &mut StorageView,
```
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODk1Da84DOtIs_ru12V:-ODk1Da84DOtIs_ru12W:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression_test.rs#L25)):*
> ```XML
> }
> 
> fn initial_state(n_exist_aliases: u8) -> CachedState<DictStateReader> {
> ```





_Suggestion:_
```XML
n_existing_aliases
```
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODk2GwE4nA9qt9VCvbe:-ODk2GwE4nA9qt9VCvbf:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression_test.rs#L82)):*
> ```XML
>     // Test the new aliases.
>     let mut expected_storage_diff = HashMap::new();
>     let mut next_alias = MIN_VALUE_FOR_ALIAS_ALLOC + Felt::from(n_exist_aliases);
> ```





_Suggestion:_
```XML
expected_next_alias
```


<!-- Sent from Reviewable.io -->

2024-12-10 15:13 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODeBWVg38mbsJ0fJ6ki:-ODkE4E8BSv705OIvbvd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a4d28d55c2d297002f20a2c2f14fa18da157021/crates/blockifier/src/state/stateful_compression.rs#L30)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you should be able to make the first two const as well, e.g.
```
impl PatriciaKey {
    const fn new(v: Felt) -> Self { Self(v) }
}

const x: StorageKey = StorageKey(PatriciaKey::new(Felt::ZERO))
```
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODjzLWsCNNe6ZLrwjMy:-ODk9zey1XB0m_5B0oF4:b-q85xfs) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression.rs#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do you need the `#[path]` if the module name is identical to the file name?
</blockquote></details>

Yes. Checking why.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODjzWZT-Q544rcqZ_si:-ODkE0zNDAz-uA8-iUu6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you make these typed? maybe you can add const definitions in the types themselves
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODk0I3TBFwDkdrnpwhj:-ODl3p0gB2riFjSfDKmu:b-ffzlev) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why operate directly on the state?
I would prefer starting a transactional state, and then you can have a `fn finalize_and_commit`
</blockquote></details>

I made some changes to give aliases only for addresses and keys with nontrivial changes.
The state is immutable now.
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODk1U9c9TN8vYceYqPS:-ODkGEzZ3NMAElqe9Ofl:b-d526ir) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression_test.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how about using an existing type?
</blockquote></details>

I don't need the wrapping type.
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODk1Da84DOtIs_ru12V:-ODkGKTl4bgYd4JhXqb7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression_test.rs#L25)):*
> ```XML
> }
> 
> fn initial_state(n_exist_aliases: u8) -> CachedState<DictStateReader> {
> ```

Done.
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODk2GwE4nA9qt9VCvbe:-ODkGOpY1rmSZdgoUu-t:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression_test.rs#L82)):*
> ```XML
>     // Test the new aliases.
>     let mut expected_storage_diff = HashMap::new();
>     let mut next_alias = MIN_VALUE_FOR_ALIAS_ALLOC + Felt::from(n_exist_aliases);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-15 06:23 UTC, nimrod-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: 1 of 4 files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE7xmCL27rPsTGt-KPb:-OE7xmCL27rPsTGt-KPc:b-f61bwm) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L23)):*
> ```XML
> // The minimal value for a key to be allocated an alias. Smaller keys are serialized as is (their
> // alias is identical to the key).
> const MIN_VALUE_FOR_ALIAS_ALLOC: Felt = Felt::from_hex_unchecked("0x80");
> ```

please also add `INITIAL_AVAILABLE_ALIAS: Felt` as a constant, so you don't need to recompute `PatriciaKey::try_from(MIN_VALUE_FOR_ALIAS_ALLOC)` every time you check wether to allocate or not.



_Suggestion:_
```XML
// The minimal value for a key to be allocated an alias. Smaller keys are serialized as is (their
// alias is identical to the key).
const INITIAL_AVAILABLE_ALIAS: Felt = Felt::from_hex_unchecked("0x80");

// ....
const MIN_VALUE_FOR_ALIAS_ALLOC: PatriciaKey = PatriciaKey::new_unchecked(INITIAL_AVAILABLE_ALIAS);
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE7ySDp9LQJGHGH1xDu:-OE7ySDp9LQJGHGH1xDv:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L50)):*
> ```XML
>     /// Inserts the alias key to the updates if it's not already aliased.
>     fn insert_alias(&mut self, alias_key: &AliasKey) -> StateResult<()> {
>         if alias_key.0 >= PatriciaKey::try_from(MIN_VALUE_FOR_ALIAS_ALLOC)?
> ```





_Suggestion:_
```XML
MIN_VALUE_FOR_ALIAS_ALLOC
```
___
*[`crates/starknet_api/src/core.rs` line 125 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE7wZTED3r_5aRmgRDH:-OE7wZTG1bgn6moxETRU:bsfblyl) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/starknet_api/src/core.rs#L125)):*
> ```XML
>     }
> 
>     pub const fn new(val: Felt) -> Self {
> ```

Shouldn't that be also named `new_unchecked`?



_Code quote:_
```XML
pub const fn new
```


<!-- Sent from Reviewable.io -->

2024-12-15 08:44 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: all files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/starknet_api/src/core.rs` line 125 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE7wZTED3r_5aRmgRDH:-OE8U4ty7GWmN7FlAQKL:b-27vo6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/starknet_api/src/core.rs#L125)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Shouldn't that be also named `new_unchecked`?
</blockquote></details>

no, no type conversions are done here
___
*[`crates/starknet_api/src/core.rs` line 367 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8U8siBDxDKwtxvRLW:-OE8U8sj3XMTK5Ihbbww:b-w81ll9) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/starknet_api/src/core.rs#L367)):*
> ```XML
>     pub const fn new_unchecked(val: StarkHash) -> Self {
>         Self(val)
>     }
> ```

you are not performing conversions here - nothing is "unchecked"



_Suggestion:_
```XML
    pub const fn new(val: StarkHash) -> Self {
        Self(val)
    }
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8TKjxDVs8QjwqLbVT:-OE8TKjxDVs8QjwqLbVU:b-wuon6t) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L63)):*
> ```XML
>     /// contract.
>     fn finalize_updates(mut self) -> HashMap<StorageEntry, Felt> {
>         if !self.new_aliases.is_empty() || self.next_free_alias == MIN_VALUE_FOR_ALIAS_ALLOC {
> ```

if no new aliases are allocated and the next free alias is not zero, why set the counter value?
shouldn't you be checking if the next free alias is zero (not initialized yet)?



_Code quote:_
```XML
self.next_free_alias == MIN_VALUE_FOR_ALIAS_ALLOC
```


<!-- Sent from Reviewable.io -->

2024-12-15 09:08 UTC, nimrod-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8TKjxDVs8QjwqLbVT:-OE8ZYiXB0iaHfjrUghV:bgkq4ye) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if no new aliases are allocated and the next free alias is not zero, why set the counter value?
shouldn't you be checking if the next free alias is zero (not initialized yet)?
</blockquote></details>

In the OS, if the counter is 0, we set it to 128 right away, regardless of whether new aliases were allocated or not.
___
*[`crates/starknet_api/src/core.rs` line 125 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE7wZTED3r_5aRmgRDH:-OE8ZINm4T01gHH73vHc:b-wr0buu) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/starknet_api/src/core.rs#L125)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, no type conversions are done here
</blockquote></details>

What if `val >= 2**251`? the contract address will be invalid.


<!-- Sent from Reviewable.io -->

2024-12-15 10:37 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODjzqqQEQbiCr98yjbi:-OE8qG9W57a5uO0mYmFw:bp8uuhi) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we need to verify consistency with python-side constants.
please expose these constants with `pyfunction`s in the native blockifier, and open a py side PR to test that these values are identical to there python counterparts
</blockquote></details>

OK, but bot in this PR
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE7xmCL27rPsTGt-KPb:-OE8pKbfBsQ7SmZxmkrQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L23)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

please also add `INITIAL_AVAILABLE_ALIAS: Felt` as a constant, so you don't need to recompute `PatriciaKey::try_from(MIN_VALUE_FOR_ALIAS_ALLOC)` every time you check wether to allocate or not.
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/core.rs` line 125 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE7wZTED3r_5aRmgRDH:-OE8pFaF1fW68Jz2qi89:bp3aow6) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/starknet_api/src/core.rs#L125)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

What if `val >= 2**251`? the contract address will be invalid.
</blockquote></details>

Reverted.
___
*[`crates/starknet_api/src/core.rs` line 367 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8U8siBDxDKwtxvRLW:-OE8pIRM3Z6zJQZ1_9k6:bp3aow6) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/starknet_api/src/core.rs#L367)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are not performing conversions here - nothing is "unchecked"
</blockquote></details>

Reverted.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE7ySDp9LQJGHGH1xDu:-OE8pC2M6uMTHd-w2GRB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L50)):*
> ```XML
>     /// Inserts the alias key to the updates if it's not already aliased.
>     fn insert_alias(&mut self, alias_key: &AliasKey) -> StateResult<()> {
>         if alias_key.0 >= PatriciaKey::try_from(MIN_VALUE_FOR_ALIAS_ALLOC)?
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-15 11:02 UTC, nimrod-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8y_IUEaAixDYpYDuh:-OE8y_IUEaAixDYpYDui:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/48faf8d1ed17726cc2eaabf8fcd2a03d0f81a83b/crates/blockifier/src/state/stateful_compression.rs#L26)):*
> ```XML
>         PatriciaKey::try_from(Felt::TWO).unwrap()
>     );
>     // const ALIAS_CONTRACT_ADDRESS: ContractAddress = ContractAddress::new(Felt::TWO);
> ```




<!-- Sent from Reviewable.io -->

2024-12-15 11:12 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: all files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8TKjxDVs8QjwqLbVT:-OE901sTEA7L6kuOfVie:bqg9bs2) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L63)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

In the OS, if the counter is 0, we set it to 128 right away, regardless of whether new aliases were allocated or not.
</blockquote></details>

yes but it seems to me like the counter is *not* zero here, i.e. already set to 128 previously. why set again?
___
*[`crates/blockifier/Cargo.toml` line 38 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE9-lX67K4MqytXyDoe:-OE9-lX67K4MqytXyDof:bmgjx8k) ([raw file](https://github.com/starkware-libs/sequencer/blob/48faf8d1ed17726cc2eaabf8fcd2a03d0f81a83b/crates/blockifier/Cargo.toml#L38)):*
> ```TOML
> itertools.workspace = true
> keccak.workspace = true
> lazy_static.workspace = true
> ```

remove - use `LazyLock`



_Code quote:_
```TOML
lazy_static.workspace = true
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE9-remBUbW17yBsIWl:-OE9-remBUbW17yBsIWm:bp7x9pm) ([raw file](https://github.com/starkware-libs/sequencer/blob/48faf8d1ed17726cc2eaabf8fcd2a03d0f81a83b/crates/blockifier/src/state/stateful_compression.rs#L35)):*
> ```XML
>     static ref MIN_VALUE_FOR_ALIAS_ALLOC: PatriciaKey =
>         PatriciaKey::try_from(INITIAL_AVAILABLE_ALIAS).unwrap();
> }
> ```

please use LazyLock, not lazy_static. it doesn't require an external dep (we have examples in code)



_Code quote:_
```XML
lazy_static! {
    // The address of the alias contract.
    static ref ALIAS_CONTRACT_ADDRESS: ContractAddress = ContractAddress(
        PatriciaKey::try_from(Felt::TWO).unwrap()
    );
    // const ALIAS_CONTRACT_ADDRESS: ContractAddress = ContractAddress::new(Felt::TWO);
    // The storage key of the alias counter in the alias contract.
    static ref ALIAS_COUNTER_STORAGE_KEY: StorageKey = StorageKey(
        PatriciaKey::try_from(Felt::ZERO).unwrap()
    );
    // The minimal value for a key to be allocated an alias. Smaller keys are serialized as is (their
    // alias is identical to the key).
    static ref MIN_VALUE_FOR_ALIAS_ALLOC: PatriciaKey =
        PatriciaKey::try_from(INITIAL_AVAILABLE_ALIAS).unwrap();
}
```


<!-- Sent from Reviewable.io -->

2024-12-15 12:11 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8TKjxDVs8QjwqLbVT:-OE9BJQ_4waPIX86PtXC:b-s95yrs) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes but it seems to me like the counter is *not* zero here, i.e. already set to 128 previously. why set again?
</blockquote></details>

Only here we write the counter in the storage.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE9-remBUbW17yBsIWl:-OE9AjlTCFv0z1BZjiEL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48faf8d1ed17726cc2eaabf8fcd2a03d0f81a83b/crates/blockifier/src/state/stateful_compression.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please use LazyLock, not lazy_static. it doesn't require an external dep (we have examples in code)
</blockquote></details>

Done.
___
*[`crates/blockifier/Cargo.toml` line 38 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE9-lX67K4MqytXyDoe:-OE9Agl02K8sdQP7ihT6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48faf8d1ed17726cc2eaabf8fcd2a03d0f81a83b/crates/blockifier/Cargo.toml#L38)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove - use `LazyLock`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8y_IUEaAixDYpYDuh:-OE9Ainu0mW_duV3f_FZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48faf8d1ed17726cc2eaabf8fcd2a03d0f81a83b/crates/blockifier/src/state/stateful_compression.rs#L26)):*
> ```XML
>         PatriciaKey::try_from(Felt::TWO).unwrap()
>     );
>     // const ALIAS_CONTRACT_ADDRESS: ContractAddress = ContractAddress::new(Felt::TWO);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-15 15:35 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8TKjxDVs8QjwqLbVT:-OE9xFNtAkPV75TUAJnv:br5hjpm) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L63)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Only here we write the counter in the storage.
</blockquote></details>

it is theoretically possible for the next available alias to be the initial available alias, even after we initialize it in a previous block, no? what if the first block after upgrade does not introduce any alias?


<!-- Sent from Reviewable.io -->

2024-12-15 16:23 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-ODjzLWsCNNe6ZLrwjMy:-OEA5yoA5xI9xFJic-69:b-5pm8g) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd3c8821d8e990ec05bcd729c959921c7055c679/crates/blockifier/src/state/stateful_compression.rs#L10)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Yes. Checking why.
</blockquote></details>

It can be removed if the test module is declared in `state.rs`.
In `cached_state.rs` we did the same as here.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8TKjxDVs8QjwqLbVT:-OEA5Bl33OI2Wr58Oo9V:b-1zyc8y) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it is theoretically possible for the next available alias to be the initial available alias, even after we initialize it in a previous block, no? what if the first block after upgrade does not introduce any alias?
</blockquote></details>

You're right.
If there are no aliases in the first two blocks, there is unnecessary writing. Fixed.


<!-- Sent from Reviewable.io -->

2024-12-16 09:16 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8TKjxDVs8QjwqLbVT:-OEDkDwz9w-b-OKp9Hnm:b-je45s5) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L63)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

You're right.
If there are no aliases in the first two blocks, there is unnecessary writing. Fixed.
</blockquote></details>

where? I don't see a diff


<!-- Sent from Reviewable.io -->

2024-12-17 08:56 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 78 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OEIp1EhDxXvSeaGkQvx:-OEIp1EhDxXvSeaGkQvy:b-dmqbpm) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bde26399f2b39f11f6074dcb89336d3da0d692f/crates/blockifier/src/state/stateful_compression.rs#L78)):*
> ```XML
>                 }
>             }
>         }
> ```

does this match OS behavior? @nimrod-starkware 



_Code quote:_
```XML
        match self.next_free_alias {
            None => {
                self.new_aliases.insert(*ALIAS_COUNTER_STORAGE_KEY, INITIAL_AVAILABLE_ALIAS);
            }
            Some(alias) => {
                if !self.new_aliases.is_empty() {
                    self.new_aliases.insert(*ALIAS_COUNTER_STORAGE_KEY, alias);
                }
            }
        }
```


<!-- Sent from Reviewable.io -->

2024-12-17 08:59 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OE8TKjxDVs8QjwqLbVT:-OEIpq9735GvqVn-HlFO:bff6wki) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9c83da1dce1248dde7b473c5c03b41c9988f5d8/crates/blockifier/src/state/stateful_compression.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where? I don't see a diff
</blockquote></details>

Done, sorry


<!-- Sent from Reviewable.io -->

2024-12-17 09:15 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 78 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-OEIp1EhDxXvSeaGkQvx:-OEItbaW9epuUvtcPZM9:b-hv9eb7) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bde26399f2b39f11f6074dcb89336d3da0d692f/crates/blockifier/src/state/stateful_compression.rs#L78)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this match OS behavior? @nimrod-starkware
</blockquote></details>

yes :)


<!-- Sent from Reviewable.io -->

2024-12-17 10:40 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-:-OEJCBR01sC157dboFmv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-17 11:05 UTC, nimrod-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534#-:-OEJHwJTERgCLdhODVm6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-17 11:23 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2534)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-17 15:38 UTC, merged