feat(blockifier): iterate over aliases on the state diff
starkware-libs/sequencer pull request #2535
Opened 2024-12-08 16:02 UTC by yoavGrs

2024-12-08 16:02 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2535)
<!-- Reviewable:end -->

2024-12-08 16:02 UTC, yoavGrs commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2535?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2535** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2535?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2534** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2534?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-09 07:38 UTC, nimrod-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODeJ3bA1e6gFAa5q1l-:-ODeJ3bA1e6gFAa5q1l0:bmn18rm) ([raw file](https://github.com/starkware-libs/sequencer/blob/dff6b2fab1dee9162e5ba1ecbc20f34ce435e08d/crates/blockifier/src/state/stateful_compression.rs#L23)):*
> ```XML
> // The maximal contract address for which aliases are not used and all keys are serialized as is,
> // without compression.
> const MAX_NON_COMPRESSED_CONTRACT_ADDRESS: u8 = 15;
> ```

Like in the previous PR (and delete `fn get_max_non_compressed_contract_address()`)



_Suggestion:_
```XML
const MAX_NON_COMPRESSED_CONTRACT_ADDRESS: ContractAddress = ContractAddress::from(15)
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODeJbOIDpCYPuk9kWdJ:-ODeJbOIDpCYPuk9kWdK:b-3v05x3) ([raw file](https://github.com/starkware-libs/sequencer/blob/dff6b2fab1dee9162e5ba1ecbc20f34ce435e08d/crates/blockifier/src/state/stateful_compression.rs#L38)):*
> ```XML
> }
> 
> pub fn insert_aliases<S: StateReader>(state: &mut CachedState<S>) -> StateResult<()> {
> ```

Better IMO, non-blocking



_Suggestion:_
```XML
pub fn allocate_aliases
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODeKsCs7LaJuNdg0IfM:-ODeKsCt3xh6wvfC0YZm:b8166nl) ([raw file](https://github.com/starkware-libs/sequencer/blob/dff6b2fab1dee9162e5ba1ecbc20f34ce435e08d/crates/blockifier/src/state/stateful_compression.rs#L61)):*
> ```XML
>         }
>         alias_updater.set_alias(&StorageKey(address.0))?;
>     }
> ```

You also need to filter out **all** addresses < 16 (not only with storage updates)



_Suggestion:_
```XML
    // Collect the addresses and storage keys that need aliases.
    let mut addresses = BTreeSet::new();
    let mut sorted_storage_keys = HashMap::new();
    addresses.extend(writes.class_hashes.keys().chain(writes.nonces.keys()));
    for (address, storage_key) in writes.storage.keys() {
        addresses.insert(address);
        sorted_storage_keys.entry(address).or_insert_with(BTreeSet::new).insert(storage_key);
    }

    // Iterate over the addresses and the storage keys and update the aliases.
    let mut alias_updater = AliasUpdater::new(state)?;
    for address in addresses {
        if address < 16 {
            continue;
        }
        if let Some(storage_keys) = sorted_storage_keys.get(address) {
            for key in storage_keys {
                alias_updater.set_alias(key)?;
            }
        }
        alias_updater.set_alias(&StorageKey(address.0))?;
    }
```


<!-- Sent from Reviewable.io -->

2024-12-10 09:19 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODeJbOIDpCYPuk9kWdJ:-ODjndqEBdg9UkaOwrS2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dff6b2fab1dee9162e5ba1ecbc20f34ce435e08d/crates/blockifier/src/state/stateful_compression.rs#L38)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Better IMO, non-blocking
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODeKsCs7LaJuNdg0IfM:-ODjo0uj7zsMT92L07VY:b4oo130) ([raw file](https://github.com/starkware-libs/sequencer/blob/dff6b2fab1dee9162e5ba1ecbc20f34ce435e08d/crates/blockifier/src/state/stateful_compression.rs#L61)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

You also need to filter out **all** addresses < 16 (not only with storage updates)
</blockquote></details>

I validate that the addresses and the storage keys are greater than 127 in `set_alias`.


<!-- Sent from Reviewable.io -->

2024-12-10 09:29 UTC, nimrod-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODeKsCs7LaJuNdg0IfM:-ODjspVz8oHVXKv6x7jK:b-c88y97) ([raw file](https://github.com/starkware-libs/sequencer/blob/dff6b2fab1dee9162e5ba1ecbc20f34ce435e08d/crates/blockifier/src/state/stateful_compression.rs#L61)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I validate that the addresses and the storage keys are greater than 127 in `set_alias`.
</blockquote></details>

ah ok, my bad


<!-- Sent from Reviewable.io -->

2024-12-10 10:19 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 7 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk2dv3EVR3KxgiRcF5:-ODk2dv3EVR3KxgiRcF6:b-92swdd) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L23)):*
> ```XML
> // The maximal contract address for which aliases are not used and all keys are serialized as is,
> // without compression.
> const MAX_NON_COMPRESSED_CONTRACT_ADDRESS: u8 = 15;
> ```

like previous PR: verify consistency with python value.
also, I believe this number is 3 now, no? @nimrod-starkware 



_Code quote:_
```XML
const MAX_NON_COMPRESSED_CONTRACT_ADDRESS: u8 = 15;
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk2pzGC4dOsVoGQw9_:-ODk2pzGC4dOsVoGQw9a:bj8pttp) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L42)):*
> ```XML
> /// storage keys (in ascending order) and for the address itself.
> pub fn allocate_aliases<S: StateReader>(state: &mut CachedState<S>) -> StateResult<()> {
>     let writes = state.borrow_updated_state_cache()?.clone().writes;
> ```

not sure this clone will be needed if you use a transactional state (see prev PR)



_Code quote:_
```XML
let writes = state.borrow_updated_state_cache()?.clone().writes;
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk2yL24ZiTNqCPxFz8:-ODk2yL24ZiTNqCPxFz9:bljn0ec) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L47)):*
> ```XML
>     let mut addresses = BTreeSet::new();
>     let mut sorted_storage_keys = HashMap::new();
>     addresses.extend(writes.class_hashes.keys().chain(writes.nonces.keys()));
> ```

@nimrod-starkware are we still aliasing class hashes?



_Code quote:_
```XML
writes.class_hashes.keys()
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk35q_6pUFAkV-P62-:-ODk35q_6pUFAkV-P620:b-kwc4kd) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L48)):*
> ```XML
>     let mut sorted_storage_keys = HashMap::new();
>     addresses.extend(writes.class_hashes.keys().chain(writes.nonces.keys()));
>     for (address, storage_key) in writes.storage.keys() {
> ```

@nimrod-starkware the OS also processes reads, right?
is iterating over the `writes` enough?



_Code quote:_
```XML
for (address, storage_key) in writes.storage.keys()
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk3cjDDxs3jo72Bobo:-ODk3cjDDxs3jo72Bobp:b-i81m93) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L50)):*
> ```XML
>     for (address, storage_key) in writes.storage.keys() {
>         addresses.insert(address);
>         if address > &get_max_non_compressed_contract_address() {
> ```

why add the address to `addresses` if it's not over the max-non-compressed address?
@nimrod-starkware which address range does NOT get an alias?



_Code quote:_
```XML
        addresses.insert(address);
        if address > &get_max_non_compressed_contract_address() {
```
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk41A445mPUwFIfhuL:-ODk41A445mPUwFIfhuM:bov0w9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression_test.rs#L120)):*
> ```XML
>     state.get_class_hash_at(ContractAddress::from(0x202_u16)).unwrap();
>     state.set_class_hash_at(ContractAddress::from(0x202_u16), ClassHash::default()).unwrap();
>     state.increment_nonce(ContractAddress::from(0x200_u16)).unwrap();
> ```

please add a contract address that sets storage at keys 7, 9, 4 in that order (to check alias order).
also, this contract should have address 0x200, so contract address aliasing order is also checked



_Code quote:_
```XML
    state
        .set_storage_at(ContractAddress::from(0x201_u16), StorageKey::from(0x300_u16), Felt::ONE)
        .unwrap();
    state
        .set_storage_at(
            get_max_non_compressed_contract_address(),
            StorageKey::from(0x301_u16),
            Felt::ONE,
        )
        .unwrap();
    state.get_class_hash_at(ContractAddress::from(0x202_u16)).unwrap();
    state.set_class_hash_at(ContractAddress::from(0x202_u16), ClassHash::default()).unwrap();
    state.increment_nonce(ContractAddress::from(0x200_u16)).unwrap();
```


<!-- Sent from Reviewable.io -->

2024-12-10 10:59 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk2dv3EVR3KxgiRcF5:-ODkB0NiBMfDH5B2H7D7:b3co499) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

like previous PR: verify consistency with python value.
also, I believe this number is 3 now, no? @nimrod-starkware
</blockquote></details>

It's still 15, but we only verify that it's greater than 3 when deploying an account.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk2yL24ZiTNqCPxFz8:-ODkBLEh714Dsnn05cno:b-ggwzh4) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@nimrod-starkware are we still aliasing class hashes?
</blockquote></details>

It's for the addresses that their class hash has changed IIUC, so that should be ok
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk35q_6pUFAkV-P62-:-ODkCOQg9ywXyr43PfPj:b-sxmji9) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@nimrod-starkware the OS also processes reads, right?
is iterating over the `writes` enough?
</blockquote></details>

We need to verify the written value is different than the read value. Only in that case we should allocate (maybe it's already the case here).
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk3cjDDxs3jo72Bobo:-ODkCxDCDEMOcqGG45e4:b-pbmjor) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why add the address to `addresses` if it's not over the max-non-compressed address?
@nimrod-starkware which address range does NOT get an alias?
</blockquote></details>

For address < 16, we don't allocate aliases for storage keys (and since address < 16 < 128),  we won't allocate for the address as well.
For storage keys < 128 we also don't allocate.


<!-- Sent from Reviewable.io -->

2024-12-10 11:15 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk35q_6pUFAkV-P62-:-ODkGQ68-K_zS7KW8vSg:bue4hz9) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L48)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

We need to verify the written value is different than the read value. Only in that case we should allocate (maybe it's already the case here).
</blockquote></details>

why should we only allocate in that case? is that what's happening in the OS, or is that what we "should" be doing?
in any case I think Yoav's way is the correct way so I'm unblocking, but @nimrod-starkware please make sure the OS tests (py side) include cases where an address is only read from, and make sure an alias *isn't* allocated


<!-- Sent from Reviewable.io -->

2024-12-10 11:19 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk35q_6pUFAkV-P62-:-ODkHLEj08Hp_jGIaTs2:b-itrrua) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why should we only allocate in that case? is that what's happening in the OS, or is that what we "should" be doing?
in any case I think Yoav's way is the correct way so I'm unblocking, but @nimrod-starkware please make sure the OS tests (py side) include cases where an address is only read from, and make sure an alias *isn't* allocated
</blockquote></details>

We should do it because we post non-trivial state diff to L1.
That's also what is done in the OS.
There are already cases where only class hash changed and only the nonce has changed, or appeared in the state diff with prev_value == new_value


<!-- Sent from Reviewable.io -->

2024-12-10 15:13 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODeJ3bA1e6gFAa5q1l-:-ODkS1h2Ad362Czs-s7K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dff6b2fab1dee9162e5ba1ecbc20f34ce435e08d/crates/blockifier/src/state/stateful_compression.rs#L23)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Like in the previous PR (and delete `fn get_max_non_compressed_contract_address()`)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk2pzGC4dOsVoGQw9_:-ODkUVql2bNoffIxXdH9:b6kk9jp) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not sure this clone will be needed if you use a transactional state (see prev PR)
</blockquote></details>

Not needed in the new approach.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk2yL24ZiTNqCPxFz8:-ODkS8i0BGg5cEBCszTT:byr4flj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L47)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

It's for the addresses that their class hash has changed IIUC, so that should be ok
</blockquote></details>

Right.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk35q_6pUFAkV-P62-:-ODl4w3lDpLR8uEoC3wn:bl07c0n) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression.rs#L48)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

We should do it because we post non-trivial state diff to L1.
That's also what is done in the OS.
There are already cases where only class hash changed and only the nonce has changed, or appeared in the state diff with prev_value == new_value
</blockquote></details>

For that, we need to take addresses and keys from the state diff.
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-ODk41A445mPUwFIfhuL:-ODkW7DXCA3Y7y9FUiwi:b-jocz7l) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3f2b88c731728a4dcc260ddebcb768589a5ffd8/crates/blockifier/src/state/stateful_compression_test.rs#L120)):*
We increment the nonce in address 0x200, for the second check.
> ```
> state.increment_nonce(ContractAddress::from(0x200_u16)).unwrap();
> ```


<!-- Sent from Reviewable.io -->

2024-12-15 08:37 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OE8RUZv2Yx1sbwgo6dq:-OE8RUZw0Adj36dPK6Tl:b-l6mkjh) ([raw file](https://github.com/starkware-libs/sequencer/blob/937947e330cf24cef8333a410f95c7951bc141ef/crates/blockifier/src/blockifier/transaction_executor.rs#L172)):*
> ```XML
>         let mut block_state = self.block_state.take().expect(BLOCK_STATE_ACCESS_ERR);
>         let state_diff = if self.block_context.versioned_constants.enable_stateful_compression {
>             state_diff_with_allocating_aliases(&mut block_state)?
> ```

rename



_Suggestion:_
```XML
state_diff_with_alias_allocation
```


<!-- Sent from Reviewable.io -->

2024-12-15 10:37 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OE8RUZv2Yx1sbwgo6dq:-OE8q0JKAahZgZ7Axytq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/937947e330cf24cef8333a410f95c7951bc141ef/crates/blockifier/src/blockifier/transaction_executor.rs#L172)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-15 11:12 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-15 11:16 UTC, nimrod-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-:-OE916P38lQqaHJvT22C:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-15 11:18 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-15 13:21 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 171 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OE9T7z49Twak50nSGul:-OE9T7z49Twak50nSGum:b-yszhnd) ([raw file](https://github.com/starkware-libs/sequencer/blob/9974dc2b1e4ff23b575c5c8dc0f4c65b438ccaa6/crates/blockifier/src/blockifier/transaction_executor.rs#L171)):*
> ```XML
>         log::debug!("Final block weights: {:?}.", self.bouncer.get_accumulated_weights());
>         let mut block_state = self.block_state.take().expect(BLOCK_STATE_ACCESS_ERR);
>         let state_diff = if self.block_context.versioned_constants.enable_stateful_compression {
> ```

@Yoni-Starkware, this state is sent to Python.
Is that what you meant?



_Code quote:_
```XML
let state_diff 
```


<!-- Sent from Reviewable.io -->

2024-12-15 15:33 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-12-17 08:56 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 171 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OE9T7z49Twak50nSGul:-OEIpGv3-bJZ4OCmCvpt:bz9cfdz) ([raw file](https://github.com/starkware-libs/sequencer/blob/772bd4cb517eec1989f5631303294779c4c66b8d/crates/blockifier/src/blockifier/transaction_executor.rs#L171)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

@Yoni-Starkware, this state is sent to Python.
Is that what you meant?
</blockquote></details>

py side needs both state diffs: compressed and uncompressed. are both sent to python?


<!-- Sent from Reviewable.io -->

2024-12-17 10:41 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs and @Yoni-Starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 55 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEJCKBoBtzEoUYt0xRj:-OEJCKBoBtzEoUYt0xRk:b-dmm6xo) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea681da8796be9705baac356cdab7a8e7017089b/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L55)):*
> ```XML
>             "0x79b59c5036c9427b5194796ede67bdfffed1f311a77382d715174fcfcc33003",
>         ),
>     ];
> ```

why did these change? please add @Itay-Tsabary-Starkware eyes



_Code quote:_
```XML
    let expected_content_ids = [
        Felt::from_hex_unchecked(
            "0x58ad05a6987a675eda038663d8e7dcc8e1d91c9057dd57f16d9b3b9602fc840",
        ),
        Felt::from_hex_unchecked(
            "0x79b59c5036c9427b5194796ede67bdfffed1f311a77382d715174fcfcc33003",
        ),
    ];
```


<!-- Sent from Reviewable.io -->

2024-12-17 12:21 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 55 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEJCKBoBtzEoUYt0xRj:-OEJZAV_23Uiejh_dn0z:bw39v6q) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea681da8796be9705baac356cdab7a8e7017089b/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L55)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Changing the state diff changes the block hash.
</blockquote></details>

these are block hashes?


<!-- Sent from Reviewable.io -->

2024-12-17 12:21 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-17 12:26 UTC, nimrod-starkware requested changes
blocking until [python](https://reviewable.io/reviews/starkware-industries/starkware/36391) side passes (may take a few days)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-:-OEJ_5Te1kEumNERDtd5:bglpw75)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-17 12:27 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware and @yoavGrs)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEJ_Wex1W7AB9W7PJFS:-OEJ_Wex1W7AB9W7PJFT:b-8ldpf3) (no related file):*
since you can't really self-block - here is a block for py side :)


<!-- Sent from Reviewable.io -->

2024-12-17 13:02 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 55 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEJCKBoBtzEoUYt0xRj:-OEJhWKS0XzwKH2CVUR1:bk8un31) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea681da8796be9705baac356cdab7a8e7017089b/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these are block hashes?
</blockquote></details>

@matan-starkware , could you verify?


<!-- Sent from Reviewable.io -->

2024-12-17 16:01 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-18 11:29 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 49 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEOVtFT54umGONwzAqr:-OEOVtFT54umGONwzAqs:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bfc939733adb2297201ac51a8cce680c85211919/crates/blockifier/src/state/stateful_compression.rs#L49)):*
> ```XML
>         state_diff.get_modified_contracts().into_iter().collect();
>     let mut sorted_storage_keys = HashMap::new();
>     for (address, storage_key) in state_diff.storage.keys() {
> ```





_Suggestion:_
```XML
    // Collect the contract addresses and the storage keys that need aliases.
    let sorted_contract_addresses: BTreeSet<ContractAddress> =
        state_diff.get_modified_contracts().into_iter().collect();
    let mut contract_address_to_sorted_storage_keys = HashMap::new();
    for (contract_address, storage_key) in state_diff.storage.keys() {
```


<!-- Sent from Reviewable.io -->

2024-12-18 11:40 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 73 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEOZLD92mXf7KvJ2gIo:-OEOZLD92mXf7KvJ2gIp:b9hfg81) ([raw file](https://github.com/starkware-libs/sequencer/blob/bfc939733adb2297201ac51a8cce680c85211919/crates/blockifier/src/state/stateful_compression.rs#L73)):*
> ```XML
> /// Generate updates for the alias contract with the new keys.
> struct AliasUpdater<'a, S: StateReader> {
>     state: &'a CachedState<S>,
> ```

Is holding CachedState here necessary?



_Suggestion:_
```XML
struct AliasUpdater<'a, S: StateReader> {
    state: &'a S,
```


<!-- Sent from Reviewable.io -->

2024-12-18 12:13 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 4 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 111 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEOfhJQ8yaGApg9ZhPK:-OEOfhJR6XizF6zNlIpG:ba6bnq4) ([raw file](https://github.com/starkware-libs/sequencer/blob/bfc939733adb2297201ac51a8cce680c85211919/crates/blockifier/src/state/stateful_compression.rs#L111)):*
> ```XML
>             None => {
>                 self.new_aliases.insert(*ALIAS_COUNTER_STORAGE_KEY, INITIAL_AVAILABLE_ALIAS);
>             }
> ```

@nimrod-starkware please make sure this is consistent with your code.



_Suggestion:_
```XML
        match self.next_free_alias {
            None => {
                // Initialize the counter even if no new aliases were allocated.
                self.new_aliases.insert(*ALIAS_COUNTER_STORAGE_KEY, INITIAL_AVAILABLE_ALIAS);
            }
```


<!-- Sent from Reviewable.io -->

2024-12-18 12:17 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 4 unresolved discussions (waiting on @yoavGrs and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 111 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEOfhJQ8yaGApg9ZhPK:-OEOg_rUADs84P1_R_he:b-7osgbq) ([raw file](https://github.com/starkware-libs/sequencer/blob/bfc939733adb2297201ac51a8cce680c85211919/crates/blockifier/src/state/stateful_compression.rs#L111)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@nimrod-starkware please make sure this is consistent with your code.
</blockquote></details>

it is


<!-- Sent from Reviewable.io -->

2024-12-18 12:30 UTC, matan-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware, @yoavGrs, and @Yoni-Starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 55 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEJCKBoBtzEoUYt0xRj:-OEKhVOM0SKnd5_IXulE:bwwb5q9) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea681da8796be9705baac356cdab7a8e7017089b/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L55)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I checked, it's the state diff commitment (with `BlockHash` type).
</blockquote></details>

Consensus does use the StateDiffCommitment to identify a proposal. Since this PR doesn't change the TXs in the proposal and it does change how we calculate the state diff root, then it makes sense to update these.
 
Please add to the commit message that this changes how the StateDiffCommitment is calculated. 


<!-- Sent from Reviewable.io -->

2024-12-18 12:37 UTC, nimrod-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-:-OEOlNqF2N7aCmyAWgbs:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware, @yoavGrs, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-18 12:55 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware, @yoavGrs, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-18 13:48 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @matan-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 73 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEOZLD92mXf7KvJ2gIo:-OEP00iV12Rm5AKXAmX5:b-8ct5a9) ([raw file](https://github.com/starkware-libs/sequencer/blob/829a09a6a586242bcbead6872b0b41047e5999a8/crates/blockifier/src/state/stateful_compression.rs#L73)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is holding CachedState here necessary?
</blockquote></details>

I call `state.to_state_diff()`
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 55 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEJCKBoBtzEoUYt0xRj:-OEP-27J1ZTkRUvkRyWT:b-q03c2x) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea681da8796be9705baac356cdab7a8e7017089b/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L55)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Consensus does use the StateDiffCommitment to identify a proposal. Since this PR doesn't change the TXs in the proposal and it does change how we calculate the state diff root, then it makes sense to update these.
 
Please add to the commit message that this changes how the StateDiffCommitment is calculated.
</blockquote></details>

It changes the StateDiff when finalizing a block, not the commitment calculation.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 49 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEOVtFT54umGONwzAqr:-OEOztD220097H6NHu5g:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/829a09a6a586242bcbead6872b0b41047e5999a8/crates/blockifier/src/state/stateful_compression.rs#L49)):*
> ```XML
>         state_diff.get_modified_contracts().into_iter().collect();
>     let mut sorted_storage_keys = HashMap::new();
>     for (address, storage_key) in state_diff.storage.keys() {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-18 14:40 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 5 unresolved discussions (waiting on @matan-starkware, @yoavGrs, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-18 16:07 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 73 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEOZLD92mXf7KvJ2gIo:-OEPWUch8Jqn7Znk4N56:b-wx1vzs) ([raw file](https://github.com/starkware-libs/sequencer/blob/829a09a6a586242bcbead6872b0b41047e5999a8/crates/blockifier/src/state/stateful_compression.rs#L73)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I call `state.to_state_diff()`
</blockquote></details>

Not inside the `AliasUpdater`


<!-- Sent from Reviewable.io -->

2024-12-19 12:29 UTC, matan-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @yoavGrs and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-19 12:40 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 73 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEOZLD92mXf7KvJ2gIo:-OETtwIl4GReKejIpEp_:b-n2k3k9) ([raw file](https://github.com/starkware-libs/sequencer/blob/829a09a6a586242bcbead6872b0b41047e5999a8/crates/blockifier/src/state/stateful_compression.rs#L73)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not inside the `AliasUpdater`
</blockquote></details>

Right. Removed.


<!-- Sent from Reviewable.io -->

2024-12-19 12:51 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OETxH0a1DHCoz-hEOgp:-OETxH0b0TnvbGPo3BM0:b-tbzr8u) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
> ```XML
> 
>         log::debug!("Final block weights: {:?}.", self.bouncer.get_accumulated_weights());
>         let mut block_state = self.block_state.take().expect(BLOCK_STATE_ACCESS_ERR);
> ```

It's going to break the reexecution I think. TAL at this line - https://github.com/starkware-libs/sequencer/blob/d7be3148574690c2fe4a6abc165285ae4440f5d8/crates/blockifier_reexecution/src/state_reader/utils.rs#L241

need to solve this @dorimedini-starkware @AvivYossef-starkware 
(it would be best if `finalize` will consume `self`)



_Code quote:_
```XML
let mut block_state = self.block_state.take().
```


<!-- Sent from Reviewable.io -->

2024-12-19 13:01 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 33 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEU-N3dCRDRbliM5bH3:-OEU-N3dCRDRbliM5bH4:b8ly37l) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/state/stateful_compression.rs#L33)):*
> ```XML
> // alias is identical to the key).
> static MIN_VALUE_FOR_ALIAS_ALLOC: LazyLock<PatriciaKey> =
>     LazyLock::new(|| PatriciaKey::try_from(INITIAL_AVAILABLE_ALIAS).unwrap());
> ```

Implement `from_hex_unchecked` for PatriciaKey and remove these statics



_Code quote:_
```XML
static MAX_NON_COMPRESSED_CONTRACT_ADDRESS: LazyLock<ContractAddress> = LazyLock::new(|| {
    ContractAddress(PatriciaKey::try_from(Felt::from_hex_unchecked("0xf")).unwrap())
});
// The minimal value for a key to be allocated an alias. Smaller keys are serialized as is (their
// alias is identical to the key).
static MIN_VALUE_FOR_ALIAS_ALLOC: LazyLock<PatriciaKey> =
    LazyLock::new(|| PatriciaKey::try_from(INITIAL_AVAILABLE_ALIAS).unwrap());
```


<!-- Sent from Reviewable.io -->

2024-12-19 13:07 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OETxH0a1DHCoz-hEOgp:-OEU0oHz-kzUbMLRWJqK:b9wwgya) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It's going to break the reexecution I think. TAL at this line - https://github.com/starkware-libs/sequencer/blob/d7be3148574690c2fe4a6abc165285ae4440f5d8/crates/blockifier_reexecution/src/state_reader/utils.rs#L241

need to solve this @dorimedini-starkware @AvivYossef-starkware 
(it would be best if `finalize` will consume `self`)
</blockquote></details>

I.e., I guess that the reexecution needs the state with the aliases


<!-- Sent from Reviewable.io -->

2024-12-19 14:39 UTC, dorimedini-starkware reviewed
> Reviewed 3 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @yoavGrs, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OETxH0a1DHCoz-hEOgp:-OEULnQK8WO_Ips7VTaa:b88y38i) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I.e., I guess that the reexecution needs the state with the aliases
</blockquote></details>

WDYM? [reexecution tests pass](https://github.com/starkware-libs/sequencer/actions/runs/12412795316/job/34653334619) on this PR


<!-- Sent from Reviewable.io -->

2024-12-19 15:19 UTC, dorimedini-starkware reviewed
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @yoavGrs, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-19 17:17 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 4 files at r12, 1 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @yoavGrs)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OETxH0a1DHCoz-hEOgp:-OEUs_0b4Yfq-JNLzaH1:bfrhott) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM? [reexecution tests pass](https://github.com/starkware-libs/sequencer/actions/runs/12412795316/job/34653334619) on this PR
</blockquote></details>

* The broken function is `write_block_reexecution_data_to_file`, maybe it is not tested.
* Consider whether this test needs the state before or after the alias allocation. Anyway, I guess that no 0.13.4 block is tested so the tests won't catch it


<!-- Sent from Reviewable.io -->

2024-12-20 12:13 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @yoavGrs)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OETxH0a1DHCoz-hEOgp:-OEYz-Sn6-WYdF1aXgaz:b-po7z8c) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

* The broken function is `write_block_reexecution_data_to_file`, maybe it is not tested.
* Consider whether this test needs the state before or after the alias allocation. Anyway, I guess that no 0.13.4 block is tested so the tests won't catch it
</blockquote></details>

I think there is nothing that needs to be done with this ATM. the correct order IMO is: after 0.13.4 is released on mainnet, we add example blocks to the reexecution tests, and fix issues we find then


<!-- Sent from Reviewable.io -->

2024-12-20 12:39 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @yoavGrs)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OETxH0a1DHCoz-hEOgp:-OEZ3Nv154RAJhzkrWug:b-j0k3a7) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think there is nothing that needs to be done with this ATM. the correct order IMO is: after 0.13.4 is released on mainnet, we add example blocks to the reexecution tests, and fix issues we find then
</blockquote></details>

This PR breaks the reexecution script even for old blocks, and we need it for next week for debugging the replay. Let's do it properly


<!-- Sent from Reviewable.io -->

2024-12-22 07:59 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OETxH0a1DHCoz-hEOgp:-OEhLL6A2rS-ZDIN1Aqi:b-5xmsxj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This PR breaks the reexecution script even for old blocks, and we need it for next week for debugging the replay. Let's do it properly
</blockquote></details>

I don't see where it breaks.
For blocks pre-0.13.4, the versioned constant `enable_stateful_compression` ensures backward compatibility.
For 0.13.4 blocks, `reexecute_and_verify_correctness` calls `transaction_executor.finalize()`, the function that updates the aliases.


<!-- Sent from Reviewable.io -->

2024-12-22 08:43 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @yoavGrs)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OETxH0a1DHCoz-hEOgp:-OEhWozW5DuBEbkCLl86:bpseoxy) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
> This PR breaks the reexecution script even for old blocks, and we need it for next week for debugging the replay. Let's do it properly

@Yoni-Starkware what you're saying is: we will want to test the *compressed* output of old blocks, even though they were never compressed?

`write_block_reexecution_data_to_file` indeed will not write compression data, but the current behavior will be (IIUC) as if no key has an alias yet - each reexecuted block will be treated as if it's the "first 0.13.4 block", which seems fine to me. no?


<!-- Sent from Reviewable.io -->

2024-12-22 08:52 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 44 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEhYm268zLvdS-oefbj:-OEhYm268zLvdS-oefbk:b-i9fuq8) ([raw file](https://github.com/starkware-libs/sequencer/blob/46d453e8c183a2dcc2bcf7d6e6ac70c44f843c9d/crates/blockifier/src/state/stateful_compression.rs#L44)):*
> ```XML
>     // Collect the contract addresses and the storage keys that need aliases.
>     let contract_addresses: BTreeSet<ContractAddress> =
>         state_diff.get_modified_contracts().into_iter().collect();
> ```

Please rename this function to `get_contract_addresses`. 
(They are the modified ones only when the the struct is created using `diff`) 



_Code quote:_
```XML
.get_modified_contracts()
```


<!-- Sent from Reviewable.io -->

2024-12-22 08:56 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @yoavGrs)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OETxH0a1DHCoz-hEOgp:-OEhZYis60NCJ_g0Np0W:bqewad8) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> This PR breaks the reexecution script even for old blocks, and we need it for next week for debugging the replay. Let's do it properly

@Yoni-Starkware what you're saying is: we will want to test the *compressed* output of old blocks, even though they were never compressed?

`write_block_reexecution_data_to_file` indeed will not write compression data, but the current behavior will be (IIUC) as if no key has an alias yet - each reexecuted block will be treated as if it's the "first 0.13.4 block", which seems fine to me. no?
</blockquote></details>

Two problems:
* This function consumes the block_state, which is accessed after the call to finalize() - `self.block_state.take()`
* the block_state does not contain the compression, so fixing 1 without 2 will postpone the issue. Better to change finalize to consume the entire `self` and let Aviv/Aner fix the reexecution script accordingly


<!-- Sent from Reviewable.io -->

2024-12-22 14:44 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OETxH0a1DHCoz-hEOgp:-OEioLR51K7JGWElNWHJ:bse0ioz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e40418407a5357b19dfed3c9b3692a481181ffd0/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Two problems:
* This function consumes the block_state, which is accessed after the call to finalize() - `self.block_state.take()`
* the block_state does not contain the compression, so fixing 1 without 2 will postpone the issue. Better to change finalize to consume the entire `self` and let Aviv/Aner fix the reexecution script accordingly
</blockquote></details>

TODO :(
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 44 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEhYm268zLvdS-oefbj:-OEion9q4cVpX7_R5mdt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/46d453e8c183a2dcc2bcf7d6e6ac70c44f843c9d/crates/blockifier/src/state/stateful_compression.rs#L44)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please rename this function to `get_contract_addresses`. 
(They are the modified ones only when the the struct is created using `diff`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-22 14:52 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 4 unresolved discussions (waiting on @yoavGrs and @Yoni-Starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 242 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEiqjuCEWuAogAa7Nr9:-OEiqjuCEWuAogAa7NrA:biz7uvx) ([raw file](https://github.com/starkware-libs/sequencer/blob/de47b5a5191d1703bb5ddbb02fe6b0e39fa397b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L242)):*
> ```XML
> 
>     // TODO(Yoav): After finalizing, the block state is None. We should return some fields from the
>     // state.
> ```

you are doing this in a separate PR...?



_Code quote:_
```XML
    // TODO(Yoav): After finalizing, the block state is None. We should return some fields from the
    // state.
```


<!-- Sent from Reviewable.io -->

2024-12-22 15:52 UTC, Yoni-Starkware approved these changes
> Reviewed 3 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-22 16:31 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 242 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-OEiqjuCEWuAogAa7Nr9:-OEjCLmbE4T4hFhfF2x0:b7v6e2i) ([raw file](https://github.com/starkware-libs/sequencer/blob/de47b5a5191d1703bb5ddbb02fe6b0e39fa397b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L242)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are doing this in a separate PR...?
</blockquote></details>

Me or Aner...


<!-- Sent from Reviewable.io -->

2024-12-23 05:48 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-23 10:43 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r15, 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535#-:-OEn6OJe9qkHVBGLilj8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-23 10:43 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2535)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2024-12-23 12:33 UTC, yoavGrs commented
### Merge activity

* **Dec 23, 7:33 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2535).

2024-12-23 12:33 UTC, merged