feat(starknet_integration_tests): end to end integration test as executable (not test)
starkware-libs/sequencer pull request #2598
Opened 2024-12-09 15:52 UTC by lev-starkware

**Stack**:
- #2598 ⬅
- #2597

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-12-09 15:52 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2598)
<!-- Reviewable:end -->

2024-12-09 18:29 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2598)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/starknet_integration_tests/src/bin/e2e_integration_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2598#-ODgdCH8DOJ0lVJ7cTkZ:-ODgdCH8DOJ0lVJ7cTk_:b-xok4o0) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fd70eb71d8d416a09a5357ad533a7292585a30d/crates/starknet_integration_tests/src/bin/e2e_integration_test.rs#L16)):*
> ```XML
>     // Run end to end integration test.
>     end_to_end_integration(tx_generator).await;
> }
> ```

Great!
Could you please also change the test in `tests` dir to directly invoke this executable?

Suggested way:
1. Use `create_shell_command` to invoke the binary from within the test.
2. To get its path, check https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates and look for `CARGO_BIN_EXE_`. 

Going through the env variable should have twofold advantages: 
1. No need for messy dir traversals to find the test binary
2. The doc mentions this way also builds the binary, so no need to do that manually:`Binaries are automatically built when the test is built, unless the binary has required features that are not enabled.`



_Code quote:_
```XML
#[tokio::main]
async fn main() {
    configure_tracing();
    info!("Running integration test setup.");

    // Creates a multi-account transaction generator for integration test
    let tx_generator = create_integration_test_tx_generator();

    // Run end to end integration test.
    end_to_end_integration(tx_generator).await;
}
```


<!-- Sent from Reviewable.io -->

2024-12-10 13:01 UTC, lev-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2598)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/bin/e2e_integration_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2598#-ODgdCH8DOJ0lVJ7cTkZ:-ODkeAIq4_FCXriSoE0V:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fd70eb71d8d416a09a5357ad533a7292585a30d/crates/starknet_integration_tests/src/bin/e2e_integration_test.rs#L16)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Great!
Could you please also change the test in `tests` dir to directly invoke this executable?

Suggested way:
1. Use `create_shell_command` to invoke the binary from within the test.
2. To get its path, check https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates and look for `CARGO_BIN_EXE_`. 

Going through the env variable should have twofold advantages: 
1. No need for messy dir traversals to find the test binary
2. The doc mentions this way also builds the binary, so no need to do that manually:`Binaries are automatically built when the test is built, unless the binary has required features that are not enabled.`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-10 15:06 UTC, Itay-Tsabary-Starkware approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2598)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 15:44 UTC, merged