chore(starknet_integration_tests): running end to end integration test as binary
starkware-libs/sequencer pull request #2642
Opened 2024-12-10 15:29 UTC by lev-starkware

**Stack**:
- #2642 ⬅
- #2598
- #2597

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-12-10 15:29 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2642)
<!-- Reviewable:end -->

2024-12-12 08:37 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2642)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`.github/workflows/sequencer_integration_tests.yml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2642#-ODu-xYPCl7vIE-M79hD:-ODu-xYQ2ZlQ_Tdyb--y:b-x18s0x) ([raw file](https://github.com/starkware-libs/sequencer/blob/70e9d8f9605fead9bc1de301bc414318c419502c/.github/workflows/sequencer_integration_tests.yml#L13)):*
> ```YAML
> 
> env:
>   SEQUENCER_INTEGRATION_TESTS: 1
> ```

Please also delete the following function:
https://github.com/starkware-libs/sequencer/blob/main/crates/starknet_integration_tests/src/utils.rs#L253-L255



_Code quote:_
```YAML
 SEQUENCER_INTEGRATION_TESTS: 1
```


<!-- Sent from Reviewable.io -->

2024-12-12 09:39 UTC, lev-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2642)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`.github/workflows/sequencer_integration_tests.yml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2642#-ODu-xYPCl7vIE-M79hD:-ODuAqQs52lAs0mJ9Mf0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/70e9d8f9605fead9bc1de301bc414318c419502c/.github/workflows/sequencer_integration_tests.yml#L13)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please also delete the following function:
https://github.com/starkware-libs/sequencer/blob/main/crates/starknet_integration_tests/src/utils.rs#L253-L255
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-12 09:55 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2642#-:-ODuHnmo86poRT2b1UC5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)



<!-- Sent from Reviewable.io -->

2024-12-15 09:57 UTC, merged