test(starknet_state_sync): test state sync runner after refactor to p2p
starkware-libs/sequencer pull request #2695
Opened 2024-12-16 13:07 UTC by AlonLStarkWare

2024-12-16 13:07 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2695)
<!-- Reviewable:end -->

2024-12-19 07:45 UTC, ShahakShama requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2695)* status: all files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare and @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/runner/test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2695#-OESrfQo4VaxOGp6A-ie:-OESrfQo4VaxOGp6A-if:bganams) ([raw file](https://github.com/starkware-libs/sequencer/blob/375c4bcc1003f2323f37d03c334e4a768cf2d8c8/crates/starknet_state_sync/src/runner/test.rs#L20)):*
> ```XML
> 
> #[test]
> fn run_returns_when_sync_client_future_returns() {
> ```

Add one for server as well
___
*[`crates/starknet_state_sync/src/runner/test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2695#-OESrjHp7WULKnhEgyCl:-OESrjHp7WULKnhEgyCm:b-ht0ysk) ([raw file](https://github.com/starkware-libs/sequencer/blob/375c4bcc1003f2323f37d03c334e4a768cf2d8c8/crates/starknet_state_sync/src/runner/test.rs#L30)):*
> ```XML
> 
> #[test]
> fn run_returns_error_when_sync_server_future_returns() {
> ```

Keep the same order as the termination tests (network, client, server)


<!-- Sent from Reviewable.io -->

2024-12-19 10:03 UTC, AlonLStarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2695)* status: all files reviewed, 1 unresolved discussion (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/starknet_state_sync/src/runner/test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2695#-OESrfQo4VaxOGp6A-ie:-OETLf851Sh3EZDukP7f:b-y941cj) ([raw file](https://github.com/starkware-libs/sequencer/blob/375c4bcc1003f2323f37d03c334e4a768cf2d8c8/crates/starknet_state_sync/src/runner/test.rs#L20)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add one for server as well
</blockquote></details>

Because the server is a future without a value unlike the client and network which return a result, there is only one flow to test for the server.


<!-- Sent from Reviewable.io -->

2024-12-22 12:02 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2695)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/runner/test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2695#-OEiEmeF5-_59xnZs1LC:-OEiEmeF5-_59xnZs1LD:b-3z6kyh) ([raw file](https://github.com/starkware-libs/sequencer/blob/375c4bcc1003f2323f37d03c334e4a768cf2d8c8/crates/starknet_state_sync/src/runner/test.rs#L30)):*
> ```XML
> 
> #[test]
> fn run_returns_error_when_sync_server_future_returns() {
> ```

You should fix the source code to return Ok(()) if the sync server component finished and change this test accordingly


<!-- Sent from Reviewable.io -->

2024-12-22 13:33 UTC, AlonLStarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2695)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/starknet_state_sync/src/runner/test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2695#-OEiEmeF5-_59xnZs1LC:-OEiZQMw4dYaDe1SP1So:b984n1u) ([raw file](https://github.com/starkware-libs/sequencer/blob/375c4bcc1003f2323f37d03c334e4a768cf2d8c8/crates/starknet_state_sync/src/runner/test.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should fix the source code to return Ok(()) if the sync server component finished and change this test accordingly
</blockquote></details>

I don't really understand why but done


<!-- Sent from Reviewable.io -->

2024-12-22 13:45 UTC, ShahakShama requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2695)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/runner/test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2695#-OEiEmeF5-_59xnZs1LC:-OEibI578rX7CFS79RQR:bufvjwy) ([raw file](https://github.com/starkware-libs/sequencer/blob/375c4bcc1003f2323f37d03c334e4a768cf2d8c8/crates/starknet_state_sync/src/runner/test.rs#L30)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

I don't really understand why but done
</blockquote></details>

Rename the test as well

why - There's no difference between this case and the sync client case. In both cases one future finishes so they should return the same


<!-- Sent from Reviewable.io -->

2024-12-26 12:44 UTC, AlonLStarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2695)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/starknet_state_sync/src/runner/test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2695#-OEiEmeF5-_59xnZs1LC:-OF1zS5OC3Z5V8wW0x1B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/375c4bcc1003f2323f37d03c334e4a768cf2d8c8/crates/starknet_state_sync/src/runner/test.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename the test as well

why - There's no difference between this case and the sync client case. In both cases one future finishes so they should return the same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-31 07:48 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2695#-:-OFQg3A22ZkFv_PFAxDL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 07:29 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2695#-:-OFVlG35DSzlRxo6-hSF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 11:07 UTC, merged