feat(starknet_batcher): extract validate height matches storage
starkware-libs/sequencer pull request #2732
Opened 2024-12-17 14:37 UTC by ArniStarkware

2024-12-17 14:38 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2732)
<!-- Reviewable:end -->

2024-12-17 14:38 UTC, ArniStarkware commented
* **#2733** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2733?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2732** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2732?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2732?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-18 08:48 UTC, alonh5 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2732)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2732#-OENx75T-h_cmtOugmST:-OENx75U1NMm966RXwKY:byh3uki) (no related file):*
This PR can be closed. See comment in next PR.


<!-- Sent from Reviewable.io -->

2024-12-18 11:25 UTC, ArniStarkware commented
Closing this PR. We decided to handle the other use case with a simple panic.

2024-12-18 11:25 UTC, closed without merging