refactor(consensus): add handling proposal part as branch in the select
starkware-libs/sequencer pull request #2737
Opened 2024-12-17 15:34 UTC by asmaastarkware

2024-12-17 15:34 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2737)
<!-- Reviewable:end -->

2024-12-17 18:25 UTC, matan-starkware requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2737)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2737#-OEKnuwsCGQy9kUm7BRT:-OEKnuwsCGQy9kUm7BRU:b-gebev8):*
Explain the cancellation safety.



_Code quote:_
```
- aaa4977: refactor(consensus): add handling proposal part as branch in the select
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2737#-OEKoAxd9SK_GuQO8FX6:-OEKoAxd9SK_GuQO8FX7:b3wv85t) ([raw file](https://github.com/starkware-libs/sequencer/blob/aaa49778753c4025cc98beb8c350554f8fec602d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L405)):*
> ```XML
>                 tokio::select! {
>                     _ = notify_clone.notified() => {
>                         // TODO(Asmaa): Tell the batcher to abort.
> ```

And put a warn log (and below)



_Code quote:_
```XML
                        // TODO(Asmaa): Tell the batcher to abort.
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 413 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2737#-OEKo57_2_pF16IvHv77:-OEKo57_2_pF16IvHv78:b-760icu) ([raw file](https://github.com/starkware-libs/sequencer/blob/aaa49778753c4025cc98beb8c350554f8fec602d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L413)):*
> ```XML
>                     }
>                     proposal_part = content_receiver.next() => {
>                         match handle_proposal_part(height, proposal_id, batcher.as_ref(), proposal_part, &mut content, chain_id.clone()).await {
> ```

Too long. I think you need to manually format because it's inside a macro.



_Code quote:_
```XML
                        match handle_proposal_part(height, proposal_id, batcher.as_ref(), proposal_part, &mut content, chain_id.clone()).await {
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 535 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2737#-OEKrIYNEgrZ9Ae5XAVA:-OEKrIYNEgrZ9Ae5XAVB:bh1bqbp) ([raw file](https://github.com/starkware-libs/sequencer/blob/aaa49778753c4025cc98beb8c350554f8fec602d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L535)):*
> ```XML
>     content: &mut Vec<ExecutableTransaction>,
>     chain_id: ChainId,
> ) -> Result<Option<(ProposalContentId, ProposalFin)>, ()> {
> ```

Returning an empty error feels wrong. What about 

enum HandledProposalPart {
    Continue,
    Finished(Id, Fin),
    Failed,
}



_Suggestion:_
```XML
) -> HandledProposalPart {
```


<!-- Sent from Reviewable.io -->

2024-12-18 10:29 UTC, asmaastarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2737)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2737#-OEKoAxd9SK_GuQO8FX6:-OEO11Q9B7J29dB4ZS4S:b-njc7sv) ([raw file](https://github.com/starkware-libs/sequencer/blob/aaa49778753c4025cc98beb8c350554f8fec602d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L405)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

And put a warn log (and below)
</blockquote></details>

batcher abort next PR


<!-- Sent from Reviewable.io -->

2024-12-18 14:04 UTC, matan-starkware approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2737)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)



<!-- Sent from Reviewable.io -->

2024-12-18 14:05 UTC, merged