fix(consensus): make sure StreamHandler sends receiver on message zero
starkware-libs/sequencer pull request #2748
Opened 2024-12-18 09:48 UTC by guy-starkware

2024-12-18 09:48 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2748)
<!-- Reviewable:end -->

2024-12-18 09:49 UTC, guy-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2748?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2748** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2748?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2748?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2746** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2746?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2745** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2745?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2730** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2730?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-18 15:34 UTC, matan-starkware requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2748)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2748#-OEPOcRKC4Dy9HpT2HB3:-OEPOcRKC4Dy9HpT2HB4:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/be4b2b6aee509bbd99547d05bd01046ff731453a/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L283)):*
> ```XML
>                 // // TODO(guyn): reconsider the "expect" here.
>                 // self.inbound_channel_sender.try_send(receiver).expect("Send should succeed");
>                 StreamData::new()
> ```





_Suggestion:_
```XML
                StreamData::new()
```


<!-- Sent from Reviewable.io -->

2024-12-18 16:08 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2748)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2748#-OEPOcRKC4Dy9HpT2HB3:-OEPWgkqBsAIyovo2bL3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/be4b2b6aee509bbd99547d05bd01046ff731453a/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L283)):*
> ```XML
>                 // // TODO(guyn): reconsider the "expect" here.
>                 // self.inbound_channel_sender.try_send(receiver).expect("Send should succeed");
>                 StreamData::new()
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-19 07:45 UTC, matan-starkware approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2024-12-22 12:57 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2748)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @graphite-app[bot] and @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-12-22 12:57 UTC, guy-starkware commented on crates/sequencing/papyrus_consensus/src/stream_handler_test.rs
> +        // Get the receiver for the first stream.
:thumbsup: 
<!-- Reviewable comment -OEiRDtj8rVSJFR9NneC:b4c9lyr -->
<!-- Sent from Reviewable.io -->

2024-12-22 12:57 UTC, guy-starkware reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2748)* status: all files reviewed, 1 unresolved discussion (waiting on @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-12-22 14:09 UTC, guy-starkware reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2748)* status: all files reviewed, 1 unresolved discussion (waiting on @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-12-23 09:06 UTC, guy-starkware reviewed
> Dismissed @graphite-app[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2024-12-23 09:11 UTC, merged

2024-12-23 09:11 UTC, guy-starkware commented
### Merge activity

* **Dec 23, 4:11 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2748).