chore(cairo_native): add the compilation  of native to the flow
starkware-libs/sequencer pull request #2770
Opened 2024-12-18 15:56 UTC by meship-starkware

2024-12-18 15:56 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2770)
<!-- Reviewable:end -->

2024-12-18 16:09 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEPVbTVBMkhZCpHKEOJ:-OEPVbTVBMkhZCpHKEOK:bhcj8t4) ([raw file](https://github.com/starkware-libs/sequencer/blob/1600a7deb88836807b3b2a147ea3088ff63a70b8/crates/papyrus_state_reader/src/papyrus_state.rs#L156)):*
> ```XML
>         #[cfg(feature = "cairo_native")]
>         {
>             let versioned_constants = VersionedConstants::latest_constants();
> ```

We should probably add the min Sierra version to the Papyrus reader instead. 



_Code quote:_
```XML
let versioned_constants = VersionedConstants::latest_constants();
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEPWq2Q0PuKX-B_hwBu:-OEPWq2Q0PuKX-B_hwBv:bpky1n9) ([raw file](https://github.com/starkware-libs/sequencer/blob/1600a7deb88836807b3b2a147ea3088ff63a70b8/crates/papyrus_state_reader/src/papyrus_state.rs#L195)):*
> ```XML
>                             self.contract_class_manager
>                                 .get_sierra(&class_hash)
>                                 .expect("Sierra class not found"),
> ```

this is not right if we are in cairo0 we wont have the sierra in the cache need to fix 



_Code quote:_
```XML
                            self.contract_class_manager
                                .get_sierra(&class_hash)
                                .expect("Sierra class not found"),
```


<!-- Sent from Reviewable.io -->

2024-12-22 08:58 UTC, noaov1 requested changes
> Reviewed 1 of 3 files at r2, 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEh0UrH90O7POJ0X_gb:-OEh0UrI5s29MDOy5hNZ:b-k9ogsm) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L55)):*
> ```XML
>     /// Returns a V1 contract if found, or a V0 contract if a V1 contract is not
>     /// found, or an `Error` otherwise.
>     fn get_compiled_class_inner(&self, class_hash: ClassHash) -> StateResult<InnerCallReturnType> {
> ```

Why not cache the sierra (and the casm) within this method to avoid returning the sierra?



_Code quote:_
```XML
    fn get_compiled_class_inner(&self, class_hash: ClassHash) -> StateResult<InnerCallReturnType> {
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 122 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhZl-g5GGgj7RZ20E7:-OEhZl-h-Qi3LwoPxjbU:b-ente21) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L122)):*
> ```XML
> 
>     #[cfg(feature = "cairo_native")]
>     fn get_casm_and_sierra_when_casm_in_cache(
> ```

Consider defining a method that fetches sierra (starting from the sierra cache and then papyrus)



_Code quote:_
```XML
    fn get_casm_and_sierra_when_casm_in_cache(
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 249 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhWhXzBicLr1wmZzGj:-OEhWhXzBicLr1wmZzGk:b-leo7x3) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L249)):*
> ```XML
>                                     Some(Arc::new(
>                                         sierra.expect("Sierra class should exist in cairo1 flow."),
>                                     )),
> ```

Note that this is already checked in `couple_casm_and_sierra` (which is called in `get_compiled_class_inner`.



_Code quote:_
```XML
                            match versioned_casm {
                                VersionedRunnableCompiledClass::Cairo0(casm) => {
                                    assert!(sierra.is_none(), "Sierra should be None for Cairo0.");
                                    (VersionedRunnableCompiledClass::Cairo0(casm), None)
                                }
                                VersionedRunnableCompiledClass::Cairo1((casm, sierra_version)) => (
                                    VersionedRunnableCompiledClass::Cairo1((casm, sierra_version)),
                                    Some(Arc::new(
                                        sierra.expect("Sierra class should exist in cairo1 flow."),
                                    )),
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 256 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhYcYn1Say3aHEISlZ:-OEhYcYn1Say3aHEISl_:b-ora0ge) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L256)):*
> ```XML
> 
>                     let versioned_casm = casm.clone();
>                     match sierra {
> ```

Consider matching  the cairo version



_Code quote:_
```XML
                    match sierra {
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 265 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhYUStD1hmwISbnoDN:-OEhYUStD1hmwISbnoDO:b-k38zx3) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L265)):*
> ```XML
>                                 _,
>                             )) = casm
>                             {
> ```

Can you please cache the sierra as well?
cc @avi-starkware 


<!-- Sent from Reviewable.io -->

2024-12-22 09:03 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 155 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEh_5yf5q-Bu6nI-PRM:-OEh_5yg9Ae1T6vLqv9i:b-qunm1z) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L155)):*
> ```XML
>             }
>         }
>     }
> ```

If you don't have both casm and sierra, you anyway have to go through `get_casm_and_sierra` to get the missing contract. So I think we can reduce the amount of flows if we just try to get both contracts from cache, and if both are not in cache then fetch both from the state_reader.

Alternatively, if it is easy to add `get_sierra` to the state reader, then we should consider separating the flow that fetches sierra from the flow that fetches casm.



_Code quote:_
```XML
    #[cfg(feature = "cairo_native")]
    fn get_casm_and_sierra_when_casm_in_cache(
        &self,
        class_hash: ClassHash,
        versioned_casm: VersionedRunnableCompiledClass,
    ) -> StateResult<(VersionedRunnableCompiledClass, Option<Arc<SierraContractClass>>)> {
        match versioned_casm {
            // Cairo0 does not have a sierra class.
            VersionedRunnableCompiledClass::Cairo0(casm) => {
                Ok((VersionedRunnableCompiledClass::Cairo0(casm), None))
            }
            VersionedRunnableCompiledClass::Cairo1((casm, sierra_version)) => {
                let new_versioned_casm =
                    VersionedRunnableCompiledClass::Cairo1((casm, sierra_version));
                //
                let sierra_option = self.contract_class_manager.get_sierra(&class_hash);
                match sierra_option {
                    Some(sierra) => Ok((new_versioned_casm, Some(sierra))),
                    None => {
                        // We assume that the class is already declared because the casm was in the
                        // cache.
                        let (_, option_sierra) = self
                            .reader()?
                            .get_casm_and_sierra(&class_hash)
                            .map_err(|err| StateError::StateReadError(err.to_string()))?;
                        let sierra = option_sierra.expect(
                            "Should be able to fetch a Sierra class if its definition exists, \
                             database is inconsistent.",
                        );
                        Ok((new_versioned_casm, Some(Arc::new(sierra))))
                    }
                }
            }
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-12-22 09:26 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 225 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhfaDyD7uEJYQyEcIL:-OEhfaDyD7uEJYQyEcIM:b418n3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L225)):*
> ```XML
>                         }
>                     }
>                 }
> ```

These nested `match`s get confusing.



_Suggestion:_
```XML
            if let Some(native_compiled_class) = native_versioned_contract_class {
                // we already compiled to native and have the cached version
                Some(cached_native) => {
                    match cached_native {
                        CachedCairoNative::Compiled(compiled_native) => {
                            Ok(RunnableCompiledClass::from(compiled_native))
                        }
                        // for some reason the compilation failed, we use the non cairo native flow.
                        CachedCairoNative::CompilationFailed => {
                            self.get_compiled_class_non_native_flow(class_hash)
                        }
                    }
                }
            }
```


<!-- Sent from Reviewable.io -->

2024-12-22 09:48 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 8 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 267 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhhbzT6K2hDZOlLY-1:-OEhhbzU0aD_4yCM05Jy:b-5j53yg) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L267)):*
> ```XML
>                             {
>                                 self.contract_class_manager
>                                     .send_compilation_request((class_hash, sierra, casm));
> ```

You can also add the flow where native compilation is blocking here (see #2771)
You can share code with the case where the compiled native already exists in cache.



_Suggestion:_
```XML
                                self.contract_class_manager
                                    .send_compilation_request((class_hash, sierra, casm));
                                if self.contract_class_manager.config.wait_on_native_compilation {
                                    /// Get native compiled class from cache
                                    ...
                                    Ok(RunnableCompiledClass::from(native)
                                }
```


<!-- Sent from Reviewable.io -->

2024-12-23 12:28 UTC, meship-starkware reviewed
> Dismissed @graphite-app[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @graphite-app[bot], and @noaov1)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEh0UrH90O7POJ0X_gb:-OEiQFXg91WBvv1hxjA5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L55)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not cache the sierra (and the casm) within this method to avoid returning the sierra?
</blockquote></details>

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 122 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhZl-g5GGgj7RZ20E7:-OEnUFtpEMfgGiMO5o0m:b-96kgm7) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L122)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining a method that fetches sierra (starting from the sierra cache and then papyrus)
</blockquote></details>

Not relevant. 
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 155 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEh_5yf5q-Bu6nI-PRM:-OEnUIgf-JY4vYjuYqY7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L155)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

If you don't have both casm and sierra, you anyway have to go through `get_casm_and_sierra` to get the missing contract. So I think we can reduce the amount of flows if we just try to get both contracts from cache, and if both are not in cache then fetch both from the state_reader.

Alternatively, if it is easy to add `get_sierra` to the state reader, then we should consider separating the flow that fetches sierra from the flow that fetches casm.
</blockquote></details>

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 225 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhfaDyD7uEJYQyEcIL:-OEnUM5C1vxN53Hj3HmU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L225)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

These nested `match`s get confusing.
</blockquote></details>

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 249 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhWhXzBicLr1wmZzGj:-OEmW5cfBNXEl_ex1Ogn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L249)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note that this is already checked in `couple_casm_and_sierra` (which is called in `get_compiled_class_inner`.
</blockquote></details>

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 265 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhYUStD1hmwISbnoDN:-OEnUP7wC5rJ4SWKMj4H:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L265)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please cache the sierra as well?
cc @avi-starkware
</blockquote></details>

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 267 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEhhbzT6K2hDZOlLY-1:-OEnUR971qFUrzcfO2NU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99252849cca97c53719c0eae4f8904736565b399/crates/papyrus_state_reader/src/papyrus_state.rs#L267)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

You can also add the flow where native compilation is blocking here (see #2771)
You can share code with the case where the compiled native already exists in cache.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 156 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEj0F6u5BTmI8tCEFEg:-OEj0F6v1E2SvTCK8EyE:b-qi57m3) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c8731706b9381a9f94b9272ba70f421db3fefa9/crates/blockifier/src/state/contract_class_manager.rs#L156)):*
> ```XML
>     pub fn cache_request_contracts(&self, request: &CompilationRequest) {
>         let (class_hash, sierra, casm) = request.clone();
>         self.contract_caches.set_sierra(class_hash, sierra);
> ```

It won't be necessary once the Sierra and Casm Cache are united 



_Code quote:_
```XML
    pub fn cache_request_contracts(&self, request: &CompilationRequest) {
        let (class_hash, sierra, casm) = request.clone();
        self.contract_caches.set_sierra(class_hash, sierra);
```


<!-- Sent from Reviewable.io -->

2024-12-23 12:28 UTC, meship-starkware commented on crates/papyrus_state_reader/src/papyrus_state.rs
> +                            Ok(RunnableCompiledClass::V1(casm))
Done.
<!-- Reviewable comment -OEnCAB96evjS7ewJCTQ:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-12-23 12:35 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @graphite-app[bot], and @noaov1)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 203 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnUq0fC-qd59FmdjWP:-OEnUq0fC-qd59FmdjWQ:b-okjemr) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L203)):*
> ```XML
>                     // for some reason the compilation failed, we use the non cairo native flow.
>                     CachedCairoNative::CompilationFailed => {
>                         return self.get_compiled_class_non_native_flow(class_hash);
> ```

This creates a small inconsistency. If the compilation failed and the Casm and Sierra were in the cache, we would have both. If they were not in the cache, we would only save the cache.  The more common case would be that we have the Casm and sierra in the cache.   



_Code quote:_
```XML
     return self.get_compiled_class_non_native_flow(class_hash);
```


<!-- Sent from Reviewable.io -->

2024-12-23 13:17 UTC, noaov1 reviewed
> Reviewed 2 of 4 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @graphite-app[bot], and @meship-starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 31 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEne4Ho02d0hck62grU:-OEne4Ho02d0hck62grV:bc2de5m) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L31)):*
> ```XML
> type RawPapyrusReader<'env> = papyrus_storage::StorageTxn<'env, RO>;
> type GetCompiledIneerReturnType =
>     StateResult<(RunnableCompiledClass, Option<Arc<SierraContractClass>>)>;
> ```

Can you use `CachedCasm`?



_Code quote:_
```XML
type GetCompiledIneerReturnType =
    StateResult<(RunnableCompiledClass, Option<Arc<SierraContractClass>>)>;
```


<!-- Sent from Reviewable.io -->

2024-12-23 13:50 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 203 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnUq0fC-qd59FmdjWP:-OEnkj9Q9RHCpXBCzzd9:b-wy8eix) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L203)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This creates a small inconsistency. If the compilation failed and the Casm and Sierra were in the cache, we would have both. If they were not in the cache, we would only save the cache.  The more common case would be that we have the Casm and sierra in the cache.
</blockquote></details>

I think this is okay.
We will still only recompile after the cached Cairo native entry gets dropped from cache, which shouldn't happen very often.

WDYT @Yoni-Starkware @noaov1 ?


<!-- Sent from Reviewable.io -->

2024-12-23 14:03 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 127 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnnB7pEElw0Si7KRFX:-OEnnB7pEElw0Si7KRFY:blc4pb3) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L127)):*
> ```XML
>         casm: RunnableCompiledClass,
>     ) -> RunnableCompiledClass {
>         let cached_native = self
> ```

Can you please assert that `wait_on_native_compilation == true`?



_Code quote:_
```XML
        let cached_native = self
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 135 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnnT7S9pmCqegUFJIn:-OEnnT7T8I2FLC7oomQi:b6dgr20) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L135)):*
> ```XML
>                 RunnableCompiledClass::from(compiled_native)
>             }
>             CachedCairoNative::CompilationFailed => casm,
> ```

In this case, do we want to cache the casm?



_Code quote:_
```XML
CachedCairoNative::CompilationFailed => casm,
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 218 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnoKXoA-9KLl28azOC:-OEnoKXoA-9KLl28azOD:b-aawcmf) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L218)):*
> ```XML
> 
>             if let Some(sierra) = option_sierra {
>                 if let RunnableCompiledClass::V1(casm_v1) = casm.clone() {
> ```

We will always enter this `if`, right? You only use it to extract the casm?



_Code quote:_
```XML
 if let RunnableCompiledClass::V1(casm_v1) = casm.clone() {
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 224 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnoe8q5LBvj9HNydPJ:-OEnoe8q5LBvj9HNydPK:b51fkk6) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L224)):*
> ```XML
>                         return Ok(self.handle_sync_compilation(class_hash, casm));
>                     }
>                 } else if casm_cached.is_none() {
> ```

Why is this `if` needed?



_Code quote:_
```XML
if casm_cached.is_none()
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 229 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnomTh51HVgQq4M1iL:-OEnomTh51HVgQq4M1iM:bys8tt5) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L229)):*
> ```XML
>                 }
>             }
>             Ok(casm)
> ```

Do we cache the casm in case of no sierra?



_Code quote:_
```XML
Ok(casm)
```


<!-- Sent from Reviewable.io -->

2024-12-23 14:20 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 135 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnnT7S9pmCqegUFJIn:-OEnrOotEBm_UiOVFNQ1:bd1ijx5) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L135)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In this case, do we want to cache the casm?
</blockquote></details>

It is for testing, so I do not know if it's that important, but we have already cached both the Sierra and Casm.
in here   
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 218 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnoKXoA-9KLl28azOC:-OEnruGrDEDQfI-tQkow:b-7bbiry) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L218)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We will always enter this `if`, right? You only use it to extract the casm?
</blockquote></details>

Yes, I just don't know of any other way. 
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 224 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnoe8q5LBvj9HNydPJ:-OEns1GB7OFbzR6Dptnl:bwbelgx) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L224)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is this `if` needed?
</blockquote></details>

not relevant 
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 229 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnomTh51HVgQq4M1iL:-OEns5EnCDKuQT0T9H5A:bwbelgx) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L229)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we cache the casm in case of no sierra?
</blockquote></details>

not relevant 


<!-- Sent from Reviewable.io -->

2024-12-23 14:30 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 135 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnnT7S9pmCqegUFJIn:-OEnvBLX2JDS6lCbco6W:bzepdzx) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L135)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

It is for testing, so I do not know if it's that important, but we have already cached both the Sierra and Casm.
in here
</blockquote></details>

https://github.com/starkware-libs/sequencer/blob/18129b5a547186f3967d1e597bc2aa2df618ef4b/crates/papyrus_state_reader/src/papyrus_state.rs#L218


<!-- Sent from Reviewable.io -->

2024-12-23 22:28 UTC, noaov1 reviewed
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 203 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnUq0fC-qd59FmdjWP:-OEpYgv7BTRVmbwosQER:bs9q529) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L203)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think this is okay.
We will still only recompile after the cached Cairo native entry gets dropped from cache, which shouldn't happen very often.

WDYT @Yoni-Starkware @noaov1 ?
</blockquote></details>

Good point. I think it can be problematic. Assume we override the casm and sierra tuple with casm only. Assume that for some reason the native entry was overridden as well (maybe the native cache is smaller?). When we ask for that casm, it will not trigger a compilation request.
A suggestion: being consistent: when the native flag is on, always cache the casm with the sierra (we have the sierra anyway, so why not?)
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 117 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEpbBxX0VLokVEBnDJp:-OEpbBxX0VLokVEBnDJq:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a60a63d2bc93b2b4ebfe8a4d85a08d752037d3c/crates/papyrus_state_reader/src/papyrus_state.rs#L117)):*
> ```XML
> 
>     #[cfg(feature = "cairo_native")]
>     fn handle_sync_native_compilation(
> ```





_Suggestion:_
```XML
    fn try_read_native(
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 133 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEpbXddD4IQadQ5wsND:-OEpbXddD4IQadQ5wsNE:btaqov8) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a60a63d2bc93b2b4ebfe8a4d85a08d752037d3c/crates/papyrus_state_reader/src/papyrus_state.rs#L133)):*
> ```XML
>                 RunnableCompiledClass::from(compiled_native)
>             }
>             CachedCairoNative::CompilationFailed => {
> ```

We should consider adding the casm to the `CompilationFailed` variant. 



_Code quote:_
```XML
CachedCairoNative::CompilationFailed
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 78 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEo2p-yEccLxSH7sa5Q:-OEo2p-yEccLxSH7sa5R:bxlaszc) ([raw file](https://github.com/starkware-libs/sequencer/blob/18129b5a547186f3967d1e597bc2aa2df618ef4b/crates/papyrus_state_reader/src/papyrus_state.rs#L78)):*
> ```XML
>                 sierra_version,
>             ))?);
>             return Ok(CachedCasm::WithSierra(runnable_casm, Arc::new(sierra)));
> ```

Do we always want to return the casm with the sierra? Consider conditioning it on the cairo native flag (can be done in a saparate PR). 



_Code quote:_
```XML
            return Ok(CachedCasm::WithSierra(runnable_casm, Arc::new(sierra)));
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 106 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEo42Y5Dxz19YQdDYg2:-OEo42Y5Dxz19YQdDYg3:bs2lidv) ([raw file](https://github.com/starkware-libs/sequencer/blob/18129b5a547186f3967d1e597bc2aa2df618ef4b/crates/papyrus_state_reader/src/papyrus_state.rs#L106)):*
> ```XML
>             Some(contract_class) => match contract_class {
>                 CachedCasm::WithoutSierra(casm) => Ok(casm),
>                 CachedCasm::WithSierra(casm, _) => Ok(casm),
> ```

Can you unify the case? 



_Code quote:_
```XML
                CachedCasm::WithoutSierra(casm) => Ok(casm),
                CachedCasm::WithSierra(casm, _) => Ok(casm),
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 134 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEo4Tb43lGxmWlGHfZG:-OEo4Tb43lGxmWlGHfZH:b-t1nyuh) ([raw file](https://github.com/starkware-libs/sequencer/blob/18129b5a547186f3967d1e597bc2aa2df618ef4b/crates/papyrus_state_reader/src/papyrus_state.rs#L134)):*
> ```XML
>         match cached_native {
>             CachedCairoNative::Compiled(compiled_native) => {
>                 self.contract_class_manager.set_casm(class_hash, cached_casm);
> ```

Why is it needed? Haven't we just cached it?



_Code quote:_
```XML
                self.contract_class_manager.set_casm(class_hash, cached_casm);
```
___
*[`crates/blockifier/src/state/global_cache.rs` line 25 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEoPKlq7qKeZrUBgo2X:-OEoPKlq7qKeZrUBgo2Y:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a60a63d2bc93b2b4ebfe8a4d85a08d752037d3c/crates/blockifier/src/state/global_cache.rs#L25)):*
> ```XML
> }
> impl CachedCasm {
>     pub fn get_casm(&self) -> RunnableCompiledClass {
> ```





_Suggestion:_
```XML
pub fn casm(&self) -> RunnableCompiledClass {
```


<!-- Sent from Reviewable.io -->

2024-12-24 07:58 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 203 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnUq0fC-qd59FmdjWP:-OErUHky1JjMciLqDqdT:b-cnw3sy) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L203)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Good point. I think it can be problematic. Assume we override the casm and sierra tuple with casm only. Assume that for some reason the native entry was overridden as well (maybe the native cache is smaller?). When we ask for that casm, it will not trigger a compilation request.
A suggestion: being consistent: when the native flag is on, always cache the casm with the sierra (we have the sierra anyway, so why not?)
</blockquote></details>

We won't necessarily have the Sierra. We might have to fetch it from the DB, which might make this flow more complicated or make it more complicated to handle non_native flow. Also, I thought that if the compilation failed, we wouldn't want to compile this contract again (unless we clean the cache).
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 78 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEo2p-yEccLxSH7sa5Q:-OErTMSYAiGfA2BWwm3h:br30m8p) ([raw file](https://github.com/starkware-libs/sequencer/blob/18129b5a547186f3967d1e597bc2aa2df618ef4b/crates/papyrus_state_reader/src/papyrus_state.rs#L78)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we always want to return the casm with the sierra? Consider conditioning it on the cairo native flag (can be done in a saparate PR).
</blockquote></details>

I think here we always want to return the casm with sierra and handle it separately in the outer function when caching the casm and sierra  
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 117 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEpbBxX0VLokVEBnDJp:-OErV0Io7TGG5hWuW0tk:brykc1h) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a60a63d2bc93b2b4ebfe8a4d85a08d752037d3c/crates/papyrus_state_reader/src/papyrus_state.rs#L117)):*
> ```XML
> 
>     #[cfg(feature = "cairo_native")]
>     fn handle_sync_native_compilation(
> ```

I don't think this name is indicative enough because we assume we only call this function in the sync case; also, we do not return a result, so try might be a bit confusing. 


<!-- Sent from Reviewable.io -->

2024-12-24 08:39 UTC, noaov1 approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 203 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnUq0fC-qd59FmdjWP:-OErn2p31goLgXU5boU1:b-7zinjp) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L203)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

We won't necessarily have the Sierra. We might have to fetch it from the DB, which might make this flow more complicated or make it more complicated to handle non_native flow. Also, I thought that if the compilation failed, we wouldn't want to compile this contract again (unless we clean the cache).
</blockquote></details>

Oh I see. Then I think the inconsistency is okay. 
Summerzing it here:
Compilation failed:
We have the casm (and sierra) in the cache, return the casm.
We don't have it: set the casm only in the cache.
What happens if the corresponding native entry is overridden?
First case: attempt to re-compile
Second case: return the casm directly.
Since the native component should not affect the execution, it only impacts the runtime performance, which is okay.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 117 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEpbBxX0VLokVEBnDJp:-OErhku_1NJfec-oofCn:b-9caa4r) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a60a63d2bc93b2b4ebfe8a4d85a08d752037d3c/crates/papyrus_state_reader/src/papyrus_state.rs#L117)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I don't think this name is indicative enough because we assume we only call this function in the sync case; also, we do not return a result, so try might be a bit confusing.
</blockquote></details>

An alternative `extract_contract_in_sync_compilation`. (non-blocking)
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 133 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OErgJRpEyRawbm6K22M:-OErgJRpEyRawbm6K22N:bu7xdc6) ([raw file](https://github.com/starkware-libs/sequencer/blob/204fbd663da72d28c86e03eb090a70a324311d72/crates/papyrus_state_reader/src/papyrus_state.rs#L133)):*
> ```XML
>             CachedCairoNative::CompilationFailed => {
>                 self.contract_class_manager
>                     .set_casm(class_hash, CachedCasm::WithoutSierra(casm.clone()));
> ```

Can be removed as well. 



_Code quote:_
```XML
                self.contract_class_manager
                    .set_casm(class_hash, CachedCasm::WithoutSierra(casm.clone()));
```


<!-- Sent from Reviewable.io -->

2024-12-24 08:53 UTC, noaov1 approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-24 09:19 UTC, avi-starkware requested changes
> Reviewed 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/global_cache.rs` line 25 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OErwYEZ2T2A3r1yUFuV:-OErwYEZ2T2A3r1yUFuW:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/blockifier/src/state/global_cache.rs#L25)):*
> ```XML
> }
> impl CachedCasm {
>     pub fn casm(&self) -> RunnableCompiledClass {
> ```





_Suggestion:_
```XML
    pub fn to_runnable_casm(&self) -> RunnableCompiledClass {
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 112 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OErxHZ9-xnuNqnXjpRZ:-OErxHZ9-xnuNqnXjpR_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L112)):*
> ```XML
>                 );
>                 Ok(contract_class_from_db)
>             }
> ```





_Suggestion:_
```XML
        let cached_casm_option = self.contract_class_manager.get_casm(&class_hash);
        match cached_casm_option {
            Some(cached_casm) => Ok(cached_casm.to_runnable_casm()),
            None => {
                let runnable_casm_from_db = self.get_compiled_class_inner(class_hash)?.to_runnable_casm();
                self.contract_class_manager.set_casm(
                    class_hash,
                    CachedCasm::WithoutSierra(runnable_casm_from_db.clone()),
                );
                Ok(runnable_casm_from_db)
            }
```


<!-- Sent from Reviewable.io -->

2024-12-24 09:21 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 112 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OErxHZ9-xnuNqnXjpRZ:-OErxs-N5bm-iI-_YMCh:bse5xux) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L112)):*
> ```XML
>                 );
>                 Ok(contract_class_from_db)
>             }
> ```

Actually, why not make the beginning:
```
        match self.contract_class_manager.get_casm(&class_hash) {
```


<!-- Sent from Reviewable.io -->

2024-12-24 09:27 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 203 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEnUq0fC-qd59FmdjWP:-OEryenG2PUUHYhSohjt:bvjabth) ([raw file](https://github.com/starkware-libs/sequencer/blob/83cf6f298980a0d84c68c89c813157b90a17961b/crates/papyrus_state_reader/src/papyrus_state.rs#L203)):*
> A suggestion: being consistent: when the native flag is on, always cache the casm with the sierra (we have the sierra anyway, so why not?)
Noa I think we shouldn't save the sierra in cases where we get the casm from state and decide that it shouldn't be compiled to native for some reason (due to something like the sierra version, not because it failed compilation). This both save us room in the cache and signals not to send a compilation request in future cache hits (because we have already checked and decided we don't want to compile this sierra to native).


<!-- Sent from Reviewable.io -->

2024-12-24 09:34 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 225 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OErzwk-EwviYX8fyV-x:-OErzwk-EwviYX8fyV-y:be1c1c6) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L225)):*
> ```XML
>                         }
>                     }
>                     Ok(runnable_casm)
> ```

I think we need to print a warning if we find a `CachedCasm` that doesn't contain a V1 compiled class.



_Suggestion:_
```XML
                    } else {
                        log::warning!("A Sierra file was saved in cache for a Cairo0 contract - class hash {class_hash}.
                        This is probably a bug as no Sierra file exists for a Cairo0 contract.")
                    }
                    Ok(runnable_casm)
```


<!-- Sent from Reviewable.io -->

2024-12-24 10:00 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 10 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 117 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs5qC29YO68QUawv0w:-OEs5qC29YO68QUawv0x:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L117)):*
> ```XML
> 
>     #[cfg(feature = "cairo_native")]
>     fn extract_contract_in_sync_compilation(
> ```





_Suggestion:_
```XML
get_contract_after_waiting_on_native_compilation
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 184 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs0hjHATuvaD84Xshg:-OEs0hjHATuvaD84Xshh:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L184)):*
> ```XML
>         #[cfg(feature = "cairo_native")]
>         {
>             // If we turned off the cairo native compilation, we use the non cairo native flow.
> ```





_Suggestion:_
```XML
// If Cairo native compilation is disabled, use the non-Cairo-native flow (i.e., save only casm in cache, and make no compilation requests).
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 189 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs1jtL47xRkv7aH_L1:-OEs1jtL47xRkv7aH_L2:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L189)):*
> ```XML
>             }
> 
>             // We have the Native in cache.
> ```





_Suggestion:_
```XML
            // The cache contains a Cairo-native entry for the given class hash.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 195 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs0ERH-3V4mj5Ufa4Q:-OEs0ERH-3V4mj5Ufa4R:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L195)):*
> ```XML
>                         return Ok(RunnableCompiledClass::from(compiled_native));
>                     }
>                     // for some reason the compilation failed, we use the non cairo native flow.
> ```





_Suggestion:_
```XML
                    // The compilation previously failed. Make no further compilation attempts. Use the non-Cairo-native flow.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 203 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs2R2e9i4wOrrWbCIa:-OEs2R2e9i4wOrrWbCIb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L203)):*
> ```XML
> 
>             let cached_casm = match self.contract_class_manager.get_casm(&class_hash) {
>                 // Casm is in cache.
> ```





_Suggestion:_
```XML
            // Get the `CachedCasm` for the given class hash. Upon cache miss, fetch it from state and cache it. 
            let cached_casm = match self.contract_class_manager.get_casm(&class_hash) {
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 212 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs39-r1BIPYHunRsDO:-OEs39-r1BIPYHunRsDP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L212)):*
> ```XML
>             };
> 
>             match cached_casm {
> ```





_Suggestion:_
```XML
            // If the fetched casm includes a Sierra, send a compilation request.
            // Return the casm.
            // NOTE: We assume that whenever the fetched casm does not include a Sierra, compilation to native is not required.
            match cached_casm {
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 220 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs4WtM17GnE6Dp4g5v:-OEs4WtM17GnE6Dp4g5w:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L220)):*
> ```XML
>                             casm_v1.clone(),
>                         ));
>                         if self.contract_class_manager.wait_on_native_compilation() {
> ```





_Suggestion:_
```XML
                        if self.contract_class_manager.wait_on_native_compilation() {
                            // With this config, sending a compilation request blocks the sender until the compilation compilation completes.
                            // Fetch the resulting native compiled class and return it if compilation succeeded.
```


<!-- Sent from Reviewable.io -->

2024-12-24 10:01 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 98 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs6E4e0Y6NgbjXahZW:-OEs6E4e0Y6NgbjXahZX:b5cluh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L98)):*
> ```XML
>     }
> 
>     fn get_compiled_class_non_native_flow(
> ```

Add docstring



_Code quote:_
```XML
    fn get_compiled_class_non_native_flow(
```


<!-- Sent from Reviewable.io -->

2024-12-24 10:01 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 117 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs5qC29YO68QUawv0w:-OEs6Iqo9yYjxb8I86mP:b-19rxow) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L117)):*
> ```XML
> 
>     #[cfg(feature = "cairo_native")]
>     fn extract_contract_in_sync_compilation(
> ```

+ add docstring


<!-- Sent from Reviewable.io -->

2024-12-24 10:02 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 52 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs6Q5W8-uzmWTrDwwX:-OEs6Q5W8-uzmWTrDwwY:bqslak8) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L52)):*
> ```XML
> 
>     /// Returns a V1 contract if found, or a V0 contract if a V1 contract is not
>     /// found, or an `Error` otherwise.
> ```

Fix the docstring given our changes.



_Code quote:_
```XML
    /// Returns a V1 contract if found, or a V0 contract if a V1 contract is not
    /// found, or an `Error` otherwise.
```


<!-- Sent from Reviewable.io -->

2024-12-24 10:05 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 117 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEs5qC29YO68QUawv0w:-OEs6eZ2Bg9JHyng5vAq:b-oaovn5) ([raw file](https://github.com/starkware-libs/sequencer/blob/e42fa94c11c0b46aa9507cc88189fa2b7a2a9bcc/crates/papyrus_state_reader/src/papyrus_state.rs#L117)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

+ add docstring
</blockquote></details>

Actually, maybe `get_compiled_class_after_waiting_on_native_compilation`
(to be consistent with other method names in this `impl`)


<!-- Sent from Reviewable.io -->

2024-12-24 10:06 UTC, avi-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 12 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-24 11:00 UTC, dorimedini-starkware submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 13 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsJkRO77XT8fZMSn3y:-OEsJkRO77XT8fZMSn3z:bpbja99) (no related file):*
rebase over `main-v0.13.4`


<!-- Sent from Reviewable.io -->

2024-12-24 11:12 UTC, avi-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 13 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-24 11:45 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @noaov1, and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsJkRO77XT8fZMSn3y:-OEsTrKX3wIcW0UGBElx:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rebase over `main-v0.13.4`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-24 12:10 UTC, avi-starkware requested changes
> Reviewed 3 of 4 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 193 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsWsgfCBIKj62ZMQcz:-OEsWsgfCBIKj62ZMQd-:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L193)):*
> ```XML
>             // If Cairo native compilation is disabled, use the non-Cairo-native flow (i.e., save
>             // only casm in cache, and make no compilation requests).
>             if !self.contract_class_manager.run_cairo_native() {
> ```





_Suggestion:_
```XML
            if !self.contract_class_manager.run_cairo_native() {
                // Cairo native is disabled - use the non-Cairo-native flow.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 199 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsXYIG7BF4UpYHzTRO:-OEsXYIG7BF4UpYHzTRP:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L199)):*
> ```XML
>             // This flow is when we have the Native in cache, in this flow we return a runnable
>             // compiled native if the compilation succeed and runnable casm otherwise.
>             if let Some(cached_native) = self.contract_class_manager.get_native(&class_hash) {
> ```





_Suggestion:_
```XML
            // Try fetching native from cache.
            if let Some(cached_native) = self.contract_class_manager.get_native(&class_hash) {
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 206 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsYBrK80Sx0ZpsdejI:-OEsYBrK80Sx0ZpsdejJ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L206)):*
> ```XML
>                     // The compilation previously failed. Make no further compilation attempts. Use
>                     // the non-Cairo-native flow.
>                     CachedCairoNative::CompilationFailed => {
> ```





_Suggestion:_
```XML
                    CachedCairoNative::CompilationFailed => {
                        // The compilation previously failed. Make no further compilation attempts. Use
                        // the non-Cairo-native flow.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 213 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsYsExADItwKUBZCG5:-OEsYsExADItwKUBZCG6:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L213)):*
> ```XML
> 
>             // Get the `CachedCasm` for the given class hash. Upon cache miss, fetch it from state
>             // and cache it.
> ```





_Suggestion:_
```XML
            // Native not found in cache. Get the `CachedCasm` - if not in cache, fetch it from state
            // and cache it.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 240 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsW8lU4CbgwZVTUM3p:-OEsW8lU4CbgwZVTUM3q:bl5m1xh) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L240)):*
> ```XML
>                             // completes. Fetch the resulting native
>                             // compiled class and return it if compilation
>                             // succeeded.
> ```

plus fix the line breaks



_Suggestion:_
```XML
                            // With this config, sending a compilation request blocks the sender
                            // until compilation
                            // completes. Retry fetching Native from cache.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 251 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsYdfoB8yDUP1OX710:-OEsYdfoB8yDUP1OX711:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L251)):*
> ```XML
>                             "A Sierra file was saved in cache for a Cairo0 contract - class hash \
>                              {class_hash}.
>                         This is probably a bug as no Sierra file exists for a Cairo0 contract."
> ```





_Suggestion:_
```XML
                            This is probably a bug as no Sierra file exists for a Cairo0 contract."
```


<!-- Sent from Reviewable.io -->

2024-12-24 12:16 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-24 12:17 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 100 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsaAcF0pDuRTEWnlAV:-OEsaAcF0pDuRTEWnlAW:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L100)):*
> ```XML
>     // Handle get compiled class when cairo native is turned off.
>     // Returns the Runnable Casm from the cache if it exists, otherwise fetches it from the
>     // database.
> ```





_Suggestion:_
```XML
    // Handle `get_compiled_class` when cairo native is turned off.
    // Returns casm from cache if exists, otherwise fetches it from state.
```


<!-- Sent from Reviewable.io -->

2024-12-24 12:20 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 240 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsW8lU4CbgwZVTUM3p:-OEsaaTWA-whXimIgFFY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L240)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

plus fix the line breaks
</blockquote></details>

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 193 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsWsgfCBIKj62ZMQcz:-OEs_rdf8SE4JSzVV_PE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L193)):*
> ```XML
>             // If Cairo native compilation is disabled, use the non-Cairo-native flow (i.e., save
>             // only casm in cache, and make no compilation requests).
>             if !self.contract_class_manager.run_cairo_native() {
> ```

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 199 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsXYIG7BF4UpYHzTRO:-OEs_xfIDAVJArT9NT9M:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L199)):*
> ```XML
>             // This flow is when we have the Native in cache, in this flow we return a runnable
>             // compiled native if the compilation succeed and runnable casm otherwise.
>             if let Some(cached_native) = self.contract_class_manager.get_native(&class_hash) {
> ```

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 206 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsYBrK80Sx0ZpsdejI:-OEsa5iL1mzyNvpd38_g:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L206)):*
> ```XML
>                     // The compilation previously failed. Make no further compilation attempts. Use
>                     // the non-Cairo-native flow.
>                     CachedCairoNative::CompilationFailed => {
> ```

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 251 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsYdfoB8yDUP1OX710:-OEsb5Nm91SI55-BAjNi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L251)):*
> ```XML
>                             "A Sierra file was saved in cache for a Cairo0 contract - class hash \
>                              {class_hash}.
>                         This is probably a bug as no Sierra file exists for a Cairo0 contract."
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-24 12:20 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 119 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsahzE7HZqUga0lBXN:-OEsahzE7HZqUga0lBXO:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L119)):*
> ```XML
>     #[cfg(feature = "cairo_native")]
>     // Returns the native compiled class if the compilation succeeded and the runnable casm upon
>     // failure.
> ```





_Suggestion:_
```XML
    // Handles `get_compiled_class` under the assumption that native compilation has finished.
    // Returns the native compiled class if the compilation succeeded and the runnable casm upon
    // failure.
```


<!-- Sent from Reviewable.io -->

2024-12-24 12:24 UTC, avi-starkware reviewed
> Reviewed 1 of 4 files at r6, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-24 12:24 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 100 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsaAcF0pDuRTEWnlAV:-OEsc5V2-d-N2b4aBXx6:b-sedq7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L100)):*
> ```XML
>     // Handle get compiled class when cairo native is turned off.
>     // Returns the Runnable Casm from the cache if it exists, otherwise fetches it from the
>     // database.
> ```

`Handles` sorry.


<!-- Sent from Reviewable.io -->

2024-12-24 12:25 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 100 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsaAcF0pDuRTEWnlAV:-OEsbvkw9MWcByfSU64l:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L100)):*
> ```XML
>     // Handle get compiled class when cairo native is turned off.
>     // Returns the Runnable Casm from the cache if it exists, otherwise fetches it from the
>     // database.
> ```

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 119 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsahzE7HZqUga0lBXN:-OEsbvKh5eomHhOwfy68:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L119)):*
> ```XML
>     #[cfg(feature = "cairo_native")]
>     // Returns the native compiled class if the compilation succeeded and the runnable casm upon
>     // failure.
> ```

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 213 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsYsExADItwKUBZCG5:-OEsbS8K-xqCTlTQAZA1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L213)):*
> ```XML
> 
>             // Get the `CachedCasm` for the given class hash. Upon cache miss, fetch it from state
>             // and cache it.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-24 12:26 UTC, avi-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r6, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-:-OEscTy67bqTRGi7B2li:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-24 12:48 UTC, noaov1 approved these changes
> Reviewed 1 of 4 files at r13, 1 of 1 files at r14, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2770)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 52 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsajhQ0vzYQ9pue6ps:-OEsajhQ0vzYQ9pue6pt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b6461c62ba0226f2831f6d4dded6613a62c784e/crates/papyrus_state_reader/src/papyrus_state.rs#L52)):*
> ```XML
> 
>     /// Returns a CachedCasm with Sierra if V1 contract is found, or a CachedCasm without Sierra if
>     /// a V1 contract is not found, or an `Error` otherwise.
> ```





_Suggestion:_
```XML
    /// Returns a V1 contract with Sierra if V1 contract is found, or a V0 contract without Sierra if
    /// a V1 contract is not found, or an `Error` otherwise.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 100 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsdLi88W2AnpAcMgno:-OEsdLi88W2AnpAcMgnp:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1a78698e65e72e72707a44cff49dc9d90cbd50a/crates/papyrus_state_reader/src/papyrus_state.rs#L100)):*
> ```XML
>     // Handles `get_compiled_class` when cairo native is turned off.
>     // Returns casm from cache if exists, otherwise fetches it from state.
>     fn get_compiled_class_non_native_flow(
> ```





_Suggestion:_
```XML
    /// Returns casm from cache if exists, otherwise fetches it from state.
    fn fetch_casm(
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 119 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsdi2q4eRLGZRFhqc3:-OEsdi2q4eRLGZRFhqc4:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1a78698e65e72e72707a44cff49dc9d90cbd50a/crates/papyrus_state_reader/src/papyrus_state.rs#L119)):*
> ```XML
>     // Handles `get_compiled_class` under the assumption that native compilation has finished.
>     // Returns the native compiled class if the compilation succeeded and the runnable casm upon
>     // failure.
> ```





_Suggestion:_
```XML
    /// Handles `get_compiled_class` under the assumption that native compilation has finished.
    /// Returns the native compiled class if the compilation succeeded and the runnable casm upon
    /// failure.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 219 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsfmaQDdDj2bi6ZKE9:-OEsfmaR70ahWEJrZHdj:b-wcypyx) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1a78698e65e72e72707a44cff49dc9d90cbd50a/crates/papyrus_state_reader/src/papyrus_state.rs#L219)):*
> ```XML
>                     cached_casm
>                 }
>             };
> ```

This is exactly what `get_compiled_class_non_native_flow` does, no?
 Two differences:
1. return value.
2. with/without sierra.

Consider sharing code (non-blocking)



_Code quote:_
```XML
            let cached_casm = match self.contract_class_manager.get_casm(&class_hash) {
                Some(cached_casm) => cached_casm,
                None => {
                    let cached_casm = self.get_compiled_class_inner(class_hash)?;
                    self.contract_class_manager.set_casm(class_hash, cached_casm.clone());
                    cached_casm
                }
            };
```
___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 247 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2770#-OEsf0xjDB5UcGKEfaAG:-OEsf0xk2pxPhoa_GvBf:b-iyjcs1) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1a78698e65e72e72707a44cff49dc9d90cbd50a/crates/papyrus_state_reader/src/papyrus_state.rs#L247)):*
> ```XML
>                              {class_hash}. This is probably a bug as no Sierra file exists for a \
>                              Cairo0 contract."
>                         );
> ```

I think it should be a panic. 



_Code quote:_
```XML
                        log::warn!(
                            "A Sierra file was saved in cache for a Cairo0 contract - class hash \
                             {class_hash}. This is probably a bug as no Sierra file exists for a \
                             Cairo0 contract."
                        );
```


<!-- Sent from Reviewable.io -->

2024-12-24 12:56 UTC, merged