fix(ci): fix warnings
starkware-libs/sequencer pull request #2775
Opened 2024-12-18 16:55 UTC by giladchase

Without --all-targets they don't run on tests and benchmarks.

2024-12-18 16:56 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2775)
<!-- Reviewable:end -->

2024-12-18 20:14 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2775)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`scripts/run_tests.py` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2775#-OEQOx7LAhFLY3RDAVf9:-OEQOx7LAhFLY3RDAVfA:bhl6cxl) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7e9d61b2be3dee27a4c4dfbedb6c1945a84723a/scripts/run_tests.py#L47)):*
> ```Python
>         elif self == BaseCommand.CLIPPY:
>             clippy_args = package_args if len(package_args) > 0 else ["--workspace"]
>             return ["cargo", "clippy"] + clippy_args + ["--all-targets"]
> ```

nice!!
solves @Itay-Tsabary-Starkware 's issue, right?



_Code quote:_
```Python
return ["cargo", "clippy"] + clippy_args + ["--all-targets"]
```
___
*[`crates/blockifier/Cargo.toml` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2775#-OEQOkee8hKYfmeJockh:-OEQOkee8hKYfmeJocki:bxaqh88) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7e9d61b2be3dee27a4c4dfbedb6c1945a84723a/crates/blockifier/Cargo.toml#L83)):*
> ```TOML
> name = "blockifier_bench"
> path = "bench/blockifier_bench.rs"
> required-features = ["testing"]
> ```

why is this required? didn't the benchmark run without this before?



_Code quote:_
```TOML
required-features = ["testing"]
```


<!-- Sent from Reviewable.io -->

2024-12-19 04:03 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2775)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/Cargo.toml` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2775#-OEQOkee8hKYfmeJockh:-OES3YB--1BbdLR5DKKh:b-n976mh) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7e9d61b2be3dee27a4c4dfbedb6c1945a84723a/crates/blockifier/Cargo.toml#L83)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this required? didn't the benchmark run without this before?
</blockquote></details>

Yep, with all-targets only the "default target" is run, which is everything branching out of lib.rs/main.rs.
all-targets also runs tests, benchmarks and examples.

The required-feature thing is necessary anyway though, since this benchmark doesn't compile without "testing".
___
*[`scripts/run_tests.py` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2775#-OEQOx7LAhFLY3RDAVf9:-OES4FAqBYjJyiSnMfCp:bl41ry4) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7e9d61b2be3dee27a4c4dfbedb6c1945a84723a/scripts/run_tests.py#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nice!!
solves @Itay-Tsabary-Starkware 's issue, right?
</blockquote></details>

It solves the warnings i had on vscode :grimacing: 


<!-- Sent from Reviewable.io -->

2024-12-19 08:17 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2775#-:-OESzUn94bXK5AMW4y5a:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-12-19 08:30 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2775)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`scripts/run_tests.py` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2775#-OEQOx7LAhFLY3RDAVf9:-OET131s8fwxlovRLbYM:b-jj1nwd) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7e9d61b2be3dee27a4c4dfbedb6c1945a84723a/scripts/run_tests.py#L47)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

It solves the warnings i had on vscode :grimacing:
</blockquote></details>

Thanks, it does!
Did we have this check before, and it got removed during recently?


<!-- Sent from Reviewable.io -->

2024-12-19 08:30 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2775#-:-OET1TpF0WNo606ho8A1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-12-19 09:26 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2775)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-12-19 12:29 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2775)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`scripts/run_tests.py` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2775#-OEQOx7LAhFLY3RDAVf9:-OETtJCQ1ZuB2PE_5BA3:bpyw7qp) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7e9d61b2be3dee27a4c4dfbedb6c1945a84723a/scripts/run_tests.py#L47)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Thanks, it does!
Did we have this check before, and it got removed during recently?
</blockquote></details>

No idea


<!-- Sent from Reviewable.io -->

2024-12-19 12:30 UTC, merged