fix(mempool_test_utils): remove unnecessary pub
starkware-libs/sequencer pull request #2803
Opened 2024-12-19 08:09 UTC by yair-starkware

2024-12-19 08:09 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2803)
<!-- Reviewable:end -->

2024-12-19 08:09 UTC, yair-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2803?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2805** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2805?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2804** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2804?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2803** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2803?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2803?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2802** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2802?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2801** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2801?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2724** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2724?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-29 12:25 UTC, alonh5 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2803)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2803#-OFHN0CU357TwxgBpUNn:-OFHN0CU357TwxgBpUNo:b-aenln) ([raw file](https://github.com/starkware-libs/sequencer/blob/8893f3bae9ead81c6589e9368b6d4971f5ea6be8/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L149)):*
> ```XML
> // 2. Execution phase - generate transactions.
> 
> // TODO: Add optional StateReader and assert that the state supports each operation (e.g. nonce).
> ```

Could you explain this TODO?



_Code quote:_
```XML
// TODO: Add optional StateReader and assert that the state supports each operation (e.g. nonce).
```


<!-- Sent from Reviewable.io -->

2024-12-30 10:01 UTC, yair-starkware commented
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2803#-OFHN0CU357TwxgBpUNn:-OFHn0f040VAuHgh3emU:b-m17txq) ([raw file](https://github.com/starkware-libs/sequencer/blob/8893f3bae9ead81c6589e9368b6d4971f5ea6be8/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L149)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Could you explain this TODO?
</blockquote></details>

Functions like `mark_deployed` require that the storage will be in the desired state.
We could assert that in the function if we had a state reader.


<!-- Sent from Reviewable.io -->

2024-12-30 11:28 UTC, alonh5 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2803)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-12-30 11:28 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2803#-:-OFMJkW53UR3MphAzKyg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 08:25 UTC, yair-starkware reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2803)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 08:45 UTC, merged