feaT(mempool_test_utils): utility to create transfer txs
starkware-libs/sequencer pull request #2804
Opened 2024-12-19 08:09 UTC by yair-starkware

2024-12-19 08:09 UTC, yair-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2804?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2805** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2805?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2804** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2804?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2804?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2803** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2803?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2802** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2802?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2801** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2801?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2724** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2724?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-29 12:28 UTC, alonh5 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2804)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-OFHNOVO16M3vG3Z63qt:-OFHNOVO16M3vG3Z63qu:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c97512743045a5a89fb261709380d3dc5d5fd3b1/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L340)):*
> ```XML
>     }
> 
>     pub fn generate_transfer(&mut self, to: &Contract) -> RpcTransaction {
> ```





_Suggestion:_
```XML
receiver
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-OFHNhyE19QrGRPMYBrq:-OFHNhyF3jewLYfI8WPI:b-e5i3pl) ([raw file](https://github.com/starkware-libs/sequencer/blob/c97512743045a5a89fb261709380d3dc5d5fd3b1/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L340)):*
> ```XML
>     }
> 
>     pub fn generate_transfer(&mut self, to: &Contract) -> RpcTransaction {
> ```

This isn't used in this stack, right? Did you test that the transfer works?


<!-- Sent from Reviewable.io -->

2024-12-29 12:49 UTC, alonh5 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2804)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-OFHNOVO16M3vG3Z63qt:-OFHSZR07XjZiPW80KjQ:bsjdzlu) ([raw file](https://github.com/starkware-libs/sequencer/blob/c97512743045a5a89fb261709380d3dc5d5fd3b1/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L340)):*
> ```XML
>     }
> 
>     pub fn generate_transfer(&mut self, to: &Contract) -> RpcTransaction {
> ```

Or `recipient` actually.


<!-- Sent from Reviewable.io -->

2024-12-30 10:42 UTC, yair-starkware commented
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-OFHNhyE19QrGRPMYBrq:-OFM8pMk12ANe8VlQ3p9:bn3zfr) ([raw file](https://github.com/starkware-libs/sequencer/blob/c97512743045a5a89fb261709380d3dc5d5fd3b1/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L340)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This isn't used in this stack, right? Did you test that the transfer works?
</blockquote></details>

It is used but not necessary since we fund the account in the setup.
I wrote this code before I realized it couldn't work, so I decided to leave it.


<!-- Sent from Reviewable.io -->

2024-12-30 11:25 UTC, alonh5 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2804)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-OFHNhyE19QrGRPMYBrq:-OFMImrp2y1O3KmFTr00:b-1cb6fg) ([raw file](https://github.com/starkware-libs/sequencer/blob/c97512743045a5a89fb261709380d3dc5d5fd3b1/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L340)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It is used but not necessary since we fund the account in the setup.
I wrote this code before I realized it couldn't work, so I decided to leave it.
</blockquote></details>

Yes, I think it's good to leave it. I'm just asking if you made sure this tx passes at all, in case someone uses this.


<!-- Sent from Reviewable.io -->

2024-12-30 11:51 UTC, yair-starkware commented
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-OFHNhyE19QrGRPMYBrq:-OFMOv1LDwX3DUbzL2Pw:bjx21qy) ([raw file](https://github.com/starkware-libs/sequencer/blob/c97512743045a5a89fb261709380d3dc5d5fd3b1/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L340)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yes, I think it's good to leave it. I'm just asking if you made sure this tx passes at all, in case someone uses this.
</blockquote></details>

Yes, it is part of the e2e flow test


<!-- Sent from Reviewable.io -->

2024-12-31 08:11 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2804)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-OFHNOVO16M3vG3Z63qt:-OFQl3Ta0NBXkcGk95Vt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c97512743045a5a89fb261709380d3dc5d5fd3b1/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L340)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Or `recipient` actually.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 10:35 UTC, alonh5 requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2804)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-OFHNhyE19QrGRPMYBrq:-OFWQ_Nt2ODlCIqAQ6Ck:b-ufm0c9) ([raw file](https://github.com/starkware-libs/sequencer/blob/c97512743045a5a89fb261709380d3dc5d5fd3b1/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L340)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Yes, it is part of the e2e flow test
</blockquote></details>

Great :)
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 330 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-OFWQTD5B2gKfMeuC4rz:-OFWQTD5B2gKfMeuC4s-:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae9ad0ae701e682c5ac974ed005ef024a1f018b7/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L330)):*
> ```XML
>     }
> 
>     pub fn generate_transfer(&mut self, receipt: &Contract) -> RpcTransaction {
> ```





_Suggestion:_
```XML
recipient
```


<!-- Sent from Reviewable.io -->

2025-01-01 11:20 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2804)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 330 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-OFWQTD5B2gKfMeuC4rz:-OFW_ztt9iymURqwFr2n:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae9ad0ae701e682c5ac974ed005ef024a1f018b7/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L330)):*
> ```XML
>     }
> 
>     pub fn generate_transfer(&mut self, receipt: &Contract) -> RpcTransaction {
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 13:06 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2804#-:-OFWySGv1VL8EDCaUM1-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 08:21 UTC, merged