feat(mempool_test_utils): util to generate deploy account txs
starkware-libs/sequencer pull request #2805
Opened 2024-12-19 08:09 UTC by yair-starkware

2024-12-19 08:09 UTC, yair-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2805?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2805** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2805?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2805?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2804** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2804?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2803** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2803?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2802** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2802?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2801** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2801?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2724** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2724?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-29 12:42 UTC, alonh5 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2805)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2805#-OFHQmQ_552br5Kr10LM:-OFHQmQ_552br5Kr10LN:b-utlgsj) ([raw file](https://github.com/starkware-libs/sequencer/blob/52b48fd28173d958fa23f38290c6c3b2e95e77f2/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L195)):*
> ```XML
> /// let deploy_account_tx = tx_generator.account_with_id_mut(2).generate_deploy_account();
> /// // Mark the undeployed account as deployed.
> /// tx_generator.account_with_id_mut(2).mark_deployed();
> ```

Is this how it's meant to be used? What if the deploy account tx was generated but didn't pass? We still mark it as deployed?



_Code quote:_
```XML
/// // Generate a deploy account transaction for the undeployed account.
/// let deploy_account_tx = tx_generator.account_with_id_mut(2).generate_deploy_account();
/// // Mark the undeployed account as deployed.
/// tx_generator.account_with_id_mut(2).mark_deployed();
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2805#-OFHQJ9G6cG3wyI5TIdg:-OFHQJ9HCB1gblDihNln:b-w2eg8u) ([raw file](https://github.com/starkware-libs/sequencer/blob/52b48fd28173d958fa23f38290c6c3b2e95e77f2/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L376)):*
> ```XML
>         );
>         let nonce = self.next_nonce();
>         assert_ne!(nonce, nonce!(0), "The deploy account tx should have nonce 0.");
> ```

How did this pass?



_Suggestion:_
```XML
assert_eq!(nonce, nonce!(0), "The deploy account tx should have nonce 0.");
```


<!-- Sent from Reviewable.io -->

2024-12-31 08:35 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2805)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2805#-OFHQmQ_552br5Kr10LM:-OFMP2bQ2a53H7ba9mv1:ba3dfob) ([raw file](https://github.com/starkware-libs/sequencer/blob/52b48fd28173d958fa23f38290c6c3b2e95e77f2/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L195)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this how it's meant to be used? What if the deploy account tx was generated but didn't pass? We still mark it as deployed?
</blockquote></details>

Removed
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2805#-OFHQJ9G6cG3wyI5TIdg:-OFQnhB70sY_zPxzqR0R:b8eglx4) ([raw file](https://github.com/starkware-libs/sequencer/blob/52b48fd28173d958fa23f38290c6c3b2e95e77f2/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L376)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

How did this pass?
</blockquote></details>

Because I fixed it in a later PR where I actually used this function.
Moved the fix to this PR anyway


<!-- Sent from Reviewable.io -->

2025-01-01 10:37 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2805#-:-OFWRKL0DAwvtA_81K6Z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 13:07 UTC, alonh5 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 10:02 UTC, merged