wip
starkware-libs/sequencer pull request #2807
Opened 2024-12-19 08:09 UTC by yair-starkware

2024-12-19 08:09 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2807)
<!-- Reviewable:end -->

2024-12-19 08:09 UTC, yair-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2807?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2807** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2807?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2807?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2806** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2806?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2805** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2805?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2804** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2804?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2803** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2803?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2802** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2802?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2801** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2801?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2724** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2724?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-29 13:24 UTC, alonh5 requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2807)* status: all files reviewed, 7 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 0 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHWShi6ySXkCAg7J6C:-OFHWInd0CG9I_LoINnv:bjg2tkt) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/src/state_reader.rs#L0)):*
Can you explain the changes in this file? Was this one of the bugs you found?
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFH_EYvC56TXLhRkcuw:-OFH_EYvC56TXLhRkcux:b-mrpqt1) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L102)):*
> ```XML
>         Box::new(move |tx_generator: &mut MultiAccountTransactionGenerator| {
>             fund_new_account(tx_generator.account_with_id_mut(ACCOUNT_ID_0), &undeployed_account)
>         }),
> ```

Can you create a function for this and remove the Boxes? You can get the undeployed account with its ID.
Also, do we need an extra block or can we have the funding and the deployment in the same block?



_Code quote:_
```XML
        Box::new(move |tx_generator: &mut MultiAccountTransactionGenerator| {
            fund_new_account(tx_generator.account_with_id_mut(ACCOUNT_ID_0), &undeployed_account)
        }),
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHYQhM4O6QLEgHe8jt:-OFHYQhM4O6QLEgHe8ju:ba3dfmt) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L128)):*
> ```XML
>         test_tx_hashes_scenarios.len(),
>         "Expected the same number of heights and scenarios"
>     );
> ```

Remove.



_Code quote:_
```XML
    assert_eq!(
        n_heights,
        expected_content_ids.len(),
        "Expected the same number of heights and content ids"
    );
    assert_eq!(
        n_heights,
        create_rpc_txs_scenarios.len(),
        "Expected the same number of heights and scenarios"
    );
    assert_eq!(
        n_heights,
        test_tx_hashes_scenarios.len(),
        "Expected the same number of heights and scenarios"
    );
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 279 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHZ-dZ-ve3lvu9JDXD:-OFHZ-dZ-ve3lvu9JDXE:b-32uv7g) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L279)):*
> ```XML
> 
> fn fund_new_account(
>     funding_acount: &mut AccountTransactionGenerator,
> ```

You should add `Code Spell Checker` extension to vscode.



_Suggestion:_
```XML
funding_account
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 280 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHZEmB1y4_4vgvT6yh:-OFHZEmB1y4_4vgvT6yi:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L280)):*
> ```XML
> fn fund_new_account(
>     funding_acount: &mut AccountTransactionGenerator,
>     to: &Contract,
> ```





_Suggestion:_
```XML
recipient
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 293 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHZtmn14OTdTXIKV3F:-OFHZtmn14OTdTXIKV3G:b3x17c9) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L293)):*
> ```XML
> fn deploy_account(tx_generator: &mut MultiAccountTransactionGenerator) -> Vec<RpcTransaction> {
>     assert_eq!(tx_generator.account_tx_generators().len(), UNDEPLOYED_ACCOUNT_ID + 1);
>     let undeployed_account_tx_generator = tx_generator.account_tx_generators().last_mut().unwrap();
> ```

Can you instead use the ID to get the account? Why do we need to check that it's the last?



_Code quote:_
```XML
    assert_eq!(tx_generator.account_tx_generators().len(), UNDEPLOYED_ACCOUNT_ID + 1);
    let undeployed_account_tx_generator = tx_generator.account_tx_generators().last_mut().unwrap();
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 302 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHY3nd4SXtWYHAHCD9:-OFHY3nd4SXtWYHAHCDA:b-z5kx1p) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L302)):*
> ```XML
>     assert_eq!(tx_hashes.len(), 1, "Expected a single transaction");
>     tx_hashes.to_vec()
> }
> ```

If there isn't anything else we want to test, we can just have one function for both.



_Suggestion:_
```XML
fn test_single_tx(tx_hashes: &[TransactionHash]) -> Vec<TransactionHash> {
    assert_eq!(tx_hashes.len(), 1, "Expected a single transaction");
    tx_hashes.to_vec()
}
```


<!-- Sent from Reviewable.io -->

2024-12-31 10:34 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2807)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line  at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHWShi6ySXkCAg7J6C:-OFQvAmG0f7-etnOeF7f:b-jfot4f) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/src/state_reader.rs#L)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you explain the changes in this file? Was this one of the bugs you found?
</blockquote></details>

Yes.
If you register multiple contracts with the same class, the class will be declared multiple times, and it will fail.
These changes make classes be declared only once.
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFH_EYvC56TXLhRkcuw:-OFR9Iup6G7nwP7hOONm:b-xw0dau) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L102)):*
> Can you create a function for this and remove the Boxes? You can get the undeployed account with its ID.

Done

> do we need an extra block or can we have the funding and the deployment in the same block?

We need another block, otherwise the GW will reject the deployment tx because there is not enough balance (once we remove the initial balance from the test setup)
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHYQhM4O6QLEgHe8jt:-OFRGxx00yfrbUVsf7DP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L128)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 279 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHZ-dZ-ve3lvu9JDXD:-OFRA70iAxl9Aldl60MC:b-s7mv6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L279)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You should add `Code Spell Checker` extension to vscode.
</blockquote></details>

Fixed (the code moved)
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 293 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHZtmn14OTdTXIKV3F:-OFRGDMq4cdIVJpa6Xlw:b-yhhzm9) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L293)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you instead use the ID to get the account? Why do we need to check that it's the last?
</blockquote></details>

Technically, nothing is coupling the account IDs in the tests to their index in the generator.
This is another thing we need to refactor in the utility.
What happens if someone registers more accounts in the middle?
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 302 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHY3nd4SXtWYHAHCD9:-OFRGA2g68c0nnHRBM1C:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L302)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

If there isn't anything else we want to test, we can just have one function for both.
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 280 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHZEmB1y4_4vgvT6yh:-OFRASno-Tbviihlx2Ac:bb73xfv) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L280)):*
> ```XML
> fn fund_new_account(
>     funding_acount: &mut AccountTransactionGenerator,
>     to: &Contract,
> ```

Same


<!-- Sent from Reviewable.io -->

2025-01-01 15:23 UTC, alonh5 requested changes
> Reviewed 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2807)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 293 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHZtmn14OTdTXIKV3F:-OFX9Lyf2MUg4Y0I7rQM:bqz3hwi) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L293)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Technically, nothing is coupling the account IDs in the tests to their index in the generator.
This is another thing we need to refactor in the utility.
What happens if someone registers more accounts in the middle?
</blockquote></details>

So it will fail here but it won't be clear why. You should assert the the account id is equal to `UNDEPLOYED_ACCOUNT_ID` when registering it, and then use `UNDEPLOYED_ACCOUNT_ID` to get it (as you did in `create_funding_txs` for example).
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 113 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFX8t8N74fQr6yGchUq:-OFX8t8O8kOL4xdui3Kh:b-g2283z) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ec6d5c8e3c5795c10238446237391b0587c799f/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L113)):*
> ```XML
> type ExpectedContentId = Felt;
> 
> fn create_test_scenarios() -> Vec<(CreateRpcTxsFn, TestTxHashesFn, ExpectedContentId)> {
> ```

Add height also instead of ziping them together?
Also document this function.



_Suggestion:_
```XML
create_test_blocks
```


<!-- Sent from Reviewable.io -->

2025-01-02 09:56 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2807)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 293 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFHZtmn14OTdTXIKV3F:-OFaDHfj9OAjwDLxq3Q0:b-owetpw) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbe5e3d653a009761a5f9fd54d33d3e6dccbcaf9/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L293)):*
> You should assert the the account id is equal to `UNDEPLOYED_ACCOUNT_ID` when registering it

Already doing it: https://github.com/starkware-libs/sequencer/blob/93e65241d683e55739d80c20b1f26385ee9bcfdf/crates/starknet_integration_tests/src/utils.rs#L188


> and then use `UNDEPLOYED_ACCOUNT_ID` to get it

Done


<!-- Sent from Reviewable.io -->

2025-01-02 09:56 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2807)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 113 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-OFX8t8N74fQr6yGchUq:-OFaR_l8DpPAdQvM4piz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ec6d5c8e3c5795c10238446237391b0587c799f/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L113)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add height also instead of ziping them together?
Also document this function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-02 10:02 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2807#-:-OFaSjd4CHGFTNRwX1Kl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 12:15 UTC, alonh5 approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2807)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2025-01-07 16:10 UTC, yair-starkware reviewed
> Reviewed 3 of 5 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2807)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-07 16:16 UTC, merged