fix(cairo_native): use current dir in cairo compile.
starkware-libs/sequencer pull request #2815
Opened 2024-12-19 10:05 UTC by noaov1

2024-12-19 10:05 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2815)
<!-- Reviewable:end -->

2024-12-19 13:53 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2815)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/build.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2815#-OEUBFL63AUEP3jdhHVf:-OEUBFL63AUEP3jdhHVg:bggf7lq) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4878345f2444a38c3fe99912eed8000f93d5afc/crates/blockifier/build.rs#L9)):*
> ```XML
> 
>     let cairo_native_dir =
>         current_dir().expect("Failed to get current directory").join(PathBuf::from("cairo_native"));
> ```

this is resolved at runtime, and the resulting dir depends on the calling context; this is desired behavior?



_Code quote:_
```XML
current_dir().expect("Failed to get current directory")
```


<!-- Sent from Reviewable.io -->

2024-12-23 06:57 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2815)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

___
*[`crates/blockifier/build.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2815#-OEUBFL63AUEP3jdhHVf:-OEmGsLJ7q3jd2eY7AbC:b-l9nbzj) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4878345f2444a38c3fe99912eed8000f93d5afc/crates/blockifier/build.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is resolved at runtime, and the resulting dir depends on the calling context; this is desired behavior?
</blockquote></details>

@avi-starkware ?
I just reverted the changes in #2289.
Do you have other ideas? 


<!-- Sent from Reviewable.io -->

2024-12-23 08:56 UTC, avi-starkware commented
*[`crates/blockifier/build.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2815#-OEUBFL63AUEP3jdhHVf:-OEmhVad6V6PjXYiGHX2:b-tcvhc5) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4878345f2444a38c3fe99912eed8000f93d5afc/crates/blockifier/build.rs#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@avi-starkware ?
I just reverted the changes in #2289.
Do you have other ideas?
</blockquote></details>

Why do you want to do this?

The problem with using `current_dir` is that it depends on the dir from which the crate is built. In particular, running
```
cargo build --package "blockifier"
```
and running
```
cd ~
cargo build --manifest-path ~/workspace/sequencer/crates/blockifier/Cargo.toml
```
would give you different results.

Which is weird and unexpected behavior that could easily cause bugs in the future.

Why are you doing this PR?


<!-- Sent from Reviewable.io -->

2024-12-23 10:12 UTC, closed without merging