refactor(ci): separate rustdoc to different job
starkware-libs/sequencer pull request #2824
Opened 2024-12-19 13:09 UTC by giladchase

It compiles in `--release` so cache is irrelevant.

2024-12-19 13:09 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2824)
<!-- Reviewable:end -->

2024-12-22 08:09 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2824)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`.github/workflows/main_nightly.yml` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-OEhPF4a9X0tQQAgIkpk:-OEhPF4a9X0tQQAgIkpl:b10k1l0) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f541a21b34eacf7402b986c8d1f81362e525266/.github/workflows/main_nightly.yml#L66)):*
> ```YAML
> 
>         - name: Build Documentation
>           run: cargo doc --all --no-deps
> ```

the command in run_tests.py is `cargo doc -r --document-private-items --no-deps` (disregarding the `--workspace` vs. `-p crate` list).
why not just remove the `-r` and keep it in run_tests.py`?



_Code quote:_
```YAML
 run: cargo doc --all --no-deps
```
___
*[`.github/workflows/main_nightly.yml` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-OEhOzQx1NeZu-sgsL9V:-OEhOzQx1NeZu-sgsL9W:bopcmku) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f541a21b34eacf7402b986c8d1f81362e525266/.github/workflows/main_nightly.yml#L69)):*
> ```YAML
>           env:
>             # Note that cargo doc requires RUSTDOCFLAGS, not RUSTFLAGS.
>             RUSTDOCFLAGS: "-D warnings -C link-arg=-fuse-ld=lld"
> ```

won't this work?



_Suggestion:_
```YAML
RUSTDOCFLAGS: ${{ env.RUSTFLAGS }}
```


<!-- Sent from Reviewable.io -->

2024-12-22 08:20 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2824)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/main_nightly.yml` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-OEhPF4a9X0tQQAgIkpk:-OEhQwKq0iNmagbkNQbu:bp0o693) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f541a21b34eacf7402b986c8d1f81362e525266/.github/workflows/main_nightly.yml#L66)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the command in run_tests.py is `cargo doc -r --document-private-items --no-deps` (disregarding the `--workspace` vs. `-p crate` list).
why not just remove the `-r` and keep it in run_tests.py`?
</blockquote></details>

Whoops, added.

RE run_tests, you mean remove release so we can keep it in the PR flow?
I'm not sure why release was there in the first place, Ill reopen the PR as draft then and bring it up in the infra sync.

Regardless, I suggest moving it to nightly unless someone is actually looking at them on a regular basis / when reviewing PRs.
I see other ppl only generating them in a "release" workflow, and then I assume fixing all the issues on the spot. 
The only issues that arise are broken links in the docs, which are trivial to fix all at once before release.
___
*[`.github/workflows/main_nightly.yml` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-OEhOzQx1NeZu-sgsL9V:-OEhQtVe4ohLJi4xQGq7:bfkryoh) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f541a21b34eacf7402b986c8d1f81362e525266/.github/workflows/main_nightly.yml#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

won't this work?
</blockquote></details>

Ohh nice.
Done


<!-- Sent from Reviewable.io -->

2024-12-22 09:11 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2824)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`.github/workflows/main_nightly.yml` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-OEhPF4a9X0tQQAgIkpk:-OEhccDv2d-9gFE7xjIt:b-dro4dg) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f541a21b34eacf7402b986c8d1f81362e525266/.github/workflows/main_nightly.yml#L66)):*
> Regardless, I suggest moving it to nightly unless someone is actually looking at them on a regular basis / when reviewing PRs.

I'm saying: if it doesn't slow down the CI (i.e. we get a cache hit on compilation) it's nice to fix doc issues in the PR that introduces them
___
*[`.github/workflows/main_nightly.yml` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-OEhOzQx1NeZu-sgsL9V:-OEhboKWExDqBjWVrWIC:b4hfofi) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f541a21b34eacf7402b986c8d1f81362e525266/.github/workflows/main_nightly.yml#L69)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ohh nice.
Done
</blockquote></details>

I'm actually asking if this works or not :sweat_smile: 


<!-- Sent from Reviewable.io -->

2024-12-24 11:00 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2824)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-OEsJr5X9vyDJfCde_HE:-OEsJr5X9vyDJfCde_HF:bpbja99) (no related file):*
rebase over `main-v0.13.4`


<!-- Sent from Reviewable.io -->

2024-12-29 15:14 UTC, dorimedini-starkware reviewed
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2824)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-12-29 19:30 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2824)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-OEsJr5X9vyDJfCde_HE:-OFItSoeDu9CCci-568m:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rebase over `main-v0.13.4`
</blockquote></details>

Done.
___
*[`.github/workflows/main_nightly.yml` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-OEhPF4a9X0tQQAgIkpk:-OFI2Rhx-Ys6KBJo1zVw:bbyygr0) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f541a21b34eacf7402b986c8d1f81362e525266/.github/workflows/main_nightly.yml#L66)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> Regardless, I suggest moving it to nightly unless someone is actually looking at them on a regular basis / when reviewing PRs.

I'm saying: if it doesn't slow down the CI (i.e. we get a cache hit on compilation) it's nice to fix doc issues in the PR that introduces them
</blockquote></details>

Added in run_tests, file change is reverted.
___
*[`.github/workflows/main_nightly.yml` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-OEhOzQx1NeZu-sgsL9V:-OFI2ZwXD9PEutCBGAjt:b-uyk8y1) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f541a21b34eacf7402b986c8d1f81362e525266/.github/workflows/main_nightly.yml#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I'm actually asking if this works or not :sweat_smile:
</blockquote></details>

Stale, file change reverted.


<!-- Sent from Reviewable.io -->

2024-12-29 20:42 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2824#-:-OFJ8uAh9T0ZZDFdL1-J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-12-30 08:10 UTC, merged