feat(sequencing): cende into consensus
starkware-libs/sequencer pull request #2827
Opened 2024-12-19 13:46 UTC by DvirYo-starkware

2024-12-19 13:47 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2827)
<!-- Reviewable:end -->

2024-12-19 14:19 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2827)* status: 0 of 5 files reviewed, 2 unresolved discussions

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 418 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEUH8c7D6g1qslsyX8P:-OEUH8c7D6g1qslsyX8Q:b-eawq81) ([raw file](https://github.com/starkware-libs/sequencer/blob/58d7815582fb70b4b335e3b21ea24f2f08fd410c/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L418)):*
> ```XML
>             }),
>         })
>     });
> ```

copied from the original `propose_block` test



_Code quote:_
```XML
    let mut batcher = MockBatcherClient::new();
    let proposal_id = Arc::new(OnceLock::new());
    let proposal_id_clone = Arc::clone(&proposal_id);
    batcher.expect_propose_block().returning(move |input: ProposeBlockInput| {
        proposal_id_clone.set(input.proposal_id).unwrap();
        Ok(())
    });
    batcher
        .expect_start_height()
        .withf(|input| input.height == BlockNumber(0))
        .return_once(|_| Ok(()));
    let proposal_id_clone = Arc::clone(&proposal_id);
    batcher.expect_get_proposal_content().times(1).returning(move |input| {
        assert_eq!(input.proposal_id, *proposal_id_clone.get().unwrap());
        Ok(GetProposalContentResponse { content: GetProposalContent::Txs(TX_BATCH.clone()) })
    });
    let proposal_id_clone = Arc::clone(&proposal_id);
    batcher.expect_get_proposal_content().times(1).returning(move |input| {
        assert_eq!(input.proposal_id, *proposal_id_clone.get().unwrap());
        Ok(GetProposalContentResponse {
            content: GetProposalContent::Finished(ProposalCommitment {
                state_diff_commitment: STATE_DIFF_COMMITMENT,
            }),
        })
    });
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEUGuuw1sgKSNijUzEG:-OEUGuuw1sgKSNijUzEH:btw5bw3) ([raw file](https://github.com/starkware-libs/sequencer/blob/177759ec3efda0790ebae27ce2914db086a5717a/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L105)):*
> ```XML
> 
> #[tokio::test]
> async fn build_proposal() {
> ```

Moved in file. In addition, extraction of common code was done.


<!-- Sent from Reviewable.io -->

2024-12-22 13:38 UTC, matan-starkware requested changes
> Reviewed 2 of 5 files at r1, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2827)* status: all files reviewed, 16 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @graphite-app[bot])

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 392 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiYcsr1161D-vAMvdb:-OEiYcsr1161D-vAMvdc:b-fr6d4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L392)):*
> ```XML
> // Setup for test of the `build_proposal` function.
> async fn build_proposal_setup(
>     mock_cende_context: MockCendeContext,
> ```

Put setup functions at the top of the file



_Code quote:_
```XML
// Setup for test of the `build_proposal` function.
async fn build_proposal_setup(
    mock_cende_context: MockCendeContext,
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 434 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiQuI9AsbtHKL0-Mdp:-OEiQuI9AsbtHKL0-Mdq:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L434)):*
> ```XML
> 
> #[tokio::test]
> async fn build_proposal_fail_false_writing_failed() {
> ```





_Suggestion:_
```XML
#[tokio::test]
async fn cende_failure() {
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 434 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiZOE51jLucABxRdEF:-OEiZOE51jLucABxRdEG:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L434)):*
> ```XML
> 
> #[tokio::test]
> async fn build_proposal_fail_false_writing_failed() {
> ```





_Suggestion:_
```XML
async fn cende_unsuccessful() {
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 448 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiR7OA8U3_EUpoWave:-OEiR7OA8U3_EUpoWavf:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L448)):*
> ```XML
> 
> #[tokio::test]
> async fn build_proposal_fail_writing_not_ended() {
> ```





_Suggestion:_
```XML
cende_incomplete
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 462 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiZ78w7sVfPxjbiH7Y:-OEiZ78w7sVfPxjbiH7Z:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L462)):*
> ```XML
>     let (fin_receiver, _network) = build_proposal_setup(mock_cende_context).await;
> 
>     assert_eq!(fin_receiver.await, Err(oneshot::Canceled));
> ```





_Suggestion:_
```XML
    let mut mock_cende_context = MockCendeContext::new();
    let (sender, receiver) = oneshot::channel();
    mock_cende_context.expect_write_prev_height_blob().times(1).returning(|_height| receiver);

    let (fin_receiver, _network) = build_proposal_setup(mock_cende_context).await;
    assert_eq!(fin_receiver.await, Err(oneshot::Canceled));
    drop(sender); // Only drop after assert to make sure the receiver remains open.
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 475 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiY_WBAXHipTjNnF0I:-OEiY_WCAxzHguWJT_EY:b-fr6d4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L475)):*
> ```XML
> 
>     mock_cende
> }
> ```

Put setup functions at the top of the file



_Suggestion:_
```XML
// Returns a mock CendeContext that will return a successful write_prev_height_blob.
fn success_cende_ammbassador() -> MockCendeContext {
    let mut mock_cende = MockCendeContext::new();
    mock_cende.expect_write_prev_height_blob().returning(|_height| {
        let (sender, reciver) = oneshot::channel();
        sender.send(true).unwrap();
        reciver
    });

    mock_cende
}
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiZgLx9a8sN5JlMnWU:-OEiZgLx9a8sN5JlMnWV:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L124)):*
> ```XML
>     // Used to convert Transaction to ExecutableTransaction.
>     chain_id: ChainId,
>     cende_ambassador: Arc<dyn CendeContext>,
> ```





_Suggestion:_
```XML
    cende_client: Arc<dyn CendeClient>,
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 168 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiL9FdBwDNQ5L1Xhvf:-OEiL9FdBwDNQ5L1Xhvg:botcv3r) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L168)):*
> ```XML
>         info!("Building proposal: timeout={timeout:?}");
>         let writing_blob_succeeded =
>             self.cende_ambassador.write_prev_height_blob(proposal_init.height);
> ```

cende_write_succeeded_recv - change the name throughout



_Suggestion:_
```XML
        let cende_write_succeess =
            self.cende_ambassador.write_prev_height(proposal_init.height);
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 337 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiLgP70PM2uvzS3akC:-OEiLgP70PM2uvzS3akD:brk34qv) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L337)):*
> ```XML
>         // TODO(dvir): when passing here the correct `BlobParameters`, also test that
>         // `prepare_blob_for_next_height` is called with the correct parameters.
>         self.cende_ambassador.prepare_blob_for_next_height(BlobParameters::default()).await;
> ```

I don't feel like the word "blob" is useful for the clients of cende.



_Suggestion:_
```XML
        self.cende_ambassador.prepare_for_next_height(BlobParameters::default()).await;
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 549 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiP-1c4WU71SllPDqp:-OEiP-1c4WU71SllPDqq:b98x2r1) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L549)):*
> ```XML
>                 // If the blob writing operation to Aerospike doesn't return a success status, we
>                 // can't finish the proposal.
>                 let Ok(Some(succeeded)) = writing_blob_succeeded.try_recv() else {
> ```

We use try_recv to avoid blocking, which is good. This also means there is an implicit timer on cende. If this fails cende is not actually forced to stop writing to aerospike. What happens if this block write is still ongoing when the node calls again to `ce [...]

2024-12-22 13:38 UTC, matan-starkware commented on crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
> +        let (sender, reciver) = oneshot::channel();
:thumbsup: 
<!-- Reviewable comment -OEiQSKb78MGuJjHPhHU:b4c9lyr -->
<!-- Sent from Reviewable.io -->

2024-12-22 15:09 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2827)* status: 2 of 5 files reviewed, 16 unresolved discussions (waiting on @dan-starkware, @graphite-app[bot], and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 168 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiL9FdBwDNQ5L1Xhvf:-OEigo4s3x0GTFVUgoTc:bj3g87f) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L168)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

cende_write_succeeded_recv - change the name throughout
</blockquote></details>

Changed to `cende_write_succeess`. About the function name, as the previous comment in a different PR.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 337 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiLgP70PM2uvzS3akC:-OEih7Pc6nSgwXVMS8Bh:bgd13ly) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L337)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't feel like the word "blob" is useful for the clients of cende.
</blockquote></details>

As before.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 549 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiP-1c4WU71SllPDqp:-OEihu-I4SRJ0ybM_LgZ:b-5z2sxk) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L549)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We use try_recv to avoid blocking, which is good. This also means there is an implicit timer on cende. If this fails cende is not actually forced to stop writing to aerospike. What happens if this block write is still ongoing when the node calls again to `cende_ambassador.prepare_for_next_height` for the next height?
</blockquote></details>

That's a good point. Nothing will get stuck. The `Recorder` will continue to handle the writing until it finishes. We want that to happen in the rare case where we have a very, very big block for which writing to AS will take a lot of time.
To be sure, will the `try_recv()` return immediately?
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 556 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiOFqg-A5xqBL5OWt6:-OEijD-v7AvEbSLO1Mgt:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L556)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

WDYT of making the error handling 1 block?
</blockquote></details>

Done
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 392 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiYcsr1161D-vAMvdb:-OEijzodC-jE94ljVM1-:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L392)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Put setup functions at the top of the file
</blockquote></details>

Done
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 475 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiY_WBAXHipTjNnF0I:-OEikaXwAWU4gWeOxuNm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L475)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Put setup functions at the top of the file
</blockquote></details>

Done.
___
*[`crates/starknet_consensus_manager/src/consensus_manager.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEi_fiU42lZAIDO1s85:-OEikhru0-HoOXwVQ_8C:bbmebzp) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/starknet_consensus_manager/src/consensus_manager.rs#L89)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Do we expect this to need a config?
</blockquote></details>

Yes. In the next PR.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiZgLx9a8sN5JlMnWU:-OEifoU11BIQWJxyAANA:b-lbhtdr) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L124)):*
> ```XML
>     // Used to convert Transaction to ExecutableTransaction.
>     chain_id: ChainId,
>     cende_ambassador: Arc<dyn CendeContext>,
> ```

I will discuss this with Yael and Dafna and change in a different PR. Note that this is not like the `BatcherClient`. It is a simple struct and not a component with communication abstraction.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 434 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiQuI9AsbtHKL0-Mdp:-OEiosa89wVW8-_5ZJJz:b-yp97pt) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L434)):*
> ```XML
> 
> #[tokio::test]
> async fn build_proposal_fail_false_writing_failed() {
> ```

changed function name suffix
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 448 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiR7OA8U3_EUpoWave:-OEiowT_CGWj-WWbFR9q:b-yp97pt) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L448)):*
> ```XML
> 
> #[tokio::test]
> async fn build_proposal_fail_writing_not_ended() {
> ```

changed function name suffix
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 462 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiZ78w7sVfPxjbiH7Y:-OEikwgBD7_AX3ky2nDL:bahwqs5) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L462)):*
> ```XML
>     let (fin_receiver, _network) = build_proposal_setup(mock_cende_context).await;
> 
>     assert_eq!(fin_receiver.await, Err(oneshot::Canceled));
> ```

Your suggestion looks very good, I tried it, but I am getting an error
`cannot move out of receiver, a captured variable in an FnMut closure`
I am not sure how to solve this. I don't think this is possible.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiZbawB95uz0Pxhp12:-OEikfU83ZUnSkIM1-Vd:b-549cmw) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L22)):*
> ```XML
> #[cfg_attr(test, automock)]
> #[async_trait]
> pub trait CendeContext: Send + Sync [...]

2024-12-22 15:09 UTC, DvirYo-starkware commented on crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
> +        let (sender, reciver) = oneshot::channel();
Done.
<!-- Reviewable comment -OEikH5L85hRafMjcqQL:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-12-22 15:09 UTC, DvirYo-starkware commented on crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs
> +    fn write_prev_height_blob(&self, height: BlockNumber) -> oneshot::Receiver<bool> {
Done.
<!-- Reviewable comment -OEiuXjs6s8DVERaRiQV:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-12-22 18:07 UTC, matan-starkware requested changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2827)* status: all files reviewed, 11 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, @graphite-app[bot], and @Itay-Tsabary-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiZgLx9a8sN5JlMnWU:-OEjV6J518SAvRIlEzRi:b-ouiwyz) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L124)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I will discuss this with Yael and Dafna and change in a different PR. Note that this is not like the `BatcherClient`. It is a simple struct and not a component with communication abstraction.
</blockquote></details>

Ok if there's no distinct cende component within the node then it's not Client. IDK if I have a great name, I just like being able to refer to "the context" and not have sub components that are also named "context"
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 337 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiLgP70PM2uvzS3akC:-OEjW37X3nmSeXj1m97q:b-22aswf) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L337)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

As before.
</blockquote></details>

different pr?
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 549 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiP-1c4WU71SllPDqp:-OEjWZnkDgKYGvHzA8sm:b-dlzfg8) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L549)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

That's a good point. Nothing will get stuck. The `Recorder` will continue to handle the writing until it finishes. We want that to happen in the rare case where we have a very, very big block for which writing to AS will take a lot of time.
To be sure, will the `try_recv()` return immediately?
</blockquote></details>

Yes. AFAIU the entire point of `try_recv` is to return immediately.

This made me realize that you probably are spawning a tokio task. Make sure that you do not just drop it, it needs to be held on to so that we can propagate any panics. Talk to @Itay-Tsabary-Starkware for more details on the matter.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 462 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiZ78w7sVfPxjbiH7Y:-OEjYDYGD8pfQ8eTKtbu:b-bz7byl) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L462)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Your suggestion looks very good, I tried it, but I am getting an error
`cannot move out of receiver, a captured variable in an FnMut closure`
I am not sure how to solve this. I don't think this is possible.
</blockquote></details>

Really, even with `times(1)`? Try switching `returning` to `return_once`


<!-- Sent from Reviewable.io -->

2024-12-22 18:07 UTC, matan-starkware commented on crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
> +            self.cende_ambassador.write_prev_height_blob(proposal_init.height);
The variable `cende_write_succeess` contains a typo and should be renamed to `cende_write_success`
<!-- Reviewable comment -OEjVv56BZTr8kGsvxhp:bvtjlp9 -->
<!-- Sent from Reviewable.io -->

2024-12-22 18:07 UTC, matan-starkware commented on crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
> +                }
:thumbsdown: 
<!-- Reviewable comment -OEjXx-GB-6kquJVOHdR:b-reanra -->
<!-- Sent from Reviewable.io -->

2024-12-23 08:50 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2827)* status: all files reviewed, 9 unresolved discussions (waiting on @dan-starkware, @graphite-app[bot], @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 337 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiLgP70PM2uvzS3akC:-OEmfbT1BAhegpItyhBZ:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L337)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

different pr?
</blockquote></details>

Yes
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 549 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiP-1c4WU71SllPDqp:-OEmgzDpBBMcw0HiuzmE:b-ga7hmr) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L549)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Yes. AFAIU the entire point of `try_recv` is to return immediately.

This made me realize that you probably are spawning a tokio task. Make sure that you do not just drop it, it needs to be held on to so that we can propagate any panics. Talk to @Itay-Tsabary-Starkware for more details on the matter.
</blockquote></details>

I will talk with him.
But note that I don't care if the task will panic; if the write operation doesn't return a success status, another node will try to perform it until someone succeeds.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 462 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiZ78w7sVfPxjbiH7Y:-OEmgqDI8wdhVzN-YrrL:bhmjkb1) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L462)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Really, even with `times(1)`? Try switching `returning` to `return_once`
</blockquote></details>

The `return_once` solves this. Thanks.


<!-- Sent from Reviewable.io -->

2024-12-23 08:50 UTC, DvirYo-starkware commented on crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
> +            self.cende_ambassador.write_prev_height_blob(proposal_init.height);
Done.
<!-- Reviewable comment -OEjFH-P8CfImv7kVYR2:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-12-23 08:50 UTC, DvirYo-starkware commented on crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
> +                }
Not true, the method returns Option<>
<!-- Reviewable comment -OEjFLfi5cQSKG5NQinA:b-cgq7m8 -->
<!-- Sent from Reviewable.io -->

2024-12-23 09:09 UTC, matan-starkware approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2827)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware, @graphite-app[bot], and @Itay-Tsabary-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 549 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2827#-OEiP-1c4WU71SllPDqp:-OEmlTpd953VdYMpQMXB:btd6lnx) ([raw file](https://github.com/starkware-libs/sequencer/blob/73f16cef977468940d32670a8e1cbbd694e67ac4/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L549)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I will talk with him.
But note that I don't care if the task will panic; if the write operation doesn't return a success status, another node will try to perform it until someone succeeds.
</blockquote></details>

If the write operation fails that's fine like you said, I don't see why that would panic. 


<!-- Sent from Reviewable.io -->

2024-12-23 09:58 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2827)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware and @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-12-23 09:58 UTC, DvirYo-starkware commented on crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
> +            self.cende_ambassador.write_prev_height_blob(proposal_init.height);
Done.
<!-- Reviewable comment -OEmv3jK66IimRWUrjGI:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-12-23 09:58 UTC, DvirYo-starkware commented on crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
> +                }
Done.
<!-- Reviewable comment -OEmwoalC0VvemWHqX_h:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-12-23 09:58 UTC, DvirYo-starkware reviewed
> Dismissed @graphite-app[bot] from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2827)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2024-12-23 11:35 UTC, merged