chore(cairo_native): update cairo native version to 0.2.5-rc1
starkware-libs/sequencer pull request #2839
Opened 2024-12-19 16:34 UTC by meship-starkware

2024-12-19 16:34 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2839)
<!-- Reviewable:end -->

2024-12-19 16:43 UTC, meship-starkware reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: 1 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-22 07:53 UTC, meship-starkware reviewed
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: 1 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-22 10:25 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: 1 of 6 files reviewed, 1 unresolved discussion

___
*[`crates/bin/starknet-native-compile/Cargo.lock` line 471 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OEhsaqsBSF3o1OrtmWV:-OEhsaqsBSF3o1OrtmWW:b-7wyk5y) ([raw file](https://github.com/starkware-libs/sequencer/blob/e495b98be162be6f6ab2cae70a79f065f7c94737/crates/bin/starknet-native-compile/Cargo.lock#L471)):*
> ```TOML
> ]
> 
> [[package]]
> ```

This cargo.lock file did not update, so I ran cargo update inside the folder and only accepted the relevant changes. I think it might be risky. 


<!-- Sent from Reviewable.io -->

2024-12-22 11:16 UTC, noaov1 requested changes
> Reviewed 2 of 5 files at r1, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/bin/starknet-native-compile/Cargo.lock` line 471 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OEhsaqsBSF3o1OrtmWV:-OEi4An9EW4NEjWmzcSP:b-qzr70o) ([raw file](https://github.com/starkware-libs/sequencer/blob/e495b98be162be6f6ab2cae70a79f065f7c94737/crates/bin/starknet-native-compile/Cargo.lock#L471)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This cargo.lock file did not update, so I ran cargo update inside the folder and only accepted the relevant changes. I think it might be risky.
</blockquote></details>

Why wasn't it updated? 
___
*[`Cargo.toml` line 106 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OEi4LL_11NRIM1N7NEm:-OEi4LL_11NRIM1N7NEn:bb6qkic) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cc6f64f3e02f999e3d149aaa3e1fa13653bce48/Cargo.toml#L106)):*
> ```TOML
> cairo-lang-utils = "2.9.2"
> # Important: when updated, make sure to update the cairo-native submodule as well.
> cairo-native = "0.2.5-rc1"
> ```

Update the submodule?



_Code quote:_
```TOML
# Important: when updated, make sure to update the cairo-native submodule as well.
cairo-native = "0.2.5-rc1"
```


<!-- Sent from Reviewable.io -->

2024-12-23 12:52 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`Cargo.toml` line 106 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OEi4LL_11NRIM1N7NEm:-OEnZahvE8doLZ9xNnJM:bf03kxq) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cc6f64f3e02f999e3d149aaa3e1fa13653bce48/Cargo.toml#L106)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Update the submodule?
</blockquote></details>

I did update it but it seems like I cant push it for some reason :( 
___
*[`crates/bin/starknet-native-compile/Cargo.lock` line 471 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OEhsaqsBSF3o1OrtmWV:-OEnZCZ0316Gvir1c2O8:b-jbfyq2) ([raw file](https://github.com/starkware-libs/sequencer/blob/e495b98be162be6f6ab2cae70a79f065f7c94737/crates/bin/starknet-native-compile/Cargo.lock#L471)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why wasn't it updated?
</blockquote></details>

I am not sure. I think that it is only updated through cargo update or when you run a code that uses the cargo.toml packages. I only run the tests, so this might be the issue. 


<!-- Sent from Reviewable.io -->

2024-12-29 10:14 UTC, noaov1 reviewed
> Reviewed 1 of 3 files at r2, 1 of 3 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/bin/starknet-native-compile/Cargo.lock` line 471 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OEhsaqsBSF3o1OrtmWV:-OFGuCLwEeKQdPUTnk8c:b67esol) ([raw file](https://github.com/starkware-libs/sequencer/blob/e495b98be162be6f6ab2cae70a79f065f7c94737/crates/bin/starknet-native-compile/Cargo.lock#L471)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure. I think that it is only updated through cargo update or when you run a code that uses the cargo.toml packages. I only run the tests, so this might be the issue.
</blockquote></details>

Try building the crate/cargo update?
___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFGra4p5-5kn0LbGejq:-OFGra4p5-5kn0LbGejr:b-p2qd13):*
Please add to the commit message the update of the compiler version.



_Code quote:_
```
- e0d1baf: chore(cairo_native): update cairo native version to 0.2.5-rc2
```


<!-- Sent from Reviewable.io -->

2024-12-29 11:43 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-12-30 13:50 UTC, noaov1 reviewed
> Reviewed 14 of 18 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/bin/starknet-native-compile/Cargo.toml` line 4 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFMoI4xCi1PeVyP9Xy9:-OFMoI4xCi1PeVyP9XyA:bz5qgiq) ([raw file](https://github.com/starkware-libs/sequencer/blob/46c9c8d116bc46e128b96049d21a801fb7b55067/crates/bin/starknet-native-compile/Cargo.toml#L4)):*
> ```TOML
> name = "starknet-native-compile"
> # The version of this crate should equal the version of cairo-native.
> version = "0.2.5"
> ```

Does having `-rc2` create problems?



_Code quote:_
```TOML
version = "0.2.5"
```
___
*[`crates/blockifier/feature_contracts/cairo1/sierra/cairo_steps_test_contract.sierra.json` line 4 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFMoaN54ELhZcRwovkH:-OFMoaN54ELhZcRwovkI:bngdp0l) ([raw file](https://github.com/starkware-libs/sequencer/blob/46c9c8d116bc46e128b96049d21a801fb7b55067/crates/blockifier/feature_contracts/cairo1/sierra/cairo_steps_test_contract.sierra.json#L4)):*
> ```JSON
>   "sierra_program": [
>     "0x1",
>     "0x6",
> ```

Why was it changed? Isn't the compiler version for this contract fixed?



_Code quote:_
```JSON
    "0x6",
```


<!-- Sent from Reviewable.io -->

2024-12-31 14:06 UTC, meship-starkware reviewed
> Reviewed 13 of 18 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: 20 of 21 files reviewed, 3 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2025-01-01 13:28 UTC, noaov1 requested changes
> Reviewed 14 of 17 files at r11, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: 34 of 39 files reviewed, 4 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 61 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFX127K3dQLCQrcSv3Y:-OFX127L5emSivSKYGF6:bhofei7) ([raw file](https://github.com/starkware-libs/sequencer/blob/afb11f57f3886bbdd1fde9902d0d464b7e4bb42a/crates/blockifier/src/execution/execution_utils.rs#L61)):*
> ```XML
> ) -> EntryPointExecutionResult<CallInfo> {
>     let current_tracked_resource = compiled_class.get_current_tracked_resource(context);
>     println!("current_tracked_resource: {:?}", current_tracked_resource);
> ```

Delete?



_Code quote:_
```XML
    println!("current_tracked_resource: {:?}", current_tracked_resource);
```


<!-- Sent from Reviewable.io -->

2025-01-01 14:26 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: 34 of 39 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/bin/starknet-native-compile/Cargo.lock` line 471 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OEhsaqsBSF3o1OrtmWV:-OFWx4QAAbz2B-BAPgnr:bn2dk0l) ([raw file](https://github.com/starkware-libs/sequencer/blob/e495b98be162be6f6ab2cae70a79f065f7c94737/crates/bin/starknet-native-compile/Cargo.lock#L471)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Try building the crate/cargo update?
</blockquote></details>

You need to do cargo update inside the starknet-native-compile crate
___
*[`crates/blockifier/feature_contracts/cairo1/sierra/cairo_steps_test_contract.sierra.json` line 4 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFMoaN54ELhZcRwovkH:-OFWvQhh-PwJ9Z_TPTYF:b-spkvt) ([raw file](https://github.com/starkware-libs/sequencer/blob/46c9c8d116bc46e128b96049d21a801fb7b55067/crates/blockifier/feature_contracts/cairo1/sierra/cairo_steps_test_contract.sierra.json#L4)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why was it changed? Isn't the compiler version for this contract fixed?
</blockquote></details>

From what Tzahi told me, it was 0x6, but AvivY changed it manually to 0x5 so the test would pass
  


<!-- Sent from Reviewable.io -->

2025-01-01 17:14 UTC, meship-starkware reviewed
> Reviewed 1 of 5 files at r9, 1 of 4 files at r24.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: 30 of 39 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 61 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFX127K3dQLCQrcSv3Y:-OFXr1V8A3GH3AU83Rqx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/afb11f57f3886bbdd1fde9902d0d464b7e4bb42a/crates/blockifier/src/execution/execution_utils.rs#L61)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Delete?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-02 12:22 UTC, noaov1 approved these changes
> Reviewed 1 of 4 files at r19, 2 of 7 files at r21, 1 of 1 files at r23, 4 of 4 files at r24, 2 of 2 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 102 at r27](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFaJXtv5xPo_PZHHVok:-OFaJXtv5xPo_PZHHVol:beeg9xd) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8317ba6197810c667e791472250fe1e24a77e9/.github/workflows/upload_artifacts_workflow.yml#L102)):*
> ```YAML
> 
>       # Build artifact.
>       - uses: ./.github/actions/bootstrap
> ```

We don't need it anymore?
@dorimedini-starkware 



_Code quote:_
```YAML
      - uses: ./.github/actions/bootstrap
```


<!-- Sent from Reviewable.io -->

2025-01-02 12:39 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 102 at r27](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFaJXtv5xPo_PZHHVok:-OFb0W084UUsf583nrtd:b-nidfki) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8317ba6197810c667e791472250fe1e24a77e9/.github/workflows/upload_artifacts_workflow.yml#L102)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We don't need it anymore?
@dorimedini-starkware
</blockquote></details>

I think it's contained in `build_native_in_docker`... read the contents of the bootstrap action (and the setup_native_deps action it uses) and make sure the sequencer dockerfile does the same?


<!-- Sent from Reviewable.io -->

2025-01-05 05:24 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 102 at r27](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFaJXtv5xPo_PZHHVok:-OFm3VAwC3bkAZfcgpT9:bz3c4c) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8317ba6197810c667e791472250fe1e24a77e9/.github/workflows/upload_artifacts_workflow.yml#L102)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it's contained in `build_native_in_docker`... read the contents of the bootstrap action (and the setup_native_deps action it uses) and make sure the sequencer dockerfile does the same?
</blockquote></details>

From a short glimpse it seems that it is not the same (but maybe I'm missing something). 
The bootstrap script contains 3 actions:
1. Update the git submodule. Done in the `build_native_blockifier.sh`, so all good.
2. Install rust. I did not see any mentioned for that in `build_native_in_docker.sh` or `build_native_blockifier.sh`
3. Install cairo native. Same.

But, I may be missing something and thought you might know. 


<!-- Sent from Reviewable.io -->

2025-01-05 08:37 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 102 at r27](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFaJXtv5xPo_PZHHVok:-OFpapZO57gBFajDMgTg:bg4fkzl) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8317ba6197810c667e791472250fe1e24a77e9/.github/workflows/upload_artifacts_workflow.yml#L102)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

From a short glimpse it seems that it is not the same (but maybe I'm missing something). 
The bootstrap script contains 3 actions:
1. Update the git submodule. Done in the `build_native_blockifier.sh`, so all good.
2. Install rust. I did not see any mentioned for that in `build_native_in_docker.sh` or `build_native_blockifier.sh`
3. Install cairo native. Same.

But, I may be missing something and thought you might know.
</blockquote></details>

1. build_native_in_docker uses hte sequencer-ci docker
2. which calls install_build_tools
3. which has an install_rust function, that does
```
curl https://sh.rustup.rs -sSf | sh -s -- -y
```


<!-- Sent from Reviewable.io -->

2025-01-06 08:05 UTC, noaov1 reviewed
> Reviewed 1 of 18 files at r33, 2 of 4 files at r36, 2 of 13 files at r37, 1 of 11 files at r38, 1 of 11 files at r44.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: 23 of 40 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-06 08:11 UTC, noaov1 approved these changes
> Reviewed 1 of 13 files at r37, 3 of 4 files at r42, 3 of 4 files at r43, 10 of 11 files at r44, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_class_hash_at.rs` line 44 at r44](https://reviewable.io/reviews/starkware-libs/sequencer/2839#-OFudtdhB02hCxl0TVxM:-OFudtdiAjH-p5ZRwYip:b-ekk5iy) ([raw file](https://github.com/starkware-libs/sequencer/blob/670245052e39583e454639260f8e8bbd63999436/crates/blockifier/src/execution/syscalls/syscall_tests/get_class_hash_at.rs#L44)):*
> ```XML
>         CallExecution {
>             retdata: retdata!(),
>             gas_consumed: REQUIRED_GAS_GET_CLASS_HASH_AT_TEST + redeposit_gas,
> ```

You can simply change the `REQUIRED_GAS_GET_CLASS_HASH_AT_TEST`, no?  And set the `redeposit_gas` in the out of gas test to 600.



_Code quote:_
```XML
            gas_consumed: REQUIRED_GAS_GET_CLASS_HASH_AT_TEST + redeposit_gas,
```


<!-- Sent from Reviewable.io -->

2025-01-06 08:20 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r45, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2839)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-06 08:51 UTC, merged