chore(papyrus_base_layer): add eth base layer config to node infra
starkware-libs/sequencer pull request #2850
Opened 2024-12-20 17:40 UTC by giladchase

Required change in infra in order to support required params.
Changes made by Itay and merged into this commit

2024-12-20 17:41 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2850)
<!-- Reviewable:end -->

2024-12-22 07:28 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2850)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @elintul and @matan-starkware)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 140 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2850#-OEhFeiqA4lo8DrYnr3E:-OEhFeiqA4lo8DrYnr3F:b-nrwqak) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L140)):*
> ```XML
>             "0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4".parse().unwrap();
> 
>         Self {
> ```

There seems to be an infra issue here, when keeping it ser_required_param, adding it to the sequencer node settings breaks the infra `test_required_params_setting`, but when switching to ser_param this passes infra checks but requires changing papyrus configs which rely on it being required.

Will ask someone in papyrus team about it



_Code quote:_
```XML
            ser_required_param(
                "node_url",
                SerializationType::String,
                "Ethereum node URL. A schema to match to Infura node: https://mainnet.infura.io/v3/<your_api_key>, but any other node can be used.",
                ParamPrivacyInput::Private,
            ),
```


<!-- Sent from Reviewable.io -->

2024-12-22 09:06 UTC, elintul requested changes
> Reviewed 2 of 9 files at r2, 1 of 1 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2850)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @matan-starkware)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 90 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2850#-OEhbQKWEMLfpMTgXAB4:-OEhbQKWEMLfpMTgXAB5:b-y4l5s9) ([raw file](https://github.com/starkware-libs/sequencer/blob/f887cbb821fbdc54db9fab39255194a82ca8e956/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L90)):*
> ```XML
>         events: &[&str],
>     ) -> EthereumBaseLayerResult<Vec<L1Event>> {
>         let filter = EthEventFilter::new()
> ```

This change appeared in an earlier PR.
Same for whole `eth_events.rs` file.


<!-- Sent from Reviewable.io -->

2024-12-25 09:14 UTC, matan-starkware approved these changes
> Reviewed 2 of 6 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2850)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, and @graphite-app[bot])

___
*[`-- commits` line 5 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2850#-OEx3uDN6a06tt9Hy7YG:-OEx3uDN6a06tt9Hy7YH:beouubq):*
Can you please talk to yoav (who did a lot of the config work) and someone from the infra team about this?



_Code quote:_
```
- 83be466: chore(papyrus_base_layer): add eth base layer config to node infra

  `ser_required_param` seems to be unsupported by the current infra tests
  and unused elsewhere, using regular `ser_param` instead.
```
___
*[`config/sequencer/default_config.json` line 3 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2850#-OEx4CQg1EUa75obB5Oe:-OEx4CQg1EUa75obB5Of:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/83be466a0d9a2629895738ce659263a640bea568/config/sequencer/default_config.json#L3)):*
> ```JSON
> {
>   "base_layer_config.node_url": {
>     "description": "A required param! Ethereum node URL. A schema to match to Infura node: https://mainnet.infura.io/v3/<your_api_key>, but any other node can be used.",
> ```





_Suggestion:_
```JSON
    "description": "A required param! Ethereum node URL. Example: https://mainnet.infura.io/v3/<your_api_key>
```


<!-- Sent from Reviewable.io -->

2024-12-25 12:32 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2850)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @elintul, @graphite-app[bot], and @matan-starkware)

___
*[`-- commits` line 5 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2850#-OEx3uDN6a06tt9Hy7YG:-OExmT0WDW4V62beGVea:bt7rq9q):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can you please talk to yoav (who did a lot of the config work) and someone from the infra team about this?
</blockquote></details>

Stale.
Spoke with Tsabary previously, he has a fix up [here](https://github.com/starkware-libs/sequencer/pull/2936).
Will merge it into this one as a separate commit once the stack reaches this spot.
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 90 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2850#-OEhbQKWEMLfpMTgXAB4:-OExnLns9O-oEKfoYBSq:b9x2p3v) ([raw file](https://github.com/starkware-libs/sequencer/blob/f887cbb821fbdc54db9fab39255194a82ca8e956/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L90)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This change appeared in an earlier PR.
Same for whole `eth_events.rs` file.
</blockquote></details>

Rebased
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 140 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2850#-OEhFeiqA4lo8DrYnr3E:-OExnMmL5oLFK4GvsjpY:b5b8oop) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L140)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

There seems to be an infra issue here, when keeping it ser_required_param, adding it to the sequencer node settings breaks the infra `test_required_params_setting`, but when switching to ser_param this passes infra checks but requires changing papyrus configs which rely on it being required.

Will ask someone in papyrus team about it
</blockquote></details>

Resolved here: https://github.com/starkware-libs/sequencer/pull/2936, will merge it soon into this pr
___
*[`config/sequencer/default_config.json` line 3 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2850#-OEx4CQg1EUa75obB5Oe:-OExnFie7l7nAFVbkRmp:bbueg92) ([raw file](https://github.com/starkware-libs/sequencer/blob/83be466a0d9a2629895738ce659263a640bea568/config/sequencer/default_config.json#L3)):*
> ```JSON
> {
>   "base_layer_config.node_url": {
>     "description": "A required param! Ethereum node URL. A schema to match to Infura node: https://mainnet.infura.io/v3/<your_api_key>, but any other node can be used.",
> ```

This will require changing also the values in papyrus node, which also uses this config, that OK?


<!-- Sent from Reviewable.io -->

2024-12-26 07:46 UTC, elintul approved these changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2850)* status: all files reviewed, 3 unresolved discussions (waiting on @graphite-app[bot] and @matan-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 08:19 UTC, giladchase commented
Closed in favor of https://github.com/starkware-libs/sequencer/pull/3063

2025-01-02 08:20 UTC, closed without merging