Gilad/add scraper
starkware-libs/sequencer pull request #2853
Opened 2024-12-20 20:45 UTC by giladchase

2024-12-20 20:45 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2853)
<!-- Reviewable:end -->

2024-12-22 09:09 UTC, elintul approved these changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2853)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @matan-starkware)

___
*[`crates/starknet_l1_provider/src/l1_scraper.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-OEhc4RSB48fnTzRAss1:-OEhc4RSB48fnTzRAss2:b9in4x1) ([raw file](https://github.com/starkware-libs/sequencer/blob/573a0b33da4a9d8989fe1c55f9ece7d4491f9583/crates/starknet_l1_provider/src/l1_scraper.rs#L55)):*
> ```XML
>             self.fetch_events().await?;
>         }
>     }
> ```

Is this the canonical `run` implementation in our node?



_Code quote:_
```XML
    async fn _run(&mut self) -> L1ScraperResult<(), B> {
        loop {
            sleep(self.config.polling_interval).await;
            // TODO: retry.
            self.fetch_events().await?;
        }
    }
```
___
*[`crates/starknet_l1_provider/src/l1_scraper.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-OEhcDT_4xbalTif3H2S:-OEhcDT_4xbalTif3H2T:b-xscx36) ([raw file](https://github.com/starkware-libs/sequencer/blob/573a0b33da4a9d8989fe1c55f9ece7d4491f9583/crates/starknet_l1_provider/src/l1_scraper.rs#L60)):*
> ```XML
> #[derive(Clone, Debug, Serialize, Deserialize, Validate, PartialEq)]
> pub struct L1ScraperConfig {
>     // TODO: make this config into trait.
> ```

WDYM? Why?



_Code quote:_
```XML
// TODO: make this config into trait.
```


<!-- Sent from Reviewable.io -->

2024-12-24 13:56 UTC, elintul approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2853)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-12-25 09:22 UTC, matan-starkware requested changes
> Reviewed 4 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2853)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-OEx5QCtEwBe7Sc2Olg3:-OEx5QCuBCXmOSEM9EkD:b-qt5jky):*
We don't want these to be configurable?



_Code quote:_
```
  - base layer constant file will hold the identifiers of Starknet Events.
```
___
*[`crates/starknet_l1_provider/src/l1_scraper_tests.rs` line 0 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-OEx6cY62aaBu1YWirWA:-OEx6cY62aaBu1YWirWB:b-bbitnr) ([raw file](https://github.com/starkware-libs/sequencer/blob/75d3714f0abb233492eba550731ead69e3520611/crates/starknet_l1_provider/src/l1_scraper_tests.rs#L0)):*
Why add an empty file?


<!-- Sent from Reviewable.io -->

2024-12-25 12:45 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2853)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @elintul and @matan-starkware)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-OEx5QCtEwBe7Sc2Olg3:-OExnzwyBkRyGdYxL1KU:b-65no3e):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We don't want these to be configurable?
</blockquote></details>

I might be misunderstanding you, but AFAIK event identifiers (in Ethereum) are fixed, they are always:
`keccak(<signature_of_event>)`.
The identifier will only change if the signature changes, and this updates the const during compilation time (since the consts are generated from `sol!`).
___
*[`crates/starknet_l1_provider/src/l1_scraper.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-OEhc4RSB48fnTzRAss1:-OExoir-5c-NcnxqZfXl:bwg1z6f) ([raw file](https://github.com/starkware-libs/sequencer/blob/573a0b33da4a9d8989fe1c55f9ece7d4491f9583/crates/starknet_l1_provider/src/l1_scraper.rs#L55)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the canonical `run` implementation in our node?
</blockquote></details>

I haven't found any similar `run` use-case in our code. We currently only have loop-and-select! style `run`s, without any `loop-do-sleep-awake` loops.

With that said, this is a very basic implementation, I'll extend it soon once the pressure's off, unless you have stuff in mind now?
___
*[`crates/starknet_l1_provider/src/l1_scraper.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-OEhcDT_4xbalTif3H2S:-OExq77J8aGqqGdBNbxK:baf2plc) ([raw file](https://github.com/starkware-libs/sequencer/blob/573a0b33da4a9d8989fe1c55f9ece7d4491f9583/crates/starknet_l1_provider/src/l1_scraper.rs#L60)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM? Why?
</blockquote></details>

Seems to be refactoring leftovers, doesn't make sense here, removed.


<!-- Sent from Reviewable.io -->

2024-12-26 07:55 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-:-OF0xiVG0Ycis-gy5peG:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @matan-starkware)

___
*[`crates/starknet_l1_provider/src/l1_scraper.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-OEhc4RSB48fnTzRAss1:-OF0xdlQAHB0b7GjVaqe:b-tnj3p8) ([raw file](https://github.com/starkware-libs/sequencer/blob/573a0b33da4a9d8989fe1c55f9ece7d4491f9583/crates/starknet_l1_provider/src/l1_scraper.rs#L55)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I haven't found any similar `run` use-case in our code. We currently only have loop-and-select! style `run`s, without any `loop-do-sleep-awake` loops.

With that said, this is a very basic implementation, I'll extend it soon once the pressure's off, unless you have stuff in mind now?
</blockquote></details>

Nope, sounds good.


<!-- Sent from Reviewable.io -->

2024-12-26 07:56 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2853)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-12-26 07:56 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2853)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 08:19 UTC, giladchase commented
Closed in favor of #3063

2025-01-02 09:01 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2853)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 18:32 UTC, matan-starkware approved these changes
> Reviewed 1 of 7 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-OEx5QCtEwBe7Sc2Olg3:-OFcGtBE8QP5523r-qDJ:b-siqkbx):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I might be misunderstanding you, but AFAIK event identifiers (in Ethereum) are fixed, they are always:
`keccak(<signature_of_event>)`.
The identifier will only change if the signature changes, and this updates the const during compilation time (since the consts are generated from `sol!`).
</blockquote></details>

I understand a given event has a fixed identifier, I was wondering if the set of identifiers we want to track may change over time or with tests.

Ok thanks for explaining about them being generated by `sol!`. I see in your later PR `pub const LOG_MESSAGE_TO_L2_EVENT_IDENTIFIER: &str = Starknet::LogMessageToL2::SIGNATURE;` So my idea was infeasible


<!-- Sent from Reviewable.io -->

2025-01-06 08:47 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2853)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @elintul and @matan-starkware)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2853#-OEx5QCtEwBe7Sc2Olg3:-OFumOP47E9oixgotwSI:bxcmqy8):*
>I understand a given event has a fixed identifier, I was wondering if the set of identifiers we want to track may change over time or with tests.

For sure, that is covered by the `tracked_event_identifiers` field which is passed to the provider in its constructor.


<!-- Sent from Reviewable.io -->

2025-01-06 08:54 UTC, merged