chore(blockifier): remove syscall_gas_costs from os_constans
starkware-libs/sequencer pull request #2864
Opened 2024-12-22 11:59 UTC by Yonatan-Starkware

2024-12-22 11:59 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2864)
<!-- Reviewable:end -->

2024-12-23 13:02 UTC, meship-starkware requested changes
> Dismissed @graphite-app[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yonatan-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OEnb5rr9PWdPa3zsA09:-OEnb5rr9PWdPa3zsA0A:b7q030u) ([raw file](https://github.com/starkware-libs/sequencer/blob/74046d71c7e150dad4fe84e0ab1436db643e6bb3/crates/blockifier/src/execution/entry_point.rs#L160)):*
> ```XML
>         ));
> 
>         println!("remaining_gas: {}", remaining_gas);
> ```

remove before merge



_Code quote:_
```XML
  println!("remaining_gas: {}", remaining_gas);
```


<!-- Sent from Reviewable.io -->

2024-12-23 13:05 UTC, meship-starkware requested changes
> Reviewed 9 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yonatan-Starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OEnb9oi-W7M6ORxplnb:-OEnb9oi-W7M6ORxplnc:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/74046d71c7e150dad4fe84e0ab1436db643e6bb3/crates/blockifier/src/execution/execution_utils.rs#L88)):*
> ```XML
>             }
>             update_remaining_gas(remaining_gas, &call_info);
>             println!("here with remaining gas: {}", remaining_gas);
> ```

same



_Code quote:_
```XML
     println!("here with remaining gas: {}", remaining_gas);
```
___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 217 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OEnbJCeDPb3f9Qv64-7:-OEnbJCeDPb3f9Qv64-8:b-ds3w77) ([raw file](https://github.com/starkware-libs/sequencer/blob/74046d71c7e150dad4fe84e0ab1436db643e6bb3/crates/blockifier/resources/versioned_constants_0_13_4.json#L217)):*
> ```JSON
>                 "builtin_instance_counter": {},
>                 "n_memory_holes": 0
>             },
> ```

add this with 0 to all old versioned constans



_Code quote:_
```JSON
            "Keccak": {
                "n_steps": 100,
                "builtin_instance_counter": {},
                "n_memory_holes": 0
            },
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OEnb_X5AdPvMcCuCnsm:-OEnb_X5AdPvMcCuCnsn:b-9re4mb) ([raw file](https://github.com/starkware-libs/sequencer/blob/74046d71c7e150dad4fe84e0ab1436db643e6bb3/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L37)):*
> ```XML
>             // 'Out of gas'
>             retdata: retdata![felt!["0x4f7574206f6620676173"]],
>             gas_consumed: REQUIRED_GAS_STORAGE_READ_WRITE_TEST ,
> ```

Why? I am just curious as to why it works without the 70 now 



_Code quote:_
```XML
  gas_consumed: REQUIRED_GAS_STORAGE_READ_WRITE_TEST
```


<!-- Sent from Reviewable.io -->

2024-12-23 13:07 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yonatan-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OEnc9U79EKDmZNg_aZA:-OEnc9U79EKDmZNg_aZB:b-xfbzdj) ([raw file](https://github.com/starkware-libs/sequencer/blob/74046d71c7e150dad4fe84e0ab1436db643e6bb3/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L37)):*
> ```XML
>             // 'Out of gas'
>             retdata: retdata![felt!["0x4f7574206f6620676173"]],
>             gas_consumed: REQUIRED_GAS_STORAGE_READ_WRITE_TEST ,
> ```

please revert when you understand what makes the test fall



_Code quote:_
```XML
        gas_consumed: REQUIRED_GAS_STORAGE_READ_WRITE_TEST
```


<!-- Sent from Reviewable.io -->

2024-12-25 15:30 UTC, noaov1 requested changes
> Reviewed 9 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 5 unresolved discussions (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OEyQl3A3089H7_MtJ7p:-OEyQl3A3089H7_MtJ7q:b-n6d6dn) ([raw file](https://github.com/starkware-libs/sequencer/blob/74046d71c7e150dad4fe84e0ab1436db643e6bb3/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L111)):*
> ```XML
>             b"GetTxSignature" => Ok(Self::GetTxSignature),
>             b"Keccak" => Ok(Self::Keccak),
>             b"KeccakRound" => Ok(Self::KeccakRound),
> ```

Please remove



_Code quote:_
```XML
b"KeccakRound" => Ok(Self::KeccakRound),
```


<!-- Sent from Reviewable.io -->

2024-12-26 07:14 UTC, Yonatan-Starkware commented
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 217 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OEnbJCeDPb3f9Qv64-7:-OF0oIBl7hSwM0p0ZAxq:b-hzyri) ([raw file](https://github.com/starkware-libs/sequencer/blob/74046d71c7e150dad4fe84e0ab1436db643e6bb3/crates/blockifier/resources/versioned_constants_0_13_4.json#L217)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

add this with 0 to all old versioned constans
</blockquote></details>

0 n_steps? 


<!-- Sent from Reviewable.io -->

2024-12-26 12:25 UTC, Yonatan-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: 0 of 20 files reviewed, 5 unresolved discussions (waiting on @graphite-app[bot], @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OEyQl3A3089H7_MtJ7p:-OF1rmaG2Pcf7BrQJ0oR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74046d71c7e150dad4fe84e0ab1436db643e6bb3/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L111)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 10:00 UTC, noaov1 requested changes
> Reviewed 8 of 14 files at r5, 10 of 14 files at r6, 1 of 4 files at r7, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 9 unresolved discussions (waiting on @meship-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_0.json` line 314 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGhAl40XmuOUoUoNtT:-OFGhAl40XmuOUoUoNtU:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e7d6e42771120a819ceba7851a7afad94bacf3f/crates/blockifier/resources/versioned_constants_0_13_0.json#L314)):*
> ```JSON
>                 "builtin_instance_counter": {},
>                 "n_memory_holes": 0,
>                 "n_steps": 100
> ```





_Suggestion:_
```JSON
                "n_steps": 0
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 31 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGqTwK9dWweuskJJKF:-OFGqTwK9dWweuskJJKG:b-ab90f3) ([raw file](https://github.com/starkware-libs/sequencer/blob/71b8b0b10e88409c1b3ede5fc5a4d6b8e38edcce/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L31)):*
> ```XML
>         entry_point_selector: selector_from_name("test_get_block_hash"),
>         calldata,
>         initial_gas: 5220 - 1,
> ```

Please define a constant `REQUIRED_GAS_GET_BLOCK_HASH`)



_Code quote:_
```XML
5220
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 35 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGqqTZ9vkFc6kYCmOg:-OFGqqTZ9vkFc6kYCmOh:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/71b8b0b10e88409c1b3ede5fc5a4d6b8e38edcce/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L35)):*
> ```XML
>     };
> 
>     let difference = constants::GET_BLOCK_HASH_GAS_COST - constants::SYSCALL_BASE_GAS_COST;
> ```





_Suggestion:_
```XML
    let syscall_required_gas = constants::GET_BLOCK_HASH_GAS_COST - constants::SYSCALL_BASE_GAS_COST;
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 37 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGqjtR-rxMevN1KiNH:-OFGqjtR-rxMevN1KiNI:b1jthdt) ([raw file](https://github.com/starkware-libs/sequencer/blob/71b8b0b10e88409c1b3ede5fc5a4d6b8e38edcce/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L37)):*
> ```XML
>     let difference = constants::GET_BLOCK_HASH_GAS_COST - constants::SYSCALL_BASE_GAS_COST;
>     assert_eq!(
>         entry_point_call.clone().execute_directly(&mut state).unwrap().execution,
> ```

Please define a variable. 



_Code quote:_
```XML
entry_point_call.clone().execute_directly(&mut state).unwrap()
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/constants.rs` line 6 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGqO1W4MTAwVr_YTdu:-OFGqO1X4L8DeTf-qYVf:btj1eoo) ([raw file](https://github.com/starkware-libs/sequencer/blob/71b8b0b10e88409c1b3ede5fc5a4d6b8e38edcce/crates/blockifier/src/execution/syscalls/syscall_tests/constants.rs#L6)):*
> ```XML
> pub const REQUIRED_GAS_LIBRARY_CALL_TEST: u64 = 108430;
> pub const GET_BLOCK_HASH_GAS_COST: u64 = 10540;
> pub const SYSCALL_BASE_GAS_COST: u64 = 10000;
> ```

Is it needed? Can you extract it from the versioned constant?



_Code quote:_
```XML
pub const GET_BLOCK_HASH_GAS_COST: u64 = 10540;
pub const SYSCALL_BASE_GAS_COST: u64 = 10000;
```


<!-- Sent from Reviewable.io -->

2024-12-29 11:31 UTC, Yonatan-Starkware commented
*[`crates/blockifier/src/execution/syscalls/syscall_tests/constants.rs` line 6 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGqO1W4MTAwVr_YTdu:-OFHAPQSCxWU6uih8wiQ:b5nsy7g) ([raw file](https://github.com/starkware-libs/sequencer/blob/71b8b0b10e88409c1b3ede5fc5a4d6b8e38edcce/crates/blockifier/src/execution/syscalls/syscall_tests/constants.rs#L6)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it needed? Can you extract it from the versioned constant?
</blockquote></details>

I can, but it requires to create an object of struct versioned_constants. Felt a little weird to do so just to have the constants.  


<!-- Sent from Reviewable.io -->

2024-12-29 11:34 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 9 unresolved discussions (waiting on @meship-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/constants.rs` line 6 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGqO1W4MTAwVr_YTdu:-OFHBB0O2fhQsh4WFzmc:b-6hawr8) ([raw file](https://github.com/starkware-libs/sequencer/blob/71b8b0b10e88409c1b3ede5fc5a4d6b8e38edcce/crates/blockifier/src/execution/syscalls/syscall_tests/constants.rs#L6)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

I can, but it requires to create an object of struct versioned_constants. Felt a little weird to do so just to have the constants.
</blockquote></details>

I think it's better (to avoid code duplication). You can use `create_for_testing`. 


<!-- Sent from Reviewable.io -->

2024-12-29 11:35 UTC, meship-starkware reviewed
> Reviewed 8 of 14 files at r5, 9 of 14 files at r6, 1 of 4 files at r7, 4 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 5 unresolved discussions (waiting on @Yonatan-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-29 11:35 UTC, Yonatan-Starkware commented
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 31 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGqTwK9dWweuskJJKF:-OFHBjHTEOpxC7ogFWTN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/71b8b0b10e88409c1b3ede5fc5a4d6b8e38edcce/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L31)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please define a constant `REQUIRED_GAS_GET_BLOCK_HASH`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 11:35 UTC, Yonatan-Starkware commented
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 35 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGqqTZ9vkFc6kYCmOg:-OFHBqrb-K44ASfaGbwM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/71b8b0b10e88409c1b3ede5fc5a4d6b8e38edcce/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L35)):*
> ```XML
>     };
> 
>     let difference = constants::GET_BLOCK_HASH_GAS_COST - constants::SYSCALL_BASE_GAS_COST;
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 11:36 UTC, meship-starkware reviewed
> Reviewed 1 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yonatan-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-29 11:37 UTC, meship-starkware approved these changes

2024-12-29 11:37 UTC, Yonatan-Starkware commented
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 37 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGqjtR-rxMevN1KiNH:-OFHCFMjCoBXNg7000b6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/71b8b0b10e88409c1b3ede5fc5a4d6b8e38edcce/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L37)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please define a variable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 11:47 UTC, meship-starkware approved these changes
> Reviewed 1 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yonatan-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-29 11:50 UTC, Yonatan-Starkware commented
*[`crates/blockifier/src/execution/syscalls/syscall_tests/constants.rs` line 6 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGqO1W4MTAwVr_YTdu:-OFHF2n-67iEWF63lLwB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/71b8b0b10e88409c1b3ede5fc5a4d6b8e38edcce/crates/blockifier/src/execution/syscalls/syscall_tests/constants.rs#L6)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it's better (to avoid code duplication). You can use `create_for_testing`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 11:50 UTC, Yonatan-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/resources/versioned_constants_0_13_0.json` line 314 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFGhAl40XmuOUoUoNtT:-OFHAKzm4gaA9u0l60W1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e7d6e42771120a819ceba7851a7afad94bacf3f/crates/blockifier/resources/versioned_constants_0_13_0.json#L314)):*
> ```JSON
>                 "builtin_instance_counter": {},
>                 "n_memory_holes": 0,
>                 "n_steps": 100
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 12:03 UTC, noaov1 requested changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 3 unresolved discussions (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 38 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFHHVKB037vaZRR9rKK:-OFHHVKC1Z-Dv1ifxDcb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5029d9d9d072913bece349d4f4cd17892271f4d8/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L38)):*
> ```XML
>     let gas_costs = VersionedConstants::create_for_testing().os_constants.gas_costs;
>     let get_block_hash_gas_cost =
>         gas_costs.syscalls.get_syscall_gas_cost(&SyscallSelector::GetBlockHash)?;
> ```





_Suggestion:_
```XML
    let get_block_hash_gas_cost =
        gas_costs.syscalls.get_syscall_gas_cost(&SyscallSelector::GetBlockHash).unwrap();
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 48 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFHHdSH5swVmV6_ajj4:-OFHHdSH5swVmV6_ajj5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5029d9d9d072913bece349d4f4cd17892271f4d8/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L48)):*
> ```XML
>             // 'Out of gas'
>             retdata: retdata![felt!["0x4f7574206f6620676173"]],
>             gas_consumed: constants::REQUIRED_GAS_GET_BLOCK_HAS_TEST - syscall_required_gas,
> ```





_Suggestion:_
```XML
            // We hit the out of gas error right before executing the syscall.
            gas_consumed: constants::REQUIRED_GAS_GET_BLOCK_HAS_TEST - syscall_required_gas,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 744 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFHI-VM3bT52cgDA5dw:-OFHI-VM3bT52cgDA5dx:bhmdeuf) ([raw file](https://github.com/starkware-libs/sequencer/blob/5029d9d9d072913bece349d4f4cd17892271f4d8/crates/blockifier/src/versioned_constants.rs#L744)):*
> ```XML
> 
> impl BaseGasCosts {
>     pub fn get_base_gas_cost(&self, field: &str) -> u64 {
> ```

Where else do you use it, aside from tests?



_Code quote:_
```XML
pub fn get_base_gas_cost(&self, field: &str) -> u64 {
```


<!-- Sent from Reviewable.io -->

2024-12-29 12:25 UTC, Yonatan-Starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 744 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFHI-VM3bT52cgDA5dw:-OFHN7FJ0DrtClw5ch6a:b-xguin) ([raw file](https://github.com/starkware-libs/sequencer/blob/5029d9d9d072913bece349d4f4cd17892271f4d8/crates/blockifier/src/versioned_constants.rs#L744)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Where else do you use it, aside from tests?
</blockquote></details>

just in the test.


<!-- Sent from Reviewable.io -->

2024-12-29 12:26 UTC, Yonatan-Starkware commented
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 48 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFHHdSH5swVmV6_ajj4:-OFHNNqj9lxKuD5t8Sn2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5029d9d9d072913bece349d4f4cd17892271f4d8/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L48)):*
> ```XML
>             // 'Out of gas'
>             retdata: retdata![felt!["0x4f7574206f6620676173"]],
>             gas_consumed: constants::REQUIRED_GAS_GET_BLOCK_HAS_TEST - syscall_required_gas,
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 12:26 UTC, Yonatan-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: 20 of 24 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 38 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFHHVKB037vaZRR9rKK:-OFHNCpP1wl5Bcvv3ES3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5029d9d9d072913bece349d4f4cd17892271f4d8/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L38)):*
> ```XML
>     let gas_costs = VersionedConstants::create_for_testing().os_constants.gas_costs;
>     let get_block_hash_gas_cost =
>         gas_costs.syscalls.get_syscall_gas_cost(&SyscallSelector::GetBlockHash)?;
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 14:48 UTC, noaov1 requested changes
> Reviewed 2 of 4 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 1 unresolved discussion (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 744 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFHI-VM3bT52cgDA5dw:-OFHsls75GJ9ePtgOxgP:b-dbqg2j) ([raw file](https://github.com/starkware-libs/sequencer/blob/5029d9d9d072913bece349d4f4cd17892271f4d8/crates/blockifier/src/versioned_constants.rs#L744)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

just in the test.
</blockquote></details>

I think it's better to remove it. 


<!-- Sent from Reviewable.io -->

2024-12-29 15:24 UTC, Yonatan-Starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 744 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFHI-VM3bT52cgDA5dw:-OFI08-0-LW00brMr5Iz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5029d9d9d072913bece349d4f4cd17892271f4d8/crates/blockifier/src/versioned_constants.rs#L744)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it's better to remove it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 16:44 UTC, noaov1 approved these changes
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 1 unresolved discussion (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 22 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFII4W_3nPyIH10n6GS:-OFII4WaAye9j5kbYwBQ:b-x9pivt) ([raw file](https://github.com/starkware-libs/sequencer/blob/00a9ce2ff5bb72bbd7e9db6e7826a959e50e1959/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L22)):*
> ```XML
> use crate::versioned_constants::VersionedConstants;
> 
> const SYSCALL_BASE_GAS_COST: u64 = 10000;
> ```

And then use:
`let syscall_base_gas_cost = gas_costs.base.get_base_gas_cost(SYSCALL_BASE_GAS_COST);`



_Suggestion:_
```XML
const SYSCALL_BASE_GAS_COST: &str = "syscall_base_gas_cost";
```


<!-- Sent from Reviewable.io -->

2025-01-02 13:50 UTC, noaov1 approved these changes
> Reviewed 16 of 18 files at r16, 2 of 2 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 1 unresolved discussion (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 22 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFII4W_3nPyIH10n6GS:-OFbGTSE36-uQu29LnE-:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/00a9ce2ff5bb72bbd7e9db6e7826a959e50e1959/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L22)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

but we didn't impeled get_base_gas_cost. Should we?
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2025-01-02 13:50 UTC, meship-starkware reviewed
> Reviewed 1 of 4 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, 10 of 18 files at r16, 2 of 2 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 1 unresolved discussion (waiting on @Yonatan-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 16:34 UTC, Yonatan-Starkware commented
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 22 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFII4W_3nPyIH10n6GS:-OFbriz414zlDnexpJOx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/00a9ce2ff5bb72bbd7e9db6e7826a959e50e1959/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L22)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-05 05:55 UTC, meship-starkware reviewed
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yonatan-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 15:57 UTC, meship-starkware approved these changes
> Reviewed 5 of 18 files at r16, 3 of 3 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yonatan-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 17:01 UTC, noaov1 approved these changes
> Reviewed 1 of 2 files at r19, 1 of 3 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: all files reviewed, 1 unresolved discussion (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 43 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFrPEGq5Vsa75xa3IRD:-OFrPEGq5Vsa75xa3IRE:b-hb5izw) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9c5cc24accfc40b0764422f37960356f9a87308/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L43)):*
> ```XML
> 
>     // We hit the out of gas error right before executing the syscall.
>     let syscall_base_gas_cost = gas_costs.base.get_base_gas_cost(SYSCALL_BASE_GAS_COST);
> ```

Will this work? If so, please remove `get_base_gas_cost`.



_Suggestion:_
```XML
    let syscall_base_gas_cost = gas_costs.base.syscall_base_gas_cost;
```


<!-- Sent from Reviewable.io -->

2025-01-05 17:38 UTC, Yonatan-Starkware commented
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 43 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/2864#-OFrPEGq5Vsa75xa3IRD:-OFrXx4EDbRx_UtQxIF9:b-lkyxgj) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9c5cc24accfc40b0764422f37960356f9a87308/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L43)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Will this work? If so, please remove `get_base_gas_cost`.
</blockquote></details>

works. Done.


<!-- Sent from Reviewable.io -->

2025-01-05 21:58 UTC, noaov1 approved these changes
> Reviewed 1 of 3 files at r20, 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yonatan-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-06 06:24 UTC, noaov1 approved these changes
> Reviewed 1 of 3 files at r20, 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2864)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yonatan-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-06 06:24 UTC, merged