feat(blockifier): convert L2 gas to L1 gas units when computing fee w…
starkware-libs/sequencer pull request #2869
Opened 2024-12-22 13:45 UTC by dorimedini-starkware

…ith no L2 bounds

2024-12-22 13:45 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2869)
<!-- Reviewable:end -->

2024-12-24 11:01 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2869)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2869#-OEsK3Bh1mQZfXhgJMst:-OEsK3Bi2Sn9ReYhKgih:bpbja99) (no related file):*
rebase over `main-v0.13.4`


<!-- Sent from Reviewable.io -->

2025-01-01 12:22 UTC, TzahiTaub requested changes
> Reviewed 4 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2869)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2869#-OFWjksA0-yGA7QewwAQ:-OFWjksA0-yGA7QewwAR:bf599c3) ([raw file](https://github.com/starkware-libs/sequencer/blob/486d8d3ccbdd121591d2ef6c6e7c05aab85b441a/crates/blockifier/src/fee/fee_utils.rs#L29)):*
> ```XML
> /// A trait for converting a gas vector to L1 gas for fee. Converts both L1 data gas and L2 gas to
> /// L1 gas units.
> pub trait GasVectorToL1GasForFee {
> ```

Comment that the trait is defined in order to be able to add the implementation to the sturct imported from starknet_api.
___
*[`crates/starknet_api/src/execution_resources.rs` line 176 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2869#-OFWoHOZ6Tqg9RFu6Dw6:-OFWoHOZ6Tqg9RFu6Dw7:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/486d8d3ccbdd121591d2ef6c6e7c05aab85b441a/crates/starknet_api/src/execution_resources.rs#L176)):*
> ```XML
>     /// function does nothing.
>     /// Panics on overflow.
>     /// Does not take L2 gas into account - this must be handled separately.
> ```

?



_Suggestion:_
```XML
 /// Does not take L2 gas into account - this must be handled separately as it requires data outside of this crate scope.
```


<!-- Sent from Reviewable.io -->

2025-01-01 12:25 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2869)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2869#-OFWjksA0-yGA7QewwAQ:-OFWoip84ByGlwJJOvUS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/486d8d3ccbdd121591d2ef6c6e7c05aab85b441a/crates/blockifier/src/fee/fee_utils.rs#L29)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Comment that the trait is defined in order to be able to add the implementation to the sturct imported from starknet_api.
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/execution_resources.rs` line 176 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2869#-OFWoHOZ6Tqg9RFu6Dw6:-OFWovywACLF6hvpUL-b:bvyb82y) ([raw file](https://github.com/starkware-libs/sequencer/blob/486d8d3ccbdd121591d2ef6c6e7c05aab85b441a/crates/starknet_api/src/execution_resources.rs#L176)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

?
</blockquote></details>

better?


<!-- Sent from Reviewable.io -->

2025-01-01 13:04 UTC, TzahiTaub approved these changes
> Reviewed 1 of 8 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2869)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 320 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2869#-OFWxdMdCAYQRfufXOtB:-OFWxdMeD2yf4-xEbbX9:ber5tw9) ([raw file](https://github.com/starkware-libs/sequencer/blob/191993e21f8eb258909c47e1d1235f7e15ae1724/crates/blockifier/src/fee/gas_usage_test.rs#L320)):*
> ```XML
>             &tx_context.block_context.versioned_constants,
>         ) < actual_result
>     );
> ```

You can just assert above that `converted_l2_gas > 0` (and revert the `gas_usage` mutability).



_Code quote:_
```XML
    // Make sure L2 gas has an effect.
    gas_usage.l2_gas = 0_u8.into();
    assert!(
        gas_usage.to_l1_gas_for_fee(
            tx_context.get_gas_prices(),
            &tx_context.block_context.versioned_constants,
        ) < actual_result
    );
```


<!-- Sent from Reviewable.io -->

2025-01-01 17:18 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 320 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2869#-OFWxdMdCAYQRfufXOtB:-OFXrxXs-F4mcTkWON5s:b-xte3yt) ([raw file](https://github.com/starkware-libs/sequencer/blob/191993e21f8eb258909c47e1d1235f7e15ae1724/crates/blockifier/src/fee/gas_usage_test.rs#L320)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

You can just assert above that `converted_l2_gas > 0` (and revert the `gas_usage` mutability).
</blockquote></details>

but I want to test `to_l1_gas_for_fee`, not `sierra_gas_to_l1_gas_amount_round_up`


<!-- Sent from Reviewable.io -->

2025-01-02 11:46 UTC, TzahiTaub approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 320 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2869#-OFWxdMdCAYQRfufXOtB:-OFapUqW5rD37n1p1CtF:b-mz45pu) ([raw file](https://github.com/starkware-libs/sequencer/blob/e6d14eeb0a6dfcb66828e98e979652332670667d/crates/blockifier/src/fee/gas_usage_test.rs#L320)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

but I want to test `to_l1_gas_for_fee`, not `sierra_gas_to_l1_gas_amount_round_up`
</blockquote></details>

Ah, ok. 


<!-- Sent from Reviewable.io -->

2025-01-02 11:46 UTC, TzahiTaub approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2869#-:-OFapgAt5fYfKYU4xH-S:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 14:32 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 14:33 UTC, TzahiTaub approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 14:33 UTC, merged