refactor(starknet_api,blockifier): to_discounted_gas_amount
starkware-libs/sequencer pull request #2874
Opened 2024-12-22 14:48 UTC by dorimedini-starkware

2024-12-22 14:48 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2874)
<!-- Reviewable:end -->

2024-12-22 14:50 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2874)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/starknet_api/src/execution_resources.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OEiq8Ny08Nifr3Ad4rM:-OEiq8Ny08Nifr3Ad4rN:b-c7k36l) ([raw file](https://github.com/starkware-libs/sequencer/blob/8540cef94e936053ddd942167f972d5a5762cefd/crates/starknet_api/src/execution_resources.rs#L179)):*
> ```XML
>     l1_gas: GasAmount,
>     l1_data_gas: GasAmount,
> ) -> GasAmount {
> ```

this change is to make explicit the fact that L2 gas is ignored here



_Code quote:_
```XML
pub fn to_discounted_l1_gas(
    l1_gas_price: NonzeroGasPrice,
    l1_data_gas_price: GasPrice,
    l1_gas: GasAmount,
    l1_data_gas: GasAmount,
) -> GasAmount {
```


<!-- Sent from Reviewable.io -->

2025-01-01 13:24 UTC, TzahiTaub requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2874)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/execution_resources.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFWzk1T1PztAmB73FVM:-OFWzk1T1PztAmB73FVN:bubcycg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2dcbb4d97e5d2bcb6c85133dfbf330dc885a3eb/crates/starknet_api/src/execution_resources.rs#L167)):*
> ```XML
> }
> 
> /// Compute l1_gas estimation from gas_vector using the following formula:
> ```

Why is this an "estimation"?



_Suggestion:_
```XML
Computes the total l1 gas amount from the different given l1 gas arguments using the following formula:
```
___
*[`crates/starknet_api/src/execution_resources.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFX1GWy9CKZDwVeT1bm:-OFX1GWy9CKZDwVeT1bn:b5krnb) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2dcbb4d97e5d2bcb6c85133dfbf330dc885a3eb/crates/starknet_api/src/execution_resources.rs#L185)):*
> ```XML
>     l1_data_gas: GasAmount,
> ) -> GasAmount {
>     let l1_data_gas_fee = l1_data_gas.checked_mul(l1_data_gas_price).unwrap_or_else(|| {
> ```

Makes more sense to make the conversion here and have the type as it's in GasPriceVector IMO



_Suggestion:_
```XML
pub fn to_discounted_l1_gas(
    l1_gas_price: NonzeroGasPrice,
    l1_data_gas_price: NonzeroGasPrice,
    l1_gas: GasAmount,
    l1_data_gas: GasAmount,
) -> GasAmount {
    let l1_data_gas_fee = l1_data_gas.checked_mul(l1_data_gas_price.into()).unwrap_or_else(|| {
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFX1SeyBrs5QiKejfWV:-OFX1SeyBrs5QiKejfWW:b-sjpzht) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2dcbb4d97e5d2bcb6c85133dfbf330dc885a3eb/crates/blockifier/src/fee/fee_utils.rs#L47)):*
> ```XML
>         let discounted_l1_gas = to_discounted_l1_gas(
>             gas_prices.l1_gas_price,
>             gas_prices.l1_data_gas_price.into(),
> ```

Remove if you accept the suggestion below



_Suggestion:_
```XML
  gas_prices.l1_data_gas_price,
```


<!-- Sent from Reviewable.io -->

2025-01-01 17:22 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2874)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFX1SeyBrs5QiKejfWV:-OFXsLbt2yFr06Blw43V:byrq2m7) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2dcbb4d97e5d2bcb6c85133dfbf330dc885a3eb/crates/blockifier/src/fee/fee_utils.rs#L47)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Remove if you accept the suggestion below
</blockquote></details>

see below
___
*[`crates/starknet_api/src/execution_resources.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFWzk1T1PztAmB73FVM:-OFXsRYq7X0Qobe9uOLi:bszqnan) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2dcbb4d97e5d2bcb6c85133dfbf330dc885a3eb/crates/starknet_api/src/execution_resources.rs#L167)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why is this an "estimation"?
</blockquote></details>

maybe the wording is unclear: the actual value returned isn't really an amount of L1 gas, it's a "best effort" conversion, to be able to charge users signing deprecated resource bounds in proportion to actual computation resources / DA gas used.
I used the word "estimation", do you have a suggestion?
(your suggestion implies the returned value is actually L1 gas, when it really isn't..)
___
*[`crates/starknet_api/src/execution_resources.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFX1GWy9CKZDwVeT1bm:-OFXsD0FDhhhXy3DmLZY:b-28oe5m) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2dcbb4d97e5d2bcb6c85133dfbf330dc885a3eb/crates/starknet_api/src/execution_resources.rs#L185)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Makes more sense to make the conversion here and have the type as it's in GasPriceVector IMO
</blockquote></details>

as an API decision: we require the L1 gas price to be nonzero, but the data gas price is allowed to be zero. Why enforce nonzero data gas price?


<!-- Sent from Reviewable.io -->

2025-01-02 08:39 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2874)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFa9pjIBpjfEWOLxG77:-OFa9pjIBpjfEWOLxG78:b-2y2j2f) (no related file):*
[py side](https://reviewable.io/reviews/starkware-industries/starkware/36632)


<!-- Sent from Reviewable.io -->

2025-01-02 10:57 UTC, TzahiTaub commented
*[`crates/starknet_api/src/execution_resources.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFX1GWy9CKZDwVeT1bm:-OFadxNR1abEqdi5qO0_:bjrewc3) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab5576c02fe60cdd7c9ee61825fba598f6a06d8c/crates/starknet_api/src/execution_resources.rs#L185)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

as an API decision: we require the L1 gas price to be nonzero, but the data gas price is allowed to be zero. Why enforce nonzero data gas price?
</blockquote></details>

I don't know but that's the type we have [here](https://github.com/starkware-libs/sequencer/blob/2c1b9941205e61076d568add421a18b4240c3b6d/crates/starknet_api/src/block.rs#L446)


<!-- Sent from Reviewable.io -->

2025-01-02 11:00 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2874)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/starknet_api/src/execution_resources.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFX1GWy9CKZDwVeT1bm:-OFaeoSZBxdq_Y5YZh2l:bsv919i) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab5576c02fe60cdd7c9ee61825fba598f6a06d8c/crates/starknet_api/src/execution_resources.rs#L185)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I don't know but that's the type we have [here](https://github.com/starkware-libs/sequencer/blob/2c1b9941205e61076d568add421a18b4240c3b6d/crates/starknet_api/src/block.rs#L446)
</blockquote></details>

yes, gas prices in general must be non-zero because *sometimes* we divide by them.
in this specific function, we divide by L1 gas price, but we only *multiply* by data gas price, so it can be zero


<!-- Sent from Reviewable.io -->

2025-01-02 11:03 UTC, TzahiTaub commented
*[`crates/starknet_api/src/execution_resources.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFX1GWy9CKZDwVeT1bm:-OFafjGg51zdOFHJFGSr:brtuvyc) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab5576c02fe60cdd7c9ee61825fba598f6a06d8c/crates/starknet_api/src/execution_resources.rs#L185)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, gas prices in general must be non-zero because *sometimes* we divide by them.
in this specific function, we divide by L1 gas price, but we only *multiply* by data gas price, so it can be zero
</blockquote></details>

I don't understand, it's illegal for a use to give a 0 DA price, but you want to support it in this specific helper function?


<!-- Sent from Reviewable.io -->

2025-01-02 11:05 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2874)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/starknet_api/src/execution_resources.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFX1GWy9CKZDwVeT1bm:-OFagB4zDTtWdPIpObya:b6htla9) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab5576c02fe60cdd7c9ee61825fba598f6a06d8c/crates/starknet_api/src/execution_resources.rs#L185)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I don't understand, it's illegal for a use to give a 0 DA price, but you want to support it in this specific helper function?
</blockquote></details>

yes, because this function doesn't care.
GasPriceVector is used in many places, specifically in the block info, where we do not allow zero gas prices


<!-- Sent from Reviewable.io -->

2025-01-02 11:08 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2874)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/execution_resources.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFWzk1T1PztAmB73FVM:-OFaclXl0EVpdfjRZhft:b-e2ntrk) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab5576c02fe60cdd7c9ee61825fba598f6a06d8c/crates/starknet_api/src/execution_resources.rs#L167)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe the wording is unclear: the actual value returned isn't really an amount of L1 gas, it's a "best effort" conversion, to be able to charge users signing deprecated resource bounds in proportion to actual computation resources / DA gas used.
I used the word "estimation", do you have a suggestion?
(your suggestion implies the returned value is actually L1 gas, when it really isn't..)
</blockquote></details>

Computes the total l1 gas amount estimation from the different given l1 gas arguments using the following formula:


<!-- Sent from Reviewable.io -->

2025-01-02 12:05 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2874)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2874#-OFa9pjIBpjfEWOLxG77:-OFatewh1_ToTP5K7D3B:b-m6tflo) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[py side](https://reviewable.io/reviews/starkware-industries/starkware/36632)
</blockquote></details>

passes


<!-- Sent from Reviewable.io -->

2025-01-09 12:51 UTC, merged