chore(starknet_http_server): add metrics tests, still partial
starkware-libs/sequencer pull request #2885
Opened 2024-12-22 18:39 UTC by Itay-Tsabary-Starkware

**Stack**:
- #2885 ⬅
- #2884
- #2881
- #2744

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-12-22 18:39 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2885)
<!-- Reviewable:end -->

2024-12-23 09:28 UTC, Itay-Tsabary-Starkware reviewed
> Dismissed @graphite-app[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2885)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @graphite-app[bot])



<!-- Sent from Reviewable.io -->

2024-12-23 09:28 UTC, Itay-Tsabary-Starkware commented on crates/starknet_http_server/src/http_server_test.rs
> +        match i {
Done.
<!-- Reviewable comment -OEmq3Ps2mCl1mLZLM9C:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-12-23 12:27 UTC, nadin-Starkware requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2885)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @graphite-app[bot] and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_http_server/src/http_server_test.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2885#-OEnRe3o397NIEFJx4zU:-OEnRe3o397NIEFJx4zV:b-3ifclj) ([raw file](https://github.com/starkware-libs/sequencer/blob/f7fd62353a031bfdd82242440aebf454a2ed92d3/crates/starknet_http_server/src/http_server_test.rs#L50)):*
> ```XML
>     // The current setup does not test that. Fix the bug and update this test accordingly.
>     // Create a mock gateway client that returns arbitrary responses.
>     let txs_to_send = 3;
> ```

Should this be a constant?



_Code quote:_
```XML
txs_to_send 
```


<!-- Sent from Reviewable.io -->

2024-12-25 13:03 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2885)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @graphite-app[bot] and @nadin-Starkware)

___
*[`crates/starknet_http_server/src/http_server_test.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2885#-OEnRe3o397NIEFJx4zU:-OExuRoq70Yb9wFsqVxH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f7fd62353a031bfdd82242440aebf454a2ed92d3/crates/starknet_http_server/src/http_server_test.rs#L50)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Should this be a constant?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-25 13:03 UTC, Itay-Tsabary-Starkware commented on crates/starknet_http_server/src/http_server_test.rs
> +        parse_numeric_metric::<usize>(&metrics, ADDED_TRANSACTIONS_TOTAL.0);
Done.
<!-- Reviewable comment -OExuTaLClmUXtuzM-hZ:b-896fix -->
<!-- Sent from Reviewable.io -->

2025-02-01 08:04 UTC, closed without merging