refactor(papyrus_storage): add append_events function that writes the events of a block to storage
starkware-libs/sequencer pull request #2900
Opened 2024-12-23 12:06 UTC by AlonLStarkWare

2024-12-23 12:06 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2900)
<!-- Reviewable:end -->

2024-12-24 11:39 UTC, ShahakShama requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2900)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_storage/src/body/events.rs` line 377 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OEs8CBJDjjjf21t0qw9:-OEs8CBJDjjjf21t0qwA:b9sphs1) ([raw file](https://github.com/starkware-libs/sequencer/blob/718999b86d91eab83d51c482275856a241d54040/crates/papyrus_storage/src/body/events.rs#L377)):*
> ```XML
>     DbCursor<'txn, RO, TransactionIndex, VersionZeroWrapper<TransactionMetadata>, SimpleTable>;
> 
> /// interface for updating the events in the storage.
> ```

capitalization
___
*[`crates/papyrus_storage/src/body/events.rs` line 382 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OEs8Vm89s5mEa3Vm8zT:-OEs8Vm89s5mEa3Vm8zU:bc3kk4w) ([raw file](https://github.com/starkware-libs/sequencer/blob/718999b86d91eab83d51c482275856a241d54040/crates/papyrus_storage/src/body/events.rs#L382)):*
> ```XML
>     Self: Sized,
> {
>     /// Appends the events of an entire block to the storage.
> ```

Copy this comment: https://github.com/starkware-libs/sequencer/blob/34c98a06696a00fd766831e8089bdfd6b8e7d558/crates/papyrus_storage/src/class.rs#L118
___
*[`crates/papyrus_storage/src/body/events.rs` line 386 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OEs8Ja88nI6sWvrDKJt:-OEs8Ja88nI6sWvrDKJu:bn3gf45) ([raw file](https://github.com/starkware-libs/sequencer/blob/718999b86d91eab83d51c482275856a241d54040/crates/papyrus_storage/src/body/events.rs#L386)):*
> ```XML
>         self,
>         block_number: BlockNumber,
>         block_events: Vec<Vec<Event>>,
> ```

Receive this by reference and as an array slice and not a vec: &[&[Event]]

In general if you don't need to consume the value it's better to pass it by reference (as long as you don't clone it anywhere)
Also, in general it's better to receive &[T] instead of &Vec<T> as the former can handle the latter yet also handle different stuff like arrays (You'll find that useful in tests for example)
___
*[`crates/papyrus_storage/src/body/events.rs` line 425 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OEsR4i02clZeZo6pVDT:-OEsR4i02clZeZo6pVDU:bmixj27) ([raw file](https://github.com/starkware-libs/sequencer/blob/718999b86d91eab83d51c482275856a241d54040/crates/papyrus_storage/src/body/events.rs#L425)):*
> ```XML
>     for (index, transaction_events) in block_events.iter().enumerate() {
>         let transaction_index = TransactionIndex(block_number, TransactionOffsetInBlock(index));
>         let event_offset = file_handlers.append_events(&transaction_events.clone());
> ```

Why clone?


<!-- Sent from Reviewable.io -->

2024-12-25 13:15 UTC, AlonLStarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2900)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_storage/src/body/events.rs` line 377 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OEs8CBJDjjjf21t0qw9:-OExrBdb0Yx785puZcBq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/718999b86d91eab83d51c482275856a241d54040/crates/papyrus_storage/src/body/events.rs#L377)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

capitalization
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/events.rs` line 382 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OEs8Vm89s5mEa3Vm8zT:-OExrd-R-EUZw-65TryZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/718999b86d91eab83d51c482275856a241d54040/crates/papyrus_storage/src/body/events.rs#L382)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Copy this comment: https://github.com/starkware-libs/sequencer/blob/34c98a06696a00fd766831e8089bdfd6b8e7d558/crates/papyrus_storage/src/class.rs#L118
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/events.rs` line 386 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OEs8Ja88nI6sWvrDKJt:-OExs4Ef6b4y77Zjm3k_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/718999b86d91eab83d51c482275856a241d54040/crates/papyrus_storage/src/body/events.rs#L386)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Receive this by reference and as an array slice and not a vec: &[&[Event]]

In general if you don't need to consume the value it's better to pass it by reference (as long as you don't clone it anywhere)
Also, in general it's better to receive &[T] instead of &Vec<T> as the former can handle the latter yet also handle different stuff like arrays (You'll find that useful in tests for example)
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/events.rs` line 425 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OEsR4i02clZeZo6pVDT:-OExx3N22fQy73x4u6Yl:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/718999b86d91eab83d51c482275856a241d54040/crates/papyrus_storage/src/body/events.rs#L425)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why clone?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-30 13:15 UTC, ShahakShama requested changes
> Reviewed 1 of 5 files at r4, 2 of 5 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2900)* status: all files reviewed, 4 unresolved discussions (waiting on @AlonLStarkWare and @noamsp-starkware)

___
*[`crates/papyrus_storage/src/body/mod.rs` line 89 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OFMgjECDGbmS78pCUw7:-OFMgjECDGbmS78pCUw8:b-58hxy2) ([raw file](https://github.com/starkware-libs/sequencer/blob/298f1b1153ff616c41d9ff76135a240c3339ff2c/crates/papyrus_storage/src/body/mod.rs#L89)):*
> ```XML
>     CommonPrefix,
> >;
> // TODO: remove the dead code attribute.
> ```

Name this TODO on you
___
*[`crates/papyrus_storage/src/body/events.rs` line 415 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OFMfhlG0P3ORTp2wJX4:-OFMfhlG0P3ORTp2wJX5:bufnhck) ([raw file](https://github.com/starkware-libs/sequencer/blob/298f1b1153ff616c41d9ff76135a240c3339ff2c/crates/papyrus_storage/src/body/events.rs#L415)):*
> ```XML
>                 let transaction_index =
>                     TransactionIndex(block_number, TransactionOffsetInBlock(index));
>                 let event_offset = self.file_handlers.append_events(transaction_events);
> ```

event -> events
Is this called offset regularly? maybe file_offset for clarity
___
*[`crates/papyrus_storage/src/body/events.rs` line 417 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OFMgGVbE5ePh3rl8aWg:-OFMgGVc6RLbmjR2L8mn:b4ayeh8) ([raw file](https://github.com/starkware-libs/sequencer/blob/298f1b1153ff616c41d9ff76135a240c3339ff2c/crates/papyrus_storage/src/body/events.rs#L417)):*
> ```XML
>                 let event_offset = self.file_handlers.append_events(transaction_events);
>                 events_table.append(&self.txn, &transaction_index, &event_offset)?;
>                 for event in transaction_events {
> ```

It looks like in [main](https://github.com/starkware-libs/sequencer/blob/0055360404cd968b54b0d53ce36ee3847009eaab/crates/papyrus_storage/src/body/mod.rs#L486) we gather all the contract addresses of all the events of a single tx and then write them all together. Could you do the same here?
___
*[`crates/papyrus_storage/src/lib.rs` line 725 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OFMh-HVD7-Z1_oMharL:-OFMh-HVD7-Z1_oMharM:bm1m3u) ([raw file](https://github.com/starkware-libs/sequencer/blob/298f1b1153ff616c41d9ff76135a240c3339ff2c/crates/papyrus_storage/src/lib.rs#L725)):*
> ```XML
>     // Appends an event to the corresponding file and returns its location.
>     fn append_events(&self, events: &[Event]) -> LocationInFile {
>         self.clone().event.append(&events.to_vec())
> ```

If you need to do that, then it's better the type will be Vec<Event>
So the outer type should be &[&Vec<Event>]


<!-- Sent from Reviewable.io -->

2024-12-31 09:12 UTC, AlonLStarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2900)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/lib.rs` line 725 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OFMh-HVD7-Z1_oMharL:-OFQz2iN6YaspVjwRj4N:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/298f1b1153ff616c41d9ff76135a240c3339ff2c/crates/papyrus_storage/src/lib.rs#L725)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

If you need to do that, then it's better the type will be Vec<Event>
So the outer type should be &[&Vec<Event>]
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/events.rs` line 415 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OFMfhlG0P3ORTp2wJX4:-OFMhcc_0_FB7kw16eW3:b7qw2pz) ([raw file](https://github.com/starkware-libs/sequencer/blob/298f1b1153ff616c41d9ff76135a240c3339ff2c/crates/papyrus_storage/src/body/events.rs#L415)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

event -> events
Is this called offset regularly? maybe file_offset for clarity
</blockquote></details>

It is only called once. I can change the name to event_location to match the transaction case ([where the return value of file_handlers.append_transactions is named tx_location](https://github.com/starkware-libs/sequencer/blob/298f1b1153ff616c41d9ff76135a240c3339ff2c/crates/papyrus_storage/src/body/mod.rs#L469))
___
*[`crates/papyrus_storage/src/body/mod.rs` line 89 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OFMgjECDGbmS78pCUw7:-OFMj4A50z8dL8BtF-KV:b-l0uu0g) ([raw file](https://github.com/starkware-libs/sequencer/blob/298f1b1153ff616c41d9ff76135a240c3339ff2c/crates/papyrus_storage/src/body/mod.rs#L89)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Name this TODO on you
</blockquote></details>

It's already removed in a later PR but sure


<!-- Sent from Reviewable.io -->

2025-01-05 10:46 UTC, AlonLStarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2900)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/body/events.rs` line 417 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2900#-OFMgGVbE5ePh3rl8aWg:-OFRRyQWDVflGMcjLJIW:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/298f1b1153ff616c41d9ff76135a240c3339ff2c/crates/papyrus_storage/src/body/events.rs#L417)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It looks like in [main](https://github.com/starkware-libs/sequencer/blob/0055360404cd968b54b0d53ce36ee3847009eaab/crates/papyrus_storage/src/body/mod.rs#L486) we gather all the contract addresses of all the events of a single tx and then write them all together. Could you do the same here?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2025-02-12 08:05 UTC, closed without merging