feat(starknet_gateway): create transaction generator towards benchmarking
starkware-libs/sequencer pull request #2911
Opened 2024-12-24 08:51 UTC by ArniStarkware

2024-12-24 08:51 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2911)
<!-- Reviewable:end -->

2024-12-24 08:51 UTC, ArniStarkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2911?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2911** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2911?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2911?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2404** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2404?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-26 10:10 UTC, yair-starkware requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: all files reviewed, 11 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @Yael-Starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1ODqd5Ffl_O4oHM_9:-OF1ODqd5Ffl_O4oHM_A:bxgfnok) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/gateway.rs#L29)):*
> ```XML
> pub mod gateway_test;
> 
> pub struct GatewayBusinessLogic {
> ```

Why not pub(crate)?



_Code quote:_
```XML
pub
```
___
*[`crates/starknet_gateway/src/gateway.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1OIM9DJ26SpJL6nP9:-OF1OIM9DJ26SpJL6nPA:bxgfnok) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/gateway.rs#L79)):*
> ```XML
> pub struct Gateway {
>     pub mempool_client: SharedMempoolClient,
>     pub business_logic: GatewayBusinessLogic,
> ```

Why not pub(crate)?



_Code quote:_
```XML
pub
```
___
*[`crates/starknet_gateway/bench/gateway_bench.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1OZfP1LqvVHk9gA6A:-OF1OZfP1LqvVHk9gA6B:b-cbfd0l) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/bench/gateway_bench.rs#L15)):*
> ```XML
> use starknet_gateway::bench_test_utils::{BenchTestSetup, BenchTestSetupConfig};
> 
> pub fn declare_benchmark(c: &mut Criterion) {
> ```

Can these functions not be pub?



_Code quote:_
```XML
pub
```
___
*[`crates/starknet_gateway/bench/gateway_bench.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1OvA94ONiG0NEeHB0:-OF1OvA94ONiG0NEeHB1:baoqi4e) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/bench/gateway_bench.rs#L28)):*
> ```XML
> 
>     let test_setup = BenchTestSetup::new(tx_generator_config);
>     c.bench_with_input(BenchmarkId::new("invoke", n_txs), &test_setup, |b, s| {
> ```

Can you give meaningful names?



_Code quote:_
```XML
b, s
```
___
*[`crates/starknet_gateway/src/bench_test_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1QvMb8bkdyh84TDek:-OF1QvMb8bkdyh84TDel:b-za80oz) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/bench_test_utils.rs#L49)):*
> ```XML
>     sender_address: ContractAddress,
>     test_contract_address: ContractAddress,
> }
> ```

Can we reuse `AccountTransactionGenerator` from sn_api_test_utils?



_Code quote:_
```XML
struct TransactionGenerator {
    nonce_manager: NonceManager,
    sender_address: ContractAddress,
    test_contract_address: ContractAddress,
}
```
___
*[`crates/starknet_gateway/src/bench_test_utils.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1PVDx3u1t8PMVjpFH:-OF1PVDy9kGeicFVHt3T:b-4nki6u) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/bench_test_utils.rs#L71)):*
> ```XML
> }
> 
> impl BenchTestSetup {
> ```

Move the impl closer to the struct



_Code quote:_
```XML
impl BenchTestSetup
```
___
*[`crates/starknet_gateway/src/bench_test_utils.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1PobS4W81N0gSNZXV:-OF1PobTAJYJVk3w03Ar:ba84aze) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/bench_test_utils.rs#L73)):*
> ```XML
> impl BenchTestSetup {
>     pub fn new(config: BenchTestSetupConfig) -> Self {
>         let cairo_version = CairoVersion::Cairo0;
> ```

Why Cairo0?



_Code quote:_
```XML
Cairo0
```
___
*[`crates/starknet_gateway/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NT448AiIsBQZQpNN:-OF1NT448AiIsBQZQpNO:bh0jq5o) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/lib.rs#L1)):*
> ```XML
> #[cfg(any(feature = "testing", test))]
> ```

Why testing?



_Code quote:_
```XML
#[cfg(any(feature = "testing", test))]
```
___
*[`crates/starknet_gateway/src/lib.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NPemALExqkpiBgd0:-OF1NPemALExqkpiBgd1:b8b3jvj) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/lib.rs#L2)):*
> ```XML
> #[cfg(any(feature = "testing", test))]
> pub mod bench_test_utils;
> ```

Why pub?



_Code quote:_
```XML
pub mod bench_test_utils;
```
___
*[`crates/starknet_gateway/src/lib.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NVnsE1phEux0LgAZ:-OF1NVnsE1phEux0LgA_:bh0jq5o) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/lib.rs#L14)):*
> ```XML
> mod rpc_state_reader_test;
> pub mod state_reader;
> #[cfg(any(feature = "testing", test))]
> ```

Why testing?



_Code quote:_
```XML
#[cfg(any(feature = "testing", test))]
```
___
*[`crates/starknet_gateway/Cargo.toml` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1RK8vAANWOtaw3xOf:-OF1RK8vAANWOtaw3xOg:bghxr81) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/Cargo.toml#L58)):*
> ```TOML
> name = "gateway_bench"
> path = "bench/gateway_bench.rs"
> required-features = ["testing"]
> ```

Why do we need this?



_Code quote:_
```TOML
required-features = ["testing"]
```


<!-- Sent from Reviewable.io -->

2024-12-26 15:41 UTC, ArniStarkware commented
*[`crates/starknet_gateway/src/gateway.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1OIM9DJ26SpJL6nP9:-OF2c9UD-ydhrfBiDQPy:b6gakad) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/gateway.rs#L79)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not pub(crate)?
</blockquote></details>

This is not possible. It is used in: `crates/starknet_sequencer_node/src/components.rs`.


<!-- Sent from Reviewable.io -->

2024-12-26 15:47 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @alonh5, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_gateway/bench/gateway_bench.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1OZfP1LqvVHk9gA6A:-OF2ZarS7C1cFXq8uGi1:blg2dno) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/bench/gateway_bench.rs#L15)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can these functions not be pub?
</blockquote></details>

Done. (in previous PR).
___
*[`crates/starknet_gateway/bench/gateway_bench.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1OvA94ONiG0NEeHB0:-OF2a_jLEYgVL9ika7Lb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/bench/gateway_bench.rs#L28)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can you give meaningful names?
</blockquote></details>

Done.
___
*[`crates/starknet_gateway/src/bench_test_utils.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1PVDx3u1t8PMVjpFH:-OF2b7wq-BcVyEq4cl-N:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/bench_test_utils.rs#L71)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Move the impl closer to the struct
</blockquote></details>

Done.
___
*[`crates/starknet_gateway/src/bench_test_utils.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1PobS4W81N0gSNZXV:-OF2bWpWDielRE5ELqqI:b-970oye) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/bench_test_utils.rs#L73)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why Cairo0?
</blockquote></details>

No good reason. Now using Cairo1 to better reflect reality. Done.
___
*[`crates/starknet_gateway/src/gateway.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1ODqd5Ffl_O4oHM_9:-OF2c_383zQUjN88ZMX2:b-7blbtm) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/gateway.rs#L29)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not pub(crate)?
</blockquote></details>

Done. 

(This must not "`private`" as `crates/starknet_gateway/src/bench_test_utils.rs` uses this struct - outside this file).


<!-- Sent from Reviewable.io -->

2024-12-29 08:36 UTC, yair-starkware reviewed
> Reviewed 1 of 2 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @Yael-Starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1OIM9DJ26SpJL6nP9:-OFGYf366bTKPvrIEKkJ:b24zrn1) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/gateway.rs#L79)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is not possible. It is used in: `crates/starknet_sequencer_node/src/components.rs`.
</blockquote></details>

Private is even better :)


<!-- Sent from Reviewable.io -->

2024-12-29 08:36 UTC, yair-starkware reviewed
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-29 09:21 UTC, ArniStarkware commented
*[`crates/starknet_gateway/src/gateway.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1OIM9DJ26SpJL6nP9:-OFGhaZA7iCETo_Y-s9l:bdalfr2) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/gateway.rs#L79)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Private is even better :)
</blockquote></details>

1. It can't be private for the same reason.
2. There is an import in `crates/starknet_gateway/src/communication.rs`


<!-- Sent from Reviewable.io -->

2024-12-29 10:17 UTC, ArniStarkware commented
*[`crates/starknet_gateway/src/lib.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NPemALExqkpiBgd0:-OFGuBPA6w4Y137sdWTy:bxjx3o2) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/lib.rs#L2)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why pub?
</blockquote></details>

I tried some more private variations. Did not work. 
With `pub(crate)` and without anything, `crates/starknet_gateway/bench/gateway_bench.rs` complaints on
```
error[E0603]: module `bench_test_utils` is private
  --> crates/starknet_gateway/bench/gateway_bench.rs:13:23
   |
13 | use starknet_gateway::bench_test_utils::{BenchTestSetup, BenchTestSetupConfig};
   |                       ^^^^^^^^^^^^^^^^ private module
```


<!-- Sent from Reviewable.io -->

2024-12-29 11:08 UTC, yair-starkware commented
*[`crates/starknet_gateway/src/gateway.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1OIM9DJ26SpJL6nP9:-OFH5ULA4bRSOp-cyW4F:bifqt34) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/gateway.rs#L79)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

1. It can't be private for the same reason.
2. There is an import in `crates/starknet_gateway/src/communication.rs`
</blockquote></details>

I meant the `business_logic` member in the `Gateway` struct


<!-- Sent from Reviewable.io -->

2024-12-29 11:19 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @Yael-Starkware)

___
*[`crates/starknet_gateway/src/lib.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NPemALExqkpiBgd0:-OFH7vmc6G4G8vznZJSV:b63oumi) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/lib.rs#L2)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I tried some more private variations. Did not work. 
With `pub(crate)` and without anything, `crates/starknet_gateway/bench/gateway_bench.rs` complaints on
```
error[E0603]: module `bench_test_utils` is private
  --> crates/starknet_gateway/bench/gateway_bench.rs:13:23
   |
13 | use starknet_gateway::bench_test_utils::{BenchTestSetup, BenchTestSetupConfig};
   |                       ^^^^^^^^^^^^^^^^ private module
```
</blockquote></details>

Ok resolving


<!-- Sent from Reviewable.io -->

2024-12-29 11:54 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @alonh5, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_gateway/Cargo.toml` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1RK8vAANWOtaw3xOf:-OFGxOM1CdWkFEyfm-PC:b-osks8z) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/Cargo.toml#L58)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need this?
</blockquote></details>

Removed, post [this](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NT448AiIsBQZQpNN) discussion.
We can instead decide to use a new feature `"bench"` if we do not  like the latest solution I suggested.
___
*[`crates/starknet_gateway/src/bench_test_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1QvMb8bkdyh84TDek:-OF2adNw0DBPg3DDfU1U:b-abdjas) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/bench_test_utils.rs#L49)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can we reuse `AccountTransactionGenerator` from sn_api_test_utils?
</blockquote></details>

I tried.
There are some differences in the addresses.

Here, we use `get_instance_address` for the address - which matches the state generated with `local_test_state_reader_factory`. 
The addresses `AccountTransactionGenerator` are generated with a deploy account tx, and the state is generated in `IntegrationTestSetup` and `StorageTestSetup::new`.

For now, I just want to create something that works.
Added a todo to use the shared util.
___
*[`crates/starknet_gateway/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NT448AiIsBQZQpNN:-OFGwq0Z5fWGnLG1Iq4C:bn8mc83) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/lib.rs#L1)):*
[Here](https://github.com/rust-lang/cargo/issues/8897#issuecomment-733404410) is an explanation of the current structure.

> Modules annotated with the `#[cfg(test)]` macro cannot be `use`'d by benchmarks, as an unresolved import error is thrown when `$ cargo bench` is run.
___
*[`crates/starknet_gateway/src/lib.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NVnsE1phEux0LgAZ:-OFHCG-pErWbWMLAoPQ5:b-umtnls) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/lib.rs#L14)):*
> Modules annotated with the `#[cfg(test)]` macro cannot be `use`'d by benchmarks, as an unresolved import error is thrown when `$ cargo bench` is run.
Tried a new approach. This module is not `pub` anyway - so removing the `test` cfg should be not an issue.


<!-- Sent from Reviewable.io -->

2024-12-29 13:53 UTC, yair-starkware reviewed
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_gateway/src/lib.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NVnsE1phEux0LgAZ:-OFHfp_w3qpfGIJQQ1hB:b-o57y3r) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/lib.rs#L14)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

> Modules annotated with the `#[cfg(test)]` macro cannot be `use`'d by benchmarks, as an unresolved import error is thrown when `$ cargo bench` is run.
Tried a new approach. This module is not `pub` anyway - so removing the `test` cfg should be not an issue.
</blockquote></details>

SGTM.
Perhaps we can create a folder called `bench_utils` and put everything inside?


<!-- Sent from Reviewable.io -->

2024-12-29 13:53 UTC, yair-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-:-OFHgRZV0CU4thnBnc-r:bnfp4nl)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @alonh5 and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-29 14:28 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @alonh5, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_gateway/src/lib.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NVnsE1phEux0LgAZ:-OFHnqxM5tBQhoU6bbk6:btdcphe) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/lib.rs#L14)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

SGTM.
Perhaps we can create a folder called `bench_utils` and put everything inside?
</blockquote></details>

Including the `state_reader_test_utils` (also used for other things)?
For now, it is just the file `bench_test_utils`.

It is probably going to expand soon, so when it does - we should keep it organized. 


<!-- Sent from Reviewable.io -->

2025-01-02 11:04 UTC, yair-starkware approved these changes
> Reviewed 1 of 2 files at r5, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_gateway/src/lib.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OF1NVnsE1phEux0LgAZ:-OFaf_jn7fEzSlGzYwct:boq5g2s) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce1576d6405f11a6f5155ee3c1f489d9b85d9348/crates/starknet_gateway/src/lib.rs#L14)):*
> Including the `state_reader_test_utils`

I don't know what this is, ask @Yael-Starkware 


<!-- Sent from Reviewable.io -->

2025-01-02 13:32 UTC, alonh5 requested changes
> Reviewed 1 of 2 files at r5, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/starknet_gateway/src/lib.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OFbCJY0945hLYvhUlq_:-OFbCJY14wGWFMkO3tmO:b-1734j0) ([raw file](https://github.com/starkware-libs/sequencer/blob/1eb67ddd36cf11a67c53ac5c8594d100863cb4c4/crates/starknet_gateway/src/lib.rs#L12)):*
> ```XML
> mod rpc_state_reader_test;
> pub mod state_reader;
> #[cfg(test)]
> ```

Instead of removing this can you add a "testing" feature and use it in the bench?


<!-- Sent from Reviewable.io -->

2025-01-05 08:55 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/starknet_gateway/src/lib.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OFbCJY0945hLYvhUlq_:-OFpbL8Z1TuCIoM8gl5R:b-lagbzo) ([raw file](https://github.com/starkware-libs/sequencer/blob/1eb67ddd36cf11a67c53ac5c8594d100863cb4c4/crates/starknet_gateway/src/lib.rs#L12)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Instead of removing this can you add a "testing" feature and use it in the bench?
</blockquote></details>

@yair-starkware - This is at odds with our discussions on the topic.

IIUC, the feature "testing" is about sharing utilities that other crates can use for testing. For example, `starknet_api` has a `test_utils` module in the "testing" feature so that the test utils can be used in the gateway's tests.
This is not the case here. Here are the utils used to test this specific crate.
Also, see [this](https://github.com/rust-lang/cargo/issues/8897#issuecomment-733404410) that indicates that the benchmark is not considered a test.


We can also create another feature, for example, "bench-testing." Or we can decide it is not an issue to have all this code in the "testing" feature - as, indeed, the bench is an external code that uses code from the module for testing purposes. 


<!-- Sent from Reviewable.io -->

2025-01-05 09:34 UTC, yair-starkware commented
*[`crates/starknet_gateway/src/lib.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OFbCJY0945hLYvhUlq_:-OFpniVVCRX9HZ-rNHaQ:bc1ibd) ([raw file](https://github.com/starkware-libs/sequencer/blob/1eb67ddd36cf11a67c53ac5c8594d100863cb4c4/crates/starknet_gateway/src/lib.rs#L12)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@yair-starkware - This is at odds with our discussions on the topic.

IIUC, the feature "testing" is about sharing utilities that other crates can use for testing. For example, `starknet_api` has a `test_utils` module in the "testing" feature so that the test utils can be used in the gateway's tests.
This is not the case here. Here are the utils used to test this specific crate.
Also, see [this](https://github.com/rust-lang/cargo/issues/8897#issuecomment-733404410) that indicates that the benchmark is not considered a test.


We can also create another feature, for example, "bench-testing." Or we can decide it is not an issue to have all this code in the "testing" feature - as, indeed, the bench is an external code that uses code from the module for testing purposes.
</blockquote></details>

Is it possible to make it an inner module of the bench test?


<!-- Sent from Reviewable.io -->

2025-01-05 10:04 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_gateway/src/lib.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OFbCJY0945hLYvhUlq_:-OFpsMvn189p1kxm7wPW:b1ea2vl) ([raw file](https://github.com/starkware-libs/sequencer/blob/1eb67ddd36cf11a67c53ac5c8594d100863cb4c4/crates/starknet_gateway/src/lib.rs#L12)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is it possible to make it an inner module of the bench test?
</blockquote></details>

It is possible to move the `bench_test_utils` to be an inner module of the bench test. We still have to address the visibility of `state_reader_test_utils`. This state reader is used for this bench.


<!-- Sent from Reviewable.io -->

2025-01-05 10:50 UTC, alonh5 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_gateway/src/lib.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OFbCJY0945hLYvhUlq_:-OFq43-R2FlMmBhkBuq5:b-oo17pd) ([raw file](https://github.com/starkware-libs/sequencer/blob/1eb67ddd36cf11a67c53ac5c8594d100863cb4c4/crates/starknet_gateway/src/lib.rs#L12)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It is possible to move the `bench_test_utils` to be an inner module of the bench test. We still have to address the visibility of `state_reader_test_utils`. This state reader is used for this bench.
</blockquote></details>

This is testing code, even if other crates currently don't use it. If it's possible please add the "testing" feature and use it in the bench.


<!-- Sent from Reviewable.io -->

2025-01-05 12:32 UTC, ArniStarkware commented
*[`crates/starknet_gateway/src/lib.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OFbCJY0945hLYvhUlq_:-OFqRyfxC3D0rA6kFE9w:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1eb67ddd36cf11a67c53ac5c8594d100863cb4c4/crates/starknet_gateway/src/lib.rs#L12)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is testing code, even if other crates currently don't use it. If it's possible please add the "testing" feature and use it in the bench.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-05 12:35 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r8, 2 of 3 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-:-OFqScAZ7mzs2DHIlAHl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware and @yair-starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 12:53 UTC, yair-starkware reviewed
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/starknet_gateway/src/lib.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OFbCJY0945hLYvhUlq_:-OFqWEoG1vSXPCphfuro:bq1e9sz) ([raw file](https://github.com/starkware-libs/sequencer/blob/1eb67ddd36cf11a67c53ac5c8594d100863cb4c4/crates/starknet_gateway/src/lib.rs#L12)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't want to be too pedantic, but benchmarking is not testing.
You can collect benchmark data and test for regressions.


<!-- Sent from Reviewable.io -->

2025-01-05 13:11 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @alonh5, @ArniStarkware, and @Yael-Starkware)

___
*[`crates/starknet_gateway/src/lib.rs` line 13 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OFq_dCT2FzBddp2-0YP:-OFq_dCT2FzBddp2-0YQ:b72yor1) ([raw file](https://github.com/starkware-libs/sequencer/blob/392dca680e1fb6dc80c7ff5edc56340404948b3a/crates/starknet_gateway/src/lib.rs#L13)):*
> ```XML
> pub mod state_reader;
> #[cfg(any(feature = "testing", test))]
> pub mod state_reader_test_utils;
> ```

TODO: Move to mempool test utils.
Per our latest discussion.
We agreed this is non-blocking.

@alonh5 @yair-starkware 



_Code quote:_
```XML
#[cfg(any(feature = "testing", test))]
pub mod state_reader_test_utils;
```


<!-- Sent from Reviewable.io -->

2025-01-05 14:08 UTC, alonh5 reviewed
> Reviewed 3 of 5 files at r11, 1 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 14:30 UTC, alonh5 requested changes
> Reviewed 1 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/starknet_gateway/bench/bench_lib.rs` line 1 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OFqrnK93GesoPCAPe-M:-OFqrnK93GesoPCAPe-N:b-8w6mrn) ([raw file](https://github.com/starkware-libs/sequencer/blob/392dca680e1fb6dc80c7ff5edc56340404948b3a/crates/starknet_gateway/bench/bench_lib.rs#L1)):*
> ```XML
> //! Benchmark module for the starknet gateway crate. It provides functionalities to benchmark
> ```

Why do we need this module and not just have the utils in `bench/`?


<!-- Sent from Reviewable.io -->

2025-01-05 15:56 UTC, ArniStarkware commented
*[`crates/starknet_gateway/bench/bench_lib.rs` line 1 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2911#-OFqrnK93GesoPCAPe-M:-OFrAZvu7HaT9SfLpIhJ:bp3aow6) ([raw file](https://github.com/starkware-libs/sequencer/blob/392dca680e1fb6dc80c7ff5edc56340404948b3a/crates/starknet_gateway/bench/bench_lib.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do we need this module and not just have the utils in `bench/`?
</blockquote></details>

Reverted.


<!-- Sent from Reviewable.io -->

2025-01-05 16:03 UTC, ArniStarkware reviewed
> Reviewed 1 of 2 files at r8, 2 of 6 files at r12, 3 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 16:43 UTC, merged