feat(consensus): add declare transaction for cende
starkware-libs/sequencer pull request #2921
Opened 2024-12-24 12:12 UTC by Yael-Starkware

2024-12-24 12:12 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2921)
<!-- Reviewable:end -->

2024-12-24 12:13 UTC, Yael-Starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2921?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2921** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2921?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2921?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2872** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2872?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2861** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2861?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2715** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2715?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-30 12:56 UTC, dafnamatsry requested changes
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2921)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2921#-OFM_otzB69nsDNpnGKV:-OFM_otzB69nsDNpnGKW:b-d1vvnt) ([raw file](https://github.com/starkware-libs/sequencer/blob/cabd90b39a8f6534b874b2e953b37df7c0834a67/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L120)):*
> ```XML
> }
> 
> impl From<CentralSierraVersion> for (String, String, String) {
> ```

Where is this being used?
___
*[`crates/starknet_api/src/executable_transaction.rs` line 162 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2921#-OFMaQNHDIlOLDVmgGAl:-OFMaQNHDIlOLDVmgGAm:b1b7o9v) ([raw file](https://github.com/starkware-libs/sequencer/blob/cabd90b39a8f6534b874b2e953b37df7c0834a67/crates/starknet_api/src/executable_transaction.rs#L162)):*
> ```XML
>         (account_deployment_data, AccountDeploymentData),
>         (compiled_class_hash, CompiledClassHash),
>         (resource_bounds, ValidResourceBounds)
> ```

Note that you are adding here getters for all tx versionsm that panics for versions that don't have those field.
I think it is fine but at least worth documenting it.
Or add a similar `implement_v3_tx_getters!` as done in the inner transaction types.



_Code quote:_
```XML
        (tip, Tip),
        (nonce_data_availability_mode, DataAvailabilityMode),
        (fee_data_availability_mode, DataAvailabilityMode),
        (paymaster_data, PaymasterData),
        (account_deployment_data, AccountDeploymentData),
        (compiled_class_hash, CompiledClassHash),
        (resource_bounds, ValidResourceBounds)
```


<!-- Sent from Reviewable.io -->

2024-12-30 13:41 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2921)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2921#-OFM_otzB69nsDNpnGKV:-OFMm55H3vGqxTxcKi_c:b-o0tyu0) ([raw file](https://github.com/starkware-libs/sequencer/blob/cabd90b39a8f6534b874b2e953b37df7c0834a67/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L120)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Where is this being used?
</blockquote></details>

when serializing this object, it needs to be serialized as a hex string.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 162 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2921#-OFMaQNHDIlOLDVmgGAl:-OFMnEBABak5ZObyT6CJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cabd90b39a8f6534b874b2e953b37df7c0834a67/crates/starknet_api/src/executable_transaction.rs#L162)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Note that you are adding here getters for all tx versionsm that panics for versions that don't have those field.
I think it is fine but at least worth documenting it.
Or add a similar `implement_v3_tx_getters!` as done in the inner transaction types.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-31 09:11 UTC, dafnamatsry requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2921)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2921#-OFM_otzB69nsDNpnGKV:-OFQyHvI8uqIVCPYEYs9:b-pa73ow) ([raw file](https://github.com/starkware-libs/sequencer/blob/cabd90b39a8f6534b874b2e953b37df7c0834a67/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L120)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

when serializing this object, it needs to be serialized as a hex string.
</blockquote></details>

So why do we need this object (`CentralSierraVersion`) at all if we convert it to string tuple?
You can define the sierra_version directly as `(String, String, String)`, and implement `From<SierraVersion> for (String, String, String)`
___
*[`crates/starknet_api/src/executable_transaction.rs` line 172 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2921#-OFQmDV7-eWg09c5Upf9:-OFQmDV7-eWg09c5UpfA:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f60e0d349d830f0ba70460fdc698d53c45c8734c/crates/starknet_api/src/executable_transaction.rs#L172)):*
> ```XML
>         (account_deployment_data, AccountDeploymentData),
>         (resource_bounds, ValidResourceBounds)
>     );
> ```





_Suggestion:_
```XML
    implement_inner_tx_getter_calls!(
        (class_hash, ClassHash),
        (nonce, Nonce),
        (sender_address, ContractAddress),
        (signature, TransactionSignature),
        (version, TransactionVersion),
        
        // compiled_class_hash is only supported in V2 and V3, otherwise the getter panics.
        (compiled_class_hash, CompiledClassHash),
        
        // The following fields are only supported in V3, otherwise the getter panics.
        (tip, Tip),
        (nonce_data_availability_mode, DataAvailabilityMode),
        (fee_data_availability_mode, DataAvailabilityMode),
        (paymaster_data, PaymasterData),
        (account_deployment_data, AccountDeploymentData),
        (resource_bounds, ValidResourceBounds)
    );
```


<!-- Sent from Reviewable.io -->

2024-12-31 13:57 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2921)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2921#-OFM_otzB69nsDNpnGKV:-OFS-IwRBsuMdW6IMsH6:b-ljhv6u) ([raw file](https://github.com/starkware-libs/sequencer/blob/cabd90b39a8f6534b874b2e953b37df7c0834a67/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L120)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

So why do we need this object (`CentralSierraVersion`) at all if we convert it to string tuple?
You can define the sierra_version directly as `(String, String, String)`, and implement `From<SierraVersion> for (String, String, String)`
</blockquote></details>

can't impl From in this file due to rust orphan rule.
but I defined my own into_string_tuple function instead.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 172 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2921#-OFQmDV7-eWg09c5Upf9:-OFRzroPDmL9ThR_Xn_f:b9yoyo6) ([raw file](https://github.com/starkware-libs/sequencer/blob/f60e0d349d830f0ba70460fdc698d53c45c8734c/crates/starknet_api/src/executable_transaction.rs#L172)):*
> ```XML
>         (account_deployment_data, AccountDeploymentData),
>         (resource_bounds, ValidResourceBounds)
>     );
> ```

can't add blank lines here due to auto-formatting


<!-- Sent from Reviewable.io -->

2024-12-31 13:58 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2921)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2921#-OFM_otzB69nsDNpnGKV:-OFS-XJRBnMAVuTYLeao:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/cabd90b39a8f6534b874b2e953b37df7c0834a67/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L120)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can't impl From in this file due to rust orphan rule.
but I defined my own into_string_tuple function instead.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2025-01-01 07:31 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r2, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2921#-:-OFVle416LdQVfROyZDM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 11:21 UTC, dafnamatsry approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2921)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 11:51 UTC, merged