fix(blockifier): avoid negative consumed gas
starkware-libs/sequencer pull request #2922
Opened 2024-12-24 12:33 UTC by avivg-starkware

2024-12-24 12:33 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2922)
<!-- Reviewable:end -->

2024-12-24 12:33 UTC, avivg-starkware commented
* **#2922** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2922?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2922?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-29 12:40 UTC, noaov1 requested changes
> Reviewed 12 of 15 files at r1, 1 of 18 files at r4, 6 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 7 of 37 files reviewed, 5 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_1.json` line 122 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFHP9j5EilX8ELnzDkQ:-OFHP9j69c58IkVfITyU:b-wgw47h) ([raw file](https://github.com/starkware-libs/sequencer/blob/d75f7a60d81961ab9aa42de328ceef6afac92528/crates/blockifier/resources/versioned_constants_0_13_1.json#L122)):*
> ```JSON
>                 "syscall_base_gas_cost": 1,
>                 "step_gas_cost": 510,
>                 "entry_point_initial_budget": 0
> ```

Since you leave "entry_point_initial_budget" in the versioned constant, you can simply delete it here (and in all the relevant syscalls). 



_Code quote:_
```JSON
     "entry_point_initial_budget": 0
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OExBU-T721q-Szbkdcc:-OExBU-T721q-Szbkdcd:b32w12) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b7da166e59f49e0786b8e83795c38d596611a38/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L222)):*
> ```XML
>         caller_address: syscall_handler.storage_address,
>         call_type: CallType::Call,
>         // Question (AvivG): Should we refund initial budget to caller's remaining gas?
> ```

No



_Code quote:_
```XML
        // Question (AvivG): Should we refund initial budget to caller's remaining gas?
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 83 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFHQI0MBmQT9yyUQH9_:-OFHQI0N5OCURipFlVgp:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d75f7a60d81961ab9aa42de328ceef6afac92528/crates/blockifier/src/execution/entry_point_execution.rs#L83)):*
> ```XML
>     ) {
>         Ok(args) => args,
>         Err(PreExecutionError::OutOfGas) => {
> ```





_Suggestion:_
```XML
Err(PreExecutionError::OutOfGas) if context.versioned_constants().enable_reverts => {
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 418 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OEwVE_HC9Xl2TVtjMfy:-OEwVE_HC9Xl2TVtjMfz:b32w12) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b7da166e59f49e0786b8e83795c38d596611a38/crates/blockifier/src/execution/entry_point.rs#L418)):*
> ```XML
> 
>     let Some(constructor_selector) = compiled_class.constructor_selector() else {
>         // AvivG 10000 is removed here?
> ```

No



_Code quote:_
```XML
        // AvivG 10000 is removed here?
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 536 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OExBRM87hMsO5WOmVva:-OExBRM87hMsO5WOmVvb:b32w12) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b7da166e59f49e0786b8e83795c38d596611a38/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L536)):*
> ```XML
>         caller_address: syscall_handler.caller_address,
>         call_type: CallType::Delegate,
>         // Question (AvivG): Should we refund initial budget to caller's remaining gas?
> ```

No



_Code quote:_
```XML
        // Question (AvivG): Should we refund initial budget to caller's remaining gas?
```


<!-- Sent from Reviewable.io -->

2024-12-29 14:16 UTC, noaov1 requested changes
> Reviewed 1 of 18 files at r4, 2 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 10 of 37 files reviewed, 7 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 96 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFHkt9eAuU3d72jwezb:-OFHkt9eAuU3d72jwezc:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d75f7a60d81961ab9aa42de328ceef6afac92528/crates/blockifier/src/execution/entry_point_execution.rs#L96)):*
> ```XML
>             });
>         }
>         Err(err) => return Err(EntryPointExecutionError::from(err)),
> ```





_Suggestion:_
```XML
Err(err) => return Err(err?),
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 236 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFHl4wu8vnH958TmL-T:-OFHl4wu8vnH958TmL-U:bk3jeao) ([raw file](https://github.com/starkware-libs/sequencer/blob/d75f7a60d81961ab9aa42de328ceef6afac92528/crates/blockifier/src/execution/entry_point_execution.rs#L236)):*
> ```XML
>         return Err(PreExecutionError::OutOfGas);
>     }
>     let initial_gas = call.initial_gas - entry_point_initial_budget;
> ```

Can you please add an assert that it's a non-negative number?



_Code quote:_
```XML
    let initial_gas = call.initial_gas - entry_point_initial_budget;
```


<!-- Sent from Reviewable.io -->

2024-12-29 14:50 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 10 of 37 files reviewed, 5 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/resources/versioned_constants_0_13_1.json` line 122 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFHP9j5EilX8ELnzDkQ:-OFHtDZn7NWksMQBsUHf:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d75f7a60d81961ab9aa42de328ceef6afac92528/crates/blockifier/resources/versioned_constants_0_13_1.json#L122)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Since you leave "entry_point_initial_budget" in the versioned constant, you can simply delete it here (and in all the relevant syscalls).
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 236 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFHl4wu8vnH958TmL-T:-OFHrlQZ9UsfbY5nrW9u:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d75f7a60d81961ab9aa42de328ceef6afac92528/crates/blockifier/src/execution/entry_point_execution.rs#L236)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please add an assert that it's a non-negative number?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 96 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFHkt9eAuU3d72jwezb:-OFHtTWI2gRxLpTnGYEM:b3sgf49) ([raw file](https://github.com/starkware-libs/sequencer/blob/d75f7a60d81961ab9aa42de328ceef6afac92528/crates/blockifier/src/execution/entry_point_execution.rs#L96)):*
> ```XML
>             });
>         }
>         Err(err) => return Err(EntryPointExecutionError::from(err)),
> ```

done, with err.into()


<!-- Sent from Reviewable.io -->

2024-12-29 16:26 UTC, noaov1 reviewed
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 10 of 37 files reviewed, 6 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 64 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFIDFD9ERu6qY8o4zq0:-OFIDFDADUVth6KN_Iyn:b-n64emd) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdfc4930a097c3b1afacbe7db8e78dc719045b17/crates/blockifier/src/execution/entry_point_execution.rs#L64)):*
> ```XML
>     let tracked_resource =
>         *context.tracked_resource_stack.last().expect("Unexpected empty tracked resource.");
>     let enable_reverts = context.versioned_constants().enable_reverts;
> ```

Please define it below (where you use it).



_Code quote:_
```XML
let enable_reverts = context.versioned_constants().enable_reverts;
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 237 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFIDi1DBbIaqfB5phVH:-OFIDi1DBbIaqfB5phVI:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdfc4930a097c3b1afacbe7db8e78dc719045b17/crates/blockifier/src/execution/entry_point_execution.rs#L237)):*
> ```XML
>     }
>     let initial_gas = call.initial_gas - entry_point_initial_budget;
>     assert!(call.initial_gas >= entry_point_initial_budget, "initial_gas must be non-negative");
> ```





_Suggestion:_
```XML
  assert!(initial_gas >= 0 , "initial_gas must be non-negative");
```


<!-- Sent from Reviewable.io -->

2024-12-29 16:55 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 9 of 37 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 64 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFIDFD9ERu6qY8o4zq0:-OFIJFmg-WQ2tId4KThM:b45x3p8) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdfc4930a097c3b1afacbe7db8e78dc719045b17/crates/blockifier/src/execution/entry_point_execution.rs#L64)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please define it below (where you use it).
</blockquote></details>

as context is being passed to 'initialize_execution_context', it can't be accessed after the call
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 237 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFIDi1DBbIaqfB5phVH:-OFIIvuD2LhGqsIMdUku:bgzx3kv) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdfc4930a097c3b1afacbe7db8e78dc719045b17/crates/blockifier/src/execution/entry_point_execution.rs#L237)):*
> ```XML
>     }
>     let initial_gas = call.initial_gas - entry_point_initial_budget;
>     assert!(call.initial_gas >= entry_point_initial_budget, "initial_gas must be non-negative");
> ```

for that to work, see my change ,WDYT? 
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 83 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFHQI0MBmQT9yyUQH9_:-OFIEwaB74FzyL3b0j8Z:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d75f7a60d81961ab9aa42de328ceef6afac92528/crates/blockifier/src/execution/entry_point_execution.rs#L83)):*
> ```XML
>     ) {
>         Ok(args) => args,
>         Err(PreExecutionError::OutOfGas) => {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 21:23 UTC, noaov1 requested changes
> Reviewed 11 of 15 files at r2, 1 of 11 files at r3, 11 of 18 files at r4, 4 of 12 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: all files reviewed, 13 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 237 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFIDi1DBbIaqfB5phVH:-OFJBqh86IsMjA42-kWG:b-h6cxag) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdfc4930a097c3b1afacbe7db8e78dc719045b17/crates/blockifier/src/execution/entry_point_execution.rs#L237)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

for that to work, see my change ,WDYT?
</blockquote></details>

Alternative:



_Code snippet:_
```XML
let call_initial_gas = call.initial_gas.checked_sub(entry_point_initial_budget).expect("initial_gas must be non-negative.");
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 77 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJG69mCxK49beK5WL5:-OFJG69n1J-DTtq3igpR:b-dl5h0i) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L77)):*
> ```XML
>             // 'Out of gas'
>             retdata: retdata![felt!["0x4f7574206f6620676173"]],
>             gas_consumed: MAX_POSSIBLE_SIERRA_GAS - 5380,
> ```

New magic number?



_Code quote:_
```XML
gas_consumed: MAX_POSSIBLE_SIERRA_GAS - 5380,
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 65 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJ89h461Uwg4FAAoQv:-OFJ89h461Uwg4FAAoQw:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/entry_point_execution.rs#L65)):*
> ```XML
>         *context.tracked_resource_stack.last().expect("Unexpected empty tracked resource.");
>     let enable_reverts = context.versioned_constants().enable_reverts;
>     let entry_point_initial_budget = context.gas_costs().base.entry_point_initial_budget;
> ```





_Suggestion:_
```XML
    // Extract information from the context, as it will be passed as a mutable reference.
    let enable_reverts = context.versioned_constants().enable_reverts;
    let entry_point_initial_budget = context.gas_costs().base.entry_point_initial_budget;
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 232 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJ8zgaEfMmX89vpoFg:-OFJ8zgb7O27Dnrj-Nm2:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/entry_point_execution.rs#L232)):*
> ```XML
>         return Err(PreExecutionError::InvalidBuiltin(*builtin_name));
>     }
>     // Include the initial entry point budget in the initial gas calculation.
> ```





_Suggestion:_
```XML
// Pre-charge entry point's initial budget to ensure sufficient gas for executing a minimal entry point code.
// When redepositing is used, the entry point is aware of this pre-charge and adjusts the gas counter accordingly 
// if a smaller amount of gas is required.
```
___
*[`crates/blockifier/src/test_utils.rs` line 210 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJ7ro3Dstqro_MoV7M:-OFJ7ro3Dstqro_MoV7N:b-i6vi9q) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/test_utils.rs#L210)):*
> ```XML
>     .default_initial_gas_cost +
>     // Caller's initial budget is refunded for paying entry point's initial budget.
>     vesrioned_const.os_constants.gas_costs.base.entry_point_initial_budget;
> ```

WDYM?
I see that you use `default_initial_gas_cost` in some tests. Why did you had to subtract the `entry_point_initial_budget`?



_Code quote:_
```XML
    // Caller's initial budget is refunded for paying entry point's initial budget.
    vesrioned_const.os_constants.gas_costs.base.entry_point_initial_budget;
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 87 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJFmoT7WfwcmCQEEfB:-OFJFmoU31g-fZNs2QOw:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L87)):*
> ```XML
>                 felt!("0x454e545259504f494e545f4641494c4544")
>             ]),
>             gas_consumed: 110980,
> ```

?



_Code quote:_
```XML
gas_consumed: 110980,
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 28 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJE-j7BGpvjNqJeoC7:-OFJE-j7BGpvjNqJeoC8:b-cccu8m) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/native/entry_point_execution.rs#L28)):*
> ```XML
>     context: &mut EntryPointExecutionContext,
> ) -> EntryPointExecutionResult<CallInfo> {
>     let orig_call = call.clone();
> ```

Why is the clone needed?
Is it possible to use `syscall_handler.base.call` below?



_Code quote:_
```XML
let orig_call = call.clone();
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 63 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJD-zC7OxK2bzVAl-z:-OFJD-zC7OxK2bzVAl0-:bz7as5) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/native/entry_point_execution.rs#L63)):*
> ```XML
>     let stack_size_red_zone = 160 * 1024 * 1024;
>     let target_stack_size = stack_size_red_zone + 10 * 1024 * 1024;
>     // Include the initial entry point budget in the initial gas calculation.
> ```

See my suggestion above. 



_Code quote:_
```XML
    // Include the initial entry point budget in the initial gas calculation.
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJCsuS6tBUPkaQhnNZ:-OFJCsuS6tBUPkaQhnN_:b-a1blpb) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/native/entry_point_execution.rs#L69)):*
> ```XML
>         let current_tracked_resource = compiled_class
>             .casm()
>             .tracked_resource(&context.versioned_constants().min_sierra_version_for_sierra_gas);
> ```

If we are in native, you can be sure that the tracked resources is sierra gas.



_Code quote:_
```XML
        let current_tracked_resource = compiled_class
            .casm()
            .tracked_resource(&context.versioned_constants().min_sierra_version_for_sierra_gas);
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 83 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJDe0u7msG8cwuX_Xc:-OFJDe0u7msG8cwuX_Xd:b-uie97k) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/native/entry_point_execution.rs#L83)):*
> ```XML
>         });
>     }
>     let initial_gas = syscall_handler.base.call.initial_gas - entry_point_initial_budget;
> ```

Please use `sub_checked`. 



_Suggestion:_
```XML
    let call_initial_gas = syscall_handler.base.call.initial_gas - entry_point_initial_budget;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1668 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJHt8M8WTV-tI30QZc:-OFJHt8M8WTV-tI30QZd:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/transaction/t [...]

2024-12-30 09:54 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: all files reviewed, 11 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 210 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJ7ro3Dstqro_MoV7M:-OFLyYE8BWBxxGgTs-PU:bp8b7db) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/test_utils.rs#L210)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM?
I see that you use `default_initial_gas_cost` in some tests. Why did you had to subtract the `entry_point_initial_budget`?
</blockquote></details>

Sorry, changed wording, I meant to explain the addition. 
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 237 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFIDi1DBbIaqfB5phVH:-OFLpG5u65Z4CA1GzD2W:bdefh2o) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdfc4930a097c3b1afacbe7db8e78dc719045b17/crates/blockifier/src/execution/entry_point_execution.rs#L237)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Alternative:
</blockquote></details>

Thank you!! much cleaner :)
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 28 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJE-j7BGpvjNqJeoC7:-OFLsLAjAVyga5ImdNL1:bgntq5k) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/native/entry_point_execution.rs#L28)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is the clone needed?
Is it possible to use `syscall_handler.base.call` below?
</blockquote></details>

I did so because 'call' is mutable and passed before, but i see it is not passed as a mutable reference.  I changed so that a clone will be passed. WDYT? (I'm a bit confused- couldn't find here access to a '`syscall_handler`)
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 63 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJD-zC7OxK2bzVAl-z:-OFLwf8K2fkUUjJIRKis:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/native/entry_point_execution.rs#L63)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

See my suggestion above.
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJCsuS6tBUPkaQhnNZ:-OFLwjMa5Ct7IXAc0CgV:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/native/entry_point_execution.rs#L69)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

If we are in native, you can be sure that the tracked resources is sierra gas.
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 83 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJDe0u7msG8cwuX_Xc:-OFLwxbQ2e8Ws5OnQ1hp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/native/entry_point_execution.rs#L83)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please use `sub_checked`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1744 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJGpazECc3rO3hEe5-:-OFLxzZp4YhjLTMxo5iG:b-wvnv9f) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/transaction/account_transactions_test.rs#L1744)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

sorry, changed my wording. make more sense now? I wanted to explain the addition
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 65 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJ89h461Uwg4FAAoQv:-OFLp3JI0X0RYL7FvCXk:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/entry_point_execution.rs#L65)):*
> ```XML
>         *context.tracked_resource_stack.last().expect("Unexpected empty tracked resource.");
>     let enable_reverts = context.versioned_constants().enable_reverts;
>     let entry_point_initial_budget = context.gas_costs().base.entry_point_initial_budget;
> ```

Done
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1668 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJHt8M8WTV-tI30QZc:-OFLyP_424xHq2XinMuK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/transaction/transactions_test.rs#L1668)):*
> ```XML
>         CairoVersion::Cairo0 => GasAmount(0),
>         CairoVersion::Cairo1(_) => {
>             if tx_version == TransactionVersion::ZERO {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-30 14:40 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 36 of 37 files reviewed, 11 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 68 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFMiKxK4MWQD2JPsd7e:-OFMwzKg1DS_wjVhNAFa:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b875cc04058c08d4e6ea09c97d8888917eabdd65/crates/blockifier/src/execution/execution_utils.rs#L68)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 124 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFMdyae8AxEh6toU4ZN:-OFMxFj6AXWMq0u8cmk6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/610349f694cff2aea52469512c02c409762d5093/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L124)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 28 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJE-j7BGpvjNqJeoC7:-OFMz-jT4sigz2hS4Zn8:bqdgssd) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/native/entry_point_execution.rs#L28)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It is moved inside the syscall handler. See my comment below.
</blockquote></details>

I was looking at an older version, after rebasing I see. 
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 63 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJD-zC7OxK2bzVAl-z:-OFMzJ0W7PH50Q5OT4T9:bz7xuwz) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/native/entry_point_execution.rs#L63)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

I was looking at an older version, after rebasing I see.
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 72 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFMifXQB1gdgSspxTcV:-OFMzW341etX1zB1OTHX:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/610349f694cff2aea52469512c02c409762d5093/crates/blockifier/src/execution/native/entry_point_execution.rs#L72)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Will this work? (avoiding the clone)
</blockquote></details>

yes
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 232 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJ8zgaEfMmX89vpoFg:-OFN-P8q7WBCZjxXj7ZA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/execution/entry_point_execution.rs#L232)):*
> ```XML
>         return Err(PreExecutionError::InvalidBuiltin(*builtin_name));
>     }
>     // Include the initial entry point budget in the initial gas calculation.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-30 14:59 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 30 of 37 files reviewed, 10 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 234 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFMi6vM3XJHxuXoN8Fk:-OFN1k37DBrlmFSw8YVu:b-7zi8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/610349f694cff2aea52469512c02c409762d5093/crates/blockifier/src/execution/entry_point_execution.rs#L234)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining a variable
</blockquote></details>

WDYT?
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFMhuPe16DgQuFX0MFo:-OFN3Nyz-E28osoo34fK:b-7zi8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/610349f694cff2aea52469512c02c409762d5093/crates/blockifier/src/execution/native/entry_point_execution.rs#L67)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining a variable.
</blockquote></details>

WDYT?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1744 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFJGpazECc3rO3hEe5-:-OFN4353-ITJKcFyVvSW:bpp6stj) ([raw file](https://github.com/starkware-libs/sequencer/blob/c20be55bfbc56541ce350f0f1f09cb969c7a55f8/crates/blockifier/src/transaction/account_transactions_test.rs#L1744)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is the addition needed?
</blockquote></details>

not needed
___
*[`crates/blockifier/src/execution/errors.rs` line 53 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFMdoBS5qLxbSifpbQw:-OFN1z6SAG3GyKI9Prqh:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/610349f694cff2aea52469512c02c409762d5093/crates/blockifier/src/execution/errors.rs#L53)):*
> ```XML
>     #[error("Called builtins: {0:?} are unsupported in a Cairo0 contract")]
>     UnsupportedCairo0Builtin(HashSet<BuiltinName>),
>     #[error("Insufficient entry point initial gas, must be non-negative.")]
> ```

Done


<!-- Sent from Reviewable.io -->

2024-12-31 06:42 UTC, noaov1 approved these changes
> Reviewed 3 of 4 files at r10, 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 62 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFQRNXMAZ8pjYYE7hNq:-OFQRNXNBwlnqCX0TTXp:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0938578a9e0d28c42bbe9a13b4183f8f57f18667/crates/blockifier/src/execution/native/entry_point_execution.rs#L62)):*
> ```XML
>     let target_stack_size = stack_size_red_zone + 10 * 1024 * 1024;
> 
>     // Include the initial entry point budget in the initial gas calculation.
> ```





_Suggestion:_
```XML
    // Pre-charge entry point's initial budget to ensure sufficient gas for executing a minimal
    // entry point code. When redepositing is used, the entry point is aware of this pre-charge
    // and adjusts the gas counter accordingly if a smaller amount of gas is required.
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 64 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFQRne9BWMLji7RH0cs:-OFQRneABz-Eb1CMvs2y:b-51jhdd) ([raw file](https://github.com/starkware-libs/sequencer/blob/0938578a9e0d28c42bbe9a13b4183f8f57f18667/crates/blockifier/src/execution/native/entry_point_execution.rs#L64)):*
> ```XML
>     // Include the initial entry point budget in the initial gas calculation.
>     let initial_budget = syscall_handler.base.context.gas_costs().base.entry_point_initial_budget;
>     let call_initial_gas = match syscall_handler.base.call.initial_gas.checked_sub(initial_budget) {
> ```

Did you mean to use `ok_or`?



_Code quote:_
```XML
 let call_initial_gas = match syscall_handler.base.call.initial_gas.checked_sub(initial_budget) {
```


<!-- Sent from Reviewable.io -->

2024-12-31 07:01 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 36 of 37 files reviewed, 4 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 75 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFQVrOp66o3eMB1zDJB:-OFQVrOp66o3eMB1zDJC:bq0zeph) ([raw file](https://github.com/starkware-libs/sequencer/blob/0938578a9e0d28c42bbe9a13b4183f8f57f18667/crates/blockifier/src/execution/entry_point_execution.rs#L75)):*
> ```XML
>     } = initialize_execution_context(call, &compiled_class, state, context)?;
> 
>     let args = match prepare_call_arguments(
> ```

Why not catching in the `wrapper` func? Will save this code duplication


<!-- Sent from Reviewable.io -->

2024-12-31 08:58 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 64 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFQRne9BWMLji7RH0cs:-OFQvCBiAR3dsmrYL9Ao:brxryqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/0938578a9e0d28c42bbe9a13b4183f8f57f18667/crates/blockifier/src/execution/native/entry_point_execution.rs#L64)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Did you mean to use `ok_or`?
</blockquote></details>

yes, I confused the native's and the blockifier's 'entry_point_execution.rs' files. However here it's not as clean as in the blockifier as we are returning Ok(CallInfo{..}) and not an error
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 62 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFQRNXMAZ8pjYYE7hNq:-OFQvqBn-SX_BbSmM9hS:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/0938578a9e0d28c42bbe9a13b4183f8f57f18667/crates/blockifier/src/execution/native/entry_point_execution.rs#L62)):*
> ```XML
>     let target_stack_size = stack_size_red_zone + 10 * 1024 * 1024;
> 
>     // Include the initial entry point budget in the initial gas calculation.
> ```

Done


<!-- Sent from Reviewable.io -->

2024-12-31 09:23 UTC, Yoni-Starkware reviewed
> Reviewed 7 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 35 of 37 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-12-31 09:26 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 36 of 37 files reviewed, 2 unresolved discussions (waiting on @avivg-starkware)



<!-- Sent from Reviewable.io -->

2024-12-31 09:49 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 36 of 37 files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 75 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFQVrOp66o3eMB1zDJB:-OFR6iQ9AgGf1s9ZYpln:b-clw1k9) ([raw file](https://github.com/starkware-libs/sequencer/blob/0938578a9e0d28c42bbe9a13b4183f8f57f18667/crates/blockifier/src/execution/entry_point_execution.rs#L75)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not catching in the `wrapper` func? Will save this code duplication
</blockquote></details>

Here https://github.com/starkware-libs/sequencer/blob/855d985bc003962473afd49bfef7dfbdf9e7937e/crates/blockifier/src/execution/execution_utils.rs#L76


<!-- Sent from Reviewable.io -->

2024-12-31 12:02 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 34 of 37 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 75 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFQVrOp66o3eMB1zDJB:-OFRa1U459FWw_jf4tiM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0938578a9e0d28c42bbe9a13b4183f8f57f18667/crates/blockifier/src/execution/entry_point_execution.rs#L75)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Here https://github.com/starkware-libs/sequencer/blob/855d985bc003962473afd49bfef7dfbdf9e7937e/crates/blockifier/src/execution/execution_utils.rs#L76
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-31 12:11 UTC, noaov1 requested changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 81 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFRbocr6B438kYnwmdm:-OFRbocr6B438kYnwmdn:b-cp6uot) ([raw file](https://github.com/starkware-libs/sequencer/blob/558bd7f8abea74478ee1defa576ca7f34c3b5fd1/crates/blockifier/src/execution/native/entry_point_execution.rs#L81)):*
> ```XML
>             });
>         }
>     };
> ```

With the addition in the wrapper function you can also delete this code. 



_Code quote:_
```XML
    // Pre-charge entry point's initial budget to ensure sufficient gas for executing a minimal
    // entry point code. When redepositing is used, the entry point is aware of this pre-charge
    // and adjusts the gas counter accordingly if a smaller amount of gas is required.
    let initial_budget = syscall_handler.base.context.gas_costs().base.entry_point_initial_budget;
    let call_initial_gas = match syscall_handler.base.call.initial_gas.checked_sub(initial_budget) {
        Some(gas) => gas,
        None => {
            return Ok(CallInfo {
                call: syscall_handler.base.call,
                execution: CallExecution {
                    retdata: Retdata(vec![Felt::from_hex(OUT_OF_GAS_ERROR).unwrap()]),
                    failed: true,
                    gas_consumed: 0,
                    ..CallExecution::default()
                },
                tracked_resource: TrackedResource::SierraGas,
                ..CallInfo::default()
            });
        }
    };
```


<!-- Sent from Reviewable.io -->

2024-12-31 12:18 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 6 files at r11, 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 218 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFRdKQh0w1oOjVhDnKY:-OFRdKQh0w1oOjVhDnKZ:b-ttm8u) ([raw file](https://github.com/starkware-libs/sequencer/blob/558bd7f8abea74478ee1defa576ca7f34c3b5fd1/crates/blockifier/src/execution/entry_point_execution.rs#L218)):*
> ```XML
>     // Pre-charge entry point's initial budget to ensure sufficient gas for executing a minimal
>     // entry point code. When redepositing is used, the entry point is aware of this pre-charge
>     // and adjusts the gas counter accordingly if a smaller amount of gas is required.
> ```

Great documentation



_Code quote:_
```XML
    // Pre-charge entry point's initial budget to ensure sufficient gas for executing a minimal
    // entry point code. When redepositing is used, the entry point is aware of this pre-charge
    // and adjusts the gas counter accordingly if a smaller amount of gas is required.
```


<!-- Sent from Reviewable.io -->

2024-12-31 12:44 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 35 of 37 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 81 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-OFRbocr6B438kYnwmdm:-OFRjmlF5rUlTwS0_3jw:b-8rw7uf) ([raw file](https://github.com/starkware-libs/sequencer/blob/558bd7f8abea74478ee1defa576ca7f34c3b5fd1/crates/blockifier/src/execution/native/entry_point_execution.rs#L81)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

With the addition in the wrapper function you can also delete this code.
</blockquote></details>

Done. thanjks!


<!-- Sent from Reviewable.io -->

2024-12-31 12:59 UTC, Yoni-Starkware approved these changes
> Reviewed 8 of 15 files at r2, 1 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922)* status: 35 of 37 files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-12-31 13:42 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2922#-:-OFRx2tF-tY1N-ZdKxGp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)



<!-- Sent from Reviewable.io -->

2024-12-31 16:11 UTC, merged