Meship/test get compiled class
starkware-libs/sequencer pull request #2949
Opened 2024-12-25 12:05 UTC by meship-starkware

2024-12-25 12:06 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2949)
<!-- Reviewable:end -->

2024-12-30 20:03 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: 0 of 9 files reviewed, 2 unresolved discussions

___
*[`Cargo.lock` line 7708 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFO97jZ2oTJQvSfQWq2:-OFO97jZ2oTJQvSfQWq3:b-uc4cbi) ([raw file](https://github.com/starkware-libs/sequencer/blob/b647c99bbba6aaecae770bfba8da390f6b473412/Cargo.lock#L7708)):*
> ```TOML
>  "blockifier",
>  "indexmap 2.6.0",
>  "infra_utils",
> ```

No need will revert
___
*[`crates/papyrus_state_reader/Cargo.toml` line 30 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFO9JJ9B9LEUMXt54A1:-OFO9JJ9B9LEUMXt54A2:b-uc4cbi) ([raw file](https://github.com/starkware-libs/sequencer/blob/b647c99bbba6aaecae770bfba8da390f6b473412/crates/papyrus_state_reader/Cargo.toml#L30)):*
> ```TOML
> 
> [build-dependencies]
> infra_utils.workspace = true
> ```

No need will revert


<!-- Sent from Reviewable.io -->

2024-12-30 20:04 UTC, meship-starkware reviewed
> Reviewed 2 of 8 files at r3, 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: 5 of 9 files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-12-31 07:13 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 150 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFQYvI76j9ntiSP46SV:-OFQYvI8Cs-urJvCG10O:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L150)):*
> ```XML
>         assert!(run_cairo_native);
>     }
>     // We only cache the sierra is the contract is cairo1 and the run cairo native flag is on.
> ```





_Suggestion:_
```XML
// We only cache the sierra if the contract is cairo1 and the run cairo native flag is on.
```


<!-- Sent from Reviewable.io -->

2025-01-01 19:57 UTC, noaov1 requested changes
> Reviewed 2 of 8 files at r3, 5 of 5 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: all files reviewed, 15 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/papyrus_state_reader/Cargo.toml` line 9 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYFP7CEE5CWavWdWbU:-OFYFP7CEE5CWavWdWbV:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/Cargo.toml#L9)):*
> ```TOML
> 
> [features]
> cairo_native = ["blockifier/cairo_native"]
> ```





_Suggestion:_
```TOML
[features]
cairo_native = ["blockifier/cairo_native"]
testing = ["rstest"]
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 93 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYP-KO2li8CEA852PZ:-OFYP-KO2li8CEA852P_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L93)):*
> ```XML
>     contract: FeatureContract,
>     contract_manager_config: ContractClassManagerConfig,
> ) -> papyrus_storage::StorageResult<PapyrusReader> {
> ```





_Suggestion:_
```XML
fn build_papyrus_state_reader_and_declare_contract(
    class_hash: ClassHash,
    contract: FeatureContract,
    contract_manager_config: ContractClassManagerConfig,
) {
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 103 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYPahTEnwPKl241mgz:-OFYPahTEnwPKl241mh-:bhjqkge) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L103)):*
> ```XML
>             let thin_state_diff = ThinStateDiff {
>                 declared_classes: IndexMap::from([(class_hash, test_compiled_class_hash)]),
>                 nonces: IndexMap::from([(contract.get_instance_address(1), Nonce(1.into()))]),
> ```

Why is it needed?



_Code quote:_
```XML
                nonces: IndexMap::from([(contract.get_instance_address(1), Nonce(1.into()))]),
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 138 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYFhKwDUo6ULNZbGVM:-OFYFhKwDUo6ULNZbGVN:b-ipe3ol) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L138)):*
> ```XML
> #[case(false, false)]
> #[cfg_attr(feature = "cairo_native", case(true, false))]
> #[cfg_attr(feature = "cairo_native", case(true, true))]
> ```

Name the cases?



_Code quote:_
```XML
#[case(false, false)]
#[cfg_attr(feature = "cairo_native", case(true, false))]
#[cfg_attr(feature = "cairo_native", case(true, true))]
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 145 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYOjt3CKiwUSFwWCYa:-OFYOjt3CKiwUSFwWCYb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L145)):*
> ```XML
>     #[case] run_cairo_native: bool,
>     #[case] wait_on_native_compilation: bool,
> ) -> papyrus_storage::StorageResult<()> {
> ```





_Suggestion:_
```XML
fn test_get_compiled_class(
    #[values(CairoVersion::Cairo0, CairoVersion::Cairo1(RunnableCairo1::Casm))]
    cairo_version: CairoVersion,
    #[values(true, false)] is_cached: bool,
    #[case] run_cairo_native: bool,
    #[case] wait_on_native_compilation: bool,
){
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 146 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYK69J86KyfTKdxmqb:-OFYK69K7nJ4jFnanuGA:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L146)):*
> ```XML
>     #[case] wait_on_native_compilation: bool,
> ) -> papyrus_storage::StorageResult<()> {
>     // sanity check
> ```





_Suggestion:_
```XML
// Sanity check.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 149 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYKmJn8nPFgo5IWHIj:-OFYKmJn8nPFgo5IWHIk:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L149)):*
> ```XML
>     if wait_on_native_compilation {
>         assert!(run_cairo_native);
>     }
> ```





_Suggestion:_
```XML
    if !run_cairo_native {
        assert!(!wait_on_native_compilation);
    }
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 150 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYIUGA1LiaE94ZUX-8:-OFYIUGA1LiaE94ZUX-9:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L150)):*
> ```XML
>         assert!(run_cairo_native);
>     }
>     // We only cache the sierra is the contract is cairo1 and the run cairo native flag is on.
> ```





_Suggestion:_
```XML
    // We store the sierra with the casm only when the casm is cairo1 and the native flag is enabled.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 166 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYJD2j2bV6ZQDp8u2X:-OFYJD2j2bV6ZQDp8u2Y:bqug1n5) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L166)):*
> ```XML
>         contract_manager_config,
>     )?;
> ```

What about the case where the native is cached?
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 168 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYHLRP6A_p7vF6nhDt:-OFYHLRQBg5k7knaS-TQ:beng8vm) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L168)):*
> ```XML
> 
>     if is_cached {
>         // Here we are testing the flow that the classes are already in the cache.
> ```

Why is it interesting? You can assume that `get_cached_casm` returns a cached casm (it does not matter if it was cached before)



_Suggestion:_
```XML
        // Simulate the scenario where the classes are already in the cache.
        // Create a cached casm and store it in the cache.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 188 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYMgWM6nKpCYXe0j5c:-OFYMgWM6nKpCYXe0j5d:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L188)):*
> ```XML
>             "When compiling cairo1 contract with the wait_on_native_compilation flag we expect to \
>              get the native class."
>         );
> ```





_Suggestion:_
```XML
    if cached_with_sierra {
         // TODO: Test that a compilation request was sent.
        if wait_on_native_compilation {
            #[cfg(feature = "cairo_native")]
            assert_matches!(
                compiled_class,
                RunnableCompiledClass::V1Native(_),
                "We should have waited to the native class."
            );
        }
        else {
             assert_matches!(
                compiled_class,
                RunnableCompiledClass::V1(_)
            );
            
        }
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 189 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYNrTYAU0w9Re1ky5F:-OFYNrTYAU0w9Re1ky [...]

2025-01-02 08:16 UTC, avi-starkware commented
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 163 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFa4d2S03XztWxr6571:-OFa4d2S03XztWxr6572:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc6f005a3dfe5a5667808ba75883cd4db0de8a3b/crates/papyrus_state_reader/src/papyrus_state_test.rs#L163)):*
> ```XML
>     let cached_with_sierra = run_cairo_native && matches!(cairo_version, CairoVersion::Cairo1(_));
>     // We don't need a native contract because we only use the contract to get the casm amd sierra
>     // classes.
> ```





_Suggestion:_
```XML
    // We don't need a native contract because we only use the contract to get the casm and sierra
    // classes.
```


<!-- Sent from Reviewable.io -->

2025-01-02 08:35 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: 6 of 9 files reviewed, 10 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 103 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYPahTEnwPKl241mgz:-OF_kqt91w-CNND9ywWv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L103)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 166 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYJD2j2bV6ZQDp8u2X:-OF_q6k-Bs_DpV4RK2I6:bv9gbzk) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L166)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What about the case where the native is cached?
</blockquote></details>

I will add a different test for it is too different from the other cases 
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 168 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYHLRP6A_p7vF6nhDt:-OFa8P8WDs1fuXu-qj4S:bqcsuy5) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L168)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it interesting? You can assume that `get_cached_casm` returns a cached casm (it does not matter if it was cached before)
</blockquote></details>

The flow would be slightly different if they had been cached before, but you are right. It is not different enough to justify a test case  
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 189 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYNrTYAU0w9Re1ky5F:-OF_nU9112gM1-c1Rrk6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L189)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We should consider adding an assert that the native flag is off when the native feature is off.
</blockquote></details>

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 204 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYOofU-CyWX7VNC9rG:-OF_hu6eC28B6EpnNpJc:b1f7eyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L204)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not needed. It should be tested when testing `get_cached_casm`.
</blockquote></details>

I disagree we cache the casm in this function. I want to see that we did not cache the wrong thing in some cases. that is the reason I only check the type and, not the contracts  
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 93 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYP-KO2li8CEA852PZ:-OF_kno6CwJse_wnI3cY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L93)):*
> ```XML
>     contract: FeatureContract,
>     contract_manager_config: ContractClassManagerConfig,
> ) -> papyrus_storage::StorageResult<PapyrusReader> {
> ```

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 145 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYOjt3CKiwUSFwWCYa:-OF_kscL-PF4z5lBcGT2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L145)):*
> ```XML
>     #[case] run_cairo_native: bool,
>     #[case] wait_on_native_compilation: bool,
> ) -> papyrus_storage::StorageResult<()> {
> ```

Done.
___
*[`crates/papyrus_state_reader/Cargo.toml` line 9 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYFP7CEE5CWavWdWbU:-OF_qg1qE1SQMBj62Dr8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/Cargo.toml#L9)):*
> ```TOML
> 
> [features]
> cairo_native = ["blockifier/cairo_native"]
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-02 08:44 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: 6 of 9 files reviewed, 11 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 163 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFa4d2S03XztWxr6571:-OFaB1uq7b0QciKyQHu6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc6f005a3dfe5a5667808ba75883cd4db0de8a3b/crates/papyrus_state_reader/src/papyrus_state_test.rs#L163)):*
> ```XML
>     let cached_with_sierra = run_cairo_native && matches!(cairo_version, CairoVersion::Cairo1(_));
>     // We don't need a native contract because we only use the contract to get the casm amd sierra
>     // classes.
> ```

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 232 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFa9r3Q3fdVGIPhDowW:-OFa9r3Q3fdVGIPhDowX:b7n2u3z) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc6f005a3dfe5a5667808ba75883cd4db0de8a3b/crates/papyrus_state_reader/src/papyrus_state_test.rs#L232)):*
> ```XML
> #[cfg(feature = "cairo_native")]
> #[test]
> fn test_get_compiled_class_when_native_is_cached() {
> ```

I can add it as a case in the test_compiled class, but it will result in more cases (I can no longer use values on the Cairo version), and the test would be a bit harder to read. On a positive note, if I merge this test, the compiled test will have a similar build to the function. I think that splitting it into two tests is more elegant, but I am not fixed on this 



_Code quote:_
```XML
fn test_get_compiled_class_when_native_is_cached() {
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 188 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYMgWM6nKpCYXe0j5c:-OFaAmJfDsA8Q-eP1ll5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L188)):*
> ```XML
>             "When compiling cairo1 contract with the wait_on_native_compilation flag we expect to \
>              get the native class."
>         );
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-02 08:45 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: 6 of 9 files reviewed, 11 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 166 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYJD2j2bV6ZQDp8u2X:-OFaBFbLDhK9CgJKSjeE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L166)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I will add a different test for it is too different from the other cases
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-08 12:01 UTC, noaov1 requested changes
> Reviewed 2 of 3 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: all files reviewed, 9 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 204 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYOofU-CyWX7VNC9rG:-OG4fW3-1SP49a5jfaER:b-rz4fcj) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L204)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I disagree we cache the casm in this function. I want to see that we did not cache the wrong thing in some cases. that is the reason I only check the type and, not the contracts
</blockquote></details>

We don't. We cache the casm in `get_cached_casm` and decide on the cached type in `get_compiled_class_inner.
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 232 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFa9r3Q3fdVGIPhDowW:-OG4lw-qDcp7ZrXovucQ:b-e8t1q7) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc6f005a3dfe5a5667808ba75883cd4db0de8a3b/crates/papyrus_state_reader/src/papyrus_state_test.rs#L232)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I can add it as a case in the test_compiled class, but it will result in more cases (I can no longer use values on the Cairo version), and the test would be a bit harder to read. On a positive note, if I merge this test, the compiled test will have a similar build to the function. I think that splitting it into two tests is more elegant, but I am not fixed on this
</blockquote></details>

I think that you can add it with a `native_exist` flag (and in this case, set the native in the cache and expect a ntive class as the returned value). But it can also be as a separate test. 
If you choose to separate, consider asserting no native in cache in the previous test. 
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 88 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4aI2Q1zkNmtLU2hII:-OG4aI2Q1zkNmtLU2hIJ:b-6lso2w) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/papyrus_state_reader/src/papyrus_state_test.rs#L88)):*
> ```XML
> 
> fn build_papyrus_state_reader_and_declare_contract(
>     class_hash: ClassHash,
> ```

Why is it needed?
Can you use `get_class_hash` of `FeatureContract`?



_Code quote:_
```XML
    class_hash: ClassHash,
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 177 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4b7mjE9H-IIWqFC8T:-OG4b7mjE9H-IIWqFC8U:b-a8k3rf) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/papyrus_state_reader/src/papyrus_state_test.rs#L177)):*
> ```XML
> 
>     if cached_with_sierra {
>         // TODO: Test that a compilation request was sent.
> ```

Next PR?



_Code quote:_
```XML
        // TODO: Test that a compilation request was sent.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 189 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4f8KJ95d8porxwrqf:-OG4f8KJ95d8porxwrqg:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/papyrus_state_reader/src/papyrus_state_test.rs#L189)):*
> ```XML
>                 compiled_class,
>                 RunnableCompiledClass::V1(_),
>                 "`get_compiled_class` should return Cario1 casm"
> ```





_Suggestion:_
```XML
                "We do not wait for native, return the cairo1 casm."
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 197 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4fOQgAmQDB2BrWap5:-OG4fOQgAmQDB2BrWap6:bhjqkge) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/papyrus_state_reader/src/papyrus_state_test.rs#L197)):*
> ```XML
>             RunnableCompiledClass::V0(_),
>             "`get_compiled_class` should return Cario0 casm"
>         );
> ```

Why is it needed?



_Code quote:_
```XML
    } else if run_cairo_native {
        assert_matches!(
            compiled_class,
            RunnableCompiledClass::V0(_),
            "`get_compiled_class` should return Cario0 casm"
        );
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 218 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4mI037F0pmapG1XhW:-OG4mI037F0pmapG1XhX:b-mo34hh) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/papyrus_state_reader/src/papyrus_state_test.rs#L218)):*
> ```XML
> fn test_get_compiled_class_when_native_is_cached() {
>     let ((storage_reader, _), _) = papyrus_storage::test_utils::get_test_storage();
>     let test_contract = FeatureContract::TestContract(CairoVersion::Cairo1(RunnableCairo1::Native));
> ```

Papyrus does not hold native classes. 



_Suggestion:_
```XML
    let test_contract = FeatureContract::TestContract(CairoVersion::Cairo1(RunnableCairo1::Cairo1));
```
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 154 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4H-p61FjP-bAEDIEs:-OG4H-p61FjP-bAEDIEt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/blockifier/src/state/contract_class_manager.rs#L154)):*
> ```XML
>     }
> 
>     #[cfg(all(feature = "cairo_native", feature = "testing"))]
> ```





_Suggestion:_
```XML
#[cfg(all(feature = "cairo_native", feature = "testing", test))]
```


<!-- Sent from Reviewable.io -->

2025-01-08 15:22 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: 4 of 9 files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 204 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OFYOofU-CyWX7VNC9rG:-OG5Vf_gCyoUt3AnBgtI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0f408e38d1750a490b4f7a504b9a56db8c003c9/crates/papyrus_state_reader/src/papyrus_state_test.rs#L204)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We don't. We cache the casm in `get_cached_casm` and decide on the cached type in `get_compiled_class_inner.
</blockquote></details>

Done.
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 177 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4b7mjE9H-IIWqFC8T:-OG5JXY36X57yXhwvsSv:banuoqd) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/papyrus_state_reader/src/papyrus_state_test.rs#L177)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Next PR?
</blockquote></details>

Yes let's do it in another PR. 
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 197 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4fOQgAmQDB2BrWap5:-OG5JtGN6Lyp7HnKvJxB:b-l9r6yl) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/papyrus_state_reader/src/papyrus_state_test.rs#L197)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

I wanted to ensure that if we run with Cairo native, the only case we do not save the Sierra is Cairo 0.
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 218 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4mI037F0pmapG1XhW:-OG5Untg8qHa4fRb4c5H:bmz5xh8) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/papyrus_state_reader/src/papyrus_state_test.rs#L218)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Papyrus does not hold native classes.
</blockquote></details>

We don't save the casm  in this case 
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 154 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4H-p61FjP-bAEDIEs:-OG5RjdzCHuRRtHTOHC4:bj73068) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/blockifier/src/state/contract_class_manager.rs#L154)):*
> ```XML
>     }
> 
>     #[cfg(all(feature = "cairo_native", feature = "testing"))]
> ```

No need becuse we only call it from another crate.
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 189 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4f8KJ95d8porxwrqf:-OG5KFQYCjvhNt5C0YyW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/papyrus_state_reader/src/papyrus_state_test.rs#L189)):*
> ```XML
>                 compiled_class,
>                 RunnableCompiledClass::V1(_),
>                 "`get_compiled_class` should return Cario1 casm"
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-12 10:11 UTC, noaov1 approved these changes
> Reviewed 4 of 5 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 197 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OG4fOQgAmQDB2BrWap5:-OGOyhGoA-husl2kVzMs:b-6fk795) ([raw file](https://github.com/starkware-libs/sequencer/blob/67dfcf874e33041011fa5f403d0fee4c088e8e2c/crates/papyrus_state_reader/src/papyrus_state_test.rs#L197)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I wanted to ensure that if we run with Cairo native, the only case we do not save the Sierra is Cairo 0.
</blockquote></details>

I see. I think that you can conclude it as `cached_with_sierra = run_cairo_native && matches!(cairo_version, CairoVersion::Cairo1(_));` and we know that `wait_on_native_compilation = false`. 
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 158 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OGOz4_o8TdgGcvBTAyV:-OGOz4_o8TdgGcvBTAyW:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1b3f114afaa59e97cae0c6bbb51f3cce5dc997a/crates/papyrus_state_reader/src/papyrus_state_test.rs#L158)):*
> ```XML
>     let cached_with_sierra = run_cairo_native && matches!(cairo_version, CairoVersion::Cairo1(_));
>     // We don't need a native contract because we only use the contract to get the casm and sierra
>     // classes.
> ```

WDYM?



_Code quote:_
```XML
    // We don't need a native contract because we only use the contract to get the casm and sierra
    // classes.
```
___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 168 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OGOzX1I3g3jUDNq74A6:-OGOzCgPAcljg9-UO05o:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1b3f114afaa59e97cae0c6bbb51f3cce5dc997a/crates/papyrus_state_reader/src/papyrus_state_test.rs#L168)):*
> ```XML
>     let papyrus_reader =
>         build_papyrus_state_reader_and_declare_contract(test_contract, contract_manager_config);
> ```





_Code snippet:_
```XML
assert!(papyrus_reader.contract_class_manager.get_native(test_class_hash).is_none();
```


<!-- Sent from Reviewable.io -->

2025-01-12 14:05 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 158 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OGOz4_o8TdgGcvBTAyV:-OGPnCF-ETeYaD6pg5ZX:b7y2ru1) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1b3f114afaa59e97cae0c6bbb51f3cce5dc997a/crates/papyrus_state_reader/src/papyrus_state_test.rs#L158)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

Adding native here won't work, and there is no need because the contract is just for getting the casm and Sierra, and it does not care for the runnable version. 


<!-- Sent from Reviewable.io -->

2025-01-12 14:14 UTC, meship-starkware reviewed
> Dismissed @avi-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 158 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OGPqmmd6KjAAOlysmZ3:-OGPqmmd6KjAAOlysmZ4:bxkb9pn) ([raw file](https://github.com/starkware-libs/sequencer/blob/35eb9b72a2a0b333c7bb9bccd45513e93040789b/crates/papyrus_state_reader/src/papyrus_state_test.rs#L158)):*
> ```XML
>     let cached_with_sierra = run_cairo_native && matches!(cairo_version, CairoVersion::Cairo1(_));
>     // We use the test contract only to extract the casm and sierra so the runnable version dose not
>     // matter.
> ```

The main idea of this comment is to make sure that when someone looks for tests to add native to, he won't unnecessarily add native to this test 



_Code quote:_
```XML
    // We use the test contract only to extract the casm and sierra so the runnable version dose not
    // matter.
```


<!-- Sent from Reviewable.io -->

2025-01-12 14:45 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state_test.rs` line 158 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-OGPqmmd6KjAAOlysmZ3:-OGPyRo0CgsAc0vI33nz:b-d5dtfk) ([raw file](https://github.com/starkware-libs/sequencer/blob/35eb9b72a2a0b333c7bb9bccd45513e93040789b/crates/papyrus_state_reader/src/papyrus_state_test.rs#L158)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

The main idea of this comment is to make sure that when someone looks for tests to add native to, he won't unnecessarily add native to this test
</blockquote></details>

I think that you can remove it given the test name. 


<!-- Sent from Reviewable.io -->

2025-01-12 16:11 UTC, meship-starkware reviewed
> Reviewed 2 of 5 files at r4, 4 of 5 files at r10, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)



<!-- Sent from Reviewable.io -->

2025-01-12 16:29 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2949#-:-OGQLJv97rIWlg96OORA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)



<!-- Sent from Reviewable.io -->

2025-01-12 17:41 UTC, merged