chore(starknet_sequencer_node): fix the conditional print on config tests
starkware-libs/sequencer pull request #2971
Opened 2024-12-25 17:39 UTC by ArniStarkware

2024-12-30 19:51 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2971)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_api/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO5GaaE0t-wk4Q1jBN:-OFO5GaaE0t-wk4Q1jBO:b9mobi8) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/Cargo.toml#L13)):*
> ```TOML
> 
> [dependencies]
> assert-json-diff.workspace = true
> ```

IIUC:
The added macro is part of  the`test_utils` module, which is compiled as part of the `testing` feature.
If so, then please add it to the feature dependency -- check out the syntax for that, it requires defining this as `optional`.



_Code quote:_
```TOML
assert-json-diff.workspace = true
```
___
*[`crates/starknet_api/src/test_utils/assert_json_eq.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO65FcApGnlXo-DI2a:-OFO65FcApGnlXo-DI2b:b-nszkh6) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/src/test_utils/assert_json_eq.rs#L14)):*
> ```XML
> {
>     assert_json_matches_no_panic(lhs, rhs, Config::new(CompareMode::Strict))
> }
> ```

Is this indirection needed? Can we simply call the `no_panic(lhs,rhs,config)` directly?
If not, does this function need to be public?



_Code quote:_
```XML
/// Compares two JSON values for an exact match without panicking.
/// See [`assert_json_matches_no_panic`]
pub fn assert_json_exact_matches_no_panic<Lhs, Rhs>(lhs: &Lhs, rhs: &Rhs) -> Result<(), String>
where
    Lhs: Serialize,
    Rhs: Serialize,
{
    assert_json_matches_no_panic(lhs, rhs, Config::new(CompareMode::Strict))
}
```
___
*[`crates/starknet_api/src/test_utils/assert_json_eq.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO6d3S02PwOKyOoGoR:-OFO6d3TDM5BKV7KGYPQ:b-ji7d7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/src/test_utils/assert_json_eq.rs#L37)):*
> ```XML
>         }
>     }};
> }
> ```

Could you add inline comments explaining what's happening here?
Why are there to calls to the ` $crate::test_utils::assert_json_exact_matches_no_panic(&$lhs, &$rhs)`?



_Code quote:_
```XML
#[macro_export]
/// Compare two JSON values for an exact match.
///
/// Extends the functionality of [`assert_json_diff::assert_json_eq`] by also adding a customizable
/// error message print.
macro_rules! assert_json_eq {
    ($lhs:expr, $rhs:expr, $error_message:expr $(,)?) => {{
        if let Err(error) =
            $crate::test_utils::assert_json_eq::assert_json_exact_matches_no_panic(&$lhs, &$rhs)
        {
            let printed_error = format!("\n\n{}\n{}\n\n", $error_message, error);
            panic!("{}", printed_error);
        }
    }};

    ($lhs:expr, $rhs:expr $(,)?) => {{
        if let Err(error) = $crate::test_utils::assert_json_exact_matches_no_panic(&$lhs, &$rhs) {
            let printed_error = format!("\n\n{}\n\n", error);
            panic!("{}", printed_error);
        }
    }};
}
```


<!-- Sent from Reviewable.io -->

2024-12-30 19:52 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2971)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/test_utils.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO71fyBLyqqfL7hu-E:-OFO71fyBLyqqfL7hu-F:b-276yec) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/src/test_utils.rs#L26)):*
> ```XML
> use crate::transaction::{Transaction, TransactionHash};
> 
> pub mod assert_json_eq;
> ```

Maybe `json_utils`?



_Code quote:_
```XML
pub mod assert_json_eq;
```


<!-- Sent from Reviewable.io -->

2024-12-31 09:23 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2971)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_api/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO5GaaE0t-wk4Q1jBN:-OFR-kMc6-idPJM0t0O7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/Cargo.toml#L13)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

IIUC:
The added macro is part of  the`test_utils` module, which is compiled as part of the `testing` feature.
If so, then please add it to the feature dependency -- check out the syntax for that, it requires defining this as `optional`.
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/test_utils.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO71fyBLyqqfL7hu-E:-OFQy0fR9z0iZdPDWKgE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/src/test_utils.rs#L26)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Maybe `json_utils`?
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/test_utils/assert_json_eq.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO65FcApGnlXo-DI2a:-OFQgd4B9ziMIHo8wnme:b-sohnk9) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/src/test_utils/assert_json_eq.rs#L14)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this indirection needed? Can we simply call the `no_panic(lhs,rhs,config)` directly?
If not, does this function need to be public?
</blockquote></details>

Yes and yes.
Why not call `assert_json_matches_no_panic` directly? we need to also import `assert_json_diff::Config` into the code where the macro is called from - and thus it needs to be included in the `.toml`. Hiding it under the indirection makes it so the toml of the calling code does not need to import `assert-json-diff`.

Why must the function be public? For the macro to run in the calling file, it needs access to this function, `assert_json_exact_matches_no_panic`.
___
*[`crates/starknet_api/src/test_utils/assert_json_eq.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO6d3S02PwOKyOoGoR:-OFQxJOO-2iTNUKT_zkE:b3s27o8) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/src/test_utils/assert_json_eq.rs#L37)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could you add inline comments explaining what's happening here?
Why are there to calls to the ` $crate::test_utils::assert_json_exact_matches_no_panic(&$lhs, &$rhs)`?
</blockquote></details>

I improved the code (using the power of AI) for improved reliability.
Do you still think we need an inline explanation? I find the new code more readable.


<!-- Sent from Reviewable.io -->

2024-12-31 11:15 UTC, Itay-Tsabary-Starkware requested changes
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2971)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/test_utils/assert_json_eq.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO65FcApGnlXo-DI2a:-OFROnrh-gIriK3BeEij:b-vk4745) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/src/test_utils/assert_json_eq.rs#L14)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Yes and yes.
Why not call `assert_json_matches_no_panic` directly? we need to also import `assert_json_diff::Config` into the code where the macro is called from - and thus it needs to be included in the `.toml`. Hiding it under the indirection makes it so the toml of the calling code does not need to import `assert-json-diff`.

Why must the function be public? For the macro to run in the calling file, it needs access to this function, `assert_json_exact_matches_no_panic`.
</blockquote></details>

There is some importing implicitness here that I'd rather avoid.

Importing `assert_json_eq` a crate essentially creates a dependency of `starknet_api/test_utils/json_utils`, which suffices import-wise for `$crate::test_utils::json_utils::assert_json_exact_matches_no_panic`.

If we're going for implicitness then the macro might as well call `assert_json_diff::assert_json_matches_no_panic(lhs,rhs,assert_json_diff::Config(...))` -- the inclusion of `assert_json_diff` is as implicit as of `assert_json_exact_matches_no_panic`, without the indirection.

Does this make sense? WDYT?
___
*[`crates/starknet_api/src/test_utils/assert_json_eq.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO6d3S02PwOKyOoGoR:-OFROQL19Q_LE02kzzuS:b9sjkf1) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/src/test_utils/assert_json_eq.rs#L37)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I improved the code (using the power of AI) for improved reliability.
Do you still think we need an inline explanation? I find the new code more readable.
</blockquote></details>

Yes please.
For instance, what does `($lhs:expr, $rhs:expr, $error_message:expr $(,)?)` mean?

Also there are two `$crate::test_utils::assert_json_eq::assert_json_exact_matches_no_panic(&$lhs, &$rhs)` calls, which I find confusing.
___
*[`crates/starknet_api/Cargo.toml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFRNPBz5IRhOmgf3OCV:-OFRNPBz5IRhOmgf3OCW:b7u6h9m) ([raw file](https://github.com/starkware-libs/sequencer/blob/cce781d322fa33d0037f6a2944e991c08fe8acd6/crates/starknet_api/Cargo.toml#L10)):*
> ```TOML
> 
> [features]
> testing = ["infra_utils", "dep:assert-json-diff"]
> ```

What is this prefix?



_Code quote:_
```TOML
dep:
```


<!-- Sent from Reviewable.io -->

2024-12-31 14:32 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2971)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_api/Cargo.toml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFRNPBz5IRhOmgf3OCV:-OFRUc470yGrtB8soBh-:bht5s8c) ([raw file](https://github.com/starkware-libs/sequencer/blob/cce781d322fa33d0037f6a2944e991c08fe8acd6/crates/starknet_api/Cargo.toml#L10)):*
In another thread, you requested:
> If so, then please add it to the feature dependency -- check out the syntax for that, it requires defining this as `optional`.

I now understand I did not understand what you meant. I asked ChatGPT and this is what it said was the syntax for that...
___
*[`crates/starknet_api/src/test_utils/assert_json_eq.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO65FcApGnlXo-DI2a:-OFS6oqh8NJXwABDJ4Vq:b-6f9axq) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/src/test_utils/assert_json_eq.rs#L14)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

There is some importing implicitness here that I'd rather avoid.

Importing `assert_json_eq` a crate essentially creates a dependency of `starknet_api/test_utils/json_utils`, which suffices import-wise for `$crate::test_utils::json_utils::assert_json_exact_matches_no_panic`.

If we're going for implicitness then the macro might as well call `assert_json_diff::assert_json_matches_no_panic(lhs,rhs,assert_json_diff::Config(...))` -- the inclusion of `assert_json_diff` is as implicit as of `assert_json_exact_matches_no_panic`, without the indirection.

Does this make sense? WDYT?
</blockquote></details>

Now simplified as a function.
___
*[`crates/starknet_api/src/test_utils/assert_json_eq.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFO6d3S02PwOKyOoGoR:-OFRTjP4Bu6LcLLD_Olm:b-w9kr6s) ([raw file](https://github.com/starkware-libs/sequencer/blob/084a448b6611ceccb73a6abfb328368b701ad9d2/crates/starknet_api/src/test_utils/assert_json_eq.rs#L37)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Yes please.
For instance, what does `($lhs:expr, $rhs:expr, $error_message:expr $(,)?)` mean?

Also there are two `$crate::test_utils::assert_json_eq::assert_json_exact_matches_no_panic(&$lhs, &$rhs)` calls, which I find confusing.
</blockquote></details>

Now a simplified function.


<!-- Sent from Reviewable.io -->

2025-01-01 07:52 UTC, ArniStarkware commented
*[`crates/starknet_api/Cargo.toml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFRNPBz5IRhOmgf3OCV:-OFSSIwQ93xtShAz4wws:bco46jm) ([raw file](https://github.com/starkware-libs/sequencer/blob/cce781d322fa33d0037f6a2944e991c08fe8acd6/crates/starknet_api/Cargo.toml#L10)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

In another thread, you requested:
> If so, then please add it to the feature dependency -- check out the syntax for that, it requires defining this as `optional`.

I now understand I did not understand what you meant. I asked ChatGPT and this is what it said was the syntax for that...
</blockquote></details>

See the explanation from [claude](https://claude.ai/chat/):

The `dep:` prefix in Rust's feature syntax is a relatively recent addition (stabilized in Rust 1.60) that stands for "dependency." It provides explicit syntax for enabling optional dependencies.

Here's what it does specifically:

1. Without `dep:` prefix:
```toml
[features]
testing = ["assert-json-diff"]
```
This older syntax is ambiguous - "assert-json-diff" could refer to either:
- A feature named "assert-json-diff" in some dependency
- An optional dependency named "assert-json-diff"

2. With `dep:` prefix:
```toml
[features]
testing = ["dep:assert-json-diff"]
```
This explicitly tells Cargo that "assert-json-diff" is an optional dependency that should be enabled when the "testing" feature is active.

The dependency itself would be declared in your `Cargo.toml` like this:
```toml
[dependencies]
assert-json-diff = { version = "2.0", optional = true }
```

The `dep:` prefix helps avoid naming conflicts and makes the intent clearer. For example, if you had both a feature and an optional dependency with the same name, the `dep:` prefix lets you specifically refer to the dependency.

This is part of Rust's larger effort to make feature resolution more explicit and less ambiguous.


<!-- Sent from Reviewable.io -->

2025-01-01 07:54 UTC, ArniStarkware commented
*[`crates/starknet_api/Cargo.toml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFRNPBz5IRhOmgf3OCV:-OFVqzYTBxNuanKQx7Ig:bkkwwx9) ([raw file](https://github.com/starkware-libs/sequencer/blob/cce781d322fa33d0037f6a2944e991c08fe8acd6/crates/starknet_api/Cargo.toml#L10)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

See the explanation from [claude](https://claude.ai/chat/):

The `dep:` prefix in Rust's feature syntax is a relatively recent addition (stabilized in Rust 1.60) that stands for "dependency." It provides explicit syntax for enabling optional dependencies.

Here's what it does specifically:

1. Without `dep:` prefix:
```toml
[features]
testing = ["assert-json-diff"]
```
This older syntax is ambiguous - "assert-json-diff" could refer to either:
- A feature named "assert-json-diff" in some dependency
- An optional dependency named "assert-json-diff"

2. With `dep:` prefix:
```toml
[features]
testing = ["dep:assert-json-diff"]
```
This explicitly tells Cargo that "assert-json-diff" is an optional dependency that should be enabled when the "testing" feature is active.

The dependency itself would be declared in your `Cargo.toml` like this:
```toml
[dependencies]
assert-json-diff = { version = "2.0", optional = true }
```

The `dep:` prefix helps avoid naming conflicts and makes the intent clearer. For example, if you had both a feature and an optional dependency with the same name, the `dep:` prefix lets you specifically refer to the dependency.

This is part of Rust's larger effort to make feature resolution more explicit and less ambiguous.
</blockquote></details>

or simply: https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies


<!-- Sent from Reviewable.io -->

2025-01-01 08:11 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-:-OFVul7M1qbKCl_QmymT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/starknet_api/Cargo.toml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2971#-OFRNPBz5IRhOmgf3OCV:-OFVttCp1FEoS97fvMie:b-7ldjr9) ([raw file](https://github.com/starkware-libs/sequencer/blob/cce781d322fa33d0037f6a2944e991c08fe8acd6/crates/starknet_api/Cargo.toml#L10)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

or simply: https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies
</blockquote></details>

Thanks.
We have only a few instances of that in the code base, i.e., we need to decide if we use this throught the repo or not for consistency.
I'll bring this up in the repo infra meeting, let's go with this synatx for the time being, and clear it later if we decide against it.


<!-- Sent from Reviewable.io -->

2025-01-01 08:35 UTC, merged