chore(papyrus_node): use printing util in papyrus node config test
starkware-libs/sequencer pull request #2972
Opened 2024-12-25 17:39 UTC by ArniStarkware

2024-12-25 17:40 UTC, ArniStarkware commented
*[`crates/papyrus_config/src/lib.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2972#-OEyttZaBg5ZpX2gIn8I:-OEyttZaBg5ZpX2gIn8J:b-btr4jq) ([raw file](https://github.com/starkware-libs/sequencer/blob/37c5fa4eaeadf8abf66d42820fa4bbf628d2f15d/crates/papyrus_config/src/lib.rs#L73)):*
> ```XML
> pub mod loading;
> pub mod presentation;
> #[cfg(test)]
> ```

I do not understand why I need to delete this for the import to work...



_Code quote:_
```XML
#[cfg(test)]
```


<!-- Sent from Reviewable.io -->

2024-12-26 10:01 UTC, ArniStarkware reviewed
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2972)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-30 19:54 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2972)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/papyrus_config/src/lib.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2972#-OEyttZaBg5ZpX2gIn8I:-OFO7LbvA_mprzH_hOF-:b54v5ve) ([raw file](https://github.com/starkware-libs/sequencer/blob/37c5fa4eaeadf8abf66d42820fa4bbf628d2f15d/crates/papyrus_config/src/lib.rs#L73)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I do not understand why I need to delete this for the import to work...
</blockquote></details>

I can take a deeper look if needed, please lmk
___
*[`crates/papyrus_node/src/config/config_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2972#-OFO7VzZ9CPdv47GhEiL:-OFO7VzZ9CPdv47GhEiM:bgdc151) ([raw file](https://github.com/starkware-libs/sequencer/blob/07bc96d1514e2721a5764d4bdb38e7d7018c0fed/crates/papyrus_node/src/config/config_test.rs#L164)):*
> ```XML
>             .purple()
>             .bold(),
>         "Diffs shown below."
> ```

Is there a reasonable way to unify this message with the `Sequencer` node one? Aside from the binary name they are the same.



_Code quote:_
```XML
    let error_message = format!(
        "{}\n{}",
        "Default config file doesn't match the default NodeConfig implementation. Please update \
         it using the papyrus_dump_config binary."
            .purple()
            .bold(),
        "Diffs shown below."
```


<!-- Sent from Reviewable.io -->

2024-12-31 09:21 UTC, ArniStarkware commented
*[`crates/papyrus_config/src/lib.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2972#-OEyttZaBg5ZpX2gIn8I:-OFR-uQ78rFLGVPmV-se:b-ll8cry) ([raw file](https://github.com/starkware-libs/sequencer/blob/37c5fa4eaeadf8abf66d42820fa4bbf628d2f15d/crates/papyrus_config/src/lib.rs#L73)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I can take a deeper look if needed, please lmk
</blockquote></details>

No longer relevant. test_utils is no longer a part of this lib.


<!-- Sent from Reviewable.io -->

2024-12-31 09:25 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2972)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_node/src/config/config_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2972#-OFO7VzZ9CPdv47GhEiL:-OFR0Mhh5hP88a4KSIg6:b-w1xawq) ([raw file](https://github.com/starkware-libs/sequencer/blob/07bc96d1514e2721a5764d4bdb38e7d7018c0fed/crates/papyrus_node/src/config/config_test.rs#L164)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is there a reasonable way to unify this message with the `Sequencer` node one? Aside from the binary name they are the same.
</blockquote></details>

Will do in another PR. For now, let us use the same infra.


<!-- Sent from Reviewable.io -->

2024-12-31 11:02 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2972)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/papyrus_node/src/config/config_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2972#-OFO7VzZ9CPdv47GhEiL:-OFRNGlo6B3j9RqHIu_v:b-n3iojl) ([raw file](https://github.com/starkware-libs/sequencer/blob/07bc96d1514e2721a5764d4bdb38e7d7018c0fed/crates/papyrus_node/src/config/config_test.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Will do in another PR. For now, let us use the same infra.
</blockquote></details>

Ack. Please add a todo?
Removed the block.


<!-- Sent from Reviewable.io -->

2024-12-31 14:32 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2972)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_node/src/config/config_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2972#-OFO7VzZ9CPdv47GhEiL:-OFRXFvtBfWl_D51eb37:b-elyc65) ([raw file](https://github.com/starkware-libs/sequencer/blob/07bc96d1514e2721a5764d4bdb38e7d7018c0fed/crates/papyrus_node/src/config/config_test.rs#L164)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ack. Please add a todo?
Removed the block.
</blockquote></details>

Added a TODO. The similarity is on the whole test level.


<!-- Sent from Reviewable.io -->

2025-01-01 08:11 UTC, Itay-Tsabary-Starkware approved these changes
> Reviewed 1 of 5 files at r2, 1 of 1 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2972)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2025-01-01 09:02 UTC, ArniStarkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2972)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2025-01-01 09:17 UTC, merged