fix(consensus): send init before starting work on proposal content
starkware-libs/sequencer pull request #2975
Opened 2024-12-26 07:51 UTC by guy-starkware

2024-12-26 07:51 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2975)
<!-- Reviewable:end -->

2024-12-26 07:51 UTC, guy-starkware commented
* **#2975** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2975?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2975?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-26 09:08 UTC, matan-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2975)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2975#-OF1Cyec2qEx28VuwfRh:-OF1Cyec2qEx28VuwfRi:b-37m05r) (no related file):*
I don't quite follow. You are changing the sending procedure, so that Init is in the receiver before the StreamHandler receives this to broadcast.

The error is on the inbound direction. Streaming should fill the first message before it sends the receiver to consensus.


<!-- Sent from Reviewable.io -->

2024-12-26 09:38 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2975)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2975#-OF1Cyec2qEx28VuwfRh:-OF1K7MECmo-k0VS-H00:braxj2i) (no related file):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't quite follow. You are changing the sending procedure, so that Init is in the receiver before the StreamHandler receives this to broadcast.

The error is on the inbound direction. Streaming should fill the first message before it sends the receiver to consensus.
</blockquote></details>

You are right. I didn't notice there's a race condition in the stream handler itself. I've flipped the order, now it will first send the message into the channel and only then send the channel. 


<!-- Sent from Reviewable.io -->

2024-12-29 17:41 UTC, matan-starkware approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2975)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 222 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2975#-OFIVNWXEJGGb-nTZcYn:-OFIVNWY-sHatQ4PPM55:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a40a2e8440da8205ca3564970f718b23ddb4405/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L222)):*
> ```XML
>                 // Send the receiver to the application.
>                 self.inbound_channel_sender.try_send(receiver).expect("Send should succeed");
>             }
> ```





_Suggestion:_
```XML
            // Send the receiver only once the first message has been sent.
            if message.message_id == 0 {
                // TODO(guyn): consider the expect in both cases.
                // If this is the first message, send the receiver to the application.
                let receiver = data.receiver.take().expect("Receiver should exist");
                // Send the receiver to the application.
                self.inbound_channel_sender.try_send(receiver).expect("Send should succeed");
            }
```


<!-- Sent from Reviewable.io -->

2024-12-29 20:41 UTC, guy-starkware reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2975)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 08:28 UTC, guy-starkware reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2975)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 08:48 UTC, merged