chore(papyrus_p2p_sync): receive queried and internal block simultaneously
starkware-libs/sequencer pull request #2985
Opened 2024-12-26 12:54 UTC by eitanm-starkware

2024-12-26 12:54 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2985)
<!-- Reviewable:end -->

2024-12-26 14:12 UTC, ShahakShama requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2985)* status: all files reviewed, 3 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2985#-OF29U33A8OIWQdwlEIY:-OF29U343myhaSzryOMA:b-r6mtoq) ([raw file](https://github.com/starkware-libs/sequencer/blob/af4a20eb54163b7928b3a69eb6ac8f440e7584e6/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L49)):*
> ```XML
>     const BLOCK_NUMBER_LIMIT: BlockNumberLimit;
> 
>     // Async functions in trait don't work well with argument references
> ```

Copy this comment to get_internal_block_at
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2985#-OF2IR25BJsHp8xU0mnl:-OF2IR25BJsHp8xU0mnm:bis8zym) ([raw file](https://github.com/starkware-libs/sequencer/blob/40f8eff2153de6b5205e6380257766959400ed4a/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L69)):*
> ```XML
>         internal_block_receiver: &'a mut Option<Receiver<(BlockNumber, SyncBlock)>>,
>         current_block_number: BlockNumber,
>     ) -> BoxFuture<'a, Option<Self::Output>> {
> ```

You can change the return type to just Self::Output, and panic if the stream finishes (the way it is in main)
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 191 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2985#-OF2Iq-GAmdqKEfr9uF1:-OF2Iq-GAmdqKEfr9uF2:bi5cebh) ([raw file](https://github.com/starkware-libs/sequencer/blob/40f8eff2153de6b5205e6380257766959400ed4a/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L191)):*
> ```XML
>                                 current_block_number = current_block_number.unchecked_next();
>                                 yield Ok(Box::<dyn BlockData>::from(Box::new(block)));
>                                 debug!("Network query ending at block {} for {:?} being ignored", end_block_number, Self::TYPE_DESCRIPTION);
> ```

add "due to internal block" at the end of the sentence


<!-- Sent from Reviewable.io -->

2024-12-26 14:39 UTC, eitanm-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2985)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2985#-OF2IR25BJsHp8xU0mnl:-OF2P5PY61E5_VB-cIRn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/40f8eff2153de6b5205e6380257766959400ed4a/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L69)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can change the return type to just Self::Output, and panic if the stream finishes (the way it is in main)
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 191 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2985#-OF2Iq-GAmdqKEfr9uF1:-OF2P66--tbMzzoD25TE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/40f8eff2153de6b5205e6380257766959400ed4a/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L191)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

add "due to internal block" at the end of the sentence
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 13:01 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2985#-:-OFHVLyg9Ak16xYxnxEA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)



<!-- Sent from Reviewable.io -->

2024-12-29 13:19 UTC, merged