feat(mempool_test_utils,starknet_integration_tests): prepare state diff for testing with funded but undeployed accounts
starkware-libs/sequencer pull request #2986
Opened 2024-12-26 13:11 UTC by yair-starkware

2024-12-26 13:11 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2986)
<!-- Reviewable:end -->

2024-12-26 13:11 UTC, yair-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2986?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2986** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2986?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2986?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2806** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2806?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#2807](https://github.com/starkware-libs/sequencer/pull/2807) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2807?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#2805** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2805?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2804** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2804?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2803** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2803?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2802** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2802?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2801** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2801?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2724** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2724?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-29 13:03 UTC, alonh5 requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2986)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-OFHVho54kstfUa7Rq-r:-OFHVho54kstfUa7Rq-s:b-kb3x4v) ([raw file](https://github.com/starkware-libs/sequencer/blob/d58ba8eec7e3627dc614003b7b729b1beb7a4c9e/crates/starknet_integration_tests/src/state_reader.rs#L412)):*
> ```XML
>     }
> 
>     // TODO(deploy_account_support): delete method once we have batcher with execution.
> ```

Can we delete this here and deploy accounts only with txs now that you have added support for that?



_Code quote:_
```XML
// TODO(deploy_account_support): delete method once we have batcher with execution.
```


<!-- Sent from Reviewable.io -->

2024-12-31 08:38 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2986)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-OFHVho54kstfUa7Rq-r:-OFQrQSyDYSkb14ZKzZl:b-9ix241) ([raw file](https://github.com/starkware-libs/sequencer/blob/d58ba8eec7e3627dc614003b7b729b1beb7a4c9e/crates/starknet_integration_tests/src/state_reader.rs#L412)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can we delete this here and deploy accounts only with txs now that you have added support for that?
</blockquote></details>

Isn't it used by the integration test as well?


<!-- Sent from Reviewable.io -->

2024-12-31 08:39 UTC, yair-starkware commented
*[`crates/starknet_integration_tests/src/state_reader.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-OFHVho54kstfUa7Rq-r:-OFQr_b2-m-EjcpkczIL:bta84ef) ([raw file](https://github.com/starkware-libs/sequencer/blob/d58ba8eec7e3627dc614003b7b729b1beb7a4c9e/crates/starknet_integration_tests/src/state_reader.rs#L412)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Isn't it used by the integration test as well?
</blockquote></details>

IMO this whole module shouldn't exist.
Needs to be part of the `MultiAccountTxGenerator`.


<!-- Sent from Reviewable.io -->

2025-01-01 11:05 UTC, alonh5 requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2986)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-OFHVho54kstfUa7Rq-r:-OFWX4cT-LYATrit_f20:b-qop83c) ([raw file](https://github.com/starkware-libs/sequencer/blob/d58ba8eec7e3627dc614003b7b729b1beb7a4c9e/crates/starknet_integration_tests/src/state_reader.rs#L412)):*
Yes you're right it's used in the integration test.

>Needs to be part of the `MultiAccountTxGenerator`
Do you think it's easy and we should do it now?
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 427 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-OFWXdjcByD6lg2_A339:-OFWXdjcByD6lg2_A33A:b-v086mg) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3da5877f0f5b6a82f0cc62279924e65dcf3c76f/crates/starknet_integration_tests/src/state_reader.rs#L427)):*
> ```XML
>     }
> 
>     // TODO(deploy_account_support): delete method once we have batcher with execution.
> ```

Here you can remove it right?



_Code quote:_
```XML
// TODO(deploy_account_support): delete method once we have batcher with execution.
```


<!-- Sent from Reviewable.io -->

2025-01-01 11:27 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2986)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-OFHVho54kstfUa7Rq-r:-OFWaGvLA-m3_j_cc_p_:b-mougqf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d58ba8eec7e3627dc614003b7b729b1beb7a4c9e/crates/starknet_integration_tests/src/state_reader.rs#L412)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yes you're right it's used in the integration test.

>Needs to be part of the `MultiAccountTxGenerator`
Do you think it's easy and we should do it now?
</blockquote></details>

I don't think it's that easy.
I think we should do it before adding more flows to the e2e tests.
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 427 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-OFWXdjcByD6lg2_A339:-OFWb3XA-rN8BuRm-JfW:b4m2fnu) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3da5877f0f5b6a82f0cc62279924e65dcf3c76f/crates/starknet_integration_tests/src/state_reader.rs#L427)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Here you can remove it right?
</blockquote></details>

The functions are still needed because we can't update the state with the transfer txs yet.
Also, I think it's a useful functionality for easy setups (instead of needing to fund, declare and deploy every contract in every test).
Removed the TODOs.


<!-- Sent from Reviewable.io -->

2025-01-01 13:28 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-:-OFX2TuNDVbWbo-N6Ter:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-OFHVho54kstfUa7Rq-r:-OFWynYGA0TxBiuqDQHK:b71fhz6) ([raw file](https://github.com/starkware-libs/sequencer/blob/d58ba8eec7e3627dc614003b7b729b1beb7a4c9e/crates/starknet_integration_tests/src/state_reader.rs#L412)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't think it's that easy.
I think we should do it before adding more flows to the e2e tests.
</blockquote></details>

Okay, can you add a TODO for it then?
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 427 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-OFWXdjcByD6lg2_A339:-OFWyiQD14OsCKHmUHz2:b-8wssox) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3da5877f0f5b6a82f0cc62279924e65dcf3c76f/crates/starknet_integration_tests/src/state_reader.rs#L427)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The functions are still needed because we can't update the state with the transfer txs yet.
Also, I think it's a useful functionality for easy setups (instead of needing to fund, declare and deploy every contract in every test).
Removed the TODOs.
</blockquote></details>

Yes I only meant remove the TODO here.


<!-- Sent from Reviewable.io -->

2025-01-02 09:59 UTC, alonh5 approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2986)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 11:32 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2986)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2986#-OFHVho54kstfUa7Rq-r:-OFamUHJED0koyWa8drI:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d58ba8eec7e3627dc614003b7b729b1beb7a4c9e/crates/starknet_integration_tests/src/state_reader.rs#L412)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Okay, can you add a TODO for it then?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2025-01-02 12:14 UTC, alonh5 approved these changes
> Reviewed 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2986)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 12:25 UTC, merged