feat(consensus): add central l1 handler transaction
starkware-libs/sequencer pull request #2988
Opened 2024-12-26 13:59 UTC by Yael-Starkware

2024-12-26 13:59 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2988)
<!-- Reviewable:end -->

2024-12-26 13:59 UTC, Yael-Starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2988?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2988** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2988?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2988?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2921** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2921?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2872** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2872?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2861** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2861?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2715** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2715?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-30 11:04 UTC, DvirYo-starkware requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2988)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2988#-OFMDhOv5UW6rd5Z3OgE:-OFMDhOwEJJl8FSbiuMG:b-q9ov7h):*
sequencing



_Code quote:_
```
consensus
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2988#-OFME6NvE0ilkvtLoJk2:-OFME6NvE0ilkvtLoJk3:b-dgsicv) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d97ab3934698280ce63f08741d8cf40bab2199/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L317)):*
> ```XML
>             }
>             Transaction::Account(AccountTransaction::Declare(declare_tx)) => {
>                 CentralTransaction::Declare(CentralDeclareTransaction::V3(declare_tx.into()))
> ```

why does the into was added here?



_Code quote:_
```XML
eclare_tx.into()
```


<!-- Sent from Reviewable.io -->

2024-12-30 11:36 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2988)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2988#-OFMDhOv5UW6rd5Z3OgE:-OFMLdfP3kWTbOCb6t8o:b-7rl0jd):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

sequencing
</blockquote></details>

done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2988#-OFME6NvE0ilkvtLoJk2:-OFMKmPy2aaJZrda6lMg:b-k6z4jm) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d97ab3934698280ce63f08741d8cf40bab2199/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L317)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

why does the into was added here?
</blockquote></details>

just replaced all match cases to use into() instead of from() for consistency


<!-- Sent from Reviewable.io -->

2024-12-30 11:56 UTC, DvirYo-starkware approved these changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2988)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2025-01-01 07:32 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2988#-:-OFVlws54L95Y95z9avR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 12:49 UTC, DvirYo-starkware approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2988)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 14:35 UTC, merged