fix(starknet_gateway): convert mempool errors to the correct gw error
starkware-libs/sequencer pull request #2995
Opened 2024-12-29 09:44 UTC by yair-starkware

2024-12-29 09:44 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2995)
<!-- Reviewable:end -->

2024-12-29 09:44 UTC, yair-starkware commented
* **#2995** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2995?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2995?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-29 11:22 UTC, yair-starkware commented
*[`crates/starknet_gateway/src/errors.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-OFH8MoJ4PpRzv01NbE8:-OFH8MoJ4PpRzv01NbE9:blxo97z) ([raw file](https://github.com/starkware-libs/sequencer/blob/41e11f01340f7b9daace1cc65b14c93357201b48/crates/starknet_gateway/src/errors.rs#L99)):*
> ```XML
>                     // mempool clients.
>                     unreachable!("Unexpected mempool error in gateway context: {}", mempool_error);
>                 }
> ```

@giladchase @ShahakShama 
Please approve that `P2pPropagatorClientError` & `TransactionNotFound` are not supposed to happen in any GW flow to your best knowledge.



_Code quote:_
```XML
                MempoolError::P2pPropagatorClientError { .. }
                | MempoolError::TransactionNotFound { .. } => {
                    // These errors are not expected to happen within the gateway, only from other
                    // mempool clients.
                    unreachable!("Unexpected mempool error in gateway context: {}", mempool_error);
                }
```


<!-- Sent from Reviewable.io -->

2024-12-29 13:29 UTC, alonh5 requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2995)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase, @ShahakShama, and @yair-starkware)

___
*[`crates/starknet_gateway/src/errors.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-OFHaFD78rQ8taN8ArZP:-OFHaFD8675GMN6NeMvW:btb7cw4) ([raw file](https://github.com/starkware-libs/sequencer/blob/41e11f01340f7b9daace1cc65b14c93357201b48/crates/starknet_gateway/src/errors.rs#L81)):*
> ```XML
> }
> 
> pub fn mempool_client_err_to_gw_spec_err(value: MempoolClientError) -> GatewaySpecError {
> ```

Can this be a `From` impl?


<!-- Sent from Reviewable.io -->

2024-12-29 13:40 UTC, yair-starkware commented
*[`crates/starknet_gateway/src/errors.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-OFHaFD78rQ8taN8ArZP:-OFHd5LU5S7ApqQ4wpVC:bhnz7eu) ([raw file](https://github.com/starkware-libs/sequencer/blob/41e11f01340f7b9daace1cc65b14c93357201b48/crates/starknet_gateway/src/errors.rs#L81)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can this be a `From` impl?
</blockquote></details>

No, because neither `MempoolClientError` nor `GatewaySpecError` are defined in our crate


<!-- Sent from Reviewable.io -->

2024-12-29 13:49 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-:-OFHfQ9L7_i_T_BPUQ5i:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @ShahakShama)

___
*[`crates/starknet_gateway/src/errors.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-OFH8MoJ4PpRzv01NbE8:-OFHeiL-0y48Tia47Rnk:b-47a9z2) ([raw file](https://github.com/starkware-libs/sequencer/blob/41e11f01340f7b9daace1cc65b14c93357201b48/crates/starknet_gateway/src/errors.rs#L99)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

@giladchase @ShahakShama 
Please approve that `P2pPropagatorClientError` & `TransactionNotFound` are not supposed to happen in any GW flow to your best knowledge.
</blockquote></details>

`TransactionNotFound` can't happen in the `add_tx` flow AFAICT. @ShahakShama Can you confirm for `P2pPropagatorClientError`?


<!-- Sent from Reviewable.io -->

2024-12-29 14:02 UTC, ShahakShama reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2995)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/starknet_gateway/src/errors.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-OFH8MoJ4PpRzv01NbE8:-OFHiHdg9lSz3_-gEAax:b-dephto) ([raw file](https://github.com/starkware-libs/sequencer/blob/41e11f01340f7b9daace1cc65b14c93357201b48/crates/starknet_gateway/src/errors.rs#L99)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

`TransactionNotFound` can't happen in the `add_tx` flow AFAICT. @ShahakShama Can you confirm for `P2pPropagatorClientError`?
</blockquote></details>

It can happen. I'll create a PR to change it so that it can't happen


<!-- Sent from Reviewable.io -->

2024-12-29 14:09 UTC, ShahakShama reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2995)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/starknet_gateway/src/errors.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-OFH8MoJ4PpRzv01NbE8:-OFHk0aV8bflc7bOk3GZ:bmqwf9w) ([raw file](https://github.com/starkware-libs/sequencer/blob/41e11f01340f7b9daace1cc65b14c93357201b48/crates/starknet_gateway/src/errors.rs#L99)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It can happen. I'll create a PR to change it so that it can't happen
</blockquote></details>

After #3001 is merged it can't happen


<!-- Sent from Reviewable.io -->

2024-12-30 09:31 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2995)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

___
*[`crates/starknet_gateway/src/errors.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-OFH8MoJ4PpRzv01NbE8:-OFLtpLq8ksmkoKgiBKe:b-7xvisu) ([raw file](https://github.com/starkware-libs/sequencer/blob/41e11f01340f7b9daace1cc65b14c93357201b48/crates/starknet_gateway/src/errors.rs#L99)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

After #3001 is merged it can't happen
</blockquote></details>

Converted the error to a warning


<!-- Sent from Reviewable.io -->

2024-12-30 09:31 UTC, yair-starkware commented
*[`crates/starknet_gateway/src/errors.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-OFH8MoJ4PpRzv01NbE8:-OFLu-3cAMP-zvtjzpE2:bpzwbc1) ([raw file](https://github.com/starkware-libs/sequencer/blob/41e11f01340f7b9daace1cc65b14c93357201b48/crates/starknet_gateway/src/errors.rs#L99)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Converted the error to a warning
</blockquote></details>

As we talked in slack


<!-- Sent from Reviewable.io -->

2024-12-30 11:04 UTC, alonh5 requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2995)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @yair-starkware)

___
*[`crates/starknet_gateway/src/errors.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-OFMBCbh6C8-Ox1C5xlT:-OFMBCbh6C8-Ox1C5xlU:b-dv4pyq) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ec86370c03fa73bd2df4f750873876800c849d1/crates/starknet_gateway/src/errors.rs#L81)):*
> ```XML
> }
> 
> pub fn mempool_client_result_to_gw_spec_result(
> ```

Add a short doc?


<!-- Sent from Reviewable.io -->

2024-12-31 12:32 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2995)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

___
*[`crates/starknet_gateway/src/errors.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2995#-OFMBCbh6C8-Ox1C5xlT:-OFRgyhlDDxVWJj0rN4e:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ec86370c03fa73bd2df4f750873876800c849d1/crates/starknet_gateway/src/errors.rs#L81)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add a short doc?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 10:33 UTC, alonh5 approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2995)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2025-01-01 10:55 UTC, merged