feat(starknet_batcher): fill in ThinStateDiff fields
starkware-libs/sequencer pull request #2997
Opened 2024-12-29 11:48 UTC by alonh5

2024-12-29 11:48 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/2997)
<!-- Reviewable:end -->

2024-12-29 11:52 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFHFMs-EQB9LQUEAh89:-OFHFMs-EQB9LQUEAh8A:b-ub1kq1) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e0f59dd2fd4e13e1de54ef706840221280a6ed9/crates/starknet_batcher/src/block_builder.rs#L95)):*
> ```XML
>     pub fn state_diff(&self) -> ThinStateDiff {
>         // TODO(Ayelet): Remove the clones.
>         let deployed_contracts = self.commitment_state_diff.address_to_class_hash.clone();
> ```

@yair-starkware said this map should be sorted by address before writing.



_Code quote:_
```XML
self.commitment_state_diff.address_to_class_hash.clone();
```
___
*[`crates/starknet_batcher/src/block_builder.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFHFXba45v-MzNN-Jhi:-OFHFXbbDYKIdM5hg9H4:bxqeqca) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e0f59dd2fd4e13e1de54ef706840221280a6ed9/crates/starknet_batcher/src/block_builder.rs#L97)):*
> ```XML
>         let deployed_contracts = self.commitment_state_diff.address_to_class_hash.clone();
>         let storage_diffs = self.commitment_state_diff.storage_updates.clone();
>         let declared_classes = self.commitment_state_diff.class_hash_to_compiled_class_hash.clone();
> ```

same, but sorted by class hash



_Code quote:_
```XML
self.commitment_state_diff.class_hash_to_compiled_class_hash.clone();
```


<!-- Sent from Reviewable.io -->

2024-12-29 13:38 UTC, yair-starkware commented
@ShahakShama please confirm that the p2p sync expects the data to be sorted


<!-- Sent from Reviewable.io -->

2024-12-29 13:40 UTC, ShahakShama reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @alonh5, @asmaastarkware, @dafnamatsry, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFHcYeo1VsKxV2mmLMx:-OFHd45I-q5c71fLepDL:ba3qzrr) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

@ShahakShama please confirm that the p2p sync expects the data to be sorted
</blockquote></details>

No. We've added special logic to handle non sorted data so you can send it not sorted.
I don't know how consensus expects it though. @matan-starkware @asmaastarkware ?

We did this because @Itay-Tsabary-Starkware can't guarantee the messages will be received sorted even if you send them sorted


<!-- Sent from Reviewable.io -->

2024-12-29 13:41 UTC, ShahakShama reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @alonh5, @asmaastarkware, @dafnamatsry, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFHcYeo1VsKxV2mmLMx:-OFHdQwU5BYq27aj5Ify:buvcl4m) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No. We've added special logic to handle non sorted data so you can send it not sorted.
I don't know how consensus expects it though. @matan-starkware @asmaastarkware ?

We did this because @Itay-Tsabary-Starkware can't guarantee the messages will be received sorted even if you send them sorted
</blockquote></details>

Note that we buffer non sorted data until we receive the missing hole so if you missed a block the pod will be out of memory


<!-- Sent from Reviewable.io -->

2024-12-29 13:48 UTC, yair-starkware commented
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Note that we buffer non sorted data until we receive the missing hole so if you missed a block the pod will be out of memory
</blockquote></details>

Thanks.
I still think we need to sort the data to calculate the commitments (and IIRC the storage also requires the data to be sorted).
@alonh5 


<!-- Sent from Reviewable.io -->

2024-12-29 14:49 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @asmaastarkware, @dafnamatsry, @Itay-Tsabary-Starkware, @matan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFHcYeo1VsKxV2mmLMx:-OFHg8whCqZLPV3NRTBl:bdqr9nf) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Thanks.
I still think we need to sort the data to calculate the commitments (and IIRC the storage also requires the data to be sorted).
@alonh5
</blockquote></details>

I think you're talking about two different orders. @ShahakShama is talking about the messages sent being sorted by block number, and @yair-starkware about the internal fields `deployed_contracts` and `declared_classes` being sorted.

The mappings are sorted when calculating the hashes (as they should be), so no need to sort. Added a test for that.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFHFMs-EQB9LQUEAh89:-OFHt2Vo8xIbdIa1aPVO:b9thr77) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e0f59dd2fd4e13e1de54ef706840221280a6ed9/crates/starknet_batcher/src/block_builder.rs#L95)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

@yair-starkware said this map should be sorted by address before writing.
</blockquote></details>

See the comment above.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFHFXba45v-MzNN-Jhi:-OFHt9oeBaptvdZvx7sr:b-816h6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e0f59dd2fd4e13e1de54ef706840221280a6ed9/crates/starknet_batcher/src/block_builder.rs#L97)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same, but sorted by class hash
</blockquote></details>

Same.


<!-- Sent from Reviewable.io -->

2024-12-30 08:59 UTC, yair-starkware commented
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think you're talking about two different orders. @ShahakShama is talking about the messages sent being sorted by block number, and @yair-starkware about the internal fields `deployed_contracts` and `declared_classes` being sorted.

The mappings are sorted when calculating the hashes (as they should be), so no need to sort. Added a test for that.
</blockquote></details>

Need to check in the papyrus storage writers (state, classes & casm) if the data is expected to be sorted


<!-- Sent from Reviewable.io -->

2025-01-01 12:45 UTC, Yael-Starkware requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: all files reviewed, 10 unresolved discussions (waiting on @alonh5, @asmaastarkware, @dafnamatsry, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWqeYT1VWfmKmOJx35:-OFWqeYT1VWfmKmOJx36:bv8r23c) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher_test.rs#L62)):*
> ```XML
>             &BlockExecutionArtifacts::create_for_testing().state_diff,
>         ),
>     }
> ```

I think the commitment can just be a constant for testing purposes , no?



_Code quote:_
```XML
    ProposalCommitment {
        state_diff_commitment: calculate_state_diff_hash(
            &BlockExecutionArtifacts::create_for_testing().state_diff,
        ),
    }
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 574 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWtATB0Canp6G1NQ6S:-OFWtATB0Canp6G1NQ6T:b-fryod0) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher_test.rs#L574)):*
> ```XML
>     let address_to_nonce = HashMap::from_iter(
>         expected_artifacts.state_diff.nonces.iter().map(|(address, nonce)| (*address, *nonce)),
>     );
> ```

I think a helper function indexmap_to_hashmap() could be useful here and in the batcher code.



_Code quote:_
```XML
    let address_to_nonce = HashMap::from_iter(
        expected_artifacts.state_diff.nonces.iter().map(|(address, nonce)| (*address, *nonce)),
    );
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 612 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWsI6Q7hcJ8Ztsm0nW:-OFWsI6Q7hcJ8Ztsm0nX:bz8so7w) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher_test.rs#L612)):*
> ```XML
>         batcher.decision_reached(DecisionReachedInput { proposal_id: PROPOSAL_ID }).await.unwrap();
>     assert_eq!(response.state_diff, expected_artifacts.state_diff);
>     assert!(response.state_diff.storage_diffs.keys().collect::<Vec<_>>().is_sorted());
> ```

do we want to check that the other fields are sorted as well?



_Code quote:_
```XML
assert!(response.state_diff.storage_diffs.keys().collect::<Vec<_>>().is_sorted());
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 422 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWlwLs27iB7W3An2lo:-OFWlwLs27iB7W3An2lp:b-wq499m) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L422)):*
> ```XML
>         let BlockExecutionArtifacts { l2_gas_used, execution_infos, mut state_diff, .. } =
>             block_execution_artifacts;
>         self.finalize_state_diff(&mut state_diff)?;
> ```

why not run this logic in into_state_diff and get the final_state_diff to begin with? 
is there any reason to store the intermediate presentation?



_Code quote:_
```XML
self.finalize_state_diff(&mut state_diff)?;
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 426 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWmfrO4l9yS78DTMCp:-OFWmfrO4l9yS78DTMCq:b-pmaj5h) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L426)):*
> ```XML
>             height,
>             state_diff.clone(),
>             HashMap::from_iter(state_diff.nonces.iter().map(|(address, nonce)| (*address, *nonce))),
> ```

if we already pass the state_diff here, why do we need the address_to_nonce which is calculated from the state_diff?



_Code quote:_
```XML
HashMap::from_iter(state_diff.nonces.iter().map(|(address, nonce)| (*address, *nonce))),
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 440 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWmy-d3imyX8zvFNl0:-OFWmy-d3imyX8zvFNl1:b-qbeimv) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L440)):*
> ```XML
>         for (address, class_hash) in state_diff.deployed_contracts.clone() {
>             if self.storage_reader.address_is_assigned(address).map_err(|err| {
>                 error!("Failed to get class hash from storage: {}", err);
> ```

I think it's better to emphasize that the function failed, and not that we failed to get the class hash - since this scenario is possible when the address is not deployed.



_Suggestion:_
```XML
error!("Get class hash from storage failed: {}", err);
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 454 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWqNKo9H54s8zOLAf2:-OFWqNKo9H54s8zOLAf3:b-mkydjv) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L454)):*
> ```XML
>         state_diff.storage_diffs.sort_keys();
>         state_diff.declared_classes.sort_keys();
>         state_diff.nonces.sort_keys();
> ```

what was @yair-starkware 's conclusion regarding the sorting requirement?



_Code quote:_
```XML
        deployed_contracts.sort_keys();
        replaced_classes.sort_keys();
        state_diff.deployed_contracts = deployed_contracts;
        state_diff.replaced_classes = replaced_classes;
        state_diff.storage_diffs.sort_keys();
        state_diff.declared_classes.sort_keys();
        state_diff.nonces.sort_keys();
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 463 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWpwyTB2V087zL9vA9:-OFWpwyTB2V087zL9vAA:bazfek7) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L463)):*
> ```XML
>         state_diff: ThinStateDiff,
>         address_to_nonce: HashMap<ContractAddress, Nonce>,
>         tx_hashes: HashSet<TransactionHash>,
> ```

not that the HashSet does not keep the insertion ordering . better to use Vec.
I'm not sure it's a problem here since the HashSet is only used for the mempool. 
But the trace could be a bit confusing.

maybe better to pass a Vec as input and then convert it only for the mempool call.



_Code quote:_
```XML
tx_hashes: HashSet<TransactionHash>,
```
___
*[`crates/starknet_batcher/src/block_builder.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWsNtV9MPRywOcXOZy:-OFWsNtV9MPRywOcXOZz:bzftu3a) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/block_builder.rs#L70)):*
> ```XML
> pub struct BlockExecutionArtifacts {
>     pub execution_infos: IndexMap<TransactionHash, TransactionExecutionInfo>,
>     pub state_diff: ThinStateDiff,
> ```

Sweet!



_Code quote:_
```XML
pub state_diff: ThinStateDiff,
```


<!-- Sent from Reviewable.io -->

2025-01-01 13:19 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: all files reviewed, 10 unresolved discussions (waiting on @alonh5, @asmaastarkware, @dafnamatsry, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 463 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWpwyTB2V087zL9vA9:-OFX0Fk8DjWPR7gsdn_C:bfw7v77) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L463)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not that the HashSet does not keep the insertion ordering . better to use Vec.
I'm not sure it's a problem here since the HashSet is only used for the mempool. 
But the trace could be a bit confusing.

maybe better to pass a Vec as input and then convert it only for the mempool call.
</blockquote></details>

*note


<!-- Sent from Reviewable.io -->

2025-01-01 15:48 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: all files reviewed, 8 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 422 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWlwLs27iB7W3An2lo:-OFXUvrh3EOhYZFFxHmO:b-7g1u5f) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L422)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why not run this logic in into_state_diff and get the final_state_diff to begin with? 
is there any reason to store the intermediate presentation?
</blockquote></details>

Because I need the storage for this, and I prefered not to pass a reader into the the block builder.
___
*[`crates/starknet_batcher/src/batcher.rs` line 426 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWmfrO4l9yS78DTMCp:-OFXW1Ra7g-xD0TH1Phk:boyexbg) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L426)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

if we already pass the state_diff here, why do we need the address_to_nonce which is calculated from the state_diff?
</blockquote></details>

Done. Thanks.
___
*[`crates/starknet_batcher/src/batcher.rs` line 440 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWmy-d3imyX8zvFNl0:-OFXVKMh3N7_MGV0urdr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L440)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think it's better to emphasize that the function failed, and not that we failed to get the class hash - since this scenario is possible when the address is not deployed.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 454 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWqNKo9H54s8zOLAf2:-OFXW5TO9S3zdsBvZ2cq:b-nxtaut) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L454)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what was @yair-starkware 's conclusion regarding the sorting requirement?
</blockquote></details>

It looks like they are supposed to be sorted but I still need to verify for sure.
___
*[`crates/starknet_batcher/src/batcher.rs` line 463 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWpwyTB2V087zL9vA9:-OFXWr3A-SYtbbBO1H-B:bhattk9) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L463)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

*note
</blockquote></details>

I started doing this but then noticed we are collection them in decision reached from the execution info so this adds another iteration over all the tx hashes so I don't think it's important enough to do that.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWqeYT1VWfmKmOJx35:-OFXXOoj48GXBIjK1h5p:biy0i6z) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher_test.rs#L62)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think the commitment can just be a constant for testing purposes , no?
</blockquote></details>

It's tested against the one returned from the batcher so it needs to be the one that s received from the test `BlockExecutionArtifacts`.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 574 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWtATB0Canp6G1NQ6S:-OFXXoES4N3BEpJ7_e8j:bgijpnx) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher_test.rs#L574)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think a helper function indexmap_to_hashmap() could be useful here and in the batcher code.
</blockquote></details>

I thought about it, but it's just one line I don't want to overcomplicate. I did make it nicer with collect() in both locations.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 612 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWsI6Q7hcJ8Ztsm0nW:-OFXY-lt6LzOYyYFX2cE:b4g2yqj) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher_test.rs#L612)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

do we want to check that the other fields are sorted as well?
</blockquote></details>

That means filling all the fields in the state diff, wdyt? maybe in a separate test just for that with a full state diff?


<!-- Sent from Reviewable.io -->

2025-01-02 07:36 UTC, Yael-Starkware requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 422 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWlwLs27iB7W3An2lo:-OF_uuSm76QDgddiolGI:bldzroj) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher.rs#L422)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Because I need the storage for this, and I prefered not to pass a reader into the the block builder.
</blockquote></details>

got it, 
To make it clear, so that others won't use it the wrong way, lets change the name in BlockExecutionArtifacts to reflect that it is not a final state_diff , maybe something like unsorted_state_diff or raw_state_diff.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 612 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFWsI6Q7hcJ8Ztsm0nW:-OF_w4qi1GyMRvQqFM68:b-nec2kw) ([raw file](https://github.com/starkware-libs/sequencer/blob/dae16c1c7b4f92db7a3f0310c48644cde8127332/crates/starknet_batcher/src/batcher_test.rs#L612)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

That means filling all the fields in the state diff, wdyt? maybe in a separate test just for that with a full state diff?
</blockquote></details>

Ok, makes sense.


<!-- Sent from Reviewable.io -->

2025-01-02 11:19 UTC, yair-starkware requested changes
> Reviewed 3 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: all files reviewed, 7 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFaiSOVBQeuRWGZv8Vx:-OFaiSOVBQeuRWGZv8Vy:b-8ch0no) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d7b492d0dc0e5bafc5e217a8a1d60a8b5bf894/crates/starknet_batcher/src/batcher_test.rs#L63)):*
> ```XML
>         ),
>     }
> }
> ```

Can this be a constant?



_Code quote:_
```XML
fn proposal_commitment() -> ProposalCommitment {
    ProposalCommitment {
        state_diff_commitment: calculate_state_diff_hash(
            &BlockExecutionArtifacts::create_for_testing().state_diff,
        ),
    }
}
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 445 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFahY0x0qJXlCFBt9e6:-OFahY0x0qJXlCFBt9e7:b1m42u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d7b492d0dc0e5bafc5e217a8a1d60a8b5bf894/crates/starknet_batcher/src/batcher.rs#L445)):*
> ```XML
>                 deployed_contracts.insert(address, ClassHash(class_hash.0));
>             }
>         }
> ```

Consider extracting to a function



_Code quote:_
```XML
        for (address, class_hash) in state_diff.deployed_contracts.clone() {
            if self.storage_reader.address_is_assigned(address).map_err(|err| {
                error!("Get class hash from storage failed: {}", err);
                BatcherError::InternalError
            })? {
                replaced_classes.insert(address, ClassHash(class_hash.0));
            } else {
                deployed_contracts.insert(address, ClassHash(class_hash.0));
            }
        }
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 446 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFahdBMCRWZw3ZYKWRe:-OFahdBMCRWZw3ZYKWRf:bvufdsl) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d7b492d0dc0e5bafc5e217a8a1d60a8b5bf894/crates/starknet_batcher/src/batcher.rs#L446)):*
> ```XML
>             }
>         }
>         deployed_contracts.sort_keys();
> ```

Consider extracting all the sorting to a function
___
*[`crates/starknet_batcher/src/batcher.rs` line 450 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFahEKx1cHnR4oHpo8v:-OFahEKy6_TRIOmshQRI:bye8tnl) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d7b492d0dc0e5bafc5e217a8a1d60a8b5bf894/crates/starknet_batcher/src/batcher.rs#L450)):*
> ```XML
>         state_diff.deployed_contracts = deployed_contracts;
>         state_diff.replaced_classes = replaced_classes;
>         state_diff.storage_diffs.sort_keys();
> ```

Also the storage diffs of each contract need to be sorted



_Code quote:_
```XML
state_diff.storage_diffs.sort_keys();
```


<!-- Sent from Reviewable.io -->

2025-01-05 05:34 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: all files reviewed, 8 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFownNv2b84b6-jG2f5:-OFownNw05bXgyU2XkIo:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d7b492d0dc0e5bafc5e217a8a1d60a8b5bf894/crates/starknet_batcher/src/block_builder.rs#L70)):*
> ```XML
> pub struct BlockExecutionArtifacts {
>     pub execution_infos: IndexMap<TransactionHash, TransactionExecutionInfo>,
>     pub state_diff: ThinStateDiff,
> ```





_Suggestion:_
```XML
// <comment explaining this state diff cannot be written to storage as is
pub unsorted_state_diff: ThinStateDiff,
```


<!-- Sent from Reviewable.io -->

2025-01-06 09:43 UTC, yair-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-:-OFuzxcwAALHKz0Eq8TV:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @ShahakShama, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-07 06:42 UTC, Yael-Starkware requested changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, and @ShahakShama)

___
*[`crates/starknet_batcher/src/batcher.rs` line 442 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFzSqD31RECiCW0AAM9:-OFzSqD4BAmO8aUFmoGN:b-xi2p2j) ([raw file](https://github.com/starkware-libs/sequencer/blob/201570f5c9870a74659227496e02ae3403214f6f/crates/starknet_batcher/src/batcher.rs#L442)):*
> ```XML
>                 BatcherError::InternalError
>             })? {
>                 replaced_classes.insert(address, ClassHash(class_hash.0));
> ```

what happens if a class is declared and replaced in the same block?



_Code quote:_
```XML
            if self.storage_reader.address_is_assigned(address).map_err(|err| {
                error!("Get class hash from storage failed: {}", err);
                BatcherError::InternalError
            })? {
                replaced_classes.insert(address, ClassHash(class_hash.0));
```


<!-- Sent from Reviewable.io -->

2025-01-13 08:02 UTC, ShahakShama approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-OFHcYeo1VsKxV2mmLMx:-OGTfaIi7YWW7I0N-1rZ:b-ekyx63) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Need to check in the papyrus storage writers (state, classes & casm) if the data is expected to be sorted
</blockquote></details>

I was indeed talking about the messages being sorted by block number.
Regarding state diff, they son't need to be sorted. The state diff hash function sorts it before calculating


<!-- Sent from Reviewable.io -->

2025-01-14 15:20 UTC, alonh5 reviewed
Closing this PR due to this not being relevant for the sequencer. The distinction between deployed contracts and replaced classes is only relevant for an RPC.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2997#-:-OG_OR6r5TmN_wlsNJ4b:b-gdeg2o)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2025-01-14 15:21 UTC, closed without merging