feat(blockifier): refactor native stack config
starkware-libs/sequencer pull request #3003
Opened 2024-12-29 15:04 UTC by AvivYossef-starkware

2024-12-29 15:04 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3003)
<!-- Reviewable:end -->

2024-12-29 15:05 UTC, AvivYossef-starkware commented
* **#3003** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3003?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3003?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main-v0.13.4`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-29 19:06 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 503 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFImuvz-ST7gXeQ2q_Z:-OFImuvz-ST7gXeQ2q__:b-j9tz1z) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d9e407af744a6c408b4aed177419a4fa79a19dd/crates/blockifier/src/versioned_constants.rs#L503)):*
> ```XML
>     pub fn get_target_stack_size(&self, red_zone: usize) -> usize {
>         std::cmp::min(red_zone + self.buffer_size, self.max_stack_size)
>     }
> ```

Take the `min` in `get_stack_size_red_zone` as well, not here.
Add the `self.max_stack_size` to the red zone without capping to get the target size.
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFInPQi3rQJ9IaGmox8:-OFInPQj9-Pnq0Tvl_bD:bkw5el3) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d9e407af744a6c408b4aed177419a4fa79a19dd/crates/blockifier/src/execution/native/entry_point_execution.rs#L65)):*
> ```XML
>         max_stack_size: 170 * 1024 * 1024,
>         min_stack_red_zone: 2 * 1024 * 1024,
>         buffer_size: 1024 * 1024,
> ```

To be on the safe side



_Suggestion:_
```XML
        gas_to_stack_ratio: Ratio::new(1, 20),
        max_stack_size: 200 * 1024 * 1024,
        min_stack_red_zone: 2 * 1024 * 1024,
        buffer_size: 5 * 1024 * 1024,
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFIlXTb1BGp4Zt4pPp7:-OFIlXTb1BGp4Zt4pPp8:bqy79k6) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d9e407af744a6c408b4aed177419a4fa79a19dd/crates/blockifier/src/execution/native/entry_point_execution.rs#L69)):*
> ```XML
>     let stack_size_red_zone = stack_config.get_stack_size_red_zone(
>         usize::try_from(syscall_handler.base.call.initial_gas)
>             .expect("initial gas to usize should always succeed"),
> ```

Not sure about it. usize can be 32 bit.
The stack size should be usize, try to convert at the end.



_Code quote:_
```XML
.expect("initial gas to usize should always succeed"),
```


<!-- Sent from Reviewable.io -->

2024-12-29 19:06 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 503 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFImuvz-ST7gXeQ2q_Z:-OFIo1dJ9mZVawxoDK3S:bgq1dr2) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d9e407af744a6c408b4aed177419a4fa79a19dd/crates/blockifier/src/versioned_constants.rs#L503)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Take the `min` in `get_stack_size_red_zone` as well, not here.
Add the `self.max_stack_size` to the red zone without capping to get the target size.
</blockquote></details>

(I want the target size to always be greater then the red zone)


<!-- Sent from Reviewable.io -->

2024-12-30 08:20 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 503 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFImuvz-ST7gXeQ2q_Z:-OFLXiO72XMe5IaLy3Po:buyro9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d9e407af744a6c408b4aed177419a4fa79a19dd/crates/blockifier/src/versioned_constants.rs#L503)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(I want the target size to always be greater then the red zone)
</blockquote></details>

So, don't we want to limit the stack size?
In that case, do we need both `buffer_size` and `max_stack_size`?
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFInPQi3rQJ9IaGmox8:-OFLVvks9UIIm7A0o-Bk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d9e407af744a6c408b4aed177419a4fa79a19dd/crates/blockifier/src/execution/native/entry_point_execution.rs#L65)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

To be on the safe side
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFIlXTb1BGp4Zt4pPp7:-OFLVzKO7bkdwcJNqFce:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d9e407af744a6c408b4aed177419a4fa79a19dd/crates/blockifier/src/execution/native/entry_point_execution.rs#L69)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not sure about it. usize can be 32 bit.
The stack size should be usize, try to convert at the end.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-30 08:23 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFLeAvU07LN8C9q1abZ:-OFLeAvU07LN8C9q1ab_:b-9bh8zf) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa0e3b850051f3669db9e9fed611f3b8c58db16f/crates/blockifier/src/execution/native/entry_point_execution.rs#L71)):*
> ```XML
>     let target_stack_size =
>         usize::try_from(stack_config.get_target_stack_size(stack_size_red_zone))
>             .map_err(|e| EntryPointExecutionError::InternalError(e.to_string()))?;
> ```

You should panic here - it is our problem, not the user's (returning an error will fail the transaction)



_Code quote:_
```XML
.map_err(|e| EntryPointExecutionError::InternalError(e.to_string()))?;
```


<!-- Sent from Reviewable.io -->

2024-12-30 08:24 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 503 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFImuvz-ST7gXeQ2q_Z:-OFLeNop05xRQzW240dE:b-1ya5jz) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d9e407af744a6c408b4aed177419a4fa79a19dd/crates/blockifier/src/versioned_constants.rs#L503)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

So, don't we want to limit the stack size?
In that case, do we need both `buffer_size` and `max_stack_size`?
</blockquote></details>

We want:
* to limit the stack size
* to have the target size always `red_zone + buffer`.

So the "real" max is the config + buffer, which is fine.


<!-- Sent from Reviewable.io -->

2024-12-30 12:25 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 503 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFImuvz-ST7gXeQ2q_Z:-OFLktiJ-FJcZAO7Xkvf:b-1n196n) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d9e407af744a6c408b4aed177419a4fa79a19dd/crates/blockifier/src/versioned_constants.rs#L503)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We want:
* to limit the stack size
* to have the target size always `red_zone + buffer`.

So the "real" max is the config + buffer, which is fine.
</blockquote></details>

Ok so I'll limit the min < red zone < max
 and always add the buffer size 
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFLeAvU07LN8C9q1abZ:-OFLk9toAEFOPYcZ311B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa0e3b850051f3669db9e9fed611f3b8c58db16f/crates/blockifier/src/execution/native/entry_point_execution.rs#L71)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You should panic here - it is our problem, not the user's (returning an error will fail the transaction)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-30 13:07 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 494 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFMf7u2DRnuBA_1s1iB:-OFMf7u2DRnuBA_1s1iC:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5d2bcf8f457641932b71adb431796e32539e31bc/crates/blockifier/src/versioned_constants.rs#L494)):*
> ```XML
> 
> impl CairoNativeStackConfig {
>     /// Returns the size of the stack red zone, relative to the remaining gas.
> ```





_Suggestion:_
```XML
    /// Returnד the stack size sufficient for running Cairo Native with the given gas.
```


<!-- Sent from Reviewable.io -->

2024-12-30 13:27 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 498 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFMeCb2DfjqjjV4kDx6:-OFMidH7-W7nU5Kmik-0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5d2bcf8f457641932b71adb431796e32539e31bc/crates/blockifier/src/versioned_constants.rs#L498)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oops.
Use `clamp` instead (google it)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 494 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFMf7u2DRnuBA_1s1iB:-OFMix5uAoVUEtOPH6h_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5d2bcf8f457641932b71adb431796e32539e31bc/crates/blockifier/src/versioned_constants.rs#L494)):*
> ```XML
> 
> impl CairoNativeStackConfig {
>     /// Returns the size of the stack red zone, relative to the remaining gas.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-31 08:50 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFQuCmJ-rE_e2GjPzGS:-OFQuCmK6cpxcmllxCsl:btk0dck) ([raw file](https://github.com/starkware-libs/sequencer/blob/d14f9d4644ea62e3014257cceadb37220fb99f2d/crates/blockifier/src/execution/native/entry_point_execution.rs#L76)):*
> ```XML
>     let execution_result = stacker::maybe_grow(
>         usize::try_from(stack_size_red_zone)
>             .unwrap_or_else(|e| panic!("Failed to convert stack size red zone to usize: {}", e)),
> ```

Move the convesion up, to be consistent with `target_stack_size`



_Code quote:_
```XML
        usize::try_from(stack_size_red_zone)
            .unwrap_or_else(|e| panic!("Failed to convert stack size red zone to usize: {}", e)),
```


<!-- Sent from Reviewable.io -->

2025-01-01 07:43 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFQuCmJ-rE_e2GjPzGS:-OFV_i4GCgCcr9H7A1Su:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d14f9d4644ea62e3014257cceadb37220fb99f2d/crates/blockifier/src/execution/native/entry_point_execution.rs#L76)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Move the convesion up, to be consistent with `target_stack_size`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 07:48 UTC, Yoni-Starkware requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 512 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFVp7Ey8PZ2KB4hVp3t:-OFVp7Ey8PZ2KB4hVp3u:bbtxjjl) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c60441e946f643d78368fe7de83a4ecbd6d6e2f/crates/blockifier/src/versioned_constants.rs#L512)):*
> ```XML
> 
>     pub fn get_target_stack_size(&self, red_zone: u64) -> u64 {
>         red_zone + self.buffer_size
> ```

This is the size that matters. Round also here to be on the safe side.



_Code quote:_
```XML
red_zone + self.buffer_size
```


<!-- Sent from Reviewable.io -->

2025-01-01 07:49 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 511 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFVp_W02qEB3aPArO1W:-OFVp_W17qrvvZ6zlDvf:b-chy1) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c60441e946f643d78368fe7de83a4ecbd6d6e2f/crates/blockifier/src/versioned_constants.rs#L511)):*
> ```XML
>     }
> 
>     pub fn get_target_stack_size(&self, red_zone: u64) -> u64 {
> ```

Also, document that the stack size must be in `page_size` multiplications since there is a bug in `stacker::grow`



_Code quote:_
```XML
    pub fn get_target_stack_size(&self, red_zone: u64) -> u64 {
```


<!-- Sent from Reviewable.io -->

2025-01-01 08:29 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 511 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFVp_W02qEB3aPArO1W:-OFVpmE12CQ_xO9XVtjL:b-eq30x3) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c60441e946f643d78368fe7de83a4ecbd6d6e2f/crates/blockifier/src/versioned_constants.rs#L511)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Also, document that the stack size must be in `page_size` multiplications since there is a bug in `stacker::grow`
</blockquote></details>

Ok, I wasn't sure if we want to make it public
___
*[`crates/blockifier/src/versioned_constants.rs` line 512 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFVp7Ey8PZ2KB4hVp3t:-OFVy_gi-dbrTvcRbpBC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c60441e946f643d78368fe7de83a4ecbd6d6e2f/crates/blockifier/src/versioned_constants.rs#L512)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This is the size that matters. Round also here to be on the safe side.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 08:42 UTC, Yoni-Starkware approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 511 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFVp_W02qEB3aPArO1W:-OFW0f_3Ea2Cov2FYQXZ:b-il3oxn) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c60441e946f643d78368fe7de83a4ecbd6d6e2f/crates/blockifier/src/versioned_constants.rs#L511)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Ok, I wasn't sure if we want to make it public
</blockquote></details>

Hmm okay, so let's rephrase
```
        // Stack size should be a multiple of page size, since `stacker::grow` works with this unit.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 497 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFW0OUR3xkEtMR2F0Dw:-OFW0OUS-6d6pO9LmneV:brv6pjy) ([raw file](https://github.com/starkware-libs/sequencer/blob/121acb4dc1aa6f2ae7ab699e4dee424bd130656c/crates/blockifier/src/versioned_constants.rs#L497)):*
> ```XML
>     pub fn round_up_to_mb(size: u64) -> u64 {
>         const MB: u64 = 1024 * 1024;
>         if size % MB == 0 { size } else { ((size / MB) + 1) * MB }
> ```

Consider



_Suggestion:_
```XML
((size + MB - 1) / MB) * MB
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 513 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFW-Nd_7IxJdXUeW5F7:-OFW-Nda6m8CSEOQfdmD:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/121acb4dc1aa6f2ae7ab699e4dee424bd130656c/crates/blockifier/src/versioned_constants.rs#L513)):*
> ```XML
>     pub fn get_target_stack_size(&self, red_zone: u64) -> u64 {
>         // Stack size must be a multiple of page size.
>         // Since there is a bug in `stacker::grow`.
> ```




<!-- Sent from Reviewable.io -->

2025-01-01 09:18 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 497 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFW0OUR3xkEtMR2F0Dw:-OFW5L6uAEQDKtyl_wbO:b-9mnaz0) ([raw file](https://github.com/starkware-libs/sequencer/blob/121acb4dc1aa6f2ae7ab699e4dee424bd130656c/crates/blockifier/src/versioned_constants.rs#L497)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Consider
</blockquote></details>

 The compiler asked me to use `div_ceil` ( its the same ) 


<!-- Sent from Reviewable.io -->

2025-01-01 09:29 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 497 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-OFW0OUR3xkEtMR2F0Dw:-OFWBTV_6eDL9wK4AnqZ:b-byxu1g) ([raw file](https://github.com/starkware-libs/sequencer/blob/121acb4dc1aa6f2ae7ab699e4dee424bd130656c/crates/blockifier/src/versioned_constants.rs#L497)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

The compiler asked me to use `div_ceil` ( its the same )
</blockquote></details>

Don't you need to multiply by MB?


<!-- Sent from Reviewable.io -->

2025-01-01 09:34 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3003#-:-OFWCvr6AnDUYaEL-EZt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 11:44 UTC, merged