chore(blockifier): test egative consumed gas
starkware-libs/sequencer pull request #3005
Opened 2024-12-29 15:19 UTC by avivg-starkware

2024-12-29 15:19 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3005)
<!-- Reviewable:end -->

2024-12-29 15:19 UTC, avivg-starkware commented
* **#3005** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3005?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3005?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-01 13:36 UTC, noaov1 reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3005)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @meship-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2889 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3005#-OFX3sBbBxNI3HL0EYAN:-OFX3sBbBxNI3HL0EYAO:b-tt5f1n) ([raw file](https://github.com/starkware-libs/sequencer/blob/46b555b81da11dc5bccdd4b87d331021504596f6/crates/blockifier/src/transaction/transactions_test.rs#L2889)):*
> ```XML
> #[case(RunnableCairo1::Casm)]
> #[cfg_attr(feature = "cairo_native", case(RunnableCairo1::Native))]
> fn test_empty_function_flow(#[case] runnable: RunnableCairo1) {
> ```

Maybe it's better to move this test to the call_contract.rs file.
WDYT?



_Code quote:_
```XML
fn test_empty_function_flow(#[case] runnable: RunnableCairo1) {
```


<!-- Sent from Reviewable.io -->

2025-01-01 19:03 UTC, meship-starkware requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3005)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2902 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3005#-OFYEhV6EOsBXQ6CvW-G:-OFYEhV6EOsBXQ6CvW-H:b-fpikij) ([raw file](https://github.com/starkware-libs/sequencer/blob/46b555b81da11dc5bccdd4b87d331021504596f6/crates/blockifier/src/transaction/transactions_test.rs#L2902)):*
> ```XML
>     let calldata = create_calldata(
>         test_contract_address,
>         "empty_function",
> ```

Can you add it as a constant EMPTY_FUNCTION_SELECTOR



_Code quote:_
```XML
  "empty_function",
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2912 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3005#-OFYF1dK49kZtjulOTPD:-OFYF1dL5vLgftby4k2H:byp18fd) ([raw file](https://github.com/starkware-libs/sequencer/blob/46b555b81da11dc5bccdd4b87d331021504596f6/crates/blockifier/src/transaction/transactions_test.rs#L2912)):*
> ```XML
> 
>     let execution_info = invoke_tx.execute(state, block_context).unwrap();
>     println!("{:?}", execution_info);
> ```

Remove



_Code quote:_
```XML
 println!("{:?}", execution_info);
```


<!-- Sent from Reviewable.io -->

2025-01-02 14:16 UTC, meship-starkware reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3005)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2902 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3005#-OFYEhV6EOsBXQ6CvW-G:-OFbMS2IB6A5mOH63tB_:b8qkl53) ([raw file](https://github.com/starkware-libs/sequencer/blob/46b555b81da11dc5bccdd4b87d331021504596f6/crates/blockifier/src/transaction/transactions_test.rs#L2902)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

not sure where to take this from. 
I only found 2 mentions to this, but no definition. in both it's accessed through:
SecurityTestContract.EMPTY_FUNCTION_SELECTOR, 

which is defined in a cairo file: security_test_contract.cairo 

could you clarify your intention?
</blockquote></details>

I meant to add a constant with the name EMPTY_FUNCTION_SELECTOR. If the transaction has a test utils, I would drop it there. If not, then just on top of the test file. 


<!-- Sent from Reviewable.io -->

2025-01-02 14:16 UTC, meship-starkware reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3005)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2025-01-02 14:16 UTC, meship-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3005)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2025-01-05 05:23 UTC, noaov1 requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3005)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 406 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3005#-OFm6zZm67-SLa0H9C7z:-OFm6zZn0ddb1ejN_ttW:bqh1da3) ([raw file](https://github.com/starkware-libs/sequencer/blob/d8888178bc7be672e725fb57c6d3db9c8813bf23/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L406)):*
> ```XML
> 
>     let execution_info = invoke_tx.execute(state, block_context).unwrap();
>     assert!(!execution_info.is_reverted());
> ```

No need the account transaction for this test. 



_Suggestion:_
```XML
    let test_contract = FeatureContract::TestContract(CairoVersion::Cairo1(runnable));
    let chain_info = &ChainInfo::create_for_testing();
    let state = &mut test_state(chain_info, BALANCE, &[(account_contract, 1), (test_contract, 1)]);
    let test_contract_address = test_contract.get_instance_address(0);
  
    let calldata = create_calldata(
        test_contract_address,
        "empty_function",
        &[], // Calldata.
    );
    let outer_entry_point_selector = selector_from_name("test_call_contract");
    let entry_point_call = CallEntryPoint {
        entry_point_selector: outer_entry_point_selector,
        calldata,
        ..trivial_external_entry_point_new(outer_contract)
    };

    assert_eq!(
        !entry_point_call.execute_directly(&mut state).unwrap().execution.failed,
    );
```


<!-- Sent from Reviewable.io -->

2025-01-05 13:50 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3005)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 406 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3005#-OFm6zZm67-SLa0H9C7z:-OFqegMh1fS1Qncfnu6b:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d8888178bc7be672e725fb57c6d3db9c8813bf23/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L406)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No need the account transaction for this test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-06 11:04 UTC, avivg-starkware reviewed
> Reviewed 1 of 4 files at r1, 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3005)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)



<!-- Sent from Reviewable.io -->

2025-01-06 13:36 UTC, merged