refactor(sequencing): cende context, add logic and tests
starkware-libs/sequencer pull request #3007
Opened 2024-12-29 16:05 UTC by DvirYo-starkware

2024-12-29 16:05 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3007)
<!-- Reviewable:end -->

2024-12-30 09:09 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLn_eCCnX-gqeoxTLL:-OFLn_eD77FuMVxDn2uG:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L10)):*
> ```XML
> #[case::success(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(10), 1, true)]
> #[case::none_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, None, 0, false)]
> #[case::mismatch_heihgt_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(7), 0, false)]
> ```





_Suggestion:_
```XML
mismatch_height_prev_block
```


<!-- Sent from Reviewable.io -->

2024-12-30 09:34 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLu_oG0nS5g1DhYgWQ:-OFLu_oHA0uN36tlD71h:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L34)):*
> ```XML
>     }
> 
>     let reciver = cende_ambassador.write_prev_height_blob(BlockNumber(written_height));
> ```





_Suggestion:_
```XML
receiver
```


<!-- Sent from Reviewable.io -->

2024-12-30 09:35 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLue51AeqembpivAI5:-OFLue51AeqembpivAI6:bi45r3q) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L37)):*
> ```XML
> 
>     assert_eq!(reciver.await.unwrap(), result);
>     mock.expect(expected_calls);
> ```

from reading the docs I think you need to add mock.assert() after this line for the expectation to be enforced.



_Suggestion:_
```XML
mock.expect(expected_calls);
mock.assert();
```


<!-- Sent from Reviewable.io -->

2024-12-30 11:32 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 0 of 4 files reviewed, 15 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMED1LDP9j3ykdtxl9:-OFMED1LDP9j3ykdtxlA:bnewdo) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L8)):*
> ```XML
> 
> #[rstest]
> #[case::success(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(10), 1, true)]
> ```

define a const for prev_height = 10 that will be used also for the other test. 
Then you can delete the written_height from the input to the function.



_Code quote:_
```XML
10
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLwNYbBEIEJg89H4QF:-OFLwNYcDGreSeFS8DyY:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L9)):*
> ```XML
> #[rstest]
> #[case::success(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(10), 1, true)]
> #[case::none_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, None, 0, false)]
> ```





_Suggestion:_
```XML
no_prev_block
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLwT5N1t8Cyy2zcp5G:-OFLwT5N1t8Cyy2zcp5H:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L10)):*
> ```XML
> #[case::success(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(10), 1, true)]
> #[case::none_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, None, 0, false)]
> #[case::mismatch_heihgt_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(7), 0, false)]
> ```





_Suggestion:_
```XML
prev_block_height_mismatch
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLwbVB3pB1w0KhSnnd:-OFLwbVB3pB1w0KhSnne:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L11)):*
> ```XML
> #[case::none_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, None, 0, false)]
> #[case::mismatch_heihgt_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(7), 0, false)]
> #[case::send_recorder_fail("different_recorder_path", 200, 10, Some(10), 0, false)]
> ```





_Suggestion:_
```XML
send_to_recorder_failed
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMGE31CbF0BuAJIWaq:-OFMGE31CbF0BuAJIWar:bx7srvc) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L11)):*
> ```XML
> #[case::none_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, None, 0, false)]
> #[case::mismatch_heihgt_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(7), 0, false)]
> #[case::send_recorder_fail("different_recorder_path", 200, 10, Some(10), 0, false)]
> ```

iiuc this case only tests the mock itself. 



_Code quote:_
```XML
#[case::send_recorder_fail("different_recorder_path", 200, 10, Some(10), 0, false)]
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLw78ZDdVA0Dc5aF5f:-OFLw78ZDdVA0Dc5aF5g:b-a234tu) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L17)):*
> ```XML
>     #[case] path: &str,
>     #[case] status_code: usize,
>     #[case] written_height: u64,
> ```

this is not written yet, 
I would go with height_to_write or just prev_height



_Suggestion:_
```XML
height_to_write
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMEgJX0ssz49idCLGY:-OFMEgJX0ssz49idCLGZ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L20)):*
> ```XML
>     #[case] prev_block: Option<u64>,
>     #[case] expected_calls: usize,
>     #[case] result: bool,
> ```





_Suggestion:_
```XML
expected_result
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMEHMH-rfEP9yAMEbN:-OFMEHMH-rfEP9yAMEbO:b-l4j5wq) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L45)):*
> ```XML
>         CendeAmbassador::new(CendeConfig { recorder_url: "http://parsable_url".parse().unwrap() });
> 
>     const WRITTEN_HEIGHT: BlockNumber = BlockNumber(1701);
> ```

use the global const PREV_HEIGHT=10



_Code quote:_
```XML
const WRITTEN_HEIGHT: BlockNumber = BlockNumber(1701);
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLvGE737s5wiOOraKV:-OFLvGE737s5wiOOraKW:bby9ii2) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L26)):*
> ```XML
> pub(crate) struct AerospikeBlob {
>     // TODO(yael, dvir): add the blob fields.
>     block_number: BlockNumber,
> ```

block_number is a part of the block_info



_Code quote:_
```XML
 block_number: BlockNumber,
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMJrTm-b4YmrXmvOKa:-OFMJrTm-b4YmrXmvOKb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L98)):*
> ```XML
> #[async_trait]
> impl CendeContext for CendeAmbassador {
>     fn write_prev_height_blob(&self, height: BlockNumber) -> oneshot::Receiver<bool> {
> ```





_Suggestion:_
```XML
write_prev_height_blob(&self, prev_height: BlockNumber)
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMJQQb8orult3Slzix:-OFMJQQb8orult3Slziy:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L127)):*
> ```XML
> 
>             // Can happen in case the consensus got a block from the state sync and due to that not
>             // update the cende ambassador in `decision_reached` function.
> ```





_Suggestion:_
```XML
            // Can happen in case the consensus got a block from the state sync and due to that did not
            // update the cende ambassador in `decision_reached` function.
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMJi4ZEq7fVZlfQKhD:-OFMJi4ZEq7fVZlfQKhE:bwpbrgq) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L128)):*
> ```XML
>          [...]

2024-12-30 13:42 UTC, Yael-Starkware reviewed
> Reviewed 3 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: all files reviewed, 15 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2024-12-30 13:45 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: all files reviewed, 16 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMo0e08pH0kD-4N1J9:-OFMo0e08pH0kD-4N1JA:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2fa3f71e40bb7f84f14761434a9d78e24f46149/crates/starknet_integration_tests/src/utils.rs#L77)):*
> ```XML
>         create_state_sync_config(state_sync_storage_config, available_ports.get_next_port());
>     // Creates a mockito server for the recorder. The server returns a success status for each call,
>     // which means that the recorder side will not have any problems in the test.
> ```





_Suggestion:_
```XML
    // Creates a mockito server for the recorder. The server returns a success status for each call,
    // which means that the recorder side will never return an error in the test.
```


<!-- Sent from Reviewable.io -->

2024-12-31 10:54 UTC, dafnamatsry requested changes
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: all files reviewed, 19 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRGpafEXOc0CjqQs87:-OFRGpafEXOc0CjqQs88:b-xn13wv) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L136)):*
> ```XML
>                 oneshot_send(sender, false);
>                 return;
>             }
> ```

Can you move this logic to some `is_blob_valid(...)` function?
The entire function is getting too long and hard to follow.



_Code quote:_
```XML
            let Some(ref blob) = *prev_height_blob.lock().await else {
                // This case happens when restarting the node, `prev_height_blob` intial value is
                // `None`.
                debug!("No blob to write to Aerospike.");
                oneshot_send(sender, false);
                return;
            };

            // Can happen in case the consensus got a block from the state sync and due to that not
            // update the cende ambassador in `decision_reached` function.
            if blob.block_number != height {
                debug!(
                    "Mismatch blob block number and height, can't write blob to Aerospike. Blob \
                     block number {}, height {}",
                    blob.block_number, height
                );
                oneshot_send(sender, false);
                return;
            }
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRHA0P30b8o3XlGMK5:-OFRHA0P30b8o3XlGMK6:b-3dv1bq) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L158)):*
> ```XML
>                     oneshot_send(sender, false);
>                 }
>             }
> ```

This section can also move to a helper function.



_Code quote:_
```XML
            debug!("Writing blob to Aerospike.");
            match request_builder.json(blob).send().await {
                Ok(response) => {
                    if response.status().is_success() {
                        debug!("Blob written to Aerospike successfully.");
                        oneshot_send(sender, true);
                    } else {
                        debug!(
                            "The recorder failed to write blob.\nStatus code: {}\nMessage: {}",
                            response.status(),
                            response.text().await.unwrap_or_default()
                        );
                        oneshot_send(sender, false);
                    }
                }
                Err(err) => {
                    debug!("Failed to send a request to the recorder. Error: {}", err);
                    oneshot_send(sender, false);
                }
            }
```
___
*[`crates/starknet_integration_tests/src/utils.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRIJMzBRSYSU8VH88q:-OFRIJMzBRSYSU8VH88r:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2fa3f71e40bb7f84f14761434a9d78e24f46149/crates/starknet_integration_tests/src/utils.rs#L79)):*
> ```XML
>     // which means that the recorder side will not have any problems in the test.
>     let mut server = mockito::Server::new_async().await;
>     server.mock("POST", "/write_blob").with_status(200).create();
> ```





_Suggestion:_
```XML
/cende/write_blob
```


<!-- Sent from Reviewable.io -->

2024-12-31 15:02 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 1 of 7 files reviewed, 19 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMED1LDP9j3ykdtxl9:-OFRtVmXEUQ7PPpOWGuH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L8)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

define a const for prev_height = 10 that will be used also for the other test. 
Then you can delete the written_height from the input to the function.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMGE31CbF0BuAJIWaq:-OFRthnw8uPsaU3aRENa:b-uqqmri) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L11)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

iiuc this case only tests the mock itself.
</blockquote></details>

No, it tested the case that the send failed, which is different than the case in which the send was successful, but the recorder returned an error. 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLw78ZDdVA0Dc5aF5f:-OFRuANBD3SaVCluPwSk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L17)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this is not written yet, 
I would go with height_to_write or just prev_height
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLue51AeqembpivAI5:-OFRujgPBt2d_qwDpCqO:bhae2eu) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L37)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

from reading the docs I think you need to add mock.assert() after this line for the expectation to be enforced.
</blockquote></details>

You are right, fixed
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMEHMH-rfEP9yAMEbN:-OFRujMt-BpPQBwWKYd9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L45)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

use the global const PREV_HEIGHT=10
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLvGE737s5wiOOraKV:-OFRv8C25DDqBW5E7gK-:b1mv3rg) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L26)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

block_number is a part of the block_info
</blockquote></details>

We need to have this field directly on the Python side to prevent deserialization of all the `BlockInfo` (if I remember correctly, it is part of the `StateDiff`)
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMJi4ZEq7fVZlfQKhD:-OFRwWxo6OvwZ0q0oZXv:bowf4yj) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L128)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

iiuc you describe a scenario where  the blob is older than the one we should write.
what happens if the blob block_number is bigger? I guess this function should return an error since it could indicate a bug in the consensus_context.
</blockquote></details>

It really does mean a bug. I added a todo for that for now.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRGpafEXOc0CjqQs87:-OFSAqW05R9kri5rV4Za:bnk0cui) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L136)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you move this logic to some `is_blob_valid(...)` function?
The entire function is getting too long and hard to follow.
</blockquote></details>

I made some changes. Is it cleaner now?
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRHA0P30b8o3XlGMK5:-OFSB03KDza7DBjIRiyR:b-vd48yp) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L158)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

This section can also move to a helper function.
</blockquote></details>

Moved to utility function
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLwNYbBEIEJg89H4QF:-OFRtY_N4Sdf_OrsTwhn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L9)):*
> ```XML
> #[rstest]
> #[case::success(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(10), 1, true)]
> #[case::none_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, None, 0, false)]
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLn_eCCnX-gqeoxTLL:-OFRt_wt3H0S0kC_ZTIU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L10)):*
> ```XML
> #[case::success(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(10), 1, true)]
> #[case::none_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, None, 0, false)]
> #[case::mismatch_heihgt_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(7), 0, false)]
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLwT5N1t8Cyy2zcp5G:-OFRtcDiEp8NTMWmBZYc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L10)):*
> ```XML
> #[case::success(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(10), 1, true)]
> #[case::none_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, None, 0, false)]
> #[case::mismatch_heihgt_prev_block(RECORDER_WRITE_BLOB_PATH, 200, 10, Some(7), 0, false)]
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 11 at r1](https://reviewabl [...]

2025-01-01 07:20 UTC, dafnamatsry requested changes
> Reviewed 3 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 6 of 7 files reviewed, 19 unresolved discussions (waiting on @DvirYo-starkware and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRGpafEXOc0CjqQs87:-OFVf-GJ--FGPqR2lCB4:b3efvh2) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L136)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I made some changes. Is it cleaner now?
</blockquote></details>

Yes.
I think the other checks can also move out of the spawned task.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFVgXJf3dVc-DS21XgI:-OFVgXJf3dVc-DS21XgJ:bfozom0) ([raw file](https://github.com/starkware-libs/sequencer/blob/558ee54c07848371172b29a7ea50377c183e0d83/crates/starknet_integration_tests/src/utils.rs#L151)):*
> ```XML
> fn spawn_success_recorder() -> Url {
>     // [127, 0, 0, 1] is the localhost IP address.
>     let socket_addr = ([127, 0, 0, 1], find_free_port()).into();
> ```

into what? Can you specify the type or use `from` instead?



_Code quote:_
```XML
.into();
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 147 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFVen0B72kgtSdXTipa:-OFVen0B72kgtSdXTipb:b-yqcjd1) ([raw file](https://github.com/starkware-libs/sequencer/blob/558ee54c07848371172b29a7ea50377c183e0d83/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L147)):*
> ```XML
>         return receiver;
> 
>         async fn sent_write_blob(
> ```

Why are you defining it inside `write_prev_height_blob`?



_Suggestion:_
```XML
async fn send_write_blob(
```


<!-- Sent from Reviewable.io -->

2025-01-01 09:14 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 5 of 7 files reviewed, 19 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFVgXJf3dVc-DS21XgI:-OFW8D57Exe9ljVmdr4q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/558ee54c07848371172b29a7ea50377c183e0d83/crates/starknet_integration_tests/src/utils.rs#L151)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

into what? Can you specify the type or use `from` instead?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 11:30 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 5 of 7 files reviewed, 20 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, and @Yael-Starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 151 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFWcHx51nsJgnLp-JG3:-OFWcHx51nsJgnLp-JG4:b2ee97x) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ab7b0fcb1cab3088461a0facfa413b6232b18c/crates/starknet_integration_tests/src/utils.rs#L151)):*
> ```XML
> fn spawn_success_recorder() -> Url {
>     // [127, 0, 0, 1] is the localhost IP address.
>     let socket_addr = SocketAddr::from(([127, 0, 0, 1], find_free_port()));
> ```

We don't use this function any more. Let's further discuss in person.
As a pointer, check out the `AvailablePorts` struct.



_Code quote:_
```XML
 let socket_addr = SocketAddr::from(([127, 0, 0, 1], find_free_port()));
```


<!-- Sent from Reviewable.io -->

2025-01-01 11:31 UTC, Yael-Starkware requested changes
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMGE31CbF0BuAJIWaq:-OFWWZEk14ruBYfwGh9-:b5f3hyb) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L11)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

No, it tested the case that the send failed, which is different than the case in which the send was successful, but the recorder returned an error.
</blockquote></details>

but in practice it doesn't take the if branch you want it to . 
The mock returns ok with error code 501 in this case and takes the same if branch in the code as the next case.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLvGE737s5wiOOraKV:-OFWXLVv1Qir-Iqtyd08:b-ad0glj) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L26)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

We need to have this field directly on the Python side to prevent deserialization of all the `BlockInfo` (if I remember correctly, it is part of the `StateDiff`)
</blockquote></details>

so maybe worth adding a check to see that it matches the value from the block_info, please add a todo for it.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMJrTm-b4YmrXmvOKa:-OFWXcygBFYDHgACYsn1:bgxm3uc) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L98)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

This intentionally. See the documentation for this function in the `CendeContext` trait.
</blockquote></details>

so maybe current_height,  just to make it clear when using the function.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMo0e08pH0kD-4N1J9:-OFWcG986YdZPuZbsbKt:b-t918t8) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2fa3f71e40bb7f84f14761434a9d78e24f46149/crates/starknet_integration_tests/src/utils.rs#L77)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I have done this with a simple HTTP server instead. The mockito didn't work; I don't know exactly why.
</blockquote></details>

lets understand why, but not as part of this PR.
In general the mocking part should be in a separate PR from the cende internal logic.


<!-- Sent from Reviewable.io -->

2025-01-01 14:24 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 2 of 7 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMGE31CbF0BuAJIWaq:-OFWinQN54MsCS6mhGPT:b-vlehwn) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L11)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

but in practice it doesn't take the if branch you want it to . 
The mock returns ok with error code 501 in this case and takes the same if branch in the code as the next case.
</blockquote></details>

You are right; my mistake. Removed.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFLvGE737s5wiOOraKV:-OFWix83A3HA_DGjWrSn:b-kxkv2l) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L26)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

so maybe worth adding a check to see that it matches the value from the block_info, please add a todo for it.
</blockquote></details>

It will be taken from the block info when we create the real blob. This will happen in the next PR.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMJrTm-b4YmrXmvOKa:-OFWj6wp0lyHYdj-hxvZ:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L98)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

so maybe current_height,  just to make it clear when using the function.
</blockquote></details>

done
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRGpafEXOc0CjqQs87:-OFWjZrg-ZHTKMxniOwb:b-yzgt6x) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L136)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Yes.
I think the other checks can also move out of the spawned task.
</blockquote></details>

I like it that way because all the relevant logic is directly in the spawned task.
In addition, this is a bit hard because we play with a reference to a blob. Unless you have a strong opinion about that, let's keep it that way.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 147 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFVen0B72kgtSdXTipa:-OFWjQdX8DNy0yl4yw1j:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/558ee54c07848371172b29a7ea50377c183e0d83/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L147)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why are you defining it inside `write_prev_height_blob`?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 128 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFWvAWV0cklweZZamI9:-OFXCgXvCSJ3fVh7uwhb:b-eplnle) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ab7b0fcb1cab3088461a0facfa413b6232b18c/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L128)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think that if the consensus got a newer block from the state_update it should clear the cende_ambassador.
maybe we need an additional api for clear_blob.

and then any height mismatch means a consensus_context bug.
</blockquote></details>

I prefer not to do this because this invariant is hard to save. You can add it to the Monday and we will discuss it in the future.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 188 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFWx1ucDd88wm0pN1F1:-OFXCL0W3VE4eJLLxSiV:b-tdm3te) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ab7b0fcb1cab3088461a0facfa413b6232b18c/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L188)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

if you're worried for the serialization, BlockNumber also serializes to an integer so it's fine to keep it that way.
</blockquote></details>

No. I use height when this is a raw info from consensus (in consensus the use height as `u64` and not `BlockNumber`)
___
*[`crates/starknet_integration_tests/src/utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFMo0e08pH0kD-4N1J9:-OFWkDJz0eErXzupDii5:bmjk3ec) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2fa3f71e40bb7f84f14761434a9d78e24f46149/crates/starknet_integration_tests/src/utils.rs#L77)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

lets understand why, but not as part of this PR.
In general the mocking part should be in a separate PR from the cende internal logic.
</blockquote></details>

This is part of this PR because, without that, it will not pass tests
___
*[`crates/starknet_integration_tests/src/utils.rs` line 151 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFWcHx51nsJgnLp-JG3:-OFWmc_8EDWcG95TleEi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ab7b0fcb1cab3088461a0facfa413b6232b18c/crates/starknet_integration_tests/src/utils.rs#L151)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

We don't use this function any more. Let's further discuss in person.
As a pointer, check out the `AvailablePorts` struct.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 14:46 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 2 of 7 files reviewed, 12 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, and @Yael-Starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 128 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXJiDb3T2h5mDl8BHD:-OFXJiDc-WRD2lCS89G5:b-q01c66) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/starknet_integration_tests/src/utils.rs#L128)):*
> ```XML
>     timeouts.proposal_timeout *= 3;
> 
>     let recorder_url = spawn_success_recorder(available_ports.get_next_port());
> ```

Please move this to be near the spawning of the rpc state reader server.



_Code quote:_
```XML
  let recorder_url = spawn_success_recorder(available_ports.get_next_port());
```


<!-- Sent from Reviewable.io -->

2025-01-01 14:55 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, and @Itay-Tsabary-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 188 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFWx1ucDd88wm0pN1F1:-OFXJGfK07ER2pJ2A8Pi:bmbgw9g) ([raw file](https://github.com/starkware-libs/sequencer/blob/06ab7b0fcb1cab3088461a0facfa413b6232b18c/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L188)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

No. I use height when this is a raw info from consensus (in consensus the use height as `u64` and not `BlockNumber`)
</blockquote></details>

I prefer BlockNumber. optional
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 139 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXMDXW1fQwGrlRxVmS:-OFXMDXW1fQwGrlRxVmT:bd4v7q4) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L139)):*
> ```XML
>                 oneshot_send(sender, false);
>                 return;
>             }
> ```

extract to a function  should_write_blob().



_Code quote:_
```XML
            let Some(ref blob): Option<AerospikeBlob> = *prev_height_blob.lock().await else {
                // This case happens when restarting the node, `prev_height_blob` intial value is
                // `None`.
                debug!("No blob to write to Aerospike.");
                oneshot_send(sender, false);
                return;
            };

            // Can happen in case the consensus got a block from the state sync and due to that did
            // not update the cende ambassador in `decision_reached` function.
            // TODO(dvir): what to do in the case of the `blob.block_number.0 >= height.0`? this
            // means a bug.
            if blob.block_number.0 + 1 != current_height.0 {
                debug!(
                    "Mismatch blob block number and height, can't write blob to Aerospike. Blob \
                     block number {}, height {}",
                    blob.block_number, current_height
                );
                oneshot_send(sender, false);
                return;
            }
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXHGzm6YGdKNHdifFM:-OFXHGzm6YGdKNHdifFN:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L16)):*
> ```XML
> #[tokio::test]
> async fn write_prev_height_blob(
>     #[case] status_code: usize,
> ```





_Suggestion:_
```XML
mock_status_code
```


<!-- Sent from Reviewable.io -->

2025-01-02 11:09 UTC, dafnamatsry requested changes
> Reviewed 2 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @DvirYo-starkware, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRGpafEXOc0CjqQs87:-OFagB1N1amIpjSgGM2N:b9cixe8) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L136)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I like it that way because all the relevant logic is directly in the spawned task.
In addition, this is a bit hard because we play with a reference to a blob. Unless you have a strong opinion about that, let's keep it that way.
</blockquote></details>

Not insisting, but here is why I think it would be better to move it out:
* Saves spawing a task when not needed. This kind of basic validations don't need to be a separated task.
* In invalid cases (such as blob.height > current_height) you could return immediately with an informative error.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 139 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXMDXW1fQwGrlRxVmS:-OFah3yN85Cd4BZONndk:b32v57) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L139)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

extract to a function  should_write_blob().
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2025-01-02 14:18 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 2 of 10 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRGpafEXOc0CjqQs87:-OFbICfv3BVeW8ZH3WFF:b-qkfygx) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L136)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not insisting, but here is why I think it would be better to move it out:
* Saves spawing a task when not needed. This kind of basic validations don't need to be a separated task.
* In invalid cases (such as blob.height > current_height) you could return immediately with an informative error.
</blockquote></details>

Although I do not entirely agree with the separation, I would do that because you both asked, but there is technical complexity. Unless we decide we don't care to clone the blob object (which can be very big) in each writing, that means returning locked objects between functions and returning a reference from a function, which will make it harder to understand and refactor in need.
I added a todo for that.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 139 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXMDXW1fQwGrlRxVmS:-OFbLJ7T2jmLUr76SZu_:bhnwk7e) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L139)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

+1
</blockquote></details>

added a todo
___
*[`crates/starknet_integration_tests/src/utils.rs` line 128 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXJiDb3T2h5mDl8BHD:-OFaCR8PAuWZ0ZUGJhcM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/starknet_integration_tests/src/utils.rs#L128)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please move this to be near the spawning of the rpc state reader server.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXHGzm6YGdKNHdifFM:-OFa8-cM3VNv3ArVX4gr:b-6jjvdx) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L16)):*
> ```XML
> #[tokio::test]
> async fn write_prev_height_blob(
>     #[case] status_code: usize,
> ```

I think this is clear from the context


<!-- Sent from Reviewable.io -->

2025-01-05 05:40 UTC, Yael-Starkware requested changes
> Reviewed 1 of 2 files at r4, 1 of 6 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, and @Itay-Tsabary-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXHGzm6YGdKNHdifFM:-OFoxZSKAp3wfwYgWlj7:b-ych8wg) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L16)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I think this is clear from the context
</blockquote></details>

I actually had to read the docs to be sure it is the return value and not some input to verify.
"return_code/return_status_code" is also fine.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 139 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXMDXW1fQwGrlRxVmS:-OFoyNI-2aUHAbDhd9IC:blngvkz) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L139)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

added a todo
</blockquote></details>

ack, if it makes it easier to apply in a separate PR.
___
*[`temp.txt` line 1 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFoxIc14Kjmv8z4TbNP:-OFoxIc14Kjmv8z4TbNQ:bcrh3tm) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec5fd61ea000bc2d31002113a1b61e55440fac03/temp.txt#L1)):*
> ```help
> 
> ```

please remove this file from the PR


<!-- Sent from Reviewable.io -->

2025-01-05 07:34 UTC, dafnamatsry requested changes
> Reviewed 3 of 6 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @DvirYo-starkware, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRGpafEXOc0CjqQs87:-OFpN1eb17RyNryOLIIY:bodsmb7) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L136)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Although I do not entirely agree with the separation, I would do that because you both asked, but there is technical complexity. Unless we decide we don't care to clone the blob object (which can be very big) in each writing, that means returning locked objects between functions and returning a reference from a function, which will make it harder to understand and refactor in need.
I added a todo for that.
</blockquote></details>

We don't want to clone it.
But not sure I understand the complexity, can you elaborate?
Also, I don't see anything wrong with returning a reference from a function.


<!-- Sent from Reviewable.io -->

2025-01-05 10:13 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXHGzm6YGdKNHdifFM:-OFpwJOq18-kGUIiEx1h:befabkj) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/sequencing/papyrus_consensus_orchestrator/src/cende/cende_test.rs#L16)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I actually had to read the docs to be sure it is the return value and not some input to verify.
"return_code/return_status_code" is also fine.
</blockquote></details>

Done. We call this value `status_code` in other tests in the rep.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRGpafEXOc0CjqQs87:-OFpwX6A61lNZxAmFCP9:b-u3rfl1) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L136)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We don't want to clone it.
But not sure I understand the complexity, can you elaborate?
Also, I don't see anything wrong with returning a reference from a function.
</blockquote></details>

עד כמה שניסיתי, אם מחזירים רפרנס לאובייקט בתוך מוטקס צריך עדין להיות עם נעילה על המוטקס וזה נהיה קצת מסורבל ולא נעים טכנית ולקורא.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 139 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFXMDXW1fQwGrlRxVmS:-OFpwte39V3cJ7PZqVXC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/01ab55fc5d53d698f0f82c534eeba77a55145cc9/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L139)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

ack, if it makes it easier to apply in a separate PR.
</blockquote></details>

Done.
___
*[`temp.txt` line 1 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFoxIc14Kjmv8z4TbNP:-OFpw3YQ9LyaY-nDQAdo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec5fd61ea000bc2d31002113a1b61e55440fac03/temp.txt#L1)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

please remove this file from the PR
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-05 12:21 UTC, Yael-Starkware approved these changes
> Reviewed 1 of 2 files at r4, 1 of 3 files at r7, 2 of 6 files at r8, 1 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, and @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 12:28 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, and @Itay-Tsabary-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFRGpafEXOc0CjqQs87:-OFqQv5zCwLKM0xlvRWV:bb7rcol) ([raw file](https://github.com/starkware-libs/sequencer/blob/608d5fa343231717a35fa202422caec206d74270/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L136)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

עד כמה שניסיתי, אם מחזירים רפרנס לאובייקט בתוך מוטקס צריך עדין להיות עם נעילה על המוטקס וזה נהיה קצת מסורבל ולא נעים טכנית ולקורא.
</blockquote></details>

I don't think you can pass a locked object between threads. 


<!-- Sent from Reviewable.io -->

2025-01-05 12:58 UTC, dafnamatsry approved these changes
> Reviewed 2 of 5 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware, @Itay-Tsabary-Starkware, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 13:01 UTC, Yael-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 14:27 UTC, Itay-Tsabary-Starkware requested changes
> Reviewed 1 of 6 files at r8, 2 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`-- commits` line 2 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFqqyri3YfbHOtkKWNv:-OFqqyrjA38DupME20FH:be7obr5):*
Conceptual <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but:
1. Please wait with this until we discuss the system test implication with @dan-starkware 
2. There's a conflict with `main`



_Code quote:_
```
New commits in r11 on 05/01/2025 at 14:38, probably rebased from r10:
- 49ca25e: refactor(sequencing): cende context, add logic and tests
```


<!-- Sent from Reviewable.io -->

2025-01-05 16:12 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 22 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OFrEJV95HTZwJKJAAqu:-OFrEJV95HTZwJKJAAqv:bt3uxks) ([raw file](https://github.com/starkware-libs/sequencer/blob/0685a6e9e0b977958211ecf176771a6f1af112de/crates/starknet_integration_tests/src/integration_test_setup.rs#L22)):*
> ```XML
> use crate::config_utils::dump_config_file_changes;
> use crate::state_reader::StorageTestSetup;
> use crate::utils::{create_node_config, spawn_success_recorder};
> ```

rebase things


<!-- Sent from Reviewable.io -->

2025-01-07 08:53 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r4, 1 of 3 files at r7, 2 of 5 files at r10, 1 of 3 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-:-OFzy-1G6NqXEq7IWgxe:bnfp4nl)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2025-01-07 10:01 UTC, dafnamatsry requested changes
> Reviewed 4 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 113 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-OG-9w264ztFLh_7sl2-:-OG-9w264ztFLh_7sl20:b-gajhq1) ([raw file](https://github.com/starkware-libs/sequencer/blob/976cfda897a6617a9476d9c65f52bad28875c5b1/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L113)):*
> ```XML
>                 current_height
>             );
>             return tokio::spawn(ready(true));
> ```

Either:
* Change the return value to somthing like `Result<Joinhandle<bool>>` and return `Err(Skipped)` or something like that.
* Split to 2 functions: `should_write` and `write`.



_Code quote:_
```XML
return tokio::spawn(ready(true));
```


<!-- Sent from Reviewable.io -->

2025-01-07 12:11 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007#-:-OG-fMc27RCwP-yVnuUQ:bnfp4nl)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2025-01-07 12:30 UTC, DvirYo-starkware reviewed
> Reviewed 1 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2025-01-07 12:30 UTC, DvirYo-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3007)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2025-01-07 12:36 UTC, merged