chore(blockifier): add nstive stack config to vc
starkware-libs/sequencer pull request #3008
Opened 2024-12-29 16:08 UTC by AvivYossef-starkware

2024-12-29 16:08 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3008)
<!-- Reviewable:end -->

2024-12-29 16:08 UTC, AvivYossef-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3008?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3008** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3008?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3008?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#3003** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3003?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main-v0.13.4`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-29 16:10 UTC, AvivYossef-starkware reviewed
wait to python PR 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3008#-:-OFIAhTM2Ro_JwiAdJmb:b-l2m8cn)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-30 07:48 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3008)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3008#-OFLXFyH7qv0jRhCLjWX:-OFLXFyH7qv0jRhCLjWY:b1tu0fz) ([raw file](https://github.com/starkware-libs/sequencer/blob/63df17f3de7cf0279f2716ddfb9a735fa150ade8/crates/blockifier/resources/versioned_constants_0_13_4.json#L65)):*
> ```JSON
>         "min_stack_red_zone": 2,
>         "buffer_size": 1
>     },
> ```

Set it like this on all files (weird to have max_stack_size 0, even if not reachable in regular flows)



_Code quote:_
```JSON
    "cairo_native_stack_config": {
        "gas_to_stack_ratio": [
            1,
            20
        ],
        "max_stack_size": 170,
        "min_stack_red_zone": 2,
        "buffer_size": 1
    },
```


<!-- Sent from Reviewable.io -->

2024-12-30 12:26 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3008)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3008#-OFLXFyH7qv0jRhCLjWX:-OFMX2-MBmeG_fVci2Kj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63df17f3de7cf0279f2716ddfb9a735fa150ade8/crates/blockifier/resources/versioned_constants_0_13_4.json#L65)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Set it like this on all files (weird to have max_stack_size 0, even if not reachable in regular flows)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-30 12:48 UTC, AvivYossef-starkware reviewed
[python](https://reviewable.io/reviews/starkware-industries/starkware/36588)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3008#-:-OFMb2Lq87JrEZsWEjOg:byci1r)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-31 08:40 UTC, Yoni-Starkware requested changes
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3008)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/3008#-OFQrttN2fHlUCeB2QWT:-OFQrttOBkwJcIF_3JqM:bmixj27) ([raw file](https://github.com/starkware-libs/sequencer/blob/64bddabda2698c8738f7ca17e676d10dbda237d8/crates/blockifier/src/execution/native/entry_point_execution.rs#L28)):*
> ```XML
>     let entry_point = compiled_class.get_entry_point(&call)?;
> 
>     let stack_config = context.cairo_native_stack_config.clone();
> ```

Why clone?



_Code quote:_
```XML
context.cairo_native_stack_config.clone();
```


<!-- Sent from Reviewable.io -->

2025-01-01 07:44 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3008)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/3008#-OFQrttN2fHlUCeB2QWT:-OFVakUYADYDgObqt1am:bs4vqr6) ([raw file](https://github.com/starkware-libs/sequencer/blob/64bddabda2698c8738f7ca17e676d10dbda237d8/crates/blockifier/src/execution/native/entry_point_execution.rs#L28)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why clone?
</blockquote></details>

Move of context occurs one line below, but I can borrow it from syscall_handler instead 


<!-- Sent from Reviewable.io -->

2025-01-01 07:50 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3008#-:-OFVpxcq7Vm5Ft0QRqAl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 09:35 UTC, Yoni-Starkware approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3008)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2025-02-24 08:06 UTC, closed without merging