feat(consensus): pass l2_gas_price in validate and build proposal
starkware-libs/sequencer pull request #3017
Opened 2024-12-30 11:01 UTC by ayeletstarkware

2024-12-30 11:01 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3017)
<!-- Reviewable:end -->

2024-12-30 11:02 UTC, ayeletstarkware commented
* **#3017** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3017?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3017?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-02 12:50 UTC, alonh5 requested changes
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3017)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3017#-OFb2g-22XbbpfQjQ6H3:-OFb2g-36FcbFIp8fTbH:b-6s1due) ([raw file](https://github.com/starkware-libs/sequencer/blob/732304ba8c1c7bac65a08ef94e14760fd8334035/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L69)):*
> ```XML
> 
> // TODO(Dan, Matan): Remove this once and replace with real gas prices.
> const TEMPORARY_GAS_PRICES: GasPrices = GasPrices {
> ```

Can you keep this for now and use it in `gas_prices()`?


<!-- Sent from Reviewable.io -->

2025-01-02 13:38 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3017)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3017#-OFb2g-22XbbpfQjQ6H3:-OFbELlV4kKd4QIKEaap:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/732304ba8c1c7bac65a08ef94e14760fd8334035/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L69)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you keep this for now and use it in `gas_prices()`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-05 10:54 UTC, alonh5 requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3017)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @matan-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3017#-OFq5HOKAOg5lQA7dWOF:-OFq5HOKAOg5lQA7dWOG:b1cw1pb) ([raw file](https://github.com/starkware-libs/sequencer/blob/333696719ffbab015cc55443b979c7b805dd7b22/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L75)):*
> ```XML
>         ),
>         Felt::from_hex_unchecked(
>             "0x5ec39365c6bbf631f3957f41d7b972f1c57e12544484b1db53458de03714b19",
> ```

Does this change make sense or are we still not sure why it changed again?


<!-- Sent from Reviewable.io -->

2025-01-05 11:23 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3017)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @matan-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3017#-OFq5HOKAOg5lQA7dWOF:-OFqBwQiAaPht1Hk6R61:b-p2zct1) ([raw file](https://github.com/starkware-libs/sequencer/blob/333696719ffbab015cc55443b979c7b805dd7b22/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L75)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Does this change make sense or are we still not sure why it changed again?
</blockquote></details>

it makes sense, it's related to a change that was merged into this file 


<!-- Sent from Reviewable.io -->

2025-01-05 12:00 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3017#-:-OFqKW3N9OzN1YQrfYuM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 12:16 UTC, matan-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3017)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2025-01-05 12:28 UTC, merged