feat(blockifier): support reverted sierra gas tracking and charging
starkware-libs/sequencer pull request #3019
Opened 2024-12-30 12:11 UTC by dorimedini-starkware

2024-12-30 12:11 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3019)
<!-- Reviewable:end -->

2024-12-30 12:11 UTC, dorimedini-starkware commented
* **#3020** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3020?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3019** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3019?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3019?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main-v0.13.4`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-30 13:15 UTC, Yoni-Starkware requested changes
Don't forget the Native syscall handler

> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-:-OFMh7vIEYFKaS2uVUQx:b-aa0887)* status: 1 of 10 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMfy_q72K7aIW7ih0H:-OFMfy_r8D60u35eIt67:b-h5st6e) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L175)):*
> ```XML
>             // If the execution of the outer call failed, revert the transction.
>             if call_info.execution.failed {
>                 context.update_revert_gas_with_next_remaining_gas(GasAmount(*remaining_gas));
> ```

Cool. This should work since `self.execute` updates it



_Code quote:_
```XML
remaining_gas
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 226 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMgAeF9vLyO9Tdw2rG:-OFMgAeF9vLyO9Tdw2rH:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L226)):*
> ```XML
>     }
> 
>     /// Given the next remaining gas (before entering the next syscall), updates the consumed gas
> ```





_Suggestion:_
```XML
as,
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMgjWMEKyPUzGaYlAl:-OFMgjWMEKyPUzGaYlAm:b-rqc3id) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L229)):*
> ```XML
>     /// (difference between previous and next remaining gas) and then updates the last seen
>     /// remaining gas.
>     pub fn update_with_next_remaining_gas(&mut self, next_remaining_gas: GasAmount) {
> ```

Make it private



_Suggestion:_
```XML
   fn 
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 230 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMgm3G2NQkmfbuWBok:-OFMgm3H2ccxiFnHK1NY:b-4meriv) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L230)):*
> ```XML
>     /// remaining gas.
>     pub fn update_with_next_remaining_gas(&mut self, next_remaining_gas: GasAmount) {
>         // Only track sierra gas for reverts if tracking gas.
> ```

Not relevant for this function, right?



_Code quote:_
```XML
        // Only track sierra gas for reverts if tracking gas.
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 513 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMgWKA3TlUNMWbIMCq:-OFMgWKA3TlUNMWbIMCr:b-9vhg9r) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L513)):*
> ```XML
>     };
> 
>     // TODO: On error, compute sierra gas consumed and charge for blockifier revert flow.
> ```

Already supported


<!-- Sent from Reviewable.io -->

2024-12-30 13:21 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMfy_q72K7aIW7ih0H:-OFMib8d7UiuKbpondSW:bh3cu27) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L175)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Cool. This should work since `self.execute` updates it
</blockquote></details>

discussing offline, not so sure this will work
___
*[`crates/blockifier/src/execution/entry_point.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMgjWMEKyPUzGaYlAl:-OFMiDrFELRjJLSZe1ol:bu9on6x) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L229)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Make it private
</blockquote></details>

can't, see usage in non_reverting_execute (the context no longer has the tracked resource stack)
___
*[`crates/blockifier/src/execution/entry_point.rs` line 230 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMgm3G2NQkmfbuWBok:-OFMiWLG7JPKEqRAE54f:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L230)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not relevant for this function, right?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 513 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMgWKA3TlUNMWbIMCq:-OFMiZNr5a2Spx4rWqYK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L513)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Already supported
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-30 13:26 UTC, dorimedini-starkware reviewed
done

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-:-OFMjTI11f7hX_rIDZ0S:bb7f2mf)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-12-30 13:43 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019)* status: 1 of 11 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 248 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMn_eeA1uS55-6vyFq:-OFMn_efAv9I3je4Qa-D:b-y903oq) ([raw file](https://github.com/starkware-libs/sequencer/blob/e020b711ee38ed35dddce85e1d84aa411aa181b3/crates/blockifier/src/execution/entry_point.rs#L248)):*
> ```XML
>                     self.sierra_gas_consumed_so_far
>                 )
>             });
> ```

shouldn't these be saturating? we don't want to panic when computing revert gas, right?



_Code quote:_
```XML
            self.last_seen_remaining_gas.checked_sub(next_remaining_gas).unwrap_or_else(|| {
                panic!(
                    "Next remaining gas higher than last. Last seen remaining gas: {}, next \
                     remaining gas: {next_remaining_gas}.",
                    self.last_seen_remaining_gas
                )
            });
        self.sierra_gas_consumed_so_far =
            self.sierra_gas_consumed_so_far.checked_add(next_gas_consumed).unwrap_or_else(|| {
                panic!(
                    "Sierra gas consumed overflowed. Last consumed gas: {}, extra consumed gas: \
                     {next_gas_consumed}.",
                    self.sierra_gas_consumed_so_far
                )
            });
```


<!-- Sent from Reviewable.io -->

2024-12-31 08:30 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMfy_q72K7aIW7ih0H:-OFQpBT3AkLQ7D9_uWjX:bl5c93w) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L175)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

discussing offline, not so sure this will work
</blockquote></details>

Should work since this code visited [this line](https://github.com/starkware-libs/sequencer/blob/855d985bc003962473afd49bfef7dfbdf9e7937e/crates/blockifier/src/execution/execution_utils.rs#L87) before
___
*[`crates/blockifier/src/execution/entry_point.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMgjWMEKyPUzGaYlAl:-OFQpR5x2Wo3MKNe3tHp:b-855whv) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L229)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can't, see usage in non_reverting_execute (the context no longer has the tracked resource stack)
</blockquote></details>

But you do have the tracked resource in that context (call_info.tracked_resource). 
To be on the safe side, please change this function to get the tracked resource as arg.


<!-- Sent from Reviewable.io -->

2024-12-31 08:50 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFMgjWMEKyPUzGaYlAl:-OFQtwUWD3-eTRevyM1y:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7001d9ddfc1812c9a81d033ae5b6efee0e97cf9b/crates/blockifier/src/execution/entry_point.rs#L229)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

But you do have the tracked resource in that context (call_info.tracked_resource). 
To be on the safe side, please change this function to get the tracked resource as arg.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-31 09:08 UTC, Yoni-Starkware requested changes
> Reviewed 4 of 10 files at r1, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 178 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFQwSvRAzCZUe4N0jKa:-OFQwSvS264ATOiygm99:bksgjys) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e7669a97691f455319c7da2b22ed314e2232c90/crates/blockifier/src/execution/entry_point.rs#L178)):*
> ```XML
>                     call_info.tracked_resource,
>                     GasAmount(*remaining_gas),
>                 );
> ```

For completeness, let's always update this. This way, its gas_consumed should always match the actual gas consumed. You can add an assert here and run the CI for sanity



_Suggestion:_
```XML
        if let Ok(call_info) = &execution_result {
            context.sierra_gas_revert_tracker.update_with_next_remaining_gas(
                call_info.tracked_resource,
                GasAmount(*remaining_gas),
            );
            // If the execution of the outer call failed, revert the transction.
            if call_info.execution.failed {
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 227 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFQy1mO5aVoZLUigVaY:-OFQy1mO5aVoZLUigVaZ:b-cg30hp) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e7669a97691f455319c7da2b22ed314e2232c90/crates/blockifier/src/execution/entry_point.rs#L227)):*
> ```XML
>     pub fn new_validate() -> Self {
>         Self::new_execute(GasAmount::MAX)
>     }
> ```

You are right but this object is out there and the reverted gas consumed is determined by the initial value. If it's easy, better to inject the true initial value in any case.



_Code quote:_
```XML
    /// In validate, we cannot charge for reverted gas, so the values are meaningless.
    pub fn new_validate() -> Self {
        Self::new_execute(GasAmount::MAX)
    }
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 451 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFQvWD_3E3SNwOACHdw:-OFQvWD_3E3SNwOACHdx:b-r0t8fj) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e7669a97691f455319c7da2b22ed314e2232c90/crates/blockifier/src/execution/entry_point.rs#L451)):*
> ```XML
>     /// Calls update_with_next_remaining_gas if the tracked resource is sierra gas.
>     pub fn update_revert_gas_with_next_remaining_gas(&mut self, next_remaining_gas: GasAmount) {
>         if let Some(tracked_resource) = self.tracked_resource_stack.last() {
> ```

Enforce this. It must exist at this point.



_Code quote:_
```XML
if let Some(tracked_resource) = self.tracked_resource_stack.last() {
```


<!-- Sent from Reviewable.io -->

2024-12-31 10:16 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 178 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFQwSvRAzCZUe4N0jKa:-OFRAtJJC7AcGJkPsZAF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e7669a97691f455319c7da2b22ed314e2232c90/crates/blockifier/src/execution/entry_point.rs#L178)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

For completeness, let's always update this. This way, its gas_consumed should always match the actual gas consumed. You can add an assert here and run the CI for sanity
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 227 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFQy1mO5aVoZLUigVaY:-OFRCSfbCAD5RixaEhSe:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e7669a97691f455319c7da2b22ed314e2232c90/crates/blockifier/src/execution/entry_point.rs#L227)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You are right but this object is out there and the reverted gas consumed is determined by the initial value. If it's easy, better to inject the true initial value in any case.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 451 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFQvWD_3E3SNwOACHdw:-OFRCdoL2apDEMs-xN4W:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e7669a97691f455319c7da2b22ed314e2232c90/crates/blockifier/src/execution/entry_point.rs#L451)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Enforce this. It must exist at this point.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-31 11:43 UTC, Yoni-Starkware reviewed
> Reviewed 3 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 16:13 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-:-OFXd7AmD6h0OQekewlu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 18:40 UTC, Yoni-Starkware approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 10:35 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 233 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFa_G0RBIb3-HH7TK_u:-OFa_G0RBIb3-HH7TK_v:b-ti5x66) ([raw file](https://github.com/starkware-libs/sequencer/blob/2aaa71eedf82eaf66315c40f6cc24b8b65f823af/crates/blockifier/src/execution/entry_point.rs#L233)):*
> ```XML
>     }
> 
>     pub fn get_gas_consumed(&self, initial_gas: GasAmount) -> GasAmount {
> ```

Why not save it on the struct (at the construction)?



_Code quote:_
```XML
initial_gas
```


<!-- Sent from Reviewable.io -->

2025-01-02 10:40 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 233 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-OFa_G0RBIb3-HH7TK_u:-OFaaIKR1D72GnIwjpQA:b-4ncwqd) ([raw file](https://github.com/starkware-libs/sequencer/blob/2aaa71eedf82eaf66315c40f6cc24b8b65f823af/crates/blockifier/src/execution/entry_point.rs#L233)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not save it on the struct (at the construction)?
</blockquote></details>

good idea, done


<!-- Sent from Reviewable.io -->

2025-01-02 12:05 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3019#-:-OFatyPRAjttnrpXrD8d:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 13:09 UTC, merged