feat(blockifier): only consume a step in the VM if we are tracking steps
starkware-libs/sequencer pull request #3020
Opened 2024-12-30 12:11 UTC by dorimedini-starkware

2024-12-30 12:11 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3020)
<!-- Reviewable:end -->

2024-12-30 12:11 UTC, dorimedini-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3020?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3020** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3020?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3020?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#3019** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3019?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main-v0.13.4`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-30 13:29 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 446 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFMkSiB9aB_BUlNiPYW:-OFMkSiB9aB_BUlNiPYX:bavy4gc) ([raw file](https://github.com/starkware-libs/sequencer/blob/9fac26e6a711d564823288fe32618f8ef7ac3cf1/crates/blockifier/src/transaction/account_transactions_test.rs#L446)):*
> ```XML
> /// Tests that validation fails on out-of-gas if L2 gas bound is too low.
> #[rstest]
> fn test_max_fee_limit_validate(
> ```

note that we cannot really test this anymore unless user signs on L2 bounds



_Code quote:_
```XML
/// Tests that validation fails on out-of-gas if L2 gas bound is too low.
#[rstest]
fn test_max_fee_limit_validate(
```


<!-- Sent from Reviewable.io -->

2024-12-31 14:52 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFSC5pq0AdcE17RZYXQ:-OFSC5pr7f_9jfat1TSA:b-2y2l7x) (no related file):*
[py side](https://reviewable.io/reviews/starkware-industries/starkware/36605)


<!-- Sent from Reviewable.io -->

2024-12-31 16:29 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFSC5pq0AdcE17RZYXQ:-OFSYFbA1P_jxSOA8O8z:b-m6tflo) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[py side](https://reviewable.io/reviews/starkware-industries/starkware/36605)
</blockquote></details>

passes


<!-- Sent from Reviewable.io -->

2025-01-01 16:17 UTC, TzahiTaub requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 648 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXSNER4oOUhbI2lmj3:-OFXSNER4oOUhbI2lmj4:b-hsv07f) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/execution/syscalls/hint_processor.rs#L648)):*
> ```XML
> 
>     fn consume_step(&mut self) {
>         // Only consume steps if the current resource is a CairoSteps resource.
> ```

I think it should be a docstring and not a comment.



_Code quote:_
```XML
  // Only consume steps if the current resource is a CairoSteps resource.
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 653 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXS5yT5dzpFYX1c5p3:-OFXS5yU18sDsFTiJ1Ng:bgz0rqe) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/execution/syscalls/hint_processor.rs#L653)):*
> ```XML
>                 self.base.context.vm_run_resources.consume_step();
>             }
>             Some(TrackedResource::SierraGas) | None => (),
> ```

AFAIU, the `None` should never be reached. I think it's should be asserted to not be None, or at least, print a debug message in this case.



_Code quote:_
```XML
        Some(TrackedResource::SierraGas) | None => (),
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 480 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXUanI0TgCBIwfTkFZ:-OFXUanI0TgCBIwfTkF_:bp47pmy) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L480)):*
> ```XML
>     // We want to test the block step bounds here - so set them to something low.
>     let old_validate_max_n_steps = block_context.versioned_constants.validate_max_n_steps;
>     block_context.versioned_constants.validate_max_n_steps = 1000;
> ```

I'm kind of confused - we needed to set a low max when we ran with steps, but we don't do it now and it's OK? Was this made just to get a quick failure? Please remove the steps update and replace it with a gas update.



_Code quote:_
```XML
    // We want to test the block step bounds here - so set them to something low.
    let old_validate_max_n_steps = block_context.versioned_constants.validate_max_n_steps;
    block_context.versioned_constants.validate_max_n_steps = 1000;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 982 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXWBlw1_3DI7zXMaj5:-OFXWBlw1_3DI7zXMaj6:b-xh87ya) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L982)):*
> ```XML
>         CairoVersion::Cairo1(_) => TrackedResource::SierraGas,
>         CairoVersion::Cairo0 => TrackedResource::CairoSteps,
>     };
> ```

I have some problems with this, we have the `CompilerBasedVersion` that is exactly meant for this, should probably replace the CairoVersion in here.



_Code quote:_
```XML
    let tracked_resource = match cairo_version {
        CairoVersion::Cairo1(_) => TrackedResource::SierraGas,
        CairoVersion::Cairo0 => TrackedResource::CairoSteps,
    };
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1052 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXd1ASDnmSCSiRox2V:-OFXd1ASDnmSCSiRox2W:beh7skc) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L1052)):*
> ```XML
>             actual_resources_0.n_reverted_steps += single_call_units_delta;
>             assert_eq!(actual_resources_0, actual_resources_1);
>             actual_resources_0.vm_resources.n_steps = n_units_0;
> ```

Shouldn't this be an assertion? Same for the gas below.



_Code quote:_
```XML
  actual_resources_0.vm_resources.n_steps = n_units_0;
```


<!-- Sent from Reviewable.io -->

2025-01-01 16:22 UTC, TzahiTaub requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1348 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXekxQAVzTPys9Wa0E:-OFXekxQAVzTPys9Wa0F:b-o4uenq) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L1348)):*
> ```XML
>             // within a sane range.
>             assert!(tx_execution_info3.revert_error.unwrap().to_string().contains("Out of gas"));
>             assert!(Fee(2 * tx_execution_info3.receipt.fee.0) >= tx_execution_info1.receipt.fee);
> ```

Why doesn't an out-of-gas tx necessarily charge more than a successful one?



_Code quote:_
```XML
  assert!(Fee(2 * tx_execution_info3.receipt.fee.0) >= tx_execution_info1.receipt.fee);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1351 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXezY7DO9ECzdwFVzy:-OFXezY7DO9ECzdwFVzz:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L1351)):*
> ```XML
>         }
>         (CairoVersion::Cairo1(RunnableCairo1::Casm), ValidResourceBounds::L1Gas(l1_bound)) => {
>             // If a user supplied L1 gas bounds only, sierra gas is not limitted in proportion to
> ```





_Suggestion:_
```XML
limited 
```


<!-- Sent from Reviewable.io -->

2025-01-01 16:49 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 446 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFMkSiB9aB_BUlNiPYW:-OFXl7aCEiEBEZd-obv8:b-m5ktdf) ([raw file](https://github.com/starkware-libs/sequencer/blob/9dc9a2126e98a3a955459d97d0c44bdedd0c6eb4/crates/blockifier/src/transaction/account_transactions_test.rs#L446)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

note that we cannot really test this anymore unless user signs on L2 bounds
</blockquote></details>

So all step tests are gone?
Is there an easy way to keep them? manipulating the sierra-version-for-sierra-gas config?


<!-- Sent from Reviewable.io -->

2025-01-01 18:06 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 648 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXSNER4oOUhbI2lmj3:-OFY0WnS4enXqmQjx-Bu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/execution/syscalls/hint_processor.rs#L648)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I think it should be a docstring and not a comment.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 653 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXS5yT5dzpFYX1c5p3:-OFY0XTx3PgxEqPFi_ec:b-2ab9v4) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/execution/syscalls/hint_processor.rs#L653)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

AFAIU, the `None` should never be reached. I think it's should be asserted to not be None, or at least, print a debug message in this case.
</blockquote></details>

Done. @Yoni-Starkware another potential panic location, is that ok?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 446 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFMkSiB9aB_BUlNiPYW:-OFXvpwZ25nSBU_s4EuR:b-ffkyfc) ([raw file](https://github.com/starkware-libs/sequencer/blob/9dc9a2126e98a3a955459d97d0c44bdedd0c6eb4/crates/blockifier/src/transaction/account_transactions_test.rs#L446)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

So all step tests are gone?
Is there an easy way to keep them? manipulating the sierra-version-for-sierra-gas config?
</blockquote></details>

all step tests that use cairo0 contracts are still in place.
now we have some "disjoint coverage": e.g. `test_infinite_recursion` uses cairo0 contracts.
`test_reverted_reach_steps_limit` is parametrized in the next PR, and `test_n_reverted_steps` is parametrized here.

A good task to do while we are in integration with 0.13.4: go over the tests here, and parametrize what is "only for steps" or "only for L1 bounds / all bounds". WDYT?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 480 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXUanI0TgCBIwfTkFZ:-OFXy2IQB6yu2DtsEsKD:b-qlyknz) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L480)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I'm kind of confused - we needed to set a low max when we ran with steps, but we don't do it now and it's OK? Was this made just to get a quick failure? Please remove the steps update and replace it with a gas update.
</blockquote></details>

Was made for quick failure.
Done.
I also kept the step bound adjustment, in case we parametrize this test back later
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1052 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXd1ASDnmSCSiRox2V:-OFY-5CGEomhvXm3qfoY:b-s1f6ga) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L1052)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Shouldn't this be an assertion? Same for the gas below.
</blockquote></details>

we expect (IIUC how this test was built) that the number of spent steps without reverted steps is the same, both in run 0 and in run 1. we assert equality on the antire resources struct, except for the reverted steps. since actual_resources_0 is not used again after this `match`, not sure why the value was changed; deleted these lines.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1348 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXekxQAVzTPys9Wa0E:-OFY-rUW0wGcCLnmxa5f:b-y58871) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L1348)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why doesn't an out-of-gas tx necessarily charge more than a successful one?
</blockquote></details>

because a successful one can also add extra costs in L2 gas units - events, etc.
I am missing the other inequality direction though... adding
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1351 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXezY7DO9ECzdwFVzy:-OFY0Prz5RSdYCp24LTA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L1351)):*
> ```XML
>         }
>         (CairoVersion::Cairo1(RunnableCairo1::Casm), ValidResourceBounds::L1Gas(l1_bound)) => {
>             // If a user supplied L1 gas bounds only, sierra gas is not limitted in proportion to
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 18:31 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 653 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXS5yT5dzpFYX1c5p3:-OFY7H9A4OmlIRhVF6Jp:bb7k0qh) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/execution/syscalls/hint_processor.rs#L653)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done. @Yoni-Starkware another potential panic location, is that ok?
</blockquote></details>

lgtm
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 446 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFMkSiB9aB_BUlNiPYW:-OFY7VriErijRevvY1a1:bf76dd) ([raw file](https://github.com/starkware-libs/sequencer/blob/9dc9a2126e98a3a955459d97d0c44bdedd0c6eb4/crates/blockifier/src/transaction/account_transactions_test.rs#L446)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

all step tests that use cairo0 contracts are still in place.
now we have some "disjoint coverage": e.g. `test_infinite_recursion` uses cairo0 contracts.
`test_reverted_reach_steps_limit` is parametrized in the next PR, and `test_n_reverted_steps` is parametrized here.

A good task to do while we are in integration with 0.13.4: go over the tests here, and parametrize what is "only for steps" or "only for L1 bounds / all bounds". WDYT?
</blockquote></details>

Sounds good. And I think that by changing the VC, we can test both steps and sierra gas in the same test (with cairo 1)


<!-- Sent from Reviewable.io -->

2025-01-01 18:33 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 653 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXS5yT5dzpFYX1c5p3:-OFY8Amx2wiC0wxq7828:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/execution/syscalls/hint_processor.rs#L653)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 18:45 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 446 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFMkSiB9aB_BUlNiPYW:-OFYAI7HBhYN1uYgPUY_:b-t3hdzs) ([raw file](https://github.com/starkware-libs/sequencer/blob/9dc9a2126e98a3a955459d97d0c44bdedd0c6eb4/crates/blockifier/src/transaction/account_transactions_test.rs#L446)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Sounds good. And I think that by changing the VC, we can test both steps and sierra gas in the same test (with cairo 1)
</blockquote></details>

we can probably do it without VC change - using the `units` trick I use in these tests


<!-- Sent from Reviewable.io -->

2025-01-02 11:41 UTC, TzahiTaub approved these changes
> Reviewed 1 of 3 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1052 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXd1ASDnmSCSiRox2V:-OFaj_wC6XlpBKNlVMja:but0gfd) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L1052)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we expect (IIUC how this test was built) that the number of spent steps without reverted steps is the same, both in run 0 and in run 1. we assert equality on the antire resources struct, except for the reverted steps. since actual_resources_0 is not used again after this `match`, not sure why the value was changed; deleted these lines.
</blockquote></details>

I think it was meant to verify (thus should have been an assert) that the `total_charged_computation_units` or unit_0 (steps before the change) is exactly the "valid" resources from the computation, i.e., that n_reverted_steps == 0. Maybe this should be asserted.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1348 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXekxQAVzTPys9Wa0E:-OFaoNMx4nkcgS6y6b5x:b-y37c7p) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L1348)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because a successful one can also add extra costs in L2 gas units - events, etc.
I am missing the other inequality direction though... adding
</blockquote></details>

I actually meant to ask why doesn't it charge the maximal fee


<!-- Sent from Reviewable.io -->

2025-01-02 12:23 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1052 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXd1ASDnmSCSiRox2V:-OFaxxuy33hGmPGQoNIA:b4bix4d) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L1052)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I think it was meant to verify (thus should have been an assert) that the `total_charged_computation_units` or unit_0 (steps before the change) is exactly the "valid" resources from the computation, i.e., that n_reverted_steps == 0. Maybe this should be asserted.
</blockquote></details>

1. tried, the assert fails; I don't understand what you think should be equal to 0, or to n_units_0?
2. I think the only thing we really want to check is that `actual_resources_0.vm_resources.n_steps == actual_resources_1.vm_resources.n_steps` (and the similar check for gas), which is covered by the object comparison
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1348 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3020#-OFXekxQAVzTPys9Wa0E:-OFauzbgCnVssWTykImt:by1sumz) ([raw file](https://github.com/starkware-libs/sequencer/blob/8065a4391d4aef718d7f08d52953fe9f14c59c99/crates/blockifier/src/transaction/account_transactions_test.rs#L1348)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I actually meant to ask why doesn't it charge the maximal fee
</blockquote></details>

OOG reverts are different from post-execution "out of L2 gas bounds" reverts.
OOG happens mid-execution
(by "maximal fee" you mean "charge for user_bounds.l2_gas.max_amount L2 gas units", right?)


<!-- Sent from Reviewable.io -->

2025-01-02 13:11 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3020)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 13:38 UTC, merged