chore(cairo_native): make the starknet-native-compile crate a part of the workspace
starkware-libs/sequencer pull request #3021
Opened 2024-12-30 13:03 UTC by avi-starkware

2024-12-30 13:13 UTC, noaov1 requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`Cargo.toml` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OFMgU0o5OCc9-4ApPWV:-OFMgU0o5OCc9-4ApPWW:bmp3lmd) ([raw file](https://github.com/starkware-libs/sequencer/blob/b875cc04058c08d4e6ea09c97d8888917eabdd65/Cargo.toml#L60)):*
> ```TOML
> ]
> 
> exclude = ["crates/bin/starknet-native-compile"]
> ```

What does it mean?



_Code quote:_
```TOML
exclude = ["crates/bin/starknet-native-compile"]
```
___
*[`crates/bin/starknet-native-compile/src/utils.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OFMfqHP7pltCKPhGusO:-OFMfqHP7pltCKPhGusP:b-4ss8qq) ([raw file](https://github.com/starkware-libs/sequencer/blob/e03856d007e25648c06c7f32ead848ffad6fa99b/crates/bin/starknet-native-compile/src/utils.rs#L1)):*
> ```XML
> #[cfg(feature = "cairo_native")]
> ```

Is it necessary, considering the file already has the feature flag above its declaration? :thinking: 



_Code quote:_
```XML
#[cfg(feature = "cairo_native")]
```


<!-- Sent from Reviewable.io -->

2024-12-30 13:16 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/bin/starknet-native-compile/Cargo.toml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OFMhKWeEJFPrW4N22Je:-OFMhKWeEJFPrW4N22Jf:bxktll9) ([raw file](https://github.com/starkware-libs/sequencer/blob/e03856d007e25648c06c7f32ead848ffad6fa99b/crates/bin/starknet-native-compile/Cargo.toml#L11)):*
> ```TOML
> 
> [features]
> cairo_native = [
> ```

How do you make sure that the `starknet_sierra_compile` crate uses this crate with the `cairo_native` feature flag?



_Code quote:_
```TOML
cairo_native = [
```


<!-- Sent from Reviewable.io -->

2024-12-30 13:38 UTC, avi-starkware commented
*[`crates/bin/starknet-native-compile/Cargo.toml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OFMhKWeEJFPrW4N22Je:-OFMjVD9DD5WKmPyBxWD:b-m1bb7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/e03856d007e25648c06c7f32ead848ffad6fa99b/crates/bin/starknet-native-compile/Cargo.toml#L11)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

How do you make sure that the `starknet_sierra_compile` crate uses this crate with the `cairo_native` feature flag?
</blockquote></details>

starknet_sierra_compile does not depend on this crate directly it builds it via `cargo install`, so I just add the feature as an argument in `cargo install`


<!-- Sent from Reviewable.io -->

2024-12-30 13:38 UTC, avi-starkware commented
*[`Cargo.toml` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OFMgU0o5OCc9-4ApPWV:-OFMhYfhBNYfxJExjYUu:b-rxx8b7) ([raw file](https://github.com/starkware-libs/sequencer/blob/b875cc04058c08d4e6ea09c97d8888917eabdd65/Cargo.toml#L60)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What does it mean?
</blockquote></details>

It just means that the crate is not part of the workspace and will not be compiled automatically when running `cargo build` from the root dir. I did this to avoid having the entire workspace depend on `cairo_native`.


<!-- Sent from Reviewable.io -->

2025-01-01 17:29 UTC, meship-starkware approved these changes
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-05 21:19 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-06 07:17 UTC, avi-starkware commented
*[`crates/bin/starknet-native-compile/src/utils.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OFMfqHP7pltCKPhGusO:-OFuTD2WDJMscL5ZVn5Z:b-5rfbkg) ([raw file](https://github.com/starkware-libs/sequencer/blob/e03856d007e25648c06c7f32ead848ffad6fa99b/crates/bin/starknet-native-compile/src/utils.rs#L1)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it necessary, considering the file already has the feature flag above its declaration? :thinking:
</blockquote></details>

If we don't put this over each import that is only used with the feature flag, we will get an `unused_import` clippy error


<!-- Sent from Reviewable.io -->

2025-01-06 09:16 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-:-OFutlr0D2pNY7T_loyZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2025-02-02 17:04 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 7 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/starknet_sierra_multicompile/build.rs` line 18 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OI6b6I7DOX8MxJYwQrb:-OI6b6I7DOX8MxJYwQrc:bhdejkm) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a9235bd5b5178a70bd08fa22c3f3016dd4b5bd1/crates/starknet_sierra_multicompile/build.rs#L18)):*
> ```XML
> }
> 
> const REQUIRED_CAIRO_LANG_VERSION: &str = "2.10.0-rc.1";
> ```

ok for the current scope, but... this dep is flaky. is there anything that will prevent a dev from changing the compiler crate deps in the root cargo.toml to a version other than this one?



_Code quote:_
```XML
const REQUIRED_CAIRO_LANG_VERSION: &str = "2.10.0-rc.1";
```
___
*[`crates/starknet_sierra_multicompile/build.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OI6bI4CD3huWNNKGkCR:-OI6bI4CD3huWNNKGkCS:b77nf0j) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a9235bd5b5178a70bd08fa22c3f3016dd4b5bd1/crates/starknet_sierra_multicompile/build.rs#L20)):*
> ```XML
> const REQUIRED_CAIRO_LANG_VERSION: &str = "2.10.0-rc.1";
> #[cfg(feature = "cairo_native")]
> const REQUIRED_CAIRO_NATIVE_VERSION: &str = env!("CARGO_PKG_VERSION");
> ```

this is resolved at compile-time, right?
what does this resolve to during `cargo install` from crates.io?



_Code quote:_
```XML
env!("CARGO_PKG_VERSION");
```
___
*[`crates/bin/starknet-native-compile/src/main.rs` line 61 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OI6ahMiEpoxJuskFqBw:-OI6ahMiEpoxJuskFqBx:bp4gi4r) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a9235bd5b5178a70bd08fa22c3f3016dd4b5bd1/crates/bin/starknet-native-compile/src/main.rs#L61)):*
> ```XML
>         });
>     }
> }
> ```

probably simpler to split into modules... WDYT?



_Suggestion:_
```XML
#[cfg(feature = "cairo_native")]
pub mod cairo_native_main;

fn main() {
    #[cfg(not(feature = "cairo_native"))]
    {
        eprintln!(
            "The `starknet-native-compile` binary was compiled without the 'cairo_native' feature."
        );
        process::exit(1);
    }
    #[cfg(feature = "cairo_native")]
    cairo_native_main::main()
}
```


<!-- Sent from Reviewable.io -->

2025-02-02 17:25 UTC, dorimedini-starkware reviewed
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/starknet_sierra_multicompile/Cargo.toml` line 37 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OI6gMOTDasdE8OUEDKl:-OI6gMOTDasdE8OUEDKm:b-dwxuek) ([raw file](https://github.com/starkware-libs/sequencer/blob/b71a8fa96985f3ee411e745b6c373a2a1f77fef1/crates/starknet_sierra_multicompile/Cargo.toml#L37)):*
> ```TOML
> 
> [build-dependencies]
> starknet-native-compile.path = "../bin/starknet-native-compile"
> ```

build.rs does not run in `cargo install`, right?



_Code quote:_
```TOML
starknet-native-compile.path = "../bin/starknet-native-compile"
```


<!-- Sent from Reviewable.io -->

2025-02-03 07:41 UTC, meship-starkware reviewed
> Reviewed 1 of 7 files at r5, 3 of 6 files at r6, 4 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2025-02-05 09:20 UTC, avi-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/bin/starknet-native-compile/src/main.rs` line 61 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OI6ahMiEpoxJuskFqBw:-OIKJl9o8CIwIt_OK3Ac:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a9235bd5b5178a70bd08fa22c3f3016dd4b5bd1/crates/bin/starknet-native-compile/src/main.rs#L61)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

probably simpler to split into modules... WDYT?
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_multicompile/build.rs` line 18 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OI6b6I7DOX8MxJYwQrb:-OIKHjpb1pLabdJ-HhBW:b-t9vr9) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a9235bd5b5178a70bd08fa22c3f3016dd4b5bd1/crates/starknet_sierra_multicompile/build.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok for the current scope, but... this dep is flaky. is there anything that will prevent a dev from changing the compiler crate deps in the root cargo.toml to a version other than this one?
</blockquote></details>

We will let the people working on the gateway decide how to manage this version.
___
*[`crates/starknet_sierra_multicompile/build.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OI6bI4CD3huWNNKGkCR:-OIKHXVk6LjkK5WKSCOr:b-kqxs15) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a9235bd5b5178a70bd08fa22c3f3016dd4b5bd1/crates/starknet_sierra_multicompile/build.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is resolved at compile-time, right?
what does this resolve to during `cargo install` from crates.io?
</blockquote></details>

It will be resolved at compile time to the version of the workspace
___
*[`crates/starknet_sierra_multicompile/Cargo.toml` line 37 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OI6gMOTDasdE8OUEDKl:-OIKHBirE6HRJKa4-J5L:b1d73qm) ([raw file](https://github.com/starkware-libs/sequencer/blob/b71a8fa96985f3ee411e745b6c373a2a1f77fef1/crates/starknet_sierra_multicompile/Cargo.toml#L37)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

build.rs does not run in `cargo install`, right?
</blockquote></details>

This is an artificial dependency - it doesn't do anything
It is there just to add the dependency to the dependency tree


<!-- Sent from Reviewable.io -->

2025-02-05 09:59 UTC, avi-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/starknet_sierra_multicompile/build.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/3021#-OI6bI4CD3huWNNKGkCR:-OIKY1U48QnmLJtbfhyN:bveueco) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a9235bd5b5178a70bd08fa22c3f3016dd4b5bd1/crates/starknet_sierra_multicompile/build.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

discussed offline (tl;dr: still unclear what happens when externals do `cargo install`)
</blockquote></details>

I changed the version to be explicit, and I will make another PR that adds a test that the version in this constant is the same as the workspace version.


<!-- Sent from Reviewable.io -->

2025-02-05 10:03 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2025-02-06 10:00 UTC, meship-starkware reviewed
> Reviewed 3 of 4 files at r8, 1 of 4 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3021)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2025-03-22 08:05 UTC, closed without merging