test(blockifier): update test_reverted_reach_steps_limit for gas reverts
starkware-libs/sequencer pull request #3024
Opened 2024-12-30 14:35 UTC by dorimedini-starkware

2024-12-30 14:35 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3024)
<!-- Reviewable:end -->

2024-12-30 14:36 UTC, dorimedini-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3024?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3024** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3024?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3024?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#3020** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3020?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3019** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3019?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main-v0.13.4`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-01 16:27 UTC, TzahiTaub requested changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3024)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 852 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3024#-OFXfVyZ62-Itj4ulHIu:-OFXfVyZ62-Itj4ulHIv:baf13cw) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4086cbbf7be7086a18ab75ab479a69d4ea67e07/crates/blockifier/src/transaction/account_transactions_test.rs#L852)):*
> ```XML
>         CairoVersion::Cairo0 => TrackedResource::CairoSteps,
>         CairoVersion::Cairo1(_) => TrackedResource::SierraGas,
>     };
> ```

Consider replacing the CairoVersion with `CompilerBasedVersion` and use `own_tracked_resource`



_Code quote:_
```XML
    let tracked_resource = match cairo_version {
        CairoVersion::Cairo0 => TrackedResource::CairoSteps,
        CairoVersion::Cairo1(_) => TrackedResource::SierraGas,
    };
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 854 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3024#-OFX8ZSw3EZdxIJxCGhT:-OFX8ZSw3EZdxIJxCGhU:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4086cbbf7be7086a18ab75ab479a69d4ea67e07/crates/blockifier/src/transaction/account_transactions_test.rs#L854)):*
> ```XML
>     };
> 
>     // Limit the max amount of computation (so we quickly hit the limit).
> ```





_Suggestion:_
```XML
max amount of computation units
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 946 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3024#-OFXg3BY64eqhcsy6fmH:-OFXg3BY64eqhcsy6fmI:bgah7we) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4086cbbf7be7086a18ab75ab479a69d4ea67e07/crates/blockifier/src/transaction/account_transactions_test.rs#L946)):*
> ```XML
>     // the smaller valid transaction.
> 
>     // If this fail, try to increase the max computation limit on the block context above.
> ```

I don't get the comment; it gives a hint for a case where we defined a test where the n_units_1 is exactly the block max bound?
___
*[`crates/blockifier/src/fee/resources.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3024#-OFX3JG75_1YQpy-g7go:-OFX3JG75_1YQpy-g7gp:b-arxdic) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4086cbbf7be7086a18ab75ab479a69d4ea67e07/crates/blockifier/src/fee/resources.rs#L108)):*
> ```XML
>             TrackedResource::SierraGas => {
>                 usize::try_from(self.sierra_gas.0 + self.reverted_sierra_gas.0).unwrap()
>             }
> ```

Or change the order in the gas - just have them match,



_Suggestion:_
```XML
            TrackedResource::CairoSteps => self.vm_resources.n_steps + self.n_reverted_steps,
            TrackedResource::SierraGas => {
                usize::try_from(self.sierra_gas.0 + self.reverted_sierra_gas.0).unwrap()
            }
```


<!-- Sent from Reviewable.io -->

2025-01-01 18:06 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3024)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/resources.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3024#-OFX3JG75_1YQpy-g7go:-OFY1ImFEPJhi3oO13QU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4086cbbf7be7086a18ab75ab479a69d4ea67e07/crates/blockifier/src/fee/resources.rs#L108)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Or change the order in the gas - just have them match,
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 946 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3024#-OFXg3BY64eqhcsy6fmH:-OFY1pPm3t5mD7OyaSoS:b-yxznhw) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4086cbbf7be7086a18ab75ab479a69d4ea67e07/crates/blockifier/src/transaction/account_transactions_test.rs#L946)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I don't get the comment; it gives a hint for a case where we defined a test where the n_units_1 is exactly the block max bound?
</blockquote></details>

rephrased, clearer?


<!-- Sent from Reviewable.io -->

2025-01-02 10:47 UTC, TzahiTaub reviewed
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3024)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 946 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3024#-OFXg3BY64eqhcsy6fmH:-OFabb0I5pStMFxYttsA:b-8m3r8v) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4086cbbf7be7086a18ab75ab479a69d4ea67e07/crates/blockifier/src/transaction/account_transactions_test.rs#L946)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rephrased, clearer?
</blockquote></details>

Yes, just weird to a see a comment for a possible failure in a test.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 909 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3024#-OFac86AE5Mp_v84tJS_:-OFac86AE5Mp_v84tJSa:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4713b26a158933137fe85c54b948c5ed56481680/crates/blockifier/src/transaction/account_transactions_test.rs#L909)):*
> ```XML
>     // Make sure that the n_units and actual_fee are higher as the recursion depth increases.
>     let validate_tracked_resource = result.validate_call_info.unwrap().tracked_resource;
>     assert_eq!(cairo_version.own_tracked_resource(), validate_tracked_resource);
> ```





_Suggestion:_
```XML
tracked_resource
```


<!-- Sent from Reviewable.io -->

2025-01-02 10:47 UTC, TzahiTaub approved these changes
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3024)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 10:48 UTC, TzahiTaub approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3024#-:-OFacM2E81c9XnwTEh5r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 10:50 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3024)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 946 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3024#-OFXg3BY64eqhcsy6fmH:-OFacQzt88j-oeoUhlmR:bjv32o9) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4086cbbf7be7086a18ab75ab479a69d4ea67e07/crates/blockifier/src/transaction/account_transactions_test.rs#L946)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Yes, just weird to a see a comment for a possible failure in a test.
</blockquote></details>

Yeah but it's also weird to have hard-coded magic numbers in tests, so better to have an accompanying comment


<!-- Sent from Reviewable.io -->

2025-01-02 11:42 UTC, TzahiTaub approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3024)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 14:31 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3024)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 14:31 UTC, merged