test(sequencing): add a bouncer_weights serialization test for cende
starkware-libs/sequencer pull request #3026
Opened 2024-12-30 15:13 UTC by Yael-Starkware

2024-12-30 15:13 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3026)
<!-- Reviewable:end -->

2024-12-30 15:14 UTC, Yael-Starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3026?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3026** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3026?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3026?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2988** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2988?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2921** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2921?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2872** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2872?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2861** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2861?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2715** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2715?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-30 15:42 UTC, DvirYo-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3026)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/3026#-OFNDCEI5vg8xXelSwMW:-OFNDCEI5vg8xXelSwMX:b-saf06x) (no related file):*
Is the serialization of the blockifier type the same as that of the Python?
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3026#-OFNDkim5DFN7vV9QB5p:-OFNDkim5DFN7vV9QB5q:b-ladg4a) ([raw file](https://github.com/starkware-libs/sequencer/blob/000dec5c717dbc4cf62b011ea7d33592ea9a18b0/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L57)):*
> ```XML
> pub const CENTRAL_DEPLOY_ACCOUNT_TX_JSON_PATH: &str = "central_deploy_account_tx.json";
> pub const CENTRAL_DECLARE_TX_JSON_PATH: &str = "central_declare_tx.json";
> pub const CENTRAL_L1_HANDLER_TX_JSON_PATH: &str = "central_l1_handler_tx.json";
> ```

I don't think you added the file


<!-- Sent from Reviewable.io -->

2024-12-30 15:49 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3026)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3026#-OFNDkim5DFN7vV9QB5p:-OFNFOWC1DWooOhUZK9_:b-8g1mz7) ([raw file](https://github.com/starkware-libs/sequencer/blob/000dec5c717dbc4cf62b011ea7d33592ea9a18b0/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L57)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I don't think you added the file
</blockquote></details>

right, added now, done.


<!-- Sent from Reviewable.io -->

2024-12-30 15:49 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3026)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/3026#-OFNDCEI5vg8xXelSwMW:-OFNFW4z3GdoVFzH3SR-:b8ggx75) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Is the serialization of the blockifier type the same as that of the Python?
</blockquote></details>

yes. it is just a struct of integers


<!-- Sent from Reviewable.io -->

2024-12-30 15:51 UTC, DvirYo-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3026#-:-OFNFwYjEfZc2n7TACjG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-12-31 10:22 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3026#-:-OFRE9sw2_xoJJFBIEmx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 15:59 UTC, DvirYo-starkware approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3026)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 16:05 UTC, merged