test(sequencing): test sierra contract class serialization
starkware-libs/sequencer pull request #3039
Opened 2024-12-31 13:47 UTC by Yael-Starkware

2024-12-31 13:47 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3039)
<!-- Reviewable:end -->

2024-12-31 13:48 UTC, Yael-Starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3039?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3039** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3039?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3039?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2921** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2921?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#2988](https://github.com/starkware-libs/sequencer/pull/2988) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2988?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#2872** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2872?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2861** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2861?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2715** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2715?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-07 12:24 UTC, DvirYo-starkware requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3039)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG-i06Z7LWkrP8sZsEH:-OG-i06Z7LWkrP8sZsEI:b-mcs9dp) ([raw file](https://github.com/starkware-libs/sequencer/blob/440ed2963be23e261f96a11ba4a17df80db48881/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L227)):*
> ```XML
> }
> 
> #[test]
> ```

Why not do the same for all objects? Why do we need to create the test object manually for other types?


<!-- Sent from Reviewable.io -->

2025-01-07 12:39 UTC, DvirYo-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3039)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2025-01-08 13:22 UTC, dafnamatsry requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3039)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 283 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG53DrZ20xwZWFnIJqt:-OG53DrZ20xwZWFnIJqu:b-4rtzpr) ([raw file](https://github.com/starkware-libs/sequencer/blob/008e09398081e8a3e854a3411946e8ee48ca9905/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L283)):*
> ```XML
>     let serialized_sierra_contract_class = serde_json::to_value(&sierra_contract_class).unwrap();
> 
>     assert_eq!(central_sierra_contract_class, serialized_sierra_contract_class);
> ```

What these 2 lines are testing?
It serializes an object that was created from a JSON, so it has to be that it will get serialized back to the same JSON.

I think it would be better to manually create a SierraContractClass instance, serialize it, and then compare.



_Suggestion:_
```XML
    let serialized_sierra_contract_class = serde_json::to_value(&sierra_contract_class).unwrap();

    assert_eq!(central_sierra_contract_class, serialized_sierra_contract_class);than
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/resources/central_sierra_contract_class.json` line 2286 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG51b1z8-17_WH85fUe:-OG51b1z8-17_WH85fUf:b71qz0k) ([raw file](https://github.com/starkware-libs/sequencer/blob/440ed2963be23e261f96a11ba4a17df80db48881/crates/sequencing/papyrus_consensus_orchestrator/resources/central_sierra_contract_class.json#L2286)):*
> ```JSON
>     "L1_HANDLER": []
>   },
>   "abi": "[\n  {\n    \"type\": \"impl\",\n    \"name\": \"IERC20Impl\",\n    \"interface_name\": \"cairo_level_tests::contracts::erc20::IERC20\"\n  },\n  {\n    \"type\": \"struct\",\n    \"name\": \"core::integer::u256\",\n    \"members\": [\n      {\n        \"name\": \"low\",\n        \"type\": \"core::integer::u128\"\n      },\n      {\n        \"name\": \"high\",\n        \"type\": \"core::integer::u128\"\n      }\n    ]\n  },\n  {\n    \"type\": \"interface\",\n    \"name\": \"cairo_level_tests::contracts::erc20::IERC20\",\n    \"items\": [\n      {\n        \"type\": \"function\",\n        \"name\": \"get_name\",\n        \"inputs\": [],\n        \"outputs\": [\n          {\n            \"type\": \"core::felt252\"\n          }\n        ],\n        \"state_mutability\": \"view\"\n      },\n      {\n        \"type\": \"function\",\n        \"name\": \"get_symbol\",\n        \"inputs\": [],\n        \"outputs\": [\n          {\n            \"type\": \"core::felt252\"\n          }\n        ],\n        \"state_mutability\": \"view\"\n      },\n      {\n        \"type\": \"function\",\n        \"name\": \"get_decimals\",\n        \"inputs\": [],\n        \"outputs\": [\n          {\n            \"type\": \"core::integer::u8\"\n          }\n        ],\n        \"state_mutability\": \"view\"\n      },\n      {\n        \"type\": \"function\",\n        \"name\": \"get_total_supply\",\n        \"inputs\": [],\n        \"outputs\": [\n          {\n            \"type\": \"core::integer::u256\"\n          }\n        ],\n        \"state_mutability\": \"view\"\n      },\n      {\n        \"type\": \"function\",\n        \"name\": \"balance_of\",\n        \"inputs\": [\n          {\n            \"name\": \"account\",\n            \"type\": \"core::starknet::contract_address::ContractAddress\"\n          }\n        ],\n        \"outputs\": [\n          {\n            \"type\": \"core::integer::u256\"\n          }\n        ],\n        \"state_mutability\": \"view\"\n      },\n      {\n        \"type\": \"function\",\n        \"name\": \"allowance\",\n        \"inputs\": [\n          {\n            \"name\": \"owner\",\n            \"type\": \"core::starknet::contract_address::ContractAddress\"\n          },\n          {\n            \"name\": \"spender\",\n            \"type\": \"core::starknet::contract_address::ContractAddress\"\n          }\n        ],\n        \"outputs\": [\n          {\n            \"type\": \"core::integer::u256\"\n          }\n        ],\n        \"state_mutability\": \"view\"\n      },\n      {\n        \"type\": \"function\",\n        \"name\": \"transfer\",\n        \"inputs\": [\n          {\n            \"name\": \"recipient\",\n            \"type\": \"core::starknet::contract_address::ContractAddress\"\n          },\n          {\n            \"name\": \"amount\",\n            \"type\": \"core::integer::u256\"\n          }\n        ],\n        \"outputs\": [],\n        \"state_mutability\": \"external\"\n      },\n      {\n        \"type\": \"function\",\n        \"name\": \"transfer_from\",\n        \"inputs\": [\n          {\n            \"name\": \"sender\",\n            \"type\": \"core::starknet::contract_address::ContractAddress\"\n          },\n          {\n            \"name\": \"recipient\",\n            \"type\": \"core::starknet::contract_address::ContractAddress\"\n          },\n          {\n            \"name\": \"amount\",\n            \"type\": \"core::integer::u256\"\n          }\n        ],\n        \"outputs\": [],\n        \"state_mutability\": \"external\"\n      },\n      {\n        \"type\": \"function\",\n        \"name\": \"approve\",\n        \"inputs\": [\n          {\n            \"name\": \"spender\",\n            \"type\": \"core::starknet::contract_address::ContractAddress\"\n          },\n          {\n            \"name\": \"amount\",\n            \"type\": \"core::integer::u256\"\n          }\n        ],\n        \"outputs\": [],\n        \"state_mutability\": \"external\"\n      },\n      {\n        \"type\": \"function\",\n        \"name\": \"increase_allowance\",\n        \"inputs\": [\n          {\n            \"name\": \"spender\",\n            \"type\": \"core::starknet::contract_address::ContractAddress\"\n          },\n          {\n            \"name\": \"added_value\",\n            \"type\": \"core::integer::u256\"\n          }\n        ],\n        \"outputs\": [],\n        \"state_mutability\": \"external\"\n      },\n      {\n        \"type\": \"function\",\n        \"name\": \"decrease_allowance\",\n        \"inputs\": [\n          {\n            \"name\": \"spender\",\n            \"type\": \"core::starknet::contract_address::ContractAddress\"\n          },\n          {\n            \"name\": \"subtracted_value\",\n            \"type\": \"core::integer::u256\"\n          }\n        ],\n        \"outputs\": [],\n        \"state_mutability\": \"external\"\n      }\n    ]\n  },\n  {\n    \"type\": \"constructor\",\n    \"name\": \"constructor\",\n    \"inputs\": [\n      {\n        \"name\": \"name_\",\n        \"type\": \"core::felt252\"\n      },\n      {\n        \"name\": \"symbol_\",\n        \"type\": \"core::felt252\"\n      },\n      {\n        \"name\": \"decimals_\",\n        \"type\": \"core::integer::u8\"\n      },\n      {\n        \"name\": \"initial_supply\",\n        \"type\": \"core::integer::u256\"\n      },\n      {\n        \"name\": \"recipient\",\n        \"type\": \"core::starknet::contract_address::ContractAddress\"\n      }\n    ]\n  },\n  {\n    \"type\": \"event\",\n    \"name\": \"cairo_level_tests::contracts::erc20::erc_20::Transfer\",\n    \"kind\": \"struct\",\n    \"members\": [\n      {\n        \"name\": \"from\",\n        \"type\": \"core::starknet::contract_address::ContractAddress\",\n        \"kind\": \"data\"\n      },\n      {\n        \"name\": \"to\",\n        \"type\": \"core::starknet::contract_address::ContractAddress\",\n        \"kind\": \"data\"\n      },\n      {\n        \"name\": \"value\",\n        \"type\": \"core::integer::u256\",\n        \"kind\": \"data\"\n      }\n    ]\n  },\n  {\n    \"type\": \"event\",\n    \"name\": \"cairo_level_tests::contracts::erc [...]

2025-01-08 15:49 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3039)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/resources/central_sierra_contract_class.json` line 2286 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG51b1z8-17_WH85fUe:-OG5afZT3XS_SOelGFYL:b-xt97hm) ([raw file](https://github.com/starkware-libs/sequencer/blob/440ed2963be23e261f96a11ba4a17df80db48881/crates/sequencing/papyrus_consensus_orchestrator/resources/central_sierra_contract_class.json#L2286)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can we format it to a nice JSON (without the `\`s)?
</blockquote></details>

this is a real contract abi string.
The field type is String , so it can't be a nice json.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 283 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG53DrZ20xwZWFnIJqt:-OG5ZnPz9Nbi6zeYli9h:bd8hkcq) ([raw file](https://github.com/starkware-libs/sequencer/blob/008e09398081e8a3e854a3411946e8ee48ca9905/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L283)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What these 2 lines are testing?
It serializes an object that was created from a JSON, so it has to be that it will get serialized back to the same JSON.

I think it would be better to manually create a SierraContractClass instance, serialize it, and then compare.
</blockquote></details>

The first deserialization is in order to create a sierra_contract_class_object. 
the second is in order to check that the serialization of the object creates the same json as was serialized from python.

in general serialization and deserialization of an object doesn't necessarily have the use and result with the same json. 


<!-- Sent from Reviewable.io -->

2025-01-12 13:31 UTC, dafnamatsry requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3039)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/resources/central_sierra_contract_class.json` line 2286 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG51b1z8-17_WH85fUe:-OGPhGhiEYXdoanEJj1f:biqhv7g) ([raw file](https://github.com/starkware-libs/sequencer/blob/440ed2963be23e261f96a11ba4a17df80db48881/crates/sequencing/papyrus_consensus_orchestrator/resources/central_sierra_contract_class.json#L2286)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this is a real contract abi string.
The field type is String , so it can't be a nice json.
</blockquote></details>

The `\n` can be removed.
Not critical, only if you feel like changing it...
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 283 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG53DrZ20xwZWFnIJqt:-OGPczK6-XLte4ei-PEI:b-p4d9v3) ([raw file](https://github.com/starkware-libs/sequencer/blob/008e09398081e8a3e854a3411946e8ee48ca9905/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L283)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The first deserialization is in order to create a sierra_contract_class_object. 
the second is in order to check that the serialization of the object creates the same json as was serialized from python.

in general serialization and deserialization of an object doesn't necessarily have the use and result with the same json.
</blockquote></details>

Say tomorrow someone adds an optional field to `SierraContractClass` (with skip serialise if none, like in `CasmContractClass`), this test will still pass. I would have want it to fail in this case.


<!-- Sent from Reviewable.io -->

2025-01-13 13:48 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3039)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 283 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG53DrZ20xwZWFnIJqt:-OGUewM66mlreXTWHlbT:bjlgtwl) ([raw file](https://github.com/starkware-libs/sequencer/blob/008e09398081e8a3e854a3411946e8ee48ca9905/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L283)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Say tomorrow someone adds an optional field to `SierraContractClass` (with skip serialise if none, like in `CasmContractClass`), this test will still pass. I would have want it to fail in this case.
</blockquote></details>

It is the same for all central objects, 
if someone adds a field to an object, they need to add it to the entire pipeline, both rust and python and test end to end that it is passed to the pythonic services.


<!-- Sent from Reviewable.io -->

2025-01-14 08:24 UTC, dafnamatsry requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3039)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 283 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG53DrZ20xwZWFnIJqt:-OGYsGg_AytfLNPYkZtx:bvhn9ft) ([raw file](https://github.com/starkware-libs/sequencer/blob/008e09398081e8a3e854a3411946e8ee48ca9905/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L283)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

It is the same for all central objects, 
if someone adds a field to an object, they need to add it to the entire pipeline, both rust and python and test end to end that it is passed to the pythonic services.
</blockquote></details>

In the other central objects tests, you create an instance manually (not by deserialize it from JSON). You have a rust_json, and a python_json which you compare.

Here, you begin with the expected json, and the test is less hermetic. As an example:
In the other cases, adding a new field to an object will make the test not compile, which is good, since then it must be adjusted to the changes.
Here adding an optional field for example, won't affect the test at all.


<!-- Sent from Reviewable.io -->

2025-01-14 14:10 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3039)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 283 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG53DrZ20xwZWFnIJqt:-OG_7nRmD1q1JOHQghdK:b-96a15r) ([raw file](https://github.com/starkware-libs/sequencer/blob/008e09398081e8a3e854a3411946e8ee48ca9905/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L283)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

In the other central objects tests, you create an instance manually (not by deserialize it from JSON). You have a rust_json, and a python_json which you compare.

Here, you begin with the expected json, and the test is less hermetic. As an example:
In the other cases, adding a new field to an object will make the test not compile, which is good, since then it must be adjusted to the changes.
Here adding an optional field for example, won't affect the test at all.
</blockquote></details>

1. it is still not hermetic since you can make the test compile even without adding this field to the central object.
2. even if I manually create this object, I won't be able to manually create the transaction_execution_info object since it has some private fields.


<!-- Sent from Reviewable.io -->

2025-01-16 06:43 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3039)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 283 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-OG53DrZ20xwZWFnIJqt:-OGhqRkc2eSdP-UNO_EO:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/008e09398081e8a3e854a3411946e8ee48ca9905/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L283)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

1. it is still not hermetic since you can make the test compile even without adding this field to the central object.
2. even if I manually create this object, I won't be able to manually create the transaction_execution_info object since it has some private fields.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2025-01-16 06:43 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3039#-:-OGhqZsx5Pl4O-PxHYip:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-16 06:54 UTC, merged