chore(starknet_sequencer_infra): removing unnecessary Sync trait bound from component servers
starkware-libs/sequencer pull request #3040
Opened 2024-12-31 14:22 UTC by lev-starkware

2024-12-31 14:22 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3040)
<!-- Reviewable:end -->

2024-12-31 14:31 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3040)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/starknet_sequencer_infra/src/tests/remote_component_client_server_test.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3040#-OFS78iDD-K0CiE1fcUo:-OFS78iEC6L2IyQpRteT:b-y83xmt) ([raw file](https://github.com/starkware-libs/sequencer/blob/7931af0a67172b49c14b5ac644f4d688799c8c45/crates/starknet_sequencer_infra/src/tests/remote_component_client_server_test.rs#L127)):*
> ```XML
>         ) -> Result<Response<Body>, hyper::Error>
>         where
>             T1: Serialize + DeserializeOwned + Debug + Send,
> ```

פרה פרה
Let's handle this separately
Please revert this change, and add a todo 



_Code quote:_
```XML
        async fn handler<T1>(
            _http_request: Request<Body>,
            body: T1,
        ) -> Result<Response<Body>, hyper::Error>
        where
            T1: Serialize + DeserializeOwned + Debug + Send,
```


<!-- Sent from Reviewable.io -->

2025-01-02 10:15 UTC, lev-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3040)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_infra/src/tests/remote_component_client_server_test.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3040#-OFS78iDD-K0CiE1fcUo:-OFaVJQODqH2dM5nMIoF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7931af0a67172b49c14b5ac644f4d688799c8c45/crates/starknet_sequencer_infra/src/tests/remote_component_client_server_test.rs#L127)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

פרה פרה
Let's handle this separately
Please revert this change, and add a todo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-02 10:18 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3040#-:-OFaWVGD6vw2iRW9ZLW8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 10:36 UTC, lev-starkware reviewed
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3040)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)



<!-- Sent from Reviewable.io -->

2025-01-02 10:50 UTC, merged