chore: support a distributed node setup
starkware-libs/sequencer pull request #3042
Opened 2024-12-31 15:00 UTC by nadin-Starkware

2024-12-31 15:00 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/3042)
<!-- Reviewable:end -->

2025-01-01 13:24 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3042)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFX0wdT8Ioe29cs70v-:-OFX0wdT8Ioe29cs70v0:bbpwwce) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a13cb924c412134bc8ca5cbe38651c78de8a207/crates/starknet_integration_tests/src/end_to_end_integration.rs#L85)):*
> ```XML
>             .take(N_CONSOLIDATED_SEQUENCERS)
>             .chain(create_remote_node_configs(&mut available_ports, N_DISTRIBUTED_SEQUENCERS))
>             .collect();
> ```

This is becoming confusing. Can we be consistent here with the creation of each of the config types?

That is, the code currently creates the consolidated configs using `repeat_with`,  and but wraps the creation of the disributed ones with a function. 

Suggestion: use a wrapper function for the consolidated ones.



_Code quote:_
```XML
    let component_configs: Vec<Vec<ComponentConfig>> =
        std::iter::repeat_with(|| vec![ComponentConfig::default()])
            .take(N_CONSOLIDATED_SEQUENCERS)
            .chain(create_remote_node_configs(&mut available_ports, N_DISTRIBUTED_SEQUENCERS))
            .collect();
```


<!-- Sent from Reviewable.io -->

2025-01-01 13:24 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3042)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFX1TOMBdzfQBz4n2Jo:-OFX1TON2JOQ4m-KlrXe:b-qhyr9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a13cb924c412134bc8ca5cbe38651c78de8a207/crates/starknet_integration_tests/src/end_to_end_integration.rs#L84)):*
> ```XML
>         std::iter::repeat_with(|| vec![ComponentConfig::default()])
>             .take(N_CONSOLIDATED_SEQUENCERS)
>             .chain(create_remote_node_configs(&mut available_ports, N_DISTRIBUTED_SEQUENCERS))
> ```

Should be renamed to `distributed` instead of `remote`, correct?



_Code quote:_
```XML
create_remote_node_configs
```


<!-- Sent from Reviewable.io -->

2025-01-01 13:26 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3042)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFX1h8TE13wFak0Mj_7:-OFX1h8TE13wFak0Mj_8:b-tm36dd) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a13cb924c412134bc8ca5cbe38651c78de8a207/crates/starknet_integration_tests/src/end_to_end_integration.rs#L81)):*
> ```XML
>         AvailablePorts::new(TestIdentifier::EndToEndIntegrationTest.into(), 0);
> 
>     let component_configs: Vec<Vec<ComponentConfig>> =
> ```

I think we should consider defining a struct that captures this, e.g., `DistributedNodeConfigs`, that can hold the identifier as well. Add a todo?



_Code quote:_
```XML
Vec<ComponentConfig>
```


<!-- Sent from Reviewable.io -->

2025-01-01 14:12 UTC, nadin-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3042)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFX1h8TE13wFak0Mj_7:-OFXCUhZDAnk66Swa3Hm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a13cb924c412134bc8ca5cbe38651c78de8a207/crates/starknet_integration_tests/src/end_to_end_integration.rs#L81)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I think we should consider defining a struct that captures this, e.g., `DistributedNodeConfigs`, that can hold the identifier as well. Add a todo?
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFX1TOMBdzfQBz4n2Jo:-OFX3W55ALRKIKCF1QGY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a13cb924c412134bc8ca5cbe38651c78de8a207/crates/starknet_integration_tests/src/end_to_end_integration.rs#L84)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Should be renamed to `distributed` instead of `remote`, correct?
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFX0wdT8Ioe29cs70v-:-OFXCTdl0tJ2DdtYytL_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a13cb924c412134bc8ca5cbe38651c78de8a207/crates/starknet_integration_tests/src/end_to_end_integration.rs#L85)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This is becoming confusing. Can we be consistent here with the creation of each of the config types?

That is, the code currently creates the consolidated configs using `repeat_with`,  and but wraps the creation of the disributed ones with a function. 

Suggestion: use a wrapper function for the consolidated ones.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 14:55 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3042)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFXKikiBdMJ1oxeO23L:-OFXKikiBdMJ1oxeO23M:b2kujgx) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1a660eb992682b7383a042d55e76f281dc2c01e/crates/starknet_integration_tests/src/end_to_end_integration.rs#L83)):*
> ```XML
>     // TODO(Nadin): replace Vec<ComponentConfig> with a struct - DistributedNodeConfigs.
>     let component_configs: Vec<Vec<ComponentConfig>> =
>         create_consolidate_sequencer_configs(N_CONSOLIDATED_SEQUENCERS)
> ```

missing *d*



_Code quote:_
```XML
consolidate
```
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 161 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFXKovn7ihD_l_HohjA:-OFXKovn7ihD_l_HohjB:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1a660eb992682b7383a042d55e76f281dc2c01e/crates/starknet_integration_tests/src/end_to_end_integration.rs#L161)):*
> ```XML
> 
> /// Generates configurations for a specified number of distributed sequencer nodes,
> /// each consisting of an HTTP container configuration and a non-HTTP container configuration.
> ```

?



_Code quote:_
```XML
container
```
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFXKwQU3eX68xtYjPTL:-OFXKwQU3eX68xtYjPTM:b-58so6z) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1a660eb992682b7383a042d55e76f281dc2c01e/crates/starknet_integration_tests/src/integration_test_setup.rs#L44)):*
> ```XML
>         let chain_info = create_chain_info();
>         let accounts = tx_generator.accounts();
>         let n_distributed_sequencers: usize =
> ```

needed?



_Code quote:_
```XML
: usize
```
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFXLJqh6nWLZmJFKEbB:-OFXLJqh6nWLZmJFKEbC:bm68bgt) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1a660eb992682b7383a042d55e76f281dc2c01e/crates/starknet_integration_tests/src/integration_test_setup.rs#L57)):*
> ```XML
> 
>         let mut sequencers = vec![];
>         for (sequencer_id, component_group) in component_configs.iter().enumerate() {
> ```

Is this a sequencer that is either distributed or consolidated? If so, please rename, also in the comment below.
I'd go with "NodeEnsemble" or "NodeComposition" to describe this is the whole of multiple, connected yet distinct parts.



_Code quote:_
```XML
component_group
```


<!-- Sent from Reviewable.io -->

2025-01-01 15:02 UTC, nadin-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3042)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFXKikiBdMJ1oxeO23L:-OFXNaxZAZ77DPoEnr4P:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1a660eb992682b7383a042d55e76f281dc2c01e/crates/starknet_integration_tests/src/end_to_end_integration.rs#L83)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

missing *d*
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 161 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFXKovn7ihD_l_HohjA:-OFXNbUPE4APL6VhYw9_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1a660eb992682b7383a042d55e76f281dc2c01e/crates/starknet_integration_tests/src/end_to_end_integration.rs#L161)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFXKwQU3eX68xtYjPTL:-OFXN57L5OBSR2y6c-36:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1a660eb992682b7383a042d55e76f281dc2c01e/crates/starknet_integration_tests/src/integration_test_setup.rs#L44)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

needed?
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-OFXLJqh6nWLZmJFKEbB:-OFXNWmtD1Zaj-wyCbZN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1a660eb992682b7383a042d55e76f281dc2c01e/crates/starknet_integration_tests/src/integration_test_setup.rs#L57)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this a sequencer that is either distributed or consolidated? If so, please rename, also in the comment below.
I'd go with "NodeEnsemble" or "NodeComposition" to describe this is the whole of multiple, connected yet distinct parts.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 15:08 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3042#-:-OFXPEHU3HSGqAOk48-J:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 15:08 UTC, Itay-Tsabary-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3042)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)



<!-- Sent from Reviewable.io -->

2025-01-01 15:39 UTC, merged