Support reverts of inner calls.
starkware-libs/sequencer pull request #381
Opened 2024-08-11 08:09 UTC by ilyalesokhin-starkware

2024-09-09 09:06 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 271 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6L16eZBzT_QMX6ex6V:-O6L16eZBzT_QMX6ex6W:btd7u0f) ([raw file](https://github.com/starkware-libs/sequencer/blob/d56c432c177df42dd7f6aefd23341772bcd2d960/crates/blockifier/src/execution/syscalls/hint_processor.rs#L271)):*
> ```XML
>                 .expect("Missing contract revert info.")
>                 .orig_values,
>         );
> ```

This is not mandatory, but I felt it would be nicer to do it here than on every storage access.



_Code quote:_
```XML
        let orig_values = std::mem::take(
            &mut context
                .revert_infos
                .0
                .last_mut()
                .expect("Missing contract revert info.")
                .orig_values,
        );
```


<!-- Sent from Reviewable.io -->

2024-09-09 09:37 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1896 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6L8N412EkS0Mg_e_AJ:-O6L8N412EkS0Mg_e_AK:brmmrzh) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c1b5572594d75e9405e0c080b2c7bcbb2cd9553/crates/blockifier/src/transaction/transactions_test.rs#L1896)):*
> ```XML
>             ),
>         ]),
>         n_steps: get_tx_resources(TransactionType::L1Handler).n_steps + 164,
> ```

I have no idea why we save 7 steps here :(



_Code quote:_
```XML
 164,
```


<!-- Sent from Reviewable.io -->

2024-09-15 06:30 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 80 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6oMhCi0iVpAQoEQonu:-O6oMhCi0iVpAQoEQonv:b1dd85u) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c1b5572594d75e9405e0c080b2c7bcbb2cd9553/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L80)):*
> ```Cairo
>         contract_address: ContractAddress,
>         entry_point_selector: felt252,
>         calldata: Array::<felt252>
> ```

Don't we have syntactic sugar for calling contracts in Cairo1?



_Code quote:_
```Cairo
        entry_point_selector: felt252,
        calldata: Array::<felt252>
```
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6o7PCe8YdLvlbfpTcu:-O6o7PCe8YdLvlbfpTcv:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c1b5572594d75e9405e0c080b2c7bcbb2cd9553/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L94)):*
> ```Cairo
>             },
>         };
>         assert(self.my_storage_var.read() == 0, 'values should not change.');
> ```





_Suggestion:_
```Cairo
        };
        // TODO(Yoni, 1/12/2024): test replace class once get_class_hash_at syscall is supported.
        assert(self.my_storage_var.read() == 0, 'values should not change.');
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6oMp9p2pLK_sexkwZk:-O6oMp9p2pLK_sexkwZl:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c1b5572594d75e9405e0c080b2c7bcbb2cd9553/crates/blockifier/src/execution/entry_point.rs#L50)):*
> ```XML
>     pub original_class_hash: ClassHash,
>     /// The original storage values.
>     pub orig_values: HashMap<StorageKey, Felt>,
> ```





_Suggestion:_
```XML
    pub original_class_hash: ClassHash,
    /// The original storage values.
    pub original_values: HashMap<StorageKey, Felt>,
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 271 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6L16eZBzT_QMX6ex6V:-O6o7d41AHTHwbyYnXv3:b-sg25i3) ([raw file](https://github.com/starkware-libs/sequencer/blob/d56c432c177df42dd7f6aefd23341772bcd2d960/crates/blockifier/src/execution/syscalls/hint_processor.rs#L271)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This is not mandatory, but I felt it would be nicer to do it here than on every storage access.
</blockquote></details>

Is it more efficient?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1896 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6L8N412EkS0Mg_e_AJ:-O6o6PBT00Je6yZu1ULz:b-1jgdta) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c1b5572594d75e9405e0c080b2c7bcbb2cd9553/crates/blockifier/src/transaction/transactions_test.rs#L1896)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I have no idea why we save 7 steps here :(
</blockquote></details>

You compiled with 2.8.0 (the test contract was compiled with 2.7.0)


<!-- Sent from Reviewable.io -->

2024-09-15 06:36 UTC, Yoni-Starkware reviewed
Very cool. Tiny issue is with concurrency - the set of writes might contain values that were not written by the tx.
Should be okay since there is a read before every write.
cc @noaov1 - is it safe to save the diff instead of the writes [here](https://github.com/starkware-libs/sequencer/blob/9745223e7d07778b67771ab5af925087653dd4e5/crates/blockifier/src/concurrency/worker_logic.rs#L141) and [here](https://github.com/starkware-libs/sequencer/blob/9745223e7d07778b67771ab5af925087653dd4e5/crates/blockifier/src/concurrency/worker_logic.rs#L152)?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381#-:-O6oN4478uMR9DWiPAF5:b48o501)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-09-15 06:43 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 271 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6L16eZBzT_QMX6ex6V:-O6oPuZiA-AI-NvxGMOy:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/d56c432c177df42dd7f6aefd23341772bcd2d960/crates/blockifier/src/execution/syscalls/hint_processor.rs#L271)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is it more efficient?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2024-09-15 08:23 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/transaction/transactions.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6olPZ81090I5pmUZfo:-O6olPZ81090I5pmUZfp:by5zgf9) ([raw file](https://github.com/starkware-libs/sequencer/blob/beffa7501d303f28da3c3f667c8a3042067236dd/crates/blockifier/src/transaction/transactions.rs#L85)):*
> ```XML
>             Ok(value) => {
>                 if let Some(call_info) = &value.execute_call_info {
>                     // If the execution of the outer call failed, revert the transction.
> ```

@dorimedini-starkware, does the following make sense?

Without it, the unwrap_err() here:
https://github.com/starkware-libs/sequencer/blob/834eff6a6712e6ab90318d14caf946e84d1d3b0f/crates/blockifier/src/transaction/transactions_test.rs#L1566
fails.



_Code quote:_
```XML
// If the execution of the outer call failed, revert the transction.
```


<!-- Sent from Reviewable.io -->

2024-09-15 08:24 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 80 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6oMhCi0iVpAQoEQonu:-O6om76a1X5P5tQOeVh3:b-qu2g33) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c1b5572594d75e9405e0c080b2c7bcbb2cd9553/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L80)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Don't we have syntactic sugar for calling contracts in Cairo1?
</blockquote></details>

yes, but then you can't pass the selector in the calldata.


<!-- Sent from Reviewable.io -->

2024-09-15 08:25 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1896 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6L8N412EkS0Mg_e_AJ:-O6omEud9k6NyEGjo6G-:b-qssebl) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c1b5572594d75e9405e0c080b2c7bcbb2cd9553/crates/blockifier/src/transaction/transactions_test.rs#L1896)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You compiled with 2.8.0 (the test contract was compiled with 2.7.0)
</blockquote></details>

fixed.


<!-- Sent from Reviewable.io -->

2024-09-15 08:53 UTC, ilyalesokhin-starkware commented
"the set of writes might contain values that were not written by the tx."

can you elaborate? what writes?





<!-- Sent from Reviewable.io -->

2024-09-15 10:20 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 80 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6oMhCi0iVpAQoEQonu:-O6pBQWNCXDlz4JyphGN:b-l41qgz) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c1b5572594d75e9405e0c080b2c7bcbb2cd9553/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L80)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

yes, but then you can't pass the selector in the calldata.
</blockquote></details>

Why do you need it? why not calling `test_revert_helper`?


<!-- Sent from Reviewable.io -->

2024-09-15 10:48 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 80 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6oMhCi0iVpAQoEQonu:-O6pHzvD3_-RaINVYeGM:bnayy6c) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c1b5572594d75e9405e0c080b2c7bcbb2cd9553/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L80)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why do you need it? why not calling `test_revert_helper`?
</blockquote></details>

I need to define a contract ABI for that. not sure it is worth the hustle,

we don't do it in other tests.


<!-- Sent from Reviewable.io -->

2024-09-15 12:01 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 4 files at r4, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 2 of 11 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-15 12:01 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 2 of 11 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6olPZ81090I5pmUZfo:-O6pYBBm8Aw-lDJYc8iB:bllbw3h) ([raw file](https://github.com/starkware-libs/sequencer/blob/beffa7501d303f28da3c3f667c8a3042067236dd/crates/blockifier/src/transaction/transactions.rs#L85)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware, does the following make sense?

Without it, the unwrap_err() here:
https://github.com/starkware-libs/sequencer/blob/834eff6a6712e6ab90318d14caf946e84d1d3b0f/crates/blockifier/src/transaction/transactions_test.rs#L1566
fails.
</blockquote></details>

when txs revert (with your new feature), we want to return an `Err` variant in the result of `account_tx.execute`, right @Yoni-Starkware ?
if this is the case, then yes, this seems to make sense to me


<!-- Sent from Reviewable.io -->

2024-09-15 14:27 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/transaction/transactions.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6olPZ81090I5pmUZfo:-O6q3ux5DSzX0-m04uGV:bpv9ywn) ([raw file](https://github.com/starkware-libs/sequencer/blob/beffa7501d303f28da3c3f667c8a3042067236dd/crates/blockifier/src/transaction/transactions.rs#L85)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

when txs revert (with your new feature), we want to return an `Err` variant in the result of `account_tx.execute`, right @Yoni-Starkware ?
if this is the case, then yes, this seems to make sense to me
</blockquote></details>

Note that this is also temporary, in the future we would want to include prove reverted transactions and not use trusted reverts like we do today.


<!-- Sent from Reviewable.io -->

2024-09-15 14:43 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 2 of 11 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6olPZ81090I5pmUZfo:-O6q7sTk5I7ShrC-lG2i:bkvhcjj) ([raw file](https://github.com/starkware-libs/sequencer/blob/beffa7501d303f28da3c3f667c8a3042067236dd/crates/blockifier/src/transaction/transactions.rs#L85)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Note that this is also temporary, in the future we would want to include prove reverted transactions and not use trusted reverts like we do today.
</blockquote></details>

this will be a nightmare to untangle but I don't have a better idea ATM


<!-- Sent from Reviewable.io -->

2024-09-15 19:39 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6r7vvUDKyey1ewjGPk:-O6r7vvVANgjoETaNiF9:bmaamhx) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/src/execution/entry_point.rs#L84)):*
> ```XML
>     pub call_info: CallInfo,
>     pub revert_info: ExecutionRevertInfo,
> }
> ```

Needed?



_Code quote:_
```XML
pub struct ExecutionResult {
    pub call_info: CallInfo,
    pub revert_info: ExecutionRevertInfo,
}
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 720 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6r9_kk8LybQacnjr7D:-O6r9_kl3qSAfK7Al5YF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/src/execution/syscalls/hint_processor.rs#L720)):*
> ```XML
>         self.original_values
>             .entry(key)
>             .or_insert_with(|| self.state.get_storage_at(contract_address, key).unwrap());
> ```





_Suggestion:_
```XML
)?;
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 852 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6rAnrX66TzumGvcspJ:-O6rAnrY7Ta7WIwGYDxg:b-3mvcmq) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/src/execution/syscalls/hint_processor.rs#L852)):*
> ```XML
>             .push(Felt::from_hex(ENTRYPOINT_FAILED_ERROR).map_err(SyscallExecutionError::from)?);
>         return Err(SyscallExecutionError::SyscallError { error_data: raw_retdata });
>     }
> ```

Is this an AC prep for the versioned constants check?



_Code quote:_
```XML
    if failed {
        raw_retdata
            .push(Felt::from_hex(ENTRYPOINT_FAILED_ERROR).map_err(SyscallExecutionError::from)?);
        return Err(SyscallExecutionError::SyscallError { error_data: raw_retdata });
    }
```


<!-- Sent from Reviewable.io -->

2024-09-15 19:45 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 2 of 11 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6rCr_54TcgfyOuKGap:-O6rCr_54TcgfyOuKGaq:bu8151k) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L89)):*
> ```Cairo
>                 let mut error_span = errors.span();
>                 assert(
>                     *error_span.pop_back().unwrap() == 'ENTRYPOINT_FAILED',
> ```

Where do you write this?



_Code quote:_
```Cairo
ENTRYPOINT_FAILED
```


<!-- Sent from Reviewable.io -->

2024-09-16 06:42 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 852 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6rAnrX66TzumGvcspJ:-O6tZJ_08FFhX93IR1Me:b-gp6si9) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/src/execution/syscalls/hint_processor.rs#L852)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this an AC prep for the versioned constants check?
</blockquote></details>

what is a versioned constants check?


<!-- Sent from Reviewable.io -->

2024-09-16 06:46 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6rCr_54TcgfyOuKGap:-O6t_HqBDTdsD-CYoJXZ:bj8ohas) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L89)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Where do you write this?
</blockquote></details>

here:
https://github.com/starkware-libs/sequencer/blob/447fc11d2eb03c3c7bd5a0bc424e4ab2d8ec5410/crates/blockifier/src/execution/syscalls/hint_processor.rs#L855


<!-- Sent from Reviewable.io -->

2024-09-16 06:46 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 720 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6r9_kk8LybQacnjr7D:-O6t_LX2AfyDiWzIX32S:bd3olh8) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/src/execution/syscalls/hint_processor.rs#L720)):*
> ```XML
>         self.original_values
>             .entry(key)
>             .or_insert_with(|| self.state.get_storage_at(contract_address, key).unwrap());
> ```

can't do it inside the lambda.


<!-- Sent from Reviewable.io -->

2024-09-16 06:47 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 0 of 15 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6r7vvUDKyey1ewjGPk:-O6t_KhwDi2kgU4iZran:brpmqc3) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/src/execution/entry_point.rs#L84)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Needed?
</blockquote></details>

removed.


<!-- Sent from Reviewable.io -->

2024-09-16 06:49 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/transaction/transactions.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6t_qA58hQu2vvMoV5T:-O6t_qA58hQu2vvMoV5U:b-rcqu41) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/src/transaction/transactions.rs#L101)):*
> ```XML
>                         });
>                     }
>                 }
> ```

I had to move it elsewhere to support AccountTransaction::Execute to support reverts.



_Code quote:_
```XML
                if let Some(call_info) = &value.execute_call_info {
                    // If the execution of the outer call failed, revert the transction.
                    if call_info.execution.failed {
                        let retdata = &call_info.execution.retdata.0;

                        log::debug!("Transaction reverted with: {:?}", retdata);
                        transactional_state.abort();

                        return Err(TransactionExecutionError::ExecutionError {
                            error: EntryPointExecutionError::ExecutionFailed {
                                error_data: retdata.clone(),
                            },
                            class_hash: call_info.call.class_hash.unwrap(),
                            storage_address: call_info.call.storage_address,
                            selector: call_info.call.entry_point_selector,
                        });
                    }
                }
```


<!-- Sent from Reviewable.io -->

2024-09-16 06:52 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/transaction/account_transaction.rs` line 461 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6taW-o12xEGd0gpH6Y:-O6taW-pC7ufsmqCOFDG:bkrpkgv) ([raw file](https://github.com/starkware-libs/sequencer/blob/447fc11d2eb03c3c7bd5a0bc424e4ab2d8ec5410/crates/blockifier/src/transaction/account_transaction.rs#L461)):*
> ```XML
>         };
> 
>         if let Ok(Some(call_info)) = &res {
> ```

I'm not sure if this should be here or in some kind of wrapper and how to call the wrapper.



_Code quote:_
```XML
  if let Ok(Some(call_info)) = &res {
```


<!-- Sent from Reviewable.io -->

2024-09-16 06:54 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6t_qA58hQu2vvMoV5T:-O6taDaGC3UwN4yq4V65:b21xjvw) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/src/transaction/transactions.rs#L101)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I had to move it elsewhere to support AccountTransaction::Execute to support reverts.
</blockquote></details>

sorry, 


<!-- Sent from Reviewable.io -->

2024-09-16 07:52 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 0 of 15 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6rCr_54TcgfyOuKGap:-O6toK7W5bdw2rjjPEV7:bgtd8nm) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L89)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

here:
https://github.com/starkware-libs/sequencer/blob/447fc11d2eb03c3c7bd5a0bc424e4ab2d8ec5410/crates/blockifier/src/execution/syscalls/hint_processor.rs#L855
</blockquote></details>

But you return Err right after


<!-- Sent from Reviewable.io -->

2024-09-16 07:59 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 84 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6tpppjAhZ5rTfWPlaD:-O6tpppjAhZ5rTfWPlaE:b3kqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/59930bc4837da0dc27f4b1c3a6d59f46ad54ce66/crates/blockifier/src/transaction/errors.rs#L84)):*
> ```XML
>     #[error(transparent)]
>     FromStr(#[from] FromStrError),
>     #[error("The `validate` entry point panicked with {panic_reaon:?}.")]
> ```

.



_Suggestion:_
```XML
 with: {}.", format_panic_data(panic_reaon.0))]
```


<!-- Sent from Reviewable.io -->

2024-09-16 09:56 UTC, Yoni-Starkware reviewed
Handle events and messages
L1 handler
"if" (VC prep)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381#-:-O6uFUfx3UvlAzUPXLXR:b-iw9xpu)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-09-17 07:39 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6rCr_54TcgfyOuKGap:-O6yux0F1ooGh2FRHlOt:bc5qdsk) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f0334566b0b2b4768a471bb6c92f03d251f183/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L89)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

But you return Err right after
</blockquote></details>

discussed f2f


<!-- Sent from Reviewable.io -->

2024-09-17 07:39 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 84 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6tpppjAhZ5rTfWPlaD:-O6yv17eCuTS_fOp3mwH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/59930bc4837da0dc27f4b1c3a6d59f46ad54ce66/crates/blockifier/src/transaction/errors.rs#L84)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-17 10:45 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 156 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6z_cgO2aCTgrm1-NJ1:-O6z_cgO2aCTgrm1-NJ2:b-sp0vel) ([raw file](https://github.com/starkware-libs/sequencer/blob/48f58228420fec12d9e16930d8f4a12d0f1700f4/crates/blockifier/src/execution/entry_point.rs#L156)):*
> ```XML
> 
>     /// Similar to `execute`, but returns an error if the outer call is reverted.
>     pub fn execute_outer_call(
> ```

not sure what is the best name here.



_Suggestion:_
```XML
execute_fail_on_panic
```


<!-- Sent from Reviewable.io -->

2024-09-18 12:13 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 13 files at r7, 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 2 of 16 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 156 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6z_cgO2aCTgrm1-NJ1:-O741la20-rP4_FZQR3Q:b-2fks3j) ([raw file](https://github.com/starkware-libs/sequencer/blob/48f58228420fec12d9e16930d8f4a12d0f1700f4/crates/blockifier/src/execution/entry_point.rs#L156)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not sure what is the best name here.
</blockquote></details>

`non_reverting_execute` to be consistent with the OS?
___
*[`crates/blockifier/src/execution/entry_point.rs` line 131 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74-h252eAKh13NgSFb:-O74-h252eAKh13NgSFc:b-g4skli) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/entry_point.rs#L131)):*
> ```XML
>             None => storage_class_hash, // If not given, take the storage contract class hash.
>         };
> ```

Revert the new line
___
*[`crates/blockifier/src/execution/entry_point.rs` line 145 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74-m64-I5KB7xos1lV:-O74-m64-I5KB7xos1lW:bl7rvs0) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/entry_point.rs#L145)):*
> ```XML
>         let contract_class = state.get_compiled_contract_class(class_hash)?;
> 
>         context.revert_infos.0.push(EntryPointRevertInfo::new(
> ```

@TzahiTaub please be consistent with @ilyalesokhin-starkware's update. Maybe add functions `enter_call`/`exit_call` to the execution context.



_Code quote:_
```XML
        context.revert_infos.0.push(EntryPointRevertInfo::new(
```


<!-- Sent from Reviewable.io -->

2024-09-18 14:43 UTC, Yoni-Starkware requested changes
> Reviewed 3 of 10 files at r9, 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 6 of 16 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 212 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74ShVL7Ic9fmZjAIra:-O74ShVL7Ic9fmZjAIrb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/hint_processor.rs#L212)):*
> ```XML
> // "ENTRYPOINT_FAILED";
> pub const ENTRYPOINT_FAILED_ERROR: &str =
>     "0x000000000000000000000000000000454e545259504f494e545f4641494c4544";
> ```





_Suggestion:_
```XML
// "Block number out of range";
pub const BLOCK_NUMBER_OUT_OF_RANGE_ERROR: &str =
    "0x00000000000000426c6f636b206e756d626572206f7574206f662072616e6765";
// "ENTRYPOINT_FAILED";
pub const ENTRYPOINT_FAILED_ERROR: &str =
    "0x000000000000000000000000000000454e545259504f494e545f4641494c4544";
// "Invalid input length";
pub const INVALID_INPUT_LENGTH_ERROR: &str =
    "0x000000000000000000000000496e76616c696420696e707574206c656e677468";
// "Invalid argument";
pub const INVALID_ARGUMENT: &str =
    "0x00000000000000000000000000000000496e76616c696420617267756d656e74";
    
// "L1_GAS";
pub const L1_GAS: &str = "0x00000000000000000000000000000000000000000000000000004c315f474153";
// "L2_GAS";
pub const L2_GAS: &str = "0x00000000000000000000000000000000000000000000000000004c325f474153";
// "L1_DATA";
pub const L1_DATA: &str = "0x000000000000000000000000000000000000000000000000004c315f44415441";
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 851 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74_PqK2MQh_sZIOG22:-O74_PqK2MQh_sZIOG23:b-x2p9hl) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/hint_processor.rs#L851)):*
> ```XML
> 
>     let failed = call_info.execution.failed;
>     syscall_handler.inner_calls.push(call_info);
> ```

We need to handle events and messages. Safer to remove them. Otherwise we need to change `summarize` here and python's equivalent
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 860 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74W9Nc4ZhX_dGf0V6M:-O74W9Nc4ZhX_dGf0V6N:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/hint_processor.rs#L860)):*
> ```XML
> 
>     let retdata_segment = create_retdata_segment(vm, syscall_handler, &raw_retdata)?;
>     Ok(retdata_segment)
> ```





_Suggestion:_
```XML
    let call_info =
        call.execute(syscall_handler.state, syscall_handler.resources, syscall_handler.context)?;
    
    let failed = call_info.execution.failed;    
    let mut raw_retdata = call_info.execution.retdata.0.clone();
    update_remaining_gas(remaining_gas, &call_info);
    syscall_handler.inner_calls.push(call_info);
    if failed {
        syscall_handler.context.revert(revert_idx, syscall_handler.state)?;
        raw_retdata
            .push(Felt::from_hex(ENTRYPOINT_FAILED_ERROR).map_err(SyscallExecutionError::from)?);
        return Err(SyscallExecutionError::SyscallError { error_data: raw_retdata });
    }

    Ok(create_retdata_segment(vm, syscall_handler, &raw_retdata)?)
```


<!-- Sent from Reviewable.io -->

2024-09-18 14:58 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 13 files at r7, 1 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 8 of 16 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 41 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74bibR2iTMltTpnKZX:-O74bibR2iTMltTpnKZY:b-mzb29e) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L41)):*
> ```XML
>             failed: false,
>             ..CallExecution::default()
>         }
> ```

Isn't it enough?



_Suggestion:_
```XML
    assert!(!res.execution.failed);
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 43 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74bwAC5bkL4xKkc4q5:-O74bwAC5bkL4xKkc4q6:b-julevq) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L43)):*
> ```XML
>         }
>     );
> }
> ```

Please check the `failed` and `retdata` of the child call also here



_Code quote:_
```XML
    );
}
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 32 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74a2IpB2uyXRLxXtPd:-O74a2IpB2uyXRLxXtPe:b3jcqkq) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L32)):*
> ```XML
>     assert_eq!(
>         format_panic_data(&call_info.execution.retdata.0),
>         "0x4f7574206f6620676173 ('Out of gas')"
> ```

FYI @noaov1 - Native tests are going to fail here until we add the revert support to their syscall handler



_Code quote:_
```XML
    assert_eq!(
        format_panic_data(&call_info.execution.retdata.0),
        "0x4f7574206f6620676173 ('Out of gas')"
```


<!-- Sent from Reviewable.io -->

2024-09-19 05:54 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 8 of 16 files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 855 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O77q4rU3TzmNYp962XG:-O77q4rVE7Y-MZIUxgpD:bx28vkk) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/hint_processor.rs#L855)):*
> ```XML
>     if failed {
>         raw_retdata
>             .push(Felt::from_hex(ENTRYPOINT_FAILED_ERROR).map_err(SyscallExecutionError::from)?);
> ```

Need to do this in the OS as well, right?



_Code quote:_
```XML
.push(Felt::from_hex(ENTRYPOINT_FAILED_ERROR)
```


<!-- Sent from Reviewable.io -->

2024-09-19 05:58 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 8 of 16 files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 101 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O77qp6zDGUr6bNrTMpn:-O77qp6zDGUr6bNrTMpo:b-m1i2fz) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L101)):*
> ```Cairo
>     #[external(v0)]
>     fn test_revert_helper(ref self: ContractState) {
>         self.my_storage_var.write(17);
> ```

Can you add message + event + replace_class/deploy here before the panic?



_Code quote:_
```Cairo
    #[external(v0)]
    fn test_revert_helper(ref self: ContractState) {
        self.my_storage_var.write(17);
```


<!-- Sent from Reviewable.io -->

2024-09-19 06:31 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 190 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O77yg332PFxzhCtWcOa:-O77yg332PFxzhCtWcOb:b-t3yniq) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/hint_processor.rs#L190)):*
> ```XML
> }
> 
> /// Error codes returned by Cairo 1.0 code.
> ```

I think most of those are returned by the OS.



_Code quote:_
```XML
Error codes returned by Cairo 1.0 code.
```


<!-- Sent from Reviewable.io -->

2024-09-19 06:38 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 855 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O77q4rU3TzmNYp962XG:-O78-JbiBm4tkjihH2Zm:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/hint_processor.rs#L855)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Need to do this in the OS as well, right?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2024-09-19 06:49 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/transaction/account_transaction.rs` line 461 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O6taW-o12xEGd0gpH6Y:-O781c0779AFlEOZD-Kf:bvth56w) ([raw file](https://github.com/starkware-libs/sequencer/blob/447fc11d2eb03c3c7bd5a0bc424e4ab2d8ec5410/crates/blockifier/src/transaction/account_transaction.rs#L461)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not sure if this should be here or in some kind of wrapper and how to call the wrapper.
</blockquote></details>

reverted


<!-- Sent from Reviewable.io -->

2024-09-19 08:04 UTC, Yoni-Starkware requested changes
> Reviewed 2 of 8 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 6 of 17 files reviewed, 12 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 206 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O78HzQA4sje-atMJO5P:-O78HzQA4sje-atMJO5Q:b-srlp9p) ([raw file](https://github.com/starkware-libs/sequencer/blob/37c9ae50f7ff5a961a0fe1f141ec9795de709098/crates/blockifier/src/execution/call_info.rs#L206)):*
> ```XML
>             if call_info.execution.failed {
>                 continue;
>             }
> ```

You have [this](https://github.com/starkware-libs/sequencer/blob/6f89ecefdd80a8172464f18d244a219b7451f1f7/crates/blockifier/src/execution/call_info.rs#L50), and [this](https://github.com/starkware-libs/sequencer/blob/d5d44a4000894924291a4900e42ddb988a88ca5c/crates/blockifier/src/transaction/objects.rs#L464)... 
it's risky. I'll try to improve this in a preliminary PR



_Code quote:_
```XML
        for call_info in self.iter() {
            if call_info.execution.failed {
                continue;
            }
```


<!-- Sent from Reviewable.io -->

2024-09-19 08:14 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 6 of 17 files reviewed, 12 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 206 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O78HzQA4sje-atMJO5P:-O78Kwgc4so6ahnZ5dDp:bwuq4ct) ([raw file](https://github.com/starkware-libs/sequencer/blob/37c9ae50f7ff5a961a0fe1f141ec9795de709098/crates/blockifier/src/execution/call_info.rs#L206)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You have [this](https://github.com/starkware-libs/sequencer/blob/6f89ecefdd80a8172464f18d244a219b7451f1f7/crates/blockifier/src/execution/call_info.rs#L50), and [this](https://github.com/starkware-libs/sequencer/blob/d5d44a4000894924291a4900e42ddb988a88ca5c/crates/blockifier/src/transaction/objects.rs#L464)... 
it's risky. I'll try to improve this in a preliminary PR
</blockquote></details>

Oh, you cleared them. Great
So remove this skip - a reverted entrypoint should be considered here - we load its class and storage in the OS


<!-- Sent from Reviewable.io -->

2024-09-19 13:14 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 6 of 17 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 212 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74ShVL7Ic9fmZjAIra:-O77ypWP7dP1PSnRWxno:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/hint_processor.rs#L212)):*
> ```XML
> // "ENTRYPOINT_FAILED";
> pub const ENTRYPOINT_FAILED_ERROR: &str =
>     "0x000000000000000000000000000000454e545259504f494e545f4641494c4544";
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 851 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74_PqK2MQh_sZIOG22:-O780F8xCHrtVsiH5DVS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/hint_processor.rs#L851)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We need to handle events and messages. Safer to remove them. Otherwise we need to change `summarize` here and python's equivalent
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 860 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74W9Nc4ZhX_dGf0V6M:-O78B_44-z284Ovbci84:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/hint_processor.rs#L860)):*
> ```XML
> 
>     let retdata_segment = create_retdata_segment(vm, syscall_handler, &raw_retdata)?;
>     Ok(retdata_segment)
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 41 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O74bibR2iTMltTpnKZX:-O781TVlB-cvIVjvJyic:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cbfaa71d967cbb40498d2e43f0e5ce53c6b5418/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L41)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Isn't it enough?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-19 13:47 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 6 of 17 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 848 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O79WofOAeqi2TXIDVrL:-O79WofP63siVRJJ3Pfy:b6pm2yf) ([raw file](https://github.com/starkware-libs/sequencer/blob/37c9ae50f7ff5a961a0fe1f141ec9795de709098/crates/blockifier/src/execution/syscalls/hint_processor.rs#L848)):*
> ```XML
> 
>         // Delete events and l2_to_l1_messages from the reverted call.
>         let execution = &mut syscall_handler.inner_calls.last_mut().unwrap().execution;
> ```

Oh basa. What about inner calls?
I'll ask @ArielElp 



_Code quote:_
```XML
        // Delete events and l2_to_l1_messages from the reverted call.
        let execution = &mut syscall_handler.inner_calls.last_mut().unwrap().execution;
```


<!-- Sent from Reviewable.io -->

2024-09-22 07:07 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: 5 of 17 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 848 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O79WofOAeqi2TXIDVrL:-O7NYeBh9nCacfXP-MP-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/37c9ae50f7ff5a961a0fe1f141ec9795de709098/crates/blockifier/src/execution/syscalls/hint_processor.rs#L848)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh basa. What about inner calls?
I'll ask @ArielElp
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/call_info.rs` line 206 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O78HzQA4sje-atMJO5P:-O79SZU9Ao9tXl6IiHQc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/37c9ae50f7ff5a961a0fe1f141ec9795de709098/crates/blockifier/src/execution/call_info.rs#L206)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh, you cleared them. Great
So remove this skip - a reverted entrypoint should be considered here - we load its class and storage in the OS
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-22 07:18 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 13 files at r7, 3 of 8 files at r11, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381#-:-O7Na2wZ39qt9J3IrYO3:bnfp4nl)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-22 07:18 UTC, Yoni-Starkware reviewed
(Fix the OS with ENTRYPOINT_FAILED before merging)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381#-:-O7Na5be4bS_0yzndn9G:b-s6yei0)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-22 11:30 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 4 files at r4, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 108 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O7OT93-2zb0u5Ifi9E5:-O7OT9306EraEA5zPhGO:b5fstwr) ([raw file](https://github.com/starkware-libs/sequencer/blob/410998003c46e199be9cd3e4c87b3e7ee1f0e2b1/crates/blockifier/src/execution/entry_point_execution.rs#L108)):*
> ```XML
>     )?;
> 
>     if call_info.execution.failed && !context.versioned_constants().enable_reverts {
> ```

Revert new line



_Suggestion:_
```XML
    )?;
    if call_info.execution.failed && !context.versioned_constants().enable_reverts {
```


<!-- Sent from Reviewable.io -->

2024-09-23 06:30 UTC, Yoni-Starkware approved these changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-10-06 14:20 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381#-:-O8XC3XxEb4BmcqQEBCS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-10-06 14:22 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 20 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/381#-O8XCL_c7rodVkxVU1d8:-O8XCL_c7rodVkxVU1d9:b-13mg4v) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbebe80f90dedd4be92efda8b84f48a584cd558d/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L20)):*
> ```XML
> 
> #[test]
> fn test_call_contract_that_panics() {
> ```

@noaov1 TODO: test also with native once integrated


<!-- Sent from Reviewable.io -->

2024-10-06 14:22 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-10-07 07:34 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 4 files at r4, 2 of 13 files at r7, 1 of 10 files at r9, 2 of 8 files at r11, 2 of 6 files at r12, 1 of 3 files at r13, 7 of 9 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/381)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-10-07 07:35 UTC, merged