feat(consensus): redefine consensus height metric to working height
starkware-libs/sequencer pull request #404
Opened 2024-08-12 09:01 UTC by matan-starkware

This will be more useful than stating the most recent decision when we are stuck on block 0.
Also moved out of Context::decision due to sync

2024-08-12 09:01 UTC, matan-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/404?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#404** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/404?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#389** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/389?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#403](https://github.com/starkware-libs/sequencer/pull/403) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/403?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#387** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/387?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#386** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/386?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-12 11:58 UTC, asmaastarkware requested changes
you should make changes in run_consensus.py, in case one node got stuck and didn't start (now height = 0 not None)

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/404#-:-O45RTrKCp-DYl67zgyV:bkk9anx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-08-14 04:33 UTC, asmaastarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/404#-:-O4E9CyeBQz3J_SV5o29:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-08-14 11:01 UTC, asmaastarkware approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/404)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-08-15 07:00 UTC, matan-starkware commented
### Merge activity

* **Aug 15, 3:00 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/404).

2024-08-15 07:01 UTC, merged