feat(batcher): proposals manager module
starkware-libs/sequencer pull request #417
Opened 2024-08-12 14:20 UTC by yair-starkware

2024-08-13 11:12 UTC, dafnamatsry requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O49uzOd12M3l4lxYc3v:-O49uzOd12M3l4lxYc3w:borreg2) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2880fadbf04831565413ba447053bd64cc61a48/crates/batcher/src/proposals_manager.rs#L16)):*
> ```XML
> #[async_trait]
> pub trait ProposalGeneration {
>     async fn start_new_proposal(&mut self, proposal_id: ProposalId);
> ```

Please document.



_Code quote:_
```XML
async fn start_new_proposal(&mut self, proposal_id: ProposalId);
```
___
*[`crates/batcher/src/proposals_manager.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O49uDSd2Zh6UHjSW6pG:-O49uDSd2Zh6UHjSW6pH:bxfhhtp) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2880fadbf04831565413ba447053bd64cc61a48/crates/batcher/src/proposals_manager.rs#L31)):*
> ```XML
> }
> 
> // TODO: Use BuilderTask when it is available.
> ```

What do you mean with BuilderTask?



_Code quote:_
```XML
// TODO: Use BuilderTask when it is available.
```
___
*[`crates/batcher/src/proposals_manager.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O49vBE85nYIMcIDl9Z7:-O49vBE85nYIMcIDl9Z8:b-tex1sn) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2880fadbf04831565413ba447053bd64cc61a48/crates/batcher/src/proposals_manager.rs#L50)):*
> ```XML
>     storage_writer: StorageWriter,
>     mempool_client: SharedMempoolClient,
>     proposals_in_generation: HashMap<ProposalId, Proposal>,
> ```

What does this contain? Blocks we propose and validate, or only propose?
"in_generation" sounds like only blocks that we propose. In that case, there is only one block that can be proposed at any time.



_Code quote:_
```XML
proposals_in_generation
```


<!-- Sent from Reviewable.io -->

2024-08-14 11:48 UTC, dafnamatsry requested changes
> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FMLOx3k1bDKXlOprP:-O4FMLOx3k1bDKXlOprQ:b-szrvci) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L97)):*
> ```XML
> {
>     config: ProposalsManagerConfig,
>     mempool_client: Arc<M>,
> ```

Why not `SharedMempoolClient`, and define a similar one for the consensus client?



_Code quote:_
```XML
mempool_client: Arc<M>,
```
___
*[`crates/batcher/src/proposals_manager.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4Fa19s25g-BDbWTf6L:-O4Fa19t2pFs9yCTKZqH:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L99)):*
> ```XML
>     mempool_client: Arc<M>,
>     consensus_client: Arc<C>,
>     /// The proposal currently being generated, if any.
> ```





_Suggestion:_
```XML
/// The block proposal that is currently being proposed, if any. 
/// At any given time, there can be only one block being proposed, though multiple blocks can be validated simultaneously.
```
___
*[`crates/batcher/src/proposals_manager.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FNjep8LeWDvTJch0Y:-O4FNjep8LeWDvTJch0Z:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L123)):*
> ```XML
>         &mut self,
>         proposal_id: ProposalId,
>         _hight: BlockNumber,
> ```





_Suggestion:_
```XML
_height
```
___
*[`crates/batcher/src/proposals_manager.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FNtIlBLoxcAZMmULA:-O4FNtIlBLoxcAZMmULB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L124)):*
> ```XML
>         proposal_id: ProposalId,
>         _hight: BlockNumber,
>         _base_proposa_id: Option<ProposalId>,
> ```





_Suggestion:_
```XML
_base_proposal_id
```
___
*[`crates/batcher/src/proposals_manager.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FOCXl89rTP2dvcVZY:-O4FOCXl89rTP2dvcVZZ:ba2bxsb) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L126)):*
> ```XML
>         _base_proposa_id: Option<ProposalId>,
>     ) -> ProposalsManagerResult<()> {
>         info!("Starting generation of new proposal.");
> ```

needed? (the `instrument` covers that no?)



_Code quote:_
```XML
info!("Starting generation of new proposal.");
```
___
*[`crates/batcher/src/proposals_manager.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FhlAG5WyTn8HDdHJD:-O4FhlAG5WyTn8HDdHJE:b-8zs6q9) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L137)):*
> ```XML
> 
>         // TODO: Should we return the task handle?
>         tokio::spawn(generate_block_task.in_current_span());
> ```

What does it do?



_Code quote:_
```XML
.in_current_span()
```
___
*[`crates/batcher/src/proposals_manager.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FPMsr7I6aqQKb6XTn:-O4FPMsr7I6aqQKb6XTo:bogn3dv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L182)):*
> ```XML
>             // here or from inside the function.
>             block_builder.add_txs(mempool_txs);
>             tokio::time::sleep(sleep_time_between_add_txs).await;
> ```

`block_builder.add_txs(...)` should return the status of the block, i.e. if it is full or can accept more txs.
You can use it instead of `tokio::time::sleep`



_Code quote:_
```XML
            block_builder.add_txs(mempool_txs);
            tokio::time::sleep(sleep_time_between_add_txs).await;
```


<!-- Sent from Reviewable.io -->

2024-08-15 06:59 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O49uzOd12M3l4lxYc3v:-O4FkP6F8Eqc2B1Ziet0:b-7wso34) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2880fadbf04831565413ba447053bd64cc61a48/crates/batcher/src/proposals_manager.rs#L16)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please document.
</blockquote></details>

Not relevant anymore
___
*[`crates/batcher/src/proposals_manager.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O49uDSd2Zh6UHjSW6pG:-O4FkZ2R7fube_kOjQw4:b-7wso34) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2880fadbf04831565413ba447053bd64cc61a48/crates/batcher/src/proposals_manager.rs#L31)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What do you mean with BuilderTask?
</blockquote></details>

Not relevant anymore
___
*[`crates/batcher/src/proposals_manager.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O49vBE85nYIMcIDl9Z7:-O4Fiw5b9pvNqI-bv6Bj:b33yf54) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2880fadbf04831565413ba447053bd64cc61a48/crates/batcher/src/proposals_manager.rs#L50)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What does this contain? Blocks we propose and validate, or only propose?
"in_generation" sounds like only blocks that we propose. In that case, there is only one block that can be proposed at any time.
</blockquote></details>

This is for the single block that we propose, and because we can have only 1 it is a single ProposalId
___
*[`crates/batcher/src/proposals_manager.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4Fa19s25g-BDbWTf6L:-O4Jo8ZkBeVgcId3zWdJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L99)):*
> ```XML
>     mempool_client: Arc<M>,
>     consensus_client: Arc<C>,
>     /// The proposal currently being generated, if any.
> ```

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FNjep8LeWDvTJch0Y:-O4JoCLR8_sVmdL2fbv4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L123)):*
> ```XML
>         &mut self,
>         proposal_id: ProposalId,
>         _hight: BlockNumber,
> ```

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FNtIlBLoxcAZMmULA:-O4JoEGC4tt5c2VDJpjw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L124)):*
> ```XML
>         proposal_id: ProposalId,
>         _hight: BlockNumber,
>         _base_proposa_id: Option<ProposalId>,
> ```

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FOCXl89rTP2dvcVZY:-O4FjFlH7u4ebHRN5IBd:b-y87z5o) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L126)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

needed? (the `instrument` covers that no?)
</blockquote></details>

The instrument starts a new span, but it doesn't produce an event (unless the subscriber is configured to add events for opening/closing of spans).
___
*[`crates/batcher/src/proposals_manager.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FhlAG5WyTn8HDdHJD:-O4FjUHd71ZpTbAPmm_r:bmrlb2j) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L137)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What does it do?
</blockquote></details>

It makes the span of the task be a chile of the span we are currently inside.
You need it when you use `spawn`.
___
*[`crates/batcher/src/proposals_manager.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FPMsr7I6aqQKb6XTn:-O4FjtuBAdLWSUOzJlVK:bo9best) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L182)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

`block_builder.add_txs(...)` should return the status of the block, i.e. if it is full or can accept more txs.
You can use it instead of `tokio::time::sleep`
</blockquote></details>

I added the return value, but the sleep is still needed because if the mempool is empty then the while loop will stuck the Tokio executor


<!-- Sent from Reviewable.io -->

2024-08-15 08:27 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FMLOx3k1bDKXlOprP:-O4K8VLKAF-vtZhudt4s:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L97)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why not `SharedMempoolClient`, and define a similar one for the consensus client?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-15 10:47 UTC, dafnamatsry requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 8 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4Fa19s25g-BDbWTf6L:-O4KXJ4QAM-26ikN6OMQ:bh46hj7) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L99)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

another change, sorry for the confusion:

```
/// The block proposal that is currently being executed, if any.
/// At any given time, there can be only one proposal being actively executed (either proposed or validated).
```
___
*[`crates/batcher/src/proposals_manager.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FPMsr7I6aqQKb6XTn:-O4KDOMi-SVxUpM-ZcVP:bpt2m0c) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L182)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I added the return value, but the sleep is still needed because if the mempool is empty then the while loop will stuck the Tokio executor
</blockquote></details>

Maybe we can hide the sleep in something like `try_get_txs(min_num_txs, max_num_txs, timeout)`. WDYT?
___
*[`crates/batcher/src/proposals_manager.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KZ-cl49EwXWWKj4JL:-O4KZ-cl49EwXWWKj4JM:bsi9o7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L80)):*
> ```XML
> // TODO: Remove dead_code attribute.
> #[allow(dead_code)]
> pub(crate) struct ProposalsManager {
> ```

The manager should also hold a mapping from a `ProposalId` to a `Proposal`.
`Proposal` should hold the block builder, that proposal status (that's what I can think of for now).

You can add it in another PR if you prefer.
___
*[`crates/batcher/src/proposals_manager.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KVbpA7oZVZlZUKqfJ:-O4KVbpB9pu3S8FI2qSD:b-ww9d7i) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L83)):*
> ```XML
>     config: ProposalsManagerConfig,
>     mempool_client: SharedMempoolClient,
>     consensus_client: SharedConsensusClient,
> ```

Let's remove it for now, as the communication with the consensus might be different.



_Code quote:_
```XML
consensus_client: SharedConsensusClient,
```
___
*[`crates/batcher/src/proposals_manager.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KWMxgEooJK6IFpEiI:-O4KWMxgEooJK6IFpEiJ:b1mq6ly) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L156)):*
> ```XML
>     // Not a passing &self method, because it's called from tokio::spawn.
>     #[instrument(skip(mempool_client, consensus_client), err)]
>     async fn generate_block_task(
> ```

Consider making it a standalone function outside of the `ProposalManager`



_Code quote:_
```XML
async fn generate_block_task(
```
___
*[`crates/batcher/src/proposals_manager.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KWpPK2MFKnFWrrNxl:-O4KWpPK2MFKnFWrrNxm:bpl8vcg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L165)):*
> ```XML
>         debug!("Starting a new block proposal generation task.");
>         let block_builder = block_builder::BlockBuilder::new(consensus_client.clone());
>         // TODO: Should this code be here or in the block_builder?
> ```

here, the block_builder only gets txs from outside.



_Code quote:_
```XML
// TODO: Should this code be here or in the block_builder?
```
___
*[`crates/batcher/src/proposals_manager_test.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KdJ3YCfiRpunRVDMT:-O4KdJ3Z2OI-DrfN3SVD:b5uynkm) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager_test.rs#L13)):*
> ```XML
> #[tokio::test]
> async fn multiple_proposals_generation() {
>     configure_tracing();
> ```

What's this?



_Code quote:_
```XML
configure_tracing();
```


<!-- Sent from Reviewable.io -->

2024-08-19 07:47 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 8 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4Fa19s25g-BDbWTf6L:-O4dUtrV3Qa8S66gWCFl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L99)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

another change, sorry for the confusion:

```
/// The block proposal that is currently being executed, if any.
/// At any given time, there can be only one proposal being actively executed (either proposed or validated).
```
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FPMsr7I6aqQKb6XTn:-O4dVXGxCT2A31JvI8og:b-7sktpy) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L182)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Maybe we can hide the sleep in something like `try_get_txs(min_num_txs, max_num_txs, timeout)`. WDYT?
</blockquote></details>

I don't see any difference
___
*[`crates/batcher/src/proposals_manager.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KZ-cl49EwXWWKj4JL:-O4dWb9JDln1stet-c3y:b-8utae1) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L80)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

The manager should also hold a mapping from a `ProposalId` to a `Proposal`.
`Proposal` should hold the block builder, that proposal status (that's what I can think of for now).

You can add it in another PR if you prefer.
</blockquote></details>

For now I added the task handle as a member to the struct.
There is no need for a mapping because we can have only 1 task at a time.
___
*[`crates/batcher/src/proposals_manager.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KVbpA7oZVZlZUKqfJ:-O4d_PTx7aRD44lXuvYm:bzh5rmf) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L83)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Let's remove it for now, as the communication with the consensus might be different.
</blockquote></details>

Done.
I talked with Matan last week about the communication flows between the consensus and the Batcher.
I will modify the functions accordingly in a following PR.
___
*[`crates/batcher/src/proposals_manager.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KWMxgEooJK6IFpEiI:-O4dV1HjAuN4QroW1VoH:b8ruph2) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L156)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider making it a standalone function outside of the `ProposalManager`
</blockquote></details>

In a separate PR (will add a struct for passing the members)
___
*[`crates/batcher/src/proposals_manager.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KWpPK2MFKnFWrrNxl:-O4dVKNhB1rYpjuDcq_U:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L165)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

here, the block_builder only gets txs from outside.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KdJ3YCfiRpunRVDMT:-O4dWHxU1lpQBXSoYSPV:byczn69) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager_test.rs#L13)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What's this?
</blockquote></details>

Left by mistake.
With this you can see the tracing events emitted during the test


<!-- Sent from Reviewable.io -->

2024-08-19 11:00 UTC, dafnamatsry requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FPMsr7I6aqQKb6XTn:-O4eEKgH0OyROdQxLg05:bclqlpg) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L182)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't see any difference
</blockquote></details>

No logical difference I agree, but would be more readable IMO.
___
*[`crates/batcher/src/proposals_manager.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KZ-cl49EwXWWKj4JL:-O4eE6wK9kCD43DVxUHS:b514acz) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L80)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

For now I added the task handle as a member to the struct.
There is no need for a mapping because we can have only 1 task at a time.
</blockquote></details>

We can have 1 task at a time, yes. But we might have multiple proposals waiting for a decision.
___
*[`crates/batcher/src/proposals_manager.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4eHeIw8-UOf2KEHa1j:-O4eHeIw8-UOf2KEHa1k:b-eehdva) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ad420dcc008e99368097a14653f41f0c8079c5b/crates/batcher/src/proposals_manager.rs#L121)):*
> ```XML
>         );
> 
>         self.generation_task_handle = Some(tokio::spawn(generate_block_task.in_current_span()));
> ```

I guess we need it to hold the status of the task?
What about the txs included in the proposal? We will need access to them as well.



_Code quote:_
```XML
self.generation_task_handle
```


<!-- Sent from Reviewable.io -->

2024-08-19 11:50 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4eTIO9EYQ1D0KuLDiQ:-O4eTIO9EYQ1D0KuLDiR:b-5rqdsd) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ad420dcc008e99368097a14653f41f0c8079c5b/crates/batcher/src/proposals_manager.rs#L154)):*
> ```XML
>         max_txs_per_mempool_request: usize,
>         sleep_time_between_add_txs: std::time::Duration,
>     ) -> ProposalsManagerResult<()> {
> ```

Can you add a TODO here to update the mempool, that a new block is being proposed?


<!-- Sent from Reviewable.io -->

2024-08-19 13:08 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FPMsr7I6aqQKb6XTn:-O4eeimoC4DMzcv8JjFE:b-jxxjxu) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L182)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

No logical difference I agree, but would be more readable IMO.
</blockquote></details>

What should I do when getting timed out?
Abort the builder task?
Doesn't sound correct to me
___
*[`crates/batcher/src/proposals_manager.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KZ-cl49EwXWWKj4JL:-O4eXjeu42JZtaQKFgTy:bsuoaz6) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L80)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We can have 1 task at a time, yes. But we might have multiple proposals waiting for a decision.
</blockquote></details>

Ok, I  think it will be better to add this mapping when we work on the feature that needs it
___
*[`crates/batcher/src/proposals_manager.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4eHeIw8-UOf2KEHa1j:-O4edK-_4jDTRjNT8DEW:b5525u0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ad420dcc008e99368097a14653f41f0c8079c5b/crates/batcher/src/proposals_manager.rs#L121)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I guess we need it to hold the status of the task?
What about the txs included in the proposal? We will need access to them as well.
</blockquote></details>

WDYM status of the task?
The handle has an `is_finished` function.

I will handle storing the txs in a separate PR when I work on streaming them
___
*[`crates/batcher/src/proposals_manager.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4eTIO9EYQ1D0KuLDiQ:-O4eeMIfB8vktRtuczFO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ad420dcc008e99368097a14653f41f0c8079c5b/crates/batcher/src/proposals_manager.rs#L154)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you add a TODO here to update the mempool, that a new block is being proposed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-20 09:21 UTC, dafnamatsry requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FPMsr7I6aqQKb6XTn:-O4j0bDH1Ll9ujr7Lu2_:b-s3js5j) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L182)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What should I do when getting timed out?
Abort the builder task?
Doesn't sound correct to me
</blockquote></details>

We should close the block when time is out.

And actually there is a difference.
Right now, we will sleep/yield even if the mempool is not empty.
___
*[`crates/batcher/src/proposals_manager.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KZ-cl49EwXWWKj4JL:-O4iz5oO9zmXTQVTH_GQ:bb5yzzu) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L80)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Ok, I  think it will be better to add this mapping when we work on the feature that needs it
</blockquote></details>

I don't mind it being in another PR, but we need this also in the propose flow.
When we finish a task, we need to keep the result (it's state diff, etc.) and wait until the client either commits/drops the proposal.
___
*[`crates/batcher/src/proposals_manager.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4eHeIw8-UOf2KEHa1j:-O4j0KF15r6eP3UKrBX5:b6uw3at) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ad420dcc008e99368097a14653f41f0c8079c5b/crates/batcher/src/proposals_manager.rs#L121)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

WDYM status of the task?
The handle has an `is_finished` function.

I will handle storing the txs in a separate PR when I work on streaming them
</blockquote></details>

Just wondering where are you planning to use this task handle?
___
*[`crates/batcher/src/proposals_manager.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4j4ozHB42qfNHw9rGk:-O4j4ozHB42qfNHw9rGl:b-v0duql) ([raw file](https://github.com/starkware-libs/sequencer/blob/22648f505aae1599ea8d0bdea1c1a16a08602d81/crates/batcher/src/proposals_manager.rs#L153)):*
> ```XML
>             // Allow other tasks to run in case we are blocking the tokio runtime (when the mempool
>             // is empty).
>             tokio::task::yield_now().await;
> ```

Why did you change it?



_Code quote:_
```XML
tokio::task::yield_now()
```


<!-- Sent from Reviewable.io -->

2024-08-20 10:01 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FPMsr7I6aqQKb6XTn:-O4jAliN8gjknlQ_H33E:bcjkkwv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L182)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We should close the block when time is out.

And actually there is a difference.
Right now, we will sleep/yield even if the mempool is not empty.
</blockquote></details>

Got you.
Will add it in a separate PR.
___
*[`crates/batcher/src/proposals_manager.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4KZ-cl49EwXWWKj4JL:-O4jD6eK7T-AvMbXayQf:b-a7xcmq) ([raw file](https://github.com/starkware-libs/sequencer/blob/a87f24d77603d4ebbde5c9588da5d7a89be73c43/crates/batcher/src/proposals_manager.rs#L80)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I don't mind it being in another PR, but we need this also in the propose flow.
When we finish a task, we need to keep the result (it's state diff, etc.) and wait until the client either commits/drops the proposal.
</blockquote></details>

For now I just want to implement a basic flow where the client callback starts a builder task.
I will add the rest of the flow in future PRs.
___
*[`crates/batcher/src/proposals_manager.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4eHeIw8-UOf2KEHa1j:-O4jB5ne0AyQtUzkFp1N:bt8tbug) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ad420dcc008e99368097a14653f41f0c8079c5b/crates/batcher/src/proposals_manager.rs#L121)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Just wondering where are you planning to use this task handle?
</blockquote></details>

I just started working on actually connecting the API of the batcher client to the proposals manager, so some things will change.
I think we will need the handle to abort tasks / monitoring / tests.
There's also an issue where Tokio doesn't guarantee the spawned tasks will start until joining on their handle. This is still WIP.
___
*[`crates/batcher/src/proposals_manager.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4j4ozHB42qfNHw9rGk:-O4jAd8_89GlT-RuNexP:bwbmxfo) ([raw file](https://github.com/starkware-libs/sequencer/blob/22648f505aae1599ea8d0bdea1c1a16a08602d81/crates/batcher/src/proposals_manager.rs#L153)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why did you change it?
</blockquote></details>

Didn't know about this function when I used sleep, this is better than sleeping


<!-- Sent from Reviewable.io -->

2024-08-20 10:09 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FPMsr7I6aqQKb6XTn:-O4jEoHK-FzBTgxlwAkb:b231b11) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L182)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Got you.
Will add it in a separate PR.
</blockquote></details>

I don't like pushing bugs to main, at least add an `if mempool_txs.len() == 0` and move it to be right after the call to `get_txs`.
___
*[`crates/batcher/src/proposals_manager.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4eHeIw8-UOf2KEHa1j:-O4jEOU4-kmI_hR9IOdu:byhz43j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ad420dcc008e99368097a14653f41f0c8079c5b/crates/batcher/src/proposals_manager.rs#L121)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I just started working on actually connecting the API of the batcher client to the proposals manager, so some things will change.
I think we will need the handle to abort tasks / monitoring / tests.
There's also an issue where Tokio doesn't guarantee the spawned tasks will start until joining on their handle. This is still WIP.
</blockquote></details>

In that case, let's remove the `generation_task_handle`, and add it if needed.
___
*[`crates/batcher/src/proposals_manager.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4j4ozHB42qfNHw9rGk:-O4jFTwk85-Gr3r2PfV0:b-ync56j) ([raw file](https://github.com/starkware-libs/sequencer/blob/22648f505aae1599ea8d0bdea1c1a16a08602d81/crates/batcher/src/proposals_manager.rs#L153)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Didn't know about this function when I used sleep, this is better than sleeping
</blockquote></details>

But how do we know it won't be just a busy wait? We have no control on when the task will continue with this...


<!-- Sent from Reviewable.io -->

2024-08-20 12:11 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4FPMsr7I6aqQKb6XTn:-O4jgNAS3EzNJfBQMh9Z:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c473bc78f97b3524c480cfc58b75834fffe1ab/crates/batcher/src/proposals_manager.rs#L182)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I don't like pushing bugs to main, at least add an `if mempool_txs.len() == 0` and move it to be right after the call to `get_txs`.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4eHeIw8-UOf2KEHa1j:-O4jgJy1CPF8WczSmzXV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ad420dcc008e99368097a14653f41f0c8079c5b/crates/batcher/src/proposals_manager.rs#L121)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

In that case, let's remove the `generation_task_handle`, and add it if needed.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4j4ozHB42qfNHw9rGk:-O4jL4eqD9T2xImspV50:blf794f) ([raw file](https://github.com/starkware-libs/sequencer/blob/22648f505aae1599ea8d0bdea1c1a16a08602d81/crates/batcher/src/proposals_manager.rs#L153)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

But how do we know it won't be just a busy wait? We have no control on when the task will continue with this...
</blockquote></details>

I am not sure I understand, let's talk f2f.
Added a TODO


<!-- Sent from Reviewable.io -->

2024-08-21 11:51 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417#-:-O4ohq-K8J7dxrgobdbE:bg7igk9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-08-22 09:29 UTC, alonh5 requested changes
> Reviewed 1 of 5 files at r2, 2 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 8 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 14 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tFuqz57nO0-fUsQTH:-O4tFuqz57nO0-fUsQTI:b-bcpou7) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L14)):*
> ```XML
> 
> // TODO: Should be defined in SN_API probably (shared with the consensus).
> pub type ProposalId = u64;
> ```

Consider removing this type, I don't think it adds clarity, just another jump in the code the reader has to do.



_Code quote:_
```XML
pub type ProposalId = u64;
```
___
*[`crates/batcher/src/proposals_manager.rs` line 73 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tF3Fr21cI-h8NaWWw:-O4tF3Fr21cI-h8NaWWx:b-8oo5fi) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L73)):*
> ```XML
> }
> 
> impl ProposalsManager {
> ```

Sounds better I think



_Suggestion:_
```XML
ProposalManager
```
___
*[`crates/batcher/src/proposals_manager.rs` line 85 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tORfgAeHxgXkdDAXR:-O4tORfgAeHxgXkdDAXS:bnm8p4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L85)):*
> ```XML
>     pub async fn generate_block_proposal(
>         &mut self,
>         proposal_id: ProposalId,
> ```

Should the ids be sequential? Right now the id value isn't used it can be anything
___
*[`crates/batcher/src/proposals_manager.rs` line 86 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tH6eBA-HjEs90k09h:-O4tH6eBA-HjEs90k09i:baw24e6) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L86)):*
> ```XML
>         &mut self,
>         proposal_id: ProposalId,
>         timeout: tokio::time::Instant,
> ```

Do you plan to change this between tasks? If not maybe this could be added to the proposal manager config.
Also, consider storing the duration of the timeout and only passing the instant to the task.



_Code quote:_
```XML
timeout: tokio::time::Instant,
```
___
*[`crates/batcher/src/proposals_manager.rs` line 186 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tENm7E4xEUQTv--UW:-O4tENm7E4xEUQTv--UX:b-gnu82x) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L186)):*
> ```XML
>             // TODO: This is cpu bound operation, should use spawn_blocking / Rayon / std::thread
>             // here or from inside the function.
>             let is_block_ready = block_builder.add_txs(mempool_txs.as_slice());
> ```

Another option



_Suggestion:_
```XML
&mempool_txs
```
___
*[`crates/batcher/src/proposals_manager.rs` line 192 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tLOYV0EAa-aRT16qz:-O4tLOYV0EAa-aRT16r-:b-sx4ex1) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L192)):*
> ```XML
>         }
> 
>         info!("Closing block.");
> ```

This is reached even when timeout is reached, is that the intention?



_Code quote:_
```XML
info!("Closing block.");
```
___
*[`crates/batcher/src/proposals_manager_test.rs` line 1 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tIcbDD9ckqhweSTL3:-O4tIcbDD9ckqhweSTL4:bus05vo) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager_test.rs#L1)):*
> ```XML
> use std::sync::Arc;
> ```

Consider having the test module in the same file, as is seen [here](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html)
___
*[`crates/batcher/src/proposals_manager_test.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tLisL9gkMm8bGGqwL:-O4tLisL9gkMm8bGGqwM:b-m4ikqq) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager_test.rs#L26)):*
> ```XML
>         .unwrap();
> 
>     let another_generate_request = proposals_manager
> ```

Can you add a positive flow?


<!-- Sent from Reviewable.io -->

2024-08-22 12:51 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 7 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 14 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tFuqz57nO0-fUsQTH:-O4u5UPDAk3gycxU502o:bjjt2nz) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L14)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Consider removing this type, I don't think it adds clarity, just another jump in the code the reader has to do.
</blockquote></details>

I disagree, IMO it helps, especially when it is the return type of a function
___
*[`crates/batcher/src/proposals_manager.rs` line 73 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tF3Fr21cI-h8NaWWw:-O4u67Xv807UHCLRYAB8:b-nrlzre) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L73)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Sounds better I think
</blockquote></details>

It will manage more than one proposal eventually
___
*[`crates/batcher/src/proposals_manager.rs` line 85 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tORfgAeHxgXkdDAXR:-O4u6Knt-PI66afgJkYq:bboludi) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L85)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Should the ids be sequential? Right now the id value isn't used it can be anything
</blockquote></details>

Not necessarily, but they will be. in a following PR I use it.
___
*[`crates/batcher/src/proposals_manager.rs` line 86 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tH6eBA-HjEs90k09h:-O4u6aAU9sh7wRMD8YKk:b928gvl) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L86)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do you plan to change this between tasks? If not maybe this could be added to the proposal manager config.
Also, consider storing the duration of the timeout and only passing the instant to the task.
</blockquote></details>

The user provides the deadline by which the block should be ready
___
*[`crates/batcher/src/proposals_manager.rs` line 192 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tLOYV0EAa-aRT16qz:-O4u70BvBTRsiwUSpErh:b-6jl1ai) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L192)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is reached even when timeout is reached, is that the intention?
</blockquote></details>

Yes. We close the block when it's full or when we reached the deadline.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 1 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tIcbDD9ckqhweSTL3:-O4u79Cb0uuzoOImD-b1:b-jstgwi) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager_test.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Consider having the test module in the same file, as is seen [here](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html)
</blockquote></details>

I add more tests in the following PRs so it becomes long.
Besides, all the tests in the repo are in separate files as convention.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tLisL9gkMm8bGGqwL:-O4u7ZGB9WTA21eFHiAM:b-ykeo0i) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager_test.rs#L26)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you add a positive flow?
</blockquote></details>

Added in a following PR where I mock the builder.


<!-- Sent from Reviewable.io -->

2024-08-22 13:08 UTC, alonh5 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 73 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tF3Fr21cI-h8NaWWw:-O4u8fiv9MsTfJURe-BW:b-lo784b) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L73)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It will manage more than one proposal eventually
</blockquote></details>

Both can be used for relating to multiple proposals (like an employee manager isn't a manager of a single employee). But it's just a suggestion.
___
*[`crates/batcher/src/proposals_manager.rs` line 86 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tH6eBA-HjEs90k09h:-O4uB8md43PQtOPoMtSP:b-e2z1t3) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L86)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The user provides the deadline by which the block should be ready
</blockquote></details>

Does the user care about the deadline or about the duration? If he's going to calcualte `now + duration` every time you might as well save it from him. 
___
*[`crates/batcher/src/proposals_manager.rs` line 192 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tLOYV0EAa-aRT16qz:-O4uARQqDI3LfXiVF9Se:b-1pbu4g) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L192)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Yes. We close the block when it's full or when we reached the deadline.
</blockquote></details>

Just notice a block could be empty too.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 1 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tIcbDD9ckqhweSTL3:-O4uA4af9Buk9W_Ezlnd:b7ntv52) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager_test.rs#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I add more tests in the following PRs so it becomes long.
Besides, all the tests in the repo are in separate files as convention.
</blockquote></details>

I know, I think this convention was taken from Python, I'm showing you the rust convention.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tLisL9gkMm8bGGqwL:-O4uBvEW1HdDndqPOPZg:b-87hbi0) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager_test.rs#L26)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Added in a following PR where I mock the builder.
</blockquote></details>

Great


<!-- Sent from Reviewable.io -->

2024-08-25 07:09 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/417)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 73 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tF3Fr21cI-h8NaWWw:-O57LDoe3jVeyoxIeHWg:b35pnve) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L73)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Both can be used for relating to multiple proposals (like an employee manager isn't a manager of a single employee). But it's just a suggestion.
</blockquote></details>

I asked ChatGPT:

```
The name choice between `ProposalManager` and `ProposalsManager` depends on the perspective you want to emphasize:

- **`ProposalManager`**: This implies that the struct manages one proposal at a time or that its primary focus is on managing the proposal concept in a singular sense. It's a more general term, which might make sense if the struct's functions or methods are designed to handle individual proposals, even if the struct manages multiple proposals internally.

- **`ProposalsManager`**: This suggests that the struct manages a collection of proposals. If the struct's primary role is to manage multiple proposals (e.g., adding, removing, listing proposals), then this name might be more descriptive and clear about its purpose.

**Recommendation**: If the struct primarily handles a collection of proposals, `ProposalsManager` might be a better choice. If it's more about managing the concept of proposals, where the singular form might be more intuitive, then `ProposalManager` is appropriate.
```

I think proposals suits better :)
___
*[`crates/batcher/src/proposals_manager.rs` line 86 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tH6eBA-HjEs90k09h:-O57KYLV3YAhN23UJqMf:bmhw93m) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L86)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Does the user care about the deadline or about the duration? If he's going to calcualte `now + duration` every time you might as well save it from him.
</blockquote></details>

He cares about the absolute time (datetime) 
___
*[`crates/batcher/src/proposals_manager.rs` line 192 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/417#-O4tLOYV0EAa-aRT16qz:-O57KtaGDsHb9zSy-305:b2nhswv) ([raw file](https://github.com/starkware-libs/sequencer/blob/749b720efc797aeef79e132404de4bdb23a7dba6/crates/batcher/src/proposals_manager.rs#L192)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Just notice a block could be empty too.
</blockquote></details>

Yep


<!-- Sent from Reviewable.io -->

2024-08-25 07:11 UTC, merged