refactor(network): create test utils
starkware-libs/sequencer pull request #447
Opened 2024-08-14 08:46 UTC by eitanm-starkware

2024-08-21 13:17 UTC, ShahakShama requested changes
> Reviewed 8 of 12 files at r1, 2 of 4 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447)* status: all files reviewed, 15 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4FohC531XrXLHn-XwQ:-O4FohC531XrXLHn-XwR:bug4v8c) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/mod.rs#L136)):*
> ```XML
>     /// Register a new subscriber for sending a single query and receiving multiple responses.
>     /// Panics if the given protocol is already subscribed.
>     /// TODO: Seperate query and response buffer sizes.
> ```

Unrelated to the PR: Could you change the TODO lines to be with 2 slashes and not 3 and move them all below the documentation
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4FpadiAIbfCUzK3BRe:-O4FpadiAIbfCUzK3BRf:bqan2zk) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test.rs#L239)):*
> ```XML
>             .take(VEC1.len())
>             .map(|(i, result)| {
>                 let result: Vec<_> = result.unwrap();
> ```

Do you get a compiler error if you remove this? What's the error?
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4Fsr6vCRjlDWK6bVKf:-O4Fsr6vCRjlDWK6bVKg:b-3a9q3f) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test_utils.rs#L22)):*
> ```XML
> use crate::sqmr::Bytes;
> 
> pub fn create_test_sqmr_client_channel<Query, Response>(
> ```

rename to mock_register_sqmr_protocol_client
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4FtqVECV-ubO_mqXzn:-O4FtqVECV-ubO_mqXzo:b46rrbx) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test_utils.rs#L40)):*
> ```XML
> }
> 
> pub fn create_test_sqmr_server_channel<Query, Response>(
> ```

rename to mock_register_sqmr_protocol_server
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4Fq8DT1uf-vL9x8V09:-O4Fq8DT1uf-vL9x8V0A:bguix68) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test_utils.rs#L119)):*
> ```XML
> pub type TestReceiver<T> = Box<dyn Stream<Item = T> + Unpin + Send>;
> 
> pub struct SqmrClientPayloadForTest<Query: TryFrom<Bytes>, Response: TryFrom<Bytes>> {
> ```

Rename to MockClientResponsesManager or ServerResponsesManagerForTest
Payload should only appear on private structs
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4FqRC23geXe4XOQAaE:-O4FqRC23geXe4XOQAaF:b-9cmgkv) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test_utils.rs#L120)):*
> ```XML
> 
> pub struct SqmrClientPayloadForTest<Query: TryFrom<Bytes>, Response: TryFrom<Bytes>> {
>     pub query: Result<Query, <Query as TryFrom<Bytes>>::Error>,
> ```

remove pub from these two fields and add the following methods: `query(&self)`, `assert_reported(self, timeout)`
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4Fqvvm4CmMkQjSm7P7:-O4Fqvvm4CmMkQjSm7P8:b-dcy06l) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test_utils.rs#L126)):*
> ```XML
> 
> impl<Query: TryFrom<Bytes>, Response: TryFrom<Bytes>> SqmrClientPayloadForTest<Query, Response> {
>     pub async fn send(&mut self, response: Response) -> Result<(), SendError> {
> ```

rename to send_response (like in ServerQueryManager)
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-FOe9IBJipb9YOF-:-O4p-FOe9IBJipb9YOF0:bi2h5ti) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L24)):*
> ```XML
> pub fn create_test_sqmr_client_channel<Query, Response>(
>     buffer_size: usize,
> ) -> (SqmrClientSender, TestReceiver<SqmrClientPayloadForTest<Query, Response>>)
> ```

Add TODO to wrap the 2nd type with a struct
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-IuXEHZ3oVBw_xu1:-O4p-IuXEHZ3oVBw_xu2:b-7c5aka) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L42)):*
> ```XML
> pub fn create_test_sqmr_server_channel<Query, Response>(
>     buffer_size: usize,
> ) -> (Sender<ServerQueryManager<Query, Response>>, SqmrServerReceiver<Query, Response>)
> ```

add TODO to wrap the 2nd type with a struct and change the create_test_server_query_manager function into a method of this struct
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-nOC3ezwNcbGpPfv:-O4p-nOC3ezwNcbGpPfw:b-gj7bly) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L55)):*
> ```XML
> pub fn create_test_server_query_manager<Query, Response>(
>     query: Query,
> ) -> (ServerQueryManager<Query, Response>, ReportReceiver, GenericReceiver<Response>)
> ```

Add TODO to wrap the 2nd and 3rd type with a struct
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p156926Dcp81MWztl:-O4p156926Dcp81MWztm:bg7li1r) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L71)):*
> ```XML
> }
> 
> const CHANNEL_BUFFER_SIZE: usize = 1000;
> ```

I think you can add another zero
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-Ab4E6I90Myu7DKv:-O4p-Ab57PgTJRmoVMZo:bc5hcz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L117)):*
> ```XML
> }
> 
> pub type TestReceiver<T> = Box<dyn Stream<Item = T> + Unpin + Send>;
> ```

What's the difference between this and GenericReceiver?
___
*[`crates/papyrus_node/src/main.rs` line 365 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p2Dal5tAIVkFOmgPH:-O4p2Dal5tAIVkFOmgPI:bw7by6n) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_node/src/main.rs#L365)):*
> ```XML
> 
>     let header_client_sender = network_manager
>         .register_sqmr_protocol_client::<HeaderQuery, DataOrFin<SignedBlockHeader>>(
> ```

Try to remove these type hint
___
*[`crates/papyrus_p2p_sync/src/client/header_test.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p3n-564QLH-y3pbY4:-O4p3n-564QLH-y3pbY5:b-p90kxm) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abc [...]

2024-08-21 14:02 UTC, eitanm-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447)* status: all files reviewed, 14 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/test.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4FpadiAIbfCUzK3BRe:-O4pEUYa6gK93JtiRoyh:b4od54n) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test.rs#L239)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Do you get a compiler error if you remove this? What's the error?
</blockquote></details>

type must be known at this point
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4Fsr6vCRjlDWK6bVKf:-O4p6Q0c3ceQ5vG4HSfi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test_utils.rs#L22)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to mock_register_sqmr_protocol_client
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4FtqVECV-ubO_mqXzn:-O4p8XdR-KGIUJZXvFm2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test_utils.rs#L40)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to mock_register_sqmr_protocol_server
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4Fq8DT1uf-vL9x8V09:-O4p9giL2Ho6NsQYZSUG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test_utils.rs#L119)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to MockClientResponsesManager or ServerResponsesManagerForTest
Payload should only appear on private structs
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4FqRC23geXe4XOQAaE:-O4p9lA61hvRwwpRnnFS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test_utils.rs#L120)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

remove pub from these two fields and add the following methods: `query(&self)`, `assert_reported(self, timeout)`
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4Fqvvm4CmMkQjSm7P7:-O4pCfNg8w-4ANZ-1Q3t:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test_utils.rs#L126)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to send_response (like in ServerQueryManager)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-FOe9IBJipb9YOF-:-O4pED6u4u4ZTplSKlA0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L24)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to wrap the 2nd type with a struct
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-IuXEHZ3oVBw_xu1:-O4pECBVCWKNUFr2miAm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L42)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

add TODO to wrap the 2nd type with a struct and change the create_test_server_query_manager function into a method of this struct
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-nOC3ezwNcbGpPfv:-O4pEBwt7dHom9bUqKuo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L55)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to wrap the 2nd and 3rd type with a struct
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p156926Dcp81MWztl:-O4p9ST48GUdUrFhC0Zg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L71)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think you can add another zero
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-Ab4E6I90Myu7DKv:-O4p64eM-D1n5mN1TIyy:b8k2thz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L117)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What's the difference between this and GenericReceiver?
</blockquote></details>

visibility


<!-- Sent from Reviewable.io -->

2024-08-22 06:36 UTC, eitanm-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447)* status: 8 of 14 files reviewed, 14 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_node/src/main.rs` line 365 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p2Dal5tAIVkFOmgPH:-O4sjPIAA5tJCUiwyyHf:bb7e59l) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_node/src/main.rs#L365)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try to remove these type hint
</blockquote></details>

cant
___
*[`crates/papyrus_p2p_sync/src/client/header_test.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p3n-564QLH-y3pbY4:-O4sl1s43PxRkCphrBHM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_p2p_sync/src/client/header_test.rs#L47)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename according to the name you chose for the struct (see comment above). Same throughout all the tests
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p4JZU3SJNwd0YmN5P:-O4smpxU1LSX9PfxySRz:bl3u6nn) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L62)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why is this a requirement
</blockquote></details>

i dont see the green but the first line was there before and moved it from above. the second line is because the sender uses bytes and is no longer defined in the sqmrclientsender


<!-- Sent from Reviewable.io -->

2024-08-22 06:44 UTC, ShahakShama requested changes
> Reviewed 4 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447)* status: all files reviewed, 9 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 141 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4sosrb-U-MELtnBgu6:-O4sosrb-U-MELtnBgu7:b-bf52u2) ([raw file](https://github.com/starkware-libs/sequencer/blob/808c92aa3d12981e7d5f2034a14400fbf41209b6/crates/papyrus_network/src/network_manager/mod.rs#L141)):*
> ```XML
>     }
> 
>     // Register a new subscriber for sending a single query and receiving multiple responses.
> ```

The first two lines should be ///
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4FpadiAIbfCUzK3BRe:-O4snck6BLtuqrXF2rzO:b48yybq) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test.rs#L239)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

type must be known at this point
</blockquote></details>

could you send the full error?
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-nOC3ezwNcbGpPfv:-O4snofC6gVe2tBgDWQk:bg78lpj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L55)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Where's the TODO
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-Ab4E6I90Myu7DKv:-O4snsElA0TnF6YgzYGV:bm4ifhz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L117)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

visibility
</blockquote></details>

then make GenericReceiver public
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4soP0K0vpb1kYqSc8N:-O4soP0K0vpb1kYqSc8O:bwxtvi) ([raw file](https://github.com/starkware-libs/sequencer/blob/808c92aa3d12981e7d5f2034a14400fbf41209b6/crates/papyrus_network/src/network_manager/test_utils.rs#L79)):*
> ```XML
> const CHANNEL_BUFFER_SIZE: usize = 10000;
> 
> pub fn mock_register_broadcast_subscriber<T>()
> ```

Could you fix this to mock_register_broadcast_topic the same way the original function is called (it was renamed and whoever renamed it didn't fix this one)
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 137 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4so2cp0Z96dlzus_l6:-O4so2cp0Z96dlzus_l7:bfwedht) ([raw file](https://github.com/starkware-libs/sequencer/blob/808c92aa3d12981e7d5f2034a14400fbf41209b6/crates/papyrus_network/src/network_manager/test_utils.rs#L137)):*
> ```XML
> 
>     pub async fn assert_reported(self, timeout: Duration) -> Result<(), oneshot::Canceled> {
>         tokio::time::timeout(timeout, self.report_receiver).await.unwrap()
> ```

assert means to panic if there was an error. Remove the return type and unwrap the second result
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 137 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4soB6V9elVeUxlAxCA:-O4soB6V9elVeUxlAxCB:b-7uqrbf) ([raw file](https://github.com/starkware-libs/sequencer/blob/808c92aa3d12981e7d5f2034a14400fbf41209b6/crates/papyrus_network/src/network_manager/test_utils.rs#L137)):*
> ```XML
> 
>     pub async fn assert_reported(self, timeout: Duration) -> Result<(), oneshot::Canceled> {
>         tokio::time::timeout(timeout, self.report_receiver).await.unwrap()
> ```

Is it possible to use now_or_never instead of timeout?
___
*[`crates/papyrus_node/src/main.rs` line 365 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p2Dal5tAIVkFOmgPH:-O4soxwx6DPuMFDEwKgd:b-nbmcuh) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_node/src/main.rs#L365)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

cant
</blockquote></details>

what error are you getting?
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p4JZU3SJNwd0YmN5P:-O4soi5T0gsDKwDcoFyW:b-gzs6k6) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L62)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

i dont see the green but the first line was there before and moved it from above. the second line is because the sender uses bytes and is no longer defined in the sqmrclientsender
</blockquote></details>

What doesn't compile if you remove the 2nd line?


<!-- Sent from Reviewable.io -->

2024-08-22 08:05 UTC, eitanm-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447)* status: all files reviewed, 9 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 141 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4sosrb-U-MELtnBgu6:-O4t3gEi1pLTPAeEVbx-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/808c92aa3d12981e7d5f2034a14400fbf41209b6/crates/papyrus_network/src/network_manager/mod.rs#L141)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The first two lines should be ///
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4FpadiAIbfCUzK3BRe:-O4t3quE8j-KJmPQn4lH:b-flv7t1) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdbc1f4c3d11c7ab4a795eb07b6c64b659680202/crates/papyrus_network/src/network_manager/test.rs#L239)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

could you send the full error?
</blockquote></details>

type annotations needed  
cannot satisfy \`<\_ as std::convert::TryFrom<std::vec::Vec<u8>>>::Error == \_\`
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-nOC3ezwNcbGpPfv:-O4t431xDZDT5woIU50s:bgp992i) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L55)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Where's the TODO
</blockquote></details>

didnt save - added
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p-Ab4E6I90Myu7DKv:-O4t5OWT1h9UE9KLtUC1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_network/src/network_manager/test_utils.rs#L117)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

then make GenericReceiver public
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4soP0K0vpb1kYqSc8N:-O4t5MS76tkxe6dO_gXq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/808c92aa3d12981e7d5f2034a14400fbf41209b6/crates/papyrus_network/src/network_manager/test_utils.rs#L79)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Could you fix this to mock_register_broadcast_topic the same way the original function is called (it was renamed and whoever renamed it didn't fix this one)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 137 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4soB6V9elVeUxlAxCA:-O4t5yGlCyvwO3RSdhNP:bvox63b) ([raw file](https://github.com/starkware-libs/sequencer/blob/808c92aa3d12981e7d5f2034a14400fbf41209b6/crates/papyrus_network/src/network_manager/test_utils.rs#L137)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Is it possible to use now_or_never instead of timeout?
</blockquote></details>

yeah but then why receiver a timeout time?
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 137 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4so2cp0Z96dlzus_l6:-O4t66Sy3oBkGzkoMQmJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/808c92aa3d12981e7d5f2034a14400fbf41209b6/crates/papyrus_network/src/network_manager/test_utils.rs#L137)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

assert means to panic if there was an error. Remove the return type and unwrap the second result
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/main.rs` line 365 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p2Dal5tAIVkFOmgPH:-O4t6AQDEzo8fhITOD_L:b-flv7t1) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_node/src/main.rs#L365)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

what error are you getting?
</blockquote></details>

type annotations needed  
cannot satisfy \`<\_ as std::convert::TryFrom<std::vec::Vec<u8>>>::Error == \_\`
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4p4JZU3SJNwd0YmN5P:-O4t6_dpAkUg7kKbbuSR:b-ueuvd) ([raw file](https://github.com/starkware-libs/sequencer/blob/e035c2a09b74bf1dd1abca78b9ae409eb756c00f/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L62)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What doesn't compile if you remove the 2nd line?
</blockquote></details>

the trait bound \`std::vec::Vec<u8>: std::convert::From<TQuery>\` is not satisfied  
the trait \`std::convert::From<TQuery>\` is not implemented for \`std::vec::Vec<u8>\`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B3%5D?3#file%3A%2F%2F%2Fhome%2Feitan%2Fworkspace%2Fsequencer-3%2Fcrates%2Fpapyrus_p2p_sync%2Fsrc%2Fclient%2Fstream_builder.rs)

mod.rs(639, 16): required by a bound in \`papyrus\_network::network\_manager::SqmrClientSender::send\_new\_query


<!-- Sent from Reviewable.io -->

2024-08-22 08:19 UTC, ShahakShama requested changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447)* status: all files reviewed, 3 unresolved discussions (waiting on @eitanm-starkware)



<!-- Sent from Reviewable.io -->

2024-08-22 09:03 UTC, ShahakShama requested changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 636 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4tJ8Ri7n_hzmvGenA8:-O4tJ8Ri7n_hzmvGenA9:bh3c9i2) ([raw file](https://github.com/starkware-libs/sequencer/blob/dafe77cdd53e5542a0dd4efe9b7261f817af927e/crates/papyrus_network/src/network_manager/mod.rs#L636)):*
> ```XML
>     sender: GenericSender<SqmrClientPayload>,
>     buffer_size: usize,
>     _query: std::marker::PhantomData<Query>,
> ```

Rename to _query_type and _response_type
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 646 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4tJZhf9JDypfjdn2zX:-O4tJZhf9JDypfjdn2zY:b-2ce99m) ([raw file](https://github.com/starkware-libs/sequencer/blob/dafe77cdd53e5542a0dd4efe9b7261f817af927e/crates/papyrus_network/src/network_manager/mod.rs#L646)):*
> ```XML
>     <Response as TryFrom<Bytes>>::Error: 'static + Send,
> {
>     pub fn new(sender: GenericSender<SqmrClientPayload>, buffer_size: usize) -> Self {
> ```

This should be private


<!-- Sent from Reviewable.io -->

2024-08-22 09:16 UTC, eitanm-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 636 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4tJ8Ri7n_hzmvGenA8:-O4tMwkK13m7PdO8O8sT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dafe77cdd53e5542a0dd4efe9b7261f817af927e/crates/papyrus_network/src/network_manager/mod.rs#L636)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to _query_type and _response_type
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 646 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/447#-O4tJZhf9JDypfjdn2zX:-O4tMwBe0mEnhsAoLbvu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dafe77cdd53e5542a0dd4efe9b7261f817af927e/crates/papyrus_network/src/network_manager/mod.rs#L646)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should be private
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-22 09:17 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447#-:-O4tN08e0ty9css8roUL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)



<!-- Sent from Reviewable.io -->

2024-08-22 09:21 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447#-:-O4tO1qP-finXRGIBAPi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)



<!-- Sent from Reviewable.io -->

2024-08-22 09:29 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/447#-:-O4tPopn61AVoNzZyafz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)



<!-- Sent from Reviewable.io -->

2024-08-22 09:51 UTC, merged