Mohammad/transaction queue/implement update gas threshold
starkware-libs/sequencer pull request #483
Opened 2024-08-18 06:15 UTC by MohammadNassar1

2024-08-21 03:46 UTC, elintul requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n0j_m6puMtwksDRRW:-O4n0j_m6puMtwksDRRX:b-fsctu) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/mempool.rs#L104)):*
> ```XML
> 
>     // TODO(Mohammad): Rename this method once consensus API is added.
>     pub fn update_gas_price_threshold(&mut self, new_threshold: u128) {
> ```

Clear from the context it's new. :)
x2



_Suggestion:_
```XML
threshold
```
___
*[`crates/mempool/src/transaction_queue.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n0sfQ9Ov4zhsRww4E:-O4n0sfQ9Ov4zhsRww4F:b32wzj) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L86)):*
> ```XML
>     pub fn update_gas_price_threshold(&mut self, new_threshold: u128) {
>         if new_threshold < self.gas_price_threshold {
>             for tx in self.pending_queue.iter() {
> ```

x2



_Suggestion:_
```XML
tx_reference
```
___
*[`crates/mempool/src/transaction_queue.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n0yMq4groWwJtZY6F:-O4n0yMq4groWwJtZY6G:bjglffw) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L86)):*
> ```XML
>     pub fn update_gas_price_threshold(&mut self, new_threshold: u128) {
>         if new_threshold < self.gas_price_threshold {
>             for tx in self.pending_queue.iter() {
> ```

Is `iter` what we aimed for? Isn't there a `take until condition` API?
What's the complexity here?



_Code quote:_
```XML
.iter()
```
___
*[`crates/mempool/src/transaction_queue.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n1Mqr9anKkgXh0WbL:-O4n1Mqr9anKkgXh0WbM:b-wrpqoy) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L88)):*
> ```XML
>             for tx in self.pending_queue.iter() {
>                 if tx.get_l2_gas_price() >= new_threshold {
>                     self.priority_queue.insert(tx.0.clone().into());
> ```

Any way to make this more elegant? Can we remove by value?



_Code quote:_
```XML
tx.0.clone()
```
___
*[`crates/mempool/src/transaction_queue.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n1Rm532o5eL5pkYAb:-O4n1Rm532o5eL5pkYAc:b-wxjpz6) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L91)):*
> ```XML
>                 } else {
>                     break;
>                 }
> ```

Any ergomonic method that's more suitable here? What about `take_while`?



_Code quote:_
```XML
                } else {
                    break;
                }
```


<!-- Sent from Reviewable.io -->

2024-08-21 05:55 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n0sfQ9Ov4zhsRww4E:-O4nS8TN2G7imMu4Zj0J:b9kaib1) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L86)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

x2
</blockquote></details>

I prefer to use `pending_tx` or `priority_tx` instead of `tx_reference`.
___
*[`crates/mempool/src/transaction_queue.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n1Mqr9anKkgXh0WbL:-O4nV26iDVKd2fsQCWyG:baw7o1a) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L88)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Any way to make this more elegant? Can we remove by value?
</blockquote></details>

Cannot remove elements while iterating over them in a for loop.


<!-- Sent from Reviewable.io -->

2024-08-21 06:46 UTC, elintul reviewed
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-08-22 06:38 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n0yMq4groWwJtZY6F:-O4o1uFLCQ4olbw4X95l:b4hd5kn) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L86)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is `iter` what we aimed for? Isn't there a `take until condition` API?
What's the complexity here?
</blockquote></details>

Exactly, as discussed offline, it should be a binary search for the new price, followed by removing the prefix in the tree (`split_off` does both a binary search and bulk removal at once I think). 
___
*[`crates/mempool/src/transaction_queue.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n1Mqr9anKkgXh0WbL:-O4o2OcJ9ZRj55A3XCAI:b7ejc5c) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L88)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Cannot remove elements while iterating over them in a for loop.
</blockquote></details>

Solved by the above comment when removing in bulk.
___
*[`crates/mempool/src/transaction_queue.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4smxPwAzbr35dXnryq:-O4smxPwAzbr35dXnryr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/14236c21b0de23cd81a3483af543ef0cca9a0cad/crates/mempool/src/transaction_queue.rs#L99)):*
> ```XML
>             let mut to_remove = Vec::new();
> 
>             for priority_tx in self.priority_queue.iter() {
> ```





_Suggestion:_
```XML
            for priority_tx in self.priority_queue {
```


<!-- Sent from Reviewable.io -->

2024-08-22 09:58 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n0yMq4groWwJtZY6F:-O4tUcsp2sgMK2H6KWIz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L86)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Exactly, as discussed offline, it should be a binary search for the new price, followed by removing the prefix in the tree (`split_off` does both a binary search and bulk removal at once I think).
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_queue.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n1Mqr9anKkgXh0WbL:-O4tWHt-3NBN98sIMNbV:b-ax4kjd) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L88)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Solved by the above comment when removing in bulk.
</blockquote></details>

@giladchase, how does it solve it?
We still need to insert it into the pending queue.
___
*[`crates/mempool/src/transaction_queue.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n1Rm532o5eL5pkYAb:-O4tVibt-Cw9HiYBLhaX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L91)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Any ergomonic method that's more suitable here? What about `take_while`?
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_queue.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4smxPwAzbr35dXnryq:-O4tVjM3EMbzjLXlQbjD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/14236c21b0de23cd81a3483af543ef0cca9a0cad/crates/mempool/src/transaction_queue.rs#L99)):*
> ```XML
>             let mut to_remove = Vec::new();
> 
>             for priority_tx in self.priority_queue.iter() {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-08-22 13:09 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4uBsUeAs3mLUXUvQhH:-O4uBsUeAs3mLUXUvQhI:bv67115) ([raw file](https://github.com/starkware-libs/sequencer/blob/b514e14bb6e65abe6e5a8d621038b8b74ba2b2f9/crates/mempool/src/transaction_queue.rs#L98)):*
> ```XML
>             // Insert all transactions from the split point into the priority queue
>             for pending_tx in &split_point {
>                 self.priority_queue.insert(pending_tx.clone().0.into());
> ```

Is there an `extend` API?



_Code quote:_
```XML
insert
```


<!-- Sent from Reviewable.io -->

2024-08-22 13:11 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4uBsUeAs3mLUXUvQhH:-O4uCXRa5j87pXNT28P4:b5w3t6w) ([raw file](https://github.com/starkware-libs/sequencer/blob/b514e14bb6e65abe6e5a8d621038b8b74ba2b2f9/crates/mempool/src/transaction_queue.rs#L98)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there an `extend` API?
</blockquote></details>

Same for inserting to the priority Q.
___
*[`crates/mempool/src/transaction_queue.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4uCOXF-XWcTNEVMsGF:-O4uCOXGCqeeWR7tP3ys:b7jrzpr) ([raw file](https://github.com/starkware-libs/sequencer/blob/b514e14bb6e65abe6e5a8d621038b8b74ba2b2f9/crates/mempool/src/transaction_queue.rs#L102)):*
> ```XML
>         } else {
>             let mut to_remove = Vec::new();
> ```

Any way to reduce the number of `clone`s?


<!-- Sent from Reviewable.io -->

2024-08-25 09:21 UTC, giladchase reviewed
plz rebase

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483#-:-O57ph-Y57L1uYgxHbpX:b-f1x79)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_queue.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4n1Mqr9anKkgXh0WbL:-O57o_N29zGBWYtdpiTf:b-67zhjz) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba5620f3bf6543ac91e7b958dfc6ad668be601f/crates/mempool/src/transaction_queue.rs#L88)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

@giladchase, how does it solve it?
We still need to insert it into the pending queue.
</blockquote></details>

that's insert, different thing.
Was talking specifically about the removal that can now be done via split_off


<!-- Sent from Reviewable.io -->

2024-08-25 09:56 UTC, MohammadNassar1 reviewed
done

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483#-:-O57wRLq07siXNl0CkkR:bb7f2mf)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)



<!-- Sent from Reviewable.io -->

2024-08-26 08:57 UTC, ayeletstarkware reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5Cssyi5kl_Gc9s6BJE:-O5Cssyi5kl_Gc9s6BJF:b-82l0zg) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/transaction_queue.rs#L85)):*
> ```XML
>             ];
> 
>             let at_pending_tx = PendingTransaction(TransactionReference {
> ```

consider rename this tx:
*Split Marker Transaction
*Threshold Setter Transaction



_Code quote:_
```XML
at_pending_tx
```
___
*[`crates/mempool/src/transaction_queue.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5CtQiE9P4AcoxLMBnJ:-O5CtQiE9P4AcoxLMBnK:bg0kwnh) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/transaction_queue.rs#L106)):*
> ```XML
> 
>             for tx in &to_remove {
>                 self.priority_queue.remove(tx);
> ```

Consider adding a comment to explain that this is a removal for priority queue logic, or possibly create a dedicated function for it.



_Code quote:_
```XML
            for priority_tx in &self.priority_queue {
                if priority_tx.get_l2_gas_price() < threshold {
                    to_remove.push(priority_tx.clone());
                }
            }

            for tx in &to_remove {
                self.priority_queue.remove(tx);
```


<!-- Sent from Reviewable.io -->

2024-08-26 10:30 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: all files reviewed, 12 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5CRis0D9Jc1JJc31--:-O5CRis0D9Jc1JJc31-0:bts5zen) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/mempool.rs#L106)):*
> ```XML
>     pub fn update_gas_price_threshold(&mut self, threshold: u128) {
>         self.tx_queue.update_gas_price_threshold(threshold);
>     }
> ```

Should this be `pub`? is it part of the mempool API?



_Code quote:_
```XML
    pub fn update_gas_price_threshold(&mut self, threshold: u128) {
        self.tx_queue.update_gas_price_threshold(threshold);
    }
```
___
*[`crates/mempool/src/transaction_queue.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O4uBsUeAs3mLUXUvQhH:-O5Cl3OS6PeeoU9oDVwd:b-kdvc7k) ([raw file](https://github.com/starkware-libs/sequencer/blob/b514e14bb6e65abe6e5a8d621038b8b74ba2b2f9/crates/mempool/src/transaction_queue.rs#L98)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Plz add a short comment just to clarify that the extend changes the order of inputs it is given (it's given txs ordered by fee but inserts them into pqueue after reordering them by Tip).
___
*[`crates/mempool/src/transaction_queue.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5Cfns99K6j6lozi1wO:-O5CfnsA5nE4WrnyQAgA:b-c40lpc) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/transaction_queue.rs#L88)):*
> ```XML
>                 resource_bounds: resource_bounds.try_into().unwrap(),
>                 ..Default::default()
>             });
> ```

Maybe.

I took me a few moments to understand why vec! and not regular array, then also why there was a temporary type, so perhaps condensing it into one command makes it immediately clear what the goal is?



_Suggestion:_
```XML
            let resource_bounds: DeprecatedResourceBoundsMapping = vec![
                (Resource::L1Gas, ResourceBounds::default()),
                (Resource::L2Gas, ResourceBounds { max_amount: 0, max_price_per_unit: threshold }),
            ]
            .try_into()
            .unwrap();

            let at_pending_tx =
                PendingTransaction(TransactionReference { resource_bounds, ..Default::default() });
```
___
*[`crates/mempool/src/transaction_queue.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5CkkiVCYeiuz8uviAD:-O5CkkiVCYeiuz8uviAE:bx4f3hs) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/transaction_queue.rs#L91)):*
> ```XML
> 
>             // Split off the pending queue at the given transaction higher than the threshold.
>             let mut split_point = self.pending_queue.split_off(&at_pending_tx);
> ```

maybe the name should include `tmp`, so it's clear that its an aux var



_Code quote:_
```XML
            let mut split_point = self.pending_queue.split_off(&at_pending_tx);
```
___
*[`crates/mempool/src/transaction_queue.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5CktV8CB8elXy5zOH2:-O5CktV8CB8elXy5zOH3:b-btm9wd) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/transaction_queue.rs#L92)):*
> ```XML
>             // Split off the pending queue at the given transaction higher than the threshold.
>             let mut split_point = self.pending_queue.split_off(&at_pending_tx);
>             split_point.remove(&at_pending_tx);
> ```

I think it'd be easier to skip the last element in the iterator in the next line, would also save the log operation



_Code quote:_
```XML
            split_point.remove(&at_pending_tx);
```
___
*[`crates/mempool/src/transaction_queue.rs` line 99 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5ClZLi9rU-VbonYU9M:-O5ClZLi9rU-VbonYU9N:bnc5jxr) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/transaction_queue.rs#L99)):*
> ```XML
>             let mut to_remove = Vec::new();
> 
>             for priority_tx in &self.priority_queue {
> ```

What if the price is unchanged? will it still iterate over the entire queue and do NOPs?



_Code quote:_
```XML
        } else {
            let mut to_remove = Vec::new();

            for priority_tx in &self.priority_queue {
```


<!-- Sent from Reviewable.io -->

2024-08-27 11:44 UTC, ayeletstarkware reviewed
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`-- commits` line 5 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5Id-809pio1MWwVN8P):*
bad rebase?


<!-- Sent from Reviewable.io -->

2024-08-27 11:57 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 1 of 2 files reviewed, 11 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5CRis0D9Jc1JJc31--:-O5IbVwX00tajOTDHD_K:byteyqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/mempool.rs#L106)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Good question, I added a TODO above.
This API should be maybe part of the `init` API. and `init` API should be public.
</blockquote></details>

Can't this be checked now?
___
*[`crates/mempool/src/transaction_queue.rs` line 99 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5ClZLi9rU-VbonYU9M:-O5IeRu91cxUh5CNdumw:b-vz0h5s) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/transaction_queue.rs#L99)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Good point, updated!
</blockquote></details>

Great!
Plz reorder functions inside file, private function should appear after public ones.
___
*[`crates/mempool/src/transaction_queue.rs` line 96 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5Id44c6wnFGvVYrK_O:-O5Id44c6wnFGvVYrK_P:b-n9259r) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1ef7791e6462d1b967d0b685c9e2cdd36e576cd/crates/mempool/src/transaction_queue.rs#L96)):*
> ```XML
>         // Note: extend will reorder transactions by `Tip` during insertion, despite them being
>         // initially ordered by fee.
>         self.priority_queue.extend(tmp_split_point.into_iter().skip(1).map(|tx| tx.0.into()));
> ```

This is a similar comment to one in one of the tests: temporary entities should take as little real-estate as possible, the more space they take the less tmp they appear. 

Here this tmp var is a pure technical constraint, so if we finish all the handling of it sooner that's better.



_Suggestion:_
```XML
        // Split off the pending queue at the given transaction higher than the threshold.
        let txs_over_threshold = self.pending_queue.split_off(&tmp_split_tx).into_iter().skip(1);

        // Insert all transactions from the split point into the priority queue, skip
        // `tmp_split_tx`.
        // Note: extend will reorder transactions by `Tip` during insertion, despite them being
        // initially ordered by fee.
        self.priority_queue.extend(txs_over_threshold.map(|tx| tx.0.into()));
```
___
*[`crates/mempool/src/transaction_queue.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5IfZcc4Sr7x3OtGsKA:-O5IfZcc4Sr7x3OtGsKB:b-pzwtsj) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1ef7791e6462d1b967d0b685c9e2cdd36e576cd/crates/mempool/src/transaction_queue.rs#L123)):*
> ```XML
> 
>         self.gas_price_threshold = threshold;
>     }
> ```

Name of this function is good, as it explains what this function does.

Names of the inner functions need to be reworked, they should also explain   what they do.
Current name mostly explains what triggered them to be called, or even potentially be misleading, as it hints that they are the ones updating the threshold, which isn't the case, since that happens in line 122.



_Code quote:_
```XML
    pub fn update_gas_price_threshold(&mut self, threshold: u128) {
        match threshold.cmp(&self.gas_price_threshold) {
            Ordering::Less => self.update_threshold_below(threshold),
            Ordering::Greater => self.update_threshold_above(threshold),
            Ordering::Equal => {}
        }

        self.gas_price_threshold = threshold;
    }
```


<!-- Sent from Reviewable.io -->

2024-08-28 06:49 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`-- commits` line 5 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5Id-809pio1MWwVN8P):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

bad rebase?
</blockquote></details>

rebased.
___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5CRis0D9Jc1JJc31--:-O5J6dbW0p_N6oz4fQ4I:b79y40d) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/mempool.rs#L106)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can't this be checked now?
</blockquote></details>

Appearantly we need to add `init` API. But I'm not entirely sure how to determine the required arguments for it. There are also several APIs that will need to be added once consensus support is implemented in the Mempool.

For now, I've made the method private and will rename and change it to public once we add the consensus APIs."
___
*[`crates/mempool/src/transaction_queue.rs` line 99 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5ClZLi9rU-VbonYU9M:-O5J7vkX8S8OY7KJxcFp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/transaction_queue.rs#L99)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Great!
Plz reorder functions inside file, private function should appear after public ones.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_queue.rs` line 96 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5Id44c6wnFGvVYrK_O:-O5J8h_Z-4wSoME9Xi3w:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1ef7791e6462d1b967d0b685c9e2cdd36e576cd/crates/mempool/src/transaction_queue.rs#L96)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This is a similar comment to one in one of the tests: temporary entities should take as little real-estate as possible, the more space they take the less tmp they appear. 

Here this tmp var is a pure technical constraint, so if we finish all the handling of it sooner that's better.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_queue.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5IfZcc4Sr7x3OtGsKA:-O5Mjqrf2BQwt73UzgR1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1ef7791e6462d1b967d0b685c9e2cdd36e576cd/crates/mempool/src/transaction_queue.rs#L123)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Name of this function is good, as it explains what this function does.

Names of the inner functions need to be reworked, they should also explain   what they do.
Current name mostly explains what triggered them to be called, or even potentially be misleading, as it hints that they are the ones updating the threshold, which isn't the case, since that happens in line 122.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-28 07:04 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5CRis0D9Jc1JJc31--:-O5MlyAzBXw6HjJlgHCS:b-atyadz) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/mempool.rs#L106)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Appearantly we need to add `init` API. But I'm not entirely sure how to determine the required arguments for it. There are also several APIs that will need to be added once consensus support is implemented in the Mempool.

For now, I've made the method private and will rename and change it to public once we add the consensus APIs."
</blockquote></details>

I think i'm not sure what Init API is :thinking: 
Who is going to call this (now private) function in the flow?
___
*[`crates/mempool/src/mempool.rs` line 105 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5MlkHOC6U7rhJP2FGU:-O5MlkHOC6U7rhJP2FGV:b8nc1wj) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb59b7917010c617729f19b150810864feeddd13/crates/mempool/src/mempool.rs#L105)):*
> ```XML
>     // TODO(Mohammad): Rename this method once consensus API is added.
>     #[allow(dead_code)]
>     fn update_gas_price_threshold(&mut self, threshold: u128) {
> ```

I think this is better than clippy attribute, less chance of forgetting to remove the `_` then there is to remove the clippy lint. 



_Suggestion:_
```XML
    fn _update_gas_price_threshold(&mut self, threshold: u128) {
```
___
*[`crates/mempool/src/transaction_queue.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5IfZcc4Sr7x3OtGsKA:-O5MmgDS3wW9hRR1_LTd:b-vxnthf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1ef7791e6462d1b967d0b685c9e2cdd36e576cd/crates/mempool/src/transaction_queue.rs#L123)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe instead of `transfer` for both it should be promote/demote? like `promote_txs_to_ready` and `demote_txs_to_pending`? is it clearer that way?


<!-- Sent from Reviewable.io -->

2024-08-28 11:04 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 105 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5MlkHOC6U7rhJP2FGU:-O5NdXHB6z8_S1uJCRLG:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb59b7917010c617729f19b150810864feeddd13/crates/mempool/src/mempool.rs#L105)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think this is better than clippy attribute, less chance of forgetting to remove the `_` then there is to remove the clippy lint.
</blockquote></details>

Done
___
*[`crates/mempool/src/transaction_queue.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5IfZcc4Sr7x3OtGsKA:-O5NPyq_84bBbMGE1cdQ:b-i5g34q) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1ef7791e6462d1b967d0b685c9e2cdd36e576cd/crates/mempool/src/transaction_queue.rs#L123)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Maybe instead of `transfer` for both it should be promote/demote? like `promote_txs_to_ready` and `demote_txs_to_pending`? is it clearer that way?
</blockquote></details>

Looks good to me.
Do you mean `promote_txs_to_priority` right?
As it's called priority_queue and not ready_queue.

updated.
___
*[`crates/mempool/src/transaction_queue.rs` line 104 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5NdjEF-dwq3LqjaC6s:-O5NdjEF-dwq3LqjaC6t:bxu2iwg) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb59b7917010c617729f19b150810864feeddd13/crates/mempool/src/transaction_queue.rs#L104)):*
> ```XML
> 
>         // Split off the pending queue at the given transaction higher than the threshold.
>         let txs_over_threshold = self.pending_queue.split_off(&tmp_split_tx).into_iter().skip(1);
> ```

I need to explain why it's not required anymore.



_Code quote:_
```XML
let txs_over_threshold = self.pending_queue.split_off(&tmp_split_tx).into_iter().skip(1);
```


<!-- Sent from Reviewable.io -->

2024-08-28 11:19 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5CRis0D9Jc1JJc31--:-O5Neng72xfT7Zc6GxBK:b1nj6zb) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/mempool.rs#L106)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think i'm not sure what Init API is :thinking: 
Who is going to call this (now private) function in the flow?
</blockquote></details>

Let me clarify my perspective:

This method updates the gas price threshold. The gas price update occurs when the mempool (node) becomes the leader. At the beginning of the consensus round, the mempool receives the new price as part of the `init` process, as discussed with Elin and DanB.

Currently, we don't have the consensus APIs (`init`, `staged`, `build_above_block`, etc.), so the `update_gas_price_threshold` method isn't being used. However, once the `init` API is added, it should either call this method or possibly replace it.


<!-- Sent from Reviewable.io -->

2024-08-28 13:12 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 104 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5NdjEF-dwq3LqjaC6s:-O5O5vNCAtuTmf5I2CG7:bim0jku) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb59b7917010c617729f19b150810864feeddd13/crates/mempool/src/transaction_queue.rs#L104)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I need to explain why it's not required anymore.
</blockquote></details>

Apparently, `split_off` does not add a new transaction, so there's no need to remove or skip anything. 

Sorry, the example [here](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html#method.split_off) was a bit confusing.


<!-- Sent from Reviewable.io -->

2024-08-29 04:17 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5CRis0D9Jc1JJc31--:-O5RKytcACNlqB_MZR84:bxmz05g) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/mempool.rs#L106)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Let me clarify my perspective:

This method updates the gas price threshold. The gas price update occurs when the mempool (node) becomes the leader. At the beginning of the consensus round, the mempool receives the new price as part of the `init` process, as discussed with Elin and DanB.

Currently, we don't have the consensus APIs (`init`, `staged`, `build_above_block`, etc.), so the `update_gas_price_threshold` method isn't being used. However, once the `init` API is added, it should either call this method or possibly replace it.
</blockquote></details>

So `Init` is the API name for "you have been selected as the proposer"?
If so, then what happens is that `init` will be the endpoint of this flow inside the mempool, and it'll call update_gas_price_threshold as a subroutine?


<!-- Sent from Reviewable.io -->

2024-08-29 06:28 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/483#-O5CRis0D9Jc1JJc31--:-O5RoaWdDx9daqn8BwJB:b-1vijnq) ([raw file](https://github.com/starkware-libs/sequencer/blob/66993dffaea9f7d176722a041e8b98c14464fcef/crates/mempool/src/mempool.rs#L106)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

So `Init` is the API name for "you have been selected as the proposer"?
If so, then what happens is that `init` will be the endpoint of this flow inside the mempool, and it'll call update_gas_price_threshold as a subroutine?
</blockquote></details>

Exactly!


<!-- Sent from Reviewable.io -->

2024-08-29 06:41 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483#-:-O5RrWxj9wge6B02muP1:bnfp4nl)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @elintul)



<!-- Sent from Reviewable.io -->

2024-08-29 10:24 UTC, MohammadNassar1 reviewed
> Dismissed @elintul from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-08-29 10:39 UTC, giladchase approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/483)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)



<!-- Sent from Reviewable.io -->

2024-08-29 10:47 UTC, merged