feat(consensus): handle timeouts in shc and manager
starkware-libs/sequencer pull request #502
Opened 2024-08-19 10:46 UTC by asmaastarkware

2024-08-19 14:06 UTC, matan-starkware requested changes
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/502)* status: all files reviewed, 15 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 158 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4egwjL1IOzdvNvWLbj:-O4egwjL1IOzdvNvWLbk:b5x5fr4) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/run_consensus.py#L158)):*
> ```Python
>         cmd += f"--consensus.test.drop_probability {papryus_args.drop_probability} "
>     if papryus_args.invalid_probability is not None:
>         cmd += f"--consensus.test.invalid_probability {papryus_args.invalid_probability} "
> ```

Can we move this refactor to its own PR? We discussed this without connection to Milestone 4.



_Code quote:_
```Python
    if papryus_args.proposal_timeout is not None:
        cmd += f"--consensus.timeouts.proposal_timeout {papryus_args.proposal_timeout} "
    if papryus_args.prevote_timeout is not None:
        cmd += f"--consensus.timeouts.prevote_timeout {papryus_args.prevote_timeout} "
    if papryus_args.precommit_timeout is not None:
        cmd += f"--consensus.timeouts.precommit_timeout {papryus_args.precommit_timeout} "
    if papryus_args.cache_size is not None:
        cmd += f"--consensus.test.cache_size {papryus_args.cache_size} "
    if papryus_args.random_seed is not None:
        cmd += f"--consensus.test.random_seed {papryus_args.random_seed} "
    if papryus_args.drop_probability is not None:
        cmd += f"--consensus.test.drop_probability {papryus_args.drop_probability} "
    if papryus_args.invalid_probability is not None:
        cmd += f"--consensus.test.invalid_probability {papryus_args.invalid_probability} "
```
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eiZtd-SGOB_6ucJAM:-O4eiZtd-SGOB_6ucJAN:b-kacoqo) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/config.rs#L162)):*
> ```XML
> 
> /// Configuration for consensus timeouts.
> #[derive(Debug, Deserialize, Serialize, Clone, PartialEq, Copy)]
> ```

Are you sure we want this to be Copy? Is there a standard for when to make things Copy?



_Code quote:_
```XML
Copy
```
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4ehYSS1Gw10e7kga_y:-O4ehYSS1Gw10e7kga_z:b-h6iun) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/config.rs#L165)):*
> ```XML
> pub struct TimeoutsConfig {
>     /// The timeout for a proposal.
>     #[serde(deserialize_with = "deserialize_seconds_to_duration")]
> ```

We may want small timeouts when running local simulations.



_Suggestion:_
```XML
deserialize_milliseconds_to_duration
```
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4ehtgMAstE7v9eCx8I:-O4ehtgN9zXFgOz_NNXx:bl2bp4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/config.rs#L203)):*
> ```XML
>     fn default() -> Self {
>         Self {
>             proposal_timeout: Duration::from_secs(8),
> ```

Our only use case currently is local simulations, so let's go for a smaller default.



_Suggestion:_
```XML
            proposal_timeout: Duration::from_secs(3),
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eiJTJ-04AHxEUfM_o:-O4eiJTJ-04AHxEUfM_p:bjr453) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager.rs#L115)):*
> ```XML
>         height: BlockNumber,
>         validator_id: ValidatorId,
>         timeouts: TimeoutsConfig,
> ```

Let's move these to become fields of `Manager` instead of function inputs.



_Code quote:_
```XML
        validator_id: ValidatorId,
        timeouts: TimeoutsConfig,
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4elyEt-htgr8WexxgZ:-O4elyEt-htgr8Wexxg_:b8kqh5o) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager.rs#L175)):*
> ```XML
>         shc: &mut SingleHeightConsensus<BlockT>,
>         message: ConsensusMessage,
>     ) -> Result<Option<ShcReturn<BlockT>>, ConsensusError>
> ```

We can replace the None by just returning `Tasks(vec![])` which does nothing.



_Suggestion:_
```XML
Result<ShcReturn<BlockT>, ConsensusError>
```
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4enyFJEztlQ79H7xdo:-O4enyFJEztlQ79H7xdp:bz8c782) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager_test.rs#L271)):*
> ```XML
> #[tokio::test]
> async fn test_timeouts() {
>     let mut context = MockTestContext::new();
> ```

Let's construct this below, when we begin to use it.



_Code quote:_
```XML
    let mut context = MockTestContext::new();
```
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 280 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eo66iEMC9GJCd8gkc:-O4eo66iEMC9GJCd8gkd:bz8c782) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager_test.rs#L280)):*
> ```XML
>     send(&mut sender, precommit(None, 1, 0, *VALIDATOR_ID_3)).await;
> 
>     let mut manager = MultiHeightManager::new();
> ```

Let's construct this below, when we begin to use it.



_Code quote:_
```XML
    let mut manager = MultiHeightManager::new();
```
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eontR-3kvFPzPOfrt:-O4eontR-3kvFPzPOfru:b-m1yon5) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager_test.rs#L315)):*
> ```XML
> 
>     // Delay to ensure the timeouts are triggered.
>     tokio::time::sleep(Duration::from_millis(10)).await;
> ```

I don't like using sleeps this way in tests. What I suggest is:
1. Create a oneshot channel
2. In the `expect_broadcast` where you wait for the timeout Prevote(NIL), take the send side of the channel and send (will probably requite `times(1).return_once`
3. Now instead of this sleep you can await the receiver.

I did something similar in `run_consensus` with `(decision_tx, decision_rx)`.



_Code quote:_
```XML
    // Delay to ensure the timeouts are triggered.
    tokio::time::sleep(Duration::from_millis(10)).await;
```
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4esz3iBzsA4tWsF31F:-O4esz3iBzsA4tWsF31G:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager_test.rs#L321)):*
> ```XML
>     send(&mut sender, prevote(Some(BlockHash(Felt::ONE)), 1, 1, *VALIDATOR_ID_3)).await;
>     send(&mut sender, precommit(Some(BlockHash(Felt::ONE)), 1, 1, *VALIDATOR_ID_2)).await;
>     send(&mut sender, precommit(Some(BlockHash(Felt::ONE)), 1, 1, *VALIDATOR_ID_3)).await;
> ```





_Suggestion:_
```XML
    // Show that after the timeout is trig [...]

2024-08-19 14:11 UTC, matan-starkware commented
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4ey28a4UYYu9YUhcyT:-O4ey28a4UYYu9YUhcyU:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5a6fa43f21df32ef3a9c0e063574c74d27491c4/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L52)):*
> ```XML
>         assert_eq!(init.height, BlockNumber(0));
>         assert_eq!(init.proposer, *VALIDATOR_ID_1);
>         fin_receiver_clone.set(fin_receiver).unwrap();
> ```





_Suggestion:_
```XML
        assert_eq!(init.proposer, *VALIDATOR_ID_1);
        // This is done so that we can return immediately without dropping the receiver.
        fin_receiver_clone.set(fin_receiver).unwrap();
```


<!-- Sent from Reviewable.io -->

2024-08-20 06:13 UTC, asmaastarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/502)* status: 0 of 9 files reviewed, 15 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 158 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4egwjL1IOzdvNvWLbj:-O4f0mjl2C-pZlbUd-8O:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/run_consensus.py#L158)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can we move this refactor to its own PR? We discussed this without connection to Milestone 4.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eiZtd-SGOB_6ucJAM:-O4iOOq82F5DdWZEVCfY:bhxv9gd) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/config.rs#L162)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Are you sure we want this to be Copy? Is there a standard for when to make things Copy?
</blockquote></details>

I added Copy because it's a small simple struct, but I noticed most config structs don't use it.
I'm not sure if there's a standard for this. good point to bring up!
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4ehYSS1Gw10e7kga_y:-O4f0lFN6p4l9cgszGFr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/config.rs#L165)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We may want small timeouts when running local simulations.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4ehtgMAstE7v9eCx8I:-O4f0kpR2-LOrfY3TgHt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/config.rs#L203)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Our only use case currently is local simulations, so let's go for a smaller default.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eiJTJ-04AHxEUfM_o:-O4f22P2Et_pExTwSULS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager.rs#L115)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's move these to become fields of `Manager` instead of function inputs.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4elyEt-htgr8WexxgZ:-O4iC7jl3BwO5KsQxZKU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager.rs#L175)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We can replace the None by just returning `Tasks(vec![])` which does nothing.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4enyFJEztlQ79H7xdo:-O4iFIDhAcK5vGQERb4M:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager_test.rs#L271)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's construct this below, when we begin to use it.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 280 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eo66iEMC9GJCd8gkc:-O4iFHyJ3anmOztZ8X4K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager_test.rs#L280)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's construct this below, when we begin to use it.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eontR-3kvFPzPOfrt:-O4iKajc5IieRFKv-4N5:bmoog5n) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager_test.rs#L315)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't like using sleeps this way in tests. What I suggest is:
1. Create a oneshot channel
2. In the `expect_broadcast` where you wait for the timeout Prevote(NIL), take the send side of the channel and send (will probably requite `times(1).return_once`
3. Now instead of this sleep you can await the receiver.

I did something similar in `run_consensus` with `(decision_tx, decision_rx)`.
</blockquote></details>

Done. I like the trick!!
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4esz3iBzsA4tWsF31F:-O4f3x8OASXd2wC8FPPU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager_test.rs#L321)):*
> ```XML
>     send(&mut sender, prevote(Some(BlockHash(Felt::ONE)), 1, 1, *VALIDATOR_ID_3)).await;
>     send(&mut sender, precommit(Some(BlockHash(Felt::ONE)), 1, 1, *VALIDATOR_ID_2)).await;
>     send(&mut sender, precommit(Some(BlockHash(Felt::ONE)), 1, 1, *VALIDATOR_ID_3)).await;
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4etNQS1HwAKjHRQ2p5:-O4iMaz8CUJT1bRGac25:b-80bil4) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L38)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think I'd prefer not having the `ShcResult` alias. I view it as an extra step to understanding the return type. If you feel strongly that you'd like to keep it I'm open.
</blockquote></details>

agree, it's not a complex type that needs a separate alias, Done
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4etswt5J3x9ADEFKVi:-O4f48p2EmlJITmQRxkg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L195)):*
> ```XML
>                 self.handle_state_machine_events(context, sm_events).await
>             }
>             _ => panic!("Unexpected task: {:?}", task),
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4ewt8NCmdH9NyXq8Ld:-O4i9cPMA0zEI9NdfpLA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L116)):*
> ```XML
>         }
>         _ => panic!("Expected decision"),
>     }
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 20 [...]

2024-08-20 11:58 UTC, matan-starkware requested changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/502)* status: all files reviewed, 6 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eiZtd-SGOB_6ucJAM:-O4jYhHe7nqCjqJG7_Pi:bpl0qbf) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/config.rs#L162)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

I added Copy because it's a small simple struct, but I noticed most config structs don't use it.
I'm not sure if there's a standard for this. good point to bring up!
</blockquote></details>

I think this struct is actually fine to make copy I was just thinking out loud. The standard I can think of/found parts of:
1. No pointers - this implies no heap allocations.
2. Immutable - it would be surprising if someone called a `&mut self` function only to change a local copy.
3. Small - I lean towards 64B since that is a typical L1 cache line.

LMK what you think. Maybe we can tighten this up and talk to Gilad about putting something in the style guide.
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4ehtgMAstE7v9eCx8I:-O4j_tanAqGQceyYXaqq:b-jxz2xv) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/config.rs#L203)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If this is millis it should be 3000, 1000, 1000.

On second thought, it would be much nicer if we could just deserialize `f64` seconds. Then someone could write `0.5` if they want 500ms.  It would obfuscate the need for the separate deserializer, and there already exists https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.from_secs_f64

Ask Dan & Dvir what they think.
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 166 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4jdh9I5bq_9rfFjxDA:-O4jdh9I5bq_9rfFjxDB:b92azhg) ([raw file](https://github.com/starkware-libs/sequencer/blob/e13765ed958423517a075f7302e760ef70912e35/crates/sequencing/papyrus_consensus/src/config.rs#L166)):*
> ```XML
> /// Configuration for consensus timeouts.
> #[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
> pub struct TimeoutsConfig {
> ```

How about if we add this struct in another PR?



_Code quote:_
```XML
pub struct TimeoutsConfig {
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eiJTJ-04AHxEUfM_o:-O4jb73e3YA0lFaj4Gzs:b-ugrzu) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager.rs#L115)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I also meant `validator_id`
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 368 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4jdGM41dmzufqeyP1w:-O4jdGM41dmzufqeyP1x:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e13765ed958423517a075f7302e760ef70912e35/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L368)):*
> ```XML
>                     return None;
>                 }
>                 Some(vote.clone())
> ```





_Suggestion:_
```XML
                if vote.block_hash == Some(block_hash) { Some(vote.clone()) } else { None }
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4jcphv6S3H2mElBwpp:-O4jcphv6S3H2mElBwpq:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e13765ed958423517a075f7302e760ef70912e35/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L109)):*
> ```XML
>     );
>     let ShcReturn::Decision(decision) =
>         shc.handle_message(&mut context, precommits[3].clone()).await.unwrap()
> ```





_Suggestion:_
```XML
    let precommits = vec![
        precommit(Some(*BLOCK_ID), 0, 0, *PROPOSER_ID),
        precommit(Some(BlockHash(Felt::TWO)), 0, 0, *VALIDATOR_ID_3),
        precommit(Some(*BLOCK_ID), 0, 0, *VALIDATOR_ID_2),
        precommit(Some(*BLOCK_ID), 0, 0, *VALIDATOR_ID_1),
    ];
    assert_eq!(
        shc.handle_message(&mut context, precommits[0].clone()).await,
        Ok(ShcReturn::Tasks(vec![]))
    );
    // The disagreeing vote counts towards the timeout, which uses a heterogeneous quorum, but not the decision, which uses a homogenous quorum.
    assert_eq!(
        shc.handle_message(&mut context, precommits[1].clone()).await,
        Ok(ShcReturn::Tasks(vec![ShcTask {
            duration: TIMEOUTS.precommit_timeout,
            event: StateMachineEvent::TimeoutPrecommit(0)
        }]))
    );
    let ShcReturn::Decision(decision) =
        shc.handle_message(&mut context, precommits[2].clone()).await.unwrap()
```


<!-- Sent from Reviewable.io -->

2024-08-21 07:51 UTC, asmaastarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/502)* status: all files reviewed, 6 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eiZtd-SGOB_6ucJAM:-O4nnKfVE9w05lX_aK8v:bq69owq) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/config.rs#L162)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think this struct is actually fine to make copy I was just thinking out loud. The standard I can think of/found parts of:
1. No pointers - this implies no heap allocations.
2. Immutable - it would be surprising if someone called a `&mut self` function only to change a local copy.
3. Small - I lean towards 64B since that is a typical L1 cache line.

LMK what you think. Maybe we can tighten this up and talk to Gilad about putting something in the style guide.
</blockquote></details>

AGREE!
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4ehtgMAstE7v9eCx8I:-O4niTZz2pGpftXB3xDq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/config.rs#L203)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

If this is millis it should be 3000, 1000, 1000.

On second thought, it would be much nicer if we could just deserialize `f64` seconds. Then someone could write `0.5` if they want 500ms.  It would obfuscate the need for the separate deserializer, and there already exists https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.from_secs_f64

Ask Dan & Dvir what they think.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 166 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4jdh9I5bq_9rfFjxDA:-O4nhwtkDLKpZ42gcc7q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e13765ed958423517a075f7302e760ef70912e35/crates/sequencing/papyrus_consensus/src/config.rs#L166)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

How about if we add this struct in another PR?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4eiJTJ-04AHxEUfM_o:-O4nivmO-VsuF37vpkFk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580c24c93005f197f1b74522e50f4e3234c15811/crates/sequencing/papyrus_consensus/src/manager.rs#L115)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I also meant `validator_id`
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 368 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4jdGM41dmzufqeyP1w:-O4k2XTw-7YsNFxnnMgY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e13765ed958423517a075f7302e760ef70912e35/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L368)):*
> ```XML
>                     return None;
>                 }
>                 Some(vote.clone())
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/502#-O4jcphv6S3H2mElBwpp:-O4k30Sr9Y1Y471VF_iB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e13765ed958423517a075f7302e760ef70912e35/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L109)):*
> ```XML
>     );
>     let ShcReturn::Decision(decision) =
>         shc.handle_message(&mut context, precommits[3].clone()).await.unwrap()
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-08-21 13:55 UTC, matan-starkware approved these changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/502)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)



<!-- Sent from Reviewable.io -->

2024-08-21 15:02 UTC, merged