build(fee): current tx_info holds validResourceBounds
starkware-libs/sequencer pull request #505
Opened 2024-08-19 10:47 UTC by nimrod-starkware

2024-08-19 10:47 UTC, nimrod-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/505?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#506** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/506?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#505** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/505?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#504** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/504?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#503** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/503?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-19 11:29 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 480 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4eNCup6XeUvTpAjl1z:-O4eNCuq3UijsiFJ8Dx7:b-1y4een) ([raw file](https://github.com/starkware-libs/sequencer/blob/643aa9eb918c0b7a1f93616c8c3025f4520f5eec/crates/blockifier/src/execution/syscalls/hint_processor.rs#L480)):*
> ```XML
>                     l2_gas_as_felt,
>                     Felt::ZERO,
>                     Felt::ZERO,
> ```

WDYT? 
l2_gas should always be zero.



_Code quote:_
```XML
                    l2_gas_as_felt,
                    Felt::ZERO,
                    Felt::ZERO,
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 299 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4eO2KS5U3wiwsC5-Vb:-O4eO2KS5U3wiwsC5-Vc:b-snr0b0) ([raw file](https://github.com/starkware-libs/sequencer/blob/643aa9eb918c0b7a1f93616c8c3025f4520f5eec/crates/blockifier/src/transaction/transactions.rs#L299)):*
> ```XML
>                 TransactionInfo::Current(CurrentTransactionInfo {
>                     common_fields,
>                     resource_bounds: tx.resource_bounds.0.clone().try_into().expect("todo"),
> ```

treated in an upper branch on the stack



_Code quote:_
```XML
try_into().expect("todo")
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4eOFh-9DEhBC5FRQpL:-O4eOFh-9DEhBC5FRQpM:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/643aa9eb918c0b7a1f93616c8c3025f4520f5eec/crates/blockifier/src/transaction/transactions.rs#L404)):*
> ```XML
>                 TransactionInfo::Current(CurrentTransactionInfo {
>                     common_fields,
>                     resource_bounds: tx.resource_bounds.0.clone().try_into().expect("todo"),
> ```

ditto



_Code quote:_
```XML
0.clone().try_into().expect("todo"),
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 522 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4eOK6N3STxv4wFY8I9:-O4eOK6N3STxv4wFY8IA:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/643aa9eb918c0b7a1f93616c8c3025f4520f5eec/crates/blockifier/src/transaction/transactions.rs#L522)):*
> ```XML
>                 TransactionInfo::Current(CurrentTransactionInfo {
>                     common_fields,
>                     resource_bounds: tx.resource_bounds.0.clone().try_into().expect("todo"),
> ```

ditto



_Code quote:_
```XML
.0.clone().try_into().expect("todo"),
```


<!-- Sent from Reviewable.io -->

2024-08-20 09:52 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 480 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4eNCup6XeUvTpAjl1z:-O4jBECa2btju2FaENq-:bw4j02d) ([raw file](https://github.com/starkware-libs/sequencer/blob/643aa9eb918c0b7a1f93616c8c3025f4520f5eec/crates/blockifier/src/execution/syscalls/hint_processor.rs#L480)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

WDYT? 
l2_gas should always be zero.
</blockquote></details>

I like it.
@noaov1 ?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jBXO94wFHjrfOpDY6:-O4jBXO94wFHjrfOpDY7:bev5794) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8be06ae6e607ecdcc7a75809fe55444d98261a3/crates/blockifier/src/execution/syscalls/hint_processor.rs#L209)):*
> ```XML
> pub const L2_GAS: &str = "0x00000000000000000000000000000000000000000000000000004c325f474153";
> // "L1_DATA_GAS"
> pub const L1_DATA_GAS: &str = "0x0000000000000000000000000000000000000000004c315f444154415f474153";
> ```

how did you compute this?
i see there is no test for these values... is it simple to add?



_Code quote:_
```XML
// "L1_DATA_GAS"
pub const L1_DATA_GAS: &str = "0x0000000000000000000000000000000000000000004c315f444154415f474153";
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jBh-k6T4iGmY2Uihs:-O4jBh-k6T4iGmY2Uiht:b7yfin8) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8be06ae6e607ecdcc7a75809fe55444d98261a3/crates/blockifier/src/transaction/objects.rs#L142)):*
> ```XML
>         match self.resource_bounds {
>             ValidResourceBounds::L1Gas(bounds) => Ok(bounds),
>             ValidResourceBounds::AllResources { .. } => todo!(),
> ```

why todo? you can implement now



_Suggestion:_
```XML
 ValidResourceBounds::AllResources { l1_gas, .. } => l1_gas,
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 299 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4eO2KS5U3wiwsC5-Vb:-O4jBpWWAT1MXo68vof6:b3b06on) ([raw file](https://github.com/starkware-libs/sequencer/blob/643aa9eb918c0b7a1f93616c8c3025f4520f5eec/crates/blockifier/src/transaction/transactions.rs#L299)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

treated in an upper branch on the stack
</blockquote></details>

I think it's redundant... you can implement this in this PR,
however if this messes up your stack, LMK and I'll unblock
___
*[`crates/blockifier/src/transaction/transactions.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4eOFh-9DEhBC5FRQpL:-O4jBupr1hu9besd9BKU:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/643aa9eb918c0b7a1f93616c8c3025f4520f5eec/crates/blockifier/src/transaction/transactions.rs#L404)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`crates/blockifier/src/transaction/transactions.rs` line 522 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4eOK6N3STxv4wFY8I9:-O4jBw90-kP3wmg4fKAy:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/643aa9eb918c0b7a1f93616c8c3025f4520f5eec/crates/blockifier/src/transaction/transactions.rs#L522)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2024-08-20 09:54 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jBh-k6T4iGmY2Uihs:-O4jCDaOC3iNbOW0n8Ze:b-8p0xt2) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8be06ae6e607ecdcc7a75809fe55444d98261a3/crates/blockifier/src/transaction/objects.rs#L142)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why todo? you can implement now
</blockquote></details>

also, I see it isn't implemented at [the top of the stack](https://reviewable.io/reviews/starkware-libs/sequencer/511) either


<!-- Sent from Reviewable.io -->

2024-08-20 09:55 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jCV1o3TPfGdpD2Kvy:-O4jCV1o3TPfGdpD2Kvz:b2n2csv) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8be06ae6e607ecdcc7a75809fe55444d98261a3/crates/blockifier/src/transaction/objects.rs#L144)):*
> ```XML
>             ValidResourceBounds::AllResources { .. } => todo!(),
>         }
>     }
> ```

this function always succeeds (or panics, but after implementing you will always succeed).
No need to return a `Result`



_Suggestion:_
```XML
    pub fn l1_resource_bounds(&self) -> ResourceBounds {
        match self.resource_bounds {
            ValidResourceBounds::L1Gas(bounds) => bounds,
            ValidResourceBounds::AllResources { .. } => todo!(),
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-08-20 11:06 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jBXO94wFHjrfOpDY6:-O4jNHZs-lDUU5ZylL-i:b-4c2co6) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa091b8d308fa9da09d1d81ed12078edf08803c1/crates/blockifier/src/execution/syscalls/hint_processor.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how did you compute this?
i see there is no test for these values... is it simple to add?
</blockquote></details>

I computed it using [this](https://string-functions.com/string-hex.aspx)
It's the same calculation as done for l1_gas and l1_data_gas
___
*[`crates/blockifier/src/transaction/objects.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jBh-k6T4iGmY2Uihs:-O4jMYjJ5h91SF95YWcn:bcx2j64) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa091b8d308fa9da09d1d81ed12078edf08803c1/crates/blockifier/src/transaction/objects.rs#L142)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

also, I see it isn't implemented at [the top of the stack](https://reviewable.io/reviews/starkware-libs/sequencer/511) either
</blockquote></details>

1. At the current implementation, when this function is called, the caller assumes that l1_gas can cover for other resources. This function will eventually be removed.  I prefer that it will fail for now
2. The stack is unfinished yet...
___
*[`crates/blockifier/src/transaction/objects.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jCV1o3TPfGdpD2Kvy:-O4jOof386vHO24SC1xe:boav5te) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa091b8d308fa9da09d1d81ed12078edf08803c1/crates/blockifier/src/transaction/objects.rs#L144)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function always succeeds (or panics, but after implementing you will always succeed).
No need to return a `Result`
</blockquote></details>

Done.
It caused many functions to be able to return `T` instead of  `Result<T>,` so I changed them as well, which making the PR longer than expected; sorry.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 299 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4eO2KS5U3wiwsC5-Vb:-O4jRuUv1L35C8YuYNG7:b-tilz4n) ([raw file](https://github.com/starkware-libs/sequencer/blob/643aa9eb918c0b7a1f93616c8c3025f4520f5eec/crates/blockifier/src/transaction/transactions.rs#L299)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it's redundant... you can implement this in this PR,
however if this messes up your stack, LMK and I'll unblock
</blockquote></details>

It's in the next one on the stack, I prefer to keep it that way


<!-- Sent from Reviewable.io -->

2024-08-20 11:13 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jBXO94wFHjrfOpDY6:-O4jUIOj7BtrmN5dRgp_:b-t1ltph) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa091b8d308fa9da09d1d81ed12078edf08803c1/crates/blockifier/src/execution/syscalls/hint_processor.rs#L209)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I computed it using [this](https://string-functions.com/string-hex.aspx)
It's the same calculation as done for l1_gas and l1_data_gas
</blockquote></details>

please add a unit test for these three values... to "self document"
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 908 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jU05C6RXSxQRdb4Q8:-O4jU05C6RXSxQRdb4Q9:b-ub4mw) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a17d9655d4842b92d9e288912335900cfae37a5/crates/blockifier/src/transaction/account_transactions_test.rs#L908)):*
> ```XML
>     #[case] version: TransactionVersion,
> ) {
>     use cairo_vm::vm::runners::cairo_runner::ResourceTracker;
> ```

why did you move this import?



_Code quote:_
```XML
use cairo_vm::vm::runners::cairo_runner::ResourceTracker;
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jCV1o3TPfGdpD2Kvy:-O4jUAnM5-25823IohOx:b-f7qhmi) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa091b8d308fa9da09d1d81ed12078edf08803c1/crates/blockifier/src/transaction/objects.rs#L144)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
It caused many functions to be able to return `T` instead of  `Result<T>,` so I changed them as well, which making the PR longer than expected; sorry.
</blockquote></details>

nice!! reviewing `unwrap` and `?` deletions is always a welcome addition


<!-- Sent from Reviewable.io -->

2024-08-20 13:59 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 3 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jBXO94wFHjrfOpDY6:-O4k47SJ9hw6FuiQTSxM:b-7ir8ok) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa091b8d308fa9da09d1d81ed12078edf08803c1/crates/blockifier/src/execution/syscalls/hint_processor.rs#L209)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

add tests that `assert_eq!(L1_GAS, from_hex("L1_GAS"));` times 3
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4k4Ko6DPElLThV_Xcz:-O4k4Ko6DPElLThV_Xd-:b-fls0d7) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea1ff51131bd8b790d782231bbb7e372f98b2f1a/crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs#L215)):*
> ```XML
>                 ..Default::default()
>             },
>             resource_bounds: starknet_api::transaction::DeprecatedResourceBoundsMapping(
> ```

why not import the type?



_Code quote:_
```XML
starknet_api::transaction::DeprecatedResourceBoundsMapping
```


<!-- Sent from Reviewable.io -->

2024-08-21 06:37 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4jBXO94wFHjrfOpDY6:-O4ndmCy0A_jN0PmB1U_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa091b8d308fa9da09d1d81ed12078edf08803c1/crates/blockifier/src/execution/syscalls/hint_processor.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add tests that `assert_eq!(L1_GAS, from_hex("L1_GAS"));` times 3
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4k4Ko6DPElLThV_Xcz:-O4k52Lr2JxJXWCyCQ_T:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea1ff51131bd8b790d782231bbb7e372f98b2f1a/crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs#L215)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not import the type?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-21 07:39 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-21 12:18 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-21 12:37 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-22 06:08 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4sgYxyBE19_Pp-NVs3:-O4sgYxyBE19_Pp-NVs4:b7qsd76) ([raw file](https://github.com/starkware-libs/sequencer/blob/95a4d6ef3fabcfea4b325bd0ef27ce4dc1111ad8/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L50)):*
> ```XML
> pub const VALID_L1_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
> pub const VALID_L2_GAS_MAX_AMOUNT: u64 = 203484;
> pub const VALID_L2_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
> ```

@MohammadNassar1 Does that make sense? ATM the (python) gateway enforces l2 gas bounds to be zero



_Code quote:_
```XML
pub const VALID_L2_GAS_MAX_AMOUNT: u64 = 203484;
pub const VALID_L2_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
```


<!-- Sent from Reviewable.io -->

2024-08-22 06:50 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4sgYxyBE19_Pp-NVs3:-O4spRvlCMZgNKLoqYnn:bkaiy4) ([raw file](https://github.com/starkware-libs/sequencer/blob/95a4d6ef3fabcfea4b325bd0ef27ce4dc1111ad8/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L50)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@MohammadNassar1 Does that make sense? ATM the (python) gateway enforces l2 gas bounds to be zero
</blockquote></details>

Please note that this code is part of the mempool test utility crate. It doesn't run in a centralized SN; instead, it uses the Rust gateway.
In our mempool tests, we use non-zero L2 gas prices.


<!-- Sent from Reviewable.io -->

2024-08-22 07:28 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4sgYxyBE19_Pp-NVs3:-O4syglp12ekxWFTNV8O:b6s9cay) ([raw file](https://github.com/starkware-libs/sequencer/blob/95a4d6ef3fabcfea4b325bd0ef27ce4dc1111ad8/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L50)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please note that this code is part of the mempool test utility crate. It doesn't run in a centralized SN; instead, it uses the Rust gateway.
In our mempool tests, we use non-zero L2 gas prices.
</blockquote></details>

@nimrod-starkware the python GW will be updated to allow nonzero L2 gas if DA gas is set; mempool is developing a future version of SN. nonzero L2 gas prices should be allowed.
@MohammadNassar1 however, for nonzero L2 gas prices to be valid, you MUST provide DA gas bounds as well (they can be zero but shouldn't be, most of the time).
@nimrod-starkware why did these max bounds need to be zero?


<!-- Sent from Reviewable.io -->

2024-08-22 08:01 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4sgYxyBE19_Pp-NVs3:-O4t3lW90VAjIqiCvHVR:b7rnusg) ([raw file](https://github.com/starkware-libs/sequencer/blob/95a4d6ef3fabcfea4b325bd0ef27ce4dc1111ad8/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@nimrod-starkware the python GW will be updated to allow nonzero L2 gas if DA gas is set; mempool is developing a future version of SN. nonzero L2 gas prices should be allowed.
@MohammadNassar1 however, for nonzero L2 gas prices to be valid, you MUST provide DA gas bounds as well (they can be zero but shouldn't be, most of the time).
@nimrod-starkware why did these max bounds need to be zero?
</blockquote></details>

Currently, in the mempool, we don't have the L1_DA field. 
So once you merge your PRs, we need to use the new struct in the mempool, which enables L1 gas, L2 gas, and L1 DA.


<!-- Sent from Reviewable.io -->

2024-08-22 08:16 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O4sgYxyBE19_Pp-NVs3:-O4t8q0oAP5w5jgxaQIf:b-iz5s8b) ([raw file](https://github.com/starkware-libs/sequencer/blob/95a4d6ef3fabcfea4b325bd0ef27ce4dc1111ad8/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L50)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Currently, in the mempool, we don't have the L1_DA field. 
So once you merge your PRs, we need to use the new struct in the mempool, which enables L1 gas, L2 gas, and L1 DA.
</blockquote></details>

the new struct enforces the invariant that "L2 gas > 0 => L1 DA gas exists".
we cannot support positive L2 gas without L1 DA gas.
what would you estimate is the effort of adding L1 DA gas support?
if it's a lot of effort, what do you suggest would be a temporary solution? redefining resource bounds type in the mempool temporarily?


<!-- Sent from Reviewable.io -->

2024-08-25 07:38 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-25 08:24 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-25 10:58 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 52 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O58AsBU9uAXcM9En0jy:-O58AsBU9uAXcM9En0jz:bnduvzs) ([raw file](https://github.com/starkware-libs/sequencer/blob/4335170de655411e8a37d14d128abbc315ac0e4e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L52)):*
> ```XML
> pub const VALID_L2_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
> pub const VALID_L1_DATA_GAS_MAX_AMOUNT: u64 = 203484;
> pub const VALID_L1_DATA_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
> ```

where are these numbers from...?



_Code quote:_
```XML
pub const VALID_L2_GAS_MAX_AMOUNT: u64 = 203484;
pub const VALID_L2_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
pub const VALID_L1_DATA_GAS_MAX_AMOUNT: u64 = 203484;
pub const VALID_L1_DATA_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
```


<!-- Sent from Reviewable.io -->

2024-08-25 11:45 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 52 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O58AsBU9uAXcM9En0jy:-O58LFb092INVCTu4lzH:b-hd77r3) ([raw file](https://github.com/starkware-libs/sequencer/blob/4335170de655411e8a37d14d128abbc315ac0e4e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where are these numbers from...?
</blockquote></details>

I reverted `VALID_L2_GAS_MAX_AMOUNT` & `VALID_L2_GAS_MAX_PRICE_PER_UNIT`.
`VALID_L1_DATA_GAS_MAX_AMOUNT` & `VALID_L1_DATA_GAS_MAX_PRICE_PER_UNIT` is a copy paste.
IDK if it makes sense... @MohammadNassar1 ?


<!-- Sent from Reviewable.io -->

2024-08-25 13:25 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-25 15:36 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 52 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O58AsBU9uAXcM9En0jy:-O59ADYJ2-nTyiidOslQ:blii75v) ([raw file](https://github.com/starkware-libs/sequencer/blob/c56a17157c8d0630cf5fbe8e9d6a471207a44c1c/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L52)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I reverted `VALID_L2_GAS_MAX_AMOUNT` & `VALID_L2_GAS_MAX_PRICE_PER_UNIT`.
`VALID_L1_DATA_GAS_MAX_AMOUNT` & `VALID_L1_DATA_GAS_MAX_PRICE_PER_UNIT` is a copy paste.
IDK if it makes sense... @MohammadNassar1 ?
</blockquote></details>

These are the values used for testing, specifically the L2 values that I recently added. 
We used these values to establish resource bounds for testing. I believe no change is necessary here.


<!-- Sent from Reviewable.io -->

2024-08-26 09:45 UTC, dorimedini-starkware reviewed
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-26 13:19 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 209 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O5Dpg1C9xGvWlvJy6bj:-O5Dpg1C9xGvWlvJy6bk:b48475i) ([raw file](https://github.com/starkware-libs/sequencer/blob/582f4b3bf29763c8fa2fe99dcc5c679d288b7a01/crates/blockifier/src/execution/syscalls/hint_processor.rs#L209)):*
> ```XML
> pub const L2_GAS: &str = "0x00000000000000000000000000000000000000000000000000004c325f474153";
> // "L1_DATA";
> pub const L1_DATA: &str = "0x000000000000000000000000000000000000000000000000004c315f44415441";
> ```

why drop the `_GAS`?



_Code quote:_
```XML
// "L1_DATA";
pub const L1_DATA: &str = "0x000000000000000000000000000000000000000000000000004c315f44415441";
```


<!-- Sent from Reviewable.io -->

2024-08-26 13:21 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @MohammadNassar1, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 209 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O5Dpg1C9xGvWlvJy6bj:-O5Dq607023I784Cc6Jy:b5zi5j5) ([raw file](https://github.com/starkware-libs/sequencer/blob/582f4b3bf29763c8fa2fe99dcc5c679d288b7a01/crates/blockifier/src/execution/syscalls/hint_processor.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why drop the `_GAS`?
</blockquote></details>

Discussed it with @AvivYossef-starkware .
`L1_DATA_GAS` introduces some overflow (he can explain better what that is)


<!-- Sent from Reviewable.io -->

2024-08-26 13:23 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 209 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O5Dpg1C9xGvWlvJy6bj:-O5DqlmP6VFP5CP4rVoW:byeoth8) ([raw file](https://github.com/starkware-libs/sequencer/blob/582f4b3bf29763c8fa2fe99dcc5c679d288b7a01/crates/blockifier/src/execution/syscalls/hint_processor.rs#L209)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Discussed it with @AvivYossef-starkware .
`L1_DATA_GAS` introduces some overflow (he can explain better what that is)
</blockquote></details>

@AvivYossef-starkware can you explain?


<!-- Sent from Reviewable.io -->

2024-08-27 07:56 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-28 08:22 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 209 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O5Dpg1C9xGvWlvJy6bj:-O5N42c85HCYLPl6fsEM:b-k1pxin) ([raw file](https://github.com/starkware-libs/sequencer/blob/582f4b3bf29763c8fa2fe99dcc5c679d288b7a01/crates/blockifier/src/execution/syscalls/hint_processor.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@AvivYossef-starkware can you explain?
</blockquote></details>

see here 
https://github.com/EvyatarO/SNIPs/blob/snip-8/SNIPS/snip-8.md#:~:text=h(tip%2C%20resource_bounds_for_fee)%20%3D%20h(tip%2C%20(resource%7C%7Cmax_amount%7C%7Cmax_price_per_unit)%2C(resource%7C%7Cmax_amount%7C%7Cmax_price_per_unit)...)%2C%20where%20the%20resource%20order%20is%20L1_gas%2C%20L2_gas%2C%20and%20the%20resource%20name%20is%20at%20most%207%20characters.


<!-- Sent from Reviewable.io -->

2024-08-28 08:28 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 209 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/505#-O5Dpg1C9xGvWlvJy6bj:-O5N5QHI8PNrIYPsXSUo:bljmrma) ([raw file](https://github.com/starkware-libs/sequencer/blob/582f4b3bf29763c8fa2fe99dcc5c679d288b7a01/crates/blockifier/src/execution/syscalls/hint_processor.rs#L209)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

see here 
https://github.com/EvyatarO/SNIPs/blob/snip-8/SNIPS/snip-8.md#:~:text=h(tip%2C%20resource_bounds_for_fee)%20%3D%20h(tip%2C%20(resource%7C%7Cmax_amount%7C%7Cmax_price_per_unit)%2C(resource%7C%7Cmax_amount%7C%7Cmax_price_per_unit)...)%2C%20where%20the%20resource%20order%20is%20L1_gas%2C%20L2_gas%2C%20and%20the%20resource%20name%20is%20at%20most%207%20characters.
</blockquote></details>

wow
hidden very well


<!-- Sent from Reviewable.io -->

2024-08-28 08:55 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505#-:-O5NBcw6-bgaNBz47Aqo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-28 10:35 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/505)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-28 13:25 UTC, nimrod-starkware commented
### Merge activity

* **Aug 28, 9:25 AM EDT**: @nimrod-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/505).

2024-08-28 13:44 UTC, merged