build(fee): tx_args holds valid resource bounds
starkware-libs/sequencer pull request #508
Opened 2024-08-19 10:47 UTC by nimrod-starkware

2024-08-19 10:47 UTC, nimrod-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/508?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#508** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/508?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#507** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/507?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#506** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/506?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#505** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/505?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#504** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/504?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#503** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/503?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-19 11:41 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4ePZIH-1LzjXwDNXLD:-O4ePZIH-1LzjXwDNXLE:baxz39s) ([raw file](https://github.com/starkware-libs/sequencer/blob/181dc7ac0bdb8b03a6928fe44100f806b75146f7/crates/blockifier/src/test_utils/declare.rs#L111)):*
> ```XML
>                     signature: declare_tx_args.signature,
>                     sender_address: declare_tx_args.sender_address,
>                     resource_bounds: declare_tx_args.resource_bounds.0.try_into().expect("todo"),
> ```

will be handled in an upper branch



_Code quote:_
```XML
0.try_into().expect("todo")
```
___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4ePc_u03ga-KwExrrc:-O4ePc_u03ga-KwExrrd:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/181dc7ac0bdb8b03a6928fe44100f806b75146f7/crates/blockifier/src/test_utils/deploy_account.rs#L99)):*
> ```XML
>         starknet_api::transaction::DeployAccountTransaction::V3(DeployAccountTransactionV3 {
>             signature: deploy_tx_args.signature,
>             resource_bounds: deploy_tx_args.resource_bounds.0.try_into().expect("todo"),
> ```

ditto



_Code quote:_
```XML
.0.try_into().expect("todo"),
```
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4ePeJ8DexclEZkdzFU:-O4ePeJ8DexclEZkdzFV:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/181dc7ac0bdb8b03a6928fe44100f806b75146f7/crates/blockifier/src/test_utils/invoke.rs#L99)):*
> ```XML
>     } else if invoke_args.version == TransactionVersion::THREE {
>         starknet_api::transaction::InvokeTransaction::V3(InvokeTransactionV3 {
>             resource_bounds: invoke_args.resource_bounds.0.try_into().expect("todo"),
> ```

ditto



_Code quote:_
```XML
s.0.try_into().expect("todo")
```
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4ePrZgCL5MoujpNZN3:-O4ePrZgCL5MoujpNZN4:b-drcrqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/181dc7ac0bdb8b03a6928fe44100f806b75146f7/crates/papyrus_common/src/transaction_hash.rs#L226)):*
> ```XML
> ) -> Result<Felt, StarknetApiError> {
>     let (l1_resource_bounds, l2_resource_bounds) = match resource_bounds {
>         ValidResourceBounds::L1Gas(l1_gas_bounds) => (l1_gas_bounds, &ResourceBounds::default()),
> ```

WDYT?
Assuming l2_gas previously was always zero.



_Code quote:_
```XML
&ResourceBounds::default())
```
___
*[`crates/starknet_api/src/transaction_hash.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4eRFFj6G1gNo4SPggz:-O4eRFFj6G1gNo4SPgh-:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/181dc7ac0bdb8b03a6928fe44100f806b75146f7/crates/starknet_api/src/transaction_hash.rs#L181)):*
> ```XML
> ) -> Result<Felt, StarknetApiError> {
>     let (l1_resource_bounds, l2_resource_bounds) = match resource_bounds {
>         ValidResourceBounds::L1Gas(l1_gas_bounds) => (l1_gas_bounds, &ResourceBounds::default()),
> ```

ditto



_Code quote:_
```XML
ResourceBounds::default()
```


<!-- Sent from Reviewable.io -->

2024-08-20 11:34 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 10 files at r1, 11 of 17 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 26 of 31 files reviewed, 16 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYNU4D8draPEy-S64:-O4jYNU4D8draPEy-S65:bjzqb6u) (no related file):*
please add reviewer(s) from papyrus team

___
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 557 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jWn8K0_e11IxhDnmg:-O4jWn8K0_e11IxhDnmh:b-wpzklu) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L557)):*
> ```XML
>                 tip,
>                 nonce,
>                 resource_bounds: ExecutableResourceBoundsMapping::default(),
> ```

what did this previously return? was it equivalent to `l1_gas: ResourceBounds::default(), l2_gas: <ZERO BOUNDS>`?



_Code quote:_
```XML
ExecutableResourceBoundsMapping::default()
```
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4ePrZgCL5MoujpNZN3:-O4jX9b_-le7o9ZBHmQY:b-zd18vr) ([raw file](https://github.com/starkware-libs/sequencer/blob/181dc7ac0bdb8b03a6928fe44100f806b75146f7/crates/papyrus_common/src/transaction_hash.rs#L226)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

WDYT?
Assuming l2_gas previously was always zero.
</blockquote></details>

I prefer you do this:
```
let (l1_resource_bounds, l2_resource_bounds) = (
    resource_bounds.get_bound(Resource::L1Gas),
    resource_bounds.get_bound(Resource::L2Gas),
);
```
the fact that L2 bounds are zero in the "only L1" variant is an implementation detail of `ValidResourceBounds` IMO
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXalxEoTj83l2PxrT:-O4jXaly8P36GkV5iQYu:b-4ed193) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
> ```XML
>         Self::L1Gas(value.l1_gas)
>     }
> }
> ```

make this a `TryFrom` - you need to make sure the `l2_gas` is a zero bound in this conversion, right?



_Code quote:_
```XML
impl From<ResourceBoundsMapping> for starknet_api::transaction::ValidResourceBounds {
    fn from(value: ResourceBoundsMapping) -> Self {
        Self::L1Gas(value.l1_gas)
    }
}
```
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 166 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXi2C0rGv21fPndDh:-O4jXi2C0rGv21fPndDi:bmk9az5) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L166)):*
> ```XML
> }
> 
> impl From<starknet_api::transaction::ValidResourceBounds> for ResourceBoundsMapping {
> ```

why fully-qualified and not just import the ValidResourceBounds at the top of the module?



_Code quote:_
```XML
starknet_api::transaction::ValidResourceBounds
```
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXq6J4cS2KnYj6noZ:-O4jXq6K9lNCjJCCcnyd:bi89ni9) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L172)):*
> ```XML
>                 Self { l1_gas, l2_gas: ResourceBounds::default() }
>             }
>             starknet_api::transaction::ValidResourceBounds::AllResources(_) => todo!(),
> ```

how will you implement this?
this is RPC v0_6, should we be supporting data gas bounds at all?
please confer with the papyrus team



_Code quote:_
```XML
starknet_api::transaction::ValidResourceBounds::AllResources(_) => todo!(),
```
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jY1898vmNMJ5uslfG:-O4jY1898vmNMJ5uslfH:b-v6su7n) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_7/transaction.rs#L0)):*
same Q as above: will RPC v0_7 support data gas?
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXzWZ0Q4FKCQZ2UAY:-O4jXzWZ0Q4FKCQZ2UAZ:bslpbkk) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_7/transaction.rs#L172)):*
> ```XML
> }
> 
> impl From<ResourceBoundsMapping> for starknet_api::transaction::ValidResourceBounds {
> ```

why not import this type?



_Code quote:_
```XML
starknet_api::transaction::ValidResourceBounds
```
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jY9Xf3jtAL6sB4Xra:-O4jY9Xf3jtAL6sB4Xrb:bmwvhqn) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_storage/src/serialization/serializers.rs#L156)):*
> ```XML
>         pub l2_gas: ResourceBounds,
>         pub l1_data_gas: ResourceBounds,
>     }
> ```

what's this? what does this macro do? why do you need to explicitly enumerate the enum below?



_Code quote:_
```XML
auto_storage_serde! {
    pub struct AccountDeploymentData(pub Vec<Felt>);
    pub struct AllResourceBounds {
        pub l1_gas: ResourceBounds,
        pub l2_gas: ResourceBounds,
        pub l1_data_gas: ResourceBounds,
    }
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYUKU9FDlDuKP9MUH:-O4jYUKV2g5ZQIgzB_jK:b-45g45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/starknet_api/src/executable_transaction.rs#L79)):*
> ```XML
>                     tip: *rpc_tx.tip(),
>                     nonce: *rpc_tx.nonce(),
>                     resource_bounds: DeprecatedResourceBoundsMapping::default(),
> ```

is this still identical behavior (other than field type change)? identical "values"?



_Code quote:_
```XML
DeprecatedResourceBoundsMapping::default()
```
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 210 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYaB85aV5VELSOXar:-O4jYaB85aV5VELSOXas:b7v69kg) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/rpc_transaction.rs#L210)):*
> ```XML
> }
> 
> impl From<ResourceBoundsMapping> for crate::transaction::ValidResourceBounds {
> ```

why not import?



_Code quote:_
```XML
crate::transaction::ValidResourceBounds
```
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 213 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYevL4bRj6r7PvRpK:-O4jYevM5t6ikBRjrR1p:b-dgey3w) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/rpc_transaction.rs#L213)):*
> ```XML
>     fn from(value: ResourceBoundsMapping) -> Self {
>         Self::L1Gas(value.l1_gas)
>     }
> ```

as above: try from, make sure l2_gas is zero



_Code quote:_
```XML
    fn from(value: ResourceBoundsMapping) -> Self {
        Self::L1Gas(value.l1_gas)
    }
```
___
*[`crates/starknet_api/src/transaction.rs` line 990 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZ1yo9IqD8f4zyTCZ:-O4jZ1yo9IqD8f4zyTC_:bw3ocb6) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/transaction.rs#L990)):*
> ```XML
> 
> /// Serializes ValidResourceBounds as map for BC.
> // TODO(Nimrod): Can this be removed?
> ` [...]

2024-08-20 14:01 UTC, dorimedini-starkware reviewed
> Reviewed 18 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 26 of 31 files reviewed, 16 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-21 07:44 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 26 of 31 files reviewed, 16 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 557 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jWn8K0_e11IxhDnmg:-O4ngtXJBV7rb8Vq61xj:b-lov51p) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L557)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what did this previously return? was it equivalent to `l1_gas: ResourceBounds::default(), l2_gas: <ZERO BOUNDS>`?
</blockquote></details>

mmm no, it returned an empty mapping...
It's not equivalent
___
*[`crates/papyrus_common/src/transaction_hash.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4ePrZgCL5MoujpNZN3:-O4niCluEPzkqAvb0pnJ:bl99ua4) ([raw file](https://github.com/starkware-libs/sequencer/blob/181dc7ac0bdb8b03a6928fe44100f806b75146f7/crates/papyrus_common/src/transaction_hash.rs#L226)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer you do this:
```
let (l1_resource_bounds, l2_resource_bounds) = (
    resource_bounds.get_bound(Resource::L1Gas),
    resource_bounds.get_bound(Resource::L2Gas),
);
```
the fact that L2 bounds are zero in the "only L1" variant is an implementation detail of `ValidResourceBounds` IMO
</blockquote></details>

added 
```
impl ValidResourceBounds {
    pub fn get_l1_bounds(&self) -> ResourceBounds
    pub fn get_l2_bounds(&self) -> ResourceBounds 
}
```
and did a bit of refactor in `allocate_tx_resource_bounds_segment`
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 166 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXi2C0rGv21fPndDh:-O4noPs580TlImKvErTf:b-hjs7fm) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L166)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why fully-qualified and not just import the ValidResourceBounds at the top of the module?
</blockquote></details>

I was consistent with the other `From` functions in this area. What do you prefer?
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXzWZ0Q4FKCQZ2UAY:-O4npYIQEh3whlcIVBsg:b-hjs7fm) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_7/transaction.rs#L172)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not import this type?
</blockquote></details>

I was consistent with the other `From` functions in this area. What do you prefer?
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jY9Xf3jtAL6sB4Xra:-O4nrxvY6Swmg5Plh9F8:b-wn4z7b) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_storage/src/serialization/serializers.rs#L156)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this? what does this macro do? why do you need to explicitly enumerate the enum below?
</blockquote></details>

IDK, it doesn't compile otherwise.
It implements a storage trait and since `InvokeTransactionV3` has the field `ValidResourceBounds` it enforces `ValidResourceBounds` to be here and recursively `AllResourceBounds` to be here as well.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYUKU9FDlDuKP9MUH:-O4npjn10mbjKvI1YhoA:b-9gc6f4) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/starknet_api/src/executable_transaction.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this still identical behavior (other than field type change)? identical "values"?
</blockquote></details>

no, the mapping here is empty, it's not equivalent
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 210 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYaB85aV5VELSOXar:-O4nsqAp6HSVS6kRi1XU:b-hjs7fm) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/rpc_transaction.rs#L210)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not import?
</blockquote></details>

I was consistent with the other `From` functions in this area. What do you prefer?
___
*[`crates/starknet_api/src/transaction_hash.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4eRFFj6G1gNo4SPggz:-O4nqAFq32aH30XbEN0P:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/181dc7ac0bdb8b03a6928fe44100f806b75146f7/crates/starknet_api/src/transaction_hash.rs#L181)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same answer as above: use `get_bound`
</blockquote></details>

Done
___
*[`crates/starknet_api/src/transaction_hash.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZ9BFAeeyAeXtLc6C:-O4npxmE8hrQGZXZeD28:b-9jb029) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/transaction_hash.rs#L180)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

deja vu
this function is defined twice, yes? why?
</blockquote></details>

it is, IDK why.
Who should know?


<!-- Sent from Reviewable.io -->

2024-08-21 07:58 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 17 files at r2, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 30 of 32 files reviewed, 12 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 557 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jWn8K0_e11IxhDnmg:-O4nuXCI9geLr--8wkZ9:b963wam) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L557)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

mmm no, it returned an empty mapping...
It's not equivalent
</blockquote></details>

hmmm.. ok it's a test util but still, please ask for mempool eyes here
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 166 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXi2C0rGv21fPndDh:-O4nwN9D16muA4Fy-IGd:b-kwl9fd) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L166)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I was consistent with the other `From` functions in this area. What do you prefer?
</blockquote></details>

same as below - fine by me, consider adding a TODO
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXzWZ0Q4FKCQZ2UAY:-O4nwRwR6Gap6Gqm1Mx_:b-kwl9fd) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_7/transaction.rs#L172)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I was consistent with the other `From` functions in this area. What do you prefer?
</blockquote></details>

same as below - fine by me, consider adding a TODO
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jY9Xf3jtAL6sB4Xra:-O4nwJgg-tT9TlvB3Py3:bi70vrg) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_storage/src/serialization/serializers.rs#L156)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

IDK, it doesn't compile otherwise.
It implements a storage trait and since `InvokeTransactionV3` has the field `ValidResourceBounds` it enforces `ValidResourceBounds` to be here and recursively `AllResourceBounds` to be here as well.
</blockquote></details>

need eyes from papyrus team here
___
*[`crates/starknet_api/src/executable_transaction.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYUKU9FDlDuKP9MUH:-O4nutT4-mTv5wFlBM0W:bcu9n5m) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/starknet_api/src/executable_transaction.rs#L79)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

no, the mapping here is empty, it's not equivalent
</blockquote></details>

why was this the case originally? an empty mapping is not and was never a valid bounds object... can you investigate (via git blame) who wrote this function and ask the author?
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 210 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYaB85aV5VELSOXar:-O4nv77s1qFap3CR1EmX:b-18bjc) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/rpc_transaction.rs#L210)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I was consistent with the other `From` functions in this area. What do you prefer?
</blockquote></details>

consistency... though maybe add a TODO to use `use` in this module (non-blocking)
___
*[`crates/starknet_api/src/transaction.rs` line 974 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4nvfgd3z7-YmIJByuR:-O4nvfgd3z7-YmIJByuS:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bec47ceec0b1ad20c74afe734721ce306d28e61/crates/starknet_api/src/transaction.rs#L974)):*
> ```XML
>         }
>     }
> }
> ```





_Suggestion:_
```XML
impl ValidResourceBounds {
    pub fn get_l1_bounds(&self) -> ResourceBounds {
        match self {
            Self::L1Gas(l1_bounds) => *l1_bounds,
            Self::AllResources(AllResourceBounds { l1_gas, .. }) => *l1_gas,
        }
    }

    pub fn get_l2_bounds(&self) -> ResourceBounds {
        match self {
            Self::L1Gas(_) => ResourceBounds::default(),
            Self::AllResources(AllResourceBounds { l2_gas, .. }) => *l2_gas,
        }
    }
}
```
___
*[`crates/starknet_api/src/transaction_hash.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZ9BFAeeyAeXtLc6C:-O4nvug63_MtsFDDIsLd:b-rjw5it) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/transaction_hash.rs#L180)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

it is, IDK why.
Who should know?
</blockquote></details>

papyrus team (it's also defined in papyrus common - if they can `use` the one in starknet-api, they should)


<!-- Sent from Reviewable.io -->

2024-08-21 11:19 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 28 of 32 files reviewed, 12 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @ShahakShama, and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 557 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jWn8K0_e11IxhDnmg:-O4odhYTBT-f3sKwu0rO:b-vysxbo) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L557)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm.. ok it's a test util but still, please ask for mempool eyes here
</blockquote></details>

@MohammadNassar1 
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXalxEoTj83l2PxrT:-O4oQjRiDuTKLjaWnMQ4:b-9m3lho) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

make this a `TryFrom` - you need to make sure the `l2_gas` is a zero bound in this conversion, right?
</blockquote></details>

Eventually,`ResourceBoundsMapping` will be removed.
This code is temporary anyway, what do you prefer? panic if l2_gas bounds are not zero or change it to `TryFrom` and `expect` the results?
 
___
*[`crates/starknet_api/src/executable_transaction.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYUKU9FDlDuKP9MUH:-O4odu-T7nNkmfg8iyjF:bqk6gmt) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/starknet_api/src/executable_transaction.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was this the case originally? an empty mapping is not and was never a valid bounds object... can you investigate (via git blame) who wrote this function and ask the author?
</blockquote></details>

@MohammadNassar1 WDYT? 
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 213 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYevL4bRj6r7PvRpK:-O4oeW0o8O3UddzVzJtr:bnj7hl0) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/rpc_transaction.rs#L213)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

as above: try from, make sure l2_gas is zero
</blockquote></details>

same as above
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZFhW0CNHTjSRDVbI:-O4odpD51v1rBXAd6vHK:b-vysxbo) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_client/src/reader/objects/transaction.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

needs review from mempool/batcher team; I guess the mempool team.
</blockquote></details>

@MohammadNassar1 


<!-- Sent from Reviewable.io -->

2024-08-21 12:20 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 17 files at r2, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 10 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXalxEoTj83l2PxrT:-O4osD0f08HUBcmEdhsJ:b-km0end) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Eventually,`ResourceBoundsMapping` will be removed.
This code is temporary anyway, what do you prefer? panic if l2_gas bounds are not zero or change it to `TryFrom` and `expect` the results?
</blockquote></details>

let's go with panic
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 213 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYevL4bRj6r7PvRpK:-O4osI1R8BqFumVqRtqA:boyelym) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/rpc_transaction.rs#L213)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

same as above
</blockquote></details>

as above, panic for now


<!-- Sent from Reviewable.io -->

2024-08-21 12:33 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 30 of 33 files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXalxEoTj83l2PxrT:-O4ovM-371HNZM2VaSRS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

let's go with panic
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 213 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYevL4bRj6r7PvRpK:-O4ovOcpDAfjxauNmH6y:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/rpc_transaction.rs#L213)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

as above, panic for now
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-21 12:39 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 9 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/starknet_api/src/rpc_transaction.rs` line 213 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYevL4bRj6r7PvRpK:-O4owZuXDeJzX-ZihC8z:b-4hdivf) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/rpc_transaction.rs#L213)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not here, but you added something without a comment of mine somewhere here


<!-- Sent from Reviewable.io -->

2024-08-22 03:52 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXq6J4cS2KnYj6noZ:-O4s9ylw5cXvgs6pMJA0:bv34dn3) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L172)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@ShahakShama ?
</blockquote></details>

I think this should be product's call. I'll ask Leo in slack and let you know
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jY1898vmNMJ5uslfG:-O4sABWgBxMnPeFLbypz:b-t0nxhy) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_7/transaction.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same Q as above: will RPC v0_7 support data gas?
</blockquote></details>

same as v0_6
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jY9Xf3jtAL6sB4Xra:-O4sAGIcA8wxew4jHqwx:b-xnov7g) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_storage/src/serialization/serializers.rs#L156)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@ShahakShama
</blockquote></details>

This is ok. This macro generates storage serde functions for the struct and you need to explicitly list all the fields for that
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 429 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4sAu_X8jBhGolmgiv7:-O4sAu_X8jBhGolmgiv8:bhvlkjb) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fd99fa0f4234b109290643b4827de46ab8bb0a6/crates/papyrus_storage/src/serialization/serializers.rs#L429)):*
> ```XML
>     pub struct TransactionSignature(pub Vec<Felt>);
>     pub struct TransactionVersion(pub Felt);
>     pub enum ValidResourceBounds {
> ```

This should be erased by the time it gets to the storage. In the starknet_client you expect to have either an old transaction with just l1 gas or a new transaction with all 3 but by the time you get here you should convert old txs to the new format with l2_gas=0
Need to check with Leo that we indeed want l2_gas=0
___
*[`crates/starknet_api/src/transaction.rs` line 990 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZ1yo9IqD8f4zyTCZ:-O4sCJNb4Yx8aH_sC4ct:bpotzpb) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/transaction.rs#L990)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I think it can't be removed because of BC, right? @ShahakShama
</blockquote></details>

I think this shows my point that ValidResourceBounds should be just AllResourceBounds with #[serde(default)] on the l2 fields
___
*[`crates/starknet_api/src/transaction.rs` line 962 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4sBvBg2tQEdemsq9y8:-O4sBvBg2tQEdemsq9y9:bv9o05k) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fd99fa0f4234b109290643b4827de46ab8bb0a6/crates/starknet_api/src/transaction.rs#L962)):*
> ```XML
> 
> #[derive(Clone, Debug, Eq, PartialEq, Hash, Ord, PartialOrd)]
> pub enum ValidResourceBounds {
> ```

I think this should be just AllResourceBounds with possible option on the l2 fields or treat 0 as non existing
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZFhW0CNHTjSRDVbI:-O4sCiG4DwQxXxeVX-fJ:bji3l7y) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_client/src/reader/objects/transaction.rs#L)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@MohammadNassar1
</blockquote></details>

This has nothing to do with the mempool


<!-- Sent from Reviewable.io -->

2024-08-22 05:25 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 429 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4sAu_X8jBhGolmgiv7:-O4sXDeg9CT3Q_KKSaHB:b-orm6jf) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fd99fa0f4234b109290643b4827de46ab8bb0a6/crates/papyrus_storage/src/serialization/serializers.rs#L429)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should be erased by the time it gets to the storage. In the starknet_client you expect to have either an old transaction with just l1 gas or a new transaction with all 3 but by the time you get here you should convert old txs to the new format with l2_gas=0
Need to check with Leo that we indeed want l2_gas=0
</blockquote></details>

IIUC the 'old' txs signed l1 gas bounds and l2 gas bounds which had to be set to zero.
Isn't it the same case here?


<!-- Sent from Reviewable.io -->

2024-08-22 07:31 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 9 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 990 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZ1yo9IqD8f4zyTCZ:-O4szXlY6IaHJhV2aiQD:b5sblyc) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/transaction.rs#L990)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think this shows my point that ValidResourceBounds should be just AllResourceBounds with #[serde(default)] on the l2 fields
</blockquote></details>

no; we need to differentiate between old and new format:
1. old format: L1 gas and L2 gas exist, L2 gas MUST be zero
2. new format: L1 gas, L2 gas, L1 DA gas all exist, none of them have to be zero
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZFhW0CNHTjSRDVbI:-O4szkUTABL8XyhNnV0M:b-codm8f) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_client/src/reader/objects/transaction.rs#L)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This has nothing to do with the mempool
</blockquote></details>

from which project is the starknet client then? infra team?


<!-- Sent from Reviewable.io -->

2024-08-22 07:50 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 557 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jWn8K0_e11IxhDnmg:-O4t-zVKBZKD3QeYHy3p:b-i0k2gx) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L557)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@MohammadNassar1
</blockquote></details>

Please ensure that the input argument is of the same type. You don't need to use `try_into`.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 555 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4t-EK58Ld1KLVOOOrU:-O4t-EK58Ld1KLVOOOrV:b-558vaq) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6c55d99bb7ecdbfff6fd05dcddb214509a2cb39/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L555)):*
> ```XML
>     tip: Tip,
>     nonce: Nonce,
>     resource_bounds: DeprecatedResourceBoundsMapping,
> ```

Are you planning to keep the deprecated type?



_Code quote:_
```XML
resource_bounds: DeprecatedResourceBoundsMapping,
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYUKU9FDlDuKP9MUH:-O4t2BsBD77lhN3wCEOy:bom6ly9) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/starknet_api/src/executable_transaction.rs#L79)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@MohammadNassar1 WDYT?
</blockquote></details>

What exactly is your question? 
I don't see any changes in this code. 

This function creates an executable transaction from an RPC transaction. The resource bounds structs differ, so I implemented a `from` method. In this code, I used `.into()` to convert between the resource bounds types.
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZFhW0CNHTjSRDVbI:-O4t34948ENDI2lnhJit:b-hetn5k) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_client/src/reader/objects/transaction.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

from which project is the starknet client then? infra team?
</blockquote></details>

I think it's for the Papyurs team.


<!-- Sent from Reviewable.io -->

2024-08-22 07:56 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 9 unresolved discussions (waiting on @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jYUKU9FDlDuKP9MUH:-O4t4U44Ak4-s3qeArNo:b-plofgt) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e83dd38819bccffe6a1d15a27c0acc4ac1fb70e/crates/starknet_api/src/executable_transaction.rs#L79)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What exactly is your question? 
I don't see any changes in this code. 

This function creates an executable transaction from an RPC transaction. The resource bounds structs differ, so I implemented a `from` method. In this code, I used `.into()` to convert between the resource bounds types.
</blockquote></details>

right, the problematic change was reverted... unblocking :)


<!-- Sent from Reviewable.io -->

2024-08-22 08:25 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @ShahakShama, and @TzahiTaub)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 555 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4t-EK58Ld1KLVOOOrU:-O4t6UQp421D7aZCCF_V:b58kv6r) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6c55d99bb7ecdbfff6fd05dcddb214509a2cb39/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L555)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Are you planning to keep the deprecated type?
</blockquote></details>

No, `ValidResourceBounds` should replace it.


<!-- Sent from Reviewable.io -->

2024-08-22 09:15 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 11 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 634 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tME9x0KXx5TtbOtej:-O4tME9x0KXx5TtbOtek:b-a6519m) ([raw file](https://github.com/starkware-libs/sequencer/blob/054bcefab4aae19d266af7b867b6f384247016e1/crates/papyrus_protobuf/src/converters/transaction.rs#L634)):*
> ```XML
> impl From<ValidResourceBounds> for protobuf::ResourceBounds {
>     fn from(value: ValidResourceBounds) -> Self {
>         let mut res = protobuf::ResourceBounds::default();
> ```

informative name please



_Suggestion:_
```XML
 protobuf_bounds
```
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 652 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tMJIc4ld96-zptE3S:-O4tMJIc4ld96-zptE3T:b-m3nejd) ([raw file](https://github.com/starkware-libs/sequencer/blob/054bcefab4aae19d266af7b867b6f384247016e1/crates/papyrus_protobuf/src/converters/transaction.rs#L652)):*
> ```XML
>         res.l2_gas = Some(resource_limits_l2);
> 
>         res
> ```

What is `protobuf::ResourceLimits`?
another duplicated resource bounds struct?
where is the DA gas?



_Code quote:_
```XML
res
```


<!-- Sent from Reviewable.io -->

2024-08-22 09:30 UTC, ShahakShama reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZFhW0CNHTjSRDVbI:-O4tQ7VH15QyqIOuilLL:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_client/src/reader/objects/transaction.rs#L)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think it's for the Papyurs team.
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2024-08-22 09:38 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 33 of 36 files reviewed, 12 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 634 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tME9x0KXx5TtbOtej:-O4tOa0uEo5NEVmlxaqM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/054bcefab4aae19d266af7b867b6f384247016e1/crates/papyrus_protobuf/src/converters/transaction.rs#L634)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

informative name please
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 652 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tMJIc4ld96-zptE3S:-O4tOMOV762-K68FAXh4:b1brsdv) ([raw file](https://github.com/starkware-libs/sequencer/blob/054bcefab4aae19d266af7b867b6f384247016e1/crates/papyrus_protobuf/src/converters/transaction.rs#L652)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

What is `protobuf::ResourceLimits`?
another duplicated resource bounds struct?
where is the DA gas?
</blockquote></details>

yes, another duplication...
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 180 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tRo1l89y2sRyW8f1u:-O4tRo1l89y2sRyW8f1v:b-py0qwe) ([raw file](https://github.com/starkware-libs/sequencer/blob/22959083a1560b1240e9105ed7137f1760d09027/crates/papyrus_rpc/src/v0_6/transaction.rs#L180)):*
> ```XML
>                 l2_gas,
>                 ..
>             }) => Self { l1_gas, l2_gas },
> ```

added this now, it's required for some tests but eventually will be removed



_Code quote:_
```XML
Self { l1_gas, l2_gas },
```
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 192 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tRw-oDyzHyXDMg211:-O4tRw-oDyzHyXDMg212:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/22959083a1560b1240e9105ed7137f1760d09027/crates/papyrus_rpc/src/v0_7/transaction.rs#L192)):*
> ```XML
>                 l2_gas,
>                 ..
>             }) => Self { l1_gas, l2_gas },
> ```

ditto



_Code quote:_
```XML
 Self { l1_gas, l2_gas },
```


<!-- Sent from Reviewable.io -->

2024-08-22 09:38 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 11 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 180 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tRmaBEWMOGhu47cUS:-O4tRmaBEWMOGhu47cUT:b8twsm6) ([raw file](https://github.com/starkware-libs/sequencer/blob/22959083a1560b1240e9105ed7137f1760d09027/crates/papyrus_rpc/src/v0_6/transaction.rs#L180)):*
> ```XML
>                 l2_gas,
>                 ..
>             }) => Self { l1_gas, l2_gas },
> ```

shouldn't we panic / raise error in this case? this indicates new bounds format on RPC 0_6



_Code quote:_
```XML
            starknet_api::transaction::ValidResourceBounds::AllResources(AllResourceBounds {
                l1_gas,
                l2_gas,
                ..
            }) => Self { l1_gas, l2_gas },
```
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 192 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tRun0BEpRYuVZ0TVy:-O4tRun0BEpRYuVZ0TVz:b-isijkq) ([raw file](https://github.com/starkware-libs/sequencer/blob/22959083a1560b1240e9105ed7137f1760d09027/crates/papyrus_rpc/src/v0_7/transaction.rs#L192)):*
> ```XML
>                 l2_gas,
>                 ..
>             }) => Self { l1_gas, l2_gas },
> ```

same Q as for 0_6



_Code quote:_
```XML
            starknet_api::transaction::ValidResourceBounds::AllResources(AllResourceBounds {
                l1_gas,
                l2_gas,
                ..
            }) => Self { l1_gas, l2_gas },
```


<!-- Sent from Reviewable.io -->

2024-08-22 09:42 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 11 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 180 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tRo1l89y2sRyW8f1u:-O4tSRwN6QUTTNUiyeyH:braa0ff) ([raw file](https://github.com/starkware-libs/sequencer/blob/22959083a1560b1240e9105ed7137f1760d09027/crates/papyrus_rpc/src/v0_6/transaction.rs#L180)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

added this now, it's required for some tests but eventually will be removed
</blockquote></details>

add a todo then?
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 192 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tRw-oDyzHyXDMg211:-O4tSXTs0EOtzB5_HSCh:bw5qaxr) ([raw file](https://github.com/starkware-libs/sequencer/blob/22959083a1560b1240e9105ed7137f1760d09027/crates/papyrus_rpc/src/v0_7/transaction.rs#L192)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

todo please


<!-- Sent from Reviewable.io -->

2024-08-22 09:43 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 180 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tRo1l89y2sRyW8f1u:-O4tSyNA71Amw8KSCgoR:bcowp1w) ([raw file](https://github.com/starkware-libs/sequencer/blob/22959083a1560b1240e9105ed7137f1760d09027/crates/papyrus_rpc/src/v0_6/transaction.rs#L180)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a todo then?
</blockquote></details>

there is already a [PR](https://reviewable.io/reviews/starkware-libs/sequencer/557) which removes this struct entirely.
do you want a todo anyway?


<!-- Sent from Reviewable.io -->

2024-08-22 09:46 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 11 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 180 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tRo1l89y2sRyW8f1u:-O4tTav01ta5XU47eVOA:b-p335z0) ([raw file](https://github.com/starkware-libs/sequencer/blob/22959083a1560b1240e9105ed7137f1760d09027/crates/papyrus_rpc/src/v0_6/transaction.rs#L180)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

there is already a [PR](https://reviewable.io/reviews/starkware-libs/sequencer/557) which removes this struct entirely.
do you want a todo anyway?
</blockquote></details>

yes, because we always assume commits that are merged are self-contained; if you are merging temporary code it should be marked as such, even if development of the fix is complete


<!-- Sent from Reviewable.io -->

2024-08-22 09:58 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 34 of 36 files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 180 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tRo1l89y2sRyW8f1u:-O4tWSqV61ttsVi5hV8A:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/22959083a1560b1240e9105ed7137f1760d09027/crates/papyrus_rpc/src/v0_6/transaction.rs#L180)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, because we always assume commits that are merged are self-contained; if you are merging temporary code it should be marked as such, even if development of the fix is complete
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 192 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tRw-oDyzHyXDMg211:-O4tWS006_Gd4srzYAh7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/22959083a1560b1240e9105ed7137f1760d09027/crates/papyrus_rpc/src/v0_7/transaction.rs#L192)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

todo please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-22 10:05 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 9 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @ShahakShama, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-25 08:25 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 9 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, @ShahakShama, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-25 11:00 UTC, dorimedini-starkware reviewed
> Reviewed 7 of 7 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 9 unresolved discussions (waiting on @MohammadNassar1, @ShahakShama, and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 962 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4sBvBg2tQEdemsq9y8:-O58BJJyCtxyJdZBcpVj:bw9uu26) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fd99fa0f4234b109290643b4827de46ab8bb0a6/crates/starknet_api/src/transaction.rs#L962)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think this should be just AllResourceBounds with possible option on the l2 fields or treat 0 as non existing
</blockquote></details>

why?
the semantics of not exists/exists and eq zero/exists and positive are confusing anyway; I like that we document via code which bounds input exactly we accept


<!-- Sent from Reviewable.io -->

2024-08-25 13:26 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @MohammadNassar1, @ShahakShama, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-26 09:46 UTC, dorimedini-starkware reviewed
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @MohammadNassar1, @ShahakShama, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-26 13:19 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @MohammadNassar1, @ShahakShama, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-27 07:56 UTC, dorimedini-starkware reviewed
> Reviewed 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @MohammadNassar1, @ShahakShama, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-28 08:57 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @MohammadNassar1, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 652 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tMJIc4ld96-zptE3S:-O5NBsxZ3OY8QHu5nMEs:b828mia) ([raw file](https://github.com/starkware-libs/sequencer/blob/054bcefab4aae19d266af7b867b6f384247016e1/crates/papyrus_protobuf/src/converters/transaction.rs#L652)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

yes, another duplication...
</blockquote></details>

@ShahakShama does this struct need updating for the new data gas bounds?
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZFhW0CNHTjSRDVbI:-O5NC6ewEoAAdspwyVv2:b5hbeht) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_client/src/reader/objects/transaction.rs#L)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

yes
</blockquote></details>

@ShahakShama do you approve these changes?


<!-- Sent from Reviewable.io -->

2024-08-28 10:36 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @MohammadNassar1, @ShahakShama, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-08-28 14:15 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @MohammadNassar1, @ShahakShama, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-01 07:02 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/mempool/src/transaction_queue.rs` line 107 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5gNhWw2Q8C245uE_yj:-O5gNhWw2Q8C245uE_yk:b5l3mfi) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/mempool/src/transaction_queue.rs#L107)):*
> ```XML
>             nonce: Nonce::default(),
>             tx_hash: TransactionHash::default(),
>             tip: Tip::default(),
> ```

why change this?



_Suggestion:_
```XML
            ..Default::default()
```


<!-- Sent from Reviewable.io -->

2024-09-01 07:15 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/mempool/src/transaction_queue.rs` line 107 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5gNhWw2Q8C245uE_yj:-O5gQkVp3bCiUme9OScK:b3otj7e) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/mempool/src/transaction_queue.rs#L107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why change this?
</blockquote></details>

The problem was that `TransactionReference` cannot derive `Default` anymore.
`ValidResourceBounds` is an enum that doesn't have a natural default choice.
I had to remove `#[derive(Default)]` from `TransactionReference` and the syntax `..Default::default()` is no longer valid.


<!-- Sent from Reviewable.io -->

2024-09-01 08:28 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXalxEoTj83l2PxrT:-O4tRI4i-qJBB1niyufO:b-yboioh) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Panic is very bad!! it means the node will panic if someone tries to get the receipt of a post 0.13.3 transaction
I think that what you did at the start is good. It


<!-- Sent from Reviewable.io -->

2024-09-01 08:49 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXalxEoTj83l2PxrT:-O5glT3HA_mWnqeknmtf:b-rsw48j) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Panic is very bad!! it means the node will panic if someone tries to get the receipt of a post 0.13.3 transaction
I think that what you did at the start is good. It
</blockquote></details>

Do you mean this?
`Self::L1Gas(value.l1_gas)`
Without asserting that l2_gas bounds are zero?


<!-- Sent from Reviewable.io -->

2024-09-02 10:23 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 16 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/mod.rs` line 26 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m8CX4DdM3oRbJeFbU:-O5m8CX4DdM3oRbJeFbV:b-sy6blm) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/mod.rs#L26)):*
> ```XML
>     DecodeError(#[from] DecodeError),
>     #[error(transparent)]
>     StarknetApiError(#[from] StarknetApiError),
> ```

Remove this after you do the rest of the changes suggested
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 652 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tMJIc4ld96-zptE3S:-O5m8i_y2mPRkqb0cdTP:b9hhmtx) ([raw file](https://github.com/starkware-libs/sequencer/blob/054bcefab4aae19d266af7b867b6f384247016e1/crates/papyrus_protobuf/src/converters/transaction.rs#L652)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@ShahakShama does this struct need updating for the new data gas bounds?
</blockquote></details>

Yes, but you need to add the new fields at the end of the message so that it can work with nodes that didn't do this upgrade (Juno/Pathfinder)
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 449 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m8Hyc0ruflK5Yp7fP:-O5m8Hyc0ruflK5Yp7fQ:bx6iema) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction.rs#L449)):*
> ```XML
>             })?,
>         )?
>         .try_into()?;
> ```

You should add `impl TryFrom<protobuf::ResourceBounds> for ValidResourceBounds` and then use it here instead of try_into()?
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 555 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m9LCs12vkm8vcn-Wr:-O5m9LCs12vkm8vcn-Ws:b-lmwb7a) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction.rs#L555)):*
> ```XML
> }
> 
> impl TryFrom<protobuf::ResourceBounds> for DeprecatedResourceBoundsMapping {
> ```

Can we erase this?
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 606 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m9Myk4KRWRmt6mrLP:-O5m9Myk4KRWRmt6mrLQ:b-lmwb7a) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction.rs#L606)):*
> ```XML
> }
> 
> impl From<DeprecatedResourceBoundsMapping> for protobuf::ResourceBounds {
> ```

Can we erase this?
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 790 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m8zF98nJizlrgBj7L:-O5m8zF98nJizlrgBj7M:buo9nmt) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction.rs#L790)):*
> ```XML
>             })?,
>         )?
>         .try_into()?;
> ```

Same here
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 1109 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m9-j9-I3qUX4T-yTv:-O5m9-j9-I3qUX4T-yTw:buo9nmt) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction.rs#L1109)):*
> ```XML
>             })?,
>         )?
>         .try_into()?;
> ```

Same here
___
*[`crates/papyrus_protobuf/src/converters/transaction_test.rs` line 199 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m9bXkCD18ISr80pnd:-O5m9bXkCD18ISr80pne:bbhvrus) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction_test.rs#L199)):*
> ```XML
>         gas_consumed: GasVector::default(),
>     };
>     static ref RESOURCE_BOUNDS_MAPPING: DeprecatedResourceBoundsMapping =
> ```

Instead of calling try_into on this all the time, change it to ValidResourceBounds. IMO you should use AllResourceBounds variant since it's more interesting
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXalxEoTj83l2PxrT:-O5m9lCeEIn3ikMWKQTb:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Do you mean this?
`Self::L1Gas(value.l1_gas)`
Without asserting that l2_gas bounds are zero?
</blockquote></details>

yes
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 176 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5mAGBJ-eo4D2xXTKbg:-O5mAGBJ-eo4D2xXTKbh:b7h81ar) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_rpc/src/v0_7/transaction.rs#L176)):*
> ```XML
>     fn from(value: ResourceBoundsMapping) -> Self {
>         if !value.l2_gas.is_zero() {
>             panic!("Resource bounds mapping l2 gas is expected to be zero. Got: {:?}", value.l2_gas)
> ```

Same as v0_6, remove this panic
___
*[`crates/starknet_api/src/transaction.rs` line 990 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZ1yo9IqD8f4zyTCZ:-O5mAa189nGsf-a38TYc:bmn44v6) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/transaction.rs#L990)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no; we need to differentiate between old and new format:
1. old format: L1 gas and L2 gas exist, L2 gas MUST be zero
2. new format: L1 gas, L2 gas, L1 DA gas all exist, none of them have to be zero
</blockquote></details>

Back to the original comment by Nimrod, what is BC?
___
*[`crates/starknet_api/src/transaction.rs` line 1001 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5mF4ee1Wyfp2WAX2Zo:-O5mF4ee1Wyfp2WAX2Zp:b7shhn) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/starknet_api/src/transaction.rs#L1001)):*
> ```XML
> 
> /// Deserializes raw resource bounds, given as map, into valid resource bounds.
> impl<'de> Deserialize<'de> for ValidResourceBounds {
> ```

I think it's better and more bugless to derive Deserialize and Serialize, add `#[serde(untagged)]` to the enum and add `#[serde(deny_unknown_fields)]` to DeprecatedResourceBounds
___
*[`crates/starknet_api/src/transaction_hash.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZ9BFAeeyAeXtLc6C:-O5mFQYHAFmNRC9LdeXz:b-yxqq7p) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/transaction_hash.rs#L180)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@ShahakShama WDYT?
</blockquote></details>

We'll erase papyrus_common in a separate PR
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZFhW0CNHTjSRDVbI:-O5mFeFgD2GNJ9bmJziB:b-488jcw) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_client/src/reader/objects/transaction.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@ShahakShama do you approve these changes?
</blockquote></details>

Can I take a json string of the deprecated resource [...]

2024-09-02 11:14 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 16 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXalxEoTj83l2PxrT:-O5mR-49CilX-4i0Fd_p:b6fez33) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

yes
</blockquote></details>

I confused. You should change this to TryFrom and use `internal_server_error("Got a transaction with non zero l2 gas")`
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXq6J4cS2KnYj6noZ:-O5mQrqW33Fsy9X0XXIu:b-ho4oec) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L172)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think this should be product's call. I'll ask Leo in slack and let you know
</blockquote></details>

You should keep it as it is. You can remove the TODO


<!-- Sent from Reviewable.io -->

2024-09-02 13:13 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 15 unresolved discussions (waiting on @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 990 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZ1yo9IqD8f4zyTCZ:-O5mrO8ZBjwz2w_mr4iY:bkx3x5n) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/transaction.rs#L990)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Back to the original comment by Nimrod, what is BC?
</blockquote></details>

backwards compatibility
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZFhW0CNHTjSRDVbI:-O5mrcnm-swjlSCiGx9R:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_client/src/reader/objects/transaction.rs#L)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Can I take a json string of the deprecated resource bounds and load it into ValidResourceBounds? If yes, then I approve
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2024-09-03 06:34 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 15 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/mod.rs` line 26 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m8CX4DdM3oRbJeFbU:-O5qUoHoBbA_t5VqDd7Y:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/mod.rs#L26)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this after you do the rest of the changes suggested
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 449 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m8Hyc0ruflK5Yp7fP:-O5mPEBi7Xw9Vv73of86:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction.rs#L449)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should add `impl TryFrom<protobuf::ResourceBounds> for ValidResourceBounds` and then use it here instead of try_into()?
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 555 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m9LCs12vkm8vcn-Wr:-O5qSX4t63RtRbAoXG_T:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction.rs#L555)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Can we erase this?
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 606 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m9Myk4KRWRmt6mrLP:-O5qUWsw20aPjkkFowCE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction.rs#L606)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Can we erase this?
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 790 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m8zF98nJizlrgBj7L:-O5qUh7nCuLG16IXmq00:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction.rs#L790)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 1109 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m9-j9-I3qUX4T-yTv:-O5qUhLmCTMlZYzEnYX7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction.rs#L1109)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction_test.rs` line 199 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5m9bXkCD18ISr80pnd:-O5qUyM1-8sMh9B0RGkA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_protobuf/src/converters/transaction_test.rs#L199)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Instead of calling try_into on this all the time, change it to ValidResourceBounds. IMO you should use AllResourceBounds variant since it's more interesting
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXalxEoTj83l2PxrT:-O5qXp1236kh3nTTLtg8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I confused. You should change this to TryFrom and use `internal_server_error("Got a transaction with non zero l2 gas")`
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXq6J4cS2KnYj6noZ:-O5qVqqWDQSMeMuHqOwE:b6pjlab) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L172)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should keep it as it is. You can remove the TODO
</blockquote></details>

WDYM?
Should I panic in the case of `ValidResourceBounds::AllResources(_)`?
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 176 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5mAGBJ-eo4D2xXTKbg:-O5qXSf7ACseE0I7DChK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/papyrus_rpc/src/v0_7/transaction.rs#L176)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as v0_6, remove this panic
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-03 06:46 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 33 of 43 files reviewed, 14 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 1001 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5mF4ee1Wyfp2WAX2Zo:-O5qcEdXAFxOwcZQgAh9:b-f2whsp) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/starknet_api/src/transaction.rs#L1001)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think it's better and more bugless to derive Deserialize and Serialize, add `#[serde(untagged)]` to the enum and add `#[serde(deny_unknown_fields)]` to DeprecatedResourceBounds
</blockquote></details>

Your suggestion won't work..
It will always deserialize to the `AllResources` variant...
We need to check somewhere that l2 gas is zero in the first variant


<!-- Sent from Reviewable.io -->

2024-09-03 07:16 UTC, dorimedini-starkware requested changes
> Reviewed 10 of 10 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 16 unresolved discussions (waiting on @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 577 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5qi77JDofy-t1XxccN:-O5qi77JDofy-t1XxccO:b-2e6390) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd556ecc1f8ac633d627fb2cc4eca2b7ceac7ff3/crates/papyrus_protobuf/src/converters/transaction.rs#L577)):*
> ```XML
>         } else {
>             ValidResourceBounds::AllResources(AllResourceBounds { l1_gas, l2_gas, l1_data_gas })
>         })
> ```

I am not at all sure about this.
@ShahakShama is this an area we said we want to be able to differentiate between missing data gas, or not mossing data gas?
1. If we allow no data gas, why return MissingField if it doesn't exist?
2. If we don't allow lack of data gas, why would we ever return the `L1Gas` variant?

Or, is this code only supposed to handle txs with "fee enforcement" enabled? If this is the case, and this code will never handle an all-bounds-are-zero case, then I'll unblock...



_Code quote:_
```XML
        Ok(if l1_data_gas.is_zero() && l2_gas.is_zero() {
            ValidResourceBounds::L1Gas(l1_gas.clone())
        } else {
            ValidResourceBounds::AllResources(AllResourceBounds { l1_gas, l2_gas, l1_data_gas })
        })
```
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5qj7VQ2aqd15BFJ5E-:-O5qj7VQ2aqd15BFJ5E0:b-17rc89) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd556ecc1f8ac633d627fb2cc4eca2b7ceac7ff3/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
> ```XML
>     type Error = ErrorObjectOwned;
>     fn try_from(value: ResourceBoundsMapping) -> Result<Self, Self::Error> {
>         if !value.l2_gas.is_zero() {
> ```

shouldn't you also check if data gas bounds exist...? what is the input object type? a mapping?



_Code quote:_
```XML
if !value.l2_gas.is_zero() {
```
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 176 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5qjPvcDxFr39gfY6Yx:-O5qjPvcDxFr39gfY6Yy:b-i1e23q) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd556ecc1f8ac633d627fb2cc4eca2b7ceac7ff3/crates/papyrus_rpc/src/v0_7/transaction.rs#L176)):*
> ```XML
>     type Error = ErrorObjectOwned;
>     fn try_from(value: ResourceBoundsMapping) -> Result<Self, Self::Error> {
>         if !value.l2_gas.is_zero() {
> ```

same Q about data gas



_Code quote:_
```XML
 if !value.l2_gas.is_zero() {
```


<!-- Sent from Reviewable.io -->

2024-09-03 08:18 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 16 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 577 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5qi77JDofy-t1XxccN:-O5qxS5R1Pe-IdE7gR76:btobls4) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd556ecc1f8ac633d627fb2cc4eca2b7ceac7ff3/crates/papyrus_protobuf/src/converters/transaction.rs#L577)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I am not at all sure about this.
@ShahakShama is this an area we said we want to be able to differentiate between missing data gas, or not mossing data gas?
1. If we allow no data gas, why return MissingField if it doesn't exist?
2. If we don't allow lack of data gas, why would we ever return the `L1Gas` variant?

Or, is this code only supposed to handle txs with "fee enforcement" enabled? If this is the case, and this code will never handle an all-bounds-are-zero case, then I'll unblock...
</blockquote></details>

I spoke with Shahak about it, and he said that's what he and Ariel agreed on.


<!-- Sent from Reviewable.io -->

2024-09-03 08:22 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 16 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 164 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5qj7VQ2aqd15BFJ5E-:-O5qxmZe-9WNN8UTd6vu:bqyzlp3) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd556ecc1f8ac633d627fb2cc4eca2b7ceac7ff3/crates/papyrus_rpc/src/v0_6/transaction.rs#L164)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shouldn't you also check if data gas bounds exist...? what is the input object type? a mapping?
</blockquote></details>

This is the input type:
```
pub struct ResourceBoundsMapping {
    pub l1_gas: ResourceBounds,
    pub l2_gas: ResourceBounds,
}
```
There are a lot of duplicates....
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 176 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5qjPvcDxFr39gfY6Yx:-O5qyKpj0bbQhMP7UmiA:b-wo0wf8) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd556ecc1f8ac633d627fb2cc4eca2b7ceac7ff3/crates/papyrus_rpc/src/v0_7/transaction.rs#L176)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same Q about data gas
</blockquote></details>

same answer :)


<!-- Sent from Reviewable.io -->

2024-09-03 13:49 UTC, dorimedini-starkware submitted a review, later dismissed
> Reviewed 4 of 4 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 14 unresolved discussions (waiting on @nimrod-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/transaction.proto` line 13 at r24](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5s7j73BorDsb_i-41h:-O5s7j73BorDsb_i-41i:bv253ez) ([raw file](https://github.com/starkware-libs/sequencer/blob/72677c18836de5eee0642b173bd48c70a3d46c59/crates/papyrus_protobuf/src/proto/p2p/proto/transaction.proto#L13)):*
> ```proto
>     ResourceLimits l1_gas = 1;
>     ResourceLimits l2_gas = 2;
>     ResourceLimits l1_data_gas = 3;
> ```

what's this...? @ShahakShama any BC issues may arise from this addition?



_Code quote:_
```proto
 ResourceLimits l1_data_gas = 3;
```


<!-- Sent from Reviewable.io -->

2024-09-03 13:52 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 14 unresolved discussions (waiting on @nimrod-starkware, @ShahakShama, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-03 14:22 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 577 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5qi77JDofy-t1XxccN:-O5sAxgx5twh21AxqeIN:bdj0sf) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd556ecc1f8ac633d627fb2cc4eca2b7ceac7ff3/crates/papyrus_protobuf/src/converters/transaction.rs#L577)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I spoke with Shahak about it, and he said that's what he and Ariel agreed on.
</blockquote></details>

Yes. @dorimedini-starkware the reason it's ok here is that this is a transaction inside a block, and the gateway would've rejected it if l2_gas=0 but l1_data_gas is present
___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 582 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5sBaVw7jNcpywpFQHz:-O5sBaVw7jNcpywpFQI-:b-l9168) ([raw file](https://github.com/starkware-libs/sequencer/blob/78c8a8215912590d346da58cc4a699b8efc4fa00/crates/papyrus_protobuf/src/converters/transaction.rs#L582)):*
> ```XML
> }
> 
> impl TryFrom<protobuf::ResourceLimits> for ResourceBounds {
> ```

Unrelated to your PR: ResourceBounds is very confusing. Can we rename it?
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/transaction.proto` line 13 at r24](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5s7j73BorDsb_i-41h:-O5s9bQb4apyXfW-fWtS:bcm346m) ([raw file](https://github.com/starkware-libs/sequencer/blob/72677c18836de5eee0642b173bd48c70a3d46c59/crates/papyrus_protobuf/src/proto/p2p/proto/transaction.proto#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this...? @ShahakShama any BC issues may arise from this addition?
</blockquote></details>

No, because it's appended to the list of fields. If we would've added it before l2_gas then BC issues would've happened
___
*[`crates/papyrus_rpc/src/v0_6/transaction.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jXq6J4cS2KnYj6noZ:-O5sECA65bIRtHl6bQQl:budpb8s) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/papyrus_rpc/src/v0_6/transaction.rs#L172)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

WDYM?
Should I panic in the case of `ValidResourceBounds::AllResources(_)`?
</blockquote></details>

No, you should just convert the l1_gas and l2_gas to the output struct and not use the l1_data_gas
This code is called when the user asks: "Give me all the txs of block 1,000,000". If in block 1,000,000 we have a "new style" transaction then we don't want to panic, we'll just give the data that we know how to give and drop the data we don't know how to. That was what the l2_gas A/C preparation was for, right?

In summary, just remove the TODO
___
*[`crates/papyrus_rpc/src/v0_7/transaction.rs` line 190 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5sEof16C4LGAz8w_-D:-O5sEof16C4LGAz8w_-E:b8qx8l4) ([raw file](https://github.com/starkware-libs/sequencer/blob/78c8a8215912590d346da58cc4a699b8efc4fa00/crates/papyrus_rpc/src/v0_7/transaction.rs#L190)):*
> ```XML
>                 Self { l1_gas, l2_gas: ResourceBounds::default() }
>             }
>             // TODO(Nimrod): Don't allow this conversion.
> ```

Same as before, remove this TODO
___
*[`crates/starknet_api/src/transaction.rs` line 990 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZ1yo9IqD8f4zyTCZ:-O5sFUe2AK5yW2eIyL09:blbtzaf) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_api/src/transaction.rs#L990)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

backwards compatibility
</blockquote></details>

I think you can derive Serialize with serde(untagged) and the result will be the same. Only in deserialization you are doing something unique
___
*[`crates/starknet_api/src/transaction.rs` line 1001 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5mF4ee1Wyfp2WAX2Zo:-O5sCgUK0X4sVNy-7f0G:b-abfusa) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f0a3266cb0d7aa83ba37489b10a7a9d8cb94193/crates/starknet_api/src/transaction.rs#L1001)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Your suggestion won't work..
It will always deserialize to the `AllResources` variant...
We need to check somewhere that l2 gas is zero in the first variant
</blockquote></details>

That's why I suggested adding serde(deny_unknown_fields). This way it will distinguish between the two by looking if the l1_data_gas field is present. Is that good enough or do you prefer distinguishing through l2_gas being zero specifically?
___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4jZFhW0CNHTjSRDVbI:-O5sFHJMEAsRUv8_JRec:b-e60aw4) ([raw file](https://github.com/starkware-libs/sequencer/blob/99667f85ebbd8d31a43d0410ab5757f479baf320/crates/starknet_client/src/reader/objects/transaction.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes
</blockquote></details>

Approved


<!-- Sent from Reviewable.io -->

2024-09-03 14:35 UTC, ShahakShama reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-03 15:27 UTC, dorimedini-starkware reviewed
> Reviewed 3 of 3 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware, @ShahakShama, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-04 05:49 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508#-:-O5v_5-72DFcWnHE85B_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-04 05:52 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 567 at r26](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5v_l8O6vznu271CjMq:-O5v_l8O6vznu271CjMr:bizo99o) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6d0bb9ced49e689916999c2b4dcc26d1f772148/crates/papyrus_protobuf/src/converters/transaction.rs#L567)):*
> ```XML
>         };
>         let Some(l1_data_gas) = value.l1_data_gas else {
>             return Err(ProtobufConversionError::MissingField {
> ```

Don't return an error here. Use unwrap_or_default and add a TODO to assert this is not None once we remove support for 0.13.2


<!-- Sent from Reviewable.io -->

2024-09-04 06:38 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 567 at r26](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O5v_l8O6vznu271CjMq:-O5vkOP48Y1HxBYI4LCV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6d0bb9ced49e689916999c2b4dcc26d1f772148/crates/papyrus_protobuf/src/converters/transaction.rs#L567)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Don't return an error here. Use unwrap_or_default and add a TODO to assert this is not None once we remove support for 0.13.2
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 08:36 UTC, ShahakShama reviewed
> Reviewed 1 of 2 files at r27.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 42 of 44 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-04 08:48 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508#-:-O5wD4Nt0HXSIV73WTTT:bnfp4nl)* status: 42 of 44 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-04 08:53 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 42 of 44 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/transaction.rs` line 652 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/508#-O4tMJIc4ld96-zptE3S:-O5wEIAj8SosCF5ZkqST:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/054bcefab4aae19d266af7b867b6f384247016e1/crates/papyrus_protobuf/src/converters/transaction.rs#L652)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Yes, but you need to add the new fields at the end of the message so that it can work with nodes that didn't do this upgrade (Juno/Pathfinder)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 12:55 UTC, nimrod-starkware reviewed
> Dismissed @dorimedini-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 42 of 44 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-04 13:00 UTC, nimrod-starkware reviewed
> Reviewed 1 of 1 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: 43 of 44 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-04 13:01 UTC, nimrod-starkware reviewed
> Reviewed 1 of 2 files at r27.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/508)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-09-04 13:02 UTC, merged