refactor: use snapi class info in process declare tx
starkware-libs/sequencer pull request #516
Opened 2024-08-19 13:19 UTC by ArniStarkware

2024-08-19 13:19 UTC, ArniStarkware commented
* **#520** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/520?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#519** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/518?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/517?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#516** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/516?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-21 07:00 UTC, dafnamatsry requested changes
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/516)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @ayeletstarkware, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/compilation_test.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/516#-O4nhEk3DdHMTw6XriEK:-O4nhEk441tzEDTfSti6:bfg7udq) ([raw file](https://github.com/starkware-libs/sequencer/blob/10fc2e94db29f708f908c4178b431e0e94488fd1/crates/gateway/src/compilation_test.rs#L105)):*
> ```XML
> 
>     let class_info = gateway_compiler.process_declare_tx(&declare_tx).unwrap();
>     assert_eq!(class_info.sierra_program_length, sierra_program_length);
> ```

Please add also an assertion for the `casm_contract_class`.


<!-- Sent from Reviewable.io -->

2024-08-21 10:19 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/516)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/compilation_test.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/516#-O4nhEk3DdHMTw6XriEK:-O4oRQi8C1Oz_rKCeCWZ:b-phzzuo) ([raw file](https://github.com/starkware-libs/sequencer/blob/10fc2e94db29f708f908c4178b431e0e94488fd1/crates/gateway/src/compilation_test.rs#L105)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add also an assertion for the `casm_contract_class`.
</blockquote></details>

Done.
This is enough - it hard to compare the entire contract class is as expected. It is enough to see the result casm contract class has the expected hash.


<!-- Sent from Reviewable.io -->

2024-08-25 10:23 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/516#-:-O582wDs104rYp9gycqG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @MohammadNassar1, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-08-25 11:37 UTC, merged