refactor: create executable tx in the gateway process_tx
starkware-libs/sequencer pull request #517
Opened 2024-08-19 13:19 UTC by ArniStarkware

2024-08-19 13:19 UTC, ArniStarkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/517?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#520** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/520?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#519** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/518?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/517?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#516** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/516?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-19 13:26 UTC, ArniStarkware commented on crates/gateway/src/gateway.rs
> +                error!("Failed to convert class info: {}", e);
error!("Failed to convert Starknet API ClassInfo to Blockifier ClassInfo: {:?}", e);

2024-08-19 13:28 UTC, ArniStarkware commented
*[`crates/gateway/src/gateway.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/517#gh-1721787527:-O4eoJKh5Brf0HiKSJSJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/528f847765a6264437695884c1e291b316abca4f/crates/gateway/src/gateway.rs#L139)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

 error!("Failed to convert Starknet API ClassInfo to Blockifier ClassInfo: {:?}", e);
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-21 08:31 UTC, dafnamatsry requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 135 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4o2dTg0-wuxpABC4Uo:-O4o2dTg0-wuxpABC4Up:b-68zyo8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/gateway.rs#L135)):*
> ```XML
>         &tx,
>         &gateway_compiler,
>         &stateful_tx_validator.config.chain_info.chain_id,
> ```

Can you add a TODO to move the chain ID config out to the GW config?



_Code quote:_
```XML
&stateful_tx_validator.config.chain_info.chain_id,
```
___
*[`crates/gateway/src/utils.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4nyzloCOjN6NHLZscO:-O4nyzloCOjN6NHLZscP:b8uf344) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L35)):*
> ```XML
> use crate::errors::{GatewaySpecError, StatefulTransactionValidatorResult};
> 
> pub fn external_tx_to_executable_tx(
> ```

Let's move all this code to SNAPI?
___
*[`crates/gateway/src/utils.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4o--5D04BB-v5wTOg3:-O4o--5D04BB-v5wTOg4:b-aslnyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L35)):*
> ```XML
> use crate::errors::{GatewaySpecError, StatefulTransactionValidatorResult};
> 
> pub fn external_tx_to_executable_tx(
> ```

Here and everywhere else.



_Suggestion:_
```XML
rpc_tx_to_executable_tx
```
___
*[`crates/gateway/src/utils.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4nxoK1-iL_zWWMz3lT:-O4nxoK1-iL_zWWMz3lU:b-762pwr) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L58)):*
> ```XML
> fn external_declare_tx_to_executable_tx(
>     external_tx: &RpcDeclareTransaction,
>     gateway_compiler: &GatewayCompiler,
> ```

I think this function should get the compiled `class_info` as an argument.
Convert functions shouldn't hide heavy stuff like compilation.



_Code quote:_
```XML
gateway_compiler: &GatewayCompiler,
```
___
*[`crates/gateway/src/utils.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4o-mO3-823EqoEqZfc:-O4o-mO3-823EqoEqZfd:by0hisq) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L62)):*
> ```XML
> ) -> Result<ExecutableDeclareTransaction, GatewaySpecError> {
>     let class_info = gateway_compiler.process_declare_tx(external_tx)?;
>     let RpcDeclareTransaction::V3(tx) = external_tx;
> ```

Just to make sure: if we add another version, i.e. `RpcDecalareTransaction::V4`, this code won't compile right?



_Code quote:_
```XML
let RpcDeclareTransaction::V3(tx) = external_tx;
```
___
*[`crates/gateway/src/utils.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4o0tn1BDFTJMUhEx8m:-O4o0tn1BDFTJMUhEx8n:blbam68) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L65)):*
> ```XML
>     let declare_tx = DeclareTransaction::V3(DeclareTransactionV3 {
>         class_hash: ClassHash::default(), /* FIXME(yael 15/4/24): call the starknet-api
>                                            * function once ready */
> ```

Is it ready?



_Code quote:_
```XML
        class_hash: ClassHash::default(), /* FIXME(yael 15/4/24): call the starknet-api
                                           * function once ready */
```


<!-- Sent from Reviewable.io -->

2024-08-21 08:33 UTC, dafnamatsry reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 135 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4o2dTg0-wuxpABC4Uo:-O4o3IqC0eHra_hVNMsF:b-44lvsb) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/gateway.rs#L135)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you add a TODO to move the chain ID config out to the GW config?
</blockquote></details>

Just noticed you added it in a following PR :)


<!-- Sent from Reviewable.io -->

2024-08-21 10:20 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4o--5D04BB-v5wTOg3:-O4o7p3Z6j0Fpa04pZdI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L35)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Here and everywhere else.
</blockquote></details>

Done.
___
*[`crates/gateway/src/utils.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4o-mO3-823EqoEqZfc:-O4o7yZk6NanABqDuEiw:bo6apac) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L62)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Just to make sure: if we add another version, i.e. `RpcDecalareTransaction::V4`, this code won't compile right?
</blockquote></details>

Indeed.
___
*[`crates/gateway/src/utils.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4o0tn1BDFTJMUhEx8m:-O4o8Ck17J8Mh-3-lrX_:b-iwvflo) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L65)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Is it ready?
</blockquote></details>

I looked for it. Seems like it is not ready.
In the current flow, it is computed by the pythonic gateway.


<!-- Sent from Reviewable.io -->

2024-08-22 15:56 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4nyzloCOjN6NHLZscO:-O4u_3IF0-U_PGvAYNKD:b-3tzltv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L35)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Let's move all this code to SNAPI?
</blockquote></details>

Done.
I like that in this version of the code (`r4`), unlike the next version of the code (`r5`), there is no: `Option<ClassInfo>` and no `expect`.
___
*[`crates/gateway/src/utils.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4nxoK1-iL_zWWMz3lT:-O4u_Z2ED3Hodbbot2a2:bm7yzvb) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L58)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think this function should get the compiled `class_info` as an argument.
Convert functions shouldn't hide heavy stuff like compilation.
</blockquote></details>

Done.
See comment in `snapi`.


<!-- Sent from Reviewable.io -->

2024-08-25 11:01 UTC, dafnamatsry requested changes
> Reviewed 1 of 4 files at r4, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4nyzloCOjN6NHLZscO:-O587zPD--SOhgO13C6W:brc38cx) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L35)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
I like that in this version of the code (`r4`), unlike the next version of the code (`r5`), there is no: `Option<ClassInfo>` and no `expect`.
</blockquote></details>

I understand your point, but still to me it hides a main expensive computation that happens here during the conversion.

I have a suggestion to consider, tell me what you think:
you can add an assertion in the SANPI rpc_tx_to_executable_tx for declare txs, that the class hash matches. i.e. call `validate_compiled_class_hash()`.
___
*[`crates/gateway/src/utils.rs` line 34 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O585KcG8Xc4fepUM5Xi:-O585KcHCAKoueLHws0k:b-li6anh) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e92b981f3d0884c9f702bf25801a61635bed729/crates/gateway/src/utils.rs#L34)):*
> ```XML
>     gateway_compiler: &GatewayCompiler,
>     chain_id: &ChainId,
> ) -> Result<ExecutableTransaction, GatewaySpecError> {
> ```

Still, let's move the compilation outside to the main flow of the GW (and delete this function).
Whenever someone will read `rpc_tx_to_executable_tx`, it won't be clear that a compilation is happening here.



_Code quote:_
```XML
pub fn rpc_tx_to_executable_tx(
    rpc_tx: &RpcTransaction,
    gateway_compiler: &GatewayCompiler,
    chain_id: &ChainId,
) -> Result<ExecutableTransaction, GatewaySpecError> {
```


<!-- Sent from Reviewable.io -->

2024-08-26 14:50 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O4nyzloCOjN6NHLZscO:-O5E3zgl1GMyGV0p3zHq:b-mby3ek) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056be03c65bd5092511a7aa0a81b8ad8a24e3ae/crates/gateway/src/utils.rs#L35)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I understand your point, but still to me it hides a main expensive computation that happens here during the conversion.

I have a suggestion to consider, tell me what you think:
you can add an assertion in the SANPI rpc_tx_to_executable_tx for declare txs, that the class hash matches. i.e. call `validate_compiled_class_hash()`.
</blockquote></details>

After consulting with @yair-starkware, I partially reverted my change. He agrees that we do not need an `Optional` here. Per his suggestion, the conversion of rpc-declare to executable-declare is happening in the gateway compiler now (this is very similar to the current flow, anyway).

He also suggested that the conversion rpc-to-executable will be a method of the gateway - but sadly - `process_tx` is not a method of the gateway.




Regarding your suggestion about moving `validate_compiled_class_hash`, I am in favor of it (in any constellation of the code). It is practically implemented by this version of the code.
___
*[`crates/gateway/src/utils.rs` line 34 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O585KcG8Xc4fepUM5Xi:-O5E67DqECE3DV0A-8RR:bw6srot) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e92b981f3d0884c9f702bf25801a61635bed729/crates/gateway/src/utils.rs#L34)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Still, let's move the compilation outside to the main flow of the GW (and delete this function).
Whenever someone will read `rpc_tx_to_executable_tx`, it won't be clear that a compilation is happening here.
</blockquote></details>

Is this something a good name can solve? 
(Not that the name suggested here is "good").

I agree - it is indeed a heavy step of the program. The thing is this tells the story correctly. This step is an atomic step that requires compilation.


<!-- Sent from Reviewable.io -->

2024-09-03 08:24 UTC, dafnamatsry requested changes
> Reviewed 6 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 6 of 8 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 33 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qqsUeD1a79HxILdOq:-O5qqsUeD1a79HxILdOr:b-k3k0xu) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/compilation.rs#L33)):*
> ```XML
>     }
> 
>     // TODO(Arni): Squash this function into `process_declare_tx`.
> ```

You can do it as part of this PR.
___
*[`crates/gateway/src/compilation.rs` line 60 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qrJ0A2wcwopyS7N5n:-O5qrJ0A2wcwopyS7N5o:b-gttt05) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/compilation.rs#L60)):*
> ```XML
>         rpc_tx: RpcDeclareTransaction,
>         chain_id: &ChainId,
>     ) -> GatewayResult<DeclareTransaction> {
> ```

Why did you change the return value?

The role of the compiler is to compile and shouldn't handle any other unrelated declare tx fields.
Please move the conversion logic to `compile_to_casm_and_convert_rpc_to_executable_tx`.



_Code quote:_
```XML
GatewayResult<DeclareTransaction> 
```
___
*[`crates/gateway/src/gateway.rs` line 158 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qu2Fp-FICFe8ROL1G:-O5qu2Fp-FICFe8ROL1H:b-oeqcat) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/gateway.rs#L158)):*
> ```XML
>     // TODO(Arni): Add the Sierra and the Casm to the mempool input.
>     Ok(MempoolInput {
>         tx: Transaction::new_from_rpc_tx(
> ```

Is this function going to be deleted?



_Code quote:_
```XML
Transaction::new_from_rpc_tx(
```
___
*[`crates/gateway/src/utils.rs` line 41 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qourQBIUvaG8l0q50:-O5qourR-u8SL5F83CXv:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/utils.rs#L41)):*
> ```XML
>     gateway_compiler: &GatewayCompiler,
>     chain_id: &ChainId,
> ) -> Result<ExecutableTransaction, GatewaySpecError> {
> ```





_Suggestion:_
```XML
GatewayResult<ExecutableTransaction> 
```
___
*[`crates/gateway/src/utils.rs` line 44 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qpGwV4dF4qYuDPns-:-O5qpGwV4dF4qYuDPns0:b63qtgm) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/utils.rs#L44)):*
> ```XML
>     Ok(match rpc_tx {
>         RpcTransaction::Declare(rpc_declare_tx) => ExecutableTransaction::Declare(
>             gateway_compiler.process_declare_tx(rpc_declare_tx, chain_id).map_err(|error| {
> ```

No need for the `map_err` right?

Note that you are mapping a legitimate `CompilationFailed` and `ompiledClassHashMismatch` to `UnexpectedError`.
Please add a test to `gateway_test` to make sure we return those errors.



_Code quote:_
```XML
.map_err(|error| {
```
___
*[`crates/gateway/src/utils.rs` line 79 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5queQM96WJ-TjCmEJp:-O5queQM96WJ-TjCmEJq:bh5v7t7) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/utils.rs#L79)):*
> ```XML
> }
> 
> // TODO(Arni): Remove this function. Replace with a function that take ownership of RpcTransaction.
> ```

What do you mean?
We won't need conversion from rpc to account tx IIUC.



_Code quote:_
```XML
Replace with a function that take ownership of RpcTransaction.
```
___
*[`crates/gateway/src/gateway_test.rs` line 104 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qva4Z79c09qKsOLGc:-O5qva4Z79c09qKsOLGd:bg3mtps) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/gateway_test.rs#L104)):*
> ```XML
>     };
> 
>     let account_tx = rpc_tx_to_account_tx(
> ```

Can we calculate the hash without going through an `AccountTransaction`?

Maybe you can use `rpc_tx.into().calculate_transaction_hash()`.



_Code quote:_
```XML
let account_tx = rpc_tx_to_account_tx(
```


<!-- Sent from Reviewable.io -->

2024-09-03 08:27 UTC, dafnamatsry reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 34 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O585KcG8Xc4fepUM5Xi:-O5qzDlRE7A9rBhB12LC:b4bb6o7) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e92b981f3d0884c9f702bf25801a61635bed729/crates/gateway/src/utils.rs#L34)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is this something a good name can solve? 
(Not that the name suggested here is "good").

I agree - it is indeed a heavy step of the program. The thing is this tells the story correctly. This step is an atomic step that requires compilation.
</blockquote></details>

I still prefer decoupling the 2 steps (where one depends on the other), but I'm also ok with the rename.


<!-- Sent from Reviewable.io -->

2024-09-03 08:36 UTC, dafnamatsry requested changes
> Reviewed 1 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 6 of 8 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 37 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5r0m9x1ItYEFOIZlwO:-O5r0m9y9vcbObJvjpbk:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/utils.rs#L37)):*
> ```XML
> /// Note, that for declare transaction this step is heavy, as it requires compilation of Sierra to
> /// executable contract class.
> pub fn compile_to_casm_and_convert_rpc_to_executable_tx(
> ```





_Suggestion:_
```XML
compile_contract_and_build_executable_tx
```


<!-- Sent from Reviewable.io -->

2024-09-03 11:03 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 1 of 8 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 158 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qu2Fp-FICFe8ROL1G:-O5r2Os84a2mDzw2EtF4:byjbzdq) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/gateway.rs#L158)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Is this function going to be deleted?
</blockquote></details>

yes, it is. There is a TODO on it.
___
*[`crates/gateway/src/utils.rs` line 37 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5r0m9x1ItYEFOIZlwO:-O5rEtVZCfUK4itapEYc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/utils.rs#L37)):*
> ```XML
> /// Note, that for declare transaction this step is heavy, as it requires compilation of Sierra to
> /// executable contract class.
> pub fn compile_to_casm_and_convert_rpc_to_executable_tx(
> ```

Done.
___
*[`crates/gateway/src/utils.rs` line 41 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qourQBIUvaG8l0q50:-O5rFNpG9VC14POAH9Dx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/utils.rs#L41)):*
> ```XML
>     gateway_compiler: &GatewayCompiler,
>     chain_id: &ChainId,
> ) -> Result<ExecutableTransaction, GatewaySpecError> {
> ```

Done.
___
*[`crates/gateway/src/utils.rs` line 79 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5queQM96WJ-TjCmEJp:-O5rKq8M4s_OeE_cNQic:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/utils.rs#L79)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What do you mean?
We won't need conversion from rpc to account tx IIUC.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-05 08:54 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 1 of 9 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 33 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qqsUeD1a79HxILdOq:-O60LyKbBSAp3FMx77Y4:b-cxchxo) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/compilation.rs#L33)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

You can do it as part of this PR.
</blockquote></details>

No longer relevant.
___
*[`crates/gateway/src/compilation.rs` line 60 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qrJ0A2wcwopyS7N5n:-O60M0-O5k_6H7KDAOUA:b-xnize4) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/compilation.rs#L60)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why did you change the return value?

The role of the compiler is to compile and shouldn't handle any other unrelated declare tx fields.
Please move the conversion logic to `compile_to_casm_and_convert_rpc_to_executable_tx`.
</blockquote></details>

no longer relevant.
___
*[`crates/gateway/src/gateway_test.rs` line 104 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qva4Z79c09qKsOLGc:-O5xNPyMCekp1CuWYXj0:bmnyorq) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/gateway_test.rs#L104)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can we calculate the hash without going through an `AccountTransaction`?

Maybe you can use `rpc_tx.into().calculate_transaction_hash()`.
</blockquote></details>

This function will be deleted. This is out of the scope of this PR.
___
*[`crates/gateway/src/utils.rs` line 44 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O5qpGwV4dF4qYuDPns-:-O604TfAD84SB90uY6hu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a37508877d1a26a2519cf6a2b6481c765e9d6b6/crates/gateway/src/utils.rs#L44)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

No need for the `map_err` right?

Note that you are mapping a legitimate `CompilationFailed` and `ompiledClassHashMismatch` to `UnexpectedError`.
Please add a test to `gateway_test` to make sure we return those errors.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-08 07:07 UTC, dafnamatsry requested changes
> Reviewed 7 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 36 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O60PHY17wnNM_81nq84:-O60PHY25vBrvDXmFrYS:b-v6tfsq) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef6ffeb1f10924c5c4ccdb21d8ebfcd8dd714e2a/crates/gateway/src/compilation.rs#L36)):*
> ```XML
>     }
> 
>     // TODO(Arni): Squash this function into `process_declare_tx`.
> ```

Remove :)



_Code quote:_
```XML
    // TODO(Arni): Squash this function into `process_declare_tx`.
```
___
*[`crates/gateway/src/compilation_test.rs` line 70 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O60Qxyj2y92sR-M5Skd:-O60Qxyj2y92sR-M5Ske:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef6ffeb1f10924c5c4ccdb21d8ebfcd8dd714e2a/crates/gateway/src/compilation_test.rs#L70)):*
> ```XML
> 
> #[rstest]
> fn test_class_info_from_declare_tx_tx_success(
> ```





_Suggestion:_
```XML
test_process_declare_tx_success
```
___
*[`crates/gateway/src/utils.rs` line 39 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O6FPa0GDxbFcDdAvd7x:-O6FPa0GDxbFcDdAvd7y:b2qioja) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef6ffeb1f10924c5c4ccdb21d8ebfcd8dd714e2a/crates/gateway/src/utils.rs#L39)):*
> ```XML
> /// executable contract class.
> pub fn compile_contract_and_build_executable_tx(
>     rpc_tx: RpcTransaction,
> ```

and then you won't need the clone in the gateway...

In general, I think in most cases we only want to pass references as function arguments (unless you want to enforce that an object can't be used after the function call).



_Suggestion:_
```XML
rpc_tx: &RpcTransaction,
```
___
*[`crates/gateway/src/utils.rs` line 85 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O6FPk2E3V8itjlgLjNO:-O6FPk2E3V8itjlgLjNP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef6ffeb1f10924c5c4ccdb21d8ebfcd8dd714e2a/crates/gateway/src/utils.rs#L85)):*
> ```XML
> 
> fn compile_contract_and_build_executable_declare_tx(
>     rpc_tx: RpcDeclareTransaction,
> ```





_Suggestion:_
```XML
rpc_tx: &RpcDeclareTransaction,
```


<!-- Sent from Reviewable.io -->

2024-09-08 07:41 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 36 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O60PHY17wnNM_81nq84:-O6FVez_EaR-SbRwBG4v:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef6ffeb1f10924c5c4ccdb21d8ebfcd8dd714e2a/crates/gateway/src/compilation.rs#L36)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Remove :)
</blockquote></details>

Done.
___
*[`crates/gateway/src/compilation_test.rs` line 70 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O60Qxyj2y92sR-M5Skd:-O6FVroLDTwcb5nvf5iB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef6ffeb1f10924c5c4ccdb21d8ebfcd8dd714e2a/crates/gateway/src/compilation_test.rs#L70)):*
> ```XML
> 
> #[rstest]
> fn test_class_info_from_declare_tx_tx_success(
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-08 08:25 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517#-:-O6FjBWxEbJkg4DCzrDb:bnfp4nl)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @ayeletstarkware, @MohammadNassar1, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-09-08 08:28 UTC, ArniStarkware commented
*[`crates/gateway/src/utils.rs` line 39 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/517#-O6FPa0GDxbFcDdAvd7x:-O6FWC8oA6Y_h-YeSuet:b79zy8f) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef6ffeb1f10924c5c4ccdb21d8ebfcd8dd714e2a/crates/gateway/src/utils.rs#L39)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

and then you won't need the clone in the gateway...

In general, I think in most cases we only want to pass references as function arguments (unless you want to enforce that an object can't be used after the function call).
</blockquote></details>

Discussed on DMs. Ignored.
The ownership-taking is by design.


<!-- Sent from Reviewable.io -->

2024-09-08 08:29 UTC, ArniStarkware reviewed
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/517)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-09-08 08:31 UTC, ArniStarkware commented
### Merge activity

* **Sep 8, 4:31 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/517).

2024-09-08 08:45 UTC, merged