refactor: remove most fields from statful validator output
starkware-libs/sequencer pull request #521
Opened 2024-08-19 13:19 UTC by ArniStarkware

The struct `ValidateInfo` holds all the information relevant to the rest of the transaction's lifecycle from the run of the validate. Most of its members are no longer needed as they can be obtained from the `ExecutableTransaction`.

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/521)

2024-08-19 13:19 UTC, ArniStarkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/521?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#521** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/521?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#519** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#520](https://github.com/starkware-libs/sequencer/pull/520) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/520?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/518?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/517?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#516** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/516?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-19 14:56 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O4f7-LT2bTIuGS-ws2N:-O4f7-LT2bTIuGS-ws2O:b-68k6ww) ([raw file](https://github.com/starkware-libs/sequencer/blob/bac9642ae6943ff1f8555756068428846ff92a42/crates/gateway/src/gateway.rs#L139)):*
> ```XML
>     let validator = stateful_tx_validator.instantiate_validator(state_reader_factory)?;
>     // TODO(Yael 31/7/24): refactor after IntrnalTransaction is ready, delete validate_info and
>     // compute all the info outside of run_validate.
> ```

This TODO is still relevant.



_Code quote:_
```XML
    // TODO(Yael 31/7/24): refactor after IntrnalTransaction is ready, delete validate_info and
    // compute all the info outside of run_validate.
```
___
*[`crates/gateway/src/gateway.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O4f7ABk3w3kShNHMBWS:-O4f7ABk3w3kShNHMBWT:buhifom) ([raw file](https://github.com/starkware-libs/sequencer/blob/bac9642ae6943ff1f8555756068428846ff92a42/crates/gateway/src/gateway.rs#L147)):*
> ```XML
>         account: Account {
>             sender_address: executable_tx.contract_address(),
>             state: AccountState { nonce: validate_info.account_nonce },
> ```

This member is different from `executable_tx.nonce()`.
One is the nonce of the transaction, while the other is the account's nonce.



_Code quote:_
```XML
 validate_info.account_nonce
```


<!-- Sent from Reviewable.io -->

2024-09-03 08:54 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521#-:-O5r4sjV0wktzNLbbUYq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @MohammadNassar1, @Yael-Starkware, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-09-04 12:04 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O5w_j0f-sUgu5MTcSuM:-O5wquBJ6fp3-ZfEzbIn:b-i9l0k3) ([raw file](https://github.com/starkware-libs/sequencer/blob/c06fea07b968e767c670b412e00ae181eb735f3f/crates/starknet_api/src/executable_transaction.rs#L156)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We don't need it anymore here?
</blockquote></details>

Per @yair-starkware 's suggestion - we don't want to have the `create` method also run the validate. This is healthier (for testing etc) to not have operations other than the creation in the `create` method.

It is discussed in #686.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 161 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O5wZpEj9rnbY8xP2Xlt:-O5ws_LC88g_jwYNigtH:b-xkq7o1) ([raw file](https://github.com/starkware-libs/sequencer/blob/07d6a597323a3bfdc2d986bba2a2026945c3bca3/crates/starknet_api/src/executable_transaction.rs#L161)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Other versions don't have compiled class hash?
If they do, but we just don't want to support it, so let's implement it only in the V3 struct.
</blockquote></details>

It is hard to implement only for V3 struct. The wrapping does not support it - i.e. the structure of the struct `DeclareTransaction`:
```
pub struct DeclareTransaction {
    pub tx: crate::transaction::DeclareTransaction,
    pub tx_hash: TransactionHash,
    pub class_info: ClassInfo,
}
```


Will be addressed in #686.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 168 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O5w_WOZ7SfhnACKlVsd:-O5wuqPC5TSAKeLY1ReA:beud4zb) ([raw file](https://github.com/starkware-libs/sequencer/blob/07d6a597323a3bfdc2d986bba2a2026945c3bca3/crates/starknet_api/src/executable_transaction.rs#L168)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please use match case, so the compiler will catch this when a new version is added.
</blockquote></details>

Done.
Also covered the V2 case - but let us not document it - this is not the intended behavior.


<!-- Sent from Reviewable.io -->

2024-09-08 07:29 UTC, dafnamatsry approved these changes
> Reviewed 1 of 4 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @MohammadNassar1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 168 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O5w_WOZ7SfhnACKlVsd:-O6FXDk33AsM5u74YIop:b-gt2kov) ([raw file](https://github.com/starkware-libs/sequencer/blob/07d6a597323a3bfdc2d986bba2a2026945c3bca3/crates/starknet_api/src/executable_transaction.rs#L168)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
Also covered the V2 case - but let us not document it - this is not the intended behavior.
</blockquote></details>

WDYM not the intended behaviour?


<!-- Sent from Reviewable.io -->

2024-09-08 13:28 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 168 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O5w_WOZ7SfhnACKlVsd:-O6Go1Fn6MX_LgOpsUN_:bxp51u9) ([raw file](https://github.com/starkware-libs/sequencer/blob/07d6a597323a3bfdc2d986bba2a2026945c3bca3/crates/starknet_api/src/executable_transaction.rs#L168)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

WDYM not the intended behaviour?
</blockquote></details>

Let me state a different fact.
In the current flow, the method `validate_compiled_class_hash` will never be used on a V2 declare tx. There is no problem, though. If, by chance, this method is called on a V2 contract, it will work as expected. 


<!-- Sent from Reviewable.io -->

2024-09-09 07:15 UTC, dafnamatsry approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @MohammadNassar1, @Yael-Starkware, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-09-09 16:33 UTC, ArniStarkware commented
*[`crates/gateway/src/stateful_transaction_validator.rs` line 148 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O6McW_8A90ofs7jGTGZ:-O6McW_8A90ofs7jGTG_:ba3dfmt) ([raw file](https://github.com/starkware-libs/sequencer/blob/f7d9aa2c8d2c0b4b9c4a4f7a5464ecff7ba63b34/crates/gateway/src/stateful_transaction_validator.rs#L148)):*
> ```XML
> }
> 
> // TODO(Arni): Remove irrelevant fields.
> ```

Remove.



_Code quote:_
```XML
// TODO(Arni): Remove irrelevant fields.
```


<!-- Sent from Reviewable.io -->

2024-09-15 08:46 UTC, yair-starkware requested changes
> Reviewed 1 of 3 files at r6, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 79 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O6oqm021cYj7Ngi_oI2:-O6oqm021cYj7Ngi_oI3:b-jdpu6t) ([raw file](https://github.com/starkware-libs/sequencer/blob/2682ed435e6361c55580353818e9f0924ce3b7b5/crates/gateway/src/stateful_transaction_validator.rs#L79)):*
> ```XML
>             error!("Failed to get nonce for sender address {}: {}", sender_address, e);
>             GatewaySpecError::UnexpectedError { data: "Internal server error.".to_owned() }
>         })?;
> ```

Talked f2f, get this value outside the function



_Code quote:_
```XML
        let account_nonce = validator.get_nonce(sender_address).map_err(|e| {
            error!("Failed to get nonce for sender address {}: {}", sender_address, e);
            GatewaySpecError::UnexpectedError { data: "Internal server error.".to_owned() }
        })?;
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 153 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O6oqupMA2tcqhxE5sdZ:-O6oqupMA2tcqhxE5sd_:brw0tfk) ([raw file](https://github.com/starkware-libs/sequencer/blob/2682ed435e6361c55580353818e9f0924ce3b7b5/crates/gateway/src/stateful_transaction_validator.rs#L153)):*
> ```XML
> pub struct ValidateInfo {
>     pub account_nonce: Nonce,
> }
> ```

Talked f2f, delete this struct



_Code quote:_
```XML
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ValidateInfo {
    pub account_nonce: Nonce,
}
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 53 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O6oolwP3pfCVjG0Bn2n:-O6oolwP3pfCVjG0Bn2o:b-yatn4) ([raw file](https://github.com/starkware-libs/sequencer/blob/2682ed435e6361c55580353818e9f0924ce3b7b5/crates/starknet_api/src/executable_transaction.rs#L53)):*
> ```XML
> 
> impl Transaction {
>     /// This parameter is somethimes called `sender_address`.
> ```

Consider adding another function `sender_address` which calls this function



_Code quote:_
```XML
/// This parameter is somethimes called `sender_address`.
```


<!-- Sent from Reviewable.io -->

2024-09-16 15:27 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 79 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O6oqm021cYj7Ngi_oI2:-O6vQ0sg5Pf6WMT-wqVs:b-17ap1i) ([raw file](https://github.com/starkware-libs/sequencer/blob/2682ed435e6361c55580353818e9f0924ce3b7b5/crates/gateway/src/stateful_transaction_validator.rs#L79)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Talked f2f, get this value outside the function
</blockquote></details>

Done in PR in upstack: see: #822
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 153 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O6oqupMA2tcqhxE5sdZ:-O6vQ5BmDJe2dkssP6lV:b-17ap1i) ([raw file](https://github.com/starkware-libs/sequencer/blob/2682ed435e6361c55580353818e9f0924ce3b7b5/crates/gateway/src/stateful_transaction_validator.rs#L153)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Talked f2f, delete this struct
</blockquote></details>

Done in PR in upstack: see: #822
___
*[`crates/starknet_api/src/executable_transaction.rs` line 53 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/521#-O6oolwP3pfCVjG0Bn2n:-O6vQ_5p-g0mqdaqZqs7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2682ed435e6361c55580353818e9f0924ce3b7b5/crates/starknet_api/src/executable_transaction.rs#L53)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider adding another function `sender_address` which calls this function
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-18 06:49 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521#-:-O72t2nw3Po-4eJkrrje:bnfp4nl)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @MohammadNassar1, @Yael-Starkware, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-09-19 06:57 UTC, dafnamatsry reviewed
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @MohammadNassar1, @Yael-Starkware, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-09-22 06:57 UTC, yair-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521#-:-O7NWGfv7Ypd6LmyJL65:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-22 07:03 UTC, ArniStarkware reviewed
> Reviewed 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/521)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-22 07:05 UTC, ArniStarkware commented
### Merge activity

* **Sep 22, 3:05 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/521).

2024-09-22 07:05 UTC, merged