feat(mempool): implement account nonces in add_tx and commit_block
starkware-libs/sequencer pull request #534
Opened 2024-08-20 11:46 UTC by ayeletstarkware

2024-08-20 13:04 UTC, elintul requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jsQ1Z-I_YpyCCm5nK:-O4jsQ1Z-I_YpyCCm5nL:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool.rs#L25)):*
> ```XML
>     // Represents the current state of the mempool during block creation.
>     mempool_state: HashMap<ContractAddress, AccountState>,
>     // Represents the most recently received account nonces.
> ```





_Suggestion:_
```XML
// The most recent account nonces received (might change right after), for all account in the pool.
```
___
*[`crates/mempool/src/mempool.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jcZy12LkUV08SYr63:-O4jcZy12LkUV08SYr64:b-ofdsys) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool.rs#L75)):*
> ```XML
>     pub fn add_tx(&mut self, input: MempoolInput) -> MempoolResult<()> {
>         self.validate_input(&input)?;
>         self.account_nonces.insert(input.account.sender_address, input.account.state.nonce);
> ```

Please note this: a classic unpacking pattern.



_Code quote:_
```XML
input.account.sender_address, input.account.state.nonce
```
___
*[`crates/mempool/src/mempool.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jcchkAhsk3331E8Uo:-O4jcchkAhsk3331E8Up:buw68lf) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool.rs#L75)):*
> ```XML
>     pub fn add_tx(&mut self, input: MempoolInput) -> MempoolResult<()> {
>         self.validate_input(&input)?;
>         self.account_nonces.insert(input.account.sender_address, input.account.state.nonce);
> ```

Is this the best practice for `HashMap` to override values?
A (slightly) different Q: shouldn't we ever look into the existing value?



_Code quote:_
```XML
insert
```
___
*[`crates/mempool/src/mempool_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jd8u29F9Plw6xKBcs:-O4jd8u33W9KbXaII4eC:b-v4d1dd) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L29)):*
> ```XML
>     tx_pool: Option<TransactionPool>,
>     tx_queue: Option<TransactionQueue>,
>     account_nonces: Option<HashMap<ContractAddress, Nonce>>,
> ```

Please alias.



_Code quote:_
```XML
HashMap<ContractAddress, Nonce>
```
___
*[`crates/mempool/src/mempool_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jbWLQ0skdsIUsL0pM:-O4jr5xj241nPQ-62Qm3:b-gcwqcv) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L51)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

This solution is not ideal because this line might be confusing, as it's intended to represent the full content.
</blockquote></details>

Why not add another argument? What tests use this `new`?
___
*[`crates/mempool/src/mempool_test.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jqpZ867BLxFaKz2Zz:-O4jqpZ98O1_gLXGsj4z:bf2o3yt) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L118)):*
> ```XML
>             tx_queue: tx_queue.unwrap_or_default(),
>             // TODO: Add implementation when needed.
>             mempool_state: Default::default(),
> ```

Did we decide to remove this? Please ask Mohammad.



_Code quote:_
```XML
            // TODO: Add implementation when needed.
            mempool_state: Default::default(),
```
___
*[`crates/mempool/src/mempool_test.rs` line 880 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jr_7G3Gidq15tN5tZ:-O4jr_7G3Gidq15tN5t_:b-tzkitv) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L880)):*
> ```XML
>     let nonce_after_commit = nonce_committed.try_increment().unwrap();
>     let expected_mempool = MempoolContent::with_account_nonces(vec![(address, nonce_after_commit)]);
>     expected_mempool.assert_eq_account_nonces(&mempool);
> ```

Not sure the commit is appropriately checking what you meant, since `add_tx` already updates the account nonces. What am I missing?



_Suggestion:_
```XML
    // Setup.
    let input =
        add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
    let address = input.tx.sender_address;
    let expected_mempool_content =
        MempoolContent::with_account_nonces(vec![(address, input.account.state.nonce)]);

    // Test: update through new input.
    add_tx(&mut mempool, &input);

    // Assert.
    expected_mempool.assert_eq_account_nonces(&mempool);

    // Test: update through a block.
    let committed_nonce = Nonce(felt!(0_u8));
    let state_changes = HashMap::from([(address, AccountState { nonce: committed_nonce })]);
    assert!(mempool.commit_block(state_changes).is_ok());

    // Assert.
    let next_nonce = nonce_committed.try_increment().unwrap();
    let expected_mempool_content = MempoolContent::with_account_nonces(vec![(address, next_nonce)]);
    expected_mempool_content.assert_eq_account_nonces(&mempool);
```


<!-- Sent from Reviewable.io -->

2024-08-21 09:03 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4k4DzSBPEwk9l6-Xvz:-O4o758v5Z2DBjcFyA1I:bnngdyg) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about removal?
</blockquote></details>

Good point. When should we remove an account nonce? Two options come to mind:
1.  In `commit_block`, if no new transaction is inserted into the queue.
2.  In `commit_block`, if no other transactions from the same account remain in the pool.

___
___
*[`crates/mempool/src/mempool.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jcZy12LkUV08SYr63:-O4nkUce0VM7CVag9MEV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool.rs#L75)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please note this: a classic unpacking pattern.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jcchkAhsk3331E8Uo:-O4o04mF3W70Wjhp6cwy:b-32cfhb) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool.rs#L75)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the best practice for `HashMap` to override values?
A (slightly) different Q: shouldn't we ever look into the existing value?
</blockquote></details>

There's also this solution:
`map.entry(address).and_modify(|e| *e = nonce).or_insert(nonce);`
Both `insert` and `entry` have similar complexity, but I think`insert` is simpler and more readable.
WDYT?
___
*[`crates/mempool/src/mempool_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jd8u29F9Plw6xKBcs:-O4o0tgq0700FYovFMwf:bud5y2v) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L29)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please alias.
</blockquote></details>

only in the test? or for the Mempool as well?
___
*[`crates/mempool/src/mempool_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jbWLQ0skdsIUsL0pM:-O4o5T5U4t8MPR7gi9KM:b-30rd57) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L51)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not add another argument? What tests use this `new`?
</blockquote></details>

More than 20 tests use this `new` function. 
I think it might be necessary to add the `account_nonces` argument since it represents full content, and `account nonces` is part of the mempool content now. 
What do you think about adding a partial state for both the pool and queue, so it will be used for tests that use this `new` function?
___
*[`crates/mempool/src/mempool_test.rs` line 880 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jr_7G3Gidq15tN5tZ:-O4o19dkDDeBx8AWIuHt:b-fjoo7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L880)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure the commit is appropriately checking what you meant, since `add_tx` already updates the account nonces. What am I missing?
</blockquote></details>

`add_tx` adds to account nonces the pair:
`sender: 0, account_nonce: 0`
the commit block receives 0 as an the nonce that was committed, so it updates the account nonces value to be 0+1:
`sender: 0, account_nonce: 1`
 if you'd like, we can choose a bigger committed nonce value to make it clearer


<!-- Sent from Reviewable.io -->

2024-08-21 11:34 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jqpZ867BLxFaKz2Zz:-O4ogw_o53tlLX00vFHs:b-nb9y1v) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L118)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Did we decide to remove this? Please ask Mohammad.
</blockquote></details>

The decision to retain `mempool_state` was linked to the staging area implementation. 
We decided to keep it, as it would be more efficient than performing searches within the staging area.


<!-- Sent from Reviewable.io -->

2024-08-22 12:50 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4oxW1wCmHbSHpjR2pw:-O4oxW1wCmHbSHpjR2px:b-atd5n0) ([raw file](https://github.com/starkware-libs/sequencer/blob/33eda1ade3cbdf3112741a7ae60195e5c5fe6d76/crates/mempool/src/mempool.rs#L79)):*
> ```XML
>             account: Account { sender_address, state: AccountState { nonce } }, ..
>         } = input;
>         self.account_nonces.insert(sender_address, nonce);
> ```

Can be moved to `align`?



_Code quote:_
```XML
self.account_nonces.insert(sender_address, nonce);
```
___
*[`crates/mempool/src/mempool_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jd8u29F9Plw6xKBcs:-O4oxjKxBMBMEiy56fpm:b-two0x9) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L29)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

only in the test? or for the Mempool as well?
</blockquote></details>

Mempool too, `AccountNonces`.


<!-- Sent from Reviewable.io -->

2024-08-25 12:37 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4k4DzSBPEwk9l6-Xvz:-O4t3hC9854yhkZknzUo:b-jcvn85) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Good point. When should we remove an account nonce? Two options come to mind:
1.  In `commit_block`, if no new transaction is inserted into the queue.
2.  In `commit_block`, if no other transactions from the same account remain in the pool.
</blockquote></details>

F2F: 
* removal is done in `get_txs`: if no transactions of the same account remain
* removal is done in `commit_block` and 'add_tx' if no transactions of the same account remain/ are still relevant to the committed nonce received.

___
___
*[`crates/mempool/src/mempool.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jcchkAhsk3331E8Uo:-O4t0IJQ39QDT9zssET3:bn5ykci) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool.rs#L75)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

There's also this solution:
`map.entry(address).and_modify(|e| *e = nonce).or_insert(nonce);`
Both `insert` and `entry` have similar complexity, but I think`insert` is simpler and more readable.
WDYT?
</blockquote></details>

Talked F2F and decided to use `insert`
___
*[`crates/mempool/src/mempool.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4oxW1wCmHbSHpjR2pw:-O58TjtoEwgUZLEN_319:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/33eda1ade3cbdf3112741a7ae60195e5c5fe6d76/crates/mempool/src/mempool.rs#L79)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can be moved to `align`?
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jd8u29F9Plw6xKBcs:-O4tIfDX0Vso-TXvg3k_:b-p1nw6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L29)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

only in the test? or for the Mempool as well?
</blockquote></details>

added an alias 
___
*[`crates/mempool/src/mempool_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jbWLQ0skdsIUsL0pM:-O4tIkbB6b_Neyg1q3gn:bieyd6b) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L51)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

More than 20 tests use this `new` function. 
I think it might be necessary to add the `account_nonces` argument since it represents full content, and `account nonces` is part of the mempool content now. 
What do you think about adding a partial state for both the pool and queue, so it will be used for tests that use this `new` function?
</blockquote></details>

Talked F2F and decided to add a combined partial state for both the pool and queue. #560
Updated the places that used the `new` function to now use this combined state. 
The full state now accurately represents a complete state.
___
*[`crates/mempool/src/mempool_test.rs` line 880 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O4jr_7G3Gidq15tN5tZ:-O4t20I41tW5s2pI26Uq:b-rk07x2) ([raw file](https://github.com/starkware-libs/sequencer/blob/85b387766d28f3b6072b1daf3273e33b897906a6/crates/mempool/src/mempool_test.rs#L880)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

`add_tx` adds to account nonces the pair:
`sender: 0, account_nonce: 0`
the commit block receives 0 as an the nonce that was committed, so it updates the account nonces value to be 0+1:
`sender: 0, account_nonce: 1`
 if you'd like, we can choose a bigger committed nonce value to make it clearer
</blockquote></details>

* Added a test with different cases showing that commit block nonce values override the account nonce, regardless of the previous value, as long as a transaction from the same account is still in the mempool. 
* Added tests to ensure accounts are removed or not added to the account nonces map if no relevant transactions from the same account remain, in `get_txs` and `commit_block`.


<!-- Sent from Reviewable.io -->

2024-08-25 12:39 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O58W8IqBPYGDpvUfjFV:-O58XdT0DML7BGVpm-H_:b-n8alel) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

When accout_nonce is used?
</blockquote></details>

This field will be used in the eviction flow to define the distance of a transaction from its account's current nonce.

___
___
*[`crates/mempool/src/mempool.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O58Vma88u0FLvS5-lK0:-O58XvEk5dPAItc-vhsO:b-u762kr) ([raw file](https://github.com/starkware-libs/sequencer/blob/33eda1ade3cbdf3112741a7ae60195e5c5fe6d76/crates/mempool/src/mempool.rs#L79)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Shouldn't you check if the state is new? This means a more updated state than the one currently in the mempool.
</blockquote></details>

We assume the state we receive is the most updated.


<!-- Sent from Reviewable.io -->

2024-08-25 12:44 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O58Y6lW-CLCi876w6iM:-O58Y6lW-CLCi876w6iN:b-i3c54t) ([raw file](https://github.com/starkware-libs/sequencer/blob/848a10a66b098f0512be8be9ebd9801fc62186bf/crates/mempool/src/mempool.rs#L186)):*
> ```XML
>         self.tx_pool.remove_up_to_nonce(address, nonce);
> 
>         if self.tx_pool.contains_account(address) {
> ```

This function is used in both `commit_block` and `add_tx`.  
In `add_tx`, we receive a new transaction with a nonce that is greater than or equal to the account's current nonce (though this is not checked in the mempool, and it might need to be).  
As a result, the account will always remain in the pool with the new transaction, so the `else` block is never reached.  
In `commit_block`, we might delete all transactions of the account from the pool, which would trigger the `else` block.


<!-- Sent from Reviewable.io -->

2024-08-26 08:07 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5ChlOJ-w8T8WXkc_xn:-O5ChlOJ-w8T8WXkc_xo:bw2ha8r) (no related file):*
STACK OF PRS:
1. #590 
2. #560 
3. #591 
4. #592 
5. #534 (YOU'RE HERE)

___


<!-- Sent from Reviewable.io -->

2024-08-26 15:19 UTC, MohammadNassar1 requested changes
> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O58Vma88u0FLvS5-lK0:-O5EFogz169FsUTQpf4s:b-vfe2qm) ([raw file](https://github.com/starkware-libs/sequencer/blob/33eda1ade3cbdf3112741a7ae60195e5c5fe6d76/crates/mempool/src/mempool.rs#L79)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

We assume the state we receive is the most updated.
</blockquote></details>

Is it reasonable?
Let's talk F2F.
___
*[`crates/mempool/src/mempool.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5EE08T7pJqDn0Hwns-:-O5EE08U2nbK_rMP75XN:bokstk9) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6394e37298c3c8f2a1815c83d1fb23d6529b0f7/crates/mempool/src/mempool.rs#L63)):*
> ```XML
>             let tx = self.tx_pool.remove(tx_ref.tx_hash)?;
>             if !self.tx_pool.contains_account(tx.contract_address()) {
>                 self.account_nonces.remove(&tx.contract_address());
> ```

If you still have the address, you must update the `account_nonces`, right?



_Code quote:_
```XML
self.account_nonces.remove(&tx.contract_address());
```
___
*[`crates/mempool/src/mempool.rs` line 90 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5EG4C4-llWrF_q0Knr:-O5EG4C55e_vxzT4NMtR:bwz64ws) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6394e37298c3c8f2a1815c83d1fb23d6529b0f7/crates/mempool/src/mempool.rs#L90)):*
> ```XML
>     // state_changes: a map that associates each account address with the state of the committed
>     // block.
>     pub fn commit_block(
> ```

I think it should be updated in the `commit_block`, right?



_Code quote:_
```XML
 pub fn commit_block
```


<!-- Sent from Reviewable.io -->

2024-08-27 07:10 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5EE08T7pJqDn0Hwns-:-O5HeN7B89mfGhjAxH5v:bait8cg) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6394e37298c3c8f2a1815c83d1fb23d6529b0f7/crates/mempool/src/mempool.rs#L63)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

If you still have the address, you must update the `account_nonces`, right?
</blockquote></details>

WDYM? The code checks if the transaction pool contains any transactions for a given address. If none are found, it removes the account from `account_nonces`.
___
*[`crates/mempool/src/mempool.rs` line 90 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5EG4C4-llWrF_q0Knr:-O5HewUR8nGIGPpQGd1n:bxirvui) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6394e37298c3c8f2a1815c83d1fb23d6529b0f7/crates/mempool/src/mempool.rs#L90)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think it should be updated in the `commit_block`, right?
</blockquote></details>

`commit_block` calls `align_to_account_state`, and it's being updated there. 


<!-- Sent from Reviewable.io -->

2024-08-27 08:19 UTC, elintul reviewed
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5HuDU81nTuM9gyS5WE:-O5HuDU95isKXIusnosL:bg5p3el) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6394e37298c3c8f2a1815c83d1fb23d6529b0f7/crates/mempool/src/mempool.rs#L62)):*
> ```XML
>         for tx_ref in &eligible_tx_references {
>             let tx = self.tx_pool.remove(tx_ref.tx_hash)?;
>             if !self.tx_pool.contains_account(tx.contract_address()) {
> ```

Define a variable, note it contains a `match`.



_Code quote:_
```XML
tx.contract_address()
```
___
*[`crates/mempool/src/mempool.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5HtxsR5Fow7DWNc8y_:-O5HtxsR5Fow7DWNc8ya:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6394e37298c3c8f2a1815c83d1fb23d6529b0f7/crates/mempool/src/mempool.rs#L186)):*
> ```XML
>         self.tx_pool.remove_up_to_nonce(address, nonce);
> 
>         if self.tx_pool.contains_account(address) {
> ```





_Suggestion:_
```XML
        // Remove from pool; maybe remove address if no transactions from it left.
        self.tx_pool.remove_up_to_nonce(address, nonce);
        if self.tx_pool.contains_account(address) {
```


<!-- Sent from Reviewable.io -->

2024-08-27 08:19 UTC, elintul reviewed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-08-27 10:22 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5EE08T7pJqDn0Hwns-:-O5IJqUhC888hU826Vy5:b5axs2b) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6394e37298c3c8f2a1815c83d1fb23d6529b0f7/crates/mempool/src/mempool.rs#L63)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

WDYM? The code checks if the transaction pool contains any transactions for a given address. If none are found, it removes the account from `account_nonces`.
</blockquote></details>

I mean that you need to update the account_nonce in get_txs.

We had a face-to-face conversation, and it appears that we do not want to update it in get_txs.


<!-- Sent from Reviewable.io -->

2024-08-27 11:31 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5HuDU81nTuM9gyS5WE:-O5IaRe68f_Ikx1UAlZ0:bmu13o1) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6394e37298c3c8f2a1815c83d1fb23d6529b0f7/crates/mempool/src/mempool.rs#L62)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Define a variable, note it contains a `match`.
</blockquote></details>

hope I understood what you meant


<!-- Sent from Reviewable.io -->

2024-08-28 14:04 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O58Vma88u0FLvS5-lK0:-O5OI8XX2VyXjtL_Tjdo:b2hw5hx) ([raw file](https://github.com/starkware-libs/sequencer/blob/33eda1ade3cbdf3112741a7ae60195e5c5fe6d76/crates/mempool/src/mempool.rs#L79)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Is it reasonable?
Let's talk F2F.
</blockquote></details>

Discussed F2F and decided to prevent a lower nonce from being updated in account nonces.


<!-- Sent from Reviewable.io -->

2024-08-28 14:33 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 181 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5OOH2nDmGvY7IKLjuS:-O5OOH2nDmGvY7IKLjuT:bavkm9p) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd2bea17f9b538109e2db9d7c3bee3488fb9da93/crates/mempool/src/mempool.rs#L181)):*
> ```XML
>         // Note: != is equivalent to > in `add_tx`, as lower nonces are rejected in validation.
>         if self.tx_queue.get_nonce(address).is_some_and(|queued_nonce| queued_nonce != nonce) {
>             assert!(self.tx_queue.remove(address));
> ```

Add an informative error message, asserts should not be naked.



_Code quote:_
```XML
assert!(self.tx_queue.remove(address));
```
___
*[`crates/mempool/src/mempool.rs` line 195 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5OOfx87TCx4P7A-5mi:-O5OOfx87TCx4P7A-5mj:bjuwhua) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd2bea17f9b538109e2db9d7c3bee3488fb9da93/crates/mempool/src/mempool.rs#L195)):*
> ```XML
>             } else {
>                 self.account_nonces.insert(address, nonce);
>             }
> ```

Is there a more idiomatic way to write this?



_Code quote:_
```XML
            // Update the account nonce if it's absent or set to the higher nonce.
            if let Some(current_account_nonce) = self.account_nonces.get(&address) {
                if current_account_nonce <= &nonce {
                    self.account_nonces.insert(address, nonce);
                }
            } else {
                self.account_nonces.insert(address, nonce);
            }
```


<!-- Sent from Reviewable.io -->

2024-08-29 10:18 UTC, MohammadNassar1 reviewed
> Reviewed 1 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 195 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5OOfx87TCx4P7A-5mi:-O5Scrmf-4Z4rZpyvDMC:bmx0dwq) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd2bea17f9b538109e2db9d7c3bee3488fb9da93/crates/mempool/src/mempool.rs#L195)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

There's this approach, but I don't like checking the `if` condition inside `and_modify`
</blockquote></details>

What about using `match`?


<!-- Sent from Reviewable.io -->

2024-08-29 11:14 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 894 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5SdUn23Ikb5RTIsVVV:-O5SdUn23Ikb5RTIsVVW:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec7105e4f29e9eecd57906230adff2685afb8213/crates/mempool/src/mempool_test.rs#L894)):*
> ```XML
> 
> #[rstest]
> #[case::committed_nonce_as_expected(0_u8, 0_u8, Nonce(felt!(0_u8)))]
> ```





_Suggestion:_
```XML
Nonce(Felt::ZERO)
```
___
*[`crates/mempool/src/mempool_test.rs` line 895 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5Sdar0EPoK8g1evXei:-O5Sdar0EPoK8g1evXej:bd2wplu) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec7105e4f29e9eecd57906230adff2685afb8213/crates/mempool/src/mempool_test.rs#L895)):*
> ```XML
> #[rstest]
> #[case::committed_nonce_as_expected(0_u8, 0_u8, Nonce(felt!(0_u8)))]
> #[case::committed_higher_nonce_than_current_account_nonce(0_u8, 0_u8, Nonce(felt!(3_u8)))]
> ```

please update as suggested below.



_Suggestion:_
```XML
Nonce(Felt::THREE)
```


<!-- Sent from Reviewable.io -->

2024-08-29 11:36 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 195 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5OOfx87TCx4P7A-5mi:-O5Stl4YCS1Wmmte-VVY:b-b70r95) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd2bea17f9b538109e2db9d7c3bee3488fb9da93/crates/mempool/src/mempool.rs#L195)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What about using `match`?
</blockquote></details>

It's possible, but I feel like it's less readable. I don't have a strong opinion on it.



_Code snippet:_
```XML
        if self.tx_pool.contains_account(address) {
            match self.account_nonces.get(&address) {
                Some(current_account_nonce) if current_account_nonce <= &nonce => {
                    self.account_nonces.insert(address, nonce);
                }
                None => {
                    self.account_nonces.insert(address, nonce);
                }
                _ => {}
            }
```
___
*[`crates/mempool/src/mempool_test.rs` line 894 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5SdUn23Ikb5RTIsVVV:-O5Stc0b-32LPtpK1_CH:bd70ysr) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec7105e4f29e9eecd57906230adff2685afb8213/crates/mempool/src/mempool_test.rs#L894)):*
> ```XML
> 
> #[rstest]
> #[case::committed_nonce_as_expected(0_u8, 0_u8, Nonce(felt!(0_u8)))]
> ```

`add_tx_input` expects a `u8`, so I can't pass a `Nonce`.


<!-- Sent from Reviewable.io -->

2024-08-29 13:44 UTC, MohammadNassar1 approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 195 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5OOfx87TCx4P7A-5mi:-O5TMlIVE7I_eB4Aj7p0:bjeviqb) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd2bea17f9b538109e2db9d7c3bee3488fb9da93/crates/mempool/src/mempool.rs#L195)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

It's possible, but I feel like it's less readable. I don't have a strong opinion on it.
</blockquote></details>

It looks better, actually.
___
*[`crates/mempool/src/mempool_test.rs` line 934 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5TMysm2odNspHmuUN_:-O5TMysm2odNspHmuUNa:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3f33638a0242325a81a92a865f6ccf5121cadf/crates/mempool/src/mempool_test.rs#L934)):*
> ```XML
>     expected_mempool_content.assert_eq_account_nonces(&mempool);
> 
>     // Test: update through a block.
> ```





_Suggestion:_
```XML
a commit block
```
___
*[`crates/mempool/src/mempool_test.rs` line 936 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5TN1Tl9qve1HIx-hYm:-O5TN1Tl9qve1HIx-hYn:bw82fny) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3f33638a0242325a81a92a865f6ccf5121cadf/crates/mempool/src/mempool_test.rs#L936)):*
> ```XML
>     // Test: update through a block.
>     let state_changes = HashMap::from([(address, AccountState { nonce: committed_nonce })]);
>     assert!(mempool.commit_block(state_changes).is_ok());
> ```

also the rest pls



_Suggestion:_
```XML
assert_eq!(mempool.commit_block(state_changes), Ok(()));
```


<!-- Sent from Reviewable.io -->

2024-08-29 14:25 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 195 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5OOfx87TCx4P7A-5mi:-O5TVZIs13Cfxgvc0Qez:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd2bea17f9b538109e2db9d7c3bee3488fb9da93/crates/mempool/src/mempool.rs#L195)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It looks better, actually.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 936 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5TN1Tl9qve1HIx-hYm:-O5TVqO69s6WGCI2ZzBy:bne02da) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3f33638a0242325a81a92a865f6ccf5121cadf/crates/mempool/src/mempool_test.rs#L936)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

also the rest pls
</blockquote></details>

done, but why is it better?


<!-- Sent from Reviewable.io -->

2024-09-02 15:11 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 198 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5nFuip1BhWTgzk3F4Y:-O5nFuip1BhWTgzk3F4Z:biaqy56) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743b4503208bce0a2bb49ee962c41c5bc2f3a69/crates/mempool/src/mempool.rs#L198)):*
> ```XML
>             }
>         } else {
>             // Remove address if no transactions from it left.
> ```

The removal only happens when this function is called from `commit_block`, as there will always be transactions from this account when adding a transaction (in `add_tx`). Therefore, this behavior is checked only in commit_block (in `test_account_nonces_removal_in_commit_block`).


<!-- Sent from Reviewable.io -->

2024-09-03 08:08 UTC, MohammadNassar1 approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 192 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5qv8YbDMlC18c4zOE-:-O5qv8YbDMlC18c4zOE0:b-4mml2i) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743b4503208bce0a2bb49ee962c41c5bc2f3a69/crates/mempool/src/mempool.rs#L192)):*
> ```XML
>             // Update the account nonce if it's absent or set to the higher nonce.
>             match self.account_nonces.get(&address) {
>                 Some(current_account_nonce) if current_account_nonce > &nonce => {}
> ```

Can you please remind me when it can be None?



_Code quote:_
```XML
Some(current_account_nonce) 
```
___
*[`crates/mempool/src/mempool_test.rs` line 936 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5TN1Tl9qve1HIx-hYm:-O5qvM2mDygpZfD8f9Og:b-sf5vx9) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3f33638a0242325a81a92a865f6ccf5121cadf/crates/mempool/src/mempool_test.rs#L936)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

done, but why is it better?
</blockquote></details>

It's easier to debug.


<!-- Sent from Reviewable.io -->

2024-09-03 08:33 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 192 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5qv8YbDMlC18c4zOE-:-O5qzljs3XiBkZxfsj3r:b1fjo9y) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743b4503208bce0a2bb49ee962c41c5bc2f3a69/crates/mempool/src/mempool.rs#L192)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you please remind me when it can be None?
</blockquote></details>

When we receive a transaction from an account that isn't yet in the mempool.
___
*[`crates/mempool/src/mempool_test.rs` line 923 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5qRx_zB7Xtlky3SwBR:-O5qogbv6lhR7mo6CYWu:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743b4503208bce0a2bb49ee962c41c5bc2f3a69/crates/mempool/src/mempool_test.rs#L923)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add a variant for this if doesn't exist, numbers that aren't significant shouldn't appear.
</blockquote></details>

WDYM?
___
*[`crates/mempool/src/mempool_test.rs` line 925 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5qSBr6-vcurBjmCwX_:-O5qmPsBDLBSy-SAKgn1:bpg8o5t) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743b4503208bce0a2bb49ee962c41c5bc2f3a69/crates/mempool/src/mempool_test.rs#L925)):*
> ```XML
>         add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 3_u8, account_nonce: 0_u8);
>     let address = input.account.sender_address;
>     let committed_nonce = Nonce(Felt::ZERO);
> ```

I think "account nonce" is not accurate here. This variable represents the nonce that was committed and received from the batcher; the account nonce, however, is one higher than this value.
___
*[`crates/mempool/src/mempool_test.rs` line 937 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5qTd_J3hqmsxCMBx6x:-O5qrSey5H0NQ-niXFUv:b-tkcnra) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743b4503208bce0a2bb49ee962c41c5bc2f3a69/crates/mempool/src/mempool_test.rs#L937)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Lets keep unit test at one API per test, unless unavoidable in case of coupled API methods or when an important flow must be tested this way.

Here for example the add_tx is unnecessary I think, since it is can be covered by a very basic unit test (and indeed is already covered implicitly by the other unit tests here regardless).
</blockquote></details>

In this test, I'm checking that `add_tx` updates the account nonce when receiving a transaction, and `commit_block` updates it if there are transactions from the account in the mempool. Splitting the test would require an empty mempool for `add_tx` and a filled one for `commit_block`. Would you prefer this?
___
*[`crates/mempool/src/mempool_test.rs` line 954 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5qUcip8mGSDarJzzxy:-O5qxNk_03uo9tmWQ8vd:b-5fnu6k) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743b4503208bce0a2bb49ee962c41c5bc2f3a69/crates/mempool/src/mempool_test.rs#L954)):*
> ```XML
>     let input_account_nonce_2 =
>         add_tx_input!(tx_hash: 2, sender_address: "0x0", tx_nonce: 3_u8, account_nonce: 2_u8);
>     let address = input_account_nonce_3.account.sender_address;
> ```

It's not possible because `add_tx_input` receives `u8` or hex and converts it to contract_address
___
*[`crates/mempool/src/mempool_test.rs` line 957 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5qVh9A52bH-ciadX0d:-O5qyI5566MaC8AtctNA:b-7cmp49) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743b4503208bce0a2bb49ee962c41c5bc2f3a69/crates/mempool/src/mempool_test.rs#L957)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If the clone pattern appears again move it into with_account_nonces and pass a ref instead of move
</blockquote></details>

it doesn't happen again. Should I do it anyway in a different PR?


<!-- Sent from Reviewable.io -->

2024-09-03 08:40 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 192 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5qv8YbDMlC18c4zOE-:-O5r1WOH80gK6Pc9f-Xa:b-ucfknh) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743b4503208bce0a2bb49ee962c41c5bc2f3a69/crates/mempool/src/mempool.rs#L192)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

When we receive a transaction from an account that isn't yet in the mempool.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2024-09-03 10:15 UTC, elintul submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 196 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5mYTD76fMQs9bCOWAz:-O5mYTD76fMQs9bCOWB-:bkmij8o) ([raw file](https://github.com/starkware-libs/sequencer/blob/19e41bd0ba0f51e419db09407cf87a65a8b54cd6/crates/mempool/src/mempool.rs#L196)):*
> ```XML
>                 }
>                 _ => {}
>             }
> ```

let should_insert = self.account_nonces.get(address).is_so



_Suggestion:_
```XML
            match self.account_nonces.get(&address) {
                Some(current_account_nonce) if current_account_nonce > &nonce => {}
                _ => self.account_nonces.insert(address, nonce);
            }
```


<!-- Sent from Reviewable.io -->

2024-09-08 09:22 UTC, giladchase reviewed
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 936 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5TN1Tl9qve1HIx-hYm:-O6FugA756uWAP4NHpt_:b-d4y4jp) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3f33638a0242325a81a92a865f6ccf5121cadf/crates/mempool/src/mempool_test.rs#L936)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It's easier to debug.
</blockquote></details>

Another acceptable thing here is to `unwrap`, it will also list the error in the print.
Whether to use assert_eq with Ok(()) or unwrap is at yr discretion based on the test, not critical.
___
*[`crates/mempool/src/mempool_test.rs` line 954 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5qUcip8mGSDarJzzxy:-O6Fvv3GEVLGxmX6Ngf4:b-7j964s) ([raw file](https://github.com/starkware-libs/sequencer/blob/7743b4503208bce0a2bb49ee962c41c5bc2f3a69/crates/mempool/src/mempool_test.rs#L954)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

It's not possible because `add_tx_input` receives `u8` or hex and converts it to contract_address
</blockquote></details>

stale


<!-- Sent from Reviewable.io -->

2024-09-08 13:02 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-09-08 14:49 UTC, MohammadNassar1 reviewed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 939 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O6H0Msv3gH1SebWKC-h:-O6H0Msw99VXNu8-uwBD:bohbksa) ([raw file](https://github.com/starkware-libs/sequencer/blob/acfc39a4826565d12b3c0ee51f444998e17d8965/crates/mempool/src/mempool_test.rs#L939)):*
> ```XML
> }
> 
> // account_nonces tests.
> ```

Please move it before running the flow tests. Also, arrange the tests according to the API they check.



_Code quote:_
```XML
// account_nonces tests.
```
___
*[`crates/mempool/src/mempool_test.rs` line 958 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O6H5kCd3egqKoN4M2Nx:-O6H5kCd3egqKoN4M2Ny:b-taxb4q) ([raw file](https://github.com/starkware-libs/sequencer/blob/acfc39a4826565d12b3c0ee51f444998e17d8965/crates/mempool/src/mempool_test.rs#L958)):*
> ```XML
> 
> #[rstest]
> fn test_account_nonces_update_in_commit_block() {
> ```

I think the three commit block tests, can be done in a single test.
You can create the three scenarios with different sender addresses.



_Code quote:_
```XML
test_account_nonces_update_in_commit_block
```


<!-- Sent from Reviewable.io -->

2024-09-08 14:52 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 958 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O6H5kCd3egqKoN4M2Nx:-O6H6YFXCw11_hDmKg15:bjdgpfk) ([raw file](https://github.com/starkware-libs/sequencer/blob/acfc39a4826565d12b3c0ee51f444998e17d8965/crates/mempool/src/mempool_test.rs#L958)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think the three commit block tests, can be done in a single test.
You can create the three scenarios with different sender addresses.
</blockquote></details>

@giladchase prefers having more tests to make debugging easier.


<!-- Sent from Reviewable.io -->

2024-09-08 14:54 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 196 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5mYTD76fMQs9bCOWAz:-O6H6wMK10bVsifzKjyi:bjcw6yu) ([raw file](https://github.com/starkware-libs/sequencer/blob/19e41bd0ba0f51e419db09407cf87a65a8b54cd6/crates/mempool/src/mempool.rs#L196)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

let should_insert = self.account_nonces.get(address).is_so
</blockquote></details>

Do you prefer this approach over the solution we agreed on offline?


<!-- Sent from Reviewable.io -->

2024-09-09 08:15 UTC, MohammadNassar1 requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534#-:-O6KqNHCDE0fVSooKVdv:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-09-09 10:30 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534#-:-O6LKLxxAUAK8UpcVeQe:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 958 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O6H5kCd3egqKoN4M2Nx:-O6LJJO-0CFxDO3Qj5TT:bs3ur3l) ([raw file](https://github.com/starkware-libs/sequencer/blob/acfc39a4826565d12b3c0ee51f444998e17d8965/crates/mempool/src/mempool_test.rs#L958)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

@giladchase prefers having more tests to make debugging easier.
</blockquote></details>

discussed offline, multiple tests is fine if they test different flows, even if the test structure is similar.
___
*[`crates/mempool/src/mempool_test.rs` line 1038 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O6LKKTc0F1oEaJXY-h8:-O6LKKTc0F1oEaJXY-h9:b-u4p8ir) ([raw file](https://github.com/starkware-libs/sequencer/blob/acfc39a4826565d12b3c0ee51f444998e17d8965/crates/mempool/src/mempool_test.rs#L1038)):*
> ```XML
>     // TODO(Ayelet): Consider adding full content instead of using add tx.
>     add_tx(&mut mempool, &input);
>     mempool.get_txs(1).unwrap();
> ```

split test



_Code quote:_
```XML
    add_tx(&mut mempool, &input);
    mempool.get_txs(1).unwrap();
```


<!-- Sent from Reviewable.io -->

2024-09-09 10:35 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 939 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O6H0Msv3gH1SebWKC-h:-O6LLUeWAc0pRLp750B7:bza5fny) ([raw file](https://github.com/starkware-libs/sequencer/blob/acfc39a4826565d12b3c0ee51f444998e17d8965/crates/mempool/src/mempool_test.rs#L939)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please move it before running the flow tests. Also, arrange the tests according to the API they check.
</blockquote></details>

will be done a differnet PR.


<!-- Sent from Reviewable.io -->

2024-09-09 11:09 UTC, MohammadNassar1 approved these changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-09-09 11:11 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/534)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool.rs` line 196 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/534#-O5mYTD76fMQs9bCOWAz:-O6LTrLh-65E3PFm6n47:b-2302xy) ([raw file](https://github.com/starkware-libs/sequencer/blob/19e41bd0ba0f51e419db09407cf87a65a8b54cd6/crates/mempool/src/mempool.rs#L196)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Do you prefer this approach over the solution we agreed on offline?
</blockquote></details>

stale, discussed offline


<!-- Sent from Reviewable.io -->

2024-09-09 11:13 UTC, merged