feat(batcher): mock BlockBuilder for tests
starkware-libs/sequencer pull request #541
Opened 2024-08-20 14:51 UTC by yair-starkware

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/541)

2024-08-28 12:07 UTC, dafnamatsry requested changes
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5K88OK7CQGq_FevZal:-O5K88OK7CQGq_FevZam:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager.rs#L86)):*
> ```XML
>     /// or validated).
>     proposal_in_generation: Arc<Mutex<Option<ProposalId>>>,
>     // To be able to mock BlockBuilder in tests.
> ```





_Suggestion:_
```XML
 // Use a factory object, to be able to mock BlockBuilder in tests.
```
___
*[`crates/batcher/src/proposals_manager.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5K9m8jC-WBgn-VeURe:-O5K9m8jC-WBgn-VeURf:b-n2gjhz) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager.rs#L177)):*
> ```XML
>     pub sender: tokio::sync::mpsc::Sender<Transaction>,
>     pub proposal_in_generation: Arc<Mutex<Option<ProposalId>>>,
>     pub block_builder_factory: Arc<dyn BlockBuilderFactory>,
> ```

Consider holding an `Arc<dyn BlockBuilderTrait>`.



_Code quote:_
```XML
pub block_builder_factory: Arc<dyn BlockBuilderFactory>,
```
___
*[`crates/batcher/src/proposals_manager_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5MzcDICmAJ5pjH6SVX:-O5MzcDICmAJ5pjH6SVY:bb80pl2) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L25)):*
> ```XML
> #[tokio::test]
> async fn proposal_generation_success() {
>     let proposals_manager_config = ProposalsManagerConfig::default();
> ```

Please add fixtures to create the setup for the tests.
i.e. fixture for the proposal_manager, fixture for the factory, mempool client, etc.



_Code quote:_
```XML
let proposals_manager_config = ProposalsManagerConfig::default();
```
___
*[`crates/batcher/src/proposals_manager_test.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5Mza_uDHS7t9ppvaAZ:-O5Mza_uDHS7t9ppvaA_:b8b1ncg) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L26)):*
> ```XML
> async fn proposal_generation_success() {
>     let proposals_manager_config = ProposalsManagerConfig::default();
>     let mut block_builder_factory = MockBlockBuilderFactory::new();
> ```

Why mut?



_Code quote:_
```XML
let mut block_builder_factory 
```
___
*[`crates/batcher/src/proposals_manager_test.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5NpPnG4ioju23_kMPx:-O5NpPnG4ioju23_kMPy:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L66)):*
> ```XML
>     block_builder_factory.expect_create_block_builder().times(2).returning(|| {
>         let mut mock_block_builder = MockBlockBuilderTrait::new();
>         mock_block_builder.expect_add_txs().once().returning(|_thin_txs| false);
> ```





_Suggestion:_
```XML
_txs
```
___
*[`crates/batcher/src/proposals_manager_test.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5NraSC2aUiJvZkfHsd:-O5NraSC2aUiJvZkfHse:baemlm8) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L149)):*
> ```XML
> 
>     let mut streamed_txs = vec![];
>     while let Some(tx) = tx_stream.next().await {
> ```

How do we know that the stream is over?



_Code quote:_
```XML
while let Some(tx) = tx_stream.next().await
```


<!-- Sent from Reviewable.io -->

2024-09-01 09:36 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/batcher/src/proposals_manager.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5K88OK7CQGq_FevZal:-O5gZT3o3yW60c6SWqNI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager.rs#L86)):*
> ```XML
>     /// or validated).
>     proposal_in_generation: Arc<Mutex<Option<ProposalId>>>,
>     // To be able to mock BlockBuilder in tests.
> ```

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5K9m8jC-WBgn-VeURe:-O5gfFVK1iiqGb6IIXWM:b-8drqgn) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager.rs#L177)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider holding an `Arc<dyn BlockBuilderTrait>`.
</blockquote></details>

It makes it  muchharder to mock consecutive calls
___
*[`crates/batcher/src/proposals_manager_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5MzcDICmAJ5pjH6SVX:-O5gvztq8mhbtK9D9dYD:b-vqmlkh) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L25)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add fixtures to create the setup for the tests.
i.e. fixture for the proposal_manager, fixture for the factory, mempool client, etc.
</blockquote></details>

Sort of done, didn't find how to do it completely with adding expectations to the mocks
___
*[`crates/batcher/src/proposals_manager_test.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5Mza_uDHS7t9ppvaAZ:-O5gfSZT8QzEm0smqrkL:b-u6692i) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L26)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why mut?
</blockquote></details>

Not relevant after the last change
___
*[`crates/batcher/src/proposals_manager_test.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5NpPnG4ioju23_kMPx:-O5gff4E6jYJnO12fvJo:b-u6692i) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L66)):*
> ```XML
>     block_builder_factory.expect_create_block_builder().times(2).returning(|| {
>         let mut mock_block_builder = MockBlockBuilderTrait::new();
>         mock_block_builder.expect_add_txs().once().returning(|_thin_txs| false);
> ```

Not relevant after the last change
___
*[`crates/batcher/src/proposals_manager_test.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5NraSC2aUiJvZkfHsd:-O5gfjzV7pwyFoSsww_C:b-8tc3tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L149)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

How do we know that the stream is over?
</blockquote></details>

When it returns None


<!-- Sent from Reviewable.io -->

2024-09-01 11:30 UTC, dafnamatsry requested changes
> Reviewed 1 of 5 files at r4, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5MzcDICmAJ5pjH6SVX:-O5hIarP1RlQheGwtthF:bt3sk8z) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L25)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Sort of done, didn't find how to do it completely with adding expectations to the mocks
</blockquote></details>

What do you mean by adding expectations to the mock?
Aren't these the calls to `mock_object.expect_func()` in the test bodies?
___
*[`crates/batcher/src/proposals_manager_test.rs` line 195 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5hE1JK9oWg7Ke-LVl0:-O5hE1JK9oWg7Ke-LVl1:b3fjfwu) ([raw file](https://github.com/starkware-libs/sequencer/blob/1479fff46c5e453f1b1af33423a8fa5f3aac248d/crates/batcher/src/proposals_manager_test.rs#L195)):*
> ```XML
> }
> 
> // Not using automock because the support for async traits is not good.
> ```

Can you explain?
I see that we do use automock in some async traits in our codebase.

Don't know if that's the issue, but I found that the order of calling the macros is important, i.e.:
```
// This is the good order
#[cfg_attr(test, automock)]
#[async_trait]
```


<!-- Sent from Reviewable.io -->

2024-09-01 14:51 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5MzcDICmAJ5pjH6SVX:-O5i2YceDCG6oAal83x2:b40712m) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L25)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What do you mean by adding expectations to the mock?
Aren't these the calls to `mock_object.expect_func()` in the test bodies?
</blockquote></details>

Yes, I need the mocked instances to make the expectations.
If I create the whole ProposalsManager in a fixture I don't have them at hand
___
*[`crates/batcher/src/proposals_manager_test.rs` line 195 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5hE1JK9oWg7Ke-LVl0:-O5i2s8P1P_4netdU66f:b-4gf655) ([raw file](https://github.com/starkware-libs/sequencer/blob/1479fff46c5e453f1b1af33423a8fa5f3aac248d/crates/batcher/src/proposals_manager_test.rs#L195)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you explain?
I see that we do use automock in some async traits in our codebase.

Don't know if that's the issue, but I found that the order of calling the macros is important, i.e.:
```
// This is the good order
#[cfg_attr(test, automock)]
#[async_trait]
```
</blockquote></details>

I tried to do it, but the `returning` method gets a closure which is not async, so I don't know how to mimic the function.
In particular I don't know how to make the builder stream the transactions outside.
Tried to use `sender.blocking_send` but it requires spawning threads in the test and make it very difficult


<!-- Sent from Reviewable.io -->

2024-09-02 12:15 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5MzcDICmAJ5pjH6SVX:-O5mUPC27dEN9cPMQVE8:b-itqcdt) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L25)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Yes, I need the mocked instances to make the expectations.
If I create the whole ProposalsManager in a fixture I don't have them at hand
</blockquote></details>

Can you do something like this:

```
#[fixture]
fn block_builder_factory() -> MockBlockBuilderFactory {...}

#[fixture]
fn mempool_client() -> MockMempoolClient {...}

#[fixture]
fn proposals_manager(block_builder_factory, mempool_client) -> ProposalsManager {... }

async fn test(
    proposals_manager: ProposalsManager,
    block_builder_factory: MockBlockBuilderFactory,
    mempool_client: MockMempoolClient,
) { ...}
```

?
___
*[`crates/batcher/src/proposals_manager_test.rs` line 195 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5hE1JK9oWg7Ke-LVl0:-O5mcWQ58PvoWZ0vP6CB:b-x7eusk) ([raw file](https://github.com/starkware-libs/sequencer/blob/1479fff46c5e453f1b1af33423a8fa5f3aac248d/crates/batcher/src/proposals_manager_test.rs#L195)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I tried to do it, but the `returning` method gets a closure which is not async, so I don't know how to mimic the function.
In particular I don't know how to make the builder stream the transactions outside.
Tried to use `sender.blocking_send` but it requires spawning threads in the test and make it very difficult
</blockquote></details>

I see. Makes me think that we don't really need to mimic this logic, and it is enough to check that we call the block builder as expected.
IIUC, mimicking this logic doesn't really test anything of the proposal manger; it only tests that the sender/receiver objects are working. The actual insertion to the sender will be tested in the real BlockBuilder test.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 199 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5me7Fh40WhA37WUzim:-O5me7Fh40WhA37WUzin:bnsnoy2) ([raw file](https://github.com/starkware-libs/sequencer/blob/59d905a3b4f8c09a6b0b68a1c4f528f0b2706a5d/crates/batcher/src/proposals_manager_test.rs#L199)):*
> ```XML
> struct MockBlockBuilder {
>     pub n_calls_before_closing_block: usize,
>     n_calls: AtomicRefCell<usize>,
> ```

Just `uszie` won't work?



_Code quote:_
```XML
AtomicRefCell<usize>
```


<!-- Sent from Reviewable.io -->

2024-09-03 08:34 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 129 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5r-Rgc3x7zimVJDaqG:-O5r-Rgc3x7zimVJDaqH:b-7769wy) ([raw file](https://github.com/starkware-libs/sequencer/blob/59d905a3b4f8c09a6b0b68a1c4f528f0b2706a5d/crates/batcher/src/proposals_manager.rs#L129)):*
> ```XML
>                 sender: Arc::new(sender),
>                 proposal_in_generation: self.proposal_in_generation.clone(),
>                 block_builder_factory: self.block_builder_factory.clone(),
> ```

why not create the block_builder and pass it to the Task here, instead of cloning the factory?
the Task only needs the block_builder.



_Code quote:_
```XML
block_builder_factory: self.block_builder_factory.clone(),
```
___
*[`crates/batcher/src/proposals_manager_test.rs` line 110 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5qyuvhBcyFsUkgcGoS:-O5qyuvhBcyFsUkgcGoT:b10rlxv) ([raw file](https://github.com/starkware-libs/sequencer/blob/59d905a3b4f8c09a6b0b68a1c4f528f0b2706a5d/crates/batcher/src/proposals_manager_test.rs#L110)):*
> ```XML
>     let expected_tx_hashes = (0..proposals_manager_config.max_txs_per_mempool_request * 2)
>         .map(|i| TransactionHash(felt!(u8::try_from(i).unwrap())))
>         .collect::<Vec<_>>();
> ```

I think this vector should be constructed from the same vector that the mock mempool client uses.



_Code quote:_
```XML
    let expected_tx_hashes = (0..proposals_manager_config.max_txs_per_mempool_request * 2)
        .map(|i| TransactionHash(felt!(u8::try_from(i).unwrap())))
        .collect::<Vec<_>>();
```


<!-- Sent from Reviewable.io -->

2024-09-03 08:47 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 166 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5r3HSEAuSKLUyEgxwe:-O5r3HSEAuSKLUyEgxwf:b-6akv2x) ([raw file](https://github.com/starkware-libs/sequencer/blob/59d905a3b4f8c09a6b0b68a1c4f528f0b2706a5d/crates/batcher/src/proposals_manager.rs#L166)):*
> ```XML
>         txs: Vec<Transaction>,
>         sender: Arc<tokio::sync::mpsc::Sender<Transaction>>,
>     ) -> bool;
> ```

I think an enum would be more readable than a bool.



_Code quote:_
```XML
bool
```


<!-- Sent from Reviewable.io -->

2024-09-05 13:40 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 129 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5r-Rgc3x7zimVJDaqG:-O61GxYA5L8AbqSftg1L:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/59d905a3b4f8c09a6b0b68a1c4f528f0b2706a5d/crates/batcher/src/proposals_manager.rs#L129)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why not create the block_builder and pass it to the Task here, instead of cloning the factory?
the Task only needs the block_builder.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 166 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5r3HSEAuSKLUyEgxwe:-O5r_Kev-4T466AM5kWG:bs6pw4o) ([raw file](https://github.com/starkware-libs/sequencer/blob/59d905a3b4f8c09a6b0b68a1c4f528f0b2706a5d/crates/batcher/src/proposals_manager.rs#L166)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think an enum would be more readable than a bool.
</blockquote></details>

In a later PR I change it to `Option<ClosedBlock>`
___
*[`crates/batcher/src/proposals_manager_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5MzcDICmAJ5pjH6SVX:-O61Ot8R3I895hC2O5r8:b-jotzrl) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ff3dea474d38870bf5fc641a1c153a9226c47bf/crates/batcher/src/proposals_manager_test.rs#L25)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you do something like this:

```
#[fixture]
fn block_builder_factory() -> MockBlockBuilderFactory {...}

#[fixture]
fn mempool_client() -> MockMempoolClient {...}

#[fixture]
fn proposals_manager(block_builder_factory, mempool_client) -> ProposalsManager {... }

async fn test(
    proposals_manager: ProposalsManager,
    block_builder_factory: MockBlockBuilderFactory,
    mempool_client: MockMempoolClient,
) { ...}
```

?
</blockquote></details>

It doesn't work - I get different instances of the mocks
___
*[`crates/batcher/src/proposals_manager_test.rs` line 195 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5hE1JK9oWg7Ke-LVl0:-O61HTiv4ti2CmC75WBH:b-77ekmm) ([raw file](https://github.com/starkware-libs/sequencer/blob/1479fff46c5e453f1b1af33423a8fa5f3aac248d/crates/batcher/src/proposals_manager_test.rs#L195)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I see. Makes me think that we don't really need to mimic this logic, and it is enough to check that we call the block builder as expected.
IIUC, mimicking this logic doesn't really test anything of the proposal manger; it only tests that the sender/receiver objects are working. The actual insertion to the sender will be tested in the real BlockBuilder test.
</blockquote></details>

Found a way to do it nicely.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 110 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5qyuvhBcyFsUkgcGoS:-O61H8-_Cuy68sMaKAbS:b-12i3zf) ([raw file](https://github.com/starkware-libs/sequencer/blob/59d905a3b4f8c09a6b0b68a1c4f528f0b2706a5d/crates/batcher/src/proposals_manager_test.rs#L110)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think this vector should be constructed from the same vector that the mock mempool client uses.
</blockquote></details>

It's hard because the mock takes ownership of the captured data
___
*[`crates/batcher/src/proposals_manager_test.rs` line 199 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5me7Fh40WhA37WUzim:-O61Hipa5f4OaY2OmDhO:b-gig0rf) ([raw file](https://github.com/starkware-libs/sequencer/blob/59d905a3b4f8c09a6b0b68a1c4f528f0b2706a5d/crates/batcher/src/proposals_manager_test.rs#L199)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Just `uszie` won't work?
</blockquote></details>

Not relevant now


<!-- Sent from Reviewable.io -->

2024-09-08 12:25 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 158 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6G_WJt5LlB173axdK4:-O6G_WJt5LlB173axdK5:b-htqtwt) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L158)):*
> ```XML
>                 };
>                 let mut proposal_id = proposal_in_generation.lock().await;
>                 *proposal_id = None;
> ```

To keep symmetry, I'd suggest to define a function clear_proposal_in_generation (the opposite of set_proposal_in_generation). 



_Code quote:_
```XML
                let mut proposal_id = proposal_in_generation.lock().await;
                *proposal_id = None;
```


<!-- Sent from Reviewable.io -->

2024-09-08 13:19 UTC, dafnamatsry requested changes
> Reviewed 1 of 4 files at r5, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 87 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6FlLoZ4JF6RzW0-UdY:-O6FlLoZ4JF6RzW0-UdZ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/79a6d6557d8c0d48558fe68f9dc3f53eced8a77d/crates/batcher/src/proposals_manager.rs#L87)):*
> ```XML
>     /// At any given time, there can be only one proposal being actively executed (either proposed
>     /// or validated).
>     proposal_in_generation: Arc<Mutex<Option<ProposalId>>>,
> ```





_Suggestion:_
```XML
 active_proposal
```
___
*[`crates/batcher/src/proposals_manager.rs` line 116 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6G-4oU94VpxyFwJpJ8:-O6FqRGh91wSDi1tX1YG:bjlnhgy) ([raw file](https://github.com/starkware-libs/sequencer/blob/79a6d6557d8c0d48558fe68f9dc3f53eced8a77d/crates/batcher/src/proposals_manager.rs#L116)):*
> ```XML
>         timeout: tokio::time::Instant,
>         _height: BlockNumber,
>     ) -> ProposalsManagerResult<(JoinHandle<ProposalsManagerResult<()>>, OutputTxStream)> {
> ```

Why do we return the handle?



_Code quote:_
```XML
JoinHandle<ProposalsManagerResult<()>>, OutputTxStream)
```
___
*[`crates/batcher/src/proposals_manager.rs` line 120 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6FmVgX78G0SXQ4QLE5:-O6FmVgX78G0SXQ4QLE6:b8oazoz) ([raw file](https://github.com/starkware-libs/sequencer/blob/79a6d6557d8c0d48558fe68f9dc3f53eced8a77d/crates/batcher/src/proposals_manager.rs#L120)):*
> ```XML
>         self.set_proposal_in_generation(proposal_id).await?;
> 
>         // TODO: Should we use a different config for the stream buffer size?
> ```

I think so, eventually we should be able to add to the stream even if the txs there are not consumed yet.



_Code quote:_
```XML
// TODO: Should we use a different config for the stream buffer size?
```
___
*[`crates/batcher/src/proposals_manager.rs` line 116 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6GHYwX7DeBT4sHPucF:-O6GHYwX7DeBT4sHPucG:bvxyr7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L116)):*
> ```XML
>         timeout: tokio::time::Instant,
>         _height: BlockNumber,
>     ) -> ProposalsManagerResult<(JoinHandle<ProposalsManagerResult<()>>, OutputTxStream)> {
> ```

I think the channel should be created by the caller (he is the only one who should have access to the receiver).
Lets make the sender an input argument rather than returning the receiver.



_Suggestion:_
```XML
    pub async fn generate_block_proposal(
        &mut self,
        proposal_id: ProposalId,
        timeout: tokio::time::Instant,
        _height: BlockNumber,
        output_content_sender: Sender,
    ) -> ProposalsManagerResult<(JoinHandle<ProposalsManagerResult<()>>)> {
```
___
*[`crates/batcher/src/proposals_manager.rs` line 116 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6GbTJH-hrYBrRigjEn:-O6GbTJH-hrYBrRigjEo:bowikm1) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L116)):*
> ```XML
>         timeout: tokio::time::Instant,
>         _height: BlockNumber,
>     ) -> ProposalsManagerResult<(JoinHandle<ProposalsManagerResult<()>>, OutputTxStream)> {
> ```

I think in general the one who holds the receiver should be the one to create the channel and pass the sender around.

With this the function should look like:

```
async fn generate_block_proposal(...) {
    info!("Starting generation of new proposal.");
    self.set_proposal_in_generation(proposal_id).await?;

    let handle = tokio::spwan(self.generate_block(output_stream_content));

    Ok(...)
}

async fn generate_block(self, output_content_sender) {
     let block_builder = self.block_builder_factory.create_block_builder();
     let block_finished_sender, block_finished_receiver = ...;
     let input_tx_sender = block_builder.start(output_content_sender, block_finished_sender);

    let _ = tokio::select! { ... }
}
```
___
*[`crates/batcher/src/proposals_manager.rs` line 138 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6GmGEKE4c7cenqFfPE:-O6GmGEKE4c7cenqFfPF:balzgrr) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L138)):*
> ```XML
> 
>         // Feed transactions to the block builder until it sends a signal that it finished.
>         let handle = tokio::spawn(
> ```

Please put the spawned code in a dedicated function.
___
*[`crates/batcher/src/proposals_manager.rs` line 142 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6Gidtx-A-fo_L_qk8t:-O6Gidtx-A-fo_L_qk8u:b6kpwhs) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L142)):*
> ```XML
>                 let res = tokio::select! {
>                     // This will send txs from the mempool to the stream we provided to the block builder.
>                     feeder_stopped = Self::feed_txs_to_block_builder(
> ```

feeder stopped doesn't necessarily mean we finished the proposal. The block builder can still be executing txs.
If the feeder failed, I guess we should do some cleanup and abort the task, returning an error, or we might even want to close the block with whatever we executed so far.

Anyway, I think we should close the block only when the block builder tells us it is finished.



_Code quote:_
```XML
feeder_stopped = Self::feed_txs_to_block_builder(
```
___
*[`crates/batcher/src/proposals_manager.rs` line 207 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6Gl7x45O57PlkZ5jrL:-O6Gl7x45O57PlkZ5jrM:bmgsvdd) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L207)):*
> ```XML
>             for tx in mempool_txs {
>                 mempool_tx_sender.send(tx).await.map_err(|err| {
>                     // TODO: should we return the rest of the txs to the mempool?
> ```

Even in a successful flow, we can have txs in the channel that were not included in the block.
The mempool does not delete the txs it sends to us, but put it in a staging area.
Add a todo to update the mempool with the required information (will probably happen in the commit proposal flow).


<!-- Sent from Reviewable.io -->

2024-09-08 13:32 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 2 of 5 files reviewed, 15 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 195 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6Ga_8y3oPLkCi_Cu4Z:-O6Ga_8zCu88diid85ys:bwbfayt) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L195)):*
> ```XML
>     ) -> ProposalsManagerResult<()> {
>         loop {
>             if tokio::time::Instant::now() > timeout {
> ```

I think it's safer to send a signal to the builder, like an empty list, saying we're done.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 110 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5qyuvhBcyFsUkgcGoS:-O6Gi7j26xMN20uRpltQ:bdswsu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/59d905a3b4f8c09a6b0b68a1c4f528f0b2706a5d/crates/batcher/src/proposals_manager_test.rs#L110)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It's hard because the mock takes ownership of the captured data
</blockquote></details>

it is more readable now, 
though still, I think you should define the vector at the beginning, clone it for the mock mempool, and then use it again for the assert.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6Gi-byCEyF2xIXQCxi:-O6Gi-byCEyF2xIXQCxj:b-xajaxv) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager_test.rs#L44)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn proposal_generation_success(
> ```

isn't this test contained in the next test?



_Code quote:_
```XML
proposal_generation_success(
```


<!-- Sent from Reviewable.io -->

2024-09-09 17:04 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 0 of 5 files reviewed, 15 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 87 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6FlLoZ4JF6RzW0-UdY:-O6MbB_l8cCbCL3bUMTL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/79a6d6557d8c0d48558fe68f9dc3f53eced8a77d/crates/batcher/src/proposals_manager.rs#L87)):*
> ```XML
>     /// At any given time, there can be only one proposal being actively executed (either proposed
>     /// or validated).
>     proposal_in_generation: Arc<Mutex<Option<ProposalId>>>,
> ```

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 116 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6G-4oU94VpxyFwJpJ8:-O6MbCg_5uezQGAbfto4:b4isjow) ([raw file](https://github.com/starkware-libs/sequencer/blob/79a6d6557d8c0d48558fe68f9dc3f53eced8a77d/crates/batcher/src/proposals_manager.rs#L116)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why do we return the handle?
</blockquote></details>

I need it for the tests and in the future for aborting the proposal
___
*[`crates/batcher/src/proposals_manager.rs` line 120 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6FmVgX78G0SXQ4QLE5:-O6KUIFi3h9AYeUr286Y:b-60fttm) ([raw file](https://github.com/starkware-libs/sequencer/blob/79a6d6557d8c0d48558fe68f9dc3f53eced8a77d/crates/batcher/src/proposals_manager.rs#L120)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think so, eventually we should be able to add to the stream even if the txs there are not consumed yet.
</blockquote></details>

Note that this stream feeds the block builder, not the stream that goes back to the user.
I don't think it should continue to fill the stream if the builder is busy.
___
*[`crates/batcher/src/proposals_manager.rs` line 116 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6GHYwX7DeBT4sHPucF:-O6KU5qt-_vZy-aInWJa:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L116)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think the channel should be created by the caller (he is the only one who should have access to the receiver).
Lets make the sender an input argument rather than returning the receiver.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 116 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6GbTJH-hrYBrRigjEn:-O6MbNGD0a2Yb5Bhd4hk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L116)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think in general the one who holds the receiver should be the one to create the channel and pass the sender around.

With this the function should look like:

```
async fn generate_block_proposal(...) {
    info!("Starting generation of new proposal.");
    self.set_proposal_in_generation(proposal_id).await?;

    let handle = tokio::spwan(self.generate_block(output_stream_content));

    Ok(...)
}

async fn generate_block(self, output_content_sender) {
     let block_builder = self.block_builder_factory.create_block_builder();
     let block_finished_sender, block_finished_receiver = ...;
     let input_tx_sender = block_builder.start(output_content_sender, block_finished_sender);

    let _ = tokio::select! { ... }
}
```
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 138 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6GmGEKE4c7cenqFfPE:-O6MbRJD0v1Wz-k5HXo0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L138)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please put the spawned code in a dedicated function.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 142 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6Gidtx-A-fo_L_qk8t:-O6LULlo1ayDt6AH7Vbs:b6ky5xk) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L142)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

feeder stopped doesn't necessarily mean we finished the proposal. The block builder can still be executing txs.
If the feeder failed, I guess we should do some cleanup and abort the task, returning an error, or we might even want to close the block with whatever we executed so far.

Anyway, I think we should close the block only when the block builder tells us it is finished.
</blockquote></details>

The feeder is an infinite loop - it stops only on error or if the builder finished.
If it fails the builder task will be cancelled
___
*[`crates/batcher/src/proposals_manager.rs` line 158 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6G_WJt5LlB173axdK4:-O6Mbn28AVRsjGLLsFUf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L158)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

To keep symmetry, I'd suggest to define a function clear_proposal_in_generation (the opposite of set_proposal_in_generation).
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 195 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6Ga_8y3oPLkCi_Cu4Z:-O6Mbrzu3SfYZ093LjJ4:b-lm6y9q) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L195)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think it's safer to send a signal to the builder, like an empty list, saying we're done.
</blockquote></details>

I decided to move the deadline responsibility to the builder, now it alone decides when it's done.
___
*[`crates/batcher/src/proposals_manager.rs` line 207 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6Gl7x45O57PlkZ5jrL:-O6McR9X-ZPEnVj9AadP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L207)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Even in a successful flow, we can have txs in the channel that were not included in the block.
The mempool does not delete the txs it sends to us, but put it in a staging area.
Add a todo to update the mempool with the required information (will probably happen in the commit proposal flow).
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 110 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O5qyuvhBcyFsUkgcGoS:-O6MjZ-0-b0a_wGLWr5q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/59d905a3b4f8c09a6b0b68a1c4f528f0b2706a5d/crates/batcher/src/proposals_manager_test.rs#L110)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it is more readable now, 
though still, I think you should define the vector at the beginning, clone it for the mock mempool, and then use it again for the assert.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager_test.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6Gi-byCEyF2xIXQCxi:-O6McU4TA1LYsvx1e0Dg:b7lj54p) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca [...]

2024-09-17 20:29 UTC, dafnamatsry requested changes
> Reviewed 1 of 3 files at r10, 3 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 4 of 7 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 89 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O70P6Vf7u9qpLNhWPxq:-O70P6Vf7u9qpLNhWPxr:b-elj36o) ([raw file](https://github.com/starkware-libs/sequencer/blob/2fd263e29de5a117a87641299b37c458c459281a/crates/batcher/src/proposal_manager.rs#L89)):*
> ```XML
>     // Use a factory object, to be able to mock BlockBuilder in tests.
>     block_builder_factory: Arc<dyn BlockBuilderFactoryTrait>,
>     active_proposal_handle: Option<tokio::task::JoinHandle<ProposalsManagerResult<()>>>,
> ```

Please move next to `active_proposal`.
Consider even defining a `ActiveProposalInfo` struct.



_Code quote:_
```XML
 active_proposal_handle: Option<tokio::task::JoinHandle<ProposalsManagerResult<()>>>,
```
___
*[`crates/batcher/src/proposal_manager.rs` line 195 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O70X3h2Dwa143flsq7S:-O70X3h2Dwa143flsq7T:b-1lmn1) ([raw file](https://github.com/starkware-libs/sequencer/blob/2fd263e29de5a117a87641299b37c458c459281a/crates/batcher/src/proposal_manager.rs#L195)):*
> ```XML
>                 mempool_tx_stream,
>                 self.output_content_sender.clone(),
>             );
> ```

We can do something similar for mempool txs sender/receiver: the the receiving end will create the channel, in this case `block_builder`, and will return a sender.



_Code quote:_
```XML
            let building_future = self.block_builder.build_block(
                self.deadline,
                mempool_tx_stream,
                self.output_content_sender.clone(),
            );
```
___
*[`crates/batcher/src/proposal_manager.rs` line 198 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O70_RV-0YRiSEvQrsm1:-O70_RV-0YRiSEvQrsm2:b5ze1zv) ([raw file](https://github.com/starkware-libs/sequencer/blob/2fd263e29de5a117a87641299b37c458c459281a/crates/batcher/src/proposal_manager.rs#L198)):*
> ```XML
>             pin!(building_future);
>             loop {
>                 select! {
> ```

I still think we should wait only on the `block_builder.build_block()` future.

In order to do that, the block_builder can expose an `abort` function that we can call if we fail to feed more mempool txs.

With the current approach, what happens to the builder if `feed_more_mempool_txs` fails? does it continue the execution of txs it already has? Ending the process explicitly with `block_builder.abort()` or `block_builder.close_block()` is safer and more elegant. 
___
*[`crates/batcher/src/proposals_manager.rs` line 120 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6FmVgX78G0SXQ4QLE5:-O70cliJ-u4L4wqkJTWO:b-9ksc0q) ([raw file](https://github.com/starkware-libs/sequencer/blob/79a6d6557d8c0d48558fe68f9dc3f53eced8a77d/crates/batcher/src/proposals_manager.rs#L120)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Note that this stream feeds the block builder, not the stream that goes back to the user.
I don't think it should continue to fill the stream if the builder is busy.
</blockquote></details>

The builder limitations and requirements (execution resources, chunks size) are not the same as the mempool request limitations (network, etc).
It might be the case that they will eventually have the same values, but I think it makes sense to have different configurations for them.
___
*[`crates/batcher/src/proposals_manager.rs` line 142 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6Gidtx-A-fo_L_qk8t:-O70ejLa0nEFSwhFNQ6r:b-apayz0) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L142)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The feeder is an infinite loop - it stops only on error or if the builder finished.
If it fails the builder task will be cancelled
</blockquote></details>

See my comment above.


<!-- Sent from Reviewable.io -->

2024-09-22 13:36 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 1 of 7 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 89 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O70P6Vf7u9qpLNhWPxq:-O7OiycA16n_34c5Sf1n:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2fd263e29de5a117a87641299b37c458c459281a/crates/batcher/src/proposal_manager.rs#L89)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move next to `active_proposal`.
Consider even defining a `ActiveProposalInfo` struct.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 195 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O70X3h2Dwa143flsq7S:-O7OjTNf98Ajd5pHe86Y:bzdim5m) ([raw file](https://github.com/starkware-libs/sequencer/blob/2fd263e29de5a117a87641299b37c458c459281a/crates/batcher/src/proposal_manager.rs#L195)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We can do something similar for mempool txs sender/receiver: the the receiving end will create the channel, in this case `block_builder`, and will return a sender.
</blockquote></details>

But in the future we expect to receive a stream from the mempool and just pass it to the block builder, which is more like the current code.
___
*[`crates/batcher/src/proposal_manager.rs` line 198 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O70_RV-0YRiSEvQrsm1:-O7OkEjn3tA3b1zXUpyO:b8n6l4g) ([raw file](https://github.com/starkware-libs/sequencer/blob/2fd263e29de5a117a87641299b37c458c459281a/crates/batcher/src/proposal_manager.rs#L198)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I still think we should wait only on the `block_builder.build_block()` future.

In order to do that, the block_builder can expose an `abort` function that we can call if we fail to feed more mempool txs.

With the current approach, what happens to the builder if `feed_more_mempool_txs` fails? does it continue the execution of txs it already has? Ending the process explicitly with `block_builder.abort()` or `block_builder.close_block()` is safer and more elegant.
</blockquote></details>

Talked about it (added todo in https://github.com/starkware-libs/sequencer/pull/790)
___
*[`crates/batcher/src/proposals_manager.rs` line 120 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6FmVgX78G0SXQ4QLE5:-O7Onor20rOix6S1CDu8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/79a6d6557d8c0d48558fe68f9dc3f53eced8a77d/crates/batcher/src/proposals_manager.rs#L120)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

The builder limitations and requirements (execution resources, chunks size) are not the same as the mempool request limitations (network, etc).
It might be the case that they will eventually have the same values, but I think it makes sense to have different configurations for them.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 142 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O6Gidtx-A-fo_L_qk8t:-O7Onrng2LIlYwlp6ltc:b-karkvk) ([raw file](https://github.com/starkware-libs/sequencer/blob/5989054410b60e145c9a279ca8992b6e609a8886/crates/batcher/src/proposals_manager.rs#L142)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

See my comment above.
</blockquote></details>

talked


<!-- Sent from Reviewable.io -->

2024-09-23 09:17 UTC, dafnamatsry requested changes
> Reviewed 1 of 6 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 5 of 7 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 32 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7SYIOaDnbTBAYxXVOz:-O7SYIOaDnbTBAYxXVP-:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager.rs#L32)):*
> ```XML
>         // TODO: Get correct default values.
>         Self {
>             block_builder_input_stream_bound: 100,
> ```





_Suggestion:_
```XML
block_next_txs_buffer_size:
```
___
*[`crates/batcher/src/proposal_manager.rs` line 250 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7SXJJPCYmv3BkATN_G:-O7SXJJPCYmv3BkATN_H:b-iu037j) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager.rs#L250)):*
> ```XML
>             );
>             for tx in mempool_txs {
>                 if let Err(e) = mempool_tx_sender.send(tx).await.map_err(|err| {
> ```

IIUC this can only happen if the receiving end of a channel is disconnected.
Maybe `panic` would be better here...



_Code quote:_
```XML
if let Err(e) = mempool_tx_sender.send(tx).await.map_err(|err| {
```
___
*[`crates/batcher/src/proposal_manager.rs` line 251 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7SXeImEYuQvAnGv9wP:-O7SXeImEYuQvAnGv9wQ:b-3gnuep) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager.rs#L251)):*
> ```XML
>             for tx in mempool_txs {
>                 if let Err(e) = mempool_tx_sender.send(tx).await.map_err(|err| {
>                     // TODO: should we return the rest of the txs to the mempool?
> ```

No, the mempool will be updated on `decision_reached` with all the txs that were included in the accepted block.



_Code quote:_
```XML
// TODO: should we return the rest of the txs to the mempool?
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 65 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7Sz8Tw0dd3xrWDlaAm:-O7Sz8Tw0dd3xrWDlaAn:bny51ph) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager_test.rs#L65)):*
> ```XML
> ) {
>     let n_txs = 2 * proposal_manager_config.max_txs_per_mempool_request;
>     block_builder_factory.expect_create_block_builder().once().returning(move || {
> ```

Will the following work:

```
    let mut mock_block_builder = Arc::new(MockBlockBuilderTraitWrapper::new());
    block_builder_factory.expect_create_block_builder().once().returning(move || {
        mock_block_builder
    });
    
    mock_block_builder.expect_build_block().return_once(...);
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 77 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7T3ggT1goEorkjxIoL:-O7T3ggT1goEorkjxIoM:bcdzhnq) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager_test.rs#L77)):*
> ```XML
>                 .boxed()
>             },
>         );
> ```

Please move to a `simulate_build_block(mock_block_builder, ...)` function.



_Code quote:_
```XML
        mock_block_builder.expect_build_block().return_once(
            move |deadline, mempool_tx_stream, output_content_sender| {
                simulate_block_builder(
                    deadline,
                    mempool_tx_stream,
                    output_content_sender,
                    Some(n_txs),
                )
                .boxed()
            },
        );
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 103 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7T7I8MBYgr0w3s_WKM:-O7T7I8NEPw3tnPi3qYr:bwi8rjj) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager_test.rs#L103)):*
> ```XML
> 
>     assert_matches!(proposal_manager.await_active_proposal().await, Some(Ok(())));
>     let v: Vec<_> = stream.collect().await;
> ```

(same below)



_Suggestion:_
```XML
proposal_content
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 211 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7T8DtmAND2sS1HmgTp:-O7T8DtmAND2sS1HmgTq:bwd7q20) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager_test.rs#L211)):*
> ```XML
>     );
> }
> ```

Please add tests for: deadline reached, mempool failures, and myabe other possible errors?

Can be done in a separate PR.


<!-- Sent from Reviewable.io -->

2024-09-23 10:23 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 3 of 7 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 32 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7SYIOaDnbTBAYxXVOz:-O7TJjmo9DBmtuWrT4WZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager.rs#L32)):*
> ```XML
>         // TODO: Get correct default values.
>         Self {
>             block_builder_input_stream_bound: 100,
> ```

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 250 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7SXJJPCYmv3BkATN_G:-O7THCue4MOMSDqjudfc:b6pvtg0) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager.rs#L250)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

IIUC this can only happen if the receiving end of a channel is disconnected.
Maybe `panic` would be better here...
</blockquote></details>

Don't you prefer to abort the proposal without crashing the batcher?
___
*[`crates/batcher/src/proposal_manager.rs` line 251 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7SXeImEYuQvAnGv9wP:-O7TKCI61kh-ezaTD-c1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager.rs#L251)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

No, the mempool will be updated on `decision_reached` with all the txs that were included in the accepted block.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 65 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7Sz8Tw0dd3xrWDlaAm:-O7TIDbWA5Yx6dl8JeZk:b-9r5mpc) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager_test.rs#L65)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Will the following work:

```
    let mut mock_block_builder = Arc::new(MockBlockBuilderTraitWrapper::new());
    block_builder_factory.expect_create_block_builder().once().returning(move || {
        mock_block_builder
    });
    
    mock_block_builder.expect_build_block().return_once(...);
```
</blockquote></details>

No, because Arc doesn't work well with mutability.
I think I can find ways to get around this, but I prefer the more explicit.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 77 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7T3ggT1goEorkjxIoL:-O7TN8Ak-eo-18F3YBSL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager_test.rs#L77)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move to a `simulate_build_block(mock_block_builder, ...)` function.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 103 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7T7I8MBYgr0w3s_WKM:-O7TNP1m1fXh1OtvrLtE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager_test.rs#L103)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

(same below)
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 211 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7T8DtmAND2sS1HmgTp:-O7TN_ls2OrzTIfr-XhF:bbwy7kd) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager_test.rs#L211)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add tests for: deadline reached, mempool failures, and myabe other possible errors?

Can be done in a separate PR.
</blockquote></details>

Will add in a separate PR


<!-- Sent from Reviewable.io -->

2024-09-23 10:43 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541#-:-O7TTfr691Ao-UtBb2-Z:bnfp4nl)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 250 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7SXJJPCYmv3BkATN_G:-O7TSVNhAbgmMg3xFTd0:b-gqnaut) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager.rs#L250)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Don't you prefer to abort the proposal without crashing the batcher?
</blockquote></details>

When there is a real bug in the code, I personally prefer to crash the batcher.


<!-- Sent from Reviewable.io -->

2024-09-23 11:49 UTC, Yael-Starkware requested changes
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 98 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7TgW9z2r91o9Q55xhl:-O7TgW9z2r91o9Q55xhm:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b87a5be48755a9c8be4fde84a1c5e36ebfd5d611/crates/batcher/src/proposal_manager_test.rs#L98)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn concecutive_proposal_generations_success(
> ```





_Suggestion:_
```XML
consecutive
```


<!-- Sent from Reviewable.io -->

2024-09-23 13:44 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 250 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7SXJJPCYmv3BkATN_G:-O7TwDobDZbLRpvONkF4:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/11997ba27802f23a09c3a680b4741103dc5bdb96/crates/batcher/src/proposal_manager.rs#L250)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

When there is a real bug in the code, I personally prefer to crash the batcher.
</blockquote></details>

done
___
*[`crates/batcher/src/proposal_manager_test.rs` line 98 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/541#-O7TgW9z2r91o9Q55xhl:-O7TwEvh0lVkFqyLT2VK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b87a5be48755a9c8be4fde84a1c5e36ebfd5d611/crates/batcher/src/proposal_manager_test.rs#L98)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn concecutive_proposal_generations_success(
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-24 07:28 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541#-:-O7XvXw-84Ez5yalPyvd:bnfp4nl)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-24 07:31 UTC, Yael-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2024-09-24 08:00 UTC, Yael-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2024-09-24 08:27 UTC, ArniStarkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/541)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-09-24 10:02 UTC, merged