feat(batcher): generate proposal from a batcher server callback
starkware-libs/sequencer pull request #565
Opened 2024-08-22 12:13 UTC by yair-starkware

2024-08-25 07:13 UTC, matan-starkware reviewed
> Reviewed 4 of 4 files at r2, 3 of 4 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @lev-starkware, and @yair-starkware)

___
*[`crates/batcher_types/src/communication.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O57NGxsAlecdZPy1w5v:-O57NGxsAlecdZPy1w5w:buq2fm1) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6fdaf31af94f960fa1962e48971afd6f08adf56/crates/batcher_types/src/communication.rs#L54)):*
> ```XML
> #[async_trait]
> impl BatcherClient for LocalBatcherClientImpl {
>     async fn build_proposal(&self, input: BuildProposalInput) -> BatcherClientResult<()> {
> ```

so this doesn't return anything, makes sense pre streaming. But how do we get the stream of info? Shouldn't there be another API?



_Code quote:_
```XML
   async fn build_proposal(&self, input: BuildProposalInput) -> BatcherClientResult<()> {
```


<!-- Sent from Reviewable.io -->

2024-08-25 07:16 UTC, yair-starkware commented
*[`crates/batcher_types/src/communication.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O57NGxsAlecdZPy1w5v:-O57NuhR3HkkhEkK7K93:bdz4ge6) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6fdaf31af94f960fa1962e48971afd6f08adf56/crates/batcher_types/src/communication.rs#L54)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

so this doesn't return anything, makes sense pre streaming. But how do we get the stream of info? Shouldn't there be another API?
</blockquote></details>

I am working on implementing `get_stream_content` in another PR


<!-- Sent from Reviewable.io -->

2024-09-01 13:42 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: 0 of 14 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @lev-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 26 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hPJsX9mUJ41MQzEiI:-O5hjRdL6Hjpj3-x63w1:b6sueym) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L26)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please accept the `proposal_manager` as an argument, to be able mock it in tests.
</blockquote></details>

This is in the next PR
___
*[`crates/batcher/src/batcher.rs` line 29 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hQV2XAAk9J4BCYnbt:-O5hjm6lCyP9mrG2AMVi:b8tzhpx) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L29)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think both clones here can be removed.
</blockquote></details>

No, because they are consumed in `ProposalsManager::new`.
___
*[`crates/batcher/src/batcher.rs` line 44 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hUomdBf0KvpJCoGbX:-O5hk7G_5970Swyyll9l:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L44)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Thinking about it now, I think it would make more sense to put the ID generation in the proposal manager (make it a return value of`generate_block_generation` if necessary). 
It is purely an id for internal management of the proposals and not part of the batcher API.
</blockquote></details>

Done
___
*[`crates/batcher/src/batcher.rs` line 65 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hYA5t4XawgjcRVD37:-O5hlURk0P2IpQ9zH9Oq:b-12g5ws) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L65)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think MempoolError is an informative error for the batcher clients and should not be converted to InternalError.
</blockquote></details>

How can they handle this error?
___
*[`crates/batcher/src/batcher.rs` line 66 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hWkND6WzTKWLGss-t:-O5hlbjU-NYfqP_m4TOj:b-82hqle) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L66)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please implement it with `From`.
</blockquote></details>

I can't because in different callbacks there will be a different mapping.
I can make separate error types for each callback, but not sure it is better
___
*[`crates/batcher/src/config.rs` line 13 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hPqfz1hgTIl626rxH:-O5hly6p5Rbkr4ePZFgJ:bib2gsw) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/config.rs#L13)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I don't think the `ProposalManagerConfig` should be nested in the `BatcherConfig`.
The proposal manager should be injected to the batcher with dependency injection.
</blockquote></details>

Why not? it's a private module of the batcher.
The fact that we mock it for tests doesn't mean others should handle it differently.
___
*[`crates/batcher_types/src/batcher_types.rs` line 17 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hbA-EDOypq92H0tmh:-O5hmxp08MaW4fiKWG4i:b6u89mu) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher_types/src/batcher_types.rs#L17)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What is the difference between DateTime and Instant?
Why not just accept Instant?
</blockquote></details>

Instant is not serializable and not human-readable.


<!-- Sent from Reviewable.io -->

2024-09-04 13:27 UTC, Yael-Starkware requested changes
> Reviewed 10 of 12 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: 10 of 14 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @lev-starkware, @matan-starkware, and @yair-starkware)

___
*[`config/mempool/default_config.json` line 8 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5wnYPl8fUZBc9xGXho:-O5wnYPl8fUZBc9xGXhp:b-muaoax) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/config/mempool/default_config.json#L8)):*
> ```JSON
>   },
>   "batcher_config.proposals_manager.outstream_content_buffer_size": {
>     "description": "Maximum items to add to the outstream buffer before blocking",
> ```

what does blocking mean in this context?



_Code quote:_
```JSON
Maximum items to add to the outstream buffer before blocking
```
___
*[`crates/batcher/src/batcher.rs` line 65 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hYA5t4XawgjcRVD37:-O5wlA8t0NAsT-ElwMp1:b-c3aobk) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L65)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

How can they handle this error?
</blockquote></details>

IMO, all errors should be transparent. Since the error is not returned to the end user, it doesn't need to comply with any spec.
Moreover, it will be easier to debug errors in the system level with all the required information.
and also the code will be cleaner.
___
*[`crates/batcher/src/batcher.rs` line 36 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5xAfBq3lWky4PN9Ogc:-O5xAfBq3lWky4PN9Ogd:bx3znpt) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/batcher.rs#L36)):*
> ```XML
>         build_proposal_input: BuildProposalInput,
>     ) -> Result<(), BatcherError> {
>         // TODO: Save the stream for later use.
> ```

what is the later use?
maybe for repropose_block, but I believe the stream should be stored inside the ProposalsManager , per proposal, and not in the batcher.



_Code quote:_
```XML
// TODO: Save the stream for later use.
```
___
*[`crates/batcher/src/proposals_manager.rs` line 118 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5xBSpD0zKpvY2JtD8M:-O5xBSpD0zKpvY2JtD8N:boxcz63) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L118)):*
> ```XML
>     ) -> ProposalsManagerResult<ReceiverStream<Transaction>> {
>         let proposal_id = self.proposal_id_marker;
>         self.proposal_id_marker += 1;
> ```

I think the proposal_id should be a part of the request sent from the orchestrator.



_Code quote:_
```XML
self.proposal_id_marker += 1;
```
___
*[`crates/batcher/src/proposals_manager.rs` line 119 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5wo2Db0A2Kvrcza0B5:-O5wo2Db0A2Kvrcza0B6:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L119)):*
> ```XML
>         let proposal_id = self.proposal_id_marker;
>         self.proposal_id_marker += 1;
>         info!("Starting generation of new proposal.");
> ```





_Suggestion:_
```XML
Starting generation of a new proposal, id = 
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 11 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5xCNfsCeG5cFhLu6vj:-O5xCNfsCeG5cFhLu6vk:b-srzy1s) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher_types/src/batcher_types.rs#L11)):*
> ```XML
> #[derive(Debug, Serialize, Deserialize)]
> pub struct BuildProposalInput {
>     pub stream_id: StreamId,
> ```

what is the streamId? 



_Code quote:_
```XML
stream_id: StreamId,
```


<!-- Sent from Reviewable.io -->

2024-09-04 13:32 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: 10 of 14 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @lev-starkware, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 11 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5xCNfsCeG5cFhLu6vj:-O5xE8fG8A7r_pIZJoBr:bsla68q) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher_types/src/batcher_types.rs#L11)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what is the streamId?
</blockquote></details>

maybe this is the proposal_id we should use.


<!-- Sent from Reviewable.io -->

2024-09-05 07:51 UTC, dafnamatsry requested changes
> Reviewed 1 of 5 files at r12, 6 of 12 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: 12 of 14 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @lev-starkware, @matan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 29 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hQV2XAAk9J4BCYnbt:-O606rVnADvlOl7c8ldQ:b-npiwcy) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L29)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

No, because they are consumed in `ProposalsManager::new`.
</blockquote></details>

In the next PR, when the proposal manger is injected, please make sure to remove the clones.
___
*[`crates/batcher/src/batcher.rs` line 65 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hYA5t4XawgjcRVD37:-O607BeD2dFwdZbIBkHh:b-rb1pl1) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L65)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

IMO, all errors should be transparent. Since the error is not returned to the end user, it doesn't need to comply with any spec.
Moreover, it will be easier to debug errors in the system level with all the required information.
and also the code will be cleaner.
</blockquote></details>

+1 on making the errors transparent, and let the client choose what to do with it.
___
*[`crates/batcher/src/config.rs` line 13 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hPqfz1hgTIl626rxH:-O607R6g4R3AFVdjVz2N:bjeak0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/config.rs#L13)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not? it's a private module of the batcher.
The fact that we mock it for tests doesn't mean others should handle it differently.
</blockquote></details>

Why if the proposal manager is injected, the batcher should also hold it's config? The Proposal manger is already holding the config.
Now there is a duplication.
___
*[`crates/batcher/src/proposals_manager.rs` line 89 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O608gRhApRgPcGESl99:-O608gRhApRgPcGESl9A:bk8xmwy) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L89)):*
> ```XML
>     // Use a factory object, to be able to mock BlockBuilder in tests.
>     block_builder_factory: Arc<dyn BlockBuilderFactory>,
>     proposal_id_marker: ProposalId,
> ```

Shouldn't it be also protected by a Mutex?



_Code quote:_
```XML
proposal_id_marker: ProposalId,
```
___
*[`crates/batcher/src/proposals_manager.rs` line 105 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O608MqSAX8IXUqZurDq:-O608MqSAX8IXUqZurDr:b8o5n49) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L105)):*
> ```XML
>             proposal_in_generation: Arc::new(Mutex::new(None)),
>             block_builder_factory,
>             proposal_id_marker: ProposalId::default(),
> ```

Please make it explicitly `0`.



_Code quote:_
```XML
ProposalId::default()
```
___
*[`crates/batcher/src/proposals_manager.rs` line 118 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5xBSpD0zKpvY2JtD8M:-O608rds-9QxE_1eMWFe:b-a8jbqj) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L118)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think the proposal_id should be a part of the request sent from the orchestrator.
</blockquote></details>

The orchestrator used a stream ID, which is slightly different. We can talk about it in the meeting today. 


<!-- Sent from Reviewable.io -->

2024-09-08 09:36 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: 12 of 14 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @lev-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`config/mempool/default_config.json` line 8 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5wnYPl8fUZBc9xGXho:-O6FwLMn68m8FDkabSMc:bqpr07g) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/config/mempool/default_config.json#L8)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what does blocking mean in this context?
</blockquote></details>

Edited the documentation, hopefully now it is more clear
___
*[`crates/batcher/src/batcher.rs` line 29 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hQV2XAAk9J4BCYnbt:-O6Fx1T3-b2Ve5ig9qGG:b-vrqwm9) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L29)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

In the next PR, when the proposal manger is injected, please make sure to remove the clones.
</blockquote></details>

I don't think the config is going to be injected within the instance, it is still going to be a member of the batcher config
___
*[`crates/batcher/src/batcher.rs` line 65 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hYA5t4XawgjcRVD37:-O6FxIJ23g7A6_84sNd5:b-wn9ptv) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L65)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

+1 on making the errors transparent, and let the client choose what to do with it.
</blockquote></details>

I disagree here.
Within the context of the client it shouldn't care about these errors
___
*[`crates/batcher/src/batcher.rs` line 36 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5xAfBq3lWky4PN9Ogc:-O6FxbQj3_NYA6_7mx6T:b-krvg18) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/batcher.rs#L36)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what is the later use?
maybe for repropose_block, but I believe the stream should be stored inside the ProposalsManager , per proposal, and not in the batcher.
</blockquote></details>

The consensus needs to get this stream in the `get_stream_content` api
___
*[`crates/batcher/src/config.rs` line 13 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hPqfz1hgTIl626rxH:-O6Fxq-x9Ua2CGQ21J-L:b-66nsf0) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/config.rs#L13)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why if the proposal manager is injected, the batcher should also hold it's config? The Proposal manger is already holding the config.
Now there is a duplication.
</blockquote></details>

But in the setup we create a Batcher configuration, I don't want to create also a ProposalsManager configuration which is a private module
___
*[`crates/batcher/src/proposals_manager.rs` line 89 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O608gRhApRgPcGESl99:-O6FyN4y03dPAn6tEOrN:b-ugnj9u) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L89)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Shouldn't it be also protected by a Mutex?
</blockquote></details>

I don't know how it happens, but the server API has a `&mut self` in the callbacks which makes safe to change the value without mutex
___
*[`crates/batcher/src/proposals_manager.rs` line 105 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O608MqSAX8IXUqZurDq:-O6FyrhE2AsLQ_WW3wTF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L105)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please make it explicitly `0`.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 118 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5xBSpD0zKpvY2JtD8M:-O6Fz4Eq5vzhK23VrIsp:b-karkvk) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L118)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

The orchestrator used a stream ID, which is slightly different. We can talk about it in the meeting today.
</blockquote></details>

talked
___
*[`crates/batcher/src/proposals_manager.rs` line 119 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5wo2Db0A2Kvrcza0B5:-O6FzB3q3RhYYxY-rKdc:b561qg5) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L119)):*
> ```XML
>         let proposal_id = self.proposal_id_marker;
>         self.proposal_id_marker += 1;
>         info!("Starting generation of new proposal.");
> ```

Done, but FYI the id is a field of the span so it is not really necessary
___
*[`crates/batcher_types/src/batcher_types.rs` line 11 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5xCNfsCeG5cFhLu6vj:-O6FzOtY2qFF9Cl5Tdv9:b-karkvk) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher_types/src/batcher_types.rs#L11)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

maybe this is the proposal_id we should use.
</blockquote></details>

talked


<!-- Sent from Reviewable.io -->

2024-09-09 05:52 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: 7 of 14 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @lev-starkware, @matan-starkware, and @yair-starkware)

___
*[`config/mempool/default_config.json` line 8 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5wnYPl8fUZBc9xGXho:-O6KDHIP9-qmmj0MAu-Z:bcu0t4t) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/config/mempool/default_config.json#L8)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Edited the documentation, hopefully now it is more clear
</blockquote></details>

I don't see any change
___
*[`crates/batcher/src/batcher.rs` line 66 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hWkND6WzTKWLGss-t:-O6KKLmKE51Sa-b215kg:b-d8lrwa) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L66)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I can't because in different callbacks there will be a different mapping.
I can make separate error types for each callback, but not sure it is better
</blockquote></details>

why would the mapping be different? 
___
*[`crates/batcher/src/batcher.rs` line 44 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O6KK4t1Bx_jjQID4Iwd:-O6KK4t1Bx_jjQID4Iwe:bwwn08z) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7192ace8bdae39b0ec7a86361c547c9705ace28/crates/batcher/src/batcher.rs#L44)):*
> ```XML
>                                 deadline: build_proposal_input.deadline,
>                             }
>                         })?,
> ```

compute the tokio_instant separately before you call generate_block_proposal



_Code quote:_
```XML
                    tokio::time::Instant::from_std(
                        build_proposal_input.deadline_as_instant().map_err(|_| {
                            BatcherError::TimeToDeadlineError {
                                deadline: build_proposal_input.deadline,
                            }
                        })?,
```
___
*[`crates/batcher/src/proposals_manager.rs` line 119 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5wo2Db0A2Kvrcza0B5:-O6KFIkC6f89OVGhoC0Y:b-dy8myy) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L119)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done, but FYI the id is a field of the span so it is not really necessary
</blockquote></details>

how do I see that it is part of the span?


<!-- Sent from Reviewable.io -->

2024-09-09 05:56 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: 7 of 14 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @lev-starkware, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 13 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O6KL65p9_E88DQ5HagC:-O6KL65p9_E88DQ5HagD:b-ds1nyf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7192ace8bdae39b0ec7a86361c547c9705ace28/crates/batcher_types/src/batcher_types.rs#L13)):*
> ```XML
>     pub stream_id: StreamId,
>     pub deadline: chrono::DateTime<Utc>,
>     pub height: BlockNumber,
> ```

This block_hash-10 is missing here, but not mandatory atm, I can add it later.



_Suggestion:_
```XML
pub height: BlockNumber,
pub retrospective_block_hash: Option<BlockNumberHashPair>,
```


<!-- Sent from Reviewable.io -->

2024-09-23 15:16 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: 0 of 16 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @lev-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`config/mempool/default_config.json` line 8 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5wnYPl8fUZBc9xGXho:-O7URZ8O6Y9SFirJbcIF:b2nhl01) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/config/mempool/default_config.json#L8)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I don't see any change
</blockquote></details>

Now
___
*[`crates/batcher/src/batcher.rs` line 44 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O6KK4t1Bx_jjQID4Iwd:-O7UNW9_6FSHwHKezAe3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7192ace8bdae39b0ec7a86361c547c9705ace28/crates/batcher/src/batcher.rs#L44)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

compute the tokio_instant separately before you call generate_block_proposal
</blockquote></details>

Done.
___
*[`crates/batcher_types/src/batcher_types.rs` line 13 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O6KL65p9_E88DQ5HagC:-O7UNc-U-AAPZWUm6n7Q:b-m3p24o) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7192ace8bdae39b0ec7a86361c547c9705ace28/crates/batcher_types/src/batcher_types.rs#L13)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

This block_hash-10 is missing here, but not mandatory atm, I can add it later.
</blockquote></details>

Will add when we connect the PRs
___
*[`crates/batcher/src/proposals_manager.rs` line 119 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5wo2Db0A2Kvrcza0B5:-O7UQmQv4xLYgEzweEQr:bojqof2) ([raw file](https://github.com/starkware-libs/sequencer/blob/075508b11aa36ea519894a2fa7ed80cb5ba6fff2/crates/batcher/src/proposals_manager.rs#L119)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

how do I see that it is part of the span?
</blockquote></details>

When instrumenting a function it adds the parameters as fields of the span


<!-- Sent from Reviewable.io -->

2024-09-23 15:20 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: 0 of 16 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @lev-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 66 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hWkND6WzTKWLGss-t:-O7USLX-78d4a_8Cqbnu:b-uffbff) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L66)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why would the mapping be different?
</blockquote></details>

For example in `decision_reached` you shouldn't get `AlreadyGeneratingProposal` 


<!-- Sent from Reviewable.io -->

2024-09-30 10:57 UTC, dafnamatsry requested changes
> Reviewed 1 of 5 files at r16, 6 of 16 files at r17, 3 of 6 files at r19, 2 of 3 files at r20, 5 of 5 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: all files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @lev-starkware, @matan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`config/mempool/default_config.json` line 3 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O81Ju5o34B8sF8YYfqC:-O81Ju5o34B8sF8YYfqD:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/774c9a3b8c366669f750b359e8c749da2099ae22/config/mempool/default_config.json#L3)):*
> ```JSON
> {
>   "batcher_config.outstream_content_buffer_size": {
>     "description": "Maximum items to add to the outstream buffer before blocking further filling of the stream",
> ```





_Suggestion:_
```JSON
Maximum items to add to the outstream buffer before blocking further filling of the stream.
```
___
*[`config/mempool/default_config.json` line 8 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O81K7k9CpRAB0cVWX2C:-O81K7k9CpRAB0cVWX2D:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/774c9a3b8c366669f750b359e8c749da2099ae22/config/mempool/default_config.json#L8)):*
> ```JSON
>   },
>   "batcher_config.proposal_manager.block_builder_next_txs_buffer_size": {
>     "description": "Maximum transactions to fill in the stream buffer for the block builder before further filling of the stream.",
> ```





_Suggestion:_
```JSON
Maximum transactions to fill in the stream buffer for the block builder before blocking further filling of the stream.
```
___
*[`config/mempool/default_config.json` line 13 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O81KHOA9J3YsAyJcHE2:-O81KHOA9J3YsAyJcHE3:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/774c9a3b8c366669f750b359e8c749da2099ae22/config/mempool/default_config.json#L13)):*
> ```JSON
>   },
>   "batcher_config.proposal_manager.max_txs_per_mempool_request": {
>     "description": "Maximum transactions to get from the mempool per iteration of proposal generation.",
> ```





_Suggestion:_
```JSON
Maximum transactions to get from the mempool in a single get_txs request.
```
___
*[`crates/batcher/src/batcher.rs` line 66 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hWkND6WzTKWLGss-t:-O81LL8NCJz9MBCMF3Lt:b-gwrqtx) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L66)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

For example in `decision_reached` you shouldn't get `AlreadyGeneratingProposal`
</blockquote></details>

In that case consider splitting to multiple error types (e.g.`BuildBlockProposalError` and `CommitProposalError`). I think it would make a cleaner code.
___
*[`crates/batcher/src/proposal_manager.rs` line 88 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O81ZOInCn3chfIJxQOi:-O81ZOInCn3chfIJxQOj:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/774c9a3b8c366669f750b359e8c749da2099ae22/crates/batcher/src/proposal_manager.rs#L88)):*
> ```XML
>     // Use a factory object, to be able to mock BlockBuilder in tests.
>     block_builder_factory: Arc<dyn BlockBuilderFactoryTrait>,
>     // The list of all proposals that were generated.
> ```





_Suggestion:_
```XML
// The list of all proposals that were generated in the current height.
```


<!-- Sent from Reviewable.io -->

2024-09-30 11:13 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: all files reviewed, 13 unresolved discussions (waiting on @ArniStarkware, @lev-starkware, @matan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 20 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O81cah-7fGhmxa07vQj:-O81cah-7fGhmxa07vQk:b9ynqfc) ([raw file](https://github.com/starkware-libs/sequencer/blob/774c9a3b8c366669f750b359e8c749da2099ae22/crates/batcher/src/batcher.rs#L20)):*
> ```XML
> }
> 
> impl Batcher {
> ```

What about tests?


<!-- Sent from Reviewable.io -->

2024-10-01 06:48 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: all files reviewed, 13 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @lev-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`config/mempool/default_config.json` line 3 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O81Ju5o34B8sF8YYfqC:-O85nHyqDnIk14myAniy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/774c9a3b8c366669f750b359e8c749da2099ae22/config/mempool/default_config.json#L3)):*
> ```JSON
> {
>   "batcher_config.outstream_content_buffer_size": {
>     "description": "Maximum items to add to the outstream buffer before blocking further filling of the stream",
> ```

Done.
___
*[`config/mempool/default_config.json` line 8 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O81K7k9CpRAB0cVWX2C:-O85nPic-hEqtsGu7fF9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/774c9a3b8c366669f750b359e8c749da2099ae22/config/mempool/default_config.json#L8)):*
> ```JSON
>   },
>   "batcher_config.proposal_manager.block_builder_next_txs_buffer_size": {
>     "description": "Maximum transactions to fill in the stream buffer for the block builder before further filling of the stream.",
> ```

Done.
___
*[`config/mempool/default_config.json` line 13 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O81KHOA9J3YsAyJcHE2:-O85nUjC9mIynZTvbh36:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/774c9a3b8c366669f750b359e8c749da2099ae22/config/mempool/default_config.json#L13)):*
> ```JSON
>   },
>   "batcher_config.proposal_manager.max_txs_per_mempool_request": {
>     "description": "Maximum transactions to get from the mempool per iteration of proposal generation.",
> ```

Done.
___
*[`crates/batcher/src/batcher.rs` line 66 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O5hWkND6WzTKWLGss-t:-O81e22-9CCojX6ZY-D0:bs5cmwk) ([raw file](https://github.com/starkware-libs/sequencer/blob/c418cb016f09032ee6a2b11b3c702731bad43e3c/crates/batcher/src/batcher.rs#L66)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

In that case consider splitting to multiple error types (e.g.`BuildBlockProposalError` and `CommitProposalError`). I think it would make a cleaner code.
</blockquote></details>

Done in a later PR: https://github.com/starkware-libs/sequencer/pull/1105
___
*[`crates/batcher/src/batcher.rs` line 20 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O81cah-7fGhmxa07vQj:-O85nYzD24WzTJ9zx_km:b-karkvk) ([raw file](https://github.com/starkware-libs/sequencer/blob/774c9a3b8c366669f750b359e8c749da2099ae22/crates/batcher/src/batcher.rs#L20)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What about tests?
</blockquote></details>

talked
___
*[`crates/batcher/src/proposal_manager.rs` line 88 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O81ZOInCn3chfIJxQOi:-O85nxzd9GXbN-6niWLc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/774c9a3b8c366669f750b359e8c749da2099ae22/crates/batcher/src/proposal_manager.rs#L88)):*
> ```XML
>     // Use a factory object, to be able to mock BlockBuilder in tests.
>     block_builder_factory: Arc<dyn BlockBuilderFactoryTrait>,
>     // The list of all proposals that were generated.
> ```

Done.
___
*[`crates/batcher_types/src/batcher_types.rs` line 13 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O6KL65p9_E88DQ5HagC:-O7d2t2Z1ma53ZgcH56O:b-7tfmjp) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7192ace8bdae39b0ec7a86361c547c9705ace28/crates/batcher_types/src/batcher_types.rs#L13)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Will add when we connect the PRs
</blockquote></details>

added


<!-- Sent from Reviewable.io -->

2024-10-01 10:03 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565#-:-O86X1no3GFQkvUijDI4:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @lev-starkware, @matan-starkware, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-01 10:16 UTC, ArniStarkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: all files reviewed, 6 unresolved discussions (waiting on @lev-starkware, @matan-starkware, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-06 07:36 UTC, Yael-Starkware requested changes
> Reviewed 6 of 16 files at r17, 1 of 6 files at r19, 1 of 3 files at r20, 3 of 5 files at r21, 5 of 6 files at r22.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: all files reviewed, 2 unresolved discussions (waiting on @lev-starkware, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 125 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O8VZfVHA0Iqa_qfwkGS:-O8VZfVHA0Iqa_qfwkGT:b-kh2hm0) ([raw file](https://github.com/starkware-libs/sequencer/blob/92c8e2538e5a72b267e7868114438f7d68e33d26/crates/batcher/src/proposal_manager.rs#L125)):*
> ```XML
>         info!("Starting generation of a new proposal with id {}.", proposal_id);
>         self.set_active_proposal(proposal_id).await?;
>         self.proposals.push(proposal_id);
> ```

what happens if a proposal generation fails? does it still stay in this Vec? it needs to be marked as failed somehow.



_Code quote:_
```XML
self.proposals.push(proposal_id);
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 80 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O8VkOf4EeJRaTnCSu60:-O8VkOf4EeJRaTnCSu61:bi8940v) ([raw file](https://github.com/starkware-libs/sequencer/blob/92c8e2538e5a72b267e7868114438f7d68e33d26/crates/batcher_types/src/batcher_types.rs#L80)):*
> ```XML
>     // Only sent in response to `Finish`.
>     Finished(ProposalCommitment),
>     // May be caused due to handling of a previous item of the new proposal.
> ```

I don't understand what is the scenario.



_Code quote:_
```XML
// May be caused due to handling of a previous item of the new proposal.
```


<!-- Sent from Reviewable.io -->

2024-10-06 08:07 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: all files reviewed, 2 unresolved discussions (waiting on @lev-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 125 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O8VZfVHA0Iqa_qfwkGS:-O8VnmDCEiqOrNA3iLti:btc46p8) ([raw file](https://github.com/starkware-libs/sequencer/blob/92c8e2538e5a72b267e7868114438f7d68e33d26/crates/batcher/src/proposal_manager.rs#L125)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what happens if a proposal generation fails? does it still stay in this Vec? it needs to be marked as failed somehow.
</blockquote></details>

In https://github.com/starkware-libs/sequencer/pull/1153, I store the block builder's output, which can be `aborted` (you should move this type to the block builder and change it).

If the consensus decides on a failed proposal it will get an error.
___
*[`crates/batcher_types/src/batcher_types.rs` line 80 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O8VkOf4EeJRaTnCSu60:-O8Vr8pe1uiNuuFHSnq8:b-gtcibf) ([raw file](https://github.com/starkware-libs/sequencer/blob/92c8e2538e5a72b267e7868114438f7d68e33d26/crates/batcher_types/src/batcher_types.rs#L80)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I don't understand what is the scenario.
</blockquote></details>

For example if the consensus tries to add more txs when the block is full


<!-- Sent from Reviewable.io -->

2024-10-06 08:27 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 80 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/565#-O8VkOf4EeJRaTnCSu60:-O8VvJj2BanDHOo40QEO:b43yiv3) ([raw file](https://github.com/starkware-libs/sequencer/blob/92c8e2538e5a72b267e7868114438f7d68e33d26/crates/batcher_types/src/batcher_types.rs#L80)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

For example if the consensus tries to add more txs when the block is full
</blockquote></details>

Ok, I understand that the proposal may not be valid, but just didn't understand this comment. 
I think the comment can be removed, but non-blocking.


<!-- Sent from Reviewable.io -->

2024-10-06 09:07 UTC, Yael-Starkware approved these changes
> Reviewed 1 of 6 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware, @matan-starkware, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-10-07 09:53 UTC, ArniStarkware approved these changes
> Reviewed 1 of 3 files at r20, 1 of 6 files at r22, 3 of 3 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/565)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware, @matan-starkware, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-10-07 11:30 UTC, merged