feat(blockifier): add native execution engine
starkware-libs/sequencer pull request #620
Opened 2024-08-27 12:11 UTC by varex83

> Note, this PR is a copy of https://github.com/starkware-libs/sequencer/pull/429 but with changed "from" branch

This PR bring the boilerplate for the cairo native. It contains some functions that will be used in the future, and put here to parallelize creating of the following PRs.

To test this changes locally you need to set up native dependencies, which are described in [cairo native repository](https://github.com/lambdaclass/cairo_native): 
- Setup LLVM-18: mac: `brew install llvm-18` 
- Setup ENV variables:

<details>
<summary>If installed with brew</summary>

    LIBRARY_PATH=/opt/homebrew/lib
    MLIR_SYS_180_PREFIX="$(brew --prefix llvm@18)"
    LLVM_SYS_181_PREFIX="$(brew --prefix llvm@18)"
    TABLEGEN_180_PREFIX="$(brew --prefix llvm@18)"

    export LIBRARY_PATH
    export MLIR_SYS_180_PREFIX
    export LLVM_SYS_181_PREFIX
    export TABLEGEN_180_PREFIX

</details>

<details>
<summary>If installed using Debian / Ubuntu repository</summary>

	MLIR_SYS_180_PREFIX=/usr/lib/llvm-18
    LLVM_SYS_181_PREFIX=/usr/lib/llvm-18
    TABLEGEN_180_PREFIX=/usr/lib/llvm-18
    
    export MLIR_SYS_180_PREFIX
    export LLVM_SYS_181_PREFIX
    export TABLEGEN_180_PREFIX
    
</details>

- Compile and specify path to cairo-native-runtime (for future use, you can test this PR without this step):
1) `git clone https://github.com/lambdaclass/cairo_native`
2) `cd cairo_native/runtime`
3) `cargo build --release`
4) `cd ..` and `export CAIRO_NATIVE_RUNTIME_LIBRARY=$(pwd)/target/release/libcairo_native_runtime.a`

> NOTE: This PR should be rebased/merge with main after merging the https://github.com/starkware-libs/sequencer/pull/344

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/429)

2024-08-27 12:50 UTC, meship-starkware reviewed
> Reviewed 19 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 19 of 20 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-13 10:30 UTC, varex83 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 19 of 20 files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6LT07f8kaZMEgDidJP:-O6ea5KG17HQyMdUx1ZJ:botk2f6) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73639a3b1ce05d13a14bce44c3afd2b3ce13792/crates/blockifier/src/execution/call_info.rs#L27)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Continuing [this](https://reviewable.io/reviews/starkware-libs/sequencer/429#-O4f8mTQ8FVIhgrOOgOe) conversation:
How is your `execute_inner_call` implementation different from the existing one? Why is it needed to return the call info now?
</blockquote></details>

Okay, I think we can just return `retdata` from the `execute_inner_call`, so that we can avoid using clone here.

But I'm just really curious why you don't like the idea of using `Clone`?
___
*[`crates/blockifier/src/execution/contract_class.rs` line 613 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6LX-3n1ScRxXLWo9Or:-O6euwr1-sS0MEcPoxO-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73639a3b1ce05d13a14bce44c3afd2b3ce13792/crates/blockifier/src/execution/contract_class.rs#L613)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When do you plan to delete it?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 622 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6LU9TaDNX8FdjSHb1R:-O6euxdr9YfnuLK4kZL9:bqlqqe4) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73639a3b1ce05d13a14bce44c3afd2b3ce13792/crates/blockifier/src/execution/contract_class.rs#L622)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

See [comment](https://reviewable.io/reviews/starkware-libs/sequencer/429#-O577pNA5r_KdKMNO9AE).
</blockquote></details>

Removed the function, should be done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 625 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6LWjDY7XthuDf3s7zN:-O6ev2hB-GTfV5pC4BLA:bqlqqe4) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73639a3b1ce05d13a14bce44c3afd2b3ce13792/crates/blockifier/src/execution/contract_class.rs#L625)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

See [comment](https://reviewable.io/reviews/starkware-libs/sequencer/429#-O579JWNDY_O5GirEyU5)
</blockquote></details>

Removed the function, should be done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 629 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6LX7FXEyAs1f5XzAYh:-O6ev5Ir8lqDGB03TdkJ:b-pl2sv9) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73639a3b1ce05d13a14bce44c3afd2b3ce13792/crates/blockifier/src/execution/contract_class.rs#L629)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

See [comment](https://reviewable.io/reviews/starkware-libs/sequencer/429#-O533C3FAAHKy8Z5p0zn).
</blockquote></details>

duplicating: I see your point, but these methods work with different types, so that will be challenging to make it more generic (e.g. implementing shared traits, etc. )


<!-- Sent from Reviewable.io -->

2024-09-15 08:44 UTC, meship-starkware reviewed
> Reviewed 1 of 20 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 19 of 20 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @varex83)



<!-- Sent from Reviewable.io -->

2024-09-15 08:57 UTC, meship-starkware reviewed
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @noaov1 and @varex83)



<!-- Sent from Reviewable.io -->

2024-09-15 14:28 UTC, meship-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 6 unresolved discussions (waiting on @noaov1 and @varex83)



<!-- Sent from Reviewable.io -->

2024-09-16 11:04 UTC, noaov1 requested changes
> Reviewed 12 of 20 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 3 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/call_info.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6LT07f8kaZMEgDidJP:-O6tgePK8pHrCjfmR1ST:b-i6relz) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73639a3b1ce05d13a14bce44c3afd2b3ce13792/crates/blockifier/src/execution/call_info.rs#L27)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Okay, I think we can just return `retdata` from the `execute_inner_call`, so that we can avoid using clone here.

But I'm just really curious why you don't like the idea of using `Clone`?
</blockquote></details>

We prefer to avoid clone because cloning can have performance implications, especially if the data being cloned is large or complex, as `Clone` creates a deep copy of the object (and the call info can be large).


<!-- Sent from Reviewable.io -->

2024-09-17 08:26 UTC, varex83 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 0 of 38 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6LT07f8kaZMEgDidJP:-O6z4h940kpeK1HNBJCP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73639a3b1ce05d13a14bce44c3afd2b3ce13792/crates/blockifier/src/execution/call_info.rs#L27)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We prefer to avoid clone because cloning can have performance implications, especially if the data being cloned is large or complex, as `Clone` creates a deep copy of the object (and the call info can be large).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-17 11:13 UTC, meship-starkware reviewed
Could you please fetch and rebase, we see all the CI changes in this PR. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620#-:-O6zffJ9AAyL3hlLMXOT:bc3gji5)* status: 0 of 38 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)



<!-- Sent from Reviewable.io -->

2024-09-17 11:42 UTC, varex83 reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620#-:-O6zmYbQ5rD09qIFJ3Rt:b-896fix)* status: 0 of 38 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-09-17 12:51 UTC, meship-starkware reviewed
> Reviewed 1 of 37 files at r4, 9 of 15 files at r10, 1 of 1 files at r12, 22 of 23 files at r13, 1 of 1 files at r14, 1 of 3 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 37 of 38 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)



<!-- Sent from Reviewable.io -->

2024-09-17 15:32 UTC, noaov1 requested changes
Please add the native class [here](https://github.com/starkware-libs/sequencer/blob/e5d9324edbca7234bb3e8945c7079062fcf9d586/crates/blockifier/src/transaction/account_transaction.rs#L828) as well.

> Reviewed 10 of 15 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 23 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620#-:-O7-b09q31KFL5KQdnfs:b-o6w8om)* status: all files reviewed, 12 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 11 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-UFC88wR2L-pFdjdT:-O7-UFC88wR2L-pFdjdU:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L11)):*
> ```XML
> use cairo_lang_starknet_classes::contract_class::{
>     ContractClass as SierraContractClass,
>     ContractEntryPoint,
> ```





_Suggestion:_
```XML
    ContractEntryPoint as SierraContractEntryPoint,
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 606 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6zU2yW2IsS-4LwgQOz:-O6zU2yW2IsS-4LwgQP-:b-l0b7yc) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L606)):*
> ```XML
>             && call.entry_point_selector != selector_from_name(CONSTRUCTOR_ENTRY_POINT_NAME)
>         {
>             return Err(PreExecutionError::InvalidConstructorEntryPointName);
> ```

Can you please extract this into a method and call it from `get_entry_point` of `ContractClassV1` as well?



_Code quote:_
```XML
        if call.entry_point_type == EntryPointType::Constructor
            && call.entry_point_selector != selector_from_name(CONSTRUCTOR_ENTRY_POINT_NAME)
        {
            return Err(PreExecutionError::InvalidConstructorEntryPointName);
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 632 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6zg1sq8A4HpDc2cb8m:-O6zg1sq8A4HpDc2cb8n:b-djj0l0) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L632)):*
> ```XML
>     // Storing the raw sierra program and entry points to be able to fallback to the vm
>     sierra_program: Vec<BigUintAsHex>,
> }
> ```

Why not delete it in this PR?



_Code quote:_
```XML
    // Storing the raw sierra program and entry points to be able to fallback to the vm
    sierra_program: Vec<BigUintAsHex>,
}
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 649 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-CyMpEm43OBpgSIqd:-O7-CyMpEm43OBpgSIqe:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L649)):*
> ```XML
>         // entry point with FunctionIds from SierraProgram.
>         let lookup_fid: LookupTable<'_> =
>             HashMap::from_iter(sierra_program.funcs.iter().map(|fid| {
> ```





_Suggestion:_
```XML
HashMap::from_iter(sierra_program.funcs.iter().map(|func| {
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 673 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-RTJN9eb7YTbukdv2:-O7-RTJN9eb7YTbukdv3:brm6o9u) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L673)):*
> ```XML
>             && self.sierra_program == other.sierra_program
>     }
> }
> ```

When is it used?



_Code quote:_
```XML
impl PartialEq for NativeContractClassV1Inner {
    fn eq(&self, other: &Self) -> bool {
        self.entry_points_by_type == other.entry_points_by_type
            && self.sierra_program == other.sierra_program
    }
}
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 689 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-TkIF3wpQhMl5gYgY:-O7-TkIF3wpQhMl5gYgZ:bpxchyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L689)):*
> ```XML
>     /// [FunctionId] lookup table.
>     ///
>     /// On failure returns the first FunctionId that it couldn't find.
> ```

Where can I see it in the code?



_Code quote:_
```XML
   /// On failure returns the first FunctionId that it couldn't find.
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 692 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-U2X74LhcEuobGuwi:-O7-U2X74LhcEuobGuwj:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L692)):*
> ```XML
>     fn try_from(
>         lookup: &LookupTable<'_>,
>         sierra_ep: &SierraContractEntryPoints,
> ```





_Suggestion:_
```XML
        sierra_eps: &SierraContractEntryPoints,
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 697 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-Tz2n7wzPbdajb9KJ:-O7-Tz2n7wzPbdajb9KK:brejra4) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L697)):*
> ```XML
>             .constructor
>             .iter()
>             .map(|c| NativeEntryPoint::try_from(lookup, c))
> ```

Same below



_Suggestion:_
```XML
            .map(|sierra_ep| NativeEntryPoint::try_from(lookup, c))
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 738 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-UTi16mmLBEPYCCwK:-O7-UTi16mmLBEPYCCwL:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L738)):*
> ```XML
>     fn try_from(
>         lookup: &LookupTable<'_>,
>         contract_ep: &ContractEntryPoint,
> ```





_Suggestion:_
```XML
        sierra_ep: &ContractEntryPoint,
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 741 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-ZJqN0qFcn6rxJjnb:-O7-ZJqN0qFcn6rxJjnc:b-ioj8af) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L741)):*
> ```XML
>     ) -> Result<NativeEntryPoint, NativeEntryPointError> {
>         let &function_id = lookup
>             .get(&contract_ep.function_idx)
> ```

I don't think that the function id (the key) has the same meaning as the function index



_Code quote:_
```XML
        let &function_id = lookup
            .get(&contract_ep.function_idx)
```
___
*[`crates/blockifier/src/execution/errors.rs` line 101 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-ZkadCbFkt_tvJryz:-O7-ZkadCbFkt_tvJrz-:bsdxd9e) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/errors.rs#L101)):*
> ```XML
>         #[source]
>         source: NativeRunnerError,
>     },
> ```

Please remove the added error that are not used in this PR.



_Code quote:_
```XML
    #[error("Failed to convert Sierra to Casm: {0}")]
    FailedToConvertSierraToCasm(String),
    #[error("Internal error: {0}")]
    InternalError(String),
    #[error("Invalid input: {input_descriptor}; {info}")]
    InvalidExecutionInput { input_descriptor: String, info: String },
    #[error("Native execution error: {info}")]
    NativeExecutionError { info: String },
    #[error("Native Fallback Error: {info}")]
    NativeFallbackError { info: Box<EntryPointExecutionError> },
    #[error(" [...]

2024-09-17 15:49 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 12 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 741 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-ZJqN0qFcn6rxJjnb:-O7-f0TU6eYOb6lQGzxa:bslxnkd) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L741)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I don't think that the function id (the key) has the same meaning as the function index
</blockquote></details>

You should use the `function_idx` as the index in the [function vector](https://github.com/starkware-libs/cairo/blob/c1f9ed85f3e94452819f2436358ee3a97d896949/crates/cairo-lang-sierra/src/program.rs#L126).


<!-- Sent from Reviewable.io -->

2024-09-17 18:40 UTC, varex83 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 11 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 11 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-UFC88wR2L-pFdjdT:-O70GnLIAVpTHulpuLte:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L11)):*
> ```XML
> use cairo_lang_starknet_classes::contract_class::{
>     ContractClass as SierraContractClass,
>     ContractEntryPoint,
> ```

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 606 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6zU2yW2IsS-4LwgQOz:-O70GXg63gYAUxau7dmq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L606)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please extract this into a method and call it from `get_entry_point` of `ContractClassV1` as well?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 632 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6zg1sq8A4HpDc2cb8m:-O70FU4-0eimzkNensbr:b-6qcnjs) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L632)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not delete it in this PR?
</blockquote></details>

We will need to add a few tests, and hashing for the `sierra_program` in order to compare them 
___
*[`crates/blockifier/src/execution/contract_class.rs` line 673 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-RTJN9eb7YTbukdv2:-O70CgIr5-Ezmc398qsA:b5cqyy1) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L673)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When is it used?
</blockquote></details>

ContractClass -> ContractClass::V1(NativeContractClassV1) -> NativeContractClassV1(pub Arc<NativeContractClassV1Inner>) 

Since ContractClass needs to have `PartialEq` implemented for some tests (10 occurrences), we implement it for NativeContractClassV1Inner 
___
*[`crates/blockifier/src/execution/contract_class.rs` line 689 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-TkIF3wpQhMl5gYgY:-O70BZ5u0FmTfNhlGGMu:b5m6hh5) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L689)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Where can I see it in the code?
</blockquote></details>

`NativeEntryPoint::try_from(..)` returns the `NativeEntryPointError::FunctionIdNotFound(<function_idx>)`, which is called and then unwrapped in the following code 



_Code snippet:_
```XML
let constructor = sierra_eps
            .constructor
            .iter()
            .map(|sierra_ep| NativeEntryPoint::try_from(lookup, sierra_ep))
            .collect::<Result<_, _>>()?;
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 692 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-U2X74LhcEuobGuwi:-O70BLlc1KNGMwxbkJR5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L692)):*
> ```XML
>     fn try_from(
>         lookup: &LookupTable<'_>,
>         sierra_ep: &SierraContractEntryPoints,
> ```

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 697 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-Tz2n7wzPbdajb9KJ:-O70BIdX4uGnSwCNDOQM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L697)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same below
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 738 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-UTi16mmLBEPYCCwK:-O70B6bS6bYquNZtH2sG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L738)):*
> ```XML
>     fn try_from(
>         lookup: &LookupTable<'_>,
>         contract_ep: &ContractEntryPoint,
> ```

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 101 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-ZkadCbFkt_tvJryz:-O707gJE8K-rWch9ijlM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/errors.rs#L101)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove the added error that are not used in this PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-17 18:55 UTC, varex83 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 35 of 38 files reviewed, 10 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 741 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-ZJqN0qFcn6rxJjnb:-O70Kc088CuFymsE6aqE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L741)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You should use the `function_idx` as the index in the [function vector](https://github.com/starkware-libs/cairo/blob/c1f9ed85f3e94452819f2436358ee3a97d896949/crates/cairo-lang-sierra/src/program.rs#L126).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-18 06:59 UTC, meship-starkware reviewed
> Reviewed 1 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 36 of 38 files reviewed, 12 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`.github/workflows/blockifier_ci.yml` line 59 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O72v9Nw65UmW3MTSksL:-O72v9Nw65UmW3MTSksM:b-p5r270) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc62fd1877a06fb38774ffd98e9f92f02490df51/.github/workflows/blockifier_ci.yml#L59)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v4
> ```

Revert this file changes.  
___
*[`.github/workflows/blockifier_post-merge.yml` line 39 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O72vJJ-9uiZqiaxqAnY:-O72vJJ-9uiZqiaxqAnZ:br8xan8) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc62fd1877a06fb38774ffd98e9f92f02490df51/.github/workflows/blockifier_post-merge.yml#L39)):*
> ```YAML
> 
>       - run: |
>           pip install -r crates/blockifier/tests/requirements.txt
> ```

Revert this file changes.


<!-- Sent from Reviewable.io -->

2024-09-18 10:26 UTC, noaov1 requested changes
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 36 of 38 files reviewed, 8 unresolved discussions (waiting on @meship-starkware and @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 632 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6zg1sq8A4HpDc2cb8m:-O73DjtSAkwpKN4A34c2:bvx46aj) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L632)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

We will need to add a few tests, and hashing for the `sierra_program` in order to compare them
</blockquote></details>

Got it. WDYT about storing the casm directly?
i.e. have a field of 
___
*[`crates/blockifier/src/execution/contract_class.rs` line 57 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O73B0eJ5e0dTeF-7Dcx:-O73B0eJ5e0dTeF-7Dcy:b620pmu) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc62fd1877a06fb38774ffd98e9f92f02490df51/crates/blockifier/src/execution/contract_class.rs#L57)):*
> ```XML
> pub type LookupTable<'a> = HashMap<usize, &'a FunctionId>;
> 
> fn assert_entry_point_not_constructor(call: &CallEntryPoint) -> Result<(), PreExecutionError> {
> ```

Consider defining it in the `impl` of `CallEntryPoint`.



_Suggestion:_
```XML
fn verify_constructor(call: &CallEntryPoint) -> Result
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 652 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O73GAJ7Eod_5YkzwaYT:-O73GAJ7Eod_5YkzwaYU:b-7gx5x7) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc62fd1877a06fb38774ffd98e9f92f02490df51/crates/blockifier/src/execution/contract_class.rs#L652)):*
> ```XML
>         // entry point with FunctionIds from SierraProgram.
>         let lookup_fid: LookupTable<'_> = HashMap::from_iter(
>             sierra_program.funcs.iter().enumerate().map(|(idx, func)| (idx, &func.id)),
> ```

Why not keep it as a vector of function ids??



_Code quote:_
```XML
        let lookup_fid: LookupTable<'_> = HashMap::from_iter(
            sierra_program.funcs.iter().enumerate().map(|(idx, func)| (idx, &func.id)),
```


<!-- Sent from Reviewable.io -->

2024-09-18 11:03 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 36 of 38 files reviewed, 8 unresolved discussions (waiting on @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 632 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6zg1sq8A4HpDc2cb8m:-O73iV3x-1l56RfFSKcH:bxoft05) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L632)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it. WDYT about storing the casm directly?
i.e. have a field of
</blockquote></details>

Oops, got half a comment it seems :). My 5 cents is that it won't matter too much, we are already working on eliminating it completely already
___
*[`crates/blockifier/src/execution/contract_class.rs` line 673 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-RTJN9eb7YTbukdv2:-O73iijJ6Y69uy4irp0D:b7syp3g) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L673)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

ContractClass -> ContractClass::V1(NativeContractClassV1) -> NativeContractClassV1(pub Arc<NativeContractClassV1Inner>) 

Since ContractClass needs to have `PartialEq` implemented for some tests (10 occurrences), we implement it for NativeContractClassV1Inner
</blockquote></details>

As Bohdam said it is requirement. Since we are dumping the Sierra program and comparing the executors is not straightforward since they are reference pointers and not the actual binary.

The plan is to remove sierra_program and leave a unique identifier which is a obtained hashing all the inputs (open to ideas on this as well)

We have yet to determine if the mechanism also implies we don't need to compare entry_points_by_type either.

Finally, shouldn't the CASM and Native representation of the same File have the same comparison? We haven't accounted for this yet, but maybe it needs to be implemented


<!-- Sent from Reviewable.io -->

2024-09-18 12:10 UTC, varex83 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 36 of 39 files reviewed, 8 unresolved discussions (waiting on @meship-starkware, @noaov1, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 57 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O73B0eJ5e0dTeF-7Dcx:-O741ZEsDR9-Yam9EE7x:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc62fd1877a06fb38774ffd98e9f92f02490df51/crates/blockifier/src/execution/contract_class.rs#L57)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining it in the `impl` of `CallEntryPoint`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 652 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O73GAJ7Eod_5YkzwaYT:-O741QDS7HTB_UQsm4NJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc62fd1877a06fb38774ffd98e9f92f02490df51/crates/blockifier/src/execution/contract_class.rs#L652)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not keep it as a vector of function ids??
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-18 12:29 UTC, meship-starkware reviewed
> Reviewed 1 of 2 files at r20, 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 37 of 39 files reviewed, 7 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`.github/workflows/blockifier_ci.yml` line 59 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O72v9Nw65UmW3MTSksL:-O743BWrCAvYmDlJy4Op:bb9pj01) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc62fd1877a06fb38774ffd98e9f92f02490df51/.github/workflows/blockifier_ci.yml#L59)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Revert this file changes.
</blockquote></details>

There is still this space


<!-- Sent from Reviewable.io -->

2024-09-18 12:39 UTC, varex83 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 37 of 39 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`.github/workflows/blockifier_ci.yml` line 59 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O72v9Nw65UmW3MTSksL:-O7488e6CYnq-14QyoEO:b-zd4ka6) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc62fd1877a06fb38774ffd98e9f92f02490df51/.github/workflows/blockifier_ci.yml#L59)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

There is still this space
</blockquote></details>

I tried fixing it, but it automatically formats on save, even when auto-formatting is disabled, it removes additional spaces so I think we can leave it as it is


<!-- Sent from Reviewable.io -->

2024-09-19 07:16 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 34 of 39 files reviewed, 7 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`-- commits` line 250 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O787Wr33LIq3oGPgSWP):*
Why was there a need to update the cargo.lock? Is it related to reverting the CI PR changes?


<!-- Sent from Reviewable.io -->

2024-09-19 10:20 UTC, noaov1 requested changes
> Reviewed 2 of 3 files at r17, 1 of 2 files at r20, 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 36 of 39 files reviewed, 7 unresolved discussions (waiting on @meship-starkware, @rodrigo-pino, and @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 632 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O6zg1sq8A4HpDc2cb8m:-O77spNc2xAkWeXUpWoF:borkya3) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L632)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Oops, got half a comment it seems :). My 5 cents is that it won't matter too much, we are already working on eliminating it completely already
</blockquote></details>

Opps indeed :)
I meant, have a field of type `ContractClassV1` but never mind
___
*[`crates/blockifier/src/execution/contract_class.rs` line 673 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-RTJN9eb7YTbukdv2:-O78ijik4JXKgTIlg0Z6:b-4dcpxs) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L673)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

As Bohdam said it is requirement. Since we are dumping the Sierra program and comparing the executors is not straightforward since they are reference pointers and not the actual binary.

The plan is to remove sierra_program and leave a unique identifier which is a obtained hashing all the inputs (open to ideas on this as well)

We have yet to determine if the mechanism also implies we don't need to compare entry_points_by_type either.

Finally, shouldn't the CASM and Native representation of the same File have the same comparison? We haven't accounted for this yet, but maybe it needs to be implemented
</blockquote></details>

Got it.
How do we compare casms nowadays?
___
*[`crates/blockifier/src/execution/contract_class.rs` line 56 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O77sHe7DGNgHGfJAg-S:-O77sHe7DGNgHGfJAg-T:b-8i1dwg) ([raw file](https://github.com/starkware-libs/sequencer/blob/52760f8d0727dc6b4cae55630b55ba0c2ba0add8/crates/blockifier/src/execution/contract_class.rs#L56)):*
> ```XML
> 
> pub type ContractClassResult<T> = Result<T, ContractClassError>;
> pub type LookupVector<'a> = Vec<&'a FunctionId>;
> ```

I think that now it can be removed :)



_Code quote:_
```XML
pub type LookupVector<'a> = Vec<&'a FunctionId>;
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 725 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O78jEoq1yDjTGQq4Fmw:-O78jEoq1yDjTGQq4Fmx:bzch9mo) ([raw file](https://github.com/starkware-libs/sequencer/blob/52760f8d0727dc6b4cae55630b55ba0c2ba0add8/crates/blockifier/src/execution/contract_class.rs#L725)):*
> ```XML
>             .constructor
>             .iter()
>             .map(|sierra_ep| NativeEntryPoint::try_from(lookup, sierra_ep))
> ```

Consider defining the following method (the name can change):



_Code snippet:_
```XML
fn to_native_entry_points(sierra_eps: Vec<SierraContractEntryPoint>) -> Vec<NativeEntryPoint> {
            sierra_eps
            .iter()
            .map(|sierra_ep| NativeEntryPoint::try_from(lookup, sierra_ep))
}
```
___
*[`crates/blockifier/src/execution/errors.rs` line 101 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-ZkadCbFkt_tvJryz:-O78l7Px0QVD5d9jSfPQ:b-olqiph) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/errors.rs#L101)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think that you can remove also `NativeUnexpectedError` and `NativeExecutionError`, no?
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 28 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O78mmTd6zgDOj01Dsmn:-O78mmTd6zgDOj01Dsmo:b-o6w8om) ([raw file](https://github.com/starkware-libs/sequencer/blob/52760f8d0727dc6b4cae55630b55ba0c2ba0add8/crates/blockifier/src/transaction/transaction_utils.rs#L28)):*
> ```XML
>             })
>         }
>         ContractClass::V1(_) | ContractClass::V1Native(_) => {
> ```

Please add the native class [here](https://github.com/starkware-libs/sequencer/blob/e5d9324edbca7234bb3e8945c7079062fcf9d586/crates/blockifier/src/transaction/account_transaction.rs#L828) as well.



_Code quote:_
```XML
ContractClass::V1(_) | ContractClass::V1Native(_) => {
```


<!-- Sent from Reviewable.io -->

2024-09-19 10:55 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 36 of 39 files reviewed, 9 unresolved discussions (waiting on @meship-starkware, @rodrigo-pino, and @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 721 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O78rRPo4WnicZmx8ydH:-O78rRPo4WnicZmx8ydI:bp1lmmr) ([raw file](https://github.com/starkware-libs/sequencer/blob/52760f8d0727dc6b4cae55630b55ba0c2ba0add8/crates/blockifier/src/execution/contract_class.rs#L721)):*
> ```XML
>         lookup: &LookupVector<'_>,
>         sierra_eps: &SierraContractEntryPoints,
>     ) -> Result<NativeContractEntryPoints, NativeEntryPointError> {
> ```

Ans here extract the `lookup` (would rename to `funcs_id`) and the `sierra_entry_points_by_type`. 



_Suggestion:_
```XML
    fn try_from(
        sierra_contract_class: SierraContractClass,
    ) -> Result<NativeContractEntryPoints, NativeEntryPointError> {
```
___
*[`crates/blockifier/src/execution/errors.rs` line 113 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O78tQMQ0YauoTWQkZl0:-O78tQMQ0YauoTWQkZl1:b-y9up2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/52760f8d0727dc6b4cae55630b55ba0c2ba0add8/crates/blockifier/src/execution/errors.rs#L113)):*
> ```XML
> pub enum NativeEntryPointError {
>     #[error("FunctionId {0} not found")]
>     FunctionIdNotFound(usize),
> ```

Out of curiosity: when can this happen?



_Code quote:_
```XML
    #[error("FunctionId {0} not found")]
    FunctionIdNotFound(usize),
```


<!-- Sent from Reviewable.io -->

2024-09-19 11:02 UTC, meship-starkware reviewed
> Reviewed 1 of 3 files at r17, 2 of 4 files at r24, 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 38 of 39 files reviewed, 9 unresolved discussions (waiting on @noaov1, @rodrigo-pino, and @varex83)



<!-- Sent from Reviewable.io -->

2024-09-19 11:57 UTC, varex83 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 36 of 40 files reviewed, 7 unresolved discussions (waiting on @meship-starkware, @noaov1, and @rodrigo-pino)

___
*[`-- commits` line 250 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O787Wr33LIq3oGPgSWP):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why was there a need to update the cargo.lock? Is it related to reverting the CI PR changes?
</blockquote></details>

No, it's not related. We had one problem with the CI, which seems to be magically merged into our branch while checking out, and that caused errors
___
*[`crates/blockifier/src/execution/contract_class.rs` line 56 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O77sHe7DGNgHGfJAg-S:-O79-kdW3A1xxKwVzPG5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52760f8d0727dc6b4cae55630b55ba0c2ba0add8/crates/blockifier/src/execution/contract_class.rs#L56)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that now it can be removed :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 101 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-ZkadCbFkt_tvJryz:-O795s0Z-mMmSco0YSX7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/errors.rs#L101)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that you can remove also `NativeUnexpectedError` and `NativeExecutionError`, no?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 113 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O78tQMQ0YauoTWQkZl0:-O796-mKBnBsyfqq1fM8:b67vzwv) ([raw file](https://github.com/starkware-libs/sequencer/blob/52760f8d0727dc6b4cae55630b55ba0c2ba0add8/crates/blockifier/src/execution/errors.rs#L113)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Out of curiosity: when can this happen?
</blockquote></details>

This could never happen practically, I've refactored it.
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 28 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O78mmTd6zgDOj01Dsmn:-O797SOf5FCGiFdLCNd5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52760f8d0727dc6b4cae55630b55ba0c2ba0add8/crates/blockifier/src/transaction/transaction_utils.rs#L28)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add the native class [here](https://github.com/starkware-libs/sequencer/blob/e5d9324edbca7234bb3e8945c7079062fcf9d586/crates/blockifier/src/transaction/account_transaction.rs#L828) as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-19 14:49 UTC, noaov1 requested changes
> Reviewed 3 of 3 files at r26.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 39 of 40 files reviewed, 7 unresolved discussions (waiting on @meship-starkware, @rodrigo-pino, and @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 698 at r26](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O79fFff8tbr4zJaJcJN:-O79fFff8tbr4zJaJcJO:bvfs1lm) ([raw file](https://github.com/starkware-libs/sequencer/blob/95e5d8e1c624b39a40a1675a0f2e35301b25700c/crates/blockifier/src/execution/contract_class.rs#L698)):*
> ```XML
> 
> impl NativeContractEntryPoints {
>     fn sierra_eps_to_native_eps(
> ```

Why does it need to be defined inside the `impl`?



_Code quote:_
```XML
 fn sierra_eps_to_native_eps(
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 699 at r26](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O79eddt3PJdnQiIbQpT:-O79eddt3PJdnQiIbQpU:bv9gsbb) ([raw file](https://github.com/starkware-libs/sequencer/blob/95e5d8e1c624b39a40a1675a0f2e35301b25700c/crates/blockifier/src/execution/contract_class.rs#L699)):*
> ```XML
> impl NativeContractEntryPoints {
>     fn sierra_eps_to_native_eps(
>         lookup: &[&FunctionId],
> ```

Please change it in the entire file



_Suggestion:_
```XML
        funcs_id: &[&FunctionId],
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 708 at r26](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O79dr_9AJBLqpjilatw:-O79dr_A1NE0b5d-CxO5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/95e5d8e1c624b39a40a1675a0f2e35301b25700c/crates/blockifier/src/execution/contract_class.rs#L708)):*
> ```XML
> impl From<&SierraContractClass> for NativeContractEntryPoints {
>     fn from(sierra_contract_class: &SierraContractClass) -> Self {
>         let program = sierra_contract_class.extract_sierra_program().unwrap();
> ```





_Suggestion:_
```XML
        let program = sierra_contract_class.extract_sierra_program().expect("can't extract sierra program");
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 712 at r26](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O79gnpNEAknlNtkW2gF:-O79gnpNEAknlNtkW2gG:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/95e5d8e1c624b39a40a1675a0f2e35301b25700c/crates/blockifier/src/execution/contract_class.rs#L712)):*
> ```XML
>         let lookup = program.funcs.iter().map(|func| &func.id).collect::<Vec<&FunctionId>>();
> 
>         let sierra_eps = &sierra_contract_class.entry_points_by_type;
> ```





_Suggestion:_
```XML
let entry_points_by_type = &sierra_contract_class.entry_points_by_type;
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 745 at r26](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O79eCTnAC35CaveXWf6:-O79eCTnAC35CaveXWf7:bwynnmi) ([raw file](https://github.com/starkware-libs/sequencer/blob/95e5d8e1c624b39a40a1675a0f2e35301b25700c/crates/blockifier/src/execution/contract_class.rs#L745)):*
> ```XML
> impl NativeEntryPoint {
>     fn from(lookup: &[&FunctionId], sierra_ep: &SierraContractEntryPoint) -> NativeEntryPoint {
>         let &function_id = lookup.get(sierra_ep.function_idx).unwrap();
> ```

We try to avoid using `unwraps()` :)



_Suggestion:_
```XML
let &function_id = lookup.get(sierra_ep.function_idx).expect("An informative error message");
```


<!-- Sent from Reviewable.io -->

2024-09-23 05:26 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r27.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 39 of 40 files reviewed, 2 unresolved discussions (waiting on @meship-starkware, @rodrigo-pino, and @varex83)



<!-- Sent from Reviewable.io -->

2024-09-23 10:48 UTC, meship-starkware reviewed
> Reviewed 2 of 3 files at r26.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 39 of 40 files reviewed, 2 unresolved discussions (waiting on @rodrigo-pino and @varex83)



<!-- Sent from Reviewable.io -->

2024-09-29 10:45 UTC, meship-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 39 of 40 files reviewed, 1 unresolved discussion (waiting on @noaov1, @rodrigo-pino, and @varex83)



<!-- Sent from Reviewable.io -->

2024-10-01 01:44 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 39 of 40 files reviewed, 1 unresolved discussion (waiting on @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 673 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O7-RTJN9eb7YTbukdv2:-O84ikWLAd81THlxBuup:b-viy6nc) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c8250cf8384a072ee73ee7568947deb74eb0229/crates/blockifier/src/execution/contract_class.rs#L673)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it.
How do we compare casms nowadays?
</blockquote></details>

You compare the full `ContractClassV1Inner`, the comparison code is generated automatically through the `#derive(...)` attribute and `PartialEq` trait. Snip of class:

```rust
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ContractClassV1Inner {
    pub program: Program,
    pub entry_points_by_type: HashMap<EntryPointType, Vec<EntryPointV1>>,
    pub hints: HashMap<String, Hint>,
    pub compiler_version: CompilerVersion,
    bytecode_segment_lengths: NestedIntList,
}


```


<!-- Sent from Reviewable.io -->

2024-10-06 06:27 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 9 of 45 files reviewed, 2 unresolved discussions (waiting on @noaov1, @rodrigo-pino, and @varex83)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VVJKI0mlxDB97Xex3:-O8VVJKJ1vby5Ej2HYc-:b-4hfhh6) (no related file):*
Please rebase over main 

___


<!-- Sent from Reviewable.io -->

2024-10-06 06:30 UTC, noaov1 requested changes
> Reviewed 1 of 4 files at r24, 1 of 33 files at r28, 8 of 18 files at r29, 2 of 3 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 20 of 45 files reviewed, 6 unresolved discussions (waiting on @meship-starkware, @rodrigo-pino, and @varex83)

___
*[`Dockerfile` line 36 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VU8hzBSLhUbokms_2:-O8VU8i-CvYEbSwj4Ajz:bdk7ku9) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/Dockerfile#L36)):*
> ```Dockerfile
> # RUN rustup target add x86_64-unknown-linux-musl
> 
> # Install dependencies
> ```

Why is this needed?



_Code quote:_
```Dockerfile
# Install dependencies
```
___
*[`.github/workflows/blockifier_ci.yml` line 25 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VUGoq29dqUyg_M65K:-O8VUGoq29dqUyg_M65L:bbt4azf) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/.github/workflows/blockifier_ci.yml#L25)):*
> ```YAML
>       # Other than code-related changes, all changes related to the native-blockifier build-and-push
>       # process should trigger the build (e.g., changes to the Dockerfile, build scripts, etc.).
>       - ".github/workflows/blockifier_ci.yml"
> ```

Do all the changes in the `.yml` files are auto formatter?
Can this be done in a separate PR?
___
*[`.github/workflows/committer_ci.yml` line 45 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VUhyi6-syz01Tdyna:-O8VUhyi6-syz01Tdynb:b3rh2jm) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/.github/workflows/committer_ci.yml#L45)):*
> ```YAML
> concurrency:
>   group: ${{ github.workflow }}-${{ github.ref }}
>   cancel-in-progress: ${{ github.event_name == 'pull_request' }}
> ```

Please delete (duplicate)



_Code quote:_
```YAML
# On PR events, cancel existing CI runs on this same PR for this workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
```
___
*[`.github/workflows/main.yml` line 58 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VUow4A9zTZ_ZN5R2R:-O8VUow4A9zTZ_ZN5R2S:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/.github/workflows/main.yml#L58)):*
> ```YAML
>           version: "0.9.0"
>           locked: true
>           components: clippy
> ```

?



_Code quote:_
```YAML
          components: clippy
```


<!-- Sent from Reviewable.io -->

2024-10-06 07:50 UTC, noaov1 requested changes
> Reviewed 3 of 33 files at r28, 5 of 18 files at r29, 1 of 1 files at r30, 4 of 5 files at r31, 1 of 3 files at r33, 1 of 1 files at r35.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 35 of 45 files reviewed, 9 unresolved discussions (waiting on @meship-starkware and @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 113 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VfRMe2tspDXBBL7LL:-O8VfRMe2tspDXBBL7LM:bz1ftg8) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/crates/blockifier/src/execution/contract_class.rs#L113)):*
> ```XML
>                 )
>             }
>         }
> ```

@meship-starkware  FYI
(non-blocking)



_Suggestion:_
```XML
            ContractClass::V1Native(_) => {
                todo!(
                    "Use casm to estimate casm hash computation resources"
                )
            }
        }
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 138 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VlKajCBfw0IcJtfhW:-O8VlKajCBfw0IcJtfhX:bz1ftg8) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/crates/blockifier/src/execution/contract_class.rs#L138)):*
> ```XML
>                 panic!("bytecode_length is not supported for native contracts.")
>             }
>         }
> ```

@meship-starkware  FYI
(non-blocking)



_Suggestion:_
```XML
            ContractClass::V1Native(_) => {
                todo!("implement bytecode_lengthfor native contracts.")
            }
        }
```
___
*[`scripts/sequencer-ci.Dockerfile` line 2 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8Vm2z89ObZZ8lWDthL:-O8Vm2z89ObZZ8lWDthM:b-8g5bg9) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/scripts/sequencer-ci.Dockerfile#L2)):*
> ```
> FROM ubuntu:20.04
> ```

Can you please explain the changes in this file?


<!-- Sent from Reviewable.io -->

2024-10-06 08:11 UTC, noaov1 reviewed
> Reviewed 1 of 33 files at r28, 1 of 1 files at r34.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 37 of 45 files reviewed, 8 unresolved discussions (waiting on @meship-starkware and @varex83)



<!-- Sent from Reviewable.io -->

2024-10-06 08:13 UTC, noaov1 reviewed
> Reviewed 1 of 15 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 37 of 45 files reviewed, 8 unresolved discussions (waiting on @meship-starkware and @varex83)



<!-- Sent from Reviewable.io -->

2024-10-06 12:33 UTC, meship-starkware reviewed
> Reviewed 1 of 1 files at r34.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 37 of 45 files reviewed, 9 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 746 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8Wo9bP5yrF3vHy98A0:-O8Wo9bP5yrF3vHy98A1:b-vwjgax) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/crates/blockifier/src/execution/contract_class.rs#L746)):*
> ```XML
> }
> 
> impl Eq for NativeContractClassV1Inner {}
> ```

Why do you need the Eq as well as the PartialEq?



_Code quote:_
```XML
impl Eq for NativeContractClassV1Inner {}
```


<!-- Sent from Reviewable.io -->

2024-10-06 12:34 UTC, meship-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 37 of 45 files reviewed, 9 unresolved discussions (waiting on @varex83)



<!-- Sent from Reviewable.io -->

2024-10-06 12:37 UTC, meship-starkware reviewed
> Reviewed 8 of 33 files at r28.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 9 unresolved discussions (waiting on @varex83)



<!-- Sent from Reviewable.io -->

2024-10-06 15:12 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 9 unresolved discussions (waiting on @alon-dotan-starkware, @meship-starkware, @noaov1, and @varex83)

___
*[`Dockerfile` line 36 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VU8hzBSLhUbokms_2:-O8XGz4y7djyJG2N_Ih7:b-npmhya) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/Dockerfile#L36)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

I am not sure I understand. If you believe the comment is redundant I can delete it. If you mean the whole thing is because it's a required dependencies by the LLVM project which Cairo Native uses
___
*[`.github/workflows/blockifier_ci.yml` line 25 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VUGoq29dqUyg_M65K:-O8XHI5i1g_2uL5pJVm-:bmm0sky) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/.github/workflows/blockifier_ci.yml#L25)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do all the changes in the `.yml` files are auto formatter?
Can this be done in a separate PR?
</blockquote></details>

Oops, I'll revert them
___
*[`.github/workflows/main.yml` line 58 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VUow4A9zTZ_ZN5R2R:-O8XLs1I2LLljKByCS3v:b-dmm6f8) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/.github/workflows/main.yml#L58)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

whooops
___
*[`crates/blockifier/src/execution/contract_class.rs` line 113 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VfRMe2tspDXBBL7LL:-O8XHlwF5DcWRxBnrg5B:b-1d0dsa) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/crates/blockifier/src/execution/contract_class.rs#L113)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@meship-starkware  FYI
(non-blocking)
</blockquote></details>

Should it be a `todo!` or remain a `panic`?
___
*[`crates/blockifier/src/execution/contract_class.rs` line 746 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8Wo9bP5yrF3vHy98A0:-O8XHyAQ7fNkY2mUGZxT:b-xu9xtv) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/crates/blockifier/src/execution/contract_class.rs#L746)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why do you need the Eq as well as the PartialEq?
</blockquote></details>

Because `NativeContractClassV1` requires `Eq` trait because it's an arm of `ContractClass` with  requires the `Eq` trait. 
___
*[`scripts/sequencer-ci.Dockerfile` line 2 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8Vm2z89ObZZ8lWDthL:-O8XNUU34FfTxYElwCwp:b-o8w53b) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/scripts/sequencer-ci.Dockerfile#L2)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain the changes in this file?
</blockquote></details>

Mmm, they were required to build the Docker image with Cairo Native. Maybe after @alon-dotan-starkware this is no longer the case :thinking: 


<!-- Sent from Reviewable.io -->

2024-10-06 16:43 UTC, noaov1 requested changes
> Reviewed 18 of 18 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 7 unresolved discussions (waiting on @alon-dotan-starkware, @meship-starkware, @rodrigo-pino, and @varex83)

___
*[`Dockerfile` line 36 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VU8hzBSLhUbokms_2:-O8XeVqV-qyhH_KkU3N_:bbr583l) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/Dockerfile#L36)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

I am not sure I understand. If you believe the comment is redundant I can delete it. If you mean the whole thing is because it's a required dependencies by the LLVM project which Cairo Native uses
</blockquote></details>

Oh, sorry, I meant the entire addition to the file. Let me rephrase: why is it needed on top of Alon's PR #989?
___
*[`crates/blockifier/src/execution/contract_class.rs` line 113 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VfRMe2tspDXBBL7LL:-O8XgUZa6t-q8Bsct_sU:bstp2r5) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/crates/blockifier/src/execution/contract_class.rs#L113)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Should it be a `todo!` or remain a `panic`?
</blockquote></details>

I prefer `todo!` (which panics), but either are fine.
___
*[`scripts/sequencer-ci.Dockerfile` line 2 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8Vm2z89ObZZ8lWDthL:-O8XgiDXDeLkpxbq9Wz0:bjsyy3s) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/scripts/sequencer-ci.Dockerfile#L2)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Mmm, they were required to build the Docker image with Cairo Native. Maybe after @alon-dotan-starkware this is no longer the case :thinking:
</blockquote></details>

I hope so. That was the point :)


<!-- Sent from Reviewable.io -->

2024-10-06 17:01 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 9 unresolved discussions (waiting on @alon-dotan-starkware, @meship-starkware, @rodrigo-pino, and @varex83)

___
*[`.github/workflows/committer_ci.yml` line 48 at r36](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8XlaMN4y1XpeHlEIV6:-O8XlaMN4y1XpeHlEIV7:b-8vim4s) ([raw file](https://github.com/starkware-libs/sequencer/blob/9fd6c3f9d2567dd77d61d94aae8c2ef3518e1c4d/.github/workflows/committer_ci.yml#L48)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v4
>       - uses: ./.github/actions/bootstrap
> ```

Please revert the changes in this file.
___
*[`.github/workflows/papyrus_nightly-tests.yml` line 1 at r36](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8XlfOx-qssne9rh-c5:-O8XlfOx-qssne9rh-c6:b-8vim4s) ([raw file](https://github.com/starkware-libs/sequencer/blob/9fd6c3f9d2567dd77d61d94aae8c2ef3518e1c4d/.github/workflows/papyrus_nightly-tests.yml#L1)):*
> ```YAML
> name: Papyrus-Nightly-Tests
> ```

Please revert the changes in this file.


<!-- Sent from Reviewable.io -->

2024-10-06 17:47 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: 40 of 45 files reviewed, 9 unresolved discussions (waiting on @alon-dotan-starkware, @meship-starkware, @noaov1, and @varex83)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VVJKI0mlxDB97Xex3:-O8XrV1p-boOrngxpoLa:bb6un1j) (no related file):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please rebase over main
</blockquote></details>

Done

___
___
*[`crates/blockifier/src/execution/contract_class.rs` line 113 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VfRMe2tspDXBBL7LL:-O8XsvPr4SxLpn3dtsJt:b-iuc06p) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/crates/blockifier/src/execution/contract_class.rs#L113)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I prefer `todo!` (which panics), but either are fine.
</blockquote></details>

:+1: 

I was suggesting `panic!` because `todo!` implied that there was something to do there and I thought there wasn't
___
*[`Dockerfile` line 36 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8VU8hzBSLhUbokms_2:-O8Xru5RASzcNyMynmE0:bimd2ol) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/Dockerfile#L36)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh, sorry, I meant the entire addition to the file. Let me rephrase: why is it needed on top of Alon's PR #989?
</blockquote></details>

Yes, it makes sense it shouldn't be there at all!
___
*[`.github/workflows/committer_ci.yml` line 48 at r36](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8XlaMN4y1XpeHlEIV6:-O8Xss6uCK56SlkEs7Dj:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9fd6c3f9d2567dd77d61d94aae8c2ef3518e1c4d/.github/workflows/committer_ci.yml#L48)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert the changes in this file.
</blockquote></details>

Done
___
*[`.github/workflows/papyrus_nightly-tests.yml` line 1 at r36](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8XlfOx-qssne9rh-c5:-O8Xs-a1DhmKm6G4MMSs:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9fd6c3f9d2567dd77d61d94aae8c2ef3518e1c4d/.github/workflows/papyrus_nightly-tests.yml#L1)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert the changes in this file.
</blockquote></details>

Done
___
*[`scripts/sequencer-ci.Dockerfile` line 2 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8Vm2z89ObZZ8lWDthL:-O8Xu8qoDzUfZQC6mOZw:b-8fx2u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d1b52df05a5f8b6962444d547a2ce3748f9c6fa/scripts/sequencer-ci.Dockerfile#L2)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I hope so. That was the point :)
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2024-10-06 19:35 UTC, noaov1 approved these changes
> Reviewed 1 of 37 files at r4, 1 of 1 files at r37, 1 of 1 files at r38, 1 of 1 files at r39, 1 of 1 files at r40, 1 of 1 files at r41, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @varex83)

___
*[`scripts/dependencies.sh` line 52 at r41](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8YJtQGDTll4IbnlxB0:-O8YJtQH05LMqCxHxnG7:bcgjvre) ([raw file](https://github.com/starkware-libs/sequencer/blob/43dd5d054066118274d146a019de9a84e457f632/scripts/dependencies.sh#L52)):*
> ```Shell
>     [ "$(uname)" = "Linux" ] && install_essential_deps_linux
>     setup_llvm_deps
>     echo "LLVM and Cairo native runtime dependencies installed successfully."
> ```

Why this change?



_Code quote:_
```Shell
echo "LLVM and Cairo native runtime dependencies installed success
```


<!-- Sent from Reviewable.io -->

2024-10-07 05:04 UTC, noaov1 approved these changes
> Reviewed 3 of 3 files at r42, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @varex83)



<!-- Sent from Reviewable.io -->

2024-10-07 05:14 UTC, meship-starkware approved these changes
> Reviewed 1 of 18 files at r29, 1 of 18 files at r36, 1 of 1 files at r37, 1 of 1 files at r41, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)



<!-- Sent from Reviewable.io -->

2024-10-07 11:01 UTC, rodrigo-pino reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`scripts/dependencies.sh` line 52 at r41](https://reviewable.io/reviews/starkware-libs/sequencer/620#-O8YJtQGDTll4IbnlxB0:-O8acGsB6rFCDExZArGC:b-xjaebl) ([raw file](https://github.com/starkware-libs/sequencer/blob/43dd5d054066118274d146a019de9a84e457f632/scripts/dependencies.sh#L52)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

Because we are only installing LLVM as a dependency and not the Cairo Native Runtime.  A change to reflect what we are currently doing.


<!-- Sent from Reviewable.io -->

2024-10-07 11:30 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)



<!-- Sent from Reviewable.io -->

2024-10-07 14:01 UTC, meship-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)



<!-- Sent from Reviewable.io -->

2024-10-07 19:56 UTC, noaov1 approved these changes
> Reviewed 13 of 13 files at r43, 1 of 1 files at r44, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)



<!-- Sent from Reviewable.io -->

2024-10-07 19:56 UTC, merged