feat(starknet_api, protobuf): add l2_gas_price to block header
starkware-libs/sequencer pull request #641
Opened 2024-08-28 13:04 UTC by TzahiTaub

2024-08-28 13:04 UTC, TzahiTaub commented
* **#641** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/641?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @TzahiTaub and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-28 18:15 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 0 of 16 files reviewed, 1 unresolved discussion

___
*[`crates/papyrus_storage/src/header.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5PBfhc2ueJIUaUWk7f:-O5PBfhc2ueJIUaUWk7g:bu910i2) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_storage/src/header.rs#L74)):*
> ```XML
>     pub l1_gas_price: GasPricePerToken,
>     pub l1_data_gas_price: GasPricePerToken,
>     pub l2_gas_price: GasPricePerToken,
> ```

@DvirYo-starkware note the change of storage struct - please point me to the version change needed as discussed. 


<!-- Sent from Reviewable.io -->

2024-08-28 18:18 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, and @ShahakShama)

___
*[`crates/starknet_client/src/reader/objects/block.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5PCKsa82fCAUom_Udb:-O5PCKsbDRlQJrwjntpA:bohcy9r) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/starknet_client/src/reader/objects/block.rs#L62)):*
> ```XML
>     pub l1_data_gas_price: GasPricePerToken,
>     // New field in V0.13.3.
>     #[serde(default)]
> ```

ATM, default value of 0. Might need adjustmens as a result of the discussion in [here](https://starkwareindustries.slack.com/archives/C07G1R6GDQB/p1724867458754369).



_Code quote:_
```XML
    #[serde(default)]
```


<!-- Sent from Reviewable.io -->

2024-08-29 07:11 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 2 of 16 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-08-29 11:14 UTC, DvirYo-starkware requested changes
> Reviewed 12 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 14 of 16 files reviewed, 9 unresolved discussions (waiting on @ShahakShama and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SdQNU6NVOcgxSbKpV:-O5SdQNV5uw7v_tDB-T-:blpaqa1) (no related file):*
About the changes in the files in papyrus_common:
1. The blocks there are real blocks from mainet. we can't just add a field
2. If the new field will be included in the block hash calculation, the calculation should be changed, and the test that calculates the block hash should also be changed

___
___
*[`crates/papyrus_common/resources/block_hash.json` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SecuY8i471gi2XZUg:-O5SecuY8i471gi2XZUh:b3ks3) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_common/resources/block_hash.json#L14)):*
> ```JSON
>       "price_in_wei": "0x1"
>     },
>     "l2_gas_price": {
> ```

X
___
*[`crates/papyrus_common/resources/deprecated_block_hash_v0.json` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SegqoBt2erhlNT0gy:-O5SegqoBt2erhlNT0gz:b3ks3) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_common/resources/deprecated_block_hash_v0.json#L14)):*
> ```JSON
>       "price_in_wei": "0x1"
>     },
>     "l2_gas_price": {
> ```

X
___
*[`crates/papyrus_common/resources/deprecated_block_hash_v1.json` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SehZv4UrlsAHCd-uh:-O5SehZv4UrlsAHCd-ui:b3ks3) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_common/resources/deprecated_block_hash_v1.json#L14)):*
> ```JSON
>       "price_in_wei": "0x1"
>     },
>     "l2_gas_price": {
> ```

X
___
*[`crates/papyrus_common/resources/deprecated_block_hash_v1_no_events.json` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SeiHQ0eBzxpddW3In:-O5SeiHQ0eBzxpddW3Io:b3ks3) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_common/resources/deprecated_block_hash_v1_no_events.json#L14)):*
> ```JSON
>       "price_in_wei": "0x1"
>     },
>     "l2_gas_price": {
> ```

X
___
*[`crates/papyrus_common/resources/deprecated_block_hash_v2.json` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SeixCDVqjdPplIisZ:-O5SeixCDVqjdPplIis_:b3ks3) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_common/resources/deprecated_block_hash_v2.json#L14)):*
> ```JSON
>       "price_in_wei": "0x1"
>     },
>     "l2_gas_price": {
> ```

X
___
*[`crates/papyrus_storage/src/header.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5PBfhc2ueJIUaUWk7f:-O5ShWtP-HBTi-nFaxle:b1qdahr) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_storage/src/header.rs#L74)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

@DvirYo-starkware note the change of storage struct - please point me to the version change needed as discussed.
</blockquote></details>

I will do that in a different PR. If you change something in objects written to the Papyrus database, notify someone from the Papyrus team.
What should be changed is the major versions here:
https://github.com/starkware-libs/sequencer/blob/ac2838a6ffc8b8d0a5f43eeda5872278fc4a1931/crates/papyrus_storage/src/lib.rs#L156C1-L160C76
This will prevent the old database from opening with new code.
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SlRkQDJdMUTtMhtqp:-O5SlRkQDJdMUTtMhtqq:bwvqcb4) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/starknet_client/src/reader/objects/block_test.rs#L27)):*
> ```XML
> #[test]
> fn load_block_succeeds() {
>     // TODO(Tzahi): Replace block_post_0_13_3 (copied from 0_13_2) with live data once available.
> ```

If you know that the schema of new blocks will change, add those changes manually, i.e., add the l2_get_price field to the block.


<!-- Sent from Reviewable.io -->

2024-09-01 08:55 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 14 of 16 files reviewed, 9 unresolved discussions (waiting on @DvirYo-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SdQNU6NVOcgxSbKpV:-O5gmJB561FL1DeX0hQn:b-r34vyh) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

About the changes in the files in papyrus_common:
1. The blocks there are real blocks from mainet. we can't just add a field
2. If the new field will be included in the block hash calculation, the calculation should be changed, and the test that calculates the block hash should also be changed
</blockquote></details>

Why not change them manually and fix the hash when needed? We won't have real blocks with l2_gas_price until the code will be in... And unless there's a really good reason, I don't understand why we need to keep the "real blocks that were created on chain" thing 100% true.

___


<!-- Sent from Reviewable.io -->

2024-09-01 10:49 UTC, DvirYo-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 14 of 16 files reviewed, 9 unresolved discussions (waiting on @ShahakShama and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SdQNU6NVOcgxSbKpV:-O5h6wBWEFnq4MKX9hs8:b-cnrccj) (no related file):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why not change them manually and fix the hash when needed? We won't have real blocks with l2_gas_price until the code will be in... And unless there's a really good reason, I don't understand why we need to keep the "real blocks that were created on chain" thing 100% true.
</blockquote></details>

1. I agree that the rule of real blocks is not 100% mandatory, but it is what has been decided. The advantage of that is that we know for sure that the block's hash calculation is what it should be, and we can always verify this information in the future again against the FGW.
2. Because the `L2_gas_price` field should not affect the hash of old blocks, if you know for sure if and how this field will be present in old blocks, you can add it. But, I found it very hard to believe that old blocks will retroactively get a 0x2 value in this field.

___


<!-- Sent from Reviewable.io -->

2024-09-01 10:50 UTC, DvirYo-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 14 of 16 files reviewed, 9 unresolved discussions (waiting on @ShahakShama and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SdQNU6NVOcgxSbKpV:-O5hCAnz7yVoND8H2b9R:b5e355z) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

1. I agree that the rule of real blocks is not 100% mandatory, but it is what has been decided. The advantage of that is that we know for sure that the block's hash calculation is what it should be, and we can always verify this information in the future again against the FGW.
2. Because the `L2_gas_price` field should not affect the hash of old blocks, if you know for sure if and how this field will be present in old blocks, you can add it. But, I found it very hard to believe that old blocks will retroactively get a 0x2 value in this field.
</blockquote></details>

In addition, the 0x2 value does not fit with what you implement in the reader client

___


<!-- Sent from Reviewable.io -->

2024-09-01 12:57 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 14 of 16 files reviewed, 10 unresolved discussions (waiting on @ShahakShama and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/header.proto` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5heFKyEWMJdhXGp45S:-O5heFKyEWMJdhXGp45T:b-qi6iss) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_protobuf/src/proto/p2p/proto/header.proto#L25)):*
> ```proto
>     Uint128 data_gas_price_wei = 15;
>     optional Uint128 l2_gas_price_fri = 18;  // Added on v0.13.3.
>     optional Uint128 l2_gas_price_wei = 19;  // Added on v0.13.3.
> ```

does this need to be moved down? @ShahakShama 



_Code quote:_
```proto
    optional Uint128 l2_gas_price_fri = 18;  // Added on v0.13.3.
    optional Uint128 l2_gas_price_wei = 19;  // Added on v0.13.3.
```


<!-- Sent from Reviewable.io -->

2024-09-01 12:57 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 15 of 16 files reviewed, 10 unresolved discussions (waiting on @ShahakShama and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-01 13:14 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 9 of 16 files reviewed, 8 unresolved discussions (waiting on @DvirYo-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SdQNU6NVOcgxSbKpV:-O5hYetSCQcQFmBQ0FDz:b1raydu) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

In addition, the 0x2 value does not fit with what you implement in the reader client
</blockquote></details>

I've changed the value to 0 like it should be old blocks. I'm not sure what should be maintained here, according to @ShahakShama, the hash computation in `papyrus_common` is deprecated and can probably be removed. And so are this test files, only used for validating the deprecated hash computation. Hashes are now computed via the `starknet_api` crate (and the hash computation in `papyrus_common` is not called), so I don't think we need to worry about the hash mismatch in the new edited jsons, and they can probably be removed entirely.

___
___
*[`crates/papyrus_common/resources/block_hash.json` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SecuY8i471gi2XZUg:-O5hYo_l6kclijFS3Zsr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_common/resources/block_hash.json#L14)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

X
</blockquote></details>

Done.
___
*[`crates/papyrus_common/resources/deprecated_block_hash_v0.json` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SegqoBt2erhlNT0gy:-O5hYrrO1XEUTqZ2qLfS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_common/resources/deprecated_block_hash_v0.json#L14)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

X
</blockquote></details>

Done.
___
*[`crates/papyrus_common/resources/deprecated_block_hash_v1.json` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SehZv4UrlsAHCd-uh:-O5hYue-C5RIELbuIsq9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_common/resources/deprecated_block_hash_v1.json#L14)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

X
</blockquote></details>

Done.
___
*[`crates/papyrus_common/resources/deprecated_block_hash_v1_no_events.json` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SeiHQ0eBzxpddW3In:-O5hYxslDg3mX9OfBk--:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_common/resources/deprecated_block_hash_v1_no_events.json#L14)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

X
</blockquote></details>

Done.
___
*[`crates/papyrus_common/resources/deprecated_block_hash_v2.json` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SeixCDVqjdPplIisZ:-O5hZ1KT80q7a3qAsLmh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_common/resources/deprecated_block_hash_v2.json#L14)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

X
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/header.proto` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5heFKyEWMJdhXGp45S:-O5hh5Wb95yh3ZetMpyD:buux8g3) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_protobuf/src/proto/p2p/proto/header.proto#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this need to be moved down? @ShahakShama
</blockquote></details>

I preferred the prices to be grouped by context over keeping the indices increasing visually.
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5SlRkQDJdMUTtMhtqp:-O5hZJ0g52dcqcYey8-C:b-w1zzbi) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/starknet_client/src/reader/objects/block_test.rs#L27)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

If you know that the schema of new blocks will change, add those changes manually, i.e., add the l2_get_price field to the block.
</blockquote></details>

I manually changed it. When real data is live, I'd like to replace the manually edited file with such data.


<!-- Sent from Reviewable.io -->

2024-09-01 13:30 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 9 of 16 files reviewed, 8 unresolved discussions (waiting on @DvirYo-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/header.proto` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5heFKyEWMJdhXGp45S:-O5hltxVB64hg-LOhQkz:b-4n198p) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_protobuf/src/proto/p2p/proto/header.proto#L25)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I preferred the prices to be grouped by context over keeping the indices increasing visually.
</blockquote></details>

the order may have meaning here, I want shahak's input


<!-- Sent from Reviewable.io -->

2024-09-01 13:33 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 16 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 15 of 16 files reviewed, 9 unresolved discussions (waiting on @DvirYo-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/header.rs` line 0 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5hmW1DA5Dse8UExtPI:-O5hmW1E55awLY5cbsyX:beln0ze) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/papyrus_protobuf/src/converters/header.rs#L0)):*
is the block hash computation of old block backward-compatible? we shouldn't be hashing extra zeros


<!-- Sent from Reviewable.io -->

2024-09-02 07:44 UTC, DvirYo-starkware requested changes
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama and @TzahiTaub)

___
*[`crates/starknet_client/src/reader/objects/block.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5lfhws8R9ftHsSOfXK:-O5lfhws8R9ftHsSOfXL:bz59nav) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/starknet_client/src/reader/objects/block.rs#L62)):*
> ```XML
>     pub l1_data_gas_price: GasPricePerToken,
>     // New field in V0.13.3.
>     #[serde(default)]
> ```

If I understand this PR correctly, this field will be retroactively present in old blocks. If this is the case, you can remove the `#[serde(default)]`.



_Code quote:_
```XML
#[serde(default)]
```


<!-- Sent from Reviewable.io -->

2024-09-03 12:48 UTC, ShahakShama commented
*[`crates/starknet_client/src/reader/objects/block.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5lfhws8R9ftHsSOfXK:-O5rvCkt0jttgFXRDKSK:bg33hzx) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/starknet_client/src/reader/objects/block.rs#L62)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

If I understand this PR correctly, this field will be retroactively present in old blocks. If this is the case, you can remove the `#[serde(default)]`.
</blockquote></details>

No, because we want the client to support 0.13.2 and 0.13.3 during the time period when 0.13.3 is in integration but not in mainnet


<!-- Sent from Reviewable.io -->

2024-09-03 12:49 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @DvirYo-starkware, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/header.rs` line  at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5hmW1DA5Dse8UExtPI:-O5rtN1h67XSFMX2KjlE:bqbipkt) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/papyrus_protobuf/src/converters/header.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is the block hash computation of old block backward-compatible? we shouldn't be hashing extra zeros
</blockquote></details>

Is your comment on the wrong file?
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/header.proto` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5heFKyEWMJdhXGp45S:-O5rsgXC5U-hjm235-t6:bjhepwr) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_protobuf/src/proto/p2p/proto/header.proto#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the order may have meaning here, I want shahak's input
</blockquote></details>

Move it down, and add a TODO on me to move it back up and change the numbering to be grouped by context once we insert l2 gas fields to the p2p specs
___
*[`crates/papyrus_storage/src/header.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5ru00F-aGrL9kxIuXv:-O5ru00F-aGrL9kxIuXw:biy6dm1) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/papyrus_storage/src/header.rs#L74)):*
> ```XML
>     pub l1_gas_price: GasPricePerToken,
>     pub l1_data_gas_price: GasPricePerToken,
>     pub l2_gas_price: GasPricePerToken,
> ```

@dan-starkware @DvirYo-starkware Do we need to increase the storage version for this or was the version broken recently and we can do breaking changes without increasing the version?
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5rv5eFCvkC_VS_3SzL:-O5rv5eFCvkC_VS_3SzM:bt3x26h) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L76)):*
> ```XML
>             price_in_wei: GasPrice(9),
>         },
>         l2_gas_price: GasPricePerToken { price_in_fri: GasPrice(1), price_in_wei: GasPrice(1) },
> ```

I think @yoavGrs should review this, right?
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5rvfC3EnuAu1PM3_19:-O5rvfC3EnuAu1PM3_1A:b-pjn7pj) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/starknet_client/src/reader/objects/block_test.rs#L27)):*
> ```XML
> #[test]
> fn load_block_succeeds() {
>     // TODO(Tzahi): Replace block_post_0_13_3 (copied from 0_13_2) with live data once available.
> ```

copied from 0_13_2 -> copied from 0_13_2 and added additional fields


<!-- Sent from Reviewable.io -->

2024-09-04 07:25 UTC, DvirYo-starkware submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_storage/src/header.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5ru00F-aGrL9kxIuXv:-O5vui8a3tkHSHjuU-zK:b-d4q5hs) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/papyrus_storage/src/header.rs#L74)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

@dan-starkware @DvirYo-starkware Do we need to increase the storage version for this or was the version broken recently and we can do breaking changes without increasing the version?
</blockquote></details>

We will break the storage in 13.3. There is already a PR that does that
___
*[`crates/starknet_client/src/reader/objects/block.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5lfhws8R9ftHsSOfXK:-O5vu4hT9wmNQnAVUah_:b-u3533k) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/starknet_client/src/reader/objects/block.rs#L62)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No, because we want the client to support 0.13.2 and 0.13.3 during the time period when 0.13.3 is in integration but not in mainnet
</blockquote></details>

I don't see a reason for that when Papyrus version is coupled with Starknet version.


<!-- Sent from Reviewable.io -->

2024-09-04 08:17 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5w5b4z0cuLEeA1lNGV:-O5w56MD5HoibJfeqmdo:b-hv2ucx) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L136)):*
> ```XML
>             parent_hash,
>             block_number,
>             l1_gas_price,
> ```

Consider adding a TODO for testing l2_gas_price


<!-- Sent from Reviewable.io -->

2024-09-04 08:19 UTC, DvirYo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/starknet_client/src/reader/objects/block.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5lfhws8R9ftHsSOfXK:-O5w63Mg9Kqc8raRYpRg:b-t81ewq) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/starknet_client/src/reader/objects/block.rs#L62)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I don't see a reason for that when Papyrus version is coupled with Starknet version.
</blockquote></details>

I talked with Dan; we need this quality for syncing backup.


<!-- Sent from Reviewable.io -->

2024-09-05 07:58 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 14 of 16 files reviewed, 6 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/header.rs` line  at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5hmW1DA5Dse8UExtPI:-O5xKMbz8BiELYugFd9-:bliikyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/papyrus_protobuf/src/converters/header.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

referring to the change in `impl From<(BlockHeader, Vec<BlockSignature>)> for protobuf::SignedBlockHeader`, here below
</blockquote></details>

This PR doesn't change the block hash at all.
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/header.proto` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5heFKyEWMJdhXGp45S:-O5xLeyTDHdlcMQQBDsT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48fb9f68edf53d68d371a20ee638d6e958651ecd/crates/papyrus_protobuf/src/proto/p2p/proto/header.proto#L25)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move it down, and add a TODO on me to move it back up and change the numbering to be grouped by context once we insert l2 gas fields to the p2p specs
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5rv5eFCvkC_VS_3SzL:-O5xMfHjDYwhLjdaMsCa:bmwewaf) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L76)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think @yoavGrs should review this, right?
</blockquote></details>

I take these PRs


<!-- Sent from Reviewable.io -->

2024-09-12 08:53 UTC, ShahakShama reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/header.rs` line  at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5hmW1DA5Dse8UExtPI:-O6_Qh6fC9LgdgMw6pgq:bpqgtbq) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/papyrus_protobuf/src/converters/header.rs#L)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

This PR doesn't change the block hash at all.
</blockquote></details>

@yoavGrs is right, but we need to add l2_gas to the header hash at some point in the future


<!-- Sent from Reviewable.io -->

2024-09-15 11:53 UTC, dorimedini-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-16 13:03 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: 13 of 16 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware and @TzahiTaub)

___
*[`crates/papyrus_protobuf/src/converters/header.rs` line  at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5hmW1DA5Dse8UExtPI:-O6uvWiVCsmXMutltsVC:bjwd0im) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/papyrus_protobuf/src/converters/header.rs#L)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

@yoavGrs is right, but we need to add l2_gas to the header hash at some point in the future
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/sequencer/683


<!-- Sent from Reviewable.io -->

2024-09-17 11:10 UTC, dorimedini-starkware approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-18 07:05 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/641#-O5rvfC3EnuAu1PM3_19:-O7-JcpkAPpvqRoUC1OJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52f2a184430f4e63a4cabd37675896ebdd39a498/crates/starknet_client/src/reader/objects/block_test.rs#L27)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

copied from 0_13_2 -> copied from 0_13_2 and added additional fields
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-18 07:18 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641#-:-O72zgM4DOwewi-5tKa3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-18 08:08 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-18 08:59 UTC, dorimedini-starkware approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-18 09:03 UTC, yoavGrs approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-18 11:16 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641#-:-O73qErEBSwiNyR71t91:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-18 11:32 UTC, yoavGrs approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/641)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-09-18 18:20 UTC, merged