build(fee): add l2 gas costs to versioned constants
starkware-libs/sequencer pull request #671
Opened 2024-09-01 13:47 UTC by nimrod-starkware

2024-09-01 13:49 UTC, nimrod-starkware reviewed
The l2 gas prices from @leo-starkware are [here](https://docs.google.com/document/d/1evf5OUw0AOTBkJKwY6gqYKEs3XOwgCoiLz4j2gyhd74/edit#heading=h.on7q5hjeah67)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671#-:-O5hpvZm2T8r5uJA5tKx:b-up9ssz)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @amosStarkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-01 14:00 UTC, nimrod-starkware reviewed
python side [PR](https://reviewable.io/reviews/starkware-industries/starkware/35865)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671#-:-O5hsdKJEz08PKFbkaZv:bn41wgr)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @amosStarkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-01 14:04 UTC, dorimedini-starkware requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5hrtD1-xLsk0eLMms_:-O5hrtD1-xLsk0eLMmsa:b-md8emn) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/resources/versioned_constants.json#L12)):*
> ```JSON
>     },
>     "invoke_tx_max_n_steps": 10000000,
>     "l2_resource_gas_costs": {
> ```

are are there L1 and L2 gas prices in a field called "l2_resource_gas_costs"?
these are l2 *resources*, prices in units of different gas types?



_Code quote:_
```JSON
"l2_resource_gas_costs"
```
___
*[`crates/blockifier/resources/versioned_constants.json` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5hriCt2eErY6JHZwq7:-O5hriCt2eErY6JHZwq8:bwnudtq) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/resources/versioned_constants.json#L23)):*
> ```JSON
>             ]
>         },
>         "event_key_factor": {
> ```

is this even a price?
it's a "factor" (unitless quantity);
should this be written twice (l1 and l2 gas units)?



_Code quote:_
```JSON
event_key_factor
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5htKeq6WXRrbXVXPQb:-O5htKeq6WXRrbXVXPQc:b-37u6eb) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/src/versioned_constants.rs#L186)):*
> ```XML
>     }
> 
>     #[cfg(any(feature = "testing", test))]
> ```

why defaults here? why not `1`, like for l1 gas?
___
*[`crates/blockifier/src/versioned_constants.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5htRPvEl0iW9viW7O6:-O5htRPvEl0iW9viW7O7:baguh0t) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/src/versioned_constants.rs#L240)):*
> ```XML
>     // A more complicated instance to increase test coverage.
>     #[cfg(any(feature = "testing", test))]
>     pub fn create_float_for_testing() -> Self {
> ```

why not "real" prices here?


<!-- Sent from Reviewable.io -->

2024-09-02 06:55 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 5 of 12 files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5hrtD1-xLsk0eLMms_:-O5lQ6ZQEZllyNgccvhZ:b-ra08q4) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/resources/versioned_constants.json#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

are are there L1 and L2 gas prices in a field called "l2_resource_gas_costs"?
these are l2 *resources*, prices in units of different gas types?
</blockquote></details>

yes exactly, these are l2 resources that we can charge with l1 gas & l2 gas.
i agree the names are not so clear; can you think of better names? 
___
*[`crates/blockifier/resources/versioned_constants.json` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5hriCt2eErY6JHZwq7:-O5lRErb2faIpo8gW0iP:bvunj8q) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/resources/versioned_constants.json#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this even a price?
it's a "factor" (unitless quantity);
should this be written twice (l1 and l2 gas units)?
</blockquote></details>

I guess you are right; reverted it to a single number.
___
*[`crates/blockifier/src/versioned_constants.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5htKeq6WXRrbXVXPQb:-O5lVx49609_fDd80l9g:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/src/versioned_constants.rs#L186)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why defaults here? why not `1`, like for l1 gas?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5htRPvEl0iW9viW7O6:-O5lVxQoE32q-YWOozBj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/src/versioned_constants.rs#L240)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not "real" prices here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-02 07:07 UTC, dorimedini-starkware requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5hrtD1-xLsk0eLMms_:-O5lXoqh5MPnf6tMQG7k:b9vog7g) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/resources/versioned_constants.json#L12)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

yes exactly, these are l2 resources that we can charge with l1 gas & l2 gas.
i agree the names are not so clear; can you think of better names?
</blockquote></details>

maybe `sequencer_resource_gas_costs`?
out of scope of the current PR, but @Yoni-Starkware do you have an opinion?
___
*[`crates/blockifier/src/versioned_constants.rs` line 194 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5lYOD43tswoSC9TgYD:-O5lYOD43tswoSC9TgYE:b-3j0t7h) ([raw file](https://github.com/starkware-libs/sequencer/blob/f845fcee73514eec35f7f730a5bedb30f6096c14/crates/blockifier/src/versioned_constants.rs#L194)):*
> ```XML
>                     l1_gas: ResourceCost::from_integer(1),
>                     l2_gas: ResourceCost::from_integer(1),
>                 },
> ```

to reduce duplication, implement a `from_integers` associated function and use it everywhere



_Suggestion:_
```XML
                ResourceCosts::from_integers(1, 1),
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 376 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5lYgnyEn-QyZReN26i:-O5lYgnyEn-QyZReN26j:b-8ecd2l) ([raw file](https://github.com/starkware-libs/sequencer/blob/f845fcee73514eec35f7f730a5bedb30f6096c14/crates/blockifier/src/versioned_constants.rs#L376)):*
> ```XML
>     // where rational numbers are supported.
>     pub gas_per_code_byte: ResourceCosts,
> }
> ```

where are the rest of the fields of `l2_resource_gas_costs`...? non-blocking



_Code quote:_
```XML
pub struct L2ResourceGasCosts {
    // TODO(barak, 18/03/2024): Once we start charging per byte change to milligas_per_data_byte,
    // divide the value by 32 in the JSON file.
    pub gas_per_data_felt: ResourceCosts,
    pub event_key_factor: ResourceCost,
    // TODO(avi, 15/04/2024): This constant was changed to 32 milligas in the JSON file, but the
    // actual number we wanted is 1/32 gas per byte. Change the value to 1/32 in the next version
    // where rational numbers are supported.
    pub gas_per_code_byte: ResourceCosts,
}
```


<!-- Sent from Reviewable.io -->

2024-09-02 07:18 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 194 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5lYOD43tswoSC9TgYD:-O5laAIW-Buv7KsCsmXh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f845fcee73514eec35f7f730a5bedb30f6096c14/crates/blockifier/src/versioned_constants.rs#L194)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

to reduce duplication, implement a `from_integers` associated function and use it everywhere
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 376 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5lYgnyEn-QyZReN26i:-O5l_Als1zin5f5jCKGC:b7vafud) ([raw file](https://github.com/starkware-libs/sequencer/blob/f845fcee73514eec35f7f730a5bedb30f6096c14/crates/blockifier/src/versioned_constants.rs#L376)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where are the rest of the fields of `l2_resource_gas_costs`...? non-blocking
</blockquote></details>

there are only these 3. (in addition to the builtins)


<!-- Sent from Reviewable.io -->

2024-09-02 07:22 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671#-:-O5lbGSo0u1a-UJnNIwU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-09-02 15:52 UTC, Yoni-Starkware requested changes
Blocking for now

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671#-:-O5nQuOy68EFb8f5Wcoy:bxxqpmh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-09-03 12:52 UTC, dorimedini-starkware submitted a review, later dismissed
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 25 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rto23BE1ki5FEROkd:-O5rto23BE1ki5FEROke:b-g16uym) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/resources/versioned_constants.json#L25)):*
> ```JSON
>             1
>         ]
>     },
> ```

or `l2_resource_sierra_gas_costs`, WDYT @Yoni-Starkware ?
(context: versioned constants needs to be easy to read)



_Suggestion:_
```JSON
    "l2_resource_l2_gas_costs": {
        "gas_per_data_felt": [
            5120,
            1
        ],
        "event_key_factor": [
            2,
            1
        ],
        "gas_per_code_byte": [
            35000,
            1
        ]
    },
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 134 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5ru4xvCh_5thWHVpQT:-O5ru4xvCh_5thWHVpQU:b-909uga) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/versioned_constants.rs#L134)):*
> ```XML
> 
>     /// Returns the ratio between l1 gas price and l2 gas price.
>     pub fn l1_to_l2_gas_price_ratio(&self) -> Ratio<u128> {
> ```

use the wrapper type please



_Suggestion:_
```XML
ResourceCost
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 212 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5ruZNd4u0Crki54FKX:-O5ruZNd4u0Crki54FKY:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/versioned_constants.rs#L212)):*
> ```XML
>             (BuiltinName::mul_mod.to_str_with_suffix().to_string(), ResourceCost::from_integer(1)),
>         ]));
>         let latest = Self::create_float_for_testing();
> ```





_Suggestion:_
```XML

let latest = Self::create_float_for_testing();
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 223 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rue7g2yZhu8BRyUey:-O5rue7g2yZhu8BRyUez:brvsd7h) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/versioned_constants.rs#L223)):*
> ```XML
>     #[cfg(any(feature = "testing", test))]
>     pub fn create_float_for_testing() -> Self {
>         let vm_resource_fee_cost = Arc::new(HashMap::from([
> ```

what is the difference between these values and the "real" values?
why not just use the latest VC here?



_Code quote:_
```XML
vm_resource_fee_cost
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 399 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rvN1sBM9EeQLKEWjd:-O5rvN1sBM9EeQLKEWje:bd95qbe) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/transaction/objects.rs#L399)):*
> ```XML
> 
>     /// Returns the L1 gas cost of the transaction's state changes.
>     pub fn get_state_changes_cost(&self, use_kzg_da: bool) -> GasVector {
> ```

we don't specifically compute the L1 part here: this is the real gas cost of state changes. No L2 gas will be involved here; and if it will be, we will return L2 gas as well.
either (a) remove the `L1` from the docstring or (b) rename the function to `get_state_changes_l1_cost`



_Code quote:_
```XML
    /// Returns the L1 gas cost of the transaction's state changes.
    pub fn get_state_changes_cost(&self, use_kzg_da: bool) -> GasVector {
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 405 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rvWRRCwQl582I7jLe:-O5rvWRRCwQl582I7jLf:bi3in0u) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/transaction/objects.rs#L405)):*
> ```XML
> 
>     /// Returns the L1 gas cost of the transaction's emmited events.
>     pub fn get_events_cost(&self, versioned_constants: &VersionedConstants) -> GasVector {
> ```

see above; ATM it's L1 costs but we ( @amosStarkware  ) may change this soon



_Suggestion:_
```XML
    /// Returns the gas cost of the transaction's emmited events.
    pub fn get_events_cost(&self, versioned_constants: &VersionedConstants) -> GasVector {
```
___
*[`crates/blockifier/resources/versioned_constants_13_1.json` line 0 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rvmj43Efyh1rGbpX4:-O5rvmj43Efyh1rGbpX5:b-nd2fki) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/resources/versioned_constants_13_1.json#L0)):*
about the old VCs:
the structure hasn't changed, but some values have changed *in their semantic meaning* - a value that represented L1 gas price now represents L2 gas price.
you need to update the values in these old VC JSONs as well to the "correct" values (use the inverse conversion), otherwise a new blockifier running with old VC will interpret the values incorrectly and break reexecution


<!-- Sent from Reviewable.io -->

2024-09-03 15:55 UTC, Yoni-Starkware requested changes
Don't we need to fix all VC files?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671#-:-O5sa6QKArjhgjSDBELr:bbsf68p)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 25 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rto23BE1ki5FEROkd:-O5s_JXB-RK5zWf4h_2A:b-9wkgdo) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/resources/versioned_constants.json#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

or `l2_resource_sierra_gas_costs`, WDYT @Yoni-Starkware ?
(context: versioned constants needs to be easy to read)
</blockquote></details>

Maybe `storage_l2_gas_costs`. Not in this PR.


<!-- Sent from Reviewable.io -->

2024-09-04 06:31 UTC, nimrod-starkware reviewed
yes, added them as well now

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671#-:-O5vipY72iZvy2LpKuX6:b-34m4fw)* status: 7 of 12 files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_1.json` line  at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rvmj43Efyh1rGbpX4:-O5vio1c9-RoDg7TX9cE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/resources/versioned_constants_13_1.json#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

about the old VCs:
the structure hasn't changed, but some values have changed *in their semantic meaning* - a value that represented L1 gas price now represents L2 gas price.
you need to update the values in these old VC JSONs as well to the "correct" values (use the inverse conversion), otherwise a new blockifier running with old VC will interpret the values incorrectly and break reexecution
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 134 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5ru4xvCh_5thWHVpQT:-O5vRTSx6Y4CXJIpcNkB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/versioned_constants.rs#L134)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use the wrapper type please
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 212 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5ruZNd4u0Crki54FKX:-O5vScbU2zcylwsqiKBt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/versioned_constants.rs#L212)):*
> ```XML
>             (BuiltinName::mul_mod.to_str_with_suffix().to_string(), ResourceCost::from_integer(1)),
>         ]));
>         let latest = Self::create_float_for_testing();
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 223 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rue7g2yZhu8BRyUey:-O5vRYYF5cbeoaDt_hqO:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/versioned_constants.rs#L223)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what is the difference between these values and the "real" values?
why not just use the latest VC here?
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/objects.rs` line 399 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rvN1sBM9EeQLKEWjd:-O5vSJD80YQxmGIuHX9G:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/transaction/objects.rs#L399)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we don't specifically compute the L1 part here: this is the real gas cost of state changes. No L2 gas will be involved here; and if it will be, we will return L2 gas as well.
either (a) remove the `L1` from the docstring or (b) rename the function to `get_state_changes_l1_cost`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 405 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rvWRRCwQl582I7jLe:-O5vSTmb9tH5NcXV3pQR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/transaction/objects.rs#L405)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above; ATM it's L1 costs but we ( @amosStarkware  ) may change this soon
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 07:15 UTC, Yoni-Starkware reviewed
Meshi added new VC file in this [merge](https://github.com/starkware-libs/sequencer/pull/691#pullrequestreview-2277639298).
Need to fix it as well once it is merged.
@dorimedini-starkware we need some basic test on old VC files...

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671#-:-O5vsTZ0D3X1-vVcHC0s:bfuetpz)* status: 6 of 12 files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-05 12:53 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 4 of 12 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 22 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O61EqV_2bgj9ykMHMWm:-O61EqV_2bgj9ykMHMWn:bcfyycs) ([raw file](https://github.com/starkware-libs/sequencer/blob/25a20cc98a4b3b2c74d83aa00368b4819de6f40a/crates/blockifier/resources/versioned_constants.json#L22)):*
> ```JSON
>         ],
>         "gas_per_code_byte": [
>             35000,
> ```

Blocking until fixed



_Code quote:_
```JSON
        35000,
```


<!-- Sent from Reviewable.io -->

2024-09-05 12:55 UTC, Yoni-Starkware reviewed
Fix versioned_constants_13_2_1.json as well

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671#-:-O61F38y6AXyvL4Fij4O:b-e5mykd)* status: 4 of 12 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-09-05 13:29 UTC, nimrod-starkware reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671#-:-O61Mz5yBtSBaVEYDsFL:bb6un1j)* status: 4 of 13 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 22 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O61EqV_2bgj9ykMHMWm:-O61N5875nrg0n9xW78_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/25a20cc98a4b3b2c74d83aa00368b4819de6f40a/crates/blockifier/resources/versioned_constants.json#L22)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Blocking until fixed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-05 13:46 UTC, Yoni-Starkware reviewed
> Reviewed 3 of 5 files at r5, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5hrtD1-xLsk0eLMms_:-O61Qkb19ZUuCiZVveVq:bzbpkgv) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/resources/versioned_constants.json#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe `sequencer_resource_gas_costs`?
out of scope of the current PR, but @Yoni-Starkware do you have an opinion?
</blockquote></details>

`archival_data_gas_costs`


<!-- Sent from Reviewable.io -->

2024-09-08 06:22 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5hrtD1-xLsk0eLMms_:-O6FHxDR88gDY_U1FkOV:b5slsi3) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/resources/versioned_constants.json#L12)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`archival_data_gas_costs`
</blockquote></details>

You want to rename `l2_resource_gas_costs` => `archival_data_gas_costs`?


<!-- Sent from Reviewable.io -->

2024-09-08 06:34 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5hrtD1-xLsk0eLMms_:-O6FKlya9vldSMqknIRQ:b-x0paxf) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/resources/versioned_constants.json#L12)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

You want to rename `l2_resource_gas_costs` => `archival_data_gas_costs`?
</blockquote></details>

Yes :)


<!-- Sent from Reviewable.io -->

2024-09-08 06:43 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5hrtD1-xLsk0eLMms_:-O6FM_sRAy7QgvgvJa1z:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fab73ba761ec974e53f1c18f4f1cbe6f03218f/crates/blockifier/resources/versioned_constants.json#L12)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yes :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-08 06:53 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 9 of 14 files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-08 11:29 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 10 of 14 files reviewed, 11 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 223 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rue7g2yZhu8BRyUey:-O6GMD7S6naFAJ_AMUTO:bknomk3) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/versioned_constants.rs#L223)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

The problem is that `create_for_testing` points to the latest. So changes there would break the tests.
But it's okay for now (we took the latest anyway, except the fee costs.)

@nimrod-starkware please remove the function `create_float_for_testing`
___
*[`crates/blockifier/src/versioned_constants.rs` line 128 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GELTo9EaA_0G6nJJJ:-O6GELTo9EaA_0G6nJJK:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eb1122c9f2687525f7dc36bf4ca1967eee4ce28/crates/blockifier/src/versioned_constants.rs#L128)):*
> ```XML
>     }
> 
>     /// Converts from l1 gas cost to l2 gas cost with **upward rounding**
> ```





_Suggestion:_
```XML
    /// Converts from L1 gas cost to L2 gas cost with **upward rounding**.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 129 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GEUGe-3nP4UgpjP63:-O6GEUGe-3nP4UgpjP64:bcjx37d) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eb1122c9f2687525f7dc36bf4ca1967eee4ce28/crates/blockifier/src/versioned_constants.rs#L129)):*
> ```XML
> 
>     /// Converts from l1 gas cost to l2 gas cost with **upward rounding**
>     pub fn l1_to_l2_gas_price_conversion(&self, l1_gas_price: u128) -> u128 {
> ```

Nonblocking - in general, functions should be in this form - "get", "set", "convert", ...



_Suggestion:_
```XML
convert_l1_to_l2_gas_price(
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 134 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GEj6G0C6Ggkm-DlDh:-O6GEj6H9vjwNmmB5Oz-:b741ob0) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eb1122c9f2687525f7dc36bf4ca1967eee4ce28/crates/blockifier/src/versioned_constants.rs#L134)):*
> ```XML
>     }
> 
>     /// Returns the ratio between l1 gas price and l2 gas price.
> ```

Confusing. 
In this form it's clear that `L1_gas * ration = L2_gas`



_Suggestion:_
```XML
/// Returns the following ratio: L2_gas_price/L1_gas_price.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 219 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GMjbl5roVG2mtm8op:-O6GMjbl5roVG2mtm8oq:b-b411ym) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eb1122c9f2687525f7dc36bf4ca1967eee4ce28/crates/blockifier/src/versioned_constants.rs#L219)):*
> ```XML
>         archival_data_gas_costs.gas_per_code_byte *= latest_step_cost / step_cost;
>         archival_data_gas_costs.gas_per_data_felt *= latest_step_cost / step_cost;
>         Self { vm_resource_fee_cost, archival_data_gas_costs, ..latest }
> ```

Add a comment.



_Code quote:_
```XML
        let latest_step_cost = latest.vm_resource_fee_cost["n_steps"];
        let mut archival_data_gas_costs = latest.archival_data_gas_costs;
        archival_data_gas_costs.gas_per_code_byte *= latest_step_cost / step_cost;
        archival_data_gas_costs.gas_per_data_felt *= latest_step_cost / step_cost;
        Self { vm_resource_fee_cost, archival_data_gas_costs, ..latest }
```


<!-- Sent from Reviewable.io -->

2024-09-08 13:35 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 10 of 14 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 128 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GELTo9EaA_0G6nJJJ:-O6Gommn7almuORqqOQm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eb1122c9f2687525f7dc36bf4ca1967eee4ce28/crates/blockifier/src/versioned_constants.rs#L128)):*
> ```XML
>     }
> 
>     /// Converts from l1 gas cost to l2 gas cost with **upward rounding**
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 134 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GEj6G0C6Ggkm-DlDh:-O6GowywB4PG6_z6DFQM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eb1122c9f2687525f7dc36bf4ca1967eee4ce28/crates/blockifier/src/versioned_constants.rs#L134)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Confusing. 
In this form it's clear that `L1_gas * ration = L2_gas`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 219 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GMjbl5roVG2mtm8op:-O6Gq76gEQhaxpTeAzMc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eb1122c9f2687525f7dc36bf4ca1967eee4ce28/crates/blockifier/src/versioned_constants.rs#L219)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add a comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-08 13:44 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 8 of 17 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 223 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O5rue7g2yZhu8BRyUey:-O6GrjHi-qEhbjiReXfr:bs7wumb) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1cbc283b54b0d8e2f94901169d2faf61a45589/crates/blockifier/src/versioned_constants.rs#L223)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The problem is that `create_for_testing` points to the latest. So changes there would break the tests.
But it's okay for now (we took the latest anyway, except the fee costs.)

@nimrod-starkware please remove the function `create_float_for_testing`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-08 13:44 UTC, Yoni-Starkware requested changes
> Reviewed 7 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 15 of 17 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 221 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GrJwk6Ug2TJ9jYEUG:-O6GrJwk6Ug2TJ9jYEUH:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/versioned_constants.rs#L221)):*
> ```XML
>         ]));
> 
>         // Maintain the ratio between between L1 gas price and L2 gas price.
> ```





_Suggestion:_
```XML
between L1 gas p
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 353 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GroVx-8jidX_QS4zN:-O6GroVx-8jidX_QS4zO:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L353)):*
> ```XML
>         mode: &GasVectorComputationMode,
>     ) -> GasVector {
>         let l2_resources_in_l2_gas = self.get_calldata_and_signature_cost(versioned_constants)
> ```





_Suggestion:_
```XML
et l2_gas
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6Gs1bW7jZ1ML_5wbfj:-O6Gs1bW7jZ1ML_5wbfk:b-jy533v) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L359)):*
> ```XML
>             GasVectorComputationMode::All => GasVector::from_l2_gas(l2_resources_in_l2_gas),
>             GasVectorComputationMode::NoL2Gas => GasVector::from_l1_gas(
>                 versioned_constants.convert_l2_to_l1_gas_price(l2_resources_in_l2_gas),
> ```

It's not just `price` now. Change the argument to `l2_gas`



_Suggestion:_
```XML
convert_l2_to_l1_gas
```


<!-- Sent from Reviewable.io -->

2024-09-08 13:49 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 15 of 17 files reviewed, 11 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6Gs1bW7jZ1ML_5wbfj:-O6GtAz08tNRk8x2b6Dq:bjv2aka) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L359)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It's not just `price` now. Change the argument to `l2_gas`
</blockquote></details>

Hmmm, it might be problematic. Think about a good solution. 
Also, note that @AvivYossef-starkware is changing `ResourceCost` to hold `u64`.
___
*[`crates/blockifier/src/transaction/objects.rs` line 437 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GsVup6aow3n-7Bxex:-O6GsVup6aow3n-7Bxey:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L437)):*
> ```XML
>     /// Returns the cost of the transaction's emmited events in L2 gas units.
>     pub fn get_events_cost(&self, versioned_constants: &VersionedConstants) -> u128 {
>         let l2_resource_gas_costs = &versioned_constants.archival_data_gas_costs;
> ```





_Suggestion:_
```XML
archival_data_gas_costs
```


<!-- Sent from Reviewable.io -->

2024-09-08 14:50 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 10 of 17 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 353 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GroVx-8jidX_QS4zN:-O6GyLn2B3tmgX2CUVsq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L353)):*
> ```XML
>         mode: &GasVectorComputationMode,
>     ) -> GasVector {
>         let l2_resources_in_l2_gas = self.get_calldata_and_signature_cost(versioned_constants)
> ```

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6Gs1bW7jZ1ML_5wbfj:-O6Gz44o3ns4VUPwJ2o9:b-tbd5dt) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L359)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Hmmm, it might be problematic. Think about a good solution. 
Also, note that @AvivYossef-starkware is changing `ResourceCost` to hold `u64`.
</blockquote></details>

Why u64? Isn't that problematic with the VM resources? (which are not integers).
___
*[`crates/blockifier/src/transaction/objects.rs` line 437 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6GsVup6aow3n-7Bxex:-O6GxexN6dWkR6Ov2UHd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L437)):*
> ```XML
>     /// Returns the cost of the transaction's emmited events in L2 gas units.
>     pub fn get_events_cost(&self, versioned_constants: &VersionedConstants) -> u128 {
>         let l2_resource_gas_costs = &versioned_constants.archival_data_gas_costs;
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-08 14:52 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 10 of 17 files reviewed, 11 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 356 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6H6IJf30iKV2eaBIQO:-O6H6IJgCdvJ1tBwoc-Y:bj6hgou) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee14805b148063b01398444f4bf32cad00a250a8/crates/blockifier/src/transaction/objects.rs#L356)):*
> ```XML
>             .convert_l2_to_l1_gas(self.get_calldata_and_signature_cost(versioned_constants))
>             + versioned_constants.convert_l2_to_l1_gas(self.get_code_cost(versioned_constants))
>             + versioned_constants.convert_l2_to_l1_gas(self.get_events_cost(versioned_constants));
> ```

It's messy... but otherwise, it doesn't pass the tests due to rounding issues (round is not additive).
We can't change the way we calculate fees, right? Because of re-execution?



_Code quote:_
```XML
        let l2_gas = versioned_constants
            .convert_l2_to_l1_gas(self.get_calldata_and_signature_cost(versioned_constants))
            + versioned_constants.convert_l2_to_l1_gas(self.get_code_cost(versioned_constants))
            + versioned_constants.convert_l2_to_l1_gas(self.get_events_cost(versioned_constants));
```


<!-- Sent from Reviewable.io -->

2024-09-08 17:16 UTC, Yoni-Starkware requested changes
> Reviewed 4 of 7 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 15 of 17 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6Gs1bW7jZ1ML_5wbfj:-O6HbfNm0WiQxIvfNaM2:b-8w7m3w) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L359)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Why u64? Isn't that problematic with the VM resources? (which are not integers).
</blockquote></details>

What are they?
___
*[`crates/blockifier/src/transaction/objects.rs` line 356 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6H6IJf30iKV2eaBIQO:-O6HcSge5ULlVk3n2xex:b-2x99jn) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee14805b148063b01398444f4bf32cad00a250a8/crates/blockifier/src/transaction/objects.rs#L356)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

It's messy... but otherwise, it doesn't pass the tests due to rounding issues (round is not additive).
We can't change the way we calculate fees, right? Because of re-execution?
</blockquote></details>

Right. What you did is okay - but you need to do it only in the L1 gas flow.
___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6HbvJ_1OWxRQOiftN7:-O6HbvJ_1OWxRQOiftN8:b-upf5s1) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e11794bacccbb61f3dc14ab289e0cdbe9007d4c/crates/blockifier/src/transaction/objects.rs#L359)):*
> ```XML
>         match mode {
>             GasVectorComputationMode::All => GasVector::from_l2_gas(l2_gas),
>             GasVectorComputationMode::NoL2Gas => GasVector::from_l1_gas(l2_gas),
> ```

Need a fix here



_Code quote:_
```XML
            GasVectorComputationMode::All => GasVector::from_l2_gas(l2_gas),
            GasVectorComputationMode::NoL2Gas => GasVector::from_l1_gas(l2_gas),
```


<!-- Sent from Reviewable.io -->

2024-09-09 05:05 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 15 of 17 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6Gs1bW7jZ1ML_5wbfj:-O6K7vZp0fQ7YsekhNfw:bq2p4ng) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L359)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What are they?
</blockquote></details>

rational numbers given as numerator and denominator
TAL [here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/resources/versioned_constants.json#L570)
___
*[`crates/blockifier/src/transaction/objects.rs` line 356 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6H6IJf30iKV2eaBIQO:-O6KA-mZ31-mkOKE5ivs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee14805b148063b01398444f4bf32cad00a250a8/crates/blockifier/src/transaction/objects.rs#L356)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Right. What you did is okay - but you need to do it only in the L1 gas flow.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6HbvJ_1OWxRQOiftN7:-O6KA01B2A3Vl7wnHvMM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e11794bacccbb61f3dc14ab289e0cdbe9007d4c/crates/blockifier/src/transaction/objects.rs#L359)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Need a fix here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-09 06:18 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 15 of 17 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6Gs1bW7jZ1ML_5wbfj:-O6KQ6Rb43xrPl7n96Iu:b-arplkm) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L359)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

rational numbers given as numerator and denominator
TAL [here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/resources/versioned_constants.json#L570)
</blockquote></details>

I want to change it from Ratio<u128> to Ratio<u64>.
Is it possible? Is the gas price can be represented with u64?


<!-- Sent from Reviewable.io -->

2024-09-09 06:25 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 15 of 17 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6Gs1bW7jZ1ML_5wbfj:-O6KS1fn9bxFaBpdViry:b-xo9krf) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L359)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I want to change it from Ratio<u128> to Ratio<u64>.
Is it possible? Is the gas price can be represented with u64?
</blockquote></details>

I think it's ok. I thought you meant to change it to `u64` and not `Ratio<u64>`


<!-- Sent from Reviewable.io -->

2024-09-09 09:02 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: 16 of 17 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6Gs1bW7jZ1ML_5wbfj:-O6KysIi-rCHkSRd7RmA:by0manf) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L359)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Gas **price** is 128, we can't change it
</blockquote></details>

I talked about it with @AvivYossef-starkware , I think that defining `type ResourceCost = Ratio<u64>` would work...
___
*[`crates/blockifier/src/transaction/objects.rs` line 356 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6KvobX8_CAajMjcUrW:-O6L09r201AGjXpceMMD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7bca65c5f30d6b3b32ecd3c24b03f41e89759fd/crates/blockifier/src/transaction/objects.rs#L356)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Define an array/vec, and in the `match` do sum/fold (when you need to convert)
Comment about the `fold` - we convert before summing to be backward compatible with the old calculation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-09 11:49 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671#-:-O6LbNCr1DHCuq173Fn9:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 359 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/671#-O6Gs1bW7jZ1ML_5wbfj:-O6L__9T3lO1myt3inpB:b-xjb803) ([raw file](https://github.com/starkware-libs/sequencer/blob/ede983276a6c329878767776c34fa5a717ae8c97/crates/blockifier/src/transaction/objects.rs#L359)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I talked about it with @AvivYossef-starkware , I think that defining `type ResourceCost = Ratio<u64>` would work...
</blockquote></details>

I'm not sure, need to be careful with this. But it doesn't block **this** PR


<!-- Sent from Reviewable.io -->

2024-09-09 11:51 UTC, Yoni-Starkware reviewed
> Dismissed @dorimedini-starkware from 7 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/671)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-09 11:57 UTC, merged