chore(blockifier): update transaction post execution validation
starkware-libs/sequencer pull request #712
Opened 2024-09-04 13:01 UTC by AvivYossef-starkware

2024-09-08 15:49 UTC, amosStarkware requested changes
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 1 of 8 files reviewed, 8 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6H9uT962icTIjwpK-w:-O6H9uT962icTIjwpK-x:b-65ngx2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab0f53b44069821259c50978864ee86c15e2e1f/crates/blockifier/src/fee/fee_checks.rs#L107)):*
> ```XML
>                 // TODO(Dori, 1/7/2024): When data gas limit is added (and enforced) in resource
>                 //   bounds, check it here as well (separately, with a different error variant if
>                 //   limit exceeded).
> ```

Blocker on myself: ask Yoni if should be deleted



_Code quote:_
```XML
// TODO(Aner, 21/01/24) modify for 4844 (include check for blob_gas).
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HBilo9hdovhbhTywT:-O6HBilo9hdovhbhTywU:besl38l) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L110)):*
> ```XML
>         match tx_info {
>             TransactionInfo::Current(context) => {
>                 return Ok(check_gas_within_valid_resource_bounds(
> ```

on this branch of the match expression (`Current`), the method always returns, while on the other branch (`Deprecated`) there is a return statement only if both there's an error.
please change the method to return the result of the match expression.



_Code quote:_
```XML
return Ok(check_gas_within_valid_resource_bounds(
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HGuCi9VEbdG516bX1:-O6HGuCi9VEbdG516bX2:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L227)):*
> ```XML
> }
> 
> fn check_gas_within_all_resource_bounds(
> ```





_Suggestion:_
```XML
fn check_all_resources_within_bounds(
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HHm0hBE5Fwdp54l0R:-O6HHm0hBE5Fwdp54l0S:b1pqyeq) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L227)):*
> ```XML
> }
> 
> fn check_gas_within_all_resource_bounds(
> ```

blocker on myself:
ask Yoni to TAL at this method



_Code quote:_
```XML
fn check_gas_within_all_resource_bounds(
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 236 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HHTF6DlQ2c7yOBj0K:-O6HHTF6DlQ2c7yOBj0L:brds4m0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L236)):*
> ```XML
>         all_resource_bounds.l1_data_gas.max_amount.into(),
>     );
>     if gas_vector.l1_gas > l1_gas_max_amount {
> ```

please use a match expression and return its result



_Code quote:_
```XML
if gas_vector.l1_gas > l1_gas_max_amount {
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 259 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HGpCi0ctXbJVmv8SE:-O6HGpCi0ctXbJVmv8SF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L259)):*
> ```XML
> }
> 
> fn check_gas_within_l1_bounds(
> ```





_Suggestion:_
```XML
check_l1_gas_within_bounds
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 264 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HGW1K0EEAMDzazM3E:-O6HGW1K0EEAMDzazM3F:bvmlq4o) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L264)):*
> ```XML
>     tx_context: &TransactionContext,
> ) -> Result<(), FeeCheckError> {
>     let total_discounted_gas_used = compute_discounted_gas_from_gas_vector(gas_vector, tx_context);
> ```

please rebase and use `GasVector::to_discounted_l1_gas` (I added it recently)



_Code quote:_
```XML
let total_discounted_gas_used = compute_discounted_gas_from_gas_vector(gas_vector, tx_context);
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 279 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HFSQO5aQc9AmGpo6e:-O6HFSQP4cmTUj9hg28t:b-h3949x) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L279)):*
> ```XML
>     gas_vector: &GasVector,
>     tx_context: &TransactionContext,
> ) -> Result<(), FeeCheckError> {
> ```

`tx_context` includes the the resource bounds, no need to pass them separately (relevant to two functions).
please make all three functions methods of `FeeCheckReport`.



_Code quote:_
```XML
fn check_gas_within_valid_resource_bounds(
    valid_resource_bounds: &ValidResourceBounds,
    gas_vector: &GasVector,
    tx_context: &TransactionContext,
) -> Result<(), FeeCheckError> {
```


<!-- Sent from Reviewable.io -->

2024-09-15 09:02 UTC, amosStarkware requested changes
> Reviewed 1 of 6 files at r3, 5 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 6 of 8 files reviewed, 9 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6H9uT962icTIjwpK-w:-O6oqE7e3WVGweM1Xtrk:b-yd79x6) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab0f53b44069821259c50978864ee86c15e2e1f/crates/blockifier/src/fee/fee_checks.rs#L107)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Blocker on myself: ask Yoni if should be deleted
</blockquote></details>

@dorimedini-starkware should the above TODO be deleted?
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HHm0hBE5Fwdp54l0R:-O6oqKH28I7PKfMZTFNh:bikz379) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L227)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

blocker on myself:
ask Yoni to TAL at this method
</blockquote></details>

@dorimedini-starkware can you TAL at this method?
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HGuCi9VEbdG516bX1:-O6os-7XEr1CpaLNxNr9:byn2p8v) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L227)):*
> ```XML
> }
> 
> fn check_gas_within_all_resource_bounds(
> ```

please rename
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 279 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HFSQO5aQc9AmGpo6e:-O6otDNh1ZsG8BbrubqA:b-3f6wxa) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L279)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

`tx_context` includes the the resource bounds, no need to pass them separately (relevant to two functions).
please make all three functions methods of `FeeCheckReport`.
</blockquote></details>

please remove `valid_resource_bounds`
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6otjrsBxU2IEswuRiN:-O6otjrsBxU2IEswuRiO:b-szcvf) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_checks.rs#L151)):*
> ```XML
>         );
> 
>         match () {
> ```

I asked you to use a match expression, but this is worse - please use `if` `else` like before. my bad.



_Code quote:_
```XML
match () {
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6ouEzz0IPRrAKuoOMo:-O6ouEzz0IPRrAKuoOMp:bmrc2yw) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_checks.rs#L193)):*
> ```XML
>     }
> 
>     fn check_all_resources_within_bounds(
> ```

I think you renamed the wrong method



_Code quote:_
```XML
check_all_resources_within_bounds
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6KdDDkARIErxn-SgU8:-O6KdDDkARIErxn-SgU9:b-x7zf2z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab0f53b44069821259c50978864ee86c15e2e1f/crates/blockifier/src/fee/fee_test.rs#L3)):*
> ```XML
> use std::collections::HashMap;
> 
> use assert_matches::assert_matches;
> ```

in [this](https://github.com/starkware-libs/sequencer/blob/2dcefb9d12c2b87c3f797a542962de1c3698271c/crates/blockifier/src/blockifier/stateful_validator_test.rs#L31) test:
please add 3 cases (for declare, deploy_account, invoke) that test resource validations on all the resources



_Code quote:_
```XML
use assert_matches::assert_matches;
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 211 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6omuS966nG54MbJJNY:-O6omuSA6CYEKEf_cv73:b-nnxq74) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_test.rs#L211)):*
> ```XML
> #[case::l1_data_bound_overdraft(0, 0, 1000, true)]
> #[case::no_overdraft(0, 0, 0, false)]
> fn test_post_execution_gas_overdraft_all_resource_bounds(
> ```

@dorimedini-starkware any more cases needed? can you also TAL and see if the values make sense?



_Code quote:_
```XML
fn test_post_execution_gas_overdraft_all_resource_bounds(
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 257 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6opz82CQU9qxPe1evl:-O6opz82CQU9qxPe1evm:byirr15) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_test.rs#L257)):*
> ```XML
>     if expect_failure {
>         let error = report.error().unwrap();
>         assert_matches!(error, FeeCheckError::MaxGasAmountExceeded { .. })
> ```

where does `FeeCheckError::MaxGasAmountExceeded { .. }` get its values from?
please be explicit



_Code quote:_
```XML
assert_matches!(error, FeeCheckError::MaxGasAmountExceeded { .. })
```


<!-- Sent from Reviewable.io -->

2024-09-15 09:03 UTC, amosStarkware reviewed
> Reviewed 2 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: all files reviewed, 9 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, @dorimedini-starkware, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-15 11:57 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 5 of 8 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 232 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6pFgAPEPloLusKEKvY:-O6pFgAQ-Cs1nC_O80wk:b-1inojv) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_test.rs#L232)):*
> ```XML
>             .try_into()
>             .unwrap(),
>     );
> ```

Isn't it the same as in `BlockInfo::create_for_testing()`?
(which is called in ` BlockContext::create_for_account_testing()`)



_Code quote:_
```XML
    block_context.block_info.gas_prices = GasPrices::new(
        DEFAULT_ETH_L1_GAS_PRICE.try_into().unwrap(),
        DEFAULT_STRK_L1_GAS_PRICE.try_into().unwrap(),
        DEFAULT_ETH_L1_DATA_GAS_PRICE.try_into().unwrap(),
        DEFAULT_STRK_L1_DATA_GAS_PRICE.try_into().unwrap(),
        VersionedConstants::latest_constants()
            .l1_to_l2_gas_price_conversion(DEFAULT_ETH_L1_GAS_PRICE)
            .try_into()
            .unwrap(),
        VersionedConstants::latest_constants()
            .l1_to_l2_gas_price_conversion(DEFAULT_STRK_L1_GAS_PRICE)
            .try_into()
            .unwrap(),
    );
```


<!-- Sent from Reviewable.io -->

2024-09-15 12:00 UTC, aner-starkware commented
*[`crates/blockifier/src/fee/fee_checks.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6otjrsBxU2IEswuRiN:-O6pXaTQAfSTsVGjpRP6:b7oj7t5) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_checks.rs#L151)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I asked you to use a match expression, but this is worse - please use `if` `else` like before. my bad.
</blockquote></details>

I think using a `for (resource, max_amount, actual_amount) in [...] {if...} Ok(())` on the 3 cases would look better. Also easier to extend if more resources pop up later.


<!-- Sent from Reviewable.io -->

2024-09-15 12:20 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 8 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HBilo9hdovhbhTywT:-O6K_mNpAp30lmE00DHm:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L110)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

on this branch of the match expression (`Current`), the method always returns, while on the other branch (`Deprecated`) there is a return statement only if both there's an error.
please change the method to return the result of the match expression.
</blockquote></details>

Done
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HGuCi9VEbdG516bX1:-O6KUnSvDAkL3BeQY4rB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L227)):*
> ```XML
> }
> 
> fn check_gas_within_all_resource_bounds(
> ```

Done.
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 236 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HHTF6DlQ2c7yOBj0K:-O6KWeo78vjhIy3YZ9CY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L236)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please use a match expression and return its result
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 259 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HGpCi0ctXbJVmv8SE:-O6KYC584LGmVfJ2HtSH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L259)):*
> ```XML
> }
> 
> fn check_gas_within_l1_bounds(
> ```

Done.
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 264 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HGW1K0EEAMDzazM3E:-O6KYPzq0AmFaEne15Sz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L264)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please rebase and use `GasVector::to_discounted_l1_gas` (I added it recently)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 279 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HFSQO5aQc9AmGpo6e:-O6KZJN33_OhoxEBlgiS:b244urq) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L279)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

`tx_context` includes the the resource bounds, no need to pass them separately (relevant to two functions).
please make all three functions methods of `FeeCheckReport`.
</blockquote></details>

But if I do it, I'll need to match every time to extract the resource bounds. Are you sure you prefer it rather than passing the resource bounds?
```
    let valid_resource_bounds = match &tx_context.tx_info {
        TransactionInfo::Current(info) => &info.resource_bounds,
        TransactionInfo::Deprecated(_) => return FeeCheckError::,
    };
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6otjrsBxU2IEswuRiN:-O6p72i62YEh4Z_Gb4EM:b2kqn8r) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_checks.rs#L151)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I think using a `for (resource, max_amount, actual_amount) in [...] {if...} Ok(())` on the 3 cases would look better. Also easier to extend if more resources pop up later.
</blockquote></details>

@amosStarkware, do you agree with @aner-starkware?
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6ouEzz0IPRrAKuoOMo:-O6pNACF9LzZT_gNSGyk:b2ni9hp) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_checks.rs#L193)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I think you renamed the wrong method
</blockquote></details>

ops
___
*[`crates/blockifier/src/fee/fee_test.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6KdDDkARIErxn-SgU8:-O6p_2X8CMu118YtuCmU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab0f53b44069821259c50978864ee86c15e2e1f/crates/blockifier/src/fee/fee_test.rs#L3)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

in [this](https://github.com/starkware-libs/sequencer/blob/2dcefb9d12c2b87c3f797a542962de1c3698271c/crates/blockifier/src/blockifier/stateful_validator_test.rs#L31) test:
please add 3 cases (for declare, deploy_account, invoke) that test resource validations on all the resources
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 232 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6pFgAPEPloLusKEKvY:-O6p_Mj6B9DwvbHZCiYw:b6rmfsq) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_test.rs#L232)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Isn't it the same as in `BlockInfo::create_for_testing()`?
(which is called in ` BlockContext::create_for_account_testing()`)
</blockquote></details>

Yes, it's the same and unnecessary.
I saw it here 
(https://github.com/starkware-libs/sequencer/blob/7949cb154b4046babd87f2b3ebe8261c302ca609/crates/blockifier/src/fee/fee_test.rs#L150)
I'll refactor it in a different PR
___
*[`crates/blockifier/src/fee/fee_test.rs` line 257 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6opz82CQU9qxPe1evl:-O6pOvW0EY25CCYWc5aW:b-fzoglt) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_test.rs#L257)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

where does `FeeCheckError::MaxGasAmountExceeded { .. }` get its values from?
please be explicit
</blockquote></details>

It does not get values , 
assert matches checks that error is compatible with the pattern of FeeCheckError::MaxGasAmountExceededd .  


<!-- Sent from Reviewable.io -->

2024-09-15 12:25 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 8 files reviewed, 11 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6H9uT962icTIjwpK-w:-O6pbj4u4kC3b_tQFGv9:b-yufgtj) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab0f53b44069821259c50978864ee86c15e2e1f/crates/blockifier/src/fee/fee_checks.rs#L107)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@dorimedini-starkware should the above TODO be deleted?
</blockquote></details>

yes, the new post-execution check with the data gas bound completes the todo
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HHm0hBE5Fwdp54l0R:-O6pcISA9lSL3jS1pz8x:bhmc18q) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L227)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@dorimedini-starkware can you TAL at this method?
</blockquote></details>

what about it?
___
*[`crates/blockifier/src/fee/fee_test.rs` line 211 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6omuS966nG54MbJJNY:-O6pcz5-4f37QzIXgbOx:b-4zl5m2) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_test.rs#L211)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@dorimedini-starkware any more cases needed? can you also TAL and see if the values make sense?
</blockquote></details>

answered one line down
___
*[`crates/blockifier/src/fee/fee_test.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6pcv_TCeEeFxip8kDa:-O6pcv_TCeEeFxip8kDb:be6iuer) ([raw file](https://github.com/starkware-libs/sequencer/blob/7949cb154b4046babd87f2b3ebe8261c302ca609/crates/blockifier/src/fee/fee_test.rs#L209)):*
> ```XML
> #[case::no_overdraft(0, 0, 0, false)]
> fn test_post_execution_gas_overdraft_all_resource_bounds(
>     all_resource_bounds: ValidResourceBounds,
> ```

what are the values here?
need to make sure two variants are tested, and that the bounds are not zero - i.e. in the L1Gas case the L1 gas bound is positive, and in the ALL case, all three bounds are positive



_Code quote:_
```XML
all_resource_bounds: ValidResourceBounds,
```


<!-- Sent from Reviewable.io -->

2024-09-15 12:26 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 8 files reviewed, 12 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 142 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6pdRtQDzoTuZ1Fhl_2:-O6pdRtQDzoTuZ1Fhl_3:b-l1rzxh) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa2f617aca08eb7122cf9e8f2133e9a7cb595296/crates/blockifier/src/fee/fee_checks.rs#L142)):*
> ```XML
>         all_resource_bounds: &AllResourceBounds,
>         gas_vector: &GasVector,
>     ) -> Result<(), FeeCheckError> {
> ```

this type is used 3 times, please define a `FeeCheckResult<T> = Result<T, FeeCheckError>` type and use it



_Code quote:_
```XML
Result<(), FeeCheckError>
```


<!-- Sent from Reviewable.io -->

2024-09-15 13:18 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 8 files reviewed, 12 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6H9uT962icTIjwpK-w:-O6piRsCAoFBKY1_hbt7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab0f53b44069821259c50978864ee86c15e2e1f/crates/blockifier/src/fee/fee_checks.rs#L107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, the new post-execution check with the data gas bound completes the todo
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 142 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6pdRtQDzoTuZ1Fhl_2:-O6pjHIXAozgIN_H78H3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa2f617aca08eb7122cf9e8f2133e9a7cb595296/crates/blockifier/src/fee/fee_checks.rs#L142)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this type is used 3 times, please define a `FeeCheckResult<T> = Result<T, FeeCheckError>` type and use it
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6pcv_TCeEeFxip8kDa:-O6pjqJJEg_F8KtH3AmR:b-wg68tc) ([raw file](https://github.com/starkware-libs/sequencer/blob/7949cb154b4046babd87f2b3ebe8261c302ca609/crates/blockifier/src/fee/fee_test.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what are the values here?
need to make sure two variants are tested, and that the bounds are not zero - i.e. in the L1Gas case the L1 gas bound is positive, and in the ALL case, all three bounds are positive
</blockquote></details>

The case with only L1 gas tests here
https://github.com/starkware-libs/sequencer/blob/395d24633f6fd88567667c743e3bea4c2ddca5fe/crates/blockifier/src/fee/fee_test.rs#L151

I added a test for the scenario involving all resources.


<!-- Sent from Reviewable.io -->

2024-09-15 13:42 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 8 files reviewed, 11 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-15 14:41 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 5 of 8 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @AvivYossef-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 222 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6q6xvX4VfbDQ5KoW7y:-O6q6xvX4VfbDQ5KoW7z:b-pe8dwj) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa2f617aca08eb7122cf9e8f2133e9a7cb595296/crates/blockifier/src/fee/fee_test.rs#L222)):*
> ```XML
> #[case::l2_bound_overdraft_declare_deploy_account(0, 10000, 0, true, "deploy_account")]
> #[case::l1_data_bound_overdraft_declare_deploy_account(0, 0, 1000, true, "deploy_account")]
> #[case::no_overdraft_declare_deploy_account(0, 0, 0, false, "deploy_account")]
> ```

I think it is redundant to test all 3 tx types, the post-execution logic is shared between them



_Suggestion:_
```XML
#[case::l1_bound_overdraft_invoke(1000, 0, 0, true)]
#[case::l2_bound_overdraft_invoke(0, 10000, 0, true)]
#[case::l1_data_bound_overdraft_invoke(0, 0, 1000, true)]
#[case::no_overdraft_invoke(0, 0, 0, false)]
```


<!-- Sent from Reviewable.io -->

2024-09-15 14:57 UTC, amosStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 5 of 8 files reviewed, 6 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HHm0hBE5Fwdp54l0R:-O6q7LdQ2pcW6J5U0x7n:b-u88u39) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L227)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about it?
</blockquote></details>

to make sure it looks good to you (i.e., checks the bounds correctly) - I don't feel on top of this whole L2 gas business
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 279 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HFSQO5aQc9AmGpo6e:-O6q50C31BJC81BjIInd:b-d72872) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L279)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

But if I do it, I'll need to match every time to extract the resource bounds. Are you sure you prefer it rather than passing the resource bounds?
```
    let valid_resource_bounds = match &tx_context.tx_info {
        TransactionInfo::Current(info) => &info.resource_bounds,
        TransactionInfo::Deprecated(_) => return FeeCheckError::,
    };
```
</blockquote></details>

hmm ok. but passing both `tx_context` & `resource_bounds` isn't good IMO, so how about the following:
add a TODO next to `check_resources_within_bounds` to delete the tx_context parameter.
in another PR:
refactor in `to_discounted_l1_gas` to accept fee type & gas prices instead of tx context.
delete `check_resources_within_bounds` (i.e., do this match inside `check_actual_cost_within_bounds`),
and then pass fee type & gas prices to `check_l1_gas_within_bounds` (instead of the tx context).
sounds ok?
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6otjrsBxU2IEswuRiN:-O6q0iez7MxNbBWoZAn-:bh1srlc) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_checks.rs#L151)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

@amosStarkware, do you agree with @aner-starkware?
</blockquote></details>

yes, good idea. you can use `zip()`.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6KdDDkARIErxn-SgU8:-O6q9JRm3jiIoAVvLQWl:b-ut7np8) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab0f53b44069821259c50978864ee86c15e2e1f/crates/blockifier/src/fee/fee_test.rs#L3)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it
___
*[`crates/blockifier/src/fee/fee_test.rs` line 257 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6opz82CQU9qxPe1evl:-O6q8GGr7iodMrt6wl_E:b5clc22) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_test.rs#L257)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

It does not get values , 
assert matches checks that error is compatible with the pattern of FeeCheckError::MaxGasAmountExceededd .
</blockquote></details>

what about making sure the error is about the correct resource?


<!-- Sent from Reviewable.io -->

2024-09-15 14:57 UTC, amosStarkware reviewed
> Reviewed 1 of 3 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-16 10:13 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 279 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6HFSQO5aQc9AmGpo6e:-O6uFABM65BR03VZDSiX:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e1a69d15d73916141641342953593e6b720f8c0/crates/blockifier/src/fee/fee_checks.rs#L279)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

hmm ok. but passing both `tx_context` & `resource_bounds` isn't good IMO, so how about the following:
add a TODO next to `check_resources_within_bounds` to delete the tx_context parameter.
in another PR:
refactor in `to_discounted_l1_gas` to accept fee type & gas prices instead of tx context.
delete `check_resources_within_bounds` (i.e., do this match inside `check_actual_cost_within_bounds`),
and then pass fee type & gas prices to `check_l1_gas_within_bounds` (instead of the tx context).
sounds ok?
</blockquote></details>

Yes
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6otjrsBxU2IEswuRiN:-O6uDzzc4SXpOAuV1BYH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_checks.rs#L151)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

yes, good idea. you can use `zip()`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 257 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6opz82CQU9qxPe1evl:-O6uJ9eH5MYirNb97FmD:bb6tyiv) ([raw file](https://github.com/starkware-libs/sequencer/blob/56675c5baecf399619efe6a0f894f9430ac050f4/crates/blockifier/src/fee/fee_test.rs#L257)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

what about making sure the error is about the correct resource?
</blockquote></details>

DONE
___
*[`crates/blockifier/src/fee/fee_test.rs` line 222 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6q6xvX4VfbDQ5KoW7y:-O6uFSHP0cm_Th5IZqOG:bh6gsho) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa2f617aca08eb7122cf9e8f2133e9a7cb595296/crates/blockifier/src/fee/fee_test.rs#L222)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it is redundant to test all 3 tx types, the post-execution logic is shared between them
</blockquote></details>

@amosStarkware, do you agree?
( you previously asked to add these cases)


<!-- Sent from Reviewable.io -->

2024-09-16 12:50 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 9 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @dorimedini-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 50 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6uqjPk1F_XXIL4JYjc:-O6uqjPk1F_XXIL4JYjd:b-52n3wi) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7d4f33e98bd53be1104b7f9cb09ea6185c79e02/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L50)):*
> ```XML
> pub const VALID_L1_GAS_MAX_AMOUNT: u64 = 203484;
> pub const VALID_L1_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
> pub const VALID_L2_GAS_MAX_AMOUNT: u64 = 500000;
> ```

It is needed because the TX in the tets
[VALID\_L2\_GAS\_MAX\_AMOUNT](https://github.com/starkware-libs/sequencer/blob/3f941d675ee2123b212db466147b53f365523ab1/crates/gateway/src/gateway_test.rs#L61)
consume more l2 gas than   203484


<!-- Sent from Reviewable.io -->

2024-09-16 15:16 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 11 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 142 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6uz0_3DsKPA0q_ZsZL:-O6uz0_3DsKPA0q_ZsZM:biy807b) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7d4f33e98bd53be1104b7f9cb09ea6185c79e02/crates/blockifier/src/fee/fee_checks.rs#L142)):*
> ```XML
> 
>     /// Iterate over resources and check actual_amount <= max_amount.
>     fn check_all_resources_within_bounds(
> ```

Move `check_resources_within_bounds` above this function, and document it (no need to document the inner two)



_Code quote:_
```XML
    /// Iterate over resources and check actual_amount <= max_amount.
    fn check_all_resources_within_bounds(
```


<!-- Sent from Reviewable.io -->

2024-09-17 06:28 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 11 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @dorimedini-starkware, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 142 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6uz0_3DsKPA0q_ZsZL:-O6yd5tSAnf-udxCumr-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7d4f33e98bd53be1104b7f9cb09ea6185c79e02/crates/blockifier/src/fee/fee_checks.rs#L142)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Move `check_resources_within_bounds` above this function, and document it (no need to document the inner two)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-17 07:20 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 11 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, @dorimedini-starkware, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-09-17 07:35 UTC, aner-starkware commented
*[`crates/blockifier/src/fee/fee_checks.rs` line 172 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6yszAN8wfv2hpQxg8b:-O6yszAN8wfv2hpQxg8c:bl3jfax) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/blockifier/src/fee/fee_checks.rs#L172)):*
> ```XML
>             ],
>             [gas_vector.l1_gas, gas_vector.l2_gas, gas_vector.l1_data_gas]
>         ) {
> ```

@amosStarkware , why use `zip`? Isn't it easier to understand without it?
Also, it's possible to make it one line for each case if using without the `Resource::`



_Suggestion:_
```XML
        for (resource, max_amount, actual_amount) in [
            (L1Gas, all_resource_bounds.l1_gas.max_amount.into(), gas_vector.l1_gas),
            (L2Gas, all_resource_bounds.l2_gas.max_amount.into(), gas_vector.l2_gas),
            (L1DataGas, all_resource_bounds.l1_data_gas.max_amount.into(), gas_vector.l1_data_gas),
        ] {
```


<!-- Sent from Reviewable.io -->

2024-09-17 07:39 UTC, MohammadNassar1 reviewed
> Reviewed 1 of 2 files at r11, 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 6 of 11 files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @dorimedini-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 129 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6yuepzDx6C9m9CSbEi:-O6yuepzDx6C9m9CSbEj:bucrfr7) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L129)):*
> ```XML
>         },
>         ResourceBounds {
>             max_amount: VALID_L1_DATA_GAS_MAX_AMOUNT * 10,
> ```

Why are you multiplying by 10?



_Code quote:_
```XML
VALID_L1_DATA_GAS_MAX_AMOUNT * 10
```


<!-- Sent from Reviewable.io -->

2024-09-17 09:21 UTC, amosStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 6 of 11 files reviewed, 10 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 147 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6z9wBg7MnlitGYZCcg:-O6z9wBhBCZ-aVgesyWn:b-ckc0v6) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/blockifier/src/fee/fee_checks.rs#L147)):*
> ```XML
>         tx_context: &TransactionContext,
>     ) -> FeeCheckResult<()> {
>         // TODO(Aviv): delete the tx_context parameter.
> ```

please move to the top of the function / next to the `tx_context` parameter



_Code quote:_
```XML
// TODO(Aviv): delete the tx_context parameter.
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 172 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6yszAN8wfv2hpQxg8b:-O6zAsQqAlWFtqJA1o26:b6kygoc) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/blockifier/src/fee/fee_checks.rs#L172)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

@amosStarkware , why use `zip`? Isn't it easier to understand without it?
Also, it's possible to make it one line for each case if using without the `Resource::`
</blockquote></details>

the current way is fine,
but I guess your suggestion is even nicer. @AvivYossef-starkware can decide if he want to take it
___
*[`crates/blockifier/src/fee/fee_test.rs` line 222 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6q6xvX4VfbDQ5KoW7y:-O6zByaz5-AqikuIFrYC:b-i9ek3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa2f617aca08eb7122cf9e8f2133e9a7cb595296/crates/blockifier/src/fee/fee_test.rs#L222)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

@amosStarkware, do you agree?
( you previously asked to add these cases)
</blockquote></details>

I asked to add them in in [this](https://github.com/starkware-libs/sequencer/blob/2dcefb9d12c2b87c3f797a542962de1c3698271c/crates/blockifier/src/blockifier/stateful_validator_test.rs#L31) test - because resource overdraft is also checked by [perform_validations](https://github.com/starkware-libs/sequencer/blob/9745223e7d07778b67771ab5af925087653dd4e5/crates/blockifier/src/blockifier/stateful_validator.rs#L55).
@dorimedini-starkware do you think that's redundant?
___
*[`crates/blockifier/src/fee/fee_test.rs` line 215 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6zFAUf01B77RJj0a9L:-O6zFAUf01B77RJj0a9M:bag6lba) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/blockifier/src/fee/fee_test.rs#L215)):*
> ```XML
>     #[case] l1_data_gas_used: u128,
>     #[case] expect_failure: bool,
>     #[case] resource_overdraft: Option<Resource>,
> ```

please rename to `resource_out_of_bounds`,
and please delete `expect_failure` - you expect a failure when `resource_out_of_bounds` isn't `None`, right?



_Code quote:_
```XML
    #[case] expect_failure: bool,
    #[case] resource_overdraft: Option<Resource>,
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 72 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6zFXER7HMo-yEImx9F:-O6zFXER7HMo-yEImx9G:b-7a29v9) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/gateway/src/stateful_transaction_validator_test.rs#L72)):*
> ```XML
>     Ok(ValidateInfo{
>         tx_hash: TransactionHash(felt!(
>         "0x3c6546364f70395ad7c8d1ce64b990b698be21e786bee2efff57a694f37648e"
> ```

this is because of the bounds you changed in `starknet_api_test_utils`?



_Code quote:_
```XML
"0x3c6546364f70395ad7c8d1ce64b990b698be21e786bee2efff57a694f37648e"
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 50 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6uqjPk1F_XXIL4JYjc:-O6zGHvI2MpjkRCLFYcS:b-q0mf6z) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7d4f33e98bd53be1104b7f9cb09ea6185c79e02/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L50)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

It is needed because the TX in the tets
[VALID\_L2\_GAS\_MAX\_AMOUNT](https://github.com/starkware-libs/sequencer/blob/3f941d675ee2123b212db466147b53f365523ab1/crates/gateway/src/gateway_test.rs#L61)
consume more l2 gas than   203484
</blockquote></details>

@dorimedini-starkware looks ok?
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 129 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6yuepzDx6C9m9CSbEi:-O6zGmV41oJ9MT0wMjLC:b-3g44eu) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L129)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why are you multiplying by 10?
</blockquote></details>

@dorimedini-starkware looks ok?
if it is - please change the constant's value directly
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 40 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6zG_az0smXVHrMMioR:-O6zG_az0smXVHrMMioS:b-1oagcz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/tests-integration/tests/end_to_end_test.rs#L40)):*
> ```XML
>     // because we haven't merged queue-replenishment yet.
>     let expected_tx_hashes_from_get_txs =
>         [account0_deploy_nonce0_tx_hash, account1_invoke_nonce0_tx_hash];
> ```

what's this for?


<!-- Sent from Reviewable.io -->

2024-09-17 10:41 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 6 of 11 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 147 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6z9wBg7MnlitGYZCcg:-O6zU57z317DAbVFF4CU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/blockifier/src/fee/fee_checks.rs#L147)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please move to the top of the function / next to the `tx_context` parameter
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 172 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6yszAN8wfv2hpQxg8b:-O6zUA6GEsPBfTpyHdtJ:bldmb0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/blockifier/src/fee/fee_checks.rs#L172)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

the current way is fine,
but I guess your suggestion is even nicer. @AvivYossef-starkware can decide if he want to take it
</blockquote></details>

Anner suggestion is nicer :)
___
*[`crates/blockifier/src/fee/fee_test.rs` line 215 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6zFAUf01B77RJj0a9L:-O6zT8-4ES7kgvrSshtq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/blockifier/src/fee/fee_test.rs#L215)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please rename to `resource_out_of_bounds`,
and please delete `expect_failure` - you expect a failure when `resource_out_of_bounds` isn't `None`, right?
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 72 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6zFXER7HMo-yEImx9F:-O6zTAHz5G9NfA3BNjym:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/gateway/src/stateful_transaction_validator_test.rs#L72)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

this is because of the bounds you changed in `starknet_api_test_utils`?
</blockquote></details>

Yes
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 129 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6yuepzDx6C9m9CSbEi:-O6zTVxu5o5GelGDtdlX:b-s9yssc) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L129)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@dorimedini-starkware looks ok?
if it is - please change the constant's value directly
</blockquote></details>

Its a mistake, I did it before changing directly the constant
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 40 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6zG_az0smXVHrMMioR:-O6zTE_v86wtVgfb3CUy:bfe1vtv) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/tests-integration/tests/end_to_end_test.rs#L40)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

what's this for?
</blockquote></details>

The list was sorted according to the hash values. The hash values changed...


<!-- Sent from Reviewable.io -->

2024-09-17 13:08 UTC, amosStarkware reviewed
> Reviewed 1 of 3 files at r5, 1 of 3 files at r8, 1 of 1 files at r10, 1 of 2 files at r11, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-17 15:01 UTC, amosStarkware requested changes
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 222 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6q6xvX4VfbDQ5KoW7y:-O7-TEsMDb1UyeeELd7n:b-om0s8w) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa2f617aca08eb7122cf9e8f2133e9a7cb595296/crates/blockifier/src/fee/fee_test.rs#L222)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the test you linked is pre-validation, no?
we are in post-execution context here
</blockquote></details>

it tests [perform_validations](https://github.com/starkware-libs/sequencer/blob/9745223e7d07778b67771ab5af925087653dd4e5/crates/blockifier/src/blockifier/stateful_validator.rs#L55), and that function calls `PostValidationReport::verify()`, which calls `FeeCheckReport::check_actual_cost_within_bounds`. so I thought it's relevant


<!-- Sent from Reviewable.io -->

2024-09-17 15:04 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, and @dorimedini-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 40 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6zG_az0smXVHrMMioR:-O7-VdlG3Bec9PKsQkTo:bnms64d) ([raw file](https://github.com/starkware-libs/sequencer/blob/e60953654ea2b71ef4236ae1960354b0b17c5021/crates/tests-integration/tests/end_to_end_test.rs#L40)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

The list was sorted according to the hash values. The hash values changed...
</blockquote></details>

You can revert this change, @giladchase has removed this test from the ci.
You may need to rebase.


<!-- Sent from Reviewable.io -->

2024-09-18 07:09 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @dorimedini-starkware, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 144 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O7-OcfB054l9WPiJl-6:-O72h3ix19_E_3jj4hUG:b49ihwh) ([raw file](https://github.com/starkware-libs/sequencer/blob/ffdc346bc9c30bad703ccd3cc1db471a6da7abd8/crates/blockifier/src/fee/fee_checks.rs#L144)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should be moved to be the docstring of the `check_all_resources_within_bounds` function, no need to add more commenting here
</blockquote></details>

@Yoni-Starkware asked me to move it from the docstring of the
```check_all_resources_within_bounds``` function.
https://github.com/starkware-libs/sequencer/pull/712#pullrequestreview-2306978604 
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 148 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O7-OlZ81NQt7-NTbVpF:-O72x2Am-mJgxQHJlld8:b-34vmyd) ([raw file](https://github.com/starkware-libs/sequencer/blob/ffdc346bc9c30bad703ccd3cc1db471a6da7abd8/crates/blockifier/src/fee/fee_checks.rs#L148)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

See above


<!-- Sent from Reviewable.io -->

2024-09-18 08:07 UTC, dorimedini-starkware requested changes
> Reviewed 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @AvivYossef-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 144 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O7-OcfB054l9WPiJl-6:-O739xyy9r-HCFu_vBz5:b-7tegs0) ([raw file](https://github.com/starkware-libs/sequencer/blob/ffdc346bc9c30bad703ccd3cc1db471a6da7abd8/crates/blockifier/src/fee/fee_checks.rs#L144)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware asked me to move it from the docstring of the
```check_all_resources_within_bounds``` function.
https://github.com/starkware-libs/sequencer/pull/712#pullrequestreview-2306978604
</blockquote></details>

ah ok
___
*[`crates/blockifier/src/fee/fee_test.rs` line 222 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O6q6xvX4VfbDQ5KoW7y:-O739L0Z5DPF0w4WeYpV:b-xse059) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa2f617aca08eb7122cf9e8f2133e9a7cb595296/crates/blockifier/src/fee/fee_test.rs#L222)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

it tests [perform_validations](https://github.com/starkware-libs/sequencer/blob/9745223e7d07778b67771ab5af925087653dd4e5/crates/blockifier/src/blockifier/stateful_validator.rs#L55), and that function calls `PostValidationReport::verify()`, which calls `FeeCheckReport::check_actual_cost_within_bounds`. so I thought it's relevant
</blockquote></details>

I consider this test as a unit test for `check_actual_cost_within_bounds`; so IMO we don't need to test this from multiple directions.
(We still need to brainstorm different flow test scenarios we may want, for extra coverage, but that's out of scope.)
can you think of an edge case we are overlooking in this unit test context?
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 306 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O738xXW6tSr_wS1FSC5:-O738xXW6tSr_wS1FSC6:bs9as0x) ([raw file](https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/blockifier/src/transaction/test_utils.rs#L306)):*
> ```XML
> 
> #[fixture]
> pub fn all_resource_bounds(
> ```

where is this fixture used?



_Code quote:_
```XML
all_resource_bounds
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 312 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O738SNV-TL0X3neweZM:-O738SNV-TL0X3neweZN:b63x991) ([raw file](https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/blockifier/src/transaction/test_utils.rs#L312)):*
> ```XML
>     #[default(100)] l2_max_price: u128,
>     #[default(20)] l1_data_max_amount: u64,
>     #[default(100)] l1_data_max_price: u128,
> ```

do we have default gas prices defined as constants somewhere?
it may be wise to use them as the default values for the prices here...
also, the default amounts should probably also be at least correlated to defaults we have in other places.
20 gas units sounds too low for most things; in the mempool, the "default L2 gas amount" is around 500000, IIRC.
Only data gas amount can be this low.



_Code quote:_
```XML
    #[default(20)] l1_max_amount: u64,
    #[default(100)] l1_max_price: u128,
    #[default(20)] l2_max_amount: u64,
    #[default(100)] l2_max_price: u128,
    #[default(20)] l1_data_max_amount: u64,
    #[default(100)] l1_data_max_price: u128,
```


<!-- Sent from Reviewable.io -->

2024-09-18 08:42 UTC, amosStarkware approved these changes
> Reviewed 6 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2024-09-18 09:05 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 306 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O738xXW6tSr_wS1FSC5:-O73M1VJ88WqEemuy_yF:b-83isud) ([raw file](https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/blockifier/src/transaction/test_utils.rs#L306)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is this fixture used?
</blockquote></details>

In the test
https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/blockifier/src/fee/fee_test.rs#L210
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 312 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O738SNV-TL0X3neweZM:-O73MR9t6LUuTXtnBh1E:brgk0ct) ([raw file](https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/blockifier/src/transaction/test_utils.rs#L312)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do we have default gas prices defined as constants somewhere?
it may be wise to use them as the default values for the prices here...
also, the default amounts should probably also be at least correlated to defaults we have in other places.
20 gas units sounds too low for most things; in the mempool, the "default L2 gas amount" is around 500000, IIRC.
Only data gas amount can be this low.
</blockquote></details>

I think that only in Mempool. 
https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L49
I might add TODO for it?


<!-- Sent from Reviewable.io -->

2024-09-18 09:15 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 208 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O73PDZG1728sjNTIxki:-O73PDZG1728sjNTIxkj:b-i73zyh) ([raw file](https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/blockifier/src/fee/fee_test.rs#L208)):*
> ```XML
> #[case::l2_bound_overdraft(19, 21, 19, Some(Resource::L2Gas))]
> #[case::l1_data_bound_overdraft(5, 7, 1000, Some(Resource::L1DataGas))]
> #[case::no_overdraft(18, 18, 18, None)]
> ```

the numbers here depend on the values in `all_resource_bounds`.
If the values in the fixture are changed, this test can break.
1. use named values (global constants) in the fixture
2. use the same values to determine how to get an overdraft / avoid an overdraft



_Code quote:_
```XML
#[case::l1_bound_overdraft(21, 19, 19, Some(Resource::L1Gas))]
#[case::l2_bound_overdraft(19, 21, 19, Some(Resource::L2Gas))]
#[case::l1_data_bound_overdraft(5, 7, 1000, Some(Resource::L1DataGas))]
#[case::no_overdraft(18, 18, 18, None)]
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 312 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O738SNV-TL0X3neweZM:-O73OrtI5TMvuG_xgzDd:b-3xbgzc) ([raw file](https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/blockifier/src/transaction/test_utils.rs#L312)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I think that only in Mempool. 
https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L49
I might add TODO for it?
</blockquote></details>

how about [these](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/src/test_utils.rs#L90-L104)?
feel free to add constants here for L2 gas


<!-- Sent from Reviewable.io -->

2024-09-18 10:17 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 208 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O73PDZG1728sjNTIxki:-O73cffaBkq67Camyoyq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/blockifier/src/fee/fee_test.rs#L208)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the numbers here depend on the values in `all_resource_bounds`.
If the values in the fixture are changed, this test can break.
1. use named values (global constants) in the fixture
2. use the same values to determine how to get an overdraft / avoid an overdraft
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 312 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O738SNV-TL0X3neweZM:-O73chJQ9OfvOAxyRDIl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/90c117ce495eb6f8d67656d7e1dd21f01175e819/crates/blockifier/src/transaction/test_utils.rs#L312)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how about [these](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/src/test_utils.rs#L90-L104)?
feel free to add constants here for L2 gas
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-18 10:20 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 103 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O73cpt9BaulQncPc81R:-O73cpt9BaulQncPc81S:bnwi30n) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0e9e77cf98ffc102c48ac4aa4207b4223cca7ac/crates/blockifier/src/test_utils.rs#L103)):*
> ```XML
> pub const DEFAULT_ETH_L1_GAS_PRICE: u128 = 100 * u128::pow(10, 9); // Given in units of Wei.
> pub const DEFAULT_STRK_L1_GAS_PRICE: u128 = 100 * u128::pow(10, 9); // Given in units of STRK.
> pub const DEFAULT_L1_GAS_MAX_AMOUNT: u64 = 203484;
> ```

why not use `MAX_L1_GAS_AMOUNT` as defined above?



_Code quote:_
```XML
DEFAULT_L1_GAS_MAX_AMOUNT
```
___
*[`crates/blockifier/src/test_utils.rs` line 106 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O73d-q3E6cAnF5XK0q8:-O73d-q3E6cAnF5XK0q9:bkfhsnl) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0e9e77cf98ffc102c48ac4aa4207b4223cca7ac/crates/blockifier/src/test_utils.rs#L106)):*
> ```XML
> pub const DEFAULT_ETH_L1_DATA_GAS_PRICE: u128 = u128::pow(10, 6); // Given in units of Wei.
> pub const DEFAULT_STRK_L1_DATA_GAS_PRICE: u128 = u128::pow(10, 9); // Given in units of STRK.
> pub const DEFAULT_L1_DATA_GAS_MAX_AMOUNT: u64 = 203484;
> ```

why this number? I would just go with 500000, or `u128::pow(10, 6)`



_Code quote:_
```XML
DEFAULT_L1_DATA_GAS_MAX_AMOUNT: u64 = 203484
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 318 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/712#-O73dLkM-sTStm6zry2v:-O73dLkM-sTStm6zry2w:b-hs8d8w) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0e9e77cf98ffc102c48ac4aa4207b4223cca7ac/crates/blockifier/src/transaction/test_utils.rs#L318)):*
> ```XML
>     #[default(DEFAULT_ETH_L2_GAS_PRICE)] l2_max_price: u128,
>     #[default(DEFAULT_L1_DATA_GAS_MAX_AMOUNT)] l1_data_max_amount: u64,
>     #[default(DEFAULT_ETH_L1_DATA_GAS_PRICE)] l1_data_max_price: u128,
> ```

V3 transactions (with resource bounds) pay in `STRK`, not `ETH`.
please use `DEFAULT_STRK_...` prices, not `ETH` prices.



_Code quote:_
```XML
    #[default(DEFAULT_L1_GAS_MAX_AMOUNT)] l1_max_amount: u64,
    #[default(DEFAULT_ETH_L1_GAS_PRICE)] l1_max_price: u128,
    #[default(DEFAULT_L2_GAS_MAX_AMOUNT)] l2_max_amount: u64,
    #[default(DEFAULT_ETH_L2_GAS_PRICE)] l2_max_price: u128,
    #[default(DEFAULT_L1_DATA_GAS_MAX_AMOUNT)] l1_data_max_amount: u64,
    #[default(DEFAULT_ETH_L1_DATA_GAS_PRICE)] l1_data_max_price: u128,
```


<!-- Sent from Reviewable.io -->

2024-09-18 11:21 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712#-:-O73rSCgCZGq7iLEAN7Y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-09-18 11:51 UTC, aner-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-18 11:58 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/712)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2024-09-18 11:58 UTC, merged