feat: adding block_builder object
starkware-libs/sequencer pull request #745
Opened 2024-09-09 08:17 UTC by Yael-Starkware

2024-09-15 11:31 UTC, yair-starkware requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O6pRscx5g1KwrdlOqRn:-O6pRscy0_XYR7dAyDNh:b-gw8td0) (no related file):*
You need to run the `dump_config` executable

___
___
*[`crates/batcher/src/block_builder.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O6pP6Rz5GILnMtafnmy:-O6pP6Rz5GILnMtafnmz:bk5r517) ([raw file](https://github.com/starkware-libs/sequencer/blob/b14ad5eb08c90fcfed2d273b13f819dc32a579d9/crates/batcher/src/block_builder.rs#L31)):*
> ```XML
> pub struct ExecutionConfig {
>     pub chain_info: ChainInfo,
>     pub versioned_constants: VersionedConstants,
> ```

Get versioned constants by calling `get_latest` or `get` instead of from the config



_Code quote:_
```XML
pub versioned_constants: VersionedConstants,
```
___
*[`crates/batcher/src/block_builder.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O6pRXngA-W8XLz7TbuH:-O6pRXngA-W8XLz7TbuI:b-enqi3l) ([raw file](https://github.com/starkware-libs/sequencer/blob/b14ad5eb08c90fcfed2d273b13f819dc32a579d9/crates/batcher/src/block_builder.rs#L85)):*
> ```XML
> }
> 
> pub fn get_gas_prices() -> GasPrices {
> ```

I don't think it needs to be public



_Code quote:_
```XML
pub
```


<!-- Sent from Reviewable.io -->

2024-09-15 12:09 UTC, yair-starkware commented
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You need to run the `dump_config` executable
</blockquote></details>

nvm it's still not part of the config




<!-- Sent from Reviewable.io -->

2024-09-18 10:54 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O6pP6Rz5GILnMtafnmy:-O73lDagA1tHwr-jQSvy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b14ad5eb08c90fcfed2d273b13f819dc32a579d9/crates/batcher/src/block_builder.rs#L31)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Get versioned constants by calling `get_latest` or `get` instead of from the config
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O6pRXngA-W8XLz7TbuH:-O73lCkC8tCspiTvZIeE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b14ad5eb08c90fcfed2d273b13f819dc32a579d9/crates/batcher/src/block_builder.rs#L85)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't think it needs to be public
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-19 08:05 UTC, dafnamatsry requested changes
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78ETUrDDQ4GQ0pjC41:-O78ETUrDDQ4GQ0pjC42:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L16)):*
> ```XML
> 
> pub struct BlockBuilder<S: StateReader> {
>     pub executor: TransactionExecutor<S>,
> ```





_Suggestion:_
```XML
executor
```
___
*[`crates/batcher/src/block_builder.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78F9yc6tV6_oaH7XcH:-O78F9yc6tV6_oaH7XcI:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L35)):*
> ```XML
>     pub sequencer_address: ContractAddress,
>     pub use_kzg_da: bool,
>     pub version_constants_overrides: VersionedConstantsOverrides,
> ```





_Suggestion:_
```XML
versioned_constants_overrides
```
___
*[`crates/batcher/src/block_builder.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78IXbCCWE4-rG44Qio:-O78IXbCCWE4-rG44Qip:b-6kt31h) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L38)):*
> ```XML
> }
> 
> impl<S: StateReader> BlockBuilder<S> {
> ```

Please sync with @yair-starkware .
He added a trait of the BlockBuilder and BlockBuilderFactory ([In this PR](https://reviewable.io/reviews/starkware-libs/sequencer/541#-)) that defines the API.

2 things to note:
* We need to use the factory pattern to be able to easily test the proposal manager.
* We use channels in order to add txs to the block.
___
*[`crates/batcher/src/block_builder.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78EqmpCsTwDs-_d0Wf:-O78EqmpCsTwDs-_d0Wg:be77mgf) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L42)):*
> ```XML
>         next_block_number: BlockNumber,
>         state_reader: S,
>         retrospective_block_hash: Option<BlockNumberHashPair>,
> ```

Be consistent with the name in the Batcher.



_Code quote:_
```XML
retrospective_block_hash:
```
___
*[`crates/batcher/src/block_builder.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78GX1S6zYr_XorCXQY:-O78GX1S6zYr_XorCXQZ:b3a3ffl) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L66)):*
> ```XML
>         let mut state = CachedState::new(state_reader);
> 
>         pre_process_block(&mut state, retrospective_block_hash, next_block_number)?;
> ```

Does this write to the state? I don't think it should be in the ctor.


<!-- Sent from Reviewable.io -->

2024-09-19 08:06 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: 4 of 6 files reviewed, 8 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78JGfM9jrp2qUgBDQB:-O78GMRZ6wc11fcqO77f:b-oawxev) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L39)):*
> ```XML
> 
> impl<S: StateReader> BlockBuilder<S> {
>     pub fn new(
> ```

Please accept the `TransactionExecutor` as an argument of the ctor.


<!-- Sent from Reviewable.io -->

2024-09-22 12:13 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: 4 of 6 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78ETUrDDQ4GQ0pjC41:-O7OZfqC-KagO-5fGvEZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L16)):*
> ```XML
> 
> pub struct BlockBuilder<S: StateReader> {
>     pub executor: TransactionExecutor<S>,
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78F9yc6tV6_oaH7XcH:-O7OZk-f9GXXNJEo-7Lg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L35)):*
> ```XML
>     pub sequencer_address: ContractAddress,
>     pub use_kzg_da: bool,
>     pub version_constants_overrides: VersionedConstantsOverrides,
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78IXbCCWE4-rG44Qio:-O7OIrnV-w5TCT_GoxuY:b-nvpwb0) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L38)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please sync with @yair-starkware .
He added a trait of the BlockBuilder and BlockBuilderFactory ([In this PR](https://reviewable.io/reviews/starkware-libs/sequencer/541#-)) that defines the API.

2 things to note:
* We need to use the factory pattern to be able to easily test the proposal manager.
* We use channels in order to add txs to the block.
</blockquote></details>

I am consistent with the trait, but this is only the ctor, not the trait implementation yet.
The next PR will implement the trait as Yair defined it.
deleting the "add_txs_and_stream" old API from here.
___
*[`crates/batcher/src/block_builder.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78JGfM9jrp2qUgBDQB:-O7ORFQM1oEXHNyxis3L:b-rt1s0j) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L39)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please accept the `TransactionExecutor` as an argument of the ctor.
</blockquote></details>

ok, I assume you suggest this in order to make it easier to inject a mock executed for testing and I agree, 
This means the block context, state and execute are built outside the ctor, I will keep this logic in an external function.
Done.
___
*[`crates/batcher/src/block_builder.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78EqmpCsTwDs-_d0Wf:-O7OZs8Q9rFGJp1Qkio8:b-s8u6zm) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L42)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Be consistent with the name in the Batcher.
</blockquote></details>

I like this name better because it keeps the block number general in case that someday this won't be 10 blocks ago but some other x blocks ago.
also the type is Hash and BlockNumber pair so the number 10 already appears in the data.
___
*[`crates/batcher/src/block_builder.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78GX1S6zYr_XorCXQY:-O7OVyXA0V3EJ7RLCPjr:btcydy0) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L66)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Does this write to the state? I don't think it should be in the ctor.
</blockquote></details>

Yes this function writes to the state directly. I think it makes sense to do it here since it writes to the state directly and does not use the transaction_executor abstraction. (just because that was the intention of the design by the blockifier).
Otherwise, maybe we need to add a function to the transaction_executor that wraps this call. wdty?


<!-- Sent from Reviewable.io -->

2024-09-24 08:00 UTC, dafnamatsry requested changes
> Reviewed 2 of 5 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78EqmpCsTwDs-_d0Wf:-O7XxNDS9mfLbjJ6SfaO:btecydl) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L42)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I like this name better because it keeps the block number general in case that someday this won't be 10 blocks ago but some other x blocks ago.
also the type is Hash and BlockNumber pair so the number 10 already appears in the data.
</blockquote></details>

I agree the other name is not the best, just want to make sure we use the same name across the batcher (Yair already pushed code with a different name).
We can either make the change here or there, not critical to me.
___
*[`crates/batcher/src/block_builder.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78GX1S6zYr_XorCXQY:-O7Y0E6Q3YMKdJ_MAF8l:b-khyxkv) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L66)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Yes this function writes to the state directly. I think it makes sense to do it here since it writes to the state directly and does not use the transaction_executor abstraction. (just because that was the intention of the design by the blockifier).
Otherwise, maybe we need to add a function to the transaction_executor that wraps this call. wdty?
</blockquote></details>

I agree it should be in the block_builder, I just don't like that it is implicit (the constructor or this functions are not expected to write anything to the state).
I would put it maybe at the beginning of`build_block`.
___
*[`crates/batcher/src/block_builder.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7Y-VX_5R8jcx9oM2gp:-O7Y-VX_5R8jcx9oM2gq:bx8sswt) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/block_builder.rs#L44)):*
> ```XML
>     }
> 
>     pub fn create_transaction_executor(
> ```

Who will calling this function?
I think it would make more sense to put it in the block builder factory. 
___
*[`crates/batcher/src/proposals_manager.rs` line 81 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7Y1Uew326VKq8Yiab0:-O7Y1Uew326VKq8Yiab1:b-z9l13m) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/proposals_manager.rs#L81)):*
> ```XML
> pub(crate) struct ProposalsManager {
>     config: ProposalsManagerConfig,
>     execution_config: ExecutionConfig,
> ```

I think this can also be in the `BlockBuilderFactory` (anything that is about the execution).



_Code quote:_
```XML
execution_config: ExecutionConfig,
```


<!-- Sent from Reviewable.io -->

2024-09-24 11:43 UTC, yair-starkware reviewed
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7Yl89M7Y8NoHI1TuPK:-O7Yl89M7Y8NoHI1TuPL:b-ks9ih4) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/block_builder.rs#L31)):*
> ```XML
> 
> pub struct ExecutionConfig {
>     pub chain_info: ChainInfo,
> ```

Note that you will need to add this to the config pointers like I do in https://github.com/starkware-libs/sequencer/pull/982



_Code quote:_
```XML
pub chain_info: ChainInfo,
```


<!-- Sent from Reviewable.io -->

2024-09-29 12:34 UTC, yair-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78JGfM9jrp2qUgBDQB:-O7iZCd_2wUo31OMkuLc:bmbp7fi) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L39)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

ok, I assume you suggest this in order to make it easier to inject a mock executed for testing and I agree, 
This means the block context, state and execute are built outside the ctor, I will keep this logic in an external function.
Done.
</blockquote></details>

Why do we need the constructor? And why does it return a result?
___
*[`crates/batcher/src/block_builder.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7iY0Lr0RNFCSruooCl:-O7iY0Lr0RNFCSruooCm:b-194ax2) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/block_builder.rs#L30)):*
> ```XML
> pub type BlockBuilderResult<T> = Result<T, BlockBuilderError>;
> 
> pub struct ExecutionConfig {
> ```

Add derives, impl `SerializeConfig`
___
*[`crates/batcher/src/proposals_manager.rs` line 81 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7Y1Uew326VKq8Yiab0:-O7iX31L55rUA-r0SRbw:b4i8h2d) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/proposals_manager.rs#L81)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think this can also be in the `BlockBuilderFactory` (anything that is about the execution).
</blockquote></details>

We need to talk about the batcher configuration.
I think all the configs should be nested under a single BatcherConfig struct.
The fact that we use mocks for testing shouldn't make the creation of the batcher more complex from the user's POV.


<!-- Sent from Reviewable.io -->

2024-10-01 11:30 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78JGfM9jrp2qUgBDQB:-O86iWBlCiQJdacLVPg2:bbtrx8k) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L39)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need the constructor? And why does it return a result?
</blockquote></details>

deleted, done.
___
*[`crates/batcher/src/block_builder.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78EqmpCsTwDs-_d0Wf:-O7cLNT6BqLfi7vwmqpN:bkx31vs) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L42)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I agree the other name is not the best, just want to make sure we use the same name across the batcher (Yair already pushed code with a different name).
We can either make the change here or there, not critical to me.
</blockquote></details>

Done.  changed it in batcher_types
___
*[`crates/batcher/src/block_builder.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78GX1S6zYr_XorCXQY:-O7cMEDR7QEK6uvXR1Ky:bub8j7h) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L66)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I agree it should be in the block_builder, I just don't like that it is implicit (the constructor or this functions are not expected to write anything to the state).
I would put it maybe at the beginning of`build_block`.
</blockquote></details>

Yoni move it into pre_process_and_create to make it a shared code.
___
*[`crates/batcher/src/block_builder.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7iY0Lr0RNFCSruooCl:-O86iY_cCs6XnWwc5Sew:bthpm39) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/block_builder.rs#L30)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add derives, impl `SerializeConfig`
</blockquote></details>

will add this struct to the config in a separate commit
___
*[`crates/batcher/src/block_builder.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7Yl89M7Y8NoHI1TuPK:-O7cLeC1DBqa1Ggntp9U:b1wia2b) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/block_builder.rs#L31)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Note that you will need to add this to the config pointers like I do in https://github.com/starkware-libs/sequencer/pull/982
</blockquote></details>

Thanks  added a TODO
___
*[`crates/batcher/src/block_builder.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7Y-VX_5R8jcx9oM2gp:-O7cLUh0C_vUWR_0oNxc:bdl6iiz) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/block_builder.rs#L44)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Who will calling this function?
I think it would make more sense to put it in the block builder factory.
</blockquote></details>

done. 
also moved the factory definition into the block_builder file.
___
*[`crates/batcher/src/proposals_manager.rs` line 81 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7Y1Uew326VKq8Yiab0:-O7cjOE730ioMdllAwCj:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/proposals_manager.rs#L81)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We need to talk about the batcher configuration.
I think all the configs should be nested under a single BatcherConfig struct.
The fact that we use mocks for testing shouldn't make the creation of the batcher more complex from the user's POV.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-10-01 11:34 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 81 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7Y1Uew326VKq8Yiab0:-O86r00N0OhLWI9Gb9aL:bklg91v) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/proposals_manager.rs#L81)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done.
</blockquote></details>

and sure lets talk.


<!-- Sent from Reviewable.io -->

2024-10-06 09:02 UTC, yair-starkware approved these changes
> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/batcher/src/block_builder.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7Y-VX_5R8jcx9oM2gp:-O8VznM8-oDxFVic5h0w:b5tz6cz) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/block_builder.rs#L44)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done. 
also moved the factory definition into the block_builder file.
</blockquote></details>

I don't think we need this function.
For the real flow it will be part of the `create_block_builder` and for mocking the block builder we don't need to create a transaction executor.


<!-- Sent from Reviewable.io -->

2024-10-06 09:04 UTC, dafnamatsry requested changes
> Reviewed 12 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: all files reviewed, 17 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78GX1S6zYr_XorCXQY:-O8Vzinx0CsI5Rd9GoKb:btp1kvj) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L66)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Yoni move it into pre_process_and_create to make it a shared code.
</blockquote></details>

Ok, please rename here also to `preprocess_and_create_transaction_executor`.
___
*[`crates/batcher/src/block_builder.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8VsrToBZDuYffNj_vB:-O8VsrToBZDuYffNj_vC:b-fw1qw2) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L33)):*
> ```XML
> use crate::papyrus_state::PapyrusReader;
> use crate::proposal_manager::InputTxStream;
> ```

Please rearrange the declarations in this file as follows (mainly move trait declaration to be above the implementation, and spme struct definitions to be above their usage):

```
pub enum BlockBuilderError {}
pub type BlockBuilderResult<T> = Result<T, BlockBuilderError>;
pub struct BlockExecutionArtifacts {}
pub trait BlockBuilderTrait: Send {}
impl BlockBuilderTrait for Box<dyn BlockBuilderTrait> {}

pub struct BlockBuilder {}
impl BlockBuilderTrait for BlockBuilder {}

pub trait BlockBuilderFactoryTrait {}

pub struct ExecutionConfig {}
pub struct BlockBuilderFactory {}
impl BlockBuilderFactory {}
impl BlockBuilderFactoryTrait for BlockBuilderFactory {}

pub trait BlockifierTransactionExecutorTrait: Send {}
impl<S: StateReader + Send + Sync> BlockifierTransactionExecutorTrait for TransactionExecutor<S> {}
```
___
*[`crates/batcher/src/block_builder.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8VsER4Ej7qkMCwhbfy:-O8VsER4Ej7qkMCwhbfz:b-hcylvn) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L74)):*
> ```XML
> 
> // TODO (yael 22/9/2024): implement this function for the next milestone
> pub fn get_gas_prices() -> GasPrices {
> ```

No need to add this function now.
Please use `GasPrice::new(...)` where needed with a TODO beside.
___
*[`crates/batcher/src/block_builder.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8VwloZ46TFWZ-C9Cqg:-O8VwloZ46TFWZ-C9Cqh:btxojo4) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L82)):*
> ```XML
> #[derive(Default, Debug, PartialEq)]
> pub struct BlockExecutionArtifacts {
>     // TODO(yael): what is the best id for mapping? tx_hash or tx_id? depends on the orchestrator
> ```

What is the difference?



_Code quote:_
```XML
tx_hash or tx_id?
```
___
*[`crates/batcher/src/block_builder.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8Vuh-j63d2rwYvBt6a:-O8Vuh-j63d2rwYvBt6b:bghxr81) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L91)):*
> ```XML
> 
> #[async_trait]
> impl BlockBuilderTrait for Box<dyn BlockBuilderTrait> {
> ```

Why do we need this?
___
*[`crates/batcher/src/block_builder.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W01A2Bx_Fuqw-6lm2:-O8W01A2Bx_Fuqw-6lm3:bjpvudg) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L105)):*
> ```XML
> #[async_trait]
> pub trait BlockBuilderTrait: Send {
>     async fn build_block(
> ```

Please add documentation.



_Code quote:_
```XML
async fn build_block(
```
___
*[`crates/batcher/src/block_builder.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W06GF0kch1pfKod9L:-O8W06GF0kch1pfKod9M:bjpvudg) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L115)):*
> ```XML
> #[cfg_attr(test, automock)]
> pub trait BlockBuilderFactoryTrait {
>     fn create_block_builder(
> ```

Please add documentation.



_Code quote:_
```XML
fn create_block_builder(
```
___
*[`crates/batcher/src/block_builder.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W11CnD9-LRxVfAMqQ:-O8W11CnD9-LRxVfAMqR:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L117)):*
> ```XML
>     fn create_block_builder(
>         &self,
>         next_block_number: BlockNumber,
> ```





_Suggestion:_
```XML
height: BlockNumber,
```
___
*[`crates/batcher/src/block_builder.rs` line 129 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8VxJJl2rO5pjlDXwuv:-O8VxJJmDerX7Tee7KY8:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L129)):*
> ```XML
> 
> impl BlockBuilderFactory {
>     pub fn create_transaction_executor(
> ```





_Suggestion:_
```XML
fn create_transaction_executor(
```
___
*[`crates/batcher/src/block_builder.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8Vz6bJBJLHS_wLEz1H:-O8Vz6bJBJLHS_wLEz1I:b3t2leu) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L133)):*
> ```XML
>         next_block_number: BlockNumber,
>         retrospective_block_hash: Option<BlockNumberHashPair>,
>     ) -> BlockBuilderResult<Box<dyn BlockifierTransactionExecutorTrait>> {
> ```

It's the caller decision to hold it in a Box.



_Suggestion:_
```XML
BlockBuilderResult<TransactionExecutor<StorageReader>> 
```
___
*[`crates/batcher/src/block_builder.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W-HnK0ZvMz_M5PhDs:-O8W-HnK0ZvMz_M5PhDt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L190)):*
> ```XML
> 
> #[cfg_attr(test, automock)]
> pub trait BlockifierTransactionExecutorTrait: Send {
> ```





_Suggestion:_
```XML
pub trait TransactionExecutorTrait: Send {
```
___
*[`crates/batcher/src/block_builder.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W-Ol91O7f9B9PCKB4:-O8W-Ol91O7f9B9PCKB5:b-mkosuu) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L190)):*
> ```XML
> 
> #[cfg_attr(test, automock)]
> pub trait BlockifierTransactionExecutorTrait: Send {
> ```

Let's move it to a dedicated file `transaction_executor.rs`.
This file already has many trait ans struct definitions.
___
*[`crates/batcher/src/block_builder.rs` line 191 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W0Cuj0VJXZ1nLkvt1:-O8W0Cuj0VJXZ1nLkvt2:b-dkxdp7) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L191)):*
> ```XML
> #[cfg_attr(test, automock)]
> pub trait BlockifierTransactionExecutorTrait: Send {
>     fn add_txs_to_block(
> ```

Please add documentation for both functions.



_Code quote:_
```XML
fn add_txs_to_block(
```
___
*[`crates/batcher/src/proposal_manager.rs` line 132 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W1kI0B8IyDiq1O78s:-O8W1kI0B8IyDiq1O78t:bgpp59r) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e [...]

2024-10-06 10:51 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: all files reviewed, 18 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8WSGzcA5c4tuTHHpFL:-O8WSGzcA5c4tuTHHpFM:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L36)):*
> ```XML
> pub struct BlockBuilder {
>     _executor: Mutex<Box<dyn BlockifierTransactionExecutorTrait>>,
>     _txs_chunk_size: usize,
> ```





_Suggestion:_
```XML
_tx_chunk_size
```


<!-- Sent from Reviewable.io -->

2024-10-07 10:20 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: all files reviewed, 18 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/batcher/src/block_builder.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O78GX1S6zYr_XorCXQY:-O8aSkqK9HcvOIiqHcZa:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/433a11eaed7bc62f27deb94de12fee161ef3b008/crates/batcher/src/block_builder.rs#L66)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Ok, please rename here also to `preprocess_and_create_transaction_executor`.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O7Y-VX_5R8jcx9oM2gp:-O8aRyzLCnkDGA-ruK1d:b-vwrso1) ([raw file](https://github.com/starkware-libs/sequencer/blob/20672c7c8ccf44001e718a45057dbd33d273ae9e/crates/batcher/src/block_builder.rs#L44)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't think we need this function.
For the real flow it will be part of the `create_block_builder` and for mocking the block builder we don't need to create a transaction executor.
</blockquote></details>

I removed the pub. I think this function adds a nice logic separation. not sure what is the harm in having it.
___
*[`crates/batcher/src/block_builder.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8VsrToBZDuYffNj_vB:-O8aD7N93qnwwOpkP3Xc:b-79gyfa) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L33)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please rearrange the declarations in this file as follows (mainly move trait declaration to be above the implementation, and spme struct definitions to be above their usage):

```
pub enum BlockBuilderError {}
pub type BlockBuilderResult<T> = Result<T, BlockBuilderError>;
pub struct BlockExecutionArtifacts {}
pub trait BlockBuilderTrait: Send {}
impl BlockBuilderTrait for Box<dyn BlockBuilderTrait> {}

pub struct BlockBuilder {}
impl BlockBuilderTrait for BlockBuilder {}

pub trait BlockBuilderFactoryTrait {}

pub struct ExecutionConfig {}
pub struct BlockBuilderFactory {}
impl BlockBuilderFactory {}
impl BlockBuilderFactoryTrait for BlockBuilderFactory {}

pub trait BlockifierTransactionExecutorTrait: Send {}
impl<S: StateReader + Send + Sync> BlockifierTransactionExecutorTrait for TransactionExecutor<S> {}
```
</blockquote></details>

will do in a seperate PR after we push these two since I don't want to get too many conflicts.
___
*[`crates/batcher/src/block_builder.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8WSGzcA5c4tuTHHpFL:-O8aEERqDLCSzLDyemaX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L36)):*
> ```XML
> pub struct BlockBuilder {
>     _executor: Mutex<Box<dyn BlockifierTransactionExecutorTrait>>,
>     _txs_chunk_size: usize,
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8VsER4Ej7qkMCwhbfy:-O8aQXDG6V5kBim3QK9J:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L74)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

No need to add this function now.
Please use `GasPrice::new(...)` where needed with a TODO beside.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8VwloZ46TFWZ-C9Cqg:-O8aBAZ-9Ea4RMr-dBGC:b298yfx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L82)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What is the difference?
</blockquote></details>

this comment was deleted in the following PR. deleting here as well.
done.
___
*[`crates/batcher/src/block_builder.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8Vuh-j63d2rwYvBt6a:-O8aQm3pDITlwXuXw404:b-9unw5o) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L91)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why do we need this?
</blockquote></details>

deleted
___
*[`crates/batcher/src/block_builder.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W01A2Bx_Fuqw-6lm2:-O8aRZru6gSXJzYCySiA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L105)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add documentation.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W06GF0kch1pfKod9L:-O8aRZ9l9s_BOdqDaSjn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L115)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add documentation.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W11CnD9-LRxVfAMqQ:-O8aRrVE6Yv16KHv9J8H:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L117)):*
> ```XML
>     fn create_block_builder(
>         &self,
>         next_block_number: BlockNumber,
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 129 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8VxJJl2rO5pjlDXwuv:-O8aSBzI-bO42TRzcUZ3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L129)):*
> ```XML
> 
> impl BlockBuilderFactory {
>     pub fn create_transaction_executor(
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8Vz6bJBJLHS_wLEz1H:-O8aSQtk-OS0ZnxQO9d8:b-oh7k82) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L133)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

It's the caller decision to hold it in a Box.
</blockquote></details>

the compiler is saying that 
the size for values of type `(dyn block_builder::BlockBuilderTrait + 'static)` cannot be known at compilation time
the trait `std::marker::Sized` is not implemented for `(dyn block_builder::BlockBuilderTrait + 'static)`
___
*[`crates/batcher/src/block_builder.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W-HnK0ZvMz_M5PhDs:-O8aSpp53f-Sh8SYbyfH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L190)):*
> ```XML
> 
> #[cfg_attr(test, automock)]
> pub trait BlockifierTransactionExecutorTrait: Send {
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W-Ol91O7f9B9PCKB4:-O8aSqOa44Rii5xNBlz9:b-w0zsa3) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L190)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Let's move it to a dedica [...]

2024-10-07 11:51 UTC, dafnamatsry requested changes
> Reviewed 1 of 14 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8Vz6bJBJLHS_wLEz1H:-O8amdrf56pVfXYA964q:b3z63vx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L133)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

the compiler is saying that 
the size for values of type `(dyn block_builder::BlockBuilderTrait + 'static)` cannot be known at compilation time
the trait `std::marker::Sized` is not implemented for `(dyn block_builder::BlockBuilderTrait + 'static)`
</blockquote></details>

Note I suggested to return a non generic type `BlockBuilderResult<TransactionExecutor<StorageReader>>`.
___
*[`crates/batcher/src/block_builder.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8am5aG8gz1lGIDphPZ:-O8am5aG8gz1lGIDphP_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c72333117207cbe240d4f92adfb0a8de6b6da50/crates/batcher/src/block_builder.rs#L81)):*
> ```XML
> }
> 
> /// The BlockBuilderTrait is responsible for building a new block from ransactions provided in
> ```





_Suggestion:_
```XML
transactions
```
___
*[`crates/batcher/src/proposal_manager.rs` line 132 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W1kI0B8IyDiq1O78s:-O8anoV52LSZulRnMCvc:by1dusy) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/proposal_manager.rs#L132)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure how to solve this right now, added a a todo
</blockquote></details>

You can put a temp value when calling `create_block_builder` with a todo.
This way the API and tests will stay the same.


<!-- Sent from Reviewable.io -->

2024-10-07 12:01 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8Vz6bJBJLHS_wLEz1H:-O8apQI69Z3b3wLlG_Ge:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/block_builder.rs#L133)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Note I suggested to return a non generic type `BlockBuilderResult<TransactionExecutor<StorageReader>>`.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8am5aG8gz1lGIDphPZ:-O8aopLD2i-qYXQNQo5M:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c72333117207cbe240d4f92adfb0a8de6b6da50/crates/batcher/src/block_builder.rs#L81)):*
> ```XML
> }
> 
> /// The BlockBuilderTrait is responsible for building a new block from ransactions provided in
> ```

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 132 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8W1kI0B8IyDiq1O78s:-O8aqAiVCwyfljt1dl4H:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eef98164b16800ef8d09680a4e84f3b84c7afb9/crates/batcher/src/proposal_manager.rs#L132)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

You can put a temp value when calling `create_block_builder` with a todo.
This way the API and tests will stay the same.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-07 12:03 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745#-:-O8ar8Ko5D8PEiPChrpW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-07 13:59 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745#-:-O8bGkhP3631KD9rXs5A:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-07 13:59 UTC, dafnamatsry approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/745)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-07 14:59 UTC, merged