feat(batcher): batcher client trait
starkware-libs/sequencer pull request #751
Opened 2024-09-09 09:52 UTC by yair-starkware

2024-09-09 14:05 UTC, matan-starkware requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6M2oI_1AymaGrlQYJ9:-O6M2oI_1AymaGrlQYJA:b-cu2nn0) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/batcher_types.rs#L11)):*
> ```XML
> 
> // TBD: Do we need id from the client?
> pub type ProposalId = u64;
> ```

I think that this type should be defined in consensus. My current inclination is for it to be a struct (height, round, nonce)



_Code quote:_
```XML
// TBD: Do we need id from the client?
pub type ProposalId = u64;
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6M2OASC5HgbnSnA8Wj:-O6M2OASC5HgbnSnA8Wk:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/batcher_types.rs#L22)):*
> ```XML
>     Txs(Vec<Transaction>),
>     Fin(ProposalContentId),
>     Abort,
> ```





_Suggestion:_
```XML
    // Indicates an error with the content, not the components (i.e., batcher/consensus).
    Abort,
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6M58yx1ol0m540Ej4z:-O6M58yx1ol0m540Ej5-:bhga1vp) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/batcher_types.rs#L26)):*
> ```XML
> 
> #[derive(Clone, Debug, Serialize, Deserialize)]
> pub struct BuildProposalInput {
> ```

Assumes the height of the proposal matches the most recent call to `start_height`



_Code quote:_
```XML
BuildProposalInput
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6M1ky556WpAQb8etUq:-O6M1ky556WpAQb8etUr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/batcher_types.rs#L54)):*
> ```XML
>     ValidProposal(ProposalContentId),
>     InvalidProposal,
> }
> ```





_Suggestion:_
```XML
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum SendContentResponse {
    Ack,
    // Only sent in response to `Fin`
    ValidProposal(ProposalContentId),
    // May be caused due to handling of a previous item on the stream.
    InvalidProposal,
}
```
___
*[`crates/batcher_types/src/communication.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6M5a7Y6-8C2VhztkCO:-O6M5a7Y6-8C2VhztkCP:bvod9d5) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/communication.rs#L84)):*
> ```XML
> 
> #[async_trait]
> impl BatcherClient for LocalBatcherClientImpl {
> ```

These impls are basically the boilerplate for the components IIUC. Is there an actual implementation currently or this is still just a shell?



_Code quote:_
```XML
impl BatcherClient for LocalBatcherClientImpl {
```


<!-- Sent from Reviewable.io -->

2024-09-15 07:39 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6M2oI_1AymaGrlQYJ9:-O6oZsR39O7SzE0xOFyv:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/batcher_types.rs#L11)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think that this type should be defined in consensus. My current inclination is for it to be a struct (height, round, nonce)
</blockquote></details>

Done
___
*[`crates/batcher_types/src/batcher_types.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6M58yx1ol0m540Ej4z:-O6oZNK0D4N6O-dBRc1_:b7u03hh) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/batcher_types.rs#L26)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Assumes the height of the proposal matches the most recent call to `start_height`
</blockquote></details>

Correct
___
*[`crates/batcher_types/src/batcher_types.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6M1ky556WpAQb8etUq:-O6oZgaU0uuoPo98Ldwc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/batcher_types.rs#L54)):*
> ```XML
>     ValidProposal(ProposalContentId),
>     InvalidProposal,
> }
> ```

Done.
___
*[`crates/batcher_types/src/communication.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6M5a7Y6-8C2VhztkCO:-O6oZjPu8EAWLWACZQaS:b2nhqqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/communication.rs#L84)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

These impls are basically the boilerplate for the components IIUC. Is there an actual implementation currently or this is still just a shell?
</blockquote></details>

WIP


<!-- Sent from Reviewable.io -->

2024-09-15 07:39 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6M2OASC5HgbnSnA8Wj:-O6obqrs-cLaKeNjc9TA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/batcher_types.rs#L22)):*
> ```XML
>     Txs(Vec<Transaction>),
>     Fin(ProposalContentId),
>     Abort,
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-15 08:25 UTC, Yael-Starkware requested changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: 3 of 8 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6LXi8y8tPznlCPuoXI:-O6LXi8z67CMNDAOlIMn:b-mezxuq) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/batcher_types.rs#L21)):*
> ```XML
> pub enum StreamContent {
>     Txs(Vec<Transaction>),
>     Fin(ProposalContentId),
> ```

Fin is not so clear, lets write the full word , (Finish/Final/End...)



_Code quote:_
```XML
Fin
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6oiPQU9DeCUf2qPiwz:-O6oiPQU9DeCUf2qPix-:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L27)):*
> ```XML
> pub struct BuildProposalInput {
>     pub proposal_id: ProposalId,
>     pub deadline: chrono::DateTime<Utc>,
> ```





_Suggestion:_
```XML
pub deadline: chrono::DateTime<Utc>,
pub restrospective_block_hash: BlockNumberHashPair,
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6olu5m4QOk8U1ory9t:-O6olu5m4QOk8U1ory9u:b-in9ka3) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L52)):*
> ```XML
>     Ack,
>     // Only sent in response to `Fin`
>     ValidProposal(ProposalContentId),
> ```

The batcher does not decide if the proposal is valid, it only computes the ProposalContentId



_Suggestion:_
```XML
Final(ProposalContentId),
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6om7dLDSaNp_bXr9b2:-O6om7dLDSaNp_bXr9b3:bhnkigg) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L54)):*
> ```XML
>     ValidProposal(ProposalContentId),
>     // May be caused due to handling of a previous item on the stream.
>     InvalidProposal,
> ```

again, the batcher does not decide if the proposal is valid.
wdym mean by "handling of a previous item on the stream" ?



_Code quote:_
```XML
    // May be caused due to handling of a previous item on the stream.
    InvalidProposal,
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6oj-eQ5cvoz3bxXpNr:-O6oj-eQ5cvoz3bxXpNs:bowxeog) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L66)):*
> ```XML
>     // TBD: We don't both ids.
>     pub proposal_id: ProposalId,
>     pub content_id: ProposalContentId,
> ```

lets use only proposal_id



_Code quote:_
```XML
    // TBD: We don't both ids.
    pub proposal_id: ProposalId,
    pub content_id: ProposalContentId,
```
___
*[`crates/consensus_manager_types/src/consensus_manager_types.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6okBFd9Pgp6FMQ3FVU:-O6okBFd9Pgp6FMQ3FVV:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/consensus_manager_types/src/consensus_manager_types.rs#L9)):*
> ```XML
>     Copy, Clone, Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Default, Display,
> )]
> pub struct ProposalId(pub u64);
> ```





_Suggestion:_
```XML
// TODO (Matan) decide on the id structure
pub struct ProposalId(pub u64);
```


<!-- Sent from Reviewable.io -->

2024-09-15 12:39 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: 3 of 8 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6LXi8y8tPznlCPuoXI:-O6peKIf-y6_TrSoHy7E:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c922f1603cc044abcf3ee239c5c1529ced30a886/crates/batcher_types/src/batcher_types.rs#L21)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Fin is not so clear, lets write the full word , (Finish/Final/End...)
</blockquote></details>

Done.
___
*[`crates/batcher_types/src/batcher_types.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6oiPQU9DeCUf2qPiwz:-O6p_uWnAGKmwz_S1Dfr:b67l5mj) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L27)):*
> ```XML
> pub struct BuildProposalInput {
>     pub proposal_id: ProposalId,
>     pub deadline: chrono::DateTime<Utc>,
> ```

Why do we need this from the consensus?
___
*[`crates/batcher_types/src/batcher_types.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6olu5m4QOk8U1ory9t:-O6pa4se0zyMsp3XxoKt:b-y21msm) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L52)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The batcher does not decide if the proposal is valid, it only computes the ProposalContentId
</blockquote></details>

It can decide if for example the block is full and there are more transactions
___
*[`crates/batcher_types/src/batcher_types.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6om7dLDSaNp_bXr9b2:-O6paIsjEt1l0sQn_BYo:b2jtc0y) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L54)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

again, the batcher does not decide if the proposal is valid.
wdym mean by "handling of a previous item on the stream" ?
</blockquote></details>

The case of block full for example
___
*[`crates/batcher_types/src/batcher_types.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6oj-eQ5cvoz3bxXpNr:-O6peOaZ-idwvBcC6baN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L66)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

lets use only proposal_id
</blockquote></details>

Done.
___
*[`crates/consensus_manager_types/src/consensus_manager_types.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6okBFd9Pgp6FMQ3FVU:-O6peUyb0HycDn3NxrK4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/consensus_manager_types/src/consensus_manager_types.rs#L9)):*
> ```XML
>     Copy, Clone, Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Default, Display,
> )]
> pub struct ProposalId(pub u64);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-16 12:26 UTC, matan-starkware approved these changes
> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: all files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-16 13:32 UTC, Yael-Starkware requested changes
> Reviewed 1 of 6 files at r1, 2 of 5 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6olu5m4QOk8U1ory9t:-O6v0rmlBrS6hfS58A6m:bmf3x6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L52)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It can decide if for example the block is full and there are more transactions
</blockquote></details>

as we agreed, it should be Done(ProposalContentId)
___
*[`crates/batcher_types/src/batcher_types.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6om7dLDSaNp_bXr9b2:-O6ulytg7dZt7tLnY9RV:b2nhysk) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L54)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The case of block full for example
</blockquote></details>

ack
___
*[`crates/batcher_types/src/errors.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6um9XL7ppXEFCNDhJm:-O6um9XL7ppXEFCNDhJn:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/23e323129537af048ae1c51b753b0800f2f4d4bb/crates/batcher_types/src/errors.rs#L6)):*
> ```XML
> use crate::batcher_types::ProposalId;
> 
> // TODO(Tsabary/Yael/Dafna): Populate with actual errors.
> ```




<!-- Sent from Reviewable.io -->

2024-09-17 09:18 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6oiPQU9DeCUf2qPiwz:-O6zGTwZ88SCld-13Pn-:b-rb4vpw) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L27)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need this from the consensus?
</blockquote></details>

we discussed f2f


<!-- Sent from Reviewable.io -->

2024-09-17 12:50 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6oiPQU9DeCUf2qPiwz:-O7-14JvEiO_Kk61afjT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L27)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

we discussed f2f
</blockquote></details>

Done.
___
*[`crates/batcher_types/src/batcher_types.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6olu5m4QOk8U1ory9t:-O6v9MHE6j0W0pslHkwZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63962a73a74645f523e41bcfc9a7cacbd9382639/crates/batcher_types/src/batcher_types.rs#L52)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

as we agreed, it should be Done(ProposalContentId)
</blockquote></details>

Done.
___
*[`crates/batcher_types/src/errors.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O6um9XL7ppXEFCNDhJm:-O6v9acKE_y5vAq3BJBJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/23e323129537af048ae1c51b753b0800f2f4d4bb/crates/batcher_types/src/errors.rs#L6)):*
> ```XML
> use crate::batcher_types::ProposalId;
> 
> // TODO(Tsabary/Yael/Dafna): Populate with actual errors.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-18 08:39 UTC, Yael-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @dafnamatsry, @dan-starkware, and @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-09-19 06:53 UTC, dafnamatsry requested changes
> Reviewed 3 of 6 files at r1, 1 of 5 files at r2, 1 of 3 files at r3, 3 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: all files reviewed, 10 unresolved discussions (waiting on @dan-starkware, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77vmEFC6sKzN1nt2wI:-O77vmEFC6sKzN1nt2wJ:bid9hlg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L32)):*
> ```XML
> 
> #[derive(Clone, Debug, Serialize, Deserialize)]
> pub enum GetStreamContentResponse {
> ```

Please make it a regular struct that holds a content enum.



_Code quote:_
```XML
pub enum GetStreamContentResponse {
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 36 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77w6dI-pa9g7tce7Ff:-O77w6dI-pa9g7tce7Fg:b-jvblox) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L36)):*
> ```XML
>     Finished(ProposalContentId),
>     // Indicates an error with the content, not the components (i.e., batcher/consensus).
>     Abort,
> ```

Can you give an example?



_Code quote:_
```XML
Abort,
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77wa3NDccCf3DQZXGv:-O77wa3NDccCf3DQZXGw:bdpalg5) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L53)):*
> ```XML
> /// The content of the stream that the consensus sends to the batcher.
> #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
> pub enum SendStreamContent {
> ```

This enum can be used for both `send_stream_content`, and `get_stream_content`.



_Suggestion:_
```XML
pub enum ProposalContent {
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77yO_-43kn5AN_TnhH:-O77yO_-43kn5AN_TnhI:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L60)):*
> ```XML
> 
> #[derive(Clone, Debug, Serialize, Deserialize)]
> pub enum SendContentResponse {
> ```





_Suggestion:_
```XML
SendProposalContentResponse
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77yk_-0DqPdKx8ExZU:-O77yk_-0DqPdKx8ExZV:beovbhc) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L60)):*
> ```XML
> 
> #[derive(Clone, Debug, Serialize, Deserialize)]
> pub enum SendContentResponse {
> ```

It's not clear to me if this is a blocking function or not?
When do we get an Ack? after we execute the txs, or only once we get them?

If this is not a blocking function, what happens if we find out the proposal is invalid after we acked? do we wait for the next request?

This should be well documented.
___
*[`crates/batcher_types/src/batcher_types.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77yIXb16e4gVjiApQT:-O77yIXb16e4gVjiApQU:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L62)):*
> ```XML
> pub enum SendContentResponse {
>     Ack,
>     // Only sent in response to `Fin`
> ```





_Suggestion:_
```XML
// Only sent in response to `Fin`.
```
___
*[`crates/batcher_types/src/batcher_types.rs` line 64 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O780HYh3fNeODD8QpGK:-O780HYh3fNeODD8QpGL:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L64)):*
> ```XML
>     // Only sent in response to `Fin`
>     Finished(ProposalContentId),
>     // May be caused due to handling of a previous item on the stream.
> ```





_Suggestion:_
```XML
// May be caused due to handling of a previous item of the proposal. 
// In this case, the propsal is aborted and no additional content will be processed. 
```
___
*[`crates/batcher_types/src/communication.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O72uTIk9Ltx8rVjDhH8:-O72uTIk9Ltx8rVjDhH9:bou4pyo) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/communication.rs#L40)):*
> ```XML
> #[automock]
> #[async_trait]
> pub trait BatcherClient: Send + Sync {
> ```

Please add documentation to all the functions.
___
*[`crates/batcher_types/src/communication.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O72uiZkEXUd8mBWN1Am:-O72uiZl4TRLfKGYNQR0:bro7arw) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/communication.rs#L42)):*
> ```XML
> pub trait BatcherClient: Send + Sync {
>     async fn build_proposal(&self, input: BuildProposalInput) -> BatcherClientResult<()>;
>     async fn get_stream_content(
> ```

I think we should stick to `proposal`, as we decided not to use streams and `StreamId`.
Same for the `Input` and `Response` structs.



_Suggestion:_
```XML
get_proposal_content
```
___
*[`crates/batcher_types/src/communication.rs` line 47 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O72v24lCO6WMOY0ZpJ-:-O72v24m5ymdruX1xJbj:bh1lyv7) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/communication.rs#L47)):*
> ```XML
>     ) -> BatcherClientResult<GetStreamContentResponse>;
>     async fn validate_proposal(&self, input: ValidateProposalInput) -> BatcherClientResult<()>;
>     async fn send_stream_content(
> ```

Same for the `Input` and `Response` structs.



_Suggestion:_
```XML
send_proposal_content
```


<!-- Sent from Reviewable.io -->

2024-09-22 08:37 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @matan-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77vmEFC6sKzN1nt2wI:-O7Nf0gHDluaOztFa_Xm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L32)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please make it a regular struct that holds a content enum.
</blockquote></details>

Done.
___
*[`crates/batcher_types/src/batcher_types.rs` line 36 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77w6dI-pa9g7tce7Ff:-O7Nf44oA-VFXqBIx8hN:b-6gyd9t) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L36)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you give an example?
</blockquote></details>

@matan-starkware do you remember why we needed this? Can't think of the reason now
___
*[`crates/batcher_types/src/batcher_types.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77wa3NDccCf3DQZXGv:-O7NfDi--wMI4TddA9IM:b-wie8ue) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L53)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

This enum can be used for both `send_stream_content`, and `get_stream_content`.
</blockquote></details>

We need to return the content id in the `get` method
___
*[`crates/batcher_types/src/batcher_types.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77yO_-43kn5AN_TnhH:-O7NgSLl-V734Obczopm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L60)):*
> ```XML
> 
> #[derive(Clone, Debug, Serialize, Deserialize)]
> pub enum SendContentResponse {
> ```

Done.
___
*[`crates/batcher_types/src/batcher_types.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77yk_-0DqPdKx8ExZU:-O7NgT_s-iopIDCNCzkd:bpxziv0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L60)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

It's not clear to me if this is a blocking function or not?
When do we get an Ack? after we execute the txs, or only once we get them?

If this is not a blocking function, what happens if we find out the proposal is invalid after we acked? do we wait for the next request?

This should be well documented.
</blockquote></details>

Added documentation in the client methods
___
*[`crates/batcher_types/src/batcher_types.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77yIXb16e4gVjiApQT:-O7NkOk94KuZTMNAP2YR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L62)):*
> ```XML
> pub enum SendContentResponse {
>     Ack,
>     // Only sent in response to `Fin`
> ```

Done.
___
*[`crates/batcher_types/src/batcher_types.rs` line 64 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O780HYh3fNeODD8QpGK:-O7NkcBI95FAe10XymhH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L64)):*
> ```XML
>     // Only sent in response to `Fin`
>     Finished(ProposalContentId),
>     // May be caused due to handling of a previous item on the stream.
> ```

Done.
___
*[`crates/batcher_types/src/communication.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O72uTIk9Ltx8rVjDhH8:-O7NkfFS6cAyRnocjRYy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/communication.rs#L40)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add documentation to all the functions.
</blockquote></details>

Done.
___
*[`crates/batcher_types/src/communication.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O72uiZkEXUd8mBWN1Am:-O7NkhLz4DV7nPbzSjcx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/communication.rs#L42)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think we should stick to `proposal`, as we decided not to use streams and `StreamId`.
Same for the `Input` and `Response` structs.
</blockquote></details>

Done.
___
*[`crates/batcher_types/src/communication.rs` line 47 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O72v24lCO6WMOY0ZpJ-:-O7NkiDYAn9LgHoGINlm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/communication.rs#L47)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Same for the `Input` and `Response` structs.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-22 09:35 UTC, dafnamatsry requested changes
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @dan-starkware, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 36 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77w6dI-pa9g7tce7Ff:-O7O4-gJ3-GVMXO0qhtb:b-xwoof0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L36)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

@matan-starkware do you remember why we needed this? Can't think of the reason now
</blockquote></details>

So let's remove it for now and only add it if needed?
___
*[`crates/batcher_types/src/batcher_types.rs` line 72 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O7O-N_50CKUdGDK4yYK:-O7O-N_50CKUdGDK4yYL:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/32cd9503ec27ada691f03b361ac59ca40ecd4a88/crates/batcher_types/src/batcher_types.rs#L72)):*
> ```XML
> pub enum ProposalStatus {
>     Processing,
>     // Only sent in response to `Fin`.
> ```





_Suggestion:_
```XML
`Finish`
```
___
*[`crates/batcher_types/src/communication.rs` line 62 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O7O0AkGDLXKNWdkHdBN:-O7O0AkGDLXKNWdkHdBO:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/32cd9503ec27ada691f03b361ac59ca40ecd4a88/crates/batcher_types/src/communication.rs#L62)):*
> ```XML
>     async fn start_height(&self, input: StartHeightInput) -> BatcherClientResult<()>;
>     /// Notifies the batcher that a decision has been reached.
>     async fn decision_reached(&self, input: DecisionReachedInput) -> BatcherClientResult<()>;
> ```





_Suggestion:_
```XML
    /// Starts the process of validating a proposal.
    async fn validate_proposal(&self, input: ValidateProposalInput) -> BatcherClientResult<()>;
    
    /// Sends the content of a proposal. Only relevant when validating a proposal.
    /// Note: 
    ///   * The batcher acks when the content is received immediately, not waiting for it to finish
    ///     processing. The next send might receive an `InvalidProposal` response for the previous send.
    ///   * If this marks the end of the content, i.e. `SendProposalContent::Finish` is receives, the batcher 
    ///     will until the proposal has finished processing before responding.
    async fn send_proposal_content(
        &self,
        input: SendProposalContentInput,
    ) -> BatcherClientResult<SendProposalContentResponse>;
    
    /// Starts the process of a new height. 
    /// From this point onwards, the batcher will accept requests only for proposals associated 
    /// with this height.
    async fn start_height(&self, input: StartHeightInput) -> BatcherClientResult<()>;
    
    /// Notifies the batcher that a decision has been reached.
    /// This closes the process of the given height, and the accepted proposal is committed.
    async fn decision_reached(&self, input: DecisionReachedInput) -> BatcherClientResult<()>;
```


<!-- Sent from Reviewable.io -->

2024-09-22 09:35 UTC, dafnamatsry reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: all files reviewed, 6 unresolved discussions (waiting on @dan-starkware, @matan-starkware, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-09-22 10:52 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @matan-starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 36 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O77w6dI-pa9g7tce7Ff:-O7OLB0u0lW0qPBXWBYf:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/a35b20e84b207fa9922a9dfdce9e2d7abb700261/crates/batcher_types/src/batcher_types.rs#L36)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

So let's remove it for now and only add it if needed?
</blockquote></details>

Done
___
*[`crates/batcher_types/src/batcher_types.rs` line 72 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O7O-N_50CKUdGDK4yYK:-O7OKFcd-4tVKqILlLim:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/32cd9503ec27ada691f03b361ac59ca40ecd4a88/crates/batcher_types/src/batcher_types.rs#L72)):*
> ```XML
> pub enum ProposalStatus {
>     Processing,
>     // Only sent in response to `Fin`.
> ```

Done.
___
*[`crates/batcher_types/src/communication.rs` line 62 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/751#-O7O0AkGDLXKNWdkHdBN:-O7OL30vB_Yz4OFSvxsK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/32cd9503ec27ada691f03b361ac59ca40ecd4a88/crates/batcher_types/src/communication.rs#L62)):*
> ```XML
>     async fn start_height(&self, input: StartHeightInput) -> BatcherClientResult<()>;
>     /// Notifies the batcher that a decision has been reached.
>     async fn decision_reached(&self, input: DecisionReachedInput) -> BatcherClientResult<()>;
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-22 11:52 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/751#-:-O7OZqde-3PTfjDE9m-8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-09-22 12:07 UTC, merged