fix(blockifier): recommit to fix charge_fee_enforce_fee pr order
starkware-libs/sequencer pull request #793
Opened 2024-09-15 13:53 UTC by avivg-starkware

2024-09-15 14:22 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6q1lWFBS2AEQHghaZb:-O6q1lWFBS2AEQHghaZc:bkjgftx) ([raw file](https://github.com/starkware-libs/sequencer/blob/5000aa4f78dd9f326489d999cea2dbe066fd186c/crates/blockifier/src/concurrency/versioned_state_test.rs#L273)):*
> ```XML
>     thread::scope(|s| {
>         s.spawn(move || {
>             let charge_fee_1 = account_tx_1.create_tx_info().enforce_fee(); // aviv: todo better implementation?
> ```

remove all comments that start with aviv 


<!-- Sent from Reviewable.io -->

2024-09-17 12:14 UTC, meship-starkware requested changes
> Reviewed 4 of 11 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 6 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zhxDhBOksVHkDBf4r:-O6zhxDhBOksVHkDBf4s:boeweuy) ([raw file](https://github.com/starkware-libs/sequencer/blob/1233182cea21224303de0e6f6f9cf272e51dfd12/crates/blockifier/src/transaction/account_transactions_test.rs#L164)):*
> ```XML
> 
> #[rstest]
> fn test_fee_enforcement(
> ```

We need to consider this test's relevance with the new behavior. I think this is still relevant because max fee 0 still has a special 
behavior  @noaov1  WDYT?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zs1C99USx6pK7C174:-O6zs1C99USx6pK7C175:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7affb826e88c92e1cf7efdb2276af8c30786e9cb/crates/blockifier/src/transaction/account_transactions_test.rs#L182)):*
> ```XML
> 
>     let account_tx = AccountTransaction::DeployAccount(deploy_account_tx);
>     let enforce_fee = account_tx.create_tx_info().enforce_fee();
> ```





_Suggestion:_
```XML
let charge_fee = account_tx.create_tx_info().enforce_fee();
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zsXtc-eou3Bm8a3Tb:-O6zsXtc-eou3Bm8a3Tc:be9un8z) ([raw file](https://github.com/starkware-libs/sequencer/blob/1233182cea21224303de0e6f6f9cf272e51dfd12/crates/blockifier/src/transaction/account_transactions_test.rs#L190)):*
> ```XML
> #[case(TransactionVersion::ZERO)]
> #[case(TransactionVersion::ONE)]
> #[case(TransactionVersion::THREE)]
> ```

I believe this test is irrelevant now. We can add the is_reverted check to the `test_fee_enforcement` @noaov1  WDYT?
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 306 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zgirZ1lUXlaTr9Vai:-O6zgirZ1lUXlaTr9Vaj:b-7f2jmg) ([raw file](https://github.com/starkware-libs/sequencer/blob/7affb826e88c92e1cf7efdb2276af8c30786e9cb/crates/blockifier/src/transaction/test_utils.rs#L306)):*
> ```XML
>         true,
>     ) // aviv: true, true
> }
> ```

I don't feel strongly about it, but I think it's more readable. 



_Suggestion:_
```XML
    let tx = account_invoke_tx(invoke_args.clone());
    let tx_context = Arc::new(block_context.to_tx_context(&tx));
    let charge_fee = tx_context.tx_info.enforce_fee();
    account_invoke_tx(invoke_args).execute(
        state,
        block_context,
        charge_fee,
        true,
    ) // aviv: true, true
}
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1614 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zhQ8T4LtDTat2-Xj6:-O6zhQ8T4LtDTat2-Xj7:b-34pymw) ([raw file](https://github.com/starkware-libs/sequencer/blob/7affb826e88c92e1cf7efdb2276af8c30786e9cb/crates/blockifier/src/transaction/transactions_test.rs#L1614)):*
> ```XML
> 
>     // All tx has default resource bounds, thus the default charge fee is the same for all. (aviv)
>     let default_charge_fee = account_tx.create_tx_info().enforce_fee();
> ```

why default_charge_fee? is it because we know that max_fre/ resource_bounds are Zero?


<!-- Sent from Reviewable.io -->

2024-09-19 12:50 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 2 of 11 files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6q1lWFBS2AEQHghaZb:-O79BRKcBMrxkf3MTGf9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5000aa4f78dd9f326489d999cea2dbe066fd186c/crates/blockifier/src/concurrency/versioned_state_test.rs#L273)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

remove all comments that start with aviv
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zhxDhBOksVHkDBf4r:-O79IVLQ10AUCjebF435:b-751x8z) ([raw file](https://github.com/starkware-libs/sequencer/blob/1233182cea21224303de0e6f6f9cf272e51dfd12/crates/blockifier/src/transaction/account_transactions_test.rs#L164)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

We need to consider this test's relevance with the new behavior. I think this is still relevant because max fee 0 still has a special 
behavior  @noaov1  WDYT?
</blockquote></details>

hi just sanity check  to make sure i understand: this test asserts that when max_fee/resource_bounds is 0 the execution succeeds and when it is 1 - execution fails. If so - where is the special case w max_fee = 0 can be found in the code?  
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1614 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zhQ8T4LtDTat2-Xj6:-O799rgX3b-3hw22iwQu:bvgz7vv) ([raw file](https://github.com/starkware-libs/sequencer/blob/7affb826e88c92e1cf7efdb2276af8c30786e9cb/crates/blockifier/src/transaction/transactions_test.rs#L1614)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

why default_charge_fee? is it because we know that max_fre/ resource_bounds are Zero?
</blockquote></details>

Yes Exactly. do you think it's better to just use "charge_fee" i thought it might be more indicative in this case since "account_tx" (which we're using) was created with "default_args"


<!-- Sent from Reviewable.io -->

2024-09-22 04:53 UTC, meship-starkware reviewed
> Reviewed 4 of 9 files at r3, 4 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1614 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zhQ8T4LtDTat2-Xj6:-O7N3aKtCSXRk4c6679S:b-cfbj69) ([raw file](https://github.com/starkware-libs/sequencer/blob/7affb826e88c92e1cf7efdb2276af8c30786e9cb/crates/blockifier/src/transaction/transactions_test.rs#L1614)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Yes Exactly. do you think it's better to just use "charge_fee" i thought it might be more indicative in this case since "account_tx" (which we're using) was created with "default_args"
</blockquote></details>

I think it is good with the comment. It is better than just 'charge_fee' because you use it for multiple txes.
,  


<!-- Sent from Reviewable.io -->

2024-09-22 04:55 UTC, meship-starkware reviewed
> Reviewed 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-09-22 11:59 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zhxDhBOksVHkDBf4r:-O7O_gDp-pR_9-Mnx89P:b-gp2r4v) ([raw file](https://github.com/starkware-libs/sequencer/blob/1233182cea21224303de0e6f6f9cf272e51dfd12/crates/blockifier/src/transaction/account_transactions_test.rs#L164)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

hi just sanity check  to make sure i understand: this test asserts that when max_fee/resource_bounds is 0 the execution succeeds and when it is 1 - execution fails. If so - where is the special case w max_fee = 0 can be found in the code?
</blockquote></details>

The special behavior is that we do not fail a transaction in the pre-validation test if 'enforce_fee' is false (meaning max_fee/ resource_bounds is 0), but if it is true and max_fee < actual_fee, then the transaction will fail. That is what this test checks.   


<!-- Sent from Reviewable.io -->

2024-09-29 13:24 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 120 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O7xwqPk5n9bIIZNN1ZD:-O7xwqPk5n9bIIZNN1ZE:b-v3fkji) ([raw file](https://github.com/starkware-libs/sequencer/blob/b47f494a3137eea369aa69d48e99525b797fcc37/crates/blockifier/src/transaction/transactions_test.rs#L120)):*
> ```XML
>     FeeType,
>     HasRelatedFeeType,
>     TransactionExecutionInfo,
> ```

TransactionInfoCreator was here
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 142 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O7xwuYk51vz-nxiwvhr:-O7xwuYk51vz-nxiwvhs:bxtawqj) ([raw file](https://github.com/starkware-libs/sequencer/blob/b47f494a3137eea369aa69d48e99525b797fcc37/crates/blockifier/src/transaction/transactions_test.rs#L142)):*
> ```XML
> };
> use crate::transaction::transaction_types::TransactionType;
> use crate::transaction::transactions::{ExecutableTransaction, L1HandlerTransaction, TransactionInfoCreator};
> ```

TransactionInfoCreator remove from here 


<!-- Sent from Reviewable.io -->

2024-09-29 17:04 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zhxDhBOksVHkDBf4r:-O7yjJR7DdSk2fdVzSbJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1233182cea21224303de0e6f6f9cf272e51dfd12/crates/blockifier/src/transaction/account_transactions_test.rs#L164)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

The special behavior is that we do not fail a transaction in the pre-validation test if 'enforce_fee' is false (meaning max_fee/ resource_bounds is 0), but if it is true and max_fee < actual_fee, then the transaction will fail. That is what this test checks.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1614 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zhQ8T4LtDTat2-Xj6:-O7yWryi9Ju7xmRDRIMm:brv5xyg) ([raw file](https://github.com/starkware-libs/sequencer/blob/7affb826e88c92e1cf7efdb2276af8c30786e9cb/crates/blockifier/src/transaction/transactions_test.rs#L1614)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think it is good with the comment. It is better than just 'charge_fee' because you use it for multiple txes.
,
</blockquote></details>

OK thanks
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 120 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O7xwqPk5n9bIIZNN1ZD:-O7yZDbuBsoahes26be-:bt3hlij) ([raw file](https://github.com/starkware-libs/sequencer/blob/b47f494a3137eea369aa69d48e99525b797fcc37/crates/blockifier/src/transaction/transactions_test.rs#L120)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

TransactionInfoCreator was here
</blockquote></details>

you mean that it's better to import from "objects" rather than "transactions"?
any way for just in case this is what I did.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 142 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O7xwuYk51vz-nxiwvhr:-O7yY0OJEmHHqRqhfnzj:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/b47f494a3137eea369aa69d48e99525b797fcc37/crates/blockifier/src/transaction/transactions_test.rs#L142)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

TransactionInfoCreator remove from here
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-09-30 11:07 UTC, meship-starkware reviewed
> Reviewed 5 of 11 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-01 06:25 UTC, noaov1 requested changes
Please open a python PR to test the code

> Reviewed 3 of 11 files at r5, 4 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793#-:-O83VcDd1cSdYY-3cGQJ:b-39frbx)* status: all files reviewed, 9 unresolved discussions (waiting on @avivg-starkware and @meship-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 107 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83Mg5G7K-jiI4UN_tj:-O83Mg5G7K-jiI4UN_tk:b-efqdyw) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/blockifier/transaction_executor.rs#L107)):*
> ```XML
>             self.block_state.as_mut().expect(BLOCK_STATE_ACCESS_ERR),
>         );
>         let tx_charge_fee = tx.create_tx_info().enforce_fee();
> ```

Consider creating a method for `Transaction` and `AccountTransaction`



_Code quote:_
```XML
let tx_charge_fee = tx.create_tx_info().enforce_fee();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 277 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83NouW74GH4Qmn4UeX:-O83NouW74GH4Qmn4UeY:b-cs6rf1) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/concurrency/versioned_state_test.rs#L277)):*
> ```XML
>         s.spawn(move || {
>             let charge_fee_1 = account_tx_1.create_tx_info().enforce_fee();
>             let result = account_tx_1.execute(&mut state_1, &block_context_1, charge_fee_1, true);
> ```

I think that you can leave it true here and below. This flag is not relevant for this test.



_Code quote:_
```XML
            let charge_fee_1 = account_tx_1.create_tx_info().enforce_fee();
            let result = account_tx_1.execute(&mut state_1, &block_context_1, charge_fee_1, true);
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 624 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83W41x28UohuRf69yb:-O83W41x28UohuRf69yc:baym5lj) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/execution/stack_trace_test.rs#L624)):*
> ```XML
>     let re = Regex::new(r"pc=0:[0-9]+").unwrap();
>     let cleaned_expected_error = &re.replace_all(&expected_error, "pc=0:*");
>     let charge_fee = account_tx.create_tx_info().enforce_fee();
> ```

Please revert (see comment above)



_Code quote:_
```XML
    let charge_fee = account_tx.create_tx_info().enforce_fee();
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 688 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83W82UBu8dkbVetChH:-O83W82UBu8dkbVetChI:b-n67mzv) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/execution/stack_trace_test.rs#L688)):*
> ```XML
> 
>     // Compare expected and actual error.
>     let charge_fee = deploy_account_tx.create_tx_info().enforce_fee();
> ```

Please revert



_Code quote:_
```XML
    let charge_fee = deploy_account_tx.create_tx_info().enforce_fee()
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zsXtc-eou3Bm8a3Tb:-O83YbGPB0hgV1ST_fSo:b93trp7) ([raw file](https://github.com/starkware-libs/sequencer/blob/1233182cea21224303de0e6f6f9cf272e51dfd12/crates/blockifier/src/transaction/account_transactions_test.rs#L190)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I believe this test is irrelevant now. We can add the is_reverted check to the `test_fee_enforcement` @noaov1  WDYT?
</blockquote></details>

I suggested a modification :)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 206 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83Yh61Du-ElEngDUu_:-O83Yh61Du-ElEngDUua:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/transaction/account_transactions_test.rs#L206)):*
> ```XML
>     .unwrap();
>     assert!(!tx_execution_info.is_reverted());
>     assert_eq!(tx_execution_info.receipt.fee, Fee(0));
> ```





_Suggestion:_
```XML
assert!(tx_execution_info.fee_transfer_info.is_none());
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 615 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83Z1NYE4DO_aBSxbAx:-O83Z1NZDz3Z_h0S3iKN:b5wfrtu) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/transaction/account_transactions_test.rs#L615)):*
> ```XML
>     let initial_balance = state.get_fee_token_balance(deploy_address, fee_token_address).unwrap();
> 
>     let charge_fee = deploy_account_tx.create_tx_info().enforce_fee();
> ```

Please revert to `charge_fee = true` in the rest of the file



_Code quote:_
```XML
    let charge_fee = deploy_account_tx.create_tx_info().enforce_fee();
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 307 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83ZO9fDGHwO5q0BZat:-O83ZO9fDGHwO5q0BZau:bmdz83g) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/transaction/test_utils.rs#L307)):*
> ```XML
>     let charge_fee = tx_context.tx_info.enforce_fee();
> 
>     account_invoke_tx(invoke_args).execute(state, block_context, charge_fee, true)
> ```

Please avoid calling twice to `account_invoke_tx`.



_Code quote:_
```XML
    let tx = account_invoke_tx(invoke_args.clone());
    let tx_context = Arc::new(block_context.to_tx_context(&tx));
    let charge_fee = tx_context.tx_info.enforce_fee();

    account_invoke_tx(invoke_args).execute(state, block_context, charge_fee, true)
```


<!-- Sent from Reviewable.io -->

2024-10-01 07:28 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 7 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 277 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83NouW74GH4Qmn4UeX:-O85vzlF36FF7VlxlVEv:baprbqe) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/concurrency/versioned_state_test.rs#L277)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that you can leave it true here and below. This flag is not relevant for this test.
</blockquote></details>

This test checks a flow that came from the gateway, right? In this case, charge_fee should always be equal to enforce_fee. Moreover, the test won't pass otherwise, as the resource_bounds are zero. If it also represents a flow of full node transactions, then I agree we should change the resource_bounds to a non-default one. 

On another note, we did change the behavior of transactions on the full node side. Now, if they send a transaction with charge_fee true and enforce_fee false, the transaction will fail   


<!-- Sent from Reviewable.io -->

2024-10-01 10:48 UTC, avivg-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 107 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83Mg5G7K-jiI4UN_tj:-O86f3za7LkX08hOFc7h:b7g1994) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/blockifier/transaction_executor.rs#L107)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider creating a method for `Transaction` and `AccountTransaction`
</blockquote></details>

Done, it included creating some getter funcs.

Also, i left in comment under my implementation a "match implementation" alternative that didn't work for me.  perhaps you'll have an idea? or better to leave as at is?  

Also, I trivially implemented for L1Handler, with enforce_fee() -> false (for all cases), under the assumption this is not supposed to be called, and if so- false is the desired behaviour. I'd love to ask some questions face to face about L1Handler. 


<!-- Sent from Reviewable.io -->

2024-10-01 11:15 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 3 of 15 files reviewed, 10 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 306 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86ku4w6vMuXRisDmO8:-O86ku4w6vMuXRisDmO9:bry9h3o) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/blockifier/src/transaction/account_transaction.rs#L306)):*
> ```XML
>         //     TransactionVersion::THREE => self.resource_bounds().max_possible_fee() > Fee(0)
>         // }
>     }
> ```

I think the suggestion was something like this, but it might be a better idea to move enforce_fee to be a function of transaction and not transaction info. If that is the change you'd like to make, please do it in a separate PR  



_Suggestion:_
```XML
    pub fn enforce_fee(&self) -> bool {
        self.create_tx_info().enforce_fee()
    }
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 67 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86lbWa4K4WATfWhYRf:-O86lbWa4K4WATfWhYRg:b-rkv67m) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/blockifier/src/transaction/transaction_execution.rs#L67)):*
> ```XML
>             Self::L1HandlerTransaction(tx) => tx.enforce_fee(),
>         }
>     }
> ```

I think this is better  



_Suggestion:_
```XML
    pub fn enforce_fee(&self) -> bool {
        match self {
            Self::AccountTransaction(tx) => tx.enforce_fee(),
            Self::L1HandlerTransaction(tx) => false,
        }
    }
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 605 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86lmRe9RAZYG6XEjvC:-O86lmRe9RAZYG6XEjvD:b-33b6k6) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/blockifier/src/transaction/transactions.rs#L605)):*
> ```XML
>         // AvivG: todo understand this
>         false
>     }
> ```

See comment above
___
*[`crates/starknet_api/src/executable_transaction.rs` line 197 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86jcsOEq7uhbeqYlUg:-O86jcsOEq7uhbeqYlUh:b-eng6e7) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/starknet_api/src/executable_transaction.rs#L197)):*
> ```XML
>         (version, TransactionVersion),
>         (resource_bounds, ValidResourceBounds),
>         (max_fee, Fee),
> ```

@ArniStarkware is against this getter. Is there a reason you need it? 
Anyway, I don't think it needs to be part of this PR 


<!-- Sent from Reviewable.io -->

2024-10-01 11:23 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 3 of 15 files reviewed, 10 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 67 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86lbWa4K4WATfWhYRf:-O86myv9BQsajtxZMoKd:byj7i7e) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/blockifier/src/transaction/transaction_execution.rs#L67)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think this is better
</blockquote></details>

Aviv, can you check if this function is needed? If L1Handler does not have max_fee, how did we handle it so far?
If it is needed, then maybe it is better to return an Option here, although an Option on a bool is ugly, so I'm not sure about it. 


<!-- Sent from Reviewable.io -->

2024-10-01 11:29 UTC, avivg-starkware commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 206 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83Yh61Du-ElEngDUu_:-O86pqZb6M4MSZd8ed0X:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/transaction/account_transactions_test.rs#L206)):*
> ```XML
>     .unwrap();
>     assert!(!tx_execution_info.is_reverted());
>     assert_eq!(tx_execution_info.receipt.fee, Fee(0));
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-01 11:30 UTC, ArniStarkware commented
*[`crates/starknet_api/src/executable_transaction.rs` line 197 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86jcsOEq7uhbeqYlUg:-O86psyvB7IKuq_msaL5:b6lxyvb) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/starknet_api/src/executable_transaction.rs#L197)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

@ArniStarkware is against this getter. Is there a reason you need it? 
Anyway, I don't think it needs to be part of this PR
</blockquote></details>

I am against it as it is of version lower than 3. Can the value be accessed manually? 


<!-- Sent from Reviewable.io -->

2024-10-01 11:47 UTC, avivg-starkware commented
*[`crates/blockifier/src/transaction/test_utils.rs` line 307 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83ZO9fDGHwO5q0BZat:-O86rOlL9WIMqlr8Mxo8:b-896fjb) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/transaction/test_utils.rs#L307)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please avoid calling twice to `account_invoke_tx`.
</blockquote></details>

Done 


<!-- Sent from Reviewable.io -->

2024-10-01 11:53 UTC, avivg-starkware commented
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 67 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86lbWa4K4WATfWhYRf:-O86ufrrCkfTz8eA7QiR:b-4oej34) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/blockifier/src/transaction/transaction_execution.rs#L67)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Aviv, can you check if this function is needed? If L1Handler does not have max_fee, how did we handle it so far?
If it is needed, then maybe it is better to return an Option here, although an Option on a bool is ugly, so I'm not sure about it.
</blockquote></details>

Yes thank you! Exactly what I was looking for. Done Done.


<!-- Sent from Reviewable.io -->

2024-10-01 12:28 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 1 of 15 files reviewed, 9 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 67 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O872R1eCacTahE5dVOr:-O872R1eCacTahE5dVOs:bsd0mj0) ([raw file](https://github.com/starkware-libs/sequencer/blob/b028f0d46a19dd2f960d3e27638371d8af907a30/crates/blockifier/src/transaction/transaction_execution.rs#L67)):*
> ```XML
>             Self::L1HandlerTransaction(_) => false,
>         }
>     }
> ```

Aviv, can you check if this function is needed? If L1Handler does not have max\_fee, how did we handle it so far?  
If it is needed, then maybe it is better to return an Option here, although an Option on a bool is ugly, so I'm not sure about it.



_Code quote:_
```XML
    pub fn enforce_fee(&self) -> bool {
        match self {
            Self::AccountTransaction(tx) => tx.enforce_fee(),
            Self::L1HandlerTransaction(_) => false,
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-10-01 12:29 UTC, avivg-starkware commented
*[`crates/starknet_api/src/executable_transaction.rs` line 197 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86jcsOEq7uhbeqYlUg:-O86vvzPBNzDSqSRzS9t:b29itra) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/starknet_api/src/executable_transaction.rs#L197)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I am against it as it is of version lower than 3. Can the value be accessed manually?
</blockquote></details>

I see, Thankyou for clarifying. 
I removed the macro getters then. 

I did however left the following funcs I added to starknet_api::transactions.rs 
as otherwise I'll have to address all those cases while trying to access the value manually.

Does this sound OK? Should I try finding a different way to implement this? 

thanks very very!



_Code snippet:_
```XML
impl DeclareTransaction {
    pub fn max_fee(&self) -> Fee {
        match self {
            Self::V0(tx) => tx.max_fee,
            Self::V1(tx) => tx.max_fee,
            Self::V2(tx) => tx.max_fee,
            // Aviv: i took this based on getters implementation for V3: resource_bounds. better
            // implementaion ?
            Self::V3(_) => panic!("do not support max_fee; only available for V0-V2 transactions."),
        }
    }
}

impl DeployAccountTransaction {
    pub fn max_fee(&self) -> Fee {
        match self {
            Self::V1(tx) => tx.max_fee,
            Self::V3(_) => panic!("do not support max_fee; only available for V0-V2 transactions."),
        }
    }
}

impl InvokeTransaction {
    pub fn max_fee(&self) -> Fee {
        match self {
            Self::V0(tx) => tx.max_fee,
            Self::V1(tx) => tx.max_fee,
            Self::V3(_) => panic!("do not support max_fee; only available for V0-V2 transactions."),
        }
    }
}
```


<!-- Sent from Reviewable.io -->

2024-10-01 12:39 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 1 of 15 files reviewed, 10 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 18 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O874mHU-2fcRx4dOG1t:-O874mHU-2fcRx4dOG1u:bpxgyr3) ([raw file](https://github.com/starkware-libs/sequencer/blob/b028f0d46a19dd2f960d3e27638371d8af907a30/crates/starknet_api/src/executable_transaction.rs#L18)):*
> ```XML
>     Calldata,
>     ContractAddressSalt,
>     Fee,
> ```

Remove this as well 


<!-- Sent from Reviewable.io -->

2024-10-01 12:42 UTC, avivg-starkware commented
*[`crates/blockifier/src/transaction/account_transaction.rs` line 305 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86wAx34iICbAj4OcOt:-O873Lkq5Bp1zkjECzIL:bbi2suv) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c923963478e826d45434ad22350810b5cead8ec/crates/blockifier/src/transaction/account_transaction.rs#L305)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It is a known issue with `TransactionVersion` See for example: `starknet_api::test_utils::declare::declare_tx`.

`TransactionVersion` is a struct (just a wrapper for `Felt`). Structs do not support match.
</blockquote></details>

Thank you!! explains my morning frustration.. :)  
(and fixed accordingly)


<!-- Sent from Reviewable.io -->

2024-10-01 12:46 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 1 of 15 files reviewed, 11 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 302 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O875K0rA7qkIGmFAC9J:-O875K0s0OoIgpPFbC4I:b-yhdaaa) ([raw file](https://github.com/starkware-libs/sequencer/blob/b028f0d46a19dd2f960d3e27638371d8af907a30/crates/blockifier/src/transaction/account_transaction.rs#L302)):*
> ```XML
>             // TransactionVersion::THREE =>
>             self.resource_bounds().max_possible_fee() > Fee(0)
>         }
> ```

WDYT? 



_Suggestion:_
```XML
    pub fn enforce_fee(&self) -> bool {
        let version = self.version();
        if version == TransactionVersion::THREE
        {
            self.resource_bounds().max_possible_fee() > Fee(0)
        } else {
            let max_fee = match self {
                Self::Declare(tx) => tx.tx().max_fee(),
                Self::DeployAccount(tx) => tx.tx().max_fee(),
                Self::Invoke(tx) => tx.tx().max_fee(),
            };
            max_fee != Fee(0)
            
        }
```


<!-- Sent from Reviewable.io -->

2024-10-01 12:58 UTC, avivg-starkware commented
*[`crates/blockifier/src/transaction/account_transaction.rs` line 302 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O875K0rA7qkIGmFAC9J:-O877k5a27EnCvvEmB9P:bmct3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/b028f0d46a19dd2f960d3e27638371d8af907a30/crates/blockifier/src/transaction/account_transaction.rs#L302)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

see my last version of this, this solution is cleaner, but assumes the version can't be different than 0-3. 
so perhaps it's better to catch if a "wrong" version is inputted?


<!-- Sent from Reviewable.io -->

2024-10-01 12:58 UTC, avivg-starkware commented
*[`crates/blockifier/src/transaction/account_transaction.rs` line 306 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86ku4w6vMuXRisDmO8:-O879FzQ3pcsVe0iQ16h:b-5fm4ax) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/blockifier/src/transaction/account_transaction.rs#L306)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think the suggestion was something like this, but it might be a better idea to move enforce_fee to be a function of transaction and not transaction info. If that is the change you'd like to make, please do it in a separate PR
</blockquote></details>

comment above


<!-- Sent from Reviewable.io -->

2024-10-01 13:06 UTC, meship-starkware requested changes
> Reviewed 1 of 12 files at r7, 1 of 1 files at r8, 2 of 4 files at r9, 3 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 14 of 15 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @avivg-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 4 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O879GYS9CmjRF8jd3Tm:-O879GYS9CmjRF8jd3Tn:b-n9zg9s) ([raw file](https://github.com/starkware-libs/sequencer/blob/527f5cd78e325d4446221569882a716d8259b63d/crates/blockifier/src/transaction/account_transactions_test.rs#L4)):*
> ```XML
> use std::sync::Arc;
> 
> use ark_ff::Zero;
> ```

Remove this? I think you added it accidentally 



_Code quote:_
```XML
use ark_ff::Zero;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2032 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O87AgCEDO2SyTUWfb6B:-O87AgCEDO2SyTUWfb6C:b-ykelxu) ([raw file](https://github.com/starkware-libs/sequencer/blob/527f5cd78e325d4446221569882a716d8259b63d/crates/blockifier/src/transaction/transactions_test.rs#L2032)):*
> ```XML
>     let value = calldata.0[2];
>     let payload_size = tx.payload_size();
>     let charge_fee = false; //AvivG : do we want enforce_fee impl for L1 handler?
> ```

I think it is best to revert the test to its previous state



_Suggestion:_
```XML
 let charge_fee = true;
```


<!-- Sent from Reviewable.io -->

2024-10-01 13:30 UTC, avivg-starkware commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 206 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83Yh61Du-ElEngDUu_:-O87BEgf163MKmz1Sc8v:b-neufqc) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/transaction/account_transactions_test.rs#L206)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

'tx_execution_info.receipt.fee.is_zero()' is not what we want to check. We want to check that fee_transfer_call_info is None. It might be better to change it in the last PR so a rebase won't override these changes
</blockquote></details>

I see my mistake. i did revert then.  "fee_transfer_info" does not appear for me, would you clarify what do you refer by that? 


<!-- Sent from Reviewable.io -->

2024-10-01 13:31 UTC, avivg-starkware commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 4 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O879GYS9CmjRF8jd3Tm:-O87GpycDa0BgxKhUXoz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/527f5cd78e325d4446221569882a716d8259b63d/crates/blockifier/src/transaction/account_transactions_test.rs#L4)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Remove this? I think you added it accidentally
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-01 13:44 UTC, avivg-starkware commented
*[`crates/starknet_api/src/executable_transaction.rs` line 18 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O874mHU-2fcRx4dOG1t:-O87Ji1A9EZ5GT6mHGv7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b028f0d46a19dd2f960d3e27638371d8af907a30/crates/starknet_api/src/executable_transaction.rs#L18)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Remove this as well
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-01 13:44 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 11 of 15 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2032 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O87AgCEDO2SyTUWfb6B:-O87Jmxp-qKz4ukDv9pJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/527f5cd78e325d4446221569882a716d8259b63d/crates/blockifier/src/transaction/transactions_test.rs#L2032)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think it is best to revert the test to its previous state
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-01 14:39 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 11 of 15 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @avivg-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 206 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83Yh61Du-ElEngDUu_:-O87W-Wl40b-_lL-CDwb:bgsu22f) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/transaction/account_transactions_test.rs#L206)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

I see my mistake. i did revert then.  "fee_transfer_info" does not appear for me, would you clarify what do you refer by that?
</blockquote></details>

I think its fee_transfer_call_info, and its not part of the receipt:
tx_execution_info.fee_transfer_call_info.


<!-- Sent from Reviewable.io -->

2024-10-01 14:40 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 11 of 15 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @avivg-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 67 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O872R1eCacTahE5dVOr:-O87WR0G7eTYYnNM9-HX:b-wbm355) ([raw file](https://github.com/starkware-libs/sequencer/blob/b028f0d46a19dd2f960d3e27638371d8af907a30/crates/blockifier/src/transaction/transaction_execution.rs#L67)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can you remove the function as well 


<!-- Sent from Reviewable.io -->

2024-10-01 14:43 UTC, meship-starkware reviewed
> Reviewed 2 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 13 of 15 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @avivg-starkware, and @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-01 14:43 UTC, meship-starkware reviewed
> Reviewed 1 of 4 files at r9, 1 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @avivg-starkware, and @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-04 06:24 UTC, noaov1 requested changes
> Reviewed 6 of 12 files at r7, 3 of 4 files at r9, 1 of 4 files at r10, 1 of 1 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 16 unresolved discussions (waiting on @ArniStarkware, @avivg-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 22 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8H7bUJ-hhCDTMxNXLG:-O8H7bUJ-hhCDTMxNXLH:b-n6d6dn) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/blockifier/stateful_validator.rs#L22)):*
> ```XML
> use crate::transaction::account_transaction::AccountTransaction;
> use crate::transaction::errors::{TransactionExecutionError, TransactionPreValidationError};
> // use crate::transaction::objects::TransactionInfoCreator;
> ```

Please remove



_Code quote:_
```XML
// use crate::transaction::objects::TransactionInfoCreator;
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 277 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83NouW74GH4Qmn4UeX:-O86SC6m48bvSYKkgmSt:b6s6kgv) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/concurrency/versioned_state_test.rs#L277)):*
> This test checks a flow that came from the gateway, right?

Not necessarily. It does not have to be aware of this behaviour IMO.
> the test won't pass otherwise, as the resource\_bounds are zero

I see. Note that an `enforce_fee` flag was already defined, you can use it (referenced above).  Worth documenting that we did not fund account 1, hence this behaviour. 
> On another note, we did change the behavior of transactions on the full node side

You are right,but it does not matter as the `enforce_fee` flag is an internal flag.
  
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 246 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8HAYlF1abZwB7VqIK-:-O8HAYlF1abZwB7VqIK0:b-ifeybi) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/concurrency/versioned_state_test.rs#L246)):*
> ```XML
>     );
>     let account_tx_1 = AccountTransaction::DeployAccount(deploy_account_tx_1);
>     let enforce_fee = account_tx_1.enforce_fee();
> ```

See here



_Code quote:_
```XML
let enforce_fee = account_tx_1.enforce_fee();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 282 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8HBymk02gsnT1izFzT:-O8HBymk02gsnT1izFzU:b-uhcgbh) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/concurrency/versioned_state_test.rs#L282)):*
> ```XML
>         s.spawn(move || {
>             let charge_fee_2 = account_tx_2.enforce_fee();
>             account_tx_2.execute(&mut state_2, &block_context_2, charge_fee_2, true).unwrap();
> ```

Since we fund the account and we set it's resources to be > 0



_Suggestion:_
```XML
            account_tx_2.execute(&mut state_2, &block_context_2, true, true).unwrap();
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 624 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83W41x28UohuRf69yb:-O8L4wzf4gjCdoArJMEA:b-ox23zx) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/execution/stack_trace_test.rs#L624)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert (see comment above)
</blockquote></details>

Never mind, I see that this test set the resources to zero, and does not care about the fee charge.
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 688 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83W82UBu8dkbVetChH:-O8L6CiK4lc_QC2BayzU:bks35iq) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/execution/stack_trace_test.rs#L688)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert
</blockquote></details>

Note that here we fund the account. For it to matter, we need to set the resource bounds to a non zero value. 
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 652 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8L74zW0TvD0hnopLjY:-O8L74zW0TvD0hnopLjZ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/execution/stack_trace_test.rs#L652)):*
> ```XML
>             validate_constructor: true,
>             ..Default::default()
>         });
> ```





_Suggestion:_
```XML
    let deploy_account_tx =
        create_account_tx_for_validate_test_nonce_0(FaultyAccountTxCreatorArgs {
            tx_type: TransactionType::DeployAccount,
            scenario: INVALID,
            class_hash,
           resource_bounds: max_l1_resource_bounds,
            validate_constructor: true,
            ..Default::default()
        });
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 306 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86ku4w6vMuXRisDmO8:-O8L7y5h9zXec7MZQT1V:b-omc2fl) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/blockifier/src/transaction/account_transaction.rs#L306)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

comment above
</blockquote></details>

Yes, that was my intention. I agree with @meship-starkware : please revert the changes in `transaction.rs`. We can consider it in a separate PR.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zhxDhBOksVHkDBf4r:-O8L8sHKDFOQIf4H8z3T:bcstdgm) ([raw file](https://github.com/starkware-libs/sequencer/blob/1233182cea21224303de0e6f6f9cf272e51dfd12/crates/blockifier/src/transaction/account_transactions_test.rs#L164)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@meship-starkware  you are right. This test can be removed.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zsXtc-eou3Bm8a3Tb:-O8L9QvuADz2MozGrMwX:bxuax88) ([raw file](https://github.com/starkware-libs/sequencer/blob/1233182cea21224303de0e6f6f9cf272e51dfd12/crates/blockifier/src/transaction/account_transactions_test.rs#L190)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I suggested a modification :)
</blockquote></details>

On second thought, it can be removed.
We should add such tests in the transaction executor (where we set the `fee_charge` flag to be the `enforce_fee` value (in a separate PR)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 604 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8LA9l31Ustsv5yUojU:-O8LA9l31Ustsv5yUojV:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/transaction/account_transactions_test.rs#L604)):*
> ```XML
>             max_fee: Fee(BALANCE),
>             ..Default::default()
>         });
> ```





_Suggestion:_
```XML
        create_account_tx_for_validate_test_nonce_0(FaultyAccountTxCreatorArgs {
            tx_type: TransactionType::DeployAccount,
            tx_version,
            scenario: INVALID,
            class_hash: faulty_account_feature_contract.get_class_hash(),
            max_fee: Fee(BALANCE),
            resource_bounds: max_l1_resourc [...]

2024-10-05 17:32 UTC, avivg-starkware commented
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 22 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8H7bUJ-hhCDTMxNXLG:-O8SiJ0g856QJCg0ua4C:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/blockifier/stateful_validator.rs#L22)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-06 08:26 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 10 of 15 files reviewed, 16 unresolved discussions (waiting on @ArniStarkware, @avivg-starkware, and @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-10-06 15:49 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 3 of 15 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 277 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83NouW74GH4Qmn4UeX:-O8WbXdA4YS5J9lsT_fT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/concurrency/versioned_state_test.rs#L277)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

> This test checks a flow that came from the gateway, right?

Not necessarily. It does not have to be aware of this behaviour IMO.
> the test won't pass otherwise, as the resource\_bounds are zero

I see. Note that an `enforce_fee` flag was already defined, you can use it (referenced above).  Worth documenting that we did not fund account 1, hence this behaviour. 
> On another note, we did change the behavior of transactions on the full node side

You are right,but it does not matter as the `enforce_fee` flag is an internal flag.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 282 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8HBymk02gsnT1izFzT:-O8WbZCh5dSkRSRCLRUt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/concurrency/versioned_state_test.rs#L282)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Since we fund the account and we set it's resources to be > 0
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 624 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83W41x28UohuRf69yb:-O8Si_1iAMewpKzZuuc8:ba6yz8) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/execution/stack_trace_test.rs#L624)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Never mind, I see that this test set the resources to zero, and does not care about the fee charge.
</blockquote></details>

OK thankyou
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 688 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83W82UBu8dkbVetChH:-O8Wtk_B4BFDEpdhx51F:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/execution/stack_trace_test.rs#L688)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note that here we fund the account. For it to matter, we need to set the resource bounds to a non zero value.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 206 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83Yh61Du-ElEngDUu_:-O8X-68R9PIiFgKcsWzt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/transaction/account_transactions_test.rs#L206)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think its fee_transfer_call_info, and its not part of the receipt:
tx_execution_info.fee_transfer_call_info.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 615 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O83Z1NYE4DO_aBSxbAx:-O8X-LhEETLy07ozCmjM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b0018270b578a7219eed3bdabe810554e9ce72b/crates/blockifier/src/transaction/account_transactions_test.rs#L615)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert to `charge_fee = true` in the rest of the file
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 604 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8LA9l31Ustsv5yUojU:-O8WuGAI0hO4b6ISnOVA:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/transaction/account_transactions_test.rs#L604)):*
> ```XML
>             max_fee: Fee(BALANCE),
>             ..Default::default()
>         });
> ```

Done
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 944 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8LANQ_1jMSj-CDPqrT:-O8X-YS8CyXfWMTiaBK_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/transaction/account_transactions_test.rs#L944)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same in the entire file
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 785 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8LBoNL8OL5uYCM7AUK:-O8XMfKyC7VirKPoo23l:bwjry) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/transaction/transactions_test.rs#L785)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please consider reverting the changes in this file
</blockquote></details>

I've reverted most, 

I changed to  the code below as this is used 9 times, I though it's clearer with having the comment just once. WDYT? better to change in all places to 'false' (instead of 'default_charge_fee') ?



_Code snippet:_
```XML
fn test_validate_accounts_tx
...
// Do not charge fee as all tx has default resource bounds, account is not funded (bounds=0).
    let default_charge_fee = false;
```


<!-- Sent from Reviewable.io -->

2024-10-06 15:51 UTC, avivg-starkware commented
*[`crates/blockifier/src/transaction/account_transaction.rs` line 306 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O86ku4w6vMuXRisDmO8:-O8XWjObCdiyO3vI6tA_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0fe5f2c9ea3ee5452177b7d87286a0444b033df/crates/blockifier/src/transaction/account_transaction.rs#L306)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes, that was my intention. I agree with @meship-starkware : please revert the changes in `transaction.rs`. We can consider it in a separate PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-06 16:02 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 3 of 15 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zhxDhBOksVHkDBf4r:-O8XX6-n2-J8cZdSN5xz:blsqold) ([raw file](https://github.com/starkware-libs/sequencer/blob/1233182cea21224303de0e6f6f9cf272e51dfd12/crates/blockifier/src/transaction/account_transactions_test.rs#L164)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@meship-starkware  you are right. This test can be removed.
</blockquote></details>

Done (deleted test)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O6zsXtc-eou3Bm8a3Tb:-O8XXWD6DNbsGDJ11VPm:blsqold) ([raw file](https://github.com/starkware-libs/sequencer/blob/1233182cea21224303de0e6f6f9cf272e51dfd12/crates/blockifier/src/transaction/account_transactions_test.rs#L190)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

On second thought, it can be removed.
We should add such tests in the transaction executor (where we set the `fee_charge` flag to be the `enforce_fee` value (in a separate PR)
</blockquote></details>

Done (deleted test)
___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 118 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8LBOOz6eiB6YhgIRGQ:-O8XXpU-7CKbHqi7gYIJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bafb0268527d92cfde68086954eb9a829e7b8fde/crates/blockifier/src/transaction/post_execution_test.rs#L118)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-07 10:51 UTC, avivg-starkware commented
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 67 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O872R1eCacTahE5dVOr:-O8aXwnb6TtnywjXVQhy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b028f0d46a19dd2f960d3e27638371d8af907a30/crates/blockifier/src/transaction/transaction_execution.rs#L67)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

can you remove the function as well
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-07 14:16 UTC, meship-starkware requested changes
> Reviewed 5 of 12 files at r15, 8 of 8 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 12 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 123 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8bKSLH8A9LPdJNYUYB:-O8bKSLH8A9LPdJNYUYC:b-q4xlmf) ([raw file](https://github.com/starkware-libs/sequencer/blob/e984e79d3ce23b57de7127441987d5423de461b5/crates/blockifier/src/transaction/post_execution_test.rs#L123)):*
> ```XML
>     });
>     let tx_info = approve_tx.create_tx_info();
> ```

Revert this file change


<!-- Sent from Reviewable.io -->

2024-10-07 15:39 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 12 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 123 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8bKSLH8A9LPdJNYUYB:-O8bcEQc24D5X66Z-iQA:b-asez70) ([raw file](https://github.com/starkware-libs/sequencer/blob/e984e79d3ce23b57de7127441987d5423de461b5/crates/blockifier/src/transaction/post_execution_test.rs#L123)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Revert this file change
</blockquote></details>

you mean to remove this? 

It is used later in line 154



_Code snippet:_
```XML
let tx_info = approve_tx.create_tx_info();
...
// Check the current balance, before next transaction.
let (balance, _) = state
    .get_fee_token_balance(account_address, chain_info.fee_token_address(&tx_info.fee_type()))
    .unwrap();
```


<!-- Sent from Reviewable.io -->

2024-10-08 05:42 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 12 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 123 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8bKSLH8A9LPdJNYUYB:-O8ec_716eqoJGz4058Y:b-mlaosd) ([raw file](https://github.com/starkware-libs/sequencer/blob/e984e79d3ce23b57de7127441987d5423de461b5/crates/blockifier/src/transaction/post_execution_test.rs#L123)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

you mean to remove this? 

It is used later in line 154
</blockquote></details>

When I look at the changes in this file, I see that you just added a space. I meant removing the space between let tx_info= and let approval_execution_info = 


<!-- Sent from Reviewable.io -->

2024-10-08 12:45 UTC, meship-starkware reviewed
> Reviewed 5 of 7 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 14 of 15 files reviewed, 11 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-09 12:18 UTC, meship-starkware reviewed
> Reviewed 5 of 6 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 13 of 15 files reviewed, 11 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-09 12:19 UTC, meship-starkware approved these changes
> Reviewed 1 of 7 files at r18, 1 of 6 files at r20.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 11 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-10 13:01 UTC, meship-starkware approved these changes
> Reviewed 6 of 6 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 11 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-10 14:31 UTC, avivg-starkware reviewed
python PR: 
https://github.com/starkware-industries/starkware/pull/36055

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793#-:-O8qpm4z2Fhd9eXGwGuO:bs0wp4p)* status: all files reviewed, 11 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-10 16:09 UTC, noaov1 approved these changes
> Reviewed 2 of 12 files at r15, 1 of 8 files at r17, 2 of 7 files at r18, 1 of 6 files at r20, 5 of 6 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 280 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8r7APV1yMgETGtpHpi:-O8r7APV1yMgETGtpHpj:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/421180755999c4a937f0a4d9024e9612e2702977/crates/blockifier/src/concurrency/versioned_state_test.rs#L280)):*
> ```XML
>         s.spawn(move || {
>             let result = account_tx_1.execute(&mut state_1, &block_context_1, false, true); // Do not charge fee as account is not funded.
>             assert_eq!(result.is_err(), enforce_fee);
> ```





_Suggestion:_
```XML
    thread::scope(|s| {
        s.spawn(move || {
            let result = account_tx_1.execute(&mut state_1, &block_context_1, enforce_fee, true);
            assert_eq!(result.is_err(), enforce_fee); // Transaction fails iff we enforced the fee charge (as the acount is not funded).
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1766 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8rAYIK42okb87Yk4ms:-O8rAYIK42okb87Yk4mt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/421180755999c4a937f0a4d9024e9612e2702977/crates/blockifier/src/transaction/transactions_test.rs#L1766)):*
> ```XML
>     });
>     // Do not charge fee as all tx has default resource bounds, account is not funded (bounds=0).
>     let default_charge_fee = false;
> ```





_Suggestion:_
```XML
    // We test `__validate__`, and don't care about the cahrge fee flow.
    let charge_fee = false;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2059 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/793#-O8rAsYeDEw8QF3TiQzl:-O8rAsYeDEw8QF3TiQzm:b-yprtry) ([raw file](https://github.com/starkware-libs/sequencer/blob/421180755999c4a937f0a4d9024e9612e2702977/crates/blockifier/src/transaction/transactions_test.rs#L2059)):*
> ```XML
>     let value = calldata.0[2];
>     let payload_size = tx.payload_size();
>     let actual_execution_info = tx.execute(state, block_context, false, true).unwrap(); // Do not charge fee as L1Handler's resource bounds (/max fee) is 0.
> ```

@avivg-starkware not that this is temporary. We will need to preserve the l1 handler behaviour without requiring the caller of `execute` to specify false in charge fee (separate PR).



_Code quote:_
```XML
    let actual_execution_info = tx.execute(state, block_context, false, true).unwrap(); // Do not charge fee as L1Handler's resource bounds (/max fee) is 0.
```


<!-- Sent from Reviewable.io -->

2024-10-10 16:09 UTC, noaov1 approved these changes
> Reviewed 1 of 12 files at r15, 1 of 6 files at r21.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)



<!-- Sent from Reviewable.io -->

2024-10-13 05:05 UTC, meship-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)



<!-- Sent from Reviewable.io -->

2024-10-13 15:16 UTC, avivg-starkware reviewed
> Reviewed 1 of 4 files at r9, 1 of 3 files at r12, 2 of 12 files at r15, 1 of 7 files at r18, 10 of 10 files at r23.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @avivg-starkware)



<!-- Sent from Reviewable.io -->

2024-10-13 19:21 UTC, avivg-starkware reviewed
> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/793)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)



<!-- Sent from Reviewable.io -->

2024-10-13 19:22 UTC, merged