fix(blockifier): l1 to l2 gas price ratio
starkware-libs/sequencer pull request #815
Opened 2024-09-16 12:54 UTC by aner-starkware

2024-09-16 13:06 UTC, nimrod-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uuZgTAW9OFZoPbtLZ:-O6uuZgTAW9OFZoPbtL_:bh5l27i) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L130)):*
> ```XML
> 
>     /// Converts from L1 gas price to L2 gas price **rounding towards zero**.
>     pub fn convert_l1_to_l2_gas_price(&self, l1_gas: u128) -> u128 {
> ```

l1_gas_price



_Code quote:_
```XML
l1_gas
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uubwR4YHI8BHLkk-7:-O6uubwR4YHI8BHLkk-8:brf1fbn) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L135)):*
> ```XML
> 
>     /// Converts from L1 gas amount to L2 gas amount with **upward rounding**.
>     pub fn convert_l1_to_l2_gas_amount(&self, l1_gas: u128) -> u128 {
> ```

l1_gas_amount



_Code quote:_
```XML
l1_gas
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uvqvfCsA1oHsnxdQX:-O6uvqvfCsA1oHsnxdQY:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L137)):*
> ```XML
>     pub fn convert_l1_to_l2_gas_amount(&self, l1_gas: u128) -> u128 {
>         let l1_to_l2_gas_price_ratio = self.l1_to_l2_gas_price_ratio().inv();
>         *(l1_to_l2_gas_price_ratio * l1_gas).ceil().numer()
> ```





_Suggestion:_
```XML
       *(self.l1_to_l2_gas_price_ratio().inv() * l1_gas).ceil().numer()
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uufErBa6rBdgQgNkB:-O6uufErBa6rBdgQgNkC:b-ck9uc1) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L141)):*
> ```XML
> 
>     /// Converts from L2 gas price to L1 gas price with **upward rounding**.
>     pub fn convert_l2_to_l1_gas_price(&self, l2_gas: u128) -> u128 {
> ```

l2_gas_price



_Code quote:_
```XML
l2_gas
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uuiatCGzaVYhFjasv:-O6uuiatCGzaVYhFjasw:btjw46q) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L146)):*
> ```XML
> 
>     /// Converts from L2 gas amount to L1 gas amount **rounding towards zero**.
>     pub fn convert_l2_to_l1_gas_amount(&self, l2_gas: u128) -> u128 {
> ```

l2_gas_amount



_Code quote:_
```XML
l2_gas
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uwDXVBPsk-_ZPhESy:-O6uwDXVBPsk-_ZPhESz:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L148)):*
> ```XML
>     pub fn convert_l2_to_l1_gas_amount(&self, l2_gas: u128) -> u128 {
>         let l2_to_l1_gas_amount_ratio = self.l1_to_l2_gas_price_ratio();
>         (l2_to_l1_gas_amount_ratio * l2_gas).to_integer()
> ```





_Suggestion:_
```XML
        (self.l1_to_l2_gas_price_ratio() * l2_gas).to_integer()
```


<!-- Sent from Reviewable.io -->

2024-09-16 13:29 UTC, nimrod-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6v0YOG1HXUTcIkeS_H:-O6v0YOG1HXUTcIkeS_I:b-89dbs8) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/fee/fee_test.rs#L163)):*
> ```XML
>         VersionedConstants::latest_constants()
>             //TODO!(Aner): fix test parameters to allow using `gas_price` here!
>             .convert_l1_to_l2_gas_price(DEFAULT_STRK_L1_GAS_PRICE)
> ```

Shouldn't it round upwards? and always be >= 1



_Code quote:_
```XML
DEFAULT_STRK_L1_GAS_PRICE
```


<!-- Sent from Reviewable.io -->

2024-09-16 13:54 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uuZgTAW9OFZoPbtLZ:-O6v4kFd2f-jkUuw7FyE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L130)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

l1_gas_price
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uubwR4YHI8BHLkk-7:-O6v4kXZ96agcDlKDa4q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L135)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

l1_gas_amount
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uvqvfCsA1oHsnxdQX:-O6v4lf-Aiu2J123q8E-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L137)):*
> ```XML
>     pub fn convert_l1_to_l2_gas_amount(&self, l1_gas: u128) -> u128 {
>         let l1_to_l2_gas_price_ratio = self.l1_to_l2_gas_price_ratio().inv();
>         *(l1_to_l2_gas_price_ratio * l1_gas).ceil().numer()
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uufErBa6rBdgQgNkB:-O6v4mtf1jyDSXQAI7T3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L141)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

l2_gas_price
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uuiatCGzaVYhFjasv:-O6v4nw85OCOBo79iH4-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L146)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

l2_gas_amount
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6uwDXVBPsk-_ZPhESy:-O6v59UI1mh0pXruSVrc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/versioned_constants.rs#L148)):*
> ```XML
>     pub fn convert_l2_to_l1_gas_amount(&self, l2_gas: u128) -> u128 {
>         let l2_to_l1_gas_amount_ratio = self.l1_to_l2_gas_price_ratio();
>         (l2_to_l1_gas_amount_ratio * l2_gas).to_integer()
> ```

Done.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6v0YOG1HXUTcIkeS_H:-O6v5Y590EADRz6j3S4W:b-g2emxv) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/fee/fee_test.rs#L163)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Shouldn't it round upwards? and always be >= 1
</blockquote></details>

@dorimedini-starkware ?


<!-- Sent from Reviewable.io -->

2024-09-17 07:36 UTC, nimrod-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6yu34p2c0cvCMng_Ih:-O6yu34p2c0cvCMng_Ii:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a8e89c1041a93346744978125d57d3ca6975ff1/crates/blockifier/src/versioned_constants.rs#L147)):*
> ```XML
>     /// Converts from L2 gas amount to L1 gas amount **rounding towards zero**.
>     pub fn convert_l2_to_l1_gas_amount(&self, l2_gas_amount: u128) -> u128 {
>         // amount ratio is the inverse of the price ratio
> ```





_Suggestion:_
```XML
// The amount ratio is the inverse of the price ratio.
```


<!-- Sent from Reviewable.io -->

2024-09-17 08:19 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6yu34p2c0cvCMng_Ih:-O6z3DtS4KqF5THKALBc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a8e89c1041a93346744978125d57d3ca6975ff1/crates/blockifier/src/versioned_constants.rs#L147)):*
> ```XML
>     /// Converts from L2 gas amount to L1 gas amount **rounding towards zero**.
>     pub fn convert_l2_to_l1_gas_amount(&self, l2_gas_amount: u128) -> u128 {
>         // amount ratio is the inverse of the price ratio
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-17 11:23 UTC, dorimedini-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6v0YOG1HXUTcIkeS_H:-O6zhWdqBK9FsC9bJcFW:bspnhsd) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/fee/fee_test.rs#L163)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware ?
</blockquote></details>

1. all gas prices must be positive (nonzero), because we sometimes divide by gas price; but the type of the gas prices is `NonZeroU128` so the `unwrap` will catch zero values and panic, so all good.
2. this is a test so I don't think it really matters, but in general I think you are right - if the value of one unit of L1 gas is `X` ETH, and we want to convert it to `Y` STRK, then `Y` STRK should be *worth at least* `X` ETH (i.e. no discount when converting)


<!-- Sent from Reviewable.io -->

2024-09-18 11:34 UTC, dorimedini-starkware requested changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O73tiYq-igJp2zpJoGj:-O73tiYr5PyWTS1p2qF1:bhbsw49) ([raw file](https://github.com/starkware-libs/sequencer/blob/52bacc57c292a5f7db6cb598e583954b60eb5ed2/crates/blockifier/src/fee/actual_cost_test.rs#L81)):*
> ```XML
>                     * eth_gas_constants::WORD_WIDTH
>                     + class_info.abi_length(),
>             ));
> ```

you are currently calling `convert_l2_to_l1_gas_amount_round_up` with an input of "number of bytes", not "gas amount".



_Suggestion:_
```XML
        let code_gas_cost = versioned_constants.convert_l2_to_l1_gas_amount_round_up(
            versioned_constants.archival_data_gas_costs.gas_per_code_byte
            * u128_from_usize(
                (class_info.bytecode_length() + class_info.sierra_program_length())
                    * eth_gas_constants::WORD_WIDTH
                    + class_info.abi_length(),
            ));
```
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 116 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O73tvhTDjfA-hgCFedo:-O73tvhTDjfA-hgCFedp:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/52bacc57c292a5f7db6cb598e583954b60eb5ed2/crates/blockifier/src/fee/actual_cost_test.rs#L116)):*
> ```XML
>             * versioned_constants.convert_l2_to_l1_gas_amount_round_up(u128_from_usize(
>                 calldata_length + signature_length,
>             ));
> ```

see above



_Suggestion:_
```XML
    let calldata_and_signature_gas_cost =versioned_constants.convert_l2_to_l1_gas_amount_round_up(
        versioned_constants.archival_data_gas_costs.gas_per_data_felt
            * u128_from_usize(
                calldata_length + signature_length,
            ));
```
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O73u-gEAwX3bK8SUbFw:-O73u-gEAwX3bK8SUbFx:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/52bacc57c292a5f7db6cb598e583954b60eb5ed2/crates/blockifier/src/fee/actual_cost_test.rs#L151)):*
> ```XML
>             * versioned_constants.convert_l2_to_l1_gas_amount_round_up(u128_from_usize(
>                 l1_handler_payload_size + signature_length,
>             ));
> ```

see above



_Suggestion:_
```XML
    let calldata_and_signature_gas_cost =versioned_constants.convert_l2_to_l1_gas_amount_round_up(
        versioned_constants.archival_data_gas_costs.gas_per_data_felt
            * u128_from_usize(
                l1_handler_payload_size + signature_length,
            ));
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 162 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O73uBIG5R8FdXUnxY0P:-O73uBIG5R8FdXUnxY0Q:bwcklvx) ([raw file](https://github.com/starkware-libs/sequencer/blob/52bacc57c292a5f7db6cb598e583954b60eb5ed2/crates/blockifier/src/fee/fee_test.rs#L162)):*
> ```XML
>             .unwrap(),
>         VersionedConstants::latest_constants()
>             //TODO!(Aner): fix test parameters to allow using `gas_price` here!
> ```

what is this TODO for?



_Code quote:_
```XML
//TODO!(Aner): fix test parameters to allow using `gas_price` here!
```


<!-- Sent from Reviewable.io -->

2024-09-18 11:56 UTC, aner-starkware commented
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O73tiYq-igJp2zpJoGj:-O73z9pDBxZuirUoglNQ:bb1x5r2) ([raw file](https://github.com/starkware-libs/sequencer/blob/52bacc57c292a5f7db6cb598e583954b60eb5ed2/crates/blockifier/src/fee/actual_cost_test.rs#L81)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are currently calling `convert_l2_to_l1_gas_amount_round_up` with an input of "number of bytes", not "gas amount".
</blockquote></details>

You're right. The issue is that the "gas amount" is a ratio, so it doesn't fit the input type. Should I round it twice? If so, should I round up both times?


<!-- Sent from Reviewable.io -->

2024-09-18 12:03 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 162 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O73uBIG5R8FdXUnxY0P:-O74-sZ71YZAU9DzUrx1:b-94teza) ([raw file](https://github.com/starkware-libs/sequencer/blob/52bacc57c292a5f7db6cb598e583954b60eb5ed2/crates/blockifier/src/fee/fee_test.rs#L162)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what is this TODO for?
</blockquote></details>

The test needs a refactoring.


<!-- Sent from Reviewable.io -->

2024-09-19 07:09 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O73tiYq-igJp2zpJoGj:-O786-uJ9zAGoSdBPfo9:biht3uk) ([raw file](https://github.com/starkware-libs/sequencer/blob/52bacc57c292a5f7db6cb598e583954b60eb5ed2/crates/blockifier/src/fee/actual_cost_test.rs#L81)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

You're right. The issue is that the "gas amount" is a ratio, so it doesn't fit the input type. Should I round it twice? If so, should I round up both times?
</blockquote></details>

hmm... perhaps the `convert_` functions should accept Ratios as input?


<!-- Sent from Reviewable.io -->

2024-09-22 14:06 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 9 unresolved discussions (waiting on @aner-starkware and @nimrod-starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_1.json` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OnoFw14TuWM6uA1kR:-O7P2Pr55A-XWQM72Een:b-psnicu) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/resources/versioned_constants_13_1.json#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is not equal to `archival_data_gas_costs["gas_per_code_byte"] * 0.000025`; please check if `deprecated_l2_resource_gas_costs` exists on `main-v0.13.1` (in the blockifier repo).
If it didn't exist, please set these values to zero (`[0, 1]` ratio),
and if it did, @Yoni-Starkware please advise?
</blockquote></details>

what was the value here on `main-v0.13.1`? (blockifier repo)
___
*[`crates/blockifier/resources/versioned_constants_13_2.json` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OoEirA_etBU4P5nEG:-O7P2YiZ1iGLqv2ESxlX:b-psnicu) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/resources/versioned_constants_13_2.json#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above - check `main-v0.13.2` (in the sequencer repo this time)
where did 35000 come from? the old values in Nimrod's PR?
</blockquote></details>

what was the value here on `main-v0.13.1`? (blockifier repo)
___
*[`crates/blockifier/resources/versioned_constants_13_2_1.json` line 22 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7P2_Jm5G92jnNNwsCH:-O7P2_Jm5G92jnNNwsCI:bwgjaxk) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bbcc87bf230d1a741d37ff7728673d2f8e64be4/crates/blockifier/resources/versioned_constants_13_2_1.json#L22)):*
> ```JSON
>         ],
>         "gas_per_code_byte": [
>             875,
> ```

what was the value here on `main-v0.13.2`? (sequencer repo)



_Code quote:_
```JSON
 875,
```


<!-- Sent from Reviewable.io -->

2024-09-23 05:43 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 14 of 17 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 29 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OnPnFAwkonOJzmyVz:-O7OtbqdAdYNM7tBCvOO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/resources/versioned_constants_13_0.json#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these values need to be equal to the `archival` values, times 40000 (inverse of 0.000025, the L1<>L2 ratio).
the reason you need values to appear at all, is for backward-compatibility - you need to be able to load old VC values (in 0.13.0 there were no such costs, neither for L1 nor L2), with the new VC struct.
</blockquote></details>

Done.
___
*[`crates/blockifier/resources/versioned_constants_13_1.json` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OnoFw14TuWM6uA1kR:-O7OsHtv6FcHiDiaP9Qg:b-2l9nok) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/resources/versioned_constants_13_1.json#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is not equal to `archival_data_gas_costs["gas_per_code_byte"] * 0.000025`; please check if `deprecated_l2_resource_gas_costs` exists on `main-v0.13.1` (in the blockifier repo).
If it didn't exist, please set these values to zero (`[0, 1]` ratio),
and if it did, @Yoni-Starkware please advise?
</blockquote></details>

There exists a "miligas per code byte", which is equal to 875.
___
*[`crates/blockifier/resources/versioned_constants_13_2.json` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OoEirA_etBU4P5nEG:-O7OsD0U5nLkzEgQ_mpv:b-704awg) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/resources/versioned_constants_13_2.json#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what was the value here on `main-v0.13.1`? (blockifier repo)
</blockquote></details>

Exists. Equal to 875. (31.2 Sequencer repo)
___
*[`crates/blockifier/src/blockifier/block.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OmdxG4Fj4QKLv6xgM:-O7OpMhn0soL6AhCBHH0:bnivzs) ([raw file](https://github.com/starkware-libs/sequencer/blob/69e953aab5109f625393502f725e4cbff6274156/crates/blockifier/src/blockifier/block.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this (and below todo) is waiting for which change?
</blockquote></details>

Requires a refactoring of a test that doesn't pass.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O6v0YOG1HXUTcIkeS_H:-O7OyQVV2-oUPKQOroq4:b-pmualt) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb09c42f95c03f941bf0843d81469f4897e0b021/crates/blockifier/src/fee/fee_test.rs#L163)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. all gas prices must be positive (nonzero), because we sometimes divide by gas price; but the type of the gas prices is `NonZeroU128` so the `unwrap` will catch zero values and panic, so all good.
2. this is a test so I don't think it really matters, but in general I think you are right - if the value of one unit of L1 gas is `X` ETH, and we want to convert it to `Y` STRK, then `Y` STRK should be *worth at least* `X` ETH (i.e. no discount when converting)
</blockquote></details>

Changed to rounding up, as agreed.
___
*[`Cargo.lock` line 9793 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7On6KH5Ckd4tyDRwKr:-O7Ox1aCEcmsup0IweBS:by4yq57) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/Cargo.lock#L9793)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where did this change come from...? please revert it
</blockquote></details>

It's added automatically when I run `cargo test`


<!-- Sent from Reviewable.io -->

2024-09-23 05:44 UTC, aner-starkware commented
*[`crates/blockifier/resources/versioned_constants_13_2_1.json` line 22 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7P2_Jm5G92jnNNwsCH:-O7SOy1u-aCftWtVYPS8:bl24r6c) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bbcc87bf230d1a741d37ff7728673d2f8e64be4/crates/blockifier/resources/versioned_constants_13_2_1.json#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what was the value here on `main-v0.13.2`? (sequencer repo)
</blockquote></details>

This file doesn't exist, I guess.


<!-- Sent from Reviewable.io -->

2024-09-23 05:45 UTC, aner-starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 294 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OmbD9CBgxDim79TPm:-O7SPEvE9j3Ug1QPwrRa:bbox33z) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/src/versioned_constants.rs#L294)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this still relevant? `ResourceCost` is a rational number
</blockquote></details>

@barak-b-starkware ?


<!-- Sent from Reviewable.io -->

2024-09-23 05:45 UTC, aner-starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 299 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OmYpX5-bv7srS2sU4:-O7SPHtMBbS4aokiuogg:bcvdxkx) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/src/versioned_constants.rs#L299)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this still relevant? `ResourceCost` is a rational number
</blockquote></details>

@avi-starkware ?


<!-- Sent from Reviewable.io -->

2024-09-23 05:53 UTC, aner-starkware commented
*[`crates/blockifier/src/transaction/objects.rs` line 371 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7Om74g21LHN3xZw8HZ:-O7SQXwpCi66UZKxGryf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3f8a6b8a04f7436cde31b704b84611235866bd6b/crates/blockifier/src/transaction/objects.rs#L371)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in the below functions: why not keep the API with `versioned_constants`, and add a `mode` input?
seems more abstract that way
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-23 07:23 UTC, aner-starkware commented
*[`crates/blockifier/resources/versioned_constants_13_1.json` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OnoFw14TuWM6uA1kR:-O7SkNL204KsHm3l6qKZ:b-15kauz) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/resources/versioned_constants_13_1.json#L24)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

There exists a "miligas per code byte", which is equal to 875.
</blockquote></details>

(It's a u128, not a Ratio)


<!-- Sent from Reviewable.io -->

2024-09-23 07:57 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 3 files at r12, 1 of 1 files at r13, 3 of 3 files at r14, all commit messages.
> Dismissed @nimrod-starkware from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 7 unresolved discussions (waiting on @aner-starkware, @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_1.json` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OnoFw14TuWM6uA1kR:-O7Sii3G3x2XrOtPhcM7:bxw62f6) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/resources/versioned_constants_13_1.json#L24)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

(It's a u128, not a Ratio)
</blockquote></details>

@Yoni-Starkware is the value from the tip of `main-v0.13.1` the correct value?
or did something change here on 0.13.1.1?
___
*[`crates/blockifier/resources/versioned_constants_13_2_1.json` line 22 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7P2_Jm5G92jnNNwsCH:-O7SjFpt7jSvTF_sWa4r:b-wm36zr) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bbcc87bf230d1a741d37ff7728673d2f8e64be4/crates/blockifier/resources/versioned_constants_13_2_1.json#L22)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This file doesn't exist, I guess.
</blockquote></details>

ah, on `main-v0.13.2` it should just be `versioned_constants.json` (the latest). what is the value there?
___
*[`crates/blockifier/src/versioned_constants.rs` line 294 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OmbD9CBgxDim79TPm:-O7SjRgyBQhbt-L3cd3W:b-f1dpbo) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/src/versioned_constants.rs#L294)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

@barak-b-starkware ?
</blockquote></details>

well, it's deleted code now... still relevant?
___
*[`crates/blockifier/src/versioned_constants.rs` line 299 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OmYpX5-bv7srS2sU4:-O7SjUoY5TEbPLBvEsYn:b-f1dpbo) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/src/versioned_constants.rs#L299)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

@avi-starkware ?
</blockquote></details>

well, it's deleted code now... still relevant?
___
*[`crates/blockifier/src/blockifier/block.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OmdxG4Fj4QKLv6xgM:-O7SsSok8RheKRtY73pM:bfcj9as) ([raw file](https://github.com/starkware-libs/sequencer/blob/69e953aab5109f625393502f725e4cbff6274156/crates/blockifier/src/blockifier/block.rs#L54)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Requires a refactoring of a test that doesn't pass.
</blockquote></details>

so please update the todo(s) to point to the problematic test, so it's easy to know in the future if this todo is complete / ready to do or not
___
*[`crates/blockifier/src/transaction/objects.rs` line 363 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7SjeRS9txu4GEEYLHz:-O7SjeRS9txu4GEEYLI-:b-iede43) ([raw file](https://github.com/starkware-libs/sequencer/blob/f26dfd83dae1a94f7c8ff3ff60db9120693f3930/crates/blockifier/src/transaction/objects.rs#L363)):*
> ```XML
>             // Cost in L1 gas.
>             GasVectorComputationMode::NoL2Gas => GasVector::from_l1_gas(data_costs.iter().sum()),
>         }
> ```

sorry for the flipping, but... I don't think the `get_..._cost` functions should return integers.
they should return gas vectors, because they are computing gas amounts...
please
1. refactor the `get_..._cost` functions to return a `GasVector`
2. rename them to `get_..._gas_cost`

and then the code here can look like this (`Add` is implemented on `GasVector`):



_Suggestion:_
```XML
        [
            self.get_calldata_and_signature_gas_cost(versioned_constants, mode),
            self.get_code_gas_cost(versioned_constants, mode),
            self.get_events_gas_cost(versioned_constants, mode),
        ].iter().sum()
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 381 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7SkbpW0bv4RnmlcePm:-O7SkbpW0bv4RnmlcePn:bqhshnv) ([raw file](https://github.com/starkware-libs/sequencer/blob/f26dfd83dae1a94f7c8ff3ff60db9120693f3930/crates/blockifier/src/transaction/objects.rs#L381)):*
> ```XML
>             GasVectorComputationMode::NoL2Gas => {
>                 versioned_constants.deprecated_l2_resource_gas_costs.gas_per_data_felt
>             }
> ```

this `match` logic is duplicated several times; please implement a `get_l2_resource_gas_costs(&self, mode:  &GasVectorComputationMode) -> &ArchivalDataGasCosts` function on `VersionedConstants` and use it 3 times (the struct type of `archival_data_gas_costs` and `deprecated_l2_resource_gas_costs` is the same type, right?)



_Code quote:_
```XML
            GasVectorComputationMode::All => {
                versioned_constants.archival_data_gas_costs.gas_per_data_felt
            }
            GasVectorComputationMode::NoL2Gas => {
                versioned_constants.deprecated_l2_resource_gas_costs.gas_per_data_felt
            }
```
___
*[`Cargo.lock` line 9793 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7On6KH5Ckd4tyDRwKr:-O7Sl58DB1RbNjmCIUCm:bpd23eu) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/Cargo.lock#L9793)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It's added automatically when I run `cargo test`
</blockquote></details>

strange... happens to me too, on `main`...
please don't commit this change, I'll talk to Gilad


<!-- Sent from Reviewable.io -->

2024-09-23 08:01 UTC, aner-starkware commented
*[`crates/blockifier/resources/versioned_constants_13_2_1.json` line 22 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7P2_Jm5G92jnNNwsCH:-O7StRwp1Y6ImcD0JAPv:b32vc4) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bbcc87bf230d1a741d37ff7728673d2f8e64be4/crates/blockifier/resources/versioned_constants_13_2_1.json#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, on `main-v0.13.2` it should just be `versioned_constants.json` (the latest). what is the value there?
</blockquote></details>

32


<!-- Sent from Reviewable.io -->

2024-09-23 08:15 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware, @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`Cargo.lock` line 9793 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7On6KH5Ckd4tyDRwKr:-O7SwmCPBTcZ_7Ua-Jfk:b-j0y3bi) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/Cargo.lock#L9793)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

strange... happens to me too, on `main`...
please don't commit this change, I'll talk to Gilad
</blockquote></details>

will be fixed [here](https://reviewable.io/reviews/starkware-libs/sequencer/942), you can rebase when it's merged


<!-- Sent from Reviewable.io -->

2024-09-23 08:23 UTC, aner-starkware commented
*[`crates/blockifier/src/transaction/objects.rs` line 381 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7SkbpW0bv4RnmlcePm:-O7Sy6rT5jWQGXSWRe6a:bjageu0) ([raw file](https://github.com/starkware-libs/sequencer/blob/f26dfd83dae1a94f7c8ff3ff60db9120693f3930/crates/blockifier/src/transaction/objects.rs#L381)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this `match` logic is duplicated several times; please implement a `get_l2_resource_gas_costs(&self, mode:  &GasVectorComputationMode) -> &ArchivalDataGasCosts` function on `VersionedConstants` and use it 3 times (the struct type of `archival_data_gas_costs` and `deprecated_l2_resource_gas_costs` is the same type, right?)
</blockquote></details>

It's duplicated because you asked that `versioned_constants` and `mode` would be in the input; why not give the `data_gas_costs` instead? Then it can be written once before calling these functions.


<!-- Sent from Reviewable.io -->

2024-09-23 08:30 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware, @avi-starkware, @barak-b-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_1.json` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OnoFw14TuWM6uA1kR:-O7Szt-D1jHu52eHYh1g:bxv2pfx) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/resources/versioned_constants_13_1.json#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware is the value from the tip of `main-v0.13.1` the correct value?
or did something change here on 0.13.1.1?
</blockquote></details>

The numbers here are fine. Look at `main-v0.13.2` files. 


<!-- Sent from Reviewable.io -->

2024-09-23 09:00 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware, @avi-starkware, and @barak-b-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 381 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7SkbpW0bv4RnmlcePm:-O7T5yI55cqzx41syy3T:bmeap82) ([raw file](https://github.com/starkware-libs/sequencer/blob/f26dfd83dae1a94f7c8ff3ff60db9120693f3930/crates/blockifier/src/transaction/objects.rs#L381)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It's duplicated because you asked that `versioned_constants` and `mode` would be in the input; why not give the `data_gas_costs` instead? Then it can be written once before calling these functions.
</blockquote></details>

to keep the API abstract


<!-- Sent from Reviewable.io -->

2024-09-23 09:02 UTC, aner-starkware commented
*[`crates/blockifier/src/blockifier/block.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OmdxG4Fj4QKLv6xgM:-O7T6QIQEMKng8eLMaVx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/69e953aab5109f625393502f725e4cbff6274156/crates/blockifier/src/blockifier/block.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so please update the todo(s) to point to the problematic test, so it's easy to know in the future if this todo is complete / ready to do or not
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-23 09:24 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 8 unresolved discussions (waiting on @aner-starkware, @avi-starkware, and @barak-b-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 291 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7TBYWa9tXE4qiMaRiU:-O7TBYWa9tXE4qiMaRiV:b-ahnqor) ([raw file](https://github.com/starkware-libs/sequencer/blob/39532a80f6efb64ef55881ef1174ed0b673ce4de/crates/blockifier/src/versioned_constants.rs#L291)):*
> ```XML
> }
> 
> #[derive(Copy, Clone, Debug, Default, Deserialize, Eq, PartialEq)]
> ```

I don't think you'll need this after you start returning a reference instead of an instance (See below)



_Code quote:_
```XML
Copy,
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 375 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7TAgreColAORpEJ2xP:-O7TAgreColAORpEJ2xQ:bo9d5u8) ([raw file](https://github.com/starkware-libs/sequencer/blob/39532a80f6efb64ef55881ef1174ed0b673ce4de/crates/blockifier/src/transaction/objects.rs#L375)):*
> ```XML
>         mode: &GasVectorComputationMode,
>     ) -> u128 {
>         let gas_costs = get_gas_costs(versioned_constants, mode);
> ```

1. should be a method of the VersionedConstants struct (it's basically a getter)
2. function should be named to something a bit clearer, like `get_l2_resource_gas_costs`... @Yoni-Starkware suggestions for a name? `archival_gas_costs`?



_Code quote:_
```XML
get_gas_costs
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 486 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7TBEuy5P9GRMgjqazC:-O7TBEuy5P9GRMgjqazD:bkx3vn7) ([raw file](https://github.com/starkware-libs/sequencer/blob/39532a80f6efb64ef55881ef1174ed0b673ce4de/crates/blockifier/src/transaction/objects.rs#L486)):*
> ```XML
>     versioned_constants: &VersionedConstants,
>     mode: &GasVectorComputationMode,
> ) -> crate::versioned_constants::ArchivalDataGasCosts {
> ```

add a `use` above



_Suggestion:_
```XML
ArchivalDataGasCosts
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 486 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7TBHe6E1p-sI1kw9RN:-O7TBHe6E1p-sI1kw9RO:bekd412) ([raw file](https://github.com/starkware-libs/sequencer/blob/39532a80f6efb64ef55881ef1174ed0b673ce4de/crates/blockifier/src/transaction/objects.rs#L486)):*
> ```XML
>     versioned_constants: &VersionedConstants,
>     mode: &GasVectorComputationMode,
> ) -> crate::versioned_constants::ArchivalDataGasCosts {
> ```

return a "reference", not a copy (you may need the lifetime param to indicate which borrowed input is the lifetime of the output)



_Suggestion:_
```XML
fn get_gas_costs(
    versioned_constants: &'a VersionedConstants,
    mode: &GasVectorComputationMode,
) -> &'a crate::versioned_constants::ArchivalDataGasCosts {
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 491 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7TB8us7HBcXAipqzIO:-O7TB8us7HBcXAipqzIP:bwzh9bw) ([raw file](https://github.com/starkware-libs/sequencer/blob/39532a80f6efb64ef55881ef1174ed0b673ce4de/crates/blockifier/src/transaction/objects.rs#L491)):*
> ```XML
>         GasVectorComputationMode::NoL2Gas => versioned_constants.deprecated_l2_resource_gas_costs,
>     };
>     gas_costs
> ```

no need for intermediate variable



_Suggestion:_
```XML
    match mode {
        GasVectorComputationMode::All => versioned_constants.archival_data_gas_costs,
        GasVectorComputationMode::NoL2Gas => versioned_constants.deprecated_l2_resource_gas_costs,
    }
```


<!-- Sent from Reviewable.io -->

2024-09-23 10:22 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 15 of 17 files reviewed, 8 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 291 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7TBYWa9tXE4qiMaRiU:-O7TO_vH2xrJXc6286Lp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/39532a80f6efb64ef55881ef1174ed0b673ce4de/crates/blockifier/src/versioned_constants.rs#L291)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't think you'll need this after you start returning a reference instead of an instance (See below)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 363 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7SjeRS9txu4GEEYLHz:-O7TJ-yj1cwVG4k4rl7_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f26dfd83dae1a94f7c8ff3ff60db9120693f3930/crates/blockifier/src/transaction/objects.rs#L363)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

sorry for the flipping, but... I don't think the `get_..._cost` functions should return integers.
they should return gas vectors, because they are computing gas amounts...
please
1. refactor the `get_..._cost` functions to return a `GasVector`
2. rename them to `get_..._gas_cost`

and then the code here can look like this (`Add` is implemented on `GasVector`):
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 381 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7SkbpW0bv4RnmlcePm:-O7T6bVF1oi_QpYz-BPT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f26dfd83dae1a94f7c8ff3ff60db9120693f3930/crates/blockifier/src/transaction/objects.rs#L381)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

to keep the API abstract
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 375 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7TAgreColAORpEJ2xP:-O7TMSARAsQP2VRxqQ6V:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/39532a80f6efb64ef55881ef1174ed0b673ce4de/crates/blockifier/src/transaction/objects.rs#L375)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. should be a method of the VersionedConstants struct (it's basically a getter)
2. function should be named to something a bit clearer, like `get_l2_resource_gas_costs`... @Yoni-Starkware suggestions for a name? `archival_gas_costs`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 486 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7TBEuy5P9GRMgjqazC:-O7TNfcp94w3eOooKROW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/39532a80f6efb64ef55881ef1174ed0b673ce4de/crates/blockifier/src/transaction/objects.rs#L486)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a `use` above
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 486 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7TBHe6E1p-sI1kw9RN:-O7TNwRo2xkpe60XHLMb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/39532a80f6efb64ef55881ef1174ed0b673ce4de/crates/blockifier/src/transaction/objects.rs#L486)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

return a "reference", not a copy (you may need the lifetime param to indicate which borrowed input is the lifetime of the output)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 491 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7TB8us7HBcXAipqzIO:-O7TNYCuAxBek20FQGrm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/39532a80f6efb64ef55881ef1174ed0b673ce4de/crates/blockifier/src/transaction/objects.rs#L491)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need for intermediate variable
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-23 10:58 UTC, aner-starkware commented
*[`crates/blockifier/src/blockifier/block.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OmdxG4Fj4QKLv6xgM:-O7TWng0CvSXYSV_9DRF:bdlt447) ([raw file](https://github.com/starkware-libs/sequencer/blob/69e953aab5109f625393502f725e4cbff6274156/crates/blockifier/src/blockifier/block.rs#L54)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Turns out this change would actually fail several tests (though not in the blockifier).


<!-- Sent from Reviewable.io -->

2024-09-23 11:25 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 14 of 17 files reviewed, 9 unresolved discussions (waiting on @aner-starkware, @avi-starkware, @barak-b-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 173 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7Tc9sI4s9pjFeFTlek:-O7Tc9sI4s9pjFeFTlel:bn5r8v4) ([raw file](https://github.com/starkware-libs/sequencer/blob/138f44d2e355116857eb16afc1ca772f122d2cc0/crates/blockifier/src/versioned_constants.rs#L173)):*
> ```XML
>     pub fn get_l1_to_l2_gas_price_ratio(&self) -> ResourceCost {
>         self.l1_to_l2_gas_price_ratio()
>     }
> ```

Do we really need all these functions?
I think there is only one conversion scenario: VM resources gas usage: L1 -> L2 gas conversion.
That's it, right?



_Code quote:_
```XML
    pub fn convert_l1_to_l2_gas_price_round_up(&self, l1_gas_price: u128) -> u128 {
        *(self.l1_to_l2_gas_price_ratio() * l1_gas_price).ceil().numer()
    }

    /// Converts from L1 gas amount to L2 gas amount with **upward rounding**.
    pub fn convert_l1_to_l2_gas_amount_round_up(&self, l1_gas_amount: u128) -> u128 {
        // The amount ratio is the inverse of the price ratio.
        *(self.l1_to_l2_gas_price_ratio().inv() * l1_gas_amount).ceil().numer()
    }

    /// Converts from L2 gas price to L1 gas price with **upward rounding**.
    pub fn convert_l2_to_l1_gas_price_round_up(&self, l2_gas_price: u128) -> u128 {
        *(self.l1_to_l2_gas_price_ratio().inv() * l2_gas_price).ceil().numer()
    }

    /// Converts from L2 gas amount to L1 gas amount with **upward rounding**.
    pub fn convert_l2_to_l1_gas_amount_round_up(&self, l2_gas_amount: u128) -> u128 {
        // The amount ratio is the inverse of the price ratio.
        *(self.l1_to_l2_gas_price_ratio() * l2_gas_amount).ceil().numer()
    }

    /// Returns the following ratio: L2_gas_price/L1_gas_price.
    fn l1_to_l2_gas_price_ratio(&self) -> ResourceCost {
        Ratio::new(1, u128::from(self.os_constants.gas_costs.step_gas_cost))
            * self.vm_resource_fee_cost()["n_steps"]
    }

    #[cfg(any(feature = "testing", test))]
    pub fn get_l1_to_l2_gas_price_ratio(&self) -> ResourceCost {
        self.l1_to_l2_gas_price_ratio()
    }
```


<!-- Sent from Reviewable.io -->

2024-09-23 11:34 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 14 of 17 files reviewed, 9 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 294 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OmbD9CBgxDim79TPm:-O7Te5u-1S_RfLxQjn6F:blxxq13) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/src/versioned_constants.rs#L294)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

well, it's deleted code now... still relevant?
</blockquote></details>

I asked separately; will fix in a separate PR if necessary.
___
*[`crates/blockifier/src/versioned_constants.rs` line 299 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7OmYpX5-bv7srS2sU4:-O7Te-uA7KlOx-pbgz-a:blxxq13) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dd8492cc66d1413c110e56c047506d23bc69f2e/crates/blockifier/src/versioned_constants.rs#L299)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

well, it's deleted code now... still relevant?
</blockquote></details>

I asked separately; will fix in a separate PR if necessary.
___
*[`crates/blockifier/src/versioned_constants.rs` line 173 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7Tc9sI4s9pjFeFTlek:-O7TdLNv1P_CEnGHXMYC:b-pqvxt1) ([raw file](https://github.com/starkware-libs/sequencer/blob/138f44d2e355116857eb16afc1ca772f122d2cc0/crates/blockifier/src/versioned_constants.rs#L173)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Do we really need all these functions?
I think there is only one conversion scenario: VM resources gas usage: L1 -> L2 gas conversion.
That's it, right?
</blockquote></details>

I'll check it in a separate PR. In general, it's important that we have both price and amount conversions — this is how we ended up with the conversion bug in the first place.


<!-- Sent from Reviewable.io -->

2024-09-23 11:38 UTC, aner-starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 173 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7Tc9sI4s9pjFeFTlek:-O7Tf4GBE9VH3OSVEq3t:b-ht3gy1) ([raw file](https://github.com/starkware-libs/sequencer/blob/138f44d2e355116857eb16afc1ca772f122d2cc0/crates/blockifier/src/versioned_constants.rs#L173)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I'll check it in a separate PR. In general, it's important that we have both price and amount conversions — this is how we ended up with the conversion bug in the first place.
</blockquote></details>

Two of the functions aren't used anymore, so I deleted them.


<!-- Sent from Reviewable.io -->

2024-09-23 13:17 UTC, dorimedini-starkware requested changes
> Reviewed 10 of 10 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 507 at r20](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7U0RY4DyQM0XG0r6B3:-O7U0RY4DyQM0XG0r6B4:b-cfbxso) ([raw file](https://github.com/starkware-libs/sequencer/blob/f44d9b148644ae113ffd61464f192520b4a09f2a/crates/blockifier/src/transaction/objects.rs#L507)):*
> ```XML
>         }
>     }
> }
> ```

it is not intuitive that `GasVectorComputationMode::All.as_gas_vector(x)` results in `x` L2 gas.
either (a) delete this `impl` and explicitly `match` when needed, or (b) rename to `to_l1_or_l2_gas_vector`.



_Code quote:_
```XML
impl GasVectorComputationMode {
    // Transform the gas amount from a u128 of L1\L2 (depending on the computation mode) units, to a
    // GasVector.
    pub fn as_gas_vector(&self, gas_amount: u128) -> GasVector {
        match self {
            GasVectorComputationMode::All => GasVector::from_l2_gas(gas_amount),
            GasVectorComputationMode::NoL2Gas => GasVector::from_l1_gas(gas_amount),
        }
    }
}
```


<!-- Sent from Reviewable.io -->

2024-09-23 14:15 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815#-:-O7UEDIv9j7hlw1TIPRX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-23 15:08 UTC, Yoni-Starkware requested changes
> Reviewed 6 of 10 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 271 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7UOJit2h2k64U5IiWd:-O7UOJit2h2k64U5IiWe:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f07cd9abccbc16226558acaba88daf13667c41f0/crates/blockifier/src/versioned_constants.rs#L271)):*
> ```XML
>     }
> 
>     pub fn get_gas_costs(&self, mode: &GasVectorComputationMode) -> &ArchivalDataGasCosts {
> ```





_Suggestion:_
```XML
get_archival_data_gas_costs
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 357 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7UPoJV1sksVe2Rb7Qo:-O7UPoJV1sksVe2Rb7Qp:b-lnikns) ([raw file](https://github.com/starkware-libs/sequencer/blob/f07cd9abccbc16226558acaba88daf13667c41f0/crates/blockifier/src/transaction/objects.rs#L357)):*
> ```XML
>             self.get_code_gas_cost(versioned_constants, mode),
>             self.get_events_gas_cost(versioned_constants, mode),
>         ]
> ```

You check the computation mode twice in each func. 
I have another suggestion: let these functions get the archival_data_gas_costs struct as input, and return u128.
Transform it to gas_vector only here.



_Code quote:_
```XML
        [
            self.get_calldata_and_signature_gas_cost(versioned_constants, mode),
            self.get_code_gas_cost(versioned_constants, mode),
            self.get_events_gas_cost(versioned_constants, mode),
        ]
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 499 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7UPW_OBymrxj2p264y:-O7UPW_P5TeZn8rCygS4:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f07cd9abccbc16226558acaba88daf13667c41f0/crates/blockifier/src/transaction/objects.rs#L499)):*
> ```XML
> 
> impl GasVectorComputationMode {
>     // Transform the gas amount from a u128 of L1\L2 (depending on the computation mode) units, to a
> ```





_Suggestion:_
```XML
// Transforms
```


<!-- Sent from Reviewable.io -->

2024-09-23 18:42 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 271 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7UOJit2h2k64U5IiWd:-O7VBMag6ARBS1XRcFZx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f07cd9abccbc16226558acaba88daf13667c41f0/crates/blockifier/src/versioned_constants.rs#L271)):*
> ```XML
>     }
> 
>     pub fn get_gas_costs(&self, mode: &GasVectorComputationMode) -> &ArchivalDataGasCosts {
> ```

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 357 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7UPoJV1sksVe2Rb7Qo:-O7VAY_59LFSZPgqiIPU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f07cd9abccbc16226558acaba88daf13667c41f0/crates/blockifier/src/transaction/objects.rs#L357)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You check the computation mode twice in each func. 
I have another suggestion: let these functions get the archival_data_gas_costs struct as input, and return u128.
Transform it to gas_vector only here.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 499 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7UPW_OBymrxj2p264y:-O7VAa8zC6Ak-Sn4iVgl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f07cd9abccbc16226558acaba88daf13667c41f0/crates/blockifier/src/transaction/objects.rs#L499)):*
> ```XML
> 
> impl GasVectorComputationMode {
>     // Transform the gas amount from a u128 of L1\L2 (depending on the computation mode) units, to a
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-24 06:54 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 369 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7XnTE3AR4FJanYCd09:-O7XnTE43Tvzw5rSJ9Nj:b4nlh0z) ([raw file](https://github.com/starkware-libs/sequencer/blob/c95598ea4788e959a3b4b5800c3f7a43793f7a83/crates/blockifier/src/transaction/objects.rs#L369)):*
> ```XML
>             .into_iter()
>             .sum(),
>         )
> ```

Now we can remove `to_l1_or_l2_gas_vector` since it is used only once and the name is confusing



_Suggestion:_
```XML
        let gas_amount = 
            [
                self.get_calldata_and_signature_gas_cost(archival_gas_costs),
                self.get_code_gas_cost(archival_gas_costs),
                self.get_events_gas_cost(archival_gas_costs),
            ]
            .into_iter()
            .sum(),
            
        match mode {
            GasVectorComputationMode::All => GasVector::from_l2_gas(gas_amount),
            GasVectorComputationMode::NoL2Gas => GasVector::from_l1_gas(gas_amount),
        }
```


<!-- Sent from Reviewable.io -->

2024-09-24 07:31 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-24 09:02 UTC, Yoni-Starkware reviewed
> Reviewed 2 of 8 files at r4, 2 of 6 files at r7, 3 of 10 files at r19.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-09-24 09:03 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-09-24 09:06 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 369 at r22](https://reviewable.io/reviews/starkware-libs/sequencer/815#-O7XnTE3AR4FJanYCd09:-O7YGuZj32ozdm-2n60s:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c95598ea4788e959a3b4b5800c3f7a43793f7a83/crates/blockifier/src/transaction/objects.rs#L369)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Now we can remove `to_l1_or_l2_gas_vector` since it is used only once and the name is confusing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-24 09:09 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-24 09:12 UTC, dorimedini-starkware approved these changes
> Reviewed 10 of 10 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-09-24 09:34 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 10 files at r24, 10 of 10 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815#-:-O7YNShS1eDA8R_vEqn7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-09-24 10:05 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/815)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-09-24 11:04 UTC, merged