Handler for StreamMessages
starkware-libs/sequencer pull request #823
Opened 2024-09-16 15:26 UTC by guy-starkware

Create an object called StreamHandler that can buffer StreamMessages that arrive in any order, and output them in order as soon as any messages are in contiguous order.

2024-09-18 07:48 UTC, dan-starkware requested changes
> Reviewed 1 of 3 files at r4, 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 2 of 7 files reviewed, 10 unresolved discussions (waiting on @guy-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/Cargo.toml` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72miJ_9JxreXBTh9pA:-O72miJa5XKG8KJw8HWV:b-fqsjnr) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/papyrus_protobuf/Cargo.toml#L24)):*
> ```TOML
> papyrus_test_utils = { workspace = true, optional = true }
> thiserror.workspace = true
> tokio = { workspace = true, features = ["full"] }
> ```

Is this intentional?



_Code quote:_
```TOML
tokio = { workspace = true, features = ["full"] }
```
___
*[`crates/sequencing/papyrus_consensus/Cargo.toml` line 15 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72r9zx9u6DBjtMHErS:-O72r9zx9u6DBjtMHErT:b79ui9m) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/Cargo.toml#L15)):*
> ```TOML
> futures.workspace = true
> lazy_static.workspace = true
> log.workspace = true
> ```

Please use tracing instead



_Code quote:_
```TOML
log.workspace = true
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 14 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72mq_uD9V_ROKa9VyX:-O72mq_uD9V_ROKa9VyY:b2hibe9) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/lib.rs#L14)):*
> ```XML
> #[allow(missing_docs)]
> pub mod state_machine;
> #[allow(missing_docs)]
> ```

Please remove and document instead



_Code quote:_
```XML
#[allow(missing_docs)]
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 14 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72y09mECY84DFsXZ_O:-O72y09mECY84DFsXZ_P:b-qs6nlr) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L14)):*
> ```XML
> pub struct StreamHandlerConfig {
>     pub timeout_seconds: Option<u64>,
>     pub timeout_millis: Option<u64>,
> ```

Why both?



_Code quote:_
```XML
    pub timeout_seconds: Option<u64>,
    pub timeout_millis: Option<u64>,
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 28 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72nrhx99JEBTcHyAJu:-O72nrhx99JEBTcHyAJv:b8fecx5) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L28)):*
> ```XML
>         }
>     }
> }
> ```

Seems like all fields get the default value for the type. Consider removing and deriving `default` instead. (`#[derive(Default)]`)



_Code quote:_
```XML
impl Default for StreamHandlerConfig {
    fn default() -> Self {
        StreamHandlerConfig {
            timeout_seconds: None,
            timeout_millis: None,
            max_buffer_size: None,
            max_num_streams: None,
        }
    }
}
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 38 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72qAO80he3dbAves9C:-O72qAO80he3dbAves9D:bxilvze) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L38)):*
> ```XML
>     pub receiver: mpsc::Receiver<StreamMessage<T>>,
> 
>     // these dictionaries are keyed on the stream_id
> ```

1. Try and write complete sentences in comments (Capital T, a period at the end of the sentence)

2. IMO dictionary is more python-oriented, consider renaming to mapping. 



_Code quote:_
```XML
these dictionaries are keyed on the stream_id
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 73 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72y4rTDfophBB8nxXd:-O72y4rTDfophBB8nxXe:bw63wnl) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L73)):*
> ```XML
>         let t0 = std::time::Instant::now();
>         loop {
>             log::debug!("Listening for messages for {} milliseconds", t0.elapsed().as_millis());
> ```

This is not accurate, right?



_Code quote:_
```XML
log::debug!("Listening for messages for {} milliseconds", t0.elapsed().as_millis());
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 77 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O730QXZAq8Ur92hCJxG:-O730QXZAq8Ur92hCJxH:br0uw92) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L77)):*
> ```XML
>             if let Some(timeout) = self.config.timeout_seconds {
>                 if t0.elapsed().as_secs() > timeout {
>                     break;
> ```

What happens then? Who is responsible for keep polling?



_Code quote:_
```XML
 break;
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 88 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72xhK96Guq5Vg0HiUK:-O72xhK96Guq5Vg0HiUL:b6uzudd) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L88)):*
> ```XML
> 
>             if let Ok(message) = self.receiver.try_next() {
>                 if let None = message {
> ```

No need for pattern matching, consider



_Suggestion:_
```XML
if message.is_none() {
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 93 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72yIDb2Kdk2EoMfYGw:-O72yIDb2Kdk2EoMfYGx:bmtqni6) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L93)):*
> ```XML
>                 }
> 
>                 let message = message.unwrap(); // code above handles case where message is None
> ```

1. Please refrain from `unwrap` outside of tests.
2. You can instead do something like
```
let message = match message {
    Some(message) => message,
    None => break,
};
```



_Code quote:_
```XML
 let message = message.unwrap();
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 125 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O731AqdBstVxGLgAkXn:-O731AqeBn2gLJkoi_NV:brprnxg) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L125)):*
> ```XML
>                     let num_streams = self.num_buffered.len() as u64;
>                     if num_streams > max_streams {
>                         panic!("Max number of streams reached! {}", max_streams);
> ```

This seems like an attack vector, right?



_Code quote:_
```XML
panic!("Max number of streams reached! {}", max_streams);
```


<!-- Sent from Reviewable.io -->

2024-09-18 12:43 UTC, ShahakShama requested changes
> Reviewed 2 of 4 files at r11, 2 of 3 files at r12, 1 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 7 of 8 files reviewed, 30 unresolved discussions (waiting on @dan-starkware and @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 123 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O73qwq141sZPJIN3gwX:-O73qwq141sZPJIN3gwY:b-jsar4p) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L123)):*
> ```XML
> 
>         let block_receiver = context.validate_proposal(self.height, p2p_messages_receiver).await;
>         // (ProposalContentId, ProposalFin)
> ```

Is this a debug leftover?
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 125 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O731AqdBstVxGLgAkXn:-O742cCTDWOoqL9bE-ho:b-wey6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L125)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This seems like an attack vector, right?
</blockquote></details>

+1
IMO you can just remove max_streams for now and add a TODO to solve the issue where an attacker can cause your memory to be inflated
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 15 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O73rEkmDHvrMElIK4hD:-O73rEkmDHvrMElIK4hE:buk0elj) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L15)):*
> ```XML
> #[derive(Default)]
> pub struct StreamHandlerConfig {
>     /// The maximum buffer size for each stream (if None, will have not limit).
> ```

not -> no. Same below
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 23 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O747GTF1Xm1FQ3ZAH22:-O747GTF1Xm1FQ3ZAH23:b-3b7m6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L23)):*
> ```XML
> 
> /// A StreamHandler is responsible for buffering and sending messages in order.
> pub struct StreamHandler<
> ```

BTreeMap should only be used in cases where the map needs to be sorted. Otherwise, use HashMap.
Try to find out which case suits which map here. Haven't deep-dived into it
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 27 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O73rPcoBz19VT7T8pA9:-O73rPcoBz19VT7T8pAA:b-kaa5gx) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L27)):*
> ```XML
> > {
>     /// Configuration for the StreamHandler (things like max buffer size, etc.).
>     pub config: StreamHandlerConfig,
> ```

Why are all these fields public? a public field is a field that is part of the api. All these fields look implementation specific
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 36 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O740Ma02tTLjM-U7dFa:-O740Ma02tTLjM-U7dFb:bmm48bt) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L36)):*
> ```XML
>     // All these maps are keyed on the stream_id.
>     /// The next chunk_id that is expected for each stream.
>     pub next_chunk_ids: BTreeMap<u64, u64>,
> ```

From where did the word chunk arrive? IMO this should be message_id
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 36 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O747pqK5vBUkwZAPbN-:-O747pqK5vBUkwZAPbN0:brdybu) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L36)):*
> ```XML
>     // All these maps are keyed on the stream_id.
>     /// The next chunk_id that is expected for each stream.
>     pub next_chunk_ids: BTreeMap<u64, u64>,
> ```

Please add type aliases for StreamId and MessageId and use them instead of u64 so it's easier to understand what is what.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 47 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O74789C-4dU6_QY2TDK:-O74789C-4dU6_QY2TDL:b-lpeb5b) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L47)):*
> ```XML
>     /// Each nested map is keyed by the chunk_id of the first message it contains.
>     /// The messages in each nested map are stored in a contiguous sequence of messages (as a Vec).
>     pub message_buffers: BTreeMap<u64, BTreeMap<u64, Vec<StreamMessage<T>>>>,
> ```

Use VecDeque. It's much more efficient for the actions you're doing here
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 47 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O747SZT5mFuaEcd2A5q:-O747SZT5mFuaEcd2A5r:b-h5ufv9) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L47)):*
> ```XML
>     /// Each nested map is keyed by the chunk_id of the first message it contains.
>     /// The messages in each nested map are stored in a contiguous sequence of messages (as a Vec).
>     pub message_buffers: BTreeMap<u64, BTreeMap<u64, Vec<StreamMessage<T>>>>,
> ```

try to think of a name for the value of this map, and create a type alias for it
Or even better, change it to BTreeMap<(u64, u64), Vec<StreamMessage<T>>>

Now that I've looked into the usage, It looks like you can just have BTreeMap<(u64, u64), StreamMessage<T>> and in the drain code just loop until you find a hole
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 74 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O741-Dt2oyTc8GDm37f:-O741-Dt2oyTc8GDm37g:b4siq4d) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L74)):*
> ```XML
>     /// Guarntees that messages are sent in order.
>     pub async fn listen(&mut self) {
>         let mut still_open = true;
> ```

I like the style of loop and break instead of defining a boolean variable. I think it's more rustic.
Leaving unblocking since it's a matter of taste

same below
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 80 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O741J_31BgVz5EI4RuU:-O741J_31BgVz5EI4RuV:bdvt9en) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L80)):*
> ```XML
>             } else {
>                 // Err comes when the channel is open but no message was received.
>                 tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;
> ```

call next and await instead
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 86 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O741QVbBF9EhV4SDbtl:-O741QVbBF9EhV4SDbtm:b1t4hdn) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L86)):*
> ```XML
> 
>     #[cfg(test)]
>     pub async fn listen_with_timeout(&mut self, timeout_millis: u128) {
> ```

 [...]

2024-09-18 18:48 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 4 of 11 files reviewed, 28 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/Cargo.toml` line 24 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72miJ_9JxreXBTh9pA:-O737H8_7wh5IBiupIBM:bn4re76) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/papyrus_protobuf/Cargo.toml#L24)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

No, I don't think it is... 
___
*[`crates/sequencing/papyrus_consensus/Cargo.toml` line 15 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72r9zx9u6DBjtMHErS:-O7386MO7R2toX4LYRZe:b1lm1py) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/Cargo.toml#L15)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please use tracing instead
</blockquote></details>

got it. 
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 14 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72mq_uD9V_ROKa9VyX:-O73Z8Lw4vI6jJh1XDUY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/lib.rs#L14)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove and document instead
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 14 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72y09mECY84DFsXZ_O:-O738Yxi-iAEtvqYi06_:b53soms) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L14)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why both?
</blockquote></details>

I needed millis to make the tests run faster. I'm going to get rid of these timeouts altogether. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 28 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72nrhx99JEBTcHyAJu:-O738nwj9zOkDsnZymwZ:b-hpkznd) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L28)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Seems like all fields get the default value for the type. Consider removing and deriving `default` instead. (`#[derive(Default)]`)
</blockquote></details>

good idea. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 88 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72xhK96Guq5Vg0HiUK:-O73fvSl-ttX0UChtK0U:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L88)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

No need for pattern matching, consider
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 93 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O72yIDb2Kdk2EoMfYGw:-O73gav148q2qMFsjqVd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L93)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

1. Please refrain from `unwrap` outside of tests.
2. You can instead do something like
```
let message = match message {
    Some(message) => message,
    None => break,
};
```
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 125 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O731AqdBstVxGLgAkXn:-O73gfzK-2rZpNGWy93X:biryr63) ([raw file](https://github.com/starkware-libs/sequencer/blob/480afa69831356d2e3aa245c0448b37df7da0f30/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L125)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

This seems like an attack vector, right?
</blockquote></details>

There are many ways to make this thing fail. I think we need to decide what happens in that case (I used panic but it could be other things). 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 15 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O73rEkmDHvrMElIK4hD:-O75I2c2695d5PUUvAaZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L15)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

not -> no. Same below
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 23 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O747GTF1Xm1FQ3ZAH22:-O75ICol4zu6_LMGkRUv:bsvqdic) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

BTreeMap should only be used in cases where the map needs to be sorted. Otherwise, use HashMap.
Try to find out which case suits which map here. Haven't deep-dived into it
</blockquote></details>

I do use the fact that they are sorted. Also, I think the performance is better for short keys, but I'm not sure if that makes a big difference. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 27 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O73rPcoBz19VT7T8pA9:-O758O6Q5XKxag_njnkn:b-kzfn4f) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L27)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why are all these fields public? a public field is a field that is part of the api. All these fields look implementation specific
</blockquote></details>

I thought you'd want to plug into it the channels you have from whatever code is using the handler, so it should be open to modification. I'm leaving the config, sender and receiver as public. 

The other fields, I agree, we can make them private. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 36 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O740Ma02tTLjM-U7dFa:-O758_4Y7E5lU4cs1uwI:b32wtd) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L36)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

From where did the word chunk arrive? IMO this should be message_id
</blockquote></details>

ok
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 36 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O747pqK5vBUkwZAPbN-:-O758fOs3ozCxudaFW3L:b-hpkzyk) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L36)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Please add type aliases for StreamId and MessageId and use them instead of u64 so it's easier to understand what is what.
</blockquote></details>

good idea! 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 47 at r13](https://reviewable.io/reviews/starkware-libs/sequenc [...]

2024-09-22 06:46 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 2 of 11 files reviewed, 27 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 142 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O745g-k5nDYaHEmmPXS:-O78BAP65ZtN8OUl7RFn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L142)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This shouldn't be panic. you should mark this stream as failed/abandoned/dropped, dropping any future messages from it, and report the relevant peer
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 143 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O743OQI0TPFTRIhFxnR:-O78BBOS53L1wMSaOYhN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L143)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This message contains a lot of implementation details. try to rephrase it in words that the user can quickly understand without looking at the code, and move the numbers to the end. Also, add the stream id:
Received fin message for stream with pending non-fin messages. stream_id: {}. fin message_id: {}, largest message_id in stream: {}
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 155 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O746HVIE-5-udWLnYvh:-O78BC4S0HIThGZh0IPE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L155)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here, don't panic
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 156 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O746JZ05ltjT1p5ZNW3:-O78BCaZ6ht_89WGgT1Z:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L156)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here, try to improve the message
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 164 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O746RaU8gJc97NrtGTU:-O78BDc41HlxHFjLFaMf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L164)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Don't panic here. Instead, drop the stream. But unlike the other cases above, don't report the peer
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 172 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O746gpzA_v11GZ3V5vJ:-O78BE3P1o_Y_MxzJZ70:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L172)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as before, don't panic
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 173 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O746kOK5ZAXWmPE6U58:-O78BEJZCewVfeyRNO4d:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb6187d7c23b90934d6d0d83a290f2aa7fa00607/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L173)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as before, improve the message (something along the lines of "Received multiple messages with the same stream_id and message_id")
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-22 07:42 UTC, dan-starkware reviewed
> Reviewed 1 of 7 files at r14, 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 5 of 11 files reviewed, 26 unresolved discussions (waiting on @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-09-22 07:48 UTC, dan-starkware reviewed
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 5 of 11 files reviewed, 24 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 124 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7Nfdcj1diHvmDmAW5N:-O7Nfdcj1diHvmDmAW5O:bfo1w19) ([raw file](https://github.com/starkware-libs/sequencer/blob/1dea9e7e8d608dd6fd78aa4b1eea0b63640b5b44/crates/papyrus_protobuf/src/converters/consensus.rs#L124)):*
> ```XML
>             message: T::try_from(value.message)?,
>             stream_id: value.stream_id,
>             message_id: value.message_id,
> ```

Please move this to a preliminary PR and rebase.



_Code quote:_
```XML
  message_id: value.message_id,
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 26 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7Ng8lZCiFRuUs7NkyO:-O7Ng8lZCiFRuUs7NkyP:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/1dea9e7e8d608dd6fd78aa4b1eea0b63640b5b44/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L26)):*
> ```XML
> #[derive(Default)]
> struct StreamStats {
>     // the next message_id that is expected
> ```





_Suggestion:_
```XML
The next message_id that is expected.
```


<!-- Sent from Reviewable.io -->

2024-09-22 11:08 UTC, dan-starkware reviewed
> Reviewed 9 of 13 files at r18, 3 of 3 files at r19.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 15 of 20 files reviewed, 23 unresolved discussions (waiting on @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-09-24 13:48 UTC, dan-starkware requested changes
> Reviewed 1 of 4 files at r11, 1 of 7 files at r14, 2 of 13 files at r18.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 15 of 20 files reviewed, 26 unresolved discussions (waiting on @guy-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 17 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7ZGRPJ5UUNqF1XaqUr:-O7ZGRPJ5UUNqF1XaqUs:b-vydz14) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a01f952adc0ba84a1befad8a2378621f3bec609/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L17)):*
> ```XML
> pub struct StreamHandlerConfig {
>     /// The maximum buffer size for each stream (None -> no limit).
>     max_buffer_len: Option<u64>,
> ```

Is there a reason for the unbounded version? Why not removing the Option?



_Code quote:_
```XML
 max_buffer_len: Option<u64>
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 52 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7ZAeHu4Fvc3Epb3ejm:-O7ZAeHu4Fvc3Epb3ejn:b-t1twjn) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a01f952adc0ba84a1befad8a2378621f3bec609/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L52)):*
> ```XML
>         }
>     }
> }
> ```

Consider replace with an `empty` constructor or deriving `Default` and require that `T` implements `Default`, or using a tool like educe.



_Code quote:_
```XML
impl<T: Clone + Into<Vec<u8>> + TryFrom<Vec<u8>, Error = ProtobufConversionError>> Default
    for StreamData<T>
{
    fn default() -> Self {
        StreamData {
            next_message_id: 0,
            fin_message_id: None,
            max_message_id: 0,
            num_buffered: 0,
            message_buffer: BTreeMap::new(),
        }
    }
}
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 69 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7YrwV0C4RGF9SffuLN:-O7YrwV0C4RGF9SffuLO:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a01f952adc0ba84a1befad8a2378621f3bec609/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L69)):*
> ```XML
>     // This includes both the message buffer and some metadata (like the latest message_id).
>     stream_data: HashMap<StreamId, StreamData<T>>,
>     // TODO(guyn): perhaps make input_stream_data and output_stream_data?
> ```

WDYM?



_Code quote:_
```XML
// TODO(guyn): perhaps make input_stream_data and output_stream_data?
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 100 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7ZFMFA4JM_D3tufIFe:-O7ZFMFA4JM_D3tufIFf:b-gnakni) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a01f952adc0ba84a1befad8a2378621f3bec609/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L100)):*
> ```XML
>         if !self.stream_data.contains_key(&stream_id) {
>             self.stream_data.insert(stream_id, StreamData::default());
>         }
> ```

Use `Entry` instead



_Suggestion:_
```XML
        self.stream_data.entry(stream_id).or_default();
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 109 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7ZH6J5BZYTnEeNrNS6:-O7ZH6J5BZYTnEeNrNS7:biju5v) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a01f952adc0ba84a1befad8a2378621f3bec609/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L109)):*
> ```XML
>                 panic!("Maximum number of streams reached! {}", max_streams);
>             }
>         }
> ```

1. Why checking here and not in case of a new stream?
2. Don't panic here. We can defer proper handling for later if you prefer (change the comment accordingly) 



_Code quote:_
```XML
        if let Some(max_streams) = self.config.max_num_streams {
            let num_streams = self.stream_data.len() as u64;
            if num_streams > max_streams {
                // TODO(guyn): replace panics with more graceful error handling
                panic!("Maximum number of streams reached! {}", max_streams);
            }
        }
```


<!-- Sent from Reviewable.io -->

2024-09-24 14:10 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 15 of 20 files reviewed, 22 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 17 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7ZGRPJ5UUNqF1XaqUr:-O7ZHs3NDFj32L2gQw1i:b-410dbc) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a01f952adc0ba84a1befad8a2378621f3bec609/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L17)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is there a reason for the unbounded version? Why not removing the Option?
</blockquote></details>

My thinking was that no bounds is the simplest thing to do. Do you have a number that makes sense for the maximum length? 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 52 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7ZAeHu4Fvc3Epb3ejm:-O7ZJZf66eerSrviwzNj:b-8hoqfa) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a01f952adc0ba84a1befad8a2378621f3bec609/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L52)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider replace with an `empty` constructor or deriving `Default` and require that `T` implements `Default`, or using a tool like educe.
</blockquote></details>

I thought about making `T` implement `Default` but that seems to me like to hard a requirement for a generic message. 
I'm not sure what you mean by an `empty` constructor? Is it just to write a function called `empty` that initializes? Or is there some shortcut in Rust that I don't know? 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 69 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7YrwV0C4RGF9SffuLN:-O7ZJyeB5qhV81JQUjtb:blcy5ep) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a01f952adc0ba84a1befad8a2378621f3bec609/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L69)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

When the object takes both the role of broadcaster and listener, it will have to save information about incoming streams and outgoing streams in separate places. Probably I will label them something like input/output or broadcast/listen, something like that. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 100 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7ZFMFA4JM_D3tufIFe:-O7ZMV9B1pcQI8JXR7VG:b-c600q7) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a01f952adc0ba84a1befad8a2378621f3bec609/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L100)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Use `Entry` instead
</blockquote></details>

Good idea. But I'm leaving the `if` so I can put the check for too many streams into this conditional (seeing the next comment below). 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 109 at r21](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7ZH6J5BZYTnEeNrNS6:-O7ZMbhe6dLxitcHqokN:b2o3lg6) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a01f952adc0ba84a1befad8a2378621f3bec609/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L109)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

1. Why checking here and not in case of a new stream?
2. Don't panic here. We can defer proper handling for later if you prefer (change the comment accordingly)
</blockquote></details>

Got it. 


<!-- Sent from Reviewable.io -->

2024-09-25 06:53 UTC, dan-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 14 of 20 files reviewed, 27 unresolved discussions (waiting on @guy-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7bsL6I5xKZvN66SafJ:-O7bsL6I5xKZvN66SafK:brydo2a) (no related file):*
Please refrain from panic, trace as warn instead.

___
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 35 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7bv77YCDERA6UWTdK4:-O7bv77YCDERA6UWTdK5:b-4ete8) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d281f56921e92f2d1aba2e1752f8efcb582ce5/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L35)):*
> ```XML
>     max_message_id: MessageId,
>     // The number of messages that are currently buffered.
>     num_buffered: u64,
> ```

This seems redundant, why not using `len` instead?



_Code quote:_
```XML
    // The number of messages that are currently buffered.
    num_buffered: u64,
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 62 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7bsef4-IVpkucKY-hz:-O7bsef4-IVpkucKY-i-:buuw7c3) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d281f56921e92f2d1aba2e1752f8efcb582ce5/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L62)):*
> ```XML
> 
>     // An end of a channel used to send out the messages in the correct order.
>     sender: mpsc::Sender<StreamMessage<T>>,
> ```

Shouldn't this should send `T`?



_Code quote:_
```XML
sender: mpsc::Sender<StreamMessage<T>>,
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 95 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7buVxk0NQj48mdJfxX:-O7buVxlBNpNAyJiVt5L:b-r9luh) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d281f56921e92f2d1aba2e1752f8efcb582ce5/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L95)):*
> ```XML
> 
>     // Handle the message, return true if the channel is still open.
>     fn handle_message(&mut self, message: StreamMessage<T>) -> bool {
> ```

Do we need the return value here?



_Code quote:_
```XML
 fn handle_message(&mut self, message: StreamMessage<T>) -> bool 
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 163 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7bvLoUD2amlwDoeNaE:-O7bvLoUD2amlwDoeNaF:bvm5515) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d281f56921e92f2d1aba2e1752f8efcb582ce5/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L163)):*
> ```XML
> 
>     // Go over each vector in the buffer, push to the end of it if the message_id is contiguous.
>     // If no vector has a contiguous message_id, start a new vector.
> ```

Please fix or remove the comment.



_Code quote:_
```XML
    // Go over each vector in the buffer, push to the end of it if the message_id is contiguous.
    // If no vector has a contiguous message_id, start a new vector.
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 192 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7bstfE7zZn45M89to2:-O7bstfE7zZn45M89to3:b2pdbkv) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d281f56921e92f2d1aba2e1752f8efcb582ce5/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L192)):*
> ```XML
>     // Tries to drain as many messages as possible from the buffer (in order),
>     // DOES NOT guarantee that the buffer will be empty after calling this function.
>     fn drain_buffer(&mut self, stream_id: u64) {
> ```

As the comment suggests, the name has a connotation of leaving something empty. Consider renaming, maybe `process_buffer`.

In general, IMO, it's better if the code is self-explanatory and use comments where needed/sparsely.



_Code quote:_
```XML
    // DOES NOT guarantee that the buffer will be empty after calling this function.
    fn drain_buffer(&mut self, stream_id: u64) {
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 193 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7bxBZ_Cuv_DV2-NK-A:-O7bxBZ_Cuv_DV2-NK-B:b-s68atb) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d281f56921e92f2d1aba2e1752f8efcb582ce5/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L193)):*
> ```XML
>     // DOES NOT guarantee that the buffer will be empty after calling this function.
>     fn drain_buffer(&mut self, stream_id: u64) {
>         let data = self.stream_data.get_mut(&stream_id).unwrap();
> ```

Please refrain from unwrapping



_Code quote:_
```XML
.unwrap();
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 195 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7bwSZkCSMowgNQmnBN:-O7bwSZlAEoqjsEefF7V:b-p547n0) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d281f56921e92f2d1aba2e1752f8efcb582ce5/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L195)):*
> ```XML
>         let data = self.stream_data.get_mut(&stream_id).unwrap();
>         while let Some(message) = data.message_buffer.remove(&data.next_message_id) {
>             self.sender.try_send(message).expect("Send should succeed");
> ```

Consider unifying with the previous send. For example by always storing and processing the buffer.

Add a TODO to reconsider the `expect` here.



_Code quote:_
```XML
self.sender.try_send(message).expect("Send should succeed");
```


<!-- Sent from Reviewable.io -->

2024-09-25 12:46 UTC, dan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 12 of 20 files reviewed, 18 unresolved discussions (waiting on @guy-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 195 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7bwSZkCSMowgNQmnBN:-O7dBbK4-cr109P0ONnq:bnawhit) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d281f56921e92f2d1aba2e1752f8efcb582ce5/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L195)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Just to make clear: you are suggesting to store every message in the buffer and then process the buffer to see if we can send that message?
</blockquote></details>

Yes, or having a function for the send. It relates to the second point (Add a TODO to reconsider the `expect` here). I assume there might be reasons for failing where we should'n unwrap (maybe retry or shifting buffer utilization) 


<!-- Sent from Reviewable.io -->

2024-09-25 12:47 UTC, dan-starkware reviewed
> Reviewed 2 of 2 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 14 of 20 files reviewed, 18 unresolved discussions (waiting on @guy-starkware and @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-09-25 17:24 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 14 of 20 files reviewed, 18 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 195 at r23](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7bwSZkCSMowgNQmnBN:-O7eCbvL6DfB1Q_XSbS7:blqg2ih) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7d281f56921e92f2d1aba2e1752f8efcb582ce5/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L195)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Yes, or having a function for the send. It relates to the second point (Add a TODO to reconsider the `expect` here). I assume there might be reasons for failing where we should'n unwrap (maybe retry or shifting buffer utilization)
</blockquote></details>

Got it. Moved it into a function so we only have to address the issue of sending in one place. 


<!-- Sent from Reviewable.io -->

2024-09-26 07:34 UTC, dan-starkware requested changes
> Reviewed 1 of 1 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 15 of 20 files reviewed, 4 unresolved discussions (waiting on @guy-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 48 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hEf-RAsPlSajYaIm4:-O7hEf-SDJIy2utPyszz:bdmraq0) ([raw file](https://github.com/starkware-libs/sequencer/blob/60778540cf8c5a48bb3a5a873ada4f5c4ac53645/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L48)):*
> ```XML
> > {
>     // An end of a channel used to send out the messages in the correct order.
>     sender: mpsc::Sender<T>,
> ```

Sender of a Receiver of T.
Tests should check that the corresponding channel is closed after fin. I'll explain F2F



_Code quote:_
```XML
sender: mpsc::Sender<T>,
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 11 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hApY84Tpibk6fkX2O:-O7hApY84Tpibk6fkX2P:b-oo4k00) ([raw file](https://github.com/starkware-libs/sequencer/blob/60778540cf8c5a48bb3a5a873ada4f5c4ac53645/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L11)):*
> ```XML
>     use super::*;
> 
>     fn make_random_message(
> ```

This is not random, right? 



_Code quote:_
```XML
make_random_message
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 25 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hA8tF3gW-44uaAElF:-O7hA8tF3gW-44uaAElG:b47ok9m) ([raw file](https://github.com/starkware-libs/sequencer/blob/60778540cf8c5a48bb3a5a873ada4f5c4ac53645/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L25)):*
> ```XML
> 
>     // check if two vectors are the same
>     // ref: https://stackoverflow.com/a/58175659
> ```

IMO we can check equality without the stackoverflow reference. 



_Code quote:_
```XML
    // check if two vectors are the same
    // ref: https://stackoverflow.com/a/58175659
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 26 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7h6tzf86wNpqlx2aYR:-O7h6tzf86wNpqlx2aYS:b-33ky46) ([raw file](https://github.com/starkware-libs/sequencer/blob/60778540cf8c5a48bb3a5a873ada4f5c4ac53645/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L26)):*
> ```XML
>     // check if two vectors are the same
>     // ref: https://stackoverflow.com/a/58175659
>     fn do_vecs_match<T: PartialEq>(a: &Vec<T>, b: &Vec<T>) -> bool {
> ```

Please use slice instead



_Code quote:_
```XML
 &Vec<T>, b: &Vec<T>
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 44 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hCi1Z24fcJYNPOzgQ:-O7hCi1Z24fcJYNPOzgR:bz02w51) ([raw file](https://github.com/starkware-libs/sequencer/blob/60778540cf8c5a48bb3a5a873ada4f5c4ac53645/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L44)):*
> ```XML
> 
>     #[tokio::test]
>     async fn test_stream_handler_in_order() {
> ```

Please remove the `test_` prefix.



_Code quote:_
```XML
test_stream_handler_in_order
```


<!-- Sent from Reviewable.io -->

2024-09-26 08:52 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 15 of 20 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 48 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hEf-RAsPlSajYaIm4:-O7hX4Ad60m-cIEj48x5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/60778540cf8c5a48bb3a5a873ada4f5c4ac53645/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L48)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Sender of a Receiver of T.
Tests should check that the corresponding channel is closed after fin. I'll explain F2F
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 26 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7h6tzf86wNpqlx2aYR:-O7hTxXDDh8P4VRseQZa:bs8ueue) ([raw file](https://github.com/starkware-libs/sequencer/blob/60778540cf8c5a48bb3a5a873ada4f5c4ac53645/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L26)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please use slice instead
</blockquote></details>

I can do that but there are a lot of `collect()` statements in the tests that use this function, and when I turn the inputs to `do_vecs_match` to be slices, they no longer know into what to collect the arrays. Maybe there's a shortcut I am not aware of, but it looks like I would need to explicitely cast all those cases into Vectors and then to slices. I think it is not worth the added code. 


<!-- Sent from Reviewable.io -->

2024-09-26 10:02 UTC, dan-starkware commented
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 101 at r29](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hm4pcDUZBNaFOQ8rL:-O7hm4pcDUZBNaFOQ8rM:bf68ipo) ([raw file](https://github.com/starkware-libs/sequencer/blob/2613497690f8b9ddc3136b5d98d25abdaee7910f/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L101)):*
> ```XML
>                 // If we received a message for a stream that we have not seen before,
>                 // we need to create a new receiver for it.
>                 let (sender, receiver) = mpsc::channel(100);
> ```

Please move to a const with a TODO



_Code quote:_
```XML
(100
```


<!-- Sent from Reviewable.io -->

2024-09-26 10:12 UTC, dan-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 14 of 20 files reviewed, 4 unresolved discussions (waiting on @guy-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 47 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hoKPO9fDLh-QjcZ7X:-O7hoKPO9fDLh-QjcZ7Y:b8291vz) ([raw file](https://github.com/starkware-libs/sequencer/blob/54da22d2d2c8a426cb5b35e60e8e3291eaa4dc02/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L47)):*
> ```XML
>     #[tokio::test]
>     async fn test_stream_handler_in_order() {
>         let (mut h, mut tx_input, mut rx_output) = setup_test();
> ```

Please rename, everywhere



_Suggestion:_
```XML
stream_handler
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 78 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hoCwXBYMyty2TfovY:-O7hoCwY-zec7khlqc5f:b7puarc) ([raw file](https://github.com/starkware-libs/sequencer/blob/54da22d2d2c8a426cb5b35e60e8e3291eaa4dc02/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L78)):*
> ```XML
> 
>     #[tokio::test]
>     async fn test_stream_handler_in_reverse() {
> ```

Please remove prefix, in all tests



_Code quote:_
```XML
 test_stream_handler_in_reverse
```


<!-- Sent from Reviewable.io -->

2024-09-26 10:13 UTC, dan-starkware commented
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 66 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hoc_n0rA-UoT5L8-h:-O7hoc_n0rA-UoT5L8-i:b1ndxjc) ([raw file](https://github.com/starkware-libs/sequencer/blob/54da22d2d2c8a426cb5b35e60e8e3291eaa4dc02/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L66)):*
> ```XML
>         for i in 0..10 {
>             let message = rx_output
>                 .try_next()
> ```

Why not `next`?



_Code quote:_
```XML
.try_next()
```


<!-- Sent from Reviewable.io -->

2024-09-26 10:20 UTC, dan-starkware commented
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 26 at r28](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7h6tzf86wNpqlx2aYR:-O7hpm6k2Fs-NBlkfMLZ:bpzmg4h) ([raw file](https://github.com/starkware-libs/sequencer/blob/60778540cf8c5a48bb3a5a873ada4f5c4ac53645/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L26)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

I can do that but there are a lot of `collect()` statements in the tests that use this function, and when I turn the inputs to `do_vecs_match` to be slices, they no longer know into what to collect the arrays. Maybe there's a shortcut I am not aware of, but it looks like I would need to explicitely cast all those cases into Vectors and then to slices. I think it is not worth the added code.
</blockquote></details>

Can you use `turbofish`? See `collect`'s [documentation](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.collect)


<!-- Sent from Reviewable.io -->

2024-09-26 10:48 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 14 of 20 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 101 at r29](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hm4pcDUZBNaFOQ8rL:-O7huHST24ttthaNm0IQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2613497690f8b9ddc3136b5d98d25abdaee7910f/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L101)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please move to a const with a TODO
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 66 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hoc_n0rA-UoT5L8-h:-O7hw4GUANdsb9irm_6L:bf3tad3) ([raw file](https://github.com/starkware-libs/sequencer/blob/54da22d2d2c8a426cb5b35e60e8e3291eaa4dc02/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L66)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why not `next`?
</blockquote></details>

This kind of receiver does not have `next()`. Only `try_next()`. But I did convert the `expect` into `unwrap` to make things a little bit shorter. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 78 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hoCwXBYMyty2TfovY:-O7hwSfyC032PaXi9Bst:b-qghz7h) ([raw file](https://github.com/starkware-libs/sequencer/blob/54da22d2d2c8a426cb5b35e60e8e3291eaa4dc02/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L78)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove prefix, in all tests
</blockquote></details>

Yes, of course I meant to do that... 


<!-- Sent from Reviewable.io -->

2024-09-26 11:14 UTC, dan-starkware commented
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 66 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hoc_n0rA-UoT5L8-h:-O7i1QrQ9QF4Rti-7ov-:b-agtfxb) ([raw file](https://github.com/starkware-libs/sequencer/blob/54da22d2d2c8a426cb5b35e60e8e3291eaa4dc02/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L66)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

This kind of receiver does not have `next()`. Only `try_next()`. But I did convert the `expect` into `unwrap` to make things a little bit shorter.
</blockquote></details>

You can use `futures_util::stream::stream::StreamExt`


<!-- Sent from Reviewable.io -->

2024-09-26 11:16 UTC, dan-starkware reviewed
> Reviewed 2 of 2 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 16 of 20 files reviewed, 2 unresolved discussions (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2024-09-26 11:29 UTC, guy-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 15 of 20 files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 66 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/823#-O7hoc_n0rA-UoT5L8-h:-O7i4z3o37ot-ie6zCjC:b2o3lg6) ([raw file](https://github.com/starkware-libs/sequencer/blob/54da22d2d2c8a426cb5b35e60e8e3291eaa4dc02/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L66)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

You can use `futures_util::stream::stream::StreamExt`
</blockquote></details>

Got it. 


<!-- Sent from Reviewable.io -->

2024-09-26 12:08 UTC, dan-starkware reviewed
> Reviewed 4 of 4 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2024-09-26 12:08 UTC, dan-starkware approved these changes
> Reviewed 1 of 4 files at r20.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/823)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)



<!-- Sent from Reviewable.io -->

2024-09-26 12:20 UTC, merged