refactor(blockifier): remove enforce fee from actual fee
starkware-libs/sequencer pull request #835
Opened 2024-09-17 08:00 UTC by avivg-starkware

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/835)

2024-09-17 11:10 UTC, meship-starkware requested changes
> Reviewed 3 of 3 files at r1, 1 of 8 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: all files reviewed, 5 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O6zPniV4qZqljnAF210:-O6zPniV4qZqljnAF211:b-3kig0a) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e790d8e0bce218f11663b16d4dd5c3dc7feaff1/crates/blockifier/src/concurrency/fee_utils.rs#L66)):*
> ```XML
>         //     // Fee(0),
>         //     "Transaction with no fee transfer info must have zero fee."
>         // )
> ```

Remove this code.



_Code quote:_
```XML
        // assert_eq!(
        //     //aviv: changes:
        //     // tx_execution_info.receipt.fee,
        //     // Fee(0),
        //     "Transaction with no fee transfer info must have zero fee."
        // )
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O6zQ-p2-j2kIgl5yrvx:-O6zQ-p3DZGeLhA-lGtQ:bvecbqi) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e790d8e0bce218f11663b16d4dd5c3dc7feaff1/crates/blockifier/src/fee/actual_cost.rs#L107)):*
> ```XML
>         // } else {
>         //     Fee(0)
>         // };
> ```

Remove this code. 



_Code quote:_
```XML
        // L1 handler transactions are not charged an L2 fee but it is compared to the L1 fee.
        // PREV:
        // let fee = if tx_context.tx_info.enforce_fee() || tx_type == TransactionType::L1Handler {
        //     tx_context.tx_info.get_fee_by_gas_vector(&tx_context.block_context.block_info, gas)
        // } else {
        //     Fee(0)
        // };
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O6zcInDCJ83gRP8NfWS:-O6zcInDCJ83gRP8NfWT:b-ci15zy) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e790d8e0bce218f11663b16d4dd5c3dc7feaff1/crates/blockifier/src/fee/actual_cost.rs#L108)):*
> ```XML
>         //     Fee(0)
>         // };
>         let fee = if tx_type == TransactionType::Declare
> ```

Please document this line  



_Suggestion:_
```XML
// To be backward compatible with the meaning of enforce fee in Declare V0. 
let fee = if tx_type == TransactionType::Declare
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 362 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O6zQGlB-c6Gr29731Ib:-O6zQGlB-c6Gr29731Ic:b-anp7m6) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e790d8e0bce218f11663b16d4dd5c3dc7feaff1/crates/blockifier/src/transaction/account_transaction.rs#L362)):*
> ```XML
>         concurrency_mode: bool,
>     ) -> TransactionExecutionResult<Option<CallInfo>> {
>         // aviv: if !charge_fee || actual_fee == Fee(0) {
> ```

Remove all aviv comments.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1281 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O6zb00WAfSekGBeh5Ue:-O6zb00X08BjqjFlciD2:b-44fjn0) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e790d8e0bce218f11663b16d4dd5c3dc7feaff1/crates/blockifier/src/transaction/transactions_test.rs#L1281)):*
> ```XML
>                 FeatureContract::ERC20(CairoVersion::Cairo0).get_class_hash(),
>             )
>         };
> ```

I think it is a bit cleaner this way



_Suggestion:_
```XML
    let (expected_actual_fee, expected_fee_transfer_call_info) =
        if tx_version == TransactionVersion::ZERO {
            (Fee(0), None)
        } else {
            let expected_actual_fee = actual_execution_info.receipt.resources.calculate_tx_fee(block_context, fee_type).unwrap();
            (
                expected_actual_fee,
                expected_fee_transfer_call_info(
                    tx_context,
                    sender_address,
                    expected_actual_fee,
                    FeatureContract::ERC20(CairoVersion::Cairo0).get_class_hash(),
                ),
            )
        };
```


<!-- Sent from Reviewable.io -->

2024-09-18 07:35 UTC, meship-starkware reviewed
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: all files reviewed, 5 unresolved discussions (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-09-22 04:44 UTC, meship-starkware reviewed
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-09-30 08:13 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 2 of 17 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O6zPniV4qZqljnAF210:-O79M5Ia2nzMayUMkW7Q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e790d8e0bce218f11663b16d4dd5c3dc7feaff1/crates/blockifier/src/concurrency/fee_utils.rs#L66)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Remove this code.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 362 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O6zQGlB-c6Gr29731Ib:-O80zSAI8Q8FTXTPA0IM:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e790d8e0bce218f11663b16d4dd5c3dc7feaff1/crates/blockifier/src/transaction/account_transaction.rs#L362)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Remove all aviv comments.
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1281 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O6zb00WAfSekGBeh5Ue:-O80zMoR-BJ1lnH6VJA7:b-896fjx) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e790d8e0bce218f11663b16d4dd5c3dc7feaff1/crates/blockifier/src/transaction/transactions_test.rs#L1281)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think it is a bit cleaner this way
</blockquote></details>

Done
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O6zQ-p2-j2kIgl5yrvx:-O79NAcj8_vZlMFYTp9L:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e790d8e0bce218f11663b16d4dd5c3dc7feaff1/crates/blockifier/src/fee/actual_cost.rs#L107)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Remove this code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-30 11:35 UTC, meship-starkware reviewed
> Reviewed 6 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 8 of 17 files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 1098 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O81cMweBCr0S2kJYH_V:-O81cMweBCr0S2kJYH_W:b-avnxf1) ([raw file](https://github.com/starkware-libs/sequencer/blob/5429911110e09c29105051681169ca732fa4b9f2/crates/starknet_api/src/transaction.rs#L1098)):*
> ```XML
>             l1_data_gas: ResourceBounds { max_amount: 0, max_price_per_unit: 1 },
>         };
>         Self::AllResources(resource_bounds)
> ```

Why is it part of this PR?



_Code quote:_
```XML
        // Self::L1Gas(ResourceBounds { max_amount: 0, max_price_per_unit: 1 })
        // Aviv: suggestion?
        let resource_bounds = AllResourceBounds {
            l1_gas: ResourceBounds { max_amount: 0, max_price_per_unit: 1 },
            l2_gas: ResourceBounds { max_amount: 0, max_price_per_unit: 1 },
            l1_data_gas: ResourceBounds { max_amount: 0, max_price_per_unit: 1 },
        };
        Self::AllResources(resource_bounds)
```


<!-- Sent from Reviewable.io -->

2024-09-30 16:30 UTC, avivg-starkware commented
*[`crates/blockifier/src/fee/actual_cost.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O6zcInDCJ83gRP8NfWS:-O82kr_f5uDv44Abc25r:b-gzofq9) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e790d8e0bce218f11663b16d4dd5c3dc7feaff1/crates/blockifier/src/fee/actual_cost.rs#L108)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please document this line
</blockquote></details>

Done - this is no longer in this file but rather in:
crates/blockifier/src/fee/receipt/.rs


<!-- Sent from Reviewable.io -->

2024-09-30 16:31 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 4 of 17 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 1098 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O81cMweBCr0S2kJYH_V:-O82k5Ve68qnz3cI5sJy:biofin6) ([raw file](https://github.com/starkware-libs/sequencer/blob/5429911110e09c29105051681169ca732fa4b9f2/crates/starknet_api/src/transaction.rs#L1098)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why is it part of this PR?
</blockquote></details>

found this while fixing conflicts, it is not necessary for the fix, but seemed right according to Nimrod's comment and the types. 


<!-- Sent from Reviewable.io -->

2024-10-01 05:21 UTC, meship-starkware requested changes
> Reviewed 1 of 15 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 6 of 17 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 546 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O85VWr39VF77bVRsrRH:-O85VWr39VF77bVRsrRI:b32he71) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c0701ca9f0d1985fd744dd868ed5f54d7a7a6d5/crates/blockifier/src/transaction/account_transactions_test.rs#L546)):*
> ```XML
>             sender_address: account_address,
>             calldata: create_calldata(
>                 test_contract_address,
> ```

I think it is better to use max_l1_resource_bounds as a fixture to be consistent with max_fee 



_Suggestion:_
```XML
fn test_revert_invoke(
    block_context: BlockContext,
    max_fee: Fee,
    max_resource_bounds: ValidResourceBounds,
    #[case] transaction_version: TransactionVersion,
    #[case] fee_type: FeeType,
) {
        &block_context,
        invoke_tx_args! {
            max_fee,
            resource_bounds: max_resource_bounds,
            sender_address: account_address,
            calldata: create_calldata(
                test_contract_address,
```


<!-- Sent from Reviewable.io -->

2024-10-01 05:21 UTC, meship-starkware reviewed
> Reviewed 4 of 15 files at r7, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-04 07:57 UTC, noaov1 requested changes
> Reviewed 1 of 9 files at r6, 2 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: all files reviewed, 4 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 60 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8H52kZ9fm2YM6_E_-t:-O8H52kZ9fm2YM6_E_-u:bbp8m82) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c0701ca9f0d1985fd744dd868ed5f54d7a7a6d5/crates/blockifier/src/concurrency/fee_utils.rs#L60)):*
> ```XML
>     } else {
>         let charge_fee = tx_context.tx_info.enforce_fee();
>         assert!(!charge_fee, "Transaction with no fee transfer info must have zero fee.")
> ```

Can be problematic if we allow setting the `charge_fee` flag to false when running transactions concurrently. 



_Suggestion:_
```XML
        // Assumes we set the charge fee flag to the transaction enforce fee value.
        let charge_fee = tx_context.tx_info.enforce_fee();
        assert!(!charge_fee, "Transaction with no fee transfer info must not enforced a fee charge.")
```
___
*[`crates/blockifier/src/fee/receipt.rs` line 97 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8LWLw_8bzbNHgk_W_m:-O8LWLw_8bzbNHgk_W_n:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c0701ca9f0d1985fd744dd868ed5f54d7a7a6d5/crates/blockifier/src/fee/receipt.rs#L97)):*
> ```XML
>         // To be backward compatible with the meaning of enforce fee in Declare V0.
>         let fee = if tx_type == TransactionType::Declare
>             && tx_context.tx_info.signed_version() == TransactionVersion::ZERO
> ```





_Suggestion:_
```XML
        // Backward-compatibility. 
        let fee = if tx_type == TransactionType::Declare
            && tx_context.tx_info.version() == TransactionVersion::ZERO
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 504 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8LWqjJAZhDvwiyLOA_:-O8LWqjJAZhDvwiyLOAa:b-6tiraw) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c0701ca9f0d1985fd744dd868ed5f54d7a7a6d5/crates/blockifier/src/transaction/account_transaction.rs#L504)):*
> ```XML
>     ) -> TransactionExecutionResult<Option<CallInfo>> {
>         if !charge_fee {
>             // Fee charging is not enforced in some transaction simulations and tests.
> ```

Please move it to where you set the `charge_fee` flag to be equal to the `enforce_fee` value.



_Code quote:_
```XML
            // Fee charging is not enforced in some transaction simulations and tests.
```


<!-- Sent from Reviewable.io -->

2024-10-06 06:11 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 3 of 20 files reviewed, 5 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`-- commits` line 3 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8VS2XE3wyUfbuypZ0h):*
Please rebase this PR


<!-- Sent from Reviewable.io -->

2024-10-06 09:45 UTC, meship-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 3 of 20 files reviewed, 6 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 333 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8WCudIAosaTp0cwvE7:-O8WCudIAosaTp0cwvE8:b-cu17ut) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d7f731227172ca6b6af3b0f878f5203eedf7597/crates/blockifier/src/transaction/test_utils.rs#L333)):*
> ```XML
>     account_invoke_tx(invoke_args).execute(state, block_context, charge_fee, true)
> >>>>>>> 4b0018270 (chore(blockifier): have charge_fee flag represent enforce_fee return value)
> }
> ```

Resolve this rebase conflict 



_Suggestion:_
```XML

    let tx = account_invoke_tx(invoke_args);
    let charge_fee = tx.enforce_fee();

    tx.execute(state, block_context, charge_fee, true)
}
```


<!-- Sent from Reviewable.io -->

2024-10-07 13:40 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 3 of 20 files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 60 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8H52kZ9fm2YM6_E_-t:-O8aqegx4fqydL3R9DCq:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c0701ca9f0d1985fd744dd868ed5f54d7a7a6d5/crates/blockifier/src/concurrency/fee_utils.rs#L60)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can be problematic if we allow setting the `charge_fee` flag to false when running transactions concurrently.
</blockquote></details>

Done
___
*[`crates/blockifier/src/fee/receipt.rs` line 97 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8LWLw_8bzbNHgk_W_m:-O8ar5TF8S4tFTwSDs2A:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c0701ca9f0d1985fd744dd868ed5f54d7a7a6d5/crates/blockifier/src/fee/receipt.rs#L97)):*
> ```XML
>         // To be backward compatible with the meaning of enforce fee in Declare V0.
>         let fee = if tx_type == TransactionType::Declare
>             && tx_context.tx_info.signed_version() == TransactionVersion::ZERO
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 504 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8LWqjJAZhDvwiyLOA_:-O8avuVNAgcJ0HCrFiHJ:b-x8473u) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c0701ca9f0d1985fd744dd868ed5f54d7a7a6d5/crates/blockifier/src/transaction/account_transaction.rs#L504)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please move it to where you set the `charge_fee` flag to be equal to the `enforce_fee` value.
</blockquote></details>

as it appears 9 times in the code I did the following:
I left the comment as it is. 
I added the comment in the following :
- worker_logic.rs -> fn execute_tx
- transaction_executor.rs -> fn execute
- test_utils -> fn run_invoke_tx

I didn't add in:
- the tests themselves ( 5 appearances)
- "fn perform_pre_validation_stage"
- "fn complete_fee_transfer_flow"

should I remove it here? should I add the comment someplace else? 

*easy way to find all relevant places is search: ".enforce_fee"


<!-- Sent from Reviewable.io -->

2024-10-07 14:23 UTC, meship-starkware requested changes
> Reviewed 17 of 17 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 1097 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8bMA8Q739yCzxrmtMu:-O8bMA8Q739yCzxrmtMv:bcs7u60) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6136a79c9545923b0415a1e6e3159bcb0be68d/crates/starknet_api/src/transaction.rs#L1097)):*
> ```XML
>     #[cfg(any(feature = "testing", test))]
>     pub fn create_for_testing() -> Self {
>         // Self::L1Gas(ResourceBounds { max_amount: 0, max_price_per_unit: 1 })
> ```

Please remove this comment 



_Code quote:_
```XML
 // Self::L1Gas(ResourceBounds { max_amount: 0, max_price_per_unit: 1 })
```


<!-- Sent from Reviewable.io -->

2024-10-08 09:12 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 10 of 20 files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`-- commits` line 3 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8VS2XE3wyUfbuypZ0h):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please rebase this PR
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 546 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O85VWr39VF77bVRsrRH:-O8bhscC5qkUCGFdJ74r:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c0701ca9f0d1985fd744dd868ed5f54d7a7a6d5/crates/blockifier/src/transaction/account_transactions_test.rs#L546)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think it is better to use max_l1_resource_bounds as a fixture to be consistent with max_fee
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 333 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8WCudIAosaTp0cwvE7:-O8f8j4G9tg5ZVemrv15:bujqfi5) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d7f731227172ca6b6af3b0f878f5203eedf7597/crates/blockifier/src/transaction/test_utils.rs#L333)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Resolve this rebase conflict
</blockquote></details>

resolved
___
*[`crates/starknet_api/src/transaction.rs` line 1097 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O8bMA8Q739yCzxrmtMu:-O8f9FtmA9Xje79FdAos:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6136a79c9545923b0415a1e6e3159bcb0be68d/crates/starknet_api/src/transaction.rs#L1097)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please remove this comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-08 12:19 UTC, meship-starkware reviewed
> Reviewed 9 of 10 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-08 12:20 UTC, meship-starkware approved these changes
> Reviewed 1 of 10 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-08 12:45 UTC, meship-starkware approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-13 06:31 UTC, meship-starkware approved these changes
> Reviewed 7 of 7 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-13 14:04 UTC, noaov1 requested changes
> Reviewed 2 of 17 files at r12, 5 of 7 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: all files reviewed, 6 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 101 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O959sj0882LDdqDW5TO:-O959sj0882LDdqDW5TP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/758a6c3ed6e6ff207b13451f8ad951dc82eb8906/crates/blockifier/src/blockifier/transaction_executor.rs#L101)):*
> ```XML
>             self.block_state.as_mut().expect(BLOCK_STATE_ACCESS_ERR),
>         );
>         // Fee charging is not enforced in some transaction simulations and tests.
> ```





_Suggestion:_
```XML
        // Fee charging is not enforced in some tests.
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 135 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O959yNs1f5AcWq84PC9:-O959yNt7kdNgDbWM5r9:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/758a6c3ed6e6ff207b13451f8ad951dc82eb8906/crates/blockifier/src/concurrency/worker_logic.rs#L135)):*
> ```XML
>         let mut tx_versioned_state = self.state.pin_version(tx_index);
>         let tx = &self.chunk[tx_index];
>         // Fee charging is not enforced in some transaction simulations and tests.
> ```





_Suggestion:_
```XML
        // Fee charging is not enforced in some tests.
```
___
*[`crates/blockifier/src/fee/receipt.rs` line 97 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O957F_M3ub0yLoVnp5D:-O957F_M3ub0yLoVnp5E:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/758a6c3ed6e6ff207b13451f8ad951dc82eb8906/crates/blockifier/src/fee/receipt.rs#L97)):*
> ```XML
>         // Backward-compatibility.
>         let fee = if tx_type == TransactionType::Declare
>             && tx_context.tx_info.version() == TransactionVersion::ZERO
> ```





_Suggestion:_
```XML
tx_context.tx_info.is_v0()
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 327 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O95A8Le91MjgDMy7JFO:-O95A8Le91MjgDMy7JFP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/758a6c3ed6e6ff207b13451f8ad951dc82eb8906/crates/blockifier/src/transaction/test_utils.rs#L327)):*
> ```XML
> ) -> TransactionExecutionResult<TransactionExecutionInfo> {
>     let tx = account_invoke_tx(invoke_args);
>     // Fee charging is not enforced in some transaction simulations and tests.
> ```





_Suggestion:_
```XML
    // Fee charging is not enforced in some tests.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1395 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O95AINx8fJ1oaWZTZyq:-O95AINx8fJ1oaWZTZyr:b483wyg) ([raw file](https://github.com/starkware-libs/sequencer/blob/758a6c3ed6e6ff207b13451f8ad951dc82eb8906/crates/blockifier/src/transaction/transactions_test.rs#L1395)):*
> ```XML
>     let fee_type = &account_tx.fee_type();
>     let tx_context = &block_context.to_tx_context(&account_tx);
>     let charge_fee = account_tx.enforce_fee();
> ```

Why is it needed now?



_Code quote:_
```XML
    let charge_fee = account_tx.enforce_fee();
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1412 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O95BMQE-DVJTt4bNN7u:-O95BMQE-DVJTt4bNN7v:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/758a6c3ed6e6ff207b13451f8ad951dc82eb8906/crates/blockifier/src/transaction/transactions_test.rs#L1412)):*
> ```XML
>     // Build expected fee transfer call info.
>     let (expected_actual_fee, expected_fee_transfer_call_info) =
>         if tx_context.tx_info.signed_version() == TransactionVersion::ZERO {
> ```





_Suggestion:_
```XML
 if tx_context.tx_info.is_v0()
```


<!-- Sent from Reviewable.io -->

2024-10-13 19:49 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 12 of 20 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1412 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O95BMQE-DVJTt4bNN7u:-O96NHeO5WL6CwTJEggQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/758a6c3ed6e6ff207b13451f8ad951dc82eb8906/crates/blockifier/src/transaction/transactions_test.rs#L1412)):*
> ```XML
>     // Build expected fee transfer call info.
>     let (expected_actual_fee, expected_fee_transfer_call_info) =
>         if tx_context.tx_info.signed_version() == TransactionVersion::ZERO {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-14 05:55 UTC, meship-starkware reviewed
> Reviewed 5 of 8 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-14 08:37 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1395 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O95AINx8fJ1oaWZTZyq:-O998yk85dCfmvBVdXgd:ba7l4ae) ([raw file](https://github.com/starkware-libs/sequencer/blob/758a6c3ed6e6ff207b13451f8ad951dc82eb8906/crates/blockifier/src/transaction/transactions_test.rs#L1395)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed now?
</blockquote></details>

for the case of V0 where charge_fee = false


<!-- Sent from Reviewable.io -->

2024-10-14 08:38 UTC, avivg-starkware commented
python PR: https://github.com/starkware-industries/starkware/pull/36062





<!-- Sent from Reviewable.io -->

2024-10-14 12:43 UTC, meship-starkware reviewed
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-14 13:19 UTC, noaov1 requested changes
> Reviewed 5 of 8 files at r16, 1 of 2 files at r17, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 468 at r19](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O9AAE7hBC1r2BP-4Iw3:-O9AAE7hBC1r2BP-4Iw4:b-sn0mu7) ([raw file](https://github.com/starkware-libs/sequencer/blob/3b2428e5bfdc89069b788fed95b2b0a0970df7ff/crates/blockifier/src/transaction/account_transaction.rs#L468)):*
> ```XML
>         if !charge_fee {
>             // Fee charging is not enforced in some tests.
>             return Ok(None);
> ```

I think we should revert this change. If the actual fee equals 0 there is no need to charge fee.
When can this happen?
Only in declare V0.
(and please leave here the "transaction simulation").



_Code quote:_
```XML
        if !charge_fee {
            // Fee charging is not enforced in some tests.
            return Ok(None);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1395 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O95AINx8fJ1oaWZTZyq:-O9A9BwY7uIZm4btiIYz:b-apayz0) ([raw file](https://github.com/starkware-libs/sequencer/blob/758a6c3ed6e6ff207b13451f8ad951dc82eb8906/crates/blockifier/src/transaction/transactions_test.rs#L1395)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

for the case of V0 where charge_fee = false
</blockquote></details>

See my comment above.


<!-- Sent from Reviewable.io -->

2024-10-15 14:10 UTC, avivg-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 11 of 20 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1395 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O95AINx8fJ1oaWZTZyq:-O9ELfzuCn5gFYNRF9_G:b-hfpv0l) ([raw file](https://github.com/starkware-libs/sequencer/blob/758a6c3ed6e6ff207b13451f8ad951dc82eb8906/crates/blockifier/src/transaction/transactions_test.rs#L1395)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

See my comment above.
</blockquote></details>

removed
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 468 at r19](https://reviewable.io/reviews/starkware-libs/sequencer/835#-O9AAE7hBC1r2BP-4Iw3:-O9FVufI52baDVsnBMyR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3b2428e5bfdc89069b788fed95b2b0a0970df7ff/crates/blockifier/src/transaction/account_transaction.rs#L468)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think we should revert this change. If the actual fee equals 0 there is no need to charge fee.
When can this happen?
Only in declare V0.
(and please leave here the "transaction simulation").
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-21 13:25 UTC, noaov1 reviewed
> Reviewed 8 of 8 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-10-22 07:47 UTC, noaov1 approved these changes
> Reviewed 3 of 3 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-10-29 11:05 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 8 files at r16, 3 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835#-:-OAMwrzr1rKkPVGPhAhW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-10-30 13:21 UTC, avivg-starkware reviewed
> Reviewed 1 of 9 files at r6, 2 of 15 files at r7, 3 of 17 files at r12, 5 of 10 files at r13, 1 of 8 files at r16, 4 of 8 files at r20, 1 of 3 files at r21, 1 of 3 files at r22, 2 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/835)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-10-30 13:21 UTC, merged