chore(mempool): add transaction queue content
starkware-libs/sequencer pull request #886
Opened 2024-09-19 11:26 UTC by MohammadNassar1

2024-09-19 12:13 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79Bqx16OxbKJTe2JQ6:-O79Bqx16OxbKJTe2JQ7:bketqfp) ([raw file](https://github.com/starkware-libs/sequencer/blob/74f7d98f822ece7113ace7713e0d4fa5beb349b7/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
> ```XML
>     priority_queue: Option<BTreeSet<PriorityTransaction>>,
>     pending_queue: Option<BTreeSet<PendingTransaction>>,
>     address_to_tx: Option<HashMap<ContractAddress, TransactionReference>>,
> ```

Why `address_to_tx` is part of the content?

The `TransactionQueueContent` is used to test the `TransactinoQueue` functionality.  
I think we need to check this field as well, as it can cover a potential bug. For example, when the pending/priority transaction queues are aligned, but for some reason, the `tx_to_address` is not.



_Code quote:_
```XML
 address_to_tx: Option<HashMap<ContractAddress, TransactionReference>>,
```


<!-- Sent from Reviewable.io -->

2024-09-19 12:17 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79C6375rjgupwqGzzN:-O79C6384uEq3Y7ZpycB:b-vijgj0) ([raw file](https://github.com/starkware-libs/sequencer/blob/74f7d98f822ece7113ace7713e0d4fa5beb349b7/crates/mempool/src/transaction_queue_test_utils.rs#L53)):*
> ```XML
>         P: IntoIterator<Item = TransactionReference> + Copy,
>     {
>         self._priority_queue = Some(priority_txs.into_iter().map(Into::into).collect());
> ```

Is `collect` needed?

Answer:
Yes, to collect an iterator to a set.



_Code quote:_
```XML
collect()
```


<!-- Sent from Reviewable.io -->

2024-09-21 20:41 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7LJBBF9NhdMf6v3jDn:-O7LJBBF9NhdMf6v3jDo:b7f3yr1) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa22513fc1e19c83b56cbd42a91b59181efeb/crates/mempool/src/transaction_queue_test_utils.rs#L35)):*
> ```XML
>         assert_eq!(self.pending_queue.as_ref().unwrap(), &tx_queue.pending_queue);
>         assert_eq!(self.address_to_tx.as_ref().unwrap(), &tx_queue.address_to_tx);
>     }
> ```

Why `gas_price_threshold` is not checked:
Since it's an input for the Mempool and there is no code within the Mempool that modifies its value.



_Code quote:_
```XML
    pub fn _assert_eq_priority_queue(&self, tx_queue: &TransactionQueue) {
        assert_eq!(self.priority_queue.as_ref().unwrap(), &tx_queue.priority_queue);
        assert_eq!(self.address_to_tx.as_ref().unwrap(), &tx_queue.address_to_tx);
    }

    pub fn _assert_eq_pending_queue(&self, tx_queue: &TransactionQueue) {
        assert_eq!(self.pending_queue.as_ref().unwrap(), &tx_queue.pending_queue);
        assert_eq!(self.address_to_tx.as_ref().unwrap(), &tx_queue.address_to_tx);
    }
```


<!-- Sent from Reviewable.io -->

2024-09-22 06:32 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79Bqx16OxbKJTe2JQ6:-O7NO7k5-tN4hYod6jtm:b-dc8sq3) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why `address_to_tx` is part of the content?

The `TransactionQueueContent` is used to test the `TransactinoQueue` functionality.  
I think we need to check this field as well, as it can cover a potential bug. For example, when the pending/priority transaction queues are aligned, but for some reason, the `tx_to_address` is not.
</blockquote></details>

Have we checked this until now?
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7LJBBF9NhdMf6v3jDn:-O7NODh1CR_3GoanMQvP:b-94f7uu) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa22513fc1e19c83b56cbd42a91b59181efeb/crates/mempool/src/transaction_queue_test_utils.rs#L35)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why `gas_price_threshold` is not checked:
Since it's an input for the Mempool and there is no code within the Mempool that modifies its value.
</blockquote></details>

Then why is it needed in the content?
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NQbz22TTfGF7yx1La:-O7NQbz22TTfGF7yx1Lb:bxxaio3) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L67)):*
> ```XML
>         P: IntoIterator<Item = TransactionReference>,
>     {
>         self._pending_queue = Some(pending_txs.into_iter().map(Into::into).collect());
> ```

Not clear, `from` is better.



_Code quote:_
```XML
Into::into
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NQPJE2Es6zTV7c1kD:-O7NQPJE2Es6zTV7c1kE:b-pehi6e) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L70)):*
> ```XML
>         self._address_to_tx.get_or_insert_with(HashMap::new).extend(
>             self._pending_queue.as_ref().unwrap().iter().map(|tx| (tx.sender_address, tx.0)),
>         );
> ```

Very unreadable + duplicated, there must be a better way.



_Code quote:_
```XML
        self._address_to_tx.get_or_insert_with(HashMap::new).extend(
            self._pending_queue.as_ref().unwrap().iter().map(|tx| (tx.sender_address, tx.0)),
        );
```


<!-- Sent from Reviewable.io -->

2024-09-22 06:35 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79Bqx16OxbKJTe2JQ6:-O7NR3aZ7IJVxUeeXG8d:b-5twmwk) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Have we checked this until now?
</blockquote></details>

It hasn't been checked until now, but I think it should be checked based on the reason I wrote above.


<!-- Sent from Reviewable.io -->

2024-09-22 06:36 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79Bqx16OxbKJTe2JQ6:-O7NRK5S6ZiPl-ZK9Qlo:bl3ps1h) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It hasn't been checked until now, but I think it should be checked based on the reason I wrote above.
</blockquote></details>

Are you sure it hasn't been checked until now?


<!-- Sent from Reviewable.io -->

2024-09-22 06:38 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7LJBBF9NhdMf6v3jDn:-O7NRQ1K69oYNy408_L4:b-tcp49u) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa22513fc1e19c83b56cbd42a91b59181efeb/crates/mempool/src/transaction_queue_test_utils.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Then why is it needed in the content?
</blockquote></details>

Assert for gas_price_threshold is not needed.
However, `with_gas_price_threshold` is necessary in the tests because we need to initialize a mempool with a specific gas price threshold in some tests.


<!-- Sent from Reviewable.io -->

2024-09-22 06:39 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79Bqx16OxbKJTe2JQ6:-O7NRy_l8f_jYqFIz-NQ:blv7ibr) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are you sure it hasn't been checked until now?
</blockquote></details>

Ooooh sorry,
it was checked here:



_Code snippet:_
```XML
    fn assert_eq_transaction_queue_content(&self, mempool: &Mempool) {
        assert_eq!(self.tx_queue.as_ref().unwrap(), &mempool.tx_queue);
    }
```


<!-- Sent from Reviewable.io -->

2024-09-22 07:09 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NQbz22TTfGF7yx1La:-O7NZ7YC5PnCwhICTe4C:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L67)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not clear, `from` is better.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NQPJE2Es6zTV7c1kD:-O7NWL6X35a3MsLxSZX_:b-cdfw1o) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L70)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Very unreadable + duplicated, there must be a better way.
</blockquote></details>

To make it more readable, I can split it into two lines.

For the duplication, I assume you mean the duplication with priority_queue code.
Note that priority queue hold different type of transactions, so 


<!-- Sent from Reviewable.io -->

2024-09-22 07:10 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NZCFq7LicGAPul27H:-O7NZCFq7LicGAPul27I:byqui72) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L47)):*
> ```XML
> 
> impl TransactionQueueContentBuilder {
>     pub fn _new() -> Self {
> ```

It's redundant, default can be used instead.



_Code quote:_
```XML
  pub fn _new() -> Self {
```


<!-- Sent from Reviewable.io -->

2024-09-22 07:11 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NQPJE2Es6zTV7c1kD:-O7NZPn4Azxs2VqZGFrZ:b-kv8j9j) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L70)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

To make it more readable, I can split it into two lines.

For the duplication, I assume you mean the duplication with priority_queue code.
Note that priority queue hold different type of transactions, so
</blockquote></details>

I solved it in a different way.
Please ignore the above comment.


<!-- Sent from Reviewable.io -->

2024-09-22 07:19 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NQPJE2Es6zTV7c1kD:-O7NZXUA37mBXJuo47z6:b-svarkc) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L70)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I solved it in a different way.
Please ignore the above comment.
</blockquote></details>

I've modified the code to enhance its readability.

The issue arises because the iterator input is of type `IntoIterator`, which implements `into_iter`. This takes ownership of the elements, which is necessary for moving the values into both the queue and `address_to_tx`.

The new solution first collects the transactions into a vector (which supports `iter`) and then uses this vector to populate both the queue and `address_to_tx`.

Although there’s still a single line of duplication, it now seems acceptable and keeps the code straightforward.


<!-- Sent from Reviewable.io -->

2024-09-22 07:22 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NVS6I28bBI5sJPahp:-O7NVS6J-PlRy1u3ys-u:br36ev0) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L9)):*
> ```XML
> use crate::transaction_queue::{PendingTransaction, PriorityTransaction, TransactionQueue};
> 
> // Utils.
> ```

Delete, the file contains only utils; please be mindful.



_Code quote:_
```XML
// Utils.
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7N_mLt6iLu73mIEuij:-O7N__j0-ZgK7SzPpZML:bmgpw56) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
> ```XML
>     priority_queue: Option<BTreeSet<PriorityTransaction>>,
>     pending_queue: Option<BTreeSet<PendingTransaction>>,
>     address_to_tx: Option<HashMap<ContractAddress, TransactionReference>>,
> ```

Repetitive, please alias.



_Code quote:_
```XML
HashMap<ContractAddress, TransactionReference>
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7N_p203ykAzyqk6_eL:-O7N_p203ykAzyqk6_eM:bu7rvs6) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
> ```XML
>     priority_queue: Option<BTreeSet<PriorityTransaction>>,
>     pending_queue: Option<BTreeSet<PendingTransaction>>,
>     address_to_tx: Option<HashMap<ContractAddress, TransactionReference>>,
> ```

Consider aliasing the types, at least the mapping type which is cumbersome.



_Code quote:_
```XML
    priority_queue: Option<BTreeSet<PriorityTransaction>>,
    pending_queue: Option<BTreeSet<PendingTransaction>>,
    address_to_tx: Option<HashMap<ContractAddress, TransactionReference>>,
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NafO74a7PtY4uvYFQ:-O7NafO74a7PtY4uvYFR:b2ernde) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
> ```XML
>     pub fn _assert_eq_priority_and_pending_queues(&self, tx_queue: &TransactionQueue) {
>         self._assert_eq_priority_queue(tx_queue);
>         self._assert_eq_pending_queue(tx_queue);
> ```

Address mapping is checked twice...



_Code quote:_
```XML
        self._assert_eq_priority_queue(tx_queue);
        self._assert_eq_pending_queue(tx_queue);
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NaV0c3yMctSstKNgi:-O7NaV0d16_16ZmpNVRQ:ben7mjf) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L27)):*
> ```XML
>     }
> 
>     pub fn _assert_eq_priority_queue(&self, tx_queue: &TransactionQueue) {
> ```

x3
Please be consistent with `MempoolContent` naming...



_Suggestion:_
```XML
priority_queue_content
```


<!-- Sent from Reviewable.io -->

2024-09-22 07:26 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 13 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7LJBBF9NhdMf6v3jDn:-O7NbEag4QevdmizcvuC:b-sixfws) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa22513fc1e19c83b56cbd42a91b59181efeb/crates/mempool/src/transaction_queue_test_utils.rs#L35)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Assert for gas_price_threshold is not needed.
However, `with_gas_price_threshold` is necessary in the tests because we need to initialize a mempool with a specific gas price threshold in some tests.
</blockquote></details>

Add a _succinct_ comment on why it isn't checked in the struct's docstring.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 51 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NbhQd5vlcES9GoM8F:-O7NbhQd5vlcES9GoM8G:bxhh86m) ([raw file](https://github.com/starkware-libs/sequencer/blob/d42f40a01a968088dd585fcf491053ec3c263928/crates/mempool/src/transaction_queue_test_utils.rs#L51)):*
> ```XML
>         P: IntoIterator<Item = TransactionReference>,
>     {
>         let priority_txs_vec: Vec<TransactionReference> = priority_txs.into_iter().collect();
> ```

As pointed out many times before, `variable_name_type` isn't a good practice since it overwhelms the reader with moot variables. Please shadow the input argument.



_Code quote:_
```XML
priority_txs_vec
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NbbHy2z1zJur34baV:-O7NbbHy2z1zJur34baW:b-muev5z) ([raw file](https://github.com/starkware-libs/sequencer/blob/d42f40a01a968088dd585fcf491053ec3c263928/crates/mempool/src/transaction_queue_test_utils.rs#L55)):*
> ```XML
>         self._address_to_tx
>             .get_or_insert_with(HashMap::new)
>             .extend(priority_txs_vec.iter().map(|tx| (tx.sender_address, *tx)));
> ```

I don't understand this line? Why not use same code as in `transaction_queue.rs`?



_Code quote:_
```XML
        self._address_to_tx
            .get_or_insert_with(HashMap::new)
            .extend(priority_txs_vec.iter().map(|tx| (tx.sender_address, *tx)));
```


<!-- Sent from Reviewable.io -->

2024-09-22 08:09 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7LJBBF9NhdMf6v3jDn:-O7NiubT80ouguwjv9fN:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa22513fc1e19c83b56cbd42a91b59181efeb/crates/mempool/src/transaction_queue_test_utils.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a _succinct_ comment on why it isn't checked in the struct's docstring.
</blockquote></details>

Done
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7N_mLt6iLu73mIEuij:-O7NcYCu6N1xNoSgSoXq:beajiy7) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Repetitive, please alias.
</blockquote></details>

Done.

This alias was added to `transaction_queue.rs` file. It was used there as well.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7N_p203ykAzyqk6_eL:-O7Nh1Ua5ss8JYkJPY35:b-6cjqz2) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider aliasing the types, at least the mapping type which is cumbersome.
</blockquote></details>

I've aliased the HashMap. I think priority and pending queues are clear.
Let me know what you think.

Also, `TransactionQueueContent` fields are aligned with the `TransactionQueue` struct.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NafO74a7PtY4uvYFQ:-O7Nduov-yYR09R1WD31:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Address mapping is checked twice...
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 51 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NbhQd5vlcES9GoM8F:-O7NkKFX3rvy01mgzEZ4:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d42f40a01a968088dd585fcf491053ec3c263928/crates/mempool/src/transaction_queue_test_utils.rs#L51)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

As pointed out many times before, `variable_name_type` isn't a good practice since it overwhelms the reader with moot variables. Please shadow the input argument.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-09-22 08:17 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NbbHy2z1zJur34baV:-O7NmYPtA37i3uCNsQx3:b-lyvvue) ([raw file](https://github.com/starkware-libs/sequencer/blob/d42f40a01a968088dd585fcf491053ec3c263928/crates/mempool/src/transaction_queue_test_utils.rs#L55)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I don't understand this line? Why not use same code as in `transaction_queue.rs`?
</blockquote></details>

Let me explain:

In the `transaction_queue.rs` code, we have a single case where we insert a single transaction; thus, we use `self.address_to_tx.insert`.

However, in this case, we have a vector of transactions, so I used `extend` to add all the transactions to the map at once.

The `get_or_insert_with` function ensures that if the map is empty, an empty map is initialized. If the map already contains entries (such as when `with_priority` and `with_pending` are both called), it prevents overwriting the existing transaction mappings.


<!-- Sent from Reviewable.io -->

2024-09-22 08:53 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79Bqx16OxbKJTe2JQ6:-O7NqNqv6oDWAXKR2CRM:b-cje83c) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
>I think we need to check this field as well, as it can cover a potential bug.

Bugs are always possible.
We test behavior and API, not implementation details, and certainly not implementation details of aux structs, unless we have a real good reason to do so.
I think you have another PR up right now where we had to give the same exact comment.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79C6375rjgupwqGzzN:-O7NuvAI6EQlvfD79iVs:b-r8xpv3) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L53)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Is `collect` needed?

Answer:
Yes, to collect an iterator to a set.
</blockquote></details>

This suffices, you don't need to convert priority_txs into a vector for this.
```rust
            .extend(priority_txs.clone().into_iter().map(|tx| (tx.sender_address, tx)));
```


<!-- Sent from Reviewable.io -->

2024-09-22 09:01 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7N_mLt6iLu73mIEuij:-O7Nx91TC9Y5LcrjyE8y:b-xj11ye) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.

This alias was added to `transaction_queue.rs` file. It was used there as well.
</blockquote></details>

No full type written anywhere, except for alias definition? Always make sure to mention to the reviewer you've went through all the codebase and made sure.


<!-- Sent from Reviewable.io -->

2024-09-22 09:10 UTC, elintul reviewed
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7Nyx8x1ZjBpAqXsfKs:-O7Nyx8x1ZjBpAqXsfKt:b-s4a9tn) ([raw file](https://github.com/starkware-libs/sequencer/blob/90e51e07bfb9e422f25f7857a71b5018e52098ea/crates/mempool/src/transaction_queue.rs#L15)):*
> ```XML
> use crate::mempool::TransactionReference;
> 
> type AddressToTransactionReference = HashMap<ContractAddress, TransactionReference>;
> ```

Should appear below sub-modules, as in all our code. Please be mindful.



_Code quote:_
```XML
type AddressToTransactionReference = HashMap<ContractAddress, TransactionReference>;
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NzBCOET_hKGZk89hI:-O7NzBCOET_hKGZk89hJ:b-p1z8om) ([raw file](https://github.com/starkware-libs/sequencer/blob/90e51e07bfb9e422f25f7857a71b5018e52098ea/crates/mempool/src/transaction_queue_test_utils.rs#L16)):*
> ```XML
> /// Enables customized (and potentially inconsistent) creation for unit testing.
> /// The `gas_price_threshold` is used for builing the struct, but it is not checked. This is because
> /// it's an input parameter for the Mempool, and no logic within the Mempool modifies its value.
> ```

Be succinct; and as mentioned before, refrain from using variable names in documentation.
Also, the second sentence is out of scope; a docstring should almost never refer to impl. details which most likely will become outdated, or other components. This was also discussed and pointed out in the past...



_Suggestion:_
```XML
// Note: gas price threshold is only used for builing the queue (non-test) struct.
```


<!-- Sent from Reviewable.io -->

2024-09-22 09:14 UTC, elintul requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: all files reviewed (commit messages unreviewed), 10 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79C6375rjgupwqGzzN:-O7O-CUw4S8djZYi5lxv:blw95dw) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L53)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This suffices, you don't need to convert priority_txs into a vector for this.
```rust
            .extend(priority_txs.clone().into_iter().map(|tx| (tx.sender_address, tx)));
```
</blockquote></details>

Right, you're only iterating; you can stay lazy in line 56.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7NbbHy2z1zJur34baV:-O7O-QErBjDUKTpoACpb:b-c9z8xh) ([raw file](https://github.com/starkware-libs/sequencer/blob/d42f40a01a968088dd585fcf491053ec3c263928/crates/mempool/src/transaction_queue_test_utils.rs#L55)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Let me explain:

In the `transaction_queue.rs` code, we have a single case where we insert a single transaction; thus, we use `self.address_to_tx.insert`.

However, in this case, we have a vector of transactions, so I used `extend` to add all the transactions to the map at once.

The `get_or_insert_with` function ensures that if the map is empty, an empty map is initialized. If the map already contains entries (such as when `with_priority` and `with_pending` are both called), it prevents overwriting the existing transaction mappings.
</blockquote></details>

Is there a simpler way? This line is cumbersome.
And again, it's duplicated.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 71 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7O-fof4mEQWAT1cesd:-O7O-fof4mEQWAT1cese:b-5d6hnk) ([raw file](https://github.com/starkware-libs/sequencer/blob/90e51e07bfb9e422f25f7857a71b5018e52098ea/crates/mempool/src/transaction_queue_test_utils.rs#L71)):*
> ```XML
>         P: IntoIterator<Item = TransactionReference>,
>     {
>         let pending_txs_vec: Vec<TransactionReference> = pending_txs.into_iter().collect();
> ```

Why is this still here? :(



_Code quote:_
```XML
pending_txs_vec
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 79 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7O-Zx46FSDfBUoXEG7:-O7O-Zx46FSDfBUoXEG8:blod2c3) ([raw file](https://github.com/starkware-libs/sequencer/blob/90e51e07bfb9e422f25f7857a71b5018e52098ea/crates/mempool/src/transaction_queue_test_utils.rs#L79)):*
> ```XML
>             Some(pending_txs_vec.into_iter().map(PendingTransaction::from).collect());
> 
>         self
> ```

Consistency, even in newlines.



_Suggestion:_
```XML
            Some(pending_txs_vec.into_iter().map(PendingTransaction::from).collect());
        self
```


<!-- Sent from Reviewable.io -->

2024-09-22 09:17 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: all files reviewed, 10 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-09-22 09:47 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7N_mLt6iLu73mIEuij:-O7O43bZ46qBF4Tym2wB:bemc433) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a3385a1ad388362f389f58b1d9bd4dd1727ca57/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No full type written anywhere, except for alias definition? Always make sure to mention to the reviewer you've went through all the codebase and made sure.
</blockquote></details>

You're right. 
I searched for `HashMap<ContractAddress, TransactionReference>`, and it seems it only appears in its definition and is not used elsewhere.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 71 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7O-fof4mEQWAT1cesd:-O7O4gr7BfnnjorhsgVJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/90e51e07bfb9e422f25f7857a71b5018e52098ea/crates/mempool/src/transaction_queue_test_utils.rs#L71)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this still here? :(
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-22 09:52 UTC, elintul requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7O89in1q_NL1WFmmMh:-O7O89in1q_NL1WFmmMi:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/64541b61e2b8cb7a8b26c378f9962cdb44d22131/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
> ```XML
> /// Note: gas price threshold is only used for builing the queue (non-test) struct.
> /// The `gas_price_threshold` is used for builing the struct, but it is not checked. This is because
> /// it's an input parameter for the Mempool, and no logic within the Mempool modifies its value.
> ```





_Suggestion:_
```XML
/// Note: gas price threshold is only used for builing the queue (non-test) struct.
```


<!-- Sent from Reviewable.io -->

2024-09-22 10:03 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79Bqx16OxbKJTe2JQ6:-O7O9Jsi04bzXFi52afm:brt3wkc) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>I think we need to check this field as well, as it can cover a potential bug.

Bugs are always possible.
We test behavior and API, not implementation details, and certainly not implementation details of aux structs, unless we have a real good reason to do so.
I think you have another PR up right now where we had to give the same exact comment.
</blockquote></details>

I'm not sure I fully understand your point. 

The `address_to_tx` field is checked, but I didn't create a specific utility, builder, or assertion for it. Instead, it's asserted as part of the transaction assertions. These lines:



_Code snippet:_
```XML
        assert_eq!(self.priority_queue.as_ref().unwrap(), &tx_queue.priority_queue);
        assert_eq!(self.pending_queue.as_ref().unwrap(), &tx_queue.pending_queue);
        assert_eq!(self.address_to_tx.as_ref().unwrap(), &tx_queue.address_to_tx);
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O7O89in1q_NL1WFmmMh:-O7OAqcIDDlP5ILTQpFB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/64541b61e2b8cb7a8b26c378f9962cdb44d22131/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
> ```XML
> /// Note: gas price threshold is only used for builing the queue (non-test) struct.
> /// The `gas_price_threshold` is used for builing the struct, but it is not checked. This is because
> /// it's an input parameter for the Mempool, and no logic within the Mempool modifies its value.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-22 10:05 UTC, elintul reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79Bqx16OxbKJTe2JQ6:-O7OBAV75g21xt8zBX9C:bgw1vuh) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I'm not sure I fully understand your point. 

The `address_to_tx` field is checked, but I didn't create a specific utility, builder, or assertion for it. Instead, it's asserted as part of the transaction assertions. These lines:
</blockquote></details>

I think what Gilad means, is that this mapping is implicitly tested in many tests we have, and there's no need to over-complicate this test util.


<!-- Sent from Reviewable.io -->

2024-09-22 10:11 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79Bqx16OxbKJTe2JQ6:-O7OCFV72o7B9xPd31Nl:bry30u6) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think what Gilad means, is that this mapping is implicitly tested in many tests we have, and there's no need to over-complicate this test util.
</blockquote></details>

Oooh, Could you please point out such a test?
I see all the tests in `mempool_test` use the `mempool_content` assertion, which uses the `transaction_queue_content.`


<!-- Sent from Reviewable.io -->

2024-09-22 10:24 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/886)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/886#-O79Bqx16OxbKJTe2JQ6:-O7OEgI29xKbKrrr4Lif:bz6onh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/5435ac4aa3d36be411b16c146462e73baa1fd413/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Oooh, Could you please point out such a test?
I see all the tests in `mempool_test` use the `mempool_content` assertion, which uses the `transaction_queue_content.`
</blockquote></details>

Every test that touches the Q also checks this mapping; in case it isn't consistent with the Qs we'd have much bigger problems. Please see if you can get convinced of this independently, and share your opinion.
Note I'm not necessarily saying you need to go with a specific direction, I'm asking you to mitigate the thought process, as the code writer; this should not be a discussion in the PR, and should have happened prior to it.


<!-- Sent from Reviewable.io -->

2024-09-23 13:39 UTC, closed without merging