WIP
starkware-libs/sequencer pull request #918
Opened 2024-09-22 09:29 UTC by amosStarkware

2024-09-22 12:13 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: 0 of 4 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1946 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7OdX541cgojPyuk60W:-O7OdX541cgojPyuk60X:bd31bsx) ([raw file](https://github.com/starkware-libs/sequencer/blob/f45fc68e6ddc473361db4e6740c9968a72d07abc/crates/blockifier/src/transaction/transactions_test.rs#L1946)):*
> ```XML
>             true => GasVector { l1_gas: 16023, l1_data_gas: 128, l2_gas: 25 },
>             false => GasVector { l1_gas: 17675, l1_data_gas: 0, l2_gas: 25 },
>         },
> ```

I copied these values from the expected values (i.e., I ran the test, it failed, and I copied the expected values)



_Code quote:_
```XML
        GasVectorComputationMode::All => match use_kzg_da {
            true => GasVector { l1_gas: 16023, l1_data_gas: 128, l2_gas: 25 },
            false => GasVector { l1_gas: 17675, l1_data_gas: 0, l2_gas: 25 },
        },
```


<!-- Sent from Reviewable.io -->

2024-09-22 12:52 UTC, amosStarkware reviewed
+reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918#-:-O7Om_NF1RSZIw75hvga:b-hz3kb8)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-22 14:09 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7P3Ie-7Ou1dmNma6ar):*
should I add L2 gas test cases to any more tests?



_Code quote:_
```
New commits in r1 on 22/09/2024 at 15:11:
```


<!-- Sent from Reviewable.io -->

2024-09-23 10:31 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/receipt_test.rs` line 441 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7P95x322BrZARx5J9F:-O7P95x4-mqqChWn8M_5:bemnbvy) ([raw file](https://github.com/starkware-libs/sequencer/blob/f45fc68e6ddc473361db4e6740c9968a72d07abc/crates/blockifier/src/fee/receipt_test.rs#L441)):*
> ```XML
>         None,
>         // The transfer entrypoint emits an event - pass the call info to count its resources.
>         execution_call_info_iter,
> ```

This wasn't needed until now because in the `NoL2Gas`  computation mode it was rounded to zero



_Code quote:_
```XML
        // The transfer entrypoint emits an event - pass the call info to count its resources.
        execution_call_info_iter,
```


<!-- Sent from Reviewable.io -->

2024-09-23 13:54 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1887 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7U7jRhCtdGUAeRi1Mn:-O7U7jRi-Jf_WV5CzjYK:b-2hysd1) ([raw file](https://github.com/starkware-libs/sequencer/blob/f45fc68e6ddc473361db4e6740c9968a72d07abc/crates/blockifier/src/transaction/transactions_test.rs#L1887)):*
> ```XML
> 
> #[rstest]
> fn test_l1_handler(
> ```

this is probably out of bounds for this PR, but I already did it so makes sense to add it



_Code quote:_
```XML
fn test_l1_handler(
```


<!-- Sent from Reviewable.io -->

2024-09-24 15:10 UTC, amosStarkware reviewed
+reviewer:@aner-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918#-:-O7Z_LQ_7x-MiskiD8bq:b7ntang)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-26 08:03 UTC, aner-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7czx5I-i4PUk2Mf9e1:-O7czx5JA6fIdfGWkYMH:bml34k8) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/gas_usage_test.rs#L89)):*
> ```XML
>     let call_infos_iter = call_infos.iter();
>     // 8 keys and 11 data words overall.
>     let expected = (data_word_cost * (event_key_factor * 8_u128 + 11_u128)).to_integer();
> ```

expected what?



_Code quote:_
```XML
 expected 
```


<!-- Sent from Reviewable.io -->

2024-09-26 08:04 UTC, aner-starkware reviewed
Blocking until reviwed by @dorimedini-starkware .

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918#-:-O7hLxXT3pcpriQQGuh1:b-5q7vog)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-26 08:42 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7czx5I-i4PUk2Mf9e1:-O7hUdzBAisdpgaRwgVb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/gas_usage_test.rs#L89)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

expected what?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-26 09:54 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: all files reviewed, 12 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7P3Ie-7Ou1dmNma6ar):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

should I add L2 gas test cases to any more tests?
</blockquote></details>

check usages of `max_l1_resource_bounds`, these tests should all probably migrate to using `All` bounds
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSQqzBLnxj8EnRemM:-O7hSQqzBLnxj8EnRemN:bg3ic1v) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L79)):*
> ```XML
>             std::iter::empty(),
>         );
>         let code_gas_cost = (versioned_constants.archival_data_gas_costs.gas_per_code_byte
> ```

why do you take the L2 archival data gas costs in both gas computation modes?



_Code quote:_
```XML
let code_gas_cost = (versioned_constants.archival_data_gas_costs.gas_per_code_byte
```
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSXz_5BNbQJ8U1TiC:-O7hSXz_5BNbQJ8U1TiD:b-l8l7r9) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L121)):*
> ```XML
>     );
>     let calldata_and_signature_gas_cost =
>         (versioned_constants.archival_data_gas_costs.gas_per_data_felt
> ```

same question



_Code quote:_
```XML
archival_data_gas_costs
```
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hS_gM49OKxFU6y8p8:-O7hS_gM49OKxFU6y8p9:b-l8l7r9) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L161)):*
> ```XML
>     let message_segment_length = get_message_segment_length(&[], Some(l1_handler_payload_size));
>     let calldata_and_signature_gas_cost =
>         (versioned_constants.archival_data_gas_costs.gas_per_data_felt
> ```

same question



_Code quote:_
```XML
archival_data_gas_costs
```
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSoIQ8iP-tCz48OKN:-O7hSoIQ8iP-tCz48OKO:b-hac8oc) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L185)):*
> ```XML
>         + manual_starknet_l1_gas_usage_vector
>         + calldata_and_signature_gas_cost_vector;
>     assert_eq!(l1_handler_gas_usage_vector, manual_gas_computation);
> ```

L1 handlers cannot consume L1 gas? this test looks like you never expect an L2 cost



_Code quote:_
```XML
    // Manual calculation.
    let message_segment_length = get_message_segment_length(&[], Some(l1_handler_payload_size));
    let calldata_and_signature_gas_cost =
        (versioned_constants.archival_data_gas_costs.gas_per_data_felt
            * u128_from_usize(l1_handler_payload_size + signature_length))
        .to_integer();
    let calldata_and_signature_gas_cost_vector = match gas_vector_computation_mode {
        GasVectorComputationMode::NoL2Gas => GasVector::from_l1_gas(
            (versioned_constants.get_l1_to_l2_gas_price_ratio() * calldata_and_signature_gas_cost)
                .to_integer(),
        ),
        GasVectorComputationMode::All => GasVector::from_l2_gas(calldata_and_signature_gas_cost),
    };
    let manual_starknet_l1_gas_usage = message_segment_length
        * eth_gas_constants::GAS_PER_MEMORY_WORD
        + eth_gas_constants::GAS_PER_COUNTER_DECREASE
        + usize_from_u128(
            get_consumed_message_to_l2_emissions_cost(Some(l1_handler_payload_size)).l1_gas,
        )
        .unwrap();
    let manual_starknet_l1_gas_usage_vector =
        GasVector::from_l1_gas(u128_from_usize(manual_starknet_l1_gas_usage));
    let manual_sharp_gas_usage =
        message_segment_length * eth_gas_constants::SHARP_GAS_PER_MEMORY_WORD;
    let manual_gas_computation = GasVector::from_l1_gas(u128_from_usize(manual_sharp_gas_usage))
        + manual_starknet_l1_gas_usage_vector
        + calldata_and_signature_gas_cost_vector;
    assert_eq!(l1_handler_gas_usage_vector, manual_gas_computation);
```
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 341 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSyLoEW6IMeWWg2qC:-O7hSyLoEW6IMeWWg2qD:b-hj99te) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L341)):*
> ```XML
> // in the state changes.
> // TODO(Nimrod, 1/5/2024): Test regression w.r.t. all resources (including VM). (Only starknet
> // resources are taken into account).
> ```

this TODO is also completed here, right? delete it please



_Code quote:_
```XML
// TODO(Nimrod, 1/5/2024): Test regression w.r.t. all resources (including VM). (Only starknet
// resources are taken into account).
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hj9Xw4OpH7Gcuevcy:-O7hj9Xw4OpH7Gcuevcz:btfsa7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L96)):*
> ```XML
> 
> #[fixture]
> pub fn max_l1_resource_bounds() -> ValidResourceBounds {
> ```

will this fixture be removed in the future? it really shouldn't be used, either explicitly state the mode or use `All` by default



_Code quote:_
```XML
#[fixture]
pub fn max_l1_resource_bounds() -> ValidResourceBounds {
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hj-XK9v9mbc8yD6uR:-O7hj-XK9v9mbc8yD6uS:b-9azgo2) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L97)):*
> ```XML
> #[fixture]
> pub fn max_l1_resource_bounds() -> ValidResourceBounds {
>     l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE)
> ```

reuse code



_Suggestion:_
```XML
get_resource_bounds(&GasVectorComputationMode::L1Gas)
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hiuXl4_WX_BO5A5Xd:-O7hiuXl4_WX_BO5A5Xe:baj1114) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L100)):*
> ```XML
> }
> 
> pub fn get_resource_bounds(computation_mode: &GasVectorComputationMode) -> ValidResourceBounds {
> ```

you are creating, not getting



_Suggestion:_
```XML
max_resource_bounds
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 350 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hjSuA789X7BDc8m4z:-O7hjSuA789X7BDc8m5-:bcs0lp8) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L350)):*
> ```XML
> }
> 
> fn get_all_resource_bounds(
> ```

not a getter



_Suggestion:_
```XML
construct
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1947 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hjjBF1MZmmzcpHSVe:-O7hjjBF1MZmmzcpHSVf:b-ka71uf) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/transactions_test.rs#L1947)):*
> ```XML
>             fa [...]

2024-09-26 10:42 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: all files reviewed, 12 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1947 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hjjBF1MZmmzcpHSVe:-O7hvGJH1HsAYeSc6pE6:b5smy4n) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/transactions_test.rs#L1947)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

seems nicer
</blockquote></details>

oops... `== GasVectorComputationMode::All`


<!-- Sent from Reviewable.io -->

2024-09-26 11:43 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: 1 of 5 files reviewed, 12 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7P3Ie-7Ou1dmNma6ar):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

check usages of `max_l1_resource_bounds`, these tests should all probably migrate to using `All` bounds
</blockquote></details>

But that is out of scope for this PR, no? the goal of this PR is to add unit tests for StarknetResources::to_gas_vector().
I can add a ticket for this
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSQqzBLnxj8EnRemM:-O7hyZL683uHjvf_huZg:bedwkfl) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you take the L2 archival data gas costs in both gas computation modes?
</blockquote></details>

I removed the conversion to L1 gas (i.e., removed this:
`* versioned_constants.get_l1_to_l2_gas_price_ratio()`
), and I assumed the value will be in L2 gas.
so the question is why did the test originally compute L2 gas in the first place, right? @aner-starkware do you know?
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSoIQ8iP-tCz48OKN:-O7i-q6l4jb-VuaXsHzN:bdzrtjq) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L185)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

L1 handlers cannot consume L1 gas? this test looks like you never expect an L2 cost
</blockquote></details>

`calldata_and_signature_gas_cost_vector` includes L2 gas, if the gas computation mode is `All`.
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 341 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSyLoEW6IMeWWg2qC:-O7i0Wiz072JWgYzS_SE:b-r7p841) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L341)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this TODO is also completed here, right? delete it please
</blockquote></details>

I don't think it's completed -
I didn't add VM resources here. also, this isn't a regression test, so I'm not sure what he means by regression here.
maybe the [regression test](https://reviewable.io/reviews/starkware-libs/sequencer/968) I added, that includes all resources, completes this TODO?
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hj9Xw4OpH7Gcuevcy:-O7i102069iw_gvTZTBR:b-jzn566) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L96)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

will this fixture be removed in the future? it really shouldn't be used, either explicitly state the mode or use `All` by default
</blockquote></details>

that's why I renamed to `max_l1_resource_bounds`, doesn't that fill that requirement?
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hj-XK9v9mbc8yD6uR:-O7i22EF2OXKa85P_xtl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reuse code
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hiuXl4_WX_BO5A5Xd:-O7i27uT9suP1elKi_yl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L100)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are creating, not getting
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 350 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hjSuA789X7BDc8m4z:-O7i2OmV5qlCqs5kfApj:b-csntii) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L350)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not a getter
</blockquote></details>

`create`?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1947 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hjjBF1MZmmzcpHSVe:-O7i4rHW4xsWi8rDnbqj:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/transactions_test.rs#L1947)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

oops... `== GasVectorComputationMode::All`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-09-26 11:46 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7P3Ie-7Ou1dmNma6ar):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

But that is out of scope for this PR, no? the goal of this PR is to add unit tests for StarknetResources::to_gas_vector().
I can add a ticket for this
</blockquote></details>

ah, I thought you were asking which tests need updating... please open a monday item to go over tests that use `max_l1_resource_bounds`
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 341 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSyLoEW6IMeWWg2qC:-O7i8c5O9vXEfbAQVnXf:b9p03e3) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L341)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I don't think it's completed -
I didn't add VM resources here. also, this isn't a regression test, so I'm not sure what he means by regression here.
maybe the [regression test](https://reviewable.io/reviews/starkware-libs/sequencer/968) I added, that includes all resources, completes this TODO?
</blockquote></details>

ah... gotcha
TODO is indeed not complete without VM resources
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hj9Xw4OpH7Gcuevcy:-O7i8kSz3wnEJLwTBmHC:b-rg9bdd) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L96)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

that's why I renamed to `max_l1_resource_bounds`, doesn't that fill that requirement?
</blockquote></details>

I am saying: tests shouldn't use this fixture because it's deprecated (no data gas bounds).
need a TODO here to delete it - if you want only L1 bounds you should be explicit in the test IMO
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hiuXl4_WX_BO5A5Xd:-O7i82rpA2dByToa1Vx0:b-jlv1vv) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L100)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are creating, not getting
</blockquote></details>

I would name it `max` because you are setting max values, not creating a general instance (there is a different function for that later in this PR IIRC)


<!-- Sent from Reviewable.io -->

2024-09-26 13:14 UTC, aner-starkware commented
*[`crates/blockifier/src/fee/receipt_test.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSQqzBLnxj8EnRemM:-O7iSjw33htsuCApcdwk:b871tgp) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L79)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I removed the conversion to L1 gas (i.e., removed this:
`* versioned_constants.get_l1_to_l2_gas_price_ratio()`
), and I assumed the value will be in L2 gas.
so the question is why did the test originally compute L2 gas in the first place, right? @aner-starkware do you know?
</blockquote></details>

When was it changed? Maybe it's part of Nimrod's PR, where he changed the computation to be through L2 in both cases?


<!-- Sent from Reviewable.io -->

2024-09-27 08:22 UTC, aner-starkware approved these changes
Unblocking.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918#-:-O7mZnsSCPEphVLgHeUa:bngpot7)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-09-29 08:49 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7P3Ie-7Ou1dmNma6ar):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, I thought you were asking which tests need updating... please open a monday item to go over tests that use `max_l1_resource_bounds`
</blockquote></details>

Done
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSQqzBLnxj8EnRemM:-O7wouGT67z5PLBGo4Eq:b3lt9x6) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L79)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

When was it changed? Maybe it's part of Nimrod's PR, where he changed the computation to be through L2 in both cases?
</blockquote></details>

File was recently renamed so I can't see. anyway, fixed
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hSXz_5BNbQJ8U1TiC:-O7wp2Qg6MnReezyTU6o:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same question
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hS_gM49OKxFU6y8p8:-O7wp3L85IhkAeFShZJA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/fee/receipt_test.rs#L161)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same question
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hj9Xw4OpH7Gcuevcy:-O7wpY7E24iYeWYEWDE7:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L96)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I am saying: tests shouldn't use this fixture because it's deprecated (no data gas bounds).
need a TODO here to delete it - if you want only L1 bounds you should be explicit in the test IMO
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hiuXl4_WX_BO5A5Xd:-O7wrR1nC1GPPxwkBsUT:b7b4mnv) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L100)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would name it `max` because you are setting max values, not creating a general instance (there is a different function for that later in this PR IIRC)
</blockquote></details>

not all are max values


<!-- Sent from Reviewable.io -->

2024-09-29 12:36 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7P3Ie-7Ou1dmNma6ar):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

oops... i also [created one](https://starkware.monday.com/boards/6987445459/pulses/7524892471), can you delete one of them?
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 88 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7xl9Eu1StEyMgR4Hpk:-O7xl9Eu1StEyMgR4Hpl:bdjpmmp) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0ef351c6f587f974dd3a827fded1cb07450ebc/crates/blockifier/src/fee/receipt_test.rs#L88)):*
> ```XML
>                 versioned_constants.archival_data_gas_costs.gas_per_code_byte
>             }
>         };
> ```

this method is from 5 days ago, please use it where relevant (IIRC there are similar `match`es in this PR?)



_Suggestion:_
```XML
        let gas_per_code_byte = versioned_constants.get_archival_data_gas_costs(
            gas_vector_computation_mode
        ).gas_per_code_byte;
```
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 135 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7xlUkH-hKZF5gI4zWx:-O7xlUkH-hKZF5gI4zWy:b-r1o7bk) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0ef351c6f587f974dd3a827fded1cb07450ebc/crates/blockifier/src/fee/receipt_test.rs#L135)):*
> ```XML
>             versioned_constants.archival_data_gas_costs.gas_per_data_felt
>         }
>     };
> ```

use `get_archival_data_gas_costs` (see above)



_Code quote:_
```XML
    let gas_per_data_felt = match gas_vector_computation_mode {
        GasVectorComputationMode::NoL2Gas => {
            versioned_constants.deprecated_l2_resource_gas_costs.gas_per_data_felt
        }
        GasVectorComputationMode::All => {
            versioned_constants.archival_data_gas_costs.gas_per_data_felt
        }
    };
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7hj9Xw4OpH7Gcuevcy:-O7xlomw71iVjQcd8vOs:bw1eai0) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a90c244f042e49a01f6c620833a0196566bf445/crates/blockifier/src/transaction/test_utils.rs#L96)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

[monday tracking](https://starkware.monday.com/boards/6987445459/pulses/7524892471)


<!-- Sent from Reviewable.io -->

2024-09-29 14:30 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7P3Ie-7Ou1dmNma6ar):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

oops... i also [created one](https://starkware.monday.com/boards/6987445459/pulses/7524892471), can you delete one of them?
</blockquote></details>

Done
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 88 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7xl9Eu1StEyMgR4Hpk:-O7y8g36A63ri5pglNeJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0ef351c6f587f974dd3a827fded1cb07450ebc/crates/blockifier/src/fee/receipt_test.rs#L88)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this method is from 5 days ago, please use it where relevant (IIRC there are similar `match`es in this PR?)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 135 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/918#-O7xlUkH-hKZF5gI4zWx:-O7y8htXERcchiMFujog:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0ef351c6f587f974dd3a827fded1cb07450ebc/crates/blockifier/src/fee/receipt_test.rs#L135)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `get_archival_data_gas_costs` (see above)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-29 14:31 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/918#-:-O7yBNp461q8DIefyND4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-09-29 14:48 UTC, merged