feat(batcher): implement build_block() for block_builder
starkware-libs/sequencer pull request #929
Opened 2024-09-22 13:08 UTC by Yael-Starkware

2024-09-24 10:39 UTC, dafnamatsry requested changes
> Reviewed 1 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 1 of 15 files reviewed, 17 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YXb9s4BW32NkrBORn:-O7YXb9s4BW32NkrBORo:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L40)):*
> ```XML
> pub struct BlockBuilder {
>     executor: Box<dyn BlockifierTransactionExecutorTrait>,
>     pub txs_chunk_size: usize,
> ```





_Suggestion:_
```XML
// The block builder will execute transactions in chunks. This specifies the size of each chunk.
pub tx_chunk_size: usize,
```
___
*[`crates/batcher/src/block_builder.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YY8XB2FYoiaxp_grN:-O7YY8XB2FYoiaxp_grO:b-oxdz5m) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L48)):*
> ```XML
>     BadTimestamp(#[from] std::num::TryFromIntError),
>     #[error("No transactions sent.")]
>     NoTransactions,
> ```

When will this be returned?
I don't see it used in this PR, please add it only when needed.



_Code quote:_
```XML
    #[error("No transactions sent.")]
    NoTransactions,
```
___
*[`crates/batcher/src/block_builder.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YWvLu7Rvze6RGyZ5L:-O7YWvLu7Rvze6RGyZ5M:b-bwwtas) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L67)):*
> ```XML
>     pub sequencer_address: ContractAddress,
>     pub use_kzg_da: bool,
>     pub txs_chunk_size: usize,
> ```

Can be removed?
Not sure where it is used, and it is also defined as a member of `BlockBuilder`.



_Code quote:_
```XML
pub txs_chunk_size: usize,
```
___
*[`crates/batcher/src/block_builder.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7Yaudp5AUVHapaDBBv:-O7Yaudp5AUVHapaDBBw:bxyfp88) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L116)):*
> ```XML
>             // TODO(Yael 18/9/2024): dont forget to flush the cached_state cache into the global
>             // cache on decision_reached.
>             execution_params.global_class_hash_to_class.clone(),
> ```

why clone and not move?



_Code quote:_
```XML
.clone()
```
___
*[`crates/batcher/src/block_builder.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YHdZ33fhrQxa_9xYO:-O7YHdZ33fhrQxa_9xYP:b-aiw9p8) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L134)):*
> ```XML
>         &mut self,
>         deadline: tokio::time::Instant,
>         mempool_tx_stream: impl Stream<Item = Transaction> + 'a,
> ```

Why do we need this lifetime?



_Code quote:_
```XML
 + 'a
```
___
*[`crates/batcher/src/block_builder.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YJqnk8BazcOFZpQ0x:-O7YJqnk8BazcOFZpQ0y:b-78h41j) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L138)):*
> ```XML
>     ) -> BlockBuilderResult<BlockExecutionArtifacts> {
>         let mut execution_infos = HashMap::new();
>         tokio::pin!(mempool_tx_stream);
> ```

If we accept a `Box<Pin<impl Stream...>>`, can we remove this line?
what about [`BoxStream`](https://docs.rs/futures/latest/futures/stream/type.BoxStream.html)?



_Code quote:_
```XML
tokio::pin!(mempool_tx_stream);
```
___
*[`crates/batcher/src/block_builder.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YQPW24emRtnsBH9vl:-O7YQPW24emRtnsBH9vm:b-6cogiy) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L140)):*
> ```XML
>         tokio::pin!(mempool_tx_stream);
>         let mut close_block = false;
>         while !close_block && tokio::time::Instant::now() < deadline {
> ```

Did we want to make the blockifier/bouncer deal with the time?
maybe add a todo if this is the case.



_Code quote:_
```XML
< deadline
```
___
*[`crates/batcher/src/block_builder.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YUwbR26YIq33Vv8uI:-O7YUwbR26YIq33Vv8uJ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L141)):*
> ```XML
>         let mut close_block = false;
>         while !close_block && tokio::time::Instant::now() < deadline {
>             let txs_chunk = self.get_txs_chunk(&mut mempool_tx_stream).await?;
> ```





_Suggestion:_
```XML
let tx_chunk = self.get_tx_chunk(&mut mempool_tx_stream).await?;
```
___
*[`crates/batcher/src/block_builder.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YVP_R2QxrZwUm0rNo:-O7YVP_R2QxrZwUm0rNp:b-y8cfwo) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L159)):*
> ```XML
>                             close_block = true;
>                         }
>                         _ => {
> ```

What type of errors can happen here?
What is returned in reverted/rejected txs?



_Code quote:_
```XML
 _ => {
```
___
*[`crates/batcher/src/block_builder.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YZLP09fKT6QrrzzlX:-O7YZLP1EB9_bTE-PwOp:b-p4igaa) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L185)):*
> ```XML
>         let mut txs_in_blockifier_format = Vec::new();
>         let mut txs_in_mempool_format = Vec::new();
>         tokio::pin!(mempool_tx_stream);
> ```

Do we need this if the type is `Pin<...>`?



_Code quote:_
```XML
tokio::pin!(mempool_tx_stream);
```
___
*[`crates/batcher/src/block_builder.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7Yb7Mk6Cbve4b5pD0k:-O7Yb7Mk6Cbve4b5pD0l:b-afxc9t) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L191)):*
> ```XML
>                 // is ready
>                 Some(mempool_tx) => {
>                     txs_in_mempool_format.push(mempool_tx.clone());
> ```

why clone?



_Code quote:_
```XML
.clone()
```
___
*[`crates/batcher/src/block_builder.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YJI3KBt0iT8blvaBa:-O7YJI3KBt0iT8blvaBb:b26xx3r) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L197)):*
> ```XML
>                     txs_in_blockifier_format.push(blockifier_tx);
>                 }
>                 // TODO: if None, should I give it another shot? should return error?
> ```

I think `None` means the stream is over, so no point in giving it another chance.



_Code quote:_
```XML
// TODO: if None, should I give it another shot? should return error?
```
___
*[`crates/batcher/src/block_builder.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7Y_mvP75G_e9wh4BFX:-O7Y_mvP75G_e9wh4BFY:bchenhu) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L202)):*
> ```XML
>                 }
>             }
>         }
> ```

Add an assertion that both vectors have the same length.
___
*[`crates/batcher/src/block_builder.rs` line  [...]

2024-09-24 10:43 UTC, dafnamatsry reviewed
> Reviewed 3 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 4 of 15 files reviewed, 17 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-09-29 12:48 UTC, yair-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 4 of 15 files reviewed, 20 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7i_vC89O_k5TpQHVgd:-O7i_vC89O_k5TpQHVge:b57a0mt) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L36)):*
> ```XML
> #[cfg(test)]
> #[path = "block_builder_test.rs"]
> pub mod block_builder_test;
> ```

Consider moving to the lib file and remove `pub`



_Code quote:_
```XML
#[cfg(test)]
#[path = "block_builder_test.rs"]
pub mod block_builder_test;
```
___
*[`crates/batcher/src/block_builder.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7ib0cE9me-bNvW3QuQ:-O7ib0cE9me-bNvW3QuR:bmhct3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L74)):*
> ```XML
>     pub execution_config: ExecutionConfig,
>     pub global_class_hash_to_class: GlobalContractCache,
> }
> ```

Why do we need this struct?
It is very confusing to have both `ExecutionConfig` & `ExecutionParams`



_Code quote:_
```XML
pub struct ExecutionParams {
    pub execution_config: ExecutionConfig,
    pub global_class_hash_to_class: GlobalContractCache,
}
```
___
*[`crates/batcher/src/block_builder.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7iaTHI9QB5-uX-6lsR:-O7iaTHI9QB5-uX-6lsS:bt46jjw) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L86)):*
> ```XML
>     pub fn create_transaction_executor(
>         next_block_number: BlockNumber,
>         storage_reader: StorageReader,
> ```

use `impl StateReader` to enable mocking and avoid storage specific functions



_Code quote:_
```XML
StorageReader
```
___
*[`crates/batcher/src/block_builder.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YQPW24emRtnsBH9vl:-O7xo_O66LxJslwTQU6u:b-5xumw0) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L140)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Did we want to make the blockifier/bouncer deal with the time?
maybe add a todo if this is the case.
</blockquote></details>

I suggest using `chunks_timeout`: https://docs.rs/tokio-stream/latest/tokio_stream/trait.StreamExt.html#:~:text=source-,fn%20chunks_timeout(,-self%2C%0A%20%20%20%20max_size%3A


<!-- Sent from Reviewable.io -->

2024-10-06 12:14 UTC, dafnamatsry requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 0 of 17 files reviewed, 13 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8WT3kqCEM3o_rUc5g4:-O8WT3kqCEM3o_rUc5g5:bveqijt) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L92)):*
> ```XML
>     async fn get_tx_chunk<'a>(
>         &self,
>         mempool_tx_stream: &mut Pin<&'a mut (impl Stream<Item = Transaction> + 'a)>,
> ```

Why do we need the lifetime here?
Isn't `Pin<mut InputTxStream>



_Code quote:_
```XML
&mut Pin<&'a mut (impl Stream<Item = Transaction> + 'a)>
```
___
*[`crates/batcher/src/block_builder.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8Wi7V30BFNZOY-6Rme:-O8Wi7V30BFNZOY-6Rmf:bae973p) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L124)):*
> ```XML
>         &mut self,
>         deadline: tokio::time::Instant,
>         mempool_tx_stream: InputTxStream,
> ```

If here, in the public API we accept a non generic type (`InputTxStream`) there's no point in accepting a generic type in `get_tx_chunk` (`...impl Stream...`).

Please TAL at `BoxStream`, I think it can be useful in our case.



_Code quote:_
```XML
mempool_tx_stream: InputTxStream,
```
___
*[`crates/batcher/src/block_builder.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8WQ6pm0B9NIZnjAFr2:-O8WQ6pm0B9NIZnjAFr3:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L151)):*
> ```XML
>                             debug!("Transaction {:?} failed with error: {}.", mempool_tx, err);
>                         }
>                     },
> ```





_Suggestion:_
```XML
                    // TODO(yael 18/9/2024): add timeout error handling here once this feature
                    // is added.
                    Err(BlockifierTransactionExecutorError::BlockFull) => {
                        info!("Block is full");
                        close_block = true;
                    },
                    Err(err) => {
                        debug!("Transaction {:?} failed with error: {}.", mempool_tx, err);
                    },
```
___
*[`crates/batcher/src/block_builder.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8WRaB1Esv8VWICwZ0K:-O8WRaB1Esv8VWICwZ0L:b-aud2uw) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L165)):*
> ```XML
> 
>         // TODO how to update the mempool which transactions suceeded? maybe it's the
>         // orchestrator's responsibilty
> ```

It's the batcher responsibility (at least for the upcoming milestone). But for sure it is out of scope for the block builder, so you can remove this comment.



_Code quote:_
```XML
        // TODO how to update the mempool which transactions suceeded? maybe it's the
        // orchestrator's responsibilty
```


<!-- Sent from Reviewable.io -->

2024-10-06 13:07 UTC, yair-starkware requested changes
> Reviewed 10 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 10 of 17 files reviewed, 16 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8WIVia9V6GvAxEVAMC:-O8WIVia9V6GvAxEVAMD:bk73ff4) (no related file):*
Consider moving the changes in blockifier to a separate PR

___
___
*[`crates/batcher/src/block_builder.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8W5Yun5F1UF4ijW8h9:-O8W5Yun5F1UF4ijW8hA:bosl4c2) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L90)):*
> ```XML
>     }
> 
>     async fn get_tx_chunk<'a>(
> ```

consider using `chunks_timeout`: [https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.ready_chunks](https://docs.rs/tokio-stream/latest/tokio_stream/trait.StreamExt.html#method.chunks_timeout)
___
*[`crates/batcher/src/block_builder.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8W46-oC-WkZczqGzA0:-O8W46-p62t2uDq9r9Vm:b1t1dqs) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L92)):*
> ```XML
>     async fn get_tx_chunk<'a>(
>         &self,
>         mempool_tx_stream: &mut Pin<&'a mut (impl Stream<Item = Transaction> + 'a)>,
> ```

Why is the stream not a member of the struct?



_Code quote:_
```XML
mempool_tx_stream
```
___
*[`crates/batcher/src/block_builder.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8W6q-T4ZL1jkQBk8wu:-O8W6q-T4ZL1jkQBk8wv:b-9688sz) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L179)):*
> ```XML
> // A struct that holds a chunk of transactions in two formats: mempool format and blockifier format.
> // Note: both vectors should hold the same transactions in the same order.
> struct TransactionChunk {
> ```

Consider making it a vector of tuples to enforce the same length and
___
*[`crates/batcher/src/block_builder_test.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8Ww3P67KsnP5E3MQvL:-O8Ww3P67KsnP5E3MQvM:b-txlvi) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder_test.rs#L28)):*
> ```XML
>     const INPUT_TXS_LEN: usize = 3;
>     // The output txs_bufer len will be one less than the input, since the tx one will get a block
>     // full error.
> ```

Please make a simple happy flow test and add other flows in separate tests



_Code quote:_
```XML
    // The output txs_bufer len will be one less than the input, since the tx one will get a block
    // full error.
```


<!-- Sent from Reviewable.io -->

2024-10-06 13:29 UTC, yair-starkware commented
*[`crates/batcher/src/block_builder.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8X0F2Z1I6QWTDIDZ6w:-O8X0F2Z1I6QWTDIDZ6x:b-p4rz2m) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L43)):*
> ```XML
> #[derive(Default, Debug, PartialEq)]
> pub struct BlockExecutionArtifacts {
>     pub execution_infos: HashMap<TransactionHash, TransactionExecutionInfo>,
> ```

The order of txs matters, you need to use something like `IndexMap`



_Code quote:_
```XML
HashMap
```


<!-- Sent from Reviewable.io -->

2024-10-07 08:40 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 10 of 17 files reviewed, 17 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YJqnk8BazcOFZpQ0x:-O8WAregBDZkMcv_HHGE:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L138)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

If we accept a `Box<Pin<impl Stream...>>`, can we remove this line?
what about [`BoxStream`](https://docs.rs/futures/latest/futures/stream/type.BoxStream.html)?
</blockquote></details>

done.
___
*[`crates/batcher/src/block_builder.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YQPW24emRtnsBH9vl:-O8a2cjU31zfyAE1tSqt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L140)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I suggest using `chunks_timeout`: https://docs.rs/tokio-stream/latest/tokio_stream/trait.StreamExt.html#:~:text=source-,fn%20chunks_timeout(,-self%2C%0A%20%20%20%20max_size%3A
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7Yb7Mk6Cbve4b5pD0k:-O8a67erBSkNy4EhFatZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L191)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

why clone?
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O7YaHk6AvLn3ryGx3_E:-O8a5O8N0Q3PfXyOuee7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/902bf3b174c89deea6cd6222a3b0ccbf69021687/crates/batcher/src/block_builder.rs#L225)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move above the `BlockBuilder` definition.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8X0F2Z1I6QWTDIDZ6w:-O8a2uVdBxJTmMWUMFfz:b-g235w7) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L43)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The order of txs matters, you need to use something like `IndexMap`
</blockquote></details>

it is just a mapping, doesn't define the order, but sure will change it anyway.
done
___
*[`crates/batcher/src/block_builder.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8W46-oC-WkZczqGzA0:-O8a2mgz5iCUumTr1dob:bnd7plx) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L92)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is the stream not a member of the struct?
</blockquote></details>

function deleted so not relevant anymore
___
*[`crates/batcher/src/block_builder.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8WT3kqCEM3o_rUc5g4:-O8a2qFo71yyee9xtOTs:bnd7plx) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L92)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why do we need the lifetime here?
Isn't `Pin<mut InputTxStream>
</blockquote></details>

function deleted so not relevant anymore
___
*[`crates/batcher/src/block_builder.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8Wi7V30BFNZOY-6Rme:-O8a2gWACDlASzrUfYlD:b-3d2ix0) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L124)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

If here, in the public API we accept a non generic type (`InputTxStream`) there's no point in accepting a generic type in `get_tx_chunk` (`...impl Stream...`).

Please TAL at `BoxStream`, I think it can be useful in our case.
</blockquote></details>

deleted the function get_tx_chunks so not relevant anymore
done.
___
*[`crates/batcher/src/block_builder.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8WQ6pm0B9NIZnjAFr2:-O8a2bZ9ErMI4P3xHGLJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L151)):*
> ```XML
>                             debug!("Transaction {:?} failed with error: {}.", mempool_tx, err);
>                         }
>                     },
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8WRaB1Esv8VWICwZ0K:-O8a4WftA7Gtt21J-ohv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L165)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

It's the batcher responsibility (at least for the upcoming milestone). But for sure it is out of scope for the block builder, so you can remove this comment.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8W6q-T4ZL1jkQBk8wu:-O8a4bxo73HmMWygrk6n:bnyx0lq) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L179)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider making it a vector of tuples to enforce the same length and
</blockquote></details>

deleted the struct, not relevant
___
*[`crates/batcher/src/block_builder_test.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8Ww3P67KsnP5E3MQvL:-O8a5f0hB7_MaSx2uPu2:b-lwlqb6) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder_test.rs#L28)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please make a simple happy flow test and add other flows in separate tests
</blockquote></details>

this is the simple happy flow, just have a lot of mocking to build.


<!-- Sent from Reviewable.io -->

2024-10-07 11:31 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 5 of 17 files reviewed, 16 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8W5Yun5F1UF4ijW8h9:-O8ajpZF0RqPvCRSiwnc:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L90)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

consider using `chunks_timeout`: [https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.ready_chunks](https://docs.rs/tokio-stream/latest/tokio_stream/trait.StreamExt.html#method.chunks_timeout)
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-10-08 09:39 UTC, dafnamatsry requested changes
> Reviewed 4 of 17 files at r2, 2 of 5 files at r3, 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 12 of 17 files reviewed, 18 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fIEo3-dlVfh_N1Unx:-O8fIEo3-dlVfh_N1Uny:b-mi3axx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L84)):*
> ```XML
>         &mut self,
>         deadline: tokio::time::Instant,
>         mempool_tx_stream: InputTxStream,
> ```

Doesn't have to be from mempool right?



_Suggestion:_
```XML
input_tx_stream
```
___
*[`crates/batcher/src/block_builder.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fAzZ_6Af3J2dP_CLo:-O8fAzZ_6Af3J2dP_CLp:bc2dvii) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L90)):*
> ```XML
>         let mut close_block = false;
>         let chunk_stream =
>             mempool_tx_stream.chunks_timeout(self.tx_chunk_size, Duration::from_secs(0));
> ```

Why 0?
I think with 0, we will always get chunks with size 1.



_Code quote:_
```XML
uration::from_secs(0)
```
___
*[`crates/batcher/src/block_builder.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fCzQMCysZCn4R2MMb:-O8fCzQNEtcTC_plE2LG:b-qbcv01) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L92)):*
> ```XML
>             mempool_tx_stream.chunks_timeout(self.tx_chunk_size, Duration::from_secs(0));
>         pin!(chunk_stream);
>         let mut tx_chunk_blockifier = vec![];
> ```

Please move inside the while loop.

When defined here outside the loop, the vec is not being cleared between chunk iterations, so I suspect the same txs are being sent over and over again to the executor.
Please correct me if I'm wrong and make sure it is tested.
___
*[`crates/batcher/src/block_builder.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fESMo3f80i-_X7YRN:-O8fESMo3f80i-_X7YRO:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L92)):*
> ```XML
>             mempool_tx_stream.chunks_timeout(self.tx_chunk_size, Duration::from_secs(0));
>         pin!(chunk_stream);
>         let mut tx_chunk_blockifier = vec![];
> ```





_Suggestion:_
```XML
let mut executor_input_chunk = vec![];
```
___
*[`crates/batcher/src/block_builder.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fKm-9AS-KoZNUcgBH:-O8fKm-9AS-KoZNUcgBI:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L95)):*
> ```XML
>         // TODO(yael 6/10/2024): delete the timeout condition once the executor has a timeout
>         while !close_block && tokio::time::Instant::now() < deadline {
>             let tx_chunk_mempool = chunk_stream.next().await;
> ```





_Suggestion:_
```XML
let next_chunk = chunk_stream.next().await;
```
___
*[`crates/batcher/src/block_builder.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fL25PDnZAUhPiujPO:-O8fL25PDnZAUhPiujPP:b-ey3mij) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L95)):*
> ```XML
>         // TODO(yael 6/10/2024): delete the timeout condition once the executor has a timeout
>         while !close_block && tokio::time::Instant::now() < deadline {
>             let tx_chunk_mempool = chunk_stream.next().await;
> ```

IIUC the chunk will never be empty, and next will block until at least 1 item is available. what is the deadline is reached by then? We need to figure out a way to limit the waiting time here.
Please add a TODO.
___
*[`crates/batcher/src/block_builder.rs` line 96 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fEctA9abwspIUigre:-O8fEctA9abwspIUigrf:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L96)):*
> ```XML
>         while !close_block && tokio::time::Instant::now() < deadline {
>             let tx_chunk_mempool = chunk_stream.next().await;
>             if let Some(tx_chunk_mempool) = tx_chunk_mempool {
> ```





_Suggestion:_
```XML
if tx_chunk_mempool.is_none() {
    break;
}
let tx_chunk_mempool = tx_chunk_mempool.unwrap();
```
___
*[`crates/batcher/src/block_builder.rs` line 118 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fIaie4XATugBhSOuW:-O8fIaie4XATugBhSOuX:b3s98r1) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L118)):*
> ```XML
>                         }
>                     }
>                 }
> ```

Please move to a `collect_execution_results` method:
```
should_close_block = collect_execution_results(...)
```



_Code quote:_
```XML
                for (mempool_tx, result) in tx_chunk_mempool.into_iter().zip(results.into_iter()) {
                    match result {
                        Ok(tx_execution_info) => {
                            execution_infos.insert(mempool_tx.tx_hash(), tx_execution_info);
                            output_content_sender.send(mempool_tx).await?;
                        }
                        // TODO(yael 18/9/2024): add timeout error handling here once this
                        // feature is added.
                        Err(BlockifierTransactionExecutorError::BlockFull) => {
                            info!("Block is full");
                            close_block = true;
                        }
                        Err(err) => {
                            debug!("Transaction {:?} failed with error: {}.", mempool_tx, err)
                        }
                    }
                }
```
___
*[`crates/batcher/src/block_builder_test.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fN96i-0Pe_pvQ9OeS:-O8fN96i-0Pe_pvQ9OeT:b-am8v9v) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder_test.rs#L24)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn test_build_block() {
> ```

Please move whatever possible to fixtures (all channels and the mock executor).
___
*[`crates/batcher/src/block_builder_test.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fNjHwBdiQVapiyFIP:-O8fNjHwBdiQVapiyFIQ:b-fu0kbj) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder_test.rs#L40)):*
> ```XML
>         mempool_tx_sender.send(tx.clone()).await.unwrap();
>     }
>     let (output_block_artifacts, executor_output) = executor_test_outputs(OUTPUT_TXS_LEN);
> ```

Please add test cases with different chunk sizes (smaller/larger/equal to the input stream length).
___
*[`crates/batcher/src/block_builder_test.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fTM45CFMUKMs90g5N:-O8fTM45CFMUKMs90g5O:b9xpycc) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder_test.rs#L40)):*
> ```XML
>         mempool_tx_sender.send(tx.clone()).await.unwrap();
>     }
>     let (output_block_artifacts, executor_output) = executor_test_outputs(OUTPUT_TXS_LEN);
> ```

Consider splitting to 2 functions, one to create the execution infos mapping, and one to create the block artifacts from multiple ma [...]

2024-10-08 12:24 UTC, yair-starkware reviewed
> Reviewed 1 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 12 of 17 files reviewed, 15 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8X0F2Z1I6QWTDIDZ6w:-O8g2pQuDgJHYbxgQOV1:b-wr0w6t) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L43)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it is just a mapping, doesn't define the order, but sure will change it anyway.
done
</blockquote></details>

We will need the order of the txs in the future for the proposal commitment
___
*[`crates/batcher/src/block_builder.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fAzZ_6Af3J2dP_CLo:-O8g3Jff4NBpeC5GN7qw:b-lxnkej) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L90)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why 0?
I think with 0, we will always get chunks with size 1.
</blockquote></details>

It should be `time_to_deadline - enough_time_to_execute_chunk`
___
*[`crates/batcher/src/block_builder.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fL25PDnZAUhPiujPO:-O8g3jDgA6thgrKYzWVN:bz3lea2) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L95)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

IIUC the chunk will never be empty, and next will block until at least 1 item is available. what is the deadline is reached by then? We need to figure out a way to limit the waiting time here.
Please add a TODO.
</blockquote></details>

This is the `timeout` in `chunks_timeout`


<!-- Sent from Reviewable.io -->

2024-10-08 12:59 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 12 of 17 files reviewed, 15 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fAzZ_6Af3J2dP_CLo:-O8fyW6D7XKBrJCSKQsk:brw0ina) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L90)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why 0?
I think with 0, we will always get chunks with size 1.
</blockquote></details>

it's a good question, it depends on how fast the stream is being filled, if the tasks of filling the stream is running before this code, then the stream will be filled, otherwise we can also get chunks of 0 items.
I thought about it, and I think that putting 0 here is the same as just running in a loop and popping items from the stream without waiting.
___
*[`crates/batcher/src/block_builder.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fCzQMCysZCn4R2MMb:-O8fzOWUBgFECJegerSY:bioehlm) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L92)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move inside the while loop.

When defined here outside the loop, the vec is not being cleared between chunk iterations, so I suspect the same txs are being sent over and over again to the executor.
Please correct me if I'm wrong and make sure it is tested.
</blockquote></details>

Oops, you're right.
the test does not run on multiple chunks yet, it is in a todo comment.
___
*[`crates/batcher/src/block_builder.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fL25PDnZAUhPiujPO:-O8gCGWb973mTbcaZqgO:b8osjac) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L95)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This is the `timeout` in `chunks_timeout`
</blockquote></details>

I just tested it, and chunks_timeout is blocking if the stream is empty.
the timeout only works when the stream is not empty.


<!-- Sent from Reviewable.io -->

2024-10-08 13:02 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 12 of 17 files reviewed, 15 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8X0F2Z1I6QWTDIDZ6w:-O8gD6TP1eOGmMtEkP5d:b-m17mob) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L43)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We will need the order of the txs in the future for the proposal commitment
</blockquote></details>

we have the order of the transactions from the output stream.


<!-- Sent from Reviewable.io -->

2024-10-08 13:07 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 12 of 17 files reviewed, 15 unresolved discussions (waiting on @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fAzZ_6Af3J2dP_CLo:-O8gERefE56JTH7XK9Nl:b-kiq3cr) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L90)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it's a good question, it depends on how fast the stream is being filled, if the tasks of filling the stream is running before this code, then the stream will be filled, otherwise we can also get chunks of 0 items.
I thought about it, and I think that putting 0 here is the same as just running in a loop and popping items from the stream without waiting.
</blockquote></details>

enough_time_to_execute_chunk - I don't think we have this number but will consult with @noaov1 .


<!-- Sent from Reviewable.io -->

2024-10-08 13:10 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 12 of 17 files reviewed, 15 unresolved discussions (waiting on @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 96 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fEctA9abwspIUigre:-O8gF8GY8oFyYy6yssdi:by1xy4z) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L96)):*
> ```XML
>         while !close_block && tokio::time::Instant::now() < deadline {
>             let tx_chunk_mempool = chunk_stream.next().await;
>             if let Some(tx_chunk_mempool) = tx_chunk_mempool {
> ```

I'm not sure we want to break in this case, maybe there is still time till the deadline and more transaction will arrive


<!-- Sent from Reviewable.io -->

2024-10-08 13:25 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 12 of 17 files reviewed, 15 unresolved discussions (waiting on @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fIEo3-dlVfh_N1Unx:-O8gGyPD-NU1Zh8Plivm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L84)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Doesn't have to be from mempool right?
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fCzQMCysZCn4R2MMb:-O8gH2GPDF4nBCHqyl-c:b-tio093) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L92)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Oops, you're right.
the test does not run on multiple chunks yet, it is in a todo comment.
</blockquote></details>

will add a test
___
*[`crates/batcher/src/block_builder.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fESMo3f80i-_X7YRN:-O8gH76mEtXJ_iCp7FKJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L92)):*
> ```XML
>             mempool_tx_stream.chunks_timeout(self.tx_chunk_size, Duration::from_secs(0));
>         pin!(chunk_stream);
>         let mut tx_chunk_blockifier = vec![];
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fKm-9AS-KoZNUcgBH:-O8gHALd0etra4XA2MVq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L95)):*
> ```XML
>         // TODO(yael 6/10/2024): delete the timeout condition once the executor has a timeout
>         while !close_block && tokio::time::Instant::now() < deadline {
>             let tx_chunk_mempool = chunk_stream.next().await;
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 118 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fIaie4XATugBhSOuW:-O8gGtjIAFvBcMkR7Q43:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L118)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move to a `collect_execution_results` method:
```
should_close_block = collect_execution_results(...)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-09 07:02 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 3 of 23 files reviewed, 15 unresolved discussions (waiting on @dafnamatsry, @noaov1, and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8X0F2Z1I6QWTDIDZ6w:-O8k1u0h7p_0d4qUX8fQ:b-mz0fmk) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L43)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

we have the order of the transactions from the output stream.
</blockquote></details>

That goes to the consensus, we don't consume it
___
*[`crates/batcher/src/block_builder.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fL25PDnZAUhPiujPO:-O8k2aQF2kfqqjUUcpeH:b46y73r) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L95)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I just tested it, and chunks_timeout is blocking if the stream is empty.
the timeout only works when the stream is not empty.
</blockquote></details>

You need to do something like:
```
loop {
    select! {
        next_chunk = stream.chunks_timeout(deadline - enough_time) => ...
        reached_deadline = sleep(deadline)
    }
}
```


<!-- Sent from Reviewable.io -->

2024-10-09 11:50 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 2 of 23 files reviewed, 15 unresolved discussions (waiting on @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8X0F2Z1I6QWTDIDZ6w:-O8kwCL9D0T0O4_LRoAe:b-c6lwh4) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L43)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

That goes to the consensus, we don't consume it
</blockquote></details>

but this mapping does not contain the transactions, only the tx_hashes and execution info. |
Do we need to tadd the full transactions to the blockArtifacts?
___
*[`crates/batcher/src/block_builder.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fL25PDnZAUhPiujPO:-O8klwBr4A6uZ5Hxy189:b6ne5fk) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L95)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You need to do something like:
```
loop {
    select! {
        next_chunk = stream.chunks_timeout(deadline - enough_time) => ...
        reached_deadline = sleep(deadline)
    }
}
```
</blockquote></details>

fixed it with time::timeout
done.
___
*[`crates/batcher/src/block_builder.rs` line 96 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fEctA9abwspIUigre:-O8km33ZAgsbFQrBtdxY:b-3ukxo8) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder.rs#L96)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I'm not sure we want to break in this case, maybe there is still time till the deadline and more transaction will arrive
</blockquote></details>

did something similar with the output of time_timeout, which is Result<Option<...>>


<!-- Sent from Reviewable.io -->

2024-10-09 12:09 UTC, dafnamatsry requested changes
> Reviewed 1 of 17 files at r6, 6 of 18 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 9 of 23 files reviewed, 11 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 85 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8l7N3zCBsLzATeBwCb:-O8l7N3zCBsLzATeBwCc:bds4yz5) ([raw file](https://github.com/starkware-libs/sequencer/blob/c78f888b514580182f9e3317025bdd2e62f9d600/crates/batcher/src/block_builder.rs#L85)):*
> ```XML
>         output_content_sender: tokio::sync::mpsc::Sender<Transaction>,
>     ) -> BlockBuilderResult<BlockExecutionArtifacts> {
>         let mut execution_infos = IndexMap::new();
> ```

Move to be right before the while loop.



_Code quote:_
```XML
let mut execution_infos = IndexMap::new();
```
___
*[`crates/batcher/src/block_builder.rs` line 97 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8l8FB91tdl275V380v:-O8l8FB91tdl275V380w:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c78f888b514580182f9e3317025bdd2e62f9d600/crates/batcher/src/block_builder.rs#L97)):*
> ```XML
>                 Err(_) | Ok(None) => {
>                     break;
>                 }
> ```





_Suggestion:_
```XML
                Err(_) | Ok(None) => {
                    // No further transactions to execute: either did not receive a value within 
                    // the given timeout, or the stream is finished.
                    break;
                }
```
___
*[`crates/batcher/src/block_builder.rs` line 132 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8l9uS96yTaTkAHjGBc:-O8l9uS96yTaTkAHjGBd:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c78f888b514580182f9e3317025bdd2e62f9d600/crates/batcher/src/block_builder.rs#L132)):*
> ```XML
> ) -> BlockBuilderResult<bool> {
>     let mut close_block = false;
>     for (mempool_tx, result) in tx_chunk.into_iter().zip(results.into_iter()) {
> ```





_Suggestion:_
```XML
input_tx
```
___
*[`crates/batcher/src/block_builder.rs` line 143 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8lA7EjDaZRo1uPNtwm:-O8lA7EjDaZRo1uPNtwn:b-n76545) ([raw file](https://github.com/starkware-libs/sequencer/blob/c78f888b514580182f9e3317025bdd2e62f9d600/crates/batcher/src/block_builder.rs#L143)):*
> ```XML
>                 info!("Block is full");
>                 close_block = true;
>             }
> ```

Should we keep iterating over the results?
I think `return true` would be better here if not.



_Code quote:_
```XML
            Err(BlockifierTransactionExecutorError::BlockFull) => {
                info!("Block is full");
                close_block = true;
            }
```


<!-- Sent from Reviewable.io -->

2024-10-10 06:40 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 9 of 23 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 85 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8l7N3zCBsLzATeBwCb:-O8p3gYSAwIIEY1Y_Izp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c78f888b514580182f9e3317025bdd2e62f9d600/crates/batcher/src/block_builder.rs#L85)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Move to be right before the while loop.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 97 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8l8FB91tdl275V380v:-O8p3n5f8hBtK6ec9QjB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c78f888b514580182f9e3317025bdd2e62f9d600/crates/batcher/src/block_builder.rs#L97)):*
> ```XML
>                 Err(_) | Ok(None) => {
>                     break;
>                 }
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 132 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8l9uS96yTaTkAHjGBc:-O8p3tZL-zUrIOuPkiBY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c78f888b514580182f9e3317025bdd2e62f9d600/crates/batcher/src/block_builder.rs#L132)):*
> ```XML
> ) -> BlockBuilderResult<bool> {
>     let mut close_block = false;
>     for (mempool_tx, result) in tx_chunk.into_iter().zip(results.into_iter()) {
> ```

Done.
___
*[`crates/batcher/src/block_builder.rs` line 143 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8lA7EjDaZRo1uPNtwm:-O8p4Pv-Bjcak_m-fFsM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c78f888b514580182f9e3317025bdd2e62f9d600/crates/batcher/src/block_builder.rs#L143)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Should we keep iterating over the results?
I think `return true` would be better here if not.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fN96i-0Pe_pvQ9OeS:-O8p4RkSAAE6rXyvBjAm:b-bu7qvk) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder_test.rs#L24)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move whatever possible to fixtures (all channels and the mock executor).
</blockquote></details>

mock executor moved into a function
Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fNjHwBdiQVapiyFIP:-O8p4mbNExwRbZnH-j6f:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder_test.rs#L40)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add test cases with different chunk sizes (smaller/larger/equal to the input stream length).
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fTM45CFMUKMs90g5N:-O8p5ufj1DjwSV-MhKzy:b-iu3adj) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder_test.rs#L40)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider splitting to 2 functions, one to create the execution infos mapping, and one to create the block artifacts from multiple mappings. I think it will be useful for tests with multiple chunks.
</blockquote></details>

added multiple chunks with this function as is. let time know what you think.
___
*[`crates/batcher/src/block_builder_test.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fPP4B94oesiOm6ey8:-O8p4sto3qNSwHVELvbr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder_test.rs#L53)):*
> ```XML
>     let mut block_builder = BlockBuilder::new(Box::new(mock_transaction_executor), INPUT_TXS_LEN);
>     let result_block_artifacts =
>         block_builder.build_block(deadline, mempool_tx_stream, output_stream_sender).await.unwrap();
> ```

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8fP_FXECsRQo7lU-B-:-O8p5c8f7CvZ_xr7VR_7:bix1sbo) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f3bb305820d74b9545eea4e569b490931d8d31c/crates/batcher/src/block_builder_test.rs#L90)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Flows that I can think of:
- failed txs are not included in the block.
- deadline is reached before block is full.
- input tx stream is empty.
- input_tx_stream is finished before block is full or deadline i reached.
</blockquote></details>

added all cases besides the first one. adding a todo and will add in the following PR


<!-- Sent from Reviewable.io -->

2024-10-10 08:55 UTC, dafnamatsry requested changes
> Reviewed 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 9 of 23 files reviewed, 17 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/block_builder_test.rs` line 38 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pHBsb7X9xnk-eU8nf:-O8pHBsc7bQofZWEjjNB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L38)):*
> ```XML
> #[rstest]
> #[case::one_chunk_block(5, 5, 2, 0)]
> #[case::nultiple_chunks_block(10, 2, 9, 0)]
> ```





_Suggestion:_
```XML
#[case::multiple_chunks_block(10, 2, 9, 0)]
```
___
*[`crates/batcher/src/block_builder_test.rs` line 43 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8paP1h8e-L1BaTKUcn:-O8paP1iBweWth62TOND:bg7c5s8) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L43)):*
> ```XML
> #[tokio::test]
> async fn test_build_block(
>     #[case] input_txs_len: usize,
> ```

Can we accept directly the `test_txs(..)` here instead?



_Code quote:_
```XML
 #[case] input_txs_len: usize,
```
___
*[`crates/batcher/src/block_builder_test.rs` line 46 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pUR7z4gNru3wye1w2:-O8pUR7z4gNru3wye1w3:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L46)):*
> ```XML
>     #[case] executor_tx_chunk_len: usize,
>     #[case] expected_output_txs_len: usize,
>     #[case] add_execution_delay_secs: u64,
> ```





_Suggestion:_
```XML
async fn test_build_block(
    #[case] input_txs_len: usize,
    #[case] execution_chunk_size: usize,
    #[case] block_len: usize,
    #[case] execution_delay_secs: u64,
```
___
*[`crates/batcher/src/block_builder_test.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pJhHe9PhsxdGytO7y:-O8pJhHe9PhsxdGytO7z:b-ew4o8o) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L50)):*
> ```XML
>     output_channel: (mpsc::Sender<Transaction>, mpsc::Receiver<Transaction>),
> ) {
>     // The last transaction is not included in the block, since we return BlockFull for it.
> ```

Doesn't seem like the right place for this comment.



_Code quote:_
```XML
 // The last transaction is not included in the block, since we return BlockFull for it.
```
___
*[`crates/batcher/src/block_builder_test.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pV6pcBc8jcRkm92V7:-O8pV6pcBc8jcRkm92V8:bbbpxjn) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L51)):*
> ```XML
> ) {
>     // The last transaction is not included in the block, since we return BlockFull for it.
>     let deadline = tokio::time::Instant::now() + tokio::time::Duration::from_secs(1);
> ```

Please move down before build_block.
___
*[`crates/batcher/src/block_builder_test.rs` line 53 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pVKdr6iPtqVql94xR:-O8pVKdr6iPtqVql94xS:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L53)):*
> ```XML
>     let deadline = tokio::time::Instant::now() + tokio::time::Duration::from_secs(1);
>     let (input_channel_sender, input_channel_receiver) = input_channel;
>     let (output_stream_sender, mut output_stream_receiver) = output_channel;
> ```





_Suggestion:_
```XML
    let (input_sender, input_receiver) = input_channel;
    let (output_sender, mut output_receiver) = output_channel;
```
___
*[`crates/batcher/src/block_builder_test.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pIjWV0_EtVK_mtfy6:-O8pIjWW1xZt_F5-1_2H:b-l0u5da) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L54)):*
> ```XML
>     let (input_channel_sender, input_channel_receiver) = input_channel;
>     let (output_stream_sender, mut output_stream_receiver) = output_channel;
>     let input_tx_stream = ReceiverStream::new(input_channel_receiver);
> ```

Please move to the `input_channel` fixture, and change the return type accordingly.



_Code quote:_
```XML
let input_tx_stream = ReceiverStream::new(input_channel_receiver);
```
___
*[`crates/batcher/src/block_builder_test.rs` line 80 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pcQN6D3R4l1rxuW0h:-O8pcQN6D3R4l1rxuW0i:bec4fcj) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L80)):*
> ```XML
>     while let Some(tx) = output_stream_receiver.recv().await {
>         output_txs.push(tx);
>     }
> ```

Try do something like:
`let output_txs: Vec<...> = output_stream_receiver.iter().collect()`



_Code quote:_
```XML
    let mut output_txs = vec![];
    while let Some(tx) = output_stream_receiver.recv().await {
        output_txs.push(tx);
    }
```
___
*[`crates/batcher/src/block_builder_test.rs` line 82 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8p_wjF9g_eY5DsSA4t:-O8p_wjG96IFSOKDpp7Q:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L82)):*
> ```XML
>     }
>     assert_eq!(output_txs.len(), expected_output_txs_len);
>     for tx in txs[0..expected_output_txs_len.checked_sub(1).unwrap_or_default()].iter() {
> ```





_Suggestion:_
```XML
for tx in txs.iter().take(expected_output_txs_len)
```
___
*[`crates/batcher/src/block_builder_test.rs` line 95 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pUAp48oFNrYlnkuME:-O8pUAp48oFNrYlnkuMF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L95)):*
> ```XML
>     executor_tx_chunk_len: usize,
>     add_delay_secs: u64,
> ) -> (MockTransactionExecutorTrait, BlockExecutionArtifacts) {
> ```





_Suggestion:_
```XML
fn set_transaction_executor_expectations(
    input_txs: &[Transaction],
    num_txs_to_execute: usize,
    chunk_size: usize,
    execution_delay_secs: u64,
) -> (MockTransactionExecutorTrait, BlockExecutionArtifacts) {
```
___
*[`crates/batcher/src/block_builder_test.rs` line 104 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pQkd80vHJ-bADcOXS:-O8pQkd80vHJ-bADcOXT:b-c7tcza) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L104)):*
> ```XML
>     let mut mock_transaction_executor = MockTransactionExecutorTrait::new();
> 
>     mock_transaction_executor.expect_add_txs_to_block().returning(move |executor_input| {
> ```

Add `.times(number_of_chunks)` to check we call the function the expected number of times.
___
*[`crates/batcher/src/block_builder_test.rs` line 108 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pQekJ3GGl833Zcj7m:-O8pQekJ3GGl833Zcj7n:b5gktyz) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L108)):*
> ```XML
>         std::thread::sleep(std::time::Duration::from_secs(add_delay_secs));
>         // Check that the input to the executor is correct.
>         compare_tx_hashes(&mut input_chunks, executor_input);
> ```

Please use `.with(..)` to check the input arguments.



_Code quote:_
```XML
        // Check that the input to the executor is cor [...]

2024-10-10 12:18 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 9 of 23 files reviewed, 17 unresolved discussions (waiting on @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder_test.rs` line 38 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pHBsb7X9xnk-eU8nf:-O8piK6462BhJxLCr_IE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L38)):*
> ```XML
> #[rstest]
> #[case::one_chunk_block(5, 5, 2, 0)]
> #[case::nultiple_chunks_block(10, 2, 9, 0)]
> ```

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 43 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8paP1h8e-L1BaTKUcn:-O8q-R91BBhStTnAzqsP:br65oo) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L43)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can we accept directly the `test_txs(..)` here instead?
</blockquote></details>

I couldn't find a way to make it a fixture that gets input from the test.
___
*[`crates/batcher/src/block_builder_test.rs` line 46 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pUR7z4gNru3wye1w2:-O8q-QGvDBdQkYFQMHGA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L46)):*
> ```XML
>     #[case] executor_tx_chunk_len: usize,
>     #[case] expected_output_txs_len: usize,
>     #[case] add_execution_delay_secs: u64,
> ```

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pJhHe9PhsxdGytO7y:-O8q-PROEkVcdt-tjqa8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L50)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Doesn't seem like the right place for this comment.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pV6pcBc8jcRkm92V7:-O8q-P0O969H8oR5Hz3c:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L51)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move down before build_block.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 53 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pVKdr6iPtqVql94xR:-O8pkCzg8kdlkgrZGJUs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L53)):*
> ```XML
>     let deadline = tokio::time::Instant::now() + tokio::time::Duration::from_secs(1);
>     let (input_channel_sender, input_channel_receiver) = input_channel;
>     let (output_stream_sender, mut output_stream_receiver) = output_channel;
> ```

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pIjWV0_EtVK_mtfy6:-O8pkhOM7piHzzRmNCOR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L54)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move to the `input_channel` fixture, and change the return type accordingly.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 80 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pcQN6D3R4l1rxuW0h:-O8pmUBvADycYU5iuush:b-z8oue2) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L80)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Try do something like:
`let output_txs: Vec<...> = output_stream_receiver.iter().collect()`
</blockquote></details>

no iter but I found something else - recv_many
___
*[`crates/batcher/src/block_builder_test.rs` line 82 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8p_wjF9g_eY5DsSA4t:-O8pmZlZDYxNLkuuHYFk:b-x0s0wa) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L82)):*
> ```XML
>     }
>     assert_eq!(output_txs.len(), expected_output_txs_len);
>     for tx in txs[0..expected_output_txs_len.checked_sub(1).unwrap_or_default()].iter() {
> ```

right , and the sub 1 was a bug.
done.
___
*[`crates/batcher/src/block_builder_test.rs` line 95 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pUAp48oFNrYlnkuME:-O8pnPfD23wSsI5Fafh9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L95)):*
> ```XML
>     executor_tx_chunk_len: usize,
>     add_delay_secs: u64,
> ) -> (MockTransactionExecutorTrait, BlockExecutionArtifacts) {
> ```

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 104 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pQkd80vHJ-bADcOXS:-O8pvN-SC74qEAQW7TPU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L104)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Add `.times(number_of_chunks)` to check we call the function the expected number of times.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 108 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pQekJ3GGl833Zcj7m:-O8q-5Tc2d8qZCjLDAvr:b-w837sh) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L108)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please use `.with(..)` to check the input arguments.
</blockquote></details>

I'm not sure how to do that since I need to know which chunk this is, and I can't mutate input_chunks inside with().
___
*[`crates/batcher/src/block_builder_test.rs` line 131 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pYjeEDocgXy7iPE38:-O8qMDqY2k1a1nScjoXh:btmdmvd) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L131)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I liked this function as it was before. Please divide the output to chunks after.
Try to use `vec.chunks(number_of_chunks)`.

Also I still think that splitting 2 functions would make the code nicer:
* one function that creates the expected output given a single chunk
* one that given multiple output chunks, creates the final block artifacts.
</blockquote></details>

working on it. not done yet


<!-- Sent from Reviewable.io -->

2024-10-10 19:23 UTC, dafnamatsry submitted a review, later dismissed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 10 of 23 files reviewed, 5 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/block_builder_test.rs` line 110 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8rsAKn0iJaHb9emzJe:-O8rsAKn0iJaHb9emzJf:bne6ags) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c1a5356f9876f31fb8c8a4536400edd8afd1049/crates/batcher/src/block_builder_test.rs#L110)):*
> ```XML
>     let mut mock_transaction_executor = MockTransactionExecutorTrait::new();
> 
>     let mut number_of_chunks = div_round_up(input_txs.len(), chunk_size);
> ```

would this work?



_Suggestion:_
```XML
input_txs.len().div_ceil(chunk_size);
```


<!-- Sent from Reviewable.io -->

2024-10-11 04:09 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 9 of 23 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder_test.rs` line 131 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8pYjeEDocgXy7iPE38:-O8tl0Ir1oVJd0ZVmnaz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a7b13e47521b5427dc2a800eab68c81ce367a62/crates/batcher/src/block_builder_test.rs#L131)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

working on it. not done yet
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 110 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8rsAKn0iJaHb9emzJe:-O8tl0khEXC3RJLkNYbI:b-ad7qlm) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c1a5356f9876f31fb8c8a4536400edd8afd1049/crates/batcher/src/block_builder_test.rs#L110)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

would this work?
</blockquote></details>

wow how did I miss this one.
Done.


<!-- Sent from Reviewable.io -->

2024-10-13 10:31 UTC, alonh5 requested changes
> Reviewed 2 of 18 files at r7, 6 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 10 of 23 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry, @noaov1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 57 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O93xEs9AchJ_1d_UGoX:-O93xEsA71GH9txIJxBY:bw9tbuk) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L57)):*
> ```XML
>     BlockifierStateError(#[from] StateError),
>     #[error(transparent)]
>     ExecutionError(#[from] BlockifierTransactionExecutorError),
> ```

Maybe?



_Suggestion:_
```XML
ExecutorError
```
___
*[`crates/batcher/src/block_builder.rs` line 98 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O942fkF1YJOncv14c7W:-O942fkF1YJOncv14c7X:bab7rgz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L98)):*
> ```XML
>                 Err(_) | Ok(None) => {
>                     // No further transactions to execute: either did not receive a value within
>                     // the given timeout, or the stream is finished.
> ```

Are you sure it returns an error if the stream is finished? From what I read this can only return an `Elapsed` error which is when a timeout expires before the function was able to finish.



_Code quote:_
```XML
                    // No further transactions to execute: either did not receive a value within
                    // the given timeout, or the stream is finished.
```
___
*[`crates/batcher/src/block_builder.rs` line 108 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94EtFhEWdKc_oU4XWg:-O94EtFhEWdKc_oU4XWh:b-qod36a) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L108)):*
> ```XML
>                     .push(BlockifierTransaction::Account(AccountTransaction::try_from(tx)?));
>             }
>             let results = self.executor.lock().await.add_txs_to_block(&executor_input_chunk);
> ```

Do you think the mutex can be contained in a new async tx executor struct? Instead of calling these each time
(Doesn't have to be in this PR)



_Code quote:_
```XML
.lock().await
```
___
*[`crates/batcher/src/block_builder.rs` line 148 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94IYyiEDOxVXvKYtny:-O94IYyiEDOxVXvKYtnz:b-he0wkp) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L148)):*
> ```XML
>             }
>             Err(err) => {
>                 debug!("Transaction {:?} failed with error: {}.", input_tx, err)
> ```

Shouldn't this retrun the error?



_Suggestion:_
```XML
debug!("Transaction {:?} failed with error: {}.", input_tx, err);
return Err(err.into());
```


<!-- Sent from Reviewable.io -->

2024-10-13 10:31 UTC, yair-starkware commented
*[`crates/batcher/src/block_builder.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O8X0F2Z1I6QWTDIDZ6w:-O8rhlU_336I9Fgn5Fb3:b-gf332k) ([raw file](https://github.com/starkware-libs/sequencer/blob/481659b65fd880fe89155b0c13cce8b1288d8ff0/crates/batcher/src/block_builder.rs#L43)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

but this mapping does not contain the transactions, only the tx_hashes and execution info. |
Do we need to tadd the full transactions to the blockArtifacts?
</blockquote></details>

Not currently


<!-- Sent from Reviewable.io -->

2024-10-13 11:00 UTC, yair-starkware requested changes
> Reviewed 1 of 18 files at r7, 6 of 7 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 11 of 23 files reviewed, 11 unresolved discussions (waiting on @alonh5, @dafnamatsry, @noaov1, and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 97 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O93juvO6hcO4PLhhAci:-O93juvO6hcO4PLhhAcj:b-qzfn28) ([raw file](https://github.com/starkware-libs/sequencer/blob/95a616288fb575507e81497cf113173390d57eef/crates/batcher/src/block_builder.rs#L97)):*
> ```XML
>             let next_tx_chunk = match time::timeout(time_to_deadline, chunk_stream.next()).await {
>                 Err(_) | Ok(None) => {
>                     // No further transactions to execute: either did not receive a value within
> ```

Add log
___
*[`crates/batcher/src/block_builder.rs` line 98 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O942fkF1YJOncv14c7W:-O94RJlb451wpcHguiSC:b32v57) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L98)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Are you sure it returns an error if the stream is finished? From what I read this can only return an `Elapsed` error which is when a timeout expires before the function was able to finish.
</blockquote></details>

+1
___
*[`crates/batcher/src/block_builder_test.rs` line 41 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94VwoSDfQPQSv6rFYm:-O94VwoSDfQPQSv6rFYn:bkyd732) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder_test.rs#L41)):*
> ```XML
> #[fixture]
> fn input_txs(#[default(1)] input_txs_len: usize) -> Vec<Transaction> {
>     test_txs(0..input_txs_len)
> ```

Consider sending the txs inside the fixture
___
*[`crates/batcher/src/block_builder_test.rs` line 68 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94W12n-fGE2_FDvjLX:-O94W12n-fGE2_FDvjLY:bbk5ia5) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder_test.rs#L68)):*
> ```XML
>     for tx in input_txs.iter() {
>         input_sender.send(tx.clone()).await.unwrap();
>     }
> ```

You can use the fixture instead



_Code quote:_
```XML
    // Create the input transactions and send them to the input channel.
    let input_txs = test_txs(0..input_txs_len);
    for tx in input_txs.iter() {
        input_sender.send(tx.clone()).await.unwrap();
    }
```
___
*[`crates/batcher/src/block_builder_test.rs` line 86 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94Wffy5NHz3yUdwAgY:-O94Wffy5NHz3yUdwAgZ:b-mfmxhx) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder_test.rs#L86)):*
> ```XML
>         tokio::time::Instant::now() + tokio::time::Duration::from_secs(TEST_DEADLINE_SECS);
>     let result_block_artifacts =
>         block_builder.build_block(deadline, input_receiver, output_sender).await.unwrap();
> ```

Can we run this in a separate thread to test concurrent execution and streaming?



_Code quote:_
```XML
    let result_block_artifacts =
        block_builder.build_block(deadline, input_receiver, output_sender).await.unwrap();
```


<!-- Sent from Reviewable.io -->

2024-10-13 11:20 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 11 of 23 files reviewed, 10 unresolved discussions (waiting on @alonh5, @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 97 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O93juvO6hcO4PLhhAci:-O94a6Ov6MXScR9sneAP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/95a616288fb575507e81497cf113173390d57eef/crates/batcher/src/block_builder.rs#L97)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add log
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 57 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O93xEs9AchJ_1d_UGoX:-O94a5SA9IoabZMwg8JF:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L57)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe?
</blockquote></details>

done
___
*[`crates/batcher/src/block_builder.rs` line 98 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O942fkF1YJOncv14c7W:-O94ZbVe96pE2khfl4KI:bsdrm01) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L98)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

+1
</blockquote></details>


Ok(none) means that the stream is finished.
Err is only for timeout.
___
*[`crates/batcher/src/block_builder.rs` line 108 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94EtFhEWdKc_oU4XWg:-O94aGHM7VwE60-I8cE1:bhmywsz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L108)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do you think the mutex can be contained in a new async tx executor struct? Instead of calling these each time
(Doesn't have to be in this PR)
</blockquote></details>

Actually, there is a different solution that will enable the deletion of this Mutex. 
The only reason we need it is that cachedState does not implement the Sync trait because it contains RefCell.
We plan to make the CachedState generic and then create an instance that implements Sync (by using RwLock instead of Refcell).
___
*[`crates/batcher/src/block_builder.rs` line 148 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94IYyiEDOxVXvKYtny:-O94aqlO8qug9dOkXVI4:bjafii1) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L148)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Shouldn't this retrun the error?
</blockquote></details>

no, if a transaction fails, it is not inserted into a block, but the block is still being generated without it.


<!-- Sent from Reviewable.io -->

2024-10-13 11:22 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 10 of 23 files reviewed, 10 unresolved discussions (waiting on @alonh5, @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder_test.rs` line 41 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94VwoSDfQPQSv6rFYm:-O94bH42EpgaXS6JZJiB:behbl2t) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder_test.rs#L41)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider sending the txs inside the fixture
</blockquote></details>

actually this fixture doesn't work, it was just left here by mistake.
Do you know how to make a fixture that gets as input one of the test arguments?


<!-- Sent from Reviewable.io -->

2024-10-13 13:00 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 7 of 23 files reviewed, 10 unresolved discussions (waiting on @alonh5, @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder_test.rs` line 86 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94Wffy5NHz3yUdwAgY:-O94wdSZ0oq9o_QqQQe-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder_test.rs#L86)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can we run this in a separate thread to test concurrent execution and streaming?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-13 13:58 UTC, alonh5 reviewed
> Reviewed 1 of 4 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 8 of 23 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry, @noaov1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 108 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94EtFhEWdKc_oU4XWg:-O94nXoI6tGryuFU2xL7:b-bhvrg0) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L108)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Actually, there is a different solution that will enable the deletion of this Mutex. 
The only reason we need it is that cachedState does not implement the Sync trait because it contains RefCell.
We plan to make the CachedState generic and then create an instance that implements Sync (by using RwLock instead of Refcell).
</blockquote></details>

Sounds good, is there a TODO for that?
___
*[`crates/batcher/src/block_builder.rs` line 148 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94IYyiEDOxVXvKYtny:-O94nhZs45HuIL7IhVaj:bpfugyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L148)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

no, if a transaction fails, it is not inserted into a block, but the block is still being generated without it.
</blockquote></details>

Right, thanks.


<!-- Sent from Reviewable.io -->

2024-10-14 07:00 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 7 of 23 files reviewed, 8 unresolved discussions (waiting on @alonh5, @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 108 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94EtFhEWdKc_oU4XWg:-O98nTDT7OEmFE7yUooJ:bbm4qxr) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L108)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Sounds good, is there a TODO for that?
</blockquote></details>

added now.
done.


<!-- Sent from Reviewable.io -->

2024-10-14 08:02 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929#-:-O991gv672C8IadWIHGp:bnfp4nl)* status: 7 of 23 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry, @noaov1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 40 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O9922dz74n8aGr-4KPf:-O9922e-0SLSQOU530p3:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ccc3aa781f23161d7c3a9208b3db71d728ea2df/crates/batcher/src/block_builder.rs#L40)):*
> ```XML
> 
> pub struct BlockBuilder {
>     //TODO(Yael 14/10/2024): make the executor thread safe and delete this mutex.
> ```





_Suggestion:_
```XML
// TODO(Yael 14/10/2024): make the executor thread safe and delete this mutex.
```


<!-- Sent from Reviewable.io -->

2024-10-14 08:14 UTC, Yael-Starkware reviewed
> Dismissed @dafnamatsry from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 7 of 23 files reviewed, 5 unresolved discussions (waiting on @alonh5, @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 40 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O9922dz74n8aGr-4KPf:-O994yIN0jx4hXct_-iF:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ccc3aa781f23161d7c3a9208b3db71d728ea2df/crates/batcher/src/block_builder.rs#L40)):*
> ```XML
> 
> pub struct BlockBuilder {
>     //TODO(Yael 14/10/2024): make the executor thread safe and delete this mutex.
> ```

done


<!-- Sent from Reviewable.io -->

2024-10-14 08:16 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 7 of 23 files reviewed, 5 unresolved discussions (waiting on @alonh5, @dafnamatsry, @noaov1, and @yair-starkware)

___
*[`crates/batcher/src/block_builder_test.rs` line 68 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94W12n-fGE2_FDvjLX:-O9954NrE2c0naA-nUuW:b-3wez2i) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder_test.rs#L68)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You can use the fixture instead
</blockquote></details>

the fixture was removed since it didn't work. and send() now runs in parallel with the block_builder.


<!-- Sent from Reviewable.io -->

2024-10-14 08:35 UTC, yair-starkware reviewed
> Reviewed 1 of 1 files at r16, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 9 of 23 files reviewed, 2 unresolved discussions (waiting on @alonh5, @dafnamatsry, @noaov1, and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 98 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O942fkF1YJOncv14c7W:-O99644K3mthKA_U7hKg:besm460) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder.rs#L98)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Ok(none) means that the stream is finished.
Err is only for timeout.
</blockquote></details>

The channel should never close, I think you should return an error in case of `None`.
___
*[`crates/batcher/src/block_builder_test.rs` line 41 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/929#-O94VwoSDfQPQSv6rFYm:-O999HOzCnEynoqgt4LP:bb70zc6) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0df3810b0b32d3a12110c1a23991344f0bb5e15/crates/batcher/src/block_builder_test.rs#L41)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

actually this fixture doesn't work, it was just left here by mistake.
Do you know how to make a fixture that gets as input one of the test arguments?
</blockquote></details>

No..


<!-- Sent from Reviewable.io -->

2024-10-14 10:53 UTC, yair-starkware approved these changes
> Reviewed 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: 10 of 23 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, @noaov1, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-10-14 10:58 UTC, Yael-Starkware reviewed
> Reviewed 5 of 17 files at r2, 9 of 18 files at r7, 2 of 4 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/929)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5, @dafnamatsry, and @noaov1)



<!-- Sent from Reviewable.io -->

2024-10-14 10:59 UTC, merged