refactor(mempool): remove AccountNonce struct
starkware-libs/sequencer pull request #965
Opened 2024-09-23 13:23 UTC by ayeletstarkware

Part of a larger refactor.
**Starting point:**
Two separate structs:

- AccountState (contains a nonce field)
- Account (contains sender_address and AccountState)

**Target:**
Merge into one struct, AccountState, containing two fields: sender_address and account_nonce.

**Current state:**
- AccountState (contains sender_address and nonce)

_**Please start by reviewing the mempool_types.rs file first.**_

**Stack of PRs:**

1. refactor(mempool): rename account state to account nonce #957
2. refactor(mempool): rename account to account state #959 
3. refactor(mempool): merge AccountNonce into AccountState #963 
4. refactor(mempool): remove AccountNonce struct #965 **<-- you're here**

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/965)

2024-09-24 11:46 UTC, eitanm-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965#-:-O7YqhgG3rNIcmg5kHZ1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-09-24 18:42 UTC, elintul requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7_KTMW2SoEQwa8EgZ1:-O7_KTMW2SoEQwa8EgZ2:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e86f4a553b9cf8b0ffcad91a868ff3a7169f933/crates/mempool/src/mempool.rs#L25)):*
> ```XML
>     // Transactions eligible for sequencing.
>     tx_queue: TransactionQueue,
>     // Represents the current nonce of the mempool during block creation.
> ```





_Suggestion:_
```XML
// Represents the state of the mempool during block creation.
```
___
*[`crates/mempool/src/mempool.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7_K2OFDo-KY613DwVn:-O7_K2OFDo-KY613DwVo:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e86f4a553b9cf8b0ffcad91a868ff3a7169f933/crates/mempool/src/mempool.rs#L71)):*
> ```XML
>         for tx in &eligible_txs {
>             self.mempool_state.insert(tx.contract_address(), tx.nonce());
>         }
> ```





_Suggestion:_
```XML
        for tx_ref in &eligible_tx_references {
            self.mempool_state.insert(tx_ref.sender_address, tx_ref.nonce);
        }
```


<!-- Sent from Reviewable.io -->

2024-09-25 09:05 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7_K2OFDo-KY613DwVn:-O7cPEfS2iAEbHjy18Z2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e86f4a553b9cf8b0ffcad91a868ff3a7169f933/crates/mempool/src/mempool.rs#L71)):*
> ```XML
>         for tx in &eligible_txs {
>             self.mempool_state.insert(tx.contract_address(), tx.nonce());
>         }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-25 09:10 UTC, elintul requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7cR7F6EcF412RoEOvx:-O7cR7F75EpJmduABWCA:b-z5v0tq) ([raw file](https://github.com/starkware-libs/sequencer/blob/57ce087a11401e330530eb2ced97702ed0e8060c/crates/mempool/src/mempool.rs#L97)):*
> ```XML
>         state_changes: HashMap<ContractAddress, Nonce>,
>     ) -> MempoolResult<()> {
>         for (&address, nonce) in &state_changes {
> ```

Why is address with `&` before and nonce isn't? 


<!-- Sent from Reviewable.io -->

2024-09-25 10:35 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7cR7F6EcF412RoEOvx:-O7cjtvh9dO0Bpb8PQuH:b-iuwarw) ([raw file](https://github.com/starkware-libs/sequencer/blob/57ce087a11401e330530eb2ced97702ed0e8060c/crates/mempool/src/mempool.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is address with `&` before and nonce isn't?
</blockquote></details>

&nonce works as well, fixed


<!-- Sent from Reviewable.io -->

2024-09-25 10:41 UTC, elintul requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7cR7F6EcF412RoEOvx:-O7clCmbBv6YL5yWdKNv:b4a5lfo) ([raw file](https://github.com/starkware-libs/sequencer/blob/57ce087a11401e330530eb2ced97702ed0e8060c/crates/mempool/src/mempool.rs#L97)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

&nonce works as well, fixed
</blockquote></details>

On the contrary, can we remove both?
Also, my Q remains unanswered.


<!-- Sent from Reviewable.io -->

2024-09-25 11:24 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7cR7F6EcF412RoEOvx:-O7coRHX9SKPQg-nhB_D:btcmo28) ([raw file](https://github.com/starkware-libs/sequencer/blob/57ce087a11401e330530eb2ced97702ed0e8060c/crates/mempool/src/mempool.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

On the contrary, can we remove both?
Also, my Q remains unanswered.
</blockquote></details>

I'm not sure why one used a reference and the other didn't, but we should be consistent since both `address` and `nonce` are `Copy`. ChatGPT suggests `(&address, &nonce)` is more efficient in large collections (thousands+), but since `state_changes` isn't big (correct me if wrong), we can use `(address, nonce).` What do you prefer?


<!-- Sent from Reviewable.io -->

2024-09-25 11:38 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7cR7F6EcF412RoEOvx:-O7cxkJL7NTXNQGZo3Cj:b-v65p2d) ([raw file](https://github.com/starkware-libs/sequencer/blob/57ce087a11401e330530eb2ced97702ed0e8060c/crates/mempool/src/mempool.rs#L97)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I'm not sure why one used a reference and the other didn't, but we should be consistent since both `address` and `nonce` are `Copy`. ChatGPT suggests `(&address, &nonce)` is more efficient in large collections (thousands+), but since `state_changes` isn't big (correct me if wrong), we can use `(address, nonce).` What do you prefer?
</blockquote></details>

So the reason it's possible is that they're both `Copy`?
The reason for the asymmetry is lack of attention?
I don't have a strong opinion, I want consistency. 


<!-- Sent from Reviewable.io -->

2024-09-25 12:54 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7cR7F6EcF412RoEOvx:-O7cybsK4khSEcATILfU:bnd03g3) ([raw file](https://github.com/starkware-libs/sequencer/blob/57ce087a11401e330530eb2ced97702ed0e8060c/crates/mempool/src/mempool.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So the reason it's possible is that they're both `Copy`?
The reason for the asymmetry is lack of attention?
I don't have a strong opinion, I want consistency.
</blockquote></details>

I was wrong, but I learned something new about pattern matching. 
Here's what's happening:
The `align` function expects the actual value of `address`. 
When we iterate with ` for (address, nonce) in &state_changes`, we're iterating over references, so `(address, nonce)` is of type `(&ContractAddress, &Nonce)`. To pass them to `align`, we need to manually dereference with `*` (possible because `ContractAddress` implements `Copy`).
However, when we use `(&address, nonce) in &state_changes`, the `&` in `&address` tells Rust to automatically dereference the reference and give us the actual value (`ContractAddress`).

This is why `address` and `nonce` were inconsistent -`nonce` didn't need dereferencing. To keep things consistent, we should use `(&address, &nonce)` and avoid manual `*` dereferencing in `align`.


<!-- Sent from Reviewable.io -->

2024-09-25 13:11 UTC, elintul requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7cR7F6EcF412RoEOvx:-O7dGZAP3jz11X-QT5U2:bxsqh54) ([raw file](https://github.com/starkware-libs/sequencer/blob/57ce087a11401e330530eb2ced97702ed0e8060c/crates/mempool/src/mempool.rs#L97)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I was wrong, but I learned something new about pattern matching. 
Here's what's happening:
The `align` function expects the actual value of `address`. 
When we iterate with ` for (address, nonce) in &state_changes`, we're iterating over references, so `(address, nonce)` is of type `(&ContractAddress, &Nonce)`. To pass them to `align`, we need to manually dereference with `*` (possible because `ContractAddress` implements `Copy`).
However, when we use `(&address, nonce) in &state_changes`, the `&` in `&address` tells Rust to automatically dereference the reference and give us the actual value (`ContractAddress`).

This is why `address` and `nonce` were inconsistent -`nonce` didn't need dereferencing. To keep things consistent, we should use `(&address, &nonce)` and avoid manual `*` dereferencing in `align`.
</blockquote></details>

Thanks. Note that this explorative quality is what I ask for, and what makes for a good developer.
Does this qualify as a dereference, or simply a destruct of the reference type? What happens if the struct does not implement `Copy`? Please try in code, do not take its answers as the truth without checking.

Note your last sentence is not true; please be mindful. The reason for the asymmetry is that we're passing `next_nonce: Nonce` and not `nonce: &Nonce`.


<!-- Sent from Reviewable.io -->

2024-09-25 13:16 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965#-:-O7dJsla2OhKi0xVBzDv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-09-25 13:52 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/965)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/965#-O7cR7F6EcF412RoEOvx:-O7dLbqCD3iAcr73rw3d:b-bmgx8k) ([raw file](https://github.com/starkware-libs/sequencer/blob/57ce087a11401e330530eb2ced97702ed0e8060c/crates/mempool/src/mempool.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Thanks. Note that this explorative quality is what I ask for, and what makes for a good developer.
Does this qualify as a dereference, or simply a destruct of the reference type? What happens if the struct does not implement `Copy`? Please try in code, do not take its answers as the truth without checking.

Note your last sentence is not true; please be mindful. The reason for the asymmetry is that we're passing `next_nonce: Nonce` and not `nonce: &Nonce`.
</blockquote></details>

1 - Yes, it's a destruct of the reference type.
2 - We need to pass the value to the function. If the struct is `Copy`, it works because Rust duplicates the value. But if the struct doesn’t implement `Copy`, we have to move the value by either passing it directly or dereferencing it with `*`. In both cases, this transfers ownership of the value, so if we need to use it again, we have to clone it to keep a copy.


<!-- Sent from Reviewable.io -->

2024-09-25 13:52 UTC, merged