chore(blockifier): added regression test for gas computation
starkware-libs/sequencer pull request #968
Opened 2024-09-23 13:42 UTC by amosStarkware

2024-09-24 15:29 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7ZdV_vEUlBHo21E0Oi:-O7ZdV_w9GNcWJ-yHmml:bj7v3s6) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf2c186b15f1a7ba38b2c4fb4179209358b2dea1/crates/blockifier/src/fee/gas_usage_test.rs#L292)):*
> ```XML
> // Assert gas computation results are as expected. The goal of this test is to prevent unwanted
> // changes to the gas computation.
> fn test_gas_computation_regression_test(
> ```

does it make sense that your fixes didn't break this test? @aner-starkware
maybe I should add cases which are affected by rounding up / down?



_Code quote:_
```XML
fn test_gas_computation_regression_test(
```


<!-- Sent from Reviewable.io -->

2024-09-29 13:58 UTC, aner-starkware commented
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 338 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7y3Rf9-YULlzdbLwR8:-O7y3Rf9-YULlzdbLwR9:bcpiv6k) ([raw file](https://github.com/starkware-libs/sequencer/blob/55d25000853b2be9aeb56509773375b95150acde/crates/blockifier/src/fee/gas_usage_test.rs#L338)):*
> ```XML
>             true => GasVector { l1_gas: 26, l1_data_gas: 0, l2_gas: 0 },
>             false => GasVector { l1_gas: 26, l1_data_gas: 0, l2_gas: 0 },
>         },
> ```

Why are you `match`ing if it makes no difference? Do you expect the `vm_resources` to depend on the `use_kzg_da` flag?



_Code quote:_
```XML
        GasVectorComputationMode::NoL2Gas => match use_kzg_da {
            true => GasVector { l1_gas: 26, l1_data_gas: 0, l2_gas: 0 },
            false => GasVector { l1_gas: 26, l1_data_gas: 0, l2_gas: 0 },
        },
```


<!-- Sent from Reviewable.io -->

2024-09-29 13:58 UTC, aner-starkware commented
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7y3_jpCPZgkmt46aKP:-O7y3_jpCPZgkmt46aKQ:bcpiv6k) ([raw file](https://github.com/starkware-libs/sequencer/blob/55d25000853b2be9aeb56509773375b95150acde/crates/blockifier/src/fee/gas_usage_test.rs#L342)):*
> ```XML
>             true => GasVector { l1_gas: 0, l1_data_gas: 0, l2_gas: 1040000 },
>             false => GasVector { l1_gas: 0, l1_data_gas: 0, l2_gas: 1040000 },
>         },
> ```

Why are you `match`ing if it makes no difference? Do you expect the `vm_resources` to depend on the `use_kzg_da` flag?



_Code quote:_
```XML
        GasVectorComputationMode::All => match use_kzg_da {
            true => GasVector { l1_gas: 0, l1_data_gas: 0, l2_gas: 1040000 },
            false => GasVector { l1_gas: 0, l1_data_gas: 0, l2_gas: 1040000 },
        },
```


<!-- Sent from Reviewable.io -->

2024-09-29 14:00 UTC, aner-starkware commented
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7ZdV_vEUlBHo21E0Oi:-O7x3RNOAHt8pVfJ183-:b-x8lxqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf2c186b15f1a7ba38b2c4fb4179209358b2dea1/crates/blockifier/src/fee/gas_usage_test.rs#L292)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

does it make sense that your fixes didn't break this test? @aner-starkware
maybe I should add cases which are affected by rounding up / down?
</blockquote></details>

It's very suspicious.


<!-- Sent from Reviewable.io -->

2024-09-29 14:02 UTC, aner-starkware commented
*[`crates/blockifier/src/test_utils.rs` line 392 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7y4bLVDVg3IY3b6zAN:-O7y4bLVDVg3IY3b6zAO:b-6po3jh) ([raw file](https://github.com/starkware-libs/sequencer/blob/55d25000853b2be9aeb56509773375b95150acde/crates/blockifier/src/test_utils.rs#L392)):*
> ```XML
>             (BuiltinName::bitwise, 1),
>             (BuiltinName::poseidon, 1),
>         ]),
> ```

Where are the magic numbers from?



_Code quote:_
```XML
        n_steps: 10000,
        n_memory_holes: 0,
        builtin_instance_counter: HashMap::from([
            (BuiltinName::pedersen, 10),
            (BuiltinName::range_check, 24),
            (BuiltinName::ecdsa, 1),
            (BuiltinName::bitwise, 1),
            (BuiltinName::poseidon, 1),
        ]),
```


<!-- Sent from Reviewable.io -->

2024-09-29 14:12 UTC, aner-starkware reviewed
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 364 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7y5qDdBKepYeIw2n76:-O7y5qDeAyKxB8bMt48D:b-a165jo) ([raw file](https://github.com/starkware-libs/sequencer/blob/55d25000853b2be9aeb56509773375b95150acde/crates/blockifier/src/fee/gas_usage_test.rs#L364)):*
> ```XML
>             false => GasVector { l1_gas: 62834, l1_data_gas: 0, l2_gas: 1127040 },
>         },
>     };
> ```

Not sure which option is better, but the expected `l1_data_gas` depends only on the `use_kzg_da`, the expected `l2_gas` depends only on the `gas_vector_computation_mode` and the expected `l1_gas` can be written as a conditional summation of `21543 {+ 27} {+ 41291}`.



_Code quote:_
```XML
    let expected_gas_vector = match gas_vector_computation_mode {
        GasVectorComputationMode::NoL2Gas => match use_kzg_da {
            true => GasVector { l1_gas: 21570, l1_data_gas: 2720, l2_gas: 0 },
            false => GasVector { l1_gas: 62861, l1_data_gas: 0, l2_gas: 0 },
        },
        GasVectorComputationMode::All => match use_kzg_da {
            true => GasVector { l1_gas: 21543, l1_data_gas: 2720, l2_gas: 1127040 },
            false => GasVector { l1_gas: 62834, l1_data_gas: 0, l2_gas: 1127040 },
        },
    };
```


<!-- Sent from Reviewable.io -->

2024-09-29 14:13 UTC, aner-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @amosStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7y7D4BEgYNGf8N7br0:-O7y7D4BEgYNGf8N7br1:b-v7j3ui) (no related file):*
Blocked until reviewed by @dorimedini-starkware.

___


<!-- Sent from Reviewable.io -->

2024-09-30 08:01 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @aner-starkware, @yoni, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 392 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7y4bLVDVg3IY3b6zAN:-O80pG4JBj0mSvOwK8Kd:bjy8vai) ([raw file](https://github.com/starkware-libs/sequencer/blob/55d25000853b2be9aeb56509773375b95150acde/crates/blockifier/src/test_utils.rs#L392)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Where are the magic numbers from?
</blockquote></details>

I chose values at random (this is true for all the values in the test) - I used as much values as possible, to increase the chance the test will break on any change to gas computation.
@Yoni-Starkware WYT of the current values?
do you want me to add more cases?
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7ZdV_vEUlBHo21E0Oi:-O80w_yV3gdlhppRgbpm:b-vhjzvs) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf2c186b15f1a7ba38b2c4fb4179209358b2dea1/crates/blockifier/src/fee/gas_usage_test.rs#L292)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It's very suspicious.
</blockquote></details>

@Yoni-Starkware WYT?
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 338 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7y3Rf9-YULlzdbLwR8:-O80nAyF3fZ6U3IRkRMn:b2penpb) ([raw file](https://github.com/starkware-libs/sequencer/blob/55d25000853b2be9aeb56509773375b95150acde/crates/blockifier/src/fee/gas_usage_test.rs#L338)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Why are you `match`ing if it makes no difference? Do you expect the `vm_resources` to depend on the `use_kzg_da` flag?
</blockquote></details>

I didn't notice there was no difference, Done
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7y3_jpCPZgkmt46aKP:-O80nEchDqi06fE3Du0i:b2penpb) ([raw file](https://github.com/starkware-libs/sequencer/blob/55d25000853b2be9aeb56509773375b95150acde/crates/blockifier/src/fee/gas_usage_test.rs#L342)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Why are you `match`ing if it makes no difference? Do you expect the `vm_resources` to depend on the `use_kzg_da` flag?
</blockquote></details>

I didn't notice there was no difference, Done


<!-- Sent from Reviewable.io -->

2024-09-30 08:22 UTC, aner-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O80vzJD4GBdJJtIlCat:-O80vzJE7-GiPNvKU-4O:b-twhzpy) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf2c186b15f1a7ba38b2c4fb4179209358b2dea1/crates/blockifier/src/fee/gas_usage_test.rs#L33)):*
> ```XML
> use crate::versioned_constants::{ResourceCost, StarknetVersion, VersionedConstants};
> 
> pub fn create_event_for_testing(keys_size: usize, data_size: usize) -> OrderedEvent {
> ```

Docstring.



_Code quote:_
```XML
pub fn create_event_for_testing(keys_size: usize, data_size: usize) -> OrderedEvent
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O80xl1t0lfTJgvnTKGa:-O80xl1t0lfTJgvnTKGb:b-twhzpy) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L50)):*
> ```XML
> 
> #[fixture]
> fn starknet_resources() -> StarknetResources {
> ```

Docstring.



_Code quote:_
```XML
fn starknet_resources() -> StarknetResources
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O80y2bR52KAznye9OF_:-O80y2bR52KAznye9OFa:bk6jb0z) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L76)):*
> ```XML
>         n_modified_contracts: 17,
>     });
>     StarknetResources::new(2_usize, 3_usize, 4_usize, state_resources, 6.into(), execution_summary)
> ```

I think it'd be clearer if you wrote the argument names as above. Are the specific numbers arbitrary?



_Code quote:_
```XML
2_usize, 3_usize, 4_usize, state_resources, 6.into(), execution_summary
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 329 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O80zZFd7YwZ9ZXn32CK:-O80zZFd7YwZ9ZXn32CL:b9qsqmh) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L329)):*
> ```XML
>             false => GasVector { l1_gas: 62834, l1_data_gas: 0, l2_gas: 87040 },
>         },
>     };
> ```

Here and below, it might be clearer if `expected_l1_data_gas` depends only on `use_kzg_da`, `expected_l2_gas` depends only on `gas_vector_computation_mode`, and `expected_l1_gas` would be a conditional summation.



_Code quote:_
```XML
    let expected_starknet_resources_gas_vector = match gas_vector_computation_mode {
        GasVectorComputationMode::NoL2Gas => match use_kzg_da {
            true => GasVector { l1_gas: 21544, l1_data_gas: 2720, l2_gas: 0 },
            false => GasVector::from_l1_gas(62835),
        },
        GasVectorComputationMode::All => match use_kzg_da {
            true => GasVector { l1_gas: 21543, l1_data_gas: 2720, l2_gas: 87040 },
            false => GasVector { l1_gas: 62834, l1_data_gas: 0, l2_gas: 87040 },
        },
    };
```


<!-- Sent from Reviewable.io -->

2024-09-30 08:48 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 392 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7y4bLVDVg3IY3b6zAN:-O816SXU1y_cGprvw9mh:b4skrwv) ([raw file](https://github.com/starkware-libs/sequencer/blob/55d25000853b2be9aeb56509773375b95150acde/crates/blockifier/src/test_utils.rs#L392)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I chose values at random (this is true for all the values in the test) - I used as much values as possible, to increase the chance the test will break on any change to gas computation.
@Yoni-Starkware WYT of the current values?
do you want me to add more cases?
</blockquote></details>

It's good enough
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7ZdV_vEUlBHo21E0Oi:-O815kz94E9QmAay1Ng6:b-y98me9) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf2c186b15f1a7ba38b2c4fb4179209358b2dea1/crates/blockifier/src/fee/gas_usage_test.rs#L292)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@Yoni-Starkware WYT?
</blockquote></details>

Yes, try to find numbers for such case
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O815TgY-4wCVY_Xb54O:-O815TgY-4wCVY_Xb54P:bmjqlhe) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L338)):*
> ```XML
>     // Test VM resources.
>     let vm_resources = get_vm_resource_usage();
>     let actual_vm_resources_gas_vector = get_vm_resources_cost(
> ```

Use `ComputationResources` instead



_Code quote:_
```XML
let actual_vm_resources_gas_vector = get_vm_resources_cost(
```


<!-- Sent from Reviewable.io -->

2024-10-07 11:39 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7y7D4BEgYNGf8N7br0:-O8alkHc-wPMUlxTFe7e:bvvg2yk) (no related file):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Blocked until reviewed by @dorimedini-starkware.
</blockquote></details>

reviewed

___
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 328 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8al1cgBUJ7KPtB9NOV:-O8al1cgBUJ7KPtB9NOW:bf0a5lp) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L328)):*
> ```XML
>             true => GasVector { l1_gas: 21543, l1_data_gas: 2720, l2_gas: 87040 },
>             false => GasVector { l1_gas: 62834, l1_data_gas: 0, l2_gas: 87040 },
>         },
> ```

does it make sense that one unit of L1 gas is 87040 units of L2 gas?
I would expect the computed gas vector - for L2 gas mode - would have significantly less L1 gas cost than the L! gas mode computation



_Code quote:_
```XML
        GasVectorComputationMode::NoL2Gas => match use_kzg_da {
            true => GasVector { l1_gas: 21544, l1_data_gas: 2720, l2_gas: 0 },
            false => GasVector::from_l1_gas(62835),
        },
        GasVectorComputationMode::All => match use_kzg_da {
            true => GasVector { l1_gas: 21543, l1_data_gas: 2720, l2_gas: 87040 },
            false => GasVector { l1_gas: 62834, l1_data_gas: 0, l2_gas: 87040 },
        },
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 346 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8alLGe72jjBCAgyHWk:-O8alLGe72jjBCAgyHWl:b-rxdg8g) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L346)):*
> ```XML
>     let expected_vm_resources_gas_vector = match gas_vector_computation_mode {
>         GasVectorComputationMode::NoL2Gas => GasVector { l1_gas: 26, l1_data_gas: 0, l2_gas: 0 },
>         GasVectorComputationMode::All => GasVector { l1_gas: 0, l1_data_gas: 0, l2_gas: 1040000 },
> ```

or use `..Default::default()`



_Suggestion:_
```XML
        GasVectorComputationMode::NoL2Gas => GasVector::from_l1_gas(26),
        GasVectorComputationMode::All => GasVector::from_l2_gas(1040000),
```


<!-- Sent from Reviewable.io -->

2024-10-07 12:59 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O80vzJD4GBdJJtIlCat:-O815WOVCIa-22R1DcYS:b3xdewm) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf2c186b15f1a7ba38b2c4fb4179209358b2dea1/crates/blockifier/src/fee/gas_usage_test.rs#L33)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Docstring.
</blockquote></details>

I don't think this simple test util warrants a docstring
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7ZdV_vEUlBHo21E0Oi:-O8XYzry70Hckwv5wY5K:b-vrrull) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf2c186b15f1a7ba38b2c4fb4179209358b2dea1/crates/blockifier/src/fee/gas_usage_test.rs#L292)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yes, try to find numbers for such case
</blockquote></details>

I don't see any L2 <-> L1 gas conversions in `StarknetResources` (which, IIUC, had the bug @aner-starkware fixed), so I'm not sure I can test it.
I changed `vm_resource_fee_cost.n_steps` to 30/10000, so that L2 <-> L1 gas conversions result in a fraction (which is turned into an integer).
does this fill the requirement?
or is this bad, because I haven't changed `deprecated_l2_resource_gas_costs` & `archival_data_gas_costs` and this makes the ratio between them wrong?
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O80xl1t0lfTJgvnTKGa:-O817wTmAfp6YNlX6Yv_:b3xdewm) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L50)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Docstring.
</blockquote></details>

I don't think this simple test util warrants a docstring
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O80y2bR52KAznye9OF_:-O81BePKB1BYEEHjG0mi:bsefvv0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L76)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I think it'd be clearer if you wrote the argument names as above. Are the specific numbers arbitrary?
</blockquote></details>

they are arbitrary. `StarknetResources::new` includes some logic, IMO it's better to use it
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 328 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8al1cgBUJ7KPtB9NOV:-O8b-EP80C1a-HZsRi-F:b-5z85nw) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L328)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does it make sense that one unit of L1 gas is 87040 units of L2 gas?
I would expect the computed gas vector - for L2 gas mode - would have significantly less L1 gas cost than the L! gas mode computation
</blockquote></details>

@Yoni-Starkware ?
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O815TgY-4wCVY_Xb54O:-O8azx8J0ru6mmtWkz54:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L338)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use `ComputationResources` instead
</blockquote></details>

Done
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 346 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8alLGe72jjBCAgyHWk:-O8b-843BrDFzwfJGhbK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L346)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

or use `..Default::default()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-07 13:01 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 197 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8b3LlL8BGxagNkNJCP:-O8b3LlL8BGxagNkNJCQ:bmg75we) ([raw file](https://github.com/starkware-libs/sequencer/blob/88582b8845ae6e13a64b30fd98d5744c7300836a/crates/blockifier/src/versioned_constants.rs#L197)):*
> ```XML
> 
>     // Fee related.
>     pub vm_resource_fee_cost: Arc<VmResourceCosts>,
> ```

@noaov1 is it ok I made this public?



_Code quote:_
```XML
pub vm_resource_fee_cost: Arc<VmResourceCosts>,
```


<!-- Sent from Reviewable.io -->

2024-10-07 13:46 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 197 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8b3LlL8BGxagNkNJCP:-O8bDeUs4d8pxP1_vHZg:bgynln3) ([raw file](https://github.com/starkware-libs/sequencer/blob/88582b8845ae6e13a64b30fd98d5744c7300836a/crates/blockifier/src/versioned_constants.rs#L197)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@noaov1 is it ok I made this public?
</blockquote></details>

if you can make do with `pub(crate)` for now it will be easier to approve
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 325 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8bD9GV5q1IT6n0LfP8:-O8bD9GV5q1IT6n0LfP9:b-hr53nh) ([raw file](https://github.com/starkware-libs/sequencer/blob/88582b8845ae6e13a64b30fd98d5744c7300836a/crates/blockifier/src/fee/gas_usage_test.rs#L325)):*
> ```XML
>     let mut versioned_constants = VersionedConstants::get(StarknetVersion::V0_13_2_1).clone();
> 
>     // Change the VM resource fee cost so that the L2 / L1 gas ratio is a fraction.
> ```

why?
we would want this test to also catch changes in the *actual* L1<>L2 ratio on 0.13.2.1, no?



_Code quote:_
```XML
Change the VM resource fee cost so that the L2 / L1 gas ratio is a fraction.
```


<!-- Sent from Reviewable.io -->

2024-10-07 14:31 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/receipt_test.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7i1Tka6N0FGY75EO7p:-O8bO0pJ9WFZamKJrlWr:bs155fw) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf2c186b15f1a7ba38b2c4fb4179209358b2dea1/crates/blockifier/src/fee/receipt_test.rs#L316)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

should this TODO be deleted?
</blockquote></details>

yes, you covered it


<!-- Sent from Reviewable.io -->

2024-10-07 16:01 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @dorimedini-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 328 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8al1cgBUJ7KPtB9NOV:-O8bhEu0E4wjDXCIp_JY:b-adsytk) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L328)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@Yoni-Starkware ?
</blockquote></details>

1 L1 gas == 40,000 L2 gas. 
Seems like a rounding issue, but I would expect to see 2 units of L1 gas. @amosStarkware please try to debug this


<!-- Sent from Reviewable.io -->

2024-10-07 16:03 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @dorimedini-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O7ZdV_vEUlBHo21E0Oi:-O8bhuF49n_uGuUGRIH5:b-dpunti) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf2c186b15f1a7ba38b2c4fb4179209358b2dea1/crates/blockifier/src/fee/gas_usage_test.rs#L292)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I don't see any L2 <-> L1 gas conversions in `StarknetResources` (which, IIUC, had the bug @aner-starkware fixed), so I'm not sure I can test it.
I changed `vm_resource_fee_cost.n_steps` to 30/10000, so that L2 <-> L1 gas conversions result in a fraction (which is turned into an integer).
does this fill the requirement?
or is this bad, because I haven't changed `deprecated_l2_resource_gas_costs` & `archival_data_gas_costs` and this makes the ratio between them wrong?
</blockquote></details>

The purpose of `deprecated_l2_resource_gas_costs` is to be consistent when replying to old blocks.
No constraints on future blocks and VC


<!-- Sent from Reviewable.io -->

2024-10-08 12:30 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 7 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 197 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8b3LlL8BGxagNkNJCP:-O8g5raY6wrHkAx4bY2I:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/88582b8845ae6e13a64b30fd98d5744c7300836a/crates/blockifier/src/versioned_constants.rs#L197)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you can make do with `pub(crate)` for now it will be easier to approve
</blockquote></details>

Done
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 328 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8al1cgBUJ7KPtB9NOV:-O8g4zS4D_U-uGaDspmt:bqftove) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L328)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

1 L1 gas == 40,000 L2 gas. 
Seems like a rounding issue, but I would expect to see 2 units of L1 gas. @amosStarkware please try to debug this
</blockquote></details>

Talked in slack, looks like there is no bug, and that this is because of rounding down.
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 325 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8bD9GV5q1IT6n0LfP8:-O8f_l9-Cekxp_jJvTjE:bf8j92n) ([raw file](https://github.com/starkware-libs/sequencer/blob/88582b8845ae6e13a64b30fd98d5744c7300836a/crates/blockifier/src/fee/gas_usage_test.rs#L325)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why?
we would want this test to also catch changes in the *actual* L1<>L2 ratio on 0.13.2.1, no?
</blockquote></details>

`0.13.2.1` is arbitrary - the purpose of this test is to catch any changes to gas computation


<!-- Sent from Reviewable.io -->

2024-10-08 12:49 UTC, dorimedini-starkware approved these changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O80xl1t0lfTJgvnTKGa:-O8g9eLND-JeUAb_CjiZ:b-628d79) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L50)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I don't think this simple test util warrants a docstring
</blockquote></details>

I think you can add a short description of the resources - "a little bit of every resource"?
or, rename the fixture to something more indicative
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 325 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8bD9GV5q1IT6n0LfP8:-O8g9wYM0dkZ99n2YieL:b-l60end) ([raw file](https://github.com/starkware-libs/sequencer/blob/88582b8845ae6e13a64b30fd98d5744c7300836a/crates/blockifier/src/fee/gas_usage_test.rs#L325)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

`0.13.2.1` is arbitrary - the purpose of this test is to catch any changes to gas computation
</blockquote></details>

isn't it possible that gas consumption will change when using 0.13.1 constants, and not with 0.13.2.1?
will this test be hard to parametrize for all released versions?


<!-- Sent from Reviewable.io -->

2024-10-08 13:19 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O80xl1t0lfTJgvnTKGa:-O8gGgpoD0_qam8J27Vs:b32wtd) ([raw file](https://github.com/starkware-libs/sequencer/blob/a574c2cf4fa4872083cfc8d02967809678d8ca86/crates/blockifier/src/fee/gas_usage_test.rs#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think you can add a short description of the resources - "a little bit of every resource"?
or, rename the fixture to something more indicative
</blockquote></details>

ok
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 325 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/968#-O8bD9GV5q1IT6n0LfP8:-O8gG0g4E-y0pu93AmvI:bybwmap) ([raw file](https://github.com/starkware-libs/sequencer/blob/88582b8845ae6e13a64b30fd98d5744c7300836a/crates/blockifier/src/fee/gas_usage_test.rs#L325)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't it possible that gas consumption will change when using 0.13.1 constants, and not with 0.13.2.1?
will this test be hard to parametrize for all released versions?
</blockquote></details>

hmm it is possible.
it will take some work, added a TODO


<!-- Sent from Reviewable.io -->

2024-10-08 13:22 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @aner-starkware)



<!-- Sent from Reviewable.io -->

2024-10-08 13:32 UTC, aner-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-10-08 13:32 UTC, aner-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-10-08 13:33 UTC, aner-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-10-08 13:34 UTC, aner-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-10-08 13:36 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968#-:-O8gLC9F6gD5XPzi3Qpa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-10-08 13:41 UTC, aner-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968#-:-O8gM7G409ipotDynzxE:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-10-08 13:41 UTC, aner-starkware reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968#-:-O8gMCz95rU1IuZDW6jS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-10-08 13:42 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/968)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-10-08 13:56 UTC, merged