test(mempool): add account nonces check in get_txs api test
starkware-libs/sequencer pull request #987
Opened 2024-09-24 11:56 UTC by ayeletstarkware

2024-09-24 13:16 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/987)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 366 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O7Z9PqzD19FRAoKeQHN:-O7ZA7QF1AV8VjkC9OTY:b-rtplb0) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf9a18f4aaf032463afd1c20ac9e672bb682677/crates/mempool/src/mempool_test.rs#L366)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Use:
`use starknet_api::nonce;`
</blockquote></details>

(it is new that the macro moved there).


<!-- Sent from Reviewable.io -->

2024-09-24 13:41 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/987)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 366 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O7Z9PqzD19FRAoKeQHN:-O7ZFFuJDsITf1iYC3-S:bwbgkss) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf9a18f4aaf032463afd1c20ac9e672bb682677/crates/mempool/src/mempool_test.rs#L366)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

(it is new that the macro moved there).
</blockquote></details>

Cool! 
@elintul should I change all usagas in mempool_tests?
___
*[`crates/mempool/src/mempool_test.rs` line 383 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O7Z9eZ9CDyFT9ZALxdH:-O7ZFiN56ffegNORFxwq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf9a18f4aaf032463afd1c20ac9e672bb682677/crates/mempool/src/mempool_test.rs#L383)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Use:
`use starknet_api::nonce;`
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 392 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O7Z9kHbCkjpD8_vCx7B:-O7ZForVBZEot0LP3cAw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf9a18f4aaf032463afd1c20ac9e672bb682677/crates/mempool/src/mempool_test.rs#L392)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Order.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-24 13:46 UTC, ArniStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/987#-:-O7ZH4-L4CZp4vwWvsq3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 366 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O7Z9PqzD19FRAoKeQHN:-O7ZGotu2XzlWN6dwLT5:bie7b98) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf9a18f4aaf032463afd1c20ac9e672bb682677/crates/mempool/src/mempool_test.rs#L366)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Cool! 
@elintul should I change all usagas in mempool_tests?
</blockquote></details>

Partially ahead of you: PTAL: #866


<!-- Sent from Reviewable.io -->

2024-09-24 18:33 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/987)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O7_IdSS00tXE1p3UPoV:-O7_IdSS00tXE1p3UPoW:b-ls3ieb) (no related file):*
Same comments from the other PR; please apply them here.

___
___
*[`crates/mempool/src/mempool_test.rs` line 366 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O7Z9PqzD19FRAoKeQHN:-O7_IY4mEUCbI9iTtegM:b-qlf6r7) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf9a18f4aaf032463afd1c20ac9e672bb682677/crates/mempool/src/mempool_test.rs#L366)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Partially ahead of you: PTAL: #866
</blockquote></details>

We shouldn't have many usages, we usually use our macro with a literal. Go ahead though, yes; as simple as possible.


<!-- Sent from Reviewable.io -->

2024-09-25 06:53 UTC, ArniStarkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/987)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)



<!-- Sent from Reviewable.io -->

2024-09-30 12:45 UTC, elintul requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/987)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O81xk8nCS35TAHs5aB3:-O81xk8nCS35TAHs5aB4:b-id1hgv) (no related file):*
What test is this replacing?

___
___
*[`crates/mempool/src/mempool_test.rs` line 296 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O81sLuW-z875CuoVXfu:-O81xKSm1pnInplb3sTP:b1cnf63) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea099115fda7e392d8c7515bdf742769ae4550e5/crates/mempool/src/mempool_test.rs#L296)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

This might be a better test to check the account nonces removal after `get_txs` removes the last transaction for this account, because it also checks the pool removal. We can also include this in the name of the test.
</blockquote></details>

I think it's too specific; the jist here is a vanilla flow that checks deletion.


<!-- Sent from Reviewable.io -->

2024-09-30 13:32 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/987)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O81xk8nCS35TAHs5aB3:-O81zaKe08LiyAGlozaB:bx86iyv) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What test is this replacing?
</blockquote></details>

the test of account nonces removal in get_txs was never merged because we had already decided it should be included in the API tests.

___
___
*[`crates/mempool/src/mempool_test.rs` line 296 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O81sLuW-z875CuoVXfu:-O826vBp-jXox65dx36K:b9n5z2p) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea099115fda7e392d8c7515bdf742769ae4550e5/crates/mempool/src/mempool_test.rs#L296)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it's too specific; the jist here is a vanilla flow that checks deletion.
</blockquote></details>

Okay, so no need to change the test name. 
But do you think this is a good place to test the account nonces?


<!-- Sent from Reviewable.io -->

2024-09-30 13:35 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/987)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O81xk8nCS35TAHs5aB3:-O828CCxBOIpN8j95uiI:b-837i48) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

the test of account nonces removal in get_txs was never merged because we had already decided it should be included in the API tests.
</blockquote></details>

Okay!

___
___
*[`crates/mempool/src/mempool_test.rs` line 296 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O81sLuW-z875CuoVXfu:-O82870mDTrCuMyAn4OB:b-ltx8ve) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea099115fda7e392d8c7515bdf742769ae4550e5/crates/mempool/src/mempool_test.rs#L296)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Okay, so no need to change the test name. 
But do you think this is a good place to test the account nonces?
</blockquote></details>

Is there maybe a test with multi-account?


<!-- Sent from Reviewable.io -->

2024-10-01 07:50 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/987)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 296 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/987#-O81sLuW-z875CuoVXfu:-O86141K8JevECX6yfIm:b-74pzvf) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea099115fda7e392d8c7515bdf742769ae4550e5/crates/mempool/src/mempool_test.rs#L296)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there maybe a test with multi-account?
</blockquote></details>

Yes, we can check it here (`test_get_txs_with_holes`). The behavior we check is removing an account when no transactions are left. Both tests could work well.


<!-- Sent from Reviewable.io -->

2024-10-10 05:53 UTC, closed without merging